### ISSUE TITLE
Bug: "Add Selection To Find Next Match" - Selection not reset when using cursor to select a new word

### ISSUE THREAD

**Issue by echenley** [Microsoft/vscode#55798]
![vscode-selection-bug](https://user-images.githubusercontent.com/6344219/43670096-f4cf7844-974d-11e8-9d2a-28747c01cd92.gif)

- VSCode Version:
  - 1.25.1
  - 1.26.0-insider
- OS Version:
  - Mac OS X 10.13.6

### Steps to Reproduce:

1. Open find dialog
2. Click word and press command-D to highlight full word 
3. Select another word with duplicates (this should collapse the selection)
4. Press command-D once.
5. Expect to highlight only current word, but now two cursors appear.

See .gif for demonstration. This does not happen when using the keyboard to move the cursor.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by rebornix** [comment]
Good catch, thanks!

**Comment by rebornix** [comment]
Played with it a bit and find that it's not related to the find widget. It's about how we handle `ctrl+d`.

If the selection is empty, and we press ctrl+d, we will select current word.

If we already select one word, we will search for the next same word in the document, and then select it, if we press ctrl+d. This behaves the same as we put the cursor in the word (no selection), and press ctrl+d twice.

The query in the find widget reflects what's being searched.

**Comment by misenhower** [comment]
I think there's a little more to it than that. The Ctrl+D behavior becomes "stuck" when it selects the second version, and pressing Ctrl+D again does not select the next instance of the word as you'd otherwise expect:

![2018-09-07_12-05-09](https://user-images.githubusercontent.com/1619746/45238352-6d191900-b296-11e8-9f06-b184c6c283b8.gif)

Alternatively, if this is working as designed, do you have any suggestions for how to restore the behavior from previous versions (1.24 and earlier)? Here's an example:

![2018-09-07_12-07-42](https://user-images.githubusercontent.com/1619746/45238434-a6518900-b296-11e8-92a6-ae73124746ae.gif)

**Comment by rebornix** [comment]
@misenhower thanks, the gif you showed above is definitely a bug, we need to fix that.

**Comment by misenhower** [comment]
@rebornix I think this issue was closed by accident. There was an additional bug I noticed in my last screen recording but the original issue still exists.
