### ISSUE TITLE
Explorer should have a horizontal scroll

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5580]
- VSCode Version: 1.0.1-alpha
- OS Version: Windows 10

When folders/files are deeply nested, such as a java application under many packages (src\main\java\com\google\android\etc..) the only way to see the full file name is to have a large explorer window.

**Comment by bpasero** [comment]
Disagree.

**Comment by AWTrost** [comment]
Um so the answer is 'Disagree' & Close?  This is a pretty big UX issue for me.  Example:

![image](https://cloud.githubusercontent.com/assets/1524591/20649840/107278fe-b496-11e6-8f18-22d3a73a0ecc.png)

Each of those standings files is different, has a different title, etc etc, however there's no way for me to tell what they are without a) hovering over each one or b) expanding the sidebar to the point where i can read them all.  For apps with a deeply nested structure this isn't practical.  

If the answer is 'open your files a different way', i don't think a code editor should be so deeply opinionated that users aren't able to interact with it in a way that is intuitive to them.  Especially if the editor natively provides a common file explorer idiom that in every other editor works in the same way (i.e. it scrolls). 

I switched to VS code as my full time editor from atom because of issues with indentation consistency on Atom, but this is a worse user experience than that is and I'll be changing back shortly.  At the very least give us some more info than 'Disagree'.

**Comment by craigkj** [comment]
@bpasero 

Care to provide any more detail than `disagree` ? 

Perhaps there is a easy workaround for it that some are simply not aware of yet? It's a bit annoying having to have a huge explorer. Easiest workaround I can see is the `Cmd+Shift+E` shortcut for opening/hiding the explorer window, perhaps you know a better way?

**Comment by bpasero** [comment]
I suggest we continue in https://github.com/Microsoft/vscode/issues/15539 that has more votes. Sorry for closing this without further comment, probably had a bad day on Jul 15 2016.

**Comment by craigkj** [comment]
@bpasero aha, thanks.
