### ISSUE TITLE
Should not send requests like setBreakpoints/threads for "start without debugging"

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/vscode#55850]
- VSCode Version: 
```
1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64
```
- OS Version: Microsoft Windows [Version 10.0.17134.167]

### Description
Currently by pressing `Ctrl+F5` to "start without debugging", the only difference I can see is setting `noDebug: "true"` in the launch request. Other requests like `setBreakpoints`, `threads`, etc are being sent to the debugger continuously, so the debugger has to handle these request (even though they are not meaningful in noDebug mode).  
Can VSCode just stop sending these commands? I mean for example after sending `launch` request, it should **NOT** send any other requests (breakpoints/threads related ones) except for `terminate` if necessary.

E.g. I launched a Java program **without debugging**, then I noticed VSCode was sending following requests:
1. initialize
```json
{
    "command": "initialize",
    "arguments": {
        "clientID": "vscode",
        "clientName": "Visual Studio Code",
        "adapterID": "java",
        "pathFormat": "path",
        "linesStartAt1": true,
        "columnsStartAt1": true,
        "supportsVariableType": true,
        "supportsVariablePaging": true,
        "supportsRunInTerminalRequest": true,
        "locale": "en-us"
    },
    "type": "request",
    "seq": 1
}
```

2. launch
```json
{
    "command": "launch",
    "arguments": {
        "type": "java",
        "name": "xxxxxxxxxxx",
        "request": "launch",
        "cwd": "xxxxxxxxxxxxxxxx",
        "console": "internalConsole",
        "stopOnEntry": false,
        "mainClass": "xxxxxxxxxxxxx",
        "args": "",
        ......
        "noDebug": true,      //<----------------
    },
    "type": "request",
    "seq": 2
}
```

3. setBreakpoints
```json
{
    "command": "setBreakpoints",
    "arguments": {
        "source": {
            "name": "xxxxxx",
            "path": "xxxxxx"
        },
        "lines": [
            8
        ],
        "breakpoints": [
            {
                "line": 8
            }
        ],
        "sourceModified": false
    },
    "type": "request",
    "seq": 3
}
```

4. setExceptionBreakpoints
```json
{
    "command": "setExceptionBreakpoints",
    "arguments": {
        "filters": []
    },
    "type": "request",
    "seq": 4
}
```
5. configurationDone
```json
{
    "command": "configurationDone",
    "type": "request",
    "seq": 5
}

```
6. threads
```json
{
    "command": "threads",
    "type": "request",
    "seq": 6
}
```
......

**Comment by isidorn** [comment]
It is a bit ugly to put a bunch of ifs in the `rawDebugSession` that check if the `rawDebugSession` is `noDebug` that no request get sent out.
But if that is what we want to do then I guess that is just life @weinand 
Here are all the requests and it seems like most of them would not send out antyhing if the noDebug flag is true
https://github.com/Microsoft/vscode/blob/a295e8b615fe680718654ead1e09ead3763443a4/src/vs/workbench/parts/debug/common/debug.ts#L111

**Comment by weinand** [comment]
The "ifs" would not be a problem.
The problem is that VS Code does not know whether a debug adapter honours the `noDebug` flag at all or not.
The debug spec says "If noDebug is true the launch request should launch the program without enabling debugging" but there is no way to communicate back to VS Code whether a DA supports this.

**Comment by Eskibear** [comment]
> there is no way to communicate back to VS Code whether a DA supports this.

If necessary, is it possible to add a capability e.g. `Capabilities.supportsNoDebugMode` for this?

> If a DA does not implement noDebug, then VS Code should act "normal" (i.e. support debugging).

For me as a user, what I see is: I explicitly click "start without debugging", but it turns out to run in debugging mode in the end. It's not "normal".


Back to the topic, the `noDebug` flag is indeed a good design, simple and effective. But requests like "setBreakpoints" are just strange in such a noDebug mode. And I think if VS Code stops sending these requests in noDebug mode, it brings benefits without any harm. (Please correct me if anything wrong.) 
* For DAs already supporting noDebug, these requests are useless, and I believe they also have to send back empty successful responses to make VS Code happy.  
* For DAs not supporting noDebug, currently "start without debugging" just behaves the same as "start debugging", to some extent it never works.

**Comment by weinand** [comment]
@Eskibear that "run without debugging" is not available for all debuggers might be unexpected, but it is clearly documented:
https://code.visualstudio.com/docs/editor/debugging#_run-mode

Yes, I agree a `Capabilities.supportsNoDebugMode` would be a good approach, but since we had the `noDebug` property (with the loose semantics) before we started with the `Capabilities`, it is now difficult to introduce an additional capability that late because we will have three states with three semantics: "missing supportsNoDebugMode capability", "supportsNoDebugMode: false", "supportsNoDebugMode: true". Problematic is that "missing supportsNoDebugMode capability" is not the same as "supportsNoDebugMode: false".

BTW, you should be able to avoid that VS Code calls `setBreakpoints` in noDebug mode.
just don't send an `initialized` event from the DA in noDebug mode.

**Comment by actboy168** [comment]
I don't agree with this.
If the DA supports noDebug, it only needs to ignore the request it does not need, which is not difficult.
DA can choose the features supported by Run mode. Instead of vscode to choose. For example, I will support `setExceptionBreakpoints` in Run mode, but will not support `setBreakpoints. So when the debug target raises an exception, DA will still trigger `StoppedEvent` and subsequent processing of vscode.
In any case, this change will only reduce what DA can do without getting anything new.
