### ISSUE TITLE
refactor/rename with mouse bug

### ISSUE THREAD

**Issue by DmitryBryluk** [Microsoft/vscode#55894]
Issue Type: <b>Bug</b>

set cursor to some var, press ctrl-F2, then mouse click on some other char of var, try move cursor by arrows and typing to change var name => other vars, except firstly selected, renamed incorrectly (position broken after mouse click)

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|0.1.2
xml|Dot|2.3.1
csharp|ms-|1.15.2
Go|ms-|0.6.85
vscode-docker|Pet|0.1.0
markdown-preview-enhanced|shd|0.3.5
vscode-proto3|zxh|0.2.1

</details>

**Comment by ramya-rao-a** [comment]
On pressing Ctrl+F2 all the matching words get selected. After this if you use the mouse to click else where, the selection is lost. Therefore what you type will start showing up where ever the cursor is. This is by design.

This is the same in the simplest scenario as well. Select any word, then use mouse to click in the middle of the word, now press backspace. Only the character before the cursor will be deleted, not the whole word
