### ISSUE TITLE
egrep like feature to subset display of lines based on regex  (i.e. hide code lines that don't match)

### ISSUE THREAD

**Issue by keith-morrell-sp** [microsoft/vscode#55919]
The Mac console has a nice feature where any text file viewed can have only lines that match some search criteria displayed, however the feature is limited and doesn't support regex.

What would be great in VSCode would be a regex search feature allowing multiple combinations, e.g. xxx | yyy | zzz and then have an option to *only* show matching lines.

**Comment by rebornix** [comment]
We closed this issue because we don't plan to address it in the foreseeable future. You can find more detailed information about our decision-making process [here](https://aka.ms/vscode-out-of-scope). If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Thanks for your understanding and happy coding!
