### ISSUE TITLE
Panel button hide when window is too narrow

### ISSUE THREAD

**Issue by umairkhawaja** [Microsoft/vscode#55944]
Issue Type: <b>Bug</b>

When I switch the terminal to view it on the right side instead of bottom, the buttons to kill the terminal and other disappear

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.90GB (7.09GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
angular1-code-snippets|ale|0.0.3
code-gnu-global|aus|0.2.2
vscode-eslint|dba|1.4.12
vsc-material-theme|Equ|2.3.0
language-haskell|jus|2.5.0
node-module-intellisense|lei|1.5.0
theme-monokai-pro-vscode|mon|1.1.8
python|ms-|2018.7.1
cpptools|ms-|0.17.7
Go|ms-|0.6.85
sublime-keybindings|ms-|4.0.0
material-icon-theme|PKi|3.5.2
JavaScriptSnippets|xab|1.7.0
html-css-class-completion|Zig|1.17.1

(4 theme extensions excluded)

</details>

**Comment by V-ed** [comment]
If I understood that issue correctly, this doesn't only happens when switching the terminal's view to the right, but rather when there's not enough space for the header row to fit in horizontally :

![2018-08-07_10-35-06](https://user-images.githubusercontent.com/16652915/43782723-f8c91a30-9a2d-11e8-8aea-e9ecd61b746a.gif)

This is easily reproductible when the terminal is in the right side and its panel has low width.

Of course, you can expand the terminal's panel to access the buttons, but it's a legitimate issue on small screens.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/46017
