### ISSUE TITLE
URI error on debug repl open

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#5594]
- VSCode Version: alpha
- OS Version: os x

Steps to Reproduce:

1. open debug console -> notice error

Not sure if we changed some uri validation recenetly but I was not seeing this yesterday. Giving first to @bpasero, also ping @jrieken 

![screen shot 2016-04-21 at 10 18 01](https://cloud.githubusercontent.com/assets/1926584/14702419/8e1eeb32-07aa-11e6-85f2-8aa91bba2201.png)

**Comment by isidorn** [comment]
Ok, I can no longer easily repro this, but let me know if you need more details if I hit it again

**Comment by jrieken** [comment]
That's a parse error from URI which happens if you create it with invalid strings. The rule, as contained in the error, is  _ If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character_ which means you cannot create a uri form `file:////ddd` or `file://ddd`.

To explain what is what check this: https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/uri.ts#L30

**Comment by isidorn** [comment]
Thanks man! This happened when trying to handle a link in repl which turned out to be an incorrect URU
