### ISSUE TITLE
Symbol rename to a Java class, does not rename the file

### ISSUE THREAD

**Issue by vasouv** [Microsoft/vscode#55951]
When selecting Symbol Rename to a Java class name, the physical filename in the Explorer does not change. Must rename the filename separately. Occurrences in the project are changed though.

![symbol_rename](https://user-images.githubusercontent.com/65785/43784301-72c87018-9a6c-11e8-8ddb-1a9349638761.gif)

- VSCode Version: 1.25.1
- OS Version: Win10 Pro

Steps to Reproduce:

1. Select a Java class name
2. Right click > Rename Symbol
3. Filename in explorer is not changed

vscode-boot-dev-pack | Piv | 0.0.4
vscode-concourse | Piv | 0.4.0
vscode-manifest-yaml | Piv | 0.4.0
vscode-spring-boot | Piv | 0.4.0
java | red | 0.29.0
vscode-java-debug | vsc | 0.11.0
vscode-java-pack | vsc | 0.3.0
vscode-java-test | vsc | 0.7.1
vscode-maven | vsc | 0.10.0
vscode-spring-initializr | vsc | 0.3.0

**Comment by V-ed** [comment]
The next release of VSCode (`1.26`) will [allow for a better refactoring experience, which allows extensions to also create, rename and delete files](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_26.md#better-workspace-edit).

This means that (in your case), the java extension will be able to rename the file name once it implements the new API (which I wouldn't be surprised it this was already done).

**Comment by vasouv** [comment]
Ah so it's coming soon. I'm sure RedHat will update their Java extension to handle that asap. Good to know, thanks :)

Shall I close the issue then?

**Comment by V-ed** [comment]
Normally, I would've said to leave this issue open until the feature is actually added, but since your are referring to Java in particular and the support for such feature will be added in the next 48 hours (I'm not sure exactly when they are releasing the update the stable haha), I'd say that you can close this issue and create one in RedHat's extension repo itself fo having the support the new APIs - I searched quickly through their issue and none mentions this (feel free to correct me if I'm wrong and point to the related issue).

I'm sure they'll update this quickly, refactoring classes names when prototyping is very frequent and such a feature might make me switch 100% to VSCode for java projects :D
