### ISSUE TITLE
flutter usuability

### ISSUE THREAD

**Issue by sk8tz** [Microsoft/vscode#56027]
Issue Type: <b>Feature Request</b>

How about make vs code more friendly with flutter and dart

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

**Comment by beastdestroyer** [comment]
@sk8tz I believe VSCode doesn't support Dart code natively, and requires the extension to have support. Due to the extension creating the structure and highlighting, amongst other things, it might be worth filing an issue there (if you can) and provide more details, such as what is highlighted incorrectly etc.

**Comment by ramya-rao-a** [comment]
There are extensions in the marketplace for both [dart](https://marketplace.visualstudio.com/search?term=dart&target=VSCode&category=All%20categories&sortBy=Relevance) and [flutter](https://marketplace.visualstudio.com/search?term=flutter&target=VSCode&category=All%20categories&sortBy=Relevance). Please try one of them.
