### ISSUE TITLE
After installing an extension for the first time, alert the user that they need to reload

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#56028]
For new users, it's not obvious that after installing an extension that you have to reload the app in order for them to work. This is due to the gear icon that appears in the view list and the `uninstall` button in the extension detail view. Once you "understand" how the model works, it's fine. We should guide and inform new users about this model though.

We should trigger an alert after the user installs an extension for the first time and hasn't reloaded after XX number of seconds (10s?). Here's an example (maybe @gregvanl has better ideas on how to work this) :
![image](https://user-images.githubusercontent.com/35271042/43857460-38f93220-9b00-11e8-9293-8e4ac79f6169.png)

**Comment by misolori** [comment]
Yes, this is the case where the user ignores or doesn't see the reload buttons. My suggestion is to only show this notification when the user installs an extension for the first time as a form of guidance. It shouldn't show up after they reload.

**Comment by ramya-rao-a** [comment]
> Yes, this is the case where the user ignores or doesn't see the reload buttons.

I find it hard to believe that the reload buttons are not noticeable, especially as they take the place of the "Install" button that was just clicked :)

@sandy081 I recall we had the notification model for normal installations once upon a time. Can you confirm?

**Comment by sandy081** [comment]
Yes, we used to show the prompt before but removed them as they are noisy and we show the reload button just after the installation is finished. 

I would like to know if there are any complains from the users or is it noticed from any studies?

**Comment by misolori** [comment]
There was a recent study done with new users where they did not understand the "Reload" button. Some thought it meant the extension was installed and enabled, others ignored the buttons. 

This notification would help aid those users in better understanding the "Reload" model for VS Code. My suggestion is to only show it when the user installs an extension for the first time. Once they learn the model it is not necessary to show this notification.

**Comment by sandy081** [comment]
I see. 

I am not a big fan of such prompts. If it helps new users, as you said, we can have the prompt and have do not show again option to not to show them again.

**Comment by misolori** [comment]
If this were to only show up once (after they install their first extension), is there a reason why we’d need a “Don’t show this again?”.

**Comment by sandy081** [comment]
Is not it confusing for users if we show only for first installation? We might need more descriptive message saying this message will not be shown again?

Also, this should not be shown also when users have extensions installed already.

**Comment by misolori** [comment]
I agree that the text should be more descriptive. I think if we word it in a way that implies that this is just a guide and not a typical notification that it will work. 

Something like `Tip: Reload to enable an extension after installing it`. @gregvanl , do you have any thoughts?

**Comment by qubitron** [comment]
Adding my 2c, the confusion is indeed that users think by seeing the "Reload" button that the extension has successfully installed and "Reload" is an action that they can now take (but doesn't provide any reason or call to action that it's required). They don't understand that they need to click the Reload button to finish installing. 

As another idea, instead of popping a banner, can we better communicate the installation status of the extension and that a reload is required on the extension list and/or extensions page? The extensions page has plenty of real estate so we could expand the "Reload" button to say "Reload to finish installation" or "Reload to finish uninstall"? That would communicate the need/purpose of reloading is. 

Another suggestion would be to add "Reload to finish installation" as hint text somewhere on the extensions page or the extensions list.

**Comment by sandy081** [comment]
Actually, Installation is completed but reload is required to run the extension in the window. I like the idea of tooltip.

**Comment by sandy081** [comment]
Extension viewlet has limited space, showing a tooltip makes sense there. We can be verbose in the Extension editor.

**Comment by ramya-rao-a** [comment]
Yes to using verbose text in the editor, no to the toolitp.

@sandy081 Using tooltip to provide essential information which otherwise is not clear that it exists is not a good idea from an accessibility perspective.

We already have the `Update to 1.2.3` button taking a little more space. So replacing `Reload` with `Reload to enable` shouldnt be a problem

![image](https://user-images.githubusercontent.com/16890566/45328923-d311d480-b512-11e8-85a1-10f91596c16d.png)

**Comment by sandy081** [comment]
@ramya-rao-a Ok, if it looks good with verbose labels I am ok to have them.

**Comment by isidorn** [comment]
Verified that the button is more verbose in the extension editor
