### ISSUE TITLE
Settings: Allow to pass flags to external terminal on opening.

### ISSUE THREAD

**Issue by shixzie** [Microsoft/vscode#56038]
It would be nice to be able to pass flags to the external terminal when it opens. This would be used for customization only.

For example, on xfce4 there is a `--drop-down` flag for the `xfce4-terminal` command that indeed opens the terminal as a drop-down. Of course there are more flags and these will vary depending on the terminal used, the flags would be set by the user just like the `terminal.integrated.shellArgs.[windows,linux,osx]` setting so I think it would be a nice addition.

**Comment by Tyriar** [comment]
A bunch of args are already passed when opening the terminal, so it's not as easy as with the integrated terminal where they are the only args passed to it.

Since this is the only time I've heard the request and because of the complexity it would introduce I think this should be deferred to an extension (where it is certainly possible to accomplish).
