### ISSUE TITLE
Explorer should not auto reveal excluded files

### ISSUE THREAD

**Issue by snebjorn** [Microsoft/vscode#56063]
VSCode currently selects the open file in the explorer when `"explorer.autoReveal": true` - this is very handy and a welcome feature.

However when you "Go to Definition" on a type coming from the node_modules folder it'll expand the directory tree all the way down to the file that defines it. This is obviously intended. But it causes the explorer to be flooded with 100s of folders.
A new angular project have almost 1000 packages installed.

So my proposal is to add an additional option that define paths autoReveal should ignore.
Something like: `"explorer.autoReveal.exclude": ["**/node_modules/**"]`

**Comment by isidorn** [comment]
I think I have a better suggestion which would not overcomplicate this, autoReveal should not reveal files which are listed under `"files.exclude"`
This way we do not need to introduce a new obscure setting

**Comment by snebjorn** [comment]
@isidorn the `"files.exclude"` completely removes the files/folders from the explorer making the autoReveal a none issue. As in the explorer can't select the file.

But completely getting rid of the `node_modules` folder isn't always desired. As sometimes I want to browse it.

My point is that 
> autoReveal should not reveal files which are listed under "files.exclude"

is the current behavior but doesn't allow for browsing so it's undesired.

**Comment by isidorn** [comment]
You are correct. But adding another setting would overcomplicate things imho
Let's leave this open and see if there are better suggestions
fyi @bpasero

**Comment by justingrant** [comment]
@isidorn - I agree with @snebjorn that using the existing `files.exclude` setting is not a good solution. The problem is that there are really three kinds of files: 
1. **your code** - you always want these files to be synced with the sidebar
2.  **others' code** - e.g. node_modules folders. You usually don't want to see these 100's of folders cluttering up the sidebar, but sometimes you do, e.g. when digging into library code to track down a bug or to clone some sample code.
3. **not code** - e.g. .git and other folders that you always want to ignore in the sidebar

Because there are three categories, any binary setting is going to be insufficient. The solution proposed by @snebjorn would exactly meet my needs.

I would never, however, add node_modules to the `files.exclude` list because at least a few times per week I do need to browse through those folders in the sidebar. It's not OK to have to change a persistent setting several times per week, and then have to remember to change it back.

FWIW, in terms of minutes saved per week, reducing time wasted by scrolling through node_modules folders would be at the top of the list of features I'd want to see VSCode add. Each scroll through 500+ folders only takes 5-15 seconds (depending on how far I overshoot), but multiply that by 10+ times per day, every day, and the numbers start to add up.

**Comment by flisboac** [comment]
Sorry for bringing this issue into scope again, but I am of the same opinion as the one @justingrant exposed. Are there any plans to implement such a feature?

**Comment by Ed-Ed** [comment]
> You are correct. But adding another setting would overcomplicate things imho
> Let's leave this open and see if there are better suggestions
> fyi @bpasero

I don't see how it would overcomplicate anything since the settings are already complicating. Leaving it out doesn't make things any simpler.

There should be an option below **Explorer: Auto Reveal** like **Explorer: Folders To Exclude In Auto Reveal** which allows us to use regex to exclude particular files or folders.
