### ISSUE TITLE
File paths in Open Recent Menu starts with / and lower case drive letter

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#56104]
- VSCode Version: Insiders 1.26 dated 8/9
- OS Version: Windows 10

Steps to Reproduce:

1. Close all VS Code windows
2. Open VS Code
3. Files => Open Recent

![image](https://user-images.githubusercontent.com/16890566/43921393-7ad69ae0-9bd0-11e8-8d6c-adf629fa78e5.png)

4. Choose one of the recently opened folder
5. Files => Open Recent

All is well 

Doesnt occur in stable 1.25.1

**Comment by sbatten** [comment]
Results of Investigation:
* The native menu is using the uriDisplayService to resolve the URI in the menu
* The first time the menu is created a formatter for the uri has not yet been registered, so the uriDisplayService return just the raw path

* This didn't surface when we were using dynamic menu registration for the native menus because the delay of menu registration was longer than registering formatters

* This should have no side effects and is just a display issue.


fyi @isidorn

**Comment by joaomoreno** [comment]
@kieferrm Shouldn't the milestone be called `July Recovery 2018` instead?

**Comment by kieferrm** [comment]
@joaomoreno yes. @roblourens changed it.
