### ISSUE TITLE
Timeout notification after debugging

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#56165]
Issue Type: <b>Bug</b>

1. clone vscode repo
2. build it
3. `./scripts/code.sh --inspect`
4. Open cloned repo in latest insider
5. Debug instance launched in 3. with "Attach to Extension Host launch config"; wait until attach was successful
6. Quit instance launched in 3.
7. Wait 

-> After 10s you get

![screen shot 2018-08-10 at 11 44 03 am](https://user-images.githubusercontent.com/4674940/43975739-80a5be06-9c93-11e8-92ca-ea24c2efd398.png)

VS Code version: Code - Insiders 1.26.0-insider (207ace21dfec3dccab52f1296a3880ac7644c978, 2018-08-10T06:40:10.035Z)
OS version: Darwin x64 16.7.0

**Comment by weinand** [comment]
That's the expected behaviour because the "Attach to Extension Host" launch config has a `"restart": true". The stable VS Code has the same behaviour.

If "restart" is set to false, the timeout no longer happens.

`"restart": true"` make sense when debugging the EH because the EH is restarted a lot in normal operation and it is convenient if the debugger reattaches. But the consequence is the timeout at the end because in a "attach" debug session VS Code is not controlling the debuggee and does not know whether there will be another restart or not.

**Comment by roblourens** [comment]
I have noticed this too and find it annoying. I deleted 'restart' and someone put it back. So, I use private workspace launch configs 😁
