### ISSUE TITLE
progress running after close

### ISSUE THREAD

**Issue by BO41** [Microsoft/vscode#56203]
- VSCode Version: starting at 1.24, still on 1.25
- OS Version: Linux archlabs 4.17.13-arch1-1-ARCH

Steps to Reproduce:

sometimes, after closing the last window of vsc, a process keeps still running in the background keeping one core at 100%.

Process name: `/opt/visual-studio-code/code /opt/visual-studio-code/resources/app/out/bootstrap --type=extensionHost`

It has 6 sub-processes (maybe because of my 6 core cpu)

Does this issue occur when all extensions are disabled?: probably not, but I can't test it because of its inconsistent appearance

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by BO41** [comment]
@bpasero sure, I can try. :+1: 
But as I already mentioned, not every time this behavior appears.

**Comment by BO41** [comment]
@bpasero I can't give you more info. The behavior occurs to random.
Maybe it got already fixed in `1.26`.

So I'll close this issue. If I or someone else got more info we can reopen this
