### ISSUE TITLE
几个建议 希望vsc做的更好

### ISSUE THREAD

**Issue by iscraft** [Microsoft/vscode#5620]
- VSCode Version:1.0
- OS Version:windows7

1.目前的配对仅仅只对括号有效 无法针对多个html标签进行匹配
`比如<li>1</li><li>2</li>...当鼠标光标位于第一个<li>标签时 会高亮出所有的<li>标签 而不是1后面的这个</li>`
希望在新的版本中高亮显示出与当前光标所在的标签配对的结束标签 

2.并且可以自定义配对高亮效果 比如斜体 下划线 下划虚线 加粗 颜色等 现在只有一个浅灰色的方框

3.windows下安装后 把电脑上的php文件都默认改为vsc打开了 
能不能改掉这种无耻的习惯 而在设置中添加一个功能 让用户自己选择文件扩展名打开方式?!

4.针对中日韩字体能否设置单独的字体显示效果和大小 太多的编辑器的中文字体显示问题一直都令人蛋疼不已

5.能否出portable便携zip解压即用版本 配置文件等在vsc目录下 而不是固定在c盘无法移动 一直不喜欢软件强占c盘空间的情况

**Comment by Tyriar** [comment]
Rough translation using translate tools:

## Multiple recommendations for VSCode

1. When the cursor is on opening tags in HTML the corresponding closing tag should be highlighted
2. Add custom highlight effects such as bold, italics, underline, color, instead of just a grey rectangle
3. Do not associate file type in OS with VSCode on installation
4. Allow customizing CJK font size and font family https://github.com/Microsoft/vscode/issues/5260 https://github.com/Microsoft/vscode/issues/3702
5. Portable zip https://github.com/Microsoft/vscode/issues/329

**Comment by dbaeumer** [comment]
(1) @aeschli
(2) @alexandrudima
(3) @joaomoreno. Do we do that?
(4) @bpasero & @alexandrudima
(5) @joaomoreno

**Comment by joaomoreno** [comment]
(3) We let Windows know that Code can open a bunch of extensions. If there is no other editor for them, then Windows automatically chooses Code to be the default application to open them, as far as I know.
(5) #329

**Comment by bpasero** [comment]
(4) fair request, not possible though

**Comment by aeschli** [comment]
(1) already is happening, the corresponding tag is highlighted (with a background color)
![image](https://cloud.githubusercontent.com/assets/6461412/14724645/c921fc0c-0817-11e6-9088-342fe0d5cfdf.png)

**Comment by iscraft** [comment]
@aeschli 
html code in the php file
`Untitled-1.php:
<ul id="nav">
	<li>1</li>
	<li>2</li>
	<li>3</li>
</ul>`

**Comment by Tyriar** [comment]
@iscraft thanks for clarifying, I believe that's covered as part of this https://github.com/Microsoft/vscode/issues/670

**Comment by Tyriar** [comment]
Forked off (2) so we can close this https://github.com/Microsoft/vscode/issues/7687

**Comment by rebornix** [comment]
@Tyriar your translation is precisely correct and thanks for ignoring those dirty words ...
