### ISSUE TITLE
perf - slow caches here and there

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#5621]
This glob perf discussion got me thinking about that caching we do and the conclusion is that they are bad. Take the new caches in [glob](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/glob.ts#L259), similar cases [here](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/glob.ts#L238) and [here](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/strings.ts#L270)

There is two problems, (1) they stop being a cache when their limit is reached and new elements come along, and (2) they are slow because every check for the size iterates over all elements and puts them in an array. For example, the worst case for [`normalizeNFC`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/strings.ts#L270) is to allocate an array with 10000 elements just to figure out that the cache is useless.

Since we have learnt that unbounded arrays aren't a wise choice, we should use a better caching strategy. Use an array and binarySearch or manually keep track of the length

**Comment by bpasero** [comment]
> they are slow because every check for the size iterates over all elements and puts them in an array.

I think that is only true if they are abused in a bad way. My assumption is that the glob pattern cache carries very little number of patterns that are mainly constant and do not change. The check for property names in the cache happens maybe 10-20 times depending on the number of patterns used and then stops calling because the cache is bypassed.

> For example, the worst case for normalizeNFC is to allocate an array with 10000 elements just to figure out that the cache is useless.

please explain that in more detail, I do not see the allocation of an array with 10000 elements

> Use an array and binarySearch or manually keep track of the length

Why not benefit from the fact that the cache can be hashed with a key that is suitable? using an array with search seems like a bad choice unless my key is not good for using a map.

**Comment by jrieken** [comment]
> please explain that in more detail, I do not see the allocation of an array with 10000 elements

sorry, wrong link. [this](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/glob.ts#L238) will become an array with 1000 elements. 

> Also, how does this help for the case of the bounding condition being hit?

It does not help. If cache you should respect recency of your items. Also, I doubt if your caches for glob buy you anything. You replaced a simple regular expression with a iterating over object members, array creation, and map lookup. If you think using a regex ala `^**/*.\w$` is a perf problem just use string math.

**Comment by jrieken** [comment]
perf test says it doesn't really matter. sometimes caches win, sometimes no caches win. The trivia regexes should be unrolled into string math

**Comment by bpasero** [comment]
Let me try to recap:

* we use a cache to avoid calling NFC normalize on a path but this cache can grow quickly and then it is useless for other paths. this cache uses a counter at least so that there is no lookup cost. a better cache here would be to remove the oldest paths and store the newest (MRU). given our eager ASCII check I am also easy to ditch this cache altogether.

* we use a cache to store the RegExp from a string glob pattern. this cache is currently unbounded. we use a similar cache here (https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/filters.ts#L301). the idea is to avoid having to create this RegExp all the time. I would not want to remove this cache. Also, the expensive getOwnPropertyNames() to check for the size of the cache is only called if the pattern was not cached yet (https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/glob.ts#L238)

* we use a new cache for detecting if a glob pattern is trivial or not. to test this we are running 3 different patterns over the glob pattern. each glob pattern is used many thousand times in many different places so this means an additional 3 regexp.matches() call for each thing that gets glob-matched. so we cache the fact if a glob pattern is trivial or not because why would we want to compute this info over and over again if the glob patterns are unlikely to change. I can also not see where this cache is slow or computational intense because iterating over its property names only happens if the pattern was not yet cached (see https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/glob.ts#L254). we could remove these caches though and just store the fact that a pattern is trivial together with its RegExp that we already cache anyways

Thoughts?

**Comment by jrieken** [comment]
> NFC

* We should know whether a cache pays off or not. For me caching feels like a last resort because the actual operation couldn't be made fast. Tho if we cache it should honour some sort of recency and not be full and useless after `n` operations

> filters.ts

* Please stop pointing me to more unbounded caches.

> glob

I understand the intent and want that thing to be fast. Instead of caching we should maybe nuke the trivia regexes and use code, like the pseudo below (no string, nor array allocations!)

```
args.indexOf('**/*.') === 0 && for (i = 5; i < args.len; i++) {
  args.charCodeAt(i) === one_of(A-Za-z_.)
}
```

Then we can reconsider if caching is still needed and iff so we should do a better cache. Given the constraint I'd propose something like this

* start with two empty arrays - one for the keys, one for recency counters
* use binary search (runs as log_n like maps) to find an item in the first array; for a new items the result is the inverse of its [insertion point](https://github.com/Microsoft/vscode/blob/master/src/vs/base/test/common/arrays.test.ts#L46)
* iff new splice the item into the array (unsure of the costs)
* update the second array at the same index with a recency indication (some increasing number, like Date.now without a meaning)
* when the `length` has reached a certain limit, like 80% of max throw out n% of the _oldest_ items.
* (extra) use a third aligned array to keep data (when not used as set but map)

I believe that's better then maps because we don't need `Object.keys` calls, get recency, and finding the insertion point is fast (log_n). Unsure about [splice](https://gamealchemist.wordpress.com/2013/05/01/lets-get-those-javascript-arrays-to-work-fast/)

**Comment by bpasero** [comment]
@jrieken I opened a PR for a `LinkedMap` that allows to `set` and `get` values with the possibility to set a maximum number of elements to keep. Once that limit is hit, the oldest element will be dropped.

I also provide a `LRUCache` that - once you access an entry from the map via `get` - puts the entry to the top of the linked list. This ensures that elements which are LRU are dropped from the map first when the bounding condition is hit.

I am not sure if I would use `LRUCache` for the caches discussed in this bug report though. I think the `LinkedMap` is already fine.

Also wrote tests in `map.test.ts`.

**Comment by bpasero** [comment]
Adopted `LinkedMap` for `glob`, `filters` and `strings`. Currently not exercising the `LRUCache` though because I feel it is not needed for those.
