### ISSUE TITLE
High CPU Usage of Code Helper when using large projects

### ISSUE THREAD

**Issue by richtera** [Microsoft/vscode#56216]
Issue Type: <b>Bug</b>

With larger project which have compiled output files (like gatsby, nextjs and so on) within the project's directory there is a huge performance problem with Code Helper. It uses 100% or more most of the time.
Now adding settings to ignore files and ignore watch files will fix the issue, but it would be much better if there was some kind of .vsignore file processing so ignored files can automatically be set per project rather than having global settings hopefully ignore the right files for all my projects.

VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:33:29.235Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.34GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron public/|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
vscode-eslint|dba|1.4.12
vscode-babel-coloring|dza|0.0.4
tslint|eg2|1.0.34
vsc-material-theme|Equ|2.3.0
prettier-vscode|esb|1.6.1
gc-excelviewer|Gra|2.1.25
vscode-language-babel|mgm|0.0.20
dotenv|mik|1.0.1
python|ms-|2018.7.1
debugger-for-chrome|msj|4.8.2
sass-indented|rob|1.4.9
mdx|sil|0.1.0

</details>

**Comment by bartread** [comment]
I have this on OSX 10.13.6 High Sierra with VSCode 1.25.1, working on a large Node/JavaScript side-project of mine.

The problem isn't so much the performance of the machine - it has CPU to spare: the real issue is that it drains the battery **fast** when I'm on the move, which I often am when I work on this. It'll suck around 70-75% of the battery in 2 hours use of VSCode, which isn't something I can live with (the machine's about 3 years old but will still happily run for 6 hours or so on battery alone). Much as I've come to prefer code, at least when on the move, I'm going to have to switch back to Sublime Text for now because it won't even last a return trip from Ely to Kings Cross at the moment.

This appears to be somewhat related to https://github.com/Microsoft/vscode/issues/55225 and duplicates the already closed https://github.com/Microsoft/vscode/issues/45301.

**Comment by bartread** [comment]
(Also, can somebody with enough privileges please give this bug a better title - it's doing my nut in. Something like "VSCode 1.25.1 Code Helper process constantly using CPU and draining battery" would be much more useful.)

**Comment by sandy081** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by richtera** [comment]
@sandy081 I just saw this was closed. Essentially adding certain folders to be excluded like build folders and node_modules folders will resolve the performance issues, but the problem is that not all my projects have the same project layout. So I was thinking it would be better to allow parts of this or other configuration to be overridden per project. I was thinking a file like .vsignore or a folder with custom settings per project.

**Comment by sandy081** [comment]
@richtera Do you know which extension is reading them and causing the performance issue?

As said, you can follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!
