### ISSUE TITLE
Sash double clicks to even all editor widths

### ISSUE THREAD

**Issue by JVimes** [Microsoft/vscode#5624]
The new "Sash double clicks" feature is awesome, but we need a way to equalize _all_ editor widths by double clicking sashes (currently impossible). I think accordion mode might be more likely than one sash misplaced. There's a palette command we can leverage: even editor widths.

Ideas for how to even all editor widths via sashes:
- Double click a sash, it adjusts. Double click the same sash again, all of them equalize.
- Modifier + double click
- Other ideas? Something people are likely to try when hunting for how to do it.

**Comment by mquandalle** [comment]
Are you aware of any prior art on other editors? I could support the idea of Modifier + double click but I’m against your former suggestion of “double-double clicks” which isn’t a standard user interaction.

**Comment by JVimes** [comment]
No. I'll let the community pick which method we use. I'm not married to any of those bullet points.

**Comment by bpasero** [comment]
@mquandalle happy to review another PR but from my side I am not planning work on this atm, so moving to backlog.

**Comment by mquandalle** [comment]
I’m not planning to work on this either.

**Comment by mquandalle** [comment]
Looking at Sublime Text implementation again, double-clicking on a sash of a split editor doesn’t actually resize the two editors around the sash to half of the available width. Instead it will consider the entire “workbench” width and put the sash as its default position. So if you have a split editors with 3 panes, clicking on the first sash will put it at one third of the available space, and clicking on the second one will put it at two thirds. (Note that the resizing behavior is identical for 2-panes split editors).

I may need to think about this a bit more, but I believe this is a better behavior than the one I implemented because it makes the sash repositioning idempotent—double clicking on the sash will always put it at the same position— instead on depending on the size of the panes around it. And it would also fixes the current issue in a clean way: instead of introducing a new feature that will almost certainly be very hard to discover (pressing <kbd>Ctrl</kbd> + double click isn’t an intuitive interaction) you would basically reposition sashes one by one.

Any thought?

**Comment by JVimes** [comment]
I wonder, would anyone ever want a single sash in its idempotent position and leave the other sashes alone? Or should we reset all sashes when any one is double clicked?

**Comment by JVimes** [comment]
Today I found a use case for the current sash behavior: I want to make one editor bigger, but have the other two even with each other. I resize the first editor, then double-click the remaining sash.

This won't work with >3 editors if we implement that in the future. Trying to think of a UI design for the general case.

**Comment by bpasero** [comment]
This actually works now with the grid feature at least for one dimension, closing.
