### ISSUE TITLE
how do i choose the installation?

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#56260]
I got this interesting message:
```
You are running the system-wide installation of Code - Insiders, while having the user-wide distribution installed as well. Make sure you're running the Code - Insiders version you expect.
```

So how do I make sure I run one or another?

![image](https://user-images.githubusercontent.com/937933/44035069-9a674d1e-9edc-11e8-8297-2f82152be8e8.png)

**Comment by kolchy** [comment]
I got the same message, and struggling to understand what I actually need to do.

**Comment by hasanslayer** [comment]
I got the same message, what actually should I do ?

**Comment by andy0566** [comment]
I got the same message too

**Comment by Rarxa** [comment]
https://code.visualstudio.com/updates/v1_26#_user-setup-for-windows

**Comment by strongui** [comment]
How exactly to we switch and do away with this error? This is not specified.

**Comment by Devan35** [comment]
same here !

**Comment by jashobantac** [comment]
Same here..

**Comment by jashobantac** [comment]
As the update says it now allows user wide installation that does not need administrator access, I saw two entries in my path created  : 
1) In my user variables (the newly added path)
C:\Users\[user-account-name]\AppData\Local\Programs\Microsoft VS Code\bin
and one in the System Variables : 
C:\Program Files\Microsoft VS Code\bin
Both of which has a batch file triggering the exe. So, the error is pretty much clear. We need to decide whether we need to use the system wide or the user wide..
Based on our preferences, deleting either one of them removes the error.
PS : I removed the user-wide one and continued using the system-wide installation.

**Comment by Devan35** [comment]
I removed the C:\users path, same warning message, removed the /programs/ path, same thing, what am I missing?

**Comment by jashobantac** [comment]
Did you try restarting the machine? The changes don't appear until you restart the machine.

**Comment by Devan35** [comment]
@jashobantac ok will try again, this time restarting my machine. thanks

**Comment by Devan35** [comment]
@jashobantac I just removed the users/ path, restarted my machine, same thing. only thing I can do is to select the option to not display the message anymore.

**Comment by scienmind** [comment]
The message is also constantly pops up if having User Level install + Portable install (which is also user level).

The message content and/or it's display conditions definitely should be improved.

**Comment by alexfung888** [comment]
control panel says two VSCode are installed. One has a suffix (User). I think I was supposed to uninstall one of them. Now that I talk about it, it seems VSCode suggested me to uninstall before installing. However, I don' know which one to uninstall now.

**Comment by treio** [comment]
I had the same problem. This work for me: https://stackoverflow.com/a/51860943/6038295

**Comment by strongui** [comment]
Ok here's the definitive guide on how to fix it.

For windows 10 anyway.

1. Uninstall VS Code and VS Code User. 
2. Reboot
3. Install VS Code User edition (just re-download it from the vs code page)
4. Profit.

Error will be gone, and all your settings/plugins won't be removed, since they are not removed if uninstall the programs. You'd have to manually delete the settings folder, so just don't worry about it.

**Comment by ripplejb** [comment]
The message is not an error message, I think the icon should be changed here. This is just an information and not warning.

Now on you can have multiple copies of vs code on your system.

1. Systemwide vs code that is installed in the "C:\Program Files". This is a shared copy of the vs code that can be accessed by all the users on the system.

2. User installation is installed somewhere in "C:\users\<username>\...". This is a personal copy of the vs code for the user only.

Both copies are visible in the control panel if they are installed. You can uninstall one of them or keep both, your choice.

**Comment by joaomoreno** [comment]
Hi guys. First off, apologies for the ambiguous message. My bad. The intention with this message is to alert to you that you might not be running the version you intended... while most of the time you actually are OK. It's not an error.

The best to do here, if possible, is to uninstall the global installation. All will be good then.

Otherwise, if you want to keep both installations on, simply click the ⚙ gear icon and then `Don't Show Again` not to be disturbed again.

---

As a fix, I've lowered the message severity from Warning to Info, removed that last phrase and made the `Don't Show Again` button more visible.

**Comment by wangyoukai** [comment]
Delete desktop shortcuts, search in cortama and reopen vscode. Then you can solve this problem.

**Comment by tiopere** [comment]
In the link provided (https://code.visualstudio.com/updates/v1_26#_user-setup-for-windows)  is the explanation of this decision:

**User setup for Windows**
Announced last release, the user setup package for Windows is now available on stable. This setup does not require Administrator privileges to install. It also provides a smoother background update experience.

**Download User Setup**
If you are a current user of the system-wide Windows setup, you will be prompted to switch to the user setup, which we recommend using from now on. Don't worry, all your settings and extensions will be kept during the transition.

In my understanding, the best way is to unistall the system-wyde and maintain the user version.

**Comment by alexfung888** [comment]
yes it is important to uninstall the system wide setup (if you intend to use the user wide setup). Otherwise, the two versions will run with its own mind. Even if you started up the user wide version, open-recent from the file menu may open the folder/file using system wide version. It is completely confusing, especially because it is not easy to tell which one is running. (I hope what the task manager telling me is correct).

Decide on which one you want to run and get rid of the other asap.

**Comment by wyckster** [comment]
The recommendation when installing this new _user version_ of vscode was to _uninstall the system-wide version_ (since it requires elevation) and just use the user version (which does not require elevation and offers a better update experience).  So (for Windows, anyway) head on over to **Apps and features** (I like to tap the Windows key and type "programs" to get there.)

Just uninstall the system-wide version of Microsoft Visual Studio code.  It's the one that does **not** say (User).  (see picture below)

For me there were no lost settings, no reboot required, and it was not necessary to change my PATH or anything like that.  Clicking the Uninstall button fixed everything.

![image](https://user-images.githubusercontent.com/6098274/44503429-4935c080-a664-11e8-8bea-8e5d9c3b2b41.png)

**Comment by stanvarlamov** [comment]
"Make sure you're running the Code version you expect" is totally void, if not misleading. Why don't just say "uninstall one of the versions" or put a link to the explanation that someone put together when releasing this feature (as pointed out above)? Unless MS is promoting Google search that leads to this GitHub issue ...

**Comment by mnicic** [comment]
I solved this just by uninstalling _system-wide_ version.

**Comment by sciobotaru** [comment]
Solved the issue by removing VS Code and keeping VS Code (User):
![vs1](https://user-images.githubusercontent.com/19649056/44773660-ccca4280-ab79-11e8-8e33-ea9278c256f6.png)
