### ISSUE TITLE
JavaScript: "Add all missing imports" without generating type-checking errors

### ISSUE THREAD

**Issue by axefrog** [Microsoft/vscode#56283]
I don't enable type-checking in my JavaScript because TypeScript has a tendency to show me "errors" in my JavaScript code that don't actually exist. For example:

![image](https://user-images.githubusercontent.com/298883/44065157-6ebca35a-9fac-11e8-8913-c64193be4de2.png)

The code works exactly as intended, but to get the **"Add all missing imports"** quick fix, I have to enable semantic checking. The quick fix is then enabled and seems to work well, but at the cost of TypeScript now trying to get involved in my code with all kinds of false negatives across my codebase.

![image](https://user-images.githubusercontent.com/298883/44065222-c9da3c98-9fac-11e8-83c1-b344377633bf.png)

Could we make it possible to enable this quick fix without having TypeScript also try to analyse problems in my code?

**Comment by mjbvz** [comment]
Unfortunately we cannot distinguish the case where you write `DETACH` and forgot to add an import (which should be an error) from the case where you write `DETACH` which is actually a reference to some global that our intellisense can't understand. That's why the type checking + quick fixes is all-or-nothing. You can enable type checking but them suppress it on individual lines however using `// @ts-ignore`
