### ISSUE TITLE
Don't show breadcrumb bar when not applicable

### ISSUE THREAD

**Issue by toine-h** [microsoft/vscode#56327]
**Issue type:** polish/feature-request

Steps to reproduce

1. Set breadcrumbs setting to the following:
```
  "breadcrumbs.enabled": true,  
  "breadcrumbs.filePath": "off",
  "breadcrumbs.symbolPath": "on"
```

2. Open a file which isn't supported by the breadcrumbs, like an XML file:

![2018-08-14 11_18_12-webapi xml - visual studio code](https://user-images.githubusercontent.com/42275345/44083521-773a9c00-9fb4-11e8-8e68-35a2e36c7159.png)

---

A breadcrumb bar is shown, but it houses no content.

Is it possible to disable the breadcrumb bar if no symbol path is found? And enable it again when a symbol path is found?

**Comment by jrieken** [comment]
Hiding and showing might become a little nervous because it depends on the what you are typing. However, we could show something like 'Empty' etc

**Comment by Tyriar** [comment]
This is one of my big annoyances, but I don't want exactly what is being asked. I agree with you @jrieken that we don't want to show/hide while navigating around the file and I think that should remain.

What I want is for the setting to be evaluated in the beginning, mainly just `filePath: "off"` and if it is disabled and the editor is also incapable of providing breadcrumbs (custom editors/webviews), it should hide (https://github.com/microsoft/vscode/issues/81774).

I ended up disabling breadcrumbs because I was sick of this empty bar:

![image](https://user-images.githubusercontent.com/2193314/106778741-252f8500-65fb-11eb-9c7a-ee3f799ff7be.png)

Curiously, the behavior is what I'm after in untitled custom binary editors only.

**Comment by jrieken** [comment]
> mainly just filePath: "off" and if it is disabled and the editor is also incapable of providing breadcrumbs (custom editors/webviews), it should hide

The problem is that we don't really know this. The non-filePath breadcrumbs are provided by extensions and they often come late, e.g the opening of that file might have triggered activation etc. So, while we might be able to hide the breadcrumbs at first there will be flicker. A similar but more ugly case is when you have a provider but when the file is empty.

An easy change that would avoid the void would be placeholder message like 'no items'.

**Comment by Tyriar** [comment]
Ah ok, so it's still possible to get breadcrumbs even when using custom editors? I get why it's not so easy now.

**Comment by jrieken** [comment]
Well, at least for notebooks you can get them and in theory (from the internal API) you can get breadcrumbs for any editor.

**Comment by jrieken** [comment]
To mitigate this, I'll push a change to show a placeholder

<img width="593" alt="Screenshot 2021-03-30 at 15 43 31" src="https://user-images.githubusercontent.com/1794099/112998807-b0964400-916e-11eb-8953-be4e225e5e10.png">
