### ISSUE TITLE
Debugging an extension does not produce console output in dev host window

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5633]
- VSCode Version: 1.0.1-alpha
- OS Version: Windows 10

Steps to Reproduce:

1. Create an extension
2. Under the activate function in extension.js add:
```javascript
 console.log('Congratulations, your extension "MyTestExtension" is now active!');
```

3. Launch extension debugging.
4. Press F1 in the host to launch the extension.

Actual:
The console output is being generated in the original Code window, but no output is showing in the dev host window.

**Comment by isidorn** [comment]
I believe this is designed behavior and also how we behave in 1.0.0.
The original code window is used for debugging, so IMHO all debugging information should be displayed in the original window, like the `console.log`. Otherwise the experience would be disconnected for the user - to inspect variables he woudl go to original window but to inspect log to the dev host window.

@bpasero opinions welcome

Closing this for now as designed.
