### ISSUE TITLE
I can't change  the keyboard shortcuts for breadcrumbs.

### ISSUE THREAD

**Issue by monadbobo** [Microsoft/vscode#56379]
Hi all.
In the default, when dropdown appears in breadcumbs, we can use uparrow or downarrow select some element and moving, My question is: How can it change the uparrow/downarrow to my keyboard shortcuts(maybe ctrl+n/ctrl+p). I did not find their corresponding key.

**Comment by jrieken** [comment]
It used the normal list commands, e.g this is how you configure `cmd+p` to move focus up

```
{
		"key": "cmd+p",
		"command": "list.focusUp",
		"when": "listFocus && !inputFocus"
	},
```

**Comment by nwshane** [comment]
@jrieken I have that exact keyboard shortcut (using ctrl+p instead of cmd+p), but I can't use ctrl+p in the breadcrumbs dropdown. I _can_ use ctrl+p to move focus up in the command menu and files menu (cmd+shift+p and cmd+p). Any idea how to make the breadcrumbs dropdown behave like these other lists so that ctrl+p works?
