### ISSUE TITLE
Provide 'pause all' and 'continue all' threads action

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#5643]
Currently the pause and continue actions only pause/continue the currently debugged thread.
We should introduce actions that continue all / pause all threads

Not sure if these should be only global workbench actions or also exposed in the ui somehow

**Comment by isidorn** [comment]
fyi @weinand current pause and continue actions only pause or continue the currently debugged thread. I would introduce 2 more global workbench actions that would pause or continue all threads. Let me know what you think

**Comment by weinand** [comment]
@isidorn does Visual Studio have those additional actions as well?
And you would implement those actions by using multiple pause and continue requests for all threads that are known to you or would you need a protocol addition?

**Comment by isidorn** [comment]
@weinand installing VS to my vm to check it out..
Another idea I got, which is now my favorite is to enable context menu on threads in the call stack view. So the user can choose which thread to stop and continue. We can enable multi-select so the user could pause / continue multiple threads.

This would not require any protocol additions.
But let's wait and see what VS is doing.

**Comment by isidorn** [comment]
VS does not support pause / continue all, or at least I could not find it in their UI.
So instead of that I added context menu actions for threads, so this would give the user better control as to what threads to pause / continue...

If we get the request to pause / continue all then we just need to enable multi select in call stack view

**Comment by delmyers** [comment]
@isidorn, @jacdavis I think that the understanding of how Visual Studio works here is incorrect. The converse of your statement is actually the case. VS does _not_ support pause/continue _one_. That is, VS is pause/continue all by default, and the AD7 based debuggers are all this way. For the C# debugger and C++ debugger, I think the request is really that the debugger makes the determination about how it will pause/continue debugging.

**Comment by jacdavis** [comment]
All vs debuggers (and any debugger on windows using the win32 debug api) use the Stop One model. That is the native debuggers (visual studio, windbg) and the Clr debugger. That is, when a break event occurs, all threads are stopped by the OS before the debugger ever sees the event. A continue continues all threads in the process. 

The only way to get into stop one mode on windows is for a user, to go to the threads window in break mode and pause the one thread they want stopped in break mode and then continue. While it would be nice to support a stop one model, it is _not_ something we have ever received feedback from users as necessary. Doing this automatically would introduces huge changes in the way our debuggers would work since new debug events can now arrive while we're in break mode. This is especially heinous when we are performing function evaluations implicitly like we do in managed code. 

What diag wants is this: if the stopping event has all threads stopped set to true, continue all threads on continue. That is the behavior we wanted when we added the new flag to the stopped event.

**Comment by weinand** [comment]
Since the debug adapter decides whether we use a "all threads stopped/continue" or a "one thread stopped/continue" model, there is no need for 'pause all' or 'continue all' threads actions.
