### ISSUE TITLE
VS Code  Insiders can not upgrade!

### ISSUE THREAD

**Issue by BruceAn1978** [Microsoft/vscode#56458]
version: VS Code Insiders 1.27.0
os: Win 10 x64
issue: It downloaded upgrade package successfullly and ask me to restart to finish upgrade, but js errors dialog was displayed.

![image](https://user-images.githubusercontent.com/39219907/44142801-f9dd6ba6-a0b3-11e8-83b6-2450203c50da.png)
![image](https://user-images.githubusercontent.com/39219907/44142826-102f0c48-a0b4-11e8-8943-d2694bb1474b.png)

**Comment by joaomoreno** [comment]
Can you provide the log file?

**Comment by BruceAn1978** [comment]
[vscode-inno-updater.log](https://github.com/Microsoft/vscode/files/2300091/vscode-inno-updater.log)

**Comment by joaomoreno** [comment]
Does it work if you fully reinstall VS Code?

**Comment by BruceAn1978** [comment]
I have reinstall VS Code Insiders version fully, there is no updates, so I can not confirm this issue.

**Comment by davvelsan** [comment]
Just a quick follow up on this issue, coming from a Windows 10 user.

The problem occurs when vscode is installed in a custom location, rather than the default `~\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe`.

The updater subsequently tries to find the executable file in the default location and fails. Interestingly enough, it turns out the default location has another vscode installation inside a folder named `_`.

Copying the contents of `_` to its parent folder and running the updater (from any installation), updates the default vscode folder. You can verify this by comparing their hashes. 

If someone wanted that update really bad, I suppose it may be possible to move the default install to wherever the custom one is and use that instead.

**Comment by joaomoreno** [comment]
> I have reinstall VS Code Insiders version fully, there is no updates, so I can not confirm this issue.

Let me know if it comes back.
