### ISSUE TITLE
Breakpoint widget should expand to show multiline text

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#56521]
- Copy multiple lines of text
- Add a conditional BP or logpoint
- Paste the text into the widget. Now you can scroll around with the arrow keys

It's a single line input, it should only allow a single line of text.

@JacksonKearl fixed the same issue in the extension viewlet

**Comment by isidorn** [comment]
This is perfectly fine imho
Sometimes a condition is more complicated than a single line and a user should be allowed to paste it in.
I do not really see what is the benefit of disabling this.
Also we always allowed shit + enter to go to the second line in the breakpoint widget.

For now closing this as designed - but I can be convinced otherwise.

**Comment by roblourens** [comment]
That's fine. If we officially support that, it might look better if the widget expands to show all lines or something. I think it's hard to edit when you're looking at one line at a time.

**Comment by isidorn** [comment]
@roblourens that is correct
PR tackling that is welcome, code pointer https://github.com/Microsoft/vscode/blob/585c22af98036503f26bfec8d79af31f9fd3fda9/src/vs/workbench/parts/debug/electron-browser/breakpointWidget.ts#L47

**Comment by YisraelV** [comment]
@isidorn I have implemented this and pushed it into my fork. See it here - [](https://github.com/YisraelV/vscode/commit/f931caa442a22bb977038d4e41e0a829dbc5e689)

I'm particularly concerned about the change in breakpointWidget.css. It css rule introduced by you (3 years ago) apparently to solve a bug on windows. Should I get a windows machine in order to check that my commit hasn't reintroduced the bug?

This is my first attempt at contributing to an open source project. Please let me know if I should open a pull request.

Thank you!

**Comment by isidorn** [comment]
@YisraelV yeah please open a PR.
It would be great if you can test this on windows or OS X at least. If you do not have a win machine I can test it for you once the PR is created. Thank you

**Comment by YisraelV** [comment]
@isidorn I opened a pull request. I will install windows on a virtual machine for the future but it will take me a few days to set up as I don't have a string internet connection. If you could test it for me I'll really appreciate it.

**Comment by isidorn** [comment]
Fixed via https://github.com/Microsoft/vscode/pull/61859
