### ISSUE TITLE
Services are created with instantiation service

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5653]
With https://github.com/Microsoft/vscode/commit/951ed93604de9d29bb4ca76c84cbbbb258c6c4de I see that services like the side bar part are created using the instantiation service. I think that is very risky because the instantiation service does not include all services at the point where you use it.

I explicitly decided to not use the instantiation service to create other services but explicitly call out to the services I depend on so that we do not end up in weird NPEs because some services are not ready.

I preferred the previous explicit way of services declaring their dependencies in the constructor. What is the benefit from moving away from that?

**Comment by jrieken** [comment]
The instantiation service has no more way to just ask for a service (used to be `getService`). This change was made because people started to use the instantiation service as service accessor, not as an instantiation service. 

It's arguable if the workbench was also an offender or not. I understand the concern and how about an extra flag to the `createInstance`-call that will throw an error if dependencies aren't met - the instantiation service knows that. 

Another idea is to bring shell and workbench closer together. It seems they both created services which are inter-dependent. And I wonder why that is? Ideally service creation happens in one place and the service collection doesn't travel.

**Comment by bpasero** [comment]
I think throwing an exception when you use the instantiation service on a thing that declares a service as dependency that does not exist yet is what I would expect and would solve this issue for me because what I want is an indication that my service dependencies are not met. I would not want to find this out later via a NPE because I am using a service too early.

I see the issue with creating services in 3 different places (before shell, inside shell, inside workbench). Though if you take the editor, it also creates services only later after the workbench is already there. If I had a service that needed the IModeService or IModelService from the workbench, I could not get to it until the editor widget is created.

If we want to move services closer together I think they would have to be created all inside workbench.ts because that is where some of the services are created that need the parts to be there (viewlets, editors, status bar).

**Comment by jrieken** [comment]
> Though if you take the editor, it also creates services only later after the workbench is already there. If I had a service that needed the IModeService or IModelService from the workbench, I could not get to it until the editor widget is created.

That is not true. All services are registered either in the [shell](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/shell.ts#L224) or [workbench](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/workbench.ts#L300).

**Comment by jrieken** [comment]
Closing this since 67cc42c is a change the will throw errors when services are missing and the new `@optional` decorator isn't used.

**Comment by bpasero** [comment]
Cool 👍
