### ISSUE TITLE
Graceful handling of our hygiene failures

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#56611]
1. Add a few whitespace to our code
2. Make a commit

![image](https://user-images.githubusercontent.com/4033249/44239367-d319f100-a16d-11e8-867a-49ac51cffcc3.png)

1. I get mystic error that doesn't relate to the real cause of the error.
2. There is no easy way for me to check the hygiene error. I can go to Output -> Git, but normal users wouldn't be able to find this out.

**Comment by joaomoreno** [comment]
Yeah... we're bound to parse the output of `git commit`. Here's the full output of that command:

```
Found '/home/joao/Work/vscode/.nvmrc' with version <8.9.2>
Now using node v8.9.2 (npm v5.5.1)

> husky - npm run -s precommit
> husky - node v8.9.2

Reading git index versions...
src/vs/platform/environment/node/environmentService.ts(210,1): Bad whitespace indentation
File not formatted: src/vs/platform/environment/node/environmentService.ts


Hygiene failed with 2 errors. Check 'build/gulpfile.hygiene.js'.

> husky - pre-commit hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run precommit'
```

This output is specific to nvm, husky and our very own hygiene script. No matter what we do to fix this, it will all be specific heuristics for our own selfhost. It will still not help other users since they will have different tools outputting different errors using different syntaxes.

Also, you don't need to go `Output > Git`, that's what the `Open Git Log` button is for.

I argue that this is an issue which happens often to our team but very rarely in our user base.
