### ISSUE TITLE
Add DiagnosticTag.Deprecated

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/vscode#56694]
Now that `DiagnosticTag` has been added to the API, I would like to support the proposal from #51104 to use it for tagging deprecated items.

I figure the associated styling might be a strikethrough as proposed in #50972 but you guys can work that out separately.

**Comment by kamranayub** [comment]
@jrieken I would be interested in helping out here with this and perhaps even #50972.

Without a lot of context, I assume this issue is specifically to add a new enum member here:

https://github.com/microsoft/vscode/blob/03e13189e7518414fbbad5324908fe3eeb572eae/src/vs/vscode.d.ts#L4274

I could open a PR that adds a `Deprecated` member, if that's the case.

**Comment by jrieken** [comment]
Yes, `vscode.proposed.d.ts` is the way to go. Find your way along usages/implementations of `Unnecessary`

**Comment by kamranayub** [comment]
Thanks, I'll work on that today.

**Comment by jrieken** [comment]
Leaving this open so that we discuss this in the API sync

**Comment by jrieken** [comment]
API has been finalised.
