### ISSUE TITLE
Cannot read property 'end' of undefined

### ISSUE THREAD

**Issue by dereklakin** [Microsoft/vscode#56700]
Issue Type: <b>Bug</b>

1. Start debugging (I'm using Flutter).
1. Stop debugging.

VS Code version: Code - Insiders 1.27.0-insider (fd610b4b6ab8d4735a4d84a2b59206ad3a9c8099, 2018-08-17T05:18:51.696Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (0.71GB free)|
|Process Argv|C:\Users\derek\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
dart-code|Dar|2.17.1
flutter|Dar|2.17.1
githistory|don|0.4.2
vscode-auto-open-markdown-preview|hnw|0.0.4
csharp|ms-|1.15.2
vscode-icons|rob|7.25.0
code-spell-checker|str|1.6.10

</details>

**Comment by DanTup** [comment]
This was reported at https://github.com/Dart-Code/Dart-Code/issues/1155 too. I wonder if it's related to the changes made to terminate/disconnectRequest in the latest release.

@isidorn This was also mentioned in https://github.com/Microsoft/vscode/issues/54378 so I wonder if they may be related. There's a stack trace at https://github.com/Dart-Code/Dart-Code/issues/1155#issuecomment-413704580 which doesn't look like it's coming from my code, but since it may be processing the response to a request, who knows (our disconnectRequest is a little complicated).

I'll post back if I figure out anything useful.

**Comment by isidorn** [comment]
@DanTup thanks, I am in a middle of a large refactoring which should tackle #54378 I will let you know once it is available in insiders (probably tomorrow, or the day after).
And you can report back more details about this once you find out.

**Comment by DanTup** [comment]
My disconnectRequest method was actually written assuming that we'd be called once to shut down, and if we didn't shutdown fast enough, the debug toolbar would remain visible and if the user clicked Stop again, disconnectRequest would be called again.

I've just changed over to terminateRequest (where we now try to gracefully shutdown in terminateRequest, then forcefully in disconnectRequest) and this problem seems to have disappeared. However, it seems like disconnectRequest might be called really quickly after terminateRequest, so we end up sending a SIGKILL while we're trying to gracefully shut down (this is bad, because a SIGKILL will result in orphaned processes).

Do you know whether we should be able to delay the call to disconnectRequest if terminateRequest is slow? I think I'm not calling super.terminateRequest() or sending the TerminateEvent until the process really quits but it looks like (though I'm still investigating) that disconnectRequest might be arriving while this is still in progress.

**Comment by DanTup** [comment]
Actually, maybe I misunderstood - am I supposed to implement only terminateRequest *instead of* disconnectRequest? The release notes seem a bit vague about the implementation.

**Comment by DanTup** [comment]
Ok, scratch that - I've found my issue. I have two paths that send a TerminatedEvent() and one of them fires really early, and that's what's happening while I'm still processing my terminateRequest. With that fixed, I think this issue will go away (for Flutter). However, I'm not sure why it happened and whether it may affect other debuggers.

**Comment by weinand** [comment]
Yes, if VS Code gets a `TerminatedEvent` it assumes that the debuggee has terminated and then VS Code proceeds with its regular shutdown sequence (which includes the `DisconnectRequest`).
So please make sure that the debuggee has really terminated before sending the `TerminatedEvent` or protect your `DisconnectRequest` implementation from being called too early.

**Comment by isidorn** [comment]
This seems to behave like it should, thus closing

**Comment by DanTup** [comment]
Yep, the last few comments make sense, and that's working now. I don't think it's the same as the original issue though, since that was before I did any terminateRequest support. I think the changes to support that may have changed something which caused this error - however, since it's only been reported in Flutter so far (and that issue is resolved with the move to terminateRequest) it may have been a bug in the Flutter debugger (I thought maybe we were sending TerminatedEvent twice, though now I'm not so sure). It's probably not worth digging into unless it's reported by another debugger.
