### ISSUE TITLE
Security: User Setup recommendation is a regression of the installer experience

### ISSUE THREAD

**Issue by NightmareJoker2** [Microsoft/vscode#56736]
The new prompt for the [User Setup](https://code.visualstudio.com/updates/v1_26#_user-setup-for-windows) is a security regression on Windows. It is bad enough that the update experience has switched from using the Microsoft Installer (`.msi` files) to some other strange updater, but installing applications to the user's profile is bad, because the location is writable by any application that runs in the context of that user, including if they aren't members of the **Administrators** group.
This kind of behavior should never be encouraged by first-party software from the platform vendor, and especially not for developer tools, encouraging developers who use them to then do the same.

This is not as important, but it also means, if the PC is a multi-user machine, that the installations would duplicate for every user of the device, which is an unnecessary waste of disk space.

Related: #56421

**Comment by byyxx128** [comment]
I just wanted to open a new issue then I find yours here.😂
Yes, please do NOT make the User Setup as recommendation and default!😒

**Comment by rinkley** [comment]
VS Code and Git newbie here.  Installed 1.25.1 and it was nice.  Got a note to upgrade to 1.26.1 and all of a sudden I have two copies of the application on my Windows 7 machine.  Guess I am experiencing what the two folks above me are complaining about.  What is the fix?

**Comment by beastdestroyer** [comment]
@rinkley The solution is to uninstall one of the setups. I personally use the main setup not user-based one, you should probably uninstall the 1.26.1 and see if you can download the installer from the website at the [VSCode website](https://code.visualstudio.com)

**Comment by kumorig** [comment]
I have similar worries but I was not sure if I should bother making a new issue. Sorry if this isn't 100% related. It's regarding this:

![code_2018-08-20_01-27-45](https://user-images.githubusercontent.com/5523938/44310969-49428000-a41a-11e8-9bc2-4d1f9ac1fb30.png)

One click and a download starts before I can blink, with a url like this: https://az764295.vo.msecnd.net/stable/493869ee3e8a846b0855873836fc79d480d342de/VSCodeUserSetup-x64-1.26.1.exe 

My concerns are:

* With the notifications API, how *incredibly* easy would it be fake this popup?
* Can I even tell if this is notification is from vs-code or an extension?
* Can I verify the link in any way, or am I supposed to trust anything just because its on the Azure CDN?
* Are we just assuming all extension-devs are 100% good all the time or is this like "wordpress plugins" where you can just crash and burn and you are stupid for using the wrong one (or any at all for that matter).

Maybe I'm missing something obvious (maybe some extension auditing that I'm completely unaware?)

**Comment by beastdestroyer** [comment]
@kumorig That URL is similar to the one I clicked on to test out the User Distribution. I have virus scanned with Avast and Malwarebytes and it works completely fine. That notification is simply VSCode wanting you to try it out so you don't need to have Admin passwords (if you have it setup) etc. It isn't related to any extension and is natively shown by VSCode. To most people, you can ignore this specific notification since it basically is a user-based VSCode.

**Comment by joaomoreno** [comment]
@NightmareJoker2 Code never had an MSI distribution. It always had a setup based on Inno Setup. The new user setup is also Inno Setup based. Basically it's the user' choice of how to install VS Code, we just provide several different options, with preference on one (user setup) since it provies the best user experience.

@kumorig You make good points. I think removing the notification is better at this point. I will remove it for the next release.

@rinkley Yeah, just uninstall the global installation in the Control Panel.

**Comment by NightmareJoker2** [comment]
@joaomoreno 
> with preference on one (user setup) since it provides the best user experience.

I have to reiterate:
> installing applications to the user's profile is bad, because the location is writable by any application that runs in the context of that user, including if they aren't members of the **Administrators** group.
This kind of behavior should never be encouraged by first-party software from the platform vendor, and especially not for developer tools, encouraging developers who use them to then do the same.

Also, why do you add a *bug* label and then immediately close the issue? I see no proposed solution, referenced bug fix, or anything addressing the problem of any kind.

**Comment by joaomoreno** [comment]
The close action references https://github.com/Microsoft/vscode/commit/4754feafb0d174c84b876b87c0a77d9f959ba311 which simply removes the notification, as I mentioned above.

Nothing you said is wrong. Yet, given the amount of issues we get related to users not being able to install/update code on Windows due to lack of permissions, combined with the fact that updates run much smoother if there needs to be no escalation prompt, we think it's still preferable to suggest a user install by default. Thanks for your feedback.

**Comment by NightmareJoker2** [comment]
> given the amount of issues we get related to users not being able to install/update code on Windows due to lack of permissions

Those *users* would do good first learning about the permissions they have, or ask their administrators to install/update software instead, because if that truly stumbles them, they should either not be writing software, or aren't supposed to install any the IT department didn't approve of anyway.

> updates run much smoother if there needs to be no escalation prompt

So does malware attaching itself to frequently used programs. User Account Control exists for a reason, and it's a pretty good one.

> we think it's still preferable to suggest a user install by default

You shouldn't, that's part of the problem.
