### ISSUE TITLE
Auto indentation is not smart enough

### ISSUE THREAD

**Issue by minj** [microsoft/vscode#56769]
- VSCode Version: 1.26.1
- OS Version: Linux

It just follows the last line.

Problem can be reproduced by examples @ https://github.com/Microsoft/vscode/issues/36505#issuecomment-341164819

I am purposefully creating a duplicate of #36505 since I find the resolution to it lacking.
Duplicate? Of what? How to work/hack around this?

I don't believe editor's job is to force code style on people.

It seems to be something a capable editor should be... capable to do. This is a UX breaker for me.

**Comment by rebornix** [comment]
Can you try setting `editor.autoIndent` to `false` to see if it mitigates the problem you run into?

I agree that indentation is related to code styles.

**Comment by minj** [comment]
Wanted to post an update since it's been 6 months...

The paste problems seem to be resolved. Here's the snippet with current issues:

```js
// pretend CARET is the text cursor
// if you press enter, the new line isn't indented (it should be)
if (x) CARET

// if you press enter, the new line is indented (it shouldn't be)
if (x)
	return; CARET

// if you...
// - press enter, the new line is indented (it shouldn't be)
if (x)
	return;
CARET
```

FYI, disabling `editor.autoIndent` does 'solve' the last two problems but that kind of defeats the purpose, doesn't it?

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules and only support limited code styles), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment or use auto formatting (`editor.formatOnType`, `editor.formatOnPaste`). As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like (https://github.com/microsoft/vscode/issues/19847 and https://github.com/microsoft/vscode/issues/34621).
