### ISSUE TITLE
VSCode-linux-x64-stable.zip doesn't run as root

### ISSUE THREAD

**Issue by ctaggart** [Microsoft/vscode#5679]
- VSCode Version:
  latest stable Linux 64: VSCode-linux-x64-stable.zip
  downloaded from:
  - https://code.visualstudio.com/Docs/?dv=linux64
  - https://go.microsoft.com/fwlink/?LinkID=620884
- OS Version:
  Ubuntu 14.04

Steps to Reproduce:

```
curl -o VSCode-linux-x64-stable.zip -L https://go.microsoft.com/fwlink/?LinkID=620884
unzip -q VSCode-linux-x64-stable.zip
export PATH=$PWD/VSCode-linux-x64:$PATH
code --verbose
```

```
root@937050988adf:~# code --verbose
{ [Error: ENOENT: no such file or directory, open '/root/.config/Code/storage.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/root/.config/Code/storage.json' }
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at Object.exports.spawn (child_process.js:351:9)
    at /root/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:6:6784
    at new __dirname.undefined.t.Class.derive._oncancel (/root/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:5:6601)
    at Object.i [as getUserEnvironment] (/root/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:6:6747)
    at Object.<anonymous> (/root/VSCode-linux-x64/resources/app/out/vs/workbench/electron-main/main.js:9:10764)
    at e._invokeFactory (/root/VSCode-linux-x64/resources/app/out/vs/loader.js:4:13697)
    at e._complete (/root/VSCode-linux-x64/resources/app/out/vs/loader.js:4:14014)
    at e.resolveDependency (/root/VSCode-linux-x64/resources/app/out/vs/loader.js:4:15068)
```

**Comment by Tyriar** [comment]
@ctaggart haven't seen this before. I'm curious who owns files/folders, what the permissions are on them and whether they actually exist. Can you pass along the output of these commands?

```bash
whoami
ls -la ~ | grep .config
ls -la ~/.config | grep Code
ls -la ~/.config/Code
```

**Comment by ctaggart** [comment]
Here is the output:
```
root@937050988adf:~# whoami
root
root@937050988adf:~# ls -la ~ | grep .config
drwx------  3 root root  4096 Apr 22 22:37 .config
root@937050988adf:~# ls -la ~/.config | grep Code
drwx------  3 root root 4096 Apr 22 22:51 Code
root@937050988adf:~# ls -la ~/.config/Code
total 16
drwx------ 3 root root 4096 Apr 22 22:51 .
drwx------ 3 root root 4096 Apr 22 22:37 ..
-rw-r--r-- 1 root root    2 Apr 22 22:58 DevTools Extensions
drwxr-xr-x 2 root root 4096 Apr 22 22:37 User
```

**Comment by Tyriar** [comment]
Weird, I would expect it to work provided the user has `rw` access to `~/.config`. It might be an issue with Electron. The only things I can recommend are to try with a non-root user or installing via a package (though the latter probably won't make a difference).

**Comment by ctaggart** [comment]
It appears to be an issue when running as root. The GUI came up when I ran as a user.

**Comment by ctaggart** [comment]
@Tyriar In the [April Iteration Plan](https://github.com/Microsoft/vscode/issues/4888) I noticed:

>  Linux: Support running vscode with sudo permissions #3068 @tyriar
 Test #5062

I was hoping that this would allow me to launch VSCode as root. I downloaded the insiders build and tried launching it, but it doesn't launch and I don't get any output:

```
root@1f20642fd434:~# code-insiders --user-data-dir=/root/profile --version
1.1.0-insider
root@1f20642fd434:~# code-insiders --user-data-dir=/root/profile .        
root@1f20642fd434:~# pwd
/root
```

I noticed that a `User` subdirectory is created:
```
root@1f20642fd434:~# ls -al ./profile/User/
total 85
drwxr-xr-x 2 root root  68 May  7 19:48 .
drwxr-xr-x 3 root root 102 May  7 19:48 ..
```

Should it be possible to launch VSCode as root?

**Comment by natostanco** [comment]
I am experiencing a similar issue, just the opposite...I can run:

- `su root` -> `/opt/vsc/code`
- `sudo /opt/svc/code`
- `sudo -u non-root /opt/svc/code`

but I cannot simply run from any user, 
```
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:278:26)
    at Object.exports.spawn (child_process.js:379:9)
    at /opt/visual-studio-code/resources/app/out/vs/workbench/electron-main/main.js:6:4539
    at new __dirname.undefined.t.Class.derive._oncancel (/opt/visual-studio-code/resources/app/out/vs/workbench/electron-main/main.js:5:9667)
    at Object.o [as getUnixUserEnvironment] (/opt/visual-studio-code/resources/app/out/vs/workbench/electron-main/main.js:6:4502)
    at I (/opt/visual-studio-code/resources/app/out/vs/workbench/electron-main/main.js:10:15570)
    at Object.<anonymous> (/opt/visual-studio-code/resources/app/out/vs/workbench/electron-main/main.js:10:16109)
    at e._invokeFactory (/opt/visual-studio-code/resources/app/out/vs/loader.js:4:13697)
    at e._complete (/opt/visual-studio-code/resources/app/out/vs/loader.js:4:14014)
```
...but as I said, If I use sudo and specify a non-root user it works.

**Comment by Tyriar** [comment]
I'm curious on what you guys think the best way to handle this is. I spend most of my time in Ubuntu so running as root is not usually a thing I'm allowed to do (`su` is locked down on Ubuntu). The recent change was specifically targeting `sudo` only as previously it hung when launched.

Here's the current situation:

- The code bin command enforces a `--user-data-dir` when `id -u` is `0`, see https://github.com/Microsoft/vscode/blob/master/resources/linux/bin/code.sh#L9 - This was done because when running as sudo, the current user data directory is stored within `~/.config` which has restrictive permissions:

  ```
  ❯ ls -la ~ | grep .config
  drwx------  33 daimms daimms  4096 May 16 11:35 .config
  ```

  The need for this will go away post-https://github.com/Microsoft/vscode/pull/5570 where the --user-data-dir is specified automatically as a sibling to the regular user's data dir.
- When running as root, do not attempt to open the welcome page. This is due to a bug in `xdg-open`, see https://github.com/Microsoft/vscode/commit/ad7e861dbb9127e919bc686da162b19cbb7e2391 (this may be fixed now https://github.com/electron/electron/issues/4916, created https://github.com/Microsoft/vscode/issues/6594 to follow up).
- When in a sudo session of vscode, you can only open root-owned files. I'm sure you can get around this, I didn't invest enough time in this though since people should not be using sudo in general as it will mess up file perms which may be confusing to newer users.

It's a very bare-bones support situation at the moment, plus it focuses around running as sudo instead of root, which I don't think `id -u` differentiates between. So I believe the fixes I did may have made the situation worse when running as the root user instead of `sudo` on a non-root user.

Any input from the community would be greatly appreciated :smiley:

**Comment by ctaggart** [comment]
I created this issue originally when making some docker images with VSCode on it. My solution was simply to create a `vscode` user that has sudo access. I'm happy with that solution, so I'm going to close this issue.

https://github.com/ctaggart/dotnet-vscode/blob/master/root/install-user.sh

**Comment by Tyriar** [comment]
Going to reopen, I'd eventually like to get it working as expected for root user, sudo and regular users.

**Comment by Tyriar** [comment]
Closing since there are no plans to fix this any time soon and there is a workaround in https://github.com/Microsoft/vscode/issues/5679#issuecomment-221022927
