### ISSUE TITLE
Indentação não está funcionando ao copiar e colar

### ISSUE THREAD

**Issue by renankaic** [microsoft/vscode#56826]
Após a ultima atualização, quando mexo em um documento HTML tento copiar e colar, a indentação não fica correta, fica no começo da linha ao invés de estar dentro de onde eu colei.

![image](https://user-images.githubusercontent.com/26421325/44347546-7c166380-a46e-11e8-9b21-197ef1acfaed.png)

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules and only support limited code styles), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment or use auto formatting (`editor.formatOnType`, `editor.formatOnPaste`). As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like (https://github.com/microsoft/vscode/issues/19847 and https://github.com/microsoft/vscode/issues/34621).
