### ISSUE TITLE
Webview tab title (tooltip) is not friendly

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#56853]
- VSCode Version: 1.27
- OS Version: Windows 10 x64

![image](https://user-images.githubusercontent.com/641685/44369763-8c960080-a4a5-11e8-83bc-8a5a309a9319.png)

/cc @mjbvz 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by avannaldas** [comment]
Shall I take this up?

**Comment by mjbvz** [comment]
Sure, I believe this needs to be changed on the webview input object: https://github.com/microsoft/vscode/blob/master/src/vs/workbench/parts/webview/electron-browser/webviewEditorInput.ts#L18

The two methods to look at are `getTitle` and `getDescription` form here https://github.com/microsoft/vscode/blob/master/src/vs/workbench/common/editor.ts#L364

**Comment by avannaldas** [comment]
@mjbvz Cool, thanks for the guidance, will start looking into it. 

As indicated in the screenshot I've installed CodeStream extension. I see correct tooltip as "CodeStream".

![image](https://user-images.githubusercontent.com/11676976/48207915-b7526f80-e397-11e8-9eb7-de5d6edef3f1.png)

Any other way to test the existing behavior?

**Comment by avannaldas** [comment]
From what I've understood so far, the title text is being specified as a parameter when a WebView is created. In above case CodeStream extension (I suppose) is creating a WebView without specifying title property (as on 21st Aug '18). However, since it's now showing appropriately, it should be passing the title property. 

I checked using two extensions [Preview](https://marketplace.visualstudio.com/items?itemName=myh.preview-vscode) and [HTML Preview](https://marketplace.visualstudio.com/items?itemName=tht13.html-preview-vscode), both display title and tooltip similar to the way default Markdown Preview displays. I believe both extensions use webview.

Thoughts...
- Is the path of a resource being used as a fallback when the name/title is not provided? I see for codestream, the tooltip seems to be coming from [`path`](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/parts/webview/electron-browser/webviewEditorInput.ts#L132) of a resource. 
- Would it make sense to make the name/title a mandatory parameter and throw when it isn't provided?
- Grabbing `<title>` text from html wouldn't be a good idea I think.

Please advice. Thanks for the guidance and help!

Regards,
Abhijit

**Comment by mjbvz** [comment]
Ok, this actually seems to be working now then. Here's for the cat coding webview:

<img width="169" alt="screen shot 2018-11-09 at 1 41 22 pm" src="https://user-images.githubusercontent.com/12821956/48289672-2a55f780-e425-11e8-95af-ffbc26505d7c.png">

The original bug was the we were showing the `\webview-panel-webview-1` in tooltips, which no longer seems to be the case

Thanks for the investigation! @avannaldas Closing this since it is fixed

**Comment by isidorn** [comment]
Verified by hovering over the markdown preview
