### ISSUE TITLE
Plain text in markdown indents incorrectly

### ISSUE THREAD

**Issue by caneridge** [microsoft/vscode#56863]
Issue Type: <b>Bug</b>

When editing a markdown document with these two lines (period denotes a space); tab set to insert 4 spaces:

```
....a
......b
```

Selecting lines a,b and pressing tab results in:

```
........a
........b
```

Rather than

```
........a
..........b
```

The auto indent setting does not change the behavior. I've disabled all of my markdown extensions and the behavior is the same with them or without them. I'd like the ability to have free-format text in markdown that indents by just inserting the indent amount before every line in the selected block. 

When indenting this:

```
           ┌──────┐
           │      │
┌──────────▼────┐ │
│    Block 1    │ │
└───────────────┘ │
        │         │
        │         │
        │         │
        │         │
        ▼         │
┌───────────────┐ │
│    Block 2    │ │
└────────────┬──┘ │
             │    │
             └────┘
```

It becomes this:

```
            ┌──────┐
            │      │
    ┌──────────▼────┐ │
    │    Block 1    │ │
    └───────────────┘ │
            │         │
            │         │
            │         │
            │         │
            ▼         │
    ┌───────────────┐ │
    │    Block 2    │ │
    └────────────┬──┘ │
                │    │
                └────┘
```

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:31:26.156Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (0.60GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron -psn_0_10865244|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|2.3.0
vscode-docker|Pet|0.1.0
code-spell-checker|str|1.6.10
gitblame|wad|2.4.4

</details>

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules and only support limited code styles), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment or use auto formatting (`editor.formatOnType`, `editor.formatOnPaste`). As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like (https://github.com/microsoft/vscode/issues/19847 and https://github.com/microsoft/vscode/issues/34621).
