### ISSUE TITLE
NVM and PATH issues

### ISSUE THREAD

**Issue by dominictwlee** [Microsoft/vscode#56890]
- VSCode Version: 1.26.1
- OS Version: Ubuntu 18.04

Suggested by @ruslan-bikkinin to bring the conversation over here.

Please see: https://github.com/Microsoft/vscode-react-native/issues/755

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
The problem very likely lies in 

```
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```

Try moving the NVM setup code before that snippet in your `.bashrc`, does that fix it?

**Comment by ruslan-bikkinin** [comment]
Hi @joaomoreno, Ruslan from vscode-react-native is here. If you need any help/comments from my side feel free to ask me.

**Comment by dominictwlee** [comment]
@joaomoreno Just tried that, still no luck :(.

**Comment by dominictwlee** [comment]
@joaomoreno That may have worked! I normally get the errors 'cannot find flow in path/cannot find node in path' but that no longer appears. I'm going to try and see whether command palette and debugger works tomorrow.

**Comment by Mausic** [comment]
Hi there,
I faced pretty similar issue while running react-native project "Debug iOS" with vscode-react-native extension. 
I did not manage to determine what is a root of an issue. Since here are representatives of both teams I'd like to add some info.

**Issue**: `console.log('something')` did not print message into a 'DEBUG CONSOLE'. Debug logtrace of react-native project do not appear in a 'DEBUG CONSOLE'. All messages appear, if debug remotely via chrome.
**Additional info** when start debugging on iOS there is an exception related to web socket appears. Since it's a clean project without web-socket specific code, maybe VS Code can't instantiate connection with an RN debug module on simulator?

**Conditions**: 
1. VS Code 1.26.1
2. No `nvm` (completely uninstalled, while tried to fix an issue) 
3. Fresh install of `node` 8.11.4 from [nodejs.org](https://nodejs.org/uk/download/)
4. Fresh RN project via `react-native init helloworld`

**SOLUTION**:
1. Uninstall VS Code 1.26.1
2. Install VS Code 1.25.1

**NOTES**
I did not have any issues until I upgraded VS Code to 1.26.1. Even though I had an nvm installed before.

If you need some additional info/logs from my side - feel free to contact me.

**Comment by Mausic** [comment]
@joaomoreno ok, thank you

**Comment by dominictwlee** [comment]
@joaomoreno Everything works as long as I initially launch code from the terminal. I no longer have to set ```nvm use default``` every time before launching vscode and things seem to still work even when I load new folders or workspaces.

**Comment by joaomoreno** [comment]
So, even after moving that code before `# If not running interactively, don't do anything`, it still doesn't work when not launching from the terminal?

**Comment by ruslan-bikkinin** [comment]
@dominictwlee did you manage to resolve this or still waiting for help? 
@joaomoreno could you please reopen this issue?

**Comment by joaomoreno** [comment]
If you follow the discussion, you'll realize the issue is more a user configuration error than a VS Code issue.

> @joaomoreno That may have worked! I normally get the errors 'cannot find flow in path/cannot find node in path' but that no longer appears. I'm going to try and see whether command palette and debugger works tomorrow.

@dominictwlee Did you follow up on our investigation here?

**Comment by dominictwlee** [comment]
@joaomoreno Command palette and debugger still doesn't work unless vscode is launched from the terminal.

**Comment by joaomoreno** [comment]
Have you tried messing around with your `.bashrc` to figure out where it bails out?

**Comment by dominictwlee** [comment]
Just heads up @joaomoreno @ruslan-bikkinin even with vscode being launched from terminal it no longer works.

**Comment by ruslan-bikkinin** [comment]
@dominictwlee did you check whether your case related with the known nvm issues:
* https://github.com/creationix/nvm#compatibility-issues
* https://github.com/creationix/nvm#problems (last item in the list)?
