### ISSUE TITLE
Drag into VS Code to install VSIX extension

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#56933]
I want to be able to drag a VSIX file into VS Code to install it.

**Comment by fabiospampinato** [comment]
IMHO `.vsix` files should just be opened via VSC, so that one could install them with a double click.

If you're requesting this because installing `.vsix` files is a bit of a pain you might find my [`Install .VSIX`](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-install-vsix) extension useful.

**Comment by sandy081** [comment]
Duplicate of #31079
