### ISSUE TITLE
Allow panel placement among editor grids

### ISSUE THREAD

**Issue by sveinse** [Microsoft/vscode#57029]
I have to give kudos to the vscode developers for the new feature of having multiple editor rows and grids. This has made huge improvements to the development overview, since more can be kept visible at one time.  I'm developing on a large 4k screen, and I now often use 4 columns + sidebar, each column with 1-3 editor grids per column. The attached image shows a made-up example of this setup.

![screenshot from 2018-08-22 18-39-04](https://user-images.githubusercontent.com/13770135/44477437-f85da200-a63a-11e8-8770-0b7d8289a4f1.png)

As a user I'd like to be able to place the panel (output, terminal, etc.), freely on screen, as I am able to with an editor grids. I find that the panel takes up either very large real-estate, either using the full width at the bottom or the full height to the side. In either case too much area.

**Comment by waldyrious** [comment]
> We figured it's covering the same as another one we already have.

@isidorn since you added the duplicate label that triggered the message above, could you please mention which issue this one was considered a duplicate of? The closest one I found was #11472 ("Allow to dock editors, views and panels anywhere in the workbench"), but it seems to have been interpreted as addressed once the grid layout for editors and bottom/right locations for the panel were in place, which is a narrower feature set than what was originally asked there.

For example, similar to OP @sveinse above, I'd like to be able to have a layout like this:

```
+------------+-------------+
|            |             |
|            | Test script |
|            |             |
+    Code    +-------------+
|            |             |
|            |  Terminal   |
|            |             |
+------------+-------------+
```

**Comment by isidorn** [comment]
fyi @sbatten
