### ISSUE TITLE
Don't show mnemonics in non-English packs when disabled

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#57049]
Issue Type: <b>Bug</b>

mnemonics are still shown when disabled in non-English packs.

VS Code version: code-oss-dev 1.27.0 (Commit unknown, Date unknown)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (19.72GB free)|
|Process Argv|C:\Users\penlv\code\vscode\.build\electron\Code - OSS.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Mic|0.0.13

</details>

**Comment by sbatten** [comment]
fixed by https://github.com/Microsoft/vscode/commit/2c9408fecfc0507e78e1ac008e220d433cfef295

**Comment by sbatten** [comment]
To clarify, in language packs like simplified Chinese, mnemonics are shown as a suffix to the Chinese characters in parentheses. e.g. <File in Chinese> (F) 


The fix is to hide the parentheses and F when mnemonics are disabled. To verify, you can use the old menubar in Windows/Linux as the correct template for what the new menubar should do.
