### ISSUE TITLE
Copy value should be available for expressions with children also

### ISSUE THREAD

**Issue by Adam0914** [Microsoft/vscode#57063]
When Debugging it is not possible to export or copy an array of data from the VSCODE debug watch window to another programs like Excel or Matlab in order evaluate the data. 
![vscode_debug](https://user-images.githubusercontent.com/42383038/44510354-c721b800-a6b4-11e8-9f96-498c32d9e83b.png)
As you can see on the picture there is no option for copying the array. It is also not possible to multiple select the elements of the array and then copy it. 

- VSCODE: 1.26.0
- OS Version: macOS High Sierra 10.13.x
- Cortex-Debug extension tool

**Comment by isidorn** [comment]
The issue is that the variables which have children (like an array) have the `Copy Value` action removed because it is unclear what is the value of such an expression. Is it it's string value or should it go to the children and concatanate the value of each child (which could then potentially recurse down even more).

Leaving this open as a feature request 
fyi @weinand
