### ISSUE TITLE
New mixed titleBarStyle

### ISSUE THREAD

**Issue by Logerfo** [microsoft/vscode#57117]
As I described in https://github.com/Microsoft/vscode/issues/16363#issuecomment-413680099, changing the title bar style in order to achieve dark menus made me lost the ability to hide the title bar. I wish there was an third option, "mixed" (you can name it whatever you'd like), which uses the custom renderer (the one which achieves the dark theme), but keeps the native title bar, so I can hide it with the window flag. This implies in making the menu bar parallel to the title bar, not inside it.
Would this be hard to implement? Thanks.

**Comment by Guema** [comment]
I think the better way to do this should be to make a new custom title bar top menu that looks like the actual native one.
As it is the electron's chromium menu, it is not rendered in the web layout, but in a wrapping layout that is just not displayed at all when you set custom title bar.
For me, proceeding like this would be as better as it is easier : 
- could be themable
- will match more Code brand
- is consistent with the "custom" choice for titlebar.

**Comment by Logerfo** [comment]
When the custom title bar was implemented only in the insider preview, when you selected the custom option, the title menu was inside the title bar if it's always shown (like it still does as today) or in a new bar below the title bar if it's only shown when requested (which does not happen today, as it stills shows the menus inside the custom title bar). As for what I'm proposing, the latter is what we need for the new configuration, but using the native title bar instead of the custom one.

**Comment by Logerfo** [comment]
@Guema if the title bar is not native, then it's not hideable through the windows flag, which is the idea of this proposal.

**Comment by Guema** [comment]
I understand what you request, i was just technically speaking.
Electron, the framework that run Vscode, is - by default - rendering a first basic os-driven window with a second basic chromium-driven top menu (the one that is used when title-bar is set to native) (and the chromium dev console eventually). You can find exactly the same menubar on other electron app like : slack, ryver for exemple. 
So there is 2 layout, plus a third, the one that render your web content.

Electron can be configured to not display this default layout: native title bar and top menu, and then display only the web content (custom mode). It is still possible to display console.

What i suppose is, with Electron, it will be difficult or impossible to place the default chromium menubar under the custom title bar. I don't even know if it is possible to show this menubar without using native layout. (unless they tweak Electron's code i presume)

What i said is if they want to make a mode where menu bar is under title bar instead of inside, devs will probably have to imitate the default one in their code.

**Comment by Guema** [comment]
Ho, ok.

Well i didn't understood this like that.
Hum. This other particular case should not be really hard to do.
