### ISSUE TITLE
Current selection in suggestions widget is difficult to see in the default dark theme

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#57136]
Has the selection color in the suggestion widget changed? I noticed that I several time picked the wrong suggestion since the currently selected item was difficult to see. 

Also notice currently selected item is shown in a different color than the currently selected item in a menu.

The suggestion widget:
![image](https://user-images.githubusercontent.com/172399/44570627-c9504900-a77e-11e8-94a6-8bebce9a1a4c.png)

The menu selection
![image](https://user-images.githubusercontent.com/172399/44570754-23e9a500-a77f-11e8-958c-f5b85b3eb986.png)

Notice that the menu selection is much more clear.

**Comment by misolori** [comment]
The `list.focusBackground` color was updated to meet the color contrast ratio for when text is highlighted in the list:

![image](https://user-images.githubusercontent.com/35271042/44597038-31089300-a783-11e8-8956-b641437af756.png)

It also appears that the menu selection is using `list.activeSelectionBackground`, which is typically used when needing to show both active selection and focus in a list:

![image](https://user-images.githubusercontent.com/35271042/44597201-b4c27f80-a783-11e8-95a9-f4a48e1b0144.png)


We could look at updating the `editorWidget.background` color so that it's darker and allows more contrast between the selection (would also match the quick pick bg color):

![image](https://user-images.githubusercontent.com/35271042/44596939-da9b5480-a782-11e8-9bc1-e2923de3aa8a.png)
