### ISSUE TITLE
Symbol Completion is not work when edit in the snippet mode.

### ISSUE THREAD

**Issue by liwangqian** [Microsoft/vscode#57153]
- VSCode Version: 1.26.1
- OS Version: windows 7 64bit SP1

Show as bellow:
![demo](https://user-images.githubusercontent.com/19996314/44591205-b45fce00-a7ef-11e8-9352-41222cc1e797.gif)

**Comment by V-ed** [comment]
This is intentionnal. Usually, pressing tab accepts the selected code completion (unless configurated otherwise), and this would make a conflict when entering a snippet, because tab is then used to go to the next cursor position defined by the snippet.

You can always press Ctrl+Space to trigger the code completion manually while in "snippet"mode.

![vscode-completion-snippet](https://user-images.githubusercontent.com/16652915/44593519-919ecc80-a791-11e8-9dda-ba07c6c153ff.gif)

Now, if you want to have the code completion automatically triggered *even in snippet mode*, that's something else and something I know *I* wouldn't want, but each their own - just mention that this is what you'd want!

**Comment by liwangqian** [comment]
@V-ed But, if we can trigger the completion by Ctrl+Space, why not automatically? Completion is triggered when we edit, and if there is a complition list show, enter the TAB is expect to select the completion item, otherwise go to the next cursor position defined by the snippet.

**Comment by jrieken** [comment]
We have a setting to control that. Use `"editor.suggest.snippetsPreventQuickSuggestions": false` to enable quick suggestions when in snippet mode.
