### ISSUE TITLE
Wrong TOC highlighting

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57333]
re #57304

* scroll so that the suggest section isn't visible any more (except for its bottom whitespace)
* 🐛 the File section isn't highlight but still the suggest section

<img width="795" alt="screen shot 2018-08-28 at 09 58 17" src="https://user-images.githubusercontent.com/1794099/44709115-21ea5380-aaa9-11e8-98ba-00d29f47de08.png">

**Comment by roblourens** [comment]
Yeah, I don't have a good way to do this, except arbitrarily exclude the top 1% of the screen or something

**Comment by roblourens** [comment]
Hey @misolori do you know of other examples of this sort of behavior? I'd like to see how they handle this case.

My theory has been that it should always highlight the very topmost visible setting, because you can't see the heading for that section. Even if you scroll onto some other section that takes up most of the list, at least you can see the heading for it already.

**Comment by roblourens** [comment]
Changed so that the "first visible element" must have half its content visible. I think this looks better.
