### ISSUE TITLE
Settings editor: focus navigation not ideal for up / down

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#57372]
Refs: #57304

If I focus into the settings list and I press down I would expect that every time I press down the next setting is focused. And if I want to inspect the content of that setting I would hit tab to focus into it.
However this is not how it currently behaves, every up / down focuses random elements between settings and this makes the navigation cumbersome as compared to our other lists in vscode.

For instance this works very nicely in the table of contents in the settings.

**Comment by roblourens** [comment]
Settings essentially isn't a list anymore, it used to be but that was very unpopular

**Comment by roblourens** [comment]
We can't use the arrow keys for navigation because they are used for the input controls. For example, 'down' will open the dropdown control. Is that basically what you're suggesting? You're describing how it worked last month, but we switched to only tab-based navigation, so it's like any other form.

I considered adding commands to focus the next/previous setting control so someone can add their own keybindings like ctrl+up/down but I don't think anyone really wants that, `tab` is how navigation should work in a form.

**Comment by isidorn** [comment]
Thanks for the explanation. Ok let's go with tab and wait for user feedback
