### ISSUE TITLE
Should TextSearchPreviewOptions totalChars > leadingChars?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#57418]
Refs: https://github.com/Microsoft/vscode/issues/57305

It looks like a setting of e.g. `totalChars: 2` and `leadingChars: 10` causes `10` leading chars to show up. I would expect the `totalChars` to be more important than leading chars.

**Comment by sbatten** [comment]
I used `leadingChars: 4` and `totalChars: 5` and got 9 chars. I expected just 5. Should totalChars be totalMatchedChars?

**Comment by sbatten** [comment]
I guess `totalChars` limits the match + trailing chars but doesn't trim the match, so a match longer than the `totalChars` still outputs the full match. Perhaps, there should just be explicit `leading`, `matched`, and `trailing` limits set.

**Comment by roblourens** [comment]
I think I have it set up so the match itself will never be trimmed, but I guess that's not right, a match can be very long.

I did it this way instead of specifying the 3 different sizes, because I think these factors are what a consumer really cares about - in the viewlet we want the match to be close to the left, and we want some reasonable upper limit on the total size. But we don't care specifically how many characters are after the match.

**Comment by roblourens** [comment]
Then they know the length of the match and can derive totalChars from there :D

But still, if you have 3 components, then you are setting it up to limit the size of the match while still showing some trailing context which doesn't make sense. If we combine them, then I can say, give me a total of X characters, which will be as much of the match as you can, or the whole match and as much trailing context as you can.

**Comment by sbatten** [comment]
> Then they know the length of the match and can derive totalChars from there :D
That's not true in the case of regex search

> But still, if you have 3 components, then you are setting it up to limit the size of the match while still showing some trailing context which doesn't make sense.
Why not? In the case of logs, it wouldn't be that crazy to be searching for a set of patterns with regex that all boil down to the same thing except when including the trailing content.

As with most things, I would see it easy to say this isn't the common case, but if this isn't the place to enable this kind of extensibility, then where is?

**Comment by roblourens** [comment]
> Why not? In the case of logs, it wouldn't be that crazy to be searching for a set of patterns with regex that all boil down to the same thing except when including the trailing content.

That's a good point, I can see the use.

I think the point of these options isn't to slice the match every way an extension might want to display it, it's to protect us from accidentally sending around huge amounts of data between processes. An extension can get the full line if it wants, then slice it down to trim the match and show the trailing context. That doesn't help if the match itself is a MB of text. Should that be in the threat model for findTextInFiles? No clue...

And this kind of leads into another thing which is specifically requesting context lines on either side of a match. I want to investigate that soon, because it will make sense for showing results in an editor even if we can't use it in the search viewlet.

**Comment by roblourens** [comment]
I think previewOptions as-is could be extended with parameters for trailing characters (context within the line) and a max length of the match itself. They would still make sense along with `totalChars`, and we should keep `totalChars` because I need to be able to limit the whole preview without picking between the match and the trailing characters up front.

**Comment by roblourens** [comment]
So anyway... we can extend it in the future if we want to. For now I assert that totalChars > leadingChars and changed it to truncate the match if it's longer than totalChars.

Verification steps, verify that if you call findTextInFiles with previewOptions having totalChars <= leadingChars, you get an error.
