### ISSUE TITLE
Integrated terminal shellArgs inconsistency with "bash -c -e --rcfile" commands

### ISSUE THREAD

**Issue by mundusnine** [Microsoft/vscode#57454]
- VSCode Version:1.26.1
- OS Version: Debian 9 stretch

Steps to Reproduce:

1.  Install `npm install -D typescript` in project directory
2. Add to workspace settings: `"terminal.integrated.shellArgs.linux": ["-e"," alias tsc=./node_modules/.bin/tsc "]`
3. Open terminal(terminal closes with error "No such directory" or if using -c the terminal just closes by itself. Adding "; bash" only negates aliasing)

To make it work and still have a bug 
1. same as other
2. Add to workspace settings: `"terminal.integrated.shellArgs.linux": ["--rcfile"," script-containing-alias-calls.sh "]`
3. Terminal text becomes all white
4. Workaround add : `PS1='\[\033[1;36m\]\u\[\033[1;31m\]@\[\033[1;32m\]\h:\[\033[1;35m\]\w\[\033[1;31m\]\$\[\033[0m\] '` to .sh file

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This looks like an environment/setup issue rather than a problem with VS Code itself. The way I would go about doing this is by just adding the alias to your `~/.bashrc` file. If you don't want the alias all the time you could workaround this by:

- Checking to see if `./node_modules/.bin/tsc` exists before adding it
- Checking if `$TERM_PROGRAM` = "vscode" before adding it

But I wouldn't want a tsc alias like this, instead I would setup a tsc npm script in the package.json such that running `npm run tsc` will run `tsc`. With an optional `alias t='npm run tsc`'  in my `~/.bashrc`
