### ISSUE TITLE
Webview: apply window.zoomLevel too

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5745]
This is an electron bug: https://github.com/electron/electron/issues/7375

I am running with window.zoomLevel: 1 in VS Code and my markdown preview (https://github.com/bpasero/vscode-markdown) seems to show up with the default zoom level of 0:

![image](https://cloud.githubusercontent.com/assets/900690/14780590/d854e2de-0add-11e6-97e1-8ec698468570.png)

**Comment by bpasero** [comment]
Hm, weird. On the screenshot the zoom level looks ok, but not when I see it running here. It also seems to fix itself once I zoom in and out from the View menu. Might as well be a bug in the webview itself.

**Comment by bpasero** [comment]
I guess this issue is also related where the webview does not take the full width into account because I am zoomed in:

![image](https://cloud.githubusercontent.com/assets/900690/14781475/f90c430a-0ae2-11e6-8d5e-01479ae7dd16.png)

**Comment by jrieken** [comment]
hm... don't even know if I can set that on the web view or web contents...

**Comment by jrieken** [comment]
I have created https://github.com/electron/electron/issues/5312 to track this with electron

**Comment by jrieken** [comment]
It now depends on us updating Electron. @bpasero is that on the plan for July?

**Comment by bpasero** [comment]
@jrieken yes 👍

**Comment by bpasero** [comment]
Should be ok now with Electron 1.2.6.

**Comment by bpasero** [comment]
While the zooming now seems to be applied to the webview, the scrollbar is still behaving weird and shows off:

![image](https://cloud.githubusercontent.com/assets/900690/18508303/eaeb423e-7a73-11e6-91a7-540eb6741ad0.png)

**Comment by jrieken** [comment]
Yeah - the size is now totally wrong...

**Comment by gregvanl** [comment]
This issue also affects in-product Release Notes and I think the plan is for them to be visible by default in the October release. @jrieken @bpasero.  Should we label this issue as important?

**Comment by bpasero** [comment]
@gregvanl well I am not sure how this would help solve the issue, in the end its an electron bug: https://github.com/electron/electron/issues/7375

**Comment by gregvanl** [comment]
@bpasero I see so there's nothing we can do on our side. I just wanted to raise awareness that this will be very visible once we show the release notes automatically on startup in October. 
I was worried this was an accessibility issue for people with poor eyesight who have zoomed their VS Code but all the text is still there. The window is smaller than the editor region but the text isn't clipped.

**Comment by hsutter** [comment]
If it's possible to revert the behavior to the previous bug, which had a workaround, that would be a great improvement:

- Before I updated today, I simply worked around the bug by hitting Ctrl+- then Ctrl+= again (one smaller, one bigger) and the preview fixed itself.

- Now my only workaround is to open two instances of Code just so that I can zoom my editor in one and not zoom the preview in the other. That "works" but is still worse than before because the preview still is not zoomed so it's tiny, but at least it isn't clipped.

So the previous bug was better, if it would be convenient to give us that bug back please...

**Comment by AndrueCope** [comment]
<sarcasm>
Hey, cool! It's worse now! I just updated VS Code (to 1.6.1) and now the Preview window cannot be made to fill the entire window space. On the plus side it sort of fixes the problem because now there's little point using VS code at all. I might as well stick with a bog standard text editor for writing markdown documents.
</sarcasm>

But seriously..this does make VS code less useful to me so I probably won't be using it as much. I might as well edit documents in VS proper.

**Comment by hsutter** [comment]
### *** Workaround for the bug ***

I've found a workaround that's reasonable for me for now -- use `editor.fontSize` in your `settings.json` to avoid having to zoom your editor, and a custom CSS file to set the Markdown body text and code text scaling to avoid having to zoom your Markdown preview. Then you can force both to be the zoom level you want, without the clipping but.

Here's how in two simple steps:

1. In your `settings.json` (accessible via *File > Preferences > User Settings*), put the following:

    ~~~
    {
        "editor.fontSize": 20,
        "markdown.styles": ["d:\\somewhere\\your-markdown-style.css"],
    }
    ~~~

  Change `20` to the value that works best for you.

2. Create the file `d:\somewhere\your-markdown-style.css` with the contents:

    ~~~
    body {
        font-size: 150%;
        line-height: 150%;
    }

    code {
        font-size: 90%;
        line-height: 130%;
    }
    ~~~

  These control the Markdown preview. Tweak the percentages to what works well for you.

HTH.

**Comment by ZodmanPerth** [comment]
Me too!  Ouch, this makes it impossible to work on my commute.

Thanks @hsutter for the workaround, which will keep me working for now.

**Comment by limsim** [comment]
It's a pity this bug is no difficult to fix. Zooming is one of my favourite features of Code especially since it also zooms the text in the side panels as well. It's also important to me because I have different screen setup depending on where i'm working so I modify my zoom level often. Hopefully electron can sort this out soon.

**Comment by buckyster** [comment]
I'm keeping Atom around solely just to edit markdown files :(
