### ISSUE TITLE
Test: JSON completion for package.json and bower.json

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#5753]
Test plan for 'Push hard coded JSON schema support into extensions'

- [x] @joaomoreno 
- [x] @bgashler1 

In package.json, bower.json and project.json we offer completion and hover in the dependency sections.
Until now, that code was located in the JSON extension. I added new supports so that we can move that code to the extensions they belong, so that the corresponding owners can maintain them.
- bower.json & package.json are now in the JavaScript extension
- project.json will be in the omnisharp extension. The pull request with the change has been filed, but omnisharp is currently code frozen and we have to wait until their stream is open again. So for now there's no need to test project.json.

package.json:
1. Open a package.json 
2. in a dependency section ("dependencies", "devDependencies", "peerDependencies", "optionalDependencies") try completions and hovers. Try completing package names as well as versions. Complete in the middle of existing dependencies, or at the end, with a leading quote or without.

bower.json
1. Open a bower.json 
2. in a dependency section ("dependencies", "devDependencies") try completions and hovers. Try completing package names as well as versions. Complete in the middle of existing dependencies, or at the end, with a leading quote or without.

**Comment by bgashler1** [comment]
@aeschli Looks good.

The only thing I would suggest adding is to **automatically insert a comma** at the end of the snippet if you're inserting a dependency in the middle of the list of dependencies.  Since it's changing my cursor, I would expect it to add the necessary comma (otherwise it requires an extra click).

This might not be worth the trouble this close to release, though.  Just a suggestion for later.
