### ISSUE TITLE
[TypeScript] Cancel geterr before any user-invoked operation

### ISSUE THREAD

**Issue by amcasey** [Microsoft/vscode#57542]
i.e. Extend 558635ad1ba6acf4610db1f3e96076d248c5363e from `change` to requests like `completionInfo` and `completionEntryDetails`.

The corresponding TS issue is https://github.com/Microsoft/TypeScript/issues/19458.

**Comment by ahejlsberg** [comment]
FWIW, this issue is really pronounced when you're editing in large files, like `src/compiler/checker.ts` in the TypeScript repro--which I so happen to do a lot! Statement completion will often take as much as five seconds to show up because TSServer is busy computing an error list that will just be discarded anyway.

I'd really appreciate getting this fixed.

**Comment by isidorn** [comment]
Suggestions are shown after 0.5s, I take that as realtivly quickly considering the size of the file -> verified
