### ISSUE TITLE
Allow to close tabs from left to right rather than in order of most recently focused

### ISSUE THREAD

**Issue by jesseduffield** [Microsoft/vscode#57554]
It would be nice if there was a configurable option to close tabs from left to right rather than in order of most recently focused. I've got two notes files I regularly focus, and if I get to a point where I want to effectively wipe the slate clean with my tabs, I want to be able to spam cmd+w until I'm just back to my notes files again. In sublime text this is the default behaviour, but here I'm guaranteed to have closed my notes files if I start spamming cmd+w.

**Comment by SimonEggert** [comment]
I have achieved the wanted behavior by changing the `doCloseEditor`-method in `src\vs\workbench\common\editor\editorGroup.ts` like this:

![feature request](https://user-images.githubusercontent.com/33206628/51247701-3cf12d80-198e-11e9-97b9-bd3e2b066f89.png)

This uses the list of editors in their original order instead of the mru list to figure out the editor that has to be picked as active.

As I am new to the code of this repo, I have not looked into the process of creating a setting for changing the behavior of the above mentioned method. Any help on how to do that would be appreciated. 

If this is a useful feature for anyone else, I would be glad to create a PR for it.

**Comment by jesseduffield** [comment]
please do! This tabs thing bugs me every day haha

**Comment by bpasero** [comment]
Via https://github.com/Microsoft/vscode/pull/66635

**Comment by Somebi** [comment]
So is this feature implemented? How it's called?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_31.md#closing-order-of-editor-tabs
