### ISSUE TITLE
Settings editor ToC doesn't update properly when @modified setting is reset

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#57589]
Issue Type: <b>Bug</b>

Testing #57304

The last step is to left click in the editor below the setting:

![aug-30-2018 11-40-17](https://user-images.githubusercontent.com/9205389/44843896-bab7d500-ac49-11e8-8220-633bed2789f3.gif)

VS Code version: Code - Insiders 1.27.0-insider (051da84e0f85ec291fd2479b665f5c5c2c60ef72, 2018-08-30T07:25:39.746Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron --user-data-dir /Users/chrmarti/Development/repos/tmp/user2 --extensions-dir /Users/chrmarti/Development/repos/tmp/ext2|
|Screen Reader|no|
|VM|22%|

</details>Extensions: none

**Comment by chrmarti** [comment]
Also when trying to change the setting again.

**Comment by roblourens** [comment]
That's the best I can do for August after other changes

**Comment by rzhao271** [comment]
I'm leaving the original issue unfixed/out-of-scope, unless there are more user requests to prevent settings in `@modified` from disappearing until the search query is changed. Currently, the setting is kicked off the list once reset, because after refreshing the tree, it does not match the filter anymore. I also notice there is a significant pause before the setting is kicked off the list, and that's being tracked at https://github.com/microsoft/vscode/issues/109064.

Verification steps:
1. Modify a single setting in the Settings editor
2. Search `@modified` in the Settings editor, or `@modified [query]`, where `[query]` is a query that brings up the single modified setting.
3. Reset the modified setting.
4. Wait two seconds. The setting should disappear, and the Settings editor should show "No Settings Found".

**Comment by connor4312** [comment]
It seems like the refresh is pretty much instant now. I would expect the setting to stick around until I change the query

![](https://memes.peet.io/img/ed0b61d9-e454-42b0-86fe-9cbd72d0bfa6.gif)

**Comment by rzhao271** [comment]
That's the expected behaviour for now.
The setting not staying for longer is being tracked in https://github.com/microsoft/vscode/issues/139886.
Changing issue title to make things clearer.
