### ISSUE TITLE
Breadcrumb picker does not open when typing a non-alphabetical character

### ISSUE THREAD

**Issue by camwar11** [microsoft/vscode#57613]
Issue Type: <b>Bug</b>

1. Enable breadcrumbs
2. Focus the breadcrumbs
3. Type a numerical character (tested with 0-9) or a special character that is valid for a file name (i.e. - or _ )

Actual Result: The find window does not open and start searching for file matches.

Expected result: The find window does open and start searching for file matches (like when an alphabetical character is typed).

VS Code version: Code 1.26.1 (493869ee8e8a846b0855873886fc79d480d342de, 2018-08-16T18:38:57.434Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz (4 x 2793)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (4.37GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by DonkeyKongJr** [comment]
Can confirm the behavior when you start typing numbers, however, special characters (like - or _ or ö) are recognized and the search is executed.

Tested on version 1.27.0

**Comment by jrieken** [comment]
Yes, the problem is that given a key event, we have no clue what visible character that event (or a sequence of multiple events) will generate. Therefore we move focus to the text input box on key*down* so that on key*up*  the input box does its magic. However, we cannot do that for *all* keys, e.g. ctrl or cmd. 

@camwar11 @DonkeyKongJr What I am wondering is how you enter those, e.g ü? Is there a button on your keyboards or via composition '¨ + u' makes ü?

**Comment by DonkeyKongJr** [comment]
@jrieken Yes, I am using a German keyboard. There are dedicated buttons for special characters like ö, ä, ü, ß etc, but they are recognized just fine from the breadcrumb control and the text input is shown.

However, when start typing with numbers nothing really happens. I would expect that it behaves the same as when start typing letters.

I totally agree on special keys like cmd or ctrl since they are used for other shortcuts or system wide, but usually you won't search with them anyways.

**Comment by jrieken** [comment]
> However, when start typing with numbers nothing really happens. I would expect that it behaves the same as when start typing letters.

Yeah, number should be honored

**Comment by jrieken** [comment]
Hm, numbers and hyphen works for me. Must be super keyboard/os specific...

![sep-03-2018 12-44-34](https://user-images.githubusercontent.com/1794099/44982727-22865c80-af77-11e8-9c59-ac3d88dcf1cf.gif)

**Comment by DonkeyKongJr** [comment]
That's interesting. 

Tested it on both macOS (Mojave) and Windows 10 and neither of them worked for me for numbers.

However, what I found out is that on macOS special characters are recognized and on Windows not. So there is definitely a difference on the OS you run.

**Comment by DonkeyKongJr** [comment]
One more interesting thing that I noticed just after updating to 1.27 Release.

When typing the numbers above the letters it gets recognized but when using the dedicated numpad it won't.

**Comment by jrieken** [comment]
With 1.27 this started to work a lot better because we rely on the information the OS gives us. I have tried with my old German keyboard (good old student times) and I can trigger filtering with all kinds of characters like ü, ß, 0-9, !, @, etc. 


> [...] but when using the dedicated numpad it won't.

That also worked for me... Are you sure the numpad was enabled?

**Comment by jrieken** [comment]
Does the num pad work inside the editor and does it work inside the breadcrumbs picker when having started with another character?

**Comment by camwar11** [comment]
Yes to both.

**Comment by jrieken** [comment]
Ok, let try the following

* F1 > Open Keyboard Shortcuts File
* in the lower right, press 'Define Keybinding'
* press one of the keys on the numpad and write down what 'name' it has, e.g. `numpad8`
* Then `F1 > Inspect Key Mappings` and find the name from the step before and share the info

**Comment by camwar11** [comment]
I used key 7, which gave me "numpad7". When I find "Numpad7" in the Inspect Key Mappings page, I get this:
"Numpad7": {
		"vkey": "VK_HOME",
		"value": "",
		"withShift": "",
		"withAltGr": "",
		"withShiftAltGr": ""
	},

**Comment by jrieken** [comment]
Ok, now we have something... Our keyboard logic here things the value being produced is `""` (the empty string) and therefore we ignore that key event.What surprises me is that pressing it inside the editor or an input box prints/renders something...

**Comment by jrieken** [comment]
this is now using the default tree filter/find logic
