### ISSUE TITLE
I want report a bug.

### ISSUE THREAD

**Issue by COCO5666** [Microsoft/vscode#57649]
This bug appeared when I was writing Python code. There is no problem with the code I write, but VScode suggests a problem. As shown in the following picture. You can email me if you need to.(zj175@139.com)

![image](https://user-images.githubusercontent.com/36597804/44885558-13dc4300-acf4-11e8-997c-bad1a8d0951f.png)
![image](https://user-images.githubusercontent.com/36597804/44885574-235b8c00-acf4-11e8-97cb-41727e600dcd.png)

**Comment by AlexLandau** [comment]
This is coming from a plugin, not VS Code itself. I'd recommend:

1. Figuring out how to run Pylint from the command line, and see if it produces the same error.
2. If Pylint produces the same error when run directly, submit a bug report to the Pylint project.
3. Otherwise, find the plugin that adds Pylint support to VS Code and submit a bug report to that plugin.

**Comment by COCO5666** [comment]
This is a test code

[test.zip](https://github.com/Microsoft/vscode/files/2338389/test.zip)
![image](https://user-images.githubusercontent.com/36597804/44886886-b9df7b80-acfb-11e8-9fdc-fae4fac645a5.png)

**Comment by dbaeumer** [comment]
@COCO5666 as @AlexLandau pointed out this feature is provided by an extension so you need to file the report against the extension. You can find out the extension you have installed using the Extension viewlet.
