### ISSUE TITLE
Can't debug anymore after launching fails

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#57726]
- Have a node debug config with  `"program": "${file}"`
- Close all open tabs
- Start the debug config
- Error notification pops up, "`${file}` can't be resolved..."
- Open a file
- Try to start the debug config again, nothing happens. I can't debug until I reload the window

---

The progress bar in the debug viewlet runs forever after the error. I can stop it with Shift+F5 but debugging still doesn't work after that.

**Comment by roblourens** [comment]
Candidate?

**Comment by weinand** [comment]
git bisect showed that this bug was introduced by @isidorn in commit ["debug: fix initializing"](https://github.com/Microsoft/vscode/commit/1cd754493fe8b90c237a93759fe2ef43c368d088).

If I understand the purpose of that commit correctly, the "Initialized" state is now used to make the progress indicator active while a debug session is started.
This functionality was probably lost when [refactoring the DebugSession](https://github.com/Microsoft/vscode/commit/758be52acf26b54ec70fa31ee6c4eb4d89835670).

But the commit fails to reset the state if an error occurs that prevents the debug session from starting.

The low-risk fix is to reset the state on error and to propagate the error.
