### ISSUE TITLE
Find "all" references in a document

### ISSUE THREAD

**Issue by michaelsogos** [Microsoft/vscode#57743]
Dear,

Would be great if, using simple finder for a single document ```ctrl+f```, is possible to list all references in a separated window. Maybe in a specific panel of "OUTPUT" window.

**Comment by dbaeumer** [comment]
Two options:

- put the cursor onto the word that you want to see the references for. This will highlight all reference in the document with indication in the scroll bar.
- use find all references which opens a inline view with the found references.

I will close the issue since the feature exists. Please ping if I misunderstood you.

**Comment by michaelsogos** [comment]
Dear @dbaeumer ,

thanks, "find all references" work like a charm.

It is like "peek definition" on VS2017, i didn't know was there this "possibility". ;)
