### ISSUE TITLE
Checking out new branchs

### ISSUE THREAD

**Issue by shohambs** [Microsoft/vscode#57793]
Hi,
Currently, any branch created after VSCode started running isn't visible at checkout.
Even after "git fetch", it requires to reload VSCode to see that new branch. 
I believe it would be nice that a git fetch alone could load the new branches into the checkout list.

VSCode Version: 1.26.1
OS Version: Windows 10 Enterprise 

Steps to reproduce:

1. Create a new branch
2. Run "git fetch"
3. Press checkout at the bottom left (on the branch name)
4. Look for the new branch

Reproducible without extensions: 
Yes

Current Behavior:
The new branch is not showing until a window reload

Requested Behavior:
The branch will be visible

**Comment by joaomoreno** [comment]
Please do not ignore our issue template:

---

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.


Does this issue occur when all extensions are disabled?: Yes/No

**Comment by shohambs** [comment]
@joaomoreno Fixed

**Comment by joaomoreno** [comment]
VS Code is using different file watching strategies depending on your OS and your setup. 

**First thing to check:**
* [ ] I verified that the issue still reproduces in our insiders version (https://code.visualstudio.com/insiders/)
* [ ] I verified that this issue is happening outside of a `node_modules` folder. Our file watcher ignores this folder!

**To find out more about this issue, please first answer this:**
* [ ] Does this happen from an empty workspace, a single-folder workspace or a multi-root workspace?
* [ ] Do you have `files.useExperimentalFileWatcher: true` configured in settings?
* [ ] What is your configured `files.watcherExclude` setting?

**Then please answer the following depending on your setup:**
* [ ] It reproduces with any folder or workspace you open
* [ ] The files/folders you open are on your local disk and not on a network share nor a UNC drive
* [ ] The files/folders you open are not behind a symbolic link
* [ ] The folder(s) opened use the exact same casing as they are on disk
* [ ] It reproduces when I make a change to the file from another VS Code window (either from the editor or the file explorer)

**Then please attach the output of our development console**
* run `code --verbose` from the command line
* perform the action that causes you to not see the file change in VS Code
* attach the output from the console (`Help` > `Toggle Developer Tools` > `Console`)

Thanks for taking the time to fill out this questionnaire.
