### ISSUE TITLE
Debt - remove WinJS.Promise#timeout usage

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#57866]
We have a winjs promise removal plan #53526 and nuking `timeout` is part of this effort. The following are alternatives

* [`async.ts#timeout`](https://github.com/Microsoft/vscode/blob/e2c151064eb935933c0bccae8fc3eaf0b8f54f4e/src/vs/base/common/async.ts#L364) for a promise that can be cancelled and chained
* [`setTimeout`](
http://mdn.beonex.com/en/DOM/window.setTimeout.html) for a simple timeout
* [`TimeoutTimer`](https://github.com/Microsoft/vscode/blob/e2c151064eb935933c0bccae8fc3eaf0b8f54f4e/src/vs/base/common/async.ts#L589) or various other utilities in the `async.ts` module

**Comment by bpasero** [comment]
@jrieken is there a utility for a timeout with a `WinJS.TPromise`? I cannot just use `async.ts#timeout` without adopting `Thenable` or `Promise` in all the layers. That is something I would only do when we do the move to native Promises.

**Comment by bpasero** [comment]
...actually there might be only one case in my land to check, others seem fine as long as the timeout is being used within a chained WinJS promise.

**Comment by jrieken** [comment]
Yeah, and you can always go back into the old world via `WinJS.Promise#wrap`

**Comment by joaomoreno** [comment]
@jrieken I've removed all usages of `TPromise.timeout`; replaced them mostly with `TPromise.wrap`.

I know you wanted to avoid it, but I've added a `cancelableThen` method which provides a way to wire cancellable promises:

https://github.com/Microsoft/vscode/blob/c3aebef8369be67b371181ba2931fed367cd2ad1/src/vs/base/common/async.ts#L29

Can't remove the method declaration itself since it would break `monaco.d.ts`. I'll leave that to you.

PS: I'm going insane with single or double `l` in `cancellation`; we now have both versions in our code: `CancellationToken`, but `CancelablePromise`. :confused:

**Comment by jrieken** [comment]
@joaomoreno well, now you own the cancelable promise ;-). you should know that this is just a stepping stone to make the transition smoother. in mid term you shouldn't keep the weird cancel-causes an error behaviour that we currently have.
