### ISSUE TITLE
Git: Make autofetch period customizable

### ISSUE THREAD

**Issue by sachabrants** [Microsoft/vscode#57910]
Hi

I would love to customize `git.autofetch`'s period in the settings instead of hardcoding three minutes:

https://github.com/Microsoft/vscode/blob/cd7c7c5fa2c16c6e8281436c35e9a7709cfbd89d/extensions/git/src/autofetch.ts#L22

Thanks!

**Comment by sachabrants** [comment]
Sorry for requesting a solution without stating my problem. I have 12 repositories in my workspace, all hosted on the same VSTS project, using SSH for authentication. The git server started to randomly drop my git commands with the following message:

    > git pull -v

```
ssh_exchange_identification: read: Connection reset by peer
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Just waiting a bit a retrying the command would work, so I suspected that too many connections were attempted on the server. After stopping autofetch entirely the issues disappeared.

Hence my request to customize the period of fetch, but there might be another solution to the issue. Maybe not fetching them all at the same time (wait a few seconds in between each repos in the workspace?).

**Comment by skprabhanjan** [comment]
Hello @joaomoreno ,
I am looking to start contributing and would like to start off with this issue.
I have successfully built and run the application locally, can you please help me understand this more?
Thanks.

**Comment by joaomoreno** [comment]
The first comment in this issue is a pretty good pointer to get started.

**Comment by guywald1** [comment]
@joaomoreno I had a PR ready to fix this but saw that it's your first issue and you want to tackle this so giving you dibbs :) If you moved on tell me and I'll submit the PR, otherwise happy to help if you need anything! Started contributing to vscode not too long ago as well.

**Comment by guywald1** [comment]
@skprabhanjan I had a PR ready to close this but saw that it's your first issue and you want to tackle this so giving you dibbs :) If you moved on tell me and I'll submit the PR, otherwise happy to help if you need anything! Started contributing to vscode not too long ago as well.

**Comment by skprabhanjan** [comment]
Hey @guywald1 , really appreciate your gesture :)
I indeed need some help to get started, I just went through the source code and I am not entirely sure how to create a setting , but I figured out one place where I could configure the auto fetch period.

In the file extensions/git/package.json, should we add a new configuration similar to this?
 "git.detectSubmodulesLimit": {
          "type": "number",
          "default": 10,
          "description": "%config.detectSubmodulesLimit%"
 }
and then use that in vscode/extensions/git/src/autofetch.ts (Somewhat similar to https://github.com/Microsoft/vscode/pull/47790/files)

This was the approach that I was able to come up with, can you please let me know if this is the rite approach and should I go ahead and implement this ?
If this is not the correct approach can you help me go in the rite direction?
Thanks :)

**Comment by guywald1** [comment]
Hey @skprabhanjan, that is indeed the right direction :)
The built-in Git extension, for which we want to add an additional configuration, as I understand follows guidelines similar to external extensions, primarily [contributes.configuration](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration) which defines the configuration for the extension. The description (the one surrounded by `%`) will have to be edited elsewhere.

Then, where you want your new setting to be used, you would need to pull it from the configuration and use it instead of the static property used currently.
Would also advise somehow making sure that the period isn't 0 or negative (alerting the user of bad input, using `Math.max` etc.), haven't checked yet what the best practices are for validating input.

**Comment by skprabhanjan** [comment]
Hey @guywald1 , Thanks a lot for the help :)
I shall go ahead and implement the same taking into account the validation of input.

**Comment by skprabhanjan** [comment]
Hey @joaomoreno and @guywald1 , I have added the setting,used that instead of static value and also handled input validation.
Before sending a PR I wanted to be clear on what the default value of this auto fetch period be?
Currently I have kept 180000(3 minutes) as default value (as it was used before).
Can you please let me know if this is fine ?
![image](https://user-images.githubusercontent.com/17094832/45440071-fb4b3000-b6d8-11e8-8d8c-a1da2a38d5fd.png)


Thanks:)

**Comment by guywald1** [comment]
@skprabhanjan Good progress :)
IMO you should have the user set the amount of seconds (not ms), so the default would be 180. If doing so, make sure you convert to ms in the code using the setting.

**Comment by skprabhanjan** [comment]
@guywald1 , I will change it accordingly and then send a PR?
Thanks :)

**Comment by guywald1** [comment]
Heh for the record, I’m not a maintainer or anything, just trying to help :)
But absolutely, submit a PR when you’re ready. Worst case - you’ll get some comments and make a few changes :)

**Comment by skprabhanjan** [comment]
Okay sure, thanks for all the help:)
