### ISSUE TITLE
excess padding on problem items when docked vertically

### ISSUE THREAD

**Issue by zspitzer** [Microsoft/vscode#57950]
There is 32px of left-padding on each problem which takes up valuable space when the problems panel is docked vertically.

Would it be possible to remove this padding so more actual content is visible when the problems panel is narrower?

**Comment by sandy081** [comment]
There are two space separations

1. Alignment of children (which is 32px padding) in the tree
2. Space for light bulb for quick fixes

I do not think removing the children alignment in the tree is correct. We use the same in File explorer and Search trees.

We can think of moving the light bulb to the right. Reason why light bulb is on the left in horizontal panel because of better visibility. But I am worried this might cause inconsistencies

@misolori Any opinions?

**Comment by misolori** [comment]
@sandy081 do you think we'd be able to shift the light bulb to the left of the tree icon? That would be a better use of space:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/45198955-45866a00-b21e-11e8-8bd3-806bf8a2a357.png">

I'd worry that moving it to the right would make it hard to find and be undiscoverable.

**Comment by sandy081** [comment]
@misolori Moving to the left can be tried.

**Comment by sandy081** [comment]
@misolori Shifting to the left of the twisty might not be a good idea it can break the children alignment. Other option is to have a tree gutter area which needs to go into tree. I am afraid we can implement tree gutter for this requirement. Other option is to go back to my initial idea of overlaying light bulb on the error icon

![image](https://user-images.githubusercontent.com/10746682/42762255-1ed868ae-8910-11e8-8228-71af43d203a6.png)

**Comment by misolori** [comment]
I still think the combo icon is hard to recognize, especially at a small size.

Would it be worth exploring to swap out the error icon for the lightbulb?

**Comment by sandy081** [comment]
Can be tried

**Comment by sandy081** [comment]
![kapture 2018-12-18 at 18 30 11](https://user-images.githubusercontent.com/10746682/50171541-ffe43d80-02f2-11e9-8beb-9a082b7f1457.gif)
