### ISSUE TITLE
`Configuration setting value is default` warning Setting

### ISSUE THREAD

**Issue by ashrafhadden** [microsoft/vscode#57975]
Following the phrasing of the similar warning `⚠️ Unknown Configuration Setting (120,3)`, it would be great if we had a default user setting like so...

`⚠️ Configuration setting value is default (120,4)`
```jsonc
// defaultSettings.json

// Enables warning when configuration setting key has a value that is exactly equal to its default value
"typescript.settingValueIsDefaultWarning": false,
```

This would help minimalist users like myself looking to eliminate unnecessary code from my `settings.json` and keep things spruce and tidy.

**Comment by roblourens** [comment]
A couple cases where configuring a setting to the default is valid:

- In a workspace/folder scope, to override a different value in the user scope
- To protect against possible future changes of the default value

Also none of this is possible in the new settings UI, since changing a setting to the default value removes it from the settings.json file.

**Comment by ashrafhadden** [comment]
@roblourens Thanks for the quick response! That's great news that the new settings GUI basically has this feature already built-in. I meant for this setting to be turned off by default (I just edited my post), as I'm aware that configuring settings to their defaults has practical value and that most people would not want the warning. Thus it would only be a small little opt-in feature for those who desired it and still preferred editing the raw `settings.json`.
