### ISSUE TITLE
Cancelling a search doesn't work when the search started before the searchProcess started

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#58016]
- Disable extensions
- Ensure `"searchRipgrep.enable": false`
- Open the process viewer and check that the searchProcess hasn't started
- Start a text search and immediately cancel it with <esc>
  - This will be easiest to see if the search will run for a long time. Open a large folder and search for a string that won't appear very often so it doesn't hit the 10k limit.
- See that the search is canceled in the UI but the rg process keeps running

Then try this again when the searchProcess is already running, and see that `rg` is actually killed.

This has something to do with this function: https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/ipc/node/ipc.ts#L619

I think the Relay isn't disposed, so the source listener isn't disposed, and search relies on the event listener to be disposed when search is canceled, here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/search/node/rawSearchService.ts#L46

I can change this to use a cancellation token if that's better?

**Comment by joaomoreno** [comment]
Absolutely great catch and analysis, you are 100% correct. This is a bug on the Relay which should also handle `onFirstListenerDidAdd` and `onLastListenerRemove` calls, in order to provide detach scenarios. Pushed fix!

PS: Found out about `htop -d 1`, super fast refresh rate.
PPS: While researching this, I found another issue: https://github.com/Microsoft/vscode/issues/58057
