### ISSUE TITLE
dependent extension enablement issue

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#58065]
The built-in "Node Debug (legacy)" extension depends on "Node Debug".

- try to disable "Node Debug"

Observe: expected error occurs. This is OK.

- disable "Node Debug (legacy)"
- disable "Node Debug"
- enable "Node Debug (legacy)"

Observe: legacy can be enabled even if its dependency is disabled.

**Comment by alexr00** [comment]
@sandy081, the behavior here seems a little odd:

- Try to disable "Node Debug" but nothing happens, presumably because it has a dependency
- Try to disable "Node Debug (legacy)" and it works
- Then, also disable "Node Debug" and now it works, presumably because the dependency is gone
- Finally, try to enable "Node Debug (legacy)" and it works?! and also automatically enabled "Node Debug"

To be consistent, if it is possible to enable "Node Debug (legacy)" when "Node Debug" is disabled and automatically enable "Node Debug" then it should also be possible to disable "Node Debug" and have "Node Debug (legacy)" also be automatically disabled.
