### ISSUE TITLE
Typescript fails to report unreachable code error

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#58075]
While reviewing https://github.com/Microsoft/vscode/pull/57955 I saw this in `requestService.ts`:

<img width="562" alt="screen shot 2018-09-06 at 16 07 00" src="https://user-images.githubusercontent.com/22350/45162732-faa12e00-b1ee-11e8-8fb5-ddd765ab376c.png">

It took me way too long to find that unreachable code. Where's the squiggle?

**Comment by mjbvz** [comment]
Here's what it looks like in the latest insiders:

![screen shot 2018-09-07 at 2 45 04 pm](https://user-images.githubusercontent.com/12821956/45244433-a492c000-b2ac-11e8-8d2a-51a4f4bea587.png)

No squigglies from TS because we do not set `"allowUnreachableCode": false,`, therefore it's only a suggestion

**Comment by joaomoreno** [comment]
@mjbvz Should we set it? This was triggering a bug, and it took me way too long to figure out this was the reason. A squiggly would have solved it instantly.
