### ISSUE TITLE
SECURITY ISSUE: I can publish extensions as other user?

### ISSUE THREAD

**Issue by GabrielBB** [Microsoft/vscode#58134]
Hi, if i use "publisher" instead of my publisher name ("GabrielBB") when publishing extensions it says i'm logged in as this guy: @MarxJiao. It doesn't matter if the token was mine, it says i'm him.

Here an image:

![Logged in as [MarxJiao](https://github.com/MarxJiao)](https://user-images.githubusercontent.com/8752823/45192206-01db3280-b215-11e8-9316-b188e2a367cf.PNG)

Try it 🐙

**Comment by mjbvz** [comment]
Have you tried performing any operations as this user? I think that vsce lets you "login" as them but once I actually try making requests as them, I get 401s

**Comment by samueldaviddelacruz** [comment]
it is still a leak of private information even if you can't do operations on it.

**Comment by pkuma-msft** [comment]
Hi @GabrielBB, thank you for taking time to report this.

'vsce login <publishername> <PAT>' is sort of a misnomer in the sense that it is not really logging you in, it is just validating whether the PAT you specified is valid or not. vsce does this by invoking marketplace's get publisher api - which is an authenticated API - no permission checks are done here, you just need to be signed-in to invoke this api.
HTTP GET https://marketplace.visualstudio.com/_apis/gallery/publishers/<publishername>

If vsce gets a positive response for the above api call, it assumes that it belongs to the publisher and displays a message that says 'you are logged in as <publishername>'

There is no leak of private information here since the publisher names and publisher internal names are already available publicly on https://marketplace.visualstudio.com

As @mjbvz pointed out, any subsequent operations you try to perform, like upload an extension, would fail since the permission checks would fail.

**Comment by joaomoreno** [comment]
@pkuma-msft Can you recommend an API call VSCE could make?

**Comment by joaomoreno** [comment]
This issue was moved to Microsoft/vscode-vsce#289
