### ISSUE TITLE
Blurry text in menu and codeview

### ISSUE THREAD

**Issue by satzspiegel** [microsoft/vscode#58157]
Manchmal ist der Text im Menü verschwommen. Mit der Maus über den verschwommenen Text fahren hilft manchmal. 

Text im Code ist auch verschwommen. Alles unregelmäßig.

https://picload.org/view/dlipwlwi/unbenannt.png.html

**Comment by bpasero** [comment]
This sounds a lot like https://github.com/Microsoft/vscode/issues/51789

We are building exploration builds that use a much newer version of Electron (our UI framework). I wonder if this issue reproduces with one of these builds, could you try? Download:
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-win32-x64-1.28.0-exploration.zip)
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/883208e30da25777874a8ade5f90e1fea638a298/code-exploration-1535724826.tar.gz)

**Comment by PlyPikachu** [comment]
Hi @bpasero,

I download and test this morning your package for Windows and the issue still presents as you can see : 
![image](https://user-images.githubusercontent.com/8748440/45281699-e142ff00-b4d8-11e8-959b-f9c50d0f7011.png)

Thanks for your help!

Best Regards,

**Comment by bpasero** [comment]
Too bad, does it help if you run `code --disable-gpu`?

**Comment by PlyPikachu** [comment]
It works with the option --disable-gpu if I run code.exe from a command line in Windows with the version 1.28.

I uninstalled 1.27.1 to install 1.25 which works well this morning without any change.

Thanks for your help!

Kind Regards,

**Comment by LoveSponge** [comment]
I'm experiencing this issue with Antergos Linux (arch) (Gnome 3.28.2 desktop) with 1080p external monitor && no scaling

Running @bpasero 1.28 had no difference (maybe even a little worse?) then running with --disable-gpu seemed _better_, but unfortunately not perfect.

I have scoured google for this one and seen issues going as far back as 2016. 
Is there any other hacky quick fix i could try to omit this issue?
Happy to try anything

Thanks in advance

P.S, otherwise great job on this project, Love VS code. <3

**Comment by tpxxx** [comment]
Had the same issues on Windows 10, VS Code 1.73.1 .  Disabling FXAA antialiasing in the NVIDIA driver solved this for me
