### ISSUE TITLE
Collecting Feedback for Extensibility Documentation

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#58226]
As some of you might have noticed in the freshly baked [September Iteration Plan](https://github.com/Microsoft/vscode/issues/58224), one of our focus this month is extensibility documentation. Which comprise of:

- The "Extension Authoring" and "Extensibility Reference" sections on our doc page: https://code.visualstudio.com/docs
- https://github.com/Microsoft/vscode-extension-samples

Some of the issues we are already aware of:

- API Reference is hard to use: https://code.visualstudio.com/docs/extensionAPI/vscode-api.
- Some topics (for example, Proposed API) have information scattered throughout [release notes](https://code.visualstudio.com/updates/v1_27#_proposed-extension-apis), [wiki](https://github.com/Microsoft/vscode/wiki/Extension-API-process#about-proposed-api) and [GitHub issues](https://github.com/Microsoft/vscode/issues/33358).
- The API sections on the [website](https://code.visualstudio.com/docs) could improve its organization to have better topic categories & depth progression.

We'll try to address those issues. But we also want to hear from you, the extension authors.

While you are trying to write VS Code extensions, which doc page is hard to understand? What are the issues you run into? On what topic were you unable to find useful information? How can we make the process more enjoyable for you?

**Comment by nathfreder** [comment]
It would be great to have code examples!

**Comment by octref** [comment]
@nathfreder We do have samples: https://github.com/Microsoft/vscode-extension-samples. Did you have trouble finding that repo?

**Comment by fabiospampinato** [comment]
> Some topics (for example, Proposed API) have information scattered throughout release notes, wiki and GitHub issues.

Fixing this would probably be one of the biggest improvements for me. 

Some suggestions:

- Too much stuff is undocumented:
  - I think there's still no documentation on the `$(icon)` thing for inserting icons https://github.com/Microsoft/vscode-docs/issues/1094. What icons are supported? Where can someone use this syntax? I don't think this is documented.
  - Today I've learned one can write `$(icon~spin)` to have a rotating icon.
  - The syntax supported in `when` clauses is also undocumented I think, one has to go through the code to actually understand how that works. I recently learned that regexes are supported there.
  - I didn't know that the extension's settings are using JSON Schema, I don't think this is mentioned anywhere in the docs either.
- The following nav bar is kind of useless, for ~95% of the page we are always in the "workbench" section, maybe sub sections should be implemented.

<img width="160" alt="screen shot 2018-09-08 at 00 18 03" src="https://user-images.githubusercontent.com/1812093/45246123-e26d0400-b2ff-11e8-8f82-38df3812ab86.png">

- Maybe if there was a button or something for expanding all those collapsible sections the whole page would become more searchable.

**Comment by aaronbushnell** [comment]
Apologies if this isn’t in scope since it’s not an “extension”, but I’d love a better way to see what part of the Code UI corresponds to a workbench color customization. I like tinkering around with different color changes but often find it difficult to see which element is which.

**Comment by octref** [comment]
@fabiospampinato I agree with most of what you said. Just to make sure, the one on `when` clauses is about the `when` for keybindings, is that correct?

**Comment by lannonbr** [comment]
@octref So I am wanting documentation on examples for Unit Tests for extensions and it has already been issued on Microsoft/vscode-extension-samples#91 and I personally would be willing to write up an example here on how to do such.

**Comment by eamodio** [comment]
`when` for keybindings and menus/commands

**Comment by fabiospampinato** [comment]
@octref keybindings, commands, views, all of them, the syntax is just undocumented. At first I thought it was just some `eval`-ed javascript, but it's not.

**Comment by qcz** [comment]
@octref: It would be great if the limitations of extensibility were documented. For example files larger than a given size are not synced to the extension host, but the extension only sees that `window.activeTextEditor` is undefined. I found out this the hard way, as my extension, which was created to filter information from larger log files was not working when big files were opened, but I only saw that `activeTextEditor` is undefined.

The [VS Code API docs](https://code.visualstudio.com/docs/extensionAPI/vscode-api) does not state in which circumstances `activeTextEditor` may be undefined. Obviously it is undefined when there are no editors open, but as it turns out it is also undefined when the file is not synced to the extension host.

I had to find out this when searching for related issues, and found #3147, which contains some information, however it is not even up to date.

**Comment by octref** [comment]
@qcz That makes sense. One of my original motivation was to extract scattered information on GitHub into a central place that's searchable and more well-organized.

@YurkaninRyan Thanks for the feedback. We can certainly look into making the sample code easier to understand.

**Comment by nealot** [comment]
I would really like a glossary of all the terms used by developers to describe the components. When someone wants to create an extension, they need to understand what the editor is capable of and how these capabilities are labeled. Acquiring -- and subsequently retaining -- this information is made increasingly difficult with each additional feature. Extension developers periodically need to append new words to their already large repertoire of definitions without any sort of direct reference. Frequently, I believe, someone will also have an idea for an extension, but their limited vocabulary will prohibit them from progressing to a point where the extension is functional.

Throughout discussions, I've seen these words and others used ambigously or interchangeably:
- widget
- window
- peek
- preview/webview
- panel
- view
- explorer
- sidebar
- quick open
- editor
- menu
- viewlet

Here's a list from https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus detailing contribution points for menus:

> The global Command Palette - commandPalette
The Explorer context menu - explorer/context
The editor context menu - editor/context
The editor title menu bar - editor/title
The editor title context menu - editor/title/context
The debug callstack view context menu - debug/callstack/context
The SCM title menu - scm/title
SCM resource groups menus - scm/resourceGroup/context
SCM resources menus - scm/resource/context
SCM change title menus - scm/change/title
The View title menu - view/title
The View item menu - view/item/context

The above may seem quite intuitive for experienced vscode developers, but what about the perspective of a newbie trying to create his/her first extension?

An aggregation of terminology used throughout the community and their associated meanings would make the extension ecosystem much more friendly. Even better would be the usage of screenshots or other visual objects to enhance the definitions.

**Comment by MicrosoftEurope** [comment]
+1

**Comment by gkalpak** [comment]
I only have limited extension authoring experience, but here are some pain points I ran into:

- **Testing** - Although the testing story is pretty good (all things considered), there are some easy wins to be had imo:
  - Docs on writing tests with [Jasminej](https://jasmine.github.io/) (some people like it :wink:). The fix is quite straight forward when you know it, but I had a hard time finding out [what it takes](https://github.com/gkalpak/aio-docs-utils/blob/6cacf12934e7af0c6af92e554451eff47a3816e5/src/test/helpers/jasmine-runner.ts#L53-L70) to succeed.
  - Docs/samples on unit vs e2e/integration tests (see also https://github.com/Microsoft/vscode-extension-samples/issues/91#issuecomment-419809844).
  - Better support for running tests against multiple versions (see also Microsoft/vscode-extension-vscode#96).

- **CI Automation**
  - It could have saved me quite some time, if there were better docs on how to automate tasks like releasing and publishing on CI.
  - Here is [the setup I ended up with](https://github.com/gkalpak/aio-docs-utils/blob/6cacf12934e7af0c6af92e554451eff47a3816e5/.travis.yml#L35-L55), so that I can trigger publishing a new version with just `npm version <patch|minor|major>` (plus some [git pushing](https://github.com/gkalpak/aio-docs-utils/blob/6cacf12934e7af0c6af92e554451eff47a3816e5/package.json#L31). (Shout out to VSCoceVim/Vim, where most of this is taken from :heart:)

##
BTW, I interestingly didn't have a hard time following or finding something in the API docs (as others have mentioned), but that could be because I have only used few APIs.

In any case, the overall experience of authoring and publishing an extension was pretty enjoyable :100:

**Comment by octref** [comment]
@nealot I feel your pain. That was an issue when I was trying to learn VS Code too. I don't think the issue only applies to extensibility doc though — a clear description & illustration of VS Code UI would help regular users getting onboard with the editor too. I opened https://github.com/Microsoft/vscode-docs/issues/1842.

@gkalpak 

> unit vs e2e test

When I was writing the docs for Language Server I made this distinction: https://code.visualstudio.com/docs/extensions/example-language-server#_testing-the-language-server, but I guess in the general [Testing page](https://code.visualstudio.com/docs/extensions/testing-extensions) section could have some doc for that too.

> CI

Did you have a look this page? https://code.visualstudio.com/docs/extensions/testing-extensions

**Comment by eamodio** [comment]
Another big one is documenting menu/command callbacks -- Each context a menu/command is executed from (https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus) returns a different set of arguments. For some extra context: https://github.com/Microsoft/vscode/issues/25716 and https://github.com/Microsoft/vscode/issues/34048.

I honestly find dealing with commands the most challenging part of the vscode api.

**Comment by gkalpak** [comment]
> When I was writing the docs for Language Server I made this distinction: https://code.visualstudio.com/docs/extensions/example-language-server#_testing-the-language-server, but I guess in the general Testing page section could have some doc for that too.

@octref 👍 

> Did you have a look this page? https://code.visualstudio.com/docs/extensions/testing-extensions

Yes :grin:
It's a good start, but it could be enhanced. Basically, (as mentioned above) I was looking for a recipe to [get me there][1] (or at least some more hints), because I think this is something that makes sense for every extension that uses CI anyway.
<sub>(Disclaimer: I might be biased towards over-automating 😛)</sub>

[1]: https://github.com/gkalpak/aio-docs-utils/blob/6cacf12934e7af0c6af92e554451eff47a3816e5/.travis.yml#L35-L55

**Comment by octref** [comment]
@eamodio From what I read in that issue, if you are using the same command for multiple contexts you should prepare for different arguments. You can always register different commands for different contexts, can't you?
Although I agree with the point that it's unclear what are the arguments being passed in to the command for each context. This can be addressed with better docs.

**Comment by KamasamaK** [comment]
[Complex Command](https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands) should provide clearly formatted, linked types for the parameters and returns as in the "vscode namespace API" doc.

**Comment by octref** [comment]
@KamasamaK I agree. Many people feel the name "complex command" is confusing too.

**Comment by eamodio** [comment]
@octref yeah, I could have different commands for each context (and I might start doing that). But I avoided that because that causes SO much duplication in the package.json. For something like GitLens which has lots of commands, it now multiplies them by the number of contexts (which is many and growing). And it requires that I keep them in sync (typo's, renames, etc). And it can be confusing to a user, because now which command do they bind a keyboard shortcut to because there are not 5 versions of many commands.

It gets nuts fast once you move past a small number of commands.

**Comment by YurkaninRyan** [comment]
@octref I actually pulled it down and fiddled with it and eventually figured it out!

I was going there to try and understand how to create the multi step input.  I thought the whole repo was just doing that usecase, but in actuality, it was a few different examples that could be selected from a dropdown, and one of those examples was the multi step input.

I had problems figuring out:
1. What was the entry point that I should be paying attention to.
2. Why am I doing anything like creating a helper multistep input class.
3. What are extra features that arent involved in the "hello world" of creating a multi step input.  For example that example implements a "shouldResume" flag, which I think complicates the code a lot. There's a lot of different apis there to digest all at once.

If there was any commenting or direction pointing it would of helped a lot.  I had similar struggles in most of the examples.  I wasn't sure what to look at, or why I was looking at it.

**Comment by heatherlp** [comment]
As you've already come across, the complex commands page needs improvement. 
- not all commands listed on that page explain the return value
- Are the commands listed on that page a full list of those supported with executeCommand? I've seen setContext used, and that's not listed on that page. 

My biggest pain point in extension development has been surrounding the fact that on opening a folder in the current window, the current extension host process is shutdown, and so you have to activate the extension on the new window/folder in order to access it (i.e. to call createTerminal). I'd appreciate some further documentation surrounding how vscode handles folders, workspaces etc, for extensions that want to create, open and close folders.

**Comment by visualzoran** [comment]
I agree with previous posts about "where" for menus/commands. It was the biggest problem for me when I was creating some extensions in the past. 
But I would also like to see more documentation about exposing public API from extensions. I've been creating multi-file template engine extension that allows to visually select templates and allows to run additional wizards, specific to selected template. I only wanted to implement core engine and UI in the main extension and then allow dependant extensions to use API to register new templates and wizards. The only information I was able to find was a short note in vscode-api document that "activate" method can return public API. I've managed to do what I wanted, but it would be nice to have some sort of example and suggested list of tasks that should be done by a developer creating extension of that type. Something like:
 1. That's how you can return API from your extension - and very simple example here
 2. You have to publish your public APIs to other developers. It might be a good idea to do it by creating and publishing npm module - and maybe an example or link to sample module with API exposed in step above?
Maybe we just need to add another example to the list of your sample extensions?

**Comment by octref** [comment]
@visualzoran Thanks — extension can expose its own API is something that even I didn't know it existed. I'll include it as a topic in the new extensibility doc.

**Comment by KamasamaK** [comment]
I too just recently learned about extensions exposing public APIs by seeing the [git extension](https://github.com/Microsoft/vscode/tree/master/extensions/git/src/api) do it, and would be interested in learning more.

**Comment by octref** [comment]
Thanks a lot for all your valuable feedback! We have created an internal plan to address most of the issues. In the next one or two iterations, we'll do the minimal work possible to publish the new extension authoring doc. After publishing the new docs, we'll write new topics, edit old ones and make improvements to pages such as the [API reference](https://vscode-ext-docs.azurewebsites.net/docs/extensionAPI/vscode-api).

**Comment by Almenon** [comment]
Generally speaking the more documentation, the better.  The webview documentation was great and it would be nice to see stuff like that for other parts of the API.  For example, there are no guides on how to add telemetry to your extension. so I wrote my own: [adding telemetry with azure](https://medium.com/p/f3d52d2e573c?source=user_profile---------6------------------) and [setting up email alerts](https://medium.com/p/d755651b2e0d?source=user_profile---------3------------------). Because of the outstanding bug with the innacurate download counts telemetry is important to see how many users you have.

@lannonbr also wrote some good guides on [decorations](https://vscode.rocks/decorations/) and [unit testing](https://vscode.rocks/testing/).

**Comment by KamasamaK** [comment]
One other thing I forgot to mention and haven't seen anyone else mention is that the API and complex command references are lacking an indication of what version the item was added at.

**Comment by busticated** [comment]
minor but helpful things:

* make the property / method names easily copy+paste-able (ex. `createOutputChannel` [here](https://code.visualstudio.com/docs/extensionAPI/vscode-api#window.createOutputChannel))
* in each property / method section, include the full parent reference so i don't need to scroll around to find it - e.g. `window.createOutputChannel()`

🙏

**Comment by busticated** [comment]
another one: the docs for the `configuration` contribution point make no mention of the `scope` field - yet we are warned about setting it / not setting it under certain circumstances. what does `scope` do?

docs:
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration

example:
https://github.com/Microsoft/vscode-extension-samples/blob/master/configuration-sample/package.json#L42

warning:
https://github.com/Microsoft/vscode/issues/36623
https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs#run-time-diagnostics

@octref is there a better place to log these types of things since this issue is now closed?

**Comment by octref** [comment]
@busticated Can you post a new issue under https://github.com/microsoft/vscode-docs/issues? I'll tackle it there.

The two issues you listed above for the API doc — we have a huge backlog for that page. We'll do it from scratch and I've taken notes, so no need for new issues on those two.

**Comment by busticated** [comment]
done!
https://github.com/Microsoft/vscode/issues/60399
https://github.com/Microsoft/vscode/issues/60400

**Comment by octref** [comment]
Hey all, as some of you might have noticed, we had a multi month effort to refresh our Extension API doc. The work is near complete and will be published soon. A preview is available at https://vscode-ext-docs.azurewebsites.net/api. If you have any feedback, feel free to open an issue at https://github.com/microsoft/vscode-docs and mention me.

The update focused on making structure changes that make the doc easy to navigate and find information from. We also added new topics such as [Extension API Overview](https://vscode-ext-docs.azurewebsites.net/api), [Extension Capability Overview](https://vscode-ext-docs.azurewebsites.net/api/extension-capabilities/overview) to help you better utilize the vast extensibility system, and new guides/samples such as [Tree View](https://vscode-ext-docs.azurewebsites.net/api/extension-guides/tree-view) / [Color Theme](https://vscode-ext-docs.azurewebsites.net/api/extension-guides/color-theme) / [Textmate Grammar](https://vscode-ext-docs.azurewebsites.net/api/language-extensions/syntax-highlight-guide).

From the writers & contributors' perspective, this update makes it easier to add new topics and make changes. This should lay down a good foundation for us to address the [extensibility issues](https://github.com/Microsoft/vscode-docs/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Aextensibility+) in vscode-docs repo. We'll continue to refresh the Extension API doc, and we welcome your contribution too 😉.
