### ISSUE TITLE
PHP MySQL formatting error with accents in string

### ISSUE THREAD

**Issue by rms95** [Microsoft/vscode#58261]
Issue Type: <b>Bug</b>

The following PHP code does not format correctly:
``
$query = "INSERT INTO `table`(`" . wronglyFormatedfunctionHere() . "`)";
``
The function in between is seen as string, but it this is php code. The issue seems to have something to do with the way accents are handled in SQL strings. Note that when the INSERT INTO is removed, the error disappears.

VS Code version: Code - Insiders 1.27.1-insider (5944e81f3c46a3938a82c701f96d7a59b074cfdc, 2018-09-06T07:41:14.241Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (6.31GB free)|
|Process Argv|C:\Users\username\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Doxygen|bbe|1.0.0
vscode-eslint|dba|1.5.0
vscode-apache|mrm|1.1.1
python|ms-|2018.8.0
cpptools|ms-|0.18.1
ftp-kr|rua|1.3.16
msbuild-tools|ste|0.0.8

</details>

**Comment by Joey79100** [comment]
I have the same issue and it doesn't look like it is related to accents.
Here's an example:
![image](https://user-images.githubusercontent.com/12445716/54353216-c605a780-4653-11e9-9436-020ce408044a.png)

In other cases, the PHP formatting works, but is not reverted back to SQL when the string is reopened:
![image](https://user-images.githubusercontent.com/12445716/54353072-6d360f00-4653-11e9-930e-a901aa93e487.png)

And in the above query, it is not the starting word that seems to make the difference with the first one, because even with the same start it shows the same issues (space before the word or not gives the same result):
![image](https://user-images.githubusercontent.com/12445716/54353122-935baf00-4653-11e9-8100-6872baf30c79.png)

**Comment by roblourens** [comment]
The backtick issue is upstream: https://github.com/atom/language-php/issues/348

Highlighting sql across multiple split up strings is here https://github.com/atom/language-php/issues/318
