### ISSUE TITLE
Visual Studio Code shows a blank line at the end of file that doesn't exist

### ISSUE THREAD

**Issue by Sl0vi** [Microsoft/vscode#58276]
- VSCode Version: 1.27.1
- OS Version: Linux Mint 19 MATE 64-bit

Steps to Reproduce:

1. Open any text file.
2. Visual Studio Code shows a blank line at the end of file that doesn't actually exist.
3. If the file has no blank line at the end of file you will see a single empty line, if it has a blank line you will see two empty lines at the end of the file.

Does this issue occur when all extensions are disabled?: Yes

edit - I also downloaded the insider edtion. It says it is version 1.28.0-insider and it has the exact same issue.

**Comment by Sl0vi** [comment]
#46078 is a completely different issue.

**Comment by alexandrudima** [comment]
In short, because it is possible to have files which do not end with `\n` and we want to be able to display the textual contents after the last instance of a `\n`, we are deviating from the [POSIX definition of a line](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206).

I agree that this might seem foreign and I think we should have an option (most likely on by default on Linux) to paint lines according to the POSIX definition. Do you know what other editors do with text after the last instance of a `\n`? Is it simply dropped when opening the file?

**Comment by alexandrudima** [comment]
@Sl0vi VS Code can be configured to always add a `\n` if you forget it to get the same behaviour on save via `"files.insertFinalNewline": true`. Would this alleviate the problem at least a bit?

(But we would still render an extra line at the bottom.)

**Comment by Sl0vi** [comment]
Both vim and xed show the text even when the file doesn't end with a 0A and both of them add the 0A to the end of the file on first save if it is missing.

**Comment by alexandrudima** [comment]
Let's track in #1027
