### ISSUE TITLE
Selection rendering in bidi text problem

### ISSUE THREAD

**Issue by pixieaka** [Microsoft/vscode#58273]
When I select last word of paragraph it highlight all sentence, but actually it select the word only cause when i write in demo "ee" it replace the word only. please fix the highlight on this,,
 

![s](https://user-images.githubusercontent.com/17777237/45258745-a304ed00-b3bd-11e8-9f62-74ec760bba82.gif)

Thanks,, All the best, Great work & happy coding.

**Comment by alexandrudima** [comment]
@pixieaka Can you please provide the text in a copy-paste friendly format? Does this work correctly in a native input area like the one on this page ?

**Comment by pixieaka** [comment]
`[
   'status' => 'تمت عمليه الحفظ بنجاح',
];`

**Comment by pixieaka** [comment]
`[ 'status' => 'تمت عمليه الحفظ بنجاح'];`

**Comment by pixieaka** [comment]
`[ 'status' => 'تمت عمليه الحفظ بنجاح' ];`

**Comment by alexandrudima** [comment]
We paint the exact thing we receive from Chromium in this case. The problem is that a certain offset has two distinct horizontal positions and Chromium returns what is arguably the wrong one in this case. This is best seen when using shift+right arrow:

![kapture 2018-09-12 at 16 29 25](https://user-images.githubusercontent.com/5047891/45432000-0d14df00-b6a9-11e8-85df-e5570064f635.gif)

**Comment by alexandrudima** [comment]
Interestingly, Firefox does the correct thing in this case. I can file an issue against Chromium.

**Comment by alexandrudima** [comment]
After the fix:

![kapture 2018-09-12 at 16 47 13](https://user-images.githubusercontent.com/5047891/45433005-857c9f80-b6ab-11e8-9b05-634faf5c5b95.gif)

The cursor is rendered at the other position, but that is still OK, as a single model position maps to two distinct view positions.
