### ISSUE TITLE
Debug: node.js does not terminate when debugging simple script

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#5831]
I have a very simple index.js file with a "console.log()" statement and run it via debugger. The debugger does not terminate though, but keeps running. I would expect the debugger to stop after the console.log.

@weinand @isidorn fyi

**Comment by isidorn** [comment]
This was like this since the beggining of time - I also see it in stable.
Forwarding to @weinand since the debug adapter does not send a terminate signal - it probably does not arrive from node

**Comment by joaomoreno** [comment]
@isidorn Surely this hasn't been like this forever. If a program is done, it's done, and the debugger used to quit debugging.

**Comment by isidorn** [comment]
@joaomoreno I remember this was like this since at least 6 months, but I think since day 1. This is how node behaves @weinand can correct me here
For debugging other languages once they are done we exit the debugging session because their program terminates and the adapter sends the appropriate signal to vscode

**Comment by joaomoreno** [comment]
No it's not. Node stops executing when there is nothing more to execute, which is what happens in `node -e ''`. It continues executing otherwise (e.g. when a `setTimeout` or `setInterval` is still pending, or waiting for IO).

**Comment by weinand** [comment]
@joaomoreno what you describe is the 'happy path' (non debug) mode of node.js.

Please run your one line snippet from above in debug mode from the command line:

```
node --debug-brk test.js 
```

and then attach node-inspector and then run the program to the end. You will find that the node process does **not** exit.

So @isidorn is right: this has been like this forever.

Your statement from above '*It's especially bad if you are debugging a node server which crashes....*' is unfounded because node server crashes are not affected by node running in debug mode.

**Comment by joaomoreno** [comment]
I have to disagree, that behaviour just appears to be a bug that no one cares. A bit of searching yielded nodejs/node#1788 which they seem to be picking up soon. It's a bug since 0.12; version 0.10 actually behaves as I and Ben expect it to.

Since this is a bug in Node itself I propose to just close this issue.

**Comment by millermatt** [comment]
Node team has replaced the debugging engine and even though the same behavior is observed they are encouraging more digging into the VSCode side.

https://github.com/nodejs/node/issues/1788#issuecomment-311597767

Is it possible to re-open this for more research? 

@joaomoreno @weinand

**Comment by weinand** [comment]
The VS Code ends the debug session on receipt of a terminate event from the runtime.
If such an event is not received, VS Code cannot end the session.
It is as simple as that.

@roblourens do you receive a terminate event with the inspector protocol?

**Comment by roblourens** [comment]
This is fixed in 1.14 - https://github.com/Microsoft/vscode-node-debug2/issues/11

**Comment by weinand** [comment]
@roblourens we should mention in the release notes that this long-standing node.js bug has been finally fixed and that this will show up for the inspector protocol.
