### ISSUE TITLE
Revert selected ranges always reverts all adjecent lines

### ISSUE THREAD

**Issue by SirIntruder** [microsoft/vscode#58326]
- VSCode Version: August
- OS Version: Windows 10

Steps to Reproduce:

1. Make a multiline change in file, tracked in git
2. enter diff view
2. Right click -> revert selected range (ctrl + backspace)

Expected: revert only selected range, as in "stage/unstage selected range" behaviouir

Result: vscode always reverts the whole hunk, even though user was selecting specific lines.

Bonus bug: ctrl+z has some erratic behaviour when undoing "revert" action - cursor moves to the bottom of the file for some reason.

**Comment by Git-Lior** [comment]
I've found similar problems related to this (detailed at #58719), and started working on a fix for that and this as well.

In order to verify that the revert/stage/etc. actions work properly and to prevent future bugs, I tried to write unit tests to functions in this file:

      vscode/extensions/git/src/staging.ts
    
but the test runner seems to have a problem with `import "vscode"` at the start of that file (even after adding it as a dependency). @joaomoreno how do I overcome this?

**Comment by joaomoreno** [comment]
@Git-Lior You'd have to setup an extension test suite: https://code.visualstudio.com/docs/extensions/testing-extensions

**Comment by joaomoreno** [comment]
Not a duplicate.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/9475
