### ISSUE TITLE
Cannot inspect/watch imports when debugging typescript 

### ISSUE THREAD

**Issue by anorborg** [Microsoft/vscode#58321]
- VSCode Version: Version 1.27.1 (1.27.1)
- OS Version: macOS High Sierra (10.13.6)

Steps to Reproduce:

1. Create TypeScript module with an export (i.e. `export const TEST = 'test'`)
2. Create TypeScript main that imports and uses that module
3. Start VSCode Debugger and watch `TEST`

**Example Module**
```
// ts-proj-module.ts
const TEST = 'test'
```

**Example Main**
```
// main.ts
import { TEST } from './ts-proj-module'

function buildMessage () {
    return `${TEST }`
}

if (TEST === 'test') {
    console.log(buildMessage())
}
```

Expected Result:
Watching value of `TEST` should be `test`

Actual Result:
Watching value of `TEST` is `not available`

Minimal Repo Branch:
https://github.com/anorborg/minimal-repo/tree/vscode/ts-debugging-issue

<img width="1235" alt="capture 2018-09-09 at 3 46 31 pm" src="https://user-images.githubusercontent.com/264755/45269903-b14d1a80-b44a-11e8-8b6c-2dd58d18e69f.png">

Does this issue occur when all extensions are disabled?: Yes

I didn't see any issues referencing this nor any reference to limitations in the documentation. Not sure if there is any `tsconfig.json` option missed or anything like that. Does anyone have any ideas?

EDIT: In addition, as can be seen from the screenshot, the logic of using the import works fine.

**Comment by roblourens** [comment]
Unfortunately this is just a limitation of debugging with sourcemaps. You can see in the variables pane that the module is really imported under a different name due to how your ts is transpiled:

![image](https://user-images.githubusercontent.com/323878/45310624-a55d6900-b4db-11e8-9239-24e05f363983.png)

Since you're "really" debugging js code, you often have to keep this js/ts split in mind while debugging.

**Comment by anorborg** [comment]
Thanks for the clarification @roblourens!
