### ISSUE TITLE
Debug: continue action seems broken for Go extension

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#5835]
Testing #5644

### Setup

It's easier to install the whole thing in Linux:

- [Install Go 1.6](https://www.digitalocean.com/community/tutorials/how-to-install-go-1-6-on-ubuntu-14-04)
- [Setup Go](https://golang.org/doc/code.html#GOPATH)
- [Install and setup the go extension](https://marketplace.visualstudio.com/items?itemName=lukehoban.Go)
- Install gin: `go get github.com/gin-gonic/gin`

### Repro

Create a new folder. In it, create a `server.go` file with the following contents:

```go
package main

import "github.com/gin-gonic/gin"

func main() {
    r := gin.Default()
    r.GET("/ping", func(c *gin.Context) {
        c.JSON(200, gin.H{
            "message": "pong",
        })
    })
    r.Run() // listen and server on 0.0.0.0:8080
}
```

Set the debugger config: `"program": "${workspaceRoot}/server.go"`.

### Repro

- Set breakpoint on line 8.
- Start debug.
- Run `curl http://localhost:8080/ping` to hit the breakpoint.
- Press `Continue`

The debugger continues but the UI fails to update that it did continue. This is broken on latest Alpha but not on stable 1.0.0.

**Comment by isidorn** [comment]
The continue action has always passed the threadId of the `threaId` to continue, however there was an issue in the vscode UI and we would react as if all the threads continued. However, the go adapter ignores the `threadId` and continues all the threads, so it was working properly because of the issue we had.

I was looking into the [delve api](https://godoc.org/github.com/derekparker/delve/service/rpc2#RPCServer) and it seems like it is not possible to continue only one thread for go.

So for this milestone I propose to introduce a hacky check if we vscode is talking to go behave like previously, and in May we will have to solve this in a nicer way - e.g. each debugger could specify in it's capabilites if it supports continuing only one thread.

fyi @lukehoban @weinand

**Comment by weinand** [comment]
@isidorn can you point me to the issue that 'VSCode would react as if all threads continued'? Which debugger ran into it?

**Comment by isidorn** [comment]
@weinand https://github.com/Microsoft/vscode/issues/1703
