### ISSUE TITLE
Regex search and group replace

### ISSUE THREAD

**Issue by david-cannady** [Microsoft/vscode#58374]
- VSCode Version: 1.27.0
- OS Version: macOS High Sierra 10.13.5

Steps to Reproduce:

1. Create a new folder
2. Place a file in that folder containing the following lines:

```
import { isGameBackendServiceId } from "@aristocrat/gdk-base-lib/lib/types/GameBackendServiceId";
import { StoredPlayerRound } from "@aristocrat/gdk-base-lib/lib/types/StoredPlayerRound";
```

3. Open VSCode and attempt a **Regex** search and replace with the following search/replace criteria:
Search Text: `"@aristocrat/gdk-([a-z\-]*)-lib/lib/types/([a-zA-Z/]+)"`
Replace Text: `"@aristocrat/gdk/lib/$1/types/$2"`

Expected: Both replace-preview and replace will result in the following text:

```
import { isGameBackendServiceId } from "@aristocrat/gdk/lib/base/types/GameBackendServiceId";
import { StoredPlayerRound } from "@aristocrat/gdk/lib/base/types/StoredPlayerRound";
```

Actual:

```
import { isGameBackendServiceId } from "@aristocrat/gdk/lib/$1/types/$2";
import { StoredPlayerRound } from "@aristocrat/gdk/lib/base/types/StoredPlayerRound";
```

More:
This is a simple example where the regex fails to use grouping in the replace, though not consistently. There are cases where the replace succeeds as expected, even in the same file.
My workaround was simply to write the search/replace criteria that doesn't use regex. (In my case, resulted in 70+ separate search/replace's to do the same thing as the single regex.) Though this still works, is much less efficient.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by roblourens** [comment]
Oh, this came from work last month to separate the text "preview" from the full match text. The replace service is using the trimmed preview to figure out what the replacement should be.

If you resize the search view so that it loads a wider preview, then this works.

**Comment by roblourens** [comment]
FYI @sandy081

**Comment by liangya123** [comment]
.....sorry

**Comment by liangya123** [comment]
----

**Comment by sandy081** [comment]
@roblourens I suppose, preview mode is added to Search view for improving the performance?

I think why not using the Preview mode only when Replace mode is `off`  You can consider Replace mode is `on` whenever Replace box is visible. I think its fine to re-run the query when the replace mode is enabled. 

But not sure if it is a safe fix for recovery. Is it possible to disable preview mode for Search for now and enable it again in this milestone with above changes?

**Comment by roblourens** [comment]
This isn't related to the preview itself, the problem is that when doing a replace with the regex groups, we need the full line of text.

When we support multiline search, we will need the entire file, so we should keep that in mind too. Even if the actual match is very short, the regex can include a lookahead that matches something later in the file. And we can't return the full text of the file with each match.

I think that rerunning the search when the user opens the replace input is not ideal, it could be very annoying if the search was slow.

Currently I'm thinking that a safe recovery build fix would be just to request the full line of text from the provider when doing a regex search, and the better fix will be to have the frontend open each file and actually read the text we need from there.

**Comment by roblourens** [comment]
Maybe we could parse lookahead patterns out of the regex, then the full of the match would be enough. We could have the provider always at least return the full text of the match, even though it can be very long.

**Comment by roblourens** [comment]
We decided to take a safe fix for now - make the character limit much higher for a regex search. For multiline search we will probably need to solve this differently by opening each file when the actual replace happens. But that will be a different issue.
