### ISSUE TITLE
Menu bar toggling is inconsistent with the rest of Windows

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#58377]
I'm splitting out some [previously reported issues](https://github.com/Microsoft/vscode/issues/35010#issuecomment-339695865) since they weren't resolved with the fix to the original issue.

There are a couple of quirks with the keybinding for toggling the menu bar that don't match other Windows applications and cause workflow annoyances. These both occur when `window.menuBarVisibility` is set to `toggle`.

1. Hold Ctrl, press and release Alt, notice the menu bar is toggled.
Expected: the menu bar is not toggled.
I've tested with various other applications on Windows including Notepad, Paint, and Firefox. None of them do this.

2. Press and release Alt, press escape, notice the menu bar does not get hidden.
Expected: the menu bar should be hidden.
I tested with Firefox and Visual Studio 2015 (using https://marketplace.visualstudio.com/items?itemName=MatthewJohnsonMSFT.HideMainMenu) and both will hide the menu bar when escape is pressed.

Issue 1 is a daily annoyance for me, as it seems to happen very frequently when I jump between editor groups.

Also, the new custom title bar doesn't have these issues and it feels like the menu bars should be consistent with each other and with the rest of the Windows experience.

**Comment by sbatten** [comment]
@akbyrd just to clarify, this issue is specific to the old style menu bar?

**Comment by akbyrd** [comment]
This only applies to the old menu bar.

**Comment by m50d** [comment]
Assuming this is the same issue: when I use `Alt-\`` (toggle Japanese input method) focus moves to the menu bar (as though I'd just tapped `Alt`). Extremely frustrating when trying to write text in mixed Japanese/English!

**Comment by AB1908** [comment]
I'm having a somewhat similar issue but the relevant ones seem to have been locked.
- **System Information**:
  - Environment: Linux x64 5.6.15-arch1-1
  - DE: GNOME 3.36.2
  - Display Server: X11
  - VS Code Version: 1.45.1
  - Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
  - Date: 2020-05-14T08:27:22.494Z
  - Electron: 7.2.4
  - Chrome: 78.0.3904.130
  - Node.js: 12.8.1
  - V8: 7.8.279.23-electron.0
- **Extension Table**: 

Extension | Author (truncated) | Version
-- | -- | --
textile | idl | 0.1.5
latex-workshop | Jam | 8.10.0
textile-preview | mic | 1.0.2
python | ms- | 2020.5.80290
code-spell-checker | str | 1.9.0
vscode-icons | vsc | 10.1.1
vim | vsc | 1.14.5

- **Reproducible Steps**:
  - Split terminal using `Ctrl+Shift+%`
  - Press `Alt+Right Arrow` to switch to terminal on right
- **Expected Behaviour**: Cursor switches to terminal on the right followed by user actions such as input, etc.
- **Observed Behaviour**: Cursor switches to terminal on right followed by Menu Bar becoming visible or focused depending on prior setting of Menu Visibility.
- **Notes**: The behaviour is also observed when using any two keystroke command involving a leading `Alt`, such as any GNOME based shortcuts. It can also be observed by pressing `Ctrl+Alt`, which ideally should not lead to a capture of `Alt`.

**Comment by sbatten** [comment]
@deepak1556 this is an old issue about electron's menus

**Comment by deepak1556** [comment]
2) from https://github.com/microsoft/vscode/issues/58377#issue-358736702 is addressed, 1) is still present. Closing as blocked on upstream.
