### ISSUE TITLE
Settings: Files Association setting duplicate TabIndex stops for 'Edit in settings.json'

### ISSUE THREAD

**Issue by cleidigh** [microsoft/vscode#58403]
Tabbing through the complete settings list, once focus reaches Files, Associations settings file link, it takes two Tabs to advance.  One Tab causes of small upward scroll but without a focus change.

The problem does not appear to occur if you have a filter such as 'Files' and perform the tabbing.

![image](https://user-images.githubusercontent.com/25272315/45339027-72a88480-b55e-11e8-84d6-2162af97911a.png)

**Comment by roblourens** [comment]
That's because the list is virtualized, and if you tab off the last item that's actually in the dom, it hits a dummy focusable element which triggers a scroll, then sets the focus back to the element it came from. I can probably make it slightly nicer by also sending focus to the next focusable element. I'm not sure how to trigger a 'tab' though.

**Comment by isidorn** [comment]
We have other issues about settings accessibility and focus order.
Thus closing as duplicate
