### ISSUE TITLE
Disabling some extension's default shortcut with platform-specific condition not work in keybindings.json

### ISSUE THREAD

**Issue by johnnytemp** [Microsoft/vscode#58404]
Un-assign an extension's Alt+i shortcut with `"when": "isMac"` not work.  Tested not working in latest insiders too.

- VSCode Version: 1.27.1
- OS Version: macOS

Steps to Reproduce:

1. install extension "vscode-selection-flip" (by Marek Lewandowski)
2. edit keybindings.json to contain this:

       [
           {
               "key": "ctrl+alt+i",
               "command": "vscodeSelectionFlip.flip",
               "when": "isMac"
           },
           {
               "key": "alt+i",
               "command": "-vscodeSelectionFlip.flip",
               "when": "isMac"
           },
       ]

3. new document with content `Hello, world.`, double-click the word `Hello` to  select it, and press Alt+i, then `a`
4. Expected `â` replaced `Hello`.  However, the document become: `ˆ, world.` with some strange selection. (because both insert `ˆ` and flip selection action is performed)

Does this issue occur when all OTHER extensions are disabled?: Yes

**Comment by johnnytemp** [comment]
Thanks for your response.  Here is my opinion.  Thanks.  :)

1.  The syntax of remove & re-assign `alt+i` seems verbose.  It is also ambiguous too, because how do you know the remove and the add of `alt+i` has higher priority.

2. I have thought this is bug because there is inconsistency, on Windows the below setting work to remove `alt+left` and re-assign it:

       {
           "key": "alt+left",
           "command": "-workbench.action.navigateBack",
           "when": "isWindows"
       },
       {
           "key": "alt+left",
           "command": "cursorWordPartLeft",
           "when": "isWindows"
       },

    If it is because the "cursorWordPartLeft" is replacing "workbench.action.navigateBack", why don't both actions triggered at the same time?

**Comment by Tyriar** [comment]
> I have thought this is bug because there is inconsistency, on Windows the below setting work to remove alt+left and re-assign it

@johnnytemp That would work without the remove key as the keybinding priority is defined by their order in the keybindings.json file.

> If not, and if there could be schema checking, better underlines the forbidden syntax "when": ... for shortcut's removal when editing the JSON.

It's not forbidden though, and errors like this would cause issues for me when the file is shared across multiple OS's as it's perfectly valid to remove a keybinding with a when clause that Windows may have but macOS does not.

**Comment by johnnytemp** [comment]
Thanks a lot @Tyriar for your reply.

> it's perfectly valid to remove a keybinding with a when clause that Windows may have but macOS does not

The above confuses me, you said by design `"command": "-vscodeSelectionFlip.flip",` not work with the `"when": "isMac"`.  But from the above sentence you seems like saying `"command": "-vscodeSelectionFlip.flip"` may be valid and effective with some `"when": "..."`, and can distinguish between Windows and macOS?  @@

Thus may I ask what's the reasoning behind that the below not work?  And when a `when` clause may work in such shortcut deletion case?  Or any issue ticket for my reference?

    {
        "key": "alt+i",
        "command": "-vscodeSelectionFlip.flip",
        "when": "isMac"
    },

**Comment by Tyriar** [comment]
Actually when looking into this it doesn't actually work the way I thought it did. Sending to @alexandrudima who should know more.

**Comment by alexandrudima** [comment]
I am sorry for the confusions in this area. The removal of a keybinding is a **symbolical** operation. Keybindings can be targeted and removed **symbolically**, i.e. this happens without resolving `when` variables (which are always assumed to be dynamic).

Let's suppose you are using a mac. The keybinding logic does not know that `isMac` is a **special** context key that is permanently `true` and that `isWindows` and `isLinux` are special context keys that are permanently `false`.

To further exemplify, suppose there are four default rules we ship with (or that are contributed by default by an extension):
```json
{ "key": "escape", "command": "foo", "when": "A && B" },
{ "key": "escape", "command": "foo", "when": "B" },
{ "key": "enter", "command": "foo", "when": "C" },
{ "key": "escape", "command": "bar", "when": "D" },
```

---

#### In order to remove all bindings of Escape one needs to write:
```json
{ "key": "escape" }
```
> Note that this is not really removing the 3 rules from above with escape, this rule is simply shadowing the above 3 rules because it doesn't use a `when` condition. Also, because it doesn't define a `command`, it means that no command will be executed, and instead the keybinding will be dispatched for input producing purposes.

The effective list of keybindings will be:
```json
{ "key": "escape", "command": "foo", "when": "A && B" },
{ "key": "escape", "command": "foo", "when": "B" },
{ "key": "enter", "command": "foo", "when": "C" },
{ "key": "escape", "command": "bar", "when": "D" },
{ "key": "escape" }
```

---

#### In order to remove all bindings of a certain command one needs to write:
```json
{ "command": "-foo" }
```

Whenever a `-` is used in the command id, zero or more rules will be **removed**. In this case, everything that has the `foo` command will be removed. The effective list of keybindings will be:

```json
{ "key": "escape", "command": "bar", "when": "D" }
```

---

#### In order to remove a key + command combo:
```json
{ "command": "-foo", "key": "escape" }
```

Same as above, but now we remove the `foo` command only when the key is escape. The result of the removal is:
```json
{ "key": "enter", "command": "foo", "when": "C" },
{ "key": "escape", "command": "bar", "when": "D" }
```

---

#### In order to remove a specific binding:
```json
{ "key": "escape", "command": "-foo", "when": "B" },
```

Only exact matches are removed, as otherwise it would be impossible to leave the first rule in. The effective result is:

```json
{ "key": "escape", "command": "foo", "when": "A && B" },
{ "key": "enter", "command": "foo", "when": "C" },
{ "key": "escape", "command": "bar", "when": "D" },
```

---

P.S. this logic is implemented [here](https://github.com/Microsoft/vscode/blob/522e3a0c2a12938ee810a4eb9bc1a469e1441992/src/vs/platform/keybinding/common/keybindingResolver.ts#L50:L70)

**Comment by johnnytemp** [comment]
Thank you very much for your detail expansions.  I now understand why removal seems sometimes work and sometimes not. :)

**Comment by johnnytemp** [comment]
Here is my advice for future readers: you would better always avoid using `"when": ...` for shortcut removal, especially for platform-dependent cases.

For example, although some shortcuts is windows-only, the following actually have no effect because seems the default shortcut was not added by `"when": "isWindows"` (so better specify only "key" & `"command": "-..."` for removal):

    {
        "key": "alt+left",
        "command": "-workbench.action.navigateBack",
        "when": "isWindows"
    },
