### ISSUE TITLE
Middle click item  in explorer for "new editor" function not working.

### ISSUE THREAD

**Issue by asdme** [Microsoft/vscode#58442]
- VSCode Version:
Version: 1.27.1 (user setup)
Commit: 5944e81f3c46a3938a82c701f96d7a59b074cfdc
Date: 2018-09-06T09:21:18.328Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version:
Windows 10 Pro 64-bit (10.0, Build 17134)

Steps to Reproduce:

1. Middle click item in explorer
2. Scroll icon appear 
![2018-09-11_21-42-18](https://user-images.githubusercontent.com/39254925/45371181-c7560900-b60b-11e8-85fc-4ba999dd378d.gif)

If you open developers tools  works as expected

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by isidorn** [comment]
Hmm strangely I am no longer getting a `click` event [here](https://github.com/Microsoft/vscode/blob/361841021f32e1018bb31e7707bd122f1f020b34/src/vs/base/parts/tree/browser/treeView.ts#L554) when I do a middle mouse click
This nicely works in stable.
I see we use a different electron 2.0.9 compared to 2.0.7 but not sure if that update includes something which would influence this.
Also the middle click nicely works in the tabs title area - @bpasero  how are you handling it there?

@joaomoreno did we change something in the tree which might effect this?

**Comment by bpasero** [comment]
@isidorn yeah see https://github.com/Microsoft/vscode/commit/c8c1d83be33d727f97d3f45e704dc11147b9c3d4#diff-52dd0826e59985e9ccfc82a6fbc3b69e. I removed [`auxclick`](https://developers.google.com/web/updates/2016/10/auxclick) to prepare for Electron 3.0.x. We should probably wire this into the tree so that people can react to it. Simply forwarding the `onClick` was resulting in other issues.

**Comment by bpasero** [comment]
@isidorn yeah, the thing is, middle-click should not trigger the click, otherwise we might get wrong behaviour where people do not expect middle-click to do anything. Instead we can check clients of the tree (and list?) that want to do something on middle click and update them accordingly. Otherwise every client has to do an extra check for which mouse button was used for click.
