### ISSUE TITLE
Stack paging should not be implemented with a click

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#5849]
Testing #4819 

There are very good building blocks in our code for us to implement this properly:
- https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/paging.ts
- https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/quickopen/common/quickOpenPaging.ts

Just talk to me for tips.

**Comment by isidorn** [comment]
We have explicitly decided on the explicit action, if you have concerns please comment here 
https://github.com/Microsoft/vscode/issues/4792

**Comment by joaomoreno** [comment]
That *explicit* decision was taken based on the *loading stack frames is expensive* argument. What? The reason not to do lazy loading is because loading is slow? You **are** doing lazy loading, you're just implementing it with a very poor UI concept: an extra clickable list item.

The only thing that you are missing to implement nice paging, like we do with the extensions, is [the **total** number of stack frames](https://github.com/Microsoft/vscode/blob/fb318f0be37fbea7b4ea0a4c82c1fb221d3275c2/src/vs/base/common/paging.ts#L13). And, surprise surprise, [you do have it in the protocol](https://github.com/Microsoft/vscode-debugadapter-node/blob/08117a1286a100d2e30feddde9c8dffb16a76564/protocol/src/debugProtocol.ts#L399) and all adapters [either](https://github.com/Microsoft/vscode-mono-debug/blob/252c9e7aa72ef1d27f34c4651bc1430deb8827a4/src/MonoDebugSession.cs#L508) [could](https://github.com/Microsoft/vscode-chrome-debug/blob/fd61dcdfad2a61d3e0656db317e22adb073a705a/src/chrome/chromeDebugAdapter.ts#L439) or [do implement it](https://github.com/Microsoft/vscode-node-debug/blob/3fb9a7f671d92a7a42390fc6d95a5683acc35eaf/src/node/nodeDebug.ts#L1350).

@weinand I further suggest to make that [`totalFrames`](https://github.com/Microsoft/vscode-debugadapter-node/blob/08117a1286a100d2e30feddde9c8dffb16a76564/protocol/src/debugProtocol.ts#L399) mandatory. I doubt any debug adapter wouldn't be able to fulfil that request. A stack trace's length is always at any debugger's fingertips.

**Comment by isidorn** [comment]
I am fine with experimenting with this. It sounds good to me.
@weinand let me know what you think, if making totalFrames mandatory is fine

**Comment by weinand** [comment]
There is a difference between **explicit/voluntary** lazy loading and **implicit/involuntary** lazy loading.
We've decided to use **explicit/voluntary** lazy loading because it gives the user explicit control when to load more frames. **implicit/involuntary** lazy loading would mean: if a user resizes the CALL STACK view to be large (or uses a big screen and VS Code in fullscreen mode), more than 20 frames will be loaded. If more frames are loaded automatically, it is more likely that node.js becomes unresponsive because one of those frames is too large. You can implement Joao suggestion but then we need an opt-out mechanism for adapters like node-debug.  

We cannot make `totalFrames` (or any other attribute) mandatory without breaking all old debugAdapters, so we need a 2.0 version of the debug protocol (which would mean you will have to support two versions). We can plan for this, but it is nothing that we will introduce lightly.

**Comment by isidorn** [comment]
If nodeDebug would opt out of this then I propose to push this to the backlog.

**Comment by isidorn** [comment]
Another issue with this idea is that it does not work nicely for multi-threaded applications

**Comment by weinand** [comment]
@isidorn another good point.
