### ISSUE TITLE
Give option to change the key used for multi-selection

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#5851]
- VSCode Version: 1.0.0
- OS Version: Widows 10 (1511) x64

The current key, <kbd>Alt</kbd> conflicts with the key used for bring out menu bar.

Ref: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/view/viewController.ts#L109

**Comment by alexandrudima** [comment]
:+1: We need to extract that if/else code into a mouse dispatching rule engine.

**Comment by qwesda** [comment]
could the mouse commands be customised in the `keybindings.json`? Like: 
```{ "key": "cmd+mouse1-click",          
   "command": "editor.action.insertCursorAtMousePosition",
   "when": "editorTextFocus" }```

I'm (as probably many user are) used to the sublime text keybindings and the keyboard commands are customisable, but the mouse commands are not.

**Comment by be5invis** [comment]
Are there any progress about this? Popping out menu bar is really annoying.

**Comment by seedform** [comment]
This is super irritating for me since I use the alt + click functionality a lot. For now I've got a workaround in Windows using AutoHotkey that prevents the menu bar from popping up after releasing the Alt key. Just add the following to your AutoHotkey script:

```
#if WinActive("ahk_exe Code.exe")
	~Alt up::
```

Warning: you'll only be able to access the menu bar using the `View: Toggle Menu Bar` command in the command pane.

**Comment by alexandrudima** [comment]
Related: #3130

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8874 is related and fixed for August.

**Comment by alexandrudima** [comment]
Done via #27193
