### ISSUE TITLE
Padding and Searchboxes Polishes

### ISSUE THREAD

**Issue by beastdestroyer** [microsoft/vscode#58531]
Issue Type: Polish
Continuation of #58445 except to meet the guidelines.

In every sidebar view, the margin of searchboxes is off. In the majority of cases, the right side of the input has less space than the left side. Additionally (and most apparent in the Extensions view), bottom margin is also too small compared to the rest of the spacing. The solution would simply be to increase the margin on the right-hand side of searchboxes by about 5px? And on the bottom about the same.

**Comment by misolori** [comment]
I should be able to tweak the margins so they're all consistent:

<img width="582" alt="image" src="https://user-images.githubusercontent.com/35271042/66424424-75c0af00-e9c2-11e9-9682-634677a15816.png">

**Comment by misolori** [comment]
Cleaned up the margins so that all of the views with an input box up top are the same. The Search view has an exception where it requires more margins due to the expand/collapse chevron:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/35271042/67246103-66a21e00-f412-11e9-8572-5dd481f483d7.png">



FYI @roblourens @joaomoreno @sandy081
