### ISSUE TITLE
Exception breakpoint filters aren't set the first time

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#58541]
- Have some code

```
console.log('foo');
throw new Error('fail');
```

- Set "Uncaught exceptions" on 
- Start debugging
- It doesn't break on the exception

---

- Set a BP on the console.log line
- Toggle "Uncaught exceptions" off and back on
- Continue
- Now it breaks on the exception

The DA only gets the `setExceptionBreakpoints` message when the exception filter is toggled back on.

**Comment by isidorn** [comment]
I can not reproduce this with latest
Can you reproduce with latest and if yes please let me know what you are doing differently than me?

![exception](https://user-images.githubusercontent.com/1926584/45697642-86f40f00-bb66-11e8-8786-ee47e0143b93.gif)

**Comment by roblourens** [comment]
I can still repro. It looks like you're following the steps correctly. So let me know how I can help debug.

**Comment by isidorn** [comment]
First set a breakpoint [here](https://github.com/Microsoft/vscode/blob/5bae3f69d92fdda9bf0096841259a548703d21e7/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L339) and check if the exception breakpoints are properly set to the debug adapter.
If yes then check if there is a stop event coming [here](https://github.com/Microsoft/vscode/blob/5bae3f69d92fdda9bf0096841259a548703d21e7/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L108) I expect not.
If the stopped event is not comming and the exception info is sent then the issue is somewhere in the adapter.

Anyways let me know what you found out, thanks

**Comment by roblourens** [comment]
Nooooooooo I can't repro it today. I saw it 100% of the time for awhile. I'll reopen if it shows up again.

**Comment by isidorn** [comment]
That's just life :)

**Comment by roblourens** [comment]
Now I see it again with the original steps. 

I think this is the faulty line: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugSession.ts#L279

We should send that list even when it's empty (no exception breakpoints are enabled) right?

cc @weinand

**Comment by roblourens** [comment]
Make sure that when you repro it, you only have the one checkbox checked, because the bug only exists when you go from 1 to 0 exception filters.
