### ISSUE TITLE
Multiple Code.exe processes running in Windows Task Manager

### ISSUE THREAD

**Issue by duyn9uyen** [Microsoft/vscode#5856]
- VSCode Version: 1.00 (Stable)
- OS Version: Mac OSX Yosmite 10.10.4 - running VmWare Fusion 7.12 with guest OS: Windows 7 64-Bit

Steps to Reproduce:

1. Install VS Code 1.00 (stable)
2. Open VS Code

VS Code takes an extremely long time to open (30 seconds to over a minute). CPU performance spikes to 100%.  I see 2 Code.exe processes running in Windows Task Manager before it opens.  But once it opens, I see MANY instances of Code.exe running.

![vscodeprocessors](https://cloud.githubusercontent.com/assets/6518508/14825660/c5ef2534-0ba8-11e6-96a9-85d91bd21d75.jpg)

**Comment by bpasero** [comment]
We do spawn many Code.exe as helper processes for other things. Does it also take long when Code is running and you execute the reload window command (F1 > Reload Window)?

**Comment by Raviuppa** [comment]
@bpasero , I see the same behavior on Linux and Mac as well. My question is not about the performance but when there are 6 instances of VSCode running even with no project or file window open. What can cause to span 6 instances of it? Is this by design?

 It will be difficult to debug VSCode on Windows, Linux and Mac if there is any issue with VSCode itself and not knowing which process to target for.

**Comment by bpasero** [comment]
@Raviuppa yes by design, the UI framework we use is multi process by itself and then we have 1 process for extensions (per window), one process for file watching (per window) and 1 process for search. We also have 1 shared process for updates.

**Comment by Raviuppa** [comment]
Oh ok. Is there a way to identify the process based on its purpose such as Extensions, File Watching etc..?

**Comment by bpasero** [comment]
@Raviuppa yes if you have a program that shows you how the process was spawned.
