### ISSUE TITLE
Support for auto-import of Icon-Fonts

### ISSUE THREAD

**Issue by projectzerotohero** [Microsoft/vscode#58586]
### Feature Request: Support for auto-import of Icon-Fonts

In our project, we are using an Icon-font called LineAwesome

Here is a sample SASS snippet:

<pre>
@mixin sample-dropdown-arrow {
    content: "";
    display: inline-block;
    font-size: 1em;
    font-family: LineAwesome;
}
</pre>

Content value is copy-pasted into the VsCode and as you can see, we have no idea on what is the actual content 
`content: "";`

Good thing it works fine in the browser.

Do you have an idea on how to resolve this?

Thanks!

**Comment by joaomoreno** [comment]
I believe the font you have configured VS Code to use to render text doesn't have a glyph for that character. But I'm pretty sure the copy paste operation worked. Try changing the editor font to other fonts. Does the icon appear?

**Comment by projectzerotohero** [comment]
The actual value is pasted correctly.
I have tried changing my vscode font from Consolas to FiraCode but it still does not work.

**Comment by alexandrudima** [comment]
This is as designed.

You paste a certain character in the editor. The character is rendered using the font configured in `editor.fontFamily`. If the font family you have chosen does not contain a glyph for the character, then a box ends up being painted.

It is very likely that none of your fonts will ever have a glyph for that character because AFAIK the icon fonts always use Unicode reserved characters especially to avoid collisions.

If you don't like to see the box glyph you can use the alternative way e.g.:
```
.octicon-cloud-download:before { content: '\f00b'}
```

**Comment by projectzerotohero** [comment]
Got it. 
For now, we'll go with the alternative way.
Thanks.

It would also be nice if there's a feature that can reference an icon-font so it can be rendered inside the editor.
