### ISSUE TITLE
Promote terminal renderer API to stable

### ISSUE THREAD

**Issue by iann0036** [Microsoft/vscode#58660]
Relates to https://github.com/Microsoft/vscode/issues/46192

Terminal Providers have been in proposed since April and seem to be working fine. I don't see any open issues relating to them and was wondering what needs to occur to get this planned into a stable release?

**Comment by Tyriar** [comment]
@iann0036 I'm mainly waiting for feedback as to my knowledge only Live Share has experimented with them. If you're interested on using the terminal renderer API I'd love to hear more details.

**Comment by Gamadril** [comment]
I need the TerminalRenderer to implement a "Debug Terminal" for Input/Output with a hardware device over a serial port. I'm sure https://github.com/Microsoft/vscode-arduino project needs the same API for their arduino serial monitor. Now they use vscode.window.showInputBox() to get input from the user - for me it's not an option.  It's like opening a terminal session with a remote pc and making all inputs over popup windows...

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/55718 blocks this

**Comment by Tyriar** [comment]
We'll need to move the events to be global before stabilizing:

```ts
namespace window {
	const onDidAcceptTerminalRendererInput: Event<{renderer: TerminalRenderer, input: string}>;
	const onDidChangeTerminalRendererMaximumDimensions: Event<TerminalDimensions>;
	const OnDidWriteTerminalData: Event<string>;
	const OnDidChangeTerminalDimensions: Event<string>;
}
```

**Comment by Tyriar** [comment]
This is because of https://github.com/Microsoft/vscode/wiki/Extension-API-guidelines#global-events

Thoughts @jrieken? I think we might have gone the original way because the most typical case is that _most_ extensions will want to control only the terminal(s) they have launched. It's not clear to me when this rule should not be followed.

**Comment by jrieken** [comment]
> I think we might have gone the original way because the most typical case is that most extensions will want to control only the terminal(s) they have launched. It's not clear to me when this rule should not be followed.

I don't see a strong reason to not follow this rule. The pattern is well established and makes event easy, esp with global things like terminal that can also be created via user-gestures. What is the strong argument here to break consistency?

**Comment by GabeDeBacker** [comment]
There are a couple of reasons here to augment the rule.

First is simply performance. The more extensions you have that have to subscribe to global events and handle events they don't necessarily care about, the slower VSCode becomes. I really admire VSCode's desire for speed and am really impressed by it. So the architecture and API design should be done in a way that helps enforce that.

Second is the API surface itself. If all events were to be global, then the number of APIs in a given namespace grows significantly over time. The API surface would end up with a very large namespace with hundreds of APIs and events that would be hard to logically understand.

Some languages, C# as an example, do not allow you to place events in a namespace thereby forcing an architecture where the events are on classes.

There is also an option of having the events at a global scope as well as on an object scope. That would alleviate my performance concerns above.

Final point, if there really is a need for a global event, then perhaps creating logical namespace separations for them in the API surface will with my "large surface area" concern. The "window" namespace is already quite large today.

As an example of today. Instead of this:
```Typescript
export namespace window {
	export function createTerminal(name?: string, shellPath?: string, shellArgs?: string[]): Terminal;
	export function createTerminal(options: TerminalOptions): Terminal;
	export const onDidOpenTerminal: Event<Terminal>;
	export const onDidCloseTerminal: Event<Terminal>;
```
A much more self discovering mechanism would be:
```Typescript
export namespace terminals {
	export function createTerminal(name?: string, shellPath?: string, shellArgs?: string[]): Terminal;
	export function createTerminal(options: TerminalOptions): Terminal;
	export const onDidOpenTerminal: Event<Terminal>;
	export const onDidCloseTerminal: Event<Terminal>;
```

**Comment by Tyriar** [comment]
Closing in favor of https://github.com/Microsoft/vscode/issues/70978
