### ISSUE TITLE
Wildcard support in launch.json

### ISSUE THREAD

**Issue by flyingice** [Microsoft/vscode#58698]
Version: 1.27.1
OS: macOS 10.13.6

It seems that wildcard expansion is not supprted in launch.json of VS Code, e.g. if I pass src/main/*.txt as one of the arguments to an executable, no txt files could be found in the target directory. My workaround for now is to specify explicitly the filename in the config.

What about the feature to get the wildcard * expanded in launch.json as in the config tasks.json? Is it already supported in the current version somehow?

**Comment by weinand** [comment]
Since VS Code knows nothing about the semantics of the attributes in the launch.json, it cannot provide wildcard support generically.

So wildcard support must come from individual debug extensions (and in fact some provide already wildcard support where it makes sense in the form of "glob" patterns).

For those debugger extensions that do not support wildcards a workaround might exist:

If the debugger extensions you are using supports to launch the debuggee in the integrated terminal (which uses a standard shell), then you can use wildcards. Here is a node.js example:

```json
{
	"type": "node",
	"request": "launch",
	"name": "Launch Program",
	"program": "${workspaceFolder}/app.js",
         "args": [ "*.txt" ],
         "console": "integratedTerminal"
}
```
