### ISSUE TITLE
String length less than 10000 are still truncated

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#5872]
Tested #4952

- VSCode Version: 1.1.0-alpha e77003fd6ca90d944feb572b54fc1d122d91d704
- OS Version: MacOS

Strings are still truncated. All relevant information about the string is given in the screenshot:

<img width="1216" alt="screenshot-timed" src="https://cloud.githubusercontent.com/assets/4674940/14838940/5cf44270-0bdb-11e6-9216-f3810d84178d.png">

**Comment by isidorn** [comment]
This is happening due to https://stackoverflow.com/questions/8516235/max-length-of-title-attribute
Because in this case we use the native chrome tooltip. And yes, I agree we need to wrap somehow the value in the variables view, but that is a feature request which I believe is already open - #1128

So closing this

**Comment by kieferrm** [comment]
@isidorn Can you pls clarify what you mean with "in this case"? Is that mac, this particular tooltip, something else?

**Comment by isidorn** [comment]
@kieferrm in this case: is actually the vscode tree which we use for representing variables, watch expression and so on. 
So I did not express myself nicely, in every case we use the native tooltip, except for the hover in the editor - which is our custom hover.
