### ISSUE TITLE
User installer breaks the Git for Windows installer's ability to set Code as the default editor

### ISSUE THREAD

**Issue by CtrlZvi** [Microsoft/vscode#58748]
- VSCode Version: 1.27.1 (user setup)
- OS Version: Windows 10

Steps to Reproduce:

1. Install VSCode on Windows using the user installer
2.Install Git for Windows using the installer from https://git-scm.com/download/win
3. Select `Use Visual Studio Code as Git's default editor`
4. Notice that the `Next` button becomes greyed out

Does this issue occur when all extensions are disabled?: Yes

Workaround:
1. Install VSCode with the system installer
2. Install Git
3. Uninstall the system VSCode

**Comment by alex-jitbit** [comment]
Having the same issue. Now I can't update GIT any more.

**Comment by joaomoreno** [comment]
/duplicate #56973 

git-for-windows/git#1795

**Comment by alex-jitbit** [comment]
No, that other issue is not a duplicate!

AFTER installing VScode git for windows suddenly stops working. I don't want to REINSTALL vscode and click some magic button to fix this

**Comment by alex-jitbit** [comment]
You do realize that when git-for-windows auto-update everything will break - again?

**Comment by joaomoreno** [comment]
> AFTER installing VScode git for windows suddenly stops working

Git stops working? How so? What happens if you open a Command Prompt and type `git`?

**Comment by alex-jitbit** [comment]
When git auto-updates and runs its installer - it won't see VScode and reset the editor back to vim/nano/notepad++ so I will have to reinstall vscode AGAIN?

**Comment by alex-jitbit** [comment]
Git auto-updater breaks my (and 1000s other people) workflow.

No, the #56973 won't.fix it. You're essentially suggesting everyone should reinstall vscode every time git-for windows updates itself automatically.

Don't you get it?

1. Git auto-updates itself and runs installer
2. The installer doesn't see VSCode (because you tricked everyone to move to the "user" version)
3. To fix that - you're adding some functionality to VSCode setup - meaning everyone should re-run VSCode setup.

To properly fix the issue VSCode should trick Git into thinking it's still a system version. Using Symlinks, stub folders, I don't know. You, not the Git team. Because it's YOU who changed things.

It's called "backward compatibility"

**Comment by shiftkey** [comment]
As a workaround you can edit your `~/.gitconfig` to set the `core.editor` value (I gather this is what VSCode will eventually provide a UI for):

![](https://user-images.githubusercontent.com/359239/45597854-87df4200-b9a8-11e8-9d53-6d3f2b30e549.png)

Or if you already have code on your path:

```
[core]
	editor = code --wait
```

**Comment by joaomoreno** [comment]
@alex-jitbit You are right. What isn't implemented is the awareness of the VS Code user setup from the Git installer side. Its main developer is already in the loop about this.

**Comment by Wrongtown** [comment]
The latest version of the Git for Windows installer resolved this issue for me 😁
