### ISSUE TITLE
feature request: "locking" a text buffer

### ISSUE THREAD

**Issue by kobi2187** [microsoft/vscode#58764]
Summary:
Feature Idea: allow to specify a buffer's (start, end) so that  text operations work on a specific "locked" text buffer

Description:
I think it's a good idea: allow to lock a certain text region or buffer, so when I do search replace and other operations like renaming, or really any of the many extensions, the operations will work on only that part, leaving the rest of the file unchanged.
An example is a long file, where we have a short text to replace, but the replace value changes according to context. for example in a long file that has code for an entire namespace, I am adding a self variable to all the functions, yet the type changes frequently (other classes are being defined). So I would like operations to have an effect only in that delimited area.

it's like extending the idea of "selection". the find widget can work only within the selection. I would like all operations to be restricted, when I specify such a region. 

What do you think?

PS: vscode is awesome. it's my programming editor of choice.

**Comment by heroboy** [comment]
maybe "invert selection"?

**Comment by kobi2187** [comment]
@heroboy no, the idea is that everything else is unaffected by commands.
it's like we want the selection to hold (but there is no need for actual selection, I'm just expanding on your words). 
Basically the editor limits access to anything not in the current focus, the current buffer/region.
Then you can do destructive actions and be sure other parts of your code are unaffected.

**Comment by rebornix** [comment]
We closed this issue because we don't plan to address it in the foreseeable future. You can find more detailed information about our decision-making process [here](https://aka.ms/vscode-out-of-scope). If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Thanks for your understanding and happy coding!
