### ISSUE TITLE
Duplicate breakpoint if blank lines clicked.

### ISSUE THREAD

**Issue by bidipeppercrap** [Microsoft/vscode#58770]
- VSCode Version: 1.27.1
- OS Version: Linux x64 Fedora 28

Steps to Reproduce:

1. Add breakpoint on line 14
2. Add breakpoint on line 13 (blank line)
3. Duplicate breakpoint (makes Debugger really lag)

Does this issue occur when all extensions are disabled?: Yes
![bug2](https://user-images.githubusercontent.com/30064028/45597781-42983000-b9fb-11e8-9454-138346611210.png)
![bug3](https://user-images.githubusercontent.com/30064028/45597782-42983000-b9fb-11e8-8a34-9029d1bf171d.png)

**Comment by weinand** [comment]
The node.js debugger automatically moves breakpoints to a valid location. In your case from the empty line 13 to line 14. This is the expected behaviour.

I do not see any lag when this happens.

**Comment by bidipeppercrap** [comment]
> The node.js debugger automatically moves breakpoints to a valid location. In your case from the empty line 13 to line 14. This is the expected behaviour.
> 
> I do not see any lag when this happens.
> 
> Do you see this lag in every case where you get two breakpoints on the same line?

Don't you see the breakpoint is duplicated on the same line? (14, 14)
See second image.

**Comment by bidipeppercrap** [comment]
> And the lag disappears if you remove one of the breakpoints?

Yes.

**Comment by weinand** [comment]
In theory you are right. In practice it is a bit more complex.

The facts:
- The UI doesn't allow to create duplicate breakpoints.
- You only see duplicate breakpoints if a debug session is active and a debugger has decided to move a breakpoint to a different location (where already a breakpoint exists). See this screen recording:
  ![2018-09-19_10-04-10](https://user-images.githubusercontent.com/1898161/45739515-82296c80-bbf3-11e8-92b7-a8a1495a0559.gif)
- breakpoints are shared across all debuggers.

If we would eliminate duplicate breakpoints, how would that work from a UX perspective?

- If no debug session is active, VS Code does not know whether breakpoints will map to the same location, so they cannot be de-duped.
- If a debug session is started, some breakpoints might move and become duplicates. Should we now de-dupe them? If the user ends a debug session some would be missing which would come as a surprise to the user.
- since breakpoints are shared across all debuggers breakpoints could map to the same location and become duplicates for one debugger, and in another debugger that might not be the case. De-duping them for one debugger might be wrong for the other debugger.

As you can see, de-duping breakpoints is more involved and we have know plans to address this.
