### ISSUE TITLE
vscode.window.activeTextEditor should never include output panel editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#58869]
(from https://github.com/Microsoft/vscode/issues/58865)

I find it questionable that `vscode.window.activeTextEditor` can ever be something that is not in our editor area where you would expect the editor to be. Imho both `vscode.window.activeTextEditor` and `vscode.window.visibleTextEditors` should never include editors outside the editor area of the workbench. 

The fact that the output panel is implemented using a text editor should be an implementation detail and not leak to extensions. If we have a use case for the output editor to be customizable by extensions, we should add a separate accessor for it (`vscode.window.outputPanel`).

**Comment by alexandrudima** [comment]
AFAIK there are extensions that depend on this behaviour already and making the change now would be a breaking change.

**Comment by jrieken** [comment]
Yes - this won't happen anymore

**Comment by DanTup** [comment]
Should an alternative way be provided then? This seems like https://github.com/Microsoft/vscode/issues/45188#issuecomment-371446711 again. I don't need it for my original issue anymore, but this feels like a weird hole in the APIs to never plug.

**Comment by alexandrudima** [comment]
There are two differences:
* the output editor ended up in `window.activeTextEditor` since the first public API release (by accident); the debug console ended up in `window.activeTextEditor` around 1 year later because we wanted to have suggestions in the debug console.
* there are extensions which have actively built on top of the output editor as an integral part of their UX. i.e. they render stuff in there, show it, hide it, move the cursor, insert text, listen to selection changes, etc. This was never the case for the debug console, which is not useful for such tricks.

IMHO the pain of breaking folks should be greater than the gains. It is not 100% clear to me what the gains are except purity.

**Comment by DanTup** [comment]
I didn't mean you have to break this property but the behaviour documented in the comment is useful for the reasons mentioned in the related case.

For example, say you want to show something on the status bar for the "active document". If you hook the events for active editor changing to show/hide it, then it'll hide whenever the user focuses the output pane even though their "active editor" didn't change (as far as they're concerned).

In any case, I think the comment on `activeTextEditor` should be updated to make this clearer. If it's going to be this way going forwards then I think it should be more obvious that this can include other panes that are implemented internally as editors.

**Comment by bpasero** [comment]
Yes, at the very minimum update the comment so that this behaviour is clear.
