### ISSUE TITLE
EPERM - Permission error 

### ISSUE THREAD

**Issue by no-more** [Microsoft/vscode#58881]
I know this look like other EPERM issue but it's not exactly the same.

- VSCode Version: 1.27.2
- OS Version: Windows 10
- Project env : angular + angular-cli + typescript + yarn

Steps to Reproduce:

1. work a bit with vscode, then try to delete some files or folder. Some times it works some time not
2. In order to make it work I have to restart vs code, at least the current editor but sometimes other vscode editor that are open on other project !

random files are locked, sometimes in node_modules, I often have to launch yarn twice in order to succeed. Some times it's the dist folder which is locked. When I try to remove from vscode explorer it requests for administrative rights but don't succeed to delete any way.
Some times I just need to retry several times to make it work, but most of the time I have to reload the window. On reload everything seems ok if there's only one editor opened. If many were open I might need to close or reload all of them (randomly).

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by no-more** [comment]
Thanks, I'll have to try each plugin to find the faulty one.

Sorry for the disturbance.
