### ISSUE TITLE
VS Code adds or removes spaces after quotation symbol (i.e. ") under certain circumstances 

### ISSUE THREAD

**Issue by VLaD0S** [Microsoft/vscode#58906]
Issue happens when writing Django templating files. 

- VSCode Version: 1.27.2
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:
1. write something like **<script src="{% static "main/main.js" %}" ></script>** in a .html file
2. save.

A space will be inserted after the second quotation mark, i.e in front of frontend, and remove any space after the last quotation mark, resulting in:

**<script type="text/javascript" src="{% static "frontend/main.js" %}"></script>**

"{% static "frontend/main.js" %}" >
"{% static " frontend/main.js" %}">

 
Does this issue occur when all extensions are disabled?: Yes

Changing "editor.formatOnSave": to false fixes the issue. Althought I wonder if there is a solution without that compromise.

My Settings:
{
  "editor.formatOnSave": true,
  "python.linting.pylintArgs": [
    "--load-plugins=pylint_django",
    "--errors-only"
  ]
}

**Comment by octref** [comment]
Possibly a js-beautify issue.

**Comment by aeschli** [comment]
The problem is that the django syntax seems to allow quotes inside the template
`"{% static "frontend/main.js" %}"`

The HTML formatter sees this as two strings : `"{% static "` and `" %}"` and adds spaces.

The solution is to either to 
- use a formatter that can handle the django language. I don't know if that exists but check out the marketplace.
- disable format on save (`"editor.formatOnSave": false`). Note that you can also just turn off `editor.formatOnSave` for html. (`"[html]": { "editor.formatOnSave": false }`)

**Comment by VLaD0S** [comment]
> The problem is that the django syntax seems to allow quotes inside the template
> `"{% static "frontend/main.js" %}"`
> 
> The HTML formatter sees this as two strings : `"{% static "` and `" %}"` and adds spaces.
> 
> The solution is to either to
> 
> * use a formatter that can handle the django language. I don't know if that exists but check out the marketplace. The request to add a django formatter is #46468
> * disable format on save (`"editor.formatOnSave": false`). Note that you can also just turn off `editor.formatOnSave` for html. (`"[html]": { "editor.formatOnSave": false }`)
> 
> Marking as dup of #46468

Thanks, your suggestions fixed my issue. I wasn't aware that you could change the formatting settings for particular languages/markups. Much appreciated again
