### ISSUE TITLE
Extensions do not start at one time.

### ISSUE THREAD

**Issue by mumeiyamibito** [Microsoft/vscode#58918]
- VSCode Version: 1.27.2
- OS Version: LinuxMint 19 (64bit)

Steps to Reproduce:

Installed [Insert Date String](https://marketplace.visualstudio.com/items?itemName=jsynowiec.vscode-insertdatestring).

1. Launch VSCode.
2. Press Ctrl+Shift+P and input "insert date" in dialog.
3. Enter
4. Originally, the date and time will be inserted in this step but the function does not work.

Does this issue occur when <s>all</s> other extensions are disabled?: Yes

This problem has occured at first time after launching VSCode. Executing the same steps again, the function works.

And This problem affects other extensions such as [Markdown Preview Enhanced](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced), [join-lines](https://marketplace.visualstudio.com/items?itemName=wmaurer.join-lines), and [Table Formatter](https://marketplace.visualstudio.com/items?itemName=shuworks.vscode-table-formatter).

I guess that VScode does not cooperate with extensions at startup.

**Comment by chrmarti** [comment]
Cannot reproduce. Is there anything in the console (Help > Toggle Developer Tools)? (Also: Quick Pick is not involved here.)

**Comment by chrmarti** [comment]
This doesn't reproduce for me. It appears to be something with the activation of the extensions.

**Comment by mumeiyamibito** [comment]
@chrmarti 

I found the cause of this issue.
This issue is occured when `"git.enabled"` is `false`.
I confirmed on "Insert Date String", "Table Formatter", and "join-lines" extensions.

Thus, git function in vscode triggered this issue.

**Comment by sandy081** [comment]
@joaomoreno Git extension is not finishing activation when git is disabled

https://github.com/Microsoft/vscode/blob/4c963c08950f9c4b5623f4064f671967f13cd4ea/extensions/git/src/main.ts#L142

While executing a command which is not registered, we trigger `onCommand:command` activation event and wait until those extensions activate by this command and also those extensions eagerly activate (by `*`), to execute the command. Since `git` extension never returns from activation, command is not executed when called first time.

I think an extension should never block activation.

**Comment by chrmarti** [comment]
Should we also remove the `await` here to avoid waiting for user input during activation: https://github.com/Microsoft/vscode/blob/4c963c08950f9c4b5623f4064f671967f13cd4ea/extensions/git/src/main.ts#L156
