### ISSUE TITLE
Middle click selection in extension search doesn't copy text to 2nd clipboard linux

### ISSUE THREAD

**Issue by Yanpas** [Microsoft/vscode#59028]
- VSCode Version: 1.27.2
- OS Version: kubuntu 18.04

Steps to Reproduce:

1. enter some text to extension search bar
2. select it (by the way I can only select whole text, not part of it)
3. Text isn't copied to the second clipboard (this is linux specific, middle button clipboard)

![peek 2018-09-20 11-44](https://user-images.githubusercontent.com/7345761/45806821-ac9a2900-bcca-11e8-83ae-61467e898c85.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by ramya-rao-a** [comment]
Does this work as expected when you select text from other search boxes? For example: The find widget in the editor?

**Comment by ramya-rao-a** [comment]
@Yanpas What about from the editor? Open a file and try the same on the text in the file.

**Comment by Yanpas** [comment]
It works everywhere except extension search field. I'm sure it occurred after intellisence in this bar was introduced

**Comment by alexandrudima** [comment]
@ramya-rao-a If that tiny editor would include the `SelectionClipboard` contribution, it would begin to work.

**Comment by ramya-rao-a** [comment]
@alexandrudima The problem is that the editor lives in the `browser` layer and `SelectionClipboard` uses the clipboard from electron.

@roblourens Do you recall the need to have the `suggestEnabledInput` in the `browser` layer and not in the `electron-browser` layer?

Note: This issue will also affect the search in the new Settings editor
