### ISSUE TITLE
Search in editor (CTRL-F) changes focus to search in PROBLEMS panel

### ISSUE THREAD

**Issue by doberkofler** [Microsoft/vscode#59082]
Issue Type: <b>Bug</b>

When using a shortcur to search in the editor, the focus changes to the search box in the PROBLEMS panel. When using the menu this works as expected.

VS Code version: Code - Insiders 1.28.0-insider (2558a72d6902015b142ef45c57b664ce1f09e03f, 2018-09-21T05:19:52.215Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz (4 x 2691)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (0.91GB free)|
|Process Argv|C:\Users\doberkofler.LBITS\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.6.0
flow-for-vscode|flo|0.8.4
prettify-json|moh|0.0.3
python|ms-|2018.8.0
printcode|nob|2.3.1
vscode-icons|rob|7.26.0
code-settings-sync|Sha|3.1.2
stylelint|shi|0.43.0
language-stylus|sys|1.10.0
stylint|vtf|0.0.2
plsql-language|xyz|1.5.0

</details>

**Comment by pdanpdan** [comment]
This also happens to me, also insiders build, search display in the panel enabled.
Steps to reproduce:
- start VSCode (Problems panel should have been open so that it opens by default)
- click on a file from explorer so that the file opens
- press CTRL+F shortcup for find/search
- filter box on PROBLEMS panel gets the focus
- a need to first focus PROBLEMS panel and then focus file in order to get search in file

If the PROBLEMS panel is hidden (from start) the problem is more funny: it looks like the filter field in the PROBLEMS panel gets the focus even if it's not visible.

**Comment by sandy081** [comment]
Good catch

@pdanpdan Thanks for the steps. 

I could reproduce the first case but not this

> If the PROBLEMS panel is hidden (from start) the problem is more funny: it looks like the filter field in the PROBLEMS panel gets the focus even if it's not visible.

**Comment by pdanpdan** [comment]
Sorry, second description was wrong, it wasn't as I described. It was like this:
- start with PROBLEMS panel open
- close PROBLEMS panel
- open file
- CTRL+F
- there is no find widget open in file, so I suppose the filter field in PROBLEMS panel was focused

Now I'm sure it was the same cause.

**Comment by sandy081** [comment]
@pdanpdan Thanks for the steps. It is also got fixed.

**Comment by sandy081** [comment]
Another case

- Open a file in VS Code
- Open problems view and focus in filter
- Hide Panel
- Type cmd+down arrow in the editor

🐛 Nothing happens

**Comment by sandy081** [comment]
Verify following:

Scenario 1

- start VSCode (Problems panel should have been open so that it opens by default)
- click on a file from explorer so that the file opens
- press CTRL+F shortcup for find/search
- filter box on PROBLEMS panel gets the focus


Scenario 2

- start with PROBLEMS panel open
- close PROBLEMS panel
- open file
- CTRL+F
- there is no find widget open in file, so I suppose the filter field in PROBLEMS panel was focused

Scenario 3

- Open a file in VS Code
- Open problems view and focus in filter
- Hide Panel
- Type cmd+down arrow in the editor

🐛 Nothing happens
