### ISSUE TITLE
settings: need to restart dialog makes it hard to make changes

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#59108]
Windows

- open the classic settings editor
- add to the workspace settings
```
  "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/*/**": true
    }
```
- try to modify `"**/node_modules/*/**": true` by adding a new segment to the path.
- in the middle of typing a modal dialog pops up
![image](https://user-images.githubusercontent.com/6461412/45887103-2e697f80-bdbb-11e8-91bf-3dd26d04ea14.png)

- would better if this a non-modal notification

**Comment by bpasero** [comment]
I prefer the current behaviour because it is just one Enter away from getting the setting applied. I explain why I find the behaviour you see less of an issue:
* it does not happen in the new settings editor that is now enabled by default
* it does not happen unless auto-save is enabled in the old settings editor which is also not the default

**Comment by aeschli** [comment]
It's a very frustrating experience. Once I press cancel, maybe give me some peace?
It basically forces to turn off auto-save.

Looking at the code, I see that settings changes are forwarded to the watcher and roots are updated. Is the restart really required?
