### ISSUE TITLE
Add new file saved on shutdown to working files

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#5912]
- VSCode Version: alpha
- OS Version: Linux / Windows

Steps to Reproduce:

1. File > New File
2. Add some code/text, do not save
3. Close Code
4. Save file when prompt comes up

Actual:
The file is in working files before closing, then after re-opening Code the file is no longer in working files.

**Comment by rebornix** [comment]
It's likely a bug instead of a feature. Per current implementation of TextFileService,

*[electron-browser/textFileServices.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/textFileServices.ts#L51)*
```
public beforeShutdown(): boolean | TPromise<boolean> {
	super.beforeShutdown(); // implemented in browser/textFileServices.ts

	// Dirty files need treatment on shutdown
	if (this.getDirty().length) {
            ...
            return this.confirmBeforeShutdown(); // we still have dirty files around, so confirm normally
	}
	return false; // all good, no veto
}
```

*[browser/textFileServices.ts](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/textFileServices.ts#L235)*
```
public beforeShutdown(): boolean | TPromise<boolean> {
	// Propagate to working files model
	this.workingFilesModel.shutdown();
	return false; // no veto
}
```

We'll see that `workingFilesModel` persistence happens before `confirmBeforeShutdown`. However, in `confirmBeforeShutdown` we might update `workingFilesModel` if there are still some unsaved newly-created files, but the update is lost as we will not save `workingFilesModel` to local storage anymore.

IMHO, a proper fix is moving `workingFilesModel.shutdown` from event `onWillShutdown` to event `onShutdown` since the definition of `ILifecycleService.onShutdown` is `Fired when no client is preventing the shutdown from happening. Can be used to dispose heavy resources like running processes. Can also be used to save UI state to storage`. Saving working file status to storage in this phase is acceptable. What do you think?
