### ISSUE TITLE
Rename the javascript.validate.enable to be typescript specific

### ISSUE THREAD

**Issue by KevinGrandon** [Microsoft/vscode#59133]
- VSCode Version:  1.27.1 
- OS Version: OSX

Steps to Reproduce:
1. Install VSCode
2. Use VSCode with any non-TS codebase

Description:
Currently the typescript checker will interfere with the flow checker by default which makes for a very unpleasant experience for new developers using VSCode with flow but not TS. 

We often have to tell people to disable this option, but it's confusing due to the javascript-specific naming of it.

Suggesting changing `javascript.validate.enable` to `typescript.validate.enable`.

**Comment by mjbvz** [comment]
Our built-in JS support targets standard javascript. Setting `"javascript.validate.enable": false` disables our built-in error reporting for JavaScript , that  validation is powered by typescript is an implementation detail

If you are working with flow, I recommend you disable disable the built-in js/ts language features extension entirely instead of only disabling validation. Many of our other JS features like intellisense, refactorings, and auto imports also don't work with flow
