### ISSUE TITLE
Debugging with smartstep is super slow.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#5916]
Testing: #4954

- VSCode Version: 1.1.0-alpha
- OS Version: Windows10

Steps to Reproduce:
1. Create Basic nodejs JavaScript express3 project from Visual studio. 
2. Launch VS code and open project folder.
3. update launch.json and set the value for smartstep:"true" and sourcemap: "true"
5. Start debugging and verify application behavior.

Note: I tried with all the possible combination of smartstep and sourcemap and observed this behavior when both the properties set to true. 

Actual: Debugging is super slow and taking long time to render page. 
Expected: Debugging should not be slow down when user enable smartstep.
![smartstepdebugissue](https://cloud.githubusercontent.com/assets/17735796/14865846/98fd198c-0c75-11e6-9d0a-53ecb5785314.gif)

**Comment by weinand** [comment]
@v-pavanp 'smart step' makes only sense if your project is using source maps and those sourcemaps cover most of the source code of the project. It seems your project is a plain JavaScript project without a single source map. Why would you use 'smart step' in this case? Just to be slower?

**Comment by v-pavanp** [comment]
No, but how about mixed TypeScript and JavaScript projects.

**Comment by weinand** [comment]
Mixing works fine as long as the JavaScript you are stepping through is reasonable small (for instance because it is just glue code generated by a transpiler).

If you have lots of JavaScript that does not map to some source language, using this option makes you slow because node debug has to single-step through the JavaScript.

So the slowness you are seeing is expected and not a bug.
