### ISSUE TITLE
Inconsistent behavior for diagnostics between tooltip & problems panel (variable expanded?)

### ISSUE THREAD

**Issue by timonwong** [Microsoft/vscode#59286]
- VSCode Version: 1.27.2
- OS Version: macOS 10.11.6

Steps to Reproduce:

It seems in problems panel, the form `$(xxxxx)` will be as variables, and then accidently expanded.

**EDIT:** After some digging, it's caused by the octicon expand here, which is used by highlightLabel:
https://github.com/Microsoft/vscode/blob/4e4e6f9b44dd9e6a53d1f08565c52b8ea9f61a5e/src/vs/base/browser/ui/octiconLabel/octiconLabel.ts#L11-L15

![image](https://user-images.githubusercontent.com/1398228/45991523-dd59d400-c0b7-11e8-8f71-36b0b6c8c12e.png)

![image](https://user-images.githubusercontent.com/1398228/45991515-d03ce500-c0b7-11e8-81a0-05397ebd43ad.png)

Is it working as intended, or is there any way to workaround that?

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
This is because `HighlightedLabel` automatically renders Octicons. 

https://github.com/Microsoft/vscode/blob/4beb0d5465104ceceae2ad7eb163203166093edc/src/vs/base/browser/ui/highlightedlabel/highlightedLabel.ts#L83 

I introduced an option to not to render Octicons.

@isidorn @bpasero @jrieken Highlighted label is being used [IconLabel](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/iconLabel/iconLabel.ts#L88), [Outline](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/documentSymbols/outlineTree.ts#L141) and at other places. 

Please disable them if you do not want to render them.

**Comment by sandy081** [comment]
To verify, have a sample extension that generates diagnostics with message has octicons format and test the message is shown completely without rendering octicons.

```typescript
```
