### ISSUE TITLE
Add --trace option to help and guide the user to upload a report

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#59299]
re #59234

* run `code-insiders --help`
* 🐛  no word about `--trace`

**Comment by bpasero** [comment]
@jrieken yeah I did not add it there intentionally because I think it is so specific to us asking users to do it explicitly. I would never expect someone to run this command unless we added some guidance (like `--prof-startup` has). 

We can leave this open as feature request, but I am not planning to work on it near term.
