### ISSUE TITLE
Explorer should allow basename with dot

### ISSUE THREAD

**Issue by kutyel** [microsoft/vscode#59368]
VSCode Version: v1.26.1 (1.26.1)
OS Version: macOS High Sierra v0.13.6
When doing @reasonml, it's very annoying to have all those **.bs.js files generated (just like it was with @typescriptlang at the beginning), so I tried to ignore them in my file tree but it doesn't seem to work.

Steps to Reproduce:

1. Add this to your settings.json
```
{
  "files.exclude": {
    "**/*.bs.js": { "when": "$(basename).re" }
  }
}
```
2. Reload, go to file explorer and see that you can still see the *.bs.js generated files. ⚠️

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by isidorn** [comment]
In order to fix this I suggest to introduce a new option to the [IGlobOptions](https://github.com/Microsoft/vscode/blob/f25e9c1069f964f015b8081a4f5d2357d7a93f9f/src/vs/base/common/glob.ts#L258) 
Something like `allowBasenameWithDot` and only explorer would opt into this.
Though @bpasero would be better to comment on the `glob.ts`

**Comment by isidorn** [comment]
@rebornix did you accidently close this one maybe?
