### ISSUE TITLE
Terminal Find widget doesn't search in split panes

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#59386]
Ref #59267

* Open Terminal Find Widget, search
* Split the pane
* Search again, it searches in the second pane
* Move focus to the left side pane, now searches will happen in the first pane but never the second

Probably we should allow searching in all split panes as there is only one find widget for one panel.

**Comment by Tyriar** [comment]
This is by design, but I agree it's a bit weird how the find widget is shared between the panel though. Not sure whether we should have each pane own a find widget or whether each terminal "tab" should own it. If/when terminals eventually make it into the grid the panes will be within individual tabs so maybe it makes sense to share..?

**Comment by misolori** [comment]
My initial impression is that the find widget should search across all panes. But in the grid editor, each group has its own find widget. 

For some reason I'd still expect to be able to search across split panes in the terminal.
