### ISSUE TITLE
Right click on setting title in settings editor to show 'copy setting id' menu

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#59400]
**Request**
Allow users to right click on the title of a setting in the setting editor. This would display the same context menu as clicking on the gear that appears next to the setting.

I find the gear hard to discover, even when I know it exists

**Comment by roblourens** [comment]
What if the gear icon is visible when you hover the title? Would that make it slightly more discoverable? I am going to add a transition animation and slight delay which would make it a bit less annoying when you are mousing over settings without pausing on the title.

Right clicking on the title feels strange because it's not a "list row" or a button, just text in a form.

**Comment by mjbvz** [comment]
That would help. I still would prefer being able to trigger the action on the title itself since it's a larger target and near where my cursor normally ends up while browsing the settings

**Comment by sandy081** [comment]
Marking this as verified that gear icon is also visible when hovering on title. But I would also prefer to open the context menu when I right click on the title. This behaviour is also there in extensions view.

@roblourens If you agree I will file a new issue for that.

**Comment by roblourens** [comment]
I'm not a big fan but it's been suggested a few times so sure, it's worth filing a new issue to discuss it.
