### ISSUE TITLE
Cannot attach vscode to ConEmu via command-line

### ISSUE THREAD

**Issue by bbenoist** [Microsoft/vscode#5941]
- VSCode Version: 1.0.0
- OS Version: Windows 10

Steps to Reproduce:

1. Install [ConEmu](https://conemu.github.io/)
2. Start a new PowerShell task in ConEmu.
3. Start vscode from ConEmu with `code <somedir> -w -new_console:sV`

![capture](https://cloud.githubusercontent.com/assets/2091902/14884278/f4c85c9e-0d43-11e6-98a6-3e94d7cd99f2.JPG)

[Initiated](https://github.com/Microsoft/vscode/issues/143#issuecomment-215371371) in #143

**Comment by bpasero** [comment]
Not sure if this is bug report or feature request.

**Comment by Tyriar** [comment]
@bbenoist by attach do you mean you want the output from Chromium and/or want the process to continue running (`-w`)?

**Comment by pflannery** [comment]
I think @bbenoist means having vscode contained within conemu like

![image](https://cloud.githubusercontent.com/assets/1727302/14904465/367d0c0a-0da0-11e6-82b5-f2e8d44e0e79.png)

I have a gist that shows how to setup a conemu task that always launches vscode inside conemu https://gist.github.com/pflannery/8d28d1d5e17cc3b15ab5861639fa2e5a

Not sure what the cmd line would be though. Probably a question for https://github.com/Maximus5/ConEmu

**Comment by bbenoist** [comment]
@Tyriar Yes, @pflannery is right, I want to redirect vscode window into ConEmu via command-line. The `-w` option was just a desperate attempt; I actually don't need it..

![image](https://cloud.githubusercontent.com/assets/2091902/14909639/42cfbca0-0de6-11e6-8216-50e395645ffe.png)

Replace gitk by vscode and you get the idea :wink: 

@Maximus5 I'm afraid my problem is due to vscode process forking at startup. Do you have any ConeEmu-side workaround which would not require manual operations at each new call?

**Comment by Maximus5** [comment]
@bbenoist You are using a year old build. Code is working properly in actual ConEmu. [Why not to update?](https://conemu.github.io/en/OldBuild.html#update-your-installation)

**Comment by bbenoist** [comment]
@Maximus5 

> You are using a year old build.

You're right, the version which is tagged as stable on ConEmu Download page is 1 year old:

![capture](https://cloud.githubusercontent.com/assets/2091902/14919671/1d27a0a0-0e2a-11e6-9057-3ba60e052732.JPG)

> Code is working properly in actual ConEmu.

I've tested version 160301 preview but it still does not changes anything:

![capture2](https://cloud.githubusercontent.com/assets/2091902/14920460/1370a346-0e2e-11e6-9c0f-df361a3e6938.JPG)

Now trying version 160428 alpha...

> Why not to update?

Because I prefer to use stable versions unless it's missing a feature I find important...

**Comment by bbenoist** [comment]
Still no change with 160428 alpha :cry: :

![capture](https://cloud.githubusercontent.com/assets/2091902/14920562/8fabdb24-0e2e-11e6-8487-ab7ede634455.JPG)

**Comment by Maximus5** [comment]
For unknown reason, Code reuses parent console to dump debug information,
which has no sense for general users.

To avoid that behavior, Code installer adds `bin` with `code.cmd` to `%PATH%`
instead of folder with `code.exe`.

So, when you run `code`, the `code.cmd` is executed actually, which blocks
automatic attach of code into ConEmu tab, because this cmd executes

~~~
call "%~dp0..\Code.exe" "%~dp0..\resources\\app\\out\\cli.js" %*
~~~

The reason? I have absolutely no idea.
Why this workaround was chosen instead of implementing sort of `--dump_debug_to_console` switch
for those cases when it's really required?


## Solution

[Create alias](https://conemu.github.io/en/SettingsEnvironment.html) to run code in tab

~~~
alias codetab="C:\Program Files (x86)\Microsoft VS Code\Code.exe" -new_console $*
~~~


## More strange things

If you let your `%PATH%` to point to `C:\Program Files (x86)\Microsoft VS Code` (without bin),
or register `code.exe` in application paths

~~~
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\App Paths\Code.exe]
@="C:\\Program Files (x86)\\Microsoft VS Code\\Code.exe"
~~~

Than, when you start `code` from existing console you'll have a lot of garbage in your console instance.

**Comment by bbenoist** [comment]
@Maximus5 Thanks for the answer!

> The reason? I have absolutely no idea.
 Why this workaround was chosen instead of implementing sort of  --dump_debug_to_console  switch
 for those cases when it's really required?

I think @kevinsawicki could help answering your questions as it looks like he introduced the wrapper with https://github.com/atom/atom/pull/4560

> **Solution**

Solution worked for CMD but not for PowerShell (ConEmu alias doesn't seems to work with PS) so I tried replacing `C:\Program Files (x86)\Microsoft VS Code\bin` by `C:\Program Files (x86)\Microsoft VS Code ` in `%PATH%` and it seems to be OK with both shells.

> **More strange things**

As you can see in the screenshots below, I do not have any garbage coming from VS Code:

![image](https://cloud.githubusercontent.com/assets/2091902/15156192/332a25ac-16e6-11e6-90be-b857a25b249f.png)

![image](https://cloud.githubusercontent.com/assets/2091902/15156036/84a7f14e-16e5-11e6-933b-96f5f5f9ccc2.png)

I now wonder what are the differences between our configurations 😕 

Is it the same garbage than reported on https://github.com/atom/atom/issues/11686 ?

**Comment by bbenoist** [comment]
@Tyriar As I have a workaround, feel free to close this issue if you do not intend to implement a more convenient fix.

**Comment by Maximus5** [comment]
@bbenoist You have no garbage, because it's hidden by code window due to `-new_console` switch.
Try to run just `code` and see the awful result.

**Comment by bbenoist** [comment]
@Maximus5 You're right 😭 

![image](https://cloud.githubusercontent.com/assets/2091902/15158766/a0ada7b0-16f1-11e6-89ed-a87c7472a7c6.png)

**Comment by Tyriar** [comment]
Thanks @Maximus5 for looking into this, I created https://github.com/Microsoft/vscode/issues/6307 to fix `code.cmd` to wait.

As for why you need `code.cmd` and not just `code.exe`, this is because `code.exe` bypasses [`cli.ts`](https://github.com/Microsoft/vscode/blob/master/src/vs/code/node/cli.ts#L20) which handles the "output only args" like `--help` before electron is launched and its output is printed to the console (in order to avoid https://github.com/atom/atom/issues/11686).

Closing this off as #6307 will remove the need for the workaround.

**Comment by Maximus5** [comment]
#6307 will not fix **this** issue. If user runs `code.cmd`, user loses the ability to run Code in ConEmu tab. That is the problem!

**Comment by Tyriar** [comment]
@Maximus5 oh I think I understand now, the cli.js call runs as a node process and that launches actual vscode process after it has validated some things. Unless ConEmu can somehow work with the processes launched by the process, the workaround is how you will need to do it.

**Comment by Maximus5** [comment]
ConEmu attaches GUI application when in the tab

1. The GUI application is started as first process in this tab and creates GUI window
2. The GUI wrapper (Windows GUI subsystem, not a console subsystem) application is started as first process and wrapper executes second GUI process which creates GUI window.

If GUI application (creating GUI window) is started from existing console process (which is cmd.exe which runs `code.cmd`) than GUI window is started outside of ConEmu because otherwise the behavior would be a nonsense. User works with console and it suddenly is blocked with third-party tool?
But this console process may ask ConEmu to run GUI application in the new tab, starting, for example `code.exe -new_console` from `code.cmd`.

**Comment by bbenoist** [comment]
> Unless ConEmu can somehow work with the processes launched by the process, the workaround is how you will need to do it.

I suggest an alternative which might do the job. I would call it the "Yo dawg!" technique ®️ 

![image](https://cloud.githubusercontent.com/assets/2091902/15226591/a6c180b6-1883-11e6-8814-319afb0dac7d.png)

Let's say you do not use a batch file anymore but a .exe "GUI" wrapper which would:

1. To simplify things for end-users. Rename current `code.exe` into something else (`code-runtime.exe` in this post). That's our wrapper which will benefit from the `code.exe` name now.

2. Do the equivalent of `code.cmd` but in a native Win32 GUI executable named `code.exe`:  
       set VSCODE_DEV=
       set ATOM_SHELL_INTERNAL_RUN_AS_NODE=1
       call "%~dp0..\code-core.exe" "%~dp0..\resources\\app\\out\\cli.js" %*

3. Wrap the `code-runtime.exe` GUI into `code.exe` (same technique than for ConEmu tabs).

With this technique, I suppose that ConEmu would be able to get the window inside it because first process is a GUI and remains running.

🎨  Depending on how _current_ `code.exe` is built, it might even be possible to use a single executable which would wrap a new instance of itself. I don't know if it's actually feasible however.
