### ISSUE TITLE
Bottom status bar could show number of commits not pushed to remote and number of changes locally.

### ISSUE THREAD

**Issue by jsmith50-sc** [Microsoft/vscode#59465]
VS2017 shows this in the lower right corner, and I find it helpful to see regularly.  

I'd like to see the number of un-pushed commits.  This would be what I have locally, but not pushed to the remote.  Along with that, I'd also like to the see the number of changed files currently in the local working folder to know what I have to still commit.

**Comment by V-ed** [comment]
![image](https://user-images.githubusercontent.com/16652915/46084393-8fa1a200-c171-11e8-9413-b1114a68640c.png)

As you can see in this screenshot, we can already see the amount of un-pushed commits (I have `1` in this project with `48` commits missing from origin).

We however do not see how many files are changed in the current workspace though, and I would also like to have this information on the bottom left.

The number of changes is shown in the Activity Bar already (see screenshot below) *but* I personally *always* have the activity bar off because I prefer having more real screen estate and I move between panel using keyboard shortcuts. Therefore, having the number of changes in the bottom left would be great for me!

![image](https://user-images.githubusercontent.com/16652915/46085122-4baf9c80-c173-11e8-91eb-13c19963d0df.png)

That said, maybe the addition of changes in the workspace in the bottom left could be an extension, as having the number in the activity bar *and* in the Status Bar might be redundant and not everyone might want it. Maybe it could be in the core or VSCode but added as an option? I'll let a Microsoft member let their say on this, but I definitely support seeing the number of changes in the left side of the Status Bar.

**Comment by jsmith50-sc** [comment]
Thanks for that.  I didn't realize this info would show up in the status bar since it doesn't show zeroes like visual studio does, as well as having separate icons for each (one for commits needing push and one for uncommitted changes.)  Here's what mine usually looks like when I enter vscode:

![image](https://user-images.githubusercontent.com/11033741/46086807-ec538b80-c176-11e8-8766-715db4210dd3.png)

and what it looks like in vs2017:

![image](https://user-images.githubusercontent.com/11033741/46086884-186f0c80-c177-11e8-9d10-13d2199c6d4a.png)

I keep the activity bar off usually too, so completely agree with what you said there.  I think now seeing that the info does show, perhaps having that as separate icons/data in the bar isn't needed although I will say it's nice to see you have everything checked in and pushed occasionally.

**Comment by joaomoreno** [comment]
Closing as we purposefully don't show a zero.

**Comment by V-ed** [comment]
@joaomoreno
> The number of changes is shown in the Activity Bar already (see screenshot below) *but* I personally *always* have the activity bar off because I prefer having more real screen estate and I move between panel using keyboard shortcuts. Therefore, having the number of changes in the bottom left would be great for me!

What about this though? As I said in my comment, there are few possibilities that could fulfill the request of seeing the number of pending changes in the bottom left.

Should it be via an extension? Could it be in the core of VSCode?

**Comment by joaomoreno** [comment]
Since git now exposes an API, you could write an extension which does that. It will start exposing the changes next month: #59419
