### ISSUE TITLE
Use absolute paths for getModeIdByFilenameOrFirstLine()

### ISSUE THREAD

**Issue by jmdsg** [Microsoft/vscode#59517]
- VSCode Version: 1.25.1 1dfc5e557209371715f655691b1235b6b26a06be
- OS Version: Microsoft Windows 10 10.0.17134

Steps to Reproduce:

1. Use the `seti` icons or `vscode-icons`.
2. Configure `files.associations` with a glob expression. Where the original file extension and the "associated" extension have different icons.

Does this issue occur when all extensions are disabled?: Yes/No
Not sure if `Seti` counts as an extension.

This is my configuration:

```json
{
    "files.associations": {
        "**/imports/ui/*.js": "javascriptreact",
        "**/imports/ui/components/**/*.js": "javascriptreact",
        "**/imports/ui/layouts/**/*.js": "javascriptreact",
        "**/imports/ui/views/**/*.js": "javascriptreact"
    }
}
```

All the files listed in that folders show the `js` icon, but when i open the file and use `"Keep Open [Ctrl + k] Enter"` the icon changes to the correct `react` icon in the tab. 

<p align="center">
  <img width="300px" src="https://user-images.githubusercontent.com/11861795/46121850-b6002580-c1e3-11e8-929f-1665a01b6274.gif">
</p>

Also in the explorer happens something similar, the icon changes after i `[Ctrl + k]` and hover the bar, or move the bar up or down.

<p align="center">
  <img width="300px" src="https://user-images.githubusercontent.com/11861795/46122144-23f91c80-c1e5-11e8-9d6d-f07a74c9e367.gif">
</p>

**Comment by bpasero** [comment]
This is a (old) regression from https://github.com/Microsoft/vscode/commit/1b6fd47b5005ad542e8d459510c6fd99155db2a0. We have to pass the full absolute path of the resource to `getModeIdByFilenameOrFirstLine` and `getOrCreateModeByFilenameOrFirstLine` so that our `files.associations` glob patterns are properly working if they are more complex. 

I found two places where we are wrongly passing over a file name:
* https://github.com/Microsoft/vscode/blob/36f879d81888a35a7d05c64f1f4e53bf6599e301/src/vs/workbench/browser/labels.ts#L350 @isidorn 
* https://github.com/Microsoft/vscode/blob/36f879d81888a35a7d05c64f1f4e53bf6599e301/src/vs/editor/common/services/resourceConfigurationImpl.ts#L46 @sandy081

**Comment by sandy081** [comment]
@bpasero Is `resource.path` an absolute `path` when scheme is `file`?

**Comment by sandy081** [comment]
I see, I am using `basename` there.

**Comment by bpasero** [comment]
@sandy081 I would assume URI.path is the right thing to do, but @jrieken can confirm maybe (as author of https://github.com/Microsoft/vscode/issues/47748)

**Comment by sandy081** [comment]
Ok. Changed from basename to absolute path/

**Comment by isidorn** [comment]
@bpasero thanks for pushing a fix
