### ISSUE TITLE
Cannot start debugging of .NET Core project.

### ISSUE THREAD

**Issue by pwasiewicz** [Microsoft/vscode#59535]
- VSCode Version: 1.28.0-insider
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. Generate new .NET Core 2.1.408 project with `dotnet new console`
2. Open project with VS Code
3. Generate optional assets files (VS Code asks if I'd like to add them: launch.json and tasks.json).
4. Try to start debugging

The problem is that Debug Adapter is null and cannot set `onError` property:

![error](https://user-images.githubusercontent.com/8725777/46140037-470ce600-c250-11e8-8ded-00670d236bce.jpg)

It seems that there is some problem with adapter type because the type is null.:

![adapter](https://user-images.githubusercontent.com/8725777/46140071-5d1aa680-c250-11e8-8c2b-eecb925749d8.jpg)

My launch.json (that what  was generated, removed comments only)

```
{
   "version": "0.2.0",
   "configurations": [
       
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/netcoreapp2.1/Tools.FtpServer.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart"
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}"
        }
    ,]
}
```

Does this issue occur when all extensions are disabled?: No

**Comment by isidorn** [comment]
@pwasiewicz it would be great if you create this issue here https://github.com/OmniSharp/omnisharp-vscode

Also can you reproduce this with the latest vscode insiders (I see some code you pasted which does not look like latest)
Also can you reproduce with VSCode stable?
If you would like to investigate more on the vscode side you can put a breakpoint [here](https://github.com/Microsoft/vscode/blob/0ebb6b054f5a3b91c598cde7d7d76244a8d7cc66/src/vs/workbench/parts/debug/node/debugger.ts#L62) and check why the adapterDescriptor.type seems to be off
