### ISSUE TITLE
Show active file in explorer shows 2nd open file if active file is out of workspace

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#5955]
IMHO not important, feel free to close

1. VSCode with workspace, open a file out of that workspace
2. Open a file side by side that is inside the workspace
3. Focus on out of workspace file -> show active file in explorer
4. The other file gets revealed in explorer, I would expect no action

**Comment by bpasero** [comment]
@isidorn please see the code here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/fileActions.ts#L2348

We always open the explorer in both cases, so maybe you got that. And if the file is not inside the workspace we just expand the working files view because that one always is centered around the active file. 

Please reopen if you see an issue with the implementation there.

**Comment by isidorn** [comment]
Code looks good. Behavior I am seeing could be describe by `editorService,getActiveEditorInput()` returning the wrong input if two editors open, out of workspace is active and the other one in workspace not active.

**Comment by bpasero** [comment]
@isidorn that is very unlikely, it would break pretty much everything. getActiveEditor always targets the one editor that was last focussed.
