### ISSUE TITLE
Button in Find/Replace to swap the content of the text boxes

### ISSUE THREAD

**Issue by Darthfett** [microsoft/vscode#59652]
Suggestion: Add a button in the "Find and Replace" dialog box that swaps the text in the two boxes.

I use VS Code as my general purpose text editor, and I will often do the following operation:

1. Find and replace a separator value with newline
2. Modify the text (adding lines, removing lines, modifying lines with column select)
3. Find and replace newline with a separator value

This is particularly handy when working with system PATH values on Windows, or editing CSV files.  However, when I want to perform step 3, I have to delete the text in both boxes and re-type them.  If a button to swap the text existed, it would reduce this operation down to a single click.

**Comment by roblourens** [comment]
Do you know of any other editors that have this feature?

**Comment by Darthfett** [comment]
@roblourens , not particularly for code, but Google Translate allows you to swap between languages with a button.

**Comment by roblourens** [comment]
That's not really the same. I'll leave this open for now but I'm not sure it would be generally useful enough.

**Comment by rebornix** [comment]
We closed this issue because we don't plan to address it in the foreseeable future. You can find more detailed information about our decision-making process [here](https://aka.ms/vscode-out-of-scope). If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Thanks for your understanding and happy coding!
