### ISSUE TITLE
Open Editors shouldn't be toggleable if no editors are open

### ISSUE THREAD

**Issue by beastdestroyer** [microsoft/vscode#59753]
Issue Type: Bug

- VSCode Version: 1.28.0-insiders
- OS Version: Windows 10 1803 17134.320

Steps to Reproduce:

1. Close all editors (doesn't matter if in a workspace)
2. Click on "Open Editors" in file explorer
3. See toggle switch, but nothing shows

As per this screenshot:
![image](https://user-images.githubusercontent.com/30497573/46303543-08569300-c5a4-11e8-849a-45d5a8df329d.png)

If it is meant to be toggleable, perhaps show a message such as `There are no editors` similar to Outline view, otherwise disable toggle

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
We could show a default message if there are no editors and no groups open. Let's keep this open as a feature request for now.

**Comment by JohanssonDaniel** [comment]
Hi @isidorn I'm looking to make a first contribution to this project. Would this be a good issue to start with?

**Comment by isidorn** [comment]
@JohanssonDaniel yeah, this might be a good issue not 100% sure.
Code pointer https://github.com/Microsoft/vscode/blob/f25e9c1069f964f015b8081a4f5d2357d7a93f9f/src/vs/workbench/parts/files/electron-browser/views/openEditorsView.ts#L45

If it proves more complicated than you anticipated than I would suggest looking for issues tagged with "help-wanted" and "good-first-issue"

**Comment by JohanssonDaniel** [comment]
@isidorn thank you so much. I will look into it and report back!

**Comment by JohanssonDaniel** [comment]
Hi @isidorn I just wanted to give a quick update how my work is going. I have managed to add a message when the open file panel is expanded when there are no open editors, similar to how it is done for the file explorer and outline panels. Right now I am looking into making the message appear directly after the last editor is closed and also how to set the correct height of the expanded open file panel since it is based on the number of open files,
