### ISSUE TITLE
How should `terminal.integrated.shellArgs.windows` and tasks work together?

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#59789]
Full context here: #57452 

It looks like `shellArgs` and tasks are competing. For example:

    "terminal.integrated.shell.windows": "cmd.exe",
    "terminal.integrated.shellArgs.windows": [
        "/k",
        "C:\\devel\\fresh\\echo.bat"
	]

and

      {
            "taskName": "echosomething",
            "type": "shell",
            "command": "echo",
            "args": [
                "HERE"
            ]
    }

both `echo.bat` and `echo HERE` will be passed into cmd.exe. Which should be run? Can `shellArgs` coexist with tasks? 

I think we should probably just not use the `shellArgs` when running a task.

**Comment by dbaeumer** [comment]
Users currently can override the shell and shell args in tasks if they are unhappy with what is defined in `terminal.integrated.shellArgs.*` using the `options.shell` property. In the above example tasks builds the following command line

`cmd.exe /k C:\\devel\\fresh\\echo.bat /d /c echo HERE` 

which also wired is something we can easily explain. 

Not honoring shell args will very likely be fine as well but it might break some devs which relied on it.

May be a way forward is to introduce global

`task.shell.executable` and `task.shell.args` settings so that users can control this independently. I do have a feature request for this.

**Comment by iyoumans** [comment]
Yes, adding "terminal.integrated.shellArgs.windows": ["-NoProfile"] to my settings.json worked. Thanks for your help.

**Comment by alexr00** [comment]
We now have a setting for the automation shell, which works around a lot of the issues here.
