### ISSUE TITLE
Suggest widget looks weird today

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#5978]
Maybe the suggest widget could use a smaller line height than the editor?
Also, the text and icon are not vertically centered in each row.

![image](https://cloud.githubusercontent.com/assets/5047891/14910577/f9d58c60-0dee-11e6-8897-f7bdb16d860e.png)

**Comment by alexandrudima** [comment]
My settings:
```
	, "editor.fontFamily": "Hack"
	, "editor.renderWhitespace": true
	, "editor.fontSize": 16
	, "editor.lineHeight": 22
```

**Comment by joaomoreno** [comment]
Yeah I did change something... Thanks for your settings, I'll take a look.

**Comment by joaomoreno** [comment]
This comes from #2465, in which the suggest widget picks up on the line height and font size of the editor itself. I've pushed some changes to alleviate the line height difference in your case. Hope this solves it in the meantime. Would you rather have additional settings, `suggest.fontSize` and `suggest.lineHeight`?

I'll leave this issue open since the suggest does need some layout work to fix the vertical alignment of the icon et al.

**Comment by joaomoreno** [comment]
Reverted the changes from #2465, since it needs more work. 👍

**Comment by alexandrudima** [comment]
I like your approach of deriving the font size and line height from the editor settings more than introducing separate settings.

**Comment by joaomoreno** [comment]
The problem is that the derivation is not so smooth across all platforms... gotta figure that out platform per platform. 👎
