### ISSUE TITLE
Codeblocks stopped formatting and highlighting

### ISSUE THREAD

**Issue by jonesca** [Microsoft/vscode#5982]
- VSCode Version: 1.0.0
- OS Version: Windows 8.1

Steps to Reproduce:
1. start a code block with ```csharp
2. enter code
3. end code block with ```
Although they all seem to work here...

Before updating to version 1.0 code blocks would highlight in md and the preview; not after
when enter { } automatic indenting and formatting would occur; not after the update

Example:
There is no coloring or formatting in this codeblock...
Comments also don't show green like they did before

```csharp
public string LastName { get; set; }
public string FirstName { get; set; }
        
public string FullName
{
get { return FirstName + " " + LastName; }
}
```

**Comment by ugurozturk** [comment]
Code blocks are highlighting here. You probabby have some extension makes problem.

**Comment by jonesca** [comment]
I checked; no extensions are installed... I updated VS Code a couple days ago to 1.0 and have experienced this problem since.  Yes, code blocks do display as expected on GitHub but not in VS Code.

**Comment by golf1052** [comment]
It's because they moved C# support out of the main code base and into its own extension. See https://code.visualstudio.com/docs/languages/csharp#_installing-c35-support

The extension is available here: https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp

You can also refer to issues like https://github.com/Microsoft/vscode/issues/5424#issuecomment-211198084 or https://github.com/Microsoft/vscode/issues/5403#issue-148895180

**Comment by jonesca** [comment]
Thank you; after working through the errors created by my company proxy I was able to install the extension and everything seems to be working again.
