### ISSUE TITLE
textDocument.offsetAt does not work with varied line endings

### ISSUE THREAD

**Issue by NTaylorMullen** [Microsoft/vscode#59846]
- VSCode Version: 1.27.2
- OS Version: Win10 x64

Steps to Reproduce:

1. In windows fill a C# document with:

(Not sure if GitHub replaces newlines with crlf but make sure all the line endings in the snippet below are \n with the exception of the innards of the `#line` declarations)
```
// <auto-generated/>
#pragma warning disable 1591
namespace temp.Pages
{
    #line hidden
    using TModel = global::System.Object;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "/c:/Users/nimullen/Documents/temp/Pages/_ViewImports.cshtml"
using temp;

#line default
#line hidden
    public class _c__Users_nimullen_Documents_temp_Pages_Error : global::Microsoft.AspNetCore.Mvc.RazorPages.Page
    {
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        ((System.Action)(() => {
ErrorModel __typeHelper = default(ErrorModel);
        }
        ))();
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static System.Object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#line 4 "/c:/Users/nimullen/Documents/temp/Pages/Error.cshtml"
__o = DateTime;

#line default
#line hidden
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<ErrorModel> Html { get; private set; }
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<ErrorModel> ViewData => (global::Microsoft.AspNetCore.Mvc.ViewFeatures.ViewDataDictionary<ErrorModel>)PageContext?.ViewData;
        public ErrorModel Model => ViewData.Model;
    }
}
#pragma warning restore 1591

````
2. Call offsetAt with line 35, character 14.

You'd expect to get `1211` but instead `offsetAt` returns 1176

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
VS Code is automatically normalizing line endings when the file is opened. If a file has more than 50% of lines ending with a certain end-of-line-sequence, then that end-of-line-sequence is considered to be the one for the entire file. The file is presented as non-dirty to the user and on the first save, the normalized line endings will be saved to disk.

In the API, this is reflected in `TextDocument.getText` which always returns normalized line endings. Also, when edits are submitted via the editing API (`TextEditorEdit`), even if the edits come in with different line endings (would create a mixed line ending situation), the edits are modified to never allow for that to occur.

Although not accurate anymore (the text buffer does have the capability to represent mixed line endings), you can think of the line ending as a property of the file rather than a property of each individual line.

We have found this to be a decent decision and I'm sorry if it's causing issues. Is it possible to workaround this on your side? Should we improve the documentation in this area?
