### ISSUE TITLE
ZenMode only allows 1 tab per pane showing in latest insiders

### ISSUE THREAD

**Issue by komali2** [Microsoft/vscode#59857]
- VSCode Version: 1.28.0-insider
- OS Version: Debian 9.3

Steps to Reproduce:

1. Open 2 files in separate panes while in zen mode. 
2. Make sure both files are ctrl k + enter (non-italisized)
3. In one pane, try to open another file (ctrl + enter or however you please)
4. Note that the previous file vanishes
5. Exit zen mode and see that it's still there as a tab. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by komali2** [comment]
Occurs for both `    "zenMode.hideTabs": false` and `  "zenMode.hideTabs": true `

**Comment by isidorn** [comment]
This was behaving like this since day 1. I do not really see a difference in behavior here?
Zen mode does not change anything with regards to files being opened, it just changes how they are presented.

When you say previous file vanishes in step 4, it does not vanish it is still there just not shown if you are hiding tabs, if you are showing tabs I still see it.
Pictures / videos would help if you think there is still an issue here. Also make sure you can repro without extensions

**Comment by komali2** [comment]
I'll upload pictures later, when I'm on the machine experiencing this bug. 

If I am "showing" tabs, I don't see it. That's the bug. It doesn't behave this way in previous version for me.

**Comment by isidorn** [comment]
Ok. Post pictures once you have them. Make sure to exit / reenter zen mode since the settings only get applied once you enter zen mode.
And make sure to not have any other funky settings / extensions

**Comment by komali2** [comment]
This issue resolved itself

/shrug
