### ISSUE TITLE
Change publisher ID for an extension

### ISSUE THREAD

**Issue by PranayAgarwal** [microsoft/vscode#59918]
- VSCode Version: any
- OS Version: any

I want to change the publisher of my extension (https://marketplace.visualstudio.com/items?itemName=pranayagarwal.vscode-hack) from a personal to organization account. 

Changing just the name won't work because the ID is still visible in a lot of places in UI. Is there any way to do it without creating a new extension and having people uninstall/reinstall (similar to what VS Code has done in the past for some of its own language extensions)?

**Comment by gjsjohnmurray** [comment]
I devised a way of doing this, piloting it with a small extension called 'The Folding Stuff' which merely adds fold/unfold items to the editor context menu.

That extension was originally published as version 0.0.1 under the ID [georgejamessoftware.thefoldingstuff](https://marketplace.visualstudio.com/items?itemName=georgejamessoftware.thefoldingstuff) but then we managed to register 'georgejames' as an Azure DevOps organization we could use. This is better since our domain is georgejames.com.

First I created a new version of the extension (I chose to number it 0.1.0, but could have picked any other semver) and published it on Marketplace as [georgejames.thefoldingstuff](https://marketplace.visualstudio.com/items?itemName=georgejames.thefoldingstuff), i.e. using the new publisher ID.

Next I published an update (0.0.2)  of georgejamessoftware.thefoldingstuff, stripping out all its functionality and adding the new extension's ID to the `extensionDependencies` array of its package.json. You can view the changes between 0.0.1 and 0.0.2 [here](https://gitlab.com/georgejames/public/thefoldingstuff/tags/0.0.2).

The result is that when someone who had previously installed 0.0.1 of the old ID upgrades their extensions, the 0.0.2 stub gets installed and pulls in the replacement (0.1.0 of the new ID) which is already available on Marketplace (because it was published first).

The 0.0.2 stub has a title and a README that explains why it's there, recommending that first-time users don't install it but instead look for the superseding one. Users of the original one can simply uninstall 0.0.2 because it has done its job of installing 0.1.0 of the new extension.

I hope the above write-up may be useful to others.

**Comment by PranayAgarwal** [comment]
Thanks @gjsjohnmurray, this is really helpful

**Comment by prashantvc** [comment]
publisher_name.unique_identifier is the unique identifier for an extension. Updating it is not a common scenario on the Marketplace.

You can contact the Marketplace support to update identifier or transfer the extension to different publisher without loosing download counts

**Comment by chrisdias** [comment]
not sure if there is anything to do here. if you need to change the publisher then you/we can contact the marketplace.
