### ISSUE TITLE
Code formatting not functional after upgrade to Windows 10 1809

### ISSUE THREAD

**Issue by CallumRaabe** [Microsoft/vscode#59968]
All forms of code formatting seem to be non-functional after upgrading to Windows 10 1809. I've managed to reproduce this error across two PCs and both stable and Insider builds, along with a clean reinstall of both versions (including deleting extensions and user data)

- VSCode Version: 1.27.2 (user setup), 1.28.0-insider (user setup)
- OS Version: Windows 10 17763.1

Steps to Reproduce:

1. Update Windows 10 to October 2018 (1809) update
2. Install relevant language extension to VS Code and optionally set up automatic formatting
3. Open or create new file (and assign it to a specific language)
4. Create obvious formatting error (e.g. excessive indentation)
5. Try to trigger formatting via keyboard shortcut or an automatic method (e.g. when saving) 

Launching without extensions does not affect this error as the function relies on official extensions to provide the formatting.

![image](https://user-images.githubusercontent.com/18474640/46476509-b9bb2a00-c82b-11e8-929e-5b1ea868c081.png)

Image shows an error stating that the document formatter is missing when it is installed and active, this error only appears on files that have not been previously saved. Nothing appears if it is a previously saved file, it just does not function. This appears to be happening regardless of language rather than specifically the C/C++ plugin

**Comment by rebornix** [comment]
@CallumRaabe based on what you described, it looks like a C++ extension issue, please file issues there first.

**Comment by TanxyRogue** [comment]
I seem to have encountered a similar issue except in this code no longer opens at all.
When I open the program the cursor turns to the loading cursor and then....... 
Nothing. 
No white or black screen nothing. 
So I decided to check the task manager and as I feared, when I double click vs code it appears for a second before disappearing. 
It seems it definitely had something to do with the c++ extension because I remember Tinkering with it yesterday. However I don't know for sure if the windows 1809 has anything to do with but I installed it a few days ago so it definitely is suspect plus you factor in the news about it.
Am afraid I might have to Uninstall vs code but I'm definitely avoiding that for now, as I don't have a network connection to reinstall all my plugins..😧😧

**Comment by CallumRaabe** [comment]
I mentioned in my original post it didn't seem to be isolated to just the C/C++ extension, the same error occurs with C# and Java files (both brand new files and tests with my previous work) with their respective extensions installed from my testing on both my affected PCs, and the 'missing formatter' error appears to be appearing on existing files now (tested with C, C# and Java files)
