### ISSUE TITLE
Menu license links to non Open Source license

### ISSUE THREAD

**Issue by jsmanrique** [Microsoft/vscode#60]
I've just downloaded it:
```
Version 0.10.1
Commit df352367df2efcfa9d602d471e4e2f42140a0f05
Date 2015-11-17T15:21:23.766Z
Shell 0.34.1
Renderer 45.0.2454.85
Node 4.1.1
```

The license link points to *non Open Source* license:
https://code.visualstudio.com/license#vscode

For example:
```
[...] users cannot opt out of data collection [...]
You may not
* work around any technical limitations in the software;
```

**Comment by chrisdias** [comment]
This is correct. VS Code the product has a different license than the code in the repository.

**Comment by hartwork** [comment]
@chrisdias, could some clarification be added to that page?
Also, what's the difference between the product and the source code?
Please re-open this ticket.

**Comment by jangelfdez** [comment]
So, If we get the code from the repo is OSS but if we get the executables they aren't, isn't it? It makes no sense at all :S

**Comment by alexandrev** [comment]
+1 to reopen and talk about this issue. I hope this is a 'bug' and not a decision because it makes no sense at all.

**Comment by lontivero** [comment]
+1 to reopen it. This is not clear enough.

**Comment by chrisdias** [comment]
Thanks for the interest in this topic and I apologize for not commenting sooner, I’ve been on vacation and just getting through my backlog. Let me try to provide more details behind our thinking here.

When we set out to open source our code base, we looked for common practices to emulate for our scenario. We wanted to deliver a Microsoft branded product, built on top of an open source code base that the community could explore and contribute to. 

We observed a number of branded products being released under a custom product license, while making the underlying source code available to the community under an open source license. For example, Chrome is built on Chromium, the Oracle JDK is built from OpenJDK, Xamarin Studio is built on MonoDevelop, and JetBrains products are built on top of the IntelliJ platform. Those branded products come with their own custom license terms, but are built on top of a code base that’s been open sourced.

We then follow a similar model for Visual Studio Code. We build on top of the `vscode` code base we just open sourced and we release it under a standard, pre-release Microsoft license. 

The cool thing about all of this is that you have the choice to use the Visual Studio Code branded product under our license *or* you can build a version of the tool straight from the `vscode` repository, under the MIT license. 

Here's how it works. When you [build](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source) from the `vscode` repository, you can configure the resulting tool by customizing the [`product.json`](https://github.com/Microsoft/vscode/blob/master/product.json) file. This file controls things like the Gallery endpoints, “Send-a-Smile” endpoints, telemetry endpoints, logos, names, and more.  

When we build Visual Studio Code, we do exactly this. We clone the `vscode` repository, we lay down a customized `product.json` that has Microsoft specific functionality (telemetry, gallery, logo, etc.), and then produce a build that we release under our license.

When you clone and build from the `vscode` repo, none of these endpoints are configured in the default `product.json`. Therefore, you generate a "clean" build, without the Microsoft customizations, which is by default licensed under the MIT license (note, i made [this commit](https://github.com/Microsoft/vscode/commit/9dd095c27ea79f526b054f741bb52fa62fae80a9) to help make this more clear).

I hope this helps explain why our Microsoft branded Visual Studio Code product has a custom product license while the `vscode` open source repository has an MIT license. Last, I apologize for the fact that the naming of “Visual Studio Code”, “VS Code” and the `vscode` repository are so similar, I think it contributed to the confusion. 

Chris

**Comment by SteveALee** [comment]
@chrisdias Thanks for explaining. 

It would be good to ensure any differences other than Branding / telemetry are clearly documented. At least we don't need to be concerned that this is a 'bait and switch' manoeuvre as the branded version is free :)

**Comment by chrisdias** [comment]
@SteveALee You can look at the `product.json` that is installed with the Visual Studio Code product to see what we configure.

**Comment by SteveALee** [comment]
Hah, of course. Thanks.

**Comment by erkinalp** [comment]
@chrisdias: Unbranded builds(sth like Iceweasel) would be a showstopper here.

**Comment by chrisdias** [comment]
@erkinalp i'm not sure i understand the comment. what is the showstopper?

**Comment by erkinalp** [comment]
@chrisdias: It would be, but it is not now, i.e. a wish.

**Comment by NickCraver** [comment]
@chrisdias This distinction shouldn't be buried in an issue somewhere. The branding isn't changing, and the names (and abbreviations) everyone interchanges will forever perpetuate this licensing confusion. This needs to be content readily available from https://code.visualstudio.com/License. A blurb at the top with a link to the repo license would fix this for an increasing number of people.

Right now, if I pull up the VS Code license (at https://code.visualstudio.com/License), I'm going to read it and think:

> Microsoft does not distribute, license or provide any warranties for any of the third party packages.

Well that seems wrong. There's a Marketplace explicitly for distributing those extensions. What is this trying to say?

> You may not: work around any technical limitations in the software

...so I can't fix something and make a PR? Because it'd be illegal.

> You may not: remove, minimize, block or modify any notices of Microsoft or its suppliers in the software.

Does this mean I can't click cancel on an update? That minifies a Microsoft notice.

> You may not: share, publish, or lend the software, or provide it as a hosted solution for others to use, or transfer the software or this agreement to any third party

So I can't put the installer on a share? Sections 1 and 5 are in conflict as to what a user can do.

...we're all developers here. We all know this is confusing. Look at the laundry list of issues relating to this one linked in history. Can we please fix this with a small blurb of text at the top of https://code.visualstudio.com/License?

**Comment by chrisdias** [comment]
Hi @NickCraver,

Thanks for posting this suggestion. I can see how the product license can generate questions for developers wishing to contribute to the product.

As a result, I've updated the [stable](https://code.visualstudio.com/license) and [insider](https://code.visualstudio.com/license) pages to clarify that the license is for VS Code the product and that the source is licensed under the MIT license. The localized license pages will be updated as soon as I get the translations back.

Chris

**Comment by NickCraver** [comment]
Thanks Chris, that little blurb is a fantastic addition. I really appreciate you improving this!

**Comment by SamB** [comment]
Um, wouldn't this get less dupes if it was left open until such time as MS realizes that they can maintain their brand in a less confusing and contradictory manner?

**Comment by MrVegetables** [comment]
Anyone who accepts that proprietary license is legally prohibited from contributing to this project. The license states: "You may not...reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software". Accessing this GitHub repository is an attempt to derive the source code for the software.

**Comment by MrVegetables** [comment]
@chrisdias "You can look at the `product.json` that is installed with the Visual Studio Code product to see what we configure." Indeed we *can*, but are we permitted to? The Berne convention or your proprietary license would seem to apply and make anything in your `product.json` file copyrighted and forbidden to use, so we aren't allowed to just copy and paste it into ours. I searched through the source code with grep but couldn't find an example in this repository.

**Comment by jsolisu** [comment]
¿Can we modify the _product.json_ file on "Code OSS" **without restriction** acording to MIT License?

**Comment by MrVegetables** [comment]
@jsolisu We can, but my point is that the `product.json` included in Microsoft's pre-built deb is governed by their proprietary license, meaning we are not allowed to copy its text into the MIT-licensed version and thus cannot use the extensions gallery while retaining our freedoms.

**Comment by jsolisu** [comment]
@MrVegetables Thanks. "Code OSS" Without extensions is useless...

**Comment by aidan-fitz** [comment]
@chrisdias With all due respect, this sounds like an _[argumentum ad populum](https://en.wikipedia.org/wiki/Argumentum_ad_populum)_: since other companies are re-licensing their open-source apps under proprietary EULA's (case in point: Oracle, Google, and JetBrains); therefore, we should do it too. You're not making any money from sales of this product, and adding a custom look and feel and extension gallery doesn't seem to justify re-licensing it in this way. As a counterexample, both the source and binary distributions of [Atom](https://atom.io/) come with the package manager _and_ the MIT License. What gives?

**Comment by chrisdias** [comment]
I have not played yet!  Did have good pizza though, go figure ;)

**Comment by aidan-fitz** [comment]
Looks like you sent this reply to the wrong email

*Aidan Fitzgerald*
Peer Advisor, College of Engineering
Cornell University

*Any sufficiently advanced software is indistinguishable from artificial
intelligence.*
LinkedIn <https://www.linkedin.com/in/aidan-fitz> · GitHub
<https://github.com/aidan-fitz>

**Comment by simoniz0r** [comment]
Honestly, this is extremely confusing.  So I can't distribute the binaries that are built by you guys, but I can build it from source and distribute the build that I've made myself?  And the only real difference between these builds is the logo, telemetry, and like two other things??  This makes zero sense to me.

After discovering this, I'm very much considering moving to an editor with a much more open license.  This is just a little silly.
