### ISSUE TITLE
renderBody/layoutBody is called despite being collapsed

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#60018]
* have a viewlet panel
* collapse it
* reload workbench
* :bug: `renderBody` and `layoutBody` is being called even though the panel is collapsed

**Comment by joaomoreno** [comment]
Will not remove the `renderBody` since it will break the user assumption that the body is rendered on view creation. `layoutBody` is easy.

**Comment by jrieken** [comment]
> Will not remove the renderBody since it will break the user assumption that the body is rendered on view creation.

Well, it's not that we don't know those or wouldn't be able to add a flag...

**Comment by jrieken** [comment]
Sorry to reopen but layout is still called 10 times, always with the same dimensions...

**Comment by joaomoreno** [comment]
Yeah we can also cache sizes, tho we're exchanging time paper cuts for memory paper cuts.

**Comment by joaomoreno** [comment]
Had to revert https://github.com/Microsoft/vscode/commit/febf978c2834da84531dfc3759988845c15ef758 due to https://github.com/Microsoft/vscode/issues/61450

We need to improve this and use a width/height combination and cache on those individually. Created https://github.com/Microsoft/vscode/issues/62387
