### ISSUE TITLE
Update failing

### ISSUE THREAD

**Issue by OverLordGoldDragon** [Microsoft/vscode#60071]
When opening a file, VS Code attempts to update, displays the following error: https://puu.sh/BGGZl/282f97f70d.png OS info: https://puu.sh/BGH3L/3e22323f78.png 

The issue's persisted for ~2 weeks now. Folder filepath added to antivirus exceptions, no avail. The program otherwise works fine, with no detected problems. Error log attached.

[vscode-inno-updater-1538847353.log](https://github.com/Microsoft/vscode/files/2453246/vscode-inno-updater-1538847353.log)

**Comment by totkeks** [comment]
I got the exact same issue. Same error messages, same log file, except the user name in the profile folder.

Task manager shows no running code.exe tasks, but when uninstalling / trying to delete the "AppData\Local\Programs\Microsoft VS Code" folder, even the explorer complains that it can't delete the folder, because code.exe and inno_updater.exe are still in use. Weird thing is, the task manager does not show it running. Neither for my user, nor for any other user or the system itself.
I even just checked with sysinternals' process explorer. No handle for code.exe or inno_updater.exe

**Comment by joaomoreno** [comment]
@OverLordGoldDragon @totkeks Did you get a `Retry`/`Cancel` message box before getting that error?

**Comment by OverLordGoldDragon** [comment]
@joaomoreno It occurs after closing VSCode - where it attempts to update with the progress bar stuck empty at 0%, then closes in 1-2 mins and displays the error. When I attempt to manually update with VSCode open, I get a window with 'Retry', 'Abort', and 'Ignore' options. Furthermore, I also observe exactly what @totkets described.

**Comment by totkeks** [comment]
@joaomoreno Okay, I just started from scratch with a 1.27.2 UserSetup-x64. I completely removed the `AppData\Local\Programs\Microsoft VS Code` folder, which was still containing code.exe and inno_updater.exe after uninstalling.

Next I start code, my last project loads and the cog in the bottom left shows the clock icon. I wait until it switches to a "1". Next I click "Restart to Update...".
The "Updating VS Code..." mini windows appears and code is closed.

After roughly a minute this window appears:
![image](https://user-images.githubusercontent.com/2941389/46715245-7e6f8f80-cc5f-11e8-8c7e-4b2bbbd0fe1a.png)
The text says roughly translated "process can't access the file, because it is used by another process"
"Wiederholen" is German for retry. And "Abbrechen" is German for cancel. I select retry.

After roughly another minute the same window appears again. I select retry again.

After roughly another minute the window appears again. I select cancel this time. Now this window appears: 
![image](https://user-images.githubusercontent.com/2941389/46715401-1e2d1d80-cc60-11e8-827d-299c28683deb.png)

I select ok, the window disappears as well as the little "Updating VS Code..." window.
Code is automatically started again, still running the old 1.27.2 version.

Additionally this window pops up after roughly another minute:
![image](https://user-images.githubusercontent.com/2941389/46715459-57fe2400-cc60-11e8-91dd-6562c176d999.png)
Rough translation: "Error occured when replacing an existing file: DeleteFile failed; Code 32.
The process can't access the file, because it is used by another file.
Press retry for another try, ignore to skip this file (not recommended) or cancel to abort the installation".
I select retry.

After a couple of seconds the windows pops up again. I select cancel.

No more windows / errors appear. Code also didn't check for the update again (no clock on the bottom left cog).

**Comment by wazzamatazz** [comment]
I have seen this exact same behaviour (file is still in use) since switching to the user installer, whenever Code tries to update itself. If I download the standalone installer and run it after an automatic update fails, I see the same issue. I can update using the standalone installer after a reboot.

**Comment by totkeks** [comment]
> I have seen this exact same behaviour (file is still in use) since switching to the user installer, whenever Code tries to update itself. If I download the standalone installer and run it after an automatic update fails, I see the same issue. I can update using the standalone installer after a reboot.

Yes, that's because something locks the code.exe file and never releases it. A reboot does this.

**Comment by wazzamatazz** [comment]
Sorry, missed your reply until now, but I saw the same behaviour again when updating to version 1.28.1. When I got the "The process cannot access the file..." message I went to the Code install folder and tried renaming Code.exe, just to see what would happen. I got a message saying that it was locked by System:

![image](https://user-images.githubusercontent.com/7179614/46949558-79a94200-d08a-11e8-8a2c-757232a5cc40.png)

Searching for handles on Code.exe in Process Explorer returns zero results.

**Comment by theyo** [comment]
Same error here as well. This has happened to me when updating twice in a row now.

My current version information:
Version: 1.28.1 (user setup)
Commit: 3368db6750222d319c851f6d90eb619d886e08f5
Date: 2018-10-11T18:13:53.910Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

With the updater is running, I did a search in Process Explorer for Code.exe and it shows that there is an open handle from the System process and I am unable to kill it (Access Denied).

![image](https://user-images.githubusercontent.com/2397638/47395054-fb781b80-d6d9-11e8-8a70-fb6c903a873a.png)

Rebooting does not resolve the issue.

**Comment by arpadbarta** [comment]
Yoppe, same here, please guys look into it it has been months now... The only solution that I found is that change the install directory on fresh install, but I should not be doing a reinstall for every update....
![image](https://user-images.githubusercontent.com/6329203/47601338-8b1e1280-d9d7-11e8-9747-aeb912f503a3.png)

**Comment by mlafleur** [comment]
Has there been any progress on this? I'm facing the same issue today.

**Comment by joaomoreno** [comment]
There are two main issues surrounding this:

- #60697
- #47841

Both can be worked around by disabling background updates: `update.enableWindowsBackgroundUpdates: false`

**Comment by totkeks** [comment]
I might add that the workaround requires a restart of the PC if code.exe is still locked by the hidden process.

@joaomoreno I completely reinstalled my windows 10 (for some other reason) and all was fine for one or two updates. but now the error on update is back. Is there any way I could help debugging this?

**Comment by joaomoreno** [comment]
@totkeks Any chance you remember what you have installed between the two phases (working vs. not working)?
