### ISSUE TITLE
File renaming is inaccessible

### ISSUE THREAD

**Issue by Neurrone** [Microsoft/vscode#60087]
Issue Type: <b>Bug</b>

1. Press f2 to rename a file.

I expect NVDA to read it like it would any edit field, but arrowing around results in no feedback at all.

VS Code version: Code - Insiders 1.28.0-insider (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-03T12:44:29.343Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (10.04GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|40%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.0
python|ms-|2018.8.0
cpptools|ms-|0.19.0
rust|rus|0.4.10
markdown-preview-enhanced|shd|0.3.8

</details>

**Comment by isidorn** [comment]
@Neurrone I just tried this and I can repro.
However after trying it with our latest VSCode which uses Electron 3.0 version I see this is fixed. So those are great news.
The issue here is how we are doing accessibility for our trees inside vscode, we do not use tabindex inside the tree such that the user would not be lost once he is inside a large tree, but we use the aria-active descendent. And there seemed to be an issue that no all details are read out for active descendent items (since they do not have the tabindex property). New chrome seems to fix this and the input box is properly respected and read out if it is the active descendent in a tree.

In case you want this fixed already and not wait for us to update to electron 3.0 you can use our experimental build:
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

@bpasero fyi

**Comment by Neurrone** [comment]
@isidorn thanks.

**Comment by isidorn** [comment]
We have updated to electron 3.0 and I have verified that this is now properly read out.
@Neurrone we have also rewritten the explorer. So it would be great if you have some time to do an accessilibity pass over the explorer in vscode insiders and let us know how it feels.

**Comment by Neurrone** [comment]
Thanks @isidorn. I've filed bugs for explorer in #67156.

**Comment by isidorn** [comment]
Thank you!
