### ISSUE TITLE
debug.inlineValues does not appear to honour line/column information from scope

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#60150]
I'm trying to improve the display of `debug.inlineVariables` for Dart. I saw that would code provide [Source and line/column information](https://github.com/Microsoft/vscode-debugadapter-node/issues/78) for a `Scope` to control where the inline values would appear, but it seems to be ignored in my testing.

I've hard-coded some values from line 6-11:

<img width="889" alt="screen shot 2018-10-08 at 4 23 07 pm" src="https://user-images.githubusercontent.com/1078012/46618149-b0290f00-cb16-11e8-947a-c57ba6e6717f.png">

But when I run, I still see the inline values outside of that range:

![screen shot 2018-10-08 at 4 22 57 pm](https://user-images.githubusercontent.com/1078012/46618169-bdde9480-cb16-11e8-9944-7a0febccb91f.png)

**Comment by isidorn** [comment]
As far as I remember we decided to ignore stack frame ranges for inline sources and hover since the stack frame ranges were quite incorrect for node.
Here's a code pointer
https://github.com/Microsoft/vscode/blob/e2027598992e56d7f6f6f26f804d53449ea1a2ee/src/vs/workbench/parts/debug/electron-browser/debugEditorContribution.ts#L618

PR that fixes this would be welcome.
The PR would only change the behavior for inlineValues, not for debug hover (due to some other closed issues which I do not want to dig out)

**Comment by DanTup** [comment]
@isidorn I don't entirely understand what you mean. The code you linked looks like it is filtering based on ranges, so what needs fixing?

(I was under the impression that these fields were added [specifically to support inline debugging](https://github.com/Microsoft/vscode/issues/12256) so I'm wondering if I've misunderstood something, or implemented it incorrectly?)

Also:

> we decided to ignore stack frame ranges for inline sources

What do you mean by "inline sources"? These are files on disk - my mapToSource function is returning sources with paths - but it's possible I'm doing that wrong. If you think it should work for sources-on-disk lmk and I'll check I'm not doing something wrong in there.
