### ISSUE TITLE
issue with the frenche locale and shortcuts

### ISSUE THREAD

**Issue by Navis-Raven** [Microsoft/vscode#60391]
In the french locale vscode (french plugin) file menu there is an issue for the french plugin, the Ctrl shortcuts commands are at the wrong place.

![image](https://user-images.githubusercontent.com/15887222/46697171-56a70a00-cc14-11e8-9e7d-a275dab4570c.png)

I've tested two of them and they are wrong and not valid (Ctrl + K Ctrl + O ; and Ctrl + K S)

I don't know if there is this issue in other menues

**Comment by Navis-Raven** [comment]
linked to this https://github.com/Microsoft/Localization/issues/28#issuecomment-427963848

**Comment by egamma** [comment]
This is a limitation of the native menus, they do not support chorded key bindings.
On windows you can switch to the custom menus they do not have this issue.

**Comment by Navis-Raven** [comment]
@egamma why the bot closed the issue automatically ?

**Comment by Navis-Raven** [comment]
@egamma I did not understand what you said, can you explain more please ?

**Comment by egamma** [comment]
It is an upstream limitation of the way Electron renders the keyboard short cuts. VS Code cannot fix the native menu behaviour. It is not clear on which platform you are, but on Windows that problem does not exist anymore since there is a custom menu implementation.

![image](https://user-images.githubusercontent.com/172399/46762397-39873f80-ccd7-11e8-8ade-07b6f531031e.png)

> @egamma why the bot closed the issue automatically ?

Also when an issue is as assigned the `as designed` label then the bot helps the inbox tracker to close the issue.

**Comment by Navis-Raven** [comment]
yes the issue has been solved by the new version

![image](https://user-images.githubusercontent.com/15887222/46910732-ef59c480-cf49-11e8-80e1-762a4c446684.png)

**Comment by Navis-Raven** [comment]
@egamma  but how to use the shortcuts 

Ctrl+K F is it Ctrl+K then F or like Ctrl+K+F
and
Ctrl+K Ctrl+O 

I don't really understand
