### ISSUE TITLE
Hover popups while debugging don't work when using Unity3D.

### ISSUE THREAD

**Issue by Jasper76** [Microsoft/vscode#6042]
- VSCode Version: 1.0.0
- OS Version: OSX 10.11.3
- Unity 5.3.4f1

Steps to Reproduce:
1. Configure Visual Studio Code with Unity as described at: https://code.visualstudio.com/Docs/runtimes/unity
2. Start debugger and set breakpoint

See screenshot: Hovering on the method parameter works and I can see its values.
Hovering over the private object variables (see _startPiece, _id, etc.. in the screenshot) does **not** work. No hover popup is displayed.

![schermafbeelding 2016-05-02 om 15 27 56](https://cloud.githubusercontent.com/assets/14895933/14955631/8c08148e-107b-11e6-9793-9dbd5b2674b9.png)

**Comment by isidorn** [comment]
The issue here is that the debug hover has no AST understadning of the language and thus has some limitations. Some of these limiations include looking for variables only inside non-expensive scopes, not showing hover when there are duplicates and so on...
It is on our backlog to improve the debug hover.

In the meantime ping @lukaszunity to check if the unity debugger could support [evalute on hover](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L508). The issue with using this flag is that the user could by acciddent mutate the state of his program by simply hovering

**Comment by liucailin** [comment]
It's almost one year... any updates?

**Comment by Socapex** [comment]
+1

**Comment by JimmyDeemo** [comment]
I too would really like this functionality to be implemented. May I as what the barriers for this currently are? Does the comment from @isidorn still stand?

**Comment by isidorn** [comment]
@JimmyDeemo yes. To repeat the debug hover tries to match what is being hovered over with the variables inside scopes. If the names do not match it will not show anything, in order to work around this the extension can say it supports evaluate on hover and everything should work nicely.

**Comment by JimmyDeemo** [comment]
Ah I see, so the Unity Debugger extension needs to support evaluate on hover. I will see if that has been requested. Thanks.
