### ISSUE TITLE
Black theme, white block appears in the window

### ISSUE THREAD

**Issue by hceny** [microsoft/vscode#60430]
Issue Type: <b>Bug</b>

Black theme, white block appears in the window, the old version does not have this problem. After updating the version, there are problems with the white bars of "maximum", "minimum", "_" and "□", and when the setting menu is selected, the text will be Part does not display.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (12.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.28.2
csharp|ms-|1.16.2

</details>

**Comment by rakhi2104** [comment]
Any screenshots for more details ?

**Comment by bplubell** [comment]
@hceny-architect does this show the same thing that you are seeing?

Typing command:
![image](https://user-images.githubusercontent.com/14831159/46746058-18850700-cc63-11e8-83d2-960cd8859e33.png)

After "clear" command:
![image](https://user-images.githubusercontent.com/14831159/46746076-263a8c80-cc63-11e8-9296-6814b00dfe4e.png)

If so, here are some more details I have found:
- Happened after latest vscode update (1.28.0) and Windows 10 update (1809) - may only be caused by one, but I do not know which
    - My OS version: Windows_NT x64 10.0.17763
- Happens with Powershell
- Does not happen with Cmd (`"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe"`)
- Happens with "terminal.integrated.rendererType" set to either "canvas" or "dom"
- Affects all themes (visually similar, but different colors)
- May be related to #57803 

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.69GB (1.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>
<br>
If this is not the same issue you have, let me know and I will post a new issue.

**Comment by Tyriar** [comment]
Looks like https://github.com/Microsoft/vscode/issues/57803, let me know if that doesn't match what you're seeing.

**Comment by bplubell** [comment]
While it may have the same root cause, it seems to be a different issue. This seems to have to do with styling the console while #57803 seems to be an initialization/startup issue.

**Comment by hceny-architect** [comment]
![image](https://user-images.githubusercontent.com/26370983/46777740-2b6f0880-cd43-11e8-80c7-2d6c7f2a8eff.png)
 The above is my screenshot, I will have this problem after I started the software. And it still appears after reinstalling the software.
@rakhi2104 @bplubell @Tyriar @doudou

**Comment by hceny-architect** [comment]
Due to the difference in time zone, my comment interval is longer.

**Comment by bplubell** [comment]
@Tyriar This is a very different issue than I described and seems like it should be re-opened. It has to do with the custom title bar, not the integrated terminal.

**Comment by sbatten** [comment]
@hceny-architect as this is rendering issue that is difficult to reproduce, it can be hard to know the root cause if it is upstream. We other issues reporting similar strange behavior. Please see this comment https://github.com/Microsoft/vscode/issues/59977#issuecomment-428440740 to try one of our exploration builds to see if this reproduces for you.

**Comment by hceny-architect** [comment]
@sbatten Ok, thank you very much, I am trying to reinstall this version to see if there will be similar problems.

**Comment by hceny-architect** [comment]
@sbatten I found this version (visual studio code - exploration), there is no such problem that I have feedback.

The following is the software information:

- Version: 1.28.0-exploration (user setup)
- Commit: 5a736c2e4904ed114fae2d5941508505f53afc66
- Date: 2018-09-28T09:34:50.873Z
- Electron: 3.0.1
- Chrome: 66.0.3359.181
- Node.js: 10.2.0
- V8: 6.6.346.32
- Architecture: x64

After the installation, I upgraded to the latest version:

- Version: 1.29.0-exploration (user setup)
- Commit: d27719015aae32e9cec06eaac23d7a9c2272ca46
- Date: 2018-10-11T08:30:13.517Z
- Electron: 3.0.4
- Chrome: 66.0.3359.181
- Node.js: 10.2.0
- V8: 6.6.346.32
- Architecture: x64

This is the new version:

![image](https://user-images.githubusercontent.com/26370983/46927578-a77d8f00-d068-11e8-82fe-8f0348373c13.png)

Both versions did not find the problem I mentioned earlier, but the old version I detected a version update, this problem still exists after the update.

This is the old version:
- Version: 1.28.1 (user setup)
- Commit: 3368db6750222d319c851f6d90eb619d886e08f5
- Date: 2018-10-11T18:13:53.910Z
- Electron: 2.0.9
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41
- Architecture: x64

![image](https://user-images.githubusercontent.com/26370983/46927592-bc5a2280-d068-11e8-9fc5-955d39e8292d.png)

**Comment by sbatten** [comment]
@hceny-architect the issue appears to be an electron rendering issue, as you can see the builds that did not have the issue were using electron 3 and the build that experiences the issue is using electron 2.

**Comment by leslieeilsel** [comment]
I think I found a temporary solution!
Step1: Open CMD terminal, edit properties, check this option
![](https://s2.ax1x.com/2019/04/17/Axovy8.png)
Step2: Restart the system

#### Before：
![](https://s2.ax1x.com/2019/04/17/AxoXSP.png)
#### After：
![](https://s2.ax1x.com/2019/04/17/AxojQf.png)

#### System Info
Windows 10 1809

#### VSCode Info
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
