### ISSUE TITLE
Cleanup list/tree mouse & keyboard navigation

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#60520]
After discussing this with @bpasero, we've come up with the following steps for the list widget. Let's forget about the current tree widget as we'll soon kill it and the new one is built on top of the list

- [ ] Element focus should be an internal list concept (there should be no `setFocus` or `getFocus` methods). Interaction with the list should be configurable per device: mouse vs keyboard. The following two list options should be introduced:
  - `singleClickSelection` (defaults to `true`) will configure whether single clicking a tree element would set it to selection. Double click will always set it to selection.
  - `lightKeyboardNavigation` (defaults to `true`) will configure whether keyboard navigation would set elements to be focused vs. selected.
- [ ] When not using a keyboard controller, the list should add the set of focused elements to the keyboard event which will bubble to the outside.
- [ ] The keybinding service should forward that extra event information to the command which is about to execute. This way, list commands always have the correct context when running.
- [ ] The `List` selection events should forward the related browser events which caused those selection changes.
- [ ] The `WorkbenchList` is responsible for mapping **selection** events into **open** events. It should also expose a `open()` method which commands can call into.
- [ ] The `WorkbenchList` is also responsible for listening to the proper workbench configurations and configure the `List` accordingly.
- [ ] List/tree widget users should only rely on `open` events and forget about focus and selection altogether.
- [ ] All the `focusNext`, etc, calls should be renamed to `navigateNext`. The only remaining calls of those would be `getSelection()` and `setSelection()`.

![image](https://user-images.githubusercontent.com/22350/46743105-a1726180-cca8-11e8-88f6-c856ed93eecc.png)

**Comment by bpasero** [comment]
@joaomoreno I would add to the `open` event: a way to trigger different `open` styles:
* `default` (just open)
* `alternative` (e.g. "Open to the Side" via Alt+click)
* `strong` (better naming here? e.g. via double click)

**Comment by cleidigh** [comment]
@joaomoreno 
@bpasero 
Hoping you guys don't mind if I add some input here since I have been dealing with a variety of navigation and accessibility issues for the custom selectbox.  I see this is set for backlog but, I wanted to raise my hand before it's too late...

Keyboard/Navigation:
- support disabled entries (this was the main reason I had to do a keyboard handler for custom select box)
- first character navigation - same as above modeling select behavior

Accessibility:
- Appropriate additional ARIA roles (listbox, , combobox, grid) - have to match navigation methods
- Support labeledby, describedby and different locations for aria-label (labeling differences with voiceover)

I have been working on the accessibility issue by overwriting both container and element roles (undesirable).  While I am still dealing with voiceover versus NVDA, I am close.  Again, I am only mentioning here since the things are so tied together.

I will of course gladly contribute 👺 !

**Comment by joaomoreno** [comment]
@cleidigh Though absolutely valid, those would be separate feature requests. This item is more about cleaning up some ugly code, not implementing new features.

**Comment by cleidigh** [comment]
@joaomoreno 
Got it.  I will continue working on these and PR when appropriate. 👍
