### ISSUE TITLE
How to set keywords highlight for each language ?

### ISSUE THREAD

**Issue by g30225579** [Microsoft/vscode#6054]
- VSCode Version: 1.0.0
- OS Version: windows 10

I downloaded a theme from "http://tmtheme-editor.herokuapp.com/#!/editor/theme/Eclipse", but it seems that some setting have no effect ?

![1](https://cloud.githubusercontent.com/assets/17231597/14974152/870cb20c-1123-11e6-9fe5-17b3b19c44ae.png)

**Comment by g30225579** [comment]
Same problem on editplus theme.

![html](https://cloud.githubusercontent.com/assets/17231597/14976358/855cf4e8-113d-11e6-9443-ab90d1a70b5c.jpg)
![vs_html](https://cloud.githubusercontent.com/assets/17231597/14976367/9ffc6b8a-113d-11e6-8c77-5e877926a6ec.jpg)

![css](https://cloud.githubusercontent.com/assets/17231597/14976375/b942d926-113d-11e6-94ea-b0b016d1750c.jpg)
![vs_css](https://cloud.githubusercontent.com/assets/17231597/14976379/bfc5dab4-113d-11e6-9296-359ea3aab976.jpg)

![js](https://cloud.githubusercontent.com/assets/17231597/14976384/c93d92f8-113d-11e6-9c28-a261d689ea21.jpg)
![vs_js](https://cloud.githubusercontent.com/assets/17231597/14976388/d1c3a25a-113d-11e6-8f87-78f13b89760e.jpg)

![php](https://cloud.githubusercontent.com/assets/17231597/14976389/d8469d58-113d-11e6-9536-b68267f0a009.jpg)
![vs_php](https://cloud.githubusercontent.com/assets/17231597/14976392/de0483e0-113d-11e6-870e-f44aa970229b.jpg)

**Comment by aeschli** [comment]
The differences that you are seeing in JS and HTML are because we have different tokenizers than http://tmtheme-editor.herokuapp.com.
The scopes that tokenenizers should emit are only loosely specified, so there's no easy right or wrong. But if you have a specific request, please make a request with:
- code example showing a specific token
- the scope you are expecting for that token
