### ISSUE TITLE
Source Control Providers showing up when not required

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#60569]
Issue Type: <b>Bug</b>

- Open a repo, make changes
- Open a file from another repo in the same VS Code window

Now, the Source Control Providers section shows up. I dont see why this is relevant in the above scenario. I am not in multi-root mode.

![image](https://user-images.githubusercontent.com/16890566/46771210-5c016480-cca7-11e8-976f-2b4592f43358.png)

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-04T16:47:36.731Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by joaomoreno** [comment]
We've automatically detected repositories as files are opened since a long time, independently from multi-root. Just open a folder containing multiple folders, each a git repo: it's single folder mode, but multiple repositories are detected.

You can use the `git.autoRepositoryDetection` setting to control automatic repository detection.
