### ISSUE TITLE
VSCode frequently crashes when ctrl+P searching after 1.28

### ISSUE THREAD

**Issue by EklipZgit** [Microsoft/vscode#60672]
Issue Type: <b>Bug</b>

What I'm seeing: general slowness and freezups, delay in text showing up / results showing up when ctrl+p searching (when it works), and frequent crashes when ctrl+P searching. When the ctrl+P crashes happen, the sequence of events is like this:
1. VSCode is working fine, editor is working.
2. Ctrl+P is pressed. The 'default' results show up as normal (recently opened files etc).
3. I begin typing, but the results do not change / get filtered as quickly as normal.
4. About 4-8 characters in, the textbox stops updating with my typed input, with the 'default' results still the only shown results.
5. Hangs for 30 seconds before the 'not responding' prompt shows up.

Looks something like this when the hang initiates:
![image](https://user-images.githubusercontent.com/7151703/46829704-506b7780-cd53-11e8-885b-4ee67e0443f7.png)

I noticed a lot more freezups for several seconds than normal starting a week or so ago, but not a semi-consistent ctrl+P crash prior to 1.28.

How to reproduce:
Open a lot of tabs (5-15 seems to be enough). I tend to have Json tabs and powershell tabs open, and I notice that it tends to happen more the more tabs I have open.
In case workspace size has anything to do with it, my workspace is a multi-folder workspace containing ~15 workspace folders, ~10200 json files, ~5300 ps1 (powershell) files.
Work for several minutes - I notice ctrl+P is slower than normal on a fresh-reopened-window, but works for the first few minutes. 
After ctrl+P'ing a few times, and keeping the window open and working for several minutes then a random ctrl+P will set off the issue. 

I haven't found a consistent repro, but there was a period of time yesterday where I was reopening VSCode at least once every 15 minutes. I am currently trying to repro with only Git history, GitLens, and Powershell extensions enabled. A coworker is seeing this behavior as well, so it may have to do with extensions we run or the type of tabs we tend to open (ps1 and json). He will report in the comments as well.

VS Code version: Code 1.28.0 (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9, 2018-10-05T14:58:53.203Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.79GB (2.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.4.3
gitlens|eam|8.5.6
PowerShell|ms-|1.9.0

</details>

**Comment by EklipZgit** [comment]
To update this thread, it continues to repro with only Git history, GitLens, and Powershell extensions.
Also updated the issue description to correct that when the crash happens when ctrl+P searching, results are not filtered at all, only the initial default results show up before the hang.

**Comment by roblourens** [comment]
How many folders are in your workspace? Are they large?

Can you try setting `"searchRipgrep.enable": true` to see if that makes a difference?

**Comment by roblourens** [comment]
I can repro something like this, but I can repro the same issue in 1.27.2. Are you sure that it only happens in 1.28?

**Comment by EklipZgit** [comment]
I got some crashes before 1.28, but not many, and I don't recall them being directly linked to ctrl+P like these are. 
With that said, I don't know what version I updated from.

re: workspace size, from my post above 

> In case workspace size has anything to do with it, my workspace is a multi-folder workspace containing ~15 workspace folders, ~10200 json files, ~5300 ps1 (powershell) files.

Though I just counted and the workspace folder count is more like 39, but the file counts are accurate.

Re: "searchRipgrep.enable": true, do you mean 
```
  // Controls whether to use ripgrep in text and file search.
  "search.useRipgrep": true
```
If so that is already set to true, from the default user settings as far as I can tell.

I set `"searchRipgrep.enable": true` and will test however.

**Comment by EklipZgit** [comment]
@roblourens So to update on this, after enabling the setting you recommended (and also updating to 1.28.1), search is now significantly slower than before, but does not crash. I now constantly get very similar behavior to the crash, however with multi-second freezes instead of the full crash:
I start typing, no results show up, then the input box stops receiving my text about 4-8 characters in, but then after a few seconds it unfreezes and my results show up, the rest of my typing shows up, and then it continues searching.

Definitely not ideal behavior, I used to be able to search just fine in a workspace this size with only a second or so delay on the search results, and no text freezing. The behavior with "search.useRipgrep": true has constant freezing and about 4-5 seconds to get my file result back at minimum.

**Comment by creal1976** [comment]
Stop emailing me or I will file charges of harrasment

Sent from my Verizon Wireless 4G LTE DROID


Travis Drake <notifications@github.com> wrote:


@roblourens<https://github.com/roblourens> So to update on this, after enabling the setting you recommended (and also updating to 1.28.1), search is now significantly slower than before, but does not crash. I now constantly get very similar behavior to the crash, however with multi-second freezes instead of the full crash:
I start typing, no results show up, then the input box stops receiving my text about 4-8 characters in, but then after a few seconds it unfreezes and my results show up, the rest of my typing shows up, and then it continues searching.

Definitely not ideal behavior, I used to be able to search just fine in a workspace this size with only a second or so delay on the search results, and no text freezing. The behavior with "search.useRipgrep": true has constant freezing and about 4-5 seconds to get my file result back at minimum.

**Comment by creal1976** [comment]
Yes..about 50 times a day

Sent from my Verizon Wireless 4G LTE DROID


Travis Drake <notifications@github.com> wrote:


@creal1976<https://github.com/creal1976> there is an unsubscribe link at the bottom of the email that you replied to. Did you try clicking that?

**Comment by creal1976** [comment]
Now stop or I will report you for harrasment

Sent from my Verizon Wireless 4G LTE DROID


Travis Drake <notifications@github.com> wrote:


@creal1976<https://github.com/creal1976> there is an unsubscribe link at the bottom of the email that you replied to. Did you try clicking that?

**Comment by creal1976** [comment]
Stop emailing me I have unsubscribed and deleted my account and you flood my account with about 50 emails a min

Sent from my Verizon Wireless 4G LTE DROID


Travis Drake <notifications@github.com> wrote:


@creal1976<https://github.com/creal1976> there is an unsubscribe link at the bottom of the email that you replied to. Did you try clicking that?

**Comment by roblourens** [comment]
You're probably watching the repo. Unwatch it.

**Comment by roblourens** [comment]
My repro steps are

- Open a workspace with like 15 folders
- Open quick open, type several characters
- See the window hang

It doesn't repro if I only type a few characters or type slowly, which makes me think it's related to cancelling the search.

This change is responsible: https://github.com/Microsoft/vscode/commit/497ea886b78d492d5ed4f20addfb658ff422da07

The only effective difference in that commit is using the cancel token instead of promise cancellation

My theory is that when typing quickly, the token is often already canceled by the time we get to `collectResultsFromEvent`. So we add a listener which causes the filtering process to start in the search proc. Then asynchronously `onCancellationRequested` is triggered and we cancel the filter. But already we are trying to filter for every keypress. But I don't know why this causes everything to hang. It only hangs if this happens while the rg procs are running, so something about having too much IPC traffic in and out all at the same time. The search proc appears to simply stop executing code at some point.

Adding this to `collectResultsFromEvent` fixes it or at least makes it much harder to repro. 

```
if (token.isCancellationRequested) {
    e(canceled());
    return;
}
```

**Comment by chrmarti** [comment]
@roblourens Couldn't reproduce so far (on Mac). This search call doesn't pass a cancellation token, is that on purpose? https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/openFileHandler.ts#L223

**Comment by roblourens** [comment]
It's Windows only. That line is for the empty search to populate the cache which isn't canceled. This line is for the search with the query that does get canceled: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/openFileHandler.ts#L174

**Comment by mrcasals** [comment]
Maybe it's related, but versions 1.28.0 and 1.28.1 were slow on a Mac when searching and using the Cmd+P command. On 1.28.2 this is fixed and the speed is as fast as in 1.27.

I post this here since this is the only issue in https://github.com/Microsoft/vscode/milestone/80?closed=1 I can see this problem related to.

Thanks! 😄

**Comment by roblourens** [comment]
I believe it's related. Thanks for confirming! 😁

**Comment by dbschwartz** [comment]
> @roblourens I'm still seeing VS code freeze during Ctrl+P after updating to 1.28.2

I am also still having this issue

**Comment by roblourens** [comment]
Please open a new issue with as many details as possible. You can see the questions I asked above to see what info is useful in diagnosing this...

**Comment by haugerbr** [comment]
@roblourens #62082
