### ISSUE TITLE
Terminal Typing Position Incorrect

### ISSUE THREAD

**Issue by michael-hawker** [Microsoft/vscode#60695]
Issue Type: <b>Bug</b>

After opening a terminal, the typing input cursor is below where the actual output is.  You need to scroll up, but input still goes below.  This happens for both a command line shell and a powershell.

VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:13:53.910Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (32 x 2095)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.90GB (49.74GB free)|
|Process Argv|H:\oss\SpaceBattle\SpaceWeaver|
|Screen Reader|no|
|VM|0%|

</details>

After opening a terminal:

![image](https://user-images.githubusercontent.com/24302614/46837202-350b6700-cd69-11e8-8e44-249285e1e9f3.png)

After typing and scrolling up:

![image](https://user-images.githubusercontent.com/24302614/46837215-448ab000-cd69-11e8-923f-0cebec6d2d3e.png)

After hitting return, we seem to be good:

![image](https://user-images.githubusercontent.com/24302614/46837223-510f0880-cd69-11e8-8b94-e2c03680e9fe.png)

**Comment by wrlssqi** [comment]
I encountered just the same problem since 1.28.0 version. When opening a new terminal in vs code, the display is abnormal.
Windows 10 17763.55 

Situation 1: wired space
![image](https://user-images.githubusercontent.com/9946624/46845956-42c7f780-ce10-11e8-8eba-b1480653cd01.png)

Situation 2:  current directory not displayed 
![image](https://user-images.githubusercontent.com/9946624/46845997-71de6900-ce10-11e8-8d23-d4ad9562c963.png)

**Comment by muhammaddicky** [comment]
same here, start in v1.27.2

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/57803
