### ISSUE TITLE
最新版本遇到的问题汇总

### ISSUE THREAD

**Issue by 1020431880** [Microsoft/vscode#60708]
1.菜单栏的文字什么时候可以自定义大小呢？idea都可以，大屏幕的电脑菜单栏的字会看着特别大，这样不好。
2.最新版本很不稳定，没事就右下角弹出来个扩展主机已恢复，经常性的，提示它干嘛呢，卡就卡吧，一会儿一蹦出来很烦人，都想换旧版本了。（重要！）
3.新版本命令控制台打开后要隔十多秒才可以输入文字，以前没升级之前很快的，什么情况呢。
4.在编写微信小程序的时候，用了个吧小时后会卡，不能快捷键格式化，必须重启才可以，这是为什么呢

**Comment by vianchen** [comment]
First off, It is customary to summit issues in English. Secondly, as this issue doesn't provide any detail on when the bugs appear (likely due to outdated hardware), I suggest that the issue be closed.

尽量用英语提 issue 并提供你遇到的 bug 发生时的具体情况，否则别人不能帮助你，你也只是在浪费别人的时间。你遇到的问题可能是硬件过时导致的。对于第一种情况，你可以按 Ctrl + 破折号键 (-) 来缩放界面等级。

**Comment by sondragon** [comment]
Add the fouth, In my cash, when you debug a node problem, it will keep opening the powershell program, I don't know why it won't close itself. The Code has to reopen after tens of powershell programs run in the background because of the RAM had run out. The Code version is 1.28.0 and windows version is Windows7 x64 Professional SP1.

**Comment by egamma** [comment]
@vianchen thanks for your assistance, closing as suggested.
