### ISSUE TITLE
`Promise` wrongfully matches `TPromise` type

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#60765]
Starting with 11b364a82876e824afcf024bbd3675d213934465 (Sep 11), `Promise` became **duck-typable** to `TPromise`. The consequence of this is that this code type checks happily now:

```ts
function foo(): TPromise<string> {
	return Promise.resolve('on no');
}
```

This seems like a terrible idea given the already known [runtime differences](https://github.com/Microsoft/vscode/issues/53526#issuecomment-425853611) between the two.

This situation already started causing issues. In https://github.com/Microsoft/vscode/issues/60163, some code depended on the fact that `TPromise.then` is sync, which is fine since it actually uses the `TPromise` type (instead of `Thenable`), so it assumed to always get a TPromise. After [this](https://github.com/Microsoft/vscode/issues/60163#issuecomment-428071472) change, suddenly `Promises` started appearing in that code, bugs started to appear and the TypeScript compiler was nowhere near warning us.

---

I suggest to bring back a method (eg. `catch`) to the `TPromise` class in order to avoid this as we migrate away from `TPromise`. Unfortunately, doing this right now already triggers 34 errors. All valid errors, in my point of view, so they need to be tackled.

cc @Microsoft/vscode

**Comment by joaomoreno** [comment]
To clarify, removing all those methods from `TPromise` to make it match `Promise` was a good and necessary change, since it prevents people from using them onwards and make the migration easier. I just think the migration should still be manual by having us go into the code and doing `s/TPromise/Promise` and not let the compiler assume both are equal.

**Comment by jrieken** [comment]
that's the design of duck typing

**Comment by jrieken** [comment]
> I just think the migration should still be manual by having us go into the code and doing s/TPromise/Promise and not let the compiler assume both are equal.

The migration is still manual. I think many [words (1)](
https://github.com/Microsoft/vscode/issues/53526#issue-338230497) [of (2)](
https://github.com/Microsoft/vscode/issues/53526#issuecomment-420194920) [warning (3)](
https://github.com/Microsoft/vscode/issues/53526#issuecomment-425853611) have been spoken and everybody should know that great care is required when making these changes. This is esp true when making a change in a base component, like `nfcall`, which implicitly changes many, many places. 

Making `Promise` and `WinJS.Promise` incompatible again won't tackle the real problem but it will throw us back to where we were when we started this effort - you can either exclusively use one promise implementation but not both together. We had that situation for roughly 1 year and it didn't lead us anywhere. 

I think we should:

* share the complications and issues we are facing so that others are aware of this and don't run into the same issues
* find favourable places to begin the change, e.g. don't start at `nfcall` but "higher" in the promise tree. can this be automated?
* find code that relies on the sync-promise-execution and flag that as needed special care? should be automated.

**Comment by joaomoreno** [comment]
> We had that situation for roughly 1 year and it didn't lead us anywhere.

But we didn't have what we have today: momentum, feature alignment and planned time.

@jrieken Funny how #60163 isn't fixed with my changes. This bug, which no one in the team can reproduce, is now very likely caused by another Promise change by anyone in the team which affects someone else's code. So now, the unlucky charm lies on @bpasero since it affects his area... but did he push the change which breaks it? Who knows 🤷‍♂️ 

Why are we left in the dark here? I thought this is why we have tools: to make sure we can engineer safely and in deterministic fashion. TypeScript can help us here and we ignore it for the sake of getting this done sooner...?

> find favourable places to begin the change, e.g. don't start at nfcall but "higher" in the promise tree. can this be automated?

Yes, that is exactly my suggestion: let's not type match the two types; then, you get that for free.

> find code that relies on the sync-promise-execution and flag that as needed special care? should be automated.

Obviously, [the code in question](https://github.com/Microsoft/vscode/commit/6636ad9d080f655f21822b3a9cc1d95f9373f207) didn't depend on sync behavior  purposefully, it was purely accidental. My fear, which made me create this issue, is that there are other code pieces like this. People **will** break them unknowingly.

@Microsoft/vscode for comments

**Comment by jrieken** [comment]
> Yes, that is exactly my suggestion: let's not type match the two types; then, you get that for free.

I think that's not enough but I happily sit with you, we make TPromise and Promise incompatible, and we migrate "purposefully" _all_ usages and its dependents (something we won't get around no matter what). 

Proof me wrong, but my theory is that the reference graph is so large, and reaching into so much code you don't own, that it's effectively the same, risky change. Fencing-off changes via `TPromise.wrap` won't help because the semantic change has already happened.
