### ISSUE TITLE
Format on Save moves cursor to bottom of code file in 1.28.1

### ISSUE THREAD

**Issue by PrzemyslawKlys** [Microsoft/vscode#60808]
- VSCode Version: 1.28.1
- OS Version: Windows 10 1809

Steps to Reproduce:

1. Edit .ps1 file 
2. Press Save (make sure format on save is enabled)
3. Cursor will be moved to bottom of the file instead of keeping it in the same place

I've created issue with "movie" on VSCode-PowerShell - https://github.com/PowerShell/vscode-powershell/issues/1576

This issue didn't exists in earlier versions. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by egamma** [comment]
This is typically caused by an extension that does not implement format correctly. 
Can you reproduce this behaviour when you have this extension disabled: HookyQR.beautify@1.4.4?
Can you reproduce this when you have all extensions disabled? Can you reproduce it when you have only the Powershell extension enabled and all the other extensions disabled?

**Comment by egamma** [comment]
None of these extensions look like they participate on format on save. 
Please reopen the issue when it happens again when you have all extensions disabled.
