### ISSUE TITLE
NEW Debugging extension & lsp server issues

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#60809]
Issue Type: <b>Bug</b>

Starting in today's insiders build, I'm running into lots of issues when debugging my extension and attaching to its associated lsp server.

First when debugging the extension and attached to the lsp server, it causes the debugging drop down to contain a duplicate item for the extension:
![image](https://user-images.githubusercontent.com/641685/46891841-4754d600-ce39-11e8-89ef-52311ff579e9.png)

Also when debugging the extension and attached to the lsp server, the call stack for the lsp server doesn't even show up anymore.

![image](https://user-images.githubusercontent.com/641685/46891858-618eb400-ce39-11e8-9e98-9f9221f46007.png)

I've also seen other issue where stepping over or into a function, just basically runs rather than stepping, but I can't pin that down as it doesn't happen all the time - unlike the issues above.

//cc @isidorn 

VS Code version: Code - Insiders 1.29.0-insider (931c22033db3cc8d5dff265889307ed4076ac2d3, 2018-10-12T05:17:15.739Z)
OS version: Windows_NT x64 10.0.18252

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (16.52GB free)|
|Process Argv|c:\Users\Eric\code\vscode-gitlens|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by isidorn** [comment]
@eamodio thanks for creating this issue.
I tried reproducing with a simple out of the box vscode extension and I could not.
I tried to find the extension you are showing in your screenshots on GitHub but I coudl not.
If I start a similar compound with launch & attach like the `Debug VSCode main and renderer` from this repo I can not reprodcude.
My point is can you share some repository for which these issues can be reproduced? I believe that there is an issue caused by my session refactoring done for the multiple debug consoles.

Step over continues instead of steps sounds like an old node issue @weinand would know better

**Comment by eamodio** [comment]
@isidorn unfortunately the projects aren't currently open source. Is there other logging or something I can provide? Or can you point me where to look in the code to try to debug?

**Comment by isidorn** [comment]
@eamodio let's first try to figure out why there are duplicated sessoins in the dropdown
F1 > developer tools > source > put a breakpoint [here](
https://github.com/Microsoft/vscode/blob/eda14d219f89fd0a7456304f7551e53f8264d995/src/vs/workbench/parts/debug/common/debugModel.ts#L762)
Verify that he ends up having 3 sessions instead of 2 becuase none of them are INACTIVE - I believe that is the bug.

In case the above really happens, we need to figure out why the [`shutdown`](https://github.com/Microsoft/vscode/blob/eda14d219f89fd0a7456304f7551e53f8264d995/src/vs/workbench/parts/debug/electron-browser/debugSession.ts#L751) was not called, since it would set the `raw` to undefined, thus making the session inactive. For that I would put a breakpoint [here](https://github.com/Microsoft/vscode/blob/eda14d219f89fd0a7456304f7551e53f8264d995/src/vs/workbench/parts/debug/electron-browser/debugSession.ts#L142)

Other issues might be coming from this one, so let's first fix it.

**Comment by eamodio** [comment]
@isidorn I debugged it a bit -- and see that when I start the first debugging session (before the attach) there are 2 sessions in that array -- and they are identical references `this.sessions[0] === this.sessions[1]` is `true`, and when I start the attach there are 3, 2 dupes and a new attach.

**Comment by eamodio** [comment]
@isidorn it looks like the issue is after the debug session starts an EXTENSION_ATTACH_BROADCAST_CHANNEL event is fired here:

https://github.com/Microsoft/vscode/blob/9e83209ed59a22df3d593735d04cc963396bb89e/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L145-L151

Which then re-adds the same session again.

**Comment by isidorn** [comment]
@eamodio thanks a lot for investigating, really appreciate it.
The way Extension host debugging is designed it is expected that a session is re-initialized and thus being re-added to the model.
Anyways I have pushed a minor fix which makes sure it de-dups session in the model after they are added.
Andre also fixed some uri issues, so it would be great if you can check the behavior in the next insiders on Friday and let us know if there are still issues you are seeing. Thanks

**Comment by isidorn** [comment]
Great, thanks for letting us know it is good and for filling great issues.
Adding verified label

**Comment by isidorn** [comment]
Great, thanks for letting us know it is good and for filling great issues.
Adding verified label

**Comment by isidorn** [comment]
Great, thanks for letting us know it is good and for filling great issues.
Adding verified label

**Comment by eamodio** [comment]
I should also note that I was able to fix my issues with stepping (i.e. not stepping just running each time I tried to step in or over) by switching my webpack config to use `source-map` rather than `eval-source-map`  for its `devtool` setting. While its a bit slower to build, its a far better debugging experience -- though I'm not sure what changed as `eval-source-map` used to work with stepping

**Comment by isidorn** [comment]
@roblourens @weinand fyi regarding last comment
