### ISSUE TITLE
Terminal with ID 2 does not exist (has it already been disposed?)

### ISSUE THREAD

**Issue by safield** [Microsoft/vscode#60858]
Version: 1.29.0 insiders
OS: Linux Mint 19
**All extensions disabled**

**Steps to Reproduce:**

1. Run a task, call it **TASK A**, that calls a shell script that infinitely writes lines to the console. My shell script invokes the following java program:  
```
    public static void main (String [] args) throws IOException {
        while (true)
            System.out.println("TEST");
    }
```
2. Hit the "Kill Terminal" button in the panel, to kill terminal and close panel.

3. Run **TASK A** again. Nothing happens, and the following error is output as a notification...

> Terminal with ID 2 does not exist (has it already been disposed?)

**Comment by dbaeumer** [comment]
I can reproduce this as well on Windows. JS test case:

app.js

```js
setInterval(() => {
	console.info('Hello World');
}, 100);
```

tasks.json

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "endless",
			"type": "shell",
			"command": "node app.js",
			"problemMatcher": []
		}
	]
}
```

The underlying reason is that the terminal doesn't fire an `onExit` event when the terminal is disposed (e.g. the Kill Terminal button is pressed)

@Tyriar according to the doc the onExit should even fire if the terminal is disposed providing an `exitCode` of `null`. Please assign back if you think that needs to be handled differently in task land.

**Comment by dbaeumer** [comment]
@alexr00 might be something easy to look at.

**Comment by alexr00** [comment]
The onExit is firing eventually, but it can be a while before it fires. This is happening because there are still more `data` events coming from the `_ptyProcess` with all those `console.info`s. It looks like this is happening as designed right now. @Tyriar, when the `KillTerminalAction` executes should the terminal kill be treated as immediate or queued as it is now?

**Comment by Tyriar** [comment]
@alexr00 immediate would make sense for KillTerminalAction. The reason for the waiting for more data events is there is because of a past bug in tasks where the pty would be killed and we would miss out on the last portion of task output.
