### ISSUE TITLE
Find in selection is not auto-enabled when any text is selected

### ISSUE THREAD

**Issue by frostius** [microsoft/vscode#60856]
- VSCode Version:1.28.1
- OS Version:Win 10

Previously ( <1.28) find would auto-enable "find in selection" only when the selection spanned multiple lines.  It now appears to do so if any text is selected.  This make pre-population of the search text not as useful as it now limits the search to the selection.  Please revert to previous state where "find in selection" defaults to enabled only on multi-line selection

Steps to Reproduce:

1. Select a word (double click word)
2. Start find (ctrl-f)
3. Note that "find in selection" is enabled

**Comment by antcodd** [comment]
It sounds like previously Find and Replace in selection wasn't working at all for a single line selection before. The issue here is that it is arguably confusing and unhelpful for autoFindInSelection to automatic trigger find in selection in this case, especially since the find box is filled with the contents of the selection.

**Comment by frostius** [comment]
The current implementation doesn't make any sense to me.  

I really wish the team would pull back and rethink find and search/replace.  Many standard features are either missing or implemented in a non-standard way.

**Comment by kwaschny** [comment]
Having `editor.find.autoFindInSelection` is broken for a word selection use case. When you select a word and open the search to replace it in the current document, it activates "Find in selection", making search/replace not finding anything other than the selected word. I can see how the multi-line requirement doesn't make any sense as it would never trigger "Find in selection" when selecting more than one word within a single line. But why not just detect if the selection is a single word (definition of "single word" would be equal to the way a double click selects a word)?

**Comment by stefcameron** [comment]
Having Find default to "find in selection" is really awkward. I now always have to do (and remember to do) cmd+alt+l to first disable "find in selection" before I search. IMO, that defeats the purpose of having the find box auto-populate with selected text, which is so useful and time-saving. I'm not liking this change in behavior from <1.28.0.

If there's no intuitive way to detect when "find in selection" should automatically be toggled, it seems we need some setting to tune its behavior. Something like a setting that would inform whether it should be triggered automatically based on multi-"word" selection (using double click settings, like @kwaschny suggests above), or the presence of newlines in the selection (IMO, this would be the most sensical trigger for auto-activation of "find in selection" since I would never attempt to search for content that contains newlines, unless I was using a regular expression).

**Comment by frostius** [comment]
@stefcameron turning off ``edtor.find.autoFindInSelection``` disables automatic "find in selection".   This setting was added in 1.13 in response to #15148.  There appears to be a portion of the dev team that is opposed to this feature as it was a battle to get implemented and we continue to have these type of regressions.  

Its a standard feature (as far as I know) in every major editor ever release (even editors like Word & excel) so I personally am mystified by the push-back.

**Comment by stefcameron** [comment]
@frostius Thanks for pointing-out that other issue. I had a look, and the related #12109 as well. A bit more testing shows me that `editor.find.autoFindInSelection: false` means that if I select multiple lines, "find in selection" is no longer toggled on by default when I press `cmd+f` to start a search. Obviously, this is very subjective, but IMO, I'd rather that than the alternative of _always_ having "find in selection" toggled on regardless of what I have selected, even if it doesn't span multiple lines. More often than not, I'm making a selection and then pressing `cmd+f` to preload the search box with my selection (a behavior I really like since it seems to intuitive to me, and it saves me from having to do `cmd+c, cmd+f, cmd+v` to copy the text, open search, paste text, and then finally see results.

I'm not sure exactly what changed between 1.27 and 1.28, but I did observe that in 1.27, when I'd select a word (not multiline) and press `cmd+f`, I'd get the search widget preloaded with that word, and the "find in selection" toggle had the faintest difference in background as though it was sort of on, but the behavior was finding __all__ hits in the file, not the selection. Pressing `cmd+alt+l` would then toggle "find in selection" on, as expected, and again would toggle it off. Pressing `esc` to dismiss the find widget, and then `cmd+f` to show it again would result in "find in selection" no longer having that faint difference in background. Nonetheless, the behavior was still to find all hits in the file, not the selection. And this with `editor.find.autoFindInSelection: true`! I did test a multiline selection, and in this case, `cmd+f` would show the find widget with a more obvious toggle background on "find in selection", and the behavior was to find hits in the selection only (as I would expect in this case).

Now in 1.28, with `editor.find.autoFindInSelection: true`, I select a word (not multiple lines of text), press `cmd+f` and I see that "find in selection" has a blue border and the behavior is definitely to find in selection, not the file -- __this, to me, is a change in behavior of the IDE given the settings I already had__ (I had a chance to check the state of my settings prior to upgrading another computer, and I did have `editor.find.autoFindInSelection: true` already set, contrary to what I thought in my first comment on this thread). Suddenly, I'm using the search feature as I always have, and I'm no longer finding anything because it scopes the search to my selection by default (and I'm not noticing because I'm not even looking at the search widget, I'm just expecting the scrollbar to light-up with all the hits in the entire file like it used to).

So while `editor.find.autoFindInSelection: false` means I no longer get "find in selection" toggled on by default when pressing `cmd+f` with a multiline selection, it's so rare that I select multiple lines before searching that I'd rather have to also then press `cmd+alt+l` to toggle "find in selection" in that case.

Of course, I'd prefer the 1.27 behavior be restored since I found that more intuitive for both single and multiline selections, but at least I'm able to optimize for my workflow at the moment. 😄

**Comment by frostius** [comment]
> @stefcameron t's so rare that I select multiple lines before searching

agreed, but almost always (for me) when doing a replace, which is something I do daily

**Comment by skqr** [comment]
I was going to mention how the change to non-multiple line broke find next, but @antcodd beat me to it.

Searching within the line you're looking at is completely pointless. The edge case would be a really really long line, and being an edge case, users can enable "within selection" themselves.

**Comment by rebornix** [comment]
re https://github.com/microsoft/vscode/issues/27083#issuecomment-546539918.
