### ISSUE TITLE
Memory leaks and high CPU usage caused by the import cost extension

### ISSUE THREAD

**Issue by atilkan** [Microsoft/vscode#60927]
I like to let you know that most of the issues about memory leaks here caused by an extension. 
I wanted to point people. So you can close the issue.
```
**import-cost** from **wix.com** //shameful gb
```
https://marketplace.visualstudio.com/items?itemName=wix.vscode-import-cost

**Comment by egamma** [comment]
@atilkan thanks to tracking this down and letting us know.

It looks like there is already an issue filed on this https://github.com/wix/import-cost/issues/59. If you have more details please add them to this issue.

**Comment by axetroy** [comment]
Because most extensions are not throttled.

Such as some AST-based (Babel) extensions.

They parse the file content. But the content is too large. It will take a long time to do his job and wasted a lot of CPU.

**vscode should have a mechanism to limit the CPU usage for the extension.**

### For example: Prettier for vscode

try to format a large file. and you will see your high CPU Immediately

**Comment by atilkan** [comment]
@egamma I intend to shame wix.com, they coast me some time.
@axetroy That would limit the potential too. I would not vote for that.

**Comment by egamma** [comment]
@axetroy throtteling an individual extension is difficult in a single threaded environment. What we have in place are measurements when the extension is not responsive and we plan to automatically start profiling when this is the case.

The VS Code best practice is not parse a large file in the extension but in a separate process. This is how VS Code language servers work.
