### ISSUE TITLE
Blink current line when 'continue' goes to the same line

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#61072]
```ts
setInterval(() => {
    console.log('foo');
}, 0);
```

- Hit a breakpoint inside the setInterval
- Press "continue"
- Previously the yellow current line indicator would blink a little letting me know that something happened, now it doesn't, and I'm not sure whether I continued or not

**Comment by isidorn** [comment]
I agree with the issue you outlined.
However I have made that change in the case of multi / thread or multi session debugging to have less focus swithcing and to make that overall experience nicer.

The actual change is: if a session is continued do not automatically defocus it, but wait 200ms. This improves the multi scenario, however in the case you outlined it fails because the session never gets defocused thus you do not get any blinking.

For now leaving this open as a bug, and I might tackle it in the future - in the meantime would like to get more user feedback regarding the mutli case.
I could also add some ugly code to only do my heuristic for the multi case - but due to timing issues it does not work 100% of the time that the flashing is shown. Not sure how it was happening before since I can not repro the behavior you are descrinbing in stable

**Comment by roblourens** [comment]
I can see the desired behavior in stable but maybe it depends on DA timing or something
