### ISSUE TITLE
"Back" button & navigation history

### ISSUE THREAD

**Issue by Kelin2025** [Microsoft/vscode#61103]
When I use "Go to definition" feature I often want to go back to the previous file but it's no longer possible, you should open previous file manually  
It would be nice to have "back" button for that

**Comment by Tyriar** [comment]
There is a back command you can use (see View menu), we don't plan on adding these buttons to the UI.

**Comment by amitagrawal11** [comment]
@Tyriar thanks for the reply, but from user perspective it would be good to have a button on UI since new users did not know the commands to go back and forth. Since other IDE's like Intellij do provide this type of functionality.

I appreciate if any one can take an initiative on this feature for upcoming build.
