### ISSUE TITLE
Terminal directory is different from project directory

### ISSUE THREAD

**Issue by pyyzcwg2833** [Microsoft/vscode#61207]
I have never encountered this situation before.

After I install my vscode, I find the working directory of vscode integrated terminal always stays in my home directory no matter which project I open with vscode.

I never touch any configuration file of vscode.
Just like this
![2018-10-18 2 36 15](https://user-images.githubusercontent.com/24390069/47135977-d30cad80-d2e4-11e8-93d9-a64bd414e92b.png)

- VSCode Version: 1.28.1
- OS Version: macOS High Sierra 10.13.6
- Shell: oh-my-zsh

**Comment by Tyriar** [comment]
You're in a multi-root workspace? If you didn't open a file and hit ctrl+\` then I think `$HOME` is expected. What happens when you open a file and hit new terminal ctrl+shift+\`?

**Comment by pyyzcwg2833** [comment]
> You're in a multi-root workspace? If you didn't open a file and hit ctrl+` then I think `$HOME` is expected. What happens when you open a file and hit new terminal ctrl+shift+`?

I only opened a workspace. And when I open a file and hit new terminal ctrl+shift+\`, the working directory of terminal is still my home directory.

my `$HOME` is below
![2018-10-19 10 02 23](https://user-images.githubusercontent.com/24390069/47193561-326eca00-d386-11e8-8f07-17e1aa9f009d.png)

**Comment by ShonFrazier** [comment]
I see something similar - my integrated terminal opens to / on macOS. I've made no configuration changes to Terminal > Integrated: Cwd

**Comment by escargotprodige** [comment]
Same issue for me. It opens in $HOME instead of the actual project root. I'm using default settings.

Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-16T19:06:41.692Z
Electron: 3.1.4
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.20.10-arch1-1-ARCH

**Comment by RomainLanz** [comment]
Hey all,

Same issue for me.

---

**Shell:** fish
**Version:** 1.32.0-insider
**OS:** macOS Mojave
---

When opening the integrated terminal (in a workspace or not) it display `/`.
The command `pwd` also display `/` but I'm in the project directy since I can run command and see the file using `ls -la`.

<img width="1013" alt="screenshot 2019-02-23 at 10 53 41" src="https://user-images.githubusercontent.com/2793951/53284789-4f167680-3759-11e9-84e5-59934bf268c3.png">

It's not an issue until you are on a workspace because you cannot know in which project you currently are.

--.

**Comment by lacolaco** [comment]
I'm in the same situation.

**Shell:** fish
**Version:** 1.31.1
**OS:** macOS Mojave

- If the cwd is `~/foo` and I run `code ./bar` , the integrated terminal's cwd is `~/foo`. 
- If the cwd is `~/foo/bar` and I run `code .` , the integrated terminal's cwd is `~/foo/bar`.

As the above, the integrated terminal seems handling the directory where `code` command is called at as the cwd.

**Comment by Tyriar** [comment]
Everyone new commenting is probably talking about the issue with fish.

**Comment by Tyriar** [comment]
I suspect OP's issue is related to their zsh setup

**Comment by RomainLanz** [comment]
Hey @Tyriar 👋 

Could you please link the `fish` issue you are talking about?
Thanks!

**Comment by Tyriar** [comment]
See 3.0.2 https://fishshell.com/release_notes.html
