### ISSUE TITLE
Popover or Tooltip don't display correctly

### ISSUE THREAD

**Issue by polRk** [Microsoft/vscode#61248]
1. Версия 1.28.2 (1.28.2) 
2. Mac OS 10.14 (18A391)

Bug 
Подсказка об ошибке в package.json отображается не правильно
<img width="572" alt="2018-10-18 19 30 39" src="https://user-images.githubusercontent.com/39828645/47169610-a79db900-d30c-11e8-9802-a4dd22f0c0a7.png">

**Comment by polRk** [comment]
The warning is not shown properly. In my opinion, it should fall down, because I can't see the error.

**Comment by ramya-rao-a** [comment]
Understood. 

So looks like this happens when the warning is on the first line.
I wasn't able to see this:

<img width="875" alt="screen shot 2018-10-23 at 11 12 15 am" src="https://user-images.githubusercontent.com/16890566/47381324-9bbb4980-d6b4-11e8-9dba-7b1e3f4cd2ce.png">

Can you share your settings?

**Comment by polRk** [comment]
Okay, now shows fine, I don't know why, it's been showing some time wrong...
