### ISSUE TITLE
Debug Console doesn't update output when hidden

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#61273]
- Show the debug console
- Debug this code: `console.log('hello 1')`
- See output in the console
- Hide the debug console
- Change the message in the script to `'hello 2'`
- Debug again
- Open the console, it still says "hello 1"

**Comment by ITAsimo456** [comment]
Not sure if i can contribute at all, but i wanted to do my first OSS contribution on vscode, so:

The problem is in /vs/workbench/parts/debug/electron-browser/repl.ts, in the registerListeners, which doesn't call selectSession if the window is not visible, and therefore doesn't register the new output.
Moreover, in refreshReplElements the output isn't updated when the debug window is not visible, so the output gets updated only when the window is visible and one new output is registered. 

I'm pretty sure just removing the isVisible condition in refreshReplElements isn't an optimal solution though, because the elements get refreshed every output even if the window is not visible.

**Comment by isidorn** [comment]
@ITAsimo456 thanks for looking into this but I already started fixing this. If you would like to contribute I would suggest looking for issues with help-wanted and good-first-issue. Thanks a lot

**Comment by isidorn** [comment]
@roblourens great catch

**Comment by roblourens** [comment]
This still exists in some form, but doesn't repro as reliably as before.

- Hide the debug console
- Reload the window
- Start debugging
- Debug console appears
- Sometimes, the debug console is still missing output and I can't eval code in it

![image](https://user-images.githubusercontent.com/323878/47943942-e9566400-deb5-11e8-82db-f002c01e368b.png)

**Comment by roblourens** [comment]
Oh, yeah that looks the same.
