### ISSUE TITLE
Editor does not distinguish some unicode chars

### ISSUE THREAD

**Issue by cossio** [Microsoft/vscode#61275]
For example, try to find φ, and it will match ϕ too.

**Comment by rebornix** [comment]
By default, the search is case insensitive, if you turn this offline by checking "Match Case" in the find box.

**Comment by cossio** [comment]
@rebornix φ and ϕ are both variants of the *small case* greek phi letter. The uppercase is Φ, a different character. See https://en.wikipedia.org/wiki/Phi.

**Comment by Tyriar** [comment]
@cossio in that case it's working as intended, no? Case insensitive finds both (ie. find all letters regardless of case):

<img width="703" alt="screen shot 2018-11-28 at 12 12 59 pm" src="https://user-images.githubusercontent.com/2193314/49179344-f88acf00-f306-11e8-8004-121b50f0685f.png">


Case sensitive finds only one:

<img width="700" alt="screen shot 2018-11-28 at 12 12 53 pm" src="https://user-images.githubusercontent.com/2193314/49179356-fd4f8300-f306-11e8-88a6-eff403424d9f.png">

**Comment by Tyriar** [comment]
@cossio so you want them to _always_ match both characters then, regardless of whether match case is on or off?

**Comment by rebornix** [comment]
I don't know how to fix this issue, v8 thinks their relationship is Upper/Lower case.

**Comment by cossio** [comment]
@Tyriar No. I think it should always *distinguish* between φ and ϕ, because they are *distinct* lower case characters.

**Comment by cossio** [comment]
Atom and Sublime Text also don't distinguish φ and ϕ.

**Comment by Tyriar** [comment]
@cossio but because they are the _same character_, phi, a case insensitive search should find both, so I think this is correct:

![image](https://user-images.githubusercontent.com/2193314/49247286-c3948000-f3cb-11e8-8fe3-28ac07652f19.png)

If not, you would need to do individual searches for both variants in order to find all phi characters?

Based on my limited understanding of this, it seems like the only question is whether a case sensitive search should find both (as they're both lowercase) or only one.

![image](https://user-images.githubusercontent.com/2193314/49247488-3c93d780-f3cc-11e8-83f7-486e67be18fb.png)
