### ISSUE TITLE
Prepend items in the palette commande with an alphanumeric character for a quick access with keyboard

### ISSUE THREAD

**Issue by idrissbek** [Microsoft/vscode#61378]
If items in the palette commande are prepend with an alphanumeric character (at least the 10 fist elements) we will be able to access directly to them instead of using the arrow keys or the mouse.

Example :

The sequence :
    F1 => Insert Snippet

Will display :
    1. dowhile
    2. for
    3. foreach
    4. forin
    ...

Then we could use this sequence to directly access to foreach code snippet :
    F1 => Insert Snippet => 3

**Comment by bpasero** [comment]
This issue is being closed to keep the number of issues in our inbox on a manageable level, we are closing issues that are not going to be addressed in the foreseeable future: We look at the number of votes the issue has received and the number of duplicate issues filed. More details [here](https://aka.ms/vscode-out-of-scope). If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Thanks for your understanding and happy coding!
