### ISSUE TITLE
Add option to save opened files to workspace-file, and not to users storage.json

### ISSUE THREAD

**Issue by malaire** [Microsoft/vscode#61417]
Version: 1.28.2

Currently all opened files are saved to users storage.json file.

In my opinion those should be saved to xxx.code-workspace -file instead, so that they are not lost if xxx.code-workspace is renamed or moved.

This would also make it easy to backup everything related to a certain workspace, which is currently not possible.

**Comment by bpasero** [comment]
This issue is being closed to keep the number of issues in our inbox on a manageable level, we are closing issues that are not going to be addressed in the foreseeable future: We look at the number of votes the issue has received and the number of duplicate issues filed. More details here. If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.

If you wonder what we are up to, please see our roadmap and issue reporting guidelines.

Thanks for your understanding and happy coding!

**Comment by malaire** [comment]
I do disagree and this is definitely a crucial issue to me, but I'm not going to argue about this - I just use different editor instead of vscode.
