### ISSUE TITLE
Partially complete suggestion

### ISSUE THREAD

**Issue by engyn** [microsoft/vscode#61426]
When selecting a suggestion, I would find it helpful to be able to partially accept a suggestion, either to the next commit character if any, or for example `->` in php. then continue typing. For example:
![image](https://i.imgur.com/dwDqYXD.png)

I would then use some keybinding to autocomplete `editor`, then the options for completion would be like so:
![image](https://i.imgur.com/vxw6mD3.png)

I would find this especially useful for use with VSCodeVim, where I could accept autocompletion as if I pressed `w` (forward word)

I would be ecstatic if this is already possible or if there is an extension that does this, I've been searching for a while and haven't found anything.

**Comment by Johnmper** [comment]
Hi, this feature is also useful for me. Since in extensive and well-structure codebases with known prefixes it is easier to explore and find the desired functions by wilting down the available suggestions. 

I wanted to ask the current situation for the feature. Can i hope for its implementation in future releases?

**Comment by starball5** [comment]
Also duplicated by #77907

Related on Stack Overflow: [Partial autocomplete of the suggestions given by vscode?](https://stackoverflow.com/q/56350639/11107541)
