### ISSUE TITLE
Wrong document type reported by first time fired onDidOpenTextDocument

### ISSUE THREAD

**Issue by bartosz-antosik** [Microsoft/vscode#61441]
There is some strange behavior of `onDidOpenTextDocument` event which returns wrong document's type in some situations (first time fired?) in Insiders build of VSCode. It seems it exists only in Insiders edition, but because I had a similar situation with #60394 some ago when some issue reported in Insiders has propagated to regular.

Version: 1.29.0-insider (system setup)
Commit: 45d5d153bbebed743b77e426615aade34971eb46
Date: 2018-10-19T06:58:45.940Z
Electron: 2.0.11
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Steps to Reproduce:

1. Start VSCode Insiders build with Spell Right extension
2. F1, Open Settings (JSON)
3. See there are spellright annotations
4. Switch to another tab
5. Switch back, annotations are gone

It seems that `onDidOpenTextDocument` returns "plaintext" as document type first time it is fired. Because Spell Right spells `plaintext` documents by default it produces the diagnostics on first run whereas it does not in any subsequent run.

**Comment by jrieken** [comment]
Can you check for the `onDidCloseTextDocument` event? If the mode changed than that event would have fired

**Comment by bartosz-antosik** [comment]
In `onDidCloseTextDocument` event I remove diagnostics. It works fine for many months as it did few days back. So it looks like it is not fired until later.

May I ask a rhetorical question why would type of `jsonc` change if it is `jsonc` all along?

**Comment by jrieken** [comment]
> May I ask a rhetorical question why would type of jsonc change if it is jsonc all along?

I don't know why. Maybe some mode detection timing/sequencing has changed. However, the overall sequence is correct. There is open, close, and then open so the final state represents the state correctly.

**Comment by jrieken** [comment]
Just to clarify, the behaviour is correct and this is how we do thing since the beginning

* async load a file
* async detect and load the language mode (comes from an extension)

We don't block showing/opening of files on the language detection and update the language later (that's the same as when a user selects "F1 > Change Language"). For extensions we make mode changes appear as a close/open sequence - also ever since.

cc @bpasero if the mode of a new file is somehow now set extra delayed?
