### ISSUE TITLE
Webviews take focus when vs code is refocused

### ISSUE THREAD

**Issue by the-ress** [microsoft/vscode#61489]
Issue Type: <b>Bug</b>

Menu sometimes won't open when vscode isn't focused. (It immediately closes.)

1. Open release notes
2. Focus another application
3. Click an item in the menu bar

![vscode-menu](https://user-images.githubusercontent.com/1612377/47292560-ae2b7980-d607-11e8-9ca4-06e761514aba.gif)

VS Code version: Code - Insiders 1.29.0-insider (4d9f1d23a556dccd2c0fd5203923a24b21e41209, 2018-10-22T05:18:34.128Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (1.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by evangrayk** [comment]
This also appears to affects things like the terminal or anything in the bottom panel:
1. focus any webview
2. focus the terminal
3. switch applications
4. switch back to VS Code
=> the terminal is no longer focused

If you do the same thing but focus an editor instead of a webview, the terminal is correctly focused when switching back.

(tested on macOS in insiders)
