### ISSUE TITLE
Can't debug nodemon twice

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#61517]
- Debug a nodemon config like this:

```json
{
    "type": "node",
    "request": "launch",
    "name": "nodemon",
    "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/nodemon",
    "program": "${workspaceFolder}/out/app.js",
    "restart": true,
    "console": "integratedTerminal",
    "internalConsoleOptions": "neverOpen"
},
```

- Press stop
- Start debugging again
- "There is already a debug configuration "nodemon" running"

**Comment by isidorn** [comment]
Thanks for the nice steps, I can reproduce it.
After debugging the problem here is that on stop the debug adapter send a `onDidTerminateDebugge` with the `event.body.restart` so we try to restart and fail which leavs the session in a bad state.

So when vscode sends a terminate or disconnect request to debug adapter the debugee exit event should not contain the `restart` inside the `body`.
Forwarding to @weinand and @roblourens to potentially fix this on the extension side.

![screen shot 2018-10-23 at 16 06 26](https://user-images.githubusercontent.com/1926584/47366435-f6b56680-d6dd-11e8-964f-0264c38e6a19.png)

**Comment by roblourens** [comment]
It seems like the DA might not be handling terminate/disconnect correctly, but it works in 1.28 and nothing has changed in the DA. Did anything change with how those events are sent?

**Comment by isidorn** [comment]
@roblourens it migth be that before we were not keeping inactive session which we do now as part of the refactoring to show multiple debug consoles. 
Anyways this refactoring seems to have uncovered an issue on the adapter side. Let me know if this can not be fixed on the adapter side and if that is the case I can try to find some solution on the vscode side

**Comment by roblourens** [comment]
Yeah I need to fix it on the DA side. But I'm confused, the terminate request doesn't seem to work in 1.28. The DA sends `supportsTerminateRequest` but `this.raw.capabilities.supportsTerminateRequest` is false in debugSession.terminate...?

**Comment by roblourens** [comment]
I thought that Live Share issue was fixed? Very frustrating when debugging this stuff.

**Comment by roblourens** [comment]
This is a different issue when the program terminates cleanly, it's not the typical nodemon scenario, tbh I think this scenario has never worked quite right.

We can tell that nodemon is not going to restart when we get to here: https://github.com/Microsoft/vscode-node-debug2/blob/master/src/nodeDebugAdapter.ts#L307

**Comment by roblourens** [comment]
Actually, I don't think I want to change this. You can still restart debugging if you change the program again within 10s. If you wait more than 10s, the DA times out and you can press F5 again. I am not sure how to improve this because the DA doesn't have anything to attach to when the app is not running, and we don't have UI or a concept of the DA waiting forever for nodemon to start again... I don't remember users complaining about this either, so I'm leaving it alone.
