### ISSUE TITLE
[themes] setting for preferred light and dark color theme based on system dark mode setting (Windows/Mac)

### ISSUE THREAD

**Issue by malmaud** [microsoft/vscode#61519]
Feature request: It would be cool if I could register in VSCode a preferred light workbench color theme and a separate preferred dark color them. Then VSCode could automatically switch to my chosen light or dark theme based on the system-wide Mojave dark appearance option.

**Comment by Tyriar** [comment]
Windows also has a dark mode now which we don't respect.

**Comment by balupton** [comment]
This issue doesn't seem to be address nor duplicated.

It is about automatically switching colour theme based on macos mojave light mode vs dark mode.

So for instance, in Mojave Light Mode, I want to use:

```
	"workbench.colorTheme": "GitHub Plus",
```

However in Mojave Dark Mode, I want to use:

```
	"workbench.colorTheme": "Monokai"
```

**Comment by malmaud** [comment]
I agree - I don't see what issue duplicates this and this issue has 7 votes now.

**Comment by LinusU** [comment]
If anyone is interested in this I've made a small extension that does this for now, personally would love to see it built-in though 👍 

https://marketplace.visualstudio.com/items?itemName=LinusU.auto-dark-mode

**Comment by felixfbecker** [comment]
I change my theme a lot depending on time of the day and it's annoying to not see VS Code respect that / having to switch VS Code manually. It's the only app I have that requires this.

**Comment by michaelgosling** [comment]
Considering windows has Dark and Light mode now, and extension developers can manage it, I don't think this issue should be "out of scope." :/

**Comment by Tyriar** [comment]
Me either

**Comment by chriskuech** [comment]
macOS now supports automatic switching between dark theme and light theme depending on the time of day.  This seems like the perfect time to start respecting the system theme.

**Comment by VideoPlayerCode** [comment]
@aeschli Hi Martin, I just found this discussion via Google and noticed that you're considering the feature. I'd just like to mention a use-case to keep in mind: Some people would love the ability to switch between a Light and Dark theme, but to not be tied to the system setting.

Anyway, here are extensions that may help:
- Windows auto switch theme based on Dark mode: https://marketplace.visualstudio.com/items?itemName=danielgjackson.auto-dark-mode-windows
- Mac auto switch theme based on Dark mode: https://marketplace.visualstudio.com/items?itemName=LinusU.auto-dark-mode&ssr=false

And two more extensions that allow manually switching between Light and Dark themes:
- https://marketplace.visualstudio.com/items?itemName=freetonik.day-night-theme-switcher
- https://marketplace.visualstudio.com/items?itemName=latusinski.theme-switcher

My dream solution would be to be able to swap between two themes with a Command Palette choice. Not at all tied to the system Dark setting. Just putting that interest out there, since it's better to keep such things in mind rather than to get a bunch of user requests for such a change later.

**Comment by aeschli** [comment]
Thanks @VideoPlayerCode for the great summary of extensions out there.

With so many extensions to choose from and so many variants I think we can close the issue and leave this feature to extensions.

**Comment by BorntraegerMarc** [comment]
I disagree with that VSCode wouldn't provide this functionality out-of-the-box and I have to install an extension for this. I tried couple of extensions and some just don't work with my Mac...

**Comment by aeschli** [comment]
Please support the extensions by filing issues if something is not working for you.
We need to share the work and want to have a rich extension eco-system.

**Comment by NilsEnevoldsen** [comment]
Likewise disagree that this functionality should be delegated to extensions. It is now core functionality on system apps. [MacOS HIG specifies that Dark Mode adaptation should be automatic.](https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/dark-mode/)  _Overriding_ the system theme is optional.

**Comment by LinusU** [comment]
@aeschli my extension is broken with the automatic switching on macOS Catalina, and it seems like the only way to get it to work again is to have the extension present some kind of UI. That is a system tray bar, a window or anything else visible to the user. (ref: https://github.com/LinusU/vscode-auto-dark-mode/issues/11)

This of course would offer a very subpar experience. But if this was implemented directly in VS Code itself, it wouldn't be a problem since it already presents a window to the user.

I also very much agree with this:

> MacOS HIG specifies that Dark Mode adaptation should be automatic. Overriding the system theme is optional.

**Comment by Tyriar** [comment]
@aeschli If we wanted to add this to core we could use `window.matchMedia` to listen for changes in `prefers-color-scheme` - this wouldn't be much code and would also work in web without needing any native node modules.

I use matchMedia in xterm.js to [detect window DPR changes](https://github.com/xtermjs/xterm.js/blob/00501bd2e841a374b362114d5321cddab9240683/src/browser/ScreenDprMonitor.ts#L56).

**Comment by VideoPlayerCode** [comment]
@aeschli You're welcome. The only thing I noticed today, when going through the "auto detect dark theme" code of the Windows theme, is that it uses some batch file and a registry read to detect the mode. It's kinda horrible. Likewise the Mac themes use some kinda hacks.

So I do agree that extensions should offer this feature, but VSCode kinda needs a built-in "Is Dark Mode Active on the system?" API/"on-change callback" to make the extensions cleaner and more robust. How about that? It's a smaller scope than originally asked for, and should be a lot easier to add to VSCode, and will help the extensions become robust.

_PS: I use the "Theme Switcher" by JanBn as mentioned, and it's perfect. Bound Ctrl-Alt-T to "Next Theme (from separate list in config)" and that code now cycles between 3 or so themes for me. Just a tip for people who want that functionality. It was the least complicated extension to offer that feature, and the only one that offered more than 2 theme cycling. It was also really good for going through all installed themes (it has keybinds for that too) and comparing them quickly. Thanks to that, I was able to quickly compare all light themes and find the one with the best contrast/syntax highlighting!_

**Comment by michaelgosling** [comment]
> 
> 
> Thanks @VideoPlayerCode for the great summary of extensions out there.
> 
> With so many extensions to choose from and so many variants I think we can close the issue and leave this feature to extensions.

Light and Dark mode adapting to system theme should really be a core feature. There's plenty of resources available for implementing this. Every browser already does. Forcing the user to install an extension for basic functionality is a bit much. Extensions eat resources and you shouldn't have to raise minimum requirements for simple functionality like this. 

In regards to making it manual, I think consistency in an interface is important so a boolean setting to enable Change With System with a default of true is the best solution IMO.

**Comment by VideoPlayerCode** [comment]
@michaelchiche External extensions do not eat any resources that wouldn't already be taken by implementing the exact same JavaScript in VSCode's built-in extensions.

By the way look at https://github.com/microsoft/vscode/issues/61519#issuecomment-558738593, with @Tyriar's help, I found a way to detect dark/light mode on both Mac and Windows. All "broken" extensions above can be fixed. No need for any hacks to detect dark mode anymore.

**Comment by VideoPlayerCode** [comment]
I've now taken @aeschli's advice and alerted extension creators about the better method. There's one more extension, by @LinusU. Since I know you read this thread, I'll tell you here. You can delete https://github.com/LinusU/node-dark-mode-listener/blob/master/index.js and start using the built-in technique instead as mentioned above. Heck, [your extension](https://marketplace.visualstudio.com/items?itemName=LinusU.auto-dark-mode&ssr=false) is already very small and therefore looks like the perfect candidate for creating the most _minimalistic_ auto-dark/light mode switcher, which a lot of people here are asking for. Go for it! ;-)

**Comment by michaelgosling** [comment]
> @michaelchiche External extensions do not eat any resources that wouldn't already be taken by implementing the exact same JavaScript in VSCode's built-in extensions.
> 
> By the way look at [#61519 (comment)](https://github.com/microsoft/vscode/issues/61519#issuecomment-558738593), with @Tyriar's help, I found a way to detect dark/light mode on both Mac and Windows. All "broken" extensions above can be fixed. No need for any hacks to detect dark mode anymore.

huh? I'm pretty sure extensions thread a whole new process and an extension involves installing an entire package. Why should VSCode be the only application to not support system dark/light modes? It makes much more sense to implement this as a core feature rather than rely on the community to keep extensions up to date. Electron has [an API for this](https://electronjs.org/docs/api/system-preferences)

**Comment by NilsEnevoldsen** [comment]
@michaelgosling I think you want to link to [this Electron API](https://electronjs.org/docs/api/native-theme): `nativeTheme `

**Comment by michaelgosling** [comment]
@NilsEnevoldsen Thanks! I didn't read thoroughly enough to see that its deprecated now.

**Comment by VideoPlayerCode** [comment]
@michaelgosling You're right, I see now that each extension runs in a separate JS host, and communicates with the main host. Interesting... It's not a big deal though.

But you won me over with this comment: "Why should VSCode be the only application to not support system dark/light modes?"... True. Since APIs already exist in JavaScript for detecting the dark mode and getting a callback call whenever dark mode changes (I tested, they're supported in VSCode), and there even seems to be Electron APIs for the same thing... there really isn't much code that would need to be added to the VSCode core. Something like adding optional `darkTheme`, `lightTheme` and `autoDarkTheme` boolean JSON properties...

**Comment by michaelgosling** [comment]
Those hosts add up quick, in my opinion. But it seems we’re in agreement, at the very least this should be a core feature when vscode moves to electron 7.

**Comment by aeschli** [comment]
Ok, I reopen.Accessing the Electron or Dom API can only be done in the core.
If anyone wants to give it a try, I'm open for a PR.

**Comment by muuvmuuv** [comment]
@aeschli Could you give a hint where to start? I would take on this and enabling the Electron API, because I think it's a more consistence way for extension developers to use the VS Code API instead of using the DOM. Which would also give better abilities for tests, I guess.

**Comment by aeschli** [comment]
There's a similar path when the OS reports that high contrast mode has been enabled:

Electron event in the main thread:
https://github.com/microsoft/vscode/blob/453e750ca48b48ce25b07e4f3bc5c651a179f74f/src/vs/platform/windows/electron-main/windowsMainService.ts#L229

Broadcasted to all renderers:
https://github.com/microsoft/vscode/blob/453e750ca48b48ce25b07e4f3bc5c651a179f74f/src/vs/workbench/electron-browser/window.ts#L197

We need a setting to let users set their prefered theme for light, dark and hc.
Also a setting that controls to enable/disable the auto theme switching.

**Comment by aeschli** [comment]
If this can be done via browser event as @Tyriar describes, even better.

**Comment by VideoPlayerCode** [comment]
> Ok, I reopen.Accessing the Electron or Dom API can only be done in the core.
> If anyone wants to give it a try, I'm open for a PR.

Ouch. I see. Well at the very least, let's expose the Electron `nativeTheme` API (with both the function for checking and the ability to register callbacks) to extensions so that they can react to the correct theme. It would be needed regardless of whether switching is added to core. See: https://github.com/microsoft/vscode/issues/61519#issuecomment-558871045

**Comment by VideoPlayerCode** [comment]
> If this can be done via browser event as @Tyriar describes, even better.

It can. As mentioned, I tried it in VSCode's built in Electron console. But why is that method preferable over Electron's API?

Also thank you @muuvmuuv for looking into this!

**Comment by Tyriar** [comment]
@VideoPlayerCode we don't want to rely on Electron APIs as then they don't transfer for when VS Code is [run in the browser](https://visualstudio.microsoft.com/services/visual-studio-online/) and also Electron APIs could change and web APIs won't.

**Comment by VideoPlayerCode** [comment]
@Tyriar Woah, I didn't know vscode can run in the browser!

Well then it is fantastic that the web API exists! I hope extensions can get access to querying the various accessibility aspects. The Electron API gives hints: https://electronjs.org/docs/api/native-theme

DARK
INVERTED
HIGHCONTRAST

Those are the three types of accessibility themes available.

@aeschli already mentioned that vscode supports one of them and sends and event to all extensions.

So here is stage 1 proposal:

1. Support all three events via media match query. 
2. Send the event to extensions when they happen. 
3. Add APIs to let extensions statically query the active mode.

Stage 2: theme switcher built into Vscode, based on the principles established in stage 1.

**Comment by muuvmuuv** [comment]
Makes sense, when I have more time I will look into this and try to expose the window API to extension authors.

**Comment by muuvmuuv** [comment]
I had time to look a bit deeper into the Core and this request. It seems like that the new Electron API has some deprecation (and Code needs too much time to update electron) regarding the method to get the preferred theme. So using the window match media makes the most sense. I'll try (first time contributing to Core) to set up a first proposal today. Since it wasn't clear enough to me what the high contrast thing does (and because it is windows only at this time) I'll leave it as is for now. Starting today with setting up the schema and logic. Stay tuned.
The new setting would be at `workbench.colorThemeAutoSwitch: true/false`, open for other suggestions. But this makes the most sense to me to keep the readability for users and to be visible in the search together with `colorTheme`.

**Comment by muuvmuuv** [comment]
Hey all!

Finished up something. Commit/PR will go out today. Would love to get some feedback. I'm pretty sure I have implemented it on the correct location but would like to get someone approved this first, before I continue cleaning it a little up. 

For the moment I have not exposed the browser API with match media query rather have directly coded the theme switch into the core, which IMO makes more sense. I'm the Author of Sundial, which of course would make my extension a little useless but unless I created it just for the moment as soon as Code implements it by its own, I'm fine with that and still, Sundial provides some useful options besides the "auto theme switch".

Here is a little preview for VS Code in a browser (I haven't been able to run the native version yet):
https://imgur.com/a/o2DVjCW

**Comment by VideoPlayerCode** [comment]
@muuvmuuv That's excellent progress, thanks for working on this!

As for "high contrast", press Win+S to search, type "high contrast", and enable it. It's basically a Windows 3.1 theme. The dialogs become pitch black except for a pixel-arty window outline. ;-)

And as for the "inverted theme", I am not sure where to turn it on in Windows, but it's definitely available on Macs, and it is literally the "inverted colors" effect. It just turns everything on-screen into their opposite colors. It used to be a smart solution before "Dark themes" existed in the world.

Your current solution supports dark theme switching, and doesn't expose any API to extensions. Seems fine.

If we ever expose APIs, we should expose dark mode, high-contrast mode, and inverted mode.

And yes, using web media queries is better than the Electron API, as people mentioned above. It's more portable and works in the web browser version of VS Code.

Hope these answers help. Thanks a lot for your great work!
