### ISSUE TITLE
escaped quotation marks doubles in launch.json when I debug

### ISSUE THREAD

**Issue by kuolu** [microsoft/vscode#61531]
Hello vscode community, thanks for your amazing work.

I ran into issues as I was trying to debug my python code that involves sub arguments. For instance, a simplified version of my commandline is:
```commandprompt
python foo.py --my_rules replace_text:"current string":"replacement string"
```
So when I try to debug, I have my launch.json as:
```json
"configurations":[
  {
     "name":"my debugger",
     "program":"foo.py",
      "args":[ "--my_rules","replace_text:\"current string\":\"replacement string\""]
  }
]
```
which should be equivalent to my ideal CMD input.
However, this is what I got in my terminal:
```commandprompt
...python.exe {myworkplace}\foo.py --my_rules replace_text:""current string"":""replacement string""
```

and thus creates error taking the arguments since `\"` creates `""`. BTW I tried different spacing as well. It is not a expected JSON behavior and I couldn't find any answers from StackOverflow. I would really appreciate if someone can help. 

Best regards

**Comment by DonJayamanne** [comment]
@isidorn 
We'll need to reopen this issue as its VSC that's not escaping correctly.
The extension is passing the raw data that needs to be used for launching a terminal. VSC then builds the command and launches the code in the terminal.

Similar to https://github.com/Microsoft/vscode/issues/61056

**Comment by Some-Dood** [comment]
Hello there. I'd love to extend the discussion here by providing some additional information based on my experiences with this bug.

I recently finished setting up my Python development environment in VS Code (Windows) a few hours ago, but the debugger simply will not start. After investigating, I found that VS Code runs a batch script in the integrated terminal (Git Bash) when I press F5 (Launch Program). I redacted some information and enclosed them in the `${}` notation for privacy reasons.

```batch
cd "${workspaceDir}" ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 "C:\Program Files (x86)\Python37-32\python.exe" "\"c:/Users/${REDACTED}/.vscode/extensions/ms-python.python-2019.5.17059/pythonFiles/ptvsd_launcher.py\"" --default --client --host localhost --port 56666 "${workspaceDir}\.vscode\launch.json"
```

I'd expect VS Code to run the debugger from here, but instead, it gives me this error from the Python interpreter executable:

```
C:\Program Files (x86)\Python37-32\python.exe: can't open file '"c:/Users/${REDACTED}/.vscode/extensions/ms-python.python-2019.5.17059/pythonFiles/ptvsd_launcher.py"': [Errno 22] Invalid argument
```

Investigating further by launching the debugging session in an external terminal, I find that the issue may have something to do with the name of my user folder in Windows, which is my full name. For the sake of example, let's say my user folder name was "Full Name". This time, the Python executable would give this error:

```
C:\Program Files (x86)\Python37-32\python.exe: can't open file 'c:/Users/Full': [Errno 2] No such file or directory
```

Since the full path (the argument of the `python` executable) gets truncated for some reason, it seems that this is where the bug is, but I noticed something strange in the batch script that VS Code runs in the integrated terminal. For readability, adding `python` to the `PATH` environment variable and rearranging that script in a more decipherable manner leads to this:

```batch
cd "${workspaceDir}";
env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 python "\"c:/Users/${REDACTED}/.vscode/extensions/ms-python.python-2019.5.17059/pythonFiles/ptvsd_launcher.py\"" --default --client --host localhost --port 56666 "${workspaceDir}\.vscode\launch.json";
```

VS Code is simply trying to run the Python interpreter with the `c:/Users/${REDACTED}/.vscode/extensions/ms-python.python-2019.5.17059/pythonFiles/ptvsd_launcher.py` debugger launch script as its argument. All is fine in that regard, but the issue reveals itself when taking a closer look at line 2 (the invocation of the `python` executable via the `env` executable in Git Bash). VS Code inserts too many escaped quotation marks in the file argument of the `python` executable.

```batch
REM: This is what VS Code is doing...
python "\"c:/Users/Full Name/file.py\""

REM: Which in turn is basically saying...
python ""c:/Users/Full Name/file.py""
```

So that's where the issue is, at least I think so. Manually running `python` in the terminal with the correct arguments (in this case, the correct command without the issue of having too many quotation marks would be `python "C:\Users\Full Name\file.py"`) works as expected.

# Conclusion
Somehow, VS Code inserts too many quotation marks before running a script in a terminal. Perhaps this is affected by the fact that VS Code detects whitespace in the full qualified file path of an argument, and as such, deems it necessary to include quotation marks to escape it. To begin fixing this bug, the logic for detecting whitespace and inserting escaped quotation marks must be looked into.

**Comment by weinand** [comment]
The quotes that you use in your command line:
```
python foo.py --my_rules replace_text:"current string":"replacement string"
```
are not required by your "foo.py" program.
You use the quotes to make sure that the command shell you are running in passes everything as one argument to "foo.py".

This means you are assuming a specific shell when using quotes in the launch config's "arg" attribute:
```
"replace_text:\"current string\":\"replacement string\""
```

This is wrong because you don't know what command shell is being used.

Fix your launch config by removing the quotes:
```json
  {
     "name":"my debugger",
     "program":"foo.py",
      "args":[ "--my_rules","replace_text:current string:replacement string"]
  }
```
Based on the command shell being used VS Code will use the correct mechanism to protect the spaces and pass a single argument to "foo.py".
