### ISSUE TITLE
Ctrl+Down gets stuck when a folded section is reached.

### ISSUE THREAD

**Issue by rsthn** [microsoft/vscode#61552]
- VSCode Version: 1.28.1
- OS Version: Microsoft Windows 10 [Version 10.0.17134.228]

Steps to Reproduce:

1. Fold any section (in any language).
2. Press Ctrl+Down to move down until the top of the screen reaches the folded section. You will notice further scrolling is not possible. This only happens with Ctrl+Down. The Ctrl+Up seems to be fine.

Does this issue occur when all extensions are disabled?: **Occurs Always.**

**Comment by aeschli** [comment]
I can't reproduce. 
![scoll](https://user-images.githubusercontent.com/6461412/47354120-25234980-d6be-11e8-9f03-2dbc18ce4ba3.gif)

**Comment by rsthn** [comment]
My suggestion would be to add "revealCursor" option to editor actions "scrollLineUp" and "scrollLineDown".

**Comment by bmalehorn** [comment]
I ended up writing an extension that replaces & works around some issues with `editorScroll`: [Scroll Viewport](https://marketplace.visualstudio.com/items?itemName=bmalehorn.scroll-viewport). Ultimately, this bug should probably be called:

### `editorScroll` with `revealCursor` cannot scroll down past folded code
Repro:
1. Set this keyboard shortcut
```
  {
    "key": "ctrl+down",
    "command": "editorScroll",
    "when": "textInputFocus",
    "args": {
      "to": "down",
      "by": "line",
      "revealCursor": true,
      "value": 10
    }
  },
```
2. Fold code
3. Try to press Ctrl+Down to get past it

![Peek 2019-09-21 00-22](https://user-images.githubusercontent.com/3344958/65369775-4100d980-dc06-11e9-860a-0e3b49835b58.gif)

Strangely, this only happens when scrolling down, not scrolling up.

This probably happens because lines 74-74, then 100-120 are visible due to code folding. If I say "scroll down 10 lines", it will try to move the cursor to line 84, get confused, and round back to line 74.

In my own extension I worked around this to walk over the visible ranges [here](https://github.com/bmalehorn/vscode-scroll-viewport/blob/e430415/src/extension.ts#L22-L38). Perhaps `editorScroll` could do something similar.
