### ISSUE TITLE
Windows: submenu indicator rendered very large

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#61564]
See: 

![image](https://user-images.githubusercontent.com/900690/47339890-e9c45300-d69c-11e8-9e75-fa2a6668a738.png)

Compared to native:

![image](https://user-images.githubusercontent.com/900690/47339905-f2b52480-d69c-11e8-84d6-75569938f089.png)

/cc @misolori

**Comment by sbatten** [comment]
We had this discussion at one point. Here is right clicking on windows desktop today
![image](https://user-images.githubusercontent.com/6561887/47461292-4e62d900-d795-11e8-9c21-d4f14957f2a9.png)

but I may reduce it due to edge conflicting now with:
![image](https://user-images.githubusercontent.com/6561887/47461380-82d69500-d795-11e8-91f0-2045f33237ad.png)

Though I would say the screenshot by @bpasero is too small

**Comment by bpasero** [comment]
I think Edge is a good one for aligning with as it seems to represent the new modern look of Windows.

**Comment by sbatten** [comment]
fixed by #60304
