### ISSUE TITLE
  CTRL + mouse cursor causes causes the current source code was overwritten！！！！！

### ISSUE THREAD

**Issue by RonnieLyu** [Microsoft/vscode#61569]
- VSCode Version:1.28.2
- OS Version:Windows OS 10

Steps to Reproduce:

1.When using the an automatic function jump, the current file will be overwritten with the jumped file
2.This happens randomly.
3. Linux  C project

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by weinand** [comment]
What do you mean by "automatic function jump,"?
Please provide steps for how to reproduce the problem.

**Comment by RonnieLyu** [comment]
I' m sorry.My English is not  good. When the mouse cursor moves to a keyword, such as an external function or macro, and holds the CTRL key, the current file is overwritten.

**Comment by RonnieLyu** [comment]
![image](https://user-images.githubusercontent.com/25006975/47347792-9674f380-d6e2-11e8-87ee-a82f49e4eda1.png)

**Comment by weinand** [comment]
Probably you do not mean "overwritten" but you mean: the new file replaces the current file in the editor.

This happens if your current file is not "pinned" (and shows the name in the editor's tab slanted).
You can "pin" a file by double clicking in the editor tab or by modifying the file.
A "pinned" file is not replaced if a another file is opened.

If you don't like this behaviour you can turn it off via the

**Comment by RonnieLyu** [comment]
Thank you very much.!!!!!
