### ISSUE TITLE
Threads continue event

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6160]
- [x] win - PHP (isidor has a vm where PHP is setup) - **@bpasero**
- [x] linux - C++ (very easy to setup) - **@weinand**

C++ example - https://gist.github.com/edumunoz/80275bd231abb56165eb
PHP example - any simple php script, just launch it multiple times

We have changed how the continue event behaves. Have a multi-threaded program and verify step / continue / stop behave as expected. 

For PHP verify that continue only continues the selected thread, as for C++ verify that continue continues all the threads.

Also verify:

* Newly created threads are reflected in the callStack view 
* One thread resuming execution does not affect other stopped threads
* A thread that exits should disappear from the call stack view

**Comment by Tyriar** [comment]
@isidorn I couldn't figure out how to debug the C++ program. I did the following:

- Install cpptools
- Create `vscode-repro.cpp`
- Tried to debug, I need to compile first
- After some experimenting I landed on this to compile: `g++ -Wall -Wextra -Werror -std=c++11 -c vscode-repro.cpp -o vscode-repro.out`
- Tried to debug, hit this:

  ![image](https://cloud.githubusercontent.com/assets/2193314/15515941/4d05bcf6-21a5-11e6-81e8-be250e486295.png)

  ![image](https://cloud.githubusercontent.com/assets/2193314/15516121/37a162ba-21a6-11e6-9fb6-6b375feb1d16.png)
- Because of the permission error I thought I'd add +x to the .out file but it didn't work.

**Comment by weinand** [comment]
I've used this command

```sh
g++ -pthread -std=c++11 -g threads.cpp
```
to compile this program:

```C++
#include <iostream>
#include <cstdlib>
#include <pthread.h>
#include <unistd.h>
#include <string.h>

using namespace std;

#define NUM_THREADS	  5
#define LOOP false

void *wait(void *t)
{
	long tid = (long)t;

	do {
		sleep(1);
		cout << "Sleeping in thread " << tid << endl;
	} while(LOOP);

	return NULL;
}

int main ()
{
	int rc;
	long i;
	pthread_t threads[NUM_THREADS];
	pthread_attr_t attr;
	void *status;

	// Initialize and set thread joinable
	pthread_attr_init(&attr);
	pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_JOINABLE);

	for (i= 0; i < NUM_THREADS; i++) {
		char buf[20];
		sprintf(buf, "Thread %d", (int)i);
	  	rc = pthread_create(&threads[i], NULL, wait, (void*) i);
	  	if (rc) {
			cout << "Error: unable to create thread," << rc << endl;
			exit(-1);
		}
		pthread_setname_np(threads[i], buf);
	}

	// free attribute and wait for the other threads
	pthread_attr_destroy(&attr);

	for (i= 0; i < NUM_THREADS; i++) {
		rc = pthread_join(threads[i], &status);
		if (rc) {
			cout << "Error:unable to join," << rc << endl;
			exit(-1);
		}
		cout << "Main: completed thread " << i <<  "with status " << status << endl;
	}

	cout << "Main: program exiting." << endl;

	pthread_exit(NULL);
}
```

Setting a breakpoint on line 18 nicely shows that all threads are stopping when the breakpoint is hit, and all continue on the 'continue' command.

**Comment by Tyriar** [comment]
Thanks @weinand
