### ISSUE TITLE
I change the font family in the setting but I still have the old font

### ISSUE THREAD

**Issue by juanjardim** [Microsoft/vscode#61617]
I was trying to have a better font for the editor, but when I put back the default one I still have a the last weird font

Current Settings
![image](https://user-images.githubusercontent.com/1913469/47364998-ee0f6100-d6da-11e8-945d-a88097035e18.png)

Weird font
![image](https://user-images.githubusercontent.com/1913469/47365042-febfd700-d6da-11e8-88b0-92c7ce9a6edc.png)

Can you help me?

**Comment by alexandrudima** [comment]
@juanjardim That looks like the fallback font. Are you sure you have the font installed and are typing the name correctly ?

**Comment by juanjardim** [comment]
@alexandrudima ,

I found the issue. It's in the .vscode/settings.json. After updating the editor.fontFamily, it doesn't update this file with the new value.
What I did was change directly the file to have the correct value and restart. Now it's fine.

Could be a bug?

**Comment by pricetula** [comment]
OS: ubuntu 18.10
VS Code: Version: 1.28.2

settings.json
```
{
  "editor.fontFamily": "'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'"
}
```

Even after saving and restarting VS code the font family has not changed

**Comment by alexandrudima** [comment]
I cannot reproduce what you are describing. When I edit the `editor.fontFamily` and **save** the file, the change is applied immediately.

![kapture 2018-10-24 at 17 50 34](https://user-images.githubusercontent.com/5047891/47443761-5a5e9300-d7b5-11e8-8a87-b0424d8fe76e.gif)

**Comment by juanjardim** [comment]
If you do this in the file its fine, but if you go to throw the menu "Settings" and the change the editor.fontFamily this doesn't take effect

**Comment by alexandrudima** [comment]
@juanjardim That also appears to work fine for me:

Keep in mind, there are two distinct settings: **user** settings and **workspace** settings. **user** settings are applied for all windows you open and live on disk somewhere in your home directory and **workspace** settings are applied only to a specific folder you open and live on disk in the folder in `.vscode/settings.json`. It is **not wise** to customize something like the `editor.fontFamily` in **workspace** settings because that means only that folder will have a custom font family and with the next folder you open you're gonna have the default again. Also, it is important to note that **workspace** settings overwrite **user** settings, so if you have `editor.fontFamily` configured in **workspace** settings it will win over `editor.fontFamily` configured in **user** settings.

I am almost certain that this is covered in the documentation at https://code.visualstudio.com/docs/getstarted/settings

![kapture 2018-10-24 at 19 10 15](https://user-images.githubusercontent.com/5047891/47448537-8df2ea80-d7c0-11e8-9d3d-b3da086c7dd7.gif)

**Comment by juanjardim** [comment]
Thanks. 
Now I understand the issue
