### ISSUE TITLE
IntelliSense: do not steal arrow keys if there is only one suggestion showing up

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6163]
I find myself fighting over intellisense often when I am typing the variable name and then wanting to jump to the next line using arrow keys (down). The suggest widget shows me the completion for the variable I just typed and now I cannot arrow-down, I first have to dismiss the widget.

This video shows where I get stuck all the time:

![untitled](https://cloud.githubusercontent.com/assets/900690/15076679/22bb38de-13ab-11e6-80fc-e2adf5c45aa5.gif)

@alexandrudima @joaomoreno maybe in this case where you only have 1 suggestion, let me type arrow keys even if suggest is open?

**Comment by joaomoreno** [comment]
Note that you may have a single suggestion due to a couple of different scenarios:

- You typed `he` and the only suggestion is `hello`.
- You typed `hello` and the only suggestion is `hello`.
- You typed `helloworld` and the only suggestion is `hello`.
- You typed `something` and the only suggestion is `hello`.

Should we not eat up the keybindings in all those cases? Not so sure.

**Comment by bpasero** [comment]
@joaomoreno how is that relevant? in all these cases you select the one entry for me in the suggest window so I do not need to type arrow-down to pick it. In the case of 1 suggestion, let me type arrow down to navigate lines.
