### ISSUE TITLE
Make RunInTerminalResponse return processId as documented

### ISSUE THREAD

**Issue by gjsjohnmurray** [Microsoft/vscode#61640]
Per #16786 (Dec 2016) it seems that the initial implementation (#10574) of RunInTerminalRequest wasn't able to provide the processId field in its RunInTerminalResponse.

Any chance that subsequent developments might make this feasible now? For example, #14286 looked like it could be relevant.

**Comment by weinand** [comment]
It is not possible to return the process id of the command that runs in the shell.

With the fix for #14286 it is possible to get the process id of the shell, but not of the command that runs inside the shell.

**Comment by gjsjohnmurray** [comment]
So maybe give us the process id of the shell? Then since we're in control of what command it's running, perhaps in some cases it'll be possible to determine the command's process id (e.g. looking for child processes?). Just a thought...

**Comment by weinand** [comment]
@gjsjohnmurray I agree that returning the shell's id is better than nothing.
But I cannot return this id under the `processId ` attribute because existing debug adapters would expect the command's id here.
I suggest that you create a feature request for adding a "shellProcessId" at https://github.com/Microsoft/debug-adapter-protocol/issues.
