### ISSUE TITLE
Cursor Location inaccurate on second monitor.

### ISSUE THREAD

**Issue by cgoss** [microsoft/vscode#61641]
- VSCode Version: 1.27.2 
- OS Version: Windows 10 Enterprise 1803 Build 17134.345

Steps to Reproduce:
Pre Condition: 
Dual monitor setup. Screen 1 on top of Screen 2. 
Screen 1 Scale set to 150%
Screen 2 Scale set to 125%

1. Have Visual studio code open with a python script on Screen 1.
2. throw down some p-thon
3. Move the cursor back a few char positions and make note. 
4. Pull the vs code app from Screen 1 to Screen 2 where it resizes. 
5. Note the relocation of the cursor. 
6. Modify your code and note that the cursor does not match the output text. 

Does this issue occur when all extensions are disabled?: Unsure. 

Note: I am unsure if this is a Windows 10 bug or Visual Studio code bug but I have not noticed this on other software at the time of this bug report. In the meantime I have aligned my screen scaling as a work around for this issue.

**Comment by jmin911** [comment]
This is caused by scaling difference.  The bigger the scaling difference, the more evident.
I have my surface book 2's main monitor set to 150% scaling, and my external monitor set to 100% scaling.  Leaving VSCode open after the monitor switch will result in bad the cursor alignment.  The workaround is to restart VSCode.
