### ISSUE TITLE
Vscode is getting more and more stuck now.

### ISSUE THREAD

**Issue by Greatwallycc** [Microsoft/vscode#61769]
One of the advantages of vscode over webstorm is that it's lightweight and efficient, and now it's becoming as high-memory as webstorm, and some stutters, I prefer to use webstorm If always so. 
  Now the problem is: I don't know why, often typing code, select, copy, paste and many other very simple operations need to wait a few seconds, It leads to that I can't work at all, restart but after a period of time it comes to the same situation, I open the task manager, vscode occupied nearly 1 G of memory! 
  So I hope vscode can solve this problem as soon as possible and become better and better.
                                                                                                ---- from a coder who likes vscode very much.

**Comment by gocs** [comment]
check `Help > open Process Explorer` and Identify which process takes memory.

**Comment by weinand** [comment]
your bug report does not contain any information that could help us investigating the issue.
Please read and follow our issue reporting guideline:
https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#reporting-issues.

It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by thefiddler** [comment]
I believe sublime text allows you to switch editor tabs by holding right-click and scrolling with the mouse wheel (same functionality as ctrl-tab / ctrl-shift-tab in vscode).

This is a brilliant little usability trick originating from the Opera browser back in the old days.

**Comment by weinand** [comment]
@thefiddler you comment was probably meant for a different issue, right?

**Comment by fpsqdb** [comment]
Same issue here, CPU 50% for some seconds randomly

**Comment by kieferrm** [comment]
Please file an issue following the instructions here: https://github.com/Microsoft/vscode/wiki/Performance-Issues
