### ISSUE TITLE
TextDocument needs a dispose() method or leaks otherwise

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#618]
There currently seems to be no way of explicitly disposing a `TextDocument` instance. Only if you show it inside a `TextEditor` you are able to call a built in command to dispose the document (e.g. by closing the editor if the file is not in working files or by calling Close All Files command).

Without a dispose() method, the `workspace.textDocuments` array will leak entries.

**Comment by jrieken** [comment]
Since you cannot create documents you should not be allowed to dispose them. This will become interesting once we allow to create new documents

**Comment by jrieken** [comment]
Treating this as dup of #272

**Comment by bpasero** [comment]
@jrieken you can, I even have a test for it: https://github.com/Microsoft/vscode/blob/master/extensions/vscode-api-tests/src/workspace.test.ts#L32

**Comment by jrieken** [comment]
Not really @bpasero because `open` will just return a document if it is already open. Also, the workbench should stop disposing documents that were opened via this call which is doesn't. I don't believe it's a good idea to expose dispose for `file` and `untitled` because the core creates and managed them, for other schemes (#272) it's a different situation.
