### ISSUE TITLE
Cannot turn off HTML comment autocomplete

### ISSUE THREAD

**Issue by Inartus** [microsoft/vscode#61854]
This is infuriating.
When I am commenting out existing code, I have to continually delete the auto-completed extra code.

I type
`<!--`
And it becomes `<!---->`
This assumes I am about to write a new comment - nine times out of ten I am commenting out existing code.

Thank you

Paul

**Comment by weinand** [comment]
Instead of commenting out manually, you can use the various "Comment" functions, e.g. "Toggle Line Comment" (Cmd-Shift-7).

And please see https://code.visualstudio.com/docs/editor/intellisense#_customizing-intellisense for how to configure autocomplete.

**Comment by Inartus** [comment]
Thanks - I will use the Toggle Line and Block Comment features. I do know about these. Just never got into the habit of using them. Breaking old habits, I suppose.
BTW - My intellisense settings already say that editor.quickSuggestions comments are false.
Most of the time I just want the editor not to add anything to what I type.
Thank you again.

Paul

**Comment by aeschli** [comment]
If we make these configurable it should not just be for html, but for all languages.

Ideally would allow all language configurations to be customized in the settings.

**Comment by alexandrudima** [comment]
@aeschli I think this is an HTML specific issue. For example when I type `/*` in C++ I do not end up with `/**/`.

**Comment by aeschli** [comment]
@alexandrudima Yes, html defines
```
	"brackets": [
		["<!--", "-->"],
```
Of course we can remove that one again, making the user that requested it unhappy.
IMO it would be great if we let users customize that behaviour (and all other language configurations)

**Comment by alexandrudima** [comment]
@aeschli It is a great idea to allow for configurable settings.

But in this specific case I believe the workaround implemented via https://github.com/Microsoft/vscode/commit/b08ba054ba6f00a5a7be0c10a1f55173db2b7d55 to auto-close `<!--` with `-->` to fix a folding bug is perhaps a not-so-good workaround since it is generating real user issues. I disagree with the issue #46655 in the first place, I find that issue artificial. Whenever I comment code, I care about commenting code, I do not care about folding ranges. And if the entire file is one large comment because I have introduced a leading `<!--`, then so be it, I have larger problems like the file being all green and executing it not doing anything since it's a comment. IMHO auto-closing behaviour should not be added so lightly (just in order to mitigate - not resolve) an artificial folding issue.

**Comment by aeschli** [comment]
Sorry, reverting #46655 is currently not an option. Loosing the folded regions as soon as you start a comment was a major problem with several people with carefully folded documents. The chosen solution is pragmatic and also useful for other cases. I'm not aware of better solution, not did I get many complains for the current behaviour.
To me, making auto-pairs configurable is the best option. It would solve this issue as well as be useful in other cases. We have #38352 for that request. Marking as duplicate.
