### ISSUE TITLE
Integrated Terminal : Start named session

### ISSUE THREAD

**Issue by RuiffCardoso** [microsoft/vscode#61865]
Although renaming integrated terminal sessions is allowed (#10023), I can't find an easy way to automatically do it when you debug an application. When using "console": "integratedTerminal" in launch.json, it would be nice to have an "integratedTerminalName" attribute available.

This is specially useful, since currently is not possible to have multiple debug console windows and when running multi project and need to read each project output on a different window, navigation through the many terminals is hard, and renaming each manually after launching is a very repetitive and hard to do everytime task.

**Comment by weinand** [comment]
Supporting to name a terminal via a launch config involves the debug extension because the names and types of properties of a launch config are not defined by VS Code. So we (VS Code) cannot just add a "terminalName" property generically. Every debug extension that supports the integrated terminal needs to introduce a "terminalName" property in its launch config schema and pass this to the [`runInTerminal`API](https://microsoft.github.io/debug-adapter-protocol/specification#Reverse_Requests_RunInTerminal).

I suggest to file a feature request against the debug extension that supports to launch debuggee in the integrated terminal.
