### ISSUE TITLE
"Open Editors" panel becomes out of sync with tab bar after drag

### ISSUE THREAD

**Issue by dag10** [Microsoft/vscode#61899]
Issue Type: <b>Bug</b>

Repro:
1) Drag a file from the folder panel to the "open editors" panel, dragging it onto an existing file. I did this with the intention of opening a file at a specific position in my tab bar.
2) The file will appear in the tab bar, but not in the open editors list.
3) Clicking on the tab in the tab bar will highlight the old file in the open editors panel that you originally dragged the file onto.
4) The highlighted file in the "open editors" panel will always be off-by-one when you're viewing a file above the file you dragged.

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.68GB (47.83GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe C:\Workspaces\main\src\vrwebui|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-chrome|msj|4.10.2
perforce|sle|3.1.0
vim|vsc|0.16.11

</details>

**Comment by dag10** [comment]
Here's a zipped mp4 showing the bug on the Insiders build.

[vs_code_bug_repro.zip](https://github.com/Microsoft/vscode/files/2526005/vs_code_bug_repro.zip)

Simpler repro steps:
1) Locate a file from the open folder that's currently also open in the editor list.
2) Drag that file from the folder list onto the editor list into a new position.
3) Notice that editor list is now out of order when you click on some files in it.

**Comment by isidorn** [comment]
Great, thanks for repro steps, will investigate

**Comment by isidorn** [comment]
I have investigated this and I can reproduce.
The issue is that the `editorGroupView` is sending an `EDITOR_ACTIVE` change event instead of the `EDITOR_MOVE` event.
Forwarding to @bpasero since the issue hapens in the `editorGroupView`

Easy repro steps

1. Open two files 1.txt and 2.txt in the open editors list in that order
2. Drag 2.txt from explorer to the top of the Open Editors list
3. The editors change order however I only get an Active event, not the Move one

**Comment by bpasero** [comment]
This was a bit more work but I think the fix is good: previously the editor part would only emit events for moved editors when `moveEditor()` was explicitly called. However, it is easily possible to move an editor by calling `openEditor()` with an editor that is already opened but providing a different index (that is what happens in this case). Now, I detect this case (index provided, editor already opened at a different index) and run through the same code as `moveEditor()` before continuing to open the editor. 

I hope this does not break anything elsewhere, but I actually think this may fix the same issue from other places where we might use an explicit index when opening an editor.

**Comment by isidorn** [comment]
@bpasero thanks for the fix and the explanation. Let's keep our eyes open in case of regressions.
