### ISSUE TITLE
[feature request]: keep git message on undo last commit

### ISSUE THREAD

**Issue by AliMD** [Microsoft/vscode#6190]
I usually forgot to select special file for commit and undo last commit, select target files, commit again but i must write commit message again
Could you please add feature for restore message on undo last commit
Thank you in advance

**Comment by joaomoreno** [comment]
This is a great contribution, wanna give it a try?

**Comment by AliMD** [comment]
@joaomoreno yes of course, thank you

**Comment by sijad** [comment]
this seems easy to implement, @AliMD is it ok I work on this?

**Comment by AliMD** [comment]
@sijad yes off course
I have issue to get last commit message from git!

`ممنون سجاد جان`

**Comment by bill-mybiz** [comment]
This seems like it would be a perfect combination for issue #7830 about allowing for more powerful git messages. Whatever the persistence mechanism would be for previous git commit message, if none listed, it could then check for the [`commit.template` config setting](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Basic-Client-Configuration). In that issue, I've also made some notes as to my investigation into the architecture/process.

@sijad Are you still working on this, and if so, could you include the template in the workflow?

**Comment by sijad** [comment]
@bill-mybiz good call
I didn't spend much time on it. I'm not sure with the best practice to access to commit input and change its value.

**Comment by sijad** [comment]
I think this has been fixed #8933

**Comment by bill-mybiz** [comment]
@sijad I had it "working" per initial tests, but it was removed to make the other PR (#8933) on the Git Commit Template cleaner. I have considered whether or not to go ahead with the same approach to the fix for the previous commit msg, but because of other work I'm repurposing the machine that I was doing that work on. I also am unsure of @joaomoreno 's thoughts on how to approach it overall. 

Also the approach may not have been viable anyway, since I had it actually get the information (from my foggy memory) in the `UndoLastCommitAction` execution. Because the architecture is highly distributed, I could find no way to communicate between the action and the `ChangesView`, so I had possibly kluged it by communicating via a key/value entry in the `IStorageService`. Then in the `ChangesView`, I checked for this key/value and set the `commitInputBox` if the key/value existed (and then immediately removed it to make it idempotent). 

The problem with this was that I was [checking for the `RESET` operation](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/browser/views/changes/changesView.ts#L408), which I'm guessing gets triggered _also_ via the unstage action (I don't know the name), because it [caused a bug](https://github.com/Microsoft/vscode/pull/8933#issuecomment-234026210) that completely wiped out the current commit msg when you unstage any single file. 

Anyway, the point was that it needed further investigation, and I wasn't sure of other possible approaches anyway. All the code I did can be seen in [some of the commits](https://github.com/Microsoft/vscode/pull/8933#commits-pushed-db79a45), keeping in mind that we changed the design from a git operation with `ICommitInfo` to a cleaner function call returning a string with the template.

If we get @joaomoreno 's thoughts on how to approach a cleaner solution for this, I could work on it as soon as my new environment is back up, or whoever does work on it could use my [notes from the other issue](https://github.com/Microsoft/vscode/issues/7830#issuecomment-227515411) to help get up to speed faster.

**Comment by joaomoreno** [comment]
I think we should implement the equivalent of the `git log` command, in `git.lib.ts`. This will let us get information about any commit we wish. Upon execution of the `UndoLastCommitAction` we could call that method on `HEAD` in order to get the commit's message and then undo the last commit. These would be two separate calls.

**Comment by bill-mybiz** [comment]
Ok, so basically the same thing I had done in the other PR, but changed from using `ICommitInfo` to returning a string, in addition to placing it lower in the `git.lib.ts`. I can try it out here today or tomorrow once that environment is back up and going.
