### ISSUE TITLE
Duplicate icon in GNOME sidebar when Code is added to the favorites

### ISSUE THREAD

**Issue by alessandrodolci** [Microsoft/vscode#61989]
- VSCode Version: 1.27.2 (OSS Code, but also happens in the latest VS Code on Ubuntu)
- OS Version: Arch Linux (kernel 4.18.12-arch1-1-ARCH)

When adding Code to the favorite applications in the GNOME environment, a duplicate icon spawns when launching the application.

![screenshot from 2018-10-28 19-05-50](https://user-images.githubusercontent.com/27001991/47619957-8dba5e00-dae4-11e8-940e-e5560e43b145.png)

Steps to Reproduce:

1. Add Code to favorite applications in GNOME
2. Open an instance of Code and switch to the activities overview 

Does this issue occur when all extensions are disabled?: Yes

I'm willing to try to solve the issue if you confirm that it is related to the application.

**Comment by jpalomaki** [comment]
This also happens on Ubuntu 18.04.1, running GNOME `3.28.2` and code `1.29.1-1542309157`.

**Comment by Al2Me6** [comment]
Can reproduce.

Kubuntu 18.10, kernel 4.18.0, KDE 5.14.3, Code 1.29.1.

Steps to reproduce: pin Code to the taskbar. The hover menu shows "Visual Studio Code." Open the application. Instead of opening under the pinned icon, a new icon shows up with description "Visual Studio Code - URL Handler."

It sometimes goes away after a reboot, but is mostly unpredictable. 

I have experienced this problem since Code 1.28.1.

**Comment by DiDeoxy** [comment]
Have same probelm

**Comment by davidbailey00** [comment]
I'm having the same problem - worth noting that someone has asked this question on Ask Ubuntu here: https://askubuntu.com/questions/1095206/vscode-activity-titled-visual-studio-code-url-handler
