### ISSUE TITLE
Ignoring tsconfig.json in Angular 2 CLI generated apps

### ISSUE THREAD

**Issue by ncrawlins** [Microsoft/vscode#6200]
- VSCode Version: 1.0.0
- OS Version: Windows 10

Maybe it's a problem with the project setup, but VSCode doesn't honor the experimentalDecorators flag and other tsconfig settings for any file you open AFTER the first file in an Angular CLI generated project.  You can close all files and wait a second and then open the files in a different order and the ones reporting errors will switch.

Steps to Reproduce:
1. Install angular 2 cli from NPM
2. use "ng new test" to create a new project.
3. Open the created directory in code.  The first TS file you open won't have any problems but all the ones you open after that won't use the tsconfig.json.
![code-ng2-bug](https://cloud.githubusercontent.com/assets/291462/15098770/dfde08a2-1512-11e6-8d05-deaaab3d34cd.gif)

**Comment by dbaeumer** [comment]
The problem is the generated tsconfig.json file. It contains a files section and list only two files main and typings.d.ts. Therefore the files under source aren't considered part of the project defined by the tsconfig.json file. 

Removing the files section makes it work as expected. Opened https://github.com/angular/angular-cli/issues/684.

I will also move this to the TS team since they should already issue an error on the first opened file in the src folder.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#8523
