### ISSUE TITLE
regression: early custom events do not work

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#62038]
Regression in Insiders:

bug https://github.com/Microsoft/vscode/issues/57641#issuecomment-417714767 is back!

Just check out the old branch https://github.com/Microsoft/vscode-mock-debug/commit/16ab549f99662c4b074e37f492a759fb2399ac54 and launch mock-debug with F5.
Starting a mock debug session results in this error:

![2018-10-29_13-40-22](https://user-images.githubusercontent.com/1898161/47650440-91032780-db80-11e8-8b86-b68da96f1273.png)

The debug session cannot be found.
It looks like the assertion that looking up a session ID must work as soon as the session ID is handed out, no longer works. I had fixed this for the September release.

**Comment by isidorn** [comment]
The issue here was that previosuly we had a large session collection in the `debugService` which duplicated the model information and contained sessions while they were still initialising.
With the multiple repl work I have cleaned this up and allowed debug model to have sessions which are inactive and initialising and removed this duplication from the debugService.
However I was still only adding the session to the model only when fully initialisied. With this commit I have changed that, and I am immedaitly adding the session to the model even before it is fully initialised.
This should not have any regressions on other features, since the session will appear as inactive (not yet connected).

I have tested with the mock sample and now it works just fine for me.
