### ISSUE TITLE
Delete line does not work properly when multiple cursors are on line

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#62112]
Issue Type: <b>Bug</b>

1. For a text file:

```
a
foo boo
too
c
```

2. Create a cursor after each `foo`, `boo`, and `too`:

```
a
foo| boo|
too|
c
```

3. Now run the `delete line` command

**Expected**

```
a
c
```

**actual**

```
a
too
c
```

VS Code version: code-oss-dev 1.29.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.54GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|22%|

</details>

**Comment by YisraelV** [comment]
I'd love to try and figure this out.

**Comment by alexandrudima** [comment]
The code is at https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/linesOperations/linesOperations.ts#L284:L296

**Comment by YisraelV** [comment]
It seems I'm going to have a lot of code reading and understanding for this one. Not sure how much time it's going to take so if anyone wants to take this don't wait because of me.

**Comment by YisraelV** [comment]
@alexandrudima I fugured out the source of the bug. Using this information I found another bug. I can suggest a solution as well. 

**Why is this happening**

In the example of the OP we have 3 delete operations:
a. delete line 2 
b. delete line 2 
c delete line 3
[This merging](https://github.com/Microsoft/vscode/blob/220bff273eed39013f24b6d26fc17f2a742ce10f/src/vs/editor/contrib/linesOperations/linesOperations.ts#L319-L335) code makes them into 2 delete operations:
a. delete line 2
b. delete lines 2-3

 this code [here](https://github.com/Microsoft/vscode/blob/220bff273eed39013f24b6d26fc17f2a742ce10f/src/vs/editor/common/controller/cursor.ts#L856-L892)  makes sure there are no overlapping edit operations. unfortunately it cancels operation b and leaves operation a intact.

**another bug found with this info**
1. for a text file:
abc
def
ghi

2. place one cursor after 'b' and one after 'e'
3. press shift+right-arrow until the first cursor selects parts of 1-2 lines, and the second cursor selects parts of 2-3 lines.
4. hit ctrl+shit+k

**expected result:** all 3 lines deleted
**actual result**:  only the first two lines are deleted.

This is happening for the same reason: since the operations overlap only one of them survives.

**suggested solution**

In the merging code make sure that deletes that overlap (and not only consecutive) are merged as well.

I tested it and it solves the the original bug as well as the one I found.

What do you think about this solution?

**Comment by alexandrudima** [comment]
> In the merging code make sure that deletes that overlap (and not only consecutive) are merged as well.

:+1: That is exactly what I would do.

**Comment by YisraelV** [comment]
@alexandrudima I see what you did there. Thanks for letting me take part!
