### ISSUE TITLE
CodeLens filtration on `resolveCodeLens` hook

### ISSUE THREAD

**Issue by Ky6uk** [Microsoft/vscode#62137]
Currently documentation guides us to return data from `provideCodeLens` **as soon as possible**. So I'd like to add some complicated logic to `resolveCodeLens` which includes a result filtration (ignoring some kind of lenses based of the long computation for example). But right now I'm getting a message `<<MISSING COMMAND>>` on lens I don't want to use inside `resolveCodeLens` hook.

So I'd like to return `null` from `resolveCodeLens` or something for lens should be ignored after computation of the `provideCodeLens` array.

I'm asking for ways to do it [here](https://stackoverflow.com/questions/53015793/how-i-can-filter-lens-inside-resolvecodelens). But still no responses yet.

**Comment by jrieken** [comment]
Filtering will not be possible defeats the purpose of the two step code lens resolution. The goal is to avoid flickering, that's why you should compute all code lenses quickly and later resolve them. If we would allow for filtering then the text would jump up and down as we resolve and that is unwanted.
