### ISSUE TITLE
Improve hover for JSON scheme warning in status bar

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#62149]
testing #62087:

Yes, there is now a warning icon in the status bar, but it is difficult to understand its purpose:

For a json scheme url with a non-existing hostname the hover message shows this: 

![2018-10-30_14-39-47](https://user-images.githubusercontent.com/1898161/47722419-b1031b80-dc52-11e8-869f-c8bfc3411203.png)

For a json scheme url with a non-existing version number the hover message shows this: 

![2018-10-30_14-50-41](https://user-images.githubusercontent.com/1898161/47722676-40a8ca00-dc53-11e8-8fd4-55ef79d8e901.png)

In both cases the error shown is too low-level and the message does not explain that the status refers to the json scheme of the current editor contents.

**Comment by aeschli** [comment]
FYI @xxyy...

**Comment by xxyy** [comment]
Looks like I misinterpreted what kind of messages I'd get from the backend, sorry for that! We could resort to showing a generic message like 'Unable to resolve JSON schema from (url)', which would probably be sufficient for most issues. I also considered logging the error to console (don't know your policy on that), but if we get whole pages in the error message, that's not an option.

Displaying a generic message with the URL only would also resolve #62147. Otherwise I guess we'd need to parse the error message to find out which kind and display a meaningful message, but that doesn't seem right.

Another implication of this is that we'll probably have to re-add at least one layer of error description to vscode-languageservice-json - I always had a prefix with something like "Unable to resolve (something)", but that might have been a code reloading issue or specific to the way I was testing, by cutting the Internet connection and blocking DNS resolutions.

Let me know if a generic error message defined only in the client would work.

**Comment by octref** [comment]
> We could resort to showing a generic message like 'Unable to resolve JSON schema from (url)', which would probably be sufficient for most issues.

That's fine. Users don't really see logs.

**Comment by octref** [comment]
I can repro with this setting:

```json
{
  "json.schemas": [
    {
      "fileMatch": [
        "foo.json"
      ],
      "url": "https://json-schema.org/404"
    }
  ]
}
```
