### ISSUE TITLE
conditional breakpoint in gutter is blurry

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#62166]
Version 1.29.0-insider

Double-click screenshot in order to see unscaled image:
![2018-10-30_16-09-39](https://user-images.githubusercontent.com/1898161/47728465-b23a4580-dc5e-11e8-8e6a-24a7fe8d9ea0.png)

Please note: icon in breakpoints view is sharp whereas icon in gutter is blurry.

We should avoid to scale the gutter icon.

**Comment by isidorn** [comment]
The issue here is that the icon in our debug viewlet is 19px by 19px and in the editor we have no control over the icon size, the editor only allows 18px by 18px.

@alexandrudima is it possible to control the size of the icon in the gutter margin? I did not find a way
@misolori is it possible to get a conditional breakpoint icon which looks better in 18px by 18px in case we are limited to this size?

**Comment by misolori** [comment]
@weinand what resolution is your monitor (1x, retina, 4k, etc.)?

@isidorn I can definitely make an icon in a 19x19 size while still retaining the original size.

**Comment by weinand** [comment]
@misolori thats an Apple 27" Thunderbolt Display (https://www.apple.com/displays/index.html)
with 2560-by-1440 resolution. Since it is non-retina the resolution is probably "1x" in your scale.

**Comment by isidorn** [comment]
@misolori I also see it on my monitor which is regular non retina 24 inch display. Maybe just try it on your monitor.
Also I believe we would need 18x18, since 19x19 seems to work already.
If you want to play around in code, here are some css pointers https://github.com/Microsoft/vscode/blob/f748c0b1636348ca8055d9dcadc4835a92cd0b1a/src/vs/workbench/parts/debug/browser/media/debug.contribution.css#L67

**Comment by misolori** [comment]
The only reason why I ask is because I'm seeing the rendering vary on my two monitors (retina and4k). I'll take a look and try to find a size that works.

**Comment by alexandrudima** [comment]
@isidorn The margin size is driven by `lineHeight`, so changing the `editor.lineHeight` will end up changing the margin size, which will end up changing the margin icon sizes.

**Comment by isidorn** [comment]
@alexandrudima thanks, it makes sense that the margin size is derived from line height.
Due to that we would need an icon that works better in the default margin size if possible @misolori

**Comment by isidorn** [comment]
We have new conditional breakpoint icon and I think this behaves better now
