### ISSUE TITLE
`splitCwd` has confusing naming

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#62180]
Testing #62096.

I think `splitCwd` is confusing. `cwd` means current working directory, however this setting is only for the **initial** working directory the split terminal inherits.

Also, in the context of "splitting terminal", I find the `source` in the options confusing. I need to look into descriptions to figure out what are `sourceCwd` and `initialSourceCwd`. Instead of relying on the abbreviated `C` for signaling the behavior of inheriting the working directory, I suggest:

- `terminal.integrated.splitWorkingDirectory` (`splitCwd` is ok if you insist not to change)
  - `inherit`
  - `initial`
  - `workspaceRoot`

**Comment by alexr00** [comment]
@Tyriar, what are your thoughts on this?

I think that `terminal.integrated.splitCwd` is as clear as `terminal.integrated.splitWorkingDirectory` since cwd is a common initialism. 

For `inherit`, `initial`, and `workspaceRoot`, I think that `inherit` is confusing since it is a verb and the others are nouns/adjective. All the options seem like they should be able to take the same place in a sentence:
"Use the ____ as the starting cwd for split terminals" or "Use the ____ cwd as the starting cwd for split terminals" (or similar)

**Comment by octref** [comment]
`inherited` looks good to me too.
