### ISSUE TITLE
Very large editor wrapping column incorrectly wraps

### ISSUE THREAD

**Issue by MrVallentin** [Microsoft/vscode#6219]
- VSCode Version: 1.1.0
- OS Version: Windows 10

I just updated to 1.1.0, and as soon as VSCode reopened the folder I was using prior to prompting the update the editor was broken. Broken in the way that each line only shows a single character.

![](http://i.imgur.com/6l8V3FB.png)

*I was looking at some code from an old University exam.*

Pressing <kbd>Alt</kbd> + <kbd>Z</kbd> (View -> Toggle Word Wrap) fixed the problem. But when I close VSCode and/or open another file or folder, the problem is right back where we started.

**Comment by jackvial** [comment]
Check your editor.wrappingColumn setting in user settings. Looks like it's set to 1 character. 300 is the default.

**Comment by MrVallentin** [comment]
@jackvial wait so this update deleted my settings as well? Now when I go to File -> Preferences -> User Settings, it shows the "Default Settings" and not the one's I've set.

But even so it still says `"editor.wrappingColumn": 300` (obviously since it's the default settings). So something else must be wrong!

**Comment by MrVallentin** [comment]
By looking in the "Default Settings", I see that now you're supposed to do `"editor.wrappingColumn": -1` do disable wrapping.

**Comment by alexandrudima** [comment]
I've added optimization code that makes sure in certain places we use integers. I use a JS trick for that where `x | 0` is truncated to a int32. The problem is that `10000000000000000000 | 0 = -1981284352` and then it gets clamped to the minimum of `1`. One billion (`1000000000`) should be more than sufficient for your use-case, as that means if you have a 1GB line in a file it will be rendered on one line.

**Comment by MrVallentin** [comment]
> then it gets clamped to the minimum of 1

Why not clamp `-1` and thereby fully disabling wrap? If the user already specified such a huge number, then it would probably equally be as good (but obviously in this case better) just disabling it no matter what, instead of having a single character per line.

**Comment by alexandrudima** [comment]
Agreed, this is a bug, I was just explaining where the code goes wrong.

**Comment by ChazyTheBest** [comment]
This has nothing to do with the issue but I read you talking about numbers and just want to ask:

The maximun number of characters per line (internally) is 10k, right? I mean no matter if I set my settings to:

    "editor.wrappingColumn": -1,

It won't display more than 10k characters, instead I see three dots after the last character.

I think it would be a good idea to remove this internal limitation or at least notify it in the description. Unless it causes some kind of disaster :P

**Comment by alexandrudima** [comment]
@ChazyTheBest It's complicated :). Over the years, I've added a lot of guards in the editor to protect against freezes (things taking too long). We have virtual vertical rendering (meaning if a line is outside the viewport, it incurs 0 cost on "painting"), but we don't have virtual horizontal rendering (meaning if a line is in the viewport, it gets fully "painted"). The reason is that we don't want to re-implement text layouting (with all the corner cases of bi-di, ligatures, etc.) in JavaScript, since the browsers do already such a good job.

So, if a line is really really long, we end up rendering the whole thing (creating thousands of dom nodes and giving these to the browser). At one point, things get very very slow. That's why we ship with a default `wrappingColumn: 300` (to avoid "painting" using thousands of dom nodes).

There is an internal option `editor.stopRenderingLineAfter` that kicks in. (https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/editorCommon.ts#L325).

```
/**
 * Performance guard: Stop rendering a line after x characters.
 * Defaults to 10000 if wrappingColumn is -1. Defaults to -1 if wrappingColumn is >= 0.
 * Use -1 to never stop rendering
 */
stopRenderingLineAfter?:number;
```

Maybe I should remove all these guards, but my concern is then I'd see a plethora of VS Code freezes issues. I will think about it some more.

**Comment by ChazyTheBest** [comment]
To implement virtual horizontal rendering is it needed to rewrite the whole layout system?

There has to be easier ways, I mean, lots of basic text editors have full horizontal text rendering (like gedit) but they also freeze like hell and even more I'd say (I've tested some of them). VS Code Is more likely to just get laggy but it freezes for 2-3 secs in some cases, for example when you try to select text/line (from left to right or from top to bottom).

The thing is I really hate line wrapping, I'm looking for a way to disable wrapping but also to not lag/freeze the editor when I'm adding minified code or changing something inside the minified file.

Is there any way to access that internal option? I wouldn't mind setting it to 300, I just don't want to have wrapping :P
