### ISSUE TITLE
workspaceIdentifier not persisted in SQLite?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#62217]
#61928

macOS

Repro:

1. `code --user-data-dir ./test1`
2. Open multiple folders
3. Close stable
4. `code-insiders --user-data-dir ./test1 --logStorage`
5. Check application storage
6. Close insiders
7. Open the SQLite storage.db for the workspace, the workspaceIdentifier key is not present

<img width="1183" alt="screen shot 2018-10-30 at 3 50 08 pm" src="https://user-images.githubusercontent.com/2193314/47755462-93867f80-dc5b-11e8-9e01-0c5d5f04a10b.png">

**Comment by bpasero** [comment]
@Tyriar yeah I think the `workspaceIdentifier` was something I only needed for `window.localStorage` because of the way how data is partitioned there (everything in one big table). With the new backend, the workspace is identified by the location of where the DB is stored. In that folder you see a `workspace.json` that contains the necessary information to find out the origins (e.g. the full path of the folder or workspace file). As such I currently see no need to store this information.
