### ISSUE TITLE
Disabling vscode-icons extension does not reset icons to default

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#62298]
Not sure if this is a bug for us or a bug for vscode-icons, but it seems like disabled extensions should not permanently modify VS Code state.
Default explorer view:
![image](https://user-images.githubusercontent.com/38270282/47803940-e3387a00-dd33-11e8-86ca-6796a3d1ac27.png)

Explorer view after enabling vscode-icons then disabling it:
![image](https://user-images.githubusercontent.com/38270282/47803976-fa776780-dd33-11e8-87a9-6a5edfed73bc.png)

**Comment by isidorn** [comment]
This is an issue that once the file icon theme is disabled we should go back to the previously used file icon theme, not none.
This could be looked into by Martin, however since he is on vacation forwarding to @alexr00 and @sandy081 

The issue is probably somewhere around here https://github.com/Microsoft/vscode/blob/f748c0b1636348ca8055d9dcadc4835a92cd0b1a/src/vs/workbench/services/themes/electron-browser/fileIconThemeData.ts#L15

**Comment by sandy081** [comment]
@alexr00 Feel free to take it up or let me know if we can look into it together.

**Comment by aeschli** [comment]
The bug is that we don't change back to Seti which is the default icon theme.

We don't have a history of the themes installed, so it's not the previous, but just the default.

**Comment by alexr00** [comment]
I installed the material icon theme, set the icon theme, then uninstalled that icon theme. After the reload, I had no icons.
