### ISSUE TITLE
Toggle word wrap Checkmark does not appear in Menubar

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#62307]
Issue Type: <b>Bug</b>

Even when I have my settings json file open I'm not seeing the change happen. If manually add the setting I can see the toggle working but the menu does not apply the checkmark.

![image](https://user-images.githubusercontent.com/35271042/47807964-94222300-dcfa-11e8-8467-63bf6aaf1fba.png)

VS Code version: Code - Insiders 1.29.0-insider (97ad72a02c351d6cde0fd32b41d9700a43e5964a, 2018-10-31T06:19:46.141Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (4 x 3096)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.98GB (1.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.2.2
vscode-typescript-tslint-plugin|ms-|0.0.2
ayu|tea|0.16.0

(2 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
Word wrap is more complex than just the setting. The menubar action affects the transient state of word wrap, not the setting itself.

**Comment by jamesderlin** [comment]
This is incredibly confusing because the "Toggle Word Wrap" menu item is adjacent with "Toggle Minimap", "Toggle Render Whitespace", etc., all of which *do* use checkmarks.

I recommend either:
A. Rename "Toggle Word Wrap" to something else so that it's differentiated.
B. Make "Toggle Word Wrap" an actual toggle.

(I'd prefer B.  Personally I find the word-wrap settings to be really confusing.  My mental model is that 
I expect two independent options: whether word wrap is enabled, and how word wrap should behave when enabled.  VS Code merges both into a single setting, which means I can't do what I want, which is to leave word-wrap off by default but to wrap at my word wrap column when I explicitly toggle it.)

**Comment by david-waterworth** [comment]
Any plans to progress this? It's immensely frustrating to have to manually toggle word wrap on every time I open a file. I can see it not being a priority when working with source files as the general convention is to explicitly break long lines at say character 80. But I do a lot of documentation in latex where typically the convention is to let the editor wrap the text. So every time I open a file I have to toggle word wrap. The UI doesn't make sense since there's no way of visually telling the state, and there's no way of setting it on/off in the setting file (ideally it would also be able to be set by file type i.e. on for .tex and off for .py files)

**Comment by milesbuckton** [comment]
I'm looking forward to the release notes that reflect this as being fixed. 😄

**Comment by rebornix** [comment]
As discussed with @sbatten offline, one potential solution is adding a workbench contrib which can detects what's the word wrap state in the active editor and then set it to a global context key, and then the menu can read the state from the key. I'm assigning this back to @alexdima since I'm a bit lost with word wrap's transient state ;)

**Comment by misolori** [comment]
🥳 Verified this now works

![celebrate](https://media.giphy.com/media/qnOBmH70CGSVa/source.gif)
