### ISSUE TITLE
Multi debug console not synced

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#62311]
Re #60034 

* Open https://github.com/Microsoft/vscode-pull-request-github/ or probably any vscode extension
* Duplicate the launch extension config
* Run the first one, a vscode extension dev host instance is created
* Run the second one, the previous dev host instance is closed and a new one is created.
* The debugging toolbar only shows one debugging instance while the debug console still has two.

**Comment by isidorn** [comment]
This is perfectly fine, the debug console also shows the sessions which finished - since users might want to inspect the debug console output after debugging.

As for to why we do not support 2 extension host debugging at the same time - there are techincal limitations and this scenario is simply not supported, thus the second instance is closed.
