### ISSUE TITLE
Can't cancel a debug session while it's initializing

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#62346]
This seems broken again, maybe since the change to show the debug widget while initializing. Plus, sometimes it doesn't time out after failing to attach, so I'm stuck forever.

Launch this config with nothing running on that port, so it doesn't have anything to attach to:

```
{
    "type": "node",
    "request": "attach",
    "name": "Attach",
    "port": 9229
},
```

- Press F5, debug widget appears
- Clicking the red stop button or pressing shift+f5 has no effect
- I can't start another debug config while in this state
- Sometimes, it times out after 10s. But sometimes while trying this, it never timed out and I had to reload the window in order to debug

**Comment by isidorn** [comment]
I still can not reproduce this
@eamodio @roblourens can you please do some debugging on your end: put a breakpoint [here](https://github.com/Microsoft/vscode/blob/f1736d3c892a6b035f741a737ffac4bac8fb2740/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L621) and figure out if it is nicely being called once you click on stop. If yes check if the sessions array contains the session and if the terminate is nicely being sent out. What node version are you using?

@weinand can you please try to repro this?

**Comment by weinand** [comment]
@isidorn I can reproduce the problem reliably.
Starting to debug issue...

**Comment by weinand** [comment]
The issue is (again) a missing call to `this.endInitializingState();`
I've debugged the whole flow after clicking the red stop button and everything looks correct.
At the end an `didEndAdapter` event is fired and we end up in https://github.com/Microsoft/vscode/blob/b31b07741b0947d03c5333c136402253d2ba1e6f/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L510

But at the end of the handler a `this.endInitializingState();` is missing.

@isidorn please verify that calling `this.endInitializingState();` at the end of the hanlder is the correct thing. It fixed the problem for me.

**Comment by isidorn** [comment]
@weinand yeah calling this.endInitializingState() at the end of that handler makes sense. I will push a fix like that later today.

For debt week I have created this item
https://github.com/Microsoft/vscode/issues/62390

**Comment by isidorn** [comment]
Pushed a workaround that I end the initialising state on adapter exit. This should fix it and can not have any side effects (since if we are not initialising it is a no-op).
The actual fix is assigned for debt week as mentioned in my previous comment.

**Comment by isidorn** [comment]
@eamodio I plan to do some refactoring in this week which might improve this. If you still see those issues in a week it would be great to open a new issue so we can work on fixing those. Thanks a lot

**Comment by isidorn** [comment]
@eamodio yes please open a new issue, thanks a lot!
