### ISSUE TITLE
Remote debugging issues after Node 10.12

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#62354]
Repro steps: https://github.com/Microsoft/vscode/issues/61711#issuecomment-434877037

Or steps w/o docker:

- Set up remote debugging, must be on a different actual disk, using node 10.12+
- Set a BP, hit the BP
- File opens again in a "read-only core module" file 🐛

**Comment by jeremychone** [comment]
@roblourens Yes, I just tested the insiders build and it was fixed on my simplified repo I made in the comment referenced. In the next couple of days I will test it on our full (with .map / .ts files) and report if I see any issue. 

Thank you so much for your responsiveness. It might seem to be a corner case which is why people did not notice that much, but we have a Kubernetes centric development process, meaning all our dev process run on local Kubernetes managed containers during dev, and without this fix debugging would have become very cumbersome.

**Comment by weinand** [comment]
works fine for me now.
