### ISSUE TITLE
Remove error codes from message, source or from other properties

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#62373]
@Microsoft/vscode: Those who are owning built-in extensions and are contributing diagnostics, please remove the error codes from the message or source or other properties, since we now also render error codes.

https://github.com/Microsoft/vscode/issues/49215, https://github.com/Microsoft/vscode/issues/60749

**Comment by octref** [comment]
This came in CSS because of https://github.com/Microsoft/vscode/issues/56925.

`css.lint.someRule` in the beginning does make more sense to me than in the end.

![](https://user-images.githubusercontent.com/4033249/47863321-410ca680-ddb4-11e8-8b5f-ef2b3d53646b.png)

With this I can easily see which linting rule is triggering the error.

**Comment by sandy081** [comment]
@octref `source` property should only mention the source of the diagnostics like `ts`, `tslint`, `css`. And it should not embed code/rule information. There is `code` property for that.

About where to show the `code`, please provide your opinion here -https://github.com/Microsoft/vscode/issues/62370

**Comment by octref** [comment]
The only one in CSS which I changed back in https://github.com/Microsoft/vscode-css-languageservice/commit/4f23ae8bcf629565484bd4153d5b899b940f7ef2. Let's move discussion to #62370.
