### ISSUE TITLE
Command Palette should steal focus from active webview...

### ISSUE THREAD

**Issue by busticated** [microsoft/vscode#62403]
hey there :wave:

i ran into a weird one. i have an extension which presents a webview with a number of html button elements. when these buttons are clicked, they often run a command via `executeCommand` which in turn prompts the user via `showInputBox`.

when a user clicks, the button is focused, command is run, and the input box is shown prompting the user to enter some info. they enter text and press the `<enter>` key to submit.

since the button on the webview is _still focused_, it receives the `<enter>` key press and re-triggers the command. iow, `<enter>` in the input box is re-routed to the focused html button element.

ideally, focus should be removed from a webview (or any of it's children elements) once the user opens the command palette.

for now, i just call `el.blur()` in my webview's event handler which fixes the issue.

- VSCode Version: v1.28.2
- OS Version: macOS v10.13.6 (high sierra)

**Comment by kieferrm** [comment]
The QuickPick should be able to request focus when being opened via command execution.

**Comment by chrmarti** [comment]
But you can type in the input box? So it must have focus. Is there anything special in that regard about webviews?

**Comment by IanMatthewHuff** [comment]
I'm hitting the same issue with this. We have a webview that hosts react components, two of which trigger export and import commands (which then use the open file and save file dialogs). These commands can be triggered from the react webview buttons or the command palette. The following steps trigger this pretty easily.

1. Click the export command webview button.
2. Hit esc to close the export dialog (focus is still on the export webview button)
3. Hit Ctrl-Shift-P and select the import command in the command palette and press enter
4. First the export dialog pops up again (due to the enter key on the focused web element)
5. Next the import dialog pops up (due to the enter key in the command palette)

From an accessibility standpoint I think that we would probably want the command palette to override current focus when popped up and then restore focus when closed but even stealing the focus and not giving it back after would be better than keyboard key going to both the webview and the command palette.
