### ISSUE TITLE
Moved workspace not removed from "recently opened"

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#62411]
- Open some `foo.code-workspace`
- See that it's in the "Open Recent..." list
- Close vscode
- Delete that code-workspace
- Open vscode
- Use Open Recent to select that deleted workspace
- Get a message that `foo.code-workspace` doesn't exist anymore
- See Open Recent again - the workspace is still in that list

If I follow the same steps with a folder instead of a workspace, then the folder is removed from the list as I'd expect.

**Comment by bpasero** [comment]
@roblourens I cannot reproduce, tried with insiders on macOS. Here is what I did:
* open a workspace
* saved it as another workspace on my desktop
* closed vscode
* deleted that workspace
* opened vscode (opens empty)
* try to open that deleted workspace via file > open recent
* dismiss the dialog
* try to find the entry again

=> it is gone

Since this involves a menu update, could it be that you opened the menu too fast for the menu to update? I think the current delay is like 800ms?

**Comment by roblourens** [comment]
Interesting, I am using the "File: Open Recent..." command. When I use that, it isn't removed from the list, but when I use the File > Open Recent menu, it is removed.

**Comment by bpasero** [comment]
I can reproduce and it seems to be a regression from the work to support URIs on the main side. The flow is:
* opening the workspace fails and we call remove from recently opened ([here](https://github.com/Microsoft/vscode/blob/66f717c/src/vs/code/electron-main/windows.ts#L1097))
* since we pass over a URI we think this is a single folder workspace (which it is not) and fail to remove it

moving to @sandy081 (cc @aeschli)

**Comment by sandy081** [comment]
This was the change from @aeschli adopting URIs for files.
