### ISSUE TITLE
Add support for Goto Declaration

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#62483]
VS Code currently only supports `Goto Defintition` inside the editor. However there are languages like C++ that distinguish between declarations and definitions. We should add official support to have `Goto Declaration` in the UI and a corresponding provider in the API.

This should also include a corresponding complex command to invoke the request.

**Comment by jrieken** [comment]
All pretty straight forward: https://github.com/Microsoft/vscode/blob/f6bf792deab85e59e971096dc58a502d24cedaf9/src/vs/vscode.proposed.d.ts#L25-L50


The only weird thing is that the return type is `Definition | DefinitionLink[]`... We could alias the type, esp `DefinitionLink` as `SymbolLink` or leave it as it. @mjbvz @dbaeumer ideas?

**Comment by dbaeumer** [comment]
What about aliasing it to `Declaration` and `DeclarationLink`. From all the discussions I had in LSP so far I try to avoid talking about a Symbol since users tend to associate it with symbols in compilers / type checkers. And for us it is simply a range(s) in a document.

**Comment by jrieken** [comment]
Yeah, `DefinitionLink` wasn't a good choice maybe. I have the following ideas, feedback welcome

* We rename `DefinitionLink` to `LocationLink`
* Since step 1 was breaking, we create an alias type `DefinitionLink` for `LocationLink`
* We declare yet another alias `Declaration` as `type Declaration = Location | Location[] | LocationLink[]`

**Comment by jrieken** [comment]
This is now in latest insiders

**Comment by joaomoreno** [comment]
@jrieken Fixed the smoketest.
