### ISSUE TITLE
Support negative filters on text

### ISSUE THREAD

**Issue by braunsonm** [microsoft/vscode#62531]
It seems like attempting to filter out certain text from errors or warnings does not work. Take the following for example:

Filtering to include a warning:
![](https://i.imgur.com/swIdNNl.png)

Filtering to exclude the warning:
![](https://i.imgur.com/ZKFful8.png)

I have also tried using quotes. It seems like the exclude `!` flag does not apply to text.

**Comment by kieferrm** [comment]
There are a couple of issues here:
1) '!' only works with glob patters
2) 1) is currently broken

**Comment by 4avka** [comment]
Is this going to be addressed ever? Look at this:
![image](https://user-images.githubusercontent.com/20619963/58779597-bb193e00-85d6-11e9-88be-842d2f423a62.png)
Can't filter these faulty linter false idkwtf's they are, they look like it's being fed some garbage text from the linter (golangci-lint) and it contains no information, and it only shows up when I have a main package open, and I can't hide them using the filter.

**Comment by sandy081** [comment]
@4avka Not sure how your issue is related to this. I think you should file an issue against golangci linter extension if the problems they generate do not makes sense.

**Comment by StewartRyanSony** [comment]
Where is this issue in the backlog? 

It would be really helpful to clear out types of errors and warnings I don't care about with the filter so I can concentrate on ones I do care about.

Thanks,
Ryan

**Comment by sandy081** [comment]
@StewartRyanSony  https://github.com/microsoft/vscode/issues/47354

**Comment by TonyGravagno** [comment]
@sandy081, the referenced issue has nothing to do with this one (still an issue as of this date). This ticket correctly reports that the Filter's ! not operator does not work with text. Examples have been provided. This is not related to specific linters, extensions or languages. It is not dependent on whether the list is filtered by category via a dropdown or by buttons. Negative filtering Does work with filenames and paths, not with text.

Examples where error is "bad statement, code BADSTMT"

Filtering to see any of that text works correctly: 'state', 'BADST', ' "state" ', etc

That only works when file filtering is not also applied. Example: "state" , **foo**. You can only have text inclusion, or file inclusion/exclusion, you cannot have both.

Filtering to NOT see any of that text always fails: '!state', !BADST', !"state"
It's not globbing, these do not work either: '!*bad*' , '(!bad)' , '!(bad)', !"*state*", etc
If it were globbing, there's no documented syntax to clarify whether we're filtering on text or filtering on files/folders.

**Comment by sandy081** [comment]
@TonyGravagno #47354 is not releated to this. This is related to the comment [here](https://github.com/microsoft/vscode/issues/62531#issuecomment-498125242) by @StewartRyanSony

**Comment by StewartRyanSony** [comment]
@sandy081 
@TonyGravagno is right. The referenced issue has nothing to do with this or the situation I was talking about. Perhaps I could have been more clear in my statement, but I would like the ability to filter out types of errors or warnings, not all errors or all warnings. 

for example I might want to filter out all warnings about using a cmdlet Alias. It might not be best practice to use an alias, but my script will still run just fine. While testing and debugging I'm going to want to concentrate on warnings that are more likely to cause the script to fail. Maybe later once the script is working I'll want to clean up the code and use proper cmdlet names so at that time, once they are helpful, I'll unfilter those warnings.

**Comment by TonyGravagno** [comment]
We need to be clear and careful about exactly what we're requesting. These should probably be separate tickets:

1. ! NOT operator on text is not working. << singular focus of this ticket
1. Comma-separated text and path expressions ignores the text component.
1. Cannot refine a filter with multiple text specs.
1. No definition for And/Or logic. Syntax in this contrived example is only a suggestion:
     !\*\*foo\*\* AND ( "unknown" OR "missing" )
    The AND and OR operators are explicit, where right now it seems the comma delimiter is ambiguous about whether it means AND or OR.
1. Not sure how to filter multi-word text. Examples : `"public class"`, `!"private func"`.

I separate those, because while I agree with @StewartRyanSony about the request, I believe he is looking for multi-condition filtering, in addition to getting the NOT operator working. If that's a concept for separate ticket, we should create it.

BTW, this is not a complaint fest about filtering. The filters are greatly appreciated and this is intended as a contribution. Again, I'll look at the code to see if I can help there, but at this time I haven't looked to even see where filtering is happening.

**Comment by StewartRyanSony** [comment]
I don't mean to confuse the issue, so I'll try to be clear as well. My request is basically a use-case example of why the ability to use a Not operator in the filters is necessary. 

Filtering for specific conditions or types or errors and warnings is working great and is very useful. It's just the opposite case where trying to filter out specific issues is a problem.

**Comment by Dfinity-Alin** [comment]
One very good use case is Rust (and the Rust Language Server). I am regularly getting 30-50 "found possibly newer version of crate `x` which `y` depends on" every time I make a typo anywhere. See https://github.com/rust-lang/rls/issues/1520 for context.

What's worse, Rust/RLS tries to be as specific as it can with errors, so each one of these errors is 6-10 lines long. I.e. I have to find the one actual error among 300+ lines of output every single time I make a typo. To make matters worse, RLS takes at least 30 seconds to produce this dump. That's 30 seconds waiting for RLS and 30 seconds folding errors one by one. For every typo.

If I were able to filter out all the useless "found possibly newer version" errors, it would save me 30 seconds per typo.

Below is an example of an actual error in a sea of noise. Notice the scrollbar on the right.

![Screenshot from 2020-02-16 10-29-54](https://user-images.githubusercontent.com/58422065/74602277-512ebf00-50a7-11ea-8c3f-a41056d22a24.png)

**Comment by sandy081** [comment]
@Dfinity-Alin not sure how the problems view can be helpful here. Please contact the rust extension to avoid such noise.

**Comment by Dfinity-Alin** [comment]
I did contact them. There are a handful of related bugs filed against RLS (the link in my previous post is one). And there are currently [273 Google search exact matches](https://www.google.com/search?q=%22found+possibly+newer+version+of+crate%22) for "found possibly newer version of crate", with 7 of the first 10 being GitHub issues raised against various `rust-lang` projects, going all the way back to 2014. So this does not look like something that will be fixed any time soon.

All I'm saying is that a (comparatively) simple negative filter in VSCode would "solve" this issue and (I assume) many others like it.

Also, I find the verbosity of Rust error message actually nice to have, when it's an actual error. So I wouldn't want the errors to be single line errors, just so I can more easily eyeball the one error out of a sea of copycats. Although it wouldn't be all that bad if VSCode allowed collapsing errors into a single line.

**Comment by sandy081** [comment]
@Dfinity-Alin This is not an umbrella item for problems filter features. I would suggest to open a new issue for your requirements so that this item will not get side tracked.

**Comment by Dfinity-Alin** [comment]
@sandy081 All I was asking for was a negative filter for the Problems panel (e.g. filter out all problems containing some arbitrary substring). And providing a solid use case, [as requested](https://github.com/microsoft/vscode/issues/62531#issuecomment-576795640) by @StewartRyanSony.

And I thought this is exactly what this issue was about. Am I missing something?

**Comment by sandy081** [comment]
@Dfinity-Alin You are completely right. I am really sorry, I got carried away with the title. Updated the title to reflect the request correctly.

**Comment by Dfinity-Alin** [comment]
@sandy081 No worries, thanks for taking the time.

**Comment by Xunnamius** [comment]
Any updates on this?

**Comment by changeling** [comment]
How about now? Still !working.

**Comment by GitMensch** [comment]
Back-Link for the [SO question leading here since Dec 2019](https://stackoverflow.com/questions/59326920/how-to-filter-out-problems-in-vscode-based-on-text), just because.

Note: I did not found the issue here with some minutes searching, it seems reasonable to add "problem pane" to the question's title, at least that would have shown this issue in my (and possible others') search.

**Comment by changeling** [comment]
Just kinda bumping this issue. It would be nice.

**Comment by Nagyhal** [comment]
I need this feature. I can't use VSCode because of this.

My screen is constantly littered with a million irrelevant error messages. They are distracting, unnecessary, and ugly. I cannot work with them.

For the most part, VSCode with its Intellisense, code actions, problem highlighting, and its integration with language extensions is incredible. I need these features to help me code—it's why I want to use this platform. So simply switching off all error highlighting for me is not a solution.

I need filtering. Extension designers add new warnings, corrections and code actions on a whim, and why wouldn't they? They want to add features and create tools that have as much functionality as possible. But because of the lack of customization on the client end, it can be incredibly annoying when this happens. You see, we as coders and (in my case, former) VSCode users also need simplicity. We want to have control over our tools. We want to code with peace of mind.

I have spent a day trying to fix this just for myself and it felt like banging my head against a wall again and again. I am done. This is the first, and last time I attempt to use VSCode for quite a while. But please listen to us—this request had been made time and time again and been ignored or shut down time and time again. It shouldn't even be hard. You have a great tool—please make it usable.

**Comment by emaddoma** [comment]
Would love to be able to exclude my TODO comments or move these to a new tab

**Comment by comaniac** [comment]
Up vote this feature. It is required for the Python projects using Cython and ctypes to filter out the false no-member errors.
