### ISSUE TITLE
[Feature} Add a command to createCursor

### ISSUE THREAD

**Issue by metasong** [microsoft/vscode#62567]
currently we have command `editor.action.insertCursorBelow` and `editor.action.insertCursorAbove`, these command cound be binded to shortcuts, but the `insertCursor` could only be triggered with mouse `Alt+click`.

with a command and bind a shortcut to it, we could totally using keyboard to add another cusor.

i.e.
move cursor and add a cursor, move the cursor to another position and triger this command to add another muticursor...

**Comment by slaterbbx** [comment]
Does everyone at Microsoft use a mouse to navigate? In Linux Distro ( Solus MATE ) the CTRL + Click does not work anyway ( Without messing with the systems shortcuts first ) Honestly I cannot believe that you cannot work this by default. Why is there even an option available in the keybinding search for "createCursor" if it is non functional? 

Does anyone know how to get this to work?

I get the error that it does not know the position to place the cursor, which makes no sense, Why cant I just drop cursors all over the page? There is a plugin out there that allows for this but literally annoying to have to deal with being slowed down by the default editor. ( Cannot read line number of "undefined" ) 

"Current cursor position / location" should be the default value for this option out of the box.

There is are plugins that allows for this functionality and probably why there is not a list of complainers about this missing functionality, the plugin that I used before for this was called ( multi-cursor-emacs-mark ) and then you can add in the feature with the following. 

`{
    "key": "ctrl+m",
    "command": "extension.emacsLikeMarking.setMark",
    "when": "editorTextFocus"
}`

But you should be able to do the following by default in VsCode ( unfortunately cannot )

`{
    "key": "ctrl+shift+space",
    "command": "createCursor",
    "when": "editorTextFocus"
}`

Anyway, I UpVote this for a default feature, especially since it should be set to default to simply use "currentCursorPosition" or whatever the value is in VsCode ( just using that as example ), Personally I would copy the emacs style exactly, simply drop cursor, move cursor, drop another etc... It just seems standard to me personally and every "non mouse user" out there probably has some solution for this of their own.

It doesnt have to be so complex, even if you want to put a cursor at next position, force user to "mark" first location first, then move, then mark. Simple solution to end the debate about how this should work with keyboard, emacs movement already solved this, in my opinion. ( no need to add additional features ) and can be set to not override the ctrl+click default that every mouse user likes.

Thanks for reading, hopefully this gets considered so that I can remove another plugin.

Regards,
Kyle

**Comment by Malix-off** [comment]
- [Comment Reply](https://github.com/microsoft/vscode/issues/62567#issuecomment-857915533) from @slaterbbx:
  > [⋯](https://github.com/microsoft/vscode/issues/62567#issuecomment-857915533) `createCursor` [⋯](https://github.com/microsoft/vscode/issues/62567#issuecomment-857915533) is non functional [⋯](https://github.com/microsoft/vscode/issues/62567#issuecomment-857915533)

  Yep, created #201466 about it
