### ISSUE TITLE
file links in terminal are not always working

### ISSUE THREAD

**Issue by llegolas** [Microsoft/vscode#62586]
- VSCode Version: 1.28.2
- OS Version: fedora 28

Steps to Reproduce:

1.
![1](https://user-images.githubusercontent.com/37660621/47997601-0f257800-e105-11e8-916c-38466c5c2ea3.png)

No linkify

2.
![2](https://user-images.githubusercontent.com/37660621/47997612-19477680-e105-11e8-9ef3-4f5171c98b6b.png)

Works as expected

Trying the same but from different directory:
1. 
![3](https://user-images.githubusercontent.com/37660621/47997619-21071b00-e105-11e8-917b-a1c00cca826e.png)

works as expected

2.
![4](https://user-images.githubusercontent.com/37660621/47997627-29f7ec80-e105-11e8-867c-5da1bb32c419.png)

works as expected

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by llegolas** [comment]
Sorry but couldn't capture the pointer and the hover. Will try to take new screens

**Comment by jchang10** [comment]
I am noticing this same issue completely stopped working in the latest insiders a few days ago. I am surprised nobody else has mentioned it yet. Been a few days now. It still works in the official February 2019 release v1.32.3. I just do not want this lost feature going out in March.

https://github.com/Microsoft/vscode-python/issues/450
Says this is an issue in VSCode, and not specific Python.

Version: 1.33.0-insider

Open a terminal. just type http://www.google.com and you can hover over the link and ctrl/cmd click if you wish. URL's still work.

Files used to work. If you had "C:\users\me\to\file.py", line 142. You could hover over the file name, ctrl+click and you are there. That ability is completely lost now. It was handy when the Python interpreter crashes and displays a stack track with all the files and line numbers.

**Comment by Tyriar** [comment]
This seems to be fixed, I can't repro.

**Comment by jchang10** [comment]
The specific part not working for me is the backslack '\\' for windows file paths. It's really easy to test in the terminal window on windows.

C:> ./manage.py # => Linkified and allowed to ctrl+click the file name.
C:> .\manage.py # => Not linkified. Not recognized as a file path and no ctrl+click option give.

In my specific case, it is because I like to use ipython as my REPL and for some reason, it uses backslashes. I have a feeling if it used forward slashes, then all would be fine. Why Windows is so brain-damaged, is another issue!!!

**Comment by Tyriar** [comment]
@jchang10 seems a little hard to repro but I think I found the cause 👍

**Comment by Tyriar** [comment]
Verifier: Please test that when typing/pasting `./<validfile> .\<validfile>` into a terminal that both links work, reload the window several times and verify it always works.

**Comment by jchang10** [comment]
@Tyriar Awesome! Confirmed, working on the latest developer's build!!! Oops, sorry for the duplicate report in the other issue!

**Comment by Tyriar** [comment]
@jchang10 thanks a bunch for checking! The reason i said it was hard to repro was because it seemed to happen 100% of the time in the official build (that you use), but 0% of the time when building VS Code out of sources (where we need to develop the fix). Glad it's fixed though, it ended up being a race condition caused by a recent refactor which I guess only showed itself when loading the unminified code or something 🤔

**Comment by jchang10** [comment]
Got it. Yeah, I can see why it would be hard to repro now! Wow. Thanks again for tracking it down! Hope there arent too many of these kinds of issues between source and minfied versions. Ouch.
