### ISSUE TITLE
DataTree not yet ready?

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#62606]
The `DataTree` type seems to be the candidate to replace the old tree. However, it doesn't implement anything apart from `refresh` and lacks things like `reveal`, `expand`, `layout` etc etc - basically the whole `AbstractTree` interface seems to be missing.

**Comment by joaomoreno** [comment]
Yeah we gotta expose stuff like that, they're just forwarding methods. Let me know what else you need. Expect bugs, but also expect fast fixes!

**Comment by jrieken** [comment]
> Let me know what else you need

So, when you are asking: I would like to have a compat-layer because I am not a big fan of having rewrite all my tree consumers...

**Comment by joaomoreno** [comment]
@jrieken There shouldn't be much work coming from the old tree. Unfortunately, it also doesn't come for free. But that brings me to highly discouraging the use of the DataTree in Outline, since it is overkill. I suggest to look into the ObjectTree, which has no use of Promises. This of course is extra work, but you'll get the perf you're looking for as well as the opportunity to remove lots of code related to filtering. I can help you with that, like I did for Problems.

**Comment by jrieken** [comment]
The thing is that the outline tree (logic) is only implemented once but used in both, outline and breadcrumbs. To make matters worse, breadcrumbs uses a tree that shows files and/or symbols by using the same tree (interface) with different providers, filters, sorters... That's my challenge.
