### ISSUE TITLE
Color preview/picker popup in CSS files shows black gradient for color #fe5e5f

### ISSUE THREAD

**Issue by yura-chaikovsky** [microsoft/vscode#62619]
Issue Type: <b>Bug</b>

Color popup shows black gradient for color #fe5e5f, while it is expected to be red.

![image](https://user-images.githubusercontent.com/2750439/48030054-90f2c100-e158-11e8-8744-79bfa99e22d1.png)

VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T16:17:45.060Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.91GB (1.15GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|yes|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vetur|oct|0.13.0
vscode-docker|Pet|0.3.1
shader|sle|1.1.4
pegs|the|0.0.5

</details>

**Comment by DominoPivot** [comment]
I can confirm this is still an issue in the latest version (1.32.2 e64cb27b1a0cbbc3f643c9fc6c7d93d6c6509951).

**Comment by ndngo** [comment]
There seems to be an issue with how saturatedColor is calculated where sometimes certain values turn black. 

For example, the colour #fd5e5f:

![fd5e5f-unsaturated](https://user-images.githubusercontent.com/16291290/56069818-c9737800-5d52-11e9-98de-0f81d70e8f08.png)
![image](https://user-images.githubusercontent.com/16291290/56069822-cbd5d200-5d52-11e9-8a17-65f016dc9e13.png)
This is what the colour looks like before saturation.


After saturation:
![fd5e5f-saturated](https://user-images.githubusercontent.com/16291290/56069353-ad6ed700-5d50-11e9-863e-6a3f025c0c46.png)
![image](https://user-images.githubusercontent.com/16291290/56069587-bc09be00-5d51-11e9-8805-349cf71bb057.png)

After the saturation the colour turns black, so it displays black in the colour picker.
![fd5e5f-colour-picker](https://user-images.githubusercontent.com/16291290/56069868-02135180-5d53-11e9-9b29-b9008de9cfeb.png)

This bug also exists even when the colour picker renders the colour properly.
For example, the colour #fe5e4f:
![fe5e4f-saturated](https://user-images.githubusercontent.com/16291290/56070022-ca58d980-5d53-11e9-8ca1-8f8353b50506.png)
![image](https://user-images.githubusercontent.com/16291290/56070331-46075600-5d55-11e9-861f-0e26672231ed.png)
In this case, the colour is rendered properly because the RGB values seem to be saturated correctly even though the HSV values are black. Rendering
![fe5e4f-colour-picker](https://user-images.githubusercontent.com/16291290/56070351-67684200-5d55-11e9-9c31-7e25ca13ab37.png)

**Comment by rebornix** [comment]
I think the deeper problem here is our color convert converts `hsv(360, 1, 1)` to `rgb(0, 0, 0)` instead of `rgb(255, 0, 0)`.
