### ISSUE TITLE
Drag-to-move not working with Custom titlebar when running VSCode via X forwarding

### ISSUE THREAD

**Issue by darkvertex** [Microsoft/vscode#62613]
Issue Type: <b>Bug</b>

Steps to Reproduce:

When using "window.titleBarStyle" of type "custom", if I open VSCode via ssh with X forwarding (ie I `ssh -X myhostname`), it's impossible to move the window around by dragging the titlebar. (On the same system, running it locally, the titlebar lets me move the window fine as expected.)

However, if I switch "window.titleBarStyle" to "native", it works fine via X forwarding as well as locally on the machine from a GUI session.

- VSCode Version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:20:56.183Z)
- OS Version: Linux x64 3.10.0-693.21.1.el7.x86_64 (CentOS Linux release 7.4.1708)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz (24 x 2668)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|2, 1, 1|
|Memory (System)|62.91GB (15.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by darkvertex** [comment]
vscodebot: I don't think this is an `integrated-terminal` bug.

**Comment by paulcorke** [comment]
I think I have the same problem with a slightly different setup so I'm adding this as another data point in case it helps.

I have VSCode 1.30.0 running under CentOS 7.5.1804 in a VirtualBox 5.2.16r123759 VM with a Windows 7 host which is running VcXsrv 1.18.3.0 X Server.

From the Linux console I set DISPLAY to refer to the VcXsrv on the host so there's no X forwarding over ssh but it is effectively a remote X server running over tcp (using the Bridged adapter).

With the "window.titleBarStyle" set to "custom" (the new default) I can't move or resize the VS Code window.  Putting the pointer over the edges of the window does change the cursor to indicate "resize" rather than the usual arrow, but clicking and dragging has no effect.  The cursor stays as an arrow over the titlebar (probably as expected) but clicking and dragging again has no effect.  Reverting to "native" allows moving and resizing.

Version: 1.30.0
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:21:33.585Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 3.10.0-862.14.4.el7.x86_64

**Comment by sbatten** [comment]
if you are using X forwarding we recommend the native titlebar https://code.visualstudio.com/docs/setup/linux#_cannot-move-or-resize-the-window-while-x-forwarding-a-remote-window

**Comment by darkvertex** [comment]
It's nice that someone updated the docs, but the issue is not resolved, so why close it?

Are you officially giving up on ever making it work? 😞 (Or is just it an Electron bug outside of the VSCode code? If so, has an issue been reported in the Electron GH repo?)

**Comment by sbatten** [comment]
@darkvertex issues related to window management is frameless are mostly owned by electron and this issue is out of scope as there is a simple workaround documented. the issue seems to occur primarily when the X server on the local machine does not support it, e.g. Windows. If I use an ubuntu machine to forward code from another ubuntu machine, I can manipulate the window without issue. Thanks for understanding.

**Comment by darkvertex** [comment]
Thank you for the explanation. I now understand better why this was closed.

Has someone in the VSCode dev team filed an [issue with Electron](https://github.com/electron/electron/issues) so we can follow along with its (hopefully!) eventual resolution? It would be really nice if someone had the time to report it properly, not just for the benefit of VSCode but for any other Electron app using frameless windows.

**Comment by alexeyr** [comment]
> If you are using X forwarding to use VS Code remotely, you will need to use the native title bar to ensure you can properly manipulate the window. The native title bar is no longer the default behavior on Linux, but you can switch to using it by setting window.titleBarStyle to native.

Can this be detected in some way and suggestion to switch given?

**Comment by darkvertex** [comment]
Or perhaps even default to the native titlebar when starting vscode via X forwarding is detected, even if the titlebar preference says otherwise.

Would that be hard to add?
