### ISSUE TITLE
search.exclude ignore when using a workspace

### ISSUE THREAD

**Issue by x3r10n** [Microsoft/vscode#62632]
search.exclude is ignore when using a workspace.
When I open a folder directly, the exclude is working.

- VSCode Version: 1.28.2
- OS Version: OSX

**Comment by x3r10n** [comment]
well the best way to show you will be these two screenshot :

Here, we have a prject open with a "workspace" configuration
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/4524121/48071130-86134d00-e1a7-11e8-9217-22a35f008b71.png">

Here, I opened the client folder directly

![image](https://user-images.githubusercontent.com/4524121/48071086-6845e800-e1a7-11e8-9b28-8193f5764cd5.png)

installed ext :
aaron-bond.better-comments
Angular.ng-template
AngularDoc.angulardoc-vscode
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
CoenraadS.bracket-pair-colorizer
cssho.vscode-svgviewer
eamodio.gitlens
ecmel.vscode-html-css
eg2.tslint
eg2.vscode-npm-script
esbenp.prettier-vscode
Kasik96.swift
kisstkondoros.vscode-gutter-preview
michelemelluso.code-beautifier
mrmlnc.vscode-scss
ms-vscode.csharp
ms-vscode.PowerShell
ms-vsliveshare.vsliveshare
ms-vsts.team
msjsdiag.debugger-for-chrome
PeterJausovec.vscode-docker
PKief.material-icon-theme
pranaygp.vscode-css-peek
quicktype.quicktype
rebornix.ruby
sandcastle.vscode-open
steoates.autoimport
tintoy.msbuild-project-tools

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it happens there? I fixed a similar issue recently.
https://code.visualstudio.com/insiders

**Comment by jakub-g** [comment]
I have the same issue in stable 1.31.0 (not present in insiders 1.32.0 though when I tried to put in place the same config by copying user config JSON). But I don't know how to make sure to have 100% the same config in both.

**This issue is very disturbing when encountered because the ignored folders typically contain huge, minified files and vscode chokes and freezes the machine when searching such files.**

When you click one of those massive minified matches, it completely freezes the editor after a while:

![image](https://user-images.githubusercontent.com/1437027/52646727-92642000-2ee3-11e9-8584-0dc756995015.png)

Note that I have `"search.useIgnoreFiles": true` at all levels (user / workspace / repo)

![image](https://user-images.githubusercontent.com/1437027/52646281-c5f27a80-2ee2-11e9-9ad9-1a78756dddb9.png)

but when searching, the _exclude settings and ignore files are disabled_ text shows up and it finds entries in the excluded folders.

![image](https://user-images.githubusercontent.com/1437027/52647404-f0453780-2ee4-11e9-8494-875d5271a494.png)

The exclude pattern is correctly taken from `.gitignore` at repo level:

![image](https://user-images.githubusercontent.com/1437027/52647105-5e3d2f00-2ee4-11e9-9b87-5a38c1aa6966.png)

I can specify the exclusion directly at search as a temp workaround though:

![image](https://user-images.githubusercontent.com/1437027/52647454-05ba6180-2ee5-11e9-9197-ac86ed9b80b9.png)

**Comment by roblourens** [comment]
For those settings to work, you need to toggle on that gear button in the "files to exclude" box.

**Comment by jakub-g** [comment]
> For those settings to work, you need to toggle on that gear button in the "files to exclude" bo

@roblourens hmm indeed you're right, thanks!

Now that I know about it, it kind of makes sense, but you can see it might be unintuitive. I probably accidentally clicked the button without realizing it and expecting anything to change.

Not sure though if/how this could be improved.
