### ISSUE TITLE
[Debug] Restart workflow is changed in vscode 1.28

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode#62701]
I am the author of [azds java debug extension](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debugger-azds), recently we have met an issue of restarting debug session doesn't work, after the comparison of older vscode and vscode 1.28, I found the resolveDebugConfiguration will never be called during restart, in [azds ](https://docs.microsoft.com/en-us/azure/dev-spaces/) debug the preLaunch task will shut down the remote debug server, and thus it is important to have the resolveDebugConfiguration to setup a new debug session on a new port(we have declared the supportsRestartRequest=false).
 I think it might be caused by the changes discussed in this issue:
https://github.com/Microsoft/vscode/issues/58817 
The issue is to ask a advice how to implement a debug server which takes restart as same as the sequential command stop and start?

**Comment by isidorn** [comment]
@andxu thanks for the nice investigation and yes this issue is caused by the changes there.
However we fixed this as part of https://github.com/Microsoft/vscode/pull/59819 and the fix is available in the latest vscode insiders  https://code.visualstudio.com/insiders/
Please try it there and if you still see the issue let me know and I can reopen this. Thanks!
