### ISSUE TITLE
DevTools close when opened while stuff is loading

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#62719]
* run `scripts/code.sh`
* reload the window
* while that happens press cmd+alt+i to open dev tools
* wait a little and see how dev tools are closed again

this happens because of https://github.com/Microsoft/vscode/blob/362e69ad832813977a97de2ebc89c301fe9f185d/src/vs/platform/menubar/electron-main/menubar.ts#L701-L709

**Comment by bpasero** [comment]
@jrieken does this still happen? I pushed a change to trigger actions earlier (e.g. not waiting for workbench to have opened all editors).

**Comment by jrieken** [comment]
Yes - still happens

**Comment by bpasero** [comment]
I see why I am not seeing it because I have F12 assigned as keybinding and that one is not taken by the bootstrap-window.js already. For me the devtools only open when the workbench has started and for you they open right from the beginning but also they close again due to the second delayed invocation...
