### ISSUE TITLE
Reveal GOROOT/GOPATH in side bar

### ISSUE THREAD

**Issue by QianChenglong** [Microsoft/vscode#62729]
Useful to read relative code!

![image](https://user-images.githubusercontent.com/1881126/48138419-42236380-e2df-11e8-9d06-793bf648faf1.png)

**Comment by chrmarti** [comment]
Have you tried adding them as workspace folders (File > Add Folder to Workspace...)?

**Comment by QianChenglong** [comment]
Add GOROOT/GOPATH in every project is a little bit tricky.

**Comment by QianChenglong** [comment]
> We try to keep VS Code lean and we think the functionality you're asking for is great for a VS Code extension. Maybe you can already find one that suits you in the [VS Code Marketplace](https://aka.ms/vscodemarketplace). Just in case, in a few simple steps you can get started [writing your own extension](https://aka.ms/vscodewritingextensions). See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.
> 
> Happy Coding!

But the click the `Reveal menu` has any effect, is it reasonable?

**Comment by ramya-rao-a** [comment]
@QianChenglong The `Reveal in Side Bar` option only applies to files belonging to the current workspace. This is because the Side Bar can only contain files belonging to the workspace.

If you are using the Go extension, then what you can do is
- Keep the cursor inside the import block on the package that you want to explore
- Run the command `Go: Add Package to Workspace`

This will add the package to the workspace allowing you to explore it directly in the side bar or to use the `Reveal in Side Bar` menu.

Another option is to use the command `Go: Browse Packages` which will let you browse the files belonging to the package you select from the drop down.

**Comment by ramya-rao-a** [comment]
@QianChenglong Have you tried the `Go: Browse Packages` command?

**Comment by QianChenglong** [comment]
@ramya-rao-a Yes! Which I need is easily to browse the package structure like other package in my project.`Go: Browse Packages` use to open file is nice,but in my suitation is not working.
