### ISSUE TITLE
command 'workbench.action.editorLayoutCentered' not found

### ISSUE THREAD

**Issue by davidpope** [Microsoft/vscode#62984]
- VSCode Version: 1.29.0
- OS Version: Linux - Xubuntu 18.10

Steps to Reproduce:

1. Click View -> Editor Layout -> Centered

Does this issue occur when all extensions are disabled?: Yes

Expected behavior: The view switches to centered layout.
Actual behavior: Error message displayed

![image](https://user-images.githubusercontent.com/1066706/48386697-7b314e80-e6b8-11e8-9819-a5b8372f4c79.png)

Supporting data: There's only one key-bindable command with 'centered' in its text, Toggle Centered Layout:

![image](https://user-images.githubusercontent.com/1066706/48386733-97cd8680-e6b8-11e8-9aec-e7d66267922e.png)

**Comment by dpope-atlassian** [comment]
I see an attempted fix in 1.29.1, but it still does not behave as expected.

1. Start from Single layout.
2. Choose View -> Editor Layout -> Centered
3. Choose View -> Editor Layout -> Single

Expected behavior: Single layout is selected.
Actual behavior: Nothing happens.

In order to get Single layout back, you have to choose View -> Editor Layout -> Centered again. It's as though the menu item invokes the Toggle Centered Layout command, which isn't expected.

It also breaks, but differently, when transitioning from other layouts:

1. Start from Single layout.
2. Choose View -> Editor Layout -> Two Columns
3. Choose View -> Editor Layout -> Centered

Expected behavior: Centered layout is selected
Actual behavior: Nothing happens.

You have to go back to Single layout first in order for Centered to work.

**Comment by Nemesis19** [comment]
Version 1.29.1 on macOS
View -> Editor Layout -> Centered it works well.
To disable it I need to do again View -> Editor Layout -> Centered instead of selecting View -> Editor Layout -> Single that in that case does nothing

**Comment by niedzielski** [comment]
Issue occurred in one workspace on v1.29.0 (Ubuntu). Issue fixed in v1.29.1.

**Comment by sbatten** [comment]
@isidorn This is actually a duplicated entry in the menu. It exists as `Toggle Centered Layout` in `Appearance` and `Centered` in `Editor Layout`. Our old menu bar never had this second entry so I believe it should be removed. The rest of the entries in the `Editor Layout` menu do not toggle but set the layout directly.
