### ISSUE TITLE
Consider using Carlo vs. Electron

### ISSUE THREAD

**Issue by dandv** [Microsoft/vscode#63163]
[Carlo](https://github.com/GoogleChromeLabs/carlo) is a project by Google offering a web rendering surface for Node applications by finding a locally installed instance of Chrome, establishing a connection over the process pipe, and exposing a high level API for rendering in Chrome with the Node environment.

This would keep the rendering engine always up to date (an [important](https://code.visualstudio.com/updates/v1_29#_continued-electron-30-exploration) feature), and reduce the distributable size significantly.

**Comment by seanbudd** [comment]
I don't see this happening considering microsoft own both electron and vscode but not carlo

**Comment by dandv** [comment]
> But what about users who don't have Google Chrome installed on their computers?

A larger redistributable, bundling the older Chromium. Microsoft has done [this](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) with installers vs. redistributables.

**Comment by vially** [comment]
Wayland support (#1739, #41345) is another feature that would benefit from using `carlo`.

Thanks to the work done by @Igalia, wayland support in chromium seems to be almost finished. However, wayland support in `electron` is still lacking ([electron#12543](https://github.com/electron/electron/issues/12543), [electron#9056](https://github.com/electron/electron/issues/9056)) mostly due to it's reliance on some X11 specific APIs.

I understand that adding support for `carlo` might require some work. But I think there's definitely some value in providing an option to the user (either at run time or at build time) for choosing one library or the other (`carlo` or `electron`).

**Comment by Tyriar** [comment]
We're aware of Carlo but even if we wanted to, it's not something we could just plug in and everything would work. Here are just some of the issues:

- It's very much an experiment
- No node in the render process means everything goes through IPC which is a performance bottleneck. Just compare the performance of the terminal example with VS Code's terminal for a real example of this.
- It's missing many electron APIs
- Carlo supports only evergreen Chrome, one of the reasons Electron updates are difficult are because updating Chromium can break VS Code as so many things are touched. It's a large and complex codebase that needs care when swapping out the platform.

We have worked closely with the Electron team for several years and will likely continue to do so for the foreseeable future.
