### ISSUE TITLE
Provide an easy way to debug a freezing window (The window is no longer responding)

### ISSUE THREAD

**Issue by dtinth** [microsoft/vscode#63195]
When **The window is no longer responding** dialog appears, it would be great if there is an option to debug the window (e.g. start the DevTools and enter a debugging session). This should up me and other developers to find out and understand the cause of a freezing window more easily.

![image](https://user-images.githubusercontent.com/193136/48535990-c37e8580-e8df-11e8-9017-d9643b3535ed.png)

**Comment by jrieken** [comment]
Not sure that's a feature we should polish. Ideally, the renderer isn't unresponsive.. Anyways, there is an event that's emitted on the main side (https://electronjs.org/docs/api/browser-window#event-unresponsive). I would then require to create a another renderer process that's configured to debug that other renderer (not yet sure how it would connect?)

I have been thinking about this as well, not in a debugging context but for profiling. Today, we listen on above event and show a modal dialog. Instead, we could attach the profile for a bit and send that profile to us so that we know what's going on.
