### ISSUE TITLE
"Recent" and "Recent Workspaces" not listed in the taskbar.

### ISSUE THREAD

**Issue by Delphinidae84** [Microsoft/vscode#63197]
- VSCode Version: latest
- OS Version: Windows 10

Steps to Reproduce:

1. Open a couple of workspaces.
2. Right-click pinned vscode icon in the (windows 10) taskbar.
3. I still can't see any of my recently used workspaces. The only options listed are:
* New Window
* Visual Studio Code
* Unpin from taskbar

**Comment by bpasero** [comment]
I cannot reproduce, looks like this for me:

![image](https://user-images.githubusercontent.com/900690/48697984-435d6600-ebe6-11e8-8f5f-bf29233d04a4.png)

Does it help if you "Clear Recently Opened" and try again:

![image](https://user-images.githubusercontent.com/900690/48698011-553f0900-ebe6-11e8-823a-fc20f099e7e8.png)

?

**Comment by Riari** [comment]
I have this problem as well. Started happening since I formatted and reinstalled Windows 10 Pro 1809. No "recent workspaces" from the start menu tile or taskbar, but they do show up in VSCode itself.

**VSCode info:**
Version: 1.30.0 (user setup)
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:29:11.253Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

![image](https://user-images.githubusercontent.com/3583774/50084383-bb6f7980-01ee-11e9-90fa-cc972aedfba2.png)

![image](https://user-images.githubusercontent.com/3583774/50084423-db9f3880-01ee-11e9-8fc2-b27287f32d74.png)

![image](https://user-images.githubusercontent.com/3583774/50084522-30db4a00-01ef-11e9-81e5-a2f30c19c01b.png)

**Comment by Kaesebrot84** [comment]
@Riari Thats exactly the behavior I experience.

**Comment by bpasero** [comment]
Steps to reproduce would be great, as you probably figured out not everyone sees this issue, e.g. for me:

![image](https://user-images.githubusercontent.com/900690/50148749-9267eb00-02b9-11e9-9575-9a379ab89923.png)

Best would be to run `code --user-data-dir <some new dir>` to run fresh sessions and then record the steps that lead to the task menu not showing any entries anymore.

**Comment by Riari** [comment]
That's the difficult part - it happens with a completely fresh install. I didn't do anything particular to make it happen. It was working for me a few weeks ago until I wiped my drive, installed a fresh copy of Windows 10, then installed fresh VSCode. The issue was immediately there.

I tried running it with a different user data directory as per your suggestion and got the same result.

Is there anything else we can check?
