### ISSUE TITLE
Inscrease margin when "editor.glyphMargin" is "false"

### ISSUE THREAD

**Issue by DavidBabel** [microsoft/vscode#63215]
I LOVE (very very much) the `editor.glyphMargin` option, allowing to disable the debugger column. It saves a lot of unneeded space for those who wants, especially with multiple vertical editors.

But there is a little visual glitch here : 
![image](https://user-images.githubusercontent.com/5599375/48559199-6983bd00-e8eb-11e8-8798-ce0b4a2fdb9c.png)

Add a small `margin-left` on the line number column should be a good idea. `3px` or `4px` should be enough.

Have a good day :)

Actually : just tested it, `6px` is the best match

**Comment by isidorn** [comment]
Just to make this clear - you added the red line to show us the glitch right?
Because I do not see the glitch, on the right that marks an occurence or a cursor in the scroll bar. On the left that is just the editor content.

The point of the glyph is to be used as a margin, if you do not want margin you should disable the glyph (as I personally did). IMHO we should not introduce any more margins if the glyph is disabled.

Though forwarding this to @alexandrudima to decide

Have a nice day as well :)

**Comment by DavidBabel** [comment]
> Just to make this clear - you added the red line to show us the glitch right?
I did.

On the left, the "o" touch the 1 of 129 and on the right the "u" is almost inside the "1" in 1042. It seems nothing important, but i created the issue after using it 2 days, and it's very confuging sometimes to not see the limit between the two editors.
I tested to add a margin with this plugin https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css and it's faaaaar better with a little margin.

Of course, this is my opinion.
