### ISSUE TITLE
[VSCode-Proper] A11y_ViennaVsCodeExtension_AzureMachineLearningTAB_ScreenReader:Narrator is not providing accurate information between parent-child relations of the tree view elements.

### ISSUE THREAD

**Issue by greazer** [Microsoft/vscode#63252]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by greazer** [comment]
Environment Details:
Application Name: ViennaVsCodeExtension
Application Version: 1.27.2
Operating System: Windows10
Url:  https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-ai#overview

Repro Steps:
1) Launch VisualStudio Code.
2) Navigate to Azure TAB.
3) Azure Machine learning tree view should open.
4) Start Narrator.
5) Verify how Narrator describes the relation between parent child elements of the tree-view.

Actual
Narrator is not providing any information about the parent field of corresponding child elements under tree view. The relationship between elements is not clear.

Note
This issue exist for 'WINDOWS + JAWS18' configuration too.

Expected
Narrator should clearly describe about the parent-child relationship between elements under tree view.

User Impact
Screenreader user will not understand what child elements are present under the Parent elements.

Recommendation
https://microsoft.sharepoint.com/teams/msenable/mas/pages/mas-details.aspx?masid=4.2.6

MAS Reference
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={f3129360-453b-4e17-b038-e15e337b791c}

**Comment by greazer** [comment]
[703372_A11y_ViennaVsCodeExtension_AzureMachineLearningTAB_ScreenReader.zip](https://github.com/Microsoft/vscode/files/2587481/703372_A11y_ViennaVsCodeExtension_AzureMachineLearningTAB_ScreenReader.zip)

**Comment by sandy081** [comment]
@isidorn What is our strategy about handling accessibility issues from extensions?

**Comment by isidorn** [comment]
Narrator is not supported for vscode.
Accessibility issue from extension should go in extensions repositories. And we already have duplicates of this.

**Comment by greazer** [comment]
@isidorn 
- AFAIK, Narrator needs to be supported for all Microsoft released products, unless VSCode has gotten a specific exemption for it. If that is the case, can you please point me at where the exemption is located?
- This particular issue can't be fixed by the extension as far as I can tell. Therefore, I don't see why it would need to continue to live in the extension's repo.
- If it's a duplicate, I know that the "accessibility police" will be asking me where that dupe is. Can you point me at it?

**Comment by isidorn** [comment]
@greazer hi, thanks for coming back. 
I am not sure about how the exemption for VSCode narrator works, we just do not support Narator. Our philospohy is that we are an open source project and we support other open source projects like NVDA. For more details please contact @auchenberg 
It might be a duplicate of some other narattor issues, however we are just not fixing those and closing them, so finding the exact duplicate will not be useful in this case.

Yes this issue can not be fixed by the extension that is correct, however just copy pasting issues filled by the accessibilty team does not really help us.
What helps us if you understand the issue, translate it to a useful human readable bug, create an issue in vscode and provide a PR which potentially fixes it.

Thanks a lot

**Comment by auchenberg** [comment]
@greazer @isidorn Because VS Code is an Electron based we have a set of different requirements for MAS C compliance. Our targets are:
- Complete a successful full pass with NVDA on Windows 10 +
- Complete a successful full pass with VoiceOver on Mac
