### ISSUE TITLE
Horizontal scroll option disabled after changing sidebar view

### ISSUE THREAD

**Issue by anteprimorac** [Microsoft/vscode#63312]
Issue Type: <b>Bug</b>

1. Enable Workbench > Tree: Horizontal scrolling
2. Restart vscode
3. Open explorer sidebar view
4. Change sidebar view, for example, source control
5. Go back to explorer sidebar view (horizontal scrolling is disabled although settings option is still enabled)

VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:06:21.742Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz (4 x 1400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|4.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
acf-content-blocks|ant|0.0.1
vscode-typescript-tslint-plugin|ms-|0.0.6
vetur|oct|0.13.0
vscode-icons|rob|7.28.0
ayu|tea|0.17.0
wordpress-snippet|tun|1.1.5
gitblame|wad|2.6.1

</details>

**Comment by isidorn** [comment]
Works fine for me. Can you reproduce with latest vscode insider https://code.visualstudio.com/insiders/
If yes, what are you doing differently than me in this gif?
Are you sure that it is disabled, and not simply hidden, since we do not render it when there is nothing to scroll too (only when the view gets wide we show it)

![repro](https://user-images.githubusercontent.com/1926584/48633255-3f9dc980-e9c3-11e8-8a8c-49c019ac4a95.gif)
