### ISSUE TITLE
open new window will open 2 windows when the workspace has 2 project path

### ISSUE THREAD

**Issue by eos3tion** [Microsoft/vscode#63398]
- VSCode Version:1.29.1
- OS Version: Window 10 pro v1803

Steps to Reproduce:

1.Add 2 folder to workspace.
2.use `open new window` command.

**Comment by roblourens** [comment]
I don't see this. It opens 2 empty windows?

**Comment by bpasero** [comment]
@eos3tion I cannot reproduce, what are the exact steps?

Does it also reproduce if you pick "New Window" from the command palette?

![image](https://user-images.githubusercontent.com/900690/48754011-7eb46f00-ec90-11e8-87bf-a390c9531f7a.png)

**Comment by eos3tion** [comment]
@bpasero yeap，use `New Window` command,will also create 2 new windows.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by eos3tion** [comment]
@bpasero Version:1.30.0-insider  is ok.
It correctly open 1 new window.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by eos3tion** [comment]
@bpasero you are right,thx!  
I disable `Java IDE pack` and reenable that extension, the bug is disappeared.
