### ISSUE TITLE
Outline progress bar is distracting

### ISSUE THREAD

**Issue by mikemac8888** [microsoft/vscode#63400]
Please provide the option to disable the blue outline progress bar. Any change to the file fires this progress bar and it's very distracting. Thanks

**Comment by larsch** [comment]
I second this. The little progress ant is incredible distracting and is constantly running when editing code.

**Comment by blurHY** [comment]
From stackoverflow
```js
"workbench.colorCustomizations": {
    "progressBar.background": "#fff0",
}
```

**Comment by jrieken** [comment]
Instead of disabling this I think we should improve the smarts when it shows. Today it's hardcoded to be delayed by 150ms. If your provider/extension isn't faster than that you will always see the progress bar... Instead we should have a moving average of how long it takes to compute the outline and delay the progress by that.

**Comment by jrieken** [comment]
The progress bar delay is now based on average provider response time  (`avgDur` * 1.3). That ensure you only see the progress bar when updating the outline takes longer than usual

**Comment by jrieken** [comment]
Verifier: open a huge file like [`checker.ts`](https://github.com/microsoft/TypeScript/blob/master/src/compiler/checker.ts) and make sure outline progress isn't too annoying.
