### ISSUE TITLE
Can't close tab with middle mouse click when mouse is over the close button

### ISSUE THREAD

**Issue by xchrdw** [Microsoft/vscode#63431]
- VSCode Version: 1.29.0
- OS Version: Linux

Steps to Reproduce:

1. Try to close multiple tabs with middle mouse click
2. Due to varying tab length, the mouse will at some point be over the close button of a tab
3. Tabs can't be closed when the mouse is over the close button ('x')

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
If someone wants to fix this, be my guest.

**Comment by JohanssonDaniel** [comment]
Hi @bpasero can I take a look at this?

**Comment by bpasero** [comment]
@JohanssonDaniel sure go ahead, my guess would be somewhere in `tabsTitleControl.ts`

**Comment by bpasero** [comment]
Looks like this is caused by the check for `e.button === 1 /* Middle Button*/ && !this.originatesFromTabActionBar(e)` in tabsTitleControl.ts which was added for https://github.com/Microsoft/vscode/commit/35a12c9483c6b7b6abb79364540355c6d3040cde but I cannot reproduce that issue anymore (possibly due to the `e.stopPropagation()` right after which we did not have back in the days).

**Comment by bpasero** [comment]
Unfortunately I can still reproduce the issue on Windows when I remove that check so the solution has to solve both issues...

**Comment by JohanssonDaniel** [comment]
Hi @bpasero! I have tried to reproduce the issue you mentioned by removing the `!this.originatesFromTabActionBar(e)` check without success on both of my windows machines with two different mouses. Without the check, I am able to close a single tab by clicking with the **middle mouse button** on the x icon (and also anywhere else on the tab) without closing the tab to the right. 

With check
![Alt Text](https://i.imgur.com/PnyzQYJ.gif)

Without check
![Alt Text](https://i.imgur.com/9RSKd68.gif)

Since I am not able to reproduce it, it might be a good idea if someone else can work on it instead. It might also be a good idea to check with other mouses since I know from my own experience that the middle mouse button might become faulty and randomly perform double clicks. I did a quick google search and it seems to be a common enough problem that it might be worth looking into 👍

**Comment by bpasero** [comment]
@JohanssonDaniel did you try on Windows?

**Comment by JohanssonDaniel** [comment]
Yes, I tried it on two computers running windows.

**Comment by bpasero** [comment]
I think the fix is actually fine, what I saw seems to be a feature of my mouse where when I press the middle mouse button hard enough it will actually fire `MOUSE_UP` events periodically. We have to be on the watch out for users reporting a regression though.
