### ISSUE TITLE
breakpoints not available on startup

### ISSUE THREAD

**Issue by maziac** [Microsoft/vscode#63444]
Hi,
I'm developing a debug adapter and I was trying to read the vscode.debug.breakpoints array from the **launchRequest** method.
But unfortunately the array is defined but empty even if breakpoints are set in the sources.

Additional info: If I access the same array from the restartRequest the array is filled with all breakpoints.

**Comment by weinand** [comment]
It is not supported to use VS Code API (like `vscode.debug.breakpoints`) in the implementation of your debug adapter.

**Comment by maziac** [comment]
Why is this?
It is described in the API:
"The set of all breakpoints of a workspace can be accessed through vscode.debug.breakpoints. "
See https://code.visualstudio.com/docs/extensionAPI/api-debugging

**Comment by weinand** [comment]
A debug adapter (DA) is **not** a VS Code extension because it does not run in the extension host and therefore it cannot use the VS Code Extension API (like vscode.debug.breakpoints).

The reason for this that DAs can be used independent from VS Code.
E.g. **VisualStudio** uses DAs but VisualStudio does not support the VS Code API.
So if a DA would use VS Code API, it would not be possible to use the DA in VisualStudio.

The VS Code Debug API (like vscode.debug.breakpoints) can be used to **talk to** VS Code's debuggers but it cannot be used to implement one.

You will find this constraint in others places too: the VS Code Language API can be used to talk to language servers, but you cannot implement a language server with it. 

(From a technical perspective the problem is that you are ending in a endless recursion if your DA uses the API that it is implementing).

**Comment by maziac** [comment]
I'm using the approach mentioned here: https://code.visualstudio.com/docs/extensions/example-debuggers
and put extension and debug-adapter in one program (EMBED_DEBUG_ADAPTER).

In that case I should be able to work with vscode.debug.breakpoints, vscode.debug.addBreakpoints or vscode.debug.removeBreakpoints, I guess.

However,  I don't need to stick to this API if there is another that serves my purposes.

Do you maybe have a hint for me how to achieve my goal:

From the debug-adapter (or extension) right after starting a debug session I would like to add a few breakpoints
and change or remove some existing ones.

**Comment by weinand** [comment]
Yes, you can use the EMBED_DEBUG_ADAPTER approach, but you must not use the extension API inside the Debug Adapter code (because that results in recursion).

You said:
> From the debug-adapter (or extension) right after starting a debug session I would like to add a few breakpoints and change or remove some existing ones.

you have two options for this:
- from your DA you can create new breakpoints via the DAP protocol by emitting [Breakpoint events](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Breakpoint) with reason `new`.
- from your extension you can create new breakpoints via the extension API `vscode.debug.addBreakpoints`. 

Please note that with the latter approach you can create breakpoints even if no debug session is running because VS Code manages them for you in the meantime.

So the "pattern" is:
- in the DA only use DAP (or if you are running in EMBEDDED mode only use non-debug extension API to avoid recursion),
- in the extension only use extension API.

**Comment by maziac** [comment]
OK, but how can I remove or change breakpoints.
If I simply add them they are ignored if a breakpoint for the same line already exists.
I would therefore like to remove the breakpoints at the same line first and then write them again.

This may seem odd but I would like to be able to write breakpoints with new breakpoint conditions.

At the moment if I write a new breakpoint at the line where a breakpoint already exists the new breakpoint with the new breakpoint condition is ignored.

It would help me also if this would work differently. I.e. if the next breakpoint would always overwrite any previous breakpoint.

**Comment by weinand** [comment]
In your extension iterate over `vscode.debug.breakpoints` and find the breakpoint to remove and then remove breakpoints via `vscode.debug.removeBreakpoints`.

**Comment by maziac** [comment]
"In your extension iterate over vscode.debug.breakpoints and find the breakpoint to remove and then remove breakpoints via vscode.debug.removeBreakpoints."

That is what I was trying to do. But vscode.debug.breakpoints is empty.
At least at the time that  launchRequest is called.
It is empty although breakpoints are set in the sources.
Later e.g. in a restartRequest the array is correctly filled.

**Comment by weinand** [comment]
Please read https://code.visualstudio.com/docs/extensionAPI/api-debugging#_breakpoints-api:

![2018-11-20_23-17-11](https://user-images.githubusercontent.com/1898161/48806390-730d8a80-ed1a-11e8-8834-4f0d72f11a72.png)

**Comment by maziac** [comment]
Ok, seems I overlooked that.
So I need to check if the vscode.debug.breakpoints array is empty. If not (e.g. restartRequest) I can use it directly. If it is empty (launchRequest) I need to wait for an BreakpointChangeEvent.

Will I get exactly one event with all breakpoints? Or can I expect to receive several events? If the latter case: when do I know that I received all breakpoints?

And in case there are no breakpoints? How do I know? The array is empty and I guess I will not receive any change event?

I would have to work with some arbitrary timeout which I personally don't like.

**Comment by weinand** [comment]
First: as I explained earlier don't access the breakpoint extension API from the DA's launchRequest or restartRequest methods as that results in deadlocks.

If you want to use the `vscode.debug.breakpoints` in your extension (and not in your DA) you will have to understand that this data structure is updated asynchronously from VS Code.

"Waiting" for some events to arrive is wrong, because there are always events arriving (because the user can add/remove/change breakpoints at any time). BTW, this model is used for all datastructures living in the extension.

Instead of waiting for events just react on breakpoint events and do what you need to do on the incremental updates information you receive.

I suggest you activate your extension on "*" and in the activate function you register for breakpoint events. This will ensure that `vscode.debug.breakpoints` is up-to-data early, that is before any debug session starts.

---

But why you are not using the breakpoints that VS Code sends to the DA with the setBreakpoints request after the DA has sent the initialize request? Here you can be sure that you get all breakpoints that exist at the time you start debugging?

**Comment by maziac** [comment]
"But why you are not using the breakpoints that VS Code sends to the DA with the setBreakpoints request after the DA has sent the initialize request? Here you can be sure that you get all breakpoints that exist at the time you start debugging?"

Because I can't modify them (change the condition) or remove them at that point.

Of course, I am reacting on this request. But this is direction to set BPs from vscode to the debugger.
I need vice versa: I want to tell vscode to set some extra breakpoints, to change the condition of a few and to remove some.

I don't want to do this everytime only on startup. So even if this would work somehow I would need to  setup a state machine for this and handle the breakpoint request differently if the debugging is currently starting or if it is already running.

I hadn't thought that this is so complicated. I just want the breakpoints :-)

**Comment by weinand** [comment]
Why does this code not work for you?
```ts
export function activate(context: vscode.ExtensionContext) {

	vscode.debug.onDidChangeBreakpoints(brk_event => {
		if (brk_event.added.length) {
			// I want to tell vscode to set some extra breakpoints, to change the condition of a few and to remove some
		}
		if (brk_event.changed.length) {
			// I want to tell vscode to set some extra breakpoints, to change the condition of a few and to remove some
		}
	});

}
```

All breakpoints passed to your DA will go through the `onDidChangeBreakpoints` handler and are available for your modifications.

**Comment by weinand** [comment]
no

**Comment by maziac** [comment]
Is it guaranteed to receive onStartDebugSession after onDidChangeBreakpoints?

**Comment by weinand** [comment]
of course not because both events are independent:
- `onDidChangeBreakpoints` is fired if user has changed the breakpoints, e.g. adding one, or editing the condition of a breakpoint.
- `onStartDebugSession` is fired if a user starts a debug session.

That's the nature of events: typically there are no guarantees that they arrive in a specific order.
