### ISSUE TITLE
Potential leak detected in decorations

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#63467]
Issue Type: <b>Bug</b>

While working with VS Code today, I saw these two potential leaks in the dev console:

```
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:185 [cf4] potential listener LEAK detected, having 1001 listeners already. MOST frequent listener (501):
e.check @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:185
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:185     at new e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2037:828)
    at new e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2040:545)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2047:159
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1926:480
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1926:518
    at V (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1916:839)
    at t._renderOnce (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1923:831)
    at t.change (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1926:254)
    at t.changeViewZones (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1949:459)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2046:623
    at o._changeDecorations (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1207:185)
    at o.changeDecorations (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1206:478)
    at t.changeDecorations (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1945:46)
    at e._renderCodeLensSymbols (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2046:583)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2044:884
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
e.check @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:185
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:185 [619] potential listener LEAK detected, having 590 listeners already. MOST frequent listener (187):
e.check @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:185
/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:185     at new e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1791:516)
    at new e (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1788:363)
    at t.registerDecorationType (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1787:605)
    at t._registerDecorationType (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1955:219)
    at t.setDecorations (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1945:655)
    at e.setDecorations (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3238:409)
    at e.$trySetDecorations (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3354:80)
    at t._doInvokeHandler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3293:963)
    at t._invokeHandler (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3293:635)
    at t._receiveRequest (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3292:262)
    at t._receiveOneMessage (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3291:126)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3289:10
    at e.fire (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:186:466)
    at a (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:342:213)
    at Socket.n._socketDataListener (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:342:434)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
e.check @ /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:185
```

Sorry, no clear repo steps. I first noticed this when I was in a side-by-side diff view and trying to stage a change the selected range. This operation took quite a while. 

VS Code version: Code - Insiders 1.30.0-insider (ebe9ea85a0a0bb087dccc98949542605dfc51f6f, 2018-11-19T19:59:44.607Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|-psn_0_15298198|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.5.0
comment-tagged-templates|bie|0.2.0
emojisense|bie|0.4.1
folder-source-actions|bie|0.0.4
github-markdown-preview|bie|0.0.2
lit-html|bie|1.10.1
markdown-checkbox|bie|0.1.1
markdown-emoji|bie|0.0.7
markdown-image-size|bie|0.0.2
markdown-mermaid|bie|1.0.0
markdown-preview-github-styles|bie|0.1.4
markdown-yaml-preamble|bie|0.0.2
speech|bie|0.0.2
vscode-eslint|dba|1.7.0
gitlens|eam|8.5.6
vscode-npm-script|eg2|0.3.5
vscode-pull-request-github|Git|0.2.3
vscode-memfs|jri|0.0.3
theme-karyfoundation-themes|kar|18.2.1
vscode-azurefunctions|ms-|0.12.0
vscode-cosmosdb|ms-|0.9.0
vscode-language-pack-de|MS-|1.29.2
vscode-language-pack-zh-hans|MS-|1.29.2
mssql|ms-|1.4.0
python|ms-|2018.10.1
azure-account|ms-|0.7.0
Go|ms-|0.7.0
vscode-typescript-tslint-plugin|ms-|0.1.0
debugger-for-chrome|msj|4.11.1
java|red|0.34.0

(16 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
d37f7c158322b3b66e61721f196e7fa56c2c9ab0 looked into one potential leak. Not sure if this was the one causing the issue or not since I can't reliably repo the problem

**Comment by alexandrudima** [comment]
Deminified using https://github.com/alexandrudima/vscode-stack-beautifier


#### First stack:

That listener was introduced via https://github.com/Microsoft/vscode/commit/5005b5bbb37f706b222aa6eaa675f50ec9c11b14 @jrieken 

&nbsp;&nbsp;at&nbsp;`onDidChangeConfiguration`&nbsp;([./editor/contrib/codelens/codelensWidget.ts:87:38](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/contrib/codelens/codelensWidget.ts#L87))<br/>&nbsp;&nbsp;at&nbsp;[./editor/contrib/codelens/codelensWidget.ts:247:24](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/contrib/codelens/codelensWidget.ts#L247)<br/>&nbsp;&nbsp;at&nbsp;[./editor/contrib/codelens/codelensController.ts:253:23](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/contrib/codelens/codelensController.ts#L253)<br/>&nbsp;&nbsp;at&nbsp;`func`&nbsp;([./editor/browser/view/viewImpl.ts:589:9](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/view/viewImpl.ts#L589))<br/>&nbsp;&nbsp;at&nbsp;`callback`&nbsp;([./editor/browser/view/viewImpl.ts:498:18](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/view/viewImpl.ts#L498))<br/>&nbsp;&nbsp;at&nbsp;`func`&nbsp;([./editor/browser/view/viewImpl.ts:581:9](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/view/viewImpl.ts#L581))<br/>&nbsp;&nbsp;at&nbsp;`safeInvokeNoArg`&nbsp;([./editor/browser/view/viewImpl.ts:359:10](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/view/viewImpl.ts#L359))<br/>&nbsp;&nbsp;at&nbsp;`_renderOnce`&nbsp;([./editor/browser/view/viewImpl.ts:478:7](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/view/viewImpl.ts#L478))<br/>&nbsp;&nbsp;at&nbsp;`change`&nbsp;([./editor/browser/widget/codeEditorWidget.ts:1247:40](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/widget/codeEditorWidget.ts#L1247))<br/>&nbsp;&nbsp;at&nbsp;`changeViewZones`&nbsp;([./editor/contrib/codelens/codelensController.ts:222:16](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/contrib/codelens/codelensController.ts#L222))<br/>&nbsp;&nbsp;at&nbsp;`callback`&nbsp;([./editor/common/model/textModel.ts:1502:12](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/common/model/textModel.ts#L1502))<br/>&nbsp;&nbsp;at&nbsp;`_changeDecorations`&nbsp;([./editor/common/model/textModel.ts:1467:15](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/common/model/textModel.ts#L1467))<br/>&nbsp;&nbsp;at&nbsp;`changeDecorations`&nbsp;([./editor/browser/widget/codeEditorWidget.ts:1019:31](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/widget/codeEditorWidget.ts#L1019))<br/>&nbsp;&nbsp;at&nbsp;`changeDecorations`&nbsp;([./editor/contrib/codelens/codelensController.ts:221:15](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/contrib/codelens/codelensController.ts#L221))<br/>&nbsp;&nbsp;at&nbsp;`_renderCodeLensSymbols`&nbsp;([./editor/contrib/codelens/codelensController.ts:121:10](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/contrib/codelens/codelensController.ts#L121))<br/>&nbsp;&nbsp;at&nbsp;`hasListeners`&nbsp;([./base/common/event.ts:302:11](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./base/common/event.ts#L302))<br/>

---

#### Second stack:

Might be fixed by your change d37f7c158322b3b66e61721f196e7fa56c2c9ab0  @mjbvz .

&nbsp;&nbsp;at&nbsp;[./editor/browser/services/codeEditorServiceImpl.ts:91:28](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/services/codeEditorServiceImpl.ts#L91)<br/>&nbsp;&nbsp;at&nbsp;[./editor/browser/services/codeEditorServiceImpl.ts:42:15](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/services/codeEditorServiceImpl.ts#L42)<br/>&nbsp;&nbsp;at&nbsp;`registerDecorationType`&nbsp;([./editor/browser/widget/codeEditorWidget.ts:1495:26](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/widget/codeEditorWidget.ts#L1495))<br/>&nbsp;&nbsp;at&nbsp;`_registerDecorationType`&nbsp;([./editor/browser/widget/codeEditorWidget.ts:1060:10](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/browser/widget/codeEditorWidget.ts#L1060))<br/>&nbsp;&nbsp;at&nbsp;`setDecorations`&nbsp;([./workbench/api/electron-browser/mainThreadEditor.ts:386:19](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./workbench/api/electron-browser/mainThreadEditor.ts#L386))<br/>&nbsp;&nbsp;at&nbsp;`setDecorations`&nbsp;([./workbench/api/electron-browser/mainThreadEditors.ts:175:42](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./workbench/api/electron-browser/mainThreadEditors.ts#L175))<br/>&nbsp;&nbsp;at&nbsp;`apply`&nbsp;([./workbench/services/extensions/node/rpcProtocol.ts:461:16](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./workbench/services/extensions/node/rpcProtocol.ts#L461))<br/>&nbsp;&nbsp;at&nbsp;`_doInvokeHandler`&nbsp;([./workbench/services/extensions/node/rpcProtocol.ts:446:31](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./workbench/services/extensions/node/rpcProtocol.ts#L446))<br/>&nbsp;&nbsp;at&nbsp;`_invokeHandler`&nbsp;([./workbench/services/extensions/node/rpcProtocol.ts:366:18](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./workbench/services/extensions/node/rpcProtocol.ts#L366))<br/>&nbsp;&nbsp;at&nbsp;`_receiveRequest`&nbsp;([./workbench/services/extensions/node/rpcProtocol.ts:296:9](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./workbench/services/extensions/node/rpcProtocol.ts#L296))<br/>&nbsp;&nbsp;at&nbsp;`_receiveOneMessage`&nbsp;([./workbench/services/extensions/node/rpcProtocol.ts:171:41](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./workbench/services/extensions/node/rpcProtocol.ts#L171))<br/>&nbsp;&nbsp;at&nbsp;`call`&nbsp;([./base/common/event.ts:212:15](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./base/common/event.ts#L212))<br/>&nbsp;&nbsp;at&nbsp;`fire`&nbsp;([./base/parts/ipc/node/ipc.net.ts:103:22](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./base/parts/ipc/node/ipc.net.ts#L103))<br/>&nbsp;&nbsp;at&nbsp;`acceptChunk`&nbsp;([./base/parts/ipc/node/ipc.net.ts:132:3](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./base/parts/ipc/node/ipc.net.ts#L132))<br/>&nbsp;&nbsp;at&nbsp;`idx`&nbsp;([./base/common/paths.ts:48:5](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./base/common/paths.ts#L48))<br/>&nbsp;&nbsp;at&nbsp;`Promise`&nbsp;([./base/common/actions.ts:196:10](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./base/common/actions.ts#L196))<br/>&nbsp;&nbsp;at&nbsp;`_shouldRender`&nbsp;([./base/browser/ui/scrollbar/horizontalScrollbar.ts:72:7](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./base/browser/ui/scrollbar/horizontalScrollbar.ts#L72))<br/>&nbsp;&nbsp;at&nbsp;`_revealTimer`&nbsp;([./base/browser/ui/scrollbar/scrollbarVisibilityController.ts:91:7](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./base/browser/ui/scrollbar/scrollbarVisibilityController.ts#L91))<br/>&nbsp;&nbsp;at&nbsp;`prototype`&nbsp;([./base/browser/ui/tree/objectTreeModel.ts:98:1](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./base/browser/ui/tree/objectTreeModel.ts#L98))<br/>&nbsp;&nbsp;at&nbsp;`Position`&nbsp;([./editor/common/model/pieceTreeTextBuffer/pieceTreeBase.ts:437:16](https://github.com/Microsoft/vscode/blob/ebe9ea85a0a0bb087dccc98949542605dfc51f6f/src/vs/./editor/common/model/pieceTreeTextBuffer/pieceTreeBase.ts#L437))<br/>

**Comment by jrieken** [comment]
the code lens widgets don't leak but each widget is a listener which is maybe not the smartest...

**Comment by jrieken** [comment]
Pushed one more change to fix an actual leak, but that grows with the number of editors only.

**Comment by jrieken** [comment]
Closing this and seeing if this occurs again... Per editor code is now just 1 listener, not one per lens. Unsure what the other 500 listeners are...
