### ISSUE TITLE
Startup time to edit time could be faster

### ISSUE THREAD

**Issue by Aaron-Fleisher** [Microsoft/vscode#63542]
- VSCode Version: Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
- OS Version: Windows 10, 64-bit, Samsung 850 EVO SSD 

Steps to Reproduce:

1. Launch app 
![](https://i.gyazo.com/b41e6d09b04201da8d18c87eb5b092b8.gif)

2. Compared to Sublime:
![](https://i.gyazo.com/77ce3a2fc53eab65d280267161444418.gif)

**Comment by jrieken** [comment]
@cleidigh Please do not add labels!

**Comment by jrieken** [comment]
please follow this guide: https://github.com/Microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly

**Comment by Aaron-Fleisher** [comment]
@jrieken Hello, thank you.  Here are the stats: https://paste.ee/p/maRLW

[Here](https://i.gyazo.com/0344b8833b82cdb214a5c66b1c263c47.png) is an easier to read picture

**Comment by jrieken** [comment]
Startup is 1.5 seconds which is faster than average. There is nothing unexpected and 'yes' we are slower than ST. That's because of various reasons, the most obvious is native code vs JS code. This item isn't actionable but it's a constant theme on our plan, check the perf-label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aperf

**Comment by Aaron-Fleisher** [comment]
That's understandable, jrieken. Just a pet peeve I guess.  Thank you for taking a look!
