### ISSUE TITLE
terminal window is duplicated after restarting vscode debug

### ISSUE THREAD

**Issue by coaperator** [microsoft/vscode#63543]
When debugging, i use CTRL+SHIFT+F5 for restart debug, a new console window opens instead of using the current one.
**Is this a bug?**

![default](https://user-images.githubusercontent.com/6645911/48819955-ae807700-ed63-11e8-9ef2-2eb64c3b6dd5.png)

My debug config
```js
{
	// Используйте IntelliSense, чтобы узнать о возможных атрибутах.
	// Наведите указатель мыши, чтобы просмотреть описания существующих атрибутов.
	// Для получения дополнительной информации посетите: https://go.microsoft.com/fwlink/?linkid=830387
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Start",
			"program": "${workspaceFolder}/app.js",
			"env": { "NODE_PATH": ".", "NODE_ENV": "production" }
		},
		{
			"type": "node",
			"request": "launch",
			"name": "Launch Dev",
			"runtimeExecutable": "nodemon",
			"program": "${workspaceFolder}/app.js",
			"restart": true,
			"console": "integratedTerminal",
			"internalConsoleOptions": "neverOpen",
			"skipFiles": ["node_modules/**"], //, "public/**"
			"env": { "NODE_PATH": ".", "NODE_ENV": "development" }
		}
	]
}

```

**Comment by weinand** [comment]
@coaperator I cannot parse your sentence "When debugging CTRL + SHIFT + F5 is restarted" into steps that I can reproduce.
Could you please provide clear steps that I can reproduce? Thanks!

**Comment by coaperator** [comment]
@weinand just press CTRL + SHIFT + F5 several times or the restart button on the debag minipanel

![default](https://user-images.githubusercontent.com/6645911/48837471-86f6d200-ed96-11e8-9fd4-03985a1c5fff.png)

**Comment by weinand** [comment]
And which of the 2 launch configs are you using?

**Comment by coaperator** [comment]
> And which of the 2 launch configs are you using?

latest

**Comment by coaperator** [comment]
@weinand but what happens in the task manager when restarting debug

![image](https://user-images.githubusercontent.com/6645911/48843320-c5e15380-eda7-11e8-8d79-adf3aca19db3.png)

**Comment by coaperator** [comment]
need add windows label

**Comment by coaperator** [comment]
Is there any news to fix this problem?

**Comment by weinand** [comment]
Since your launch config uses "nodemon", and `"restart": true`, the debug session will automatically restart whenever nodemon detects a program change.

Given that behavior, I do not understand why you are using the "Restart" action (or button)?. This asks for problems...

"Restart" kills one session and starts a new session. This is basically the same as "nodemon" but there is a problem: in our documentation about node.js debugging and "nodemon" we clearly say:

<img width="743" alt="2020-11-11_13-00-22" src="https://user-images.githubusercontent.com/1898161/98809887-9a395700-241e-11eb-953c-930c3156ec92.png">

So stopping (or restarting) the debug session will **not** terminate "nodemon". If you do "restart" multiple times, you will accumulate many "nodemons". In addition every "nodemon" will block the integrated terminal it was launched in. As a consequence the next debug session cannot use the same integrated terminal (because it is blocked by the previous nodemon) and creates a new one.

This is what you are seeing: many terminals and many node processes hanging around...

The correct use of a "nodemon" launch config is:
- start it and let it run... it should restart the debug session automatically after every code change.
- for terminating debugging press the Stop button **and kill "nodemon" in the integrated terminal with Cntr-C."
