### ISSUE TITLE
JSON error when running <myTreeViewId>.focus-command

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#63638]
* have a custom view with id `foo`
* from the extension host run the `foo.focus` command
* on the main side a silent error occurs (run with break on all errors)

<img width="586" alt="screenshot 2018-11-22 at 12 30 36" src="https://user-images.githubusercontent.com/1794099/48900355-7015b580-ee52-11e8-8957-517983c57bd9.png">

**Comment by jrieken** [comment]
cc @alexandrudima for us ignoring all those errors... https://github.com/Microsoft/vscode/blob/b36ee32fe7ca1da5285f1392be22c8bd14355315/src/vs/workbench/services/extensions/node/rpcProtocol.ts#L22-L29

**Comment by alexandrudima** [comment]
I have to ignore them... Extensions constantly make RPC calls which involve recursive datastructures... This was always showing up in error telemetry.

This was also one of the root causes for leakages, e.g. a command invocation would never complete if serializing its result would throw.

Long story short, the "contract" is that calling with a non serializable object leads to the UI side getting "null". IMHO this is not so bad. The errors don't go to error telemetry because they then reach me and I have nothing to do with them.

**Comment by jrieken** [comment]
How about a `console.warn`-statement  when in dev-mode `process.env.VSCODE_DEV`?
