### ISSUE TITLE
ResourceLabel listens

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#63655]
When adding the listener-leak-warning (https://github.com/Microsoft/vscode/commit/b548ced43cb1c9f86f3a013e20ccd8613fbd4138) I had to chose a very high default limit of 500 listeners. This is mostly because of the `ResourceLabel` which registers `5` listeners per instance. This multiples quickly because the resource label is used everywhere. On a normal screen the explorer shows ~40 elements which results is 200 listeners already. The same is true for one page of  search results and a page full of git changes, totalling then at 600 listeners, 120 listener per event.

Instead, "containers" should listen. In above sample the explorer-, the search-, and the git-viewlet. That would total in 3*5 listeners. This would be especially useful for those event-handlers that are all the same, like this one: https://github.com/Microsoft/vscode/blob/d21dbf9cc1ad020a8dc686de8d29894a2a6ea7b3/src/vs/workbench/browser/labels.ts#L79-L83

Also, listening can be made smarter. Today, a theme change updates a label even when its viewlet isn't visible. 

For some events this might be more tricky, esp. those that require state form the widget, like its [uri](https://github.com/Microsoft/vscode/blob/d21dbf9cc1ad020a8dc686de8d29894a2a6ea7b3/src/vs/workbench/browser/labels.ts#L99) or specific config. It would still try to keep the widget stupid and to make that state accessible via getters so the outside can make a decision with that information.

**Comment by bpasero** [comment]
@jrieken I pushed a couple of things:
* [`ResourceLabels`](https://github.com/Microsoft/vscode/blob/51582b9dfeeb58833dad4cbf7beed01088bc8c45/src/vs/workbench/browser/labels.ts#L76) is the new guy that should be used unless you really just have one label (only 2 places currently where this is true)
* it exposes methods `onVisible` and `onHidden` (similar to the old tree) that containers on top can call to indicate if they are visible or not
* based on that the labels decide wether they should redraw or not (and if a request comes in to redraw, they will redraw once the label becomes visible

I adopted `onVisible` and `onHidden` for every view. I did not adopt it for `BreadcrumbsPicker` because I did not see an obvious isVisible change, maybe you could add that. 

@sandy081 I got a little bit lost for `Viewlet` vs `View`. My understanding is that `setVisible` is called for `Viewlets`, but I was not sure if a similar concept exists for a `View` when it gets collapsed or expanded (or actually its parent `Viewlet` gets shown or hidden).

I feel like a follow up item could be to have `Viewlet` and `View` have an event that the `ResourceLabels` could subscribe to to make this easier.

PS: the labels are still listening on events even if they are not visible. I thought about changing that, but it would have the downside that I would have to basically replay each event that happened when the label becomes visible. I thought this was not a big enough gain to have.

PPS: I guess this means we could change the event leak listener count again.

**Comment by jrieken** [comment]
> PPS: I guess this means we could change the event leak listener count again.

✅
