### ISSUE TITLE
Context key change event is triggered when setting the same URI but different instance

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#63656]
- Use Resource Context that takes URI as the value
- Create an URI from a string and set it
- Context key change event is triggered 
- Create another URI from the same string as in step 2 and set it
🐛 Context key change event is triggered again

You can see an infinite loop when running from sources by doing the following change
Change the return to 

https://github.com/Microsoft/vscode/blob/1081caf17a7862bf6cef97f2d99b77b19b4d6734/src/vs/workbench/services/preferences/common/preferencesEditorInput.ts#L115

```ts
return URI.from({
		scheme: 'vscode-settings',
		path: `settingseditor`
	});
```

Put a console log before following line

https://github.com/Microsoft/vscode/blob/1081caf17a7862bf6cef97f2d99b77b19b4d6734/src/vs/workbench/browser/parts/editor/titleControl.ts#L212

- Now Open Settings Editor
- You will see the indefinite loop.

**Comment by jrieken** [comment]
hm, they all end up calling this and that checks for equality... https://github.com/Microsoft/vscode/blob/79bcc85f3ea4c317c5392e80f0fb2ad49b29898b/src/vs/platform/contextkey/browser/contextKeyService.ts#L29-L36

**Comment by jrieken** [comment]
Yeah.... it's a new instance to the `!==`-check won't help...

**Comment by jrieken** [comment]
I have pushed a change that implements a proper equality check but this line is still fishy: https://github.com/Microsoft/vscode/blob/8b802549b03e6eee32c4b55843e3183f4d0c7398/src/vs/workbench/browser/parts/editor/titleControl.ts#L211-L212

This is updating the context when being asked for actions, which might very likely cause a call to getEditorAction in return. I have initially added that code but that was before grid and before having a well-defined world in which the title was scoped the an editor. @bpasero I assume things a better today that there is something the titleControl can implement so that it is called whenever its editor changed, right?

**Comment by bpasero** [comment]
@jrieken possible, I will check in debt week.

**Comment by jrieken** [comment]
Great, we should then also try to keep the menu alive instead of recreating it all the time. I will will then fire event to signal that the UI needs updating
