### ISSUE TITLE
Double clicking sidebar sash should optimize width of current sidebar, not just file explorer

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6367]
Currently double clicking the sash when the search sidebar is open looks like it attempts to optimize the width of the explorer. Additionally it gets it slightly off, probably because it's hidden and the explorer measurement algorithm assumed it would be visible.

/cc @mquandalle

**Comment by bpasero** [comment]
No, it sizes to the minimal sidebar width which is intended.

**Comment by Tyriar** [comment]
Isn't the behavior of the explorer more intuitive though? Getting rid of the text truncation?

**Comment by mquandalle** [comment]
I only implemented optimal resizing for the explorer viewlet but it would makes sense to have a similar behavior on other viewlets as well. I’m not sure about the exact formula we should use, I think it would be good to have an upper limit in case there are some long lines of text in the search results.

The implementation is pretty easy, it’s just a matter of defining a `getOptimalWidth` method on the viewlet (otherwise the default value is minimal sidebar), so someone should just come with a clear idea of the intended resizing behavior :)
