### ISSUE TITLE
Opening links from VSCode brings up infinite instances of winebrowser

### ISSUE THREAD

**Issue by megascrapper** [microsoft/vscode#63672]
- VSCode Version: 1.29.1
- OS Version: Kubuntu 18.04.1 LTS
- CPUs :  Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 2824)
- GPU Status :  2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: disabled_softwarevideo_decode: unavailable_softwarevideo_encode: unavailable_softwarewebgl: enabledwebgl2: enabled
- Load (avg) :  0, 1, 0
- Memory (System) :  31.36GB (29.48GB free)
- Process Argv :  --unity-launch
- Screen Reader : no
- VM |: 0%
- Extensions: none

Steps to Reproduce:
I have just freshly installed VSCode on my computer. Whenever I click on a link, instead of going to the default browser (which is Firefox in my case) it just opens an infinite instance of "winebrowser" which won't stop unless I kill the process. 

I have tried uninstalling Wine and installing `xdg-utils` but it doesn't seem to have an effect.   

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
