### ISSUE TITLE
ctrl/cmd + A should select all in lists / trees

### ISSUE THREAD

**Issue by docbiz** [Microsoft/vscode#63717]
I am using vscode 1.29.1 on a mid-2014 MacBook Pro running macOS 10.13.6.

When the file explorer is focussed:
1. cmd+a does not select all files; and
2. shift+arrows (to expand a selection) does not behave as it would in Finder.

(Bonus feature request: it'd be really cool if, like in JetBrains' IDEs, typing when the file explorer is focussed would filter the files.)

P.S. Keep up the amazing work—vscode is so good!

**Comment by isidorn** [comment]
cmd + a intentionally does not select all, since users expect it to select all in the editor. 
@bpasero wasn't that the reason for cmd+a, however I can not get it to select all now when focus is in the explorer

shift + arrows expands the selection for me. Can you provide more details as to what does not behave as expected here?

The bonus feature request is a duplicte - you can find it and upvote it if you want

**Comment by bpasero** [comment]
@isidorn I think now that we have multi-select in the explorer we could allow to select all in lists and trees with Cmd/Ctrl+A.

**Comment by isidorn** [comment]
Yeah, makes sense. Renaming and assigning to next milestone once we have moved to the new tree.

**Comment by docbiz** [comment]
@isidorn Thanks for getting back to me!

I've installed the Insiders edition (`456e8e64beb2dceac66743959f6802b66e18e300`) and have recorded the following video inside it:

![tmp](https://user-images.githubusercontent.com/10088591/49047072-3a642a00-f1ce-11e8-84e3-03cbde68009e.gif)

To explain what's going on here: I select 3.txt and start by expanding and contracting my election by holding down shift. I then start moving the start position for a new selection by using the arrows without holding shift down and create new selections (again, with shift+arrows) that overlap the original ones. It behaves quite unlike selections would in Finder; I don't know if this is intended. (It also might be nice if, when a selection has been created in the file explorer, the return key opened the files rather than started to rename the first file in the selection.)

>The bonus feature request is a duplicte - you can find it and upvote it if you want

I would if I could find it! But so long as you know of the idea, then that's fine by me.

Let me know if you need any more information!

**Comment by isidorn** [comment]
@docbiz I see the same with selection, so I would forward this to @joaomoreno as he owns the list / tree selection

@joaomoreno regarding cmd+A not working in the new explorer. The issue here is that [this command](https://github.com/Microsoft/vscode/blob/a5ff51c3b87e7546d4503696dad60a1f2e06677d/src/vs/workbench/electron-browser/commands.ts#L580) does not work with the tree. I think it should, so I tried changing it, however I am missing some api. More precisly I can not nicely tell the tree to select all of its elements.
The only way to do it is to traverse all elements via `getNode` collect them in an array and pass them to `setSelection`. There should be an easier way for this imho.

**Comment by usernamehw** [comment]
Would it be possible to use it by folder scopes?
Pressing <kbd>Cmd</kbd>+<kbd>A</kbd> would select all in folder, next press in the outer ...

| Initial state  | After <kbd>Cmd</kbd>+<kbd>A</kbd> |
| ------------- | ------------- |
| ![before](https://user-images.githubusercontent.com/9638156/51244829-197eb080-1997-11e9-9fb3-fc0950d838cc.png)  | ![after](https://user-images.githubusercontent.com/9638156/51244838-23a0af00-1997-11e9-9367-2cb467935b1f.png)  |

**Comment by joaomoreno** [comment]
I really like that! Pushed https://github.com/Microsoft/vscode/commit/20b2799124d987499eca20532a9e77eda1e368d0
