### ISSUE TITLE
Bug: Markdown, U+2028, and "Go to Symbol in File..."

### ISSUE THREAD

**Issue by docbiz** [Microsoft/vscode#63749]
Suppose you take the following file, except that the line containing `foo` also contains `U+2028` somewhere in it.

```markdown
# A
- foo

# B
- bar
```

`vscode` will render `U+2028` as a question mark in a diamond, and the list of symbols that appear in the 'Go to Symbol in File...'  popup will be shifted (by the number of `U+2028` characters present in the file). Screenshots that illustrate this are below.

![screen shot 2018-11-25 at 19 03 03](https://user-images.githubusercontent.com/10088591/48983289-c9951300-f0e4-11e8-83dc-f527226c95f7.png)

![screen shot 2018-11-25 at 19 03 08](https://user-images.githubusercontent.com/10088591/48983290-c9951300-f0e4-11e8-93cc-ccd5b77478c4.png)

(Why did this come up? If you triple-click ' felicita - hej! ' in [this link](https://www.residentadvisor.net/reviews/22851), and paste it into `vscode`, it actually has a pair of enclosing `U+2028` characters. It seems unique to that page...)

**Comment by docbiz** [comment]
@bpasero Attached. (Thanks for looking into this!)

[tmp.txt](https://github.com/Microsoft/vscode/files/2617557/tmp.txt)

**Comment by mjbvz** [comment]
I added a failing test for this with 2f9f0c35ccb681f9a1ff53e7619677b00a23cb95 

For anyone looking into this, this is likely the file that needs fixing: https://github.com/Microsoft/vscode/blob/master/extensions/markdown-language-features/src/tableOfContentsProvider.ts

**Comment by skprabhanjan** [comment]
@mjbvz , looking into this :)

**Comment by skprabhanjan** [comment]
@mjbvz , I think there is a flaw in the document object itself. If we fix that `_lines` in that, then this will be automatically taken care.
Because in the above example, lines are read as 5 with _lines[2] = "".
Can you please help me understand if this the correct approach.
PS: Screenshot attached.

<img width="1440" alt="screen shot 2018-11-28 at 8 08 29 pm" src="https://user-images.githubusercontent.com/17094832/49159205-f6962f80-f349-11e8-8bc7-d459606c1c26.png">

**Comment by mIkhail-zaretsky** [comment]
Looks like folding feature also can be broken because of this (since foldingProvider also uses MarkdownEngine.parse method):
![folding-issue](https://user-images.githubusercontent.com/7780340/49180458-c8bee400-f365-11e8-93d0-4ae2c8cbd24c.gif)

[tmp2.txt](https://github.com/Microsoft/vscode/files/2626509/tmp2.txt)

**Comment by shraiysh** [comment]
Hey! I am a starting to contribute in open source. I would like to take up this issue!

**Comment by mjbvz** [comment]
@skprabhanjan In your PR, move the `replace` call into `engine.parse`. That way it just happens automatically for all callers

@shraiysh Thanks but @skprabhanjan is already handling this. Take a look at some of the other help wanted issues

**Comment by shraiysh** [comment]
@mjbvz thanks. I'll look for something else.
Have a nice day! :)

**Comment by skprabhanjan** [comment]
> @skprabhanjan In your PR, move the `replace` call into `engine.parse`. That way it just happens automatically for all callers

@mjbvz , I realized this and updated the PR.
Please check now :)
