### ISSUE TITLE
Allow to undo/redo edits across multiple files

### ISSUE THREAD

**Issue by lukehoban** [microsoft/vscode#638]
When you do a rename operation that makes edits in multiple files, undo does not correctly undo the edits in files other than the active document.

``` typescript
// In a.ts
export function foo() {}

// In b.ts
import { foo }  from './a'
foo();
```

Rename from the usage of `foo()` to `foo3`.  Then undo.  The code now reports errors on the import because the definition in `a.ts` is still `foo3`.

I believe this affects any extension which provides a `WorkspaceEdit` crossing multiple files.

**Comment by jrieken** [comment]
Yeah, we never got around doing that...

**Comment by jrieken** [comment]
@alexandrudima pretty please ;-)

**Comment by prmichaelsen** [comment]
I agree this would be nice to have :)

**Comment by backspaces** [comment]
I just got bit by this: did a global search, 96 results in 6 files. This was the first day using vscode.

In the file explorer, there was an odd icon that I thought was to expand/contract the results in one of the 6 files. So I used that a few times just checking out how vscode worked.

Imagine my surprise when I searched again for the same word and got no results! At first I thought it was a configuration that left those files out of the subsequent searches. Then I found out it was the result of "replacing" the search response with a blank replace field! I.e. deleting the search word.

Then I found it was not undo-able! And no warning like if I had tried to do a replace in all 6 files.

Luckily I had thought to copy over a folder to test vscode, so no data lost. Whew. I also use Dropbox which would also have let me restore the files. But this seems to be both a questionable UI/UX, and a serious design flaw.

The editor I used before (atom) did not have an option to replace only in the given file.

I would at least offer a pop-up when doing an irrevertible action.

Is there a setting I could use to make sure I don't inadvertently fall prey to this if I *do* chose to continue on with vscode?

**Comment by backspaces** [comment]
Edit: I just noticed this only happens if I click on the search field's arrow icon exposing the Replace field. So a vanilla search is safe, but if you drop down the replace field, the odd icon appears that performs the replace in the given file.

Search only:
![snap 04 21 18-15 57 05](https://user-images.githubusercontent.com/124366/39089109-e9da508a-457c-11e8-9226-fc8a79ccc70f.jpg)

Replace exposed:
![snap 04 21 18-15 57 37](https://user-images.githubusercontent.com/124366/39089115-f86ccf42-457c-11e8-9d01-e91709604adb.jpg)

Clicking the small square icon to the left of the X will replace all within that file.

**Comment by backspaces** [comment]
Here's a possible UX change:
- First, make the small icon for replacing in the file a bit more obvious, clearer that it is a replace all in file.
- Second, when it is clicked, change to the file's editor so that the replacement is obviously done there.

.. or simply use a "are you sure" dialog to replace all in that file.

**Comment by jabacchetta** [comment]
Agreed on this. VSCode simply can not be used for large refactors as is. I have to open up WebStorm (which will undo _everything_ from that refactor command).

**Comment by alexdima** [comment]
This has been implemented for workspace edits, i.e. rename across files -- test plan item - #91248
