### ISSUE TITLE
Context menu offers 'Add Inline Breakpoint' and 'Run to Cursor' on document whose language does not contribute breakpoints

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#63811]
- VSCode Version: 1.29.1 and 1.30.0-insider
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Use a debugger extension whose package.json that is contributes breakpoints only for language X.
2. Open a document that VSCode treats as language Y.
3. Right-click on that document and observe context menu inappropriately offers 'Add Inline Breakpoint' and 'Run to Cursor'

**Comment by isidorn** [comment]
Yes I acknowledge this.
But only when you are debugging. In order to solve this we would need a context key which would be set to true when a file that supports debug breakpoints is opened.
Code pointer https://github.com/Microsoft/vscode/blob/d3e7f797ad16ce492a2ea5d4f28703e8b557281b/src/vs/workbench/parts/debug/browser/debugEditorActions.ts#L306

`DebugConfigurationManager` would be the one to set it.

I do not think this is a big limiation, thus I would not tackle it yet.

**Comment by gjsjohnmurray** [comment]
Fair enough. Thanks for doing the initial investigation.
