### ISSUE TITLE
Unable to attach to lsp server when debugging extension

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#63832]
Issue Type: <b>Bug</b>

This started relatively recently and only affects the insiders builds, but I can no longer attach to my lsp server when debugging my extension. When I try the attach just times out. If I switch back to the stable build (1.29.1) everything works fine.

![image](https://user-images.githubusercontent.com/641685/49114958-7ac3b680-f267-11e8-8a50-086bede0d0e1.png)

Unfortunately the project is currently closed-source, so I can't provide a good reproducible case. Let me know if I can provide any other details.

/cc @isidorn 

VS Code version: Code - Insiders 1.30.0-insider (456e8e64beb2dceac66743959f6802b66e18e300, 2018-11-26T11:05:14.406Z)
OS version: Windows_NT x64 10.0.18282

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (16.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by roblourens** [comment]
Most likely the lsp server did not start in debug mode. Can you get anything if you open `localhost:6009` in a browser?

**Comment by eamodio** [comment]
Hrm, I don't think that is the case. This is the same workflow as I've been using for months and using exactly the same code and setup prior to a week or so ago this all worked fine. Also if I switch to the 1.29.1 running against the exact same workspace, build, etc it all works fine.

**Comment by roblourens** [comment]
I can't repro it with https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-sample, can you? Can't think of anything that changed on my end.

**Comment by eamodio** [comment]
I can repro with that repo too. Here is what I see in the Debug Output:

![image](https://user-images.githubusercontent.com/641685/49120880-82418a80-f27c-11e8-8e7d-e43695e214e0.png)

Again this works fine in 1.29.1. I am also on Windows 10

**Comment by eamodio** [comment]
This is what I see in the browser with 1.30
![image](https://user-images.githubusercontent.com/641685/49121263-d5680d00-f27d-11e8-9790-ce36c512f23f.png)

With 1.29.1 I get
![image](https://user-images.githubusercontent.com/641685/49121302-fa5c8000-f27d-11e8-9ff8-b85b831f4bc7.png)

**Comment by roblourens** [comment]
You're sure your extension is being activated? Can you tell that the server process actually started? Can you find it in Task Manager and verify that its command line args contain the debug attribute?

**Comment by eamodio** [comment]
Yup it definitely works and is loaded

**Comment by roblourens** [comment]
@dbaeumer any ideas here?

**Comment by eamodio** [comment]
Here's using 1.30 (fails)
![image](https://user-images.githubusercontent.com/641685/49124167-5d074900-f289-11e8-9bf2-06866dc0b76b.png)

Here's using 1.29.1 (works)
![image](https://user-images.githubusercontent.com/641685/49124231-9b9d0380-f289-11e8-85ff-dd696aaa81fe.png)

**Comment by dbaeumer** [comment]
@roblourens no, not really since it works with 1.29.1 @eamodio can you connect using chrome ?

**Comment by eamodio** [comment]
@dbaeumer Differently than above? https://github.com/Microsoft/vscode/issues/63832#issuecomment-442276445

**Comment by eamodio** [comment]
@roblourens the command line (screenshots above) shows the process being run exactly the same in both 1.30 and 1.29

**Comment by eamodio** [comment]
FYI, I tried this on my laptop (Windows 10 as well) and I am seeing exactly the same behavior -- 1.30 won't attach, but 1.29.1 will

**Comment by eamodio** [comment]
I changed the port to `6019` and still see the same

**Comment by eamodio** [comment]
@roblourens @dbaeumer 
Figured it out! It was caused by VS Live Share! If I disable that, everything works fine. I am running running Live Share in 1.29.1 too, but there must be some incompatibility between Live Share and 1.30.

**Comment by roblourens** [comment]
So does `http://localhost:port/json` return something before protocol detection, but not after?

I remember a similar issue with attaching to electron processes but it went away a long time ago with an electron update.

Maybe we can try to do protocol detection by checking that URL first (assuming 'inspector') instead of opening a socket. That seems safer.

@eamodio if this is the case you should be able to work around it by adding `"protocol": "inspector"`

**Comment by weinand** [comment]
@roblourens When debugging `detectProtocolForAttach` in node-debug's `protocolDetection.ts` the problem does not occur...

BTW, here are repro steps:
- Open VS Code’s LSP Sample: https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-sample
- `npm install` from the LSP Sample directory
- Set workspace setting `debug.extensionHostDebugAdapter` to true
- Launch Client
- Now “Attach server”

**Comment by roblourens** [comment]
I'm confused, the LSP sample seems to be not working for me. I run it and it activates but I never see the diagnostics or completions that it says I should see...

**Comment by weinand** [comment]
Heureka, I found the issue:

- the LSP client library (used in the sample) launches the LSP server process only in debug mode if the node.js process (the EH) was started in debug mode. For this the LSP client library checks the `process.execArgv` for the existence of "--inspect" arguments.
- the "Attach to server" failed because the LSP server was not started in debug mode because `process.execArgv` contains no "--inspect" argument (although the EH node.js process was started  with an "--inspect" argument). So some code in the EH removed the "--inspect" arguments before the LSP client library had a chance to find those arguments.
- the only code in VS Code that removes "--inspect" arguments is controlled by an env var "VSCODE_PREVENT_FOREIGN_INSPECT". 
- Since this variable is only set in the EH, this explains why the problem only occurs if the DA runs in the EH: in this case "VSCODE_PREVENT_FOREIGN_INSPECT" is true and inherited to the DA which eventually launches another instance of VS Code as the debug target. And in that VS Code instance the "VSCODE_PREVENT_FOREIGN_INSPECT" variable makes the debug check in the LSP client library fail.

Consequences: 
- "VSCODE_PREVENT_FOREIGN_INSPECT" is another variable that must not leak to programs launched from VS Code. VS Code debugging now removes the env var before launching a DA. The integrated terminal probably needs to do the same.
- we need **robust** extension API for determining if in "debug mode. Looking at `process.execArgv` is not a robust solution (as this issue has shown).  

/cc @dbaeumer @alexandrudima @Tyriar @jrieken
