### ISSUE TITLE
Toggle menu bar problem.

### ISSUE THREAD

**Issue by OpenWaygate** [Microsoft/vscode#63833]
- VSCode Version: 1.30.0 insider
- OS Version: win 10 enterprise insider preview, build 18282

Steps to Reproduce:

1. View -> Appearance -> Toggle menu bar  only make text in this bar disappear, but the bar itself remains.
2. I have tried in settings file about window.menuBarVisibility and no difference made.
This is different with sublime which will give the editor an extra line.

![1](https://user-images.githubusercontent.com/27287694/49065179-31b83600-f258-11e8-8d84-fd13d6b0ef44.gif)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by sbatten** [comment]
@OpenWaygate The menu bar in VS Code is already inline with the title bar giving you that extra line. Toggling the menu bar does as intended, remove it from view. The title bar should not be hidden just because the menu bar is hidden. If you want even more editor space, you can try full screen mode (F11) which removes the title bar and menu bar by default.

**Comment by feluxe** [comment]
I had the same issue using `i3wm`. In order to fix it, I had to go into `Settings` and search for `window.titleBarStyle` and set it to `native`. Just in case anyone runs into the same issue after upgrading VSCode.
