### ISSUE TITLE
Have gobal setting to disable all task providers.

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#63841]
See https://github.com/Microsoft/vscode/issues/32467#issuecomment-441984883 why.

**Comment by alexr00** [comment]
Setting name: `task.autoDetect`. It's a boolean.

**Comment by Tyriar** [comment]
@alexr00 does this replace/supercede `gulp.autoDetect`? The type is inconsistent (`'off' | 'on'`)?

**Comment by connor4312** [comment]
@Tyriar Looks like this does, which matches what I'd expect as a user.

|                    |  task.autoDetect true  | task.autoDetect false |
|--------------------|:----------------------:|:---------------------:|
|  gulp.autoDetect on | gulp tasks, other tasks |        no tasks       |
| gulp.autoDetect off |       other tasks      |        no tasks       |

However, it is odd that we use true/false for this and on/off for others.

![image](https://user-images.githubusercontent.com/2230985/67815583-94b3dd80-fa64-11e9-92b7-c55357e8af61.png)

**Comment by alexr00** [comment]
`task.autoDetect` does supersede the individual extension settings. To be more consistent I can change it to `on` `off`.

**Comment by deitry** [comment]
Today I found that tasks from my [extension](https://marketplace.visualstudio.com/items?itemName=deitry.colcon-helper) suddenly gone missing. I thought that there is some break in tasks API and spent more that hour trying to realize why `provideTasks()` is not called anymore. And then I found `"task.autoDetect": "off",` in my user config.

I guess there was forcing push of this option into config in order to replace `true/false` with `"on"/"off"`, but for some reason it set `"off"` when previously there was no such setting at all.

The main question - why today? Didn't noticed if there was Code update.
---
Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:30.162Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-36-generic

**Comment by alexr00** [comment]
@deitry the default of `task.autoDetect` is `on`, so this is very strange. We didn't just push an update, so I'm guessing you accidentally added that setting to your user config. We show a notification now with "The {0} task provider is slow. The extension that provides {0} tasks may provide a setting to disable it, or you can disable all tasks providers" when you have a slow task provider, and one of the options is "Disable All", which would add this setting. Is it possible you click that when the notification came up?

If you like `true/false` for your extension's setting, feel free to keep it. It has no impact on this.

**Comment by deitry** [comment]
Thank you for details on this.
Don't remember if I pushed on some "Disable" button though this is possible. I will assume that I did it by accident.
