### ISSUE TITLE
Support pinning extension version when installed from CLI

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#63903]
Follow up item from https://github.com/Microsoft/vscode/issues/12764

Do not trigger auto updates when a specific version of extension is installed from CLI

**Comment by sandy081** [comment]
This depends on availability of Storage Service in the cli process. @bpasero Let me know if it is feasible otherwise I would close it as a technical limitation.

**Comment by bpasero** [comment]
@sandy081 doable, see:

// Create
[`services.set(IStorageMainService, new SyncDescriptor(StorageMainService));`](https://github.com/Microsoft/vscode/blob/763ae09/src/vs/code/electron-main/app.ts#L441)

// Init
[`this.storageMainService.initialize()`](https://github.com/Microsoft/vscode/blob/763ae09/src/vs/platform/storage/node/storageIpc.ts#L49)

// Close
[`this.lifecycleService.onWillShutdown(e => e.join(storageMainService.close()));`](https://github.com/Microsoft/vscode/blob/763ae09/src/vs/code/electron-main/app.ts#L473)

**Comment by bpasero** [comment]
If main is already running there is a small chance that you see an error when reading items because the DB is in use. I assume you are not writing values right?

**Comment by sandy081** [comment]
I have to write into storage to ignore auto updating an extension.

**Comment by bpasero** [comment]
@sandy081 got it. In that case I would suggest to:
* write into storage if CLI is the only process running
* otherwise ask the main process to do that

Reading should be fine from the CLI in either cases.

**Comment by sandy081** [comment]
Cool, Is there a way to check if cli is the only process running?

**Comment by bpasero** [comment]
@sandy081 maybe @joaomoreno knows

**Comment by joaomoreno** [comment]
When main starts up, the [first thing](https://github.com/Microsoft/vscode/blob/3385ec73419138b589c58ba27da4a7b2cd6bb156/src/vs/code/electron-main/main.ts#L45) it tries to [create a socket](https://github.com/Microsoft/vscode/blob/3385ec73419138b589c58ba27da4a7b2cd6bb156/src/vs/code/electron-main/main.ts#L70) for IPC. If it fails with `EADDRINUSE`, it means another main is already running, so it tries to [connect to the existing main](https://github.com/Microsoft/vscode/blob/3385ec73419138b589c58ba27da4a7b2cd6bb156/src/vs/code/electron-main/main.ts#L113) instance. This is how we make sure only one main runs, yet follow up mains send argv to that initial instance and we're able to open files on that initial instance.

CLI needs to join in on this dance. It should try to connect to that IPC channel. If successful, it should just tell that main what it should do. Else, it should do it itself, as quickly as possible.

**Comment by Falconne** [comment]
It seems that now, even if you install a specific older version via the GUI with "Install Another Version ...", VS Code will immediately auto update the extension to the latest version after a reload. Based on #12764 I assume this is a regression.

I noticed this when I tried to rollback the PowerShell extension as the latest version broke auto-formatting.

I don't know if I should open a new issue for that as this functionality seems to be universally broken now and not just CLI specific, but figured I'd comment here first.

**Comment by sandy081** [comment]
@Falconne Yeah it was broken and fixed it in insiders.

**Comment by WhisperingChaos** [comment]
At this time, I can't provide feedback regarding the design of this mechanism, as there's little mentioned here that discusses its implementation.  It seems the solution is limited to the CLI?  If so, why wouldn't other extension importing interfaces, like ```code```'s GUI also benefit from it? 

Adding "new" features should be considered within a broader context to better ensure feature coherence.  Feature coherence simplifies an end user's experience by eliminating point solutions.  A point solution is an individually crafted implementation that satisfies a specific context.  It almost always requires an end user understand its specific context in order to properly apply it.  Striving for feature coherence should reinforce "public" abstractions so a user need specify a desired outcome using them, instead of having to understand technology specific implementation concepts.  For example, why should an end user need know about the ```extensions``` array embedded in [devcontainer.json](https://code.visualstudio.com/docs/remote/containers#_adding-an-extension-to-devcontainerjson)?  Please note, this ```extensions``` array is necessary to properly configure the container, however, I would suggest that an end user wouldn't know this field existed let alone need to update it. 

Given the various feature request discussions concerning extension versioning, one could suggest designing a declarative means to specify a policy/constraint that governs ```code```'s installation state - something akin to Chief/Puppet.  In this situation, one could write a policy statement to enforce the loading of a specific extension version and prevent its update regardless of the mechanism used to install it.

**Comment by lovette** [comment]
I'm surprised this issue doesn't have more activity. I'm running into a [related issue today](https://github.com/microsoft/vscode-python/discussions/18822). 

The latest ms-python extension no longer supports Python 2.7 so I need to ensure an older version of the extension is installed when I attach to some remote containers. As it stands, Code installs the latest Python extension (as well as the Jupyter extension, which I never use and cannot find a way to disable.) I then have to downgrade ms-python, uninstall ms-toolsai.jupyter and relaunch the connection. (At this point a `node` process more often than not goes ballistic and eats up all the CPU until the container itself is restarted.) I wish I could simply include `ms-python.python-2022.2.1924087327` in the `extensions` list of the named container settings .json.

(Note that I'm using Remote-SSH to connect to a remote host then using Remote-Containers to attach to containers on that host. It is lost on me if/how a `devcontainer.json` comes into play here.)

**Comment by twodrops** [comment]
This issue is really imporant for us as well. We have a safety critical development environment where we baseline our tools and roll it our as Docker Image + devcontainer.json. Because of this bug, the extensions are automatically updated on the user side. [This problem](https://github.com/microsoft/vscode-remote-release/issues/3253#issuecomment-652279337) mentioned by @lawrencegripper describes our problem clearly. 
The problem becomes more severe when the extensions have two parts, an extension and a python based backend for it (like a language server). The frontend part of the extension easily runs out of sync because of the auto-update feature. We do not want to let users install the backend manually with a notification, as it can, for example, cause a lot of `pip` issues/conflicts.

**Comment by ras-relativity** [comment]
Dealing with this with omnisharp/C# extension. 

The team needs v1.23.16, but it installs the latest (currently v1.24.4) on container startup. To fix:
1. Go to the C# extension in extension tab
2. Click the dropdown next to Uninstall Button -> Install another version -> v1.23.16
3. Click the Reload Required button

We use a devcontainer.json to install the extension, would like to put this, but it has no effect:
`  "extensions": [
    "ms-dotnettools.csharp@1.23.16",
  ],`

**Comment by jankap** [comment]
This is crucial, anything we can do?

**Comment by temparus** [comment]
> We use a devcontainer.json to install the extension, would like to put this, but it has no effect:
> ` "extensions": [ "ms-dotnettools.csharp@1.23.16", ],`

We had the same issue lately. We got it working in VSCode version 1.68.1 with the following config in `devcontainer.json`:

```json
{
    "settings": {
        "extensions.autoUpdate": false,
        "extensions.autoCheckUpdates": false
    },
    "extensions": [
        "ms-dotnettools.csharp@1.23.16"
    ]
}
```

**Comment by twodrops** [comment]
@temparus Are you really sure? It does not work for me with 1.68.1 either.

During the first startup, it installs the specifed extension, but then it autoupdates itself.
Btw, I am testing it from a devcontainer.json. Don't know if this is now only a bug within devcontainer.json.

**Comment by temparus** [comment]
@twodrops you're right. It only works properly on the first start of the devcontainer. So, when the container already exists when opening the project in the devcontainer, the auto-update kicks in.

As a workaround, you can add an `initializeCommand` in the `devcontainer.json` file to remove the existing container prior to the start of the devcontainer:

```json
{
    "initializeCommand": "docker rm <devcontainer-name>"
}
```

This enforces that the container is rebuilt on startup. Building the actual container should not take long because the images and build layers are already in the cache.

**Comment by Nitschi** [comment]
This is critical for us because we need to work with a Python2.7 Codebase and both the Python and Pylance Extension dropped support.

Manually installing the older version is becoming a real pain...

**Comment by rafaelkallis** [comment]
We are facing a similar situation where our codebase uses dotnet 3.1 but the official C# extension (https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) does not support 3.1 anymore in their latest relase, hence an older extension version has to be used. (1.25.0 -> 1.24.4)

**Comment by vlockhead** [comment]
I am facing the same issue here, it would be nice to be able to specify the extension version in the devcontainer.json the point of running vscode in a docker is to have a known environment 

Having to reload re-install the extension manually each time is a pain
