### ISSUE TITLE
Debug: The stop/continue all model breaks the debug adapter for Firefox

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#6400]
- VSCode Version: 1.1.1

See: https://github.com/Microsoft/vscode/issues/6304#issuecomment-219371477

**Comment by weinand** [comment]
@isidorn I've added an attribute `allThreadsContinued` to the `ContinueResponse`. Please interpret it as follows:
- if it is missing or if its value is true, implement the old VS Code 1.0 behaviour: show all threads as running. 
- if the value is false show only the thread with the specified thread id as running.

@hbenl and @felixfbecker since you both need the single thread behaviour I suggest that you start to return the `allThreadsContinued: false` from the implementation of your continueRequest. VS Code 1.2.0 will be the first version that makes use of it.

@felixfbecker please let us know when we can remove our php workaround.

**Comment by weinand** [comment]
the fix: https://github.com/Microsoft/vscode-debugadapter-node/commit/6e704e8fef40f0050ff8559d00873c3b1e48ba11

**Comment by hbenl** [comment]
So what about the StoppedEvent - does VS Code assume that only a single thread has stopped (note that the threadId in this event is not optional)? If so, maybe making the threadId optional would make sense (otherwise debug adapters implementing the stop/continue all model would have to send one event per thread).

**Comment by weinand** [comment]
@hbenl so far we have identified two use cases for the StoppedEvent:

- if `allThreadsStopped` is false (or if this attribute is missing) the thread with id `threadId` has stopped and all other threads continue to run.
- if `allThreadsStopped` is true all threads have stopped and the thread with id `threadId` is the one in 'focus', that is the UI will auto expand it.

Yes, in the second case we could make `threadId` optional.
In the 'all threads stopped' model there is no need to send StoppedEvents for every thread. Just set `allThreadsStopped` to true instead.

**Comment by hbenl** [comment]
OK, I had missed the addition of the `allThreadsStopped` attribute. Thanks for clarifying.

**Comment by felixfbecker** [comment]
@weinand implemented `allThreadsStopped` in 1.9.0
