### ISSUE TITLE
Lint errors not updating until building and still show after fixing

### ISSUE THREAD

**Issue by vsccarl** [Microsoft/vscode#6404]
- VSCode Version: 1.1.0-alpha
- OS Version: Windows 10

Steps to Reproduce:

Using the [smoke test repo](https://github.com/Microsoft/vscode-smoketest-express)
1. Open routes/index.js (Observe no errors are reported)
2. Run build Ctrl+Shift+B
3. Observe there are now 6 errors shown
4. Delete the semi colon after router on line 9
5. Also fix the error for function on line 5 (add a space after function) 

It is still showing the lint error under router even though it has been fixed. Deleting the extra semi-colons elsewhere updates since the error is under them. The error under function is still visible until re-build also.

Should the error for semi-colons at the end of words/defns be moved to under the semi-colon instead? 

![nolintupdate](https://cloud.githubusercontent.com/assets/12900364/15304556/db11627c-1b72-11e6-863b-c314c4bffc13.gif)

**Comment by dbaeumer** [comment]
This is expected behavior. We have two different ways of providing errors:

- build errors: they only disappear when running a new build. In the above example trigger Ctrl+Shift+B again (after saving) should remove the errors
- reconcile errors: the come and go on typing. The are typically produced by language services like TS or linters.
