### ISSUE TITLE
Intelisense is too superfluous

### ISSUE THREAD

**Issue by raxim1** [Microsoft/vscode#64085]
- VSCode Version: 1.29.1
- OS Version: ubuntu 18.04.1

Steps to Reproduce:

1. The auto import has been improved a lot, but it's using absolute URLs like
import {myComponent} from "src/lib", (it should have been ../../../lib or something)
which technically kills the ng serve while automatically redeploying the changes
2. Sometimes when I type something, automatically complete it, but it was not the purpose. (it's sometimes annoying in the chrome browser bar also, as I need to delete back half of the URL by hand to get the main page of the website)
3) ctrl+shift+r command removes the auto import but does not reformat completely (does not remove superfluous empty lines, what I'm used to it in eclipse for example)
4) ctrl+space does not offer alternatives in a window when I have started a word, but moving mouse in a word shows the popup window, even if I would like to click the word inside to change one letter - it's hiding, so i'm unable to click inside the word. (in previous versions it was working differently)

It's a nice environment, but pls. replace a little bit the behaviour to make it better. At the moment it was going to a too much direction.

**Comment by mjbvz** [comment]
Using this issue to track 1. Please open seperate issues to track the other 3. 

Try setting `"typescript.preferences.importModuleSpecifier": "relative"` or `"javascript.preferences.importModuleSpecifier": "relative"`. This should make auto imports always use relative paths. Otherwise, it will use the `baseUrl`  setting for absolute when it can
