### ISSUE TITLE
Rows in the debug console can be selected/hovered

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64104]
![image](https://user-images.githubusercontent.com/323878/49323697-24a77b00-f4d4-11e8-80fc-fdc1cdf504f2.png)

- Have data in the debug console
- Click a row
- See the selection color

I think this is supposed to be disabled

**Comment by isidorn** [comment]
Thanks for filling, but fixed in latest.
@roblourens let us know if you hit any other issues. Also consider assigning yourself to https://github.com/Microsoft/vscode/issues/64003

**Comment by isidorn** [comment]
The highlight we left inentionally since you can interact with elements that are expandable.
Apart from that the highlight makes it easier to distnguish between different elements (i know people wanted some grouping).

Closing this for now and if we get more complaints I am open to changing that. Or if you feel strongly about it let me know.

fyi @joaomoreno

**Comment by joaomoreno** [comment]
@isidorn Yeah, if you hear more about the hover being a nuisance, let's just disable it.
