### ISSUE TITLE
Snippet Option To Auto Execute on Type

### ISSUE THREAD

**Issue by Astrantia** [microsoft/vscode#64135]
Hi. When adding new snippets, I want to see an option that when checked, will automatically expand the snippet for you. Now I know this can be done by creating a snippet and then binding a key to that snippet command. However, this is limiting since you can't type a string and get it auto expanded. Also, it's a lot more work.

For example when I type `class` I don't want to click tab or enter or choose the snippet suggestion from the widget. I want it to automatically expand to the defined snippet.

------------------------------------------------------------

### This is the closest vscode is to achieving this, however as I said "key" is very limited. What about another field `"triggerOnType": true`? 

```
Assign keybindings to snippets
You can create custom keybindings to insert specific snippets. Open keybindings.json (Preferences: Open Keyboard Shortcuts File), which defines all your keybindings, and add a keybinding passing "snippet" as an extra argumen
{
  "key": "cmd+k 1",
  "command": "editor.action.insertSnippet",
  "when": "editorTextFocus",
  "args": {
    "snippet": "console.log($1)$0"
  }
}
```

**Comment by Astrantia** [comment]
I am honestly very surprised no issue has been opened for this so far. This is how most of VIM snippets work. For example in UltiSnips you type a snippet and it auto-expands without clicking anything. I don't see any disadvantages to this if an option is offered to enable/disable it per snippet. Believe it or not, this increases typing fast by a big margin. @jrieken Can this be please implemented?

**Comment by Astrantia** [comment]
@jrieken Is this particularly difficult to implement? Considering vscode milestones and the way things are now do you think this will make in the releases soon? If not, I'll start learning typescript and vscode to add this on my own 😬 
Again it surprises me a lot no one has asked for this feature beforehand, but I believe this will be a very welcome addition if you do add it.

**Comment by jrieken** [comment]
> Considering vscode milestones and the way things are now do you think this will make in the releases soon?

I don't think so TBH. It's the first time this request comes up and we would wait for some more up votes here. Having said this, you can implement this as extension or make yourself familiar with our completion infrastructure but that's not so simple...

**Comment by Astrantia** [comment]
@jrieken thanks for honesty
@fabiospampinato I think this is the ideal candidate for your 34th extension 😅 😅 😅

**Comment by fabiospampinato** [comment]
@Astrantia 😄 Sorry but this is not something I would personally use.

**Comment by tecosaur** [comment]
@jrieken To add a (late) voice; I too am rather keen on this. Re: upvotes / user attention — I think this is an area where because this is by no means a 'life or death' type issue, unlike many others (depending on use case) very few feel like complaining. I also feel there's an element of "you can't miss what you've never had". However, I imagine to a fair few people it would provide a bit of utility that would be appreciated.

For example, inspired by [castel.dev: Lectures notes using LaTeX and Vim](https://castel.dev/post/lecture-notes-1/) I'm now pining for the ability to type `([A-z])(\d)` and have it automaticly replaced with `$1_$2` this may seem expecialy minor. However when considering that (after checking my files) over the past few months I've written ~4000 subscripts in latex files using vscode, even if only half a second is saved — the time adds up quickly.

**Comment by rianneogi** [comment]
This issue is the only thing that is stopping me from using VSCode for latex. Typing in Vim with UltiSnips is just so much faster. I couldn't even find any extension that provides this functionality.

**Comment by zardoy** [comment]
I know a lot of folks that actually wanted this in the past, but they didn't know they need to upvote some issue on GitHub (and me either). Since then we're using [extension](https://github.com/zardoy/vscode-better-snippets) that support typing snippets, without using builtin snippets completely. Trust me, we you can just type `cb` to expand it to `($1) => $2` anywhere in TS/JS file it'd save a lot of your time.
