### ISSUE TITLE
autosave when i open a new tab

### ISSUE THREAD

**Issue by WHITE-ILMARE** [Microsoft/vscode#64174]
this issue happens after i update vscode last time.
it autosave the whole project when opening a new file of the project and i can't stop it via configuration settings.(i have already turn the autosave setting off)
i find this problem because i'm using vue-cli3 to develop, when i open a new file, the whole project will restart or hot update.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by WHITE-ILMARE** [comment]
hi, i just tried your method but it didn't make any difference(In fact, i have searched issues about this situation a few days ago and tried that command), the problem still exists without any extensions.
Do u need more info about the issue? Is there any other methods that i can try? Here's my vscode info:
![image](https://user-images.githubusercontent.com/24714274/49373067-b662f280-f737-11e8-9299-980b4d29d2ae.png)

**Comment by bpasero** [comment]
@WHITE-ILMARE so you say that the nodemon file watcher detects a change as soon as you open a file?

**Comment by WHITE-ILMARE** [comment]
Yes.
And opening a file which is not being watched by nodemon will trigger webpack's hot update as well.

**Comment by bpasero** [comment]
That is weird indeed. 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by WHITE-ILMARE** [comment]
Thanks...
