### ISSUE TITLE
Menu spends too much time debouncing onDidChangeContext

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64170]
- Start perf tool, do just about anything
- See that lots of time is spent in setTimeout/clearTimeout via debounceEvent

Example

- Have editor open, sidebar hidden
- Press cmd+shift+f
- Quite a lot of time is spent debouncing the event

This seems to be from menu.ts, every menu instance has its own listener. Can this be put in some global spot instead of duplicating it? I think the problem is that setTimeout/clearTimeout are expensive.

The orange fringe on all these stacks is setTimeout/clearTimeout:
![image](https://user-images.githubusercontent.com/323878/49348173-c35ce480-f658-11e8-9fab-7b36120a0de3.png)

[Profile-20181202T173310.json.txt](https://github.com/Microsoft/vscode/files/2637719/Profile-20181202T173310.json.txt)

**Comment by sbatten** [comment]
@roblourens which `menu.ts` are you referring to?

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/blob/master/src/vs/platform/actions/common/menu.ts#L39

**Comment by jrieken** [comment]
Yeah, we did move the debouncing from the context key service into each menu. That made it N instead of 1 event. There are cases that require sync-context key events, that's why. What I am not sure about is if the profiler shows correct information. @alexandrudima and I have seen this before and our assumption was that performance tab put stronger emphasis on these calls because you don't see the same when measuring with a wall-clock...

**Comment by alexandrudima** [comment]
Yeah, AFAICT the Performance tab is astronomically inflating setTimeout times, I don't know why, perhaps to capture stack traces or something. The JavaScript Profiler tab is IMHO much more trustworthy.

**Comment by roblourens** [comment]
Wow, I never knew that. This stuff doesn't even show up on the JS Profiler chart. I've gone out of my way to avoid setTimeout before...
