### ISSUE TITLE
Version 0.9 and higher is super slow while opening editor, project or files

### ISSUE THREAD

**Issue by wUFr** [Microsoft/vscode#642]
After update to 0.9.0 my VSC got super slow while opening editor, projects or files takes 10 or more seconds.

Could be this machine related as i dont have any problems on another one. Tried to open editor after windows startup without any extra programs opened, still slow. Win 10 64bit

**Comment by bpasero** [comment]
@wUFr another thought I had was if - once VS Code is up and running - you could see if reloading the application is also slow. For that you can just trigger View | Command Palette | Reload Window.

If that action turns out to be as slow, we have a chance to run a profiler to see where the time is spent. For that - before reloading - run Help | Toggle Developer Tools, click Profiles, then press the Start button and run the reload action. After that, press the Stop button. You should get a list of function calls and their timings. You can export this report from the little "Save" button next to "Profile 1" on the left.

![image](https://cloud.githubusercontent.com/assets/900690/11419786/f416ec72-9429-11e5-8f5c-b4267c954076.png)

**Comment by bpasero** [comment]
This is #335

**Comment by wUFr** [comment]
When i press "record" button in console, it freezes editor. Cant edit file or open command input; Can hover on top bad or stop recording, but that wont fix it + unable to close editor normal way, have to kill it in processes.

If you want i can record whole problem and put it as private video on YT

**Comment by bpasero** [comment]
Thanks I think we got it and will release soon.

**Comment by wUFr** [comment]
ok, let me know when you release it :+1:

**Comment by bpasero** [comment]
To people hitting this issue: We might not be able to release a new version until next week. **But there is a workaround**: 

If you can start Code eventually:
* select File | Open Recent | Clear Items
* restart and things should be fast again

If you cannot start Code:
* close Code
* locate storage.json (see https://code.visualstudio.com/Docs/supporting/FAQ#_how-do-i-opt-out-of-vs-code-autoupdates for how to find it)
* delete the file or rename it
* start Code

Sorry for the trouble :heart:
