### ISSUE TITLE
Select options remain open when navigating away from settings editor

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode#64265]
Issue Type: <b>Bug</b>

1. Open the settings editor
2. Focus a setting that has a dropdown so that the options are displayed
3. Switch editors

The dropdown remains open:
![screen shot 2018-12-03 at 3 59 34 pm](https://user-images.githubusercontent.com/3672607/49409221-74748500-f714-11e8-82cd-2d70091aa127.png)

Not sure if this is an issue with the select itself, or the settings editor.

VS Code version: Code - Insiders 1.30.0-insider (9e62a05bc7c5dbb74d165e06f7c3a5f3c7549096, 2018-12-03T06:12:08.874Z)
OS version: Darwin x64 18.0.0

**Comment by cleidigh** [comment]
@roblourens  
Ha, I was afraid this would occur.
@joaomoreno set the _sticky flag that Jackson added for debugging.  I was going to ask him if this was intentional.  @joaomoreno was his left as 'true' by mistake when you're doing some mouse work for list?

I will verify if this is the case and fix unless requested otherwise...

**Comment by roblourens** [comment]
Good catch, it looks like a mistake, I'll revert it so it can get into tomorrow's build. Let me know if that's not the case @joaomoreno.

**Comment by roblourens** [comment]
Actually looks like you are on it @cleidigh, go ahead if you want to create a PR.

**Comment by cleidigh** [comment]
Fixed with, #64271

**Comment by cleidigh** [comment]
@roblourens - you have to merge, I'm not allowed :-(
