### ISSUE TITLE
trackpad two finger scroll ignores windows settings and is way too fast!

### ISSUE THREAD

**Issue by skn3** [microsoft/vscode#64261]
- VSCode Version: 1.29.1
- OS Version: 1803 - 17134.407

Steps to Reproduce:

1. Open a long document
2. Scroll using two fingers on bootcamp macbook trackpad

Does this issue occur when all extensions are disabled?: Yes

I am running latest available vscode on windows 10 via bootcamp. I have all updates installed. If I try and scroll any portion of vscode using two finger scroll, then the the scrolling speed is incredibly high. Vscode will scroll maybe 5-10 lines at a time. This makes it unusable because even minor movement on the trackpad can scroll like 50 - 100+ lines of code!

Changing the windows mouse wheel settings makes no difference. I currently have it set to 1.

Changing `"window.smoothScrollingWorkaround"` and `"window.titleBarStyle"` makes no difference.

The only thing that helps is changing `"editor.mouseWheelScrollSensitivity"` to `0.3`. This is not viable because then when using a mouse attached to the laptop, the scrolling is too slow. I have to continuously modify this mouse setting when switching between working at desk and working mobile.

No matter what I try I am unable to get smooth or inertial scrolling working.

I have read the other open issues and they seemed to have either been closed, "fixed" or don't apply to this issue.

**Comment by alexandrudima** [comment]
@skn3 Is scrolling "too fast" also when scrolling using Chrome in the editor at https://microsoft.github.io/monaco-editor/ ?

**Comment by skn3** [comment]
@alexandrudima Just testing this now and yes its scrolling about 6 lines at once with the smallest possible movement I can make to trigger a single "scroll".

**Comment by skn3** [comment]
Also I should add that I manually installed the recent Microsoft update to see if it was fixed. Unfortunately no. Running ver 1809.

I can confirm that vscode on the osx side runs as expected.

**Comment by alexandrudima** [comment]
@skn3 Unfortunately, `"editor.mouseWheelScrollSensitivity"` is the only workaround I can think of for now. Given you can reproduce in Chrome (VS Code is built with Chromium), I suppose any website suffers from this. If you can reproduce on Chrome and not in Edge, perhaps you can seek help at https://bugs.chromium.org/p/chromium/issues/list

**Comment by skn3** [comment]
Well it's only happening in the monaco editor. Everything else in chrome works fine. So for example scrolling a webpage utilises the windows settings and can be scrolled at a sensible rate.

**Comment by alexandrudima** [comment]
@skn3 Could you try scrolling in the following fiddle (in the yellow area). Are there major differences in the values from Chrome to Edge or Firefox? Are there major differences in the values between scrolling with the trackpad and the mouse wheel?

https://jsfiddle.net/3jqz9k1h/1/

Did you perhaps tweak your scroll sensitivity in Windows? AFAIK we don't honor that when scrolling with the mouse wheel because the event we receive tells us how much the mouse wheel scrolled without using that OS multiplier. Perhaps the touchpad mousewheel event ends up using that OS multiplier...

![image](https://user-images.githubusercontent.com/5047891/49571862-ad8e3e80-f93a-11e8-9e55-e53a884f6148.png)

**Comment by MatheusR42** [comment]
Same here

**Comment by Bryceed** [comment]
Same problem here and this keep happens in every Chromium-based instance `e.g. New MSEdge, Chrome Canary, Discord Desktop App`. 

I think this can be a compatibility problem with the Pointing Device Software and the Windows 10, because when this bug appears, some functions disappear from the touchpad software menu _like changing the virtual desktop, sliding 4 fingers to left/right_.

**Software:** ELAN Pointing Device
**Device:** Lenovo G40-70

**Comment by sebtiz13** [comment]
Same problem

Its a bug on electron ?

Driver:  ELAN pointing device
Device: Lenovo ideapad 330
OS: Windows 10

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 6.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCode-darwin-exploration.zip)
* Linux (DEB): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration_1.37.0-1564556412_amd64.deb)
* Linux (RPM): [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/code-exploration-1.37.0-1564556601.el7.x86_64.rpm)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/960208fdf9aa06e6892aa14c9c84ddd607fbeb2f/VSCodeUserSetup-x64-1.37.0-exploration.exe)
