### ISSUE TITLE
Farklı Kaydet ile kaybolan sayfa

### ISSUE THREAD

**Issue by sefaaydin** [Microsoft/vscode#64301]
Merhaba;
Html bir dosya açtım. ismi A.html olsun. üzerinde düzenleme yapıp kaydettim. ama A.html dosyasını kapatmadım. daha sonra ctrl + shift + S tuşu ile kaydetttiğim A.html dosyasının ismini B.html ile değiştirerek farklı kaydettim. Malesef eski dosyam olan A.html dosyasını kapatıp yerine yeni isimde kaydettiğim B.html dosyasını açtı. A.html dosyasındaki yaptığım düzenlemeri geri almama izin vermiyor. çünkü dosyayı kapatmış. ne yapabilirim.?

**Comment by octref** [comment]
Please use English to report issues. Thanks.

Translation seems to be:

Hello there;
I opened an html file. Let the name A.html. I have edited and saved. but I did not close the A.html file. then ctrl + shift + S key I saved the name of the. Unfortunately I closed my old file, A.html, and opened the .html file that I saved with the new name. A.html does not allow me to undo the edits I made. because he closed the file. what can I do.?

Once you close a file, you can't undo changes.

Bir dosyayı kapattığınızda, değişiklikleri geri alamazsınız.
