### ISSUE TITLE
onDidChangeConfiguration is not triggered in main process

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#64319]
Testing #64282

Windows

- Open VS Code with default options for menubar (custom and default visibility)
- Go to full screen mode
- Change the visibility to `toggle`
- Check menu toggling works 👍 
- Change menubar to `native`
- Restart VS Code
- Check menu toggling works 👍 
- Exit from full screen
- Check menu toggling works 👍 
- Change the visibility back to `default`

🐛 Menu bar is still in toggling mode

**Comment by rebornix** [comment]
What I ran into Native menu bar does not respect the visibility setting on Linux but the state is always 'Visible'.

**Comment by sbatten** [comment]
@sandy081 after investigation, this is because the listener in `window.ts` is never triggered, thus it never calls onDidChangeConfiguration. I believe this may be because of your change https://github.com/Microsoft/vscode/commit/ea771bdcd531b7e61a1cfa14b642c78b9ee5499a here which is where the menubar visibility change gets filtered out and doesn't trigger the event.

**Comment by sandy081** [comment]
I see. Will take a look.
