### ISSUE TITLE
Search viewlet selects entire search input when hidden and shown

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#64333]
Testing #64270

1. Open Search viewlet
2. Type some text in the Find input box
3. Pick up the resize sash and collapse the viewlet until hidden, then expand it until visible again

The entire Find input box input will be selected.

**Comment by roblourens** [comment]
I think this is by design. Typically when you open the search viewlet you want to start doing a search. It might feel weird in this case just because you are using the mouse. But we don't really distinguish between what causes the viewlet to be visible, like this vs `cmd+b`. Do you think it's an issue?

**Comment by joaomoreno** [comment]
Not really, just thought it'd be interesting to note. Feel free to close! :+1:

**Comment by roblourens** [comment]
After playing with it some more I want to restore focus to the right place when I toggle the sidebar with cmd+b (or use the mouse)

**Comment by roblourens** [comment]
I can't really decide how it should work and if I try to "improve" this I will just introduce a bunch of edge cases, I will leave it.
