### ISSUE TITLE
The windows has crashed when copy large file content

### ISSUE THREAD

**Issue by uselessscat** [microsoft/vscode#64472]
Information:
- Version: 1.30.0-insider (user setup)
- Commit: 85f805acf9436381b878cab5ab6c5146beec7893
- Date: 2018-12-05T06:19:36.555Z
- Electron: 2.0.12
- Chrome: 61.0.3163.100
- Node.js: 8.9.3
- V8: 6.1.534.41
- OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Open a large sql database dump (my dump has 78.861.290 bytes, not too big)
2. I tried to copy 75.841.605 characters using right click dialog (also occurs with ctrl-v)
3. A message says "The windows has crashed" (no content is in the clipboard)

If i open the file with notepad, i can copy all the content of the file to the clipboard.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
We have exploration builds that use newer version of Electron which uses newer version of Nodejs, I'm wondering if it's due to Nodejs string length limit, can you give them a try?

* macOS: [Download](https://az764295.vo.msecnd.net/exploration/45498d93166483c2eff886e28f8dab915ae382fc/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/code-exploration_1.28.0-1538127308_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/5a736c2e4904ed114fae2d5941508505f53afc66/VSCodeUserSetup-x64-1.28.0-exploration.exe)

**Comment by uselessscat** [comment]
Hi, thanks for you attention. 
I can confirm that the version you given in the links don't crashes when copy.

**Comment by alexandrudima** [comment]
This has been fixed in the meantime.
