### ISSUE TITLE
Storage migration doesn't work after creating a multiroot workspace

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#64473]
Testing https://github.com/Microsoft/vscode/issues/64142

- `code --user-data-dir /tmp/codedata`
- Open some folder
- "Add folder to workspace", add a second folder
- "Save workspace"
- Open some files in split view, move the workbench UI around
- Close vscode
- `code-insiders --user-data-dir /tmp/codedata`
- Insiders opens to the correct workspace.
- But no editors are open, "Recently Opened" is empty, the selected output channel is not persisted, sidebar state is not persisted, etc.

Am I doing something wrong? If you can't repro I can provide --verbose logs but I don't think they show anything interesting.

**Comment by roblourens** [comment]
Here's a scenario that does work, if that helps

- Open code stable with a new user-data-dir
- Open a workspace file that already exists
- Open some files, etc
- Open code insiders
- The state was migrated correctly

**Comment by bpasero** [comment]
@roblourens good catch, however I can already reproduce the missing state when opening again with Code stable. This indicates to me that the storage migration is actually broken in stable already.

Interestingly if I follow the same steps using Code Insiders everything seems to work fine. So I will close this issue assuming that the migration works better now than before. To verify, run the steps from https://github.com/Microsoft/vscode/issues/64473#issue-388024519 using code insiders instead of code stable.
