### ISSUE TITLE
Paint CJK characters with fat latin shapes in minimap

### ISSUE THREAD

**Issue by clumsykun** [microsoft/vscode#64477]
the minimap seems not the same with the file content in the detial. is it correct?

![detail](https://user-images.githubusercontent.com/30850989/49559915-6c525a80-f94b-11e8-8011-59290cc5bca3.png)
![full](https://user-images.githubusercontent.com/30850989/49559920-6fe5e180-f94b-11e8-9002-bb06e3fe5ae8.png)

- VSCode Version: 1.29.1
- OS Version: windows 10

Steps to Reproduce:

1. open a json file
2. the minimap seeming wrong

Does this issue occur when all extensions are disabled?: yes

**Comment by alexandrudima** [comment]
@clumsykun The geometry looks correct. I think you are referring to the way the CJK characters are painted. Our tiny font does not include those so we use a random character from a-z to paint those in the minimap. Unfortunately, that means there is no correlation between their shapes. Since we know CJK characters usually have a higher density, perhaps we could alternate between latin characters with higher density, like m, g, e, w...

**Comment by connor4312** [comment]
As of https://github.com/microsoft/vscode/pull/82265, we'll display the unicode replacement character � on unrenderable symbols.
