### ISSUE TITLE
"Auto Find In Selection" breaks "Find Next Selection"

### ISSUE THREAD

**Issue by adymoussa** [microsoft/vscode#64513]
- VSCode Version: 1.29.1
- OS Version: Windows 10 Pro, 64 bit, Version 10.0.17134 Build 17134

Enabling **"Auto Find In Selection"** will make **"Find Next Selection"** useless, as it will only search in the selected text. I would like to be able to select a word and invoke "Find Next Selection" to jump to the next occurence without having to disable "Auto Find In Selection".

Steps to Reproduce:

1. Set **editor.find.autoFindInSelection** to **true**
2. Select a word.
3. Invoke **"Find Next Selection"**

I expect it to jump to the next occurence.
But due to "Auto Find In Selection" the cursor will stay where it is.

Does this issue occur when all extensions are disabled?: Yes

**Comment by MZachmann** [comment]
Adding a vote for this annoying artifact. 
Using autoFindInSelection is natural and important but the world's most common action is to highlight a word and click ^F to find it. Not only does the selection button go on (which is ridiculous given that the entry in the field is the selection) but it sticks on so if you un-highlight the selection it still insists the string isn't found.

**Comment by namleasia** [comment]
Suggess: Auto Find In Selection should auto turn on only if multiline have been selected.

**Comment by rebornix** [comment]
Let's use https://github.com/microsoft/vscode/issues/27083 to track this issue, the solution will be introducing a richer `findInSelection` option.

**Comment by Spongman** [comment]
i don't think there's a need for a different `findInSelection` option.

It _never_ makes sense to 'find in selection' if the find input is initialized with the value of the selection. there's no need for an option to say 'always do something that never makes any sense', just don't do the broken thing.

visual studio proper has always done the right thing here, choosing 'current document' instead of 'selection' when doing a ctrl-f3.
