### ISSUE TITLE
Allow to filter list

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#64528]
It would be great to have an ability to filter found references.
For example:
"Hide imports" that will hide references inside of import statements and direct `require` assignments.
At this moment each file usually contain 2+ references and first one if always inside of the import statement, but it is rarely place that devs are looking for.
"Hide definition" there is separate commands "Go to/Peek Definition" and when looking for references-usages won't introduce one more.

In combination with #15 (that recalculated according to filters) this will provide proper count of usages.

**Comment by IllusionMH** [comment]
@jrieken I'm not sure that this is duplicate of mentioned issue.
#50062 is about general search/filter while this one is about adding controls for specific filters for references.

In particular references inside of import statements (basically duplicates inside one file where it will be actually used) and definitions (actually #68071 is duplicate of "Hide definition" part of this issue)

**Comment by IllusionMH** [comment]
@jrieken could you please reconsider and re-open this issue because it is not duplicate of #50062?

**Comment by jrieken** [comment]
Yes, this isn't a dupe but TBH this is far out of scope because the API doesn't define any semantics on references. Eg the editor doesn't know anything about references, they are just pointers to some line of source. The proposed API for call hierarchies (https://github.com/microsoft/vscode/issues/70231) will have this knowledge and while the first UX is peek based, there will likely be a viewlet based UX too.

**Comment by IllusionMH** [comment]
Thank you for explanation.
Just to clarify - if #70231 won't help with expected workflow I need to submit Language Service API proposal to enable more info about reference kind first?

**Comment by jrieken** [comment]
>  need to submit Language Service API proposal to enable

Yeah, that would be helpful. Something that enhances this API first: https://github.com/microsoft/vscode/blob/4c5705f4f8700672b9eaddeefc2a687a23cbedd4/src/vs/vscode.d.ts#L2718-L2731. E.g instead of returning a `Location[]` allow to return something comparable to `DocumentSymbol`. Once we have it in VS Code, we follow up with LSP. It also needs a reasonable default, e.g. all Location-only references are of some default kind and then the UIs can follow...

**Comment by IllusionMH** [comment]
@jrieken understood. Thank you again!
