### ISSUE TITLE
Consider improving the allow/disallow automatic task actions

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#64618]
With https://github.com/Microsoft/vscode/issues/64613 we introduced simple allow/disallow actions that mimic what we do for terminal shell configuration. This approach as several disadvantages:
- the actions show up on empty windows (no open folder)
- it's unclear what the current state is
- user doesn't see the tasks that are (supposed to be) running automatically

A more sophisticated QuickPick based UI could provide the user with this information.

**Comment by justingrant** [comment]
IMHO, this should be a Setting so that it's discoverable from the Settings Search UI or by looking at the settings JSON files.  I just wasted half an hour trying to find this configuration option because it was a command instead of a Setting!  See https://stackoverflow.com/questions/58866184/

**Comment by amunger** [comment]
@meganrogge - the setting description for auto is "prompt for permission for each folder", but I was never prompted. Is that because I trust the workspace?

Other than that, the setting seems to work fine, I just created the vanilla runOn: folderOpen as described in the linked SO post. Not sure if there's anything else I should be testing

**Comment by meganrogge** [comment]
Yes that's correct @amunger and yep that sounds good
