### ISSUE TITLE
Tabs and newlines are not included when pasting text from Debug Console into Word

### ISSUE THREAD

**Issue by iansan5653** [Microsoft/vscode#64628]
Version: 1.30.0-insider (user setup)
Commit: a152a5c7818a13666a5879b4450eb26a4d45fbde
Date: 2018-12-07T10:34:36.706Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Output to the Debug Console and include tabs (`\t`) or newlines (`\n`)
2. Select the output and copy it
3. Paste it into Microsoft Word. Tabs and newlines (besides the new line caused by outputting a new message) are not included.

Example:
![image](https://user-images.githubusercontent.com/2294248/49670728-9bdc9200-fa33-11e8-9eaf-007e2c0a3a84.png)

Pasting this into Word 2016 yields:
![image](https://user-images.githubusercontent.com/2294248/49670754-b1ea5280-fa33-11e8-9446-d7f4e4f91421.png)

**Comment by isidorn** [comment]
Pasting tabs and new linesworks fine for me when I paste it into vscode.
For empty lines this currently does not work, however we can not address it since the debug console is implemented using a tree.

For pasting into word issues please file an issue / report against microsoft word.
Closing as will not fix
