### ISSUE TITLE
The selected item in Suggestion Trigger is in the wrong position (offsceen)

### ISSUE THREAD

**Issue by sgon00** [Microsoft/vscode#64650]
# Versions Info

Dart-Code vscode plugin: 2.21.1
Mac OS X 10.13.6
VS Code (version 1.29.1)

```
flutter doctor -v
[✓] Flutter (Channel master, v0.11.10-pre.7, on Mac OS X 10.13.6 17G65, locale en-CN)
    • Flutter version 0.11.10-pre.7 at /Users/user/opt/flutter
    • Framework revision 57849e8285 (11 days ago), 2018-11-26 14:23:02 -0800
    • Engine revision eebc6a5895
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1
```

# Video

[vscode_dart_issue.mp4.zip](https://github.com/Microsoft/vscode/files/2659252/vscode_dart_issue.mp4.zip)

# Description

When the code snippet (open code completion) (trigger suggestion) window pops up, I can see the correct items are on the top of the window, but they are not selected at all and if I press `Down` key, the position will jump to some random selected item (offscreen). 

I first opened an issue in Dart-Code plugin at https://github.com/Dart-Code/Dart-Code/issues/1337, the member asked me to open an issue here and think this is a VSCode issue. 

Thanks a lot.

**Comment by DanTup** [comment]
@jrieken I tried searching but couldn't find another issue that describes this - I don't think the issue is related to which item is being selected (which can be controlled by the extension with `preselect` or by the user with `editor.suggestSelection`) but rather that there is a select item that is outside of the visible list of items (eg. it's scrolled away).

If there's another issue covering this, great - but if not, I think there's still a bug.
