### ISSUE TITLE
Support editor labels on non-file scheme "files"

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#64697]
Related to https://github.com/Microsoft/vscode/commit/4e3f58f2f4e81fd6ebe5a5a7da7587c9247ce9ad#diff-81002b6983f6ca938fb1efc58cd9da2f from https://github.com/Microsoft/vscode/issues/55110#issuecomment-423116701

I am trying to add a custom label to `gitlens` scheme files (to add the revision info), but it looks like labels only work for editors that are instances of `ResourceEditorInput` 

See
https://github.com/Microsoft/vscode/blob/e444eaa768a1e8bd8315f2cee265d725e96a8162/src/vs/workbench/services/editor/browser/editorService.ts#L549-L586

And since the `gitlens` scheme is a registered `FileSystemProvider` it seems to be treated as a `FileEditorInput`

Can labels be supported on non-`file` scheme "files"?

Also this new label was only added to `vscode.open`, can it be added to `window.showTextDocument` as well?

/cc @joaomoreno

**Comment by bpasero** [comment]
@isidorn is this covered with the proposed API `registerResourceLabelFormatter`?

**Comment by isidorn** [comment]
@bpasero no. I mean the extension can register the formatting rules as @eamodio probably already does. But the issue here is what @eamodio points out, you are using the `labelService` only for the `ResourceEditorInput`. That is the actual issue, that FileEditorInput does not go to the `labelService` to fetch the label.

**Comment by bpasero** [comment]
@isidorn got it, this is probably something we should look at

**Comment by isidorn** [comment]
@bpasero I can look into it. Are there some caveats that I am missing, or we simply need to add the `name` property to the FileEditorInput also?

**Comment by bpasero** [comment]
@isidorn each editor input has a `getName()` method (along `getDescription()` and `getTitle()`). Currently it looks like the file editor input is simply calling into basenameOrAuthority(resource) instead of using your label service ([here](https://github.com/Microsoft/vscode/blob/4cce7c0/src/vs/workbench/contrib/files/common/editors/fileEditorInput.ts#L121)).

I feel like we should use the same as for resource inputs for name, description and title to be consistent.

**Comment by isidorn** [comment]
@eamodio please try it out in tomorrow's vscode insiders and let us know if the issue gets fixed for you
@bpasero I have change the `FileEditorInput` to use the `labelService` when computing its `name`.

**Comment by isidorn** [comment]
@bpasero @eamodio can some of you verify this, so we add a verified label?
