### ISSUE TITLE
tsconfig.json paths are ignored in workspace containing multiple tsconfig.json files

### ISSUE THREAD

**Issue by ShishKabab** [microsoft/vscode#64730]
- VSCode Version: 1.27.1 and 1.30.0-inside commit 241923
- OS Version: Ubuntu Linux 18.04 LTS

Steps to Reproduce:

1. git clone --recursive https://github.com/WorldBrain/storex-workspace
2. Notice that `yarn test:watch` works correctly
3. Open the dir in vscode and navigate to any file that tries to import from a library defined in tsconfig.json (like `package/storex-schema-migrations/ts/schema-diff/index.ts` at the time of writing.)
4. See that the packages cannot be found

Does this issue occur when all extensions are disabled?: Yes

**Comment by ShishKabab** [comment]
Bump?

**Comment by mjbvz** [comment]
`git clone --recursive https://github.com/WorldBrain/storex-workspace` is failing on 41d139a5fe7e446c77a6079c042ee20b4bdc37e9:

```
error: Server does not allow request for unadvertised object 204ac6c7bb1b36733c7805a5c26e2b95408d53a0
Fetched in submodule path 'packages/@worldbrain/storex-graphql-client', but it did not contain 204ac6c7bb1b36733c7805a5c26e2b95408d53a0. Direct fetching of that commit failed.
```

**Comment by ShishKabab** [comment]
Thanks, fixed it  :)  Since this approach with a top-level tsconfig.json didn't work with VSCode, I instead adopted a solution based on Lerna, which does play nice with it. However, the behavior should be reproducible with a previous tree:
```
$ git clone --recursive https://github.com/WorldBrain/storex-workspace
$ cd storex-workspace
$ git checkout 88dd28e
$ rm -rf packages/@worldbrain/storex-graphql-* packages/@worldbrain/storex-{sync,data-tools}
$ git submodule --quiet foreach yarn # Will give an error in `packages/user-logic` that you can ignore
$ yarn test
```

The test should run, meaning that TypeScript correctly detects dependencies. But, if you open this project with VSCode and try to edit one of the packages (like `packages/@worldbrain/storex-backend-dexie/ts/index.ts`, it'll not be able to resolve inter-package dependencies, even though they're correctly resolved using `storex-workspace/tsconfig.json`.

**Comment by mjbvz** [comment]
Thanks. I gave that a try but all the intellisense seems to be working and I don't see any errors:

<img width="873" alt="Screen Shot 2019-04-22 at 8 36 51 PM" src="https://user-images.githubusercontent.com/12821956/56551886-6a75e600-653e-11e9-8d29-6113b48410e6.png">

This is using the latest VS Code insiders on mac. I do see the top level tsconfig but it was not being used by `packages/@worldbrain/storex-backend-dexie/ts/index.ts` (run the `TypeScript: Go to project configuration` command in that file to check)  and the `@worldbrain/*` dependencies seem to be pulled from npm.

Is this expected?

**Comment by mjbvz** [comment]
Closing this as more information is needed to investigate

**Comment by keemyb** [comment]
This happens to me quite a bit
I have a project that looks like this: https://pastebin.com/EgVBw7fT

It's a multi repo that works well at runtime (and under test) with tsconfig-paths, so I'm confident my configs are valid. The letters appended to `tsconfig.json` are just for illustration only. They are named properly. Each config extends the one in the parent folder. I need the configs to be different, as for example d and f have path aliases to b, but not vice versa.

I often find that when I'm in any of the specs, I have squiggly lines due to the jasmine globals (which are defined as types in c, e and g) are not recognised. When I `Ctrl+Shift+P -> Typescript: go to project configuration` in say, api.spec.ts, I am brought to f, instead of g. When I restart vscode, this sometimes resolves itself.

I don't know how the resolution works, but it may be worth crawling tsconfig locations and caching them on project load, so it is easy to walk up the folder hierarchy to select the nearest one. I don't understand how an ancestor is being found before a parent.
