### ISSUE TITLE
tree - no tree navigator

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#64793]
blocks #64727

the outline uses the tree navigator to select previous/next elements when having searched. this will be a lot more cumbersome using `getNode` API and navigation APIs

**Comment by jrieken** [comment]
Please look at how the outline uses the navigator API today

**Comment by joaomoreno** [comment]
This is the only thing I could find: https://github.com/Microsoft/vscode/blob/dbb6f6d807f63429c0eb6913e86885f431b3832b/src/vs/editor/contrib/documentSymbols/outlineTree.ts#L271

We already discussed that you'd get expansion state preservation for free...

So, I'm guessing there's another place...?

**Comment by jrieken** [comment]
yes, outlinepanel.ts

**Comment by joaomoreno** [comment]
So, let me elaborate this for myself:

- There are `outline.focusDownHighlighted` and `outline.focusUpHighlighted` commands which let the user focus the previous or next item.
- The navigator is used to figure out what's the previous/next element which is an OutlineElement with a score (filter?).
- Once you find a candidate, you focus and reveal it.

There are already `focusNext` and `focusPrevious` methods on the tree which could do the hard work for you. I think what's missing for them is a `filter` function which lets you control whether an element would be suitable for focusing or not. Would that work?

Is the another situation?

**Comment by roblourens** [comment]
I am trying to reimplement the navigator (outside of the tree) but I don't think it's possible to tell whether an element is filtered out or not, is it?

**Comment by jrieken** [comment]
> I am trying to reimplement the navigator (outside of the tree) but 

🤞 we aren't all doing this. @roblourens do you build your navigator for re-use please? then I can use it  for breadcrumbs.

**Comment by joaomoreno** [comment]
Since I think I haven't laid out my argument against a tree navigator, here it is: it inverts the model-view pattern by exposing a view as a model. Data flow ceases to be one directional and things become harder to reason about.

Because of being against it, I've been trying to be helpful in understanding each use case for it and attempting to provide alternatives, like I've done for outline: https://github.com/Microsoft/vscode/issues/64793#issuecomment-446158043. I'm pretty sure the same could be done for all current usages of the tree navigator, and would be willing to expose tree API to make it so. At the same time, I feel I'm wasting my time in dealing with unhelpful comments like:

> > Can you elaborate?
>
> Please look at how the outline uses the navigator API today

So I basically stopped caring. I've pushed a `TreeNavigator` with some tests. It might not be bug free so file an issue if you hit any problems, I'll fix them asap.

**Comment by roblourens** [comment]
No worries, thanks for making one. I understand your argument and I'm not opposed to getting rid of it in the future. Search is a very heavy user of it (more than I realized originally) and since I'm making lots of changes already, it's much easier to work with the same interface and not have to figure out how to refactor around it.

**Comment by roblourens** [comment]
@jrieken note that this navigator doesn't update its indexes if the list view is modified, so be careful if you are expanding/collapsing nodes while navigating. Search can work around it by recreating the navigator from a certain element.

**Comment by joaomoreno** [comment]
Yeah, I forgot the necessary warning: do not use it across tree modifications, it will definitely break.

**Comment by roblourens** [comment]
I added that to the navigator yesterday @jrieken

**Comment by roblourens** [comment]
Oh I guess it's only in my branch. I can put it in master.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/commit/73d7889cbeb634a38d2281b3d83d8162a7c6e59f
