### ISSUE TITLE
don't bind cmd+` for the terminal

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6481]
The terminal shouldn't use <kbd>Cmd+`</kbd> on the Mac since that's a native shortcut to toggle between different windows of on app

**Comment by Tyriar** [comment]
Thanks, didn't know about that. I'll see what other editors do.

**Comment by Tyriar** [comment]
@jrieken looks like Sublime and Atom's terminal-plus actually uses <kbd>ctrl</kbd> instead of <kbd>cmd</kbd>. It doesn't look like we do this anywhere in the code yet though in which case it's probably a bit change to allow it.

I might just leave it blank on Mac for now as the [other commonly (but lesser) used shortcuts](https://atom.io/packages/term3) I found conflict with Ubuntu OS shortcuts.

**Comment by jrieken** [comment]
@Tyriar I think <kbd>ctrl+`</kbd> is fine. We do the same for <kbd>Ctrl+Space</kbd>

**Comment by Tyriar** [comment]
@jrieken I'll look into how that's done then :+1:
