### ISSUE TITLE
Cleanup debug.contribution startDebugHandler

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#64858]
Somehow I missed the change in the debug.contribution.ts and only now found it out.
What I do not udnerstand is why we need all this code? 
I think this handler should be removed and the action should be called like it was done previously.

Code pointer: https://github.com/Microsoft/vscode/blob/89a775140e619970b13e2b23f53597a3315b80e9/src/vs/workbench/parts/debug/electron-browser/debug.contribution.ts#L137

It would be great if we could tackle this in December.
Thanks

**Comment by RMacfarlane** [comment]
The reason for this code change was that `registerWorkbenchAction` creates a handler for command that passes no arguments to the action: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/common/actions.ts#L113

So instead I used `registerCommandAndKeybindingRule` with a handler that would forward the argument.

It looks like there are other debug commands registered in this way in `debugCommands.ts`, so I think moving the code for startDebug there makes sense. The handlers there are shorter and less generic, I'll see if rewriting the startDebug one that way causes any issues

**Comment by isidorn** [comment]
@RMacfarlane what you need is calling the start debug with a configuration, and I believe we already have a way for doing this.
@weinand can you please provide a pointer to where you are already calling start debug with a configuration.
@RMacfarlane are you calling start debug from the main side or where from exactly?

@RMacfarlane I can also look into this. You can just let me know how to verify that I did not break your scenario.

**Comment by weinand** [comment]
The extension API's implementation passes a debug configuration to the debug service's startDebugging here:
https://github.com/Microsoft/vscode/blob/51f7beb40c1faa3d911b751531d5a99a40cd376f/src/vs/workbench/api/electron-browser/mainThreadDebugService.ts#L232

**Comment by RMacfarlane** [comment]
I'm trying to start debugging from the process explorer. Since it's a separate browser window, it doesn't have access to the debug workbench service, and it's also not an extension, so it can't leverage the extension API for starting debugging.

Currently, the process explorer window sends an IPC message back to the issue service in the main process. This then sends an IPC message to the main renderer process to run the debug start command:
https://github.com/Microsoft/vscode/blob/2425e594f0c2b225b0f76c79af6c8c54ace3cd4b/src/vs/platform/issue/electron-main/issueService.ts#L75-L93

The `vscode:runAction` path is also used by the native menu to trigger commands from the main process.

**Comment by isidorn** [comment]
@RMacfarlane ok got it. So the best way it seems is to what you have done going via the action.
Can you try to clean up the handler. And if that does not work I can look into an alternative solution.

**Comment by RMacfarlane** [comment]
Sure, I'll work on cleaning up the handler today
