### ISSUE TITLE
Prevent accidentally dragging in tree via hysteresis

### ISSUE THREAD

**Issue by helzgate** [Microsoft/vscode#6486]
It's so easy to accidentally drag a folder to another and not even know it, i've done it several times but each time i've been lucky to catch it.  On a huge project this could be a nightmare.  Please alert the user or at least create a preference that allows us to set an alert.

Thanks!

**Comment by weinand** [comment]
Instead of showing an annoying warning, the drag-and-drop interaction could implement a larger hysteresis which forces the user to drag the mouse at least 30 pixels before a move operation is detected.

**Comment by bpasero** [comment]
I like that but that needs tree support.

**Comment by bpasero** [comment]
Actually it rather depends on how large the spacing is in the explorer and I know we changed that number to be lower.

https://github.com/Microsoft/vscode/issues/1414

**Comment by weinand** [comment]
@bpasero the drag-delta used in the hysteresis does not need to be coupled to the item spacing.
Here is an example: consider an item spacing of 10 and a drag-delta of 30. This means that the user first has to drag an item by 30 pixels (3 items) before the move operation is detected, but then the user can continue to drag the item back so that it is only 10 pixel away from the start position. So the 30 does not mean that the user can only move items to locations that are at least 30 pixels away.

(Try to remove an item from the OS X Dock: you will have to drag it out of the Dock by quite some distance before a 'remove' is detected).

**Comment by bpasero** [comment]
Good point!

**Comment by helzgate** [comment]
I hate to make people sound stupid but if you make the delta too high then when a first time user tries to drag a folder right next to another and it doesn't work they'll assume you can't drag and drop folders in VSC.  Can you simply add an option that we can enable folder drag-n-drop alerts?  To me this sounds like a much better option than playing around with drag deltas which appear to be working well.

**Comment by bpasero** [comment]
Well but you would get feedback directly that you can move. We just want to prevent accidental moves.

**Comment by weinand** [comment]
@helzgate the value 30 from above was just an (exaggerated) example.

Since I'm suffering from the same problem as you (but hate modal dialogs coming in my way), I tried to find a less intrusive way to help with this problem: instead of showing a brutal dialog in the top center of the window when the problem occurs, we could try to avoid the problem in the first place.

/cc @stevencl

**Comment by stevencl** [comment]
Preventing accidental drag and drop is commonly done by adjusting the drag sensitivity. In Windows the default is that the mouse has to move 4 pixels before the drag is initiated. Changing this to 15 pixels seems to work well as a reasonable compromise between preventing accidental drag and drop but still looking like drag and drop is supported.

Incidentally, I experimented on Windows using this utility to change the drag sensitivity to see what would be a reasonable threshold: http://www.parkscomputing.com/applications/dragsens/. This doesn't have any impact on VS Code but I was able to use VS to experiment.

**Comment by bpasero** [comment]
Fyi for July (or insiders) https://github.com/Microsoft/vscode/issues/4842 is pushed and allows to disable DND in the explorer.

**Comment by mario-d-s** [comment]
This issue has not had any activity for over two years. Anyone still interested in changes wrt DnD in explorer view?

Personally, I like the option to disable it altogether, but the suggestions about hysteresis make sense.

One idea that appears missing: simply provide an easy undo action?

**Comment by vjpr** [comment]
@weinand

> @bpasero the drag-delta used in the hysteresis does not need to be coupled to the item spacing (Actually coupling the drag-delta to the item spacing means not to use a hysteresis).

Where is this drag-delta in the codebase? I am having same issue. Details here: https://apple.stackexchange.com/questions/444076/accidental-drag-trigger-in-vscode-explorer-only-on-some-monitors

**Comment by farfromrefug** [comment]
I would love for this to be re opened. I don't think that fully disabling DND is a fix. It is merely just a workaround which actually prevent you from using a very important feature of vscode.
Personally I still want DND while having this big fixed. Without git I would have not seen unwanted DND so many times .... And it happens on all platforms. 
Please re consider that issue as a real bug.
There are multiple ways to fix it:
* create a drag sensitivity setting (seems best)
* add a setting to allow DND to work only with a key modifier.
