### ISSUE TITLE
Broken search

### ISSUE THREAD

**Issue by sguillia** [Microsoft/vscode#65011]
Please take a look at this screenshot
![vscode-bug-2](https://user-images.githubusercontent.com/15984272/49953455-71407c80-fefe-11e8-88cf-462ce01ade6b.PNG)

**Problem 1**:

There are two refresh icons - which makes no sense.

Reproducibility 100%, just launch a search

**Problem 2**:

- Cannot search (pressing enter does nothing)
- I did not cancel the build, and my escape key is not broken
- Clicking "Search again" does nothing

When I searched for some keywords I already searched like `error`, search works, but with `fck` or things like that it doesn't work.

This problem happened once, randomly, cannot reproduce yet.

Reproduces without extension:
- Double icon: **yes**
- Broken search: **no** (cannot reproduce)

VS Code version: Code - Insiders 1.31.0-insider (7ab53e6d1c7998006bc70f18230178a702598222, 2018-12-13T06:20:30.449Z)
OS version: Windows_NT x64 10.0.15063

**Comment by IllusionMH** [comment]
Also encountered first issue:
When user starts VS Code - I can see/use **Clear Search Results** button, but it is replaced with **Refresh** button when search is complete.

Tried to repro second case, but no luck.

**Comment by Boddlnagg** [comment]
I have actually encountered Problem 2 on the current 1.30 release (didn't happen with 1.29). I think it sometimes happens when I run a search that takes very long, and then try to start another search quickly afterwards before the first search yielded any results. Then I get into a state where no input into the search panel does anything. But when I wait for some time (maybe until the original search completed in the background?) the search panel begins to work again.

**Comment by AhmedMostafa16** [comment]
I have this problem too on Ubuntu 18.04 on my computer.

**Comment by roblourens** [comment]
There are two different issues here. I am fixing "problem 1" because at least I know what it is. Someone please open a new issue for "problem 2" with as many details as possible. I'm not able to repro it.
