### ISSUE TITLE
"smartStep" skipped frames are not grayed out

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#65025]
I'm seeing that frames skipped by smartStep are not grayed out, but frames from skipFiles are. This is in 1.30. The DA is sending the right thing and you can see this info in the tooltip.

![screen shot 2018-12-13 at 11 58 40 am 2](https://user-images.githubusercontent.com/323878/49964288-f9a72900-fece-11e8-96eb-a663679abe01.png)

Here's an example of DA output (not from the screenshot)

```
			"id": 1065,
			"name": "(anonymous function)",
			"source": {
				"name": "nodeDebugAdapter.js",
				"path": "/Users/roblou/code/vscode-node-debug2/out/src/nodeDebugAdapter.js",
				"origin": "(skipped by 'smartStep')",
				"presentationHint": "deemphasize"
			},
			"line": 10,
			"column": 71
		}, {
			"id": 1066,
			"name": "__awaiter",
			"source": {
				"name": "nodeDebugAdapter.js",
				"path": "/Users/roblou/code/vscode-node-debug2/out/src/nodeDebugAdapter.js",
				"origin": "(skipped by 'smartStep')",
				"presentationHint": "deemphasize"
			},
			"line": 6,
			"column": 12
		}, {
			"id": 1067,
			"name": "terminateSession",
			"source": {
				"name": "nodeDebugAdapter.js",
				"path": "/Users/roblou/code/vscode-node-debug2/out/src/nodeDebugAdapter.js"
			},
			"line": 492,
			"column": 16
		}, {
			"id": 1068,
			"name": "chrome.Runtime.on.params",
			"source": {
				"name": "nodeDebugAdapter.ts",
				"path": "/Users/roblou/code/vscode-node-debug2/src/nodeDebugAdapter.ts"
			},
			"line": 308,
			"column": 22
		}, {
			"id": 1069,
			"name": "emitOne",
			"source": {
				"name": "events.js",
				"path": "<node_internals>/events.js",
				"sourceReference": 1001,
				"origin": "read-only core module (skipped by 'skipFiles')",
				"presentationHint": "deemphasize"
			},
			"line": 116,
			"column": 13
		}, {
			"id": 1070,
			"name": "emit",
			"source": {
				"name": "events.js",
				"path": "<node_internals>/events.js",
				"sourceReference": 1001,
				"origin": "read-only core module (skipped by 'skipFiles')",
				"presentationHint": "deemphasize"
			},
			"line": 211,
			"column": 7
		}, {
```

**Comment by isidorn** [comment]
Looking at the code I see no difference in handling these. Since all of them have a `"presentationHint": "deemphasize"`, so they are equel to the vscode frontend.

Can you please provide a reproducable sample so I can investigate further on my machine?
An alternative is that you just put a brekapoint [here](https://github.com/Microsoft/vscode/blob/2804e0d20511f6d0a826739efda3a5e0a75091a8/src/vs/workbench/parts/debug/electron-browser/callStackView.ts#L442) and check why the `disabled` class does not get toggled.

**Comment by roblourens** [comment]
Problem seems to come from here:

![image](https://user-images.githubusercontent.com/323878/50484659-47379180-09b7-11e9-81a9-f090cd1c41ed.png)

`source.presentationHint` is not read

**Comment by isidorn** [comment]
Good catch, however I think that is fine.
Please note that we have the `presentationHint` both on the `stackFrame` and on the `Source` which is somehwat confusing.
In this particular case the `source` object contains the appropriate `presentationHint` and that is passed inside the stack frame properly. When we are rendering the `stackFrame` at a code pointer I gave above, we are acutally checking the `presentationHint` of the Source object inside. And that one should be correct in this case, right?

**Comment by roblourens** [comment]
At that line in callStackView.ts, `stackFrame.source.presentationHint` is undefined. So it seems to be correct when the object is created but becomes wrong at some point between that and being rendered.

**Comment by isidorn** [comment]
@roblourens can you provide some reproducable steps so I try to investigte more?
Thanks

**Comment by roblourens** [comment]
I see this for all smartStep frames

**Comment by isidorn** [comment]
@roblourens cool. But do you have an example for which I can easily get into this situation? Asking becuase I do not and I would prefer you give me an example than me setting this up.
Thanks

**Comment by roblourens** [comment]
Sure, clone this: https://github.com/roblourens/repro65025

Set BPs on lines 6, 11, and 16.

No decoration on the unmapped .js frames when at lines 6 and 11:

![image](https://user-images.githubusercontent.com/323878/51057384-506d5480-159a-11e9-97b9-8410b25a06fd.png)

But they are decorated correctly at 16:
![image](https://user-images.githubusercontent.com/323878/51057399-5cf1ad00-159a-11e9-88ea-6bc837fe9bc9.png)

And in both cases, the DA is returning basically the same thing, 

```
"origin": "(skipped by 'smartStep')",
"presentationHint": "deemphasize"
```

for all the relevant files.

**Comment by isidorn** [comment]
@roblourens thanks for this great steps. I can nicely repro.
After investigation the issue is [here](https://github.com/Microsoft/vscode/blob/2702ef254c828fa9a4165c1a3c4b8135ffc93146/src/vs/workbench/parts/debug/electron-browser/debugSession.ts#L791)

So this issue sort of contradicts with https://github.com/microsoft/vscode/issues/42139

The problem is that we currently do not allow multiple source objects for the same resource. Only one.

As a workaround I suggest that you put the presentation hint of deemphasize on the stack frame when it happens that some parts of the call stack you want to deemphasize and some not - while all of them living in the same file.

Would that work for you?
If not I am open for suggestions on how to fix this

**Comment by roblourens** [comment]
> when it happens that some parts of the call stack you want to deemphasize and some not - while all of them living in the same file.

Is that happening here? I think only the .js is deempasized and the .ts is not.

**Comment by isidorn** [comment]
Yes. `test.js` is comming in 3 times, and only the 1 & 2 have `presentationHint`.

`asyncFn1` does not have `presentationHint` set
![screenshot 2019-01-24 at 11 53 03](https://user-images.githubusercontent.com/1926584/51673582-9f6dad80-1fce-11e9-9681-d965c51763d7.png)

![screenshot 2019-01-24 at 11 51 11](https://user-images.githubusercontent.com/1926584/51673617-b57b6e00-1fce-11e9-8440-52aea57a8755.png)

Similar situation is for the second breakpoint.

**Comment by roblourens** [comment]
I don't think there's a valid scenario for these DAs where some parts of a file will be skipped and some parts won't.

But to be safe, should I always just set `presentationHint` on the frame instead of the source?

**Comment by isidorn** [comment]
For now I would leave it on the source since we actually do not specify in the protocol that a presentationHint on the stack frame can be deemphesized. We might need to change that.

https://github.com/Microsoft/vscode/blob/fd9fbbfd507d7db9eafd86fc746b574e1b86d790/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1340
