### ISSUE TITLE
Hope to have a plugin manager

### ISSUE THREAD

**Issue by stdKonjac** [microsoft/vscode#65123]
For users who have lots of plugins, it's difficult for them to manage different 
language's plugins.Especially when they want to remove one plugin.So I hope in next version we can have a plugin manager to divide plugins into different groups.
eg.
C/C++:
C++ Intellisense
C++ Clang
Web:
HTML CSS Support
HTML Snippets
thanks:)

**Comment by sandy081** [comment]
@stdKonjac Can you please elaborate your requirement and what you are expecting in detail?

**Comment by stdKonjac** [comment]
@sandy081 I mean a tree view like this:
![treeview](https://user-images.githubusercontent.com/39939534/50062755-dd173380-01e3-11e9-928a-6fb118168c9b.png)

**Comment by misolori** [comment]
We'd need to have some type of specific categorization from the marketplace otherwise this doesn't scale properly. Right now there is only an array of categories and tags, so this would need to be supported from the marketplace. Given this, will be closing this as out of scope until we get that support.
