### ISSUE TITLE
Find/replace in a single file is exceedingly difficult for newbs

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/vscode#65149]
Currently on MacOS and the November 2018 version of VSCode.

#### Background:

I come from Webstorm, which is an excellent IDE, but I sometimes work on an older Mac machine and Webstorm sucks up too much resources so I use VSCode. Webstorm has a very intuitive find/replace functionality for a single file - and when I try to do the same on VSCode it makes me want to suicide myself lol.

_Here is a simple example of my problem:_

![screenshot 2018-12-15 17 18 17](https://user-images.githubusercontent.com/11139560/50048952-a16a5580-008d-11e9-9b4a-dd58fad0b8b9.png)

So like I explain below the "files to include" / "files to exclude" functionality is a little wonky. I put a _single file in the files to include (the absolute path to the file)_ and _nothing in the files to exclude field_, and yet VSCode still wants to replace text occurrences in **2** files not **1** file. 

### UI SUGGESTION:

Find all the files that have the text occurrence, list them, and have the user check/uncheck which files to have the replace run. Put the files that are currently open in the editor at the top of this list. Like this:

- [x] /this/file/is/currently/opened/in/the/editor.ts
- [x] /this/file/is/also/currently/opened/in/the/editor.ts
- [ ] /this/file/is/not/opened/but/has/a/matching/text/occurrence-a.ts
- [ ] /this/file/is/not/opened/but/has/a/matching/text/occurrence-b.ts
- [ ] /this/file/is/not/opened/but/has/a/matching/text/occurrence-c.ts
- [ ] /this/file/is/not/opened/but/has/a/matching/text/occurrence-d.ts
- [ ] /this/file/is/not/opened/but/has/a/matching/text/occurrence-e.ts
- [ ] /this/file/is/not/opened/but/has/a/matching/text/occurrence-f.ts
- [ ] /this/file/is/not/opened/but/has/a/matching/text/occurrence-g.ts

If you can do the above UI thing, you will have a better UI than Webstorm/Jetbrains, so that's a win.

### MORE DETAILS

In order to replace a text occurrence in a single file, I have to use 

<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>F</kbd>

and then I see this:

![screenshot 2018-12-15 17 07 00](https://user-images.githubusercontent.com/11139560/50048895-daa1c600-008b-11e9-95b3-701b77fd3cc3.png)

but I want to replace the text occurrence, not just search for it and I want to do it in a single file (the file that's currently open). So I click the caret on the left and it opens another textbox:

![screenshot 2018-12-15 17 05 47](https://user-images.githubusercontent.com/11139560/50048907-46842e80-008c-11e9-90d6-6d3b3d67bb32.png)

But the problem is that I want to find/replace only in a single file, not multiple files. The "files to include" and "files to exclude" is quite cumbersome.

### here is the DANGER:

I have accidentally replaced all occurrences of a string of text in a project (100s of files) and it's really a nightmare, especially _when you don't realize that it happened and you thought you were only doing the replacing in one file._ That danger needs to be mitigated by an easy way to replace on the text occurrences in _a specific file_, and allow the user to tightly/easily control which file that is.

## SUGGESTION:

1. a right click option - find/replace in the current file is such a common need (IMO), it should be a right-click option when you click in the file itself:

2. A right-click option would be ideal, but if not that, then at least ctrl+R or ctrl+shift+R should open a find/replace window and it should _default to the current open file only_. (The last file you clicked on or typed in).

UIs rock when they are excellent.

**Comment by ORESoftware** [comment]
Ok so if I right-click on an opened file and choose "Change All Occurences" that works for replacing a text occurrence in a single file. However, I still think that "Find all occurences" in a given file is too difficult and also "Change All Occurences" should be "Change/replace All Occurences". And I think the UI idea (with the checkboxes) above is still a very good idea.

**Comment by skreborn** [comment]
You can automatically open the replace box by using <kbd>CTRL</kbd>+<kbd>Shift</kbd>+<kbd>H</kbd>. Notice the use of key <kbd>H</kbd> instead of <kbd>F</kbd>.

Furthermore, <kbd>CTRL</kbd>+<kbd>F</kbd> finds occurences in the active editor, while <kbd>CTRL</kbd>+<kbd>H</kbd> replaces in the same.

You're right that the latter (simple) method doesn't support replacing a subset of the changes, but that's what the former (advanced) is for.

---

As a personal opinion, I don't believe "Change All Occurrences" should be changed. "Change" and "Replace" basically mean the same thing - at least in this context -, and it's usually not a good a good idea to over-complicate UI labels.

**Comment by roblourens** [comment]
@skreborn is right, you are using the search view which is global by default. The editor' find/replace will just affect that editor.

You can use the 'x' button to eliminate some files or matches before replacing. I like that this is more explicit and less noisy than checkboxes.

The "files to include/exclude" boxes work better with patterns or folder names. Since the search view is intended for global search, it may or may not work well with an absolute path to a single file.

https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options

I wouldn't add context menu items for replace since there is a button that appears on hover for each row, while in replace mode. Did you not see it?
