### ISSUE TITLE
Integrate Gitlens

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode#65155]
https://gitlens.amod.io

This set of functionality to me is absolutely amazing, I can't imagine using VS Code without it. The team should consider talking to the plugin owners and bake this into VS Code so everyone can benefit

**Comment by jpike88** [comment]
@gudvinr

`that this is very specific set of functionality and not everyone need that`

VSCode ships with a built-in TypeScript library, but not everyone codes in TypeScript. So your point is moot.

`Also if you use code as text editor without using VCS it'll also be a useless. Or if you work with small projects it's not really needed too.`

That's just plain wrong. I work on a large project, and I don't use VCS. And VSCode works just fine for us.

`If you can make something with extension and it works for you why do you need to bloat a good piece of software? Aside from this tendency in JS world to bloat everything you can touch of course `

You're entitled to your opinion, as much as I think it's a very close minded way to think.

**Comment by gudvinr** [comment]
> VSCode ships with a built-in TypeScript library, but not everyone codes in TypeScript. So your point is moot.

So we need to include everything into VSCode because it is already includes something that not everyone need. Right?
You may notice that VSCode itself is written in TS and probably that's the reason for developers to use it as their main editor.
It's kind of common to include into editor support for language you're using to develop this editor.
My point is not to include _some more_ things that works perfectly as extension and not useful for every person. Because you know, that's extensions are need for. To _extend_ something.

> That's just plain wrong. I work on a large project, and I don't use VCS. And VSCode works just fine for us.

It was being said about uselessness of gitlens and not vscode in that case.

**Comment by joaomoreno** [comment]
Closing this as we have taken it into consideration but won't keep an issue open for it. Feel free to continue discussion.

**Comment by jpike88** [comment]
>So we need to include everything into VSCode because it is already includes something that not everyone need. Right?

@gudvinr I think you should tone back the argumentative language, it's really making it hard to take you seriously.

@joaomoreno maybe it's better that I suggest a specific feature in Gitlens that is gave me the most value, and it's [this one](https://github.com/eamodio/vscode-gitlens/tree/master/#current-line-blame-). That would be honestly what I should have made this issue as, as it's the feature that got me hooked.
