### ISSUE TITLE
Keyboard shortcuts list (or any other list we can scroll) column headers should always be visible

### ISSUE THREAD

**Issue by jcrmatos** [Microsoft/vscode#65175]
When listing keyboard shortcuts, keep the column headers visible (fixed) when scrolling down.
In fact, please consider making this a default whenever you show a list that we can scroll.

**Comment by skprabhanjan** [comment]
@sandy081 , can I work on this ? 
Some starter points will be helpful , Thanks :)

**Comment by sandy081** [comment]
Keybindings editor rendering code is here - https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/browser/keybindingsEditor.ts#L1

Please go through it and let me know if you have any questions.

**Comment by skprabhanjan** [comment]
@sandy081 , Thanks :)
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/preferences/browser/keybindingsEditor.ts#L720 , This is where the headers are being set , But I did not quiet get how to add those CSS kind of attributes to this ( Like position:"fixed" ), if you could throw some more insights it will be helpful :)
Also should we consider changing it **generally when a list is scrollable** ?

**Comment by Benny1007** [comment]
Just as a general observation, how do you go about debugging this? Like for web development you would open up a browser and check output. How is this done for vscode? e.g. where do you preview the HTML/CSS changes you are making?

**Comment by skprabhanjan** [comment]
Hey @Benny1007 , You can use [Debugger for chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) 
Also, All changes should be seen once you rebuild.
Refer this for more (https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run)

**Comment by jay-khatri** [comment]
@sandy081 I spent a few hours on this yesterday, and I'm able to render the headings as part of the header (rather than the list). This is what it looks like:

![2019-01-01 20 14 42](https://user-images.githubusercontent.com/20292680/50578051-051cae80-0e02-11e9-8fbb-178d8c6a3e19.gif)

Code needs to be cleaned up (and definitely added to the `List` or `WorkbenchList` API), but this is how I did it: https://github.com/Microsoft/vscode/pull/65892/files

Would you mind directing me to where in the code base the header is actually added to the DOM? I can't seem to find it. Also, if you have any thoughts/suggestions, I'd really appreciate it 😄 .

**Comment by sandy081** [comment]
Fixed by #41558
