### ISSUE TITLE
Terminal Window : Transparent Colors

### ISSUE THREAD

**Issue by dhananjay1405** [Microsoft/vscode#65275]
- VSCode Version: 1.30.0
- OS Version: Windows 10 (x64) 10.0.17763

Upon launching terminal windows, font color of existing text (i.e. powershell command promt) is transparent.
![vscode-terminal-screenclip](https://user-images.githubusercontent.com/43024754/50145419-8f7bf300-02d7-11e9-9aec-1d0210fa486d.PNG)

After executing **clear** or **cls** command, colors turn automatically to normal theme colors, in which terminal font appear.

**Comment by ceefour** [comment]
Since #57803 is locked. I think I will comment here if someone is looking for: Visual Studio Code integrated terminal is unusable/unreadable due to transparent or same foreground-background colors.

It happens with Visual Studio Code 1.30.1 and Windows 10 build 1809. However, if Windows 10 is at fault, this problem only happens with VSCode, not the Windows cmd. And in my case, typing `cls` does not return everything to normal:

![image](https://user-images.githubusercontent.com/24123/50448108-b5496d80-0951-11e9-8b86-6ca540ed5d1b.png)
