### ISSUE TITLE
MenuBar: is created even when custom menus are used

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#65298]
It looks like we are creating the menu bar service even when not needed. This shows up on startup, can we not create the service when it is not needed by doing the same check we do here:

https://github.com/Microsoft/vscode/blob/bd2e5b8c904bc36f141a9fdc009d541d77fc6b4c/src/vs/platform/menubar/electron-main/menubar.ts#L71

**Comment by sbatten** [comment]
The service is created but nothing is created inside of it to keep that cost as little as possible without removing it altogether. I believe I have it the way it is because the detection logic requires the configuration and environment services and I didn't know how to access them in `main.ts`. The detection appears to work in `app.ts` but the mainServices creation done in `main.ts` does not.

**Comment by bpasero** [comment]
I might touch on this during the week, will report back.

**Comment by sbatten** [comment]
@bpasero created another reason to have the menubarService with #65529 in non-native case

**Comment by bpasero** [comment]
Not convinced, commented.

**Comment by sbatten** [comment]
fixed a while back
