### ISSUE TITLE
Support multiline search for file local search

### ISSUE THREAD

**Issue by views63** [microsoft/vscode#65334]
![default](https://user-images.githubusercontent.com/175116/50188579-10310280-035d-11e9-8ed6-14e7624eb9bc.png)

**Comment by roblourens** [comment]
I assume you want this to expand to show multiple lines, the same way the search view input does, right?

**Comment by roblourens** [comment]
This is implemented

**Comment by dwelle** [comment]
@roblourens partially --- currently when you `ctrl+f` on a multiline selection, it doesn't populate search box as it does for single-line selection, or for project search with multiline selection. This is particularly important behavior when `regex` search is enabled. Should I create a new issue for this?

**Comment by roblourens** [comment]
I'm not sure it should. People would probably end up with large amounts of text in the find box pretty often. But you could open an issue for it.

**Comment by dwelle** [comment]
You mean unintentionally? Then people would be unintentionally ending up with single-line selections in their input fields, too. Plus, it doesn't really matter since input field is initially selected, so it's not like you need to do `ctrl+a → backspace` before typing your query.

Also, how does it differ from when you multiline-select and do `ctrl+shift+f` (project search) instead? Why doesn't that behave according to the same logic, and not populate the input field, either? I think it should be consistent.

**Comment by roblourens** [comment]
The only answer I have is that it feels more annoying when this happen in the find widget, because it will expand into the editor view, while the search viewlet is off to the side. But I'm not sure, could you open a new issue to discuss it?

**Comment by roblourens** [comment]
I guess there is already an issue for it: https://github.com/microsoft/vscode/issues/41050

**Comment by dwelle** [comment]
Alright, I'll upvote that one - thanks.
