### ISSUE TITLE
Sometimes clicking on a tab doesn't do anything.

### ISSUE THREAD

**Issue by lexicalunit** [Microsoft/vscode#65405]
This doesn't happen all the time, but it happens often enough to be super annoying. Sometimes clicking on a tab's X doesn't do anything. I have to click the X a bunch of times. Sometimes just clicking on the tab itself doesn't do anything, I have to move the mouse around and click on the tab a bunch of times to get it to raise. Most often I've noticed this occurs when clicking on the bottom half of the tab, or to the right of the end of the filename in the tab. In the whitespace between the end of the filename and the X. I can't exactly pin it down, but it seems like there's about a 75% success rate for clicking on a tab in VSCode and it actually doing anything at all.

- VSCode Version: 1.30.0
- OS Version: macOS 10.14.1

Steps to Reproduce:

1. Try to click on a tab, most often it happens when clicking near the top of a tab.

Does this issue occur when all extensions are disabled?: Yes, but less frequently.

The extensions I have installed:

```
$ code --list-extensions
bibhasdn.unique-lines
BriteSnow.vscode-toggle-quotes
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
eamodio.gitlens
eg2.tslint
esbenp.prettier-vscode
foxundermoon.shell-format
HookyQR.beautify
huacnlee.theme-macos-classic
lehni.vscode-titlebar-less-macos
magicstack.MagicPython
mgmcdermott.vscode-language-babel
mike-co.import-sorter
mohsen1.prettify-json
ms-python.python
ms-vscode.Go
pmneo.tsimporter
robertohuertasm.vscode-icons
spywhere.guides
streetsidesoftware.code-spell-checker
timonwong.shellcheck
waderyan.gitblame
```

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by lexicalunit** [comment]
@bpasero yep it's happens with the insider build I just downloaded. There appears to be a dead-zone for clicking between the end of the text in a tab and the X button to close the tab.

![deadzone](https://user-images.githubusercontent.com/1903876/50303798-0c77ab80-0443-11e9-90e5-e10955f51f45.png)

Beyond that I've also noticed times when I clicked on the X and it didn't work. Or where I've clicked on the tab either on the text or just above it and it didn't work. The most consistently place seems to be just below the text or just below the X, and outside of the deadzone.

**Comment by lexicalunit** [comment]
Using the developer tools I found the deadzone.

![screen shot 2018-12-20 at 10 48 28 am](https://user-images.githubusercontent.com/1903876/50304541-14d0e600-0445-11e9-8fb8-05f776ef24d8.png)

The green border is around this element:

```
<div class="monaco-icon-label file-icon .babelrc-name-file-icon babelrc-ext-file-icon ext-file-icon jsonc-lang-file-icon tab-label" title="~/source/invision/trapezoid-app/.babelrc" style="border:  1px solid green;color: rgb(51, 51, 51);"><div class="monaco-icon-label-description-container"><a class="label-name">.babelrc</a></div></div>
```

And here's where the red and blue borders are in the DOM:

```
<div class="tab-close" style="
    border:  1px solid red;
"><div class="monaco-action-bar animated"><ul class="actions-container" role="toolbar" aria-label="Tab actions"><li class="action-item" role="presentation" style="
    border: 1px solid blue;
"><a class="action-label icon close-editor-action" role="button" tabindex="0" title="Close (⌘W)"></a></li></ul></div></div>
```

The deadzone is in the red box, but to the left of the blue box. Clicking there does nothing.

I haven't been able to zero in on the issues where I click outside of that zone but nothing happens...

**Comment by bpasero** [comment]
Cool I can reproduce. If someone wants to fix this, be my guest. Code lives in `tabsTitleControl.ts`

**Comment by skprabhanjan** [comment]
@bpasero , Looked at this issue and found the following .
Changing `margin-right: 0.5em;` to `margin-left: 0.5em;` [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/media/tabstitlecontrol.css#L216) will fix the issue but does not remove the gap.
Can you let me know if this is a good ? (Because I am not sure if this is the right fix)
 I will send a PR after you confirm :)

**Comment by bpasero** [comment]
I am not convinced this needs a CSS change. Imho some click listener is not bound to the correct element, so I would look for a fix there.

**Comment by skprabhanjan** [comment]
@bpasero, ya that is what I initially thought and raised this concern . 
Anyways I will fix it as you said , thanks :)

**Comment by skprabhanjan** [comment]
@bpasero 
As described , The deadzone clicking does not work and as shown here in the screenshot ( The hover of mouse at that point shows the file path and not close)
So based on that I understand that the space is considered as part of the label and not close button.
Event click listeners are added correctly and I don't see any element not bound so that this bug is seen ( As part of this I tried to add `tabsActionBar` for `tabBorderBottomContainer` and `tabBorderTopContainer`, similar to [this](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/tabsTitleControl.ts#L441)
So I am kind of stuck here , Can you please help me ?

<img width="423" alt="screen shot 2018-12-21 at 3 56 27 pm" src="https://user-images.githubusercontent.com/17094832/50338317-fb5d9600-0539-11e9-91a3-183764610aa8.png">

**Comment by vitaliymaz** [comment]
Looks like event listeners attached correctly and the problem is still in CSS. Considering this DOM model 
![dom](https://user-images.githubusercontent.com/9901578/50419846-b4beb300-083b-11e9-8ef7-05ad3257b772.png)

**li.action-item** is an element which triggers close event and that looks correct place.
**div.tab-close** container element has hard coded width 28px and that is a main problem, because  **li** element is smaller and doesn’t take the whole parent container width.

As a solution proposing to get rid of hard coded width for div.tab-close and add “margin-left: 0.5em”. That will look the same but clicking in the "margin zone" won't swallow the event.

**Comment by skprabhanjan** [comment]
@vitaliymaz , the solution was proposed but @bpasero denied a CSS change , refer the above comments for more details.

@bpasero any updates on my latest comment ?

**Comment by vitaliymaz** [comment]
@skprabhanjan, you are proposing to change styles on a.action-label element trying to take more space.  I'm proposing to play with **div.tab-close** container itself to remove hardcoded width value which will fix the source of a problem. 
But in general yes, I'm just trying to support the idea of a fix via CSS changes. Looks there is no a better solution.

**Comment by skprabhanjan** [comment]
@vitaliymaz, correct , I was talking about the CSS approach in general :)
