### ISSUE TITLE
Buggy regex search of Chinese characters

### ISSUE THREAD

**Issue by PiranhaGreg** [Microsoft/vscode#65401]
- VSCode Version: 1.30.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create file `test.txt` in blank folder `test` with following content
```plain
鹅、鹅、鹅，
(é é é)

曲项向天歌。
(qū xiàng xiàng tiān gē)

白毛浮绿水，
(bái máo fú lǜ shuǐ)

红掌拨清波
(hóng zhǎng bō qīng bō)
```
2. Open folder in VSCode and try to search in files (Ctrl+Shift+S) regex `\p{Han}+`.
3. Open found file (test.txt) and try search in files again
   * **Search will not found anything**
   * **Search in test.txt is not working too...**

![regex](https://user-images.githubusercontent.com/3635737/50228591-9f173c80-03a8-11e9-9081-e65b63b31b69.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
The search in open text buffers executes in process using the [regex implementation of JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Special_characters_meaning_in_regular_expressions). That one does not support `\p` at this time. The search for files on disk uses ripgrep and that uses the [regex implementation of Rust](https://docs.rs/regex/1/regex/#syntax).

Since there are two different runtimes, we advise users to limit to use the regex syntax that is supported in both regex implementations.

**Comment by PiranhaGreg** [comment]
Ah, thanks for clarification. I didn't expect, that two completely different implementation of regex are used...
