### ISSUE TITLE
Terminal no longer sends onLineData

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#65485]
This appears to always be false now:
https://github.com/Microsoft/vscode/blob/48cc02be6e2d3e57231de35be7c0d872650c0752/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L942

Can be reproed using the hello code sample's npm watch and the strict null check task.

**Comment by Tyriar** [comment]
Seems to work fine on macOS? Are you on Windows?

**Comment by Tyriar** [comment]
macOS with strict null checks in the background with a log when the onLineData event is fired:

<img width="759" alt="screen shot 2018-12-20 at 11 04 57 am" src="https://user-images.githubusercontent.com/2193314/50305295-3632d180-0447-11e9-8302-b0bf0cfd6931.png">

**Comment by Tyriar** [comment]
Found the issue, it's happening because of a change to distinguish null and whitespace but we didn't keep the winptyCompat addon up with the changes:

https://github.com/xtermjs/xterm.js/blob/b39e8cfbb91a7f9b3105a3a1f1c9b40943fa804b/src/Buffer.ts#L20-L26

https://github.com/xtermjs/xterm.js/blob/90ec90746e26dcc20d02787587da72faedd186e1/src/addons/winptyCompat/winptyCompat.ts#L35

**Comment by Tyriar** [comment]
@alexr00 can you can mark this one as verified after checking it?

**Comment by alexr00** [comment]
@Tyriar, thanks for the quick fix!
