### ISSUE TITLE
Debug Cluster with autoAttachChildProcesses opens a new terminal instead of using the debug console

### ISSUE THREAD

**Issue by gustavomassa** [Microsoft/vscode#65490]
- VSCode Version: 1.30.1
- OS Version: Windows 10 Pro 64bits
![image](https://user-images.githubusercontent.com/16235598/50288255-83657200-044c-11e9-9592-79024adab528.png)

Steps to Reproduce:

1. Create a launch config with the option autoAttachChildProcesses: true
2. Debug the application, preferably a NodeJS Cluster App.

Does this issue occur when all extensions are disabled?: Yes

Name of the created terminal: Node Debug Console
![image](https://user-images.githubusercontent.com/16235598/50288383-f1aa3480-044c-11e9-83dd-a685b8902651.png)

Related to #62419

Another issue is the "stopOnEntry" option, when autoAttachChildProcesses is true, sometimes the debugger ignores the "stopOnEntry: false" and put a breakpoint and stops the code for every forked worker.

**Comment by gustavomassa** [comment]
#62419

**Comment by weinand** [comment]
Yes, when `autoAttachChildProcesses` is set, we automatically use the integrated terminal instead of the debug console. Reason being: every child process would result in its own debug console, so you will end up with a lot of debug consoles.
If you don't like this behavior, just set `console` to `internalConsole`.
