### ISSUE TITLE
Copy and Paste issue with closing brace

### ISSUE THREAD

**Issue by Daijobou** [microsoft/vscode#65614]
Version: 1.30.1 (system setup)
Commit: dea8705087adb1b5e5ae1d9123278e178656186a
Datum: 2018-12-18T18:12:07.165Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Betriebssystem: Windows_NT x64 10.0.17763
Windows 10

See GIF
![vscodea](https://user-images.githubusercontent.com/260343/50382870-0125b980-06a9-11e9-87a3-99e6859b2959.gif)

The closing brace go to wrong place after paste code, in second example.

**Comment by Daijobou** [comment]
Here is much more issues with autoindent. Should I create a new ticket or paste it here? Example
![vscodeh](https://user-images.githubusercontent.com/260343/50647153-28696a00-0f78-11e9-983e-b2ef3b7c7a5d.gif)

**Comment by Daijobou** [comment]
Here another variant with 1.33.0
Structure looks fine, but after copy&paste format is mismatch. After paste I press shortcut STRG+Z (german) for "undo" and its not remove the block, its formatted the block correctly!? A second "undo" remove the pasted block. Create formating new with starting from line beginning the copy&paste error is gone. See
![pasteA](https://user-images.githubusercontent.com/260343/55872843-4acddd80-5b8e-11e9-9d9d-e5a14b311d3c.gif)

**Comment by Tronic** [comment]
The difference of indentation in a pasted block vs. receiving code gets applied to a line of code directly after paste location. Meaning: if you copy 8-spaces indented code and paste it into 4-spaces indented code, one of the original code lines incorrectly gets deindented by four spaces. If the copied code was indented less than the paste location, extra indent gets added to the next line. My testcases https://paste.zi.fi/p/vscodebug.py/view

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules and only support limited code styles), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment or use auto formatting (`editor.formatOnType`, `editor.formatOnPaste`). As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like (https://github.com/microsoft/vscode/issues/19847 and https://github.com/microsoft/vscode/issues/34621).
