### ISSUE TITLE
Copy shortcut  ctrl + c  not work 

### ISSUE THREAD

**Issue by dimkoug** [Microsoft/vscode#65866]
os : ubuntu 18.04

When i copy  a block of code with the shortcut  ctrl + c  it is not working when i paste the "copied" block
and when i right click in the copy command there is no shortcut

**Comment by egamma** [comment]
This is a very common gesture, so I would be surprised if it doesn't work.

Executing the same steps using the menus instead of the keyboard works?
Do you have a special keyboard? 
Have you changed the keybindings?

Since this looks like a keybinding issue please refer to https://github.com/Microsoft/vscode/wiki/Keybinding-Issues


What command is bound to ctrl+c (very by opening the keybindings). This is what I see on my Mac

![image](https://user-images.githubusercontent.com/172399/50588446-5b313680-0e82-11e9-83f2-f5acab3c6de7.png)
