### ISSUE TITLE
Debug console should scroll to show expanded item

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#65871]
Initial state:

<img width="562" alt="screen shot 2018-12-31 at 12 24 39 pm" src="https://user-images.githubusercontent.com/2193314/50567211-10cf7e80-0cf7-11e9-9352-de89caf42577.png">

Clicking gives:

<img width="532" alt="screen shot 2018-12-31 at 12 25 00 pm" src="https://user-images.githubusercontent.com/2193314/50567217-1c22aa00-0cf7-11e9-81c8-4d8586a91912.png">

Expected:

<img width="548" alt="screen shot 2018-12-31 at 12 25 19 pm" src="https://user-images.githubusercontent.com/2193314/50567220-280e6c00-0cf7-11e9-9de2-3efd6eb9f2e6.png">

I think the expected behavior is to expand to show the entire sub tree, or show as much as is possible without moving the item that was clicked out of the viewport.

**Comment by isidorn** [comment]
We do not do this in the explorer. Chrome dev tools does not do it in their console. Any other explorer does not do this.
I would keep this open as a feature reqeust and only add it if more users request it. Though I think this should not be done.

I am against this since it might introduce too much unexpected scrolling and the current behavior seems to be somewhat of a standard.

**Comment by Tyriar** [comment]
Hmm, I guess you're right. I'm sure I've used programs in the past that do this but can't think of them.
