### ISSUE TITLE
Strict null check 'vs/workbench/common/editor/*model'

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#65934]
Part of #60565

Tracks updating the model files under `vs/workbench/common/editor/` to have strict null checking. The following files are currently eligible:

- `vs/workbench/common/editor/resourceEditorModel.ts`
- `vs/workbench/common/editor/textDiffEditorModel.ts`
- `vs/workbench/common/editor/textEditorModel.ts`
- `vs/workbench/common/editor/untitledEditorModel.ts`

**Steps**

1. Add file to the `include` section of `src/tsconfig.strictNullChecks.json` 
1. Run `yarn strict-null-check -- --watch`
1. Fix strict null check compiler errors
1. Verify normal build still works

**Comment by bpasero** [comment]
This touches a lot of different files due to the fact that I have to change:

```ts
readonly textEditorModel: ITextModel
```

to

```ts
readonly textEditorModel: ITextModel | null
```

which is used in many places (15 errors). I am assigning owners based on compile errors. To get them, checkout `strict-null-editor-model` branch and `yarn strict-null-check`

* [ ] [`editorExtensions`](https://github.com/Microsoft/vscode/blob/18fb6f9/src/vs/editor/browser/editorExtensions.ts#L270) @jrieken 
* [ ] [`extensionActions`](https://github.com/Microsoft/vscode/blob/18fb6f9/src/vs/workbench/parts/extensions/electron-browser/extensionsActions.ts#L1777) @sandy081 
* [ ] [`dirtyDiffDecorator`](https://github.com/Microsoft/vscode/blob/18fb6f9/src/vs/workbench/parts/scm/electron-browser/dirtydiffDecorator.ts#L1095) @joaomoreno 
* [ ] [`replaceService`](https://github.com/Microsoft/vscode/blob/18fb6f9/src/vs/workbench/parts/search/browser/replaceService.ts#L74) @sandy081 @roblourens 
* [ ] [`walkThroughInput`](https://github.com/Microsoft/vscode/blob/18fb6f9/src/vs/workbench/parts/welcome/walkThrough/node/walkThroughInput.ts#L108) @chrmarti 
* [ ] [`bulkEditService`](https://github.com/Microsoft/vscode/blob/18fb6f9/src/vs/workbench/services/bulkEdit/electron-browser/bulkEditService.ts#L57) @jrieken 
* [ ] [`jsonEditingService`](https://github.com/Microsoft/vscode/blob/18fb6f9/src/vs/workbench/services/configuration/node/jsonEditingService.ts#L44) @aeschli

**Comment by bpasero** [comment]
Assigning to @mjbvz via https://github.com/Microsoft/vscode/pull/69690

**Comment by mjbvz** [comment]
These files should all be checked now
