### ISSUE TITLE
Failed to install VS Code update.

### ISSUE THREAD

**Issue by SE2017-Hugh** [Microsoft/vscode#65942]
- VSCode Version:1.23.1
- OS Version: Windows 10 Pro 64 bit

This issue has been happening for a long time. I've had to update but the update failed again and again.

Steps to Reproduce:

1.Click the gear icon at the bottom left
2.Click "Restart to update..."
3.VSCode closes itself, and the small window with text "Updating VS Code" appears
4.Following prompt appears

image
![default](https://user-images.githubusercontent.com/33033519/50620578-14534780-0f3b-11e9-8982-b181c0b5d548.png)

[vscode-inno-updater-1546478047.log](https://github.com/Microsoft/vscode/files/2722554/vscode-inno-updater-1546478047.log)

Once I click "确定"(OK)， after a short while, this prompt appears.

![default](https://user-images.githubusercontent.com/33033519/50620761-5cbf3500-0f3c-11e9-89b5-29fb63ad38cc.png)

**Comment by bliteknight** [comment]
I had a similar issue. The reason is because the installer thinks your code.exe is installed in 
"C:\Users\<user name>\AppData\Local\Programs\Microsoft VS Code\Code.exe" but mine was installed in C:\VisualStudioCode\Code.exe

So I had to update all my registry entries that pointed to the wrong location to fix this.

Is there an easier way to set the install location for code.exe so the updater know where to look?

**Comment by joaomoreno** [comment]
@SE2017-Hugh Please change the setting `"update.enableWindowsBackgroundUpdates": false` to disable background updates. You'll still have updates, just not running in the background.
