### ISSUE TITLE
Breakpoints are unexpectedly shown as not-verified after removing and re-adding them

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#65993]
@isidorn As a result of discussions in #59984 and #62264 I have started removing and re-creating breakpoints in `setBreakpointsRequest` because we deemed it was the only way to attach IDs to them if I couldn't supply the IDs immediately. However, I'm seeing a strange issue where breakpoints will become marked as unverified whenever I remove (a different) one, even though I create them with `verified: true`.

Here's a fake `setBreakpointsRequest` implementation that shows the issue. All it does is sets them all as unverified from the original request, then events to remove each one, and then sends events to recreate them (this time, with IDs). As discussed, I send the response to the request before I send the `removed`/`new` events):

```ts
	private id = 1;
	protected async setBreakPointsRequest(
		response: DebugProtocol.SetBreakpointsResponse,
		args: DebugProtocol.SetBreakpointsArguments,
	): Promise<void> {
		const source: DebugProtocol.Source = args.source;
		let breakpoints: DebugProtocol.SourceBreakpoint[] = args.breakpoints;
		if (!breakpoints)
			breakpoints = [];

		// Send back all unverified breakpoints.
		response.body = {
			breakpoints: breakpoints.map((_) => ({
				verified: false,
			} as DebugProtocol.Breakpoint)),
		};
		this.sendResponse(response);

		// Now remove them all.
		breakpoints.forEach((breakpoint) => {
			this.sendEvent(new BreakpointEvent("removed", {
				column: breakpoint.column,
				line: breakpoint.line,
				source: new Source(args.source.name, args.source.path),
			} as DebugProtocol.Breakpoint));
		});

		// Now re-add them all.
		breakpoints.forEach((breakpoint) => {
			this.sendEvent(new BreakpointEvent("new", {
				column: breakpoint.column,
				id: this.id++,
				line: breakpoint.line,
				source: new Source(args.source.name, args.source.path),
				verified: true,
			} as DebugProtocol.Breakpoint));
		});
	}
```

And here's a video showing that whenever I remove a breakpoint, the others all become unverified (yet whenever I add one, they always become verified). I can't figure out why this happens.

![breakpoints](https://user-images.githubusercontent.com/1078012/50656514-63c16400-0f8b-11e9-94e4-44c7811cd2b0.gif)

**Comment by isidorn** [comment]
@DanTup I think it would be great if we somehow improve our process of reproducing issues.
I suggest that you always try to reproduce the issue by modifying the vscode mock debug sample which is very simple https://github.com/Microsoft/vscode-mock-debug
In case you can reproduce it there I suggest to always create a fork of that and share it with me so than I can always continue the investigation easily.
Giving me just a code snippet does not really help since I do not know where to put it.

Apart from that. I see that in the response you are sending verified: false in some case, maybe try changing that and see if that changes the outcome.
Also you can put a breakpoint [here](https://github.com/Microsoft/vscode/blob/becbe36faf7082390a945902abe3a76db8a89a5a/src/vs/workbench/parts/debug/common/debugModel.ts#L563) to try to figure out why the breakpoint returns verified false.

Thanks

**Comment by DanTup** [comment]
> I suggest that you always try to reproduce the issue by modifying the vscode mock debug sample 

That makes good sense to me - I'd considered making a stripped version of Dart Code and overlooked that sample. I'll take a look at putting the code into that sample early next week and see I can find anything else useful from a breakpoint. Thanks!

**Comment by isidorn** [comment]
Great, thanks

**Comment by DanTup** [comment]
@isidorn Here's a simple repro:

https://github.com/DanTup/vscode-repro-65993

It's the mock debug essentially just with the breakpointsRequest replaced with similar code to above: https://github.com/DanTup/vscode-repro-65993/commit/6cb6355af8a4ba5a6ae4073aea6ccad2af1c137a

To repro the issue, open a folder with a `.md` file and add breakpoints to lots of lines, then press F5 to run. Once the mock debugger stops on the first line, just try to toggle some breakpoints - every time you turn one off, all breakpoints go unverified (even though my code always deletes the unverified breakpoints and re-creates them as verified and with IDs).

> Apart from that. I see that in the response you are sending verified: false in some case, maybe try changing that and see if that changes the outcome.

It does - if I don't return them as unresolved in the first place, then this problem doesn't happen. I wonder if it may be a race condition or something - though I'd expect the responses and events should all be processed in-order, I'm not sure.

I did try adding a breakpoint to the `verified` code you linked, however it only seemed to be hit when the debug session started, and not when I was toggling the breakpoints on/off. I did try breakpoints elsewhere but couldn't track down what was wrong.

**Comment by isidorn** [comment]
The problem here is that you are returning verified: false in the response.
The problem is that whenever breakpoints change I will call the setBreakpointRequest and to that one you are always responding verified: false
Please do not return that response and all will be good.

I understand that in an another case you returnging verified true, but there seems to be a timing issue here which I do not plan to fix. Backlog

**Comment by DanTup** [comment]
@isidorn I'm a little confused. The code here is returning `verified: false` because the breakpoints are not verified. It then deletes them all and re-creates them as `verified`. At the end of this code, there should be no unverified breakpoints.

In the real project, the verified breakpoints come as a result of them actually being resolved by the VM, this is just mock code that just illustrates the issue.

This "dance" of removing them all and re-adding them is required in order to attach IDs to them after the `breakpointsRequest` (because I am unable to provide IDs until the VM has started up).

I'm not sure how I can make this work (the reason I need to attach IDs to every breakpoint, is so that if the location changes as part of resolution, the correct breakpoint is updated).

**Comment by isidorn** [comment]
@DanTup will investigate a bit more tomorrow and will write details here.

**Comment by DanTup** [comment]
> To fix this you should wait for the response to be sent out, before you send breakpoint events.

@isidorn In the sample code, the updates are already sent after the response:

```ts
		// send back the unverified breakpoints
		response.body = {
			breakpoints: actualBreakpoints
		};
		this.sendResponse(response);

		// Now remove all breakpoints based on the location.
		//snip

		// Now add new breakpoints to all locations, but this time with IDs.
		// snip
```

**Comment by isidorn** [comment]
@DanTup nope, those are async operations and you are not waiting for the promise to be resolved.
Anyways I see the order how I am getting it.

**Comment by DanTup** [comment]
@isidorn `sendResponse` returns `void` - I can't wait for it.

Also - given how async the debuggers are, it seems really important that debug adapter messages should be processed in the order they are sent, otherwise there will be all sorts of race conditions?

**Comment by isidorn** [comment]
@DanTup the messages are processed in the order they are recieved. We could introduce some timer id to make sure they are processed in the way they are sent but I do not believe we will do this as it might break a lot of exisiting functionlality.
And we did not encounter all sorts of race conditions thus far.

**Comment by isidorn** [comment]
@DanTup first send a response to the set breakpoints, only once the response is sent start sending the breakpoint event.

**Comment by DanTup** [comment]
@isidorn I don't follow - isn't that what my code is doing? Or do you mean the response isn't actually sent until `breakpointsRequest` returns? So I should wrap a `setTimeout(x, 0)` around the remove/re-add?

**Comment by isidorn** [comment]
@DanTup I did not write the actual mock debug implementation. But since the method does not return a promise but suscpicion is that there is a promise it is just not bubbled up. Since the whole operation of sending something over the wire has to be async.
So the proper thing is to somehow await on the response you are sending.
if that is not possible than a workaround is to do a setTimeout which feels like a hack

**Comment by DanTup** [comment]
It's not just the mock debugger that is hiding the promise, the `sendResponse` method is implemented by the `vscode-debugadapter` library which does not provide promises:

https://github.com/Microsoft/vscode-debugadapter-node/blob/7b97e42f1ed19777044850c5f18bfce8e21fc598/adapter/src/protocol.ts#L56

I agree setTimeout is a horrible hack, but I'm struggling to understand how this else this could work. Though to be honest, I'm not sure awaiting a promise would help anyway - if you're not receiving the events in the order they're sent, waiting for a promise for them to be sent surely still wouldn't guarantee the order (since really I'd need to wait until they're received and processed) - depending on where the order is being messed up.

I do still think something sounds really wrong if the events are not received in the same order though. What happens if a StoppedEvent and ContinuedEvent were re-ordered? It'd leave the debugger in the wrong state.

Maybe @weinand has some ideas about this - how we can wait for an event to be received (processed?) from a DA (though honestly, this seems like a recipe for high latency between Code and the DA).

**Comment by weinand** [comment]
The DA uses a stream to talk to VS Code. So the order how responses and events are written to the stream is the same as they are received on the VS Code side.

The following snippet shows how to correctly return a response and send an event from a request handler:
```
    // send back the unverified breakpoints
    response.body = {
        breakpoints: actualBreakpoints
    };
    this.sendResponse(response);

    this.sendEvent(breakPointEvent);
```
There is no need to use timers or wait for anything.

**Comment by isidorn** [comment]
@weinand Dan is already sending it in the correct order, e.g calling sendRespone and than sendEvent. You can see the snippet here https://github.com/DanTup/vscode-repro-65993
https://github.com/DanTup/vscode-repro-65993/commit/6cb6355af8a4ba5a6ae4073aea6ccad2af1c137a

However on the vscode side I am getting the it in the wrong order

@DanTup sorry for potentialy sending you on the wrong side, I was not aware that calling them in the right order the library gurantess that is how they will be sent

**Comment by weinand** [comment]
@isidorn I'm pretty sure you are receiving them in the correct order but you are **processing** them in the wrong order. E.g. your event handler code does not check whether all outstanding setBreakpoint responses are processed before handling a breakpoint event (that uses the same data structure).

**Comment by DanTup** [comment]
@weinand Great, thanks for the extra info - I hoped that was the case :-)

@isidorn No worries! Should this be re-opened though (possibly with the title updated)?

**Comment by DanTup** [comment]
@isidorn I don't suppose you got chance to look at this  yet? (btw, the as-designed label is now possibly misleading :-))

**Comment by isidorn** [comment]
Yes @weinand is correct. The issue here is that the adapter gives back response / events in the correct order. However they are not being handled in the correct order.
I suspect the issue is [here](https://github.com/Microsoft/vscode/blob/6b7808f337b115084e188852304dd578bd106143/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L625) while the new Promise is being created since we are using native promises the execution is switched to handling the incoming event.
I do not plan to fix this. Suggestions on how to fix are welcome. @weinand you actually wrote that code so you might have ideas.

@DanTup as a workaround for now send the events with a timeout - sorry about that and thanks for great steps.

**Comment by weinand** [comment]
The issue is not the low-level [send](https://github.com/Microsoft/vscode/blob/6b7808f337b115084e188852304dd578bd106143/src/vs/workbench/parts/debug/electron-browser/rawDebugSession.ts#L625) but the fact that our debugger implementation is asynchronous. After a request is sent to the DA and while we are waiting for the response, an event can be received.

So our breakpoint event handler does not check whether all outstanding setBreakpoint responses have been processed (and the data structures are updated) before it handles the breakpoint event.

There are two ways to fix this:
- by processing all responses and events in a strict sequential order. So an event would only be processed if all previous events and request/responses have been processed.
- by protecting critical data structures against concurrent modification. So we would block "breakpointEvents" processing while at least one "setBreakpointRequest" is still waiting for its response (because both modify the set of breakpoints). See https://github.com/compulim/promise-critical-section for how this can be done.

We need to fix this issue and I suggest to use the second approach as it only limits concurrency where needed.

**Comment by DanTup** [comment]
Cool, thanks. I presume it's unlikely a fix will make it in the upcoming release?

**Comment by isidorn** [comment]
Yes it will not be in this release.

**Comment by DanTup** [comment]
@isidorn Is this likely to make the next one? I think it's the only remaining blocker to having proper breakpoint resolution for Dart :-)

**Comment by isidorn** [comment]
I do not plan to fix this this milestone due to lack of time.
I accept nice PRs that fix this.

**Comment by DanTup** [comment]
I don't think I know enough about how this works to make a PR. Is it likely you'll be able to look at it for next milestone? It's not really urgent but I have been trying to fix breakpoint resolution for around a year on-and-off but each time I find an issue it gets blocked for a long time. It'd be nice to see the back of it :-)
