### ISSUE TITLE
Editor Hover Customization

### ISSUE THREAD

**Issue by jabacchetta** [Microsoft/vscode#65996]
The ample amount of hover tooltips shown in the editor seems to be a common complaint among new VSCode users.

We have the ability to disable them completely via `"editor.hover.enabled": false`, and [there are](https://github.com/Microsoft/vscode/issues/51253) a [few issues](https://github.com/Microsoft/vscode/issues/33752) related to positioning them.

Personally, I'd like to be able to control what is automatically displayed in the hover, and what must be manually opened with the `Show Hover` command/shortcut. For example, 99% of the time, I'm not interested in seeing function signatures, but I almost always want to see information for an ESLint error. I'd like the error to automatically show, while the signature only shows when I trigger it.

**Comment by alexandrudima** [comment]
@jabacchetta We could perhaps add yet another setting to disable semantic hovers and have hovers only show error messages.

But please note that error messages are presented in multiple places (perhaps 1 or 3 could be a workaround to what you ask for):

1. in the problems panel (quickly toggle via cmd+shift+M on macOS):
![image](https://user-images.githubusercontent.com/5047891/50773468-33cad700-1291-11e9-8262-0b0271c9799b.png)

2. in the hover:
![image](https://user-images.githubusercontent.com/5047891/50773502-4f35e200-1291-11e9-8769-7f2b1425e4c1.png)

3. in the F8 list (use F8 and Shift-F8):
![image](https://user-images.githubusercontent.com/5047891/50773527-5ceb6780-1291-11e9-975a-a2901c93ad56.png)


All the presentations have advantages and disadvantages. I kind of like using F8 because it allows me to loop through error locations and shows me error messages without using the mouse.

**Comment by jabacchetta** [comment]
Yeah, I think I'm usually focused on a single problem when one pops up, rather than multiple that may occur in a file (f8) or across all open files (problem panel), mainly because there are some that I choose to ignore (e.g. spelling errors that I have set up to display as information).

But now that I think about it some more, this might actually not be a big deal once the hover positioning feature request is added (will have to play around with it once it's in). And until then I can use cmd+k cmd+i (not quite as convenient for just a quick view when you open a file, but it'll work for now).

I'll close this for now and see what the future updates look like.

Thanks for the suggestions!
