### ISSUE TITLE
Place shell completion scripts in correct paths

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#66154]
Need to bring this back properly: https://github.com/Microsoft/vscode/commit/493ad1da77eed29af78eea248983f34b5ef44dc1

**Comment by segevfiner** [comment]
Ohhh, so the VS Code binary has different names in different kinds of builds. So the completion scripts should simply be installed with that name too. I will have to template them out to also replace the name inside them, which is a bit annoying since you won't be able to test them in Git & users won't be able to copy them from Git without replacing the placeholders manually. I will try to come up with a PR.

**Comment by joaomoreno** [comment]
I had to fix the `--telemetry` in zsh, since zsh was complaining of a syntax error, yet I couldn't make it behave standalone like `--version` or `--help`.

Otherwise, looks great! Thanks! :beers:
