### ISSUE TITLE
Webview: support cookie and localStorage

### ISSUE THREAD

**Issue by apupier** [Microsoft/vscode#66207]
it would be nice to allow usage of Cookie and localStorage in Webview API, it will ease integration of web UIs relying on it.

@mjbvz in this comment https://github.com/Microsoft/vscode/issues/48464#issuecomment-384105131 you said that it was disabled. Do you any pointers for the reasons why? Any ideas on what needs to be done to support it?

**Comment by mjbvz** [comment]
The webview has is no concept of cookies or localstorage because it has no concept of a host, it is just an html document that is rendered and not a webpage that you visit. No plans to change this.

You can use the webview state apis to workaround this: https://code.visualstudio.com/api/extension-guides/webview#getstate-and-setstate
