### ISSUE TITLE
Extension tests not found on Azure Pipeline

### ISSUE THREAD

**Issue by chrisjsewell** [Microsoft/vscode#66218]
I have an extension, initially created using the standard `yo code` template, and successfully uploaded to the market place. I have created a test suite, which works correctly when running locally (i.e. pressing F5), and I now wanted to add CI testing to the [Github repo](https://github.com/chrisjsewell/vscode-moose).

I followed the instructions on [Continuous Integration](https://code.visualstudio.com/api/working-with-extensions/continuous-integration) and created a [config YAML file](https://github.com/chrisjsewell/vscode-moose/blob/master/azure-pipelines.yml). The extension compiles successfully in Azure, however it appears that no tests are discovered.  

For example, in [this build](https://dev.azure.com/chrisjsewell/vscode/_build/results?buildId=4) I intentionally introduced a failing test, but it still passes.

Is there a step I'm missing, or a good way to debug the problem?

PS: I posted [this question on Stackoverflow](https://stackoverflow.com/questions/53957757/vs-code-extension-tests-not-found-on-azure-pipeline) a week ago, but received no replies. Hence, escalating it to an issue.

**Comment by bpasero** [comment]
Indeed we would not return an exit code of 1 if there is any error when loading and running the mocha test files. I pushed a change to make it fail, however this could end up with a ripple of now failing extension tests for all extensions, so I might have to pull this out again (even though I think the change is right - because not being able to run tests should not be reported as exit code of 0).

**Comment by chrisjsewell** [comment]
Cheers
