### ISSUE TITLE
Closes without warning

### ISSUE THREAD

**Issue by luxsnell** [Microsoft/vscode#66222]
- VSCode Version: 1.30.2
- OS Version: Windows

Steps to Reproduce:

Whenever I hit X button to close (quit), it just closes without any warning !

**Comment by RMacfarlane** [comment]
Hey @luxsnell, sorry for the unexpected behavior! You can control this with the `files.hotExit` setting. By default it is set to 'onExit', which skips the save prompt but will remember unsaved files across sessions so that your content is not lost. If you do want to see a prompt to save files on exit, you can change this setting to 'off' instead.
