### ISSUE TITLE
After debug stopped with some errors vscode change my code in one file to code from another file

### ISSUE THREAD

**Issue by aaskat** [Microsoft/vscode#6626]
- VSCode Version:1.1.1
- OS Version: windows 10

Steps to Reproduce:

1. I run my code with node.js environment in vs code, I have 3 files app.js, task.js and repo.js
2. Before I try start debug, I selected task.js and start when my code stopped with some errors in app.js then I stopped debug(clicked stop button in debug). And happen some mysteries my code in app.js change part of code from task.js

**Comment by weinand** [comment]
@aaskat I don't understand this problem. Could you please make a video showing your problem? Thanks.

**Comment by aaskat** [comment]
Ok.

**Comment by weinand** [comment]
@aaskat any update on this?

**Comment by aaskat** [comment]
Hello. I made video for this problem.
https://www.dropbox.com/s/e07m581qicygpnk/Untitled.mp4?dl=0

**Comment by aaskat** [comment]
I wanna contribute to project. how can I start? if you give me small tasks, like bugs fixing i can resolve  it.

**Comment by aaskat** [comment]
I made new video. can you check this video available for you.
https://www.dropbox.com/s/4jp06ucrk4ka8a1/bug2.mp4?dl=0

**Comment by aaskat** [comment]
I lost my changes in code several time in this way, and I can't undo changes after this bug.

**Comment by weinand** [comment]
@aaskat could you please attach your project (or the three files and the launch configuration) here and I will investigate.

**Comment by weinand** [comment]
@aaskat sorry, but I do not understand what error you are showing me in your second video.
I've create the three files in a VS Code workspace and debugged it. 
But everything looks good to me.

Please provide detailed steps that make clear what you would expect and what you get.

**Comment by aaskat** [comment]
![c93d3-clip-11kb](https://cloud.githubusercontent.com/assets/10125293/15608079/404d990c-2439-11e6-9ad2-d5b1d174f857.png)

**Comment by aaskat** [comment]
https://www.dropbox.com/s/0emdvm57z18qv0w/project.zip?dl=0

**Comment by weinand** [comment]
@aaskat Thanks for the video and the zipped project. But after trying for more than hour I was not able to reproduce the problem. Since nobody else has reported this or a similar problem, I'm running out of ideas how to help you.

But a few days ago you said that you want to contribute to VS Code and fix some bugs. This problem would be a good opportunity! You could help us (and yourself ;-) by doing the following:

- find a minimal reproducible case and write down clear steps so that everyone can reproduce it. Your videos are somewhat OK but they don't include precise steps, e.g.:
   - I don't know how you've started the debug session,
   - you have turned off auto-save. Can you reproduce the problem with auto-save turned on?
   - when you launch the debug session, both app.js and repo.js are dirty. Does the problem occur when they are not dirty or when only one of them is dirty.
- verify that the problem exists on a different system. This would rule out that something very specific is broken on your system. In similar cases where only a single user saw a problem, it was almost ever a problem with the underlying system, or a broken installation and not a problem with VS Code itself.
- try to identify the underlying problem in VS Code.
- fix the problem
- create a pull request.

/cc @isidorn

**Comment by aaskat** [comment]
Thank you! on another machine I did not reproduce this problem. I reinstall vscode after this problem gone.

**Comment by weinand** [comment]
@aaskat great to hear that!

**Comment by aaskat** [comment]
Thank you for your time

**Comment by aaskat** [comment]
I really want contribute. if you give me small tasks I can do.
