### ISSUE TITLE
Terminal Command Line text is not showing 

### ISSUE THREAD

**Issue by ashraf-jabr** [Microsoft/vscode#66277]
We have written the needed data into your clipboard because it was too large to send. Please paste.

![image](https://user-images.githubusercontent.com/14216646/50896402-f34a9500-1419-11e9-807f-8f7a2267c6d8.png)

**Comment by ashraf-jabr** [comment]
When I click [Enter] the second line show up
+ I am using the default colors configuration of Light Theme

**Comment by hero-wzielinski** [comment]
+1, it seems like the first line of the terminal is either not displayed or is hidden. you can begin typing and text will appear, and entering any comment will trigger all text to be shown. But it is not shown on initial load of the terminal.

![image](https://user-images.githubusercontent.com/46008344/50917227-fee28f80-140a-11e9-9edc-f8936b9e3a01.png)


Windows 10 Build 17763
Visual Studio Code v1.3.2

**Comment by johnfarley-sykes** [comment]
I'm experiencing the same issue since installing the latest update. If I start typing and/or click enter I do see text. It's just the initial line of text containing the path that no longer appears in the UI. 

Windows 10 Build 17763
VSCode 1.30.2

![image](https://user-images.githubusercontent.com/13528617/50919596-d3f73c00-1408-11e9-8fb4-bbf57eabe0e7.png)

**Comment by Tyriar** [comment]
This is a bug in Windows 1809, see https://github.com/Microsoft/vscode/issues/57803
