### ISSUE TITLE
Textual proposals get same score as JSON proposals

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#6628]
- settings file, copy over some settings, do auto complete:
![image](https://cloud.githubusercontent.com/assets/6461412/15453732/d6f025ea-2020-11e6-97aa-e36a555229f4.png)
-> when scrolling down multiple pages, one can see some real settings.

Problem is that text proposals are contribted for language selector 'json' and get the same score as the proposals from the mode.

Likely caused by @alexandrudima change in 41302caa15c73f6ec9e8805a9f0d62db2bc5dc25

**Comment by jrieken** [comment]
@alexandrudima Can you point to me the registration?

**Comment by alexandrudima** [comment]
@jrieken Maybe this is caused by using the registries and no longer using `suggestSupport`. Should we add a `weight` property on registration?

Here is the default textual completion: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/abstractMode.ts#L233

**Comment by alexandrudima** [comment]
I also suggest using find all references on SuggestRegistry, maybe other places need to have a lower weight?

**Comment by jrieken** [comment]
I don't like the _weight_ option. I would register for the `*` language which results in a lower score.

**Comment by alexandrudima** [comment]
Thank you @aeschli !

**Comment by aeschli** [comment]
Hm, I kind of expected an easier fix. The problem of the higher score is that the TextualSuggestSupport is contributed for every mode id. 
```
modes.SuggestRegistry.register(this.getId(), new TextualSuggestSupport(this.getId(), editorWorkerService, configurationService));
```
If you would just contribute a single time for '*', it would get the score it had before
Also it seems the TextualSuggestSupport doesn't really need to know the mode id.

**Comment by jrieken** [comment]
Actually, the problem is bigger than textual suggestion. Basically, all language features that don't work with merging results (suggest, formatting, etc) were affected cos before they were known to be coming from a built-in language and getting the lowest score. For instance, an extension adding/replacing formatting for html would be broken by that change. That's why we restored the old implicit knowledge. Once, everything moves to the extension host, the problem goes away because you top the score by coming [later](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/modes/languageFeatureRegistry.ts#L41) which you do by taking an ext-dependency
