### ISSUE TITLE
Enable use of snippet variables in workbench.action.terminal.sendSequence

### ISSUE THREAD

**Issue by fbehrens** [Microsoft/vscode#66337]
Hi :)

I would love to be able to use [task variables](https://code.visualstudio.com/docs/editor/variables-reference) to send snippets of code to my terminal. 
```json
{ "key": "ctrl+shift+t",
  "command": "workbench.action.terminal.sendSequence", 
  "args": { "text": ". ${file}" } 
```
I am developing all the time interactively with editing a file and fiddling in a REPL (in integrated Terminal)  alongside, where I have my environment loaded. I edit a function, I load the file from the REPL, and then test it interactively.

The difference to `Tasks` is that I have state in the REPL. This then can be used for different languages with a simple configuration. 

I have written a [Sublime Plugin](https://github.com/fbehrens/sublime_ExternalREPL) for this feature,
and I will write a Extension, according to your response.

Thanks for reading, and keep up the good work

**Comment by Tyriar** [comment]
@alexr00 any tips on leveraging task code to resolve this?

**Comment by alexr00** [comment]
Let me make sure I understand the request:
1. You set up your REPL with some state
2. You run the command above using your keybinding which causes the file you want to test to be loaded into the REPL.
3. You then want to run preset snippets of code in the REPL. This is the part where you want to use tasks variables to send preset code snippets to the REPL.

Is all that correct? If so, I think this can be accomplished with tasks in insiders.

There is now a third `input` type; `command`. https://github.com/Microsoft/vscode/issues/64362. I think you could use this to accomplish step three above by having a few different `command` input types that use the `workbench.action.terminal.sendSequence` command and has the snippet you want as an argument. You would need a separate task + `command` input variable for each snippet, I can't think of a way around that unless you write a simple extension.

**Comment by Tyriar** [comment]
@alexr00 the `workbench.action.terminal.sendSequence` commands lets you send data to any terminal (not just task ones), it basically lets users fake typing in without building an extension to do it. For example you could send ctrl+c or "ls" then enter. The request is just about supporting resolving the `${...}` syntax as used within tasks in the `workbench.action.terminal.sendSequence` command.

The example keybinding:

```ts
{ "key": "ctrl+shift+t",
  "command": "workbench.action.terminal.sendSequence", 
  "args": { "text": ". ${file}" } 
```

Could be used to 'source' (run) the active file in the active terminal.

I mainly wanted to code pointer to where this variable resolution happens in tasks and/or debug so that a contributor could put a PR together and share the code.

**Comment by alexr00** [comment]
Variables are resolved here: https://github.com/Microsoft/vscode/blob/f7f063bf4c76a15b4190e8dbc65c9ea6de859941/src/vs/workbench/services/configurationResolver/electron-browser/configurationResolverService.ts

**Comment by njkevlani** [comment]
@Tyriar 
I'd love to help by implementing this feature if you guys would want me to :)

I think we need to handle `snippets` in code of `sendSequence` itself or is there any other way round?

**Comment by Tyriar** [comment]
@njkevlani you'll probably need to call this `IConfigurationResolverService.resolve` similar to how it's called on the environment:

https://github.com/Microsoft/vscode/blob/ddd17d938ffcdc40158b845c9abc25dcc2978c7e/src/vs/workbench/parts/terminal/node/terminalEnvironment.ts#L84

And yes in the code for the sendSequence action.

**Comment by njkevlani** [comment]
@fbehrens  you wanna work over this or can I take it?

**Comment by fbehrens** [comment]
@njkevlani  You can take it

**Comment by Tyriar** [comment]
@njkevlani 👌

**Comment by Tyriar** [comment]
@njkevlani you can use our dependency injection system like in this command:

https://github.com/Microsoft/vscode/blob/4fe1cdc4df003911507e53a06ccfb261f68bce18/src/vs/workbench/parts/terminal/electron-browser/terminalActions.ts#L300-L302

**Comment by njkevlani** [comment]
@Tyriar 

That works for classes which extend `Action`, I could not find such usage for some class which extends `Command`.

Probably It is because how the `Commands` are registered:

https://github.com/Microsoft/vscode/blob/4fe1cdc4df003911507e53a06ccfb261f68bce18/src/vs/workbench/parts/terminal/electron-browser/terminal.contribution.ts#L515-L519

**Comment by Tyriar** [comment]
@njkevlani I think you should be able to convert it to an `Action`?

**Comment by njkevlani** [comment]
@Tyriar I thought exactly the same!! But could not find an example of an `Action` that takes something like `args`. Will do it if you could give some pointer to such specs.

**Comment by Tyriar** [comment]
@njkevlani ah I see, I guess that's why it's a `Command` :smiley: 

Looks like a `ServicesAccessor` is passed into `runCommand`, you should be able to grab the service off that like this:

https://github.com/Microsoft/vscode/blob/4fe1cdc4df003911507e53a06ccfb261f68bce18/src/vs/editor/browser/controller/coreCommands.ts#L1652-L1654

**Comment by njkevlani** [comment]
@Tyriar 

It's working!!

How do we kick in auto suggestions in `keybinding.json`? Should I include that in this PR or a different PR would be better?

**Comment by Tyriar** [comment]
@njkevlani great! I've never done that before so I'm not sure, also not sure if we support doing that in other keybindings (in which case it'd be a bunch of work). Let's do a PR without it to start with 😃

**Comment by fbehrens** [comment]
Works like a charm in `insiders`.

I have another edge case question concerning the feature, more about haw the task variables are resolved. Don't expect an answer, and hope it is OK to ask here.

On Windows `${file}` is `d:\scripts2\libwba\src\tools\environment.fs`, but `${relativeFile}` is `src/tools/environment.fs` . Is there a way to influence the path seperator  (`\` vs `/`) ?

**Comment by alexr00** [comment]
@fbehrens, no there isn't a way to influence the path separators. https://github.com/Microsoft/vscode/issues/38381 in the issue related to this.
