### ISSUE TITLE
Version update error

### ISSUE THREAD

**Issue by HardT0Name** [Microsoft/vscode#66381]
- VSCode Version:1.30.1
- OS Version: Windows_NT x64 10.0.16299

Steps to Reproduce:
1.I want to try to update the version of vscode and I have the following problem.

![image](https://user-images.githubusercontent.com/33834823/51017317-a51aca80-15ae-11e9-9cf8-77ad7e8cfa3d.png)
[vscode-inno-updater-1547188544.log](https://github.com/Microsoft/vscode/files/2748390/vscode-inno-updater-1547188544.log)

Does this issue occur when all extensions are disabled?: Yes/No
I did not try this.

**Comment by joaomoreno** [comment]
Where is Code installed in your machine?

**Comment by changavila** [comment]
Yes, this also happened to me, i seemed that it couldnt replace the previous vscode*.exe, since this was used by the System. Tried manually deleting it, to no avail, until I restarted my PC, and Removed this file, and reinstalled with a new copy. Im not sure what happened here, but I guess, Hard-Reinstall is the solution.

**Comment by HardT0Name** [comment]
A for Q "Where is Code installed in your machine?"
D:\Microsoft VS Code

I tried to uninstall the entire vscode and deleted the configuration file. I downloaded the latest version and solved the problem too.

**Comment by joaomoreno** [comment]
Thanks for fixing with reinstallation. Glad to know you're unblocked.
