### ISSUE TITLE
ctrl+tab no longer working for terminal focusNext and focusPrevious

### ISSUE THREAD

**Issue by davidbailey00** [Microsoft/vscode#66403]
I just upgraded to Code 1.30.2 on Ubuntu 18.10 and I'd previously been using ctrl+tab and ctrl+shift+tab to switch terminal tabs although this no longer appears to be working. Here is my `keybindings.json`:

```json
// Place your key bindings in this file to override the defaults
[
  {
    "key": "ctrl+k space",
    "command": "workbench.files.action.showActiveFileInExplorer"
  },
  {
    "key": "ctrl+tab",
    "when": "terminalFocus",
    "command": "workbench.action.terminal.focusNext"
  },
  {
    "key": "ctrl+shift+tab",
    "when": "terminalFocus",
    "command": "workbench.action.terminal.focusPrevious"
  },
  {
    "key": "ctrl+tab",
    "command": "-workbench.action.openNextRecentlyUsedEditorInGroup"
  },
  {
    "key": "ctrl+shift+tab",
    "command": "-workbench.action.openPreviousRecentlyUsedEditorInGroup"
  },
  {
    "key": "ctrl+tab",
    "command": "workbench.action.nextEditor"
  },
  {
    "key": "ctrl+shift+tab",
    "command": "workbench.action.previousEditor"
  }
]
```

Instead, the keys are sent to the terminal (or possibly just the "tab" key is sent).

**Comment by Tyriar** [comment]
I just tested it and it on a clean install with 1.30.2 with this:

```
[
  {
    "key": "ctrl+tab",
    "when": "terminalFocus",
    "command": "workbench.action.terminal.focusNext"
  },
  {
    "key": "ctrl+shift+tab",
    "when": "terminalFocus",
    "command": "workbench.action.terminal.focusPrevious"
  },
]
```

It definitely works for me. Do you override `terminal.integrated.commandsToSkipShell` and not include the `focusNext`/`focusPrevious` commands maybe?

---

After looking again at your list, it's because you have these keybindings defined _below_ the terminal ones:

```
  {
    "key": "ctrl+tab",
    "command": "workbench.action.nextEditor"
  },
  {
    "key": "ctrl+shift+tab",
    "command": "workbench.action.previousEditor"
  }
```

The `when` clause does not increase priority, the priority of the keybinding is based purely on the order of the keybindings.

**Comment by davidbailey00** [comment]
@Tyriar Thanks for the reply! I just realised it works after adding "when": "editorFocus" to the other ctrl+tab shortcuts.

However, I still wonder if there is a bug due to the fact that pressing ctrl+tab in a focused terminal did not change the editor with my original keybindings. Instead, it only sent a ctrl+tab to the terminal. Surely if a keybinding is overridden then it should have an effect, rather than solely disabling the effect of a previous keybinding?

**Comment by Tyriar** [comment]
> However, I still wonder if there is a bug due to the fact that pressing ctrl+tab in a focused terminal did not focus the next editor with my original keybindings. 

@davidbailey00 the reason here is that keys are handled specially when the terminal is focused as it needs to decide which it should let the terminal process handle and which VS Code should handle. There is a list of commands which includes all terminal commands by default in the setting `terminal.integrated.commandsToSkipShell`, I don't think nextEditor is included in that list of defaults. You can read about that setting for more info.

Also if you want to use that setting, it's changing in the next version to instead of overriding the list you can add and remove from it. https://github.com/Microsoft/vscode-docs/commit/f70ff3e7abe986788582123450b785b9f1be13e2
