### ISSUE TITLE
Unable to open 'MPE Preview': ModelService: Cannot add model because it already exists!.

### ISSUE THREAD

**Issue by generalbrus** [Microsoft/vscode#66428]
- VSCode Version:  1.30.2
- OS Version: macOS High Sierra

Steps to Reproduce:

1. Open Preview of md file using Markdown Preview Enhanced (https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced#overview)
2. Move the opened tab to change layout (e.g. to have the window split horizontally)
3. The preview tab closes and the error pops up. Trying to open the preview again fails until vscode is restarted.

Does this issue occur when all extensions are disabled?: 
I cannot test the issue with the extension disabled.

**Comment by generalbrus** [comment]
I did not find the another relevant issue reported here and still open. However the bug is the same described in the repo of the extension: shd101wyy/vscode-markdown-preview-enhanced/issues/173

**Comment by RMacfarlane** [comment]
Hi @generalbrus, this repo is meant to track issues with VSCode itself. Since the error is coming from an extension, reporting it on the extension first would be great. Thanks for searching for duplicates in the extension's repository. I'm going to close this since I believe this is a problem with the extension itself and there is already an issue tracking it. Happy coding!
