### ISSUE TITLE
Breakpoints jump randomly when debugger starts

### ISSUE THREAD

**Issue by th-m** [Microsoft/vscode#66568]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Make app with Mocha, Typescript, React, Redux and Sagas
2. Run debugger

Does this issue occur when all extensions are disabled?: Yes

Here is a gif of the issue. I have a breakpoint set on 105, once the debugger gets going it jumps to 112. Super annoying and really hampers the usability of the debugger.
![breakpoint](https://user-images.githubusercontent.com/13792029/51222068-3fee0e80-18f9-11e9-8f2a-61db96466423.gif)

Here is my .vscode/launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Mocha Tests",
            "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
            "args": [
                "src/**/*.test.{js,jsx}",
                "--require",
                "${workspaceFolder}/config/tests/mocha-setup.js",
                "--colors",
                "--verbose"
            ],
            "env": {
                "NODE_ENV": "test"
            },
            "internalConsoleOptions": "openOnSessionStart"
        },
    ]
}
```

I looked for duplicates but all other threads I found were closed or had different variables. Any help getting a work around for this?

**Comment by weinand** [comment]
The VS Code debugger only reflects the information that it gets from the "Mocha, Typescript, React, Redux and Sagas" pipeline. It is not VS Code that moves breakpoints by itself.
If a breakpoints on line 105 "jumps" to line 112 on debugging start it means that the node.js runtime does not accept a breakpoint on line 105 and tries to set it on the next available position. Typically this is a problem of the generated source maps.
In order to investigate this, we need "real" reproducible steps. The sentence "Make app with Mocha, Typescript, React, Redux and Sagas" is not enough...
