### ISSUE TITLE
New Explorer: error when creating multiple children

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#66586]
Refs: https://github.com/Microsoft/vscode/issues/66485

When you create multiple children from the "New File" action using slashes (I tested on windows) I see this error:

`Data tree node not found: [object Object]: Error: Data tree node not found: [object Object]`

The tree recovers after a refresh.

![image](https://user-images.githubusercontent.com/900690/51238598-90a44c80-1977-11e9-8b27-5fc64afa2401.png)

**Comment by isidorn** [comment]
I can repro also on os x.

The issue here is that if folders a and b do not exist and i go to the file service and say create
`a/b/c.txt`
The file service will properly create folder a, than b and than c.txt. However the `onAfterOperation` will fire only for the creation of c.txt. It will not be fired for `a` and `b`even though they got created.

@bpasero does it make sense to fix this on the file service level
If not, than in the explorer for every file service create event I have to travel up the parent chain and check if the parents got created as well and create them.

This was working before by having some special logic for this feature which I dumped.

**Comment by bpasero** [comment]
@isidorn maybe the event could be enriched with all the resources that got created on the way (e.g. make it an array?). The explorer is pretty much the only client of this event so feel free to change it.

**Comment by bpasero** [comment]
Seems to work now!

**Comment by isidorn** [comment]
Lovely!
