### ISSUE TITLE
Simple full screen window gets stuck when changing montiors

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#66583]
insiders, os x

1. Turn on simple full screen mode
2. Switch off your external monitor, or connect to an external montior if not already connected
3. Rendering is severly broken. I can not even exit simple full screen mode. I can only quit vscode

**Comment by bpasero** [comment]
@ignu can you please take a look

**Comment by isidorn** [comment]
Let me sound like our users: this makes the simple full screen unusable for me ^_^

**Comment by bpasero** [comment]
@ignu thanks

**Comment by isidorn** [comment]
I am on Mojave. And can reproduce 100% of the time.

**Comment by bpasero** [comment]
@ignu it looks like the [`display-metrics-changed`](https://github.com/Microsoft/vscode/blob/5a41fdd88fa6ed36dc1f78d0d2bd4ddd3aa471a8/src/vs/code/electron-main/window.ts#L372) is maybe not firing in that case. I can reproduce easily. It could also be a regression from our recent Electron 3 update (which is not yet out for stable).

**Comment by bpasero** [comment]
I think with additionally listening to the screen events `display-added` and `display-removed` we have a workaround. Not a nice solution overall, but we have limited options. E.g. it could be seen as ugly that the fullscreen toggles when adding a monitor and nothing changes otherwise, but that's life with simple fullscreen and Electron...

**Comment by isidorn** [comment]
This works nice now, thanks for making my life better

**Comment by bpasero** [comment]
Praise G.
