### ISSUE TITLE
Debug viewlet should show on F5 (not attach)

### ISSUE THREAD

**Issue by sbatten** [Microsoft/vscode#66617]
Issue Type: <b>Bug</b>

At least in the case of the debug widget inside the debug viewlet, the debug viewlet should be shown immediately on start debugging and not wait for attaching, the same way the widget shows immediately. If I don't have the viewlet open, there is no feedback for several seconds that my F5 did anything.

VS Code version: Code - Insiders 1.31.0-insider (d3024ec0c4eb830eb22a39bc2f2feacd314a952a, 2019-01-16T07:58:52.560Z)
OS version: Windows_NT x64 10.0.17763

**Comment by isidorn** [comment]
@sbatten what you are saying makes perfect sense, especially for the widget in viewlet case.
I have changed it, such that we now open the debug viewlet before we actually attach / launch.
Note that code-wise the widget might be visible a bit before, since for the viewlet we have to wait for the configuration resovling to finish since there is a setting which controls if the viewlet should be opened or not.
In practice it should work like you wanted it, try it out and let me know. Thanks
