### ISSUE TITLE
New Explorer: revealing previous view state on startup is not smooth

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#66659]
It looks like folders get expanded one after the other which is not as smooth as it used to be:

![grid-tw](https://user-images.githubusercontent.com/900690/51317712-9aea4780-1a58-11e9-8243-0102af270f2c.gif)

**Comment by isidorn** [comment]
Agree, it was smoother.
@joaomoreno any ideas on how to make it smoother?

**Comment by joaomoreno** [comment]
How was it smoother before?

**Comment by isidorn** [comment]
@joaomoreno before there was a `expandAll` call on the tree and due to that the percieved expansion was smoother.
Now it is step by step because I actually call `expand` for each of the elements due to the lack of `expandAll` call.
So either we need an `expandAll` call, or the `expand`  should have some flag like 'do not update UX'. And I would say update ux only on the last call.

**Comment by joaomoreno** [comment]
> Now it is step by step because I actually call expand for each of the elements due to the lack of expandAll call.

Where do you do that, again?

**Comment by isidorn** [comment]
Here https://github.com/Microsoft/vscode/blob/2a0a6ebad95e1483a81682e97d4ff91ae730edda/src/vs/workbench/parts/files/electron-browser/views/explorerView.ts#L476
