### ISSUE TITLE
Collapse the folder in explorer to the bottom

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6666]
I would be nice if the explorer would collapse to the bottom given that the "Opened Editors" view is becoming more useful lately.

![image](https://cloud.githubusercontent.com/assets/900690/15473361/db99abf4-20ff-11e6-97bb-17573fe886e3.png)

**Comment by bpasero** [comment]
Reopening as this was reverted.

**Comment by isidorn** [comment]
Yes - forgot to reopen thanks!

Note to myself: this was reverted because the resizing of the workbench would mess with the layout. Thus we were not respecting the layout calls.
In order for this to be done split view views need some serious refactoring -> backlog (will look into one of the debt weeks - maybe even july).
