### ISSUE TITLE
Insiders build - touchbar no longer shows debug actions

### ISSUE THREAD

**Issue by aLagoG** [Microsoft/vscode#66689]
Issue Type: <b>Bug</b>

### Steps to reproduce

1. Download vscode insiders build
2. Write a simple script to debug (I've tested it on both js and python)
3. Set up a breakpoint
4. Run it with whatever configuration is the default for the language you chose 
5. Let it hit the breakpoint
### Expected Results 
The touchbar shows the continue, step over, step into, restart and stop
![img_0890](https://user-images.githubusercontent.com/16316305/51355282-4789f080-1a7c-11e9-9531-2d391e931df9.JPG)
Image taken from the latest standard release

### Actual results 
That section of the touchbar shows empty
![img_0891](https://user-images.githubusercontent.com/16316305/51355298-5a9cc080-1a7c-11e9-89b0-9c77cff8603c.JPG)

VS Code version: Code - Insiders 1.31.0-insider (926cfe1c4ac6a438f8fa3c4f164219c7c4bf17b5, 2019-01-17T06:14:05.649Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by isidorn** [comment]
@weinand you have a mac touchbar, can you reproduce with latest insiders?
If yes let's inspect on your machine in the afternoon

fyi @bpasero

**Comment by weinand** [comment]
@isidorn Ok, let's do this.
BTW, there are lots of touchbar simulators for those poor souls that don't have one ;-)
E.g. https://sindresorhus.com/touch-bar-simulator/ or https://red-sweater.com/touche/.

**Comment by isidorn** [comment]
Hehe thanks

**Comment by bpasero** [comment]
The simulator is perfect to test this. This could be an Electron 3 regression too.

**Comment by isidorn** [comment]
@bpasero yeah I just verified that everything is good on my end regarding context keys so this is must be a Electron 3 regression. Forwarding to you

**Comment by bpasero** [comment]
@weinand do you see this as well?

**Comment by weinand** [comment]
I have my touch bar configured to only show F keys for VS Code (and I don't know how to change this behavior...)

**Comment by bpasero** [comment]
https://github.com/electron/electron/issues/16473

**Comment by bpasero** [comment]
@misolori can you help me out here, the issue seems to be that in newer versions of Electron, the size in touchbar buttons has changed. I noticed we use 100x100px versions for our touchbar icons (PNG) and this will now cause the buttons to appear very large, thus pushing the debug buttons out of the view.

All our touchbar icons end with `tb.png`:

![image](https://user-images.githubusercontent.com/900690/51472862-0004ac80-1d7b-11e9-81a1-62bc37dae173.png)

And if you make a change to any of them and run out of sources, you should see the touchbar reflect your changes. You can use the touchbar simulator in case you do not have a touchbar: https://github.com/sindresorhus/touch-bar-simulator.

When I remove all the transparent background around the back/forward icons, I get a better result compared to what we have now, but it is still not perfect. Maybe it would also be a good idea to revisit what Apple recommends in terms of icon sizes.

Thanks!

**Comment by misolori** [comment]
@bpasero thanks for doing the investigative work (saved me a bunch of time). And you were totally right about the icon sizes, PR has been created to fix this issue.
