### ISSUE TITLE
Opened Editors: distinguish structural change events from others

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6670]
I find it a bit crazy to refresh the entire tree every time there is any event on the stacks model. For example you get an event when the active group changes but that is not a structural change that does not require any tree updates. The same is true for an editor that turns dirty or is saved.

As much as the current approach is dead simple, I think we can prevent unnecessary work by looking at the event and then deciding what to do.

Maybe if it would help, I could add a flag to the aggregated event that would indicate if the change is structural or not?

Still, you would have to solve the issue independently for an editor turning dirty or not because there you have at least a slight UI change.

**Comment by isidorn** [comment]
Agree we should improve this - would not tackle it in debt week, assigning to June so we can experiment in debt week with your ideas.

**Comment by isidorn** [comment]
Ok, for the dirty events I need to figure out which open editor has updated dirty state, which means I need to go through all the groups and find editors which match a modifed dirty URI and refresh all those.

For your current model, for the group events I would need to manage listeners for groups (add them when new group added, remove them when group closed). In order to prevent this let's modify the aggregated event.

Can you please add a structuralChange flag? A model change event would have that flag, a group (which it does now) and an optional editorInput.
If the change is structural I will refresh the part of the tree belonging to the group.
If the change is not structural I would just refresh the open editor with the editor input in the group.

**Comment by bpasero** [comment]
@isidorn I pushed a change to include more details from the model change event:
* group: is always present
* editor: is optional and only present if the change is about an editor
* structural: indicates if the change is structural or not

You can have non-structural events for only groups (e.g. rename of a group, set active) and you can have non-structural events for editors (e.g. set active).

Btw I am now also emitting a model change event when the input gets dirty (I was not doing so before), so I believe you should be OK even for dirty state.

Let me know how it goes 👍

**Comment by isidorn** [comment]
Awesomeeeeee

**Comment by bpasero** [comment]
@isidorn also I think you can drop your code that kicks off the tree refresh from file/untitled dirty events because I now also send a model change event when input gets dirty or saved (it is a non-structural change event with the input within).

**Comment by isidorn** [comment]
@bpasero yes I just killed it, code looks much cleaner now! Thanks for improving the events
All looks good - just tested it!

**Comment by bpasero** [comment]
@isidorn nice

**Comment by isidorn** [comment]
This should work nicer now - notice that I have removed the timeout, so the double click behavior is broken again - looking into if I should fix that again with a timeout or with something else. Ideas are welcome :)

**Comment by bpasero** [comment]
@isidorn timeout worked for me for the doubleclick case in the explorer

**Comment by isidorn** [comment]
Also before we could aggregate events because they would all cause the same thing (the tree to fully refreshed). Now I am respecting each event and doing a minimal refresh needed for that event. Which makes sense I believe

**Comment by bpasero** [comment]
@isidorn it might still make sense to call refresh from a timeout of 0 because e.g. closing all editors at once will cause a lot of model change events.

**Comment by isidorn** [comment]
But my events can now be mutualy disjoint, so I would need to inspect events and sum them up to figure out which refresh is needed to satisfy all the events.

That is, if we do a minimal refresh per event we must respect every event and do not do a timeout

**Comment by bpasero** [comment]
@isidorn well not sure how fine grained you now react to events, but could you not throw all structural events into the delayed tree refresh and handle the non structural ones without delay?

**Comment by isidorn** [comment]
@bpasero turned out to be a bit more complex but I think it is now behaving fine. Check it out and let me know what you think.

Overall, strucutral tree updates are doen with a 250ms, non structural immediatly. Structural changes are fine grained, but we summerize them up so they are still done with a delay.
If the tree is rendered for the first time (viewlet opened) - it is done immediatly
