### ISSUE TITLE
Last node in Settings TOC collapses when clicked instead filtering results

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#66796]
Issue Type: <b>Bug</b>

- In the settings editor, search for something
- Click on the last item in the toc

Instead of showing results filtered to that node, the toc collapses

VS Code version: Code - Insiders 1.31.0-insider (2283b29c695da3163fd4b524617dabcfb8298bbe, 2019-01-18T09:36:56.939Z)
OS version: Darwin x64 15.6.0

![settings](https://user-images.githubusercontent.com/16890566/51435301-6d082d00-1c29-11e9-876d-03a85d7df349.gif)

**Comment by roblourens** [comment]
This is very weird. There are two click listeners on the tree, one for focus and one for collapsing rows. The first one is triggered, which causes the list to rerender, then the second one triggers, and it seems confused by the fact that its original target is not in the dom anymore, because it claims to be triggered on a totally different row than the actual original target. Not sure why that happens but I will work around it for now by waiting until the event handlers are done to actually handle the event.

**Comment by roblourens** [comment]
If I remove the workaround, I can't repro the original issue. Maybe it was fixed by an electron update or something else.
