### ISSUE TITLE
Wrong indentation after chained methods

### ISSUE THREAD

**Issue by kiyutink** [microsoft/vscode#66816]
- VSCode Version: 1.30.2
- OS Version: Windows 10

Steps to Reproduce:

1. Chain methods and end it with a semicolon
2. Press enter - the caret is indented but it shouldn't be
gif: https://i.imgur.com/I2STjrm.gif

![i2stjrm](https://user-images.githubusercontent.com/5047891/52019118-1a622700-24ed-11e9-8805-0de3a80ff426.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules and only support limited code styles), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment or use auto formatting (`editor.formatOnType`, `editor.formatOnPaste`). As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like (https://github.com/microsoft/vscode/issues/19847, https://github.com/microsoft/vscode/issues/34621 or https://github.com/microsoft/vscode/issues/66235).
