### ISSUE TITLE
Debian/Ubuntu linux installer  does not use https by default in the sources.d file.

### ISSUE THREAD

**Issue by iemejia** [Microsoft/vscode#66865]
When installing the deb file it registers a .list that does not use `https` by default, even if the server support https. It would be better to have https as the default transport.

**Comment by Tyriar** [comment]
This is fine, https only provides the illusion of security and often requires an additional package to support https. https://whydoesaptnotusehttps.com/

**Comment by iemejia** [comment]
Well it is not just the illusion of security and many of the arguments in that website are argueable. A read of the [recent discussion in hacker news](https://news.ycombinator.com/item?id=18958679) is worth. My point is that the server already supports https, and if I change the vscode list file in sources to https it works perfectly both in ubuntu and debian. This change looks minimal and the unintended consequences seem not terrible. But well up to you.

**Comment by Tyriar** [comment]
@iemejia I had the same discussion with people where I was arguing your position for the setup page https://code.visualstudio.com/docs/setup/linux

The problem is that `apt-transport-https` doesn't ship on many distros so it adds an extra dependency, it really seems like it doesn't matter much based on all I've read and been told and it's not worth adding the extra dep.
