### ISSUE TITLE
Upgrade why did change my theme

### ISSUE THREAD

**Issue by RDzdf** [Microsoft/vscode#66890]
Issue Type: <b>Feature Request</b>

Upgrade why did change my theme, why? why? Your own theme is the same as shit! Don't you know?

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:12:19.495Z)
OS version: Windows_NT ia32 10.0.17134

**Comment by sandy081** [comment]
> Your own theme is the same as shit! Don't you know?

@RDzdf I am afraid such kind of comments are not expected.

We will look into your issue that why your custom theme got replaced after upgrading.

**Comment by usernamehw** [comment]
What about making those theme files (in app folder) read-only to prevent this in the future?

**Comment by aeschli** [comment]
Files in the application folder are owned by the application. What you see is the expected behavior. 

There are several ways to create your own theme:
- create a theme in the user extension folder
https://code.visualstudio.com/docs/getstarted/themes#_creating-your-own-color-theme 
- define & customize a theme in the user settings: https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme

@joaomoreno can/should the installer detect that there has been user modification in the app files?
