### ISSUE TITLE
Filter widget eating up backspace

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#66955]
VS Code version: Code - Insiders 1.31.0-insider (23f534b7b7f439fc39755821ff99ac50fcc10765, 2019-01-22T06:13:01.312Z)
OS version: Darwin x64 18.2.0

Cmd+Backspace doesn't work in explorer. No error on devtools.

**Comment by isidorn** [comment]
Great catch.

**Comment by isidorn** [comment]
I can reproduce this.
And the issue here is that the Backspace key is not being caught by the `keybindingService` [here](https://github.com/Microsoft/vscode/blob/3117f30f3d6b6d9f3174241bebe2373e58ab7ad3/src/vs/workbench/services/keybinding/electron-browser/keybindingService.ts#L324)

All the context are correct, but the key simple is not caught by the keybinding service. I can reproduce this for all trees, but not for lists. So I bet that @joaomoreno you are eating the backspace for the filtering.

The backspace should only be active if I actually typed something to fiter. Also if no other moddifier is pressed.
It should be registered like all other commands.

**Comment by isidorn** [comment]
Verified this works nicely with latest out of source -> verified
