### ISSUE TITLE
Add environment variable support to workspace file and launch.json

### ISSUE THREAD

**Issue by 9527KGG** [Microsoft/vscode#67005]
Currently, if workspace file or launch.json have environment variables, etc

{
        "folders": [
                {
                        "path": "$TEST_ENV/test_dir"
                }
        ],
        "settings": {}
}

, vscode does not work.

Please add environment variable support to workspace file and launch.json

**Comment by weinand** [comment]
This is already possible. Please read this: https://code.visualstudio.com/docs/editor/variables-reference

**Comment by JaDaar** [comment]
OK

On Jan 23, 2019 1:39 PM, "Andre Weinand" <notifications@github.com> wrote:

Closed #67005 <https://github.com/Microsoft/vscode/issues/67005>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/67005#event-2092502929>, or mute
the thread
