### ISSUE TITLE
左侧资源管理器怎么快速查找文件

### ISSUE THREAD

**Issue by zeroone2005** [Microsoft/vscode#67035]
Issue Type: <b>Feature Request</b>

文件在太多在左侧资源管理器中要快速找到一个文件并打开很麻烦。

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

**Comment by ddzy** [comment]
**Ctrl + Shift + P** 打开控制面板, 再delete掉'>'符号, 输入你想查找的文件名就行了

Please enter **Ctrl + Shift + P** to open the control panel, then press 'BACKSPACE' to delete the '>' in your keyboard. Finally enter the filename you want...

![issue_1](https://user-images.githubusercontent.com/33921398/51658561-5f64f580-1fe3-11e9-8cd1-13b6bbe3ac4e.jpg)

**Comment by zeroone2005** [comment]
不错，能找到文件。但是感觉不怎么方便，不知道有没有插件可以直接在左侧浏览器上直接搜索，更方便

**Comment by ddzy** [comment]
> 不错，能找到文件。但是感觉不怎么方便，不知道有没有插件可以直接在左侧浏览器上直接搜索，更方便

目前好像并没有这款插件, 你可以调整一下控制面板的快捷键, 调到你顺手的键位. 也可以给官方提个Feature.

Currently, there seems to be no similar plugin, I suggest you change the shortcut settings of the control panel. Or you maybe give a Feature advice to them.

**Comment by sbatten** [comment]
@zeroone2005 The explorer on the left now supports typing to search for files. You can also filter on type as well. Just focus the explorer and start typing. In order to use this feature, however, you must be on the latest insiders. https://code.visualstudio.com/insiders/

For now, you can press Ctrl+P or Ctrl+E to search files in the workspace
