### ISSUE TITLE
Open Editors: weird list changes when opening file in preview

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#67041]
Steps to Reproduce:

1. enable preview (its the default)
2. have some files opened pinned
3. open another file in preview mode

=> 🐛 I find the open editors list updates weird, the first element seems to change even though an element is just added to the end?

![before](https://user-images.githubusercontent.com/900690/51669827-90cec880-1fc5-11e9-91a4-15f3bdf0eb27.gif)

I think this is not a regression from stable.

**Comment by isidorn** [comment]
I just checked and this also happens in stable.
The issue here is that on the Open Editor change we immedatly add the element to the list but react with a delay to resize the list [here](https://github.com/Microsoft/vscode/blob/26d688fa9f3a875f3d2b04732f729319f6b68a29/src/vs/workbench/parts/files/electron-browser/views/openEditorsView.ts#L150)
Due to the delay the list does not change size, and briefly the second element appears as the first (thus the ugly flash at top).

We have to react with a dealy so we do not disrupt the double click behavior in explorer (you know the issue).

An alterantavie approach is to also delay adding the element to the list - I tried this and it works better visually. So I pushed it, try it out and let me know how it behaves for you.

**Comment by isidorn** [comment]
Good catch. Seems like my previous fix was not good, reverting it and going back to stable behavior.

The issue with the fix was that we were only changing the list wiht a timeout, and a pin event can come before the timeout is done, so we "pin" the wrong elemtn (since the opened element is still not in the list).
I could write some complicated code to make sure the events are processed in the correct order but for now will just go to the stable behavior
