### ISSUE TITLE
vscode will crash when you click results searched by regular expression many times

### ISSUE THREAD

**Issue by Lennon925** [Microsoft/vscode#67054]
- VSCode Version: 1.30.2

Steps to Reproduce:

-  Open a project using vscode.
- search by regular expression(alt+R), such as: \((([A-Z]*_){0,}[A-Z]*) ((==)|(!=)|(<)|(>)|(>=)|(<=)) ((([*&]?\w*(.)?)?(\w*)){1,})\)
- after searching finished, click the results one by one.
- vscode will crash for several times. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by chongchai** [comment]
Actually I got the same problem when view search results in project. 
I need search in a large project for refactor.

vscode version: 1.30.1
all extension disabled; yes

use an open source project to reproduce:
1. open linux source code in vscode (https://github.com/torvalds/linux)
2. open search viewlet
3. in the `files to include`, fill `./block`
4. search with regular expression `\((([A-Z]*_){0,}[A-Z]*) ((==)|(!=)|(<)|(>)|(>=)|(<=)) ((([*&]?\w*(.)?)?(\w*)){1,})\)`
5. after search finished, click results one by one
6. after several clicks, vscode will be hanged then stop working

I guess this problem is not related with regular expression since search is finished.
After click a result, it will open the file in the editor. Maybe rendering the file is hanged. 
Anyway this behavior get some bug. Hope you can fix it soon. Thanks.
@roblourens

**Comment by roblourens** [comment]
I see this too with some files. It seems to be catastrophic backtracking in your regex: https://www.regular-expressions.info/catastrophic.html

We use different regex engines between search/single file find, and it works when searching but not when the file is opened and we run the regex with the JS regex engine.

**Comment by chongchai** [comment]
Simplify regex is a solution for catastrophic backtracking. But may not  be useful to me. I use this regex to search what I need and I can't come up with a simplified regex.

>  it works when searching but hangs when the file is opened and we run the regex with the JS regex engine

@roblourens Can vscode provide a setting to control whether  to use JS regex engine?  Maybe user can choose to use other engines to avoid vscode being hanged.

**Comment by roblourens** [comment]
Unfortunately there is no way around this for us.
