### ISSUE TITLE
ViewsRegistery.deregisterView has no effect

### ISSUE THREAD

**Issue by gjsjohnmurray** [Microsoft/vscode#67067]
Issue Type: <b>Bug</b>

1. Close current workspace (Ctrl+K F)
2. From "File" menu, "Add Folder to Workspace"
3. Choose a folder on the local filesystem and click "Add"
4. Explorer panel appears but the "NO FOLDER OPENED" section remains.
![image](https://user-images.githubusercontent.com/6726799/51689686-0e5afe80-1fef-11e9-9cd7-0f45f6b68e35.png)

Repeating the test on 1.30.2 gives the correct behaviour. The "NO FOLDER OPENED" section disappears when the first folder is added to the workspace.

VS Code version: Code - Insiders 1.31.0-insider (50854c0a705745bbf50982fab3c30fd6bd1f7b19, 2019-01-24T09:15:00.061Z)
OS version: Windows_NT x64 10.0.16299

**Comment by isidorn** [comment]
@gjsjohnmurray thanks for nice steps and for using vscode insiders. I can reproduce this.
@sandy081 the issue seems to be that the [deregisterViews](https://github.com/Microsoft/vscode/blob/fd9fbbfd507d7db9eafd86fc746b574e1b86d790/src/vs/workbench/parts/files/electron-browser/explorerViewlet.ts#L94) call has no effect.
I would think this is a regression introduced by your dynamic enablement of views. Since I am doing exactly the same as in stable and it is no longer working. Thus forwarding the issue to you

**Comment by isidorn** [comment]
@sandy081 thanks for fixing
@gjsjohnmurray let us know if this solves the issue for you in next week's insiders build

**Comment by gjsjohnmurray** [comment]
Yes, now working properly in Insiders. Thanks.
