### ISSUE TITLE
show the time comsumed by a task

### ISSUE THREAD

**Issue by wang-bin** [microsoft/vscode#67094]
Issue Type: <b>Feature Request</b>

when a task finish, show the time elapsed at the bottom

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17763

**Comment by alpalla** [comment]
Hi, I'd be willing to help out with this request. Would external contributions be considered? If so, any pointers would be appreciated, thank you!

**Comment by alexr00** [comment]
I think this time elapsed is only meaningful for non-watching tasks, so the writing to the terminal would be somewhere around where `TaskEventKind.End` is fired: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L768
Before giving a PR I recommend that you give a proposal of how this would show with the terminal re-use message, since without some extensive changes(which I don't think is a good idea) the re-use message will come first.
