### ISSUE TITLE
Common functionality continually fails requiring VS Code restart

### ISSUE THREAD

**Issue by OngeUK** [microsoft/vscode#67119]
Issue Type: <b>Bug</b>

VS Code continually loses common functionality (Intellisense, go to definition, ability to git commit, etc) as well as all extensions stop working. I experience this several times a week - sometimes it happens within minutes of launching the application, other times many hours pass. This has been the case for several months, using various PCs - but all with the same extensions running.

I've been unable to find a sure fire way to replicate - this issue is sporadic but highly frequent. I assume it is related to extension(s) problems but haven't been able to identify the culprit. A restart fixes things, but this doesn't solve the issue long-term.

I have followed the [profile the running extensions instructions](https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions) and have managed to get 4 profiles where my VS Code has stopped working in this way. I don't understand how to interpret the data but hope it will be useful in debugging and narrowing down the cause of this issue.

Logs can be downloaded [here](http://cedar.staging2.cedar.digital/vs-code-logs.zip).
 or here -- [vs-code-logs.zip](https://github.com/Microsoft/vscode/files/2814918/vs-code-logs.zip)

If you require any further info from me, I'll be happy to assist.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.78GB (7.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|10.3.0
color-info|bie|0.5.0
npm-intellisense|chr|1.3.0
vscode-svgviewer|css|1.4.7
vscode-eslint|dba|1.8.0
gitlens|eam|9.4.1
tslint|eg2|1.0.42
prettier-vscode|esb|1.7.3
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-styled-components|jpo|0.0.25
vsliveshare|ms-|0.3.1134
debugger-for-chrome|msj|4.11.1
vscode-icons|rob|8.0.0
code-settings-sync|Sha|3.2.4
stylelint|shi|0.47.0
vscode-import-cost|wix|2.12.0

</details>

**Comment by alexandrudima** [comment]
The first profile:
* looks like a 10 minute profile! What stretch of the 10 minutes should I focus on?
![image](https://user-images.githubusercontent.com/5047891/52019812-4bdbf200-24ef-11e9-9b2f-c15a2bd6df4a.png)
* there isn't anything clearly wrong, except a huge amount of time spent in some complicated looking regex that appears to look for things with `<` ... Have you tried disabling the `auto-close-tag` extension? Perhaps that one is running a very expensive regex over your xml/html files?

---

The second profile:
* holy crap, 3.5 minutes spent in the same regex:
![image](https://user-images.githubusercontent.com/5047891/52019966-d4f32900-24ef-11e9-8228-493954325b56.png)

---

The third profile:
* 53 seconds in the same regex:
![image](https://user-images.githubusercontent.com/5047891/52020006-ffdd7d00-24ef-11e9-945e-77b58195ba5b.png)

---

The fourth profile:
* 16 minutes in that regex, this is ridiculous!
![image](https://user-images.githubusercontent.com/5047891/52020050-27cce080-24f0-11e9-8fb1-67beef072dbb.png)

---

And [HERE](https://github.com/formulahendry/vscode-auto-close-tag/blob/a42055d4feca2b8a5061a554c826c9aae3dc197a/src/extension.ts#L80) it is! It is caused by `vscode-auto-close-tag`. Since this extension is very popular, can you pretty please open an issue at https://github.com/formulahendry/vscode-auto-close-tag ... Unfortunately, it might be abandoned since the last change went in 6 months ago.... @egamma @kieferrm What can we do ... this extension is wildly popular and ridiculous slow...

**Comment by OngeUK** [comment]
@alexandrudima - many thanks for looking into this. As requested, I have raised a [ticket](https://github.com/formulahendry/vscode-auto-close-tag/issues/126) for this extension.

**Comment by alexandrudima** [comment]
@jrieken has this extension popped up in our monitoring?

**Comment by jrieken** [comment]
> @jrieken has this extension popped up in our monitoring?

Hell yes, it's the clear "#1" of the kill-the-extension-host hit list. We have made contact with the author but things are rolling slowing.

**Comment by jrieken** [comment]
Yeah, that was up for discussion. A bad review would be a start.
