### ISSUE TITLE
Word selection doesn't work as usual for "cursorWordStartRight"

### ISSUE THREAD

**Issue by catweazle9** [microsoft/vscode#67165]
- VSCode Version: 1.31.0
- OS Version: Windows_NT x64 10.0.17763

The issue described in the following bug report was fixed for cursorWordRight and cursorWordEndRight, but the exact problem remains when using **cursorWordStartRight**. It also fails for cursorWordStartLeft/cursorWordEndLeft:
https://github.com/Microsoft/vscode/issues/48046

Steps to Reproduce:

1. Enter this text in the editor: foo.bar();
2. Bind ctrl+right to cursorWordStartRight
3. Press ctrl+right a couple times, cursor moves to just before the dot, then to just after the dot.  Cursor should instead move directly from the 'f' to the 'b', as the '.' is a word delimiter rather than the start of an actual word.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
I have had to revert changes done for #48046 because they resulted in incompatibility with Visual Studio. 

In other words, I will not touch `cursorWordStartRight` any more. See [this test](https://github.com/microsoft/vscode/blob/67814cc6b11dad00ec264c1874f5e7b8bd4923b3/src/vs/editor/contrib/wordOperations/test/wordOperations.test.ts#L299-L313) and the note to never touch this command again in order to maintain any kind of compatibility with Visual Studio.

**Comment by catweazle9** [comment]
Surely you could add a user setting to choose the behavior, as suggested in https://github.com/microsoft/vscode/issues/51119

If Visual Studio behaves oddly perhaps a bug should be raised against Visual Studio. If you really need to provide compatibility with VS, surely VS Code could do that by default but still have a setting that provides 'sane' behavior for those who rely 100% on driving the editor via the keyboard.

**Comment by alexdima** [comment]
`cursorWordRight` is our command and can behave like we want. It appears it behaves OK.

`cursorWordStartRight` is the command that is implemented to behave like VS. We will not change it.
