### ISSUE TITLE
Some keyboard shortcuts in explorer don't work

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#67187]
- Select folder in explorer
- Press cmd+alt+f
- The wrong folder is populated in "Files to include", usually based on the current open file or the top level workspace folder

**Comment by roblourens** [comment]
Actually this is a larger issue with `getMultiSelectedResources`, other commands like "open to side" don't work with keyboard shortcuts.

First question, should the command get the resource that it was invoked on?

https://github.com/Microsoft/vscode/blob/c1c64f48f8b8bbff40dfb17c1bbf7793463dffcd/src/vs/workbench/parts/search/electron-browser/search.contribution.ts#L342

At least one problem is that `getFocus` returns an array here and the code expects a single item: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/files.ts#L50

I'm also confused about what should happen if the selection !== focused element?

**Comment by isidorn** [comment]
Good catch!

If the selection !== focused element we do the thing on the focused element.
We always check if the focused is inside selection, because if yes than the user wants it operated on the whole selection.
resource might be defined in some other cases (there are a lot of possibilities on where to invoke the command from).

Bottom line I fixed the issue and now it should work. The code is not super nice due to the various use cases how we call this get multi selected resources. However it is tested and seems to work as expected now imho
