### ISSUE TITLE
editor.fontSize

### ISSUE THREAD

**Issue by sereyn** [Microsoft/vscode#67214]
editor.fontSize property make extensions toolbar's textbox font bigger

**Comment by sereyn** [comment]
![image](https://user-images.githubusercontent.com/33748126/51832556-4ca93400-22f5-11e9-9ae5-9437eed552f3.png)

**Comment by sandy081** [comment]
@alexandrudima Is not this action should change only for the editors in the editor area?

**Comment by alexweininger** [comment]
Hi @sandy081, I am experiencing the same issue. I will try to provide all of the relevant information I can.  I've included my system info and installed extensions below. Here is a gif of the issue:

![vscode_issue_fontzoom](https://user-images.githubusercontent.com/12476526/53308082-325e6980-3853-11e9-82d1-72e1d8b7d42f.gif)

It happens when using the `Editor Font Zoom In` command.

The command `Editor Font Zoom Reset` puts everything back to normal.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.18343

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.83GB (6.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
TabOut|alb|0.1.6
spellright|ban|3.0.24
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
python-preview|don|0.0.4
gitlens|eam|9.5.1
vscode-npm-script|eg2|0.3.5
vsc-material-theme|Equ|2.7.0
prettier-vscode|esb|1.8.1
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.0.15
pythonsnippets|frh|1.0.2
vscode-pull-request-github|Git|0.4.0
beautify|Hoo|1.4.9
html-tag-wrapper|hwe|0.2.3
output-colorizer|IBM|0.1.2
error-gutters|Igo|1.0.1
oneline-selection|joe|1.0.1
types-autoinstaller|jvi|2.4.0
auto-comment-blocks|kev|1.0.1
vscode-github|Kni|0.30.1
MagicPython|mag|1.1.0
camelcasenavigation|map|1.0.1
markdown-shortcuts|mdi|0.11.0
gitignore|mic|1.0.1
vscode-pugbeautify|mrm|1.0.2
vscode-azureappservice|ms-|0.12.0
vscode-azurefunctions|ms-|0.15.0
python|ms-|2019.1.0
azure-account|ms-|0.8.0
material-icon-theme|PKi|3.6.3
polacode|pnp|0.2.2
gitlink|qez|0.4.5
java|red|0.39.0
code-settings-sync|Sha|3.2.5
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.1.3
vscode-java-debug|vsc|0.16.0
visual-snake-code|Zho|1.0.4

(3 theme extensions excluded)

</details>

**Comment by seiks** [comment]
I was able to reproduce this as well, on an empty user configuration.

Please note, @sandy081 that this seems to only happen in the Extension Marketplace search field. I tried with Find and Git panels and could not reproduce.

VS Code Version: 1.32.1 (05f146c7a8f7f78e80261aa3b2a2e642586f9eb3)
OS Version: macOS Sierra 10.12.6

**Comment by sandy081** [comment]
@seiks search field in Extensions view uses the editor and others you mentioned are simple input fields.
