### ISSUE TITLE
Test semantic selection for HTML/CSS

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#67254]
Test #65925

- [x] anyOS @roblourens
- [x] anyOS @alexr00

Complexity: 1

Run "Expand Select" and "Shrink Select" in any place in a HTML/CSS file. Make sure the selections make sense.

**Comment by alexr00** [comment]
@octref does this look correct? it seems like there should be a point where just the entire `p` tag is selected, instead of going from selecting the contents of the `p` tag to everything inside the `html` tag.
![expandselect](https://user-images.githubusercontent.com/38270282/51919218-45f8ea80-23e3-11e9-86e8-fb1743254e92.gif)

**Comment by octref** [comment]
@alexr00 Good catch. Fixed via https://github.com/Microsoft/vscode-html-languageservice/commit/00814bcf41c9e9cdbfa27f920371f67fa8dae090.
