### ISSUE TITLE
Rank index files higher in file search results

### ISSUE THREAD

**Issue by tophmey** [Microsoft/vscode#67312]
When using an index file inside a folder, I would prefer that index file be ranked by its parent folder's name.

eg, when searching for "foobar", a file "foobar/index.js" should be ranked higher than "foobarbaz".

Index files should be treated synonymously with the parent folder's name, and maybe even ranked above other exact matches.

**Comment by roblourens** [comment]
I don't really see a good way to do this because file search and ranking is language agnostic, and shouldn't know that 'index.js' files are special. It also is really just a personal preference, somebody else might want `package.json` to be boosted, somebody else wants something else. So I don't see a reasonable way to do this that won't get overly complicated.
