### ISSUE TITLE
Terminal much slower now

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#67327]
Checking the time it takes to create the terminal shows much slower times since January. 

Measure marks: https://github.com/Microsoft/vscode/blob/af608864808988ed5c6ef7259514d9386864f2b6/src/vs/workbench/electron-browser/workbench.ts#L774-L778

<img width="352" alt="screenshot 2019-01-29 at 09 33 27" src="https://user-images.githubusercontent.com/1794099/51894799-fe556d00-23a8-11e9-8ca8-f934a64453ed.png">

Report from the perf dashboard

**Comment by Tyriar** [comment]
@jrieken could deferring TerminalService have caused this? https://github.com/Microsoft/vscode/issues/65415

**Comment by jrieken** [comment]
I don't think so, it's in the range of 150ms and no single object creation can be that expensive... It should be easy to profile tho, the marks are sync, no promise inbetween

**Comment by jrieken** [comment]
Looks like a massive layout trashing party

<img width="800" alt="screenshot 2019-01-30 at 12 19 19" src="https://user-images.githubusercontent.com/1794099/51978039-48158480-2489-11e9-809e-2dd6e21124ca.png">

**Comment by Tyriar** [comment]
I can at least repro the forced layout here in 1.30 as well? It's happening because of these lines:

https://github.com/Microsoft/vscode/blob/b3ebb15a5f156e9f27185d1672b7b7b2d9daf873/src/vs/workbench/parts/terminal/browser/terminalTab.ts#L32-L33

The width and height are needed to give to the split view so it can do a layout. @joaomoreno am I doing anything wrong here?

The problems panel does something similar:

<img width="651" alt="screen shot 2019-01-31 at 9 59 32 am" src="https://user-images.githubusercontent.com/2193314/52074532-efa0be80-253e-11e9-8191-139a30738db2.png">

It might be easier to avoid this one @sandy081?

https://github.com/Microsoft/vscode/blob/b3ebb15a5f156e9f27185d1672b7b7b2d9daf873/src/vs/workbench/parts/markers/electron-browser/markersPanelActions.ts#L242-L251

**Comment by joaomoreno** [comment]
@Tyriar Why do you layout in the ctor? You should only layout the splitview when the `SplitPaneContainer` itself is laid out... layout calls flow from top to bottom and the only guy reading `offsetWidth` and `offsetHeight` should be the workbench itself reading the window's width and height. It's all top-down layout calls from there.

**Comment by sandy081** [comment]
@Tyriar Sure it can be avoided, will take a look at next milestone, as it is not causing this issue.

**Comment by Tyriar** [comment]
Yeah that's why, if I remove that layout new terminal looks like this:

<img width="658" alt="screen shot 2019-01-31 at 11 29 45 am" src="https://user-images.githubusercontent.com/2193314/52080009-ac991800-254b-11e9-828d-06a19e0e8316.png">

Will defer this as there's too many things that could break by tweaking this code.

**Comment by joaomoreno** [comment]
@Tyriar It is also a coincidence that your container is already in the DOM at ctor time. What I would do to the terminal is pass it a sensible default width and height and give it some (virtual) space before the first layout call comes along.

**Comment by joaomoreno** [comment]
Argh!

**Comment by intellix** [comment]
Not sure if it's the same issue but if I start typing too early in Terminal after opening it up, it'll run at about 0.01% performance and absolutely crawl and be totally unusable. I have to close that terminal, open another and only start typing when it's ready

**Comment by Tyriar** [comment]
Not sure I can do anything here since we need to know the dimensions of the panel before the terminal starts.
