### ISSUE TITLE
Grid: Increase/Decrease view size does not work

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#67366]
Refs #67308

* neither "Increase View Size" nor "Decrease View Size" seem to work for me
* I have assigned a keybinding to the commands so that I can focus a view and run the command

**Comment by ctf0** [comment]
same here :cry:

**Comment by sbatten** [comment]
@bpasero the command "works" in that it does resize, but it does not match the behavior of legacy layout because it does pixel resize instead of percentage. It also does not do orientation properly. However, these commands are broken in legacy layout as well. They always resize the editor no matter what part is focused.

@joaomoreno in order to properly implement this, I need to be able to resize a part on either dimension. Is this a fair request for the grid api since it already has resizeView?

**Comment by joaomoreno** [comment]
@sbatten Yeah... with https://github.com/microsoft/vscode/issues/62387 we can move this forward. As I tackle the grid this iteration we can revisit that.

**Comment by joaomoreno** [comment]
Actually I take it back, I'll close  #62387  and get you #77226.

**Comment by joaomoreno** [comment]
Turns out #77226 just fixes this issue! 💪

**Comment by sbatten** [comment]
fixes part of the issue, reopening to fix the rest

**Comment by joaomoreno** [comment]
@sbatten Cool!
