### ISSUE TITLE
Grid: Layout destroyed when problems panel is focused

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#67371]
Refs #67308

* have panel to the right
* make it large enough so that panel titles are visible
* click through elements as shown in the video
* 🐛 layout explodes at the end

![grid-tw](https://user-images.githubusercontent.com/900690/51904839-fa811500-23bf-11e9-9ca9-9146cfd8232d.gif)

//cc @joaomoreno

**Comment by sandy081** [comment]
@sbatten Not sure what do you mean by offscreen here. Tree is properly placed inside the tree container without any absolute positioning. I do not understand how it breaks the layout.

**Comment by benrosenblum** [comment]
This occurs for me with the panel on the bottom as well.

**Comment by sbatten** [comment]
@sandy081 
![image](https://user-images.githubusercontent.com/6561887/52655409-5eddc180-2ef4-11e9-85be-dfd87e32ebe5.png)

There are 2 divs in the problems pane. One that contains the message and another empty one of the same height. When the message pane is visible, the empty one is pushed offscreen. (really it starts at the top of the status bar after the first div). When not using grid layout, this likely doesn't break anything because we absolutely position every part and don't allow overflow to offset the workbench. However, grid layout is different and breaks due to the div that should be hidden.

**Comment by sandy081** [comment]
@sbatten So you say it happens only in grid layout? I will try it repro and see.
