### ISSUE TITLE
Open Editors shows vertical scrollbar when horizontal scrolling enabled

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#67441]
Issue Type: <b>Bug</b>

Testing #67275

It appears to grow/shrink with the number of entries, but forgets to disable the vertical scrollbar:

![image](https://user-images.githubusercontent.com/9205389/51929950-b6ab0180-23f9-11e9-8a87-c96e6f6be750.png)

VS Code version: Code - Insiders 1.31.0-insider (acc7365e41f9cb380e79bf78d7d102184f1ffe0d, 2019-01-29T06:14:22.700Z)
OS version: Linux x64 4.15.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (2 x 2194)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|5.77GB (0.47GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
tslint|eg2|1.0.42
beautify|Hoo|1.4.7
theme-karyfoundation-themes|kar|18.2.1
azure-account|ms-|0.8.0
lsp-inspector|oct|0.0.1
vscode-open-in-github|sys|1.10.1
ayu|tea|0.17.0

</details>

**Comment by joaomoreno** [comment]
This is because we need to reserve x pixels of space in the bottom, so the horizontal scrollbar doesn't overlap the last element. Moving to you @isidorn

**Comment by themowski** [comment]
Bumping this old issue because I'm seeing the effects in stable v1.33.1 on Win 10, and it's really noticeable / bad when only one editor/file is open:

![editor](https://user-images.githubusercontent.com/13295249/57075078-c31e4f00-6cb3-11e9-8575-4d94271e5612.png)

As you can see, the total vertical space is big enough for exactly 1 file, which is correct, but the reserved space for the horizontal scrollbar takes up about half of that space, and the file's entry ends up getting pushed up and effectively cut in half. This makes the file name difficult to read.

VS Code version: 1.33.1 (user setup)
OS: Windows 10

**Comment by olegbl** [comment]
> This is because we need to reserve x pixels of space in the bottom, so the horizontal scrollbar doesn't overlap the last element

The scroll bar still overlaps content (as visible in the screenshot in this bug report). So, it's introducing a new bug without solving the bug it's meant to solve :P

To solve both issues, what needs to grow by the height of the scroll bar is the *container* not the *content*.

**Comment by nitin2953** [comment]
### FIX: Set  `"workbench.list.horizontalScrolling": false`
