### ISSUE TITLE
Icon Theme Setting UI does not update when using `Preferences: Icon Theme` command

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#67458]
Testing #67283

When selecting from the dropdown in setting UI, the icon theme setting works fine:

![image](https://user-images.githubusercontent.com/4033249/51932666-6eb5bb80-23b4-11e9-9323-bd7ce04ac2d0.png)

However:

- Run `Preferences: Icon Theme` to select another icon theme
- Setting UI is not updated. You need to focus on the Setting UI to see the value updated. (Although the selected icon theme is already applied).

![image](https://user-images.githubusercontent.com/4033249/51932852-dc61e780-23b4-11e9-8322-14c9d423189e.png)

When I press enter, I expect both the File Explorer to update icons and the Setting UI update its value. But only the former happen.

**Comment by aeschli** [comment]
It's a issue with the settings UI. It needs to listen to schema changes

IConfigurationRegistry.onDidSchemaChange

**Comment by roblourens** [comment]
Not a regression, this just happens when that setting is focused, then is changed somewhere else. We don't refresh the view when a setting is focused to not step on your ongoing edits. And it doesn't know whether the change event came from a user edit somewhere else, or if it's just a delayed change from the settings editor earlier.

So hopefully people don't do this exact thing too often. It should fix itself as soon as focus goes off that select box.
