### ISSUE TITLE
Setting UI can get into broken state for Icon Theme change

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#67462]
Initial state

![image](https://user-images.githubusercontent.com/4033249/51933303-dae4ef00-23b5-11e9-9d7c-dea6e4afde9e.png)

After running `Preferences: Icon Theme`, select a new theme, and reload:

![image](https://user-images.githubusercontent.com/4033249/51933362-0071f880-23b6-11e9-8f4e-86ed5e46ab92.png)

![image](https://user-images.githubusercontent.com/4033249/51933392-1384c880-23b6-11e9-9ad6-ee66777a534a.png)

Plain text editor:

![image](https://user-images.githubusercontent.com/4033249/51933448-31522d80-23b6-11e9-974e-25b49e832e0a.png)

![image](https://user-images.githubusercontent.com/4033249/51933451-357e4b00-23b6-11e9-9602-9c74e2cda9e3.png)

Additionally:

- Try to uninstall Nord theme while it's active
- Continue to change the Color Theme and Icon Theme using the Setting UI for a few times
- Run a "Reload"

VS Code can get into a broken state showing a "null box" on upper left area.

![image](https://user-images.githubusercontent.com/4033249/51933579-7a09e680-23b6-11e9-9909-8aab3a72972b.png)

**Comment by aeschli** [comment]
Looks like a Settings UI issue.

**Comment by roblourens** [comment]
There are at least two bugs here

- Open settings editor, reload window. The theme and icon select boxes are empty and throw when you click them. Not sure why this is a regression, but we are not adjusting correctly when the themes are loaded.
- Edit a setting then immediately open a select box. We rerender the list and sometimes render a different setting with the template containing the open select box. This is a problem because now the open select box has an invalid state and throws when you hover an item. This is a regression apparently because the new tree is more likely to use a different template when rerendering.

**Comment by roblourens** [comment]
> Open settings editor, reload window. The theme and icon select boxes are empty and throw when you click them. Not sure why this is a regression, but we are not adjusting correctly when the themes are loaded.

Fixed with this issue

> Edit a setting then immediately open a select box. We rerender the list and sometimes render a different setting with the template containing the open select box. This is a problem because now the open select box has an invalid state and throws when you hover an item. This is a regression apparently because the new tree is more likely to use a different template when rerendering.

Fixed in #69297
