### ISSUE TITLE
Monaco API Request: Disable Sorting and Filtering of Suggestions list

### ISSUE THREAD

**Issue by tracksaw** [Microsoft/vscode#67473]
In our DSL we know exactly what list of suggestions we want to show given the current user input and the domain profile of the user. It is laborious to circumvent the default sorting and filtering of suggestions to enforce our desired display content and ordering.

### Feature Requested

Make sorting and filtering of suggestions optional, so we can turn it off easily.

**Comment by jrieken** [comment]
>  default sorting and filtering of 

The *default* sorting depends on `sortText` which is provided by the provider itself. Once the user types more, it means we want to narrow down the result set. Then `filterText` is used. This is the designed behaviour.

**Comment by tracksaw** [comment]
We use service calls to resolve suggestions for given user input, statement context, and domain profile. The algorithm used in the service is not merely an alphabetical match based on what the user typed. 

![bqleditor-search-for-m](https://user-images.githubusercontent.com/29378846/52064596-f3364480-2542-11e9-8dc5-7d9a147cc0be.png)

A trivial example is shown in the picture above, where the user has typed 'm' and the first Data Item match is "name"; the 4th is "maturity", which is alphabetically a better match to "m", but in this context is inferior.

When we have the results of the service calls we have complete set of suggestions that match, in the correct order of priority. We can enforce the desired desired display order in Monaco by tweaking the sortText and filterText etc.  but we found it easier to just turn turn the matching algorithm off.

**Comment by jrieken** [comment]
> We use service calls to resolve suggestions for given user input, statement context, and domain profile. The algorithm used in the service is not merely an alphabetical match based on what the user typed.

Yeah, that's what we do with npm-dependency suggestions. If you wanna own all of sorting and filtering you have to use the properties described above and then set your result set to incomplete - that means every keystroke will re-query for completions so that you can run your logic for `m`, `mk`, `mko`, etc. 

Tho turning this off isn't an options for us - language services are written to be queried once and they rely on us doing the filtering, users rely on how our filtering works, the IntelliSense model is built to merge the results of multiple providers which now all have to be tweaked (assuming a no-filter, no-sort provider is around).

**Comment by tracksaw** [comment]
> ... use the properties described above ... set to incomplete ... every keystroke will re-query for completions 

Yup that's what we did initially. 

For our DSL-editor purpose we have a single completions provider and it knows what results to return and in what order, so it was easier to turn the whole sorting and filtering mechanism off rather than do perverse things with sortText and filterText.
