### ISSUE TITLE
Debug N PHP applications: step over jumps to wrong one

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6757]
Refs: https://github.com/Microsoft/vscode/issues/6160

If you debug multiple PHP scripts at once, and step over a line in the one script, the other script gets revealed in the stackframe view.

**Comment by isidorn** [comment]
This is happening because the php adapter is first sending a `stopped` event before the response for `step` returns. I have created an issue for the PHP adapter here https://github.com/felixfbecker/vscode-php-debug/issues/37
Previously we had a workaround that would prevent this issue, but we have remoed this workaround due to other issues https://github.com/Microsoft/vscode/issues/5966

**Comment by bpasero** [comment]
@isidorn would appreciate if @weinand could verify on your machine because I am out until next week

**Comment by isidorn** [comment]
@bpasero there is still nothing to verify since we depend on the PHP debugger on this one

**Comment by bpasero** [comment]
Ah ok.

**Comment by weinand** [comment]
assigning for verification back to @bpasero
