### ISSUE TITLE
It took about 15-20 seconds to launch code after the updates

### ISSUE THREAD

**Issue by kook005** [Microsoft/vscode#676]
Hi,

After get the recent updates,  it took about 15-20 seconds to launch code every time which is painful.

My Os information:
Windows Server 2012 R2 Datacenter.
64-bit Operating system, x64-based processor.

**Comment by kook005** [comment]
When launch code, it stuck like below for 15-20 seconds and then show contents of the file.

![image](https://cloud.githubusercontent.com/assets/5075254/11411677/363801a2-9387-11e5-9cd7-2414b7f399c2.png)

**Comment by bpasero** [comment]
@kook005 can you try - once VS Code is up and running - to see if reloading the application is also slow. For that you can just trigger View | Command Palette | Reload Window.

If that action turns out to be as slow, we have a chance to run a profiler to see where the time is spent. For that - before reloading - run Help | Toggle Developer Tools, click Profiles, then press the Start button and run the reload action. After that, press the Stop button. You should get a list of function calls and their timings. You can export this report from the little "Save" button next to "Profile 1" on the left.

![image](https://cloud.githubusercontent.com/assets/900690/11416449/f23e2e22-940d-11e5-949f-247e0b82c663.png)

**Comment by bpasero** [comment]
This is #335

**Comment by bpasero** [comment]
To people hitting this issue: We might not be able to release a new version until next week. **But there is a workaround**: 

If you can start Code eventually:
* select File | Open Recent | Clear Items
* restart and things should be fast again

If you cannot start Code:
* close Code
* locate storage.json (see https://code.visualstudio.com/Docs/supporting/FAQ#_how-do-i-opt-out-of-vs-code-autoupdates for how to find it)
* delete the file or rename it
* start Code

Sorry for the trouble :heart:
