### ISSUE TITLE
Extension should show up in the installed extensions list as soon as it's installed

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#67603]
#66931

- Find extension, click to open its readme
- Clear extension query
- Click "Install" in the readme
- The extension should show up in the enabled list immediately if it doesn't require a reload

**Comment by sandy081** [comment]
Related to #68257

**Comment by sandy081** [comment]
Auto refreshing the extension list is expensive and can be confusing. Because this will also remove extensions from the list (uninstalled / disabled) and it might not be good experience. 

I think smarter approach is to provide a refresh button so that users can refresh the view when wanted.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/10746682/98912805-e049f580-24c6-11eb-8b16-6dd3a4a00233.png">
