### ISSUE TITLE
Debug hover widget is a little too short

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#67620]
- Hover some object with a few props
- See that it can be scrolled vertically when it doesn't need to be
- Sometimes, it even is scrolled down a bit when it first appears

![jan-30-2019 20-26-50](https://user-images.githubusercontent.com/323878/52030618-7c129900-24cd-11e9-9cc4-b38c1cc0fe76.gif)

**Comment by isidorn** [comment]
This is a known limiatation of the tree which I think @joaomoreno does not plan to fix. Forwarding to him either way.

**Comment by isidorn** [comment]
This seems to have been fixed in the meantime

![hover](https://user-images.githubusercontent.com/1926584/69858983-82aba180-1293-11ea-9633-727c798031fa.gif)

**Comment by roblourens** [comment]
Doesn't your gif show the same problem? You can scroll the widget when you shouldn't be able to.

**Comment by isidorn** [comment]
I understood this issue as the widget is too short and that can be seen in your gif since the scroll bar covers the last element. That part is fixed.
As for being able to scroll more than needed, we can not fix both with the current approach. So it is one or the other. Since I think it is more importnant to be able to see all the attributes I prefer the current approach.
If you would like we can reopen and rename this issue to cover the extra scroll case.
