### ISSUE TITLE
Custom data value format

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#67637]
Testing https://github.com/Microsoft/vscode/issues/67306

Why are the values items object literals and not simply and array of `string | number | boolean`

See

```
        "values": [
          { "name": "alerst" },
          { "name": "foo" }
        ]

```

**Comment by octref** [comment]
This is to leave space for other fields such as `documentation` or even `status` / `browsers`.

For example, now for `font-kerning`, we do suggestion of:

- auto
- normal
- none

But MDN has description for each value, so it really could be:

- auto (The browser determines whether font kerning should be used or not. For example, some browsers will disable kerning on small fonts, since applying it could harm the readability of text.)
- normal (Font kerning information stored in the font must be applied.)
- none (Font kerning information stored in the font is disabled.)
