### ISSUE TITLE
Explorer slower in restoring

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#67635]
Charts suggest that the explorer has gotten slower to restore (startup). This is even more pronounced when looking at the perf machine data in isolation. Other viewlets (search, scm, etc) do *not* show this, so I suggest to take this serious and not blame it on the way we measure

The event is `willRestoreViewlet`.

<img width="423" alt="screenshot 2019-01-31 at 11 20 22" src="https://user-images.githubusercontent.com/1794099/52047852-36e07c80-254a-11e9-9c51-b5845ad1d70b.png">

**Comment by isidorn** [comment]
Here's the times on my machine after running 5 times and doing an average:

|   |      Master      |  1.30 release |
|----------|:-------------:|------:|
| full time to constrcut explorer(with open editors) | 122ms | 80ms
| time to render explorer body (thus creating tree) |  31ms |   18ms |

So the creation of the tree got 13ms slower. Now I am investigating what caused the other 30ms degredation.
If the creations of the tree got a bit slower but the resolving and other operations are faster that should be fine since the actual creation of the viewlet is not something percieved by the users. But the actual time it took the explorer to be ready (includes resolving and revealing items which is not counted in this measurment).
Will post some more numbers soon.

**Comment by jrieken** [comment]
Question for @joaomoreno is if all places that use the new tree construct slower? Like the problems panel or the extensions viewlet. Telemetry suggest no but then I don't understand the times being slower. 

> Also note that the willResolveExplorer does not take into account contruction speed.

And did it do that before? Where do those 40ms come form?

**Comment by jrieken** [comment]
There is 40ms extra creating the explorer (https://github.com/Microsoft/vscode/issues/67635#issuecomment-459310004). I am not sure if that includes the 13ms that's spend in creating the tree (renderBody), which would 2 trees so 26ms...

**Comment by isidorn** [comment]
Yes, this includes the 13ms that's spent in creating the tree. However Open Editors is not the tree, it is a list, so not sure if it takes 13ms also, have to check.

**Comment by jrieken** [comment]
> @isidorn had the right idea. He says we should actually measure how long it takes for the Explorer to be created, tree.setInput() to be completed and expansion state to be restored.

Honestly, I believe it used to be like that way back. Just make sure the promise that's [awaited here](https://github.com/Microsoft/vscode/blob/5aaf8173b33ecb2df7f2b836fa85813ec6df5b75/src/vs/workbench/electron-browser/workbench.ts#L767-L770) resolves only after the explorer is done-done. 

That obviously means the chart goes up, but it's also the honest measurement, eg. the one that you as a user observe.

**Comment by jrieken** [comment]
> There is no discernible difference in willRestoreViewlet ✔️

How do we explain the chart creeping up?

**Comment by joaomoreno** [comment]
> How do we explain the chart creeping up?

The tree was definitely doing more work yesterday than today. https://github.com/Microsoft/vscode/commit/b1d8e8dca9116f60e32e60539aba615f207eb129 fixed that. :crossed_fingers:

**Comment by jrieken** [comment]
> This difference is also why I say above that the measurement doesn't translate well between the two versions.

Understood. Last thing that we should understand is how @isidorn got his numbers https://github.com/Microsoft/vscode/issues/67635#issuecomment-459310004 and if calling the ctor is actually slower or not (I believe that was measured using the cpu profiler)

**Comment by isidorn** [comment]
My numbers same as @joaomoreno were measured using the cpu profiler (`console.profile` trick you showed me). I believe I saw the slowdown because my machine is simply slower than Joaos desktop linux. Though what I measured is the subset of what Joao measured (I only checked explorerCreate) and Joao meassured everything between two profile ticks so that could be another source of difference.

**Comment by jrieken** [comment]
> I believe I saw the slowdown because my machine is simply slower 

I don't understand that. You did test two different versions on that same machine? Are you saying the 0.7ms @joaomoreno sees is 13ms on your machine (18 times slower)?

**Comment by isidorn** [comment]
Looks like time is going down for stable. Closing issue
![Screenshot 2019-03-14 at 17 06 47](https://user-images.githubusercontent.com/1926584/54372444-9cf90d00-467b-11e9-91ac-5b05681365e4.png)

**Comment by joaomoreno** [comment]
:clap:
