### ISSUE TITLE
Explorer multi selection expands/collapses nodes

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#67648]
* open explorer
* `alt+click` (or depending your config `cmd+click`) multiple nodes
* :bug: folders expand/collapse making multi select hard

![jan-31-2019 15-25-59](https://user-images.githubusercontent.com/1794099/52060484-93ed2a00-256c-11e9-9b07-8fe44c4f6a97.gif)

**Comment by isidorn** [comment]
Good catch, the issue here is that you have alt set to multi select modifier. For cmd it works fine.

@joaomoreno the problem is that the list does not have an instance of the configuration service so we can not check if the user changed alt to be multi select here
https://github.com/Microsoft/vscode/blob/70160d0e580d0588e37c93fe8724014d76b00939/src/vs/base/browser/ui/list/listWidget.ts#L478

**Comment by joaomoreno** [comment]
@isidorn Oversight from https://github.com/Microsoft/vscode/commit/c1ae93ef0acef242b04618227b217519142430a3

**Comment by joaomoreno** [comment]
@jrieken Great catch!
