### ISSUE TITLE
SF Mono gives bold font and fontWeight does't not help

### ISSUE THREAD

**Issue by xiaohk** [microsoft/vscode#67666]
- VSCode Version: 1.30.2
- OS Version: macOS Mojave 10.14.2

Steps to Reproduce:

1. Set `"editor.fontFamily": "SF Mono"` → Text are all bold
2. Set `"editor.fontFamily": "SFMono-Regular"` → Text are regular, but comments are still bold

Does this issue occur when all extensions are disabled?: Yes

I have encountered some issues for setting up SF Mono font in VS Code.

## Method 1

Add the following configuration in `settings.json`

    "editor.fontFamily": "SF Mono"

[![enter image description here][1]][1]

The font seems to be bold, and changing `"editor.fontWeight"` to `100` doesn't help.

## Method 2

    "editor.fontFamily": "SFMono-Regular"

[![enter image description here][2]][2]

The texts have regular font weights now, but the comment is still bold.

## Method 3

Try to configure the comment text separately.

    "editor.fontFamily": "SFMono-Regular",
    "editor.tokenColorCustomizations": {
        "textMateRules": [
          {
            "scope": "comment",
            "settings": {
                "fontStyle": "normal"
            }
          }
        ]
    }

[![enter image description here][3]][3]

It seems configuring comment texts to `normal` gives them regular font weight.

  [1]: https://i.stack.imgur.com/Fi76u.png
  [2]: https://i.stack.imgur.com/bXY1F.png
  [3]: https://i.stack.imgur.com/bYMAR.png

**Comment by alexandrudima** [comment]
I am not 100% sure how Chromium selects the fonts. I can only speculate from your experiments that even when specifying "SFMono-Regular", and having italics, Chromium ends up selecting "SF Mono" again or perhaps some variant of "SF Mono" with italics, that is also quite heavy (looks bold).

I think your workaround of making comments not be italics is solid. However, there is not really any code change we can do in vs code, since we simply pass over the font configuration to Chromium and it does the font selection. Perhaps you can create a standalone web page which reproduces the problem and open an issue against them.
