### ISSUE TITLE
Freeze with problems panel with quick fixes 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#67694]
**Repo**
1. With the tslint plugin extension installed
1. Run `tslint --init` in an empty folder
1. Now create a TS file:

```ts
const foo = 123;

food
food
food
// repeated about 200 times
food
```

1. Open problems panel

**Bug**
Entire app freezes

**Comment by mjbvz** [comment]
The freeze is in `mainThreadHeapService` inside `_doTrackRecursive`.

The size of the `stack` array becomes insanely large here. Possibly a circular reference?

**Comment by mjbvz** [comment]
Here's what I think is happening:

1. problems panel requests code actions for entire document range.
1. Because tslint is installed, we include a `fix-all` action with each of the diagnostics
1. each of these fix all actions includes 200+ edits to the file.
1. This means that the resulting object we pass to the heap service includes something like 200 edits for each of the 200+ errors, i.e. it is really big

I don't think the markers panel should requests quick fixes for the entire document. Can we make this lazy instead, like how we request errors while moving the cursor through a file?

As a workaround for now, we could also cap the number of code actions that `getCodeActions` returns

**Comment by jrieken** [comment]
> @jrieken Do we need to call trackRecursive on code actions in mainThreadLanguageFeatures? 

We need it for command arguments. When an "old" code action aka command comes it we track that because the arguments for that command aren't send to the main but stored on the ext-host side. Once the code action gets GC'ed (on the main side) we let go off the arguments.

One trick would be to know if we have to do that, e.g a "modern" code action using text edits doesn't need this at all. But that only fixes half the problem, e.g old code actions still exist. A real fix would be the introduction of a proper lifecycle - we have done that with [completions](https://github.com/Microsoft/vscode/blob/5aaf8173b33ecb2df7f2b836fa85813ec6df5b75/src/vs/editor/common/modes.ts#L458).

**Comment by sandy081** [comment]
To show light bulbs, problems panel is making single request **per visible file** to get code actions for complete file and compute it for each entry with the received data instead of asking code actions for each problem entry. 

@mjbvz I used the same example as yours with 250 problems and I do not see any freeze.

![kapture 2019-02-01 at 10 06 22](https://user-images.githubusercontent.com/10746682/52113310-45da3400-2609-11e9-999b-52b059109c76.gif)

Is there a different example to try out?

**Comment by mjbvz** [comment]
Make sure you have the tslint plugin installed and have recommended tslint config (tslint —init)

I don’t think we should be making these requests eagerly. Even without this bug, that’s a lot of extra communication and cycles for

**Comment by sandy081** [comment]
Changed the strategy to fetch code actions as follow

- Selected
- Focused
- Hover for 300ms
- Context Menu
- Triggered from Keyboard 

Also I fetch code action per marker now and it is triggered only once per marker for all above events.

**Comment by jrieken** [comment]
I have also pushed a change that gets rid of `trackRecursive` making it explicit (`trackObject`). This ensures we only track objects of interest and stop traversing arbitrary object trees
