### ISSUE TITLE
VS Code theme style is added to text copied to the clipboard as rich text instead of plain text. 

### ISSUE THREAD

**Issue by bermlee** [microsoft/vscode#67702]
Issue Type: <b>Bug</b>

1. Copy text, paste into Word or GMail or any other rich-text editor. 
2. Result: White on Black text in the font of VS Code's interface. (Or whatever the current theme is)

Expected: plain text pasted only.

Also opened before by @alex-jitbit
https://github.com/Microsoft/vscode/issues/63154
Reported as a "feature" that can be turned off by @rebornix, and indeed it can be turned off with "Editor: Copy With Syntax Highlighting"

HOWEVER, I believe that this should NOT be default behavior, and at the least believe that the "text background" should NOT be copied along with it, and the un-highlighted text be turned to black when copied as rich-text in the clipboard. 

Platform: Windows

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:54:13.295Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (6.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-autohotkey|sle|0.2.2

</details>

**Comment by ryanoshea** [comment]
Most programs copy and paste rich text where possible, and some of the nice ones (Chrome, Office) offer a paste-as-plain-text functionality on the assumption that what's in the clipboard has both rich and non-rich versions. I think the current setting is a sensible default.

**Comment by rebornix** [comment]
You can turn this feature off by `editor.copyWithSyntaxHighlighting`.

**Comment by moxley** [comment]
> Most programs copy and paste rich text where possible, and some of the nice ones (Chrome, Office) offer a paste-as-plain-text functionality on the assumption that what's in the clipboard has both rich and non-rich versions. I think the current setting is a sensible default.

Most programs are not code editors.

I can think of many reasons how this "feature" is a bug, but no reasons why this is useful.

VS Code Version: 1.38.1
OS: MacOS 10.14.6

**Comment by mhkeller** [comment]
I also think the default should be to copy as plain text since that is my most common use case – I'm pasting into chat, email, Google Doc and I don't want my syntax theme in those environments. I can't think of a common use case where you want the opposite.

**Comment by Lemmingh** [comment]
Take a look at:

* #3518

"Copy with syntax highlighting" got **hundreds of** thumbs up in 2016. (That issue was locked in 2017.)

But your "Copy as plain text" only gets **three** now. (It's three years since 2019.)

Which side wins? "Copy with syntax highlighting" should be the default. Indeed, VS Code writes both plain text and HTML into clipboard, and it's the **target application** that decides which format to paste. (<https://github.com/microsoft/vscode/issues/57577#issuecomment-421397605>)

**Comment by alex-jitbit** [comment]
@Lemmingh thumbs-driven development, huh...

I guess most people who _don't_ need the black background when pasting stuff to Gmail, are not familiar with github and issue-trackers.

**Comment by alex-jitbit** [comment]
One more point: this is _not_ the default behavior in the "full" Visual Studio (non-code). The behavior should be consistent across products.

**Comment by bermlee** [comment]
what are some things we could do to make this more visible, aside from tweeting about it?

**Comment by Lemmingh** [comment]
As far as I'm aware, this issue is eventually about **the default value of the `editor.copyWithSyntaxHighlighting` setting** (#54155), and can become an **argument about preference**.

---

> thumbs-driven development

Let the data speak. This is reasonable under limited resource constraints. VS Code's wiki also conveys such idea.

Given that VS Code can even encourage users to join GitHub, I think the thumbs here should be sufficient.

I searched for similar issues. It appears roughly 100 for `false` and 200 for `true`, so the default value should still be `true` (With syntax highlighting).

---

> The default behavior of copying the entire display theme as-is, including the background seems inappropriate when copying code for even on-screen consumption that have the opposite light (or dark) background

This has been discussed many times:

* <https://github.com/microsoft/vscode/issues/3518#issuecomment-280731653>
* <https://github.com/microsoft/vscode/issues/20837#issuecomment-281456616>

---

Well, let's take a glance at how clipboard transfers data again.

A clipboard can hold **multiple** objects of different formats (called "MIME type" on web platforms). When writing to the clipboard (**copy**), an application is expected to put the data in many possible types. When reading from the clipboard (**paste**), an application selects the one it prefers.

When copying in VS Code, a few objects are written into the clipboard, usually plain text (`text/plain`) and custom metadata (`vscode-editor-data`). HTML (`text/html`) is also appended when "Copy With Syntax Highlighting" is enabled or requested.

---

Here are a few guidelines about interacting with the clipboard.

[Microsoft (Win32)](https://docs.microsoft.com/en-us/windows/win32/dataxchg/clipboard-formats):

> A window can place more than one clipboard object on the clipboard, each representing the same information in a different clipboard format. When placing information on the clipboard, the window **should provide data in as many formats as possible**.

[Microsoft (Xamarin.Mac)](https://docs.microsoft.com/en-us/xamarin/mac/app-fundamentals/copy-paste):

> To maximize the potential for sharing, the pasteboard can hold **multiple representations of a given item** (using a standard set of common data types), this **allow the consuming app to pick the version that is best suited for its needs**.

[Apple (UIKit)](https://developer.apple.com/documentation/uikit/uipasteboard):

> You can **provide flexibility for data sharing by providing multiple representation types** for a pasteboard item during a Copy or Cut operation. Various contexts within your app or other apps can then make use of an appropriate representation type.

[Apple (AppKit)](https://developer.apple.com/documentation/appkit/documents_data_and_pasteboard):

> You can create one or more pasteboard items, set data or data providers for types, and write to them pasteboard.
>
> You can retrieve pasteboard items from the pasteboard then **read the data for types you’re interested in**.

---

> the "full" Visual Studio

I'm afraid this is a misnomer. **Visual Studio** and **Visual Studio Code** are totally different products, just like Java and JavaScript are totally different languages. I'd suggest avoiding expressions like "full / slim Visual Studio".

---

Here are **Visual Studio**'s options.

![Visual Studio 2019 - Options](https://user-images.githubusercontent.com/43396014/141442253-b5a4fb49-a19c-415e-a31e-35114ff71306.png)

---

> in Microsoft Word, it's an extra menu step to select Keep Text Only

You can change the default in **Options** > **Advanced**.

![Word for Microsoft 365 - Options](https://user-images.githubusercontent.com/43396014/141442337-d1088578-8e6d-4251-890a-45c48459bb95.png)

**Comment by alex-jitbit** [comment]
@Lemmingh 
> Visual Studio and Visual Studio Code are totally different products, just like Java and JavaScript are totally different languages. I'd suggest avoiding expressions like "full / slim Visual Studio".

"Java and JavaScript" is a fine example of poor naming and a branding disaster.

Just like "Visual Studio and Visual Studio Code". So yeah, most people call it "full" Visual Studio. MS is getting what it deserves.
