### ISSUE TITLE
smart select should stop before and after brackets

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#67721]
re https://github.com/Microsoft/vscode/issues/67662

In JSON, JS, et al we stop before and after bracket blocks and I think we should do the same of CSS and its friends. Alternatively we align the other was around and change JSON and the default provider. 

@aeschli options?

**Comment by aeschli** [comment]
@octref Also just added before/after for CSS. I think we should go with that.
Let's avoid any options unless we get a major number of requests for it.

**Comment by octref** [comment]
The change I did add inner bracket range but removed the range including brackets. In the context of CSS it's less useful.

That's why I like Vim :wink: You can do `di{` and `da{`. Same strokes with options.

Together with the proposal of first expand to whole word instead of hump word, I want to keep the ranges list short. I don't want to have to press Expand 5 times to get what I want every time.

**Comment by aeschli** [comment]
Why do you think the selection with brackets is not useful? You might want to copy the block.
We should try to be consistent across languages.

**Comment by octref** [comment]
Because in CSS, it's much more common to do: 

```
.foo (add another selector here) {
  // rules
}
```

I have never had the need to copy the whole block. Even if I do, copying inner block is good enough. I just need to type another `{` before pasting.

I don't think we should add another range that will stay in the way of selecting the complete RuleSet.

**Comment by aeschli** [comment]
won't fix
