### ISSUE TITLE
double vs single down arrow is bad alternative to enablement

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6777]
#6536

The editor groups show a double down arrow to toggle between different editors of the group. When there is only a single editor in the group, the group shows a single arrow. Instead of changing the icon it should use enablement to show if there is more than one editor in a group.

**Comment by bpasero** [comment]
@stevencl @bgashler1 what are your thoughts on using enablement? my fear is that enablement is not strong enough indicator if you have a editor group that is not active (and the action shows with slight dimming).

**Comment by bpasero** [comment]
@bgashler1 assigning to you because it is related to https://github.com/Microsoft/vscode/issues/6756 too.

**Comment by joaomoreno** [comment]
Agree with disablement. The icon could look more like a 3 horizontal line icon like:

![image](https://cloud.githubusercontent.com/assets/22350/15506047/42799a98-21c6-11e6-9c64-11cf6d65e560.png)

**Comment by bgashler1** [comment]
I think we need to look at the long term of where this is going.  We introduced the single vs. double arrow because of tabs.  Having two different types of arrows for Open Editors isn't necessary with tabs disabled, but it can be helpful for tabs.  To be consistent we used them in both.

**Single Arrow**
Single arrow does not mean disabled.  It means that none of your editors are overflowing.  You can click on it to show you all editors in the list.  This is a convention in many text editors.

**Double Arrow**
Double arrow is the same as a single arrow, except that it means that one or more editors are overflowing.  This is particularly helpful for tabs, since we don't truncate tabs like other editors.  So someone will know immediately that not all of his/her tabs are in view in case she/he is wondering where something is.

**Isn't a single arrow useless for tabs-disabled scenarios?**
Obviously, using single and double arrows isn't necessary with tabs disabled, because by definition we can only show one "tab" at a time (i.e. if you have tabs disabled and more than one editor in any group, then that group will always be overflowing).  However, we decided to be consistent for reasons explained below.

**Why do we care about consistency if double arrows really only benefit tabs-enabled?**
Users have expressed many different preferences.  Some want no tabs, some want no working files, some want neither, and it's possible some will want both.  We needed to make our design and UI not break no matter what preference users elect.  So, we left it consistent so that meanings never change and so all workflows are possible.

**What could we do to improve this while still remaining consistent?**
We could remove single arrows in all cases when only one file is open.  This would benefit all workflows.  In tabs-disabled scenarios, this would mean you would only ever see a double arrow (for more than one file open) or nothing (for one file open or less).  Then we don't even need a disabled button, which keeps the experience lighter.

**Comment by bpasero** [comment]
We decide to not show the overflow when it does not apply.
