### ISSUE TITLE
Close/Minimize buttons on macOS

### ISSUE THREAD

**Issue by antpaw** [microsoft/vscode#67787]
Issue Type: <b>Bug</b>
Set "Accent colour" to gray (on very right) in "Gerenal" macOS settings. The buttons in the top application bar are now gray in every application, except in VS Code if you are on a "standard" dpi monitor.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

**Comment by saxc** [comment]
I have test this point. I can confirm the the color for the button is not set correctly.
But i'm not sure if this an issue from VS Code or Electron.

VS Code 1.30.2 and 1.31 Insider
macOS 10.14.3

**Comment by bpasero** [comment]
Please file against Electron: https://github.com/atom/electron

**Comment by antpaw** [comment]
@bpasero what electron version does Code 1.30.2 use?

**Comment by bpasero** [comment]
@antpaw stable is currently on 2.0.x but we will soon release with 3.1.2.

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
