### ISSUE TITLE
dragging an editor pins it

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6785]
#6536

* open two different files in two groups - both editors a preview-editors
* use the Open Editors and drop the editor from the _right_ group up to the _left_
* the editor is now pinned and not in preview anymore

**Comment by stevencl** [comment]
This is by design - we believe that the act of moving the editor indicates that the user intends to work with the editor. We also only support one preview editor in each group (that's part of the definition of a preview editor). So we couldn't drop a preview editor into a group already containing a preview editor and still persist it as a preview editor.

**Comment by bpasero** [comment]
Yes, intentional.
