### ISSUE TITLE
Allow to configure where editors open

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#6787]
#6536

* see attach gif
* from a folder I have two files pinned
* from the folder I know preview each file and I don't understand why determines their sort order

![may-24-2016 14-45-43](https://cloud.githubusercontent.com/assets/1794099/15504268/76d33b1c-21be-11e6-8050-91a3acbaa124.gif)

**Comment by bpasero** [comment]
@jrieken actually @joaomoreno was also confused by this but I am trying to mimic what a tab folder would do: the fact that an editor is in preview mode means that when you open another preview editor, we close the one you have first and then open the other one +1 to the right of the currently one (that is all "tabs" would open to the right of the currently active one).

In this case it looks weird because one preview editor closes from the end and the other opens to the side.

@stevencl @bgashler1 interested to hear your feedback here if you would expect the preview editor to move or stay at the position.

**Comment by joaomoreno** [comment]
It is not as much *moving* it as it is *placing* it.

I wouldn't find it so weird if *any* new editor would always open at the end of its group.

**Comment by jrieken** [comment]
> I wouldn't find it so weird if any new editor would always open at the end of its group.

that

**Comment by bpasero** [comment]
@joaomoreno @jrieken maybe you could comment on https://github.com/Microsoft/vscode/issues/6812

I am wondering if we should remove the whole idea of showing the preview entry under "opened editors". I think it would fix some issues.

**Comment by bgashler1** [comment]
See my comment at https://github.com/Microsoft/vscode/issues/6812#issuecomment-221348884

**Comment by bpasero** [comment]
@stevencl @bgashler1 I wonder if the user has tabs disabled if we should always just open tabs at the end of the list, similar to working files. Because if tabs are not enabled, the only spatial order that you have is the one in opened editors and there it might make more sense to always open at the end.

**Comment by joaomoreno** [comment]
I would keep away from separate behaviours when certain things are enabled or not. Remember that it has repercussions on others features such as <kbd>Ctrl Tab</kbd>.

**Comment by bpasero** [comment]
@joaomoreno actually Ctrl+Tab moves in MRU order, so the spatial order does not make any impact here.

**Comment by bpasero** [comment]
UX meeting outcome: we think we should provide a setting that allows a user to decide where new editors open. We need this already for tabs (to the right of active editor, to the left of active editor) and we could just let this be an enum with more values (to the beginning of all editors, at the end). Setting this to "at the end" would restore pretty much how working files used to behave.

**Comment by bpasero** [comment]
Discussion on settings names continues in https://github.com/Microsoft/vscode/issues/7643
