### ISSUE TITLE
Counter-intuitive sorting for completion items

### ISSUE THREAD

**Issue by Gama11** [microsoft/vscode#67887]
(tested with the latest Insider's Build: 1ab254dde53)

With the Haxe extension, there's some situations where completion items are ranked in a counter-intuitive fashion. Here's a simple completion provider to reproduce:

```ts
'use strict';
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
    vscode.languages.registerCompletionItemProvider('plaintext', {
        provideCompletionItems(doc, pos, token, context) {
            var range = new vscode.Range(new vscode.Position(0, 0), pos);
            return [
                {label: "Button - ui.Button", range: range},
                {label: "Button - hl.UI.Button", range: range}
            ];
        }
    });
}
```

Entering `ui.Button` results in the following sorting order:

![](https://i.imgur.com/7uyIdHh.png)

This is counter-intuitive to me for at least two reasons:

- `ui.Button` is an _exact_ match for a substring in the second item, yet it's ranked lower. I guess it's case-insensitive, but maybe it shouldn't be? :)
- Even apart from that, the match in the second case comes earlier in the string - shouldn't that lead to it ranking higher?

**Comment by jrieken** [comment]
Yeah, good feedback. The issue is that both matches are far in the back and that therefore hotting upper-case characters (`U`) counts stronger than hitting a lower-case character `u`. We can try to tweak the matching logic towards that but it's not always easy... 

One thing I am wondering is why you aren't using the `filterText` property. It seems like a good fit here.

**Comment by Gama11** [comment]
I assume you mean setting `filterText` to `ui.Button` and `hl.ui.Button`? Yes, in this particular situation that would help, but I think it would break other things. We actually spent quite some time coming up with a way to present types in completion such that:

- it looks somewhat organized
- sorting / filtering works as you'd expect

And came up with this `<unqualified type name> - <fully qualified name>` convention in the end. The problem is that there's two use cases from a user perspective, in one case he's filtering just by the type name and in the other by the the full path package, and both should work.

If I adjust the `filterText` to just the second part of the label, we end up with situations like this:

![](https://i.imgur.com/bTtzX97.png)

Here `ImportStatus` ranks second, even though the type names of items after it start with an exact match of the filter string, and it doesn't even contain `Json` other than in its package path. That shouldn't happen.
 
You can reproduce this with the following data. Not sure why `ImportStatus` ranks even higher now, but the result is still not desirable:

```ts
return [
    {label: "Json - haxe.Json", range: range, filterText: "haxe.Json"},
    {label: "ImportStatus - haxe.display.JsonModuleTypes.ImportStatus", range: range, filterText: "haxe.display.JsonModuleTypes.ImportStatus"},
    {label: "JsonAbstract - haxe.display.JsonModuleTypes.JsonAbstract", range: range, filterText: "haxe.display.JsonModuleTypes.JsonAbstract"},
];
```

![](https://i.imgur.com/5mR16Mf.png)

**Comment by jrieken** [comment]
> You can reproduce this with the following data. Not sure why ImportStatus ranks even higher now, but the result is still not desirable:

That's pretty easy to explain because the `Json` prefix is compare against the filter text - in all cases its a contiguous, case-perfect match but the first matches at offset 4 and other two as 12. That's how the sorting happens. The confusing parts are the highlight - because sorting/ranking happened against the filter text (which is different from the label) we use a [best-guess effort](https://github.com/microsoft/vscode/blob/f60e33e1826bc683f39b3e531bcd8d19263f286f/src/vs/editor/contrib/suggest/completionModel.ts#L213-L216) to compute some highlights for the label. We could stop doing that or at least be a more strict so that such confusing highlights don't happen.

Then stepping a bit back. How about crafting labels different here? Instead of having `label: "Button - ui.Button"` and `label: "Button - hl.UI.Button"` you could use the `detail` property (which actually added for these kind of scenarios)

**Comment by Gama11** [comment]
We also want to be able to narrow / filter completion items by their fully qualified name / package. I don't think `detail` would allow for that.

Also, `detail` is only shown for the selected item. This doesn't allow comparing items with identical type names type names at a glance like our current approach does. I think the Java extension (a langauge with a similar package system) takes a similar approach.

**Comment by jrieken** [comment]
> Also, detail is only shown for the selected item. 

Yeah, I noticed that and I think that's something we should change. Esp when having repeating labels that you cannot tell apart otherwise. 

> We also want to be able to narrow / filter completion items by their fully qualified name / package. I don't think detail would allow for that.

Hm, that needs some explaining. Assuming there is `ping.pong.Pung` and `peng.peng.Pung` won't I either type `Pung` (or any prefix) and then be offered both suggestions or won't I start typing with a package like `ping`?

**Comment by Gama11** [comment]
Ah, you meant making the label the fully qualified name - I thought you meant only having the type name there.

We did initially try having only the fully qualified name without the `TypeName -` prefix. However, due to the width restriction of the suggest widget, the type name would often not be visible at all with long / deeply nested packages. This is not very helpful:

![](https://i.imgur.com/87WQTq2.png)

The `TypeName -` prefix ensures that the most important part is always visible.

**Comment by jrieken** [comment]
No, that's not what I mean. More like having `languageServerProtocol` and `protocol` as separate suggestions which I can accept and on which the user or the extension can retrigger suggestions.

**Comment by Gama11** [comment]
Hm... if the `detail` is shown for every visible suggestion, that would probably result in a similar experience. We actually already do have separate suggestions for packages.

The main difference I can think of is that it would be a bit less "immediate". For instance here I immediately get relevant results from the `display` package, even though the package name hasn't been fully typed out yet:

![](https://i.imgur.com/pcXe3Kz.png)

How practical is it to show the detail for every item? I thought the main reason for limiting that to the selected item was to keep the amount of requests low (particularly with the LSP).

**Comment by jrieken** [comment]
What I tried to say is that detail should be shown for the focused item and for all other items with the same label but not generally for all items.

**Comment by jrieken** [comment]
@Gama11 Can you think about https://github.com/microsoft/vscode/issues/67887#issuecomment-540529848, e.g suggesting each segment of a fully qualified name separately, without having the full name for each - the full name would then be a good candidate for the `qualifier` that we are discussing in #39441

**Comment by Gama11** [comment]
We actually already have that (completion items for packages), but we still want to be able to filter the types themselves by the package they're contained in.

**Comment by jrieken** [comment]
> but we still want to be able to filter the types themselves by the package they're contained in (without having to first select a package).

Sure, you will have all package name segments and all types but always only the short name, e.g when having `foo.bar.Bazz` then you suggest `foo`, `bar` (inserts foo.bar), and `Bazz` (inserts foo.bar.Bazz or Bazz + import) or are you expecting that a user types `fbb` and gets `foo.bar.Bazz` suggested?

**Comment by Gama11** [comment]
> or are you expecting that a user types `fbb` and gets `foo.bar.Bazz` suggested?

Yeah, that's more or less how it works today:

![](https://i.imgur.com/kZ7EQRw.png)

You can also filter starting from one of the package segments in the middle / you're generally quite flexible with this approach:

![](https://i.imgur.com/4PtF3Fm.png)

**Comment by jrieken** [comment]
Ok - I understand now. All that creativity... The "problematic" case is when the "prefix" (like `hd`) should match across segments, like `^haxe.^display`. That's something my simplified approach doesn't cover. 

I haven't thought properly about filtering against the qualifier but I am afraid that it will make the problem more complex because we are adding another "input-variable". We should first understand why the filterText isn't sufficient
