### ISSUE TITLE
Allow third party extension points to be marked with `isDynamic`

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#67958]
Follow up on #66574

**Request**
Add a declarative API to mark a third party extension point as dynamic. This is needed by the markdown extension (#67574) and TypeScript extensions (#67575) which have custom extension points. I am doing work this iteration to make sure these extensions properly respond to extension changes

**Comment by mjbvz** [comment]
I propose a new `contributionPoints` section for `contributes`:

```json
{
  "contributes": {
    "contributionPoints" [
      {
        "name": "markdown.previewStyles",
        "isDynamic": true
      }
    ]
  }
}
```

**Comment by sandy081** [comment]
I think you can also give the schema of your contribution point which can be added to `contributes` section.

**Comment by mjbvz** [comment]
@sandy081 We've used this trick to define schema contributions but it would be good to standardize things: https://github.com/microsoft/vscode/blob/37fbae08a4391ec3078c35772ddd33dc3d4fa62f/extensions/typescript-language-features/schemas/package.schema.json

**Comment by alexandrudima** [comment]
After discussing this in the stand-up, starting with next stable all 3rd party extension points will be implicitly considered dynamic.

@sandy081 , you had a great analysis on this, can you please share the numbers here.

**Comment by sandy081** [comment]
I have done extensions analysis to know how many extensions are using external contribution points because of which they require reload when installed. Attaching the results from top 1000 extensions

<details> Top 1000 extensions

## Top 1000 Extensions

1. ms-python.python (`yamlValidation`)
1. vscjava.vscode-java-test (`javaExtensions`)
1. vscjava.vscode-java-debug (`javaExtensions`)
1. redhat.vscode-yaml (`yamlValidation`)
1. ms-mssql.mssql (`outputChannels`)
1. yzhang.markdown-all-in-one (`markdown.markdownItPlugins`, `markdown.previewStyles`)
1. magicstack.MagicPython (`//`)
1. Ionide.Ionide-fsharp (`outputChannels`)
1. jebbs.plantuml (`markdown.markdownItPlugins`)
1. vscjava.vscode-java-dependency (`javaExtensions`)
1. VisualStudioExptTeam.vscodeintellicode (`typescriptServerPlugins`, `javaExtensions`)
1. vector-of-bool.cmake-tools (`yamlValidation`)
1. jpoissonnier.vscode-styled-components (`typescriptServerPlugins`)
1. Pivotal.vscode-spring-boot (`javaExtensions`)
1. sbrink.elm (`outputChannels`)
1. goessner.mdmath (`markdown.previewStyles`, `markdown.markdownItPlugins`)
1. joaompinto.asciidoctor-vscode (`asciidoc.previewStylesEditor`, `asciidoc.previewStylesDefault`, `asciidoc.previewScripts`)
1. bierner.markdown-preview-github-styles (`markdown.previewStyles`)
1. ms-vscode.notepadplusplus-keybindings (`activationEvents`)
1. Ionide.Ionide-Paket (`outputChannels`)
1. kangping.luaide (`luaideConfig`)
1. bierner.lit-html (`typescriptServerPlugins`)
1. ms-vscode.vscode-typescript-tslint-plugin (`typescriptServerPlugins`)
1. cake-build.cake-vscode (`outputChannels`)
1. asvetliakov.snapshot-tools (`typescriptServerPlugins`)
1. AureliaEffect.aurelia (`folding`)
1. vstirbu.vscode-mermaid-preview (`markdown.previewScripts`, `markdown.markdownItPlugins`)
1. bierner.markdown-mermaid (`markdown.previewScripts`, `markdown.markdownItPlugins`)
1. Prisma.vscode-graphql (`typescriptServerPlugins`)
1. dgileadi.java-decompiler (`javaExtensions`)
1. Ionide.Ionide-FAKE (`outputChannels`)
1. docsmsft.docs-markdown (`yamlValidation`)
1. JaimeOlivares.yuml (`markdown.markdownItPlugins`)
1. mermade.openapi-lint (`yamlValidation`)
1. manuth.markdown-converter (`markdown.markdownItPlugins`)

## Markdown (8)

1. yzhang.markdown-all-in-one
1. jebbs.plantuml
1. goessner.mdmath
1. bierner.markdown-preview-github-styles
1. vstirbu.vscode-mermaid-preview
1. bierner.markdown-mermaid
1. JaimeOlivares.yuml
1. manuth.markdown-converter

## Typescript (6)

1. VisualStudioExptTeam.vscodeintellicode
1. jpoissonnier.vscode-styled-components
1. bierner.lit-html
1. ms-vscode.vscode-typescript-tslint-plugin
1. asvetliakov.snapshot-tools
1. Prisma.vscode-graphql

## Others
* yamlValidation (5)
* javaExtensions (6)
* outputChannels (6)
* // (1)
* asciidoc.previewStylesEditor (1)
* asciidoc.previewStylesDefault (1)
* asciidoc.previewScripts (1)
* activationEvents (1)
* luaideConfig (1)
* folding (1)

</details>

**Comment by sandy081** [comment]
@alexandrudima I see the need for this new contribution point because there could be extensions whose extension points might not be dynamic (just like language pack contributions)

So we can by default consider the external contribution points to be dynamic unless they tag them not.

What do you think?

**Comment by alexandrudima** [comment]
@sandy081 I would really like to avoid adding anything to `package.json` unless there is a clear necessity. IMHO we should reach to the owners of these extension points if we know them, and let them know that starting with next stable extensions are dynamic and ... that's it.

In other words, I suggest we don't support non-dynamic 3rd party extension points.

**Comment by sandy081** [comment]
Makes sense with the strategy to wait for the users.

@mjbvz Does the typescript plugin extension point is dynamic, it means can it be loaded without reloading VS Code when the new plugin is added?

**Comment by mjbvz** [comment]
Yes, the markdown and typescript extension points are now dynamic

**Comment by sandy081** [comment]
Closing this as this feature is not needed anymore.

**Comment by alexandrudima** [comment]
:+1: I've created #68603 to remember to remove the code entirely.
