### ISSUE TITLE
Theme selection menu does not work

### ISSUE THREAD

**Issue by Sendoo** [microsoft/vscode#68019]
- VSCode Version: 1.31.0
- OS Version: Windows 10 Home x64 1809

After installing a new theme, the theme selection menu does not work.
It helps reboot the editor.

![file_name](https://duaw26jehqd4r.cloudfront.net/items/39083b1K2k393c3j3O26/Screen%20Recording%202019-02-07%20at%2001.19.55.56%20PM.gif)

**Comment by kieferrm** [comment]
This seems to happen when a WebView editor has focus and you then select the `Color Theme` action from the dropdown.

**Comment by mjbvz** [comment]
I can confirm on windows. Doesn't seem to happen on MacOS in my testing

**Comment by mjbvz** [comment]
@sbatten This seems related to custom menus in some way as it does not reproduce on windows when using native menus.

The cause of the error is that the quick input is blurred right after is shows but after debugging through this I still can't find who is changing the focus. Is there any focus restoring logic in the menu implementation that could be changing the focus? Webviews also handle focusing somewhat differently than normal editors since the webview element itself is not part of the normal dom hierarchy

**Comment by sbatten** [comment]
@mjbvz yes the menus restore focus after being dismissed, but I'm curious why this only happens when a Webview is focused. The normal flow of restoring focus to an editor or any other item seems to work okay.

**Comment by mjbvz** [comment]
Can you point me to the code that does this? I confirmed that none of the webview specific focus events are fired while repoing this bug so I don’t think those are the problem. However webviews also have a different dom structure than normal editors and this could be an issue depending on how focus is tracked

**Comment by sbatten** [comment]
@mjbvz https://github.com/Microsoft/vscode/blob/a1ed35eaaf9eb4934fa9b10e9101219cb613170e/src/vs/base/browser/ui/menu/menubar.ts#L104

**Comment by mjbvz** [comment]
Ok, this is related to the `focusToReturn` in the contextMenu: https://github.com/Microsoft/vscode/blob/762b5f1acc1dea8c2cb95f6e11c631b71b8e8c3d/src/vs/platform/contextview/browser/contextMenuHandler.ts#L110

If I comment out that code, this no longer happens

Still not sure why this only happens for webviews. One possible cause is that focusing a webview element (the electron one, not our `WebviewElement` class) causes a blur event on the window (since you are focusing into another web context)

**Comment by mjbvz** [comment]
I think I've narrowed down the problem. For the following sequence of calls:

```js
webview.focus()
otherElement.focus()
```

The webview often ends up focused after a slight delay. Our code assumes that `focus` is a synchronous operation

I can repo this in electron 4.0.4 but it works as expected in electron 2.x. I have opened https://github.com/electron/electron/issues/16953 to track this issue

/cc @bpasero Since this is electron related

**Comment by mjbvz** [comment]
Moving out of February. Working around the electron issue bug is difficult since the timing is not consistent; sometimes the focus happens next tick and sometimes after a few milliseconds. One option is to just never call `.focus()` on webviews in these paths but I'm hesistant to spread webview knowledge to other parts of the codebase

@bpasero Do we have a list of VS Code's higher priority electron issues that this could be added too?

**Comment by bpasero** [comment]
@mjbvz there is no specific list of high priority issues currently, but we have a channel in the Electron slack where I can forward the issues you have in mind if you point me to them.

**Comment by mjbvz** [comment]
Thanks @bpasero. Here's the upstream issue: [electron/electron#16953](https://github.com/electron/electron/issues/16953)
