### ISSUE TITLE
Problems in Integrated terminal window

### ISSUE THREAD

**Issue by c8u** [Microsoft/vscode#68041]
- VSCode Version: 1.31.0
- OS Version: Windows 10

Steps to Reproduce:

1. Launch integrated terminal window using ctrl+`

Issues:

1. When lauching terminal, input prompt line (Eg: `PS C:\xampp\htdocs\c8u-tagger>` ) is not rendering unless keyboard input is provided
2. There are some gaps generating before input (when rendered)

![capture](https://user-images.githubusercontent.com/32994070/52391825-453c1480-2ac5-11e9-8d11-1805535ea9bc.PNG)
)

**Comment by MikeJerred** [comment]
I also have been having this problem recently. Also if I have run some things in the terminal and have lines of text there, and then I collapse & expand the terminal window the output disappears and cannot be viewed again.

I have tried with the VSCode Insiders and the problem is happening there too.

I have made a video here: [https://www.youtube.com/watch?v=EgNwKI5HPKI](url)

**Comment by Tyriar** [comment]
This is a bug in Windows 1809.

/duplicate https://github.com/Microsoft/vscode/issues/57803
