### ISSUE TITLE
LinkedMap has extra keys sometimes

### ISSUE THREAD

**Issue by alexr00** [Microsoft/vscode#68113]
Here's a test for map.test.ts that seems like it should pass. Bonus command line for running the test after you copy it in: `.\scripts\test.bat --run .\out\vs\base\test\common\map.test.js`
````javascript
	test('LinkedMap - get keys', function () {
		const map = new LinkedMap<string, any>();

		assert.equal(map.size, 0);

		map.set('1', 1);
		map.set('2', '2');
		map.delete('2');
		map.set('3', true);
		map.delete('3');
		assert.equal(map.size, 1); // This is correct and good
		assert.equal(map.keys().length, 1); // I would expect this to also pass, but it doesn't
	});
````

**Comment by dbaeumer** [comment]
@alexr00 very good catch. There was actually a problem with the LinkedMap :-(. Lets discuss what the right fix is for your code to work around. You are basically getting keys for elements which aren't in the list anymore. So when retrieving the element you need to verify that it is not undefined. And it only happens when you deleted the tail element.
