### ISSUE TITLE
Revisit that preview editors show up under "Opened Editors"

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#6812]
Some issues:
* for one it makes it very hard to double click on a file in the explorer to pin it because the first mouse down adds it already and pushes down the view
* then people are confused that the preview editor is open in one position but when you open another editor the preview editor might move up because that other editor was elsewhere
* Joao also does not like the italic decoration when you have tabs disabled
* so one proposal would be: only show italics when tabs are enabled and only show it in the tab itself
(of course we would have to revisit where else we show the italic, e.g. Ctrl+Tab, Cmd+Alt+Tab)

**Comment by bgashler1** [comment]
**Why it might be good to remove them:**

- I also haven't been loving the italicized text in Open Editors now that I've been using it.  I didn't feel like it was strong enough of an indicator to help me find a preview editor that was buried somewhere in a group (it's like a needle in a haystack--I ).  I didn't notice that the preview editor was moving in the group, but after seeing @jrieken's gif, I see why this is confusing.
- Sublime also does not show preview tabs in their Open Files pane, but they do get their own temporary tab.

**Why it might be bad to do so:**

- It may be confusing after closing a file that a mysterious preview file that was hiding in the stack shows up instead of the file shown above in working files.
- It may be less obvious how to pin a "Diff view" or some other kind of special editor, because it does not have something you can double click (perhaps we could allow double clicking the editor's title shown at the top of the group).

**Ideas on making it work as is:**

I thought about how we might solve this without eliminating preview editors completely from the list.

1. Use smooth motion transitions (like Chrome and Sublime)
1. Always leave a dedicated space at the end of each group's list in Open Editors so that opening/closing a preview editor will never shift the Explorer files up or down.

Look at this crude prototype that demonstrates how smooth motion transitions might make it more clear what's going on in the stack.

![previeweditorsinopeneditors_5_24_2016](https://cloud.githubusercontent.com/assets/11839736/15514019/ec2177e4-219b-11e6-8374-eea6ddb6706c.gif)

**Comment by bpasero** [comment]
@bgashler1 interesting idea, if I understood you correctly, we would keep an empty slot for each possible preview editor. It would look like this:

![editors](https://cloud.githubusercontent.com/assets/900690/15530504/056c0ed0-2255-11e6-931b-83549086cf43.gif)

While it fixes the issue with annoying double click behaviour, it almost looks like a UI bug that we would grow the "Opened Editors" view with an empty element inside. 

Let's discuss this in the next planning meeting :)

**Comment by joaomoreno** [comment]
Interesting... but doesn't it look ugly?

**Comment by bpasero** [comment]
Summary from the UX meeting regarding the concerns:
* we will fix the double click issue without having to hide the preview tab (https://github.com/Microsoft/vscode/issues/6749)
* we will provide an option to configure sorting behaviour of new editors (https://github.com/Microsoft/vscode/issues/6787)
* we would like to test out the italics experience even when tabs are disabled to see if we can get used to it.

That way we think having preview tab in "opened editors" is really not a bad thing to have.

**Comment by bgashler1** [comment]
@bpasero and @joaomoreno yes, the blank space sounded good in my head until I saw it.  Definitely not pretty.
