### ISSUE TITLE
Monaco Editor Again

### ISSUE THREAD

**Issue by blendsdk** [Microsoft/vscode#6817]
Hi,

Is there any news regarding embedding the monaco editor ina custom HTML page?
I read several posts here and I would like to get an update.

Please pardon me If this question has been answered before.

Thank you.

**Comment by alexandrudima** [comment]
I am working on it, but I need to clean up quite some code before publishing the API, as my hope is to keep it as stable as possible. The file at https://github.com/Microsoft/vscode/blob/master/build/lib/monaco-editor.d.ts is generated from our sources and our sources need to be in a good shape before releasing it.

**Comment by blendsdk** [comment]
Is there anyway I can help? (I would need some basic instructions how to setup though)

**Comment by jdanyow** [comment]
this can probably be closed now:  https://github.com/Microsoft/monaco-editor

**Comment by alexandrudima** [comment]
@blendsdk Sorry for going dark on this, I needed to get the basics working before asking for outside help. Anything would be appreciated, from trying it out in different browsers and creating issues, to making PRs to fix those issues, but probably at this stage I think more use-cases would be useful (https://github.com/Microsoft/monaco-editor-samples) and https://github.com/Microsoft/monaco-editor/blob/master/website/playground/playground.mdoc

Otherwise, yeah, the editor is now on npm :)
