### ISSUE TITLE
Support octicon in ThemableDecorationRenderOptions for gutter

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#682]
Today, I can only use images (files) to create decorations, defining `gutterIconPath`. It would be interesting also support **octicons**, maybe the same way that `StatusBarItem` does:

```
    var myDecorationType = vscode.window.createTextEditorDecorationType({
        gutterIconPath: '$(icon-name)'
    });
```

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

P.S. If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
