### ISSUE TITLE
New file doesn't show in explorer after creating from path like 'folder/subfolder/file.txt'

### ISSUE THREAD

**Issue by pavelkeyzik** [Microsoft/vscode#68204]
- VSCode Version: 1.31.0
- OS Version: Windows 10 Enterprise (1803) Build: 17134.285

Steps to Reproduce:

1. Open explorer sidebar
2. Click right button on the mouse
3. Select item 'New file'
4. Write 'folder/subfolder/file.txt'
5. File not created?
6. Click 'Refresh Explorer' button
7. Oh.. I see my folders and created file

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
@isidorn I believe this changed with refreshing only the parent of a new file... we should refresh parent of the first "new" stat in the chain.

**Comment by pavelkeyzik** [comment]
Any updates of this bug?

**Comment by isidorn** [comment]
We plan to fix it soon

**Comment by isidorn** [comment]
A proper fix would be that the file service emits events all the way up to the first created resource.
However I found that too risky for endgame and due to that I only made a local change to the file actions. That if multiple resources got created we refresh the whole explorer. This is the fix I am most comfortable with, since it is user action initiated, instead of tweaking how I react on file events
