### ISSUE TITLE
Allow a touchbar that overflows

### ISSUE THREAD

**Issue by shpontex** [microsoft/vscode#68214]
- VSCode Version: 1.31.0
- OS Version: mac os mojave 10.14.2
i tried almost all the touch bar extensions but no one seems to work anymore

**Comment by bpasero** [comment]
Likely caused by: https://github.com/electron/electron/issues/16473

**Comment by bpasero** [comment]
@shpontex I cannot reproduce what you describe with the following steps. Unfortunately I do not own a MacBookPro with native touchbar, so I have installed the touchbar simulator (https://sindresorhus.com/touch-bar-simulator/)

* start Code
* install `Nasc VSCode Touchbar`
* find new buttons in the touchbar

The change with Electron 3 that we had to work on was a change in how large icons would appear in the touchbar. They showed up much larger causing the touchbar to drop all the debug items at the end because space got little. It is possible that extensions have to update their icon sizes to account for that, however `Nasc VSCode Touchbar` seems to work just fine for me.

![image](https://user-images.githubusercontent.com/900690/52518536-fff61f00-2c4b-11e9-8864-f129208941a9.png)

**Comment by bpasero** [comment]
One thing that might help is to disable "Show control strip" from:

![image](https://user-images.githubusercontent.com/900690/52518586-de496780-2c4c-11e9-961d-ae5d7d4bb097.png)

**Comment by bpasero** [comment]
@isidorn @misolori you seem to have added a new entry to the debug touchbar (Start without Debug) which could also have an impact. By that you reduced the size of the touchbar by one item, and as such if an extension adds a lot of other items there is a chance that those items get removed. 

I am hijacking this issue to have the real proper fix which is to implement a touchbar that simply scrolls left and right.

If someone wants to look into this, be my guest. Touchbar is created in https://github.com/Microsoft/vscode/blob/58fb98d/src/vs/code/electron-main/window.ts#L988

**Comment by shpontex** [comment]
@bpasero 
thank you for your explanation
i confirm Nasc VSCode Touchbar work if i hide the control strip
other plugins too
i tried before to remove two buttons on the Touch Bar Display Commands extension "which contains only 5 buttons" but it didnt work

**Comment by justinchan23** [comment]
> @bpasero
> thank you for your explanation
> i confirm Nasc VSCode Touchbar work if i hide the control strip
> other plugins too
> i tried before to remove two buttons on the Touch Bar Display Commands extension "which contains only 5 buttons" but it didnt work

i submitted a pr to update the nasc vscode touchbar to work with vscode v1.31.0 with or without the control strip.

**Comment by alistairholt** [comment]
> @isidorn @misolori you seem to have added a new entry to the debug touchbar (Start without Debug) which could also have an impact. By that you reduced the size of the touchbar by one item, and as such if an extension adds a lot of other items there is a chance that those items get removed.
> 
> I am hijacking this issue to have the real proper fix which is to implement a touchbar that simply scrolls left and right.
> 
> If someone wants to look into this, be my guest. Touchbar is created in https://github.com/Microsoft/vscode/blob/58fb98d/src/vs/code/electron-main/window.ts#L988

This is how it should function IMO. Being restricted to a fixe-width space is not a great long-term solution.

**Comment by pelmers** [comment]
I'd like to give this issue a shot by using the TouchBarScrubber (https://electronjs.org/docs/api/touch-bar-scrubber).

**Comment by pelmers** [comment]
I wasn't able to solve this with current Electron APIs, I filed an issue upstream at https://github.com/electron/electron/issues/16936.

**Comment by albelin** [comment]
Hi, I am a new user here looking to contribute to the repo. Is this task still available?

**Comment by hasimyerlikaya** [comment]
Hello to everyone. I was looking for a solution because I couldn't use the Touch Bar when debugging. I am developing a mobile application with Flutter and found a solution in my own way. I wanted to share with you the idea that it can be useful as well.
I solved the problem by customizing the Touch Bar. I just added the tools I use most to the "Control Strip" field. In this way, the area there was reduced and the debug buttons were opened. I lost two of the Debug buttons, but I didn't use it much. Now I am very happy with this use. You can use it that way too.

<img width="1085" alt="Touch Bar Shot 2019-08-03 at 07 22 39" src="https://user-images.githubusercontent.com/7986394/62407443-4efc8b80-b5c1-11e9-8d20-c7adac60dd01.png">

![image](https://user-images.githubusercontent.com/7986394/62407465-997e0800-b5c1-11e9-86c6-82e4a5f8a5a2.png)
