### ISSUE TITLE
Support more languages in Ctrl+hover (LESS, CSS)

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#6828]
#6656

This might be a larger problem with the peek feature.

![image](https://cloud.githubusercontent.com/assets/2193314/15515142/81d8f884-21a1-11e6-87e1-7c14e2c946b0.png)

**Comment by sandy081** [comment]
Looks like this is not working for any variables across CSS, SASS & LESS

**Comment by alexandrudima** [comment]
I agree, but I also did not implement this feature. If my memory is good I think @bpasero implemented the preview of the definition.

**Comment by bpasero** [comment]
@alexandrudima I am relying on `tokenizeToHtmlContent` : https://github.com/Microsoft/vscode/blob/ben/stacks/src/vs/editor/contrib/goToDeclaration/browser/goToDeclaration.ts#L376

**Comment by alexandrudima** [comment]
The method does correctly what it is supposed to do, but the passed in string begins in the middle of a rule (i.e. the text is not in the initial state)

You can think of it similar to a block comment:

```
/*
Hello
------------text starts here
My peek definition text
*/
```

`My peek definition text` will not be colored as a comment because the `tokenizeToHtmlContent` method only gets:
```
My peek definition text
*/
```

**Comment by bpasero** [comment]
This goes beyond a bug fix and needs infrastructure.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

P.S. If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
