### ISSUE TITLE
Copy and Paste not working

### ISSUE THREAD

**Issue by Chieze-Franklin** [Microsoft/vscode#68330]
Issue Type: <b>Bug</b>

When I copy a text and paste it, the text I copied is not pasted. Instead, the one I wanted the replace with the copied text is pasted, as if I never even did any copy and paste. Now I'm forced to type everything out because paste is not working.

VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.65GB free)|
|Process Argv|-psn_0_45067|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.0
learning-extension-vscode|dev|1.2.0
gc-excelviewer|Gra|2.1.28
docthis|joe|0.7.1
dotenv|mik|1.0.1
csharp|ms-|1.17.1
addDocComments|ste|0.0.8
open-in-browser|tec|2.0.0

</details>

**Comment by kieferrm** [comment]
I can't reproduce. Can you please check that Copy and Paste are correctly bound to your shortcut?  Please use the `Code` > `Preferences` > `Keyboard Shortcuts` menu.

**Comment by sonicfly** [comment]
I have the same issue on VSCode Version 1.31.1 (1.31.1) 1b8e8302e405050205e69b59abb3559592bb9e60 2019-02-12T02:10:22.500Z

Seems the problem is related to after key press of "Cmd+c" shortcut, VSCode will still be waiting for more key input, and some other key press may cause it missing the "copy" trigger.

The easiest way to reproduce is 
1. Selection a text, e.g. "ABCD", Cmd+c to copy
2. Selection another text, e.g. "CDEF", quickly do Cmd+c, Cmd+f and Cmd+v (hold the Cmd key, press "c", "f", "v" keys in sequence)
3. You will see the "ABCD" in search dialog instead of "CDEF"

Another way to reproduce is
1. Selection a text, e.g. "ABCD"
2. Quickly input Cmd+c, Cmd+v and Cmd+v (hold the Cmd key, press "c", "v", "v" keys in sequence)
3. You will notice the ABCD only get pasted once, instead of twice as expected; and there is obvious stuck after first Cmd+v key press.

**Comment by alexandrudima** [comment]
@sonicfly Can you please try to disable all extensions? Can you also try to check your keybindings around "cmd+c" ? e.g.


![keyboard-conflicts](https://cloud.githubusercontent.com/assets/5047891/25484174/38f5b004-2b59-11e7-994b-dfa96ef043ce.gif)

**Comment by sonicfly** [comment]
Seems the vscodevim plug-in causes the problem. Disable it and it is all good.
