### ISSUE TITLE
"Clear Search Results" now clears search, replace, file to include, file to exclude input boxes

### ISSUE THREAD

**Issue by patleb** [Microsoft/vscode#68367]
"Clear Search Results" now clears search, replace, file to include, file to exclude input boxes.

Is it intentional? If it is, then maybe change the name to "Clear Search Context" or something which means what it does. It wasn't working this way before and I fail to see why you would want to clear 'file to include' and 'file to exclude' boxes, these are more often than not reused when you search.

It might seem like a good idea for quick searches and smaller code bases, but when you use extensively 'file to include' and 'file to exclude' as a way to search through thousands of directories, then clearing these inputs is quite frustrating when they are complex to build.

**Comment by Poimen** [comment]
This seems to have come from #62952 commit:
```js
		this.searchIncludePattern.setValue('');
		this.searchExcludePattern.setValue('');
```

The default action of clearing all the include and and exclude patterns is rather nasty for anyone who uses a mono-repo with large number of exclude patterns. We use exclude patterns to ignore searching projects, so resetting the patterns every search just because the clear was clicked is rather unuseful.

Can this operation be tuned such that we can at least keep our exclude/include patterns?

**Comment by shhider** [comment]
Mark. I am accustomed and need to use the old 'clear search results'. How about adding the setting item to control its behavior?

**Comment by ashclarke** [comment]
This definitely should be converted to a setting or reverted. I don't understand how the changes in #62952 got through. The button says "Clear Search Results", not clear all search settings.

**Comment by roblourens** [comment]
- Why do people keep include/exclude patterns in the search view over multiple searches? Do you want to add them to settings instead?
- What if it cleared the search input but not "files to include/exclude"

@isidorn this was originally your issue, any thoughts? I don't want to add a setting for every single thing. It could be an alt-action on the button but I don't think those are discoverable and don't want to figure out a new icon either.

**Comment by ashclarke** [comment]
@roblourens - My context/two cents/experience with this:

* We have a workspace with four project folders included, from one repo. My include/exclude settings are specific to the current project folder I’m working in. My main “searchspace” happens to be a subfolder that contains newer code to other folders.

* Sometimes I may change the include/exclude; relevant to the project folder or should I just want to search for a particular file type e.g. `./<workspace-folder-name>, *.scss`, however, these settings are not going to be applicable to every user of the workspace.

* I expect the “Clear Search Results” button to just clear the input and results tree.

**Comment by patleb** [comment]
@roblourens, I'm a bit confused by your first point (was it rhetorical?)... the first question has been answered by a couple of scenarios already mentionned in this thread and the second question doesn't make a lot of sense to me: why would I want to add folders to search in as a setting and how would that make the functionality intuitive or frictionless? It would be the same as moving "Match Case" or "Match Whole Word" as a setting (how could that be useful?).

Otherwise, the second point seems like a good compromise and this is what I expect from the functionality "Clear Search Results": it makes more sense.

**Comment by roblourens** [comment]
Well some issues in the past have come out of people keeping huge lists of exclude patterns in the view and not realizing that they can offload that to a setting. Also my assumption has always been that those inputs are sort of transient but now I think that's not always the case.

I thought the original suggestion made sense in that a typical use would be to clear the whole search context to do another search from a clean slate, rather than having to select and clear 3 input boxes manually. I think that's useful. But I still don't really think it warrants a setting. 

I'm leaning towards just changing it to not clear the include/exclude boxes. But I'll wait to see if @isidorn has any thoughts.

**Comment by patleb** [comment]
@roblourens, ok, I understand now, thanks.

The thing is that if your search is already constrained to a smaller searching surface (let's say a single project without libraries at the root), then "files to include/exclude" would be something that you would tend to use from time to time, but rarely. The moment you expand your workspace to a main project with smaller projects and libraries (mono-repo style), then "files to include/exclude" are gonna be used often and will change when you want to target a diffent set of smaller projects and libraries, but the common usage will be that "files to include/exclude" will stay the same as long as you work in that specific code surface.

**Comment by Poimen** [comment]
@roblourens, just for our use case:
* Why do people keep include/exclude patterns in the search view over multiple searches? Do you want to add them to settings instead?

For our mono-repo setup we exclude a number of projects. Devs often jump between different projects/services/etc. Adding the exclusions when you switch to the settings would be a constant settings change rather than a nice helpful text box labeled `files to exclude`. Doing the settings route would reduce the flexibility that we have previously enjoyed.

* What if it cleared the search input but not "files to include/exclude"

For us this would be fine.

**Comment by isidorn** [comment]
@roblourens do not clear include / exclude resulsts, since it seems to be the feedback from users which I would go for this time.
Replace should be cleared.

**Comment by ashclarke** [comment]
I clicked on the "Clear Search Results" button this morning and it was glorious. Thanks, all 👍🏻
