### ISSUE TITLE
Settings UI Always Scrolls Automatically While Check or Uncheck an Option

### ISSUE THREAD

**Issue by byyxx128** [Microsoft/vscode#68385]
See the GIF directly.

![bug](https://user-images.githubusercontent.com/20079289/52542637-f7970480-2d6f-11e9-9685-01588f14fb05.gif)

As shown above, the settings UI always scrolls automatically, so I cannot find the modification because it went away. Marking or deselecting any item may cause this issue.

* VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:35:56.624Z)
OS version: Windows_NT x64 10.0.18334

**Comment by beastdestroyer** [comment]
Annoyed me so much. Note that it happens with dropdowns and selecting an item, and occasionally by inputting textbox and clicking to defocus it.

**Comment by sethmnielsen** [comment]
Having this exact problem as well. I just installed VS code and am having this problem while giving it a trial run. Sigh....

**Comment by roblourens** [comment]
Maybe related to https://github.com/Microsoft/vscode/issues/65319

**Comment by roblourens** [comment]
This isn't what I thought it was, I have to assign to you @joaomoreno.

I think the ListView renders the setting items with their default heights, then rerenders and saves the offset of the anchor element. Then it fixes the heights of the elements and maintains the offset of the anchor element. But since it measured the anchor element when the elements had default heights, the list will be shifted if the real heights were different from the default heights. Maybe an anchor element should be measured before rendering the items with default heights or something like that. I made the default heights more accurate which helps.

**Comment by joaomoreno** [comment]
@roblourens Why is the list re-rendered when a check box is clicked?

> I made the default heights more accurate which helps.

👍

**Comment by roblourens** [comment]
When the config service says something changed, we rerender everything. It seems unnecessary in this case but it's hard to tell that the change event came "from" this instance of the settings editor and also, some values can change ie be normalized when they get back to us, and since it should be safe to rerender, I don't put a lot of effort into reducing unneeded renders.

Another way to repro this, open two settings editors in two groups, change a setting in Group 1, and see the editor in Group 2 scroll.

**Comment by joaomoreno** [comment]
It can definitely be fixed. I was just wondering why the rerender was needed. ;)

**Comment by joaomoreno** [comment]
cc @isidorn
