### ISSUE TITLE
[themes] does not work if publisher name starts with a number

### ISSUE THREAD

**Issue by 74th** [Microsoft/vscode#6840]
- VSCode Version: 1.1.1
- OS Version: OSX10.11.4, Windows10

I made and publish a theme, but it did not work.
https://github.com/74th/vscode-naturalcontrast-with-hc
 
![screen shot 2016-05-25 at 07 08 51](https://cloud.githubusercontent.com/assets/1060011/15521650/d071a18e-2247-11e6-9831-e1bdd99b8b6a.png)

But I changed publisher name "74th" -> "j74th" in package.json, it works.
```
    "publisher": "74th",
```
```
    "publisher": "j74th",
```

![screen shot 2016-05-25 at 07 09 38](https://cloud.githubusercontent.com/assets/1060011/15521709/217bb560-2248-11e6-9e6a-154231d1a58f.png)

**Comment by joaomoreno** [comment]
@alexandrudima Seems like Code fails to load it when the publisher starts with a digit? 😕

**Comment by alexandrudima** [comment]
The extension host finds the extension and correctly calls into the theme contribution point. I've added `console.log('DETECTED THEMES: ' + extensions.map(e => e.description.id));` at https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/themes/electron-browser/themeService.ts#L117 and the extension is correctly passed to the theme extension point.

Forwarding to @aeschli as it seems to be a theme specific issue.

**Comment by aeschli** [comment]
@74th Thanks for finding this. You were right, the problem was that the publisher starts with a number. I was using the extension id (which starts with the publisher) as a css selector. However, css selectors can not start with numbers.

In your extension, you also need to rename the file `NaturalContrast.tmtheme` to `NaturalContrast.tmTheme`, so it matches to what you have in `package.json`. That way the theme is correctly loaded also on case sensitive file systems like Linux.
