### ISSUE TITLE
"Initializing TS/JS language features" in the status bar endlessly

### ISSUE THREAD

**Issue by 7cc** [Microsoft/vscode#68428]
- VSCode Version: 1.31.0
- OS Version: Windows 7 64bit

Steps to Reproduce:

1. $ mkdir foo
2. drop the folder to a vscode shortcut
3. open the Setting panel and enable "javascript.implicitProjectConfig.checkJs"
4. create index.js and write
```js
/** @type {number} */
let num = 1
```
5. press `ctrl+@` to open the integrated shell
  ```cmd
  echo {} > jsconfig.json
  del jsconfig.json
  ```
  or manually make `jsconfig.json` and delete it

Now the status bar shows the message "initializing TS/JS...", which never ends.

Does this issue occur when all extensions are disabled?: Yes

------------------

I clean-installed the latest VSCode and confirmed it's reproducible.
1. uninstall VSCode
2. delete all related files & registry keys
3. restart computer
4. install the latest stable version (VSCodeUserSetup-x64-1.31.0.exe)

**Comment by mjbvz** [comment]
Root cause is https://github.com/Microsoft/TypeScript/issues/30005

I don't want to add a workaround to suppress the loading indicator since it was helpful in catching a real upstream issue. You can use the `TypeScript: Restart TS Server` command to reset typescript intellisense if it gets stuck in this state
