### ISSUE TITLE
Keybindings have gone bonkers

### ISSUE THREAD

**Issue by BobFrankston** [Microsoft/vscode#68485]
Don't know how to repo.

After installing 1.31 my keybindings got lost. I've been using the VS bindings a ^k^d, for example, started killing lines instead of formatting. I couldn't solve it (by enabling/disabling VS bindings) so, for now, I worked around it by manually adding those bindings.

But a bigger problem is that the arrow keys have been selecting text and I have to press ESC lest the selected text get deleted as soon as I type a letter. How do I fix this?

**Comment by Bbansjkl** [comment]
To me this reads a lot more like you got a stuck "Shift" key - Ctrl+Shift+K deletes lines, Shift+Arrow marks characters/lines. Although that should have been noticeable when typing, since everything would be uppercase (unless you also had caps lock active at the same time, in which case Shift+<letter> would write lowercase).  

Try turning on the on screen keyboard while testing the issues you described - if you have a stuck "Shift" key, it will be displayed as such on the on screen keyboard.

**Comment by BobFrankston** [comment]
I've toggled shift, rebooted, plugged/unplugged keyboard and it stays.

What is strange is that I just created a new directory with an app and the problem isn't happening there. Will need to investigate more...

**Comment by alexandrudima** [comment]
@BobFrankston What OS are you on? Does this reproduce when disabling all extensions?

**Comment by BobFrankston** [comment]
Windows 10. Last night I accepted an update and the problem seems to have gone away. So I suspect there was indeed a glitch so will watch for its reappearance and explore more as I get the time.
![image](https://user-images.githubusercontent.com/5490484/52714707-95552400-2f68-11e9-84ac-109bdf055a77.png)

**Comment by alexandrudima** [comment]
Thanks for following up!
