### ISSUE TITLE
Whitespace found via regex find is not highlighted throughout the document

### ISSUE THREAD

**Issue by boringuser** [Microsoft/vscode#6849]
- VSCode Version: 1.1.1
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Open a large document with many lines and whitespace, such as a large code file.
2. Use find dialog with regex enabled to search for "\s".
3. Whitespace will be highlighted, but only on the first or second screen of text. As you scroll down the highlight will terminate.

**Comment by alexandrudima** [comment]
We have a hard limit for the find highlights and for the selection highlights at 1000. The reason is that you might have open a 30MB file consisting of 30 million `a`s and you search for `a`. In this case, 30 million decorations would be added to the model which will probably result in a OOM. Let's track this in #1110 . I think at one point it is ok to raise the limit, but we will not reduce it unless we implement virtualize the highlights (such that they are rendered on the last step in our rendering pipeline, instead of being model decorations).
