### ISSUE TITLE
Unable to rebind ctrl+shift+f

### ISSUE THREAD

**Issue by hyarionh** [Microsoft/vscode#68515]
- VSCode Version: 1.31.0
- OS Version: Windows 7

Steps to Reproduce:

1. File -> Preferences -> keyboard shortcuts
2. Click the pencil icon to assign a new keybinding.
3. Note that "ctrl+shift" followed by any letter except for "f" is accepted.   
4. Note that "ctrl+shift+f" only displays "ctrl+shift+" and if you press ENTER it shows in list as "ctrl+shift+unknown".

Additional Notes:
Manually editing the keybindings.json also does not work.  It appears that ctrl+shift+f might be hardcoded?

Does this issue occur when all extensions are disabled?: Yes

**Comment by eurico-nerd** [comment]
Confirm the issue, also happening with "ctrl + alt + " keybindings.

**Comment by Spown** [comment]
eyep, after the last hotfix ``Alt+Ctrl`` doesn't work. not even in settings.

![](https://drive.google.com/uc?id=10xI1auXBgglgK4CDkt7vanRNvvVYcrz9)
I holding ``AltGr`` all the time , but the moment I hit t ``k`` - the  modifier key state just drops.

**Comment by roblourens** [comment]
@Spown why do you think #68182 is related? I can't reproduce this.

**Comment by alexandrudima** [comment]
@eurico-nerd @Spown you are running into what is explained at https://github.com/Microsoft/vscode/issues/68003#issuecomment-461637032 .

Basically, <kbd>AltGr</kbd>+ is no longer equivalent to <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+ and it is reserved for typing special characters (it no longer has any modifier flags). So, unfortunately, you need to switch to using the longer form of pressing <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+ for those keybindings.

---

@hyarionh You have a different issue. For you, the keybinding `ctrl+shift+f` never reaches VS Code. This is most likely caused by OS configuration / other software on the same machine that "eats up" that keybinding. Is this keybinding available on other software on your machine?

**Comment by hyarionh** [comment]
@alexandrudima My apologies.  I've checked again this morning and it's working correctly.  It appears a reboot of my PC solved the issue.  I did not think to do that when I logged the bug as I had only recently booted up  (as a side note, ctrl+shift+f had been working yesterday until I updated vscode).

**Comment by Spown** [comment]
@roblourens looks like it's not related. I thought it was because these were the only keyboard related fixed in 1.31.1. 
>Basically, AltGr+ is no longer equivalent to Ctrl+Alt+ and it is reserved for typing special characters (it no longer has any modifier flags)

apparently typing smileys is more important than being able to work...

**Comment by alexandrudima** [comment]
@Spown This change came to us from upstream (Electron + Chromium). I don't believe typing smileys was their number 1 priority, but rather unblocking users with European keyboard layouts to type their special characters (see https://www.chromestatus.com/feature/5059438092222464). Before, it was not possible for us to distinguish <kbd>AltGr</kbd>+ (which is used in a lot of special characters) from <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+.

For example, on a French keyboard layout, `#` is generated only by pressing <kbd>AltGr</kbd>+<kbd>3</kbd>. In the past, this would arrive on our side virtually identical to <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>3</kbd>. With their change, we can now allow users on French keyboard to type their `#`s and not dispatch the `ctrl+alt+3` keybinding:
![image](https://user-images.githubusercontent.com/5047891/52713143-d401d300-2f96-11e9-9a7b-1b4d41f6b9c1.png)

If you don't care much for special characters, you could switch to the English/US keyboard layout and then I believe the <kbd>AltGr</kbd>+ key will function like the left-hand-side <kbd>Alt</kbd>+ key, so you could bind keybindings to it.

**Comment by Spown** [comment]
@alexandrudima actually I use German keyboard and I am able to type special characters using both modifiers, but I still expect the shortcuts to override the typing. These special character called special for a reason. For example both ``Ctrl + Alt + 3`` and ``AltGr + 3`` produce ``³``, but if I set ``Ctrl + Alt + 3`` to a command - means I am fine with this key being inaccessible. But yeah, I know I am not alone in the world and other people have other needs. 

installing additional keyboard layout is not an option for a number of reasons, in my case the most important one is that I use 2 layouts (Russian and German) and I switch between them. German absolutely covers English so I don't need a US or GB one. Being able to cycle through 2 layouts (i.e. to always know which one comes next after toggling) is much more important for me than the minute nuances that come with. Also Y and Z are swapped in DEU and EN layouts.

Anyway more accessability is better than less. I only a bit upset that such huge of a change was introduced silently and without a proper means to switch back to legacy.

**Comment by alexandrudima** [comment]
> Anyway more accessability is better than less. I only a bit upset that such huge of a change was introduced silently and without a proper means to switch back to legacy.

I am sorry about that! I honestly didn't know the change came in either, since I don't personally use any Ctrl+Alt+X keybindings (where X is a digit or a letter). The change came in with our upgrade to Electron 3.0. Since 2 months already we have the Insiders channel on Electron 3.0 and we haven't received any single issue regarding this from our users, nor did anyone from the team notice this change regarding `AltGr` until after we shipped stable and issues starting coming...

May I kindly ask you that you try using the Insiders version, it is quite high quality and we all selfhost on it... We would have found out about this change sooner if we would have had at least one user of Ctrl+Alt+X keybindings that are triggerable via AltGr+ ... We could have documented it in the release notes...

**Comment by Spown** [comment]
>May I kindly ask you that you try using the Insiders version

I am using it, but mostly only to check whether the bug I found in stable was already fixed.
