### ISSUE TITLE
Variable: relativeFile posix or not?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#68524]
While adopting our new `path` library I noticed that `relativeFile` seems to be returning file paths with slash. The path returned now will use backslash if on Windows which is probably the right behaviour, but I wanted to fyi. We currently have no helper to convert a Windows path into a Posix path because it looks like `path.posix.normalize()` will actually preserve backslash. 

//cc @dbaeumer @alexr00

**Comment by pbricout** [comment]
I also have an issue on Windows as it seems that it now return backslashes instead of forward slashes, this seems to be recent regression from this issue:
https://github.com/Microsoft/vscode/issues/40256
According to this issue forward slashes should be used on all OSes.
Doing this on windows, when the shell is bash is failing:

```
        {
            "label": "echo",
            "type": "shell",
            "command": "echo ${relativeFile}",
            "problemMatcher": []
        },
```

Will show `abc` instead of `a/b/c`.

**Comment by weinand** [comment]
@isidorn could you please link this issue to the other issue.

**Comment by pbricout** [comment]
I have create this issue which is related I think:
https://github.com/Microsoft/vscode/issues/70926

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/70050#issuecomment-472052839
