### ISSUE TITLE
Disable intellisense when typing <?php in php documents

### ISSUE THREAD

**Issue by esemlabel** [microsoft/vscode#68535]
- VSCode Version: 1.30.2
- OS Version: OS X 10.11.6
- Does this issue occur when all extensions are disabled?: Yes

It's duplicate of #663, #1380 and #2744, which were closed without fixing for some reason.
**The problem still exists in 1.30.2**

**Comment by mattacosta** [comment]
This is what I see on the latest insiders:
![untitled](https://user-images.githubusercontent.com/1007463/52750952-faca0480-2faa-11e9-8e9d-88d5fe549c89.png)

Is your `php.suggest.basic` setting set to `true`?

**Comment by esemlabel** [comment]
It is set to false, 'cause I'm using Intelephense extensions, but as I can see this doesn't matter and occurs with both values. Though, I get same result when typing `<?`, but different when starting to add symbols like `<?p`. Here is some examples with different behavior. Note that suggestion list contains snippets from user snippets folder, - maybe this is the problem.

```
New unsaved file

// PHP user snippets appears from ~/Library/Application Support/Code/User/snippets/php.json
```
![2019-02-14 11 49 55](https://user-images.githubusercontent.com/17903845/52778450-b6904000-304e-11e9-8a82-d4fe94698ddf.gif)

```
Saved file

// PHP User snippets appears from ~/Library/Application Support/Code/User/snippets/php.json
// but when fast typing only.
```
![2019-02-14 12 11 57](https://user-images.githubusercontent.com/17903845/52779908-c8bfad80-3051-11e9-8eef-c85f83671542.gif)

```
In both cases above, but hide suggestion list with Esc first, then revoke with Control+Space

// Global user snippets appears from ~/Library/Application Support/Code/User/snippets/global.code-snippets
// if php or its part matched snippet prefix
```
![2019-02-14 12 07 57](https://user-images.githubusercontent.com/17903845/52779643-3fa87680-3051-11e9-98e9-21bf2c33fd13.gif)

**Comment by mattacosta** [comment]
Oh, yeah, I can see how that would be super annoying.

I think what's happening is that because there are no words to complete when the cursor is after the question mark, the sorting algorithm gives the `<?php` entry the lowest possible weight (the only reason there is even an entry for `<?php` is because there's a special case for it).

Setting the `preselect` property on the `<?php` completion item might help, but that would have to be done by every PHP extension.

In the mean time, you could try setting `editor.snippetSuggestions` to `bottom` instead, assuming it's not more of an inconvenience.

**Comment by esemlabel** [comment]
> In the mean time, you could try setting `editor.snippetSuggestions` to `bottom` instead, assuming it's not more of an inconvenience.

Unfortunately, I can't.

I need my snippets on top of the list in regular cases, like many of other programmers to increase productivity, but not when `<?php` is typed - and not just to avoid seeing suggestion list with user snippets, but to prevent autocompletion of one of items when hitting Enter right after `<?php` is typed to add newline and keep coding, as in #663.

There is has to be proper solution to prevent user language based and global snippets appear in suggestion list when `<?php` is typed, like it was done to `php.suggest.basic` suggestions in past.

**Comment by roblourens** [comment]
I don't think this is the same as the other issues. I think there are a couple issues.

One is that because PHP supports short tags `<? ... ?>` you are in the php language mode immediately after typing `<?` and you'll get snippets that start with php. To us it's obvious what you intended but that grammar doesn't know that... I'm not sure what to do about that besides keep two versions of the grammar, or something. A space is not required after `<?`.

Secondly, not sure what's going on in the last gif. I can't reproduce it, I get the same snippets from typing after `<?` or press ctrl+enter. Any idea @jrieken?
