### ISSUE TITLE
terminal font problem with 1.31.0-1549443494 release

### ISSUE THREAD

**Issue by pmpetit** [microsoft/vscode#68608]
Hello,

with  code-1.31.0-1549443494.el7.x86_64.rpm
characters are all ||
in the integrated terminal

when i downgrade to previous : code-1.30.2-1546901769.el7.x86_64.rpm
then
![image](https://user-images.githubusercontent.com/4059185/52704156-326f8700-2f80-11e9-9089-17107814160c.png)

Thanks

**Comment by Tyriar** [comment]
You're probably not setting your powerlines right, see https://github.com/Microsoft/vscode/issues/66489

**Comment by Psykar** [comment]
I'm seeing the same issue.
1.30 doesn't have the issue.
1.31 does.

I have explicitly set my font. The font definitely exists.
```
{
    "terminal.integrated.fontFamily": "\"Source Code Pro for Powerline\""
}
```
Have also tried `"SauceCodePro Nerd Font"`

All these fonts will render the glyphs correctly in my system terminal, but none render them in vscode 1.31.

I'm on ArchLinux.
For 1.30 I was able to use a font fallback and didn't have to specify the font directly in the settings.
`/etc/fonts/conf.d/10-powerline-symbols.conf` worked instead.

**Comment by Tyriar** [comment]
@Psykar have you tried tweaking the quotes? Does the rest of the font work or does it look like the font is not registering?

**Comment by Psykar** [comment]
![image](https://user-images.githubusercontent.com/817933/53387396-978e9800-39d6-11e9-9058-4e98038f140f.png)
Tried tweaking quotes, no difference.
Font definitely appears to not register. It looks very different if it doesn't:
![image](https://user-images.githubusercontent.com/817933/53387514-200d3880-39d7-11e9-88df-77fa0824d8c6.png)

I've tried removing almost every font off the system. Tried installing both powerline patched packs, and individual patched fonts.
I also tried Insiders 1.32 (as these screenshots are)

**Comment by Svenito** [comment]
Seeing similar on 1.31.1 which was working fine in previous versions. The screenshot shows the terminal prompt from GNOME terminal and below from VSC native terminal, both using the same font. The arrows between the prompt segments are working fine, but symbols are missing.
This is happening across different devices.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

![screenshot](https://user-images.githubusercontent.com/31278/53505628-20c3ce80-3aac-11e9-9fb0-511aa7171939.png)

Version: 1.31.1
Commit: 1b8e8302e405050205e69b59abb3559592bb9e60
Date: 2019-02-12T02:19:29.629Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic

**Comment by Psykar** [comment]
Progress!
It appears this is an issue with [fish](https://fishshell.com/) shell specifically. Bash works fine.

**Comment by Svenito** [comment]
> It appears this is an issue with [fish](https://fishshell.com/) shell specifically. Bash works fine.

I'm using ZSH, so that as well

**Comment by philhendren** [comment]
I have this issue aswell on Ubuntu with ZSH. I also know someone with ZSH on OSX that has the same happening since 1.31

**Comment by GLabat** [comment]
Same here. MacOSX + ZSH + Powerline.
Since 1.31, fonts are not correctly rendered in terminal prompt.

Other things to note:
* Fonts are installed using https://github.com/gabrielelana/awesome-terminal-fonts
* in iTerm2, my prompt is correct so the fonts seem correctly installed
* if I copy a char (FontAwesome for ex) from Font Book App and paste into VSCode editor, the font is not rendered (blank square). The same thing in TextEdit for ex works correctly, the char is displayed.

Thanks.

**Comment by pmpetit** [comment]
I'm also using zsh, and thx to GLabat. it is fixed with his workaround

**Comment by Tyriar** [comment]
This might have been caused by https://github.com/Microsoft/vscode/commit/aec79b9e417c4ffaf334505dcea2f999e3575624

This made sure that the terminal correctly falls back to the default editor font which is defined as this on Mac and Linux:

https://github.com/Microsoft/vscode/blob/f9346fbcf3c2d1cad6c49832ff010b75619a3dd4/src/vs/editor/common/config/editorOptions.ts#L2569-L2570

Previously it would fall back to the xterm.js default [defined here](https://github.com/xtermjs/xterm.js/blob/8b6d5645981451f57a9b45363f6b8a9df2d4b0f4/src/Terminal.ts#L94): `'courier-new, courier, monospace'`

I still don't understand why the powerlines fonts would work when explicitly setting the terminal font as in https://github.com/Microsoft/vscode/issues/68608#issuecomment-467290922 though.

**Comment by Svenito** [comment]
Adding `FontAwesome` to the end of the `"terminal.integrated.fontFamily"` setting has fixed the issue. My config line now reads

`"terminal.integrated.fontFamily": "Hack, Fontawesome",`

And all symbols are displaying fine

**Comment by tonilaukka** [comment]
iTerm vs VS Code (1.32.3)
![Screenshot 2019-04-01 at 16 18 36](https://user-images.githubusercontent.com/1569180/55330728-6eac6780-549a-11e9-9ef6-b30eff501134.png)

Only half of the icons are shown on VS Code Terminal

`"terminal.integrated.fontFamily" "'Dank Mono', 'Hack Nerd Font'",`

**Comment by tonilaukka** [comment]
OK. So the reason was this setting: `"terminal.integrated.rendererType": "dom"`. I think earlier my VS Code has detected that my terminal is slow and suggested that I add this settings. I now removed it and everything looks good. Let's see if we still have performance issues.

https://code.visualstudio.com/docs/editor/integrated-terminal#_changing-how-the-terminal-is-rendered

**Comment by Psykar** [comment]
> OK. So the reason was this setting: `"terminal.integrated.rendererType": "dom"`. I think earlier VS Code has detected that my terminal is slow and suggested that I add this settings. I now removed it and everything looks good. Let's see if we now face performance issues again.
This does not appear to change anything with font rendering for me.

> Adding `FontAwesome` to the end of the `"terminal.integrated.fontFamily"` setting has fixed the issue. 
This does not make a difference for myself - although based on comments that does appear to resolve things for OSX users seems it doesn't help for Fish shell on Linux.

**Comment by ayozemr** [comment]
Tried all things but icons are not showing in vscode terminal, all right in iterm (this setup https://gist.github.com/kevin-smets/8568070). Tried also the FontAwesome workaround with no luck.
