### ISSUE TITLE
Whole app (window) stops responding on regular expression

### ISSUE THREAD

**Issue by warrenfalk** [Microsoft/vscode#68629]
Issue Type: <b>Bug</b>

1. Open file new file, cut and paste the content from this file: (https://raw.githubusercontent.com/Dogfalo/materialize/80e8ed370487aaf1e2185b028f7deda40da94eb9/dist/css/materialize.css)
2. Ctrl+F to open find in file
3. Make sure regular expression search is on.
3. Type or paste in regular expression ```([^\{\}]|[\n])+\{```
4. Whole app stops responding, eventually shows "The window is no longer responding" giving options: Reopen, Keep Waiitng, Close. (Note: the size of the file appears to be relevant, cutting the file down far enough will eventually allow the expression to succeed but after a long temporary lock up)

VS Code version: Code - Insiders 1.32.0-insider (a509265116babc17648c9052eeeb8ae2909fed87, 2019-02-13T06:17:10.681Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.97GB (40.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alexandrudima** [comment]
@warrenfalk Sometimes a regex evaluation can take a really really long time, and it depends both on the regex source and the text it is evaluated on. Currently, we have no way of canceling this evaluation because we evaluate it in the main thread...

Also sometimes, a very simple change to the regex can improve its runtime significantly, and only someone that implemented the regex engine would be able to explain why...

Here I have tweaked a bit your regex by adding a `}` at the beginning and it now runs almost instant:
`\}([^\{\}]|[\n])+\{`
It matches the last rule's closing bracket, so it doesn't do what you initially wanted, but I'm sorry there are no other solutions...

**Comment by warrenfalk** [comment]
I hate to complain about software that I use for free, but if roles were reversed, I'd want to be able to understand the perspective of those who are using software that I built.  I have not contributed to this project, but I have contributed to others.

It really takes a lot of effort to report a good quality bug, and so it is really disheartening and frustrating to have it closed outright with an explanation that can be summarized like this:

> [it doesn't work because it is broken, and broken is fine, so try doing something else]

I just don't understand how it is acceptable to lock up the whole application the moment your incomplete expression happens to evaluate to a valid regex that the app doesn't like.

> Sometimes a regex evaluation can take a long time.

Sure, but not this one.  Sublime Text can do the exact thing on the exact file instantly.

> Currently, we have no way of canceling because we do it on the main thread.

Right, that's the bug - why would we run a task on the main thread which we know might just take hours to complete?

> I have tweaked your regex

But I couldn't do that because the app evaluates the regex on each keystroke and so as soon as I typed in enough characters to evaluate, it locked, then I had to wait before I could try again and figure out what was locking it up, with each lockup taking at least 30 seconds.

> Only someone that implemented the regex would be able to explain.

But instead of going to someone who knows how the regex works, it got closed by someone who doesn't know how it works.  It seems to me that the whole point of submitting bugs is so that the experts can fix the issues.

It took me 30 minutes to work through the lock ups and get the insider version to verify it was still an issue, and I donated this time so that future users don't have to go through this pain.

**Comment by alexandrudima** [comment]
I did check regex101.com before closing the issue and their implementation is also timing out with your regular expression.

I have closed this bug because I have encountered similar regular expressions in the past, I get such an issue where users discover them every few months. They are called "Runaway Regular Expressions" -- https://www.regular-expressions.info/catastrophic.html . 

FYI Sublime Text does not evaluate your regular expression entirely, it gives up after some time if you look at the status bar, so yes, the regular expression itself is a "runaway regular expression":

![image](https://user-images.githubusercontent.com/5047891/52845113-9328cc00-3106-11e9-84e1-88296c720cdc.png)

Is SublimeText superior in handling runaway regular expressions? Yes.
Could we handle this better and not freeze? Yes.
Would it be very expensive to implement that given our runtime? Yes.

Here is a thread where I write what could be possible fixes -- https://github.com/Microsoft/vscode/issues/26434#issuecomment-300805668 . I have invested way more than 30 minutes in this problem and I know we will not address it anytime soon.

No expert can fix a runaway regular expression. The only thing that can be controlled is to recover from trying to evaluate it. Our runtime (JavaScript) does not allow to pass in a timeout or anything like that when evaluating a regular expression and will happily compute at it for hours.

**Comment by warrenfalk** [comment]
Thank you for your response.  I sincerely appreciate it.

I apologize for not finding the previous bug; I did look for one.  The core bug is that the whole app may freeze before you complete your regex if an incomplete form of it happens to be both valid and runaway.  But I do appreciate the difficulty in solving this issue on this platform.

For what it's worth, I did not experience the stack space error in Sublime Text, and it really was instant:

![image](https://user-images.githubusercontent.com/158330/52856588-d9743000-30f2-11e9-84fb-bd7e0e27531a.png)

But again: thanks for taking the time and effort to respond.
