### ISSUE TITLE
Slow loading extensions

### ISSUE THREAD

**Issue by arixse** [Microsoft/vscode#6863]
- VSCode Version:1.1.1
- OS Version:Win7 64

Steps to Reproduce:

1. 加载扩展插件速度缓慢

**Comment by aeschli** [comment]
@arixse Please add more details...

**Comment by arixse** [comment]
sublime text是一次性加载所有扩展，而vscode是一次性加载部分扩展，用户输入扩展名字才会去动态搜索，这样就会导致体验不是很好
![Uploading 1.png…]()

**Comment by aeschli** [comment]
@arixse The screenshot was not properly added. Can you try again?

**Comment by aeschli** [comment]
@rebornix Can help translating?

**Comment by arixse** [comment]
When i type the extension name , it will search this extension online ,this step is slowly

**Comment by joaomoreno** [comment]
@arixse Is it slow but finishes... or it never finishes?

Are you behind a proxy?

**Comment by rebornix** [comment]
He also mentioned sublime always loads the full extension lost at one time, while in VS Code, we will fetch the partial list each time users type a new keyword. This makes him feel bad ...

IMHO, it is due to the special network in China and has nothing to do with vscode side. We are running into the same issue in our website, Wade mentioned it always takes 30s + to load the homepage. Since Shanghai team is still maintaining the old vs gallery, let me see if there is any custpmization for China network, like cdn, then have a feature request for vso.

**Comment by joaomoreno** [comment]
Closing this.
