### ISSUE TITLE
Tree selection array not depenendent on order user added elements to it

### ISSUE THREAD

**Issue by prfmansell** [Microsoft/vscode#68772]
- VSCode Version: 1.31.1
- OS Version: Windows 10 Enterprise 10.0.17134

Steps to Reproduce:

1. Pick two files, choose Select for Compare
2. Two files open side-by-side but in the wrong order.  In v1.30.2 and earlier, the file which you selected first would appear on left of comparison (in read-only state), allowing the second file to be edited.  In v1.31.0 and later, files appear in fixed order, no matter which order they are selected.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This works the same as in stable. The difference is on which element you click to invoke the context menu, not in which order you select them.
Please confirm if you see the same

**Comment by prfmansell** [comment]
It seems to make no difference which file I click to invoke the context menu, the same file always appears in read-only editor regardless.

**Comment by prfmansell** [comment]
Edit: The method I use for comparing files was to use Ctrl+click to select 2 files, using context menu to compare selected.  However I see that if you invoke context menu while selecting one file, choosing Select for Compare, then using context menu on second file to Compare Selected, this now works as expected.  Can you confirm the old method no longer works correctly (when selecting both files before Compare Selected)?

**Comment by isidorn** [comment]
@prfmansell yes I agree with you this has changed.

@joaomoreno the issue is that the old tree had a selection array which was dependent on the order user added the elements to the selection. While the new tree always gives the same selection array no matter how the user created that selection.
This is fine for me and seems to only be the problem in this compare corner case. Since there is a workaround to first select for comapre and then compare with selected.

Still forwarding to you to decide if you want to change this on the tree side or close.
