### ISSUE TITLE
Add a quick watch window to inspect variables while debugging

### ISSUE THREAD

**Issue by charlesg99** [Microsoft/vscode#68804]
Please add a quick watch dialog like the one found in Visual Studio that opens with `Shift + F9` while debugging: 

![quickwatch](https://devblogs.microsoft.com/devops/wp-content/uploads/sites/6/2016/07/image_thumb389.png)

Currently the inspector window showing variables on hover is way too small (#68749) and the only solution to inspect long names/values variables is to modify the width of the debug sidebar. This isn't ideal because you need to readjust the sidebar's width when you're done, which makes it very cumbersome.

Another idea would be to allow to "pin" the current variable inspector window that appears on variable hover and to make it possible to move/resize it.

**Comment by isidorn** [comment]
This will not happen as part of the debug work.
In the future we might have more flexible workbench layout where we allow split view panes to be moved around. This will be fixed as part of that.
Since there is already an issue tracking that, and since we will not do anything special for the watch view I am closing this one

**Comment by charlesg99** [comment]
Would it be possible to allow for a larger watch view as proposed in #68749?
