### ISSUE TITLE
Text Display Weirdness When Using Cygwin Within the Integrated Terminal...

### ISSUE THREAD

**Issue by busticated** [Microsoft/vscode#68817]
hey there :wave:

i'm seeing odd text rendering / cursor positioning when i configure my integrated terminal to use Cygwin bash (`v4.4.12(3)`). here's a screengrab showing the behavior:

![vscode-terminal-cygwin](https://user-images.githubusercontent.com/367674/52891034-1107ca00-313d-11e9-87b5-f661f9d87afe.gif)

basically, the backspace and arrow up/down keys cause the text to become illegible / positioned oddly. backspace actually moves the cursor forward while deleting the previous character so things get really confusing really fast :joy:

Steps to Reproduce:

1. set `"terminal.integrated.shell.windows": "C:\\Cygwin\\bin\\bash.exe"`
2. launch a new terminal
3. enter text, then backspace and / or arrow-up or arrow-down

- VSCode Version: 1.31.1
- OS Version: window 10 pro

Does this issue occur when all extensions are disabled?: Yes

**Comment by busticated** [comment]
@Tyriar @kieferrm sorry to press but is there anything that can be done here? is it just a limitation of cygwin? a configuration issue? a bug in the terminal implementation? any hints you could provide would be very much appreciated 🙏👍

**Comment by Tyriar** [comment]
This looks like one of the class of issues caused by running the shell through winpty (https://github.com/Microsoft/vscode/issues/45693). The terminal backend is moving over to ConPTY which is maintained by the MS Console team, this should happen in the next version of Windows 10 (190*) or you can try it out in Windows Insiders now using this:

```json
"terminal.integrated.windowsEnableConpty": true
```
