### ISSUE TITLE
function call intellisense highlights incorrect argument when two parameters share common prefix 

### ISSUE THREAD

**Issue by benrbray** [Microsoft/vscode#68824]
Issue Type: <b>Bug</b>

In a new .cpp file, type the following code:

```
void func(bool write, bool writeback){
	// do stuff
}

void main(){
	
}
```

Now, place your cursor inside the main() function and start typing "func(".  The function autocomplete should pop up, and it will show the following hint (where I use ALL CAPS to mean that the text is bold and underlined in VS code)

```
void func(bool write, BOOL WRITEback)
```

The expected hint is:

```
void func(BOOL WRITE, bool writeback)
```

It looks like the regex for highlighting the argument signature isn't stopping at the first match.

VS Code version: Code 1.30.1 (dea8705087adb1b5e5ae1d9123278e178656186a, 2018-12-18T18:07:32.870Z)
OS version: Linux x64 4.4.0-142-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 3424)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.72GB (1.81GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
matlab|Gim|0.9.0
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-great-icons|emm|2.1.46
mdmath|goe|2.3.9
nbpreviewer|jit|1.2.2
vscode-cudacpp|kri|0.1.1
python|ms-|2019.1.0
cpptools|ms-|0.21.0
vscode-icons|rob|8.1.0
llvm|RRe|0.0.3
shader|sle|1.1.4
cmake|twx|0.0.17

(5 theme extensions excluded)

</details>

**Comment by JeffreyCA** [comment]
@rebornix I think the problem lies in the `getParameterLabelOffsets` function which returns the start and end indices of the text that should be bolded. It uses `lastIndexOf` to search for the current parameter in the signature which is susceptible to giving overlapping results:
 https://github.com/Microsoft/vscode/blob/013501950e78b9dde5c2e6ec3f2ddfb9201156b7/src/vs/editor/contrib/parameterHints/parameterHintsWidget.ts#L279-L282

Maybe it should compute the offsets by splitting the signature text at commas. But since this is language-agnostic, additional information might be needed like index of previous parameter (so you can do `IndexOf` on the remaining substring of the signature).

Given the following Python function definition, if `IndexOf` was used instead then in the tooltip, the function name (not the parameter) would be bolded instead.

```py
def a(a, ab):
    pass
```

**Comment by MikhailArkhipov** [comment]
Actually in Python Language Server we supply active parameter index via LSP. IMO it is not necessary to search when we already know which parameter is it. Also, some languages may contain same string as a default value or as type of the parameter.

**Comment by JeffreyCA** [comment]
Also worth taking a look at Sublime's LSP plugin implementation, they search after an open parenthesis and use RegEx to match the **entire word**:

https://github.com/tomv564/LSP/blob/master/plugin/signature_help.py#L213-L265

**Comment by JeffreyCA** [comment]
Hi, I don't think this is an extension issue.

**Comment by JeffreyCA** [comment]
Where can we continue to track this issue?

**Comment by MikhailArkhipov** [comment]
How can this be caused by extension when it happens in multiple languages and extension had no control over rendering in the signature help window?

**Comment by jrieken** [comment]
> How can this be caused by extension when

Likely because they haven't adopted the API that we have added ~6 months ago, see [`ParameterInformation#label: [number, number]`](https://github.com/Microsoft/vscode/blob/816a31517667f1ed8b0098ef6e20273614c31d1b/src/vs/vsc
ode.d.ts#L3091)
