### ISSUE TITLE
Trailing whitespace (but not leading) is trimmed from decorations after:contentText

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#68844]
Given a decoration with leading/trailing whitespace in the `contextText` for the `after` property:

<img width="443" alt="screenshot 2019-02-16 at 16 12 29" src="https://user-images.githubusercontent.com/1078012/52902202-c736e680-3205-11e9-9e77-963dc0703fc3.png">

The trailing space is trimmed, but the leading space is not which feels a little inconsistent:

<img width="308" alt="screenshot 2019-02-16 at 16 13 59" src="https://user-images.githubusercontent.com/1078012/52902209-e2a1f180-3205-11e9-9ad2-c28e035fdbf6.png">

(Sure, I'd rather not use spaces, but it seems there's no way to set padding, or borders only on the sides, and text looks terrible with a BG and no padding :-))

**Comment by alexdima** [comment]
I have double checked and we generate all CSS correctly, we are not trimming the trailing space in VS Code.

I tried and could reproduce outside of VS Code at https://jsfiddle.net/80z7mrw2/

![image](https://user-images.githubusercontent.com/5047891/76128450-a73ab680-6004-11ea-91a5-951451995581.png)

The same rendering occurs in both Chromium and Firefox, which makes me believe that this is perhaps intentional 🤷‍♂ . If you feel strongly about this, please feel free to report upstream to Chromium at https://bugs.chromium.org/p/chromium/issues/list
