### ISSUE TITLE
OSX: paste doesn't work

### ISSUE THREAD

**Issue by jaytrent** [Microsoft/vscode#6884]
- VSCode Version: 1.1.1
- OS Version:  10.11.4

Steps to Reproduce:

1. copy from any document (cmd-C)
2. verify paste works in other apps (cmd-V)
3. attempt to paste into a document open in Code (cmd-V)
4. observe paste fails

**Comment by johnazre** [comment]
I was not able to reproduce this in OSX 10.11.5 following the steps provided. Are you talking about a specific type of "document" or just anything with highlightable text?

**Comment by timerly** [comment]
Happens for me
* VSCode Version: 1.1.1
OS Version: 10.11.5

Steps to reproduce
1. Copy some text to clipboard in some other application
2. Verify it pastes correctly
3. Select a file in VST, select All (Command + A), select Copy (Command + C)
4. In another file in VSC do paste (Command + P) 
5. Text from previous copy action will paste instead of text selected and copied in VSC.
6. If instead of doing Command+A to select all, you explicitly drag across the text and copy, then paste will work. 
7. Select all plus copy doesn't work

**Comment by jaytrent** [comment]
I wonder if it is related to an OSX update; I have now noticed it in multiple apps.  Rebooting seems to have fixed it for all apps, including Code (where I first noticed the issue, and apparently wrongly blamed Code.  Sorry Code!).

**Comment by bcherny** [comment]
This was indeed an OSX issue for me. The following worked:

```sh
launchctl stop com.apple.pboard
launchctl start com.apple.pboard
```

See http://apple.stackexchange.com/questions/31866/copy-and-cut-sometimes-dont-work

**Comment by supernoir** [comment]
I have the same issue, consistently. Sometimes it helped to restart VSCode, but in the past two days, not so much. I run 10.12.1 and VSC 1.8.0
