### ISSUE TITLE
Vertical scrolling affect horizontal

### ISSUE THREAD

**Issue by jerrymani33** [Microsoft/vscode#68867]
Issue Type: <b>Bug</b>

scrolling is not good as windows system. when ever i scroll  vertical in vscode using two finger its affect horizontal scroll  alos

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:19:29.629Z)
OS version: Linux x64 4.18.0-16-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 1200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 3, 3|
|Memory (System)|7.59GB (4.21GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ionic4-snippets-vscode|4tr|1.2.0
danielo-node-snippets|dan|1.0.3
vscode-ionic-snippets|fiv|0.15.0
beautify|Hoo|1.4.8
material-icon-theme|PKi|3.6.3
ionic2|Tha|3.0.2
ionic-preview|tru|0.1.11
cordova-tools|vsm|1.8.0

(1 theme extensions excluded)

</details>

**Comment by alexandrudima** [comment]
@jerrymani33 We are not massaging input events in any way. So, if a scroll event comes in from the OS with both a `dy` and a `dx`, we will honour both values and scroll both horizontally and vertically at the same time.

Is this in any way different than other applications? What happens when you open a page from Wikipedia in Chromium on this machine and resize the browser such that you get a horizontal scrollbar? When using two fingers, does the scrollbar respect your horizontal movement as well as your vertical one?
