### ISSUE TITLE
whole system freezes after running an infinite loop in Ruby on VS Code, using Ubuntu 18.04

### ISSUE THREAD

**Issue by shanp77** [Microsoft/vscode#68885]
After accidentally creating an endless loop in Ruby in VS Code(version 1.30.2) and running it, I have this issue where my whole Ubuntu system will freeze up, forcing me to restart computer.  After running the loop, I will kill the terminal, and a few seconds to a few minutes later, the system will very often hang up to the point of not being able to do anything, not even moving the cursor works.  This has happened to me at least a half a dozen times in the past couple weeks.

**Comment by Tyriar** [comment]
I believe this will get fixed when we pull in https://github.com/xtermjs/xterm.js/pull/1818

**Comment by alexr00** [comment]
I made an infinite loop in Ruby:
````Ruby
while true
    puts("looping")
end
````
And ran it in the integrated terminal: `ruby rubytest.rb` 
I haven't been able to reproduce the original issue in stable. Are there other verification steps?

**Comment by Tyriar** [comment]
@alexr00 the issue was a result of the time to pull in data from the pty and render a frame in the terminal taking too long for the renderer to keep up. It should be much more difficult to run into this problem now on slow hardware as data parsing time is capped at ~12ms where as before it was essentially unbounded. If that worked then I'd call this verified.
