### ISSUE TITLE
Is it possible to use `$ref` & `definitions` in extension configuration contribution?

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#68884]
In `package.json`
```javascript
"contributes": {
    "configuration": {
        // here
    }
}
```
With relative path to file or `definitions` in `package.json`.

**Comment by usernamehw** [comment]
#20791

> But yes, you can do a $ref to an full URL. Relative URLs are not supported inside the configuration.

Is there an open issue to support relative URL? Why is it not supported in the first place?

Should I modify user's `package.json` in some postinstall script to make this work?

**Comment by aeschli** [comment]
Where would you place the definitions?

**Comment by usernamehw** [comment]
Any of the 2 would do.

1. At the top of `"configuration"`:
```javascript
"configuration": {
    "type": "object",
    "title": "Extension",
    "definitions": {
        "items": {
            // ...
        }
    },
    "properties": {
        // ... somewhere inside: "$ref": "#/definitions/items"
    }
},
```
2. In a separate file

```javascript
// schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "items": {
            // ...
        }
    },
}
```
```javascript
// package.json
"configuration": {
    "type": "object",
    "title": "Extension",
    "properties": {
        // ... somewhere inside: "$ref": "schema.json#/items"
    }
},
```

**Comment by aeschli** [comment]
$ref to a separate, external schema should already work.
That said, I'm in flavor of keeping it simple and keep the configuration point restricted to a subset of scheme functionality. That's why I'm not keen of recommending to use $refs.

We haven't really documented what configuration all allows, but when I will, I'll keep everything very limited to a subset of the schema capabilities.
Reason for this that we want to programmatically access and understand the configuration without the need to implement full JSON schema support in our configuration manager.
Surely that will means more verbose configuration points for some extension authors. But given that a typical extensions defines only a few settings, that's acceptable.

So, no plans of adding `$ref` & `definitions` support

**Comment by usernamehw** [comment]
How do I make recursive schema work?
