### ISSUE TITLE
vscode.workspace.asRelativePath should support to return a real path

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#68929]
If a workspace folder has a name defined in its *.code-workspace file,
`vscode.workspace.asRelativePath` will return paths that start with this name and which cannot be found in the filesystem.

I propose to add a second boolean argument to `asRelativePath` to force it to return the real relative path. Without that it is very difficult to determine the real relative path for a given url.

/cc @bpasero

**Comment by bpasero** [comment]
I actually think that we should never give out the name of a workspace as result of `asRelativePath`.

@jrieken looks like this got added a long time ago via https://github.com/Microsoft/vscode/commit/7a8bb07f4a6d9cbb42823e762d50ce5f3be4e983. Not sure we could change it now, but a better solution imho would be to join the relative path with the `basename` of the workspace URI instead of its name?

**Comment by jrieken** [comment]
> with this name and which cannot be found in the filesystem.

The idea of this function is to generate UX labels, not something that can be found on disk. The name is a bad pick and the doc isn't clear but that's the intention. Given that, I think it does make sense to prefix the workspace name. Not sure if extending this function to be file system friendly is good. 

> Without that it is very difficult to determine the real relative path for a given url.

Are there no node utils for this?

**Comment by weinand** [comment]
I understand that asRelativePath returns UX labels (because I was asking for it some time ago).
But there is a need for filesystem semantics too. 
That's why I'm asking for a boolean to control this...

I've started to use "path.relative" which leads to this cruft: https://github.com/Microsoft/vscode-node-debug/blob/adfbdc2733c034927528760034e71b7d30865583/src/node/extension/configurationProvider.ts#L278-L285
