### ISSUE TITLE
Focus is lost when inserting snippets with mouse click

### ISSUE THREAD

**Issue by usernamehw** [Microsoft/vscode#68935]
Issue Type: <b>Bug</b>

![focus](https://user-images.githubusercontent.com/9638156/52969268-cac29d00-33c0-11e9-87fa-72d847979a83.gif)

VS Code version: Code - Insiders 1.32.0-insider (bbe40c8cb0901c439b3b61221a0197fb6723783e, 2019-02-18T10:48:37.179Z)
OS version: Windows_NT x64 10.0.17763

**Comment by jrieken** [comment]
@joaomoreno did something in the list change?

**Comment by joaomoreno** [comment]
@jrieken It definitely looks like it... thought I don't know what widget, since the suggest widget disables all mouse controlling code from the list and does it itself.

When reading the code, it makes sense that on click the list gets focus. Here's my proposed change, which prevents that behavior: https://github.com/Microsoft/vscode/pull/69348
