### ISSUE TITLE
扩展宿主意外终止

### ISSUE THREAD

**Issue by ChangeZhang** [Microsoft/vscode#68950]
- VSCode Version:  1.31.1 (1.31.1)
- OS Version: mac os Mojave version 10.14

Steps to Reproduce:

1.
![image](https://user-images.githubusercontent.com/6948367/52986724-86bcb000-3433-11e9-8889-7eeb31586640.png)

2.
![image](https://user-images.githubusercontent.com/6948367/52986732-90461800-3433-11e9-8595-3a910e142ab2.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by byyxx128** [comment]
Translation of the title:
> Extension host terminated unexpectedly

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
