### ISSUE TITLE
getWordRangeAtPosition returns quotes around words for JSON type files

### ISSUE THREAD

**Issue by dakaraphi** [Microsoft/vscode#69012]
getWordRangeAtPosition returns a range including the quotes when a file type is JSON.  
However, this is inconsistent with other file types and I think this is a regression from previous behavior for JSON.

- VSCode Version: 1.31.1
- OS Version:

Steps to Reproduce:

1.  Open a JSON file
2.  Within an extension, call the getWordRangeAtPosition API
3.  The range returned will include more surrounding quotes for words in the JSON file.

Example:
{
   "attribute": "value"
}

Placing the cursor within 'attribute' will return a range that includes the surrounding quotes.

**Comment by aeschli** [comment]
The JSON language service defines the word regex to be a full string literal. This has been like that since before 1.0, no changes here.
The reason for this is that what's called a `word` is more like a 'symbol' and used e.g. by JSON code completion to define what is replaced when doing a code assist. E.g. you want to replace (or select) the full key or the full string literal.
Changing the word definition would break several existing code completion provider, so it's not planned.

The `getWordRangeAtPosition` has an optional parameter `regex` where you can pass in the regex that is useful for you.
