### ISSUE TITLE
Create new branch doesn't allow publish, and then pushes to existing branch it was created from.

### ISSUE THREAD

**Issue by ritterb82** [Microsoft/vscode#69063]
- VSCode Version: 1.31.1
- OS Version: MacOS 10.14.3

Steps to Reproduce:

1. Create a new branch
2. Notice there is no button to publish the branch

Does this issue occur when all extensions are disabled?: YES

When i create a branch, it no longer shows the publish icon.  If I click the sync icon, it just syncs the content to the original branch on remote.

I've attached the git OUTPUT, and a video demonstration.  I have multiple different GIT projects and it does this on ALL Projects.  Even brand new projects I've just cloned.

<img width="672" alt="branch-doesnt-show-publish" src="https://user-images.githubusercontent.com/565806/53107181-7fb0a300-3502-11e9-8e34-db86d15d47bc.png">

![branch-issue](https://user-images.githubusercontent.com/565806/53107463-0feee800-3503-11e9-9375-2654ca2853aa.gif)

**Comment by mjswensen** [comment]
I just ran into this as well. Here is an example workflow that demonstrates the problem:

1. While working on `feature-branch-a`, a small bit of work needs to go on its own branch, which should be freshly created off of remote `origin`'s `master`.
2. In VS Code, `Git: Create branch...`, enter branch name, choose `origin/master`

**Expected behavior:** VS Code creates a new branch, based on `origin/master`, with no upstream branch set.

**Actual behavior:** VS Code creates a new branch with `origin/master` set as the upstream.

3. Commit
4. Push... 💥💥💥 to `master` instead of new branch 💥💥💥

(The expected behavior would avoid the workaround of having to check out and pull `master` before creating the branch.)
