### ISSUE TITLE
Jump to error by double clicking on message in output window does not work

### ISSUE THREAD

**Issue by alexxx537** [Microsoft/vscode#6906]
- VSCode Version: 1.1.1
- OS Version: windows 7

Steps to Reproduce:

1. My project is in C language.
2. Root folder structure:
---+.vscode

---prj

------(this is where build starts)

---headers

------(only *.h. There are other folders with header files)

---source

------(only *.c. There are other folders with source files)
3. Error message structure:
    ..\source\<file>.c(<line>): error: <message>
    example:
    ..\source\serial_commands.c(511): error:  #65: expected a ";"
    task.json :
    "problemMatcher": {
	 "owner": "c",
	 "fileLocation": ["relative", "${workspaceRoot}"],
	 "pattern": {
	 "regexp": "^.{3}(.*c|.*h)\\((\\d+)\\):\\s+(error|warning):.*:\\s+(.+)$",
		"file": 1,
		"line": 2,
		"severity": 3,
		"message": 4
	}
   }
This captures errors and warnings.
4. When error occurs double click on message to jump to error. That does not work:/

**Comment by dbaeumer** [comment]
@isidorn assigning to you as the 'owner' of the output window. @bpasero once looked into this and we concluded that the output channel needs to allow link detection customization for this since detecting the file portion in a problem output can't be done generically. The task framework has the necessary information though due to the problem matcher.

**Comment by isidorn** [comment]
dup of #586
