### ISSUE TITLE
Issue with lua strings when re-indenting

### ISSUE THREAD

**Issue by Emexus** [microsoft/vscode#69083]
Issue Type: <b>Bug</b>

In lua, with strings like "function", it indents all lines below it.

Example:
```lua
local isFunction = type(someVar)=="function"
   thisIsIndented()
   everyThingBelowToo()
```

This issue does not exist when writing in comments, only with strings like in the example above.

VS Code version: Code - Insiders 1.32.0-insider (aeaef41d51201e555735f5e8d2f38a9d0ddb9026, 2019-02-20T06:17:32.389Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Emexus** [comment]
The issue is still present in Version: 1.34.0-insider (user setup) (Commit: d234937aedcbc265d2272ba5861125293239f9c7)

**Comment by PumpkinVision** [comment]
The issue is still present in Version 1.46.1 (user setup), commit cd9ea6488829f560dc949a8b2fb789f3cdc05f5d.

To reproduce:
print ("about to declare the PrintSomething function"); <pressing enter results in an indent>

print ("about to declare the PrintSomething fn"); <pressing enter does not result in an indent>

**Comment by rebornix** [comment]
It's caused by an immature indentation rule, to workaround this issue please set `editor.autoIndent` to `advanced`.
