### ISSUE TITLE
Support to install and uninstall extensions from cli

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#691]
_From @Tyriar on November 26, 2015 2:1_

Similar to [`apm`](https://github.com/atom/apm)'s `install` and `uninstall` commands, it would be great to have an official way of installing and uninstalling extensions via the command line in a platform independent way.

This would enable a nicer way of maintaining a consistent development environment across multiple PCs/platforms without resorting to symlinking the extensions to cloud storage (see https://github.com/Microsoft/vscode/issues/679).

_Copied from original issue: Microsoft/vscode-vsce#48_

**Comment by pascalberger** [comment]
:+1:

**Comment by brunolm** [comment]
:+1:

**Comment by mrmlnc** [comment]
It would be very convenient :+1:

**Comment by chadbr** [comment]
yes please!

**Comment by eyalsk** [comment]
_I posted this in another suggestion but maybe this is a better place to post it so here it goes:_

I'd **really** want to have is a Console that I can use to install extensions, install nuget packages, install npm packages or another kind of packages and the only thing it needs is Intellisense for packages but yeah definitely unified experience for installing packages.

Instead of tackling specific problems, I'd argue that a much better design is to let programmers handle it and what I mean by that is creating a Console that is extensible and is designed for installing packages, whatever the package might be, VSCode extensions, nuget, bower, npm, you name it.

**Just to be clear**, I mostly suggest the experience of the Package Manager Console available in Visual Stuidio to Visual Studio Code but taking it few steps farther.

**Comment by Tyriar** [comment]
I propose the following args:

```
# Install
code --install-ext=ms-vscode.csharp
code -i ms-vscode.csharp

# Uninstall
code --uninstall-ext=ms-vscode.csharp
code -u ms-vscode.csharp

# List installed extensions
code --list-ext
```

With the `--list-ext` arg returning a flat list of extension aliases:

```
$ code --list-ext
donjayamanne.python
lukehoban.Go
ms-vscode.csharp
```

**Comment by eyalsk** [comment]
@Tyriar I'd go with either one of these but the POSIX/GNU+ style is more appealing to me.

PowerShell style.
```
# Install
code install-extension ms-vscode.csharp

# Uninstall
code uninstall-extension ms-vscode.csharp

# List installed extensions
code get-extension
```

POSIX/GNU+ style.
```
# Install
code extension --install ms-vscode.csharp
code ext -i ms-vscode.csharp

# Uninstall
code extension --uninstall ms-vscode.csharp
code ext -u ms-vscode.csharp

# List installed extensions
code extension --list
code ext -ls 
```

**Comment by joaomoreno** [comment]
Unfortunately, this will bleed into May. We need further architecture work in the cli and main processes for this to happen. Anything without it would be half baked.

Namely, we need to

1. Instantiate the gallery and extension services on the CLI process. Both of these have dependencies that are nowadays very hard to instantiate on their own.
2. Not only that but make that instantiation dynamic, such that the CLI runs as fast as possible to answer the simple questions such as `--version` and `--help`.
3. Further refactor the main processes' services to become more lightweight and possibly used by any process possible.

**Comment by eyalsk** [comment]
@joaomoreno great! that way you will have more time to think about it! ;)

**Comment by egamma** [comment]
@joaomoreno makes good sense. I've also updated the April plan.

**Comment by piggyslasher** [comment]
Since we're in June is this already in the main branch?

**Comment by Tyriar** [comment]
Yes this has shipped to both stable and insiders

**Comment by jokeyrhyme** [comment]
It is wonderful. Great work! <3

**Comment by ToMakeSense** [comment]
Make this a new feature!

**Comment by rwatts3** [comment]
does this support installing from github repos or git repos ? 

like atom `apm install somerepo/some-project`
