### ISSUE TITLE
Left mouse button up when selecting text with CTRL pressed causes to follow link

### ISSUE THREAD

**Issue by Iconoclasming** [Microsoft/vscode#6910]
- VSCode Version: 1.1.1
- OS Version: Win8.1 x64

**Steps to Reproduce**:
1. In an HTML file, start selecting link in quotes inside any tag with left mouse button pressed
2. Hold down CTRL
3. Release left mouse button when cursor is above the link

**Expected**: text selection stopped
**Actual**: "follow link" invoked

**Comment by Iconoclasming** [comment]
This issue makes me to be very careful while selecting links and CTRL+C CTRL+V them.

**Comment by natsu12** [comment]
Yes! I want to disable hyperlinks in vscode so badly because every time I copy a link, I use cursor and cmd + c, then vscode determines that I use cmd + click to follow a link and open in browser. That drives me crazy! And I find no clue to turn off hyperlinks in vscode.
![c_e64f1wsaeeiyt](https://cloud.githubusercontent.com/assets/7494889/26154983/3d27c43c-3b44-11e7-9af0-4df55790ee5b.jpg)

**Comment by alexandrudima** [comment]
I agree. The go to link now installs a mouse up listener which makes it very easy to be hit. Go to link should activate only if ctrl is first pressed, **and then** mouse down occurs on the link, **and then** mouse up occurs on the link.
