### ISSUE TITLE
Newly installed debug extension does not work

### ISSUE THREAD

**Issue by actboy168** [Microsoft/vscode#69100]
Previous #69089

Please don't let me contact the author of the extension because he is already here.

It seems that the hot reload extension is not working correctly. Please tell me how to fix it. If it needs the extension to modify anything, thanks.

**Comment by sandy081** [comment]
@actboy168 Can you please explain what is not working with steps to reproduce.

**Comment by actboy168** [comment]
1.Open a directory
2.New file `test.lua`
3.Type `print 'hello'`
4.Install extension actboy168.lua-debug
5.F5

It will get an error message.
```
Cannot find debug adapter for type 'lua'.
```

**Comment by weinand** [comment]
@isidorn @alexandrudima if the lua debugger hsn't been upgrade to dynamic install, installing it should still ask for a reload, right?

**Comment by actboy168** [comment]
@weinand 
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)

**Comment by isidorn** [comment]
The issue is comming from here https://github.com/Microsoft/vscode/blob/275d2a02ca922738b58cea7dbf9dce229ea75f21/src/vs/workbench/contrib/debug/node/debugger.ts#L92

For my machine the issue is that the debug adapters are set to run in EH and the debug adapter factories are not aware of the lua debug type.
Forwarding to @weinand since he introduced the debug adapter factories.

Here's the code pointer where we get pinged from the extension service that a new extesion is installed. It might need to aslo properly update the factories https://github.com/Microsoft/vscode/blob/275d2a02ca922738b58cea7dbf9dce229ea75f21/src/vs/workbench/contrib/debug/electron-browser/debugConfigurationManager.ts#L241

**Comment by weinand** [comment]
@isidorn Why are debug adapters are set to run in EH in your case? Do you have LiveShare installed or do you use the setting that forces the DA to run in EH?

**Comment by weinand** [comment]
Oh I see. The extension uses the tracker.

**Comment by weinand** [comment]
@actboy168 the only way to avoid this problem is by not registering a DebugAdapterTracker in the case that the "lua" extension got installed via hot reload.

**Comment by weinand** [comment]
I have a fix which eliminates the error message "Cannot find debug adapter for type 'lua'.".

But always get the following error:
<img width="459" alt="2019-02-22_22-56-54" src="https://user-images.githubusercontent.com/1898161/53273815-56a43400-36f5-11e9-88be-96aec1ad07b4.png">

Since this error does not go away after a reload, I suspect that lua is not working on my macOS anyway.

**Comment by weinand** [comment]
@actboy168 please try the Insiders from next Monday.
