### ISSUE TITLE
Revisit need for node/electron-browser in workbench/contrib/tasks

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#69113]
Refs https://github.com/Microsoft/vscode/issues/68302

I am not sure why `src/vs/workbench/contrib/tasks` has to have most of its files in `electron-browser` land. Please consider lifting this to `browser` if possible.

If there is something blocking this task, speak up and we need to think about introducing new services as needed.

//cc @dbaeumer

**Comment by dbaeumer** [comment]
Major reason is that the `ProcessTaskSystem` depends on node API to spwan processes. Even the `TerminalTaskSystem` as some dependencies for FS API to find executables in win32 land. 

Since the task service depends on them (no registry right now) it pulls everything else into electron browser.

IMO the right solution to fix this is to move task execution completely to the extension host where we have node APIs by definition.

**Comment by bpasero** [comment]
> IMO the right solution to fix this is to move task execution completely to the extension host where we have node APIs by definition.

Yes :+1:
