### ISSUE TITLE
Mac OS dock menu does not clear and can contain stale entries

### ISSUE THREAD

**Issue by bennyscetbun** [Microsoft/vscode#6912]
- VSCode Version: 1.1.1
- OS Version: 10.11.5 (15F34)

Steps to Reproduce:
1.  right click vscode icon in the dock

On version 1.1.0 i was able to see the "open recent" values and open a new vscode from it (it was equal to click on File=>open recent=> click a link)
Not anymore :(
Could someone revert that or explain why it s not here anymore?
Thanks

**Comment by bpasero** [comment]
Yeah also noticed that, no clue why, might be electron update.

**Comment by bpasero** [comment]
@bennyscetbun do you still see this?

**Comment by bpasero** [comment]
Seems to work ok now with the electron update.

**Comment by bennyscetbun** [comment]
Sorry i ve missed your message.
Seems to work fine now :) my bad

**Comment by bpasero** [comment]
Thanks

**Comment by psnider** [comment]
Mac OS 10.11.6
MS VS Code 1.6.1

This happens for me.

It seems that the menu for the Code icon in the dock isn't updated correctly.
I had created two workspaces for the same repo in two different locations for testing.
The first one is the main one I use for development.
The second one was just for testing, which I deleted when I was done.

Whenever I select my repo workspace name from the menu for the Code icon in the dock, nothing happens.
If I select another repo workspace name, it works.

My guess is that the entry in the menu for the Code icon in the dock is still referring to the test workspace that no longer exists, so nothing happens when I try to launch Code with it.

Also, the menu for the Code icon in the dock appears to be unaffected by the **File -> Open Recent -> Clear Items** command.

**Comment by bpasero** [comment]
Thanks, since we do not own this code (it is in Electron), a fix would be needed in Electron land.

**Comment by taivu** [comment]
been living with this for a few months. happening on 1.16.0. clearing recents has no affect on dock context menu.

**Comment by taivu** [comment]
https://github.com/atom/atom/issues/12997

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1662
