### ISSUE TITLE
Add transformations to snippets variables

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#6920]
TextMate snippets page [says](https://manual.macromates.com/en/snippets):

> 7.7 Transformations
> 
> There are situations where we want our placeholder text mirrored but with slight changes or where we want some text to appear depending on the value/presence of a placeholder.
> 
> We can accomplish this by doing a regular expression substitution on the placeholder text (when mirroring it). The syntax for this is: ${«tab stop»/«regexp»/«format»/«options»}.

It looks like transformations are not supported in VS Code. Would be a great addition.

**Comment by leonardob17** [comment]
+1

**Comment by sunabozu** [comment]
Are there any news about it?

**Comment by mpearon** [comment]
Has there been any headway made on this issue, or has it been prioritized?

**Comment by jrieken** [comment]
Maybe... I am doing some snippet work this month, but not exclusively. We have enabled multi cursor support which I believe was the number 1 complained. Next could be nested snippets (invoke snippets when completing a snippet), choice support and transforms.

**Comment by royprocops** [comment]
Same request as others here. I would like a snippet to generate boilerplate for my React components, based off of the filename without the filename extension. Either need another variable for filename without file extension, or regular expressions to transform the filename.
Thanks!

**Comment by shvfn** [comment]
I, too, miss the feature to use the filename without the extension in a snippet. Perhaps you could add  $TM_FILENAME_BASE as a workaround until this feature gets implemented? 
Thanks!

**Comment by joelpresence** [comment]
I would love this for creating go test files.  For example, if I'm in a go package `a/b/c`, I put my tests for package `c` in `a/b/c/tests`, its own tests package.

I have a created a snippet like the following in `go.json`:
```
{
	"Test file": {
		"prefix": "tt",
		"body": [
			"package tests",
			"",
			"import (",
			"\t\"github.com/stretchr/testify/assert\"",
			"\t. \"a/b/$1\"",
			")",
			"",
			"func Test$2(t *testing.T) {",
			"\tassert := assert.New(t)",
			"",
			"\t$0",
			"}"
		],
		"description": "Create a new test file"
	}
}
```
which produces
```
package tests

import (
	"github.com/stretchr/testify/assert"
	. "a/b/"
)

func Test(t *testing.T) {
	assert := assert.New(t)

	
}
```
However, if I'm in a file `a/b/c/tests/foo_test.go` when I expand this snippet, then the line `. "a/b/"` should be `. "a/b/c"` because these are tests for the the `c` package.

How do I accomplish this?

I tried using `TM_DIRECTORY` but it doesn't seem that I can manipulate it to remove trailing cruft.  Nor can I use `workspaceRoot` ...

I'd really like to have access to the "parent package" but being able to manipulate the current filename with knowledge of workspace root would probably be good enough.

Will the fix mentioned in this issue support my use case (pretty common for go developers) and is there an ETA?  :-)

Thanks!

**Comment by jrieken** [comment]
fyi - I have just merged https://github.com/Microsoft/vscode/pull/33253 which is about snippet transformations for snippet *variables*.

**Comment by jrieken** [comment]
If have re-purposed this issue to be about snippet transformation for *snippet variables*. For transformations of snippet placeholders i have created https://github.com/Microsoft/vscode/issues/34683. Variable transformations will ship in September.
