### ISSUE TITLE
Support Live Reloading Scenarios

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode#6930]
We'd like VS Code and the Node Debugger to support Live Reloading Scenarios. The current behavior is preventing React-Native users from having a good experience: https://github.com/Microsoft/vscode-react-native/issues/74

Currently it's not supported so modifying breakpoints while the program is running can have weird results (Breakpoints set in one line, appear in another line, or get deleted completely).

Things that we'd like to be supported are:
- Be able to edit a file in memory, and set a brekpoint before saving the file, so if there is any source map associated at all with this file at all, it'll map to the wrong thing, so VS Code would need to Remember the line where the breakpoint was set, and wait until the proper source map was loaded before actually setting the breakpoint.
- Be able to edit a file, save it, and set breakpoints before the recompilation process is finished, so initially it'll be associated with the wrong source map.
- The red and greyed out stop signs for the breakpoints should correctly indicate if the breakpoints were successfully installed.
- Editing a source file with breakpoints should result in intuitive results when adding lines before, or after the breakpoints, or even on the same line.

**Comment by weinand** [comment]
related issues:
- meteor: https://github.com/Microsoft/vscode/issues/7117
- SystemJS: https://github.com/Microsoft/vscode/issues/4492
- babel-register: https://github.com/Microsoft/vscode/issues/5728

**Comment by sivaraman-gmail-com** [comment]
Will implementation of this also allow for live javascript editing when debugging a web app via the Chrome debugger extension? This is a key feature missing compared to IDEs such as WebStorm and debugging from within Chrome itself.

**Comment by auchenberg** [comment]
@weinand @roblourens We seem to have closed the blocking issues for this scenario, which means we should be good to have debuggers implementing file-watching-like functionality.

We should start by prototyping this in the Chrome family debuggers, which would light up this for Node, Chrome, Edge and others. See https://github.com/Microsoft/vscode-chrome-debug/issues/216

**Comment by nojvek** [comment]
Will there be any config to place in a hook call? E.g after live edit is called, a command defined in debugger target config is automatically executed. 

This opens up great possibilities for hot reloading and test driven development. 

Since this will work with async sourcemaps and file watchers I think it will be a lot more powerful than the live edit scenario chrome gives out of the box.

**Comment by weinand** [comment]
A typical live edit scenario.

- set autosave to off
- set breakpoint in some TypeScript source
- start debugging
- make program hit breakpoint, e.g. load a url in a browser
- single step a little in the TypeScript source until you spot some broken code
- fix source code in editor
- breakpoints are marked as unverified (grey) because underlying source has changed
- save source
- breakpoints will show up as verified again
- if current location is in the scope of the edited range, location jumps to the beginning of that range (like "restart frame" action)
- you can single step through the fixed code
- if everything works fine continue program execution

Behind the scenes:
- saving the TypeScript source triggers a build watcher to transpile the TypeScript to JavaScript and create a corresponding source map (this is independent from the debugger's live edit support)
- a file watcher in the debug adapter detects the changes to both files
- the path to the JavaScript file matches the path to a loaded script which triggers this:
- the DA replaces the loaded script with the new contents
- if this is successful it invalidates any cached source maps referring to the JavaScript
- if current location is in the scope of the edited range, issue a "restart frame"
- request a "reapply" for all breakpoints for the affected file(s). As a side effect breakpoints are revalidated.

**Comment by auchenberg** [comment]
@weinand For the `the DA replaces the loaded script with the new contents` step you have outlined. Are you referring to having the DA using API's such as Node/Chromes [debugger.setScriptSource](http://compatibility.remotedebug.org/Debugger/Node%20(V8)/commands/setScriptSource)?

The file-watcher in VS/DA should be togglable, as many developers for front-end scenarios already relies on WebPack HMR or similar, which enables https://medium.com/@auchenberg/live-edit-and-debug-your-react-apps-directly-from-vs-code-without-leaving-the-editor-3da489ed905f

**Comment by weinand** [comment]
@auchenberg yes, the 'node2' DA would use Node/Chrome's [debugger.setScriptSource](http://compatibility.remotedebug.org/Debugger/Node%20(V8)/commands/setScriptSource) and node would use `changeLiveRequest`.

The goal of this analysis was to figure out the likely interaction between VS Code editor/debugger and the DA. How the DA implements Live Edit is an implementation detail of the DA.

The file-watcher in a DA is an implementation detail of the DA and as such is not covered by the DAP. So every DA that uses a file-watcher can provide a flag in its launch config to control it.

**Comment by djmisterjon** [comment]
for me this issue is crucial and should reOpen please.
I also need live edit in my context.
![aef4eqag](https://user-images.githubusercontent.com/24865815/45452996-7e569100-b6ad-11e8-82f8-57ee58a4f48b.jpg)

**Comment by weinand** [comment]
Live edit support must be implemented by individual debuggers. It is not something VS Code can do generically.

For JS/TS you can use nodemon which is already supported by the VS Code node debugger.

**Comment by djmisterjon** [comment]
@weinand hey thank
so i install **npm install -g nodemon**
but it look not support by vscode, i can see how add to configurations ? 
Are you sure it compatible ?
![image](https://user-images.githubusercontent.com/24865815/45456776-0a6eb580-b6ba-11e8-8ed9-5fb408981138.png)

**Comment by weinand** [comment]
read:
https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_restarting-debug-sessions-automatically-when-source-is-edited
https://github.com/Microsoft/vscode-recipes/tree/master/nodemon
