### ISSUE TITLE
Hover: jsdoc portion should wrap to ~80-100 chars

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#69388]
#69204

Version: 1.32.0-insider (user setup)
Commit: [393b48d](https://github.com/Microsoft/vscode/commit/393b48d4a5de85b6fa1d2ad0a59588d6715e12ea)
Date: 2019-02-25T01:34:48.785Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18841

![image](https://user-images.githubusercontent.com/2193314/53357977-f0313880-38e3-11e9-8d42-6a10546fbae1.png)

It would be easier to read if wrapped somewhere around here (or a little more):

![image](https://user-images.githubusercontent.com/2193314/53358039-1c4cb980-38e4-11e9-96e9-d0370537ab97.png)

Maybe this should only apply the markdown sections that are not fenced code blocks.

**Comment by sandy081** [comment]
I do not think hover should do the wrapping and should show the hover as it is given by the extension. It is the responsibility of the extension to preserve the wrapping provided by the user while writing the doc. 

@mjbvz May I know if you are preserving the format of the js doc?

**Comment by mjbvz** [comment]
JS/TS does not wrap text documentation text and also does not know the size of the hover

Users can manually wrap jsdoc text if they wish (it is treated as markdown content so just end the line with a double space to hard wrap a line)

**Comment by sandy081** [comment]
I did not mean JS/TS server to wrap the text. I would expect they should preserve the format of the doc provided by the user. 

I checked that JS/TS is preserving the format but the markdown renderer is not showing the new lines. For eg JS/TS sends following markdown contents with new line characters at end of each line

```
"Represents a reference to a command. Provides a title which
will be used to represent a command in the UI and, optionally,
an array of arguments which will be passed to the command handler
function when invoked."
```

But the markdown renderer is rendering it without respecting the new line characters.

![image](https://user-images.githubusercontent.com/10746682/53395172-73649400-39a1-11e9-9f22-b57f67a976cb.png)

@jrieken Do you have any idea?

**Comment by jrieken** [comment]
> @jrieken Do you have any idea?

About the wrapping? To my knowledge that's how markdown works. You need two line breaks to get a visible line break

**Comment by sandy081** [comment]
@mjbvz So new lines are missing when getting converted from a string to mark down. Can you please make sure new lines get preserved?

**Comment by mjbvz** [comment]
@sandy081 This wrapping behavior is by design for markdown and I think it makes sense for documentation:

- Most users are not intentionally hard wrapping their docs so that text is broken up a specific way, they add the line breaks so that the lines are not too long in the source
- It leaves the hover widget to layout the text however it thinks would be be best instead of relying on the user to do break lines.
- If the user hard wraps at a weird position—such as column 160 or column 40—and we preserved the breaks, the hover may end up looking really bad

As @jrieken mentioned, you can add a hard wrap by ending a line with two spaces.

**Comment by Tyriar** [comment]
@sandy081 markdown is working correctly imo, the wrapping has to be done by the hover as wrapping points are different depending on the font family, size, etc. The fix for this probably looks something like this:

```css
.hover .markdown {
  max-width: Xpx
}
.hover .markdown .code {
  /* break out of container in css or JS*/
}
```

**Comment by sandy081** [comment]
I see different tools take different approaches here. For eg., Sublime wraps as per how user wrapping.

If the hover decides to wrap, then it should have same wrapping for all hovers. Otherwise the hovers look inconsistent. For eg., if we wrap TS/JS doc hovers at smaller width and leave others (like problems or hovers with code) with larger width it will look as below:

![image](https://user-images.githubusercontent.com/10746682/53443309-b2c7ca80-3a0b-11e9-8178-406a4761b62c.png)

@misolori FYI

**Comment by sandy081** [comment]
I think I liked this solution after playing around a bit. Here are some examples that show before (no wrapping) and after (with wrapping)

- Before
![image](https://user-images.githubusercontent.com/10746682/53446163-967b5c00-3a12-11e9-9c1f-38df5bae13c5.png)

- After
![image](https://user-images.githubusercontent.com/10746682/53446276-dd695180-3a12-11e9-8920-006eb0514856.png)

---

- Before 
![image](https://user-images.githubusercontent.com/10746682/53446156-8bc0c700-3a12-11e9-9024-da8c5b538bfd.png)

- After
![image](https://user-images.githubusercontent.com/10746682/53446291-e528f600-3a12-11e9-8ea1-a3a8c295343a.png)

---

- Before
![image](https://user-images.githubusercontent.com/10746682/53446190-a430e180-3a12-11e9-8576-0a74ee566497.png)

- After
![image](https://user-images.githubusercontent.com/10746682/53446309-ee19c780-3a12-11e9-98f8-8dd25472f17a.png)

**Comment by sandy081** [comment]
Fix is to have a smaller max width (500px) for hovers not containing code except for problem hovers.
