### ISSUE TITLE
Hover: horizontal scroll bar obscures actions

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#69391]
#69204

Version: 1.32.0-insider (user setup)
Commit: [393b48d](https://github.com/Microsoft/vscode/commit/393b48d4a5de85b6fa1d2ad0a59588d6715e12ea)
Date: 2019-02-25T01:34:48.785Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18841

![image](https://user-images.githubusercontent.com/2193314/53358465-4baff600-38e5-11e9-9810-fef63eff079e.png)

**Comment by beastdestroyer** [comment]
Would you say making the height taller so that the scrollbar fits nicely on the bottom since im guessing these scrollbars have a fixed height

**Comment by sandy081** [comment]
Not sure what's the right way to fix this. One approach is to have some space allocated for scroll bar but that will make hover does not look good. I also think that scroll bar appears very rarely. Other approach is to dynamically change the height when the scroll bar appears or disappears. Don't know if the latter solution is possible. But will investigate.

**Comment by Tyriar** [comment]
If it's possible, ideally the extra space would only appear when needed.

**Comment by roblourens** [comment]
This also happens in the debug hover where the horizontal scrollbar partially covers objects that can be expanded or selected. It's short enough that you can click around it in that case.

**Comment by eamodio** [comment]
The horizontal scrollbar shows up very often in debug hovers for me, so this isn't a rarity.

Also, not sure if this is 100% related, but if not, let me know and I can open another issue. But sometimes the debug hovers open slightly too small for the content so you get unneeded scrollbars... and then often it ends scrolled to the end, rather than the start:

![image](https://user-images.githubusercontent.com/641685/55690487-72d7f980-5960-11e9-97df-809f2b380f43.png)

In that image, I didn't touch/scroll the hover, it opened that way (seemingly scrolled to the end, rather than the start). But in this case there is no need for a vertical a scrollbar there at all.

My guess is that this only happens on machines with visible scrollbars by default (Windows, macOS if you turn off the autohide scrollbars) and the content is just slightly too big for the hover.

**Comment by sandy081** [comment]
@isidorn Is debug hovers are related to this issue or are they special?

**Comment by isidorn** [comment]
Debug hover scroll bar is unrelated to this. They are special since they use the tree.

**Comment by sandy081** [comment]
Filed a separate issue for debug hovers - https://github.com/Microsoft/vscode/issues/72144

**Comment by M0ns1gn0r** [comment]
The editor seems to be unable to wrap namespaces.

![image](https://user-images.githubusercontent.com/5908454/68478610-99c91780-0230-11ea-8986-0291758be53c.png)

**Comment by sandy081** [comment]
I think both solutions (adding space always or when needed) are not good and non trivial. Making it resizable could be a better option. This has been there for long time and I have not got any reports from users after it was filed during testing of this feature. Hence, I would close this as won't fix.

**Comment by eamodio** [comment]
Here's another case of this: https://github.com/microsoft/vscode/issues/109836

**Comment by sandy081** [comment]
Reopening it and assigning to @alexdima.
