### ISSUE TITLE
Flashing red status on the Outline view

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#69406]
Testing #69299:

Have this SCSS, `|` is cusor:

```css
.foo {
  .foobar {
|

.foo {}
```

Press enter, you see flashing red:

![flash](https://user-images.githubusercontent.com/4033249/53364312-68ebc100-38f3-11e9-8495-5ac0565cbf11.gif)

**Comment by jrieken** [comment]
Same in 1.31.x, not a regression, still unhappy. The challenge is that markers are matches at the time of editing and later (after the edit) being updated. That causes the flicker

**Comment by jrieken** [comment]
Moving to March. This is actually tricky because I have an updated outline model, but a "stale" marker model. Checking the markers means that flash completely and I think that actually worst (see gif). We can consider delaying the update a little more, e.g optimistically wait a little for a markers change event.

![feb-26-2019 12-28-59](https://user-images.githubusercontent.com/1794099/53409809-44124f00-39c2-11e9-96c8-ff37d91eee62.gif)

**Comment by alexr00** [comment]
I'm not sure how to verify this. I can repro on stable, but in insiders the whole outline is red so there is no opportunity for it to flash red.

**Comment by jrieken** [comment]
Yeah, that's already it. When there is no more flashing then everything is good
