### ISSUE TITLE
Using workspace's typescript version should look in parent node_modules

### ISSUE THREAD

**Issue by testerez** [Microsoft/vscode#69416]
When asking VSCode to use workspace's version of Typescript I get this error:
> The path [workspace dir]/node_modules/typescript/lib doesn't point to a valid tsserver install.
> Falling back to bundled TypeScript version.

This is because I work in a monorepo and I open in VSCode only the package I'm working on. As a result typescript is installed in parent directory and VSCode does not find it.

I think VSCode should use the standard node module resolution and walk up the directory tree to find Typescript installation.

- VSCode Version: 1.31.1
- OS Version: macOS 10.14.3 

**Steps to Reproduce:**

1. `mkdir testproject && cd testproject && npm init -y && npm i typescript`
2.  `mkdir nested && code nested`
4. In vscode Run command `Typescript: select typescript version`
5. VsCode error:
> The path [workspace dir]/node_modules/typescript/lib doesn't point to a valid tsserver install.
> Falling back to bundled TypeScript version.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is an intentional behavior. We used to resolve typescript this way but it turns out people would have really old TS versions installed in their user directory, and these would unexpectedly get picked up.

Two options:

- Configure `tsdk` in your user settings using an absolute path
- Open the repo as a multiroot workspace. Put the root as the first folder in the workspace and the sub folder you want to work on below it. This should let you load the typescript version from the root.

**Comment by heitorsilva** [comment]
I can confirm that `Open the repo as a multiroot workspace. Put the root as the first folder in the workspace and the sub folder you want to work on below it. This should let you load the typescript version from the root.` works!

thx @mjbvz
