### ISSUE TITLE
Getting error message "cannot find the module 'eslint-plugin-react' when opening .js.

### ISSUE THREAD

**Issue by v-pavanp** [Microsoft/vscode#6943]
- VSCode Version:1.2.0-alpha
- OS Version: Windows

I observed when I am opening any .js from my project folder I an getting error pop-up "Failed to load plugin react: cannot find the module 'eslint-plugin-react'.
I didn't understand why should user get this error message and what action they need to take to fix it. Error message it is not clear to the user whether they need to perform any manual action like install extension or any package.

![eslint-error](https://cloud.githubusercontent.com/assets/17735796/15591862/74e9dbac-2354-11e6-8ba6-433f74a42904.gif)

**Comment by dbaeumer** [comment]
This message is shown when the eslint extension tries to validate the file but fails since a specified eslint plugin can't be loaded. As soon as a extension and alter the settings we will improve this by allowing the user to exclude eslint from running using a button click. We have an issue for that. Closing this one.
