### ISSUE TITLE
No new file / folder in explorer context menu

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#69452]
Open context menu on the background. You get

<img width="256" alt="capture" src="https://user-images.githubusercontent.com/1931590/53415241-ffda7b00-39d0-11e9-8602-39228fe0eacd.png">

**Comment by isidorn** [comment]
I can not repro, either on mac or on windows.
Either way these are custom menus and not explorer related (since you can see that Find in Folder is also missing which is a search action), so forwarding to @sbatten 
@dbaeumer can you always repro? Also with no extensions?

![screenshot 2019-02-26 at 14 54 52](https://user-images.githubusercontent.com/1926584/53417735-7fb71400-39d6-11e9-9f49-695760f38f7c.png)

**Comment by dbaeumer** [comment]
Now it doesn't repro anymore. Lucky me I took a screen shot :-)

**Comment by isidorn** [comment]
This has good repro steps #70007
Closing in favor of that one
