### ISSUE TITLE
"Smart" output scroll lock is too sticky

### ISSUE THREAD

**Issue by atombender** [microsoft/vscode#69480]
- VSCode Version: 1.31.1
- OS Version: 10.14.2

![vsc](https://user-images.githubusercontent.com/50314/53442574-9742cc80-39d7-11e9-8283-251b8de77c59.gif)

Steps:

1. Make sure "scroll lock" is turned _off_ in the Output panel.
2. Run your project's test suite inside VSCode, e.g. run Go tests.
3. Click somewhere in the Output panel. This automatically enables the smart scroll lock.
4. Run your project's test suite again. **Scroll lock is still on and prevents the output from being "followed"**.

From where I'm sitting, it looks like the "smart" scroll lock becomes stuck and doesn't unstick when the terminal screen is cleared for a new run.

[This issue](https://github.com/Microsoft/vscode/issues/49110) causes the above unexpected and undesired behaviour. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by atombender** [comment]
Not a dupe of the above.

**Comment by iwittkau** [comment]
This is also an issue for me. #46819 is somewhat of the opposite of what @atombender and I need. 

The output's scroll lock should not be enabled if a test runs again. 

This smart feature works against you in this case because you have to unlock the scrolling and quickly scroll to the bottom to keep the view automatically following again.

**Comment by AlexVPopov** [comment]
Hey, I just wanted to add my two cents on the subject. 

The "smart scroll" / "smart lock" behavior conists in locking the auto-scrolling in the output pane if the user clicks inside the output panel. In order to unlock it, one has to click the icon or move the cursor to the end. Judging based on the number of issues, related to this, I'd say there are plenty of people, whose workflow is either enhanced or crippled by this. For this reason, there should be an option to enable/disable this behavior. When the behavior is off, the only way to explicitly disable or enable auto-scrolling in the output pane should be via the icon (or a shortcut/command) and not as an implicit result of some user action.

**Comment by VideoPlayerCode** [comment]
@AlexVPopov I completely agree. The smart lock is driving me nuts. This evil feature was added in https://github.com/microsoft/vscode/pull/49728

What it means, in effect, is that I press Ctrl-Alt-N to do CodeRunner and see the output of my program. Then I click in the output pane to select something, which due to the "smart" locking causes my scrolling to become locked again. Then I run another CodeRunner but since the stupid output panel is now locked, I can't see the latest output.

Here's someone else describing the problem it causes for CodeRunner users: https://stackoverflow.com/questions/51989532/how-to-completely-disable-output-scroll-lock-in-visual-studio-code

Many people hate the feature, please just make it configurable in settings.json!

**Comment by xgdgsc** [comment]
This is the single most annoying issue for me now.   Here's someone else describing the problem https://stackoverflow.com/questions/58855587/vscode-turn-auto-scrolling-permanently-on

**Comment by asterkrans** [comment]
A quick fix would be to just roll-back the smart scroll-lock feature until it works.

**Comment by Johnlon** [comment]
This issue is so irritating it's actually onthe verge of driving me away from VSCode - it is incredibly bad news that something so cripplingly bad and controvbersial isn't already an option that can be turn off completely in settings.

**Comment by sandy081** [comment]
Will add a setting to opt out if not needed.

**Comment by Johnlon** [comment]
Wow thats a huge help - I've been oscillating between VSCode for editing and the ArduinoIDE for running.

**Comment by dbsxdbsx** [comment]
I  just don't understand why smart scroll would be added as a  compulsory feature.

**Comment by sandy081** [comment]
Provided following setting `output.smartScroll.enabled` to toggle smart scrolling on/off. By default it is `true` to not to break existing users.

![image](https://user-images.githubusercontent.com/10746682/75680504-0d84a980-5c92-11ea-8943-4073eb9f3959.png)

**Comment by sandy081** [comment]
Verify that smart scrolling is enabled only when above setting is true.

**Comment by AlexVPopov** [comment]
@sandy081 how can I do the verification? Do I need to install VS Code Insiders?

**Comment by sandy081** [comment]
Its not yet available in our insiders. Currently we are frozen for 1.43 (Feb) release. The normal insiders pipeline start after releasing 1.43. You can verify then.

**Comment by connor4312** [comment]
For me it seems like even with "Smart Scroll" enabled on Insiders, clicking in the output doesn't stop scrolling. Here's a screen recording testing on stable, where scroll pauses, and insiders: https://memes.peet.io/img/20-04-3af5c0ab-1cbd-4347-9554-99425f52b59e.webm
