### ISSUE TITLE
If you can't upgrade an extension, tell why!

### ISSUE THREAD

**Issue by localhost61** [microsoft/vscode#69482]
Now I know that if I can't install latest version of an extension, it may be because I don't run the latest version on VScode. I learned it [the hard way](https://github.com/eamodio/vscode-gitlens/issues/666), because  it was not obvious and didn't understand why VScode didn't offer to update GitLens from 8.54 to 9.51 on VScode v1.2.1

- Please, in the marketplace, in the header of each extension could you indicate the VScode version needed to install it's latest version.
- When installing an extension, could you alert the user when there is a newer version of the extension that requires a more recent version of VScode.

**Comment by eamodio** [comment]
Yeah, I think it would be great if there was some kind of indication that an extension has a later version that can't be installed because vscode needs to be updated (in addition it is a way to encourage a vscode update). I have definitely had reports both with GitLens and CodeStream of users trying (thinking) they are running the latest version when they weren't because of their vscode was so out of date.
