### ISSUE TITLE
Debug console: missing empty lines

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#69535]
```
console.log('hello');
console.log();
console.log('world');
```

There is no empty line between hello and world.
The issue is in the model which is being overly smart at removing empty lines [here](https://github.com/Microsoft/vscode/blob/3bf1e49c76da3ea190eb8a1c9a3b90741e461990/src/vs/workbench/contrib/debug/common/replModel.ts#L34)

Also check if the empty lines should say they do not have a dynamic height

**Comment by apolopena** [comment]
I tried this and do not get that behavior. Windows 10, Javascript(Babel)

**Comment by DanTup** [comment]
Interestingly, if you right -click and go to "Copy All" and then paste somewhere, the newlines are all there!

**Comment by isidorn** [comment]
I have pushed a simplification of how we are adding string repl elements.
However this is still not fully fixed since the `console.log()` does not send an output event to vscode. So forwarding @roblourens to check why `console.log()` does not send 

When I run this using node, the empty line is nicely printed, so it seems that the node extension is holding out on output events that have an empty line maybe

**Comment by roblourens** [comment]
I see the same in chrome devtools, no log message comes from node. It's kind of weird because `console.log('')` works but not `console.log()`.

Debugged into the node code briefly and I don't see why it wouldn't send an empty message. It looks like the first argument is supposed to be required though: https://developer.mozilla.org/en-US/docs/Web/API/Console/log 🤷‍♂️
