### ISSUE TITLE
VScode doesn't work with vala appmenu

### ISSUE THREAD

**Issue by monyarm** [microsoft/vscode#69596]
- VSCode Version: 1.13.1
- OS Version: Arch Linux X86_64
- DE: XFCE
- WM: I3

Steps to Reproduce:

Neither window.titleBarStyle native or custom work, no matter which one is enabled, the appmenu only shows new and quit.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
@monyarm I am not familiar with vala appmenu. Could you provide some pointers to documentation on vala? Also, could you provide a screenshot of your experience?

**Comment by monyarm** [comment]
Vala Appmenu is a plugin for xfce that adds a global menu to the xfce panel.

Here are screenshots: https://imgur.com/a/Pot5ZPQ
And here is the Vala Appmenu repo https://gitlab.com/vala-panel-project/vala-panel-appmenu/

**Comment by rbreaves** [comment]
This was likely caused by a misconfiguration from the user or has since been fixed in later releases.  On Xubuntu or debian based distros with XFCE4 this tends to fix the issue. For other DEs just don't install xfce4-appmenu-plugin or xfconf-query and you will likely have all the dependencies you need.

```
sudo apt install xfce4-appmenu-plugin vala-panel-appmenu-common appmenu-gtk2-module appmenu-gtk3-module appmenu-gtk-module-common
xfconf-query -c xsettings -p /Gtk/Modules -n -t string -s "appmenu-gtk-module"
```
