### ISSUE TITLE
Running yarn fails using node version 10 on ARM (raspbian-stretch)

### ISSUE THREAD

**Issue by couven92** [Microsoft/vscode#69592]
In order to build vscode for ARM on my Raspberry Pi 3 B+, I downloaded the source-tarball from the latest GitHub release and attempted to follow the build instructions from https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run

- VSCode Version: [`1.31.1`](https://github.com/Microsoft/vscode/releases/tag/1.31.1)
- OS Version: `Raspbian GNU/Linux 9.8 (stretch)`

Steps to Reproduce:

1. `curl -sSL https://github.com/Microsoft/vscode/archive/1.31.1.tar.gz | sudo tar -xz -C /opt`
2. `cd /opt/vscode-1.31.1`
3. `sudo yarn`

Command `yarn` fails:

```
/opt/vscode-1.31.1# yarn
yarn install v1.13.0
$ node build/npm/preinstall.js
*** Please use node >=8 and <9.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Node version:

```
# node -v
v10.15.1
# npm -v
6.4.1
```

~~**Question**: Even though I downloaded the source tarbal for the latest version (1.31.1 at point of writing) `yarn` outputs `yarn install v1.13.0`. Might that be the cause of the issue?~~

**Comment by usernamehw** [comment]
Isn't the source of the issue `*** Please use node >=8 and <9.`?

I believe vscode **1.32.0** could be built using `node 10`.

**Comment by couven92** [comment]
I now realize, that `yarn` print its version number (in this case `1.13.0`). It has nothing to do with this issue.

**Comment by Tyriar** [comment]
As @usernamehw points out your _node_ version is likely the problem, there might have also been changes to the instruction since 1.31 https://github.com/Microsoft/vscode/wiki/How-to-Contribute/_history

Regardless, we don't really support this sort of thing, the build definitely works against the release version as otherwise it would not have been released.

**Comment by couven92** [comment]
@Tyriar, please reopen. The issue is not resolved.

In the build instructions the Prerequisites for NodeJS are stated as:

> Node.JS, 64-bit, recommended >=10.15.1, < 11.0.0

Could you please elaborate on what you mean with "this thing" not being supported? I just downloaded the latest release available on the GitHub releases tab. And I followed the build instructions making sure I had the listed prerequisites installed. But, the build fails immediately. Ergo, it does not work. In my mind that is an issue.

**Comment by Tyriar** [comment]
@couven92 the output of your command says the problem:

> *** Please use node >=8 and <9.

This is _node_, not _yarn_. Since v1.31 we have updated the node version required (see the wiki history above).

We don't want to spend time on these sorts of "legacy" builds requests as the codebase has moved on. Everything is available to get it building and it definitely works. Make sure you're looking at the _date appropriate_ wiki page.
