### ISSUE TITLE
SyntaxError: invalid regexp group

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#69655]
I'm trying to ship the standalone editor and it is not coming up in FF or Edge due to the following regular expressions:

https://github.com/Microsoft/vscode/blob/52306b406d9231a0667c758e536bd177e5570180/src/vs/base/browser/ui/menu/menu.ts#L23-L24

I will push a workaround to the `standalone/0.16.x` branch, but can you please tweak your regular expression such that it works also on Edge and FF? Thanks!

**Comment by bpasero** [comment]
Marking as web as this is something we should revisit eventually when supporting other browsers. 

cc @sbatten

**Comment by alexandrudima** [comment]
@bpasero Why did the importance level drop? This blocks the release of the editor...

**Comment by bpasero** [comment]
@alexandrudima my understanding is that you pushed a workaround for this issue (try-catch) that unblocks the release of the editor. For example, I can see releases that date to after this issue was created:

![image](https://user-images.githubusercontent.com/900690/62467188-6d19e580-b793-11e9-8484-b2cdd2e12cb2.png)

I think we should use important labels for stuff like data loss etc. but not if a workaround is installed. Nevertheless I agree we should fix this asap.

**Comment by alexandrudima** [comment]
I didn't do 0.17.0

**Comment by bpasero** [comment]
Yeah you are right, sorry for that :heart:
