### ISSUE TITLE
High CPU Utilization on Windows 10 (85-95%)

### ISSUE THREAD

**Issue by HarpPDX** [Microsoft/vscode#69711]
![capture](https://user-images.githubusercontent.com/7102637/53754078-bd4cee80-3e67-11e9-9675-e32703221e16.PNG)
![capture2](https://user-images.githubusercontent.com/7102637/53754086-c0e07580-3e67-11e9-9f30-569364d7250f.PNG)

Issue Type: <b>Bug</b>

Project and code resides on mapped drive shared via Samba from Linux.
Disabled all extensions.
High utilization *may* be triggered by Find in Files.
Utilization remains high even after clearing search.
Restarting vscode results in normal (low-ish) CPU utilization.
Attempting to trigger high utilization by taking specific steps has been unsuccessful.
High utilization resumes.

VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.84GB (20.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by roblourens** [comment]
Your two screenshots don't seem to match because the first only shows one process using CPU, but the second shows many more processes. One possibility is that the second shows old processes from an old vscode session which are no longer related to the live main process. Another is that they were taken at different times. Could you look again next time this happens to see which processes are responsible?

Also please see the steps here to help us troubleshoot https://github.com/Microsoft/vscode/wiki/Performance-Issues#the-rendererwindow-process-consumes-a-lot-of-cpu

**Comment by HarpPDX** [comment]
Hi @roblourens  The screen shots were taken a few seconds apart.  Notice that the Windows Task Manager is displaying grouped processes/windows.  I had only one instance of vscode running.  Here's another screenshot of Task Manager with vscode in a happy state.  Cheers.
![image](https://user-images.githubusercontent.com/7102637/53780477-8ef7ff00-3eb9-11e9-9a89-6ab330dd3527.png)

**Comment by roblourens** [comment]
Ok, but I still don't have enough info to help, so please see the wiki page linked above next time this happens.
