### ISSUE TITLE
Kill feedback widget

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#6972]
There are issues with the feedback widget:
1. Nobody reads the feedback
2. It looks bad
3. The emoji in the corner feels wrong 

Due to this I propose to remove it
@waderyan @chrisdias objections?

**Comment by waderyan** [comment]
ping @seanmcbreen 

I'm OK with removing it and have thought that would be the best option multiple times. Let @seanmcbreen weight in... he sees the feedback on Twitter and there are some positive vibes with it.

**Comment by Tyriar** [comment]
The assertion that no one reads the feedback is false. There is a lot of feedback that comes through Twitter, I find a lot of it valuable and occasionally engage with people having issues with Linux.

Removing it would remove *a lot* of VS Code mentions from Twitter, definitely a negative just because of that.

**Comment by isidorn** [comment]
Forwarding to @seanmcbreen to decide if we want to keep it.

**Comment by seanmcbreen** [comment]
I think we should keep if - it's actually amazing how many items we see in Twitter each day.  the added benefit is that these tweets go to the friends of the sender as well.  This helps promote the product is a good way.

I'll close for housekeeping but re-open if required.
