### ISSUE TITLE
History of previous searched text for files

### ISSUE THREAD

**Issue by imkathir** [microsoft/vscode#69843]
It would be great if we could get remember texts which are used while searching for a file(**command + P** in mac) like ATOM editor.
In atom after searching for a file and selecting the appropriate file will be opened when we again do search for file (command + P in mac) we can select the previously searched file by pressing  **command + z** in  ATOM editor It would be awesome if we have the same feature in VS code as well

**Comment by roblourens** [comment]
I've never heard of this feature before. So cmd+z navigates through search history in quick open, that's interesting.

**Comment by imkathir** [comment]
Any updates Guys

**Comment by imkathir** [comment]
Any updates @roblourens

**Comment by roblourens** [comment]
I think we could take a PR that hooks up a HistoryInputBox to quick open, and uses alt+up/down to navigate history, unless @bpasero disagrees. It would be useful sometimes like when I type a long query to find a file, pick a file, then realize it's the wrong file and want to bring the query back.

 It's unfortunate that we switched from alt+arrow to just arrow keys for history in the other search inputs because arrow keys here already move selection in the result list.

**Comment by alpalla** [comment]
Hi, I'd be glad to work on this issue. I'm currently toying with a solution though any additional pointers would be appreciated, thank you!
