### ISSUE TITLE
Support file language detection with more than the first line

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode#69868]
We need a way to associate ARM template files with a language ID separate from the current JSON language.  Unfortunately, the existing firstLine filter for languages doesn't suffice for ARM templates (or for any other sub-JSON support). ARM template files are .json files and generally look like this:
 
{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
 
The $schema value is the key to knowing if it’s an ARM template (technically it could be anywhere in the file although it’s usually at the top like this).  So we need a way to check further into the file than the first line.  Thanks!

**Comment by GordonSmith** [comment]
Quick "me too" and not limited to JSON - think about XML at the same time...

**Comment by ak1394** [comment]
I would like to see this resolved as well. I'm looking at implementing better support for editing Swagger/OpenAPI JSON files. However, there are two major versions of the standard with different JSON Schemas, and the recommended way to tell one from another is to check values of the top level "swagger" or "openapi" fields.

**Comment by bpasero** [comment]
This will not work even if we had a property to match on the first 3 lines because of https://github.com/Microsoft/vscode/issues/53350. Unless the file extension is different and no registration exists for the file extension, we would not pick up such a contribution. The contributions based on content currently only win if no other registration was picked based on filename, path or extension.

**Comment by bpasero** [comment]
After talking to @aeschli and @egamma here is a proposal also based on https://github.com/Microsoft/vscode/issues/10915 and https://github.com/Microsoft/vscode/issues/53350

### Introduce a new `preamble` matcher
Today we have the possibility to contribute languages based on `firstLine`. This is not enough for Azure resources that have marker text spanning multiple lines. We should have a new contribution mechanism `preamble` that is defined as the first lines of a file (e.g. 3-5). We still need to decide if we require the target text to be fully included in these lines or if we allow glob matching too as we do with `firstLine`.

### Allow language extensions to override built in extensions by more than one rule
Even if we allow this new `preamble` matcher, an extension will not be able to overrule our built in JSON extension because we always first try to match on file extensions and only ever consider textual content if no extension matches based on the file name and extension. 

To enable this, we would need a new way for extensions to contribute a language based on multiple conditions, not just one. For example:

```json
"contributes": {
  "languages": [
    {
      "id": "azure-json",
      "rules": {
          "extensions": [".json"],
          "preamble": "<some text in Azure JSON resources>"
       }
    }
  ]
}
```

(this format is just an idea taken from https://github.com/Microsoft/vscode/issues/10915 and is up for debate)

//cc @alexandrudima

**Comment by alexandrudima** [comment]
Perhaps there is some backstory to this request, but I don't understand why do we need to create a new language when the file is a `.json` file and has JSON syntax.

**Comment by ak1394** [comment]
@alexandrudima How would this approach play with built in 'json-language-features' extension? Currently it supports two languages 'json' and 'jsonc'.  Will it have to be updated to include new language IDs?

**Comment by alexandrudima** [comment]
No changes would be needed to the JSON extension.

**Comment by ak1394** [comment]
@alexandrudima This proposal looks good to me. However, in order to supply JSON Schemas for the documents which lack "$schema" attribute, I propose to extend 'json-language-features' extension, to expose API to supply schemas. I've opened a PR #73424 which should give an idea to what I'm looking to do. I would appreciate a feedback on it.
