### ISSUE TITLE
`$gcc` Problem Matcher Produces Broken Links...

### ISSUE THREAD

**Issue by busticated** [Microsoft/vscode#69873]
hey there :wave:

i'm the author of an extension which is providing a series of tasks via the `TaskProvider` API ([docs](https://code.visualstudio.com/api/references/vscode-api#TaskProvider)). my tasks are setup like so:

```js
new Task(
    { type: 'my-tasks', name },
    projFolder,
    name,
    'Test',
    exec,
    ['$gcc']
)
```

and they execute as expected. however, it seems there's an issue w/ how the `$gcc` problem matcher handles links. after running one of my tasks, i see the following in the "problems" panel:

`"ARDUINO" is not defined [-Wundef]`

in the task's Output panel i see:

```
/Users/me/my-project/lib/Adafruit_Seesaw/src/Adafruit_seesaw.h:23:6: warning: "ARDUINO" is not defined [-Wundef]
 #if (ARDUINO >= 100)
      ^
```

when i `cmd+click` on the path in this raw output log, the appropriate source file is opened and i'm taken to the correct line but when i click the item in the "problems" tab, i see an error:

```
Unable to open 'Adafruit_seesaw.h': File not found (file:///Users/me/my-project/Users/me/my-project/lib/Adafruit_Seesaw/src/Adafruit_seesaw.h).
```

and i'm prompted to "create file".

i would expect the path referenced in the raw output would be used without modification by the corresponding item in the "problems" tab. i suppose it's also worth noting that the containing item shown in the "problems" tab also displays the correct path (`/Users/me/my-project/lib/Adafruit_Seesaw/src`) so it at least knows the location of the directory containing the source file with the issue.

- VSCode Version: 1.31.1
- OS Version: macOS 10.13.6 (high sierra)

**Comment by felipecock** [comment]
I have the same issue with problem matcher, I uninstalled all extensions except Platformio.io and C/C++ (Microsoft), but the links in the problem matcher are still broken because the path is duplicated.
`Unable to open 'Datalogger.ino': File not found (file:///home/felipe/Documents/PlatformIO/Projects/Bluepill_Datalogger/home/felipe/Documents/PlatformIO/Projects/Bluepill_Datalogger/src/Datalogger.ino).`
I hope you could fix it. 
Related threads:
https://github.com/Microsoft/vscode/issues/449 (Open since 2015)
https://github.com/Microsoft/vscode-cpptools/issues/1915
https://github.com/Microsoft/vscode/issues/48841
https://github.com/Microsoft/vscode/issues/44370
https://github.com/Microsoft/vscode/issues/69873

**Comment by busticated** [comment]
possible work-around: contribute your own problem matcher - e.g.

```json
        "problemMatchers": [
            {
                "base": "$gcc",
                "name": "my-gcc",
                "fileLocation": "absolute"
            }
        ],
```

then in the `Task` you return via `provideTasks` use `['$my-gcc']` (instead of `['$gcc']`)

**Comment by alexr00** [comment]
This is by design since the C/C++ extension contributes the `$gcc` problem matcher and specifies relative paths: https://github.com/Microsoft/vscode-cpptools/blob/master/Extension/package.json#L51
@busticated 's work around is good. If you think that this problem matcher is incorrect to have relative paths then please file an issue over in https://github.com/Microsoft/vscode-cpptools !
