### ISSUE TITLE
Interface font uses serif font. 

### ISSUE THREAD

**Issue by whdgmawkd** [Microsoft/vscode#69893]
- VSCode Version: 1.31.1 and 1.32.0-insider
- OS Version: Debian buster/sid, Linux x64 4.19.0-2-amd64

Steps to Reproduce:

1. Install code or code-insider from official homepage
2. open code or code-insider
3. all UI fonts are serif font. but editor font is sans.

![screenshot from 2019-03-06 17-01-14](https://user-images.githubusercontent.com/6850405/53865065-7874b380-4031-11e9-999f-b037d141ed4a.png)

![screenshot from 2019-03-06 16-55-35](https://user-images.githubusercontent.com/6850405/53864876-f5ebf400-4030-11e9-9fa6-54a011d9c69d.png)
Left: 1.31.1, Right: 1.32.0-insider

I tried 'fc-cache -f -c' and 'apt purge code*'. but it is not working for me.

Does this issue occur when all extensions are disabled?: Yes. remove .config/Code and .vscode but still same issue.

**Comment by joaomoreno** [comment]
Are you using the snap package?

**Comment by whdgmawkd** [comment]
No. This package downloaded from official homepage

**Comment by bpasero** [comment]
This is the CSS rule we apply: 

```css
.linux { font-family: "Ubuntu", "Droid Sans", sans-serif; }
```

I am not sure why that would result in your issue.

@Tyriar ideas?

**Comment by m-thorsen** [comment]
Seems that Electron/Chromium has a peculiar way of reading fontconfig... I know the "monospace" alias needs to be in quotes to work under Linux (when setting fontFamily in user settings).   
A quick test using editor.fontFamily also netted different results from specifying "sans-serif" and "'sans-serif'" (although two different sans fonts, go figure) - so there could be something there (for reference, fc-match gives me the same font either way).

On a slight side note (although somewhat relevant), what made you choose _that_ font stack? I don't know any Linux distro or DE that ships with Droid of all things. I'd consider adding Noto Sans (KDE and Mint default) and Cantarell (GNOME default) instead of Droid. 

Maybe something like this?   
`{ Ubuntu, Noto Sans, Cantarell, 'sans-serif', sans-serif }`

**Comment by m-thorsen** [comment]
I just installed Debian Buster in a VM, default desktop (GNOME), no extras, and I did get a sans-serif UI font.  
DejaVu Sans isn't pretty, but it's at least sans.

![freshdebian](https://user-images.githubusercontent.com/14907694/53912170-a4575f80-4058-11e9-8c71-ebbad007fc32.jpg)

**Comment by whdgmawkd** [comment]
i found my font config caused this issue.
i don't know why it only occur in vscode, but now i solved font problem by removing all custom font config.
