### ISSUE TITLE
Sometimes, can't navigate to the right terminal window 

### ISSUE THREAD

**Issue by sallyur** [microsoft/vscode#69895]
- VSCode Version: 1.31.1
- OS Version: Win
- Extension: Debugger for java 0.17.0

### Steps to Reproduce:

1. Open one java project
2. Set console to " integratedTerminal" in launch.json
3. Click F5 to start to debug

### Actual result:
It can't navigate to the integeatedTerminal window automatically
![image](https://user-images.githubusercontent.com/28860891/53867008-d99a8800-402d-11e9-902c-008e56a37987.png)

### Expect result:
It navigate to the integeatedTerminal window automatically
![image](https://user-images.githubusercontent.com/28860891/53867129-1fefe700-402e-11e9-9310-c36369508549.png)

**Comment by isidorn** [comment]
@sallyur Good catch, thanks for filling this and sorry for the slower reponse.

VSCode is not aware of the `console` flag in the launch json. It is being contributed by the java extension from [here](https://github.com/microsoft/vscode-java-debug/blob/master/package.json#L202)
Thus VSCode can not do anything about this.
Due to this I suggest that the Java extension in their resolve debug configuration call makes sure the terminal window gets opened via triggereing show terminall command. The jave debug can also set the internalConsoleOptions to neverOpen in vscode.

I know it is not nice that every debug extension has to do this, but I do not want to introduce this assumption to VSCode, since it can not be aware of attributes contributed by an extesion.

fyi @testforstephen

**Comment by testforstephen** [comment]
Thanks for the information. The debugger has fixed the issue via internalConsoleOptions to neverOpen.
