### ISSUE TITLE
Regex Find is case-insensitive - Why?

### ISSUE THREAD

**Issue by bryanerayner** [Microsoft/vscode#6993]
- VSCode Version: 1.1.1
- OS Version: Os X 10.11.4

Steps to Reproduce:

1. Open a new document
2. Add the following text (country codes and the countries associated)

AFN	Afghanistan Afghani
ALL	Albania Lek
AMD	Armenia Dram
ANG	Netherlands Antilles Guilder

3. Press Ctrl+F (find)

4. Using regex mode, add the following regex: 
[A-Z]{3}

5. Note that more than just the country codes are selected - entire words are selected.

This renders Regex almost un-usable.

**Comment by nicolo-ribaudo** [comment]
You can toggle between case-sensitive and case-insensitive using `Alt+C`

**Comment by Tyriar** [comment]
Yes the `Aa` icon controls the regex case sensitivity flag.

**Comment by vtbassmatt** [comment]
I just encountered the same behavior, which was quite surprising. My use case: replace incorrect spellings of "ID" (many people spell it "id" or "Id", but in our product, it should be uppercase) in our documentation. The regex `\s[i|I]ds?\s` should have only found the incorrect spellings, but was finding all the correct versions as well.

I'm not sure the behavior is "wrong", but it was surprising. I incorrectly thought the three symbols in the search box were radio buttons, so I didn't connect that I could toggle both regex search and case-sensitivity.

**Comment by Tyriar** [comment]
It would also be strange the other way though since when doing a regular search with `Aa` unchecked is case-insensitive.

@alexandrudima any thoughts on improving the discoverability of the case sensitivity button?

**Comment by alexandrudima** [comment]
We more or less copied the toggles from Visual Studio's find widget.

@bgashler1 @stevencl thoughts?

**Comment by stevencl** [comment]
Is it really that the case sensitive button just isn't discoverable or is it that the need to set case sensitivity is unexpected? It does seem odd to have to turn case sensitivity on when the expression explicitly specifies a case.

Perhaps we just disable the case sensitive toggle whenever the user specifies a regex pattern? Or, we do a tooltip indicating when case sensitivity is turned off whenever the user toggles regex on?

**Comment by vtbassmatt** [comment]
A lot of regex implementations have a case-insensitivity flag, and I'm in favor of keeping it. Perhaps the tricky part is that I want case-insensitive by default when I'm doing a substring search, but I want case-sensitivity by default when I do a regex search.

Who would have guessed such a small feature would be so hard to do UX for? :)

**Comment by stevencl** [comment]
I wonder then if this is an initial discoverability problem that once understood never causes any further issues? In order to keep the product lightweight and not overly distracting we always try to solve for distractions not discoverability (in other words, we don't like UI that only serves to advertise the presence of some functionality that once discovered never needs to be advertised again).

One thing that might help but I'm not sure we can do it easily would be to change the tooltips that we have on these buttons to indicate that they are toggles, not a set of radio buttons. So instead of always saying 'Match case (Alt + C)' we might say 'Toggle case sensitivity {on/off} (Alt + C)' depending on the state of the toggle. That might help with identifying these as toggles.

Another option is that we might consider turning case sensitivity on by default whenever the user toggles regex search on. We would need to turn it off whenever the user toggled regex off though. I'm not that keen on this solution though, I get uneasy doing something like this as it could easily get complex.

**Comment by vtbassmatt** [comment]
Tooltips could help.

Another thing I thought of: When case-sensitivity is on, case-insensitive regex matches are still highlighted, but in gray instead of color. Maybe you could play with color differences, tooltips, or another visual tag that would let people know "hey, you're seeing this because you have case-insensitivity turned on".
