### ISSUE TITLE
Open vscode://file/<path> in vscode is broken

### ISSUE THREAD

**Issue by jameschenjav** [Microsoft/vscode#69998]
- VSCode Version:
`code --version`
1.32.0
507312a3e3b34b084b467dfd983263bc7c9d87e0
x64

- OS Version:
macOS High Sierra v10.13.6 (17G3025)

Steps to Reproduce:

1. In terminal `open vscode://file/<my_file_path>`
2. It will popup notification with error `Unable to open '<my_file>': resource is not available.`

Does this issue occur when all extensions are disabled?: Yes

Since I tried same url just changed `vscode` to `vscodium` and VSCodium v1.13.1 works perfectly

**Comment by ije** [comment]
i got the same issue...

`code --version`
1.32.1
05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
x64
macOS Mojave 10.14.3

**Comment by bpasero** [comment]
@joaomoreno I debugged this and I am not 100% sure this is a regression. We end up calling `ITextModelResolverService#createModelReference()` with the URI `vscode://...` and this correctly goes into the contribution from preferences:

https://github.com/Microsoft/vscode/blob/22fdb8e2c3efb1c7f8cf0883996044ee5c7b41b1/src/vs/workbench/contrib/preferences/common/preferencesContribution.ts#L110

Which then bails out because the URI is probably not what @roblourens expects to resolve.

**Comment by joaomoreno** [comment]
@bpasero This is a regression. I made a command available to test this a couple releases ago: `Developer: Open URL`. When I use it to open a URL in 1.31 it works. It doesn't in 1.32.

**Comment by joaomoreno** [comment]
```
8c6e97456e260c4136dd24c1948d8fb9a0f04b43 is the first bad commit
commit 8c6e97456e260c4136dd24c1948d8fb9a0f04b43
Author: Martin Aeschlimann <martinae@microsoft.com>
Date:   Wed Feb 6 16:56:53 2019 +0100

    IWindowService.openWindow takes IURIToOpen
:040000 040000 bbbaff84accf810921f7d3725d1d3e40721142d3 f8782f14f2f3b5899fbc9df9f10f2efa1088486e M      src
```

cc @aeschli
