### ISSUE TITLE
Right click on File Explorer when no file is open shows wrong options

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#70007]
![image](https://user-images.githubusercontent.com/4033249/54001986-00c28980-4102-11e9-8d6c-f323ce7eaf08.png)

![image](https://user-images.githubusercontent.com/4033249/54001989-0324e380-4102-11e9-9ee8-ddf6c27ece82.png)

Repro:

- Close all open files
- Reload VS Code
- Click in empty areas in File Explorer

Repro'ed on both macOS and Linux on 1.32.0

This is the expected behavior:

![image](https://user-images.githubusercontent.com/4033249/54002021-1df75800-4102-11e9-9278-743b9a3358f5.png)

**Comment by isidorn** [comment]
@octref fantastic repro steps. Investigating

**Comment by isidorn** [comment]
I have partially fixed this.
The issue was that the context key were not properly initialised on startup.
However there is still one issue, that the commands which require the file scheme are not shown, even thoough it is properly set. I am not sure why that is happening since debugging context keys is always a pain.
Closing this now as most of the issue is fixed. If people are passionate I can spend more time on figuring out why Find In Folders is missing...
