### ISSUE TITLE
Unsaved files are opened in two windows when reopening vscode

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#70006]
- Open a folder
- Create untitled file with some content
- Quit vscode
- Open vscode
- Two windows are opened, one has the folder +untitled file, other is an empty window + untitled file.

So the same untitled file is opened in two windows.

**Comment by Tyriar** [comment]
I could only repro this with an empty window:

1. Open Code via finder
2. Close all files/folders
3. Open an untitled file, add changes
4. cmd+q
5. Open Code via finder

<img width="490" alt="screen shot 2019-03-07 at 5 42 14 pm" src="https://user-images.githubusercontent.com/2193314/54001939-d83a8f80-4101-11e9-968c-e46e3bcbce12.png">

**Comment by bpasero** [comment]
Moving this to @aeschli as the last who touched this code.

**Comment by bpasero** [comment]
@aeschli for some reason the [`emptyToRestore`](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/windows.ts#L375) array has multiple entries for the same window?

**Comment by Heesz** [comment]
Temporally until update is not yet, for prevent backup window add to settings "window.restoreWindows": "none"

**Comment by SylwesterZarebski** [comment]
When set `"window.restoreWindows": "all"`, then every close & start VSCode will multiple windows (1 -> 2, 2 -> 4, 4 -> 6, and so on).

**Comment by bpasero** [comment]
@aeschli this change is not in the recovery build yet pending https://github.com/Microsoft/vscode/pull/70180 right?

**Comment by bpasero** [comment]
Pushed.

**Comment by roblourens** [comment]
I saw this by downgrading from 1.32.2 to 1.31.1, then upgrading back. But I don't think we care about that.

**Comment by DoCode** [comment]
@bpasero I can confirm that this issue is fixed in the latest 1.32.2 release! Thanks!

But another one what I noticed:

## Steps to reproduce

1. Open VS Code
2. Open one existing document
3. **_Optional:_** Open a new tab or new window with a new tab and type anything and do NOT save this new file
4. Close VS Code
5. Re-Open VS Code
6. **Now all tabs are correctly restored!**
8. Close VS Code
7. Open a File from Windows Explorer with right-click and open in VS Code

## Expected behavior

All tabs should re-opened (Tabs/files from Step 2., 3. and 7.)

## Actual behavior

Only the unsaved file from step 3. and the one from the Windows Explorer, step 7. are opened.
And the last session (int this example, file from step 1. is lost!

Is this wanted or can this be configured?

**Comment by SylwesterZarebski** [comment]
Confirm fix and also above bug with 1.32.2 and 1.32.3. Could You report this as new issue?
Now session is partially broken :-(

**Comment by DoCode** [comment]
@SylwesterZarebski thanks. Please see #70755
