### ISSUE TITLE
when webpack+ts-loader+tsconfig->"allowJs":true, Cannot write file because it would be overwritten by multiple input files

### ISSUE THREAD

**Issue by iugo** [microsoft/vscode#70014]
- VSCode Version: 1.32.0
- OS Version: macOS 10.14.3 (18D109)

Steps to Reproduce:

1. https://github.com/iugo/ts-test/tree/c32a86b12f9c26367abf056b8a916638aabd8131
  - use webpack + ts-loader
  - ts import js
  - tsconfig set `allowJs:true`
2. false positive: Cannot write file because it would be overwritten by multiple input files.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
During compile with `allowJs`, TS will try to copy any js files into the `outDir`. Since you have not specified any `outDir`, this would result in TS copying the input js file to the current directory and overwriting the one already there. This usually is not expected and indicates a configuration mistake

Try changing the `outDir` in your `tsconfig` to avoid this
