### ISSUE TITLE
Keybindings: Add when context for if an extension is enabled

### ISSUE THREAD

**Issue by frobinsonj** [microsoft/vscode#70068]
I have different extensions enabled in different workspaces, and similar custom keybindings for those extensions. It would be nice to be able to enable keybindings only if an extension was enabled.

Maybe something like:
When `{extensionId}.enabled == true/false`

**Comment by sandy081** [comment]
@frobinsonj Those commands from extensions will not be available when extensions are disabled. So why do you need such when context if they are not available?

**Comment by frobinsonj** [comment]
@sandy081 

In a few cases, the extensions I use do similar jobs. Would be nice to use the same key bindings without seeing warnings. It would also be useful to replace default keybindings if an extension is available to use instead.

For example:
I use a beautify extension, it would be nice if I could have the `Shift` + `Alt` + `F` keybinding use that if it's available but use the default format document command if it's not.

**Comment by sandy081** [comment]
@frobinsonj May I know your intention is to avoid warnings?

**Comment by frobinsonj** [comment]
@sandy081 Sorry, I don't understand the question. This suggestion is definitely not a necessity, the warnings are not the end of the world, nor do they prevent me from achieving my goal. It's just a possible improvement in my opinion. Hope that helps?

**Comment by sandy081** [comment]
Lets say there are two extensions A and B contributing commands commandA and commandB respectively. You defined same keybinding to commandA and commandB. When extension A is disabled, above keybinding triggers commandB and viceversa. If both are enabled, then the first one takes the precedence. 

I am trying to understand when your requirement fits in the above set up?

**Comment by frobinsonj** [comment]
@sandy081 

![image](https://user-images.githubusercontent.com/16726902/54122163-37471f80-43f4-11e9-80f1-d3dc9e3a9da4.png)

keybindings.json:
```
[
	{
		"key": "shift+alt+f",
		"command": "HookyQR.beautifyFile",
		"when": "editorTextFocus && !editorReadonly && hookyqr.beautify.enabled"
	},
	{
		"key": "shift+alt+f",
		"command": "extension.sayHello",
		"when": "editorTextFocus && !editorReadonly && atom.rc-beautify.enabled && !hookyqr.beautify.enabled"
	}
]
```

Just as an example:
We have two extensions here, `hookyqr.beautify` and `atom.rc-beautify`.
The expected results here would be:

1. If `hookyqr.beautify` is enabled, shift+alt+f should run `HookyQR.beautifyFile`
2. If `hookyqr.beautify` is disabled and `atom.rc-beautify` is enabled, shift+alt+f should run `extension.sayHello`
3. If both extensions are disabled, shift+alt+f should run the default `Format Document`

**Comment by sandy081** [comment]
@alexandrudima Does not it makes sense to make it implicit that if a command is not found for a keybinding, then it falls back to the next that exists?

**Comment by alexandrudima** [comment]
@sandy081 No. Because commands don't need to be listed in `package.json`. Listing a command there means that it is added to the `F1` list. Executing a command will wait for an activation event, which might result in the command being registered. In other words, it is possible to write an extension that activates `onCommand:X` and which contributes a keybinding for `X`, and which registers the command, but which does not list it up front in the `package.json`. Thus, it is not possible, synchronously, to determine if a command exists or not during keybinding dispatching.

**Comment by sandy081** [comment]
I think this requested context key shall determine whether an extension is running/loaded or not in extension host, and I do not think reflecting the enablement state will help because extension might be still running when extension is disabled.

Hence assigning to @alexdima.

**Comment by alexdima** [comment]
@sandy081 The request of the OP is to define new context keys `{extensionId}.enabled == true/false`. This is literally about extension enablement. Again, the fact that an extension is loaded or not should not influence keybinding dispatching because as a result of keybinding dispatching an extension can get activated.

Here is a concrete example:
* extension activates on `onCommand:hello`
* keybinding is `ctrl+f` => `hello`
* pressing `ctrl+f` results in `hello` being executed, which before executing will activate the extension and can then execute.

The intent of the OP is to have multiple workspaces, and in workspace 1 to disable the extension and in workspace 2 to enable the extension. In workspace 1, when pressing `ctrl+f`, `hello` will be executed, but before executing it will not activate the extension because the extension is disabled, so `ctrl+f` will show an error that the command is not found. The intent of the OP is to be able to define in the context key of the keybinding that they want `ctrl+f` to execute `hello` only in the workspaces where the extension is enabled.

**Comment by sandy081** [comment]
I understand that the request here is to introduce new context keys defining extension enablement. But what I am trying to say is enablement context keys will not be complete to support the requested feature completely. Because in the above example, if user disables an extension in workspace 1, enablement context key gets disabled but the extension will be still running because it required reload to disable the extension completely. So when pressing `ctrl+f`,  `hello` will not be executed even if extension is running. Hence I recommended to introduce context keys defining extension runtime status rather than enablement state.

However given this confusion, I am not inclined towards implementing this. Hence tagging out of scope.
