### ISSUE TITLE
2d quick menu

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#70074]
The idea is to create an overlay similar to the `workbench.action.quickOpenView`, only to display a matrix of icons, similar to many games (and probably some software):

![demo](https://user-images.githubusercontent.com/9638156/54038439-a09b1880-41d1-11e9-94d4-1859d455d40a.jpg)

It should be shown immediately while holding a modifier key, then hovering mouse over an icon and releasing the modifier to execute an action.

Yes, it is slower than keybinding and nobody in vscode likes icons or mouse, so I might as well write this into `/dev/null`.

**Comment by misolori** [comment]
This sounds interesting, though not sure how practical it would be. Leaving a few other screenshots for reference:

![image](https://user-images.githubusercontent.com/35271042/54140824-b4b56480-43e1-11e9-8dcf-b08ea043761e.png)

![image](https://user-images.githubusercontent.com/35271042/54140882-d31b6000-43e1-11e9-9eb4-884e82e9eef5.png)

**Comment by Tyriar** [comment]
Interesting idea. Radial menus work great in games as your hands are always on the mouse and the keyboard, that's not really the case in a text editor though. It would ease learning in a way because instead of memorizing and getting used to ctrl+shift+e/f/g/d/x/j/etc. you just need to remember the direction to move the mouse in.

Something else that might not be obvious, when you use a radial menu in an FPS for example your facing position in the actual game doesn't change, I'm not sure we can accomplish this with Electron.

**Comment by misolori** [comment]
While I do like this idea, I don't think this is something that will happen any time soon as it would require a great amount of effort all around and we typically plan for work like this early on. If we ever decide to re-visit we can re-open.
