### ISSUE TITLE
Relative paths fail to show for two files with the same name.

### ISSUE THREAD

**Issue by zzhou612** [Microsoft/vscode#70113]
- VSCode Version: 1.32.1 
- OS Version: macOS Mojave 10.14.3

Steps to Reproduce:

1. `Workbench › Editor: Label Format` set as `Default`
2. Open two files with the same name, one of them located in the root directory of the target folder/project/workspace.
3. The relative paths fail to show according to the description of the `Default` setting.

![Screen Shot 2019-03-09 at 1 47 21 PM](https://user-images.githubusercontent.com/17488719/54066837-4d2cd700-4272-11e9-9939-f08d095c2b6a.png)

Does this issue occur when all extensions are disabled?: Yes

The same issue has been verified but closed by `vscodebot`: https://github.com/Microsoft/vscode/issues/35721

**Comment by bpasero** [comment]
@mjbvz a regression from https://github.com/Microsoft/vscode/commit/4dbd042325e9724d4a35f2c7150c0c9784860e61. Since you do `string || undefined` we might end up assigning `undefined` as value even though an empty `string` was returned. Since later on we check for `typeof === 'string'` we fail to account for the description of the label.

I hope there is not more instances of this pattern that slipped through. It would be great if you could check.

**Comment by bpasero** [comment]
Arguable a candidate.
