### ISSUE TITLE
Default value for renderFinalNewline on Linux is bad for conditioned users

### ISSUE THREAD

**Issue by dlech** [Microsoft/vscode#70126]
https://github.com/Microsoft/vscode/pull/64667 introduced a new setting `renderFinalNewline`. The choice was made that on Linux, the default value for this setting is `true` which changes the behavior from versions of VS Code before the setting was introduced.

Without realizing the default behavior has been changed, I have been adding double newlines to the end of files since I have upgraded to v1.32 because I have become conditioned to the display of line numbers on all lines. I was quite surprised to find that I could put the cursor on a line without a line number! I suspect that I am not the only user that has developed such conditioning. Changing the default behavior was certainly not very nice for my UX.

**Comment by glen-84** [comment]
You're not the only one to be surprised by this change – #69129.

It wasn't even (prominently) mentioned in the update notes, which is a surprise in itself.

Ideally, Linux users could have been prompted to make a choice when upgrading VS Code. Failing that, the only other reasonable option seems to be to default to `true`. It's unfortunate (since it's not really "correct"), but as you say, many users have been conditioned to expect this numbered empty line at the end of files.

I personally use Windows, but since I work on projects with Linux EOL characters and have the EditorConfig `insert_final_newline` setting enabled, I've actually set `renderFinalNewline` to `false` so that I no longer have this "blank line" at the end of files. It's going to take some getting used to, but I still believe that it is the correct behaviour.

**Comment by glen-84** [comment]
A third option may be to display some kind of character/symbol to indicate that the last line ends with a `\n`.

Something like this:

![image](https://user-images.githubusercontent.com/261509/54355660-534ff880-4662-11e9-9a71-eee5fba170fd.png)

I mentioned this [here](https://github.com/atom/atom/issues/7787#issuecomment-332930211) as well (with some alternatives).

In that way, you know that the last line is terminated, and where to place your cursor, without erroneously numbering that as a line.
