### ISSUE TITLE
make "compileOnSave" option of tsconfig.json recognized by vscode

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#7015]
Currently "compileOnSave" option of tsconfig.json is ignored by the VS Code:

- http://stackoverflow.com/questions/29996145/visual-studio-code-compile-on-save

There is no a workaround to this problem. Please consider doing something about bringing it to life.

**Comment by dbaeumer** [comment]
Added a comment to stackoverflow. This is supported right now via a watch task. But I agree that the tsconfig.json option should be supported as well, which has to come from the TS team though.

**Comment by dbaeumer** [comment]
I opened https://github.com/Microsoft/TypeScript/issues/8884 since the support has to go there. I will close this issue as upstream.

**Comment by aleksey-bykov** [comment]
the problem with "watch" is that vscode doesn't allow to run the test command while watching typescript, saying there is another command running, so at least with having to run the tests from under vscode "watch" isn't an option

**Comment by dbaeumer** [comment]
We have feature request to allow more than one command.

**Comment by dbaeumer** [comment]
As said I close this one since it will be addressed in tsserver.

**Comment by aleksey-bykov** [comment]
Merged https://github.com/Microsoft/TypeScript/pull/9837

**Comment by styfle** [comment]
@dbaeumer Now that it is merged in tsserver will it simply work with vscode or will there need to be more work to integrate it?

**Comment by dbaeumer** [comment]
@styfle it should work with VS Code without additional integration effort. But please note that VS Code still ships with 1.8.10 and I think the feature will not make it out of the box into 2.0 either.

**Comment by mrcrowl** [comment]
@dbaeumer From what I can see, there _is_ additional integration effort needed to enable compile on save in VSCode for TypeScript.  Since v2.0.5, tsserver has supported the new API methods `compileOnSaveAffectedFileList` and `compileOnSaveEmitFile`, but they need to be called from the typescript extension.  I've done some prelim work on getting this going for myself and would be happy to support a pull request if there was support?

**Comment by dbaeumer** [comment]
@mrcrowl you are correct that the current implementation in the tsserver does require quite some work in the extensions. I started a discussion with the TS team about this here: https://github.com/Microsoft/TypeScript/issues/11526

The bottom line is that this doesn't belong into the extension since the extension can never implement this in a efficient way (and the TS team agrees on this). Especially since compileOnSave must also do problem checking. Doesn't make to much sense to write a new JS file without telling the user that you know have compile errors in dependent files.

So I would opt that instead of adding this to the extension your effort is better put into the tsserver to make this work. I started this along time ago here: https://github.com/Microsoft/TypeScript/blob/dbaeumer/9125/src/server/builder.ts and parts of the work made it into 2.0.6. But still no full builder. Their current builder only manages dependencies: https://github.com/Microsoft/TypeScript/blob/master/src/server/builder.ts

**Comment by Ciantic** [comment]
Shouldn't this be re-opened if there is more work to be done in VSCode code base? I'm running 2.2.0-dev in stable VSCode, the compile on save does not work with it.

**Comment by dbaeumer** [comment]
Yes, https://github.com/Microsoft/TypeScript/issues/11526 is the right item to track. We had again discussions with the TS team and there was agreement that something like compileOnSave and building is best implemented in the TSServer and not in VS Code. There still might be some little adoption needed in VS Code but it is currently not clear how that would look like. We will open an issue when the tsserver is ready.

**Comment by SaschaNaz** [comment]
>I'm running 2.2.0-dev in stable VSCode, the compile on save does not work with it.

Sorry for pinging on a closed old issue, but it is still not working, right? I want to make sure that this is not my settings problem.

**Comment by mrcrowl** [comment]
As far as I'm aware, Compile on Save is still not officially supported by
VS Code.  If you need an interim solution—while the tsserver approach is
being developed—you can compile your own TypeScript extension for VSCode
(which replaces the overrides the built in one) from my fork of the vscode
repo here: https://github.com/mrcrowl/vscode (specifically
https://github.com/mrcrowl/vscode/tree/master/extensions/typescript).  I'm
happy to provide a precompiled .vsix if that is easier.

**Comment by mrcrowl** [comment]
... one caveat (to my previous message) is that my version of CompileOnSave
doesn't report errors.  I use it in conjunction with a standard Build watch
process to capture errors—but it still allows me to do super-fast edits and
refresh in browser, without waiting for full compile.

On Thu, 2 Feb 2017 at 19:59 Ben Crowl <mrcrowl@gmail.com> wrote:

As far as I'm aware, Compile on Save is still not officially supported by
VS Code.  If you need an interim solution—while the tsserver approach is
being developed—you can compile your own TypeScript extension for VSCode
(which replaces the overrides the built in one) from my fork of the vscode
repo here: https://github.com/mrcrowl/vscode (specifically
https://github.com/mrcrowl/vscode/tree/master/extensions/typescript).  I'm
happy to provide a precompiled .vsix if that is easier.

On Thu, 2 Feb 2017 at 17:44 Kagami Sascha Rosylight <
notifications@github.com> wrote:

I'm running 2.2.0-dev in stable VSCode, the compile on save does not work
with it.

Sorry for pinging on a closed old issue, but it is still not
working, right? I want to make sure that this is not my settings problem.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/7015#issuecomment-276867218>,
or mute the thread

**Comment by dbaeumer** [comment]
What we usually do is to run the tsc compiler in watch mode (which gives you compile on save) via the task runner. Here is that tasks.json I use:

```json
{
	"version": "0.1.0",
	"command": "npm",
	"isShellCommand": true,
	"args": ["run", "watch"],
	"showOutput": "silent",
	"isWatching": true,
	"problemMatcher": "$tsc-watch"
}
```

and a package.json
```json
{
        ....
	"devDependencies": {
		"typescript": "^2.1.5",
	},
	"scripts": {
		"compile": "tsc -p ./src",
		"watch": "tsc -w -p ./src"
	}
}
```

This gives you project wide errors and compile on save.

**Comment by httpete** [comment]
This is pretty nice.

I have updated dbaemuer's example for the latest version of VS Code.

`{
	"version": "0.1.0",
	"command": "npm",
	"isShellCommand": true,
	"args": ["run", "watch"],
	"showOutput": "silent",
	"isBackground": true,
	"problemMatcher": "$tsc-watch"
}`

`  "scripts": {
    "dist": "node ./scripts/dist",
    "compile": "node ./node_modules/typescript/lib/tsc --pretty",
    "watch": "node ./node_modules/typescript/lib/tsc -w"
  }`

The only thing I still don't like is CTRL+SHIFT+B.

**Comment by MicahZoltu** [comment]
So it seems that https://github.com/Microsoft/TypeScript/issues/11526 indicates that TSServe work is done and ready to be used.  Should this issue be re-opened or another one created to get everything working together correctly?

**Comment by ShaharHD** [comment]
@dbaeumer Can we re-open this issue?
As it seems it can be fixed within the next minor version iteration of VSCode, or I'm mistaken?

**Comment by dbaeumer** [comment]
@ShaharHD I followed up with the TS team on this in Microsoft/TypeScript#11526. To my understanding the current solution would still need quite some work in VS Code that is better done in TSServer.

@mjbvz @waderyan did you talk to the TS team about the builder lately? What is the current state of this?

**Comment by ShaharHD** [comment]
I'm assuming this Microsoft/TypeScript#8884 (which was opened by you) haven't got any traction either.

**Comment by mrcrowl** [comment]
@dbaeumer, @httpete I agree that the watch mode of tsc is great, and works perfectly for many projects.  

In my workplace, though, I've found that watch doesn't scale well to our project size (approx 4,500 typescript files).  A change to a single file in our project can take 15-20 secs to finish compiling.  This is why I care about compileOnSave still being a supported feature.  

With the changes I made to the typescript extension in [my fork of vscode](https://github.com/mrcrowl/vscode/tree/master/extensions/typescript), I'm able to compile changes to individual files in <200ms and leave the watch running in the background to catch refactoring errors.  

I realise this "unchecked" approach is not the way you'd like it to work, but I would like to raise awareness that watch by itself is not working for us.

**Comment by dbaeumer** [comment]
@mrcrowl we are aware of the fact that tsc -watch doesn't scale well for larger project. An alternative to tsc -watch is to use gulp-tsb an incremental builder we maintain to incrementally compile VS Code itself. It is here: https://www.npmjs.com/package/gulp-tsb. Downside is that you need to use gulp and gulp watch to use it. You can also look at VS Code's gulp files to see how we use it. 

We are working with the TS team to get this builder approach into the TS project.

**Comment by dbaeumer** [comment]
one more comment: the builder might not work in all cases perfectly. So for example for internal module systems it recompiles the world on every file change.

**Comment by mihailik** [comment]
This feature request is for **compile on SAVE**, not compile on filesystem change.

Neither TSServer, nor `tsc.js`, nor `gulp` have any clue when a "file save" operation happens, so any solutions based on filesystem watchers are workarounds.

The two fundamental downsides of filesystem watch workarounds are:
* latency -- feedback taking seconds versus a fraction of a second
* CPU/battery overhead

The ideal is to compile while your fingers lift off the Ctrl key. On a commodity laptop without spare battery.

There is also a costly non-fundamental downside. 
* VSCode+TS does NOT work out of the box

Makes boasting about beauties of VSCode so much harder: _'hey you just download it and spend 1/2 hour to 45 minutes scouring blogs and GitHub issues for the right snippets of them taskings, there was a combination to paste them like Alt-P or whatever'_

I'd much rather said: _'hey you just download it and to enable feature X set flag X in config'_

**Comment by dbaeumer** [comment]
The tasks for compile the whole project and to run tsc in what mode will come preconfigured with the next release without the need of tweaking a tasks.json file.

And yes, I agree that the best solution would be the tsserver doing this on file change / save events.

**Comment by desertdev** [comment]
Looking forward to giving VSCode another try after the next release! The excellent points brought up @mihailik caused too much friction for my dev team to adopt VSCode at this time.

This is unfortunate because VSCode seems to have the best tooling available to help developers work with Typescript, _except_ for a simple, sane approach to "turning on" compile on save.

**Comment by Dashue** [comment]
Good stuff! When might that release be exp?

**Comment by Dashue** [comment]
Latest release landed, was this part of it? @dbaeumer

**Comment by dbaeumer** [comment]
@Dashue zes, but you still need to opt into it. Create an tasks.json like this:
```json
{
    "version":"2.0.0"
}
```
and you should see build tasks to compile TS -> JS without any further config steps.

**Comment by Dashue** [comment]
[Info  - 14:17:13] Using tsserver from: c:\Program Files (x86)\Microsoft VS
Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js
[Info  - 14:17:13] Forking TSServer
PATH: undefined

**Comment by Dashue** [comment]
Not sure whether you got the mention, as it was added during an edit @dbaeumer

**Comment by dbaeumer** [comment]
@mjbvz does comment https://github.com/Microsoft/vscode/issues/7015#issuecomment-308112455 ring a bell ?

**Comment by dbaeumer** [comment]
@Dashue this is unrelated to tasks and it comes from the TypeScript extensions. I pinged the corresponding dev.

**Comment by mrcrowl** [comment]
For anyone still interested in compile-on-save, here's a .vsix you can manually install in vs code 13.x that replaces the built-in typescript extension, with one that supports the compileOnSave setting in tsconfig.json:
https://github.com/mrcrowl/vscode/releases/tag/13.10.8

**Comment by Dashue** [comment]
@mrcrowl @dbaeumer Installing that would be a hack around right? When is it officially landing in vscode? I'm running on the latest typescript afaik.

**Comment by mrcrowl** [comment]
@dbaumer, your [comment from May 18](https://github.com/Microsoft/vscode/issues/7015#issuecomment-302339373) refers to a preview feature in vscode 13.x that simplifies build tasks for TypeScript (see [release notes](https://code.visualstudio.com/updates/v1_13#_preview-tasks-version-20)), which is great... but this feature hasn't yet addressed "compileOnSave", right?

---
@Dashue, yes, installing [this extension](https://github.com/mrcrowl/vscode/releases/tag/13.10.8) is a hack that is not officially supported.  Here's a bit of background:

As I see it, there are two groups of people wanting "compileOnSave":
 - _**Group 1**_ just want TypeScript compilation with minimal configuration, for small-to-medium sized projects.

 - _**Group 2**_ want performant TypeScript compilation for larger projects (this is the promise of TypeScript, right? ["JavaScript that scales"](http://www.typescriptlang.org/))

_Group 1_ are well-covered by a combination of tsconfig.json + watch + tasks.json, i.e. file-system watcher that incrementally builds when a file change is detected.

I'm concerned with _Group 2_, who are working on larger projects where even the incremental build takes too long to run.  Based on @dbaeumer's [May 5 comment](https://github.com/Microsoft/vscode/issues/7015#issuecomment-299398558) there is an awareness of this within the TypeScript and vscode teams (...is there an issue for this?)

In the meantime, my team needed a way to continue fast TypeScript compiles, often for individual files within the context of a large project.  Hence, the provided extension which uses [existing tsserver apis](https://github.com/Microsoft/TypeScript/blob/451561ec8d793309ca9daa438f22764dd0ef440a/lib/protocol.d.ts#L12) to achieve a pragmatic compile-on-save behaviour, while we wait for an official solution to materialize.  

The built-in TypeScript extension [runs a tsserver instance in the background](https://github.com/Microsoft/vscode/blob/732824c35467b7d625421d3dc048bb1bbe99377e/extensions/typescript/src/typescriptServiceClient.ts#L433), which is synchronised with editor changes. In order to take advantage of that same tsserver instance my version of the extension has to replace the built-in TypeScript extension.  It's possible a similar result could now be achieved as a typescript server plugin, although I haven't investigated that route yet.

**Comment by dbaeumer** [comment]
@mrcrowl here some issues in the TS land about compile on save and a full builder in the TS server:

https://github.com/Microsoft/TypeScript/issues/9125
https://github.com/Microsoft/TypeScript/issues/11229

Building a performant incremental builder for large projects is not trivial (as you might have noticed as well). The TS team is still on this but it might be helpful if you start to vote on https://github.com/Microsoft/TypeScript/issues/11229

**Comment by mrcrowl** [comment]
@dbaeumer would you consider #28912 as an alternative for now?

**Comment by dbaeumer** [comment]
@mrcrowl I think having TS exposing its API is useful regardless of this issue.

**Comment by josh-sachs** [comment]
The vsix provided by @mrcrowl does EXACTLY what vscode should do by default.

**Comment by meriturva** [comment]
Right now TypeScript 2.4 is landed, but i think there is no news about compileOnSave fix on TS Server or language service. Do we have to wait also VSCode new version to have a productive environment? Vsix from @mrcrowl is really a good start (thanks again) but i think that we have to expect an official solution. am i wrong?

**Comment by bkniffler** [comment]
The best solution for me was using a build task and ONLY compile the saved file:
```json
// project: .vscode/task.json
{
  "version": "0.1.0",
  "command": "node",
  "isShellCommand": true,
  "args": ["${workspaceRoot}/node_modules/.bin/tsc", "${file}"],
  "showOutput": "always",
  "problemMatcher": "$tsc"
}
```
```json
// keybindings
{
    "key": "cmd+s", 
    "command": "workbench.action.tasks.build", 
    "when":"editorTextFocus && editorLangId == 'typescript'"
}
```

Thanks for https://stackoverflow.com/a/34094418/4388296 for pointing in the right direction. I just modified the task to use the local node_modules typescript installation, you can use his snippet if you got it globally installed.

**Comment by xygahs0801** [comment]
I just write a little extension.
[https://github.com/xygahs0801/ts-compile-on-save](url)
[https://marketplace.visualstudio.com/items?itemName=liuwei.ts-compile-on-save](url)
this will execute ts -w for workspace if it contains this tsconfig.json file.

**Comment by fuyifan** [comment]
@xygahs0801 It works great. Thank you very much.

**Comment by josh-sachs** [comment]
It sucks that this issue has been closed, as it doesn't appear any official support addressing this has been provided.  Visual Studio seems to do this out of the box, without the need to run a battery draining background process during development.

**Comment by lilred** [comment]
Could this issue please be re-opened? It's not exactly resolved.

**Comment by mjbvz** [comment]
@lilred This is issue is still being tracked by #973 and #7342
