### ISSUE TITLE
Autocomplete is inserting selection after typing period

### ISSUE THREAD

**Issue by cawoodm** [microsoft/vscode#70176]
## Justification

This is a duplicate of #47696 which IMHO was closed prematurely. There seems to be confusion between a hotkey which launches intellisense (like `.`) and a hotkey which confirms the intellisense suggestion (like `<tab>` or `<enter>`. Normally, when one types `.` one expects suggestions but does NOT want the first suggestion to be accepted. If I type `window.` I do not want `window.location` because `location` is at the top of the list. `.` is not, a "commit character" as mjbvz says - rather it should offer suggestions but not choose them.

If we're agreed on that then there does seem to be a bug:
* OCCASIONALLY when I type `dp(` I get `devicePixelRatio` inserted which is not what I want.
* OCCASIONALLY, when I type `steps` I get `SVGTextPositioningElement`.

I can't reproduce it always but it happens sometimes and seems to be design according to #47696. That cannot be right.

* VSCode Version: 1.32.1 (user)
* OS Version: Windows 10

## Original Bug Report

Autocomplete is inserting the selected suggestion after the user types a period. This is not mentioned in the User Guide, which says Pressing Tab or Enter will insert the selected member., and there appears to me to be no clear way to disable this via the keymap. I suspect this is a behavior that some users may expect, but it would be nice if there was some way to disable it, as it makes for a frustrating experience to type out property names that Intellisense is not suggesting.

* VSCode Version: 1.22.1
* OS Version: macOS 10.13.1
* Does this issue occur when all extensions are disabled?: Yes

## Steps to Reproduce:

Create a Javascript file test.js
1. Type window
2. Type .
3. Because the first suggestion is addEventListener, the result will be window.addEventListener.

**Comment by mjbvz** [comment]
What you described is the expected behavior of commit characters: they accept the currently showing suggestion. We treat `.`  as a commit character in js/ts. You can press `esc` to cancel out of suggestion if you don't want to accept the current suggestion when typing a commit character, or disable commit characters by setting `"editor.acceptSuggestionOnCommitCharacter": false`

I can't reproduce `addEventListener` being the first suggestion after typing window. Are you typing `.` twice in that example? Or do you have an extension installed that could be adding additional suggestions?

**Comment by yume-chan** [comment]
Looks similar to #66868

There are multiple reports, and I can also reproduce it with latest insiders build.

![1](https://user-images.githubusercontent.com/1330321/54103976-50a69680-4409-11e9-94e9-a19be690b1a1.gif)

Yes, you have to type very fast, or make your computer run slower may help reproduce.

**Comment by yume-chan** [comment]
It's also very funny that different type speed will give me different suggestions.

![2](https://user-images.githubusercontent.com/1330321/54104278-3b7e3780-440a-11e9-8ba8-ed7cb278d3ef.gif)

When I type "T H" very fast, it gives me `UNSAFE_componentWillMount`, which is a reproduce of #66868.

But when I type slowly, it gives me `containerRef`, as the above comment shows.

**Comment by cawoodm** [comment]
> We treat . as a commit character in js/ts.
So you want `window.` to resolve to `window.location` immediately on pressing `.`?? I must be misunderstanding you, that can't be how you work. Indeed, that isn't how it works most of the time nor in any other IDE or source code editor. `.` is a typical "propose" not "commit" character.

I think @yume-chan is on the right track: when typing fast it happens, otherwise it doesn't.

**Comment by daniel-harrison-cko** [comment]
I hate this behaviour. I have added `"editor.acceptSuggestionOnCommitCharacter": false` to my `settings.json`.

It just feels so unnatural. If I want something to auto-complete I will press tab, otherwise it should never auto-complete. I don't understand why this isn't the default behaviour.

**Comment by davidgiven** [comment]
I'm getting this as well. It's maddening --- I keep getting spurious and incorrect insertion of text. I've seen it happen on commas, spaces and various other bits of punctuation, too. I know that some people like it, but I would really like a way to disable it completely (except for tab, of course).

**Comment by cawoodm** [comment]
Just had it again: typing at speed and hit `dp(` and suddenly I had `devicePixelRatio` appear. @yume-chan has nailed it - it's a speed bug.

**Comment by daniel-harrison-cko** [comment]
It's not a speed bug. If you type `dp` and then wait a while and then type `(` it will still complete with `devicePixelRatio`. No?

**Comment by daniel-harrison-cko** [comment]
@davidgiven You can disable it. Open your settings.json and add `"editor.acceptSuggestionOnCommitCharacter": false`

**Comment by daniel-harrison-cko** [comment]
> What you described is the expected behavior of commit characters: they accept the currently showing suggestion. We treat `.` as a commit character in js/ts. You can press `esc` to cancel out of suggestion if you don't want to accept the current suggestion when typing a commit character, or disable commit characters by setting `"editor.acceptSuggestionOnCommitCharacter": false`
> 
> I can't reproduce `addEventListener` being the first suggestion after typing window. Are you typing `.` twice in that example? Or do you have an extension installed that could be adding additional suggestions?

This drives me mad. I do test-driven development and the majority of the time I am writing the code as I expect it to be used before actually implementing it. So period and parentheses as commit characters always ends up producing an incorrect autocomplete. It's very annoying to have to press ESC every time I dot into or call a method that autocomplete hasn't found yet (because it doesn't exist).

**Comment by cawoodm** [comment]
I think we have to say that `(` and `.` CAN be a commit character if we're actually inside an object so `object.method(` may autocomplete on the `(` but not on the `.` for the simple reason that I may have an `object` which VSCode does not know and VSCode should not change it into `objectWhichVSCodeDoesknow`.

So if I type `dp(` there is NO REASON IN THE WORLD to replace this with `devicePixelRatio`.

If I type `object.` there is no reason to autocomplete this to `objectWhichVSCodeKnowsButIDontWant`.

I think by only autocompleting actual members instead of top level objects we would be rid of this bug.

Does anyone seriously want `win.` to become `window.`. Are they a majority?

**Comment by mlynch** [comment]
Been getting this consistently in a React class-based component where you starting typing `this.` quickly, and it auto completes to `this.UNSAFE_componentWillMount`. I disabled `"editor.acceptSuggestionOnCommitCharacter"` which does resolve the issue but it sort of just patches the problem.

Another similar issue that was closed prematurely is #56026

**Comment by ivanvoznyakovsky** [comment]
+1 to the issue. experiencing it all the time. very annoying.

**Comment by prurph** [comment]
👍 same issue here.

**Comment by brylie** [comment]
@ivanvoznyakovsky and @prurph please add your thumbs up to the issue description.

**Comment by andyearnshaw** [comment]
I've noticed for a while now that, occasionally, when I type `this.`, VSCode would autocomplete to something unexpected.

I just updated to the latest release and created a new test file.  In the new file, I could not type `it(`, because pressing the `(` character autocompleted to `italics(` as well as imported the function from somewhere. I switched off auto imports and tried again and it would autocomplete to `instanceof(`. There was no way at all for me to type `it(` until I disabled `acceptSuggestionOnCommitCharacter` in my *settings.json*.

That this is the default behaviour is absolute madness.

**Comment by jamesplease** [comment]
I keep experiencing aggressive autocomplete suggestions when trying to type three dots for, say, spreading or rest props. The autocomplete has always been excellent, but a recent change must have introduced some kind of regression.

It only happens sometimes, and it often occurs in situations where it doesn't make sense. i.e.;

```js
const { ...rest } = something;
```

would end up becoming:

```js
const { .children
```

once I type the second `.`

**Comment by Hiestaa** [comment]
Does this still require more info? I captured a gif of me typing in a python environment `fig = plt.figure('heatmap')<enter>` which get replaced by `fig plt` because the period is ignored by the autocomplete window:

<img src="http://recordit.co/QQVFpPBLtj.gif"></img>

This is incredibly counter-productive, I'm not always looking at my screen when I type code and not being able to reliably insert the line I type when followed by enter a bit too fast causes me to write many lines multiple times...

**Comment by mjbvz** [comment]
@Hiestaa Please file that issue against the python extension

**Comment by brylie** [comment]
I think this bug should remain open, as it is still affecting multiple users.
