### ISSUE TITLE
Terminal command unexpected spaces and hides the path

### ISSUE THREAD

**Issue by subashdbc** [Microsoft/vscode#70191]
Hi,
When I open Terminal on VS Code for the first time and start to type some command in it, it is taking unexpected spaces before that, and also it hides the path. It occurs only for the first time when I type the command. Below is the result,
![terminal](https://user-images.githubusercontent.com/22951240/54100852-99992380-43e6-11e9-828c-2abbd41d7a13.PNG)
When I hit enter for the first command that I typed, it works. 

There is no problem with commands, but it shows unexpected spaces and hides the relative path.

**Comment by yume-chan** [comment]
@Tyriar There are so many issues regards the integrated terminal since 1.31 was released.

#70191 Terminal command unexpected spaces and hides the path
#70135 Terminal window text becomes invisible upon typing
#70130 terminal window does not shows the directory when opens for the first time
#70148 built in terminal
#70109 Terminal VIsual Bugs, and more
#70096 Integrated terminal is printing ^C instead of canceling the command
#70051 Terminal starts blank
#70141 cmd命令模式下，首次打开没有提示符

AFAIK, the ConPTY is never enabled for Windows 1809 in stable releases, so users should always using WinPTY, is it true? What caused these issues?

**Comment by Tyriar** [comment]
@yume-chan ConPTY is available in 1809 but has big stability and performance issues so I disabled it completely (those issues are worse than this graphical glitch). These have been coming in for months now, if there has been an uptick of issues it's likely more related to more people updating Windows 10. The cause was a bug that slipped into Windows and didn't get fixed until it was too late.

/duplicate https://github.com/Microsoft/vscode/issues/57803

**Comment by FireController1847** [comment]
So I'm confused, are we implying it's fixed? Or are we saying that it's an issue on Windows' side? Does that mean there's _nothing_ that can happen to fix it without changing the Windows version?

**Comment by Tyriar** [comment]
@FireController1847 nothing can happen to fix it until you get the new version of Windows, I'm not a fan of the outcome either.

**Comment by FireController1847** [comment]
@Tyriar May I ask what the version of windows is that fixes the issue? Is it currently insiders only?

**Comment by Tyriar** [comment]
@FireController1847 yep Insiders only until the 1903 version of Windows 10 goes out.

**Comment by FireController1847** [comment]
@Tyriar That's unfortunate. Alright, thanks for the clarification!
