### ISSUE TITLE
bold links dont open in markdown file using editor mode with ctrl + click

### ISSUE THREAD

**Issue by ucavalcante** [microsoft/vscode#70254]
- VSCode Version: 1.32.1
05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
x64
![vscode link error on md files](https://user-images.githubusercontent.com/13587928/54154664-2e207780-4421-11e9-8042-b83e6867168a.png)

- OS Version: Windows 10 Pro 1809 build 17763.348

Steps to Reproduce:

1. Open .md file with internet link inside.
2. Press Ctrl + Click in the link
3. See ** on end of the link in web browser.

Does this issue occur when all extensions are disabled?: Yes

bold links don't open in markdown file using editor mode with Ctrl + click I believe the two * in end are sending to the browser, this is don't occurs in preview mode they work properly.

**Comment by KanteLabs** [comment]
@alexr00 @Tyriar If no one is working on this. I would like to take a crack at this.

**Comment by ngrygiel** [comment]
If this still isn't fixed I'd like to take a look into this.

**Comment by KanteLabs** [comment]
@ngrygiel you can take a crack at this.

**Comment by w9jds** [comment]
So, I was looking into this a bit and I found that the regex provided in the actual `documentLinkProvider.ts` doesn't actually find the link (with or without the bold). So I'm not sure that is where it would be fixed as suggested in the closed PR.

**Comment by mjbvz** [comment]
VS Code has a standard link detector that detected normal `http://...` links in text files.  (`src/vs/editor/common/modes/linkComputer.ts`). That is what is kicking in here

One option would be to push all markdown link detection into the markdown extension (into that `documentLinkProvider.ts`). Those links should override VS Code's built-in detected links. The markdown it parser can find these

Or instead of markdown it, you could try using the [`vscode.executeLinkProvider` command](https://code.visualstudio.com/api/references/commands) to get the links that VS Code built-in link detector detects and then rewriting the results to not have the trailing `*`

**Comment by w9jds** [comment]
Sorry for the delay. 

One last question for you. When I looked at the [RFC 3986](https://tools.ietf.org/html/rfc3986#section-2.2) on Reserved Characters in URIs, it looks like the `*` is considered one that is required to be encoded, so shouldn't the `linkComputer` be updated to consider it as a delimiter causing the link to end?
