### ISSUE TITLE
Update Constantly Failing

### ISSUE THREAD

**Issue by aarrico** [Microsoft/vscode#70272]
Every time I close VS Code auto update starts and fails after it has deleted the previous installation but before it finishes installing the new version.  I have to clean out leftover files then install fresh from the installer exe.  Error during installation pointed to a log file which is attached.

[vscode-inno-updater-1552337279.log](https://github.com/Microsoft/vscode/files/2954824/vscode-inno-updater-1552337279.log)

**Comment by Muzical84** [comment]
Seems like every time this bug is reported, it's linked to a bunch of other reports that are also closed as dupes, but **never is the One True Issue Report provided**!  Also, given that some of these reports go back half a year or longer, _**there's no excuse for this problem to still exist**_.  The user-profile install was supposed to eliminate these bugs, but I haven't been able to do a clean update, without having to uninstall, reboot, and reinstall from scratch, every single freaking time, since the user-profile installer debuted!

**Comment by joaomoreno** [comment]
@Muzical84 Unfortunately, they are hard bugs to fix. And despite being ugly, they hit a small portion of the user base. Additionally, in case you have issues like this one, the recommendation is to switch back to the system setup, which we still ship. I trust that works fine for you?

/duplicate #60697

**Comment by yanxijian** [comment]
It still failed when updating from x64-1.32.1 to x64-1.32.2. I have to download the new installer and install it manually every time. 
: (
