### ISSUE TITLE
Context custom menu not shown in glyph margin

### ISSUE THREAD

**Issue by PowerMogli** [Microsoft/vscode#70388]
- VSCode Version: latest insider version
- OS Version: Windows 10

Steps to Reproduce:

1. Set a breakpoint in editor
2. Try to edit breakpoint with mouse right click

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
Right click -> context menu does not do anything for you?
Can you please provide a .gif showing this issue?
Thank you

**Comment by PowerMogli** [comment]
I dont get any context menu when I use the right click.

**Comment by PowerMogli** [comment]
But in the Breakpoint View I can right click at one breakpoint and inside the context menu of right click I have the option to choose "Edit Breakpoint..."

**Comment by isidorn** [comment]
Thanks for submiting this issue. I can only repro this on Windows.
I think it is a regression of the strict null work I did a couple of days ago. Looking into it

**Comment by isidorn** [comment]
The issue here is that the custom menu is no longer shown in the glyph margin.
I have bysected this and came to 
![Screenshot 2019-03-13 at 18 03 55](https://user-images.githubusercontent.com/1926584/54299081-67401f80-45ba-11e9-9adc-28841a6deee4.png)

That commit touches the whole world. Anyways forwarding to @sbatten and @bpasero

**Comment by bpasero** [comment]
@sbatten I am not sure how my changes could have caused this, maybe you can take a look. I can debug this and see that the html context menu service is properly called all the way to the end, but the context view with the menu does not seem to appear properly.

**Comment by bpasero** [comment]
@sbatten ok this seems to be triggered by my changes, but not clear to me why it only surfaces in this small area. Previously, in the ContextMenuHandler we would call:

`this.setContainer(null);`

and now we call:

`this.setContainer(this.layoutService.container);`

However, in the standalone editor we always passed a container into the context menu handler. I added the layout service so that the service can be created without dynamic arguments and that seems to have caused this regression for the workbench at least where the behaviour is now different.

**Comment by sbatten** [comment]
@bpasero The safest but dumb fix here is to use this in the constructor for `ContextMenuHandler`
```ts
this.setContainer(this.layoutService.hasWorkbench ? null : this.layoutService.container);
```

The riskier fix is to actually remove this line https://github.com/Microsoft/vscode/blob/51ba7278afcc139c13ab1e9b3f183ff065dffa49/src/vs/platform/contextview/browser/contextMenuHandler.ts#L50

This one handles dismissing the context menu when mouse events are triggered outside the menu, but I think it is outdated. We focus menus now when they are created and use blur events to dismiss them. It is getting triggered in the wrong order in the workbench and since the layoutService now provides a container, the logic to handle this is kicking in.

**Comment by bpasero** [comment]
@sbatten so you say this mouse down listener is only being added because we provide a container? That sounds fishy to me...

**Comment by isidorn** [comment]
We need this for this milestone. More and more people are hitting it.
