### ISSUE TITLE
Drop Open Editors group rows

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7043]
How about dropping the group rows from the Open Editors?

![image](https://cloud.githubusercontent.com/assets/22350/15667233/7bd24f34-2715-11e6-9a29-60e218263ea2.png)

To represent the groups, we can draw a horizontal line between editors. As for the group's contextual actions, just place them to the right of the first open editor of that group.

**Comment by isidorn** [comment]
I am fine experimenting with this however I do not like the visual looks of your sketch - just personal preference.
I think it is also up to the ux team to decide on this since they designed the inital open editors experience.

For me the biggest flaw of the current design is that the tree grows considerebly when you go from 0 to 2 groups. I am not convinced if this is big enough of a flaw to go with a different design

**Comment by bpasero** [comment]
I also prefer our current design because you can interact with groups a lot more (potentially reorder groups, context menu on groups etc).

**Comment by joaomoreno** [comment]
I can see many other flaws other than the growing:

- The screen real estate taken up by the group rows is considerable.
- The group names and bogus and irrelevant.
- The tree-like indent of the whole view is weird, especially with very few files open.

As for the *future* interactions:

- You can still implement group reordering with an affordance to the left of the group's first editor 
![image](https://cloud.githubusercontent.com/assets/22350/15667686/eb889e94-2717-11e6-8c89-1ffa00b46694.png)
- You can have context menu on groups by having a separate group of actions in the context menu of each of the group's editors

**Comment by isidorn** [comment]
> The group names are bogus and irrelevant.

I think with your design it might be hard for the user to figure out which group some editor belongs to when > 10 editors open

> The tree-like indent of the whole view is weird, especially with very few files open.

It is the same ident we use in the explorer and explorer looks the same with very few files open.

> You can have context menu on groups by having a separate group of actions in the context menu of each of the group's editors

This would potentially work with a group submenu otherwise the context menu would be too large

Not sure if making the first editor in the group more powerful by having more options would be too complex for users. UX team can comment on that better.

**Comment by stevencl** [comment]
The feedback we got from participants last week on this indicated that they don't think the group names are bogus and irrelevant nor do they think that the indentation is weird. Participants naturally assumed that they could drag and drop files between groups for example thus suggesting that the representation serves at least three of it's purposes (namely indicating that files belong in groups, that the groups are easily identifiable and that files can be moved between groups).

**Comment by joaomoreno** [comment]
Then, let's close it.
