### ISSUE TITLE
Talking about Group Left is confusing if there is only one group

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#7044]
- VSCode Version: alpha

See screen shot. If there is only one group we should either use middle (or main) or even better not mention group as well.

![capture](https://cloud.githubusercontent.com/assets/1931590/15667448/8df98898-2716-11e6-92cd-3e480122a1b7.png)

**Comment by bpasero** [comment]
@dbaeumer the quick open prefix is "edt left" though and I am not sure you would want that to also change? Are you mainly concerned about the blue group label?

**Comment by dbaeumer** [comment]
@bpasero What I did is clicking on the sergeant icon. If I only have one editor open I would expect that the system talks about the middle edt in both the command and the blue group label

**Comment by bpasero** [comment]
Not sure about middle but maybe it should be something like "`main`".

**Comment by dbaeumer** [comment]
Main is fine with me as well. How do we call the middle when three are open? Center. Then center would be an option as well since it doesn't introduce a new term.

**Comment by bpasero** [comment]
@dbaeumer it might be confusing though that "center" shows something if you have only 1 editor open and when you open a second group, "center" is suddently showing something else because the new group opens in center and does not contain the editors from the first group.

**Comment by bpasero** [comment]
I delivered two changes that should improve this: For one, I am not showing group label anymore in the picker if there is only one group and this matches what the "opened editors" view does.

Then, when you have just 1 group open and you click the overflow icon, I just open the "show all opened editors" picker because that one does not talk about "`edt left`" but just "`edt`". Once you have more than one group open, things work with "`edt left`", "`edt right`", etc.

**Comment by dbaeumer** [comment]
Sounds great.
