### ISSUE TITLE
Add option to let Ctrl+P always reveal editor if the file is already open

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#7049]
- VSCode Version: alpha
- OS Version:

Steps to Reproduce:
1. No tabs no Open editor section
2. Two groups. G1: a.txt & b.txt with b.txt in front; G2: c.txt
3. G2 has focus
4. Ctrl+P a.txt

Observe: a.txt is opened a second time in G2

I would like to have an option to reveal a.txt in G1 instead of opening a new copy.

**Comment by bpasero** [comment]
@dbaeumer would this really be scoped to Ctrl+P or any action that opens an editor (e.g. click on the explorer)?

**Comment by dbaeumer** [comment]
@bpasero good question. I would say any action that opens an editor.

**Comment by bpasero** [comment]
Yeah that would make most sense I guess.

**Comment by ddotlic** [comment]
@dbaeumer @bpasero based on at least two duplicates of this issue, there is _some_ interest in this. Additionally seems to me this is simple to do. Any chance of seeing it soon-ish?

**Comment by bpasero** [comment]
Interest is best expressed by upvoting issues 👍

**Comment by ddotlic** [comment]
@bpasero Then it's gonna take forever... OTOH, the product _is_ OSS, if only there was some way for external contributions 😛

**Comment by ddotlic** [comment]
@bpasero OK, seriously, would this be doable if I had zero experience with VS Code code base, but a lot of experience in general? Where should I start looking?

**Comment by bpasero** [comment]
It probably needs a new option for editors similar to revealIfVisible which is being used when opening an editor from e.g. from /Users/bpasero/Development/Microsoft/monaco/src/vs/workbench/browser/parts/quickopen/quickOpenController.ts

**Comment by ddotlic** [comment]
@bpasero Great, thanks for the starting point, I guess it's time I put the "money" where my mouth is (I did say it looks like an easy one to do 😉).

**Comment by bpasero** [comment]
We always welcome PRs and are happy to review good code contributions 👍

**Comment by ddotlic** [comment]
@bpasero It's a shame we're so used to the old model where we'd ask/upvote an issue and then (having no access to the code) wait for days, months, years until someone added it into the product. Took me _minutes_ to realize I can simply follow contributor guidelines and do this myself.

I've already had one wonderful experience with VS Code (not counting daily joy of using it) where an issue I've reported was fixed in a day and by using insider I had it working on my machine in two, let's make this a second one (me scratching my own itch but also helping others).

Thanks for all the work you're putting in this product, it's much appreciated 🙌

**Comment by ddotlic** [comment]
@bpasero I think I know what I need to do (did not have time to look into this until today), but I was wondering one thing: why the `options` object? Why not fetch applicable options at the last possible moment? Too expensive to fetch, or the object providing the options isn't available everywhere? 

There's quite a bit of code fiddling with flags in the options object all over the place, looks like most of the change would boil down to propagating the flag instead of the actual issue at hand (which should be implemented in ~dozen lines of code).

One other thing: when user opens Code **empty** (no files or folders open), opens a file, then splits the editor, I don't see the way around loading the same document again, do you? I really tried to think of a way to avoid this, but I can't...

**Comment by bpasero** [comment]
@ddotlic options still allow clients to override the setting if needed, otherwise that would not be possible.

**Comment by ddotlic** [comment]
@bpasero I have it working for the "user interactive" case where the file gets open via quick open (which corresponds to the title of this issue). The only reason it does not necessarily work for other cases is propagation (or lack) of the newly added option (that I called `revealIfOpen` - naming is extremely hard, let's review names once we start merge, assuming you accept the PR).

However, as you've noted, it should in fact work for all "open document" situations, which leads us to the `options` discussion again. I can see that you're liberally putting values in this object in various contexts and it's not clear which criteria you use(d) to arrive at a given value. Quite often, the code would **not** look at the configuration but would override a given setting with a hard-coded value.

Concretely, let's say that I want to apply this same setting for the "F12" (Go to Definition) action. Should I use the same logic I currently use for the quick open (leads to code duplication, fetching settings again), or maybe push that very same logic to the code which gets called later on (one of the overrides of `openEditor` or another "low level" method which does not know where it's being called from), something third?

**Comment by bpasero** [comment]
@ddotlic wait a second, this issue asks about revealing a file if it is already opened when using quick open. Are you asking to expand this setting to possibly every place where an editor gets opened? If that is the intent then yes I agree the option does not make much sense to be carried around every time. 

So far I was assuming we only talk about using this from quick open.

**Comment by ddotlic** [comment]
@bpasero I am (of course 😉 ) talking about expanding it, [but so are you](#issuecomment-222631601) **and** the author of the issue confirms in the next comment 😃 

It's debatable of course but a few of us - you included - seem to agree that this should be the "global" setting - once set, should be used for all the actions opening a document.

**Comment by bpasero** [comment]
@ddotlic ah nice, was not aware I had this thought already. Yeah I am fine with a setting that controls this for any editor opening. In that case this should probably not be an editor option (if we want an option it should be the opposite: `forceOpenInGroup` or so in case the setting is set).

**Comment by ddotlic** [comment]
@bpasero  The _entire_ implementation is 10 lines long and is in the `editorPart.findPosition` method. 

Basically if the flag is set (whatever we call it and however we fetch it) the code tries to find an already open editor and returns its index, the rest is automatic.

There is the edge case of splitting the _only_ currently open editor where this likely won't work, but I'll debug that and figure it out.

Thanks!

**Comment by bpasero** [comment]
@ddotlic I think there are more edge cases, a user might want to explicitly open an editor to the side not just via split but also by right clicking on a file in the explorer and picking "open to side". I think in all cases where the `sideBySide` flag is set or an explicit position we need to respect that decision no matter what.

If you have something running, I suggest we continue in a Pull Request.

**Comment by ddotlic** [comment]
@bpasero Exactly, as soon as make sure it's working for more than quick open, we'll continue in the PR.

**Comment by ddotlic** [comment]
@bpasero The PR is ready, let's continue there. This feels awesome ☺️

**Comment by bpasero** [comment]
Thanks to @ddotlic there is a new option `"workbench.editor.revealIfOpen"`:

> Controls if an editor is revealed in any of the visible groups if opened. If disabled, an editor will prefer to open in the currently active editor group. If enabled, an already opened editor will be revealed instead of opened again in the currently active editor group. Note that there are some cases where this setting is ignored, e.g. when forcing an editor to open in a specific group or to the side of the currently active group.

**Comment by bpasero** [comment]
**Verify:**
* the new setting workbench.editor.revealIfOpen works and behaves as [advertised](https://github.com/Microsoft/vscode/issues/7049#issuecomment-284673008)

**Comment by stefcameron** [comment]
@bpasero This is a great new option, and one which I had been wanting, however I'd like to give some feedback on it.

I like this option, and I've enabled it, because I like that when I double-click on a file in the Explorer panel to open it, it now reveals it to me if it was already open (since tabs easily get hidden because they don't shrink to fit in the horizontal width of an editor -- something I'd also like to have and have suggested :)). Prior, I'd end-up unnecessarily having multiple editors open to the same file, especially when just single-clicking to preview the file. That was annoying, and it's now fixed. Yay!

What I don't like about this option is that `Ctrl+P` respects it and reveals the file to me instead of opening another instance when I'm in an editor group in which the file is not already open. I do this because I'm wanting to open a second view onto the same file (normally when it's a long file I need to edit at two places or edit at one place and refer to another). This was the behavior in Sublime.

Apparently, this option isn't respected when forcing an editor to open in a specific group or to the side of the active group. This sounds like a workaround for me, but I don't know how to do this other than by splitting the active editor with `Ctrl+\`. The problem with that is that I always work with a 3x1 layout (3 vertical editor groups) on a large monitor and editor splitting stops working once you have 3 groups...

I see two possible solutions:
1. Make the `workbench.editor.revealIfOpen` option a string instead of a boolean, and give it a third option to be ignored by `Ctrl+P`.
2. (My personal preference) Always allow splitting an editor. If the maximum number of groups allowed (3 at the moment; should be configurable IMO) has __not__ been reached, then split into a new group to the right. Otherwise (max __has__ been reached), split into the existing group to the right or, if in the last group, split into the existing group to the left.

**Comment by bpasero** [comment]
Understood. Though at some point I think we should stop adding more and more options for specific behaviour and just enable extensions to do this.

**Comment by stefcameron** [comment]
That's another solution, I suppose.

So I take it then that there really is no way to force-split an editor
other than with `Ctrl+\` which is tied to the layout and capped at 3 groups?

Thinking about it some more, why should the ability to split an editor be
tied to the layout? Perhaps layout should be kept separate from the editor
splitting functionality. Split the editor into a new group if one can be
created (per layout rules), otherwise re-use the next editor to the right
or left as configured (expect that someone will want it to split to the
left rather than the right... ;).

**Comment by stefcameron** [comment]
@bpasero I'm still struggling with this setting. I want it, but when it's active, I don't totally love it. As I explained earlier, I feel this setting needs to be a string with a few more behavioral modes than true/false.

But, the documentation for `workbench.editor.revealIfOpen` says that it's not respected in a couple of cases, such as "forcing an editor to open in a specific group" -- how do you do that? I only know of splitting an editor (and I've explained here why __that doesn't always work__).

Is there another way to say, "Hey, VSCode, when you open this file, open it in editor group 2 even if the file is currently open in group 1?" What's the command?

**Comment by bpasero** [comment]
@stefcameron that does not exist currently, but things like Ctrl+click will make it open "to the side" of the active editor. Same as the explicit action next to a quick open entry to open it to the side.

**Comment by stefcameron** [comment]
@bpasero Thanks! I didn't know about ctrl/cmd+click to "open to the side". That's a good enough workaround for me so I can enjoy the benefits of `workbench.editor.revealIfOpen = true`. :)

**Comment by myfairsyer** [comment]
What concerns `Ctrl+P` always opening the file in a new editor if **`Shift`** is being pressed might be an option.

It's the modifier used for links in browsers _(new window instead of the existing one)_ and e. g. in the Windows Taskbar _(new instance instead of opening the existing one)_
