### ISSUE TITLE
Cannot install a previous version when another extension depends on it

### ISSUE THREAD

**Issue by luabud** [Microsoft/vscode#70500]
I tried installing a previous version of the Python extension and I got this:

![image](https://user-images.githubusercontent.com/45497113/54374226-ea558a00-463b-11e9-82de-75cfc00da641.png)

Checking the Developer Tools console I got a more detailed message of the reason why:

![image](https://user-images.githubusercontent.com/45497113/54374204-e0338b80-463b-11e9-94c1-47aa0ce41cb3.png)

Could this be displayed in the prompt as well so we have more information of why the extension installation has failed?

**Comment by sandy081** [comment]
@luabud This error message should never appear. Installing a previous version should work even though another extension depends on it. Because you are not uninstalling it.

Fixed it.

To verify:

- Install Azure Cosmos DB extension which installs Azure account extension
- Try to install previous version of Azure account extension
- Make sure there is no error

**Comment by roblourens** [comment]
I guess you could end up with an incompatible version of the dependency, because we don't specify extension versions, because we expect people to use the latest versions normally. I guess if you are picking versions manually, you know what you're doing.
