### ISSUE TITLE
Always said the file is being used via update

### ISSUE THREAD

**Issue by Triple-Z** [Microsoft/vscode#70545]
- VSCode Version: 1.32.2 (user setup)
- OS Version: Windows 10 17134

Steps to Reproduce:

1. Close VS Code
2. Waiting for the updater

Does this issue occur when all extensions are disabled?: Yes

Here are the logs:
[vscode-inno-updater-1552634929.log](https://github.com/Microsoft/vscode/files/2969889/vscode-inno-updater-1552634929.log)

**Comment by Cirieno** [comment]
I have the same issue (also had it yesterday with 1.32.2) -- resolved it yesterday by downloading the full package instead of using the built-in installer.  Resolved it today by doing a hard exit (file > exit) rather than hot exit [X].

Does this issue occur when all extensions are disabled?: Yes

[1 __ vscode-inno-updater-1552642674.log](https://github.com/Microsoft/vscode/files/2970408/1.__.vscode-inno-updater-1552642674.log)
[2 __ vscode-inno-updater-1552643235.log](https://github.com/Microsoft/vscode/files/2970407/2.__.vscode-inno-updater-1552643235.log)

Additional: while the built-in installer waiting to install (notification message to restart VSCode) or is running (trying to install), I lose a lot of interaction with my desktop: mouse still moves but can't click every time, windows become unresponsive (titlebar message "not responding"), keyboard doesn't type or types sporadically.  Might be coincidental, might not.  Takes a minute or two for full 100% responsiveness to return.  This is also only since yesterday.

**Comment by joaomoreno** [comment]
Please switch to the system install, if the user install doesn't work for you: https://code.visualstudio.com/docs/?dv=win64

**Comment by Cirieno** [comment]
Wow.  Closing this issues as a "works for me"?  That's a low response.
As you didn't clarify which post you are responding to, I'm going to focus on mine.

1) I am using the system installer.  Which leads me to think you didn't look at my logs -- because "C:\Program Files\Microsoft VS Code" = system installer. 

2) If there is a feature that suddenly, as of one minor-point-revision, stops working, maybe that's an issue with the feature; I've been using for over a year now with no issue.

3) "ERRO Failed to mark file for deletion: Access is denied"  <- why not actually tell us in the log WHICH file was locked, anyway?  That could help us figure out why a file is locked and what might be keeping it open.

4) Not sure why you felt it was necessary to add the links, just in case we weren't capable of finding them on the VSCode site ourselves.  Maybe you were being nice, or maybe this is just a cut-n-paste answer...
