### ISSUE TITLE
Highlight breakpoint on the left side of the line number when user hover over the right side

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#70597]
During a user study, most participants tried adding a break point to the right side of the line number instead of the left side, and it took some time for them to figure out they were supposed to do it on the left side. To improve discoverability, it'd be nice if the break point on the left could be highlighted when users hover over the right side of the line number:
![image](https://user-images.githubusercontent.com/45497113/54468262-01819e00-4748-11e9-9f05-1b6eddfde796.png)

**Comment by isidorn** [comment]
@luabud  Sorry for the slow response this smowhow fall through my radar
This makes sense. However in that area we have other widgets - like the folding collapse / expando.
Thus people would see the breakpoint even if they want to click on folding or to click on line numbers (in order to select the line)

However I think it might be fine to show the breakpoint hint when the user hovers over the line number.
I will bring it up in our UX discussion tomorrow and if the team thinks it is a good idea I will change this.

**Comment by isidorn** [comment]
Fixed via a97e8c31d7
We decided to try it out insiders for a couple of days and if we like we will keep it. Thanks

**Comment by isidorn** [comment]
Verifyer: verify that you get breakpoint hints in the glyph margin when you aslo hover over the line numbers.
