### ISSUE TITLE
Setting default language to "plaintext" should suggest .txt extension

### ISSUE THREAD

**Issue by flow2k** [microsoft/vscode#70632]
In reference to https://github.com/Microsoft/vscode/issues/70523: it appears setting "files.defaultLanguage": "txt" should save new files with .txt extension, but I did not get the expected the behavior: the new file is saved without an extension.

Version: 1.32.3

**Comment by bpasero** [comment]
This is a corner case when setting `"files.defaultLanguage": "plaintext"` only, it works fine with any other language. The reason is that plain text is the default language for untitled files by definition and when saving an untitled file we never suggest the txt file extension.

We could change this, e.g. by checking if the setting is configured explicitly but it may result in an experience that is confusing for the user. Because sometimes we seem to add the extension and sometimes we do not.

**Comment by flow2k** [comment]
I agree that sometimes we need to save files without an extension (e.g., Makefile). But I often write and save plain text notes; without an extension, these notes wouldn't get opened by vscode by default when I try to open them later. 

Perhaps we can add another config that lets the user decide if they want a default extension or not. I believe this is the approach taken by Sublime and Atom.
