### ISSUE TITLE
Markdown extension: Preview display performance

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#7066]
For #6106:

A typical markdown editing flow is to rapidly switch back and forth between source and preview. 

Comparing the built-in markdown preview with the extension, the extension has a perceivable lag when displaying the preview.  We need to get back to the level of performance of the built-in editor.

**Comment by jrieken** [comment]
Problem is that the `update`-logic is only triggered on document _save_ events, not on document _change_ [events](https://github.com/Microsoft/vscode/blob/kieferrm/markdown/src/vs/vscode.d.ts#L3475). Also but smallish is an extra fs-[read](https://github.com/Microsoft/vscode/blob/kieferrm/markdown/extensions/markdown/src/extension.ts#L139), instead of using the value form the TextDocument.

**Comment by kieferrm** [comment]
Summarizing offline discussions:
The issue here is the perceived lag when the webview is created. It takes on average 250ms.

**Comment by kieferrm** [comment]
No planned activity.
