### ISSUE TITLE
Markdown extension / webview: Focus border  

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#7067]
1. Using the markdown extension (#6106) open a preview of a markdown file
1. Open command pallet
1. Close pallet by clicking into  the preview
-> focus border

![7rry5cydg1](https://cloud.githubusercontent.com/assets/4674940/15682018/8e68ab16-2710-11e6-8943-2778dda14ee5.gif)

I haven't found a styling yet that solves the issue.

**Comment by bpasero** [comment]
When quick open is closing it calls the focus() method of the active editor. It is up to the implementor of the editor (in this case the htmlPreviewPart) to do something then. We seem to call focus() on the <webview> and this brings up the native outline. 

If we add a rule to our shell.css (in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/media/shell.css#L174) to have no outline for webviews, this issue is fixed.

**Comment by jrieken** [comment]
This fix should go in the previewPart

**Comment by kieferrm** [comment]
The change is not working since the outline style is not applied to the webview but to the body of the displayed document(s).
