### ISSUE TITLE
[Feature Request] - Extension Dating & Timestamps of last updates.

### ISSUE THREAD

**Issue by SirTwsted** [microsoft/vscode#70736]
I would like to see on every extension ever created (2) things
1. - Data it was created
2. - Data of last update

I believe people should know if a extension has not been updated for a very long time.
or if it was recently updated. Also people should know when the extension was first created.
It just basically keeps people informed.

**Comment by sandy081** [comment]
Related to https://github.com/Microsoft/vscode/issues/70736

**Comment by Daijobou** [comment]
For me only "Data of last update" is of interest in overview of "@installed"-extensions, because I have a extension that not working properly, which working _years_ correctly and get no updates for months. So here must be a conflict with vscode or a extension that was silent updated? It would help to identify which extension is responsible for this issue, instead of disable all extension and enable each one by one again.
