### ISSUE TITLE
Folder settings are copied into workspace settings when creating a new workspace

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#70787]
- Open vscode or another folder with settings.json as a normal folder
- "Duplicate workspace in new window" to promote it to a workspace
- "Save workspace as" - some name
- "Open workspace configuration file" to see workspace settings json

The workspace file "settings" section has all of vscode's settings copied into it. Is this supposed to happen? This is confusing to me.

**Comment by sandy081** [comment]
@isidorn introduced this action.

**Comment by isidorn** [comment]
This is by design and as people expect it to behave. Since duplicate worksapce is a workaround that we can not open the same folder in multiple windows. As a workaround it should behave as close as to the desigred behavior, user having the same experience in both places - thus we copy settings.
I understand how you can find this confusing, however this action is out for a year and this is the first time somebody found it strange.

I can leave it open as a discussion item and we wait and see if we get more feedback like this.

Code pointer https://github.com/Microsoft/vscode/blob/2c386fa9a35d3830147c0154feadb7d53b45e2e6/src/vs/workbench/browser/actions/workspaceActions.ts#L246

**Comment by roblourens** [comment]
I never looked closely at it before but I guess I see that you might have some settings which can be workspace settings but not folder settings, and then you want to copy them into the new workspace so they still apply.
