### ISSUE TITLE
Windows+V clipboard history cannot be accessed in the Terminal window (e. g. during 

### ISSUE THREAD

**Issue by MikeBazMSFT** [microsoft/vscode#70823]
- VSCode Version: 1.32.3 (user setup) (also on 1.33.0-Insider)
- OS Version: Windows 10 1809

Steps to Reproduce:

1. In OS `Settings` -> `Clipboard`, ensure `Clipboard history` is enabled.
2. Copy several things to the clipboard.
3. Open `Notepad` (this is a validation step.)
4. Press `Windows+V` and notice you get a clipboard history.
5. Close `Notepad`
6. Open `Visual Studio Code`.
7. Create a `Terminal`
8. In the `Terminal`, press `Windows+V` and notice the clipboard history is unavailable.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
It actually works fine for me, just the window doesn't popup in the right spot:

![image](https://user-images.githubusercontent.com/2193314/54869242-f5eb3400-4d52-11e9-8fbc-df2bdd516bda.png)

I think however the only reason we position the textarea off screen is because of IE which we want to drop support for in the terminal component.

**Comment by MikeBazMSFT** [comment]
You're right, it is working, off in an unexpected part of a different monitor.  I didn't even see it over there, but I just tried it again and sure enough...
