### ISSUE TITLE
Create a replacement communication service for EH debugging 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#70835]
see #70831

**Comment by bpasero** [comment]
The messages are:
* `vscode:extensionLog`
* `vscode:extensionCloseExtensionHost`
* `vscode:extensionReload`
* `vscode:extensionAttach`
* `vscode:extensionTerminate`

(in `src/vs/platform/extensions/common/extensionHost.ts` which then maybe also should go away)

**Comment by isidorn** [comment]
Yeah, thanks. I will get rid of that file.

**Comment by isidorn** [comment]
I have introduce the `ExtensionHostDebugService`.
IMHO now the communication is much nicer and has more type safety.

@jrieken @bpasero @weinand feedback welcome

**Comment by bpasero** [comment]
@isidorn can you move that code into `workbench/contrib/debug`? `workbench/services` should be used for things that are used by the core workbench and debug seems like it only exists as a contribution to the workbench.

**Comment by isidorn** [comment]
Makes sense, @weinand gave the same feedback.
Let me move it.

**Comment by isidorn** [comment]
@bpasero acutally I can not move it. Since the [extensionHost.ts](https://github.com/Microsoft/vscode/blob/1c25c797b9e69618d6cce4615bc6b6afb4fe20b0/src/vs/workbench/services/extensions/electron-browser/extensionHost.ts#L37) depends on it. And from there I can not depend on `vs/workbench/contrib/`. I get a import violates warning.

**Comment by bpasero** [comment]
Yeah true. I moved it into the `services/extensions` folder at least.

**Comment by isidorn** [comment]
Ok, thanks.
