### ISSUE TITLE
Open applicationHost.config with code, the file appears to be empty, even if it is not

### ISSUE THREAD

**Issue by npandrei** [Microsoft/vscode#7088]
- VSCode Version: 1.1.1
- OS Version: Windows 8.1

Steps to Reproduce:
1. Navigate to path C:\Windows\System32\inetsrv\config
2. opening config folder will ask for your permission, give it
3. open applicationHost.config
4. in Code, the file looks to be empty, event if it is not. opening it with Notepad++ works.
5. Running code as administrator + drag & drop the file gives and error "the path ... does not seem to exist anymore on disk"
6. I tried using Visual Studio 2015 Update 2 to open it, but I cannot. It does not appear in "Open File Dialog"

**Comment by bpasero** [comment]
@npandrei can you try to read the file using node.js to see if that returns empty already?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Comment by garfbradaz** [comment]
Hey Guys.

Same for me:

VSCode: 1.9.1
OS: Windows 10 Enterprise N

Steps to reproduce file NOT opening:

1. GIve your username full control of  C:\Windows\System32\inetsrv\config, so that you can open the file. VSCode will advise you dont have permissions to save it otherwise.
2. Navigate to path C:\Windows\System32\inetsrv\config (Make sure IIS is installed using **Add Feature**)
3. opening config folder will ask for your permission, give it
4. open applicationHost.config in Code, the file looks to be empty.
5. Open it in Notepad and it does contain the xml in question.

**VSCode Snippet:**
![image](https://cloud.githubusercontent.com/assets/959766/23115146/e61da30c-f73a-11e6-98e0-24c5f32e178b.png)

**Notepad Snippet:**
![image](https://cloud.githubusercontent.com/assets/959766/23115172/0ac2fc5c-f73b-11e6-9be5-174d67baabb7.png)

**Now if i copy the file to my desktop and open it, VSCode WILL open it**.
[applicationHost.txt](https://github.com/Microsoft/vscode/files/786763/applicationHost.txt)


Included a version of the file here as well but renamed it .TXT for github to allow it.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by dariusj18** [comment]
I just read about this: Windows SYSWOW32 redirection

https://forums.iis.net/t/1160210.aspx?missing+applicationhost+config

This may be why code can't see this file

**Comment by bpasero** [comment]
ack, https://github.com/Microsoft/vscode/issues/7611
