### ISSUE TITLE
run all tasks with `isBuildCommand` flag set on build (all isTestCommand on test)

### ISSUE THREAD

**Issue by aleksey-bykov** [Microsoft/vscode#7091]
- VSCode Version:   1.1.1

Currently the first task with the `isBuildCommand: true` is run as the build command regardless of other tasks with the same flag. It would be a great help if all of them are run in the order of declaration.

**Comment by Ne-Ne** [comment]
This would be a great feature, you could bind typescript & sass as part of the build process rather than hooking up everything into a singular `npm run script`.

**Comment by dbaeumer** [comment]
This got addressed by the dependsOn feature for task 2.0.0. It provides the possibility to create a new task which dependsOn other tasks. So you can selectively list the task you want to run using one entry point. 

Running all isBuild task needs some UI customization as well since this can't be the default.
