### ISSUE TITLE
Sort lines correct alphabetic sorting with diacritics in Romanian

### ISSUE THREAD

**Issue by akaleeroy** [microsoft/vscode#70920]
Issue Type: <b>Bug</b>

The correct order when it comes to Romanian diacritics would be **a, ă, â, b, c ... i, î ... s, ș, t, ț, u, v ...**

[Alphabetical order - Wikipedia](https://en.wikipedia.org/wiki/Alphabetical_order)

But this is the result of **Sort Lines Ascending** on these lines:

```
Sălaj
Satu Mare
Sibiu
Suceava
```

`Sălaj` should come after `Satu Mare`

FWIW Sublime Text gets it worse, considering diacritics as continuing after the main latin alphabet: `Sălaj` comes after `Suceava`

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 6.1.7601

**Comment by akaleeroy** [comment]
On the other hand it matches up with the sorting from LibreOffice Calc.

**Comment by isidorn** [comment]
Sorting where? Are you talking about the explorer?

**Comment by akaleeroy** [comment]
**Sort Lines Ascending** in the Command Palette.

**Comment by alexandrudima** [comment]
This is actually more complicated than I thought... 

The reason is that different locales have different sort orders for the same characters. See a full example at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator

```js
function letterSort(lang, letters) {
  letters.sort(new Intl.Collator(lang).compare);
  return letters;
}

console.log(letterSort('de', ['a','z','ä']));
// expected output: Array ["a", "ä", "z"]

console.log(letterSort('sv', ['a','z','ä']));
// expected output: Array ["a", "z", "ä"]
```

So there is no absolute order of letters, ordering letters/strings only makes sense in a given locale. We are currently using `String.localeCompare`. I believe that one falls to the locale defined in the OS, and on your machine I think that is English.

Testing the sorting:
```
function sort(lang, letters) {
  letters.sort(new Intl.Collator(lang).compare);
  return letters;
}

console.log(sort('en', ["Satu Mare", "Sălaj", "Sibiu", "Suceava"]));
// ==> ["Sălaj", "Satu Mare", "Sibiu", "Suceava"]

console.log(sort('ro', ["Satu Mare", "Sălaj", "Sibiu", "Suceava"]));
// ==> ["Satu Mare", "Sălaj", "Sibiu", "Suceava"]
```

So under English the sort order is indeed `["Sălaj", "Satu Mare", "Sibiu", "Suceava"]`, while under Romanian it is `["Satu Mare", "Sălaj", "Sibiu", "Suceava"]`

I will change our code to instantiate a `Intl.Collator`, which is better than `String.localeCompare` from a performance point of view according to what I learned from MDN, but I think the only way to get the sort order you want is to change your OS locale to Romanian.
