### ISSUE TITLE
Add queuing to dialog service

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#70979]
Currently, multiple dialogs may be requested at once. We should queue them.

**Comment by bpasero** [comment]
Queueing is already happening per window here: 

https://github.com/microsoft/vscode/blob/878bf135043770f5e2270378b2376bc5e3f8deac/src/vs/platform/dialogs/electron-main/dialogMainService.ts#L126-L138

As mentioned in https://github.com/microsoft/vscode/pull/114450, I think instead of queueing we should simply ignore dialog requests when a dialog is opened per window.
