### ISSUE TITLE
Single dot accept completion and re-trigger completion

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#70974]
Version: 1.33.0-insider
Commit: 9474154f133dbbb793ca3c128c9fcfdca39f5b26
Date: 2019-03-22T06:15:30.293Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Darwin x64 18.2.0

Started to happen since 2 versions ago.

From the rough look of it, if when I type `.` before screen finishing updating `this`, it seems to accept the first completion item.

![fast-type](https://user-images.githubusercontent.com/4033249/54843388-75b0ca00-4c91-11e9-98ab-cf22c16b66fb.gif)

If I disable all extensions (including Vim, which hijacks to the `type` command and makes typing slower), this can still happen, although I need to type `this.` way faster:

![normal](https://user-images.githubusercontent.com/4033249/54843585-f53e9900-4c91-11e9-95ba-f02292dc0c39.gif)

**Comment by jrieken** [comment]
The `.` character is an auto-accept character - that means when pressed it accepts the current suggestions _and_ inserts that character. Last, if the character itself is a trigger character, suggestion is re-triggered. 

What has changed might be the defaults or the set of those character - @mjbvz knows for sure but I think that auto accept characters have become more prominent in recent versions. 

Technically everything is correct but it seems that the suggest logic is faster than the editor and list rendering, e.g. everything is sorted, filtered, and accepted before showing any list or text. 

I am not sure what to do here. Personally I have disabled auto-accept characters because of this. It might be extra-weird because TypeScript suggests `this.capabilities` when typing `t`, e.g. it suggests one level deeper than usual.

**Comment by jrieken** [comment]
I have created https://github.com/microsoft/vscode/issues/74054 to spell out what different variants of IntelliSense exists and what language used what by default. 

Having fixed https://github.com/microsoft/vscode/issues/71795 should help with this issue (what typing fast) but what I think is still missing is a better representation of filter text. The problem is that extensions can provide two values: `label` and `filterText`. The former is what you see in the UI, the latter is what scoring works with. By its nature that isn't as self-describing because highlights are often  hard to understand:

<img width="759" alt="Screenshot 2019-05-21 at 12 54 35" src="https://user-images.githubusercontent.com/1794099/58090474-992bbe80-7bc7-11e9-9689-a3066a0936e8.png">

The highlights in the screen shot above are weird because the filter text is actually `this.capabilities`, `this.cleanPendingValidation`, `this.configure` etc. Those strings are used to filter and the highlights are added later, [best-guess based](https://github.com/Microsoft/vscode/blob/df08d729c69fa5640d5ea1966fd3abfc30a333ed/src/vs/editor/contrib/suggest/completionModel.ts#L210-L218). We might be better off not showing highlights at all?

**Comment by jrieken** [comment]
I have pushed a change to reduce the highlight confusion, e.g. we show more often no highlights but iff those that make sense. 

Everything else is working as designed - suggest as you type, accept as you type, (re-)trigger as you type

**Comment by mjbvz** [comment]
I believe that changing the label would mess up the match highlighting since the user is only typing `capabilities`. As a bad example, imagine a property named `thi`. If the user has typed out `thi` in this example, we would not want to highlight: 

```
this.thi
___
```
