### ISSUE TITLE
crtl+mouseUp or ctrl+mouseDown text size

### ISSUE THREAD

**Issue by jkrth617** [Microsoft/vscode#7098]
- VSCode Version: 1.1.1
- OS Version: windows 10

Steps to Reproduce: N/A

Right now there is no binding to the crtl+mouseWheel is VS and in a lot of tools that combination would increase the text size. I understand there is a crtl+= and crtl+- which zooms in but that zooms everything in including the panel on the left. It would be nice to have a shortcut to just increase the font size

**Comment by coreh** [comment]
A couple other issues:

- I also think ctlr+= and ctrl+- (or ⌘=, ⌘-)should not zoom the entire interface, if possible. It's not as useful as zooming the document (except as maybe an accessibility setting).

- There's no ctrl+0 (or ⌘0) to restore zoom to the normal level

- Pinch to zoom (at least on OS X) actually _scrolls_ the editor view, instead of zooming in/out

**Comment by spywhere** [comment]
I think this issue is kind of a dup of #6978

**Comment by Tyriar** [comment]
Thanks @spywhere, closing as dupe
