### ISSUE TITLE
Please provide written reviews, not just scores

### ISSUE THREAD

**Issue by Cloudmersive** [Microsoft/vscode#71014]
Issue Type: <b>Feature Request</b>

Right now when you look at an extension, there is only a ratings number.  It doesn't say how many reviews, who wrote them, or what they said.  Not very useful

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

**Comment by SirTwsted** [comment]
**I agree.**
Also there should be dates for When the extension was made (and) When was the last time the extension was update.
Also,
The extensions list an overhaul clean up.  Because there are so many "[Obsolete]" extensions,
and many other extensions that are really old and legacy.
Someone needs to do some serious cleaning for the extensions library.
A lot of extensions in the library have cob webs and they need to be either trashed or cleaned.

**Comment by sandy081** [comment]
@Cloudmersive You can open reviews by

- Open the extensions editor
- Clicking on the ratings 

This will take you to market place to show the reviews. There are no plans to provide it inside vs code.
