### ISSUE TITLE
View > Toggle Output, Debug Console and Integrated Terminal are missing on alpha

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#7101]
- VSCode Version:1.2.0-alpha
- OS Version:Windows 7

Steps to Reproduce:

1. Open the View menu
2. The block with Toggle Output, Toggle Debug Console and Toggle Integrated Terminal are missing.

Might be due to refactoring with https://github.com/Microsoft/vscode/commit/207a8e33145c09aaeaa99e44ee7599a4112cfbd4#diff-cfab7992ca96cfc46d55c980e3225116

**Comment by bpasero** [comment]
They are there I just grouped them because the list of entries in that menu is getting very large.

![screen shot 2016-06-01 at 19 02 53](https://cloud.githubusercontent.com/assets/900690/15718414/7872a1c4-282b-11e6-967a-9bbfa8460ed9.png)

/cc @sandy081 you might want to put your problems and errors also under the panel category once you push to master.

**Comment by bpasero** [comment]
1.
