### ISSUE TITLE
Support to debug more than one extension

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#71081]
Today VS Code only supports to debug a single extension.

But for developing features that span multiple extensions it would be helpful if VS Code could support that OOTB.

**Comment by connorshea** [comment]
I've got a problem that I think this feature solves, but I wanted to ask about a specific edge-case I'm running into.

Essentially, I've created a [Ruby Test Explorer](https://marketplace.visualstudio.com/items?itemName=connorshea.vscode-ruby-test-adapter) and it relies on the [Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer) extension to function. I'd like to be able to test my extension with the Test Explorer UI extension, but without any of the other extensions I have, since it causes VS Code to take longer to boot. Unfortunately it doesn't seem like this is really possible right now even with this feature, because both extensions need to be in the local workspace.

I guess the recommendation for now would be to have a local copy of the Test Explorer UI extension and use this feature to debug them both at the same time after disabling all other extensions?

e.g. like this:

```jsonc
"args": [
  "--disable-extensions",
  "--extensionDevelopmentPath=${workspaceFolder:vscode-ruby-test-adapter}"
  "--extensionDevelopmentPath=${workspaceFolder:vscode-test-explorer}"
],
```

Should I open a new issue about being able to use an extension from the marketplace while disabling all others? I imagine this'd also be useful for anyone trying to debug their extension with a closed source extension like Live Share or the VS Code Remote extensions.

Apologies if this is the wrong place to ask this, and thanks for this feature! It seems to have come up at the perfect time for me :)
