### ISSUE TITLE
Activity monitor show extension name instead of codehelper

### ISSUE THREAD

**Issue by jasonbronson** [Microsoft/vscode#71082]
It would be nice to know which item in the activity monitor is using what resources rather than just the name codehelper. It really helps narrow down issues with extensions.

MAC OSX

**Comment by weinand** [comment]
the "codehelper" is just a runtime (Electron's version of node.js) that is used for different purposes. We already pass a "type" argument to the generic tool so that it identifies itself in process lists.
But macOS "activity monitor" does not show arguments. If you use "htop" you will see the type argument and you will better understand the role of the "codehelper". Other that that we cannot do anything here.
