### ISSUE TITLE
Spurious Chinese Characters VS Code Python Extension

### ISSUE THREAD

**Issue by vijaykarthik123** [Microsoft/vscode#71110]
I have this issue of some spurious Chinese characters when I right click in my workspace and when I look at the options in the command palette. I tried changing the different encoding schemes and it didn't resolve this issue. I have even uninstalled and reinstalled VS Code altogether and it still persists. I have attached the screenshot.

Thanks in advance for the help!
![vscode_complaint1](https://user-images.githubusercontent.com/35940346/54952683-c2034080-4f03-11e9-8764-9a0275e5ac76.jpg)

**Comment by vijaykarthik123** [comment]
A little more info on this. The issue seems to be in the C/C++ extension as well. I have attached both the screenshots. Is the solution to this - playing the "change the encoding scheme" roulette?
![image](https://user-images.githubusercontent.com/35940346/54963588-8332b200-4f26-11e9-8c65-d4b9ad381dc3.png)
![image](https://user-images.githubusercontent.com/35940346/54963682-d99ff080-4f26-11e9-839e-521370abbdbf.png)

**Comment by dbaeumer** [comment]
@vijaykarthik123 Is your system locale Chinese or did you evey switched the VS Code UI to Chinise. To check please run `Configure Display Lanaguge` and look at the content of the `locale.json` file. If so this is a dup of https://github.com/Microsoft/vscode/issues/62623.

Otherwise can you please provide more details about your system and our locale and the language packs installed.

**Comment by vijaykarthik123** [comment]
Thank you! It helped. I had to change the locale field to "en" in the locale.json file and restarted the Software. It changed to English. It requires a restart of VS Code, just Reload didn't suffice.
