### ISSUE TITLE
Message after installing: "Unable to write program user data: please make sure the directory .../Code is writeable"

### ISSUE THREAD

**Issue by Jure34** [Microsoft/vscode#71114]
- VSCode Version: 1.32.3
- OS Version: macOS 10.14

Steps to Reproduce:

1. Install application
2. After install and every attempt to launch, the error message is displayed.

Also, in another one of my admin accounts, it successfully installed. It's not installing on the root account

I'm very new to programming, so any help would be very much so appreciated. I also saw a prior issue in relation to this, but this was closed and the issue didn't seem to be resolved.

_Edit:_ I made sure that my user had read/write permissions for the folder in get info

**Comment by bpasero** [comment]
This sounds like a configuration issue with your machine, not an issue with VSCode. We show this message when we cannot write into the user data directory and terminate if we cannot because then VSCode can also not run. You can maybe try to point to a different folder that is writeable via the `--user-data-dir <dir>` command line.

**Comment by Jure34** [comment]
I ended up contacting apple, they had to reset permissions to my home folder among a few other things....

Thank you
