### ISSUE TITLE
regression in insiders: VSCode calls stat() on FileSystemProvider before it creates a directory

### ISSUE THREAD

**Issue by IlyaBiryukov** [Microsoft/vscode#71118]
- VSCode Version: 1.33

This is a regression in VSCode Insiders 1.33

*Repro steps:*
1. Extension registers a `vscode.FileSystemProvider` for some scheme
1. User opens a workspace with this scheme
1. User tries to create folder in Explorer in that workspace

*Expected:*
VSCode calls 'createDirectory' on the `vscode.FileSystemProvider` to create the folder. This is what it does in the stable release.

*Actual:*
VSCode calls `stat` on the file system provider for the folder being created. Since the folder is not there yet, it throws `vscode.FileSystemError.FileNotFound`. Then VSCode displays "Path not found: /path_to_the_folder" error.
It doesn't call 'createDirectory' on the `vscode.FileSystemProvider`.

*Call stack*
fileError (c:\src\cascade\vscode\extension\src\workspace\workspaceProvider2.ts:484)
stat (c:\src\cascade\vscode\extension\src\workspace\workspaceProvider2.ts:173)
[ async function ] (Unknown Source:undefined)
stat (c:\src\cascade\vscode\extension\src\workspace\workspaceProvider2.ts:142)
$stat (extHostFileSystem.ts:225)
_doInvokeHandler (rpcProtocol.ts:399)
_invokeHandler (rpcProtocol.ts:384)
_receiveRequest (rpcProtocol.ts:304)
_receiveOneMessage (rpcProtocol.ts:226)
define.constructor._protocol.onMessage.e (rpcProtocol.ts:101)
fire (event.ts:584)
e (event.ts:74)
fire (event.ts:584)
s (ipc.net.ts:389)
e (ipc.net.ts:396)
fire (event.ts:584)
_receiveMessage (ipc.net.ts:671)
define.constructor._socketDisposables.push._socketReader.onMessage.e (ipc.net.ts:542)
fire (event.ts:584)
acceptChunk (ipc.net.ts:209)

**Comment by bpasero** [comment]
@IlyaBiryukov sorry for that. I pushed a fix and will start new insider builds. The issue here was that I was not forwarding file system errors properly from an extension. Can you please verify that you are throwing a `FileNotFound` error from the `FileSystemProvider.stat()` method? As you can see [here](https://github.com/Microsoft/vscode/blob/d0211faa28587c10ee8f16f2925fd067db86d601/src/vs/workbench/services/files2/common/fileService2.ts#L539) in our method that creates directories we now bubble up any error to the outside that we do not expect. In other words, we require a file not found error to actually create the folder.

As you might have seen already, I was refactoring the file service this milestone. This impacts most file service methods (such as createFolder, stat, create/move) but not (yet) reading/writing files or file watching (will work on that next month). 

We are in endgame this week and I have a test plan item with 3 testers assigned to verify these changes, but feel free to assign me to issues directly if you encounter more things.

**Comment by bpasero** [comment]
PS: one benefit of the work I did is that these things now work correctly for you:
* move/copy of binary files across different file system providers
* recursive copy of folders across and within providers

**Comment by IlyaBiryukov** [comment]
@bpasero When could we expect Insiders build with your fix to verify it on our side?

Here is the code that creates the error in `stat()` method in our `vscode.FileSystemProvider` implementation. I'm pretty sure it is `FileNotFound` with a custom error message.
```typescript
    private static fileError(error: FileError, uri?: vscode.Uri) {
        let message;

        switch (error) {
            case FileError.FileNotFound:
                message = localize('fileError.FileNotFound', 'Path not found: $(path)');                    
                break;
            case FileError.FileExists:
                message = localize('fileError.FileExists', 'Path already exists: $(path)');                    
                break;
            case FileError.NoPermissions:
                message = localize('fileError.NoPermissions', 'Access denied: $(path)');                    
                break;
            default:
                message = '';
        }

        message = message || `Error (${error}): ${uri.path}`;
        if (uri) {
            message = message.replace('$(path)', uri.path);
        }

        const errorFunction: (message: string) => vscode.FileSystemError =
            vscode.FileSystemError[error];
        return errorFunction ? errorFunction(message) : new Error(message);
    }
```

I debugged through it and `errorFunction` was `FileSystemError.FileNotFound()`.

**Comment by bpasero** [comment]
@IlyaBiryukov the latest insiders version includes the fix, can you check?

If you are creating file system errors, you should check our helper methods for well known file errors, e.g. [`FileSystemError.FileNotFound()`](https://github.com/Microsoft/vscode/blob/c1c1f2b2af216c52e3d5f290ea1a145bb8032740/src/vs/vscode.d.ts#L5512). That one will ensure it gets the right properties so that the main side can identify this error again.

**Comment by bpasero** [comment]
Marking as verified based on feedback from @IlyaBiryukov
