### ISSUE TITLE
Call Hierarchy: double click on twistie should not go to reference

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#71142]
Refs: #71083

When you quickly toggle a twistie, it looks like the call is being opened in the editor. This makes it hard to use the twistie after all because sometimes you end up navigating without wanting to.

**Comment by jrieken** [comment]
@joaomoreno the tree shouldn't emit an dbl-click event when being configured to only expand on twisties

**Comment by DanTup** [comment]
@jrieken what's the status of call hierarchy? It's currently proposed but I couldn't find any obvious issue tracking feedback (though I did find a couple of open bugs like this one). Is it being actively progressed? I'm interested in implementing it, but it might not be worth it yet if it's not likely to ship for a while because of other priorities.

Thanks!

**Comment by jrieken** [comment]
@DanTup ➡️ https://github.com/microsoft/vscode/issues/70231

**Comment by DanTup** [comment]
@jrieken aha, thanks! Not sure how I missed that - good timing. I'll hold off anything until after those changes then 👍
