### ISSUE TITLE
jsonMain message bundle load failure

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#71144]
* open vscode
* open dev console, see error below, see that UI show error messages

<img width="686" alt="Screenshot 2019-03-26 at 10 49 13" src="https://user-images.githubusercontent.com/1794099/54987449-e9661600-4fb4-11e9-9a1a-da721bcfb9b5.png">

<img width="548" alt="Screenshot 2019-03-26 at 10 50 12" src="https://user-images.githubusercontent.com/1794099/54987466-f08d2400-4fb4-11e9-8f91-203e1c277ee5.png">

**Comment by aeschli** [comment]
@dbaeumer Any idea?

**Comment by jrieken** [comment]
fyi - I have been seeing this since a while (2wks?) but never got to file an issue

**Comment by dbaeumer** [comment]
@aeschli no, not out of the box. We would need to debug this. Is this web packed?

**Comment by aeschli** [comment]
Yes, web packed

**Comment by dbaeumer** [comment]
@jrieken no language pack installed and English UI. Right ?

**Comment by dbaeumer** [comment]
@aeschli  It looks like the jsonMain.js is missing its English strings. I guess they get somehow lost during the webpack process. The folder looks like this

![capture](https://user-images.githubusercontent.com/1931590/55067996-1253dd00-5081-11e9-9b3b-e763ee40895d.png)

whereas a correct folder looks like this:

![capture](https://user-images.githubusercontent.com/1931590/55068024-23045300-5081-11e9-91cf-20e15eac8601.png)

The two files `nls.metadata.json` and `nls.metadata.header.json` are necessary since they contain our English default strings.

**Comment by dbaeumer** [comment]
The html client has the right file:

![capture](https://user-images.githubusercontent.com/1931590/55068153-6b237580-5081-11e9-9169-592f016293af.png)

**Comment by jrieken** [comment]
> @jrieken no language pack installed and English UI. Right ?

Yeah, I have English configured, tho also german installed

**Comment by aeschli** [comment]
The problem in the JSON webpack.config. It defines a plugin which replaces the plugins from the default config.
