### ISSUE TITLE
The gears in the format command options are not very useful

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#71196]
Testing #71093

- It's hard to discover.
- For someone who doesn't already know what the gear does, he can't possibly guess what it does.
- It doesn't help you with disabling formatters. Whether you clicked it or not you still go into settings and find the formatter setting to toggle.
- I don't think uninstall or disabling certain extensions would be the suggested workflow. Workspace config that disables certain formatters should be, correct?

**Comment by jrieken** [comment]
That's the best we can do today and not a bad UX because

* it is much aligned with other quick pick secondary action usages (see task, open file etc)
* it doesn't reset the main editor context, e.g you stay in your foo file and still see meta information to the side of that
* the extensions viewlet allows to disable/uninstall and to open the extensions editor. The latter shows all information about the extension, e.g all settings and its readme. What missing is https://github.com/Microsoft/vscode/issues/70959,  or better https://github.com/Microsoft/vscode/issues/25012#issuecomment-424073078)
