### ISSUE TITLE
Close button is not keyboard accessible for custom dialog

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#71220]
Issue Type: <b>Bug</b>

Testing https://github.com/Microsoft/vscode/issues/71116

Pressing tab repeatedly cycles through the buttons options, but never to the close button. In our notifications, the 'x' can be tabbed to. So even though the native dialogs on Windows also don't tab to the close button, I think it's more consistent with the rest of the product to allow focus on that button. 

VS Code version: Code - Insiders 1.33.0-insider (b9bcca2b9830df592892d63201704026c18dcbe5, 2019-03-26T08:08:33.302Z)
OS version: Linux x64 4.11.12-100.fc24.x86_64

**Comment by sbatten** [comment]
The UX between notifications and dialogs is slightly different. In a dialog, there are only buttons that are specific to the dialog and close button. In a notification, there can also be a settings gear. This gear belongs to the same toolbar and thus is right next to the close action of the notification. Since you can focus the gear, it makes sense that the next tab would take you to the close  action. Escape is the desired  keyboard access for close in dialogs IMO.

**Comment by RMacfarlane** [comment]
The button looks like any other button in the product, so even if there are no additional actions next to it, I still think it's weird for it to not be able to take focus. Let's see if any of the other testers for this item have an opinion on it, if no one else finds the current behavior unexpected I'll close this

**Comment by auchenberg** [comment]
In our notifications the close button is focusable. We should aim for consistency, as they visually look very similar.

**Comment by sbatten** [comment]
/cc @Microsoft/vscode for additional input

When this went in @bpasero changed his mind about the behavior, so maybe he can share what convinced him.

When notification buttons have focus (not the initial state when a notification appears because they are not modal), it takes 2 presses of escape to close the notification. When dialog buttons have focus (the initial state when shown) it only takes one escape key press. This makes esc the natural method of keyboard cancellation.

Another point is that the close button in a notification is a separate action not equal to any of the buttons because notifications don't demand action. Modal dialogs however demand a response and the close button is therefore making a decision (equivalent to the cancel button). Thus, there is no reason to make it focusable.

Lastly, the main argument IMO for using keyboard focus in this case is for accessibility, not ease of use. If a user wants to dismiss this fast, they will just use ESC. Same with notifications. That means we really shouldn't expose two equivalent buttons to a screen reader as this is just confusing. Especially since this isn't how the user would be used to dialogs working.

**Comment by bpasero** [comment]
Yeah I realized that the close button is typically not keyboard accessible in a native dialog because ESC dismisses a dialog typically. You could argue the same is true for notifications but that one is not a standard widget type.
