### ISSUE TITLE
Support for command links in property descriptions

### ISSUE THREAD

**Issue by queeniema** [microsoft/vscode#71295]
Issue Type: <b>Feature Request</b>

Here's what I have tried using [this](https://code.visualstudio.com/api/extension-guides/command#command-uris) as a reference:

```json
"myextension.myProperty": {
    "type": "string",
    "default": "",
    "markdownDescription": "This is my property description and I want to link this [command](command:editor.action.addCommentLine)!"
}
```

In the settings page, "command" doesn't show up as a link, just plain text. It would be nice if command links were supported like regular URL links.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T22:46:48.547Z)
OS version: Darwin x64 18.2.0

**Comment by aeschli** [comment]
I assume you want this in the settings UI.

**Comment by queeniema** [comment]
@aeschli That's correct. A clickable command link above the field.

**Comment by roblourens** [comment]
Sure, out of curiosity, what sort of command would you use this for?

**Comment by queeniema** [comment]
The property/setting I'm trying to use this for is a directory path containing some directories. And the command is a refresh command that will pick up the latest setting value and do some parsing of the contained directories. I know I could use `workspace.onDidChangeConfiguration` to detect changes and trigger the command automatically but I want to allow the user to refresh manually.

**Comment by roblourens** [comment]
Are you avoiding `onDidChangeConfiguration` because it might trigger while the user is not done typing, or is there a different reason?

**Comment by queeniema** [comment]
Yes, that's the main reason.

**Comment by JarrettSpiker** [comment]
I would like to second this.
My use case is:
My extension involves authenticating with a server, and I have built a web-view for this. This authentication process is too complicated to handle through native VSCode settings (I want to validate the server, there might be 2FA, etc, etc)

However, since users have an expectation of seeing their settings in the settings UI, I would like to display the server that the user has authenticated to in the settings UI as a read only property. This requires me to have a description which says "You can modify this value by doing X"

And overall, it seems like a better user experience to have that description be
"you can modify this by clicking `here`"
 and having `here` open my webview, rather than:
"you can modify this setting by selecting the X command in the command palette"
