### ISSUE TITLE
Automatic log expressions for Logpoints (Print debugging)

### ISSUE THREAD

**Issue by auchenberg** [microsoft/vscode#71310]
This is feature request inspired by Komodo IDE's "Print debugging", and is sourced from NPS feedback.

**Scenario:**
1. User clicks gutter, maybe via shift/ctrl + click?
2. A Logpoint is set for the particular line, and more importantly the log expression is automatically populated from the particular lines scope and variables.

**Inspiration:**
Komodo IDE's "Print debugging"
![printdebug](https://user-images.githubusercontent.com/173559/55103829-81800000-5086-11e9-8eee-89242b563bb8.gif)

https://www.activestate.com/products/komodo-ide/whats-new/

**UX**
1. This feature could be enabled via new shortcut such as `SHIFT+gutter click`
1. We could prefix the log expression automatically based on the call hierarchy.

```
<module.<className>.<function>: <log expression>
```

**Questions**
1. Do we have available information from the LS to extract such information? 
2. Could this be contributed by each of the language specific DA's?

**Things to be output:**
1. Variables defined on the particular line.
2. Variables available in the local scope.

**Comment by weinand** [comment]
Good idea (but tricky to implement ...)

Answers:
1. A language server (LS) is not a concept known to VS Code as it is an implementation detail of a language extension. Only language contributions are known to VS Code. We could either try to use an existing language contribution to somehow find variable information or we could introduce a new language contribution for this specific purpose (or better: a new language contribution for debugging features in general, e.g. more precise hovers).
2. debug adapters (DA) don't have enough language know-how to contribute this information (and typically they don't have access to the language server). E.g. node-debug knows nothing about TypeScript and has no access to the TypeScript LS.

Since LogPoints exist outside of all debuggers but in the scope of a specific language, I envision that a language extension (and not a debugger extension) would contribute a LogExpressionProvider that VS Code would use to automatically fill expression into new LogPoints based on the context where they are created.

**Comment by roblourens** [comment]
As a simpler solution, the node debug extension (in the EH) could parse the file with TS. It only needs to know about what the variables are on a certain line, it doesn't need to understand the whole project. But that would only work for normal js/ts and every DA would have to implement it theirself.

**Comment by auchenberg** [comment]
I don't have a strong opinion on how it would be implemented, but I agree in principle that it should be contribute by each extension.

Indeed. An interesting challenge for example the Chrome Debug extension, is that you can debug JSX/JS/TS/Flow in Chrome, while other debug extension have a more 1-1 mapping between the debug target and the language.

**Comment by weinand** [comment]
@auchenberg you said:
> but I agree in principle that it should be contribute by each extension.

Is there any other mechanism to extend VS Code? ;-)

The interesting question is: by a language extension or by a debugger extension?

My statement was: 
It must be via a language extension since logpoint expressions are only language dependent but not debugger dependent.

**Comment by auchenberg** [comment]
@weinand Okay okay, point taken 🙈😂
