### ISSUE TITLE
the logpoint is printed *before* the previous line.

### ISSUE THREAD

**Issue by WiliTest** [Microsoft/vscode#71382]
Issue Type: <b>Bug</b>

looks at this (python3.6) code:
The print statement should come first, then the logpoint (since I placed it after). But it doesn't:

![log issue](https://user-images.githubusercontent.com/24194840/55161750-8b793000-5166-11e9-8aa2-b091816582e4.png)

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.87GB (0.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.1
transformer|dak|1.6.0
vscode-eslint|dba|1.8.2
beautify|Hoo|1.4.11
vscode-favorites|how|1.4.0
reg|ion|0.0.2
vscode-opn|lfu|1.1.2
python|ms-|2019.3.6139
cpptools|ms-|0.22.1
PowerShell|ms-|1.11.0
debugger-for-chrome|msj|4.11.3
vscode-fileutils|sle|2.13.5
vscode-autohotkey|sle|0.2.2
rewrap|stk|1.9.1
vscode-arduino|vsc|0.2.25
local-history|xyz|1.7.0

</details>

**Comment by V-ed** [comment]
My guess, and I might be wrong, is that the line at which you've out your logpoint is empty, and therefore, vscode applies the logpoint to the nearest execution point upward instead of downward.

You could probably test this by adding another `print` statement at the line of your logpoint, and I'd expect the output to be something along the lines of :
```
print i: 1
log i: 1
second print added at logpoint line

print i: 2
log i: 2
second print added at logpoint line
```

This was probably made to let you access your logpoint while not skipping empty lines (I'm not familiar wit python, but I assume empty lines are not executed, therefore the logpoints wouldn't be executed if put on empty lines (if the "attach to nearest execution line" I talked at the start wouldn t be there).

... if everything I just said is right though, I would indeed assume the logpoint's message should be sent *after* the actual print execution. Therefore, it should attach to to nearest execution line **downward**, but now we have a situation where there might not be a line of execution downward. This is a problem and will need to be tought out, as I cannot think of a universal solution currently.

Also, would this be a vscode problem of a python extension issue? I'm not sure which is to blame, the way vscode sends information to the Debug Adapter Protocol, or the python extension's debug adapter's implementation.

I'll let the vscode team further up on this, this was just my own idea of why you've experienced this problem!

**Comment by WiliTest** [comment]
Thanks for your reply! 
You are right, my logpoint was set on an empty line.
![log issue 1](https://user-images.githubusercontent.com/24194840/55166753-f9762500-516f-11e9-8bf4-eb9ebc829eaa.png)

But, when I put the logpoint on the same line than the print, the logpoint still goes first.
![log issue 2](https://user-images.githubusercontent.com/24194840/55167048-8b7e2d80-5170-11e9-91bb-8d600955c2f9.png)

**Comment by V-ed** [comment]
> But, when I put the logpoint on the same line than the print, the logpoint still goes first.

This is expected : the same would be true if it was a breakpoint and not a logpoint, the point would be executed before the line executes itself (it would be weird to put a breakpoint on a line and the line would execute before the breakpoint hits).

This is why, in my example, the order of the output is
```
print i: 1
log i: 1
second print added at logpoint line
```
1. `print(f"print i: {i}")`
2. execute logpoint at line 6
3. execute print at line 6 `print(f"second print added at logpoint line")`

This is why I talked about empty lines : since empty lines are not executed (in your example, empty line at 6 and logpoint at 6), but you still want a logpoint to be executed, vscode (or the python Debug Adapter) probably sets your logpoint as being placed at line 5, in other words, at your `print(f"print i: {i}")` - therefore firing before your print statement (as they are considered at the same line, and debug points are executed before the statement line it is on).

**Comment by WiliTest** [comment]
If I understand well: 
 - the logpoint goes first the line we place in
- placing it in an empty line is the same as placing it in front of the last line

So we can't logpoint a value given at the last line, which is a (little) problem.

**Comment by V-ed** [comment]
Exactly! But keep in mind this is my guess, based on my experience and what you presented, on how vscode (or the python's debug implementation) works with debug points (logpoints, breakpoints, etc), and I might be wrong on that subject.

You could, in your example, put your logpoint on the `time.sleep(1)` statement, and you would see the logpoint message being printed after the `print(f...` statement. The problem arrises when there is no statement to put a logpoint after, as you said with your last line : "*So we can't logpoint a value given at the last line, which is a (little) problem.*".

As I said earlier, let's wait for a reply from the vscode team, I'm quite curious myself if this is they could work upon, as breakpoints / logpoints on empty lines is a concept I'd like to see / understand more!

Have a good day!

**Comment by weinand** [comment]
The discussion makes complete sense and the speculation about the output ordering is probably correct.  
But please keep in mind:
VS Code is not involved here: moving breakpoints from empty lines to some close statement is typically done by the runtime (or the debugger).
VS Code just receives DAP output events form the debug adapter (inside the Python extension) and shows them in the debug console.

So please forward this issue to the Python extension if you want to have an "official" statement about the ordering.
