### ISSUE TITLE
Enhance git commit message (show a counter with (50 - commit message length)) 

### ISSUE THREAD

**Issue by a-magdy** [Microsoft/vscode#7138]
I am using VSCode on Ubuntu 14.04 x64

VSCode About:

Version 0.10.10
Commit 5b5f4db87c10345b9d5c8d0bed745bcad4533135
Date 2016-03-07T10:30:20.458Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

Steps to Reproduce:

1. Open a git repo folder
2. Make a change
3. Go the "GIT" tab
4. Start typing a git message

I am thinking of a counter starting with 50 (The number of character that'll be used as the short message appearing in git commits), it helps write meaning full messages, without have a word cut and completed in the description part, the behavior is taken as is from GitKraken

**Comment by joaomoreno** [comment]
My suggestion would be to, instead of always showing a counter, [show a message in the InputBox](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/inputbox/inputBox.ts#L242) when the first line's length has surpassed 50 characters.

I'd gladly take this as a contribution PR! Wanna give it a try?

**Comment by sijad** [comment]
It seems easy to implement this, can I give it a try?

**Comment by joaomoreno** [comment]
Absolutely, looking forward to it.

**Comment by ekfuhrmann** [comment]
It unfortunately seems as if @sijad is no longer working on this.

**Comment by n370** [comment]
Please bring it back!
