### ISSUE TITLE
Format fails silently if configured formatter is from disabled extension

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#71400]
Ref: #71173

```json
{
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}
```

- Disable Prettiter formatter (either workspace or global)
- Format JS file
- Format fails silently, no notification, no status bar msg 🐛

**Comment by jrieken** [comment]
There is to cases

1. the formatter is available but doesn't target the file in question
1. the configured formatter is disabled/uninstalled

In the former case we shouldn't suggest to configure a different formatter because often formatters only support `file` and `untitled` files but not other files. In the latter we can be more annoying because you should very likely tweak your configuration.
