### ISSUE TITLE
Closing file with unsaved changes in Extension Development Host doesn't ask to save changes

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#71405]
- Debug an extension
- In the extension dev window, open a file or an untitled editor
- Type something so the editor has unsaved changes
- Close the editor
- No confirm dialog appears and your changes are gone forever

**Comment by bpasero** [comment]
Yeah, this has always been like that to make testing easier because you can typically not control the dialog that opens when closing a dirty file.

**Comment by gjsjohnmurray** [comment]
I just noticed this behaviour and find it a but alarming. At first it didn't occur to me that it could be unique to the Extension Development Host. At the moment a lot of the time I'm using VSCode that way because I'm developing and testing extensions. @bpasero do you mean it's intentional in order to help automatic testing scenarios that are using EDH and want to create documents, change them and then discard them? Would you consider making this behaviour configurable?

**Comment by bpasero** [comment]
Yeah that is pretty much the reason why we do that. You should not do real development in the extension host window for that reason.
