### ISSUE TITLE
my ram is exploding and i don't know why it is happening

### ISSUE THREAD

**Issue by notsonoob** [Microsoft/vscode#71466]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by weinand** [comment]
There is no "needed data" because you don't have access to "my clipboard".
Please see [this guide](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests) for how to file a proper issue. Include: 

* VS Code version
* OS version
* Installed extensions
* Steps to reproduce
