### ISSUE TITLE
[scss] Validate scss @directives with `unknownProperties` rule

### ISSUE THREAD

**Issue by franciscolourenco** [microsoft/vscode#71558]
Directives like `@tailwind` or `@apply` in the scss syntax get invalidated with a `css-rcurlyexpected` error. This means it is not possible to configure the syntax to stop validating these directives specifically.

If directives were invalidated as `unknownProperties`, it would be possible to add them to the ignore list.

<img width="313" alt="Screen Shot 2019-04-01 at 21 34 03" src="https://user-images.githubusercontent.com/208149/55354414-f9568c00-54c5-11e9-8c1b-441afd15268e.png">

**Comment by octref** [comment]
http://tabatkins.github.io/specs/css-apply-rule/
https://www.xanthir.com/b4o00

**Comment by Erik-Roth** [comment]
@octref - I read the links supplied and understand the general and extended implications and why the rule was removed. But in the case of TailwindCSS it is used more as a general directive to combine pre-defined style shortcuts so you can reuse them without having to repeat the entire set of classes for each time you want them used. 

So (see screen grab) as I want to use those styles for all 3 of those points, I simply type it as shown. However the constant errors and notifications are getting annoying.
![Screen Shot 2019-10-25 at 6 35 18 PM](https://user-images.githubusercontent.com/37046891/67611373-4cd84200-f756-11e9-8214-d9a18454e17b.png)
![Screen Shot 2019-10-25 at 6 36 21 PM](https://user-images.githubusercontent.com/37046891/67611417-ad677f00-f756-11e9-9b17-3f794975bd5c.png)
![Screen Shot 2019-10-25 at 6 37 30 PM](https://user-images.githubusercontent.com/37046891/67611419-b1939c80-f756-11e9-98f3-a842417b7b1c.png)
Even if they @apply can't be added due to the DOM specifications, what about something in the settings JSON we could do to whitelist our own directives?

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode-css-languageservice/pull/194
(I added a commit to also gracefully handle unknown at-keywords: https://github.com/microsoft/vscode-css-languageservice/commit/727d17aebb3f7fc78fc3cf8ea76d22680f166a95)
