### ISSUE TITLE
Quick Fix feature not working - Really confused.

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/vscode#71579]
Hi, I am a bit new, and I have a simple code example on VS Code v1.32.3.
It says I have an error,   ok fine..... but then when I chose the "Quick Fix" option
there is never a Quick Fix for this or any other thing in the past I tried to do a quick fix on.
Whats the point of having a Quick Fix feature, if it doesn't do anything ?
Im a bit confused.
.
This is the code I tried to do a quick fix on (its an extremely simple code):
.
![Screenshot_24](https://user-images.githubusercontent.com/18384135/55377109-88bd6880-54e1-11e9-9e12-3e674c9406d9.png)

When I try to fix, I get this:
.
![Screenshot_25](https://user-images.githubusercontent.com/18384135/55377130-9b37a200-54e1-11e9-82d0-b0671c52273b.png)

**Comment by WSLUser** [comment]
I also get this issue for Python but seems to apply to any language. I have the Python extension as well as Intellicode. Still a current issue with 1.33 with the latest update.

**Comment by sandy081** [comment]
Quick Fix... action is shown even when there are no quick fixes (code actions) available. May be it can hidden then.

**Comment by WSLUser** [comment]
Optimally, an actual corrective action would be taken (or at least suggested) based on the feedback provided by the language extensions (Python and Intellicode for my use-case).

**Comment by DylanCa** [comment]
Same here, I always get the "No code actions available" when I try to Quick Fix my code, no matter the language used, and even if I have no extension installed.

![image](https://user-images.githubusercontent.com/2054131/55648234-0d5cff00-57e0-11e9-8672-e97b2541e772.png)
![image](https://user-images.githubusercontent.com/2054131/55648305-3ed5ca80-57e0-11e9-859c-6623743de072.png)

I do not really know why it is not working, but I can't get to remember since when this bug is occurring to me ( I remember last summer it was okay, and I think during December too while I was working on an Angular Project )

**Comment by sean-mcmanus** [comment]
Our C/C++ extensions does have lightbulb code actions for the error squiggle, but the quick fix still says "no code action" available -- is that a bug? Let us know if our extension isn't doing something correctly. I didn't understand the docs at https://code.visualstudio.com/updates/v1_32#_hover-and-problems-peek-improvements .

![image](https://user-images.githubusercontent.com/19859882/55651212-bb46ba00-579c-11e9-9563-e414b5a28af1.png)

**Comment by sandy081** [comment]
@sean-mcmanus Can you please provide simple steps to repro this?

**Comment by sean-mcmanus** [comment]
@sandy081 It occurs when you have a .c or .cpp file with text `#include <foo>`. We report the squiggle message via textDocument_publishDiagnostics and the code action from textDocument_codeAction. Do we need to do something special to associate the code action with the squiggle's QuickFix?

**Comment by sean-mcmanus** [comment]
@sandy081 Okay thanks a lot for informing us -- the "CodeActionKind" type is completely new to us. Our code action just returns a Command and not the additional info like the CodeActionKind. I filed a work item for us at https://github.com/Microsoft/vscode-cpptools/issues/3439 . We have a lot of "catching up" to do with the LSP updates.

**Comment by kenkendk** [comment]
I have had this issue for weeks with C#, and I finally figured out that it was just the menu.

Basic stuff where it used to suggest "import System;" no longer showed up. After reading this issue, I tried the `Cmd+.` command and the keyboard shortcut works but not the menu.

This image shows what happens when clicking the "Quick fix..." menu:
<img width="387" alt="screenshot from menu" src="https://user-images.githubusercontent.com/1510755/56462309-aa638e80-63c1-11e9-95da-f2f60b4760f2.png">

And this is what shows when pressing `cmd+.`:
<img width="414" alt="screenshot from keyboard" src="https://user-images.githubusercontent.com/1510755/56462310-aa638e80-63c1-11e9-93d7-43e1f6bcb439.png">

This looks similar to the screenshots from @RobFosterNYC and @DylanCa .

**Comment by pouledodue** [comment]
Seriously kills productivity, I am reinstalling PyCharm

**Comment by sandy081** [comment]
Looks like C# extension is also not using the `QuickFix` code action kind for their code actions. Probably we have to show all code actions for the given range.

**Comment by akost** [comment]
I see the same issue with JSHint/JavaScript.

![jshint1](https://user-images.githubusercontent.com/698174/57544400-16c01680-730c-11e9-9fe7-c9624a6510ac.png)

![jshint2](https://user-images.githubusercontent.com/698174/57544406-1889da00-730c-11e9-857c-a841e428b84d.png)

**Comment by akost** [comment]
The same thing (No code actions available) with PowerShell.

**Comment by al-wys** [comment]
Same issue with **TypeScript** in _.tsx_ file.

![image](https://user-images.githubusercontent.com/16317690/58465972-59d31400-816b-11e9-9f7e-da2296d737d8.png)

**Comment by Coderx7** [comment]
This has been nearly two months! any fixes for this ? 
I'm having this issue in the latest version as well!

**Comment by WSLUser** [comment]
This features becomes very important when you're upgrading code from a legacy version (such as Python 2) to the updated version (Python 3). I'm sure there are other languages have similar stipulations such as converting C to C++ or C# or vice versa (or even C# to C++ and vice versa).

**Comment by winsonet** [comment]
I also have this issue, and this is very important when create the new project, but the ```cmd+.  ``` works for me!

**Comment by James-Firth** [comment]
I also had this issue and only learned today from some searching that `ctrl+.` (on Linux) brings up the quick fix list of actual working suggestions

**Comment by ShivamMukherjee** [comment]
This doesn't seem to be a problem for C# in my case atm (I'm using Unity/Mono).

**Comment by tbasten** [comment]
I get the same with Powershell.

![image](https://user-images.githubusercontent.com/12264887/59498348-d71aba80-8ec7-11e9-9506-9bf16f32e45e.png)
![image](https://user-images.githubusercontent.com/12264887/59498383-e7cb3080-8ec7-11e9-984a-4a7a854a1500.png)

**Comment by dag2108** [comment]
On a Mac, the Quick Fix shortcut appears to be **⌘.** (Command + Period). It would be super helpful if we could get the quick fix to appear on mouse hover, though!

**Comment by zakaoai** [comment]
Hello there,
I have the same problem since today. Quick fix was working a week ago but now clicking on "quick fix" and then clicking on suggestion do nothing. 
But if I use ctrl+; to show suggestion it work.

**Comment by mjbvz** [comment]
Just to clarify what was fixed by #77120: we now only show the `Quick fix...` button in the hover if we know for sure that that quick fixes are available.

A few extensions provide quick fix style code action but do not explicitly mark them as quick fixes. Those code actions will show up in the lightbulb menu but not if you click `quick fix...`  in errors hovers (because we only want to show code actions that we know for sure will fix something). Extensions must mark their quick fix code actions as [`CodeActionKind.QuickFix`](https://github.com/microsoft/vscode/blob/03e13189e7518414fbbad5324908fe3eeb572eae/src/vs/vscode.d.ts#L1961) to have them show up in the problem hover `quick fix...` menu too

**Comment by WSLUser** [comment]
@DonJayamanne can you verify that the python extension is good in this regard?

**Comment by SEDoug** [comment]
I took a look at my installed extensions and noticed the C# extension was complaining that it needed to be reloaded. Hmm, so check your extensions list first. This is what I was presented after clicking reload. Notice the version I'm running as of today's date stamp after I reloaded the C# extension. I hope this helps some of you.
![c#_extension01](https://user-images.githubusercontent.com/3903554/61532944-0fdf0f80-a9f1-11e9-9dce-ebff9b3572bc.PNG)
![c#_extension02](https://user-images.githubusercontent.com/3903554/61532951-140b2d00-a9f1-11e9-811f-73c70e293bcf.PNG)
![c#_extension03](https://user-images.githubusercontent.com/3903554/61532959-179eb400-a9f1-11e9-9ba9-90725c2599bb.png)
