### ISSUE TITLE
[Feature] Add support to filter scripts from the script explorer using regular expressions

### ISSUE THREAD

**Issue by lonix1** [microsoft/vscode#71635]
Consider this `package.json`:

````json
"scripts": {
  "build-lib1": "cd libs/lib1 && build && foo && bar",
  "build-lib2": "cd libs/lib2 && build && foo && bar",
  "build":      "npm run build-lib1 && npm run build-lib2"
}
````

Sometimes scripts like `build-lib1` and `build-lib2` are not meant to be used manually, they are just there to make the file easier to manage / less complex.

It would be nice if the npm scripts explorer (the tree in the sidebar) would hide such scripts.

So for example, if the script's name is one of these special patterns:
- `#build-lib1`
- `:build-lib1`
- `-build-lib1`
- etc...

...then the explorer view won't show them.

**Comment by thw0rted** [comment]
I'd like to see this implemented with a regexp or list, or both, as suggested.  But I want to make an argument for a sensible default behavior.  Instead of defaulting `npm.scripts.ignore` (or whatever it winds up being called) to the empty string, default it to `/^pre/`.

I actually came to the tracker to find a way to stop the task runner from picking up `prebuild`, `prepack`, `pretest`, etc.  Those aren't intended to be run manually!  `pre-` scripts automatically run before the "actual" script.  I'd like for Code to ignore them by default, because when I type `CTRL+SHIFT+R` then `test`, I'm presented with two options, and `pretest` is selected because it lex-sorts before `test`.  I'm never going to pick `pretest`, y'all.  The sane thing to do is one of:

* ignore all `pre-` scripts automatically
* let me specify what to ignore (and maybe default to `pre-`)
* sort the matching scripts by MRU instead of alpha-sort, so at least I only have to arrow-down to `test` once

**Comment by ajmar** [comment]
This would be very useful for me as well. I have quite a few scripts in my package.json, many of them meant only to be called by other scripts and never by the user. A regex filter can can be applied would be great, or a way to group certain scripts together (and then hide certain groups).

**Comment by ckot** [comment]
I realize this might be a separate, but similar issue. I'm working with yarn workspaces. It would nice, at least, to be able to somehow specify or exclude which workspaces (sub-directories) get their npm scripts listed, in addition to the ability to filter individual scripts

**Comment by machineghost** [comment]
Please keep in mind that many people have two `package.json` files: one for their client/front-end, and one for their server.  They may even have a third for the parent folder of both.

If each of these files has a large number of scripts (and they well might), you have to wade through so many possible scripts that the NPM Scripts Explorer is basically useless: any convenience it offers is outweighed by the inconvenience of having to scroll through tons of scripts I don't want to run, so I'm back to using the keyboard :(

It seems to me most devs have only a handful of scripts they run regularly (eg. "start client dev server", "start API server", and maybe "run migrations" or "run tests".  But this feature can't be used to do that if you have lots of other scripts in your `package.json` ... and *especially* if you have multiple such files.

**Comment by thany** [comment]
> I'd like to see this implemented with a regexp or list, or both, as suggested. But I want to make an argument for a sensible default behavior. Instead of defaulting `npm.scripts.ignore` (or whatever it winds up being called) to the empty string, default it to `/^pre/`.

And `^post`, but not indriscriminately. There could be a script called `pretty` you *don't* want to ignore. Similarly there could be a script called `poster` you also don't want to ignore.

By default, only filter out standardized pre/post scripts, and pre/post scripts for *existing* custom scripts. I'm not sure that this can be done with a regex though... So maybe a regex is not the way to go, or my suggestion is more complex than neccesary. Either way, food for thought.

**Comment by jpSimkins** [comment]
I would just like to have the ability to use regex to filter the scripts. I do not care to have the `pre` and `post` be filtered automatically. I can write my own regex to handle that. This gets pretty complicated and would be very difficult to pull off if you want to remove all `pre` and `post` scripts as this could possible removed useful scripts like `prerelease` or `postpone`. I think just giving the ability to filter scripts by a user defined regex will suffice.

**Comment by thw0rted** [comment]
Working out a regex with exclusions (negative lookahead) is a pretty big hassle, and some engines don't support it at all.  Would it resolve the `pretty` issue if typing the exact name of the script made it appear in auto-complete, then selecting it added the script to an exact-match allow-list?  That is, if the ignore expression is `/^pre/`, you'd type `pretty`, `npm run pretty` would appear in autocomplete, you could pick that, then in the future, you could type `pre` and `pretty` would appear but `prepublish` would not.

**Comment by thany** [comment]
@thw0rted "Some engines" being... Electron? I'm not sure you mean there.
Anyway, regexes should be fairly easy to implement, whatever users end up doing with them. We should not be overthinking this.

**Comment by thw0rted** [comment]
Sorry, what I meant was, some flavors of regex (like, JS vs Perl vs C/C++/C# etc etc).  Of course it's a safe bet that it would be JS-flavored regex, but IIRC some types of lookaround support were only added in the last couple of years.  Maybe it's fine now, but I try to avoid relying on lookaround if I can help it just because it's not universally supported.  I like to think that I can write a decent regex off the top of my head in most circumstances, but I'd definitely have to look up how to write "match everything that starts `pre` except `pretty`", and I'd probably still get it wrong the first time.

**Comment by thany** [comment]
See here: https://caniuse.com/?search=regular%20expression

As you can see, lookahead assertions are universally supported, and have been for as long as regexes have been a part of Javascript. **Lookbehind**, however, has been added recently, and is currently being held back by the web's new IE6.

What's needed to except `pretty` from `^pre`, is lookahead, which can be used safely. I don't think we have to take other regex engines into account, CMIIW.
