### ISSUE TITLE
Why does editor.lineHeight default to 0?

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7164]
`editor.lineHeight` has it's default set to 0 here https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/config/defaultConfig.ts#L99

Should it actually be `GOLDEN_LINE_HEIGHT_RATIO` or `null` instead? https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/config/defaultConfig.ts#L30

It's a little confusing seeing this, since 0 means the lines will be stacked on each other:

![image](https://cloud.githubusercontent.com/assets/2193314/15766804/85a9bee6-28f7-11e6-9291-84fc04c79469.png)

**Comment by kisstkondoros** [comment]
IMO the idea was to use a computed line height for the given font size by default here: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/config/commonEditorConfig.ts#L380
And i think it is 0 because here https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/config/commonEditorConfig.ts#L510 the default value is not specified

**Comment by alexandrudima** [comment]
I did not want to make that a `string|number` where it would accept "auto" and a number. Given `0` makes no sense for a line height, I use that as an indicator that it should be computed as a ratio from the `fontSize`. I can update the description to explain what `0` actually does.
