### ISSUE TITLE
Zoom out feature

### ISSUE THREAD

**Issue by meenakshiravisankar** [microsoft/vscode#71653]
Issue Type: <b>Feature Request</b>

Hi,

Ctrl and - does not zoom out when opening an image on vs code editor. Kindly add this feature. 

Thanks.

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:38:49.842Z)
OS version: Linux x64 4.15.0-46-generic

**Comment by mjbvz** [comment]
For anyone looking into this, [here is the file that implements the viewer](https://github.com/microsoft/vscode/blob/b71932d4b725b4a55124f3fc0bc85487b8a9c8ba/src/vs/workbench/browser/parts/editor/resourceViewer.ts#L2).

I think the <kbd>ctrl</kbd><kbd>+</kbd>keyboard shortcuts are already taken so we may need to come up with different ones

**Comment by hotkovycheslav** [comment]
Hi, @mjbvz, I want to try help with that issue. Will there be any recommendations?

**Comment by mjbvz** [comment]
Yes, here's some pointers:

* We need commands for zoom in and zoom out. Take a look at the keybindings that are specific to the keybindings editor for example: https://github.com/microsoft/vscode/blob/b71932d4b725b4a55124f3fc0bc85487b8a9c8ba/src/vs/workbench/contrib/preferences/electron-browser/preferences.contribution.ts#L226

* The key here would be to create a new context that is enabled when you are in an image editor. This would be similar to the `CONTEXT_KEYBINDINGS_EDITOR` from the example command above

* These commands would just invoke `zoomIn` and zoomOut` on the resource editor. 

Since this is actually somewhat complicated, I've unmarked it as `good first issue` but left it as help wanted

**Comment by skprabhanjan** [comment]
@hotkovycheslav  , Please update if you will still go ahead with looking into this issue or not  :)

**Comment by hotkovycheslav** [comment]
Hi, @skprabhanjan, Yes I will be work on it.

**Comment by mflan48** [comment]
Hi, @hotkovycheslav are you still working on this issue? If not, I can work on it.

**Comment by hotkovycheslav** [comment]
@mflan48 Hi, you can work on it.

**Comment by sanjeev444456** [comment]
hi @mflan48, are you still working on this issue? if not i can work on it

**Comment by mjbvz** [comment]
The image preview code now all lives in an extension, which should make adding this easier: https://github.com/microsoft/vscode/blob/bac36e97c68a13488088db60c28410e7321d2871/extensions/image-preview/src/preview.ts#L20

**Comment by StackDoubleFlow** [comment]
I'd like to pick this one up if that's ok

**Comment by mjbvz** [comment]
Added two new commands `imagePreview.zoomIn` and `imagePreview.zoomOut` that zoom the active preview in or out. They do not have a default keybinding but you should be able to easily [configure one](https://code.visualstudio.com/docs/getstarted/keybindings)
