### ISSUE TITLE
Delete All Left should still function when any text is selected/highlighted

### ISSUE THREAD

**Issue by jsunsawyer** [microsoft/vscode#71683]
Currently, using `cmd + backspace` when any text is selected results in a normal backspace action.

My expectation is that anything selected and anything to the left of the selection should be deleted.

If I wanted the current functionality, I would simply use `backspace` without `cmd`.

**Comment by mflan48** [comment]
Hi @alexandrudima, I would like to work on this issue. Do you have any tips as to where to start either file-wise or implementation wise?

**Comment by alexandrudima** [comment]
@mflan48 Here it is:

https://github.com/Microsoft/vscode/blob/f3e1c7dbabd38c02a7d5f0e2e0e1c4016479166c/src/vs/editor/contrib/linesOperations/linesOperations.ts#L560-L590

**Comment by mflan48** [comment]
Okay thank you, I will be working on this issue!

**Comment by mflan48** [comment]
Hi, @alexandrudima, I've been working on this issue and believe I have a solution to it. However, I believe that implementing this feature will cause current test cases to be invalid. Specifically, in the "should work in multi cursor mode" test (located at line 250 in file 'linesOperations.test.ts' at the following path 'vscode/src/vs/editor/contrib/linesOperations/test/linesOperations.test.ts') the following tests will fail

editor.setSelections([new Selection(2, 2, 2, 2), new Selection(2, 4, 2, 5)]);
deleteAllLeftAction.run(null!, editor);
assert.equal(model.getLineContent(2), 'ord', '002');

editor.setSelections([new Selection(4, 3, 4, 3), new Selection(4, 5, 5, 4)]);
deleteAllLeftAction.run(null!, editor);
assert.equal(model.getLineContent(4), 'lljour', '004');

editor.setSelections([new Selection(5, 3, 6, 3), new Selection(6, 5, 7, 5), new Selection(7, 7, 7, 7)]);
deleteAllLeftAction.run(null!, editor);
assert.equal(model.getLineContent(5), 'horlworld', '005');

If this feature is implemented, I believe that the expected output for each test should be 'd', 'jour', and 'world' respectively rather than the current 'ord', 'lljour', and 'horlworld' values. Can you let me know if this should be the expected output and if so, how I should proceed with implementing this feature and submitting a PR?
