### ISSUE TITLE
Missing TextMate scopes in 1.33.0? (JavaScript grammar)

### ISSUE THREAD

**Issue by atomiks** [Microsoft/vscode#71694]
- VSCode Version: 1.33.0? ([macOS exploration build after update](https://az764295.vo.msecnd.net/exploration/37818ac3597b4afda264b05226b0b77fb8e85f41/VSCode-darwin-exploration.zip))
- OS Version: 10.14.3

Steps to Reproduce:

1. Scopes like `window`, `document` etc. are no longer scoped with `support.variable.dom`
2. Support function scopes like `getElementById`, `slice`, etc. are no longer scoped with `support.function`

1.30.2

<img src="https://i.gyazo.com/7a15716c3774b9638945179c0e317362.png" alt="before" width="300" />

1.33.0?

<img src="https://i.gyazo.com/8b43c1e2546a2c5780c20df5a883af7a.png" alt="after" width="300" />

Does this issue occur when all extensions are disabled?: Yes

I also noticed this on CodeSandbox which uses the latest VSCode I believe

**Comment by mjbvz** [comment]
This is intentional, see  https://github.com/Microsoft/TypeScript-TmLanguage/issues/691 for details

**Comment by atomiks** [comment]
Could you maybe revisit for variables `window`, `document`, `performance` etc? I feel like those ones don't cause conflicts.

**Comment by msftrncs** [comment]
Are objects such as `window` and `document` defined by the JavaScript specification?  Or are they merely defined casually by each JavaScript host, with not all hosts supporting them?

If they are supported by definition in the JavaScript standard, then they are reserved for one purpose, and then they should be scoped specially.  If they are merely defined in a few hosts, who have agreed independently to make them the same, then they shouldn't be scoped any differently from any other object.

Beyond that, I really think there should be more flexibility in the grammar system for each language.  For instance, I think PowerShell should have multiple grammars to support each version of the language, as it can have some significant differences between versions.  With more flexibility, you could choose a grammar specification for DOM centric JavaScript.   You could currently do this via an extension, that brings its own grammar, but there will be some confusion since the file extensions would not be different, and hence why I think there should be a separate option to choose different grammars for the same file types.
