### ISSUE TITLE
when i open terminal it's gets closed automatically with following message "The terminal process command 'C:\windows\System32\cmd.exe' failed to launch (exit code: 2)"

### ISSUE THREAD

**Issue by chennakesva** [microsoft/vscode#71714]
Issue Type: <b>Bug</b>

Steps to Reproduce:

Open Vs Code
Press Ctrl + ` to open termina

VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.64GB (7.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|2.1.2
vscode-great-icons|emm|2.1.47
debugger-for-chrome|msj|4.11.3
vscode-css-navigation|puc|1.3.0
vscode-icons|vsc|8.4.0
html-css-class-completion|Zig|1.18.0

</details>

**Comment by Tyriar** [comment]
If you launch cmd.exe from the start menu does running `C:\windows\System32\cmd.exe` work?

Also you could try on the latest version of vscode?

**Comment by XDfield** [comment]
same here. My os is windows10 64 bit.
All I can do is describe my operation in detail.

**The powershell works normally at first**, I add [oh-my-posh](https://www.powershellgallery.com/packages/oh-my-posh/2.0.249), [posh-git](https://www.powershellgallery.com/packages/posh-git/1.0.0-beta3), [git-aliases](https://www.powershellgallery.com/packages/git-aliases/0.1.2), [PSReadLine](https://www.powershellgallery.com/packages/PSReadLine/2.0.0-beta3) to my powershell manually, by unpacking the unpkg file to the $env:PSModulePath, because I am offline.
Then I add a PROFILE file for the powershell:
```powershell
Import-Module posh-git
Import-Module oh-my-posh
Import-Module git-aliases -DisableNameChecking
Set-Theme Paradox
```
I manually open the powershell and it loads normally.
When I open the terminal again in vscode, it automatically quits with following message "The terminal process command 'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe' failed to launch (exit code: 2)"
At first I thought it was because of the powershell problem, I restored all the above operations , deleted the added modules and the PROFILE file.
**But it still quits.**
After that I deleted all files in "C:\Users\username\AppData\Roaming\Code", **it still didn't work**.
Finally I have to uninstall the original vscode and install the latest one, and remove all extensions, **the problem is still**. Sad : (
Now, even if I change the terminal to cmd, it will automatically quit, with the message "The terminal process command 'C:\WINDOWS\System32\cmd.exe' failed to launch (exit code: 2)".

I don't know what to do.

**Comment by Tyriar** [comment]
@XDfield normally exit code 2 means that the path doesn't exist, `C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe` seems valid though. Are you using the 32-bit VS Code client?

**Comment by XDfield** [comment]
@Tyriar I clicked the download button directly on the official website, and I also confirmed that it is a 64-bit vscode. Even with the reinstalled version, I didn't modify the default configuration and I couldn't open the terminal.

**Comment by Tyriar** [comment]
Are there any errors in the devtools console (Help > Toggle Developer Tools)?

**Comment by XDfield** [comment]
After a few days of business trip, it miraculously worked fine. I do not know why.

**Comment by Tyriar** [comment]
In v1.34 the error message here should improve, please open a new issue after the release if the problem is not fixed (and the error message is still not clear enough).
