### ISSUE TITLE
Do not save editor onWindowChange when a modal dialog opens

### ISSUE THREAD

**Issue by narfanar** [microsoft/vscode#71731]
Tried to make the title say everything succinctly.

When `onWindowChange` is specified and I mentally don't leave VS Code, I don't want it auto-saving.

"Mentally leaving VS Code" means I either focus on another application, or another application steals focus. But a modal dialog opened by VS Code shouldn't be considered a focus-change.

Changing focus between different opened workspaces/VS Code windows should be fair game, though?

**Comment by bpasero** [comment]
This might require API from Electron to detect when a dialog is visible. Currently we simply listen on window focus changes.

**Comment by ad8e** [comment]
An amusing effect with `onWindowChange`: closing a tab with unsaved changes pops up "Do you want to save the changes you made?" But this dialog changes focus, which autosaves, and now the question is asking you to save the already-saved file.

This effect is more amusing than annoying at present, since the occurrence is immediately clear and any undesired changes can be easily backed out. It hasn't caused trouble for me yet.
