### ISSUE TITLE
Possible to suprress completion provider on specific token kinds?

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode#719]
I'm trying to fix https://github.com/Microsoft/vscode-go/issues/103, but as far as I can tell this isn't possible currently without tokenizing the whole file again in my extension and manually checking whether I'm in a comment to suprress providing results.

It would be nice if the `CompletionItemProvider` provided a setting to suppress it's results when in certain tokens/scopes.  

The implementation of the [TypeScript completion provider](https://github.com/Microsoft/vscode/blob/497788c0bcd20859f736d585b49c208af8dd518f/extensions/typescript/src/features/completionItemProvider.ts#L62) has an `excludeTokens` which seems to play this role but I can't get that to work in my own extension.

**Comment by egamma** [comment]
Currently not possible, since we do not expose token information in the extension host (something we have lost when transitioning to textmate grammars). `excludeTokens` is no longer supported.

**Comment by jrieken** [comment]
Not yet. The idea is to add scopes to `DocumentSelector`s such that you can express _I can provide suggestions in go files  when the caret is not in a comment_ 

```
{
   language: 'go',
   scope: '!comment!
}
```

Still, this requires us to expose scopes first ;-)

**Comment by mholt** [comment]
This is the only thing keeping me from using VS Code. I'm a bit sad to see this backlogged, but it's irritating enough that I hope it will be a priority.

**Comment by egamma** [comment]
@mholt we have looked into this and found that a root cause of the frustration of intellisense inside comments is that textual completions are accepted to eagerly when you type RETURN. In the [insider build](https://code.visualstudio.com/blogs/2016/02/01/introducing_insiders_build) we have therefore added support so that you can configure that completions are only accepted on TAB.

https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/latest.md#intellisense-on-tab-only

Can you please give this a try?

**Comment by mholt** [comment]
@egamma Hey this is great, I think it'll do quite nicely! Thanks.

**Comment by egamma** [comment]
@mholt glad this helps // CC @jrieken

**Comment by ramya-rao-a** [comment]
@jrieken Is https://github.com/Microsoft/vscode/issues/580#issuecomment-273740251 a blocker for https://github.com/Microsoft/vscode/issues/719#issuecomment-160064673 ?

**Comment by jrieken** [comment]
Yes and no. We have boiled things down the a small set of standard tokens: *comment*, *string*, *regex*, and *other* which is everything else. Those token live in the main side, so in theory we can register providers with more info. The problem is that we don't have token information on the ext side and that allow to evaluate a document selector there as well and that the lack of token would yield in different results...
