### ISSUE TITLE
I found a visualization issue with »« in vscode

### ISSUE THREAD

**Issue by Daijobou** [microsoft/vscode#71984]
Version: 1.33.0 (system setup)
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Datum: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
Betriebssystem: Windows_NT x64 10.0.17763

Steps to Reproduce:

insert  "»«" in editor

Result (diffrent size for «)

![image](https://user-images.githubusercontent.com/260343/55788129-0839d180-5ab8-11e9-950d-007c74225e13.png)

Expected

![image](https://user-images.githubusercontent.com/260343/55788145-11c33980-5ab8-11e9-9f16-075977890711.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@Daijobou If you open the page at https://microsoft.github.io/monaco-editor/ in Google Chrome and insert "»«", how is the rendering?

**Comment by Daijobou** [comment]
Same wrong size
![image](https://user-images.githubusercontent.com/260343/55806761-3384e680-5ae1-11e9-82ea-50c1b766266f.png)

**Comment by rebornix** [comment]
FYI I didn't see this on macOS.

**Comment by Daijobou** [comment]
I have report this issue in monaco-editor https://github.com/Microsoft/monaco-editor/issues/1433

**Comment by alexdima** [comment]
I cannot reproduce this on my machine:

Chrome Version 79.0.3945.79:
![image](https://user-images.githubusercontent.com/5047891/70613488-fdb47680-1c08-11ea-9656-4b2cf6249675.png)


VS Code version 1.40.2:
![image](https://user-images.githubusercontent.com/5047891/70613539-1ae94500-1c09-11ea-94e3-7d7a0a8b6bdb.png)


@Daijobou Can you still reproduce?

**Comment by alexdima** [comment]
From @Daijobou in https://github.com/microsoft/monaco-editor/issues/1433#issuecomment-564552298

---

Its still exists here for me in this editor, in all browsers, Edge, Firefox, Chrome, Chrome dev, Opera
![issueA](https://user-images.githubusercontent.com/260343/70627264-e9b24a00-1bf3-11ea-8223-d91025ef36a6.gif)

As you can see, this happen only in zoom factor 100% and only in this editor. Increase zoom factor >100% the issue is gone. No other text-editor have this problem on my notebook.

Its happen for font consolas (only in this editor) and monospace. See
![issueC](https://user-images.githubusercontent.com/260343/70629028-46fbca80-1bf7-11ea-86b4-7f3b7fad5343.gif)

Font Consolas in notepad
![issueB](https://user-images.githubusercontent.com/260343/70629080-5aa73100-1bf7-11ea-8195-bc15903c2b81.gif)

**Comment by alexdima** [comment]
@Daijobou Thank you for your quick response. Can you please open the page at https://fiddle.jshell.net/7qsktwj2/show/ in Chrome and check the rendering please

Here is how it renders for me (I am on a high DPI monitor):
![image](https://user-images.githubusercontent.com/5047891/70631996-5813fe00-1c2e-11ea-8661-0c1f88334c73.png)

That page is the run result of a fiddle I have created at https://jsfiddle.net/7qsktwj2/ . I have asked you to open it in a separate page because sometimes LCD text rendering does not work unless the page is loaded outside of an `<iframe>`. 

In any case, can you see the strangeness when you open that page in Chrome?

**Comment by Daijobou** [comment]
![image](https://user-images.githubusercontent.com/260343/70635895-aa3f2a00-1c02-11ea-95f6-1df4ec6397c6.png)

Only size 14 is strange. So I tried it in notepad.exe for font-size 14 too and there was the same issue. So that is not a monaco issue. I dont get it, why I have this crap for this character. ^^°

**Comment by alexdima** [comment]
That is bizarre...I guess there is something off with Consolas itself, I don't know. I would suggest to just switch to another font / font size ...
