### ISSUE TITLE
"The specified task cannot be tracked" after migrating extension to Webpack

### ISSUE THREAD

**Issue by ChaosinaCan** [Microsoft/vscode#72006]
- VSCode Version: 1.33.0
- OS Version: Windows 7 (6.7.7601)

Steps to Reproduce:

1. Create a TypeScript extension using `yo code` as described at https://code.visualstudio.com/api/get-started/your-first-extension
2. Follow the instructions at https://code.visualstudio.com/api/working-with-extensions/bundling-extension to migrate the extension to Webpack.
3. Press F5 to debug the extension. 

If the watch task is not already running, I get a "The specified task cannot be tracked" error. Everything seems to work correctly if I choose "Debug Anyway". If the watch task is already running when I press F5, debugging launches without error.

Does this issue occur when all extensions are disabled?: Yes

Here are the relevant portions of my extensions tasks/scripts:

extensions.json
```json
{
	"recommendations": [
		"eamodio.tsl-problem-matcher",
		"ms-vscode.vscode-typescript-tslint-plugin"
	]
}
```

launch.json
```json
{
	"version": "0.2.0",
	"configurations": [{
			"name": "Run Extension",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "${execPath}",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}"
			],
			"outFiles": [
				"${workspaceFolder}/dist/**/*.js"
			],
			"preLaunchTask": "npm: watch"
		}
	]
}
```

tasks.json
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "watch",
			"problemMatcher": [
				"$ts-webpack"
			],
			"isBackground": true,
			"presentation": {
				"reveal": "never"
			},
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```

package.json
```json
{
	...
	"scripts": {
		"vscode:prepublish": "webpack --mode production",
		"compile": "webpack --mode none",
		"watch": "webpack --mode none --watch",
		"postinstall": "node ./node_modules/vscode/bin/install",
		"test-compile": "tsc -p ./",
		"package": "vsce package"
	},
	...
}
```

**Comment by alexr00** [comment]
This question would be better asked at https://github.com/eamodio/vscode-tsl-problem-matcher
However, taking a quick look at what that extension contributes, you probably just need to use the $ts-webpack-watch problem matcher instead of the $ts-webpack problem matcher.

**Comment by ChaosinaCan** [comment]
The problem also occurs with an empty array for the problem matched. If I use $ts-webpack-watch, I don't get the error, but the debugging session never launches.

**Comment by alexr00** [comment]
If you have a background task as the prelaunchTask then it must have a watching problem matcher, which I assume the $ts-webpack-watch is. Debug will wait for the prelaunch task to "finish". A background task never finishes, so tasks uses the problem matcher to see when it has done its building and is just waiting for a file change. You can try opening the terminal that your task is running in and looking to see if it looks right. It is possible you are hitting the conptry issue and your terminal output is messed up. While the task is running, try saving one of the files that is being webpacked and check if the terminal output looks correct.

If the terminal output from the webpack watch task is correct, then the issue is likely with the problem matcher.

**Comment by ChaosinaCan** [comment]
That makes more sense. I was able to get it to work properly by switching to $ts-webpack-watch and adding `--info-verbosity verbose` to my watch script:

```json
{
	"scripts": {
		"watch": "webpack --mode none --watch --info-verbosity verbose",
	},
}
```

It would be helpful to add that info to https://code.visualstudio.com/api/working-with-extensions/bundling-extension.
