### ISSUE TITLE
Formatting on paste changed existed code format but not the new one

### ISSUE THREAD

**Issue by nyaachen** [microsoft/vscode#72036]
* default settings
* install C/C++ intellisense
* write down some complete code
* paste an incomplete code with a leading newline
    (for example you paste `\nint` and without the ending `;`, this often occurs when you meant to paste a common used long declare part and then write down the variable name, and somehow you decided to include the leading newline, often can be done by using the touchscreen to position and then pressing `Shift+up` so you selected the whole line before your cursor, and also the leading newline)
***
result:
the already existed code after your pasted code is incorrectly auto-indented

This will cause more confusing especially when you paste code with an unpaired bracelet, for example `{`, which will cause the whole indent after the code changed until the next bracelet.

This should consider a bug for the reason that once you paste uncompleted code(which can be detected easily using the intellisense), in most time you meant to modify the new codes but the existing completed ones. Unfortunately there's no way to avoid these unless you choose to disable the format-on-paste, which will lead to no indent adjusting on paste at all.

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules and only support limited code styles), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment or use auto formatting (`editor.formatOnType`, `editor.formatOnPaste`). As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like (https://github.com/microsoft/vscode/issues/19847, https://github.com/microsoft/vscode/issues/34621 or https://github.com/microsoft/vscode/issues/66235).
