### ISSUE TITLE
First F5 is a little slow because of activating some extensions

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode#72123]
First F5 to debug an existing Java debug configuration feels like a little slow. And through the status bar, vscode saying it's `Activating Extensions`. The fact is Java Debugger related extensions have been activated before clicking F5. Don't understand why vscode is still activating extensions.
![firstF5](https://user-images.githubusercontent.com/14052197/55946303-0b32ee80-5c7f-11e9-9ea0-7cee0712dc4c.gif)

The second F5 is apparently faster.

**Comment by isidorn** [comment]
@testforstephen please disable all extensions and find out which extension is slowing it down.
My guess is that one of your extensions is getting activated on a geeneric debug activation event, instead of listening on its own type like it should.
So let's first identify the eagerly activating extension and then we can file an issue against their repo

**Comment by testforstephen** [comment]
Thanks for suggestion.

It turns out it's activating the following extensions when first F5 to debug Java code.
- Server Ready Action
- [Kubernetes](https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools) (It add `onDebug` to `activationEvents` )

**Comment by isidorn** [comment]
Server ready  action is a general debug extension thus it activates for every debug type. However this extension is very light and should not slow down your F5. @weinand can provide more details if needed

As for Kuberenetes I have opened this issue in their repository https://github.com/Azure/vscode-kubernetes-tools/issues/521

Due to that lcosing this issue
