### ISSUE TITLE
auto closing pairs with conflicting patterns problems

### ISSUE THREAD

**Issue by msftrncs** [microsoft/vscode#72177]
```
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

Steps to Reproduce:

1. Create two auto closing pairs in a language configuration file,
```JSON
	"autoClosingPairs": [
		{"open": "(", "close": ")"},
		{"open": "(*", "close": "*)",  "notIn": ["string"]},
	],
```
2. trying using the two character auto closing pair, `(*` and you will get `(**))`.

On the other hand, if you remove the ending ')' from the closing '*)' you almost get normal function, except that in cases where `(` doesn't auto close with `)`, you get `(**`.

Note this condition exists in #57838, in a reference to the Structured Text Language, though it is not shown in the example on that feature request.  Reference the repository https://github.com/Serhioromano/vscode-st for some example.

I think the Auto Closing logic needs to consider when auto closing pairs might conflict with each other.  In this case, '(**)' overlaps with '()'.

**Comment by rmunn** [comment]
Another example is `[<SomeAttribute>]` in F#, where typing `[<` produces `>]]` where the closing bracket is doubled up because `[]` is also a bracket.

![Sample of doubled brackets](https://user-images.githubusercontent.com/90762/63142401-de6b5b00-c013-11e9-89ad-140a7152fb30.gif)

As you can see, the first `[` creates a matching `]`. Then when the `<` is typed, which is the second character of `[<`, the matching `>]` is inserted without considering the fact that there's already a `]` present in the file, which results in a doubled-up right bracket: `[<>]]` instead of `[<>]`.

This also happens with most F# tokens that are two or more characters, e.g. array syntax `[||]`, anonymous record syntax `{||}`, comment block syntax `(**)`, and so on.
