### ISSUE TITLE
QuickOpen should search near current file before performing a full project scan

### ISSUE THREAD

**Issue by allight** [microsoft/vscode#72170]
Quick open is nearly useless on very large projects. For example AOSP has over 1,000,000 files and when using QuickOpen (assuming the file is not recently opened) all of them will be searched. This means that the search takes >30 seconds to populate.

It would be good if (in addition to the recently used options) nearby directories were searched immediately. In my case >60% of the time the file i want is in the same directory  as the current file I'm looking at or a subdirectory and >90% of the time it's contained in the parent directory.

**Comment by roblourens** [comment]
We can't prioritize directories like this because we have to search everything then sort all of the results by their score. But results are cached after the first search.

If you are still having this issue, then the best I can offer is this wiki page for troubleshooting: https://github.com/microsoft/vscode/wiki/Search-Issues#slow-search-rg-running-for-a-long-time-or-consuming-lots-of-cpumemory
