### ISSUE TITLE
StringEditorInput cache of DebugService is seriously flawed

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#7217]
the debugStringEditorInputs cache in DebugService has the following serious problems:
- the source content is always requested from the debug adapter so there is no need for a cache,
- cache hit is determined by uri, but correct and available new content is ignored and stale content is returned instead,
- cache is not cleared when the debug sessions ends,
- cache is unbounded.

Found this when debugging https://github.com/Microsoft/vscode/issues/7117

**Comment by weinand** [comment]
@isidorn I've removed the cache for now. We should discuss why it is needed.

**Comment by isidorn** [comment]
Great job - I agree with the reasons you outlined above.

The cache was originally added because the workbench would complain if two editor models get instantiated with the same uri - there would be an error message in the console with lots of characters 'a' since @alexandrudima tries to hide sensitive uri information.

However I am no longer seeing any hickups even if we do not use a cache - thus we sometimes tell the workbench to open two different editor input objects with the same associated uris.
