### ISSUE TITLE
"/src" folder in sidebar haphazardly refuses to collapse

### ISSUE THREAD

**Issue by otse** [Microsoft/vscode#72199]
- VSCode Version: 1.33.0
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Compile your program in the terminal or do anything in the editor
2. Your /src folder should now refuse to pop

![Code_2019-04-12_12-01-24](https://user-images.githubusercontent.com/1123362/56029617-163b5c80-5d1b-11e9-91c1-8c988cac8825.png)

I have restarted vsc several times, to find it randomly refusing to collapse, or that suddenly it goes well. This bug is hard to reproduce.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by isidorn** [comment]
Can you reproduce with vscode insiders https://code.visualstudio.com/insiders/

**Comment by ilFusta** [comment]
I'm getting the same problem.

Looking at the breadcrumb I noticed that I had a file with the path starting from outside the Workspace, and when clicking on it the src folder emptied out and got stucked up until a manual refresh.

Still don't know why this file had the full path instead of the local one, but closing and reopening it, solved the problem for me.

**Comment by isidorn** [comment]
Reproducable steps please. Thanks
