### ISSUE TITLE
Terminal: Select Default Shell dosen't list Git Bash 

### ISSUE THREAD

**Issue by Wolfy7** [Microsoft/vscode#72200]
Issue Type: <b>Bug</b>

If i try to change the default shell `str + shift + P` "Terminal: Select Default Shell" dosen't list the Git Bash if its not installed in the default path ("C:\Program Files\Git") . I have Git installed on "D:\Git" i also tryed to set "D:\Git\bin" to the PATH but this dosen't help.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17763

**Git installed on: "D:\Git"**

![Select Default Shell without git bash](https://user-images.githubusercontent.com/16044116/56029537-e68c5480-5d1a-11e9-8e9b-1fd445e87de1.png)

**Git installed on: "C:\Program Files\Git"**

![Select Default Shell with git bash](https://user-images.githubusercontent.com/16044116/56029545-e8eeae80-5d1a-11e9-8e01-b323d8283f68.png)

**Comment by Tyriar** [comment]
This is by design, the command only looks at the default install directory, anything else and you'll need to configure it manually. This command is just a convenience for Windows, Linux and Mac need any shell changes to be done manually. https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration
