### ISSUE TITLE
Add option to disable line wrap on debug console

### ISSUE THREAD

**Issue by ccidral** [microsoft/vscode#72210]
The debug console wraps lines whose length exceeds the debug console panel's width. Sometimes it becomes difficult to read the debug console output when there are multiple long lines. It would be great if there was an option to disable line wrap on the debug console.

**Comment by isidorn** [comment]
This is a fair feature request.
Leaving it open to gather more feedback for now.
`debug.console.wordWrap` by default `true`

**Comment by rea725** [comment]
This is critical for certain use cases.  For instance, I do a ton of debugging in other IDEs where I ad-hoc print out formatted text tables, which are usually pretty wide.  These need word wrapping to be turned off in order to be human-readable.  This is a blocker for our entire team to fully adopt VS Code and deprecate our use of 2 other IDEs.

**Comment by isidorn** [comment]
Try it out with tomorrow's vscode insiders and let me know how it behaves 
https://code.visualstudio.com/insiders/

Verifier: make sure that debug console word wrpaing is respecting this setting.
When `debug.console.wordWrap` is `true` the debug console behaves as always (it wraps longs lines in multiple). When it is false, all long lines will always be one line and the horizontal scroll bar is shown.

fyi @weinand

**Comment by jrieken** [comment]
verified but I am not sure if it actually works...

**Comment by pixtim** [comment]
@isidorn Thanks for adding this! I can confirm that it's working.
![Screenshot from 2019-07-28 00-32-54](https://user-images.githubusercontent.com/47398076/62000082-51497c00-b0cf-11e9-8f55-1d619e999a45.png)
