### ISSUE TITLE
VS Code Does Not Open Ubuntu 18.04 VM

### ISSUE THREAD

**Issue by t-mccawley** [microsoft/vscode#72214]
- VSCode Version: ?
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Install snapd `sudo apt install snapd`
2. Install VS Code `sudo snap install --classic code`
3. Attempt to open code.

Does this issue occur when all extensions are disabled?: Yes

VS Code will not open via code command nor icon. When I run `code --version` I receive the following message:
`/snap/code/6/electron-launch: line 28: /snap/code/6/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders: No such file or directory
/snap/code/6/usr/share/code/bin/code: line 35: /snap/code/6/usr/share/code/bin/../code: No such file or directory`

However, the file `/snap/code/6/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders` definitely does exist.

**Comment by Kedstar99** [comment]
Is snapd running without errors?

Does the following command come back with active without any errors?
sudo service snapd status

**Comment by StoicLobster** [comment]
@Kedstar99 snapd version is 2.37.4+18.04.1

Here are my results from `sudo service snapd status`

`● snapd.service - Snappy daemon
   Loaded: loaded (/lib/systemd/system/snapd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-04-12 20:29:29 PDT; 46s ago
 Main PID: 664 (snapd)
    Tasks: 15 (limit: 9492)
   CGroup: /system.slice/snapd.service
           └─664 /usr/lib/snapd/snapd

Apr 12 20:29:32 kinetic-vm snapd[664]: snapmgr.go:247: cannot read snap info of snap "gtk-common-themes" at revision 1198: can
Apr 12 20:29:32 kinetic-vm snapd[664]: snapmgr.go:247: cannot read snap info of snap "gnome-3-26-1604" at revision 82: cannot 
Apr 12 20:29:32 kinetic-vm snapd[664]: snapmgr.go:247: cannot read snap info of snap "gnome-3-28-1804" at revision 23: cannot 
Apr 12 20:29:33 kinetic-vm snapd[664]: storehelpers.go:445: cannot refresh: snap has no updates available: "code", "code-insid
Apr 12 20:29:33 kinetic-vm snapd[664]: snapmgr.go:247: cannot read snap info of snap "gtk-common-themes" at revision 1198: can
Apr 12 20:29:33 kinetic-vm snapd[664]: snapmgr.go:247: cannot read snap info of snap "gnome-3-28-1804" at revision 23: cannot 
Apr 12 20:29:33 kinetic-vm snapd[664]: snapmgr.go:247: cannot read snap info of snap "gnome-3-26-1604" at revision 82: cannot 
Apr 12 20:29:33 kinetic-vm snapd[664]: snapmgr.go:247: cannot read snap info of snap "core" at revision 6673: cannot find inst
Apr 12 20:29:33 kinetic-vm snapd[664]: autorefresh.go:387: auto-refresh: all snaps are up-to-date
Apr 12 20:29:33 kinetic-vm snapd[664]: snapmgr.go:247: cannot read snap info of snap "core" at revision 6673: cannot find inst`

Seems like some errors but im not really sure what to do with them.

**Comment by Kedstar99** [comment]
@t-mccawley I'm not sure what is happening and it looks to somewhat be related to your snap installation going hay-wire. In this case, errors appear to be showing for 'core' etc...

One thing that is worth a try is simply to update your VM as snapd version 2.38 is the current release version. After this, I would post on snapcraft forums as again this doesn't seem to be specific to vsccode.

**Comment by abrcdf1023** [comment]
I had the same issue. Fixed by this
`snap refresh`
