### ISSUE TITLE
Support custom icons in status bars

### ISSUE THREAD

**Issue by OmarTawfik** [microsoft/vscode#72244]
## Problem

Extension writers have no way to put custom icons inside a `StatusBarItem`. They are confined to use the limited octicons set provided by GitHub, and cannot use language or engine specific icons.

## Existing Workaround 

Octicons are handled/rendered separately by this [class](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/octiconLabel/octiconLabel.ts), and the icon is specified in the status bar in the following manner:

```ts
statusBarItem.text = "$(icon-name) some text";
```

## Proposal

Enable a way for users to specify paths to custom icons in the text. I'm open for suggestions on what syntax it can use. One backward-compatible example can be:

```ts
statusBarItem.text = "$(custom:path/to/icon.svg) some text";
```

This enables authors to truly indicate what extension owns which status bar item, instead of having to specify that by either using text (which takes up precious status bar space), or using the limited set of octicons (which can be rather confusing).

I can go ahead and look into prototyping it following the example of octicons if there is an agreement on the syntax/proposal. 

cc @bpasero since you're active on all the status bar/theming issues I read today 😄

**Comment by jrieken** [comment]
cc @bpasero

**Comment by OmarTawfik** [comment]
@bpasero  any thoughts on this?

**Comment by OmarTawfik** [comment]
@bpasero any thoughts on this?

**Comment by OmarTawfik** [comment]
@jrieken looks like @bpasero is OOF :( Is there another POC to review it?

**Comment by bpasero** [comment]
@OmarTawfik I am not OOF, but with [>3000 feature requests](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request) open please bare with us if we are not giving our reply to each message we get in timely manner.

As for your question, my thoughts are that this makes sense in the same way we allow icons to be provided by an extension for actions elsewhere. The challenge here maybe is that statusbar icons should be monochromatic because you can set foreground color on them. In other words, they should be different from icons provided for actions.

**Comment by waleedalikhan** [comment]
Me too in the favour of this, would be great if we can do at as bellow 
`statusBarItem.text = "$(custom:path/to/icon.svg) some text";`

**Comment by bpasero** [comment]
There is a ton of new icons that can be used given @misolori work, closing.
