### ISSUE TITLE
Highlight currently open editor window in search results panel

### ISSUE THREAD

**Issue by Eiskis** [Microsoft/vscode#72324]
When using project-wide search to find code that needs editing, I might get a list of search results like this:

<img width="336" alt="Screenshot 2019-04-15 at 11 04 19" src="https://user-images.githubusercontent.com/1101002/56120358-40d12380-5f6e-11e9-8048-3a69e78c9d49.png">

I'm making bulk edits to my codebase by going through each search result, scrolling the file up and down and making my edits and then moving to the next one. When I select a search result, it will be highlighted, but as I start editing the file, this highlight disappears. After I'm done, I have to tell which file and/or search result I opened so I can move on to the next one.

If you're replacing the piece of code being used, it will disappear from the panel of course, but if I'm making other edits (let's say changing some parameters/attributes or editing imports at the top of the file), then the search result list will stay as it was.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1101002/56121318-28620880-5f70-11e9-8bc2-dd6867adb70d.gif)

As I'm going through each file in a sequence, I noticed it can be really hard to pinpoint which file you just selected. In this gif, which file am I editing? As you work in the editor view, you might have more tabs open, some files have the same filename etc. You have to very carefully reference the editor view to figure out which file you're editing. To make sure, you can click open the search result you think you're editing, but if you have to scroll the editor to find your edits, it gets tricky.

As a result, it takes a lot of effort to A) find the next file in the sequence, B) not select the current file again and C) make sure you're not skipping a file in the sequence.

**To solve this**, we could simply highlight the currently open file the same way as explorer does it.

**Comment by roblourens** [comment]
It looks like your theme does not have an appropriate inactive selection color. Otherwise, the selected row would be focused while you are editing. The selection is still there, just not visible in your theme.

Because of this, I don't want to do what the explorer does and move the user's focus. That would be very annoying.

**Comment by Eiskis** [comment]
I tried it with multiple themes, it's not theme related. The highlight is fine when I first select the search result, but disappears once I start editing.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1101002/56194325-04b3c680-6033-11e9-88bd-a894647f722d.gif)

Here's how it looks with the default light theme, maybe you can see it better.

**Comment by roblourens** [comment]
The fact that focus is lost when you make some edits is due to another issue: https://github.com/Microsoft/vscode/issues/20467 

Also we don't really have a way to highlight a row in the search results without moving the tree "selection". Only one thing can be selected at a time. I think when #20467 is fixed then you would basically have the behavior you want.
