### ISSUE TITLE
Add `Restart Build Task` action

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7236]
We need a `Restart Build Task` action.

**Comment by dbaeumer** [comment]
@joaomoreno others suggested that I should add a flag the Ctrl+Shift+B restarts if already started. They don't want to learn a new short cut. Would that solve your problem ?

**Comment by joaomoreno** [comment]
Yep!

**Comment by dbaeumer** [comment]
OK. Thinking about it again autorestart is a bad idea for watching tasks which have a lot of state. So I will do the following:

- if a task is already running and Ctrl+Shift+B is pressed then I only show an information that auto hides
- will add a restart action.

**Comment by dbaeumer** [comment]
I implemented the first bits. (Not showing an annoying message if the task is running). The second part is still not nice. Do we need a Restart current task or Restart build, Restart test, ...

Ideas?

**Comment by dbaeumer** [comment]
See discussion in #6578

**Comment by dbaeumer** [comment]
Moving to August since I will be out on vacation in July.

**Comment by thomas-darling** [comment]
@dbaeumer Actually, I think the previous behavior was a lot better.

In the latest release, if I press `Ctrl + Shift + B` while a watch task task is running, it just shows a useless notification with a `Close` button and nothing else. Previously it had a `Terminate task` button, which was actually quite handy.

The only annoyance was, that restarting a task would require me to press `Ctrl + Shift + B` twice - first to get the notification so I could click `Terminate task`, and then again to restart it. But that could be easily fixed - simply add a `Restart task` button to the notification - clean and simple :-)

Adding a new command for restarting the task seems like a bloated solution - it's just more stuff to remember. The old solution was perfect, it just needed a  `Restart task` button in the notification.

Personally, I also quite liked that pressing `Ctrl + Shift + B` would open the `Output` panel - it was really handy for quickly seeing build errors. That's something I can live without though - but I do miss it.

**Comment by dbaeumer** [comment]
@thomas-darling interesting. I got the opposite feed back from other people basically being annoyed by the message and being force to click the Close box since they forgot that the task is already running. The message I now show is auto closing. So no need to press the close button.

I need to rethink the whole story here. May be it is better to have a clear status bar indication about the state of the task runner and not use messages. We could even had some action there.

**Comment by dbaeumer** [comment]
Was busy adapting TS 2.0.6. Moving to November.

**Comment by dbaeumer** [comment]
We decided to totally rework the way the task running system work and especially how Ctrl+Shift+B is handled (Build). See the discussion started here: #15179. To avoid unnecessary work I will merge this with the work planned for January to implement #15179.

**Comment by dbaeumer** [comment]
I re-implemented the task execution engine for Jan to use the terminal instead of the output window. Although not the default yet I will wait until the switch is final to provide a restart build action. With the new engine this needs more thinking since the new engine support executing tasks in parallel. It will also support composing build task out of smaller tasks.

**Comment by dbaeumer** [comment]
Implemented for March. For the old output based task runner it simply restarts the current running task. For the new terminal based runner it shows a list of the running tasks and asks which one to restart.
