### ISSUE TITLE
Settings Editor (User) always shows defaults

### ISSUE THREAD

**Issue by tlgreg** [Microsoft/vscode#72385]
Issue Type: <b>Bug</b>

User Settings always shows the default settings for me. If I try to open the JSON file from the Settings Editor it throws an error: "Invalid folder URI - 1"

Tried to reinstall VSCode Insiders and deleted both `%USERPROFILE%/.vscode-insiders` and `%APPDATA%/Code - Insiders` but the issue persists with a fresh install. Nothing changed on my end with the system, it might started one of last week's later insiders updates (04.11-12 maybe).

Opening the JSON file directly from the commands has no problems, it finds the file, stored settings are working, the problem only shows up in the Settings Editor view.

VS Code version: Code - Insiders 1.34.0-insider (4f212683c16977661ad51f8d13957de9d3280b30, 2019-04-15T10:39:37.369Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Phenom(tm) II X6 1055T Processor (6 x 2812)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|8.00GB (2.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by taosx** [comment]
Same error here, exact same system and state.

VS Code version: 1.34.0-insider (user-setup)
Commit: 8b5ebbb1b

System: Windows 10 Enterprise.

**Comment by roblourens** [comment]
Is this in an empty window (without a folder open)?

Saw this on @Tyriar's machine too...

**Comment by roblourens** [comment]
I can't reproduce this

**Comment by tlgreg** [comment]
One more observation:
In a freshly loaded window, the settings editor opens without the issue. But if I close it and try to open again the issue persists until a reload. It doesn't seem to matter if a folder is open or not.
When the settings editor does open with the user settings the devtools logs a warning:
`workbench.main.js:1399  WARN SettingsEditor2: Settings not included in settingsLayout.ts: remote.extensionKind`

**Comment by selfrefactor** [comment]
Have the same issue with Ubuntu 19.04

**Comment by roblourens** [comment]
I still haven't seen this myself, but my fix for https://github.com/Microsoft/vscode/issues/72719 might fix the same thing.

**Comment by IllusionMH** [comment]
@roblourens this issue is still reproducible in Insiders builds.
In my case it's just `Ctrl + Shift + P` and picking `Preferences: Open User Settings`.
As I can see - User "subtab" is not selected (I will also see nothing with `@modified` or will get `Invalid folder URI - 1` clicking on `{}` button ).
Everything works fine as soon as I click on User or Workspace.

Another one observation:
1. `Ctrl + Shift + P` and pick  `Preferences: Open Workspace Settings`
1. Observe that Workspace "subtab" is active (highlighted underline, `@midified` works as ecpected etc.)
1. While in Settings tab `Ctrl + Shift + P` and pick  `Preferences: Open User Settings`
1. Highlight is removed from Workspace "subtab" (nothing works)

So as for me it looks like `Preferences: Open User Settings` command doesn't select correct subtab.

VS Code version: Code - Insiders 1.34.0-insider (6b2daa3388c0692fad64a32040812c27414b1385, 2019-04-23T05:22:56.435Z)
OS version: Windows_NT x64 10.0.17763

**Comment by roblourens** [comment]
Oh, I see it thanks

**Comment by SuperV1234** [comment]
I can still reproduce this with `code-insiders_1.34.0-1556688342_amd64.deb`.

**Comment by roblourens** [comment]
The issue that I was trying to fix is fixed. If you still see a problem, could you open a new issue with exact steps?
