### ISSUE TITLE
1.33 go to definition not working

### ISSUE THREAD

**Issue by mzvast** [Microsoft/vscode#72461]
v 1.33 go to definition not working anymore.
downgrade to v1.32 works fine.

macOS.

**Comment by nadbm** [comment]
Same, just downgraded now, and it works again for me

**Comment by octref** [comment]
I assume this is JS/TS? Can you post a repro case?

**Comment by kaushall** [comment]
'Go to Definition' not working after recent update of VSCode 1.33.1

Environment data
VS Code version: 1.33.1
Extension version (ms-python.python): 2019.3.6558
OS and version: Ubuntu 18.04
Python version (& distribution if applicable, e.g. Anaconda): 2.7.15
Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv

Expected Behaviour:
Visual Studio Code navigate to the definition of the function which resides inside the workspace (Working fine earlier)

Actual Behaviour:
Popup with Message: "No definition found for 'function_name' "

But if you hover the implementation then it will show you the class with function name and all the parameters of the functions that are requested in definition of the function. It's also suggesting the function while implementing. So maybe there is some issue with only "Go to Definition".

Things I've tried:
Tried to reinstall the python extension (ms-python.python) >> Not worked
Tried to install earlier versions of the python extension (ms-python.python) >> Not worked
Closing all the files and reopening of the workspace >> Not worked
Opening the definition file in new tab and tried "Go to definition" >> Not worked
Tried to downgrade VS Code to earlier versions 1.32 and 1.31 >> Not worked

@octref @nadbm Please suggest any solution.

**Comment by octref** [comment]
@kaushall Report issue to ode-python

**Comment by kaushall** [comment]
@octref I'm unable to find any user with username 'ode-python'

**Comment by octref** [comment]
Sorry, I meant https://github.com/Microsoft/vscode-python/issues

**Comment by kaushall** [comment]
@octref Thanks, I've opened new issue [#5425](https://github.com/Microsoft/vscode-python/issues/5425)

**Comment by mjbvz** [comment]
Closing this as steps to reproduce this and information about what does not work are needed from the original poster

**Comment by mzvast** [comment]
I'm using with create-react-app and typescript.
When the file is too many (250 files+) and the function died.
