### ISSUE TITLE
Terminal expands when npm script run

### ISSUE THREAD

**Issue by leegee** [Microsoft/vscode#72473]
Issue Type: <b>Bug</b>

1. Use 'npm scripts' to run a task that does not exit (ie webpack-dev-server)

2. Split the terminal into two

3. Restart the npm script 

4. The terminal covers the split view

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (10.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
npm-intellisense|chr|1.3.0
vscode-eslint|dba|1.8.2
githistory|don|0.4.6
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
rainbow-csv|mec|1.0.0
dotenv|mik|1.0.1
vscode-typescript-tslint-plugin|ms-|1.0.0
vetur|oct|0.18.1
RustyCode|sav|0.19.1
sort-lines|Tyr|1.8.0

(1 theme extensions excluded)

</details>

**Comment by leegee** [comment]
Behaviour is the same without 'vscode-npm-script' installed.

**Comment by alexr00** [comment]
This is what I tried:
1. Start a script that doesn't exit from the NPM Scripts view
2. Split the terminal that the script is running in.
3. Run the Restart Running Task command from the command palette. 

What I saw was that the task was killed (good), and then the task was started in a new terminal (also good). Since the task was killed, the terimal it was running it was killed, forcing the task to run in a new terminal. This is correct and by desgin.
