### ISSUE TITLE
Debug buttons disappearing on touch bar (macbook pro)

### ISSUE THREAD

**Issue by dmvvilela** [Microsoft/vscode#72493]
I am using Flutter FRamework, and since the update with new buttons (devtools and etc) all the buttons disappear when i am on a breakpoint..

![photo_2019-04-17_09-11-24](https://user-images.githubusercontent.com/8460696/56286779-f3c98a80-60f0-11e9-927b-f0c5fe251d83.jpg)

This bug was issued first at flutter @DanTup 

- VSCode Version:  1.33.1 (1.33.1)
- OS Version: macOS Mojave 10.14.4 (macbook pro 2017)
- Flutter Version: 1.4.9 Hotfix 1

**Comment by DanTup** [comment]
Based on a similar issue at https://github.com/Microsoft/vscode/issues/66689, my guess is that the extra buttons Flutter adds are resulting in the buttons being too wide, and they're being pushed down.

I can't repro this, but I don't have the buttons on the right (brightness etc.), I'm not sure why.

Assuming it is due to the width, I don't think the extension can fix this, since it has no idea how many buttons there are (other extensions can contribute them too, and seemingly the OS ones on the right are optional) so I think it's either a VS Code or Electron issue (I'm not familiar with how it's rendered).

**Comment by DanTup** [comment]
@dmvvilela in the meantime, I guess you could disable the control strip (see https://github.com/Microsoft/vscode/issues/68214#issuecomment-462025149), or if you'd like to keep that, we could add options to the Dart/Flutter extensions to control which items appear (if you want this, open an issue in Dart-Code and I'll take a look soon).

**Comment by dmvvilela** [comment]
There is no option to turn it into a "list view" kind of thing with dragging left to see more buttons?

**Comment by DanTup** [comment]
@dmvvilela extensions like Dart-Code have no control over how they appear at all - the only thing we can do is request buttons are shown for commands (we can either have text or icons, but I don't think there are obvious icons for either DevTools or Screenshot and there are no tooltips!). VS Code has a little more control, though based on the linked issue above, it sounds like it also has some issues that would need to be resolved by Electron.
