### ISSUE TITLE
Opening from the command line will always open “cli.js” automatically

### ISSUE THREAD

**Issue by linwrui** [microsoft/vscode#72521]
- VSCode Version: 1.33.1
- OS Version: Windows 10

Steps to Reproduce:

1.Open powershell.
2.Execute command "Code [any file path]
3.Wait for vsCode opening
4."cli.js" is opened automatically,and I don't know why.
![image](https://user-images.githubusercontent.com/22316156/56330573-335ca900-61bb-11e9-82cc-9a103768d6c5.png)

**Comment by joaomoreno** [comment]
Can you show me your `PATH` variable?

**Comment by linwrui** [comment]
![image](https://user-images.githubusercontent.com/22316156/57344467-ecd6ea80-7179-11e9-8d55-e1a9fd7a10ec.png)

**Comment by linwrui** [comment]
> Can you show me your `PATH` variable?

![image](https://user-images.githubusercontent.com/22316156/57367221-2e3bba00-71bb-11e9-94cb-c2366a1978d6.png)

**Comment by joaomoreno** [comment]
Please run `echo %PATH%` in the Command Prompt.

**Comment by linwrui** [comment]
> Please run `echo %PATH%` in the Command Prompt.

I found this to be true only when VSCode is started in administrator mode.

**Comment by joaomoreno** [comment]
Can you show me your `PATH` variable? Please run `echo %PATH%` in the Command Prompt.

**Comment by mosor** [comment]
This has been happening to me. It happens when I open VSCode from the command line and I have VSCode set to run as admin. Here is my path:
`D:\Apps\cmder\bin;D:\Apps\cmder\vendor\bin;D:\Apps\cmder\vendor\conemu-maximus5\ConEmu\Scripts;D:\Apps\cmder\vendor\conemu-maximus5;D:\Apps\cmder\vendor\conemu-maximus5\ConEmu;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Users\mosor\AppData\Local\Programs\AdoptOpenJDK\bin;C:\Users\mosor\AppData\Local\Microsoft\WindowsApps;C:\Users\mosor\.dotnet\tools;C:\Users\mosor\AppData\Local\Programs\Microsoft VS Code\bin;D:\Apps\cmder\vendor\git-for-windows\cmd;D:\Apps\cmder\vendor\git-for-windows\mingw64\bin;D:\Apps\cmder\vendor\git-for-windows\usr\bin;D:\Apps\cmder`

**Comment by LonelySteve** [comment]
我也一样。或许你应该尝试一下把VSCode的路径放到`PATH`变量的首部

Me too. Maybe you should try putting the path of VSCode at the head of the `PATH` variable.

**Comment by mosor** [comment]
Moving the path variable does not make a difference. The 'cli.js' file still opens.

**Comment by mosor** [comment]
I think I figured out a fix for anyone else facing this problem. If you run the command prompt as administrator, this problem goes away. It's only an issue if you have VSCode set to run as admin, but the command prompt terminal is not running with admin permission.
