### ISSUE TITLE
I love vscode but the codelens drives me nuts

### ISSUE THREAD

**Issue by dagda1** [Microsoft/vscode#72528]
-  Version 1.33.1 (1.33.1)
- OS Version: MAC OS 10.14.4

Steps to Reproduce:

1. select goto definition of a typescript symbol and it shows the horrible codelens viewer with the index.d.ts file as an option

For example:

![codelens](https://user-images.githubusercontent.com/118328/56339604-cd662680-61a6-11e9-9d18-d5a004292579.png)

I have tried disabling every conceivable codelens setting:

```
  "javascript.referencesCodeLens.enabled": false,
  "typescript.referencesCodeLens.enabled": false,
  "editor.codeLens": false,
  "merge-conflict.codeLens.enabled": false,
  "typescript.implementationsCodeLens.enabled": false,
```

I absolutely love VSCode but I cannot disable this thing no matter what I try.

**Comment by yume-chan** [comment]
That is NOT CodeLens

![image](https://user-images.githubusercontent.com/1330321/56343682-ff4eab80-61ed-11e9-9595-4daa6a7ad053.png)

This is.

----

That is called "peak view", and can be turned off by `"editor.gotoLocation.multiple": "goto"`, but I'm not sure Code will goto which definition by default for that.

----

It's caused by your specific coding style: when you write

```js

interface Invokeable {
    (): number;
}

const func: Invokeable = () => 42;

func();

```

And invoke Go To Definition on `func()`, Code will search definitions for both `func` itself and `func()` function call. As Code can find both, it will provide you multiple results to choose.

**Comment by dagda1** [comment]
@yume-chan thank you. this really ruins vscode and I am not alone in thinking this.  

What I would really like is for it to ignore definition files, it is like a zombie I cannot slay.  It just appears time and time again and never when I want it.

**Comment by dagda1** [comment]
this is just the latest incarnation of me trying to disable this annoying code window.

**Comment by octref** [comment]
`"editor.gotoLocation.multiple": "goto"` should solve your problem.
