### ISSUE TITLE
Debug: can add multiple inline breakpoints at the same position?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#72545]
Proof:

![before](https://user-images.githubusercontent.com/900690/56360356-af1f1b80-61e4-11e9-9e51-7ad6da6721e3.gif)

**Comment by weinand** [comment]
@isidorn since we are not allowing this for line breakpoint, we shouldn't do this for column breakpoints.

**Comment by isidorn** [comment]
The issue here is that the brekapoint gets moved by the debuger, thus when I compare the column I get fooled.

**Comment by weinand** [comment]
The same is true for line breakpoints.

**Comment by isidorn** [comment]
Pushed a fix, but please note that I prevent adding 2 breakpoints at the same line / column.
However it might happen that a user adds two inline breakpints at different postisions and they still get mapped to the same spot by the debug adapter. That I allow, and for that I do not de-dupe. I think this makes sense because user explicitly added two breakpoints at different locations, but just at runtime they get mapped to the same position.
