### ISSUE TITLE
Support Mac movement/navigation conventions

### ISSUE THREAD

**Issue by clarkcox3** [microsoft/vscode#7255]
- VSCode Version: 1.1.1
- OS Version: MacOS 10.11.5 (15F34)

It would be useful if Mac navigation conventions were supported (optionally, of course. I understand people are equally tied to the Windows conventions)

Namely:
- Page Up and Page Down scroll _without moving the cursor_
- Home and End scroll to the beginning and end of the document respectively, also without moving the cursor (as opposed to the Windows convention of moving the cursor to the beginning and end of the _line_)

**Comment by alexandrudima** [comment]
@clarkcox3 You can get this behaviour for page up and page down by editing the `keybindings.json`:

```
{ "key": "pagedown", "command": "scrollPageDown", "when": "editorTextFocus" },
{ "key": "pageup", "command": "scrollPageUp", "when": "editorTextFocus" }
```

I don't think we have commands that scroll to the beginning/end of the document that you can easily bind to.

**Comment by mcdado** [comment]
Sorry to comment on such an old Issue, but I am looking for a way to do this:

| Shortcut | Description |
|-|-|
| Fn–Left Arrow | Home: Scroll to the beginning of a document. |
| Fn–Right Arrow | End: Scroll to the end of a document. |

Source: [Mac keyboard shortcuts - Apple Support](https://support.apple.com/en-us/HT201236)

I saw that [it was proposed](https://github.com/Microsoft/vscode/issues/15401) to switch to the Windows-style of moving to the beginning or end of the line, instead of scrolling (without moving the cursor) like it happens on macOS, but ultimately it was rolled back. That doesn't look like the case to me.

Maybe it should behave differently on the two platforms?
