### ISSUE TITLE
Support consistent keybindings across all platforms.

### ISSUE THREAD

**Issue by ssylvan** [microsoft/vscode#72593]
I use VS Code on three platforms: windows, linux and mac. I currently have to learn three slightly different sets of key bindings, and make constant mistakes when I switch between machines. 

It would be far preferable if I could choose one of them and use the same one on all machines, regardless of the OS. E.g. I could choose to use the windows key bindings even though I'm on Mac, etc. 

Maybe one way to solve this is to put all the "default" keybindings in the extension marketplace (with each platform installing the one for that platform by default). That way I can just choose to install the default key binding for a different platform and get it that way.

**Comment by alexandrudima** [comment]
We have arrived at our keybindings by really trying to make them consistent across platforms.

e.g. We implemented replace in file, we have given it Ctrl+H on windows, but the natural choice Cmd+H on mac is occupied by the OS hide window, so we looked around at what other (text/code) editors have for replace and we arrived at Cmd+Option+F for it. As you can imagine, this in turn can cause another conflict if we were to bind something to Ctrl+Alt+F on Windows (...which we don't at the moment...)

Another reason for divergencies is really really strong OS expected keybindings. For example, on the mac, it is expected that all apps quit with Cmd+Q, and that Cmd+W closes a tab... so we really had to add them... This in turn caused further conflicts...  

AFAIK, all the divergences were caused by OS conflicts or really strong OS key-memory and none were intentionally introduced. So, the default keybindings are in fact the closest we could get to having consistent keybindings across all platforms.
