### ISSUE TITLE
Shortcut key for Explorer (Ctrl + Shift + e) is not working

### ISSUE THREAD

**Issue by kmrmukesh1704** [Microsoft/vscode#72642]
Issue Type: <b>Bug</b>

Whenever I use Shortcut key for Explorer (Ctrl + Shift + e), it toggles the letter e, instead of explorer

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 5.0.0-13-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.68GB (2.27GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-javascript-snippet-pack|aka|0.1.5
project-manager|ale|10.5.1
vscode-intelephense-client|bme|1.0.13
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer-2|Coe|0.0.28
vscode-eslint|dba|1.8.2
vscode-npm-source|dku|1.0.0
docs-markdown|doc|0.2.4
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|2.2.1
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.8.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-mysql|for|0.4.0
search-node-modules|jas|1.3.0
sublime-babel-vscode|jos|0.2.10
php-cs-fixer|jun|0.1.118
node-module-intellisense|lei|1.5.0
HTMLHint|mka|0.6.0
vscode-cosmosdb|ms-|0.10.1
azure-account|ms-|0.8.2
debugger-for-chrome|msj|4.11.3
advanced-new-file|pat|1.2.0
material-icon-theme|PKi|3.7.0
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
code-settings-sync|Sha|3.2.9
markdown-preview-enhanced|shd|0.3.13
stylelint|shi|0.49.0
vscode-fileutils|sle|2.13.5
vs-code-node-require|tgr|1.4.0
bootstrap4-vscode|the|6.1.0
highlight-matching-tag|vin|0.9.1
vscodeintellicode|Vis|1.1.5
change-case|wma|1.0.0
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.7.2
markdown-all-in-one|yzh|2.2.0

(1 theme extensions excluded)

</details>

**Comment by mkasprz** [comment]
I've got the same issue. What's more, when I tried to "Record Keys" the "e" got recognized as "unknown"...

Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-47-generic

**Comment by phil294** [comment]
I can confirm this issue. If I am not mistaken, it used to work with previous update. Not sure though :/ can test if desired.

This bug already existed and was fixed afterwards: #48480. See this thread, there are ways to fix it described. For me, it was running code with environment variable `GTK_IM_MODULE="xim"` set.

**Comment by mkasprz** [comment]
Thank You @phil294, Your solution (or workaround rather?) worked for me.

**Comment by isidorn** [comment]
Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/

**Comment by msponer** [comment]
This bug is present on vscode insiders.

The `GTK_IM_MODULE="xim"` environment variable does not work on my Ubuntu 19.04 system.

VS Code version: Code - Insiders 1.34.0-insider (0fde6619172c9f04c41f2e816479e432cc974b8b, 2019-04-25T05:14:57.241Z)
OS version: Linux x64 5.0.0-13-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2011)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.56GB (0.83GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by NorWilhelm** [comment]
Same here, running Ubuntu

**Comment by helmisatria** [comment]
same here, ubuntu 19.04

**Comment by scalavision** [comment]
same here, on nixos
