### ISSUE TITLE
eslint.fixAllProblems introduced in vscode v1.2 not fixing all problems

### ISSUE THREAD

**Issue by nwayve** [Microsoft/vscode#7265]
- VSCode Version: 1.2
- OS Version: Windows 10.0.10586

https://code.visualstudio.com/updates#_linters

Haven't tested this exhaustively tried out this feature and found that it fixed some issues but not others.  One issue is with the `(key-spacing)` rule.

Steps to Reproduce:
1 `.eslintrc` file local to project (at root):
```json
{
    "env": {
        "es6": true,
        "node": true,
        "mocha": true
    },
    "parserOptions": {
        "sourceType": "module"
    },
    "rules": {
        "key-spacing": 2,
        "semi": 2
    }
}
```
2 `test.js` file before:
```javascript
var foo = {
    bar:'key-spacing'
}
```
3 Trigger fix all: `shift + ctrl + alt + f`
4 `test.js` file before:
```javascript
var foo = {
    bar:'key-spacing'
};
```
Semi-colon added but space after property name's colon not added.

**Comment by dbaeumer** [comment]
Actually the action fixes all auto-fixable problems as defined by eslint (see http://eslint.org/docs/rules/). The action is clear in the UI, but not in the command name since the name sounded very long. We will update the documentation to explain this.

There is nothing VS Code can do since the rule is not auto fixable in eslint itself. Closing the issue.

**Comment by nwayve** [comment]
Didn't even think about that.  Makes sense.  Thanks for looking into this.
