### ISSUE TITLE
Merging selectionRangeProviders create inconsistent selection hierarchies

### ISSUE THREAD

**Issue by matklad** [microsoft/vscode#72679]
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.19.34

I am implementing the new selectionRange LSP extension. It works nicely, except for one issue: VSCode merges ranges from built-in provider with ranges provided by the server.

The resulting hierarchy violates the property that each subsequent range is larger than the previous one. Specifically, VS Code prefers to first select a line, and then switches semantic selection of the expression. Here's a video where I use expand/shrink selection:

https://youtu.be/YDhnrwiTLwA

cc @jrieken

**Comment by jrieken** [comment]
> The resulting hierarchy violates the property that each subsequent range is larger than the previous one.

That shouldn't happen. Can you attach the file (in source) and the data (JSON string) that you are sending?

**Comment by matklad** [comment]
@jrieken see https://gist.github.com/matklad/996aecf3e074633436e25bdcbbbaac84

Note that file contains leading whitespace, whihc makes vscode first to select the whole line (with leading ws), and then both lines with function, *without* leading ws.

**Comment by matklad** [comment]
and here's a sequence of selections I am seeing. The penultimate one is wrong

![image](https://user-images.githubusercontent.com/1711539/56581699-35b96b80-65de-11e9-82f1-81a0a8bbf1da.png)

![image](https://user-images.githubusercontent.com/1711539/56581714-3f42d380-65de-11e9-9579-4f7456a980e0.png)

![image](https://user-images.githubusercontent.com/1711539/56581729-48cc3b80-65de-11e9-83a7-3a3dac2ba91a.png)

![image](https://user-images.githubusercontent.com/1711539/56581734-4ec21c80-65de-11e9-8fe0-c59c74929e80.png)

![image](https://user-images.githubusercontent.com/1711539/56581750-55509400-65de-11e9-89f8-3411dcec53a5.png)

**Comment by Krzysztof-Cieslak** [comment]
I can reproduce the same with my SelectionRange provider - also one action that's not shown in above screenshots in mid-word selection which is always happening every time, even if such range is not returned by provider

**Comment by jrieken** [comment]
Likely fixed by https://github.com/microsoft/vscode/pull/73850

**Comment by jrieken** [comment]
@matklad I have tried to incorporate you data from https://gist.github.com/matklad/996aecf3e074633436e25bdcbbbaac84 but I have trouble understanding them. From the screen shots it seems you start at `|fn` (0,1) but your first range is at (0,4-0,4), then you expand to (0,4-0,6) (_mai_n), then to (0,4-1,4), and last everything. 

Is this maybe a different trace? Is your intend not to select the `fn ` part? Can you try this with next (likely Monday's) insider build, I have confidence that this is fixed in master (#73850)

> in mid-word selection which is always happening every time, even if such range is not returned by provider

@Krzysztof-Cieslak That's to be expected as we do some default expansions. The idea behind that is to have a uniform feel to this feature. Defaults are in-word/word expansion and whitespace (leading/trailing) expansions

**Comment by matklad** [comment]
@jrieken The code is indented by four spaces, so `|fn` is (0,4), not (0,1) (and that makes me realise I could have used a better example).

I am also pretty confident that this is fixed on master, so let's close this issue optimistically, and I'll reopen if the insiders doesn't fix it.

**Comment by mjbvz** [comment]
Marking this as verified based on @matklad's comment
