### ISSUE TITLE
Cannot go to definition

### ISSUE THREAD

**Issue by Swazimodo** [Microsoft/vscode#72713]
Issue Type: <b>Bug</b>

When I try to go to the definition of a react component from the import nothing happens. If I try to go there from my actual usage of the component it only will go up to the import. However, I have no errors displayed that would indicate that the import was not working.

I tried refactoring the import path to be relative instead of drilling down from `src/` and then I was able to jump to the definition. Using the full path does not seem to cause any build errors but just makes vscode not be able to follow the links. Is there a solution to this? I do not like being forced to use relative links as they are not as easy to read and it can cause issues when you need to refactor your project structure.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.8.2
gitlens|eam|9.6.3
vsliveshare|ms-|1.0.67
indent-rainbow|ode|7.4.0
vscode-import-cost|wix|2.12.0

</details>

**Comment by ChuckyHelse** [comment]
Hello !

Since I've upgraded to 1.33, the same problem appears with C++ source code as well (using Microsoft add-on). I guess this is a regression in the Visual Studio Code framework where IntelliSense plugs in more than in the language server itself.

#### Reproduction scenario
I've noticed that it is more likely to happen when I type in wrong code (ex: containing syntax errors) and triggers the auto-completion. After this, even when the syntax gets fixed (proven by a successful compilation with cl.exe), the _Go to definition_ contextual entry does not work any more.

#### Possible cause
What I suspect is a _misalignment_ between the _clicked-on token_ and the _token being analysed_ by the contextual menu. I am thinking this way because I noticed that while some token definitions cannot be retrieved (or the wrong file source gets opened, like the HPP instead of the CPP) the definition of tokens before the faulty one gets resolved correctly.

Thanks for your support,

Chucky

**Comment by mjbvz** [comment]
@Swazimodo Can you please share more information about your project and the file you are trying to run go to definition in, or the project itself if possible?

**Comment by Swazimodo** [comment]
It is a react project and it will not f12 to the definition of other components in the project. It will however find the definition of imported components out of the node_modules folder.

This would not allow you to go to the definition automatically:
`import {thing} from 'src/js/widgets/employees/container';`

These components would allow you to jump to the definition:
`import {Route, Switch, Redirect} from 'react-router-dom';`
`import {thing} from '../../widgets/employees/container';`

I'm not exactly sure what type of information your looking for so please let me know if I can give you more details. This is a closed source repo so I cannot give you the project in question. However, this is a problem that I have seen on previous projects but they have always just used relative references to avoid the issue.

**Comment by mjbvz** [comment]
Does your project have a [`jsconfig.json` file](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson). If not, try creating one and setting the `baseUrl` option:

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2016",
        "jsx": "preserve",
        "baseUrl": "."
    },
    "exclude": [
        "node_modules",
        "**/node_modules/*"
    ],
    "include": [
        "./src/**/*.js"
    ]
}
```

`baseUrl` tells vscode how to resolve non-relative paths

**Comment by Swazimodo** [comment]
This solved the problem once I added support for `.jsx`. Thanks for pointing me in the right direction!

    ```
"include": [
        "./src/**/*.js",
        "./src/**/*.jsx"
    ]
```
