### ISSUE TITLE
Allow to compare project file with clipboard

### ISSUE THREAD

**Issue by xianxingg** [Microsoft/vscode#7278]
when i want to compare a local file with a online resource file, i need to save the online file in project folder, and then do compare. it's a little inconvenient.

It'll be great if i can copy the content of the online file, and right-click the local file, and choose "compare with clipboard".

**Comment by Tyriar** [comment]
An extension would be ideal for a feature like this.

**Comment by alexandrudima** [comment]
@bpasero fyi

**Comment by jmconde** [comment]
It would be great too if also is allowed to compare selection with clipboard.

**Comment by JCorrivo** [comment]
It would be great if we could compare unsaved files...

**Comment by bpasero** [comment]
I would be open to a PR here, I think it is not a lot of work. Some pointers:
* register a new text document content provider to be able to open the left hand side of the diff editor to be the contents of the clipboard (pointers: [`saveErrorHandler`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/saveErrorHandler.ts#L69))
* register a new action to diff the current editor with the resource that can be handled with from the text document content provider (similar to [`CompareResourcesAction`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/fileActions.ts#L1226))

Due to sensitivity of data inside the clipboard it would probably make sense to ask the user for confirmation that the clipboard is accessed.

Related to https://github.com/Microsoft/vscode/issues/358

**Comment by raghav710** [comment]
Has someone taken up this issue? I am a complete beginner to the VSCode codebase, would I be able to contribute to this issue?

**Comment by bpasero** [comment]
@raghav710 not yet, but it seems @tfriem has started a similar PR in https://github.com/Microsoft/vscode/pull/30210 which could be used as input to this one. The difference is that the contents of the left hand side are coming from the clipboard instead of the file on disk.
