### ISSUE TITLE
Selections in terminal should invert colors like in bash

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7285]
Made a request to xterm https://github.com/sourcelair/xterm.js/issues/75, it will be too tedious to do without scripting the CSS on our side though unless they go back to a JS API for theming.

**Comment by coreh** [comment]
You can get the selection `Range` with `document.getSelection().getRangeAt(0)`.

You could then extract the client rects that form it via: `range.getClientRects()`, and create a lot of absolutely positioned white divs of the right sizes with `mix-blend-mode: difference;`. That way they reverse whatever is below them.

Would also need to use `pointer-events: none` on the divs so that they don't affect the selection.

**Comment by Tyriar** [comment]
I've actually already done this as part of https://github.com/Microsoft/vscode/pull/7288

Using `::selection`, I take the `color` and make it the selection `background-color`, then with the make the `background-color` the selection `color`. It turned out really nicely:

![image](https://cloud.githubusercontent.com/assets/2193314/15850995/cc2db92a-2c4f-11e6-95cf-8855fc38fe61.png)

**Comment by coreh** [comment]
Wow, that indeed looks way better than the current selection... Time for me to get on that Insiders build I guess haha

**Comment by Tyriar** [comment]
@coreh :smile: this will probably sit in PR for a day or 2 so land in insiders around the same time. But yeah, the daily insiders just started like an hour ago and [already has some useful fixes in it](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+label%3Aintegrated-terminal+milestone%3A%22June+2016%22+is%3Aclosed).

**Comment by Tyriar** [comment]
Landed in insiders
