### ISSUE TITLE
Quick Pick ignores "focusBorder" and "list.focusForeground"

### ISSUE THREAD

**Issue by diabolicle** [microsoft/vscode#72952]
Modify the colors for "focusBorder" and "list.focusForeground" and notice that Quick Pick ignores these values whereas the command palette correctly implements them.

You can use this to test:

```
"workbench.colorCustomizations": {
    "focusBorder": "#ff0000",
    "list.focusForeground": "#ff0000",
}
```

Quick Pick respects the "focusBorder" (but not "list.focusForeground") immediately after changing the theme, although it reverts back to the default color after it is hidden.

**Comment by jeff-hykin** [comment]
This is causing a problem with some themes since there isn't high enough contrast between the normal foreground and the selection color. This occurs specifically for quick-input-lists only
![Screen Shot 2019-08-12 at 7 22 11 PM](https://user-images.githubusercontent.com/17692058/62907166-8bee1e00-bd37-11e9-84e3-fcd6cf2d2eb1.png)

Here's how it is designed/expected to work:
![Screen Shot 2019-08-12 at 7 31 50 PM](https://user-images.githubusercontent.com/17692058/62907251-edae8800-bd37-11e9-8cf4-6acd26fe2fe1.png)

**Comment by chrmarti** [comment]
The focus border seems consistent with QuickOpen now. Fixing the focus foreground in the list to be consistent with QuickOpen too.

**Comment by jeff-hykin** [comment]
As far as I can tell, this is still an issue on the latest version `1.40.0`.

Expected behavior (quick menu)
<img width="440" alt="Screen Shot 2019-11-12 at 4 38 22 PM" src="https://user-images.githubusercontent.com/17692058/68717128-86d58080-056b-11ea-9fa9-39367a2636a1.png">

List behavior
<img width="400" alt="Screen Shot 2019-11-12 at 4 39 12 PM" src="https://user-images.githubusercontent.com/17692058/68717180-a9679980-056b-11ea-8823-45f8ece7eee6.png">

**Comment by chrmarti** [comment]
@jeff-hykin The fix for the foreground color is in todays Insiders build. Please retry with that.

**Comment by jeff-hykin** [comment]
👍  fix confirmed. Thanks @chrmarti
