### ISSUE TITLE
Cursor jumps unexpectedly to beginning of TS method after using the outline once to jump to a method

### ISSUE THREAD

**Issue by Bernd-L** [Microsoft/vscode#72965]
# Steps to Reproduce

1. Have a TypeScript file open (with some code in it)
2. Use the outline to jump to the beginning of a method
3. Type something somewhere
4. Have the cursor jump to the beginning of the previously jumped-to function as soon as you stop pressing keys for .5 seconds

### Does this issue occur when all extensions are disabled?
Yes (both in insiders & stable)

###  Versions
Version: 1.34.0-insider (user setup)
Commit: c1abf7978d59415dcfcf8cfcb15e0ee30c5e45a5
Date: 2019-04-26T13:39:29.623Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18356

**Comment by jrieken** [comment]
@joaomoreno It seems that the tree send a selection change event after updating children (which happens because markers changed). I will look into a workaround, e.g `e.browserEvent` being `undefined` but it seems like a tree issue

<img width="777" alt="Screenshot 2019-04-29 at 10 33 24" src="https://user-images.githubusercontent.com/1794099/56884480-3af93900-6a6a-11e9-874d-6d62599d6e27.png">
