### ISSUE TITLE
Window pinning breaks when a VS Code instance is closed while pinned

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#72972]
Steps to reproduce:
1. Open VS Code
2. Pin the window to the side of the screen with `Windows + Right`
3. Close the window
4. Open VS Code
5. Try to pin the window with `Windows + Right`
6. Notice that it does not work
7. Try to pin the window with `Windows + Left`
8. Notice that it works

I hit this every single day and it drives me nuts.

Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
OS: Windows_NT x64 10.0.17763

**Comment by akbyrd** [comment]
This is a daily nuisance :(

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
