### ISSUE TITLE
Search in all files, including files and folders excluded through settings

### ISSUE THREAD

**Issue by Merott** [Microsoft/vscode#7309]
This is a feature request.

I'd like to see an option under the search menu, to search in all files and folders, ignoring the configured exclusions. Very often I find myself needing to find a piece of code in my `node_modules` or the generated output for debugging reasons. So, it would be nice to be able to include globally excluded folders without having to remove the exclusions.

I'd be happy to work on a PR if someone could point me in the right direction to the source files involved.

**Comment by MaxLap** [comment]
I'm annoyd by this exact problem when doing a search in the node_modules is a pain in the ass, or needs to use another application for the search.

The way I thought of it, a nice subfeature that has overlap is that if one of the "included files" part is equal or inside an excluded folder, then it should remain "included". This is simply logical, as otherwise specifying the included part in those cases is a no-op.

**Comment by bpasero** [comment]
Click the center button:

![image](https://cloud.githubusercontent.com/assets/900690/26462434/11dd07b8-4181-11e7-8238-402444dcd627.png)
