### ISSUE TITLE
Add Live Account synchronization for settings

### ISSUE THREAD

**Issue by YoYoLups** [Microsoft/vscode#7311]
As in Visual Studio, it will cool to have our settings saved into the cloud, synchronied for instance with our live account into OneDrive.

When I'm using VsCode on several computers, it's a real pain in the ass to have all environment with the same settings

**Comment by adrilort** [comment]
Github may be a good alternative for synchronize settings, either via personal repo or via a public gist

**Comment by kaanoo2904** [comment]
Actually there's 1 extension supports this, it uses github to sync settings.

https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by wUFr** [comment]
i was just about to add request for this.

It could just use your Onedrive folder for settings / extensions.

so +1 for this one. I know there sync via github, but built-in sync via onedrive (or other services) would be awesome

**Comment by cclelio** [comment]
a built-in sync via onedrive could be really great.

**Comment by alexandrudima** [comment]
fyi @egamma @bpasero

**Comment by cuiliang** [comment]
think about add independent Account support in vscode site, allow login using Windows account or other Oauth provider.

**Comment by peabnuts123** [comment]
This is the single biggest missing feature from VScode for me at present, the ability to sync my keymaps and extensions across computers. I am resorting to [maintaining](https://gist.github.com/peabnuts123/a8561496d6bdaaa3f369e10ac8962935) some [gists](https://gist.github.com/peabnuts123/4fb079c951f8bd1dbb64) so that I may at least achieve this manually, and update these repos any time something changes, but with Microsoft's offerings for Cloud platforms, there really is no excuse to have this as a feature, other than the time spent developing it. MAKE THIS HAPPEN!

**Comment by esheafer** [comment]
Yes Please!

**Comment by shanalikhan** [comment]
What i suggest, to ask user if they want to sync then code should install my settings sync extension 😄 upon installing code.

I am planning to import export the settings - if user selects onedrive computer folder it will be sync with one drive and dropbox also - without asking user its credentials - just placing the files in user onedrive / dropbox folder and retrieve from them.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/2743

**Comment by ARambazamba** [comment]
As in the end settings are only text sync to any oauth compatible web storage of choice
