### ISSUE TITLE
workspace.ts getFolder should ignore uri query

### ISSUE THREAD

**Issue by CutieDaisy** [microsoft/vscode#73127]
Issue Type: <b>Bug</b>

When you select or use the shortcut to reveal a file in the sidebar, it show the wrong file in the sidebar

VS Code version: Code - Insiders 1.34.0-insider (072e9a35eeeb45d2df09808a2e4d3b0916d46131, 2019-04-30T22:24:30.383Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.3
vscode-angular2-files|ale|1.6.2
ng-template|Ang|0.1.11
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-eslint|dba|1.8.2
xml|Dot|2.4.0
gitlens|eam|9.6.3
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.9.0
git-project-manager|fel|1.7.1
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
vscode-pull-request-github|Git|0.6.0
angular-essentials|joh|0.6.1
Angular2|joh|7.1.4
vscode-peacock|joh|2.1.1
prettify-json|moh|0.0.3
csharp|ms-|1.19.0
vscode-typescript-tslint-plugin|ms-|1.0.0
vsliveshare|ms-|1.0.91
debugger-for-chrome|msj|4.11.3
angular2-inline|nat|0.0.17
angular-console|nrw|7.4.17
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|3.7.0
quicktype|qui|12.0.46
code-settings-sync|Sha|3.2.9
vscode-multiclip|sle|0.1.5
vscodeintellicode|Vis|1.1.5
vscode-icons|vsc|8.6.0
html-css-class-completion|Zig|1.18.0

(1 theme extensions excluded)

</details>

**Comment by RMacfarlane** [comment]
@CutieDaisy What types of files does this happen for? How did you open the file?

**Comment by CutieDaisy** [comment]
It happens on all my Angular files (*.html, *.css, and *.ts files)

**Comment by RMacfarlane** [comment]
Ok, thanks!

I was able to reproduce this when using the GitHub Pull Request extension. Opening a file from the tree there and then running `Reveal in Sidebar` doesn't work. In that case, the content of the file opened is provided by the extension, and the document has a different scheme than `file`. So the file explorer isn't able to find a matching file to reveal. I'm thinking something similar might be happening with the files you have open, where internally they are provided from an extension rather than the local file system.

**Comment by isidorn** [comment]
@RMacfarlane can you please post repro steps using the Pull Request extension. Thanks!

**Comment by RMacfarlane** [comment]
Here are the steps:
1. From the "GitHub Pull Requests" tree, expand a PR and click on a file to open the diff editor
2. Run `File: Reveal Active File in Side Bar`

The file explorer is revealed, but no file is actively selected

**Comment by isidorn** [comment]
The issue here is that the `getFolder` in the workspace.ts [here](https://github.com/Microsoft/vscode/blob/da3c97f3668393ebfcb9f8208d7616018d6d1859/src/vs/platform/workspace/common/workspace.ts#L184) respects the query.
This method should ignore the query segment of the uri when checking if an uri belongs to a workspace.
Not imporant for april. Thus assigning to @sandy081 and May.
