### ISSUE TITLE
Sass support

### ISSUE THREAD

**Issue by maxshutyak** [Microsoft/vscode#7312]
- VSCode Version: 1.2.0
- OS Version: Mac OS X El Capitan 10.11.5

1. Please add support sass(intended files) and emmet for this.

**Comment by mrmlnc** [comment]
You tried to use this extension (https://marketplace.visualstudio.com/items?itemName=robinbentley.sass-indented)?

**Comment by aeschli** [comment]
Yes, please use the sass extensions and file request against them.

**Comment by maxshutyak** [comment]
@mrmlnc yes i am tried but emmet not working with this plugin

**Comment by mrmlnc** [comment]
@maxshutyak, Today I will add an extension that solves this problem.

**Comment by glen-84** [comment]
@aeschli Could you please re-consider? I'm working on a linting extension that supports both `sass` and `scss` syntax, and I'd like to do something like:

```json
  "activationEvents": [
    "onLanguage:sass",
    "onLanguage:sass-indented"
  ]
```

**Comment by aeschli** [comment]
@glen-84 Not sure what you want me to reconsider... Our team is too small to be able to provide support for all the features requested. But we added an extension API so that the community can jump in, fill gaps and innovate. If there's a API missing or anything we need to do on our side to have extensions fully work, please let us know, or file a pull request. We're happy to help.

@mrmlnc Why not making a pull request for your fix to add 'sass-indented' to the list of languages supported by emmet. The approach to patch the code is not the indented use of an extension. Users will have to reeinstall after every update and the approach is very fragile. @egamma FYI.

@glen-84 BTW, I renamed the language id for SCSS from 'sass' to 'scss' to avoid further confusions. For the time being, to be compatible until the June build is out, you can add both "onLanguage:sass" and "onLanguage:scss" to your activation list. After June I suggest to only keep onLanguage:scss so that 'sass' can be used by the indented sass mode (if required)

**Comment by mrmlnc** [comment]
@aeschli I'm working on it. I have not made the pull request because my proposed version is a hack. Yesterday I found a better way.

**Comment by glen-84** [comment]
@aeschli I meant reconsider adding very basic (language ID + maybe syntax highlighting) for `.sass` files.

Regardless, if I want to support indented syntax, would I just include `sass-indented` in the activation list? I'm assuming (hoping) it won't result in any activation errors if the extension is not installed.

**Comment by aeschli** [comment]
@glen-84 Yes, just add `sass-indented` to the activation list. The language definition dies not have to be present.

**Comment by maxshutyak** [comment]
@mrmlnc thanks man ! You help me
