### ISSUE TITLE
Add maximize panel command

### ISSUE THREAD

**Issue by fegg** [Microsoft/vscode#7314]
- VSCode Version: 1.2.0
- OS Version: Mac OS X 10.11.6

Steps to Reproduce:

1. open the terminal function, use: ⌃`

today update version 1.2.0, terminal function is very great! but could add it max zoom panel function? switch this panel and code’s panel because ` git diff ` function code is very many, needs more zone to preview diff's code. my english is not well, hope your know what I mean, thanks~

and sometime terminal is not work... show the terminal panel is block.

**Comment by bgashler1** [comment]
Related #2806

**Comment by stevencl** [comment]
Right now we are not keen on adding controls to maximise, minimise and restore the horizontal panel (which contains the terminal) as we are wary of overloading the product with too many window management controls. We think that this would end up making VS Code feeling more bloated and less lightweight.

We do allow you to drag the horizontal splitter to approximately 90% of the height of the main window so that you can provide more space for the panel. Is this sufficient?

**Comment by Tyriar** [comment]
@stevencl just noticed that this was closed after looking at #10546. I was going to say that the only other case when I need another terminal is if I want to look at a git diff, in which case I typically launch an external terminal (ctrl+shift+c) and full screen it temporarily. I was hoping this would enable me to stay in vscode by allowing me to toggle a panel fullscreen/maximize state temporarily.

I would be happy with a command that had no keybinding by default, this wouldn't cause bloat. Using the horizontal splitter is not an option for me, taking my hands off the keyboard and resizing it is a huge pain, especially since the hit box for the splitter seems to be 3 pixels high.

**Comment by isidorn** [comment]
This has been added to our october plan, thus reopening, assigning to me and october
I have some ideas on how to do this - and we can discuss them on next wednsday ux meeting
fyi @egamma

**Comment by wilrnh** [comment]
I like the idea of a command with no default keybinding 👍

**Comment by kdheepak** [comment]
Is this a feature available in release currently?
