### ISSUE TITLE
Have our own fork of jesseweed/seti-ui

### ISSUE THREAD

**Issue by bergmeister** [microsoft/vscode#73178]
I want to add an icon for a file type (`.tests.ps1` `Pester` files) but `vscode` pulls icons in from https://github.com/jesseweed/seti-ui but this repo seems to be not maintained any more (no issue/PR activity for nearly a year and the GitHub user himself is not active any more as well).
Therefore I do ask that someone takes over maintenance of the project or that vscode forks it and uses the fork because otherwise there is no way I can open a PR to add the icon.

**Comment by misolori** [comment]
@aeschli not sure what we should do here, seems like the `seti-ui` theme is no longer being maintained. We should decide whether we need to create our own fork to maintain.

**Comment by bergmeister** [comment]
Any updates?

**Comment by aeschli** [comment]
I hear you, will bring it up for discussion in our planning meeting.

**Comment by bergmeister** [comment]
I sent an email to the `seti-ui` maintainer to ask for clarity of maintenance on his side. cc @b4nst

**Comment by DanTup** [comment]
I was just about to open an issue about this. It's been 9 months since VS Code made its own fixes for the R icon size and there have been other languages with PRs trying to get icons (for ex., we had a single-color Dart icon creating specifically to fit in here, but it also wasn't merged). It'd be great if VS Code would make a fork (or even just agree to update to someone elses if they merged in those PRs).

**Comment by orta** [comment]
Nice timing everyone, I've got access to maintain the repo this morning. I also asked a while back, and have a track record of handling lots of smaller repos

 This means that from VS Code's side we're in a good spot because they can poke me anytime because vscode is important to typescript and typescript is important to me.

**Comment by bergmeister** [comment]
Awesome, thanks.
Given this, I am happy to close the issue and will soon open a PR on `seti-ui` then.
