### ISSUE TITLE
Theme enabled/forced onto me

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#73224]
this is https://github.com/PowerShell/vscode-powershell/issues/1943

* install PowerShell extension
* theme picker shows/theme is selected

While the auto theme enablement might make sense to theme-only extensions it really confused me with this extension. I expected that I can PowerShell intellisense et al, not that my theme changes and that quick pick shows

**Comment by TylerLeonhardt** [comment]
Not as critical, the theme is also forced on you when debugging the extension from source.

**Comment by corbob** [comment]
I noticed this with insiders around the end of January, but then it seemed to revert the next day, and has since come back. It looks like maybe it was along with the change to load extensions without reloading the editor?

This is where I mentioned in the PowerShell discord and where I get the dates from:

![image](https://user-images.githubusercontent.com/30301021/57201841-0fd38580-6f53-11e9-8941-02ab7a5e8166.png)

**Comment by sandy081** [comment]
Well, this picker is very helpful for theme extensions but the powershell extension is trying to compose various (language features, themes etc) features into one extension. It would be a good design if they can split into two extensions one with language features and other with theme as they are not related. This will also help with remote set up - https://code.visualstudio.com/blogs/2019/05/02/remote-development#_managing-extensions.

You can also have a pack that can compose these extensions for those who want to have also themes. This will give flexibility to users to install either language features or both and do not force to install the theme.

I am closing this as the above suggestion needs changes in the extension
