### ISSUE TITLE
Debug WordPress: jump into hook

### ISSUE THREAD

**Issue by alimuzzaman** [Microsoft/vscode#73247]
When debugging WordPress plugin, if we click `jump into` it jumps into WordPress core function `do_action` or `apply_filters`, which is hard to navigate.

What do I expect is to ignore the core function and jump into registered action or filter directly.

Do anyone have idea if it possible?

**Comment by gjsjohnmurray** [comment]
@alimuzzaman I guess you're using the PHP Debug extension (felixfbecker.php-debug) though you haven't told us. If you are, [this issue](https://github.com/felixfbecker/vscode-php-debug/issues/313) on the extension looks relevant, and it's currently Open. That's where the feature needs to be implemented, so I suggest you close this issue here.

**Comment by alimuzzaman** [comment]
Yes I am using **felixfbecker.php-debug**.
Thanks.
