### ISSUE TITLE
Don't open folder

### ISSUE THREAD

**Issue by josegpe-gc** [microsoft/vscode#73284]
Issue Type: <b>Bug</b>

I was working in a personal project and then I opened a new window and I tried to open a folder but vs code don't opened it, nothing happened. I was needed to close and then open new window for fix this problem.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 4.9.0-8-amd64

**Comment by RMacfarlane** [comment]
- If you try to open the same folder again, do you see the problem again?
- How did you try to open the folder? (From the "Open Folder" button, from the recents list, from the welcome page?)

**Comment by josegpe-gc** [comment]
> * If you try to open the same folder again, do you see the problem again?
> * How did you try to open the folder? (From the "Open Folder" button, from the recents list, from the welcome page?)

No, I was opened the same folder again but closing and opening the editor and there was no problem. I tried to open from **Open Folder** button.

**Comment by SurelyExploding** [comment]
I'm still having this issue on Windows, primarily with unity projects. Seems to particularly be an issue with C# project file attaching in the editor, but this is particularly annoying because it shows no error in the console or in the main window, you just tell it to open a folder and nothing happens. I was even able to accidentally get it to happen on a brand new install on a completely different computer.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!
