### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#73411]
- Issue Type: `Performance`
- Extension Name: `cpu-load`
- Extension Version: `0.0.11`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.34.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/isidor/jrieken.cpu-load-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DanTup** [comment]
@isidorn @jrieken do you have a way to trigger this? I just opened https://github.com/microsoft/vscode/issues/73419 because I'd really like to get a profile of my extensions startup, but I can't find a way (users sometimes trigger this, but I can't). If there's something I can do to force it, it'd allow me to get a trace to more easily measure the impact of my changes.

**Comment by DanTup** [comment]
Never mind, I was able to force it like this:

```
const time = Date.now();
let i = 0;
while (Date.now() - time < 3000) {
	i++;
}
console.log(i);
```

My trace doesn't have anywhere near the tree of loading that the users does though.. I'll have to do some more digging into why that is :/
