### ISSUE TITLE
Terminal:`Run active file` doesn't work in remote

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#73451]
- open a WSL remote, install the C++ extension
- create a file 'main.c'
```
int main()
{
    return x;
}
```
- invoke Terminal > Run Acrive File
- error `Only files on disk can be run in the terminal`

**Comment by liushiqi9** [comment]
Experienced same problem at insider 1.35.0 with ssh to Arch. 
Any updates guys ?

**Comment by jeff-dagenais** [comment]
+1
1.38.1

**Comment by ideepika** [comment]
is this fixed?

**Comment by adrian-dinu** [comment]
Having the same issue, any workaround found ?

**Comment by jeff-dagenais** [comment]
Personally, I worked around it using a task in tasks.json (Note: 'd' is my ssh host alias)

```
	"tasks": [
		{
			"label": "run current file on remote",
			"type": "shell",
			"command": "/bin/bash",
			"args": [
				"-c",
				"-e",
				"[ -x ${file} ]; scp ${file} d:/tmp/vscode.tmpexec && ssh d /tmp/vscode.tmpexec"
			],
			"problemMatcher": []
		},
...
```
Not so great, but does the trick for me.

**Comment by TylerLeonhardt** [comment]
This doesn't appear to be 100% fixed. Using Remote WSL, I noticed that the slashes were wrong:

```
$ \home\tyler\main.c
hometylermain.c: command not found
```

It tries to run with `\`s but it should be `/` because the remote is running on Linux.

**Comment by Tyriar** [comment]
Looks like this is caused by the following not getting executed:

https://github.com/microsoft/vscode/blob/a7c466d64983d71b066cf6ce50a4559e41b3042a/src/vs/workbench/contrib/terminal/browser/terminalInstanceService.ts#L161-L164

I don't think it's possible currently for isRemote to be true at the same time the shellType is Wsl, since the latter is only detected when wsl.exe for example is run:

https://github.com/microsoft/vscode/blob/ee1655a82ebdfd38bf8792088a6602c69f7bbd94/src/vs/platform/terminal/node/windowsShellHelper.ts#L154-L161

**Comment by Tyriar** [comment]
This is fixed, the path problem is tracked in https://github.com/microsoft/vscode/issues/78751
