### ISSUE TITLE
Toggle search view position should also appear in empty search view

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#73465]
Search view, context menu on empty area -> no context menu
In this case we should still offer the option to move the search view to the panel. Since it is a "global" action, and it only appears when there are results in the search view

**Comment by skprabhanjan** [comment]
@roblourens , can i take a look at this or are you working on this ? :)

**Comment by roblourens** [comment]
You can take a look

**Comment by skprabhanjan** [comment]
@roblourens , I understood how "Toggle Search View Position" works both in [code](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/search/browser/search.contribution.ts#L322-L345) and functionality.
So when we right click on the search result then only the option comes up , so it is bound to search result. 
So what is the approach we should take to fix this ?
We need to move this whole functionality to somewhere else rite ? ( Like some button next "Refresh","Clear All Search Results".... ? ) 
Please suggest me the way forward :)

**Comment by roblourens** [comment]
@isidorn do you know how to add a context menu to an empty tree?

**Comment by isidorn** [comment]
`tree.onContextMenu` gets fired for every place in the tree, including empty items.
Here's an example how I use this in the explorer 
https://github.com/Microsoft/vscode/blob/7006ca07723ba3ea2b73f9fa0db5b1c122ffbf2b/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L342

**Comment by roblourens** [comment]
@skprabhanjan I think we should use that for this command, rather than `appendMenuItem`

**Comment by skprabhanjan** [comment]
@roblourens , I tried doing this and here is what I found.

- There is already `onContextMenu` trigger in `searchView.ts`  [here](https://github.com/Microsoft/vscode/blob/7006ca07723ba3ea2b73f9fa0db5b1c122ffbf2b/src/vs/workbench/contrib/search/browser/searchView.ts#L647)
- If we remove this check then it will work on empty tree also ( [here](https://github.com/Microsoft/vscode/blob/7006ca07723ba3ea2b73f9fa0db5b1c122ffbf2b/src/vs/workbench/contrib/search/browser/searchView.ts#L686) )
- In case of no results , we are showing custom message and here the **tree is no longer in the view** , so right clicking there would not work. ( [HasNoResultCode](https://github.com/Microsoft/vscode/blob/7006ca07723ba3ea2b73f9fa0db5b1c122ffbf2b/src/vs/workbench/contrib/search/browser/searchView.ts#L1310) ) 
- Ideally if we remove that` if condition` mentioned in case 2 , then what @isidorn suggested is already there but as the tree itself is not valid in case of "No Search Results" because of showing some custom message described above.

Please let me know the way forward to fix this :)

**Comment by roblourens** [comment]
Good analysis. Can we change it to keep the tree in the DOM when that no results message is shown? Not sure how the tree is sized in css but it would have to be vertically flexible.

Also, when I am right clicking on an empty tree, I should not see context menu items that are not valid without a row, like copy, dismiss, etc.
