### ISSUE TITLE
Terminal window goes blank. 

### ISSUE THREAD

**Issue by ketan86** [microsoft/vscode#73499]
![Screen Shot 2019-05-08 at 5 56 20 PM](https://user-images.githubusercontent.com/5973097/57420096-a786dd00-71ba-11e9-8db3-2c591b2ebc19.png)
Issue Type: <b>Bug</b>

Terminal window goes blank.  Deleting makes the VSCode go hung.

VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:22:55.268Z)
OS version: Darwin x64 17.7.0

**Comment by JaimeStill** [comment]
I've been having a similar issue in the past few versions of code (though less destructive than @ketan86 is experiencing). Anytime a new terminal instance is created (new `cmd` session), the command line is blank until the first command is executed. I have to run a `cls` in order to get the session to behave correctly.

![vs-code-terminal](https://user-images.githubusercontent.com/14102723/57454749-94feb900-7237-11e9-99ca-33498f64855d.png)

**VS Code Info**  
* **Version**: 1.33.1
* **Commit**: 51b0b28134d51361cf996d2f0a1c698247aeabd8
* **Date**: 2019-04-11T08:27:14.102Z
* **Electron**: 3.1.6
* **Chrome**: 66.0.3359.181
* **Node.js**: 10.2.0
* **V8**: 6.6.346.32
* **OS**: Windows_NT x64 10.0.17763  

**Win 10 Info**  
* **Edition**: Windows 10 Pro
* **Version**: 1809
* **OS build**: 17763.437

**Comment by Tyriar** [comment]
@JaimeStill that's a bug in Windows, see https://github.com/Microsoft/vscode/issues/57803

**Comment by Tyriar** [comment]
This looks like https://github.com/microsoft/vscode/issues/71966
