### ISSUE TITLE
Running build task in Code approximately 50% slower than in terminal

### ISSUE THREAD

**Issue by spongessuck** [Microsoft/vscode#7353]
- VSCode Version: 1.2.0
- OS Version: Windows 7

Steps to Reproduce:
1. Run build task in Code (i.e. gulp dist)
2. Run same command in cmd.exe (or integrated terminal)

Expected result:
- Tasks should take about the same amount of time

Actual result:
- Build task takes ~20 seconds to finish in Code, while it takes ~13 seconds in terminal.

**Comment by dbaeumer** [comment]
@spongessuck do you have problem matchers installed in your task? Does the task produce lots of output. We are aware of the fact that task with lots of output run slower due to rendering the text in the output panel.

**Comment by spongessuck** [comment]
I don't have any problem matchers and the task doesn't produce a lot of
output- maybe 25 lines total or so.

**Comment by dbaeumer** [comment]
I did some measurements using the new terminal runner and here is the outcome

- executing vscode compile script in a outside terminal => 84 seconds
- executing vscode compile script in the integrated terminal => 92 seconds
- executing the vscode compile script in the integrated terminal as a task => 157 seconds :-(

Looking into this the time is spend in the spinner animation. I removed the animation since it adds no value. Without the animation there is no time difference between the task and the integrated terminal.
