### ISSUE TITLE
Autocompletion/language server telemetry

### ISSUE THREAD

**Issue by gramster** [microsoft/vscode#73556]
We (Python team) would like to have telemetry for language server utility, and some of this is out of our span of control and would need to be in VSC:

- Time between user typing a ‘.’ and the completion list appearing. We can measure the latency of the language server itself but that is different to what the user experiences.
- % of times user typed '.', we offered completions and the user accepted the first suggestion (useful for Intellicode)
- % of times user typed '.', we offered completions and the user accepted a suggestion
- % of times user typed '.', and the call to the language server took too long and timed out

**Comment by mjbvz** [comment]
It would be helpful to understand what problems you are trying to solve and then work backwards from there to see what data you need. 

I've dealt with this around js/ts, so just to the current points: 

* In general, we've only cared about how fast our extension is because other extensions can be acting up.
* Many factors can influence completion sort order so getting useful data may be difficult. I believe what we track for IntelliCode is: was the accepted suggestion an IntelliCode added suggestion or not?
* The js/ts extension uses `CompletionItem.command` to track acceptance of completion items (also for intellicode)
* You may be able to monitor the cancellation token for this? The user cancelling a request while your completion provider is running may also be a good indication that the server is taking too long to provide a result

**Comment by gramster** [comment]
Thanks! I thought I had opened an issue before but couldn't find it, as it was Kenneth who did it on my behalf.
