### ISSUE TITLE
Give option to set the font of the hidden console window used by winpty

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#7355]
- VSCode Version: 1.2
- OS Version: Windows 10 x64

THE PROBLEM: At least under cp936 and using TrueType fonts, when rendering some characters, like `λ`, Windows will measure the real character width of the console font chosen, and allocate console cells to display them. (The full alglrithm of how character widths are calculated is listed in [consolelib.cs#L676](https://github.com/lzybkr/PSReadLine/blob/0ffd1b2351214f1f25a433060a6c75a29c59c90f/PSReadLine/ConsoleLib.cs#L676).) (ps. I am curious about why this algorithm is not ported to non-DBCS code pages, like 65001, given that the Console can actually render these characters, the result is not layouted well.)

Therefore if the font used for the hidden console is inconsistent with the font configured in VSCode, the character widths may be incorrect. For the `λ`, most Windows users under cp936/932 will see this character rendered and layouted in full-width in the real console (because this lambda in NSimSun and MS Gothic is full-width), but Code will treat them as half-width, causing incorrect layout.

THE SOLUTION: Give option to set the font of the hidden console used by winpty in sync with the font used in Code.

A sample font package: [Inziu](http://be5invis.github.io/Iosevka/inziu.html). (Inziu Iosevka SC for 936, Inziu Iosevka J for 932.)

**Comment by Tyriar** [comment]
I don't think [pty.js](https://github.com/chjj/pty.js) supports setting the font of winpty, I think you would need to request there first.

**Comment by be5invis** [comment]
@Tyriar There's a utility program “[setfont.exe](https://github.com/rprichard/winpty/blob/master/misc/SetFont.cc)” provided in winpty. You can actually bundle it and run it if user specified console font and size.

**Comment by be5invis** [comment]
OK I am able to confirm that "setfont.exe" works
![image](https://cloud.githubusercontent.com/assets/240091/15889791/250a5d32-2d9f-11e6-8580-58adc8ba49aa.png)
![image](https://cloud.githubusercontent.com/assets/240091/15889825/49a8c9a8-2d9f-11e6-9ea0-4b0ff9ed4c52.png)

**Comment by rprichard** [comment]
@be5invis "(The full alglrithm of how character widths are calculated is listed in consolelib.cs#L676.)"

Thanks for linking to this.  I wonder if the algorithm explains the curious behavior I noticed where the character width (half or wide) alternated back-and-forth as the console font size increased one-by-one: https://github.com/rprichard/winpty/blob/d7290359d59b6c75ded0e89370475edaaff1555b/misc/Font-Report-June2016/CP936.txt#L12.  That behavior stops in Windows 10, but only with the non-legacy console enabled.  I was wondering how the PSReadLine author figured out that algorithm, but then I noticed the Microsoft copyright.  Perhaps the author simply looked at the console source.

It looks like vscode is using a pty.js fork at https://github.com/Tyriar/pty.js, which is only slightly patched from https://github.com/platformio/pty.js.  The platformio pty.js is using a much newer winpty version, though it still has the `winpty_open_use_own_datapipe` function added in.

winpty master at https://github.com/rprichard/winpty has changed quite a bit very recently.  There are quite a few bug fixes, and the API has changed somewhat.  Instead of passing a data pipe name to `winpty_open_use_own_datapipe`, pty.js should be able to query winpty for CONIN and CONOUT pipe names, then connect to the two pipes (i.e. using CreateFile, not CreateNamedPipe).

Current winpty master changes the font as the window resizes (to fix https://github.com/rprichard/winpty/issues/61), so using `SetFont.exe` would tend not to work after updating winpty.

**Comment by be5invis** [comment]
@rprichard Width is complex, default DBCS fonts has complex gridfitting mechanism (which may change character width under GDI) and embedded bitmap, the latter one may be crucial (because these fonts do not have odd-sized bitmaps). Inziu is vector-only, and it may perform better consistency.
cc. @lzybkr

**Comment by lzybkr** [comment]
I just noticed the questions for me. The code in v1.2 of PSReadLine to calculate the cell count for characters was lifted from PowerShell.

It seems quite likely the original author of the PowerShell code simply copied the algorithm from the console implementation, but this was more than 10 years ago and before my time.

In the interest of code portability and simplicity, both the PowerShell and PSReadLine implementations now ignore the font and just rely on the Unicode standard, see [here](https://github.com/lzybkr/PSReadLine/blob/c3868e125069d87adbc5ee8f0274762a99510957/PSReadLine/Render.cs#L539).
