### ISSUE TITLE
Git: Add events to API

### ISSUE THREAD

**Issue by LeandroDoldan** [microsoft/vscode#73617]
Hello.

I'm trying to create an extension that tracks when the user changes the branch. I've been reading past issues asking of the git API, and I've been able to get the current branch of the user. However, it does not seem to be a way to subscribe to an event on the repository changes.

It would be very useful being able to subscribe to events on commits, merges, or rebases, for example. I was thinking about a function `onBranchChange`, that accepts as a parameter a callback to be executed every time the event is fired. 

I tried using the [oficial API](https://github.com/microsoft/vscode/tree/master/extensions/git), but you can't listen when git is enabled, so you can't start your extension from the startup. It does not listen to branch changes either, although it does listen to repository changes which it is even better for what I'm trying to accomplish.

Thank you.

**Comment by joaomoreno** [comment]
Care to submit a PR for this?

**Comment by babakks** [comment]
@joaomoreno 

I'd like to have a try on this.

As of my understanding, what OP suggests is to add various operation events to the GIT extension's API. The little question is, should there be an event per operation, or one single event that raises in all cases (with the operation name and details in the event context/args)? I'd go for the first, but it seemed plausible to ask it first.

Other than that, having closely related events, in my experience, there's a real question on what to do on composite operations. For instance, after you pull (e.g., with `git pull --all`,) new branches may appear in your local repository. So, is it fine to just emit the pull event (e.g., `onDidPull`) and ignore those branch creation events (`onDidCreateBranch`)? Or they should precede it?

**Comment by joaomoreno** [comment]
I'd just make it that the API would fire change events on the current repo state, independent of what operations are run. That would accommodate for when the user runs command line git commands as well.

**Comment by davinci26** [comment]
I would also love to have this feature :) ( that is my +1 for the feature)

@babakks are you working on this?

@joaomoreno from your experience how long (roughly) would you thing developing this feature would take?

**Comment by joaomoreno** [comment]
@davinci26 This should be pretty straightforward, under a day.

**Comment by davinci26** [comment]
if @babakks is not working on it I would love to take a stab at it.

**Comment by babakks** [comment]
@joaomoreno  I'm sorry. I didn't find some time to focus on this.
@davinci26 Feel free to go with it.

**Comment by davinci26** [comment]
@joaomoreno what I am thinking in terms of the implementation is the following,

In the `updateModelState()` in the `repository.ts` to have the following:

When you get the new HEAD of the repository to check the following:
1. If the head name is different than the previous emit an `onDidHeadChangeEvent`. The reason here for the user could just choose to checkout a detached head.
1.2. if the commit hash is different than the previous emit an `onDidCommitEvent`. This covers the case of pulling from origin, merging another branch, reverting, and just committing local changes.
1.3. if the rebase commit is present, then emit an `onDidRebaseEvent`.

Composite operations can emit more than one event but it is on the user to subscribe to specify the granularity of events they wish.

Do you think this approach is towards the right direction? or am I missing something?

**Comment by joaomoreno** [comment]
@davinci26 I took a good look at this. We already support:

- [Repository open/close events](https://github.com/microsoft/vscode/blob/be68a4e14c28cc81cdf422739af23123b3c91fd2/extensions/git/src/api/git.d.ts#L186-L188)
- [Repository state change events](https://github.com/microsoft/vscode/blob/be68a4e14c28cc81cdf422739af23123b3c91fd2/extensions/git/src/api/git.d.ts#L106-L107)

Given the fact that the original request:

> I'm trying to create an extension that tracks when the user changes the branch.

This is already possible in the current API. Closing this issue. Thanks for looking into it anyway.
