### ISSUE TITLE
Emmet does not expand c:ra to color:rgba()

### ISSUE THREAD

**Issue by yerzinperez** [microsoft/vscode#73627]
- VSCode Version: VSC 1.33.1
- OS Version: Windows 10 Home Single Language

![captura](https://user-images.githubusercontent.com/46495310/57576396-9b9e5380-7424-11e9-8cc5-54efeac7a86f.png)

Steps to Reproduce:

1. When using emmet in css and trying to write c: ra should generate color: rgba (); but this is not the case since he writes color: ra; and it's really uncomfortable.
2.  According to the emmet documentation this should not generate another code than the proposed one.
3. I also look at the documentation offered by Microsoft for emmet but nothing solves this error.

**Comment by devanshj** [comment]
@sergeche `"c: ra"` is in the [cheat sheet](https://docs.emmet.io/cheat-sheet/) and also in [this extended snippets.json](https://github.com/emmetio/Emmetoss/blob/a286122c0a1a0a0609e5fc26bfa44592bef5ef4d/snippets.json#L1134). So I guess people have to put this snippets themselves into the directory, but on the other hand emmet@2 is [buggy when snippets have ":" in them](https://stackblitz.com/edit/typescript-blankk-bk35ac?file=index.ts). Is `":"` not supported in snippets or is it a bug?

I'm asking this because it's normal for people to see a snippet from the cheat sheet and expect it to work out of the box. Like [here](https://github.com/microsoft/vscode/issues/84608) too. So we need to see how to go about this.

**Comment by sergeche** [comment]
Snippets like `c:ra` are not allowed anymore since `:` is used to explicitly separate property and value. Users should use `cra` name instead

**Comment by devanshj** [comment]
@sergeche Okay, thanks! That's what I had guessed. Also do you think it's a good idea to include those extended snippets (without colon) in "emmet" package? Otherwise editors will have to add it themselves so user referring to the cheat sheet can use it out of the box.

And also can you update the cheat sheet to reflect that those are not supported by default? I can send a PR if you want.

**Comment by sergeche** [comment]
I’m working on a new version of website right now, it will also include updated cheat sheet. Current cheat sheet is used for old Emmet version, available for other editors.

I’ll think about iterop with old syntax, e.g. `c:ra`, maybe I can properly match them with new parser

**Comment by devanshj** [comment]
@sergeche Okay thanks!

**Comment by devanshj** [comment]
@octref You might want to label this as "upstream".

**Comment by rzhao271** [comment]
\closedwith dc5a3da

**Comment by rzhao271** [comment]
@yerzinperez on the latest Insiders edition of VS Code you can now use `cra` and `cr` to get the rgba and rgb expansions, respectively. Unfortunately, `c:ra` and `c:r` are not supported anymore on the latest Emmet.

**Comment by rzhao271** [comment]
Verifier: in a CSS file under a selector (e.g. within a `.classname { }` block), ensure that `cr` expands to `color: rgb(0, 0, 0)` and that `cra` expands to `color: rgba(0, 0, 0, .5);`

**Comment by rzhao271** [comment]
\closedwith dc5a3da

**Comment by rzhao271** [comment]
\closedWith dc5a3da
