### ISSUE TITLE
Unable to change Editor Hover Delay in User Settings

### ISSUE THREAD

**Issue by davegear** [microsoft/vscode#73639]
<!- Please search existing issues to avoid creating duplicates. ->
Not sure any of the existing issues are this.
<!- Also please test using the latest insiders build to make sure your issue has not already been fixed: https://code.visualstudio.com/insiders/ ->
Can I run this side-by-side with my VS Code or will it overwrite the program or its configuration or conflict with something in the OS?

- VSCode Version: 1.33.1 (user setup)
- OS Version: Windows 7 Pro x64

Steps to Reproduce:

1. Hover mouse over something that causes a pop-up explaining it (like a JavaScript keyword).
2. A pop-up shows above within 300 milliseconds (virtually instant).
![image](https://user-images.githubusercontent.com/32692076/57584919-41da6f80-749e-11e9-9dcb-be49df21e5bb.png) 
(not sure what the box is called that shows, would be good to know how to activate it manually)
3. The pop-up obscures code and distracts unnecessarily.
4. When I go to File > Preferences > Settings, then search for editor.hover.delay, it Editor: Hover > Delay with a User Settings tab and a Workspace Settings tab.
5. I can edit and save the number (300) in Workspace Settings tab (to 3000, after tabbing out of the box, which auto-saves), but editing it in User Settings will simply let me change the number, and then exiting out of the box resets the number back to 300.

I'm not understanding why I can't change the User setting here when I want it to apply to all workspaces.

![image](https://user-images.githubusercontent.com/32692076/57584856-59fdbf00-749d-11e9-8b7a-29a8f925fd2f.png)

Does this issue occur when all extensions are disabled?: Yes

Also I notice the indicator of which tab is selected is very miniscule, and sometimes not easy to tell at a glance like most indicators or require a squint or a closer look (my eyesight is not great). The indicators are an extra 1-pixel line underneath the tab line and a slight bolding of the text... this is not user-friendly nor easy.

**Comment by roblourens** [comment]
> but editing it in User Settings will simply let me change the number, and then exiting out of the box resets the number back to 300.

This isn't right, but I can't reproduce it. Can you check the developer tools (Help > Toggle developer tools) for any errors in the console?

Also thanks for the feedback that it's hard to see the selected tab. Do you think it would be better if the selected tab title was also slightly more bold? FYI @misolori 

![image](https://user-images.githubusercontent.com/323878/57645183-92230180-7572-11e9-8824-543089b38a1d.png)

**Comment by davelogear** [comment]
I get this error when I try to change User Settings > Editor > Hover: Delay from 300 to 3000:

workbench.main.js:1505 Conflict in settings file file:///c%3A/Users/Dave/AppData/Roaming/Code/User/settings.json: Ignoring editor.parameterHints.enabled as editor.parameterHints is false

When I was trying to uncheck Editor > Hover: Sticky, it would check itself again; now as I'm flipping back and forth between Chrome and VS Code, it saved... but then checked again. The error seems to be this:

Conflict in settings file file:///c%3A/Users/Dave/AppData/Roaming/Code/User/settings.json: Ignoring editor.parameterHints.enabled as editor.parameterHints is false

I'm confused; fine if VS Code is HTML/JavaScript or whatever (Electron?), but it seems like flaky JavaScript right now... I'm on Windows 7 Pro x64 and I haven't had problems with user settings saving until the new settings editor came out but only since I started using VS Code again a week or so ago.

Maybe the latest version is having the problem? Or there's a cache issue? I can't tell what the errors mean.

Is there some way to clear cache or fix the conflict, or do I need to reinstall the program or plugins?

**Comment by davelogear** [comment]
The selected tab being more bold would help, but really, a tab should look like a tab, with a different-color background or a border. I understand the popular thing is to be minimalist, but when things look like other things (tabs or buttons that look like text or variations thereof) or are hardly recognizable, there's a UI/UX issue.

Thanks for being responsive and caring about the experience.

**Comment by davelogear** [comment]
I just noticed the error only happens when I click outside of the setting I just changed... so it appears to actually try to save when the element loses focus, but fails with some conflict.

**Comment by davegear** [comment]
I think I fixed it by clearing its cache... though I don't remember now how I did it.
