### ISSUE TITLE
A similar approach of hiding Title bar like in Chrome & Firefox. Space matter a lot.

### ISSUE THREAD

**Issue by PranavBhattarai** [microsoft/vscode#73674]
For those people who want to bypass this issue by offering other option, I have a very good screenshot of this condition which every newbie and sometimes even advance developer go through.
![Screenshot from 2019-05-14 06-57-56](https://user-images.githubusercontent.com/32763112/57664290-4d04db00-7617-11e9-9996-9d657480431d.png)
_P.S: We need more space. VS is not offering much. Meanwhile, Chrome & Firefox, solved this very nicely, Probably because of "VScode" name of the top bar which VScode want to force people to show everywhere & everyone. Like a promotion._ 
Note: If a product is sexy it doesn't need a promotion. VS code is a sexy concept. So give us a "hide title bar" option. It doesn't need promotion.

**Comment by chrmarti** [comment]
Have you tried Zen Mode and Fullscreen Mode in the `View` > `Appearance` menu?

**Comment by PranavBhattari** [comment]
@chrmarti sorry, the question has been updated with more details.

**Comment by misolori** [comment]
The title is used to indicate what project/workspace you have open (helpful when you have multiple windows open).

I think the hard part is going to be how to handle the editor actions that appear to the right of the tabs as those are in the same area as the window controls:

![image](https://user-images.githubusercontent.com/35271042/57874136-c130b180-77c4-11e9-8992-25816bac0b8a.png)

**Comment by PranavBhattari** [comment]
@misolori But I really think, a user should have right how would they like to view the application. Space is a pretty big deal. Not everyone can afford a dual screen. Is frustrating that I have to debate on this issue when usually re-known software provide this option on user's hand.

**Comment by misolori** [comment]
@PranavBhattari it’s not easy to disable/hide it, you have the file menu items and window controls to manage as well. 

You’re more than welcome to create a PR if you’ve got any ideas to help solve the problem.

**Comment by PranavBhattari** [comment]
@misolori people are asking the way to do this in many forums and communities like Reddit. 
And they are suggesting alternative app.

But u are ignoring them.
Isn't that really bad for doing business!?
I mean as a software developer, we try to provide things even those we don't like it. Because they might (public) might like it. Even if its a "bad practice". Because people are important.

You are trying to be ignorant. Do you want me to close this issue? Because I trying to make some point here.

>  it’s not easy to disable/hide it
who said its easy. Developing software is not easy. Making things as fast as possible is not so easy.
That's developer job to make it possible. Are u seriously telling me this is impossible to do?

(i might sound rude, but honestly, I admire Microsoft approach, But... it is what it is. )

**Comment by misolori** [comment]
@PranavBhattari I completely hear your point: you want a way to hide the title bar. What I'm saying here is that this is going to require some thoughtful discussions around how to solve this, hence why I've left this issue open.

**Comment by misolori** [comment]
Since this original issue, `window.titleBarStyle` will now show the file menu inline with the title bar. You can further maximize the screen real estate but hiding the activity bar, side bar, status bar, tab visibility, window title, and Minimap. That will give you this:

![image](https://user-images.githubusercontent.com/35271042/66352977-c4643f80-e915-11e9-96f6-724d25fc6788.png)

As you can see, even in this small window layout the VS Code tab bar area uses less vertical space than Chrome. In trying to keep our issue count on a manageable level, I'll be closing this issue as `as-designed`. Thanks.
