### ISSUE TITLE
Add 'scroll past the end' feature for the integrated terminal

### ISSUE THREAD

**Issue by Tanoemon** [microsoft/vscode#73698]
I know this is a duplicated issue of https://github.com/Microsoft/vscode/issues/47373#event-1640085187 . But it's locked, so I opened an issue again.

I am not convinced with the reason the issue closed.
cmd.exe and PowerShell let you scroll past the end. And if you shrink the entire viewport, the editor also shrinks.

**Comment by Tyriar** [comment]
Maybe I didn't explain it well but the reason it's closed is because the terminal is based on xterm and not the Windows console like conhost, because of this on Windows it's only possible via emulation so it acts like xterm. I'd be willing to reconsider if the Windows terminal manages to get a good implementation but right now I just don't think it makes sense to implement this for this reason. They have a feature request open at https://github.com/microsoft/Terminal/issues/122
