### ISSUE TITLE
Competing Language Configurations

### ISSUE THREAD

**Issue by no-stack-dub-sack** [microsoft/vscode#73798]
Hi - I realize the issue tracker is not for questions, however, I've [posted this question on SO](https://stackoverflow.com/questions/56121280/competing-language-configurations-in-vscode-extensions), poured over Google search results, and [asked the question in the Gitter chat room](https://gitter.im/Microsoft/vscode?at=5cda0030da34620ff9388d9b), all to no avail (with no responses), so I'm hoping to resolve this question with some insight from the developers / contributors, so I can finally move on. Your indulgence would be greatly appreciated (and then, of course, feel free to close the issue). 

My question is around competing language configurations. I am building an extension, however the users of my extension are sure to have other extensions enabled which provide language configs for this particular language. So, how is this handled?

I am simply trying to add an auto-closing pair, however, when debugging and packaging the extension locally, I cannot seem to get it to work. I am certain I am using the correct language ID, and the "Contributions" section of the extension shows that I'm contributing the language:

![image](https://user-images.githubusercontent.com/18563015/57815782-d9fa8200-7746-11e9-9778-b099d0b71da6.png)

My initial approach was to copy the language config from the other extension contributing this language, and just add the auto-closing pair, but I also tried just adding in only the auto-closing pairs section - neither seems to work.

My understanding from the docs, is that language configs can "enrich" VSCode's knowledge of a language it already knows about, so this suggests multiple config files should be OK. But what happens in the event that they both try to configure the same thing? Is that what's happening here? It's seems like its only taking auto-closing pairs from one config. 

Apologies if I'm not being clear enough, please also see the SO question I linked above, perhaps that's clearer. If someone can offer some insight on this, that would be much appreciated.

Thanks.

**Comment by no-stack-dub-sack** [comment]
@jrieken Any thoughts on this? As an update, I'm sure that my configuration file on its own is perfectly fine. When I disable the competing extension it works perfectly. So maybe the better question is: is there any way to augment an existing language configuration from a competing extension?

**Comment by alexandrudima** [comment]
You have reverse-engineered it correctly :).

The behaviour of conflicting language configurations (multiple extensions contributing a language configuration for the same language) is not something handled especially, so the behaviour is emergent and not designed.

The current behaviour is that extensions are scanned and sorted alphabetically by their name (the property in `package.json`). Extensions are split into 3 buckets: built-in, user-installed and under-development. Inside each bucket they are sorted by their name and the buckets have the above order.

In this order, each extension is analyzed and its contributions processed. Ultimately, the language configuration is a map from language id to configuration which ends up overwritten by the later extensions.

If you really really want to win, you can define your configuration in code and use `vscode.languages.setLanguageConfiguration` to set it, which in principle should win (as it would execute later). But even that might suffer from a race condition, because when you first open a certain language, we then read the configuration file from disk asynchronously. So if your extension is active before the language is first encountered, it is possible that the configuration file might win.

I'm sorry that this conflicting case is not really thought through...
