### ISSUE TITLE
Cannot type accented vowels on the integrated terminal

### ISSUE THREAD

**Issue by tairosonloa** [microsoft/vscode#73876]
- VSCode Version: 1.34.0
- OS Version: GNU/Linux (Manjaro with kernel 4.19 LTS)

I cannot type accented vowels in the integrated terminal. That's the info I can give to you:
- If I type «á» (dead key «´» + «a» key) it will transform into «a».
- If I type «´» (twice the dead key «´») it writes correctly «´».
- It doesn't matters if I use the canvas terminal o the dom one.
- It isn't a GUI or font issue, because the integrate terminal can show accented vowels (for example, from a file using `cat`). It's an input issue.
- I'm using a spanish keyboard.
- This issue happens on all my different machines.
- It happens on insider build too.

Steps to Reproduce:

1. Open visual studio code.
2. Open the integrate terminal.
3. Press dead key «´» and then a vowel key.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bcxpro** [comment]
@Tyriar    I do not think the description matches #6282 exactly. That one is only about the ~ sign with the Alt-Gr and only on Windows. Not the other Alt-Gr characters in the Spanish keyboard, not the accented characters. Everything except the ~ works fine (I guess the same in the Freanch/Belgian because nobody reported other behabiour)
On Linux, with my Spanish keyboard everything works perfectly.

My setup on Linux, Spanish keyboard, only ~ fails:
Versión: 1.34.0 (system setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Fecha: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

My setup on Linux, Spanish keyboard, everything works right:
Version: 1.34.0
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:55:35.507Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.20-041820-lowlatency

**Comment by Tyriar** [comment]
@bcxpro I think they all have the same root cause
