### ISSUE TITLE
GitLens text adornment is drawn over xml instead of in between lines

### ISSUE THREAD

**Issue by AArnott** [microsoft/vscode#73938]
Issue Type: <b>Bug</b>

With the latest update to VS Code, I noticed that GitLens' text sometimes overlaps the line above it instead of having an empty space created for it.
I suspect it's a regression from your (otherwise great!) "stable codelens" feature work in this version.

![image](https://user-images.githubusercontent.com/3548/57970349-869e5480-793d-11e9-8d6d-57cf821cbdf0.png)

After making any code change, gitlens text is correctly spaced:
![image](https://user-images.githubusercontent.com/3548/57970364-a7ff4080-793d-11e9-9977-8a6d9f31b037.png)

After which, if I switch tabs and come back to the file, it immediately reverts to its buggy overlapping problem.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.07GB free)|
|Process Argv|D:\git\MessagePack-CSharp\|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.3.0
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.26.0
jshint|dba|0.10.20
vscode-eslint|dba|1.9.0
githistory|don|0.4.6
xml|Dot|2.4.0
gitlens|eam|9.7.4
remotehub|eam|0.2.0
EditorConfig|Edi|0.13.0
tslint|eg2|1.0.43
vscode-npm-script|eg2|0.3.7
git-project-manager|fel|1.7.1
vscode-pull-request-github|Git|0.6.0
vscode-jasmine-test-adapter|hbe|1.4.2
vscode-test-explorer|hbe|2.10.1
docker-linter|hen|0.5.0
beautify|Hoo|1.5.0
docomment|k--|0.1.6
azure-pipelines|ms-|1.152.0
azure-account|ms-|0.8.3
cpptools|ms-|0.23.1
csharp|ms-|1.19.1
liveshare-logviewer|ms-|0.2.1
powershell|ms-|1.12.1
vsliveshare|ms-|1.0.182
team|ms-|1.149.2
debugger-for-chrome|msj|4.11.3
vscode-docker|Pet|0.6.2
vscode-versionlens|pfl|0.23.0
java|red|0.45.0
gitconfig|sid|2.0.0
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.18.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.16.2
vscode-icons|vsc|8.6.0
t4-support|zbe|0.4.3
vsc-docker|Zim|0.34.0

(1 theme extensions excluded)

</details>

**Comment by AArnott** [comment]
Um, you're not going to tell me what the duplicate issue is so that I can verify and follow it? You're letting _me_ find the duplicate? That's lame.

**Comment by jrieken** [comment]
> You're letting me find the duplicate?

Generally yes. That's why we have all those prominent hints to search for duplicated *before* filing an issue. I think that how most project work: look for existing issue first. 

And then, how about clicking the [`editor-code-lens`](https://github.com/microsoft/vscode/labels/editor-code-lens)-label, which I have added precisely for that purpose? With easy you will find the correct duplicate issue *and* for the future you will have learned how to existing find issues quickly.

**Comment by AArnott** [comment]
>  That's why we have all those prominent hints to search for duplicated before filing an issue.

Yes, and suppose I used those before filing the issue and didn't find the duplicate? Now I'm being assigned to do that again, after a 'bot' managed to find a duplicate but didn't do the favor of sharing its result with me so I can confirm/deny that it's a real dupe.

> I think that how most project work: look for existing issue first.

Yes, and most projects when they close an issue as a dupe they include the issue number that folks should be redirected to.
Suppose that someone else's search turns up *this* issue, and all they see is "it's a dupe" and they too have to repeat the search and keep searching through issues till they find the one that was deemed the worthy one to remain active (which may have seen been closed as well). Why not link all the dupes to the remaining issue so that anyone who finds any of the dupe issues can be lead directly to the real one?

**Comment by AArnott** [comment]
>  how about clicking the editor-code-lens-label, which I have added precisely for that purpose? 

Sure, that works, I see. Thanks. That said, it wasn't clear to me that you added the label for precisely that purpose. I appreciate the intent, but many projects use labels for all sorts of things, so it's hard for me to know just what is the most effective way to find the dupe issue across projects. 

Dupe of #71745

Not that hard. But danged useful for everyone who sees this issue later.

**Comment by AArnott** [comment]
Sorry. I'm probably reacting too defensively here. With 5000+ issues on this project, I imagine triaging all these is an unwieldly task. And you probably want to train your issue creators to minimize your work so that your life can remain sane and interesting. So I appreciate the efforts you're taking.

**Comment by jrieken** [comment]
> after a 'bot' managed to find a duplicate but didn't do the favor of sharing its result with me so I can confirm/deny that it's a real dupe.

The bot isn't nowhere close to being that smart - it only reacts to us adding the `*duplicate` label or us typing `duplicate of...`. We should probably update its message to use the assigned labels to narrow down on the issues of the feature area.

> And you probably want to train your issue creators to minimize your work so that your life can remain sane and interesting

Yeah, that the sad truth of things. Overs the years, triaging soo many issues, you are become a little dull. For us search is equally bad and that's why we use labels to narrow down quickly.

**Comment by eamodio** [comment]
Not to pile on at all, but actually having the duped issue linked is not only beneficial for everyone visiting this issue, it is also a signal on the "main" issue that it is maybe more important (if there are lots of dupes) or that the title should be tweaked to make it easier to find when reporting a dupe in the future. But I completely understand that the effort involved, because of the scale of this project, is great (and maybe just too much)
