### ISSUE TITLE
Can't expand reference in Find All References

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#7396]
![bug](https://cloud.githubusercontent.com/assets/22350/15888496/5f49c6d2-2d67-11e6-9081-cfbb0af31225.gif)

Sorry for the large steps...

- `cd vscode`
- `git remote add joao https://github.com/joaomoreno/vscode.git`
- `git fetch joao`
- `git checkout ae0f60e9469942097769b25e21ad597ba2db85aa`
- Open that folder in Code
- Open `src/vs/platform/telemetry/common/telemetry.ts`
- Find All References of `isOptedIn` in line 36.

**Comment by joaomoreno** [comment]
Can't reproduce after updating to last night's build...

**Comment by jrieken** [comment]
This can happen like so: (1) provider reports n references (potentially in non existent files), (2) we render all references (unchecked due to cost issues), and (3) load the file when you expand the tree note. If then loading of the file fails we show that behaviour. I have favoured that over big in your face error messages. 

Pretty sure you had a stale tsserver leading to this
