### ISSUE TITLE
Markdown "Show Source" should go to previous tab if open

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#74008]
Issue Type: <b>Bug</b>

![gif](https://user-images.githubusercontent.com/35271042/58038762-bc7e3d00-7ae5-11e9-993f-34a407276411.gif)

When using the Markdown preview, the "Show Source" action should be smart enough to know that the source is open and go to that tab. Same applies to the preview tab, if there is already a preview tab open switch focus there. Otherwise you're in this endless loop of creating duplicate tabs.

VS Code version: Code - Insiders 1.35.0-insider (a5536b8f5a16a10d859f3dec1e59701671bf069e, 2019-05-20T05:15:57.974Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.5.4
vscode-opennewinstance|chr|0.0.6
bracket-pair-colorizer|Coe|1.0.61
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.0
gitlens|eam|9.7.4
vsc-material-theme|Equ|2.8.2
prettier-vscode|esb|1.9.0
azure-virtual-machine-explorer|for|0.0.2
vscode-pull-request-github-insiders|Git|1.137.0
vscode-colorize|kam|0.8.10
theme-monokai-pro-vscode|mon|1.1.13
vscode-azureappservice|ms-|0.14.0
python|ms-|2019.4.12954
remote-containers|ms-|0.53.0
remote-ssh|ms-|0.37.0
remote-ssh-edit|ms-|0.37.0
remote-ssh-explorer|ms-|0.37.0
remote-wsl|ms-|0.36.0
azure-account|ms-|0.8.4
azurecli|ms-|0.4.5
vscode-typescript-tslint-plugin|ms-|1.0.0
debugger-for-chrome|msj|4.11.3
vetur|oct|0.21.0
vscode-docker|Pet|0.6.2
vscode-yaml|red|0.4.0
code-settings-sync|Sha|3.2.9
ayu|tea|0.18.0
WebTemplateStudio-dev-nightly|WAS|0.0.1914003
markdown-all-in-one|yzh|2.3.1

(17 theme extensions excluded)

</details>

**Comment by chirag64** [comment]
I'd like to give this a try

**Comment by chirag64** [comment]
Ok, I could use some help on this issue. I traced the click call to the function [openTextDocument in extHost.api.impl.ts](https://github.com/microsoft/vscode/blob/5cfeefdaa9d2ad673656a5511157b813349ec467/src/vs/workbench/api/node/extHost.api.impl.ts#L586), but am not sure if I should be making any changes here since it will very likely affect other functionalities as well.

I also noticed that if I have the file already open in the same split window pane, it will open that instead of creating a new split pane, but it is [calling the same code with the same parameters here](https://github.com/microsoft/vscode/blob/5cfeefdaa9d2ad673656a5511157b813349ec467/src/vs/workbench/api/node/extHost.api.impl.ts#L593) even when it opens a new pane with a new tab. So I am confused how calling the same function with the same parameter exhibits different behaviors (opening a new pane with a new tab vs opening an already open tab in the same pane).


![VSCodevideo](https://user-images.githubusercontent.com/591424/58764489-9de06300-8535-11e9-9e74-b232434d423b.gif)

Some pointers around this would be very helpful, thanks

**Comment by chirag64** [comment]
@mjbvz sorry for tagging you, not sure if you got a chance to see my previous comment. Can you please help out?

**Comment by mjbvz** [comment]
@chirag64 The api you linked to is a good starting point but that is part of core VS Code. You want the caller of that api, which in the case is the markdown extension. 

How I think this feature should work:

1. In the markdown extension, we maintain a [list of active previews](https://github.com/microsoft/vscode/blob/71deb5b6ee0c4157d70ecd7f8f2e112c5f4d81b9/extensions/markdown-language-features/src/features/previewManager.ts#L16). These should track which column created the preview. This is likely already passed in with `PreviewSettings`, we just don't store the resourceColumn anywhere as far as I remember.
1. When the [show source command](https://github.com/microsoft/vscode/blob/18146e8c71cc11179cc0f355471b88351fa09c48/extensions/markdown-language-features/src/commands/showSource.ts#L18) is invoked, use the preview's column information to decide which column to show the preview in
