### ISSUE TITLE
Graphical glitches after latest update

### ISSUE THREAD

**Issue by nahudalla** [microsoft/vscode#74058]
Issue Type: <b>Bug</b>

1. Open a file
2. Glitches appear on the screen

White rectangles were added manually by me. The bug still happens with all extensions disabled and on the insiders build. 

![Screenshot from 2019-05-21 09-14-13](https://user-images.githubusercontent.com/12059563/58096254-067d2680-7bab-11e9-94f7-4d3d4f8db624.png)

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 5.0.0-15-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4215)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|7.59GB (2.90GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.1
vscode-sqlite|ale|0.6.0
vscode-apollo|apo|1.6.9
rails|bun|0.13.0
vscode-gemfile|bun|0.0.2
vscode-standardjs-snippets|cap|0.8.4
solargraph|cas|0.19.6
vscode-standardjs|che|1.2.3
gitignore|cod|0.6.0
vscode-npm-script|eg2|0.3.7
auto-close-tag|for|0.5.6
auto-rename-tag|for|0.0.15
rest-client|hum|0.21.3
sublime-babel-vscode|jos|0.2.10
intellij-idea-keybindings|k--|0.2.32
node-module-intellisense|lei|1.5.0
python|ms-|2019.4.12954
cpptools|ms-|0.23.1
debugger-for-chrome|msj|4.11.3
sqltools|mtx|0.19.1
vscode-jest|Ort|2.9.2
ruby|reb|0.22.3
rust|rus|0.6.1
partial-diff|ryu|1.4.0
code-settings-sync|Sha|3.2.9
slim|sia|0.1.2
ReactSnippetsStandard|Tim|1.1.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.1.6
markdown-pdf|yza|1.2.0
markdown-all-in-one|yzh|2.3.1
html-css-class-completion|Zig|1.19.0

(1 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
We are building exploration builds that use a much newer version of our UI framework (Electron version 4.0.x). I wonder if this issue reproduces with one of these builds, could you try? Download:
* macOS: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCode-darwin-exploration.zip)
* Linux: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/code-exploration_1.32.0-1550490730_amd64.deb)
* Windows: [Download](https://az764295.vo.msecnd.net/exploration/14236f9f44cc7c94055bb8e65ebda29a4a91ddc7/VSCodeUserSetup-x64-1.32.0-exploration.exe)

**Comment by nahudalla** [comment]
Hi, I can confirm the issue is still happening with the Linux Exploration build. The screenshot is attached below. Please ask for any information you need to help debug this issue and I will provide it as soon as I can.

![Screenshot from 2019-05-25 13-26-08](https://user-images.githubusercontent.com/12059563/58372276-94ca1300-7ef1-11e9-8244-6e71dceb786c.png)

**Comment by pagewin** [comment]
This bug is present in "Code - OSS" builds as well, and it makes the integrated terminal completely unusable.
![vscode_gfx_glitch](https://user-images.githubusercontent.com/20141682/58377595-c7b4eb00-7f73-11e9-89ca-255814343a08.png)

VS Code version: Code - OSS 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-21T12:30:20.933Z)
_and_
VS Code version: Code - OSS 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-12T08:59:47.459Z)
OS version: Linux x64 5.1.4-arch1-1-ARCH

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.40GB (20.07GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
gitstash|art|2.1.1
gitlens|eam|9.8.1
extbundles-csharp|Fel|2.0.0
auto-using|Fud|0.7.8
csharpextensions|jch|1.3.0
docomment|k--|0.1.7
csharp-colors|log|0.1.3
sln-support|log|0.0.1
python|ms-|2019.4.12954
csharp|ms-|1.19.1
mono-debug|ms-|0.15.8
vscode-versionlens|pfl|0.23.0
msbuild-project-tools|tin|0.2.55
vim|vsc|1.8.1

(4 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

Unfortunately due to the nature of this flag, we currently cannot support a setting to set this on each startup.

**Comment by pagewin** [comment]
`--disable-gpu` fixes the terminal with canvas/auto set. I am not able to reproduce the preview issue reliably, but I'm not seeing it crop up either with `--disable-gpu`.

**Comment by cra0zy** [comment]
I have the same issues as well on one of my PCs.

**Comment by pagewin** [comment]
Also using a Radeon GPU with open source drivers (amdgpu).
```
2e:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev e7) (prog-if 00 [VGA controller])
        Subsystem: Sapphire Technology Limited Nitro+ Radeon RX 570/580
[...]
        Kernel driver in use: amdgpu
        Kernel modules: amdgpu
```

**Comment by nahudalla** [comment]
When launching with the `--disable-gpu` everything works fine. I'm also using a Sapphire Radeon RX 580 Nitro+ GPU with drivers from [Oibaf's PPA](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers).

**Comment by cra0zy** [comment]
So... it turns out that discord and opera also have corruption issues, so I checked my `pacman` log and discovered that mesa got updated as well. I think this might not be a vscode bug but a mesa/radeon bug.

**Comment by nahudalla** [comment]
It seems to be working fine now with the same VSCode version, after a GPU drivers update. It might've been a bug in mesa/radeon drivers as stated in the previous comment.
