### ISSUE TITLE
Custom key assigned to mouse can't take effort in VS Code

### ISSUE THREAD

**Issue by theglance** [microsoft/vscode#74106]
Issue Type: <b>Bug</b>

I assigned custom key `Previous Track`, `Next Track` and `Play/Pause` in Logitech Software `G HUB` to my mouse. But they can't take effort while I'm in Viusal Studio Code.
![Screenshot (41)](https://user-images.githubusercontent.com/40282945/58151031-0a887180-7c9b-11e9-833b-2eacab3d3b41.png)
But I can use my keyboard to do so.
My mouse is Logitech G703.
By the way this also happened in JetBrains IDEA.

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
reg|ion|0.0.2
intellij-idea-keybindings|k--|0.2.32
python|ms-|2019.4.12954
Go|ms-|0.10.2
java|red|0.45.0
vscode-xml|red|0.5.1
markdown-preview-enhanced|shd|0.3.13
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.18.0
vscode-java-dependency|vsc|0.4.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.16.0
vscode-maven|vsc|0.17.0
vscode-icons|vsc|8.6.0

</details>

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
