### ISSUE TITLE
vscodebot on GitHub incorrectly marks every issue as being 'integrated terminal'

### ISSUE THREAD

**Issue by mikemaccana** [microsoft/vscode#74136]
Issue Type: <b>Bug</b>

For example...

**Comment by mikemaccana** [comment]
... this one.

**Comment by DanTup** [comment]
> ... this one.

I think the bot uses ML and guesses the tags based on the contents of the issue. I don't think it's expected to be 100% accurate, but it helps reduce the effort for humans to do.

I suspect it tagged this one because you wrote "integrated terminal" in the subject, and it's learned that most issues that contain that phrase end up being tagged as it. I suspect the reason your previous issue was tagged with it is that it talks about PATH, and that probably comes up frequently in integrated terminal cases.

**Comment by mikemaccana** [comment]
Thanks @dantup. I see what you're saying about a feedback loop, to add to that: the bad behavior started started with #47940 - which doesn't mention the terminal in any way. I have mentioned terminal in some of the previous issues, but the signalling seems to be off. 

Does it tag everything **for you** with 'integrated terminal'?

**Comment by DanTup** [comment]
That one mentions emoji - and there have been a lot of emoji issues tagged as integrated-terminal:

https://github.com/Microsoft/vscode/issues?q=emoji+label%3Aintegrated-terminal

I wouldn't worry about tags - the Code team will reassign them as they see fit (and the bot will learn as they fix them).

> Does it tag everything for you with 'integrated terminal'?

It does not - and if you scan the recently opened issues, you'll see it's not doing it much either. I think you just happened to open issues that contained terms that had been in terminal issues, so the maths worked out that it seemed a good choice.

**Comment by mikemaccana** [comment]
OK. It's annoying for submitters - but if the bot to learns from the reassignments as you say (@chrmarti ?) it should go away on it's own. Thanks Dan.

**Comment by DanTup** [comment]
> It's annoying for submitters

I think you should just ignore the labels and assume they either mean nothing, or they will be fixed by a human when they get to it :-)

> if the bot to learns from the reassignments as you say 

I don't know the details because it's not open source (I wish it was :-)) but I would guess that it's being retrained periodically, so if an issue is re-tagged by a human, that would eventually be fed back into it. It's all speculation though (and some of it, like certain assignments seem to just be [simple rules](https://github.com/microsoft/vscode/blob/master/.github/classifier.yml)).

**Comment by Tyriar** [comment]
All the labels really do is assign someone, so it ends up coming to me for me to triage. I'd say the success rate is over 50%, I could opt out of the assignment but it seems like it does more good than bad.
