### ISSUE TITLE
Git: Support deleting tags

### ISSUE THREAD

**Issue by dorsany** [microsoft/vscode#74147]
It's not possible to delete a specific local git tag using the visual code

command to delete:
```git tag --delete <tag name>```

can you please add this feature?

**Comment by jadeGeist** [comment]
Hi! I'd like to try working on this feature. (This would be my first contribution to open-source tho! Would I need to be assigned first?)

**Comment by lmcarreiro** [comment]
Command `git tag --delete <tag name>` deletes only local, doesn't it?

In Git Extensions, when you select a tag to delete, it gives you the option to choose a remote if you want to delete there too:

![image](https://user-images.githubusercontent.com/13019179/58383287-36616b00-7fab-11e9-84ec-c4dc32427dd0.png)

**Comment by xuhas** [comment]
Hi, I took a look at the feature and proposed a PR(#74345)(my first PR) some hours ago. The PR only deletes the tag locally because, as you can see in the git tag documentation, it is considered as a bad practice to delete or re-tag when it is already pushed since other developers may have seen it and it could bring confusion, at least this is my understanding of the discussion found in `git tag --help`.

**Comment by joaomoreno** [comment]
Fixed by https://github.com/microsoft/vscode/pull/74345
