### ISSUE TITLE
"Search: Focus Next Search Result" should put cursor in the editor panel

### ISSUE THREAD

**Issue by MeikTranel** [microsoft/vscode#74142]
Issue Type: <b>Feature Request</b>

When going through large refactorings based on search keywords it would be really nice if the `F4` Keybind would actually put the cursor in the code instead of just highlighting and focusing the next item.
EDIT: Currently the cursor only lands on the sighting if it was in the same file.

VS Code version: Code - Insiders 1.35.0-insider (4ca38ce5584d7cd67b435b3c32ef1240c6a29628, 2019-05-21T05:18:31.618Z)
OS version: Windows_NT x64 10.0.17763

**Comment by darrinholst** [comment]
related https://github.com/Microsoft/vscode/issues/69443

**Comment by MeikTranel** [comment]
I just verified that this is a regression using the following version:

_Version: 1.33.0 (system setup)
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763_

**Comment by skprabhanjan** [comment]
@roblourens , I just looked at this and found the following
[This](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/search/browser/searchView.ts#L744) is where the focus is set 
`next.range().startLineNumber` will give the lineNumber , But i could not figure out how to put cursor there ?

**Comment by roblourens** [comment]
That block fires an event which is debounced, then handled here: https://github.com/microsoft/vscode/blob/8cd962e8418660e52f4bb0a1896e085469e81bb9/src/vs/workbench/contrib/search/browser/searchView.ts#L710

The problem is probably in this code which handles selection and decides whether to preserveFocus (should be false for focus to go to editor) https://github.com/microsoft/vscode/blob/master/src/vs/platform/list/browser/listService.ts#L726

This code is a bit weird so it might be hard to understand. Or it might be an obvious mistake, not sure :)

**Comment by MeikTranel** [comment]
Oh now that's how that works.. i was trying my best... i'm not a TS dev but gave it a try and threw me off real hard 🤣🤣🤣

**Comment by skprabhanjan** [comment]
@roblourens , Found the issue.

- [onSelection](https://github.com/microsoft/vscode/blob/master/src/vs/platform/list/browser/listService.ts#L725) was not being called after we do [setSelection](https://github.com/microsoft/vscode/blob/8cd962e8418660e52f4bb0a1896e085469e81bb9/src/vs/workbench/contrib/search/browser/searchView.ts#L711) 
- The reason why this was not called is because of the function being [registered](https://github.com/microsoft/vscode/blob/master/src/vs/platform/list/browser/listService.ts#L703) this way 
- So there are two possible ways of fixing this , By removing the [condition](https://github.com/microsoft/vscode/blob/master/src/vs/platform/list/browser/listService.ts#L703) in `listService`  **OR** 
by setting the `openOnSelection` to true [here](https://github.com/microsoft/vscode/blob/8cd962e8418660e52f4bb0a1896e085469e81bb9/src/vs/workbench/contrib/search/browser/searchView.ts#L653)

PS : I thought the second way makes more sense and sent a PR for the same.

**Comment by roblourens** [comment]
Thanks @skprabhanjan but this is quite tricky and I am still not sure that I haven't broken something else.
