### ISSUE TITLE
Convert indentation to spaces/tabs *for selection*

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#7415]
At the moment these commands apply to the whole file. Could they apply to the selection if there is one?

**Comment by alexandrudima** [comment]
fyi @isidorn

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

P.S. If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
