### ISSUE TITLE
Font size settings for different displays/resolutions

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#7416]
I have two screens which I regularly switch between. My font size is configured to be just right on one of them, but it appears far too large on the other monitor.

This is probably an advanced feature request, but I would like to have a way to configure the font size differently for each display I have.

**Comment by coreh** [comment]
Are you using Windows? Maybe you could set the interface scaling factor on one of the monitors to something like 1.5?

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

P.S. If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
