### ISSUE TITLE
Cursor jumping to the beginning of the line on save

### ISSUE THREAD

**Issue by josser** [Microsoft/vscode#7417]
- VSCode Version: 1.2.0
- OS Version: OS X 10.11.5 (15F34)

Steps to Reproduce:
1. Create empty file with such content: 
   `code {
   some code {
      another code {
      }
   }
   }
   `
2. Save your file, and place cursor just after last opening bracket.
3. Press 'return' to make newline and press cmd+s to save your file. 
4. Notice, how cursor is jumping to the beginning of the new line ignoring indentation

gif: ![output](https://cloud.githubusercontent.com/assets/103639/15895846/1721cde4-2d96-11e6-9981-d22c8b7d6b9a.gif)

Thanks and sorry for bad english!

**Comment by alexandrudima** [comment]
@josser That is because you have enabled `files.trimTrailingWhitespace` and you are doing an explicit save. The whitespace on line 4 gets removed when saving.

**Comment by josser** [comment]
@alexandrudima No, files.trimTrailingWhitespace controls removing spaces at the end of the file but not in the middle of the file. 
However I've tried to set  files.trimTrailingWhitespace and editor.trimAutoWhitespace with no luck :(

It looks like we can't control this behavior at all.

**Comment by josser** [comment]
I think the best possible solution here is to 'leave cursor where it is'  during whitespace trimming.

**Comment by josser** [comment]
Maybe it's possible to allow user to choose with three options, like
Trim trailing whitespace on save: 
- no
- all except line with cursor
- all

**Comment by alexandrudima** [comment]
@josser 

> No, files.trimTrailingWhitespace controls removing spaces at the end of the file but not in the middle of the file. 

Having written that code, I am pretty sure that `files.trimTrailingWhitespace` trims trailing whitespace on every line. Code for proof: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/commands/trimTrailingWhitespaceCommand.ts#L41

Here is the current behaviour:

* none if `files.trimTrailingWhitespace` is set to false
* all except line with cursor if `files.trimTrailingWhitespace` is set to true and save is caused by auto-save
* all if `files.trimTrailingWhitespace` is set to true and save is explicit (i.e. ctrl+s)

I agree that the last bullet point needs additional configuration, perhaps we could change `files.trimTrailingWhitespace` to be true|false|"polite" where `"polite"` would make an explicit save skip lines with cursors on them.

@bpasero thoughts?

**Comment by bpasero** [comment]
Yes, I like that. Also its not a breaking change.

**Comment by josser** [comment]
@alexandrudima 
I've found the reason why when I've tried to change files.trimTrailingWhitespace = false it doesn't actually change anything. 
Everything is because I have editorconfig and specific settings for my project. 
So, when I disabled editorconfig everything became to work.

**Comment by erihanse** [comment]
Any update on this? Some languages (like go for instance) are dependent on file saves to run static analysis tools on the code.

**Comment by arulrajnet** [comment]
Tracking the same in editorconfig-vscode https://github.com/editorconfig/editorconfig-vscode/issues/47
