### ISSUE TITLE
TypeScript language server does not load plugins from tsconfig.json

### ISSUE THREAD

**Issue by Spensaur-K** [microsoft/vscode#74220]
- VSCode Version: 1.34.0 and 1.35.0
- OS Version: Ubuntu 19.04
- TypeScript Version: 2.2 and 3.5-rc

I have constructed a minimal example of a language service plugin for TypeScript to demonstrate that it does not load. The repository contains settings that specify that the workplace version of TypeScript should be used.

Steps to Reproduce:
```
bullfrog@swamp:~$ git clone https://github.com/spensaur-k/minimal-tsserver-plugin
bullfrog@swamp:~$ code minimal-tsserver-plugin
bullfrog@swamp:~$ cd minimal-tsserver-plugin
bullfrog@swamp:~/minimal-tsserver-plugin$ npm install
bullfrog@swamp:~/minimal-tsserver-plugin$ cd plugin/
bullfrog@swamp:~/minimal-tsserver-plugin/plugin$ npm link
bullfrog@swamp:~/minimal-tsserver-plugin/plugin$ cd ..
bullfrog@swamp:~/minimal-tsserver-plugin$ npm link minimal-lplugin
bullfrog@swamp:~/minimal-tsserver-plugin$ code test.ts 
```
After restarting the TypeScript language server and opening the test file, it can be observed that the plugin is not being run and the logs do not output any information for the plugin

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by mjbvz** [comment]
Thank you for the detailed repo steps and sorry for the delay following up.

I tested this and it looks like the issue is that plugins from the workspace can only be loaded if you are also using a workspace version of typescript. Once I switch to use the workspace TS version, I see the plugin loading:

<img width="604" alt="Screen Shot 2019-08-20 at 10 48 18 AM" src="https://user-images.githubusercontent.com/12821956/63371038-2a7e0e80-c338-11e9-954e-9d9418f77726.png">

This is a security restriction. We do allow plugins that are [bundled with  a vscode extension](https://code.visualstudio.com/api/references/contribution-points#contributes.typescriptServerPlugins) to always be loaded
