### ISSUE TITLE
Recent Workspaces list broken with UNC paths and root of a drive

### ISSUE THREAD

**Issue by lmcarreiro** [microsoft/vscode#74362]
- VSCode Version: compiled local from `master` branch
- OS Version: Windows 10

Steps to Reproduce:

1. Open a folder and select the root of a partition drive
2. Open a network folder
3. Close the folder

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/13019179/58384910-513dda80-7fbf-11e9-9fbc-f67d3a9a7ea0.png)

Got this while I was trying to fix #48403

The was a similar problem in issue #38546

**Comment by isidorn** [comment]
@aeschli you introduced the splitName so you would be the better one to review this.
Though I do agree that `path.basename` and `path.dirname` should do the thing for the welcome page.
@chrmarti also assigning to you since you own the welcome page

Feel free to assign back to me and I will just stop using splitPath [here](https://github.com/Microsoft/vscode/blob/0991cb526e878ec1ed4b17c4e99a451042092fab/src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts#L353)

**Comment by lmcarreiro** [comment]
I thought about putting a `.replace(/[\/\\]$/, '')` in the parameter of splitPath before calling it, but I didn't like it.
