### ISSUE TITLE
Question / Request: Shortcut to expand multi-cursors to word boundaries

### ISSUE THREAD

**Issue by dvlsg** [Microsoft/vscode#7437]
- VSCode Version: 1.3.0-insider
- OS Version: Windows 8 x64

Question: Is there a way to expand multi cursors to select each current word, even when the words aren't the same?

Here is an example of attempting to convert javascript object notation to properly quoted JSON, using multicursor support and the ctrl+d shortcut.

Functionality in Sublime (middleclick+drag, ctrl+d):
![2016-06-07t09_09_14-multiselect_word_boundaries](https://cloud.githubusercontent.com/assets/4721566/15910086/36a7e558-2d7e-11e6-94c9-c93417c97b2b.gif)

Functionality in VSCode (leftclick, shift+alt+leftclick+drag, ctrl+d):
![2016-06-07t09_09_14-multiselect_word_boundaries-vscode](https://cloud.githubusercontent.com/assets/4721566/15910108/5473fb9e-2d7e-11e6-8e57-92a8664a853c.gif)

Is there a shortcut / function that I'm missing which will expand all cursors to their respective boundaries? I know I can _technically_ get the same functionality through usage of ctrl+arrow key to get to the beginning or end of a boundary (where necessary) followed by shift+ctrl+arrow key in the opposite direction, but I've done it with a single shortcut for so long that the habit may be difficult to break.

**Comment by kumarharsh** [comment]
It is also very useful when I have multiple cursors on different *blocks*, such as functions, and need to select all the content in between the braces:

```
test1 = () => {|
  ...5 lines...
}

test2 = () => {
  ...100 lines...
}
```

Since the number of lines inside the block don't match, I need a way to select the whole block. vscode doesn't give any way to do that. And using multi-cursors with cases when I *can* select a range of text mostly fails, miserably.

**Comment by alexandrudima** [comment]
This works as expected since quite a while now...
