### ISSUE TITLE
Avoid __nodeRequire()

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#74398]
We still have a few places of a `__nodeRequire` that we should convert into `async import()`.

For example, code such as:

`this._keytar = <IKeytarModule>require.__$__nodeRequire('keytar');`

becomes:

`this._keytar = await import('keytar');`

**Places:**
- [x] `MainThreadKeytar` @chrmarti 
- [x] `readWindowsCaCertificates` @chrmarti 
- [x] `TerminalInstanceService` @Tyriar 
- [x] `RawDebugSession` @isidorn 
- [x] `Win32UpdateService` @joaomoreno 
- [ ] `RemoteAgentConnection` @alexandrudima

**Comment by isidorn** [comment]
@weinand actually added the dependency to `vsda`. However when I change the code to `await import('vsda');` I get an error that `vsda` can not be found. @weinand should we specify that we use `vsda` somewhere?
Code pointer https://github.com/Microsoft/vscode/blob/a00a9a29452546c6f5018f89d5c9f051f841dd38/src/vs/workbench/contrib/debug/electron-browser/rawDebugSession.ts#L531

**Comment by joaomoreno** [comment]
Isn't this still going async, deep down?

**Comment by weinand** [comment]
@isidorn `__$__nodeRequire` comes from the [vscode.loader](https://github.com/microsoft/vscode-loader). The owner of that package (@alexandrudima or @jrieken) should advise how to replace this with an `async import`.

BTW, 'vsda' is used in two places: RawDebugSession and RemoteAgentConnection. Please fix both of them since Alex is out.

**Comment by bpasero** [comment]
@isidorn yeah that sucks, we probably need to throw in a `vsda.d.ts` into `src/typings` to make TS happy :-|

**Comment by bpasero** [comment]
Updated the title, there is no difference in loading behaviour but I feel __nodeRequire() is really a hack from the times where we could not write `async import(...)`. It also gives us proper typing.

**Comment by jrieken** [comment]
> Isn't this still going sync, deep down?

Yeah, it's still equally sync. Writing `async import 'foo'` is the same as writing `new Promise(resolve => load_module('foo'))`. It still helps because it auto-generates `load_module` for you. 

> I get an error that vsda can not be found. @weinand should we specify that we use vsda somewhere?

Putting `declare module 'vsda' {}` anywhere in your code should help

**Comment by isidorn** [comment]
Thanks for advice.
Added vsda.d.ts and fixed the issue in `rawDebugSession`
Now strangly the `RemoteAgentConnection` can not `await import('keytar');` since that import violates the ts lint import rule. @bpasero should I put the vsda.d.ts in some other typings folder, since the `RemoteAgentConnection` can not depend on it from `src/typings`?

**Comment by bpasero** [comment]
It should be able to depend, then we need to tweak some tslint rule maybe.

**Comment by isidorn** [comment]
Ok. I have tweaked the tslint rule to allow vsda to be imported. Did not use a * to not allow random node modules to be imported there.
Seems to work fine now

**Comment by bpasero** [comment]
@isidorn looks like this is causing build failures and they can be explained by the fact that `remoteAgentConnection` is living in `common` when it should live in `node`. I am not sure why that is, maybe we should leave that one up for next milestone and move it properly.

**Comment by isidorn** [comment]
@bpasero yup, just saw the build failure. Reverting my commit.

**Comment by Tyriar** [comment]
I'll be replacing these with importing standalone modules soon:

https://github.com/microsoft/vscode/blob/652650732653c4c4ac1f0f54788486e76aea516e/src/vs/workbench/contrib/terminal/electron-browser/terminalInstanceService.ts#L37-L38

**Comment by Tyriar** [comment]
Terminal ones removed in https://github.com/microsoft/vscode/pull/74858

**Comment by isidorn** [comment]
@bpasero I can look into moving `remoteAgentConnection` to `node`.
@aeschli does this make sense to you? I see some modules from common depend on it, so I wold probalby split the remoteAgentConnection to have the implementation in `node` and `interfaces` in `common`

**Comment by chrmarti** [comment]
@bpasero Do you know why mainThreadKeytar.ts was placed in the 'browser' and not the 'node' folder? Maybe that was an oversight.

**Comment by isidorn** [comment]
@bpasero I looked into the `remoteAgentConnection` and it is a bit more complex. The issue is that it can not be nicely split up between `common` and `node` since the actual function that uses `require.__$__nodeRequire` syntax is used by other modules not living in node.
We seem to use the `vsda` module for signing when in the native environment. And due to that I believe we need two implementations of `connectToRemoteExtensionHostAgent` one for the native and one for the rest. So we basically get rid of [this](https://github.com/Microsoft/vscode/blob/ee070dc2db3bcd83c181a34752c698bddd163abb/src/vs/platform/remote/node/remoteAgentConnection.ts#L101) check.

I could also pass in the signer as part of the options, so the remoteAgentConnection stays in common and different clients would pass a signer.

**Comment by bpasero** [comment]
@chrmarti I noticed this and it is a bad hack, but I am not sure why that was done. The right solution would be to introduce a service for this and implement it in `browser` and `node` environments. 

@isidorn I do not understand

**Comment by isidorn** [comment]
fyi 
There is a difference in the behaivor of the `__nodeRequiere()` and `await import('')` 
When the module is missing, the second patter will only throw the error the first time you import the moduel.
Due to that I had to cache the promise to always have the expected behavior for the missing module

https://github.com/Microsoft/vscode/blob/18f4630bc51a3d87c7b31d96ca9c8ea95aa649b0/src/vs/platform/sign/node/signService.ts#L15

**Comment by isidorn** [comment]
Created https://github.com/microsoft/vscode/issues/75257 as a follow up
