### ISSUE TITLE
VSCode simply deleted file contents in my code folder

### ISSUE THREAD

**Issue by SHxKM** [microsoft/vscode#74539]
I don't quite know what to say right now. Yes, I should have known better - I should have pushed changes to git. Just as I made a breakthrough with my code, I tried to copy a file (within VSCode menu), and suddenly the file went blank, and poof. Hours of work are gone. 

I don't even have the mental will to describe this issue. In 4 years with PyCharm this has NEVER happened to me.

And yes, I obviously did the save the file continuously during development. VSCode just deleted everything and I can't revert.

**Comment by kieferrm** [comment]
@SHxKM sorry to hear that you lost work. It would help us if you could describe in more detail the steps you took. Thanks!

**Comment by SHxKM** [comment]
It’s a .py file that I was working on for hours today, modifying it many times. I think it happened right when I tried to copy/duplicate it to another folder because I wanted (oh the irony) to verify I always have a version of this working structure.

The file tab was definitely open, I don’t know if it was the active tab. Right after that it was empty. I tried restoring it from \__pycache__ to no avail.

**Comment by kieferrm** [comment]
@SHxKM thanks. A couple more questions:
1) Did you have autosave enabled or not?
2) Was the file dirty when you moved it?
3) Did you move it using keyboard shortcuts in the file explorer, or the context menu on the file explorer, or in how did you do it?

**Comment by SHxKM** [comment]
@kieferrm 

1. I’m away from my computer but I’m pretty sure I don’t have auto save enabled. 

2. I didn’t know. I would like to assume I’ve saved it but I can’t say with any degree of certainty.

3. Can’t recall precisely. Either with CMD+C CMD+V or the browser on the left.

Sorry for the lack of detail, you can understand how these kind of incidents can cause memory blackouts for developers.

**Comment by kieferrm** [comment]
@SHxKM thanks for trying to remember. 

@bpasero @isidorn FYI

**Comment by bpasero** [comment]
@SHxKM is it possible that instead of duplicating the file you where cutting and then pasting it? We have a bug in our current stable release that doing cut+paste of a dirty file will revert the contents. However that would not explain that the file ended up empty, unless the file was empty already?

**Comment by SHxKM** [comment]
There is no way the file was empty. 

I would be **cut**-pasting only if I made a mis click

**Comment by thomas-darling** [comment]
I've encountered this bug a few of times too, and I think they ware all within the past month or so.
I'm not entirely sure what happens, so this may not be exactly right, but I _think_ it's something like this:

When you try to make a copy of a file, by pressing the `option` key (I'm on macOS 10.14) while dragging the file to the same folder as the file currently resides in, it should create a copy of the file next to the existing file, with a number appended to the file name. However, when the bug occurs, it instead appears to overwrite the original file with an empty file instead. I don't remember whether the file was dirty before, but it definitely had content saved on disk, as I had to use source control to restore it.

It should be noted though, that I haven't seen this bug since I last updated VS Code, so it may have been fixed somewhere along the way - it's hard to say for sure, as it was pretty rare to begin with.
I'd encourage you to investigate further, as something strange was/is definitely going on here.

**Comment by SHxKM** [comment]
> When you try to make a copy of a file, by pressing the option key (I'm on macOS 10.14) while dragging the file to the same folder as the file currently resides in, it should create a copy of the file next to the existing file, with a number appended to the file name. However, when the bug occurs, it instead appears to overwrite the original file with an empty file instead.

While the above is alarming on its own, I’m 100% it’s *not* what happened in my case. I’ll leave it to the moderators to decide whether to split this thread.

**Comment by egamma** [comment]
@thomas-darling can you please file a separate issue with your scenario.

**Comment by thomas-darling** [comment]
@egamma I just encountered the bug I described again, so it is still there in the latest release.
I've filed it as separate issue (https://github.com/microsoft/vscode/issues/76861), including a screen recording as evidence :-)
