### ISSUE TITLE
Blinky lightbulb

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#74633]
![May-30-2019 11-54-30](https://user-images.githubusercontent.com/323878/58656768-be0fe800-82d1-11e9-82f0-cd590474288e.gif)

- Open https://github.com/microsoft/vscode-chrome-debug-core/blob/master/src/chrome/chromeDebugAdapter.ts
- Put the cursor on a tslint warning
- Get a lightbulb with quick fix suggestions, but it blinks
- Seems to be related to cursor blink

I think this is a regression from 1.34 but can't be sure because it doesn't happen totally consistently.

**Comment by mjbvz** [comment]
Repos for me in that specific file around line 90. Weird

**Comment by mjbvz** [comment]
Looks like a real js/ts bug but not a regression. Too risky to fix this iteration as it involves scheduling and how we manage errors for TypeScript

**Comment by mjbvz** [comment]
The cause:

1. VS Code requests diagnostics (it doesn't matter why, but it has to happen in a state where there is a pending `geterr` request against the TSServer for the current file)
1. In our js/ts refactoring provider, we tell TS server to cancel its current work computing diagnostics (because we want to service the code actions request as soon as possible)
1. This cancel the current `geterr` request to the tsserver, triggers a `refactor` request, and then reschedules a new `geterr` request with the current file in it
1. The refactor response is returned so we show the lightbulb
1. But then we get back the geterr response as well, which updates diagnostics in the current file (even if they have not changed)
1. The diagnostic change cause VS code to request code actions again...


I fully understand why this doesn't happen all the time
