### ISSUE TITLE
Allow the popups corresponding to the diagnostics in Problems List to show custom markdown content

### ISSUE THREAD

**Issue by samrat-gavale** [microsoft/vscode#74632]
Issue Type: <b>Feature Request</b>

Currently in the problems list feature, on hovering the squiggle that marks corresponding line in editor, a popup is shown with the same text as that in the diagnostic item in the problems list. Our extension wants to show more detailed markdown content in the popup, which would be different from that in the item in the problems list.

Below is our current experience. Using a decoration, our extension highlights a line and provides rich information about the code on that line in a pop-up. We provide external links within that pop-up and thus require Markdown. To make it easier to the user to find the highlighted lines and pop-ups, we also put them in the Problems list. However, now we have both a highlight and a squiggle and the pop-up shows our rich information in addition to the actual (non-Markdown) text from the Problems list item. We’d like to eliminate the redundant highlight and data and have a single experience/API, hence this request.

![image](https://user-images.githubusercontent.com/2177197/58655165-5b691d00-82ce-11e9-8e96-c306a27da69f.png)

I am aware of [issue 64566](https://github.com/microsoft/vscode/issues/64566) and [issue 54272](https://github.com/microsoft/vscode/issues/54272) which talk about extending the Problems List to allow markdown in the individual diagnostic messages itself, but our requirement is to have a short message in the diagnostic (as we have now) and a markdown based message in the popup revealed on hovering the squiggle tied to that diagnostic.

If this looks like an acceptable extension to existing Problems list functionality, I can go ahead and make the required changes and create a pull request.

cc: @sandy081

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.18908

**Comment by sandy081** [comment]
@samrat-gavale This is a duplicate of #54272. We had a discussion recently with the typescript team where they are looking for similar support - to support rich diagnostic message and mainly links. And they are working on some prototype for that. @mjbvz Can you please let us know what is the latest state on this from typescript team so that all of us can be in sync.

Regarding implementing this, it is easy to support markdown message in the editor but since we also show the same in problems panel, it requires some thinking on how to show there. 

Please continue discussion in other item.

/duplicate.
