### ISSUE TITLE
Improve directory appearance in search results

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#74637]
Issue Type: <b>Feature Request</b>

The directory path displayed in search results can be hard to visually parse. For each result the path starts in a different horizontal location based on the length of the file name.

It would be beneficial if the path formed a second column in the results (similar to how the result count is handled on the far right).

Also, listing the workspace folder (which I've redacted in first the screenshot below) next to each result adds visual clutter, isn't very helpful, and seems to be inconsistent from a design perspective. The results are a tree structure so it's already well known which workspace folder the result belongs to. No other tree view that I can currently find seems to re-display the context of parent nodes.

Current appearance:
![image](https://user-images.githubusercontent.com/484784/58661264-4b583a00-82dc-11e9-9caf-577342d9f4c3.png)

Desired appearance
![image](https://user-images.githubusercontent.com/484784/58661378-abe77700-82dc-11e9-8a0c-87408c9538e9.png)

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.16299

**Comment by roblourens** [comment]
The redundancy of the workspace labels is a good point. We reuse the same file label that we use everywhere but other places we don't put it into a tree with the same name.

Moving the folder into a left-aligned right column is difficult because it will have to be shifted every time an entry is added or removed from the list, meaning that the folders will be jumping around while the search is running. And the folder names will easily run into the file names, so I don't know if there's a way to make that part look much better. Always open to suggestions though.

**Comment by akbyrd** [comment]
I think the paths moving as results update is perfectly reasonable and expected. The results below one being removed or added will shift vertically, which is equivalent. Paths would also only move when the *longest* result changes, which is less frequent.

On file and names and paths physically colliding, the problem already exists, and although this will make it more likely to occur that's a good trade off to me personally. I can always make the panel larger and having absurdly long names isn't going to be the most common case. Since the search panel defaults to being docked at the bottom of the editor the new user experience is the best case for avoiding collision.

I would imagine that paths start after the longest file name and if they don't fit they simply get clipped in the same way they do currently. Even better would be if the path column were sized to the longest path and pushed as far to the right as possible to give as much visual space between the file name and path as possible (like in the mockup above).

You mention that you use the same file label in other, non-tree structures as well and that leads me to the realization that those places would benefit from the same treatment. For example, using Quick Open is actually equally problematic for me. I work in a directory with ~40 projects with the same physical structure which leads to a lot of files with either the same or similar names just in different directories. Getting to a specific instance of a file is more time consuming because it's harder to visually parse which directory each file is in. In this case the workspace folder is still useful so it's likely to be 3 columns instead of 2, but I think the same rules apply.

![image](https://user-images.githubusercontent.com/484784/58673156-101b3280-82ff-11e9-9e8f-9429abd9cbf2.png)

**Comment by roblourens** [comment]
I think that the names and folders colliding is a big problem because the filename should take precedence, but that can lead to lots of cases where you can't see the folder at all because it's hidden by the name, and that's an issue.

Putting the folder to the left of the filename would also help and there are a bunch of issues about that already. Having the folder separated even further from the filename by putting it in a column on the right would arguably make it worse for the people who want to see the full path and filename all together.

**Comment by akbyrd** [comment]
I agree the file name should take precedence. The path should be clipped before the file name.

There's not an infinite amount of screen space, so absurdly long files/paths are going to get clipped at some point no matter the chosen layout. That's not solvable in any reasonable way and I'd argue optimizing for the common case is the better option.

It could be driven by a setting if there's enough resistance to improving the layout.

**Comment by roblourens** [comment]
> There's not an infinite amount of screen space, so absurdly long files/paths are going to get clipped at some point no matter the chosen layout.

Sure but I think it's much worse to lose the entire folder because a short folder path is totally covered by the filename, than to lose the end of a folder path that runs off the end. The current approach uses the full horizontal space available, the proposed one wastes space in the interest of aligning things across rows.

I don't think this is a place for another setting. We have too many settings already...

**Comment by akbyrd** [comment]
> the proposed one wastes space
I'd vehemently argue that readability is not a waste. It's genuinely difficult to use currently.

> We have too many settings already...
The abundance of easy to manage settings is one of, if not *the* primary reason I use VS Code. They fill the gaps when the editor chooses not to optimize for the common case.

**Comment by koteyur** [comment]
May be it's better to simply right align folder paths.

I think it would be nice to have this:
![Screenshot from 2020-06-16 12-53-09](https://user-images.githubusercontent.com/4014972/84766076-805f2980-afd0-11ea-80c1-2363694817ed.png)
Instead of this:
![Screenshot from 2020-06-16 12-56-28](https://user-images.githubusercontent.com/4014972/84766298-dd5adf80-afd0-11ea-91c9-cef374eb24fd.png)

To be able to see which files are in the same folder and which are not.
It's really useful when you have a lot of search results in the large project.
May be it's not perfect, but I think it's not difficult to implement and it's better than current result list...

**Comment by akbyrd** [comment]
I'm not sure how much right aligning would help. The first thing I do when searching is looking at the paths because I typically have some idea of which region of code I'm interested in or I want to know where this result is going to lead. The issue with the existing implementation is that I can't easily identify the shared part of the paths because they all start in different places. Right aligning makes identifying the beginning of the path easier, which helps a little, but it doesn't address the fundamental problem.

**Comment by koteyur** [comment]
I agree with you, right aligning doesn't solve the entire problem, it's just a simple change in CSS but it would be nice to have at least this one for now...

**Comment by roblourens** [comment]
I wonder whether the new tree view in the search tree addresses this for you? For me, that view is totally superior and I won't go back to the flat list.

I don't plan to change the rendering of folders in the flat list.

**Comment by akbyrd** [comment]
That's disappointing. This is honestly a top 3 quality of life improvement for me personally, and seems like an objective UX improvement. Visual chunking and vertical alignment are powerful tools for communicating information more efficiently. It's the difference between trying to read a CSV file versus a spreadsheet.

The tree view makes it _harder_ to see the folder names if you want to see both the matches and their location, which I almost always do. And it does nothing to help the quick open panel.
