### ISSUE TITLE
Regression: octicons in other places appear larger now?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#74659]
It looks like e.g. the sync icon in the SCM view now shows much larger:

![image](https://user-images.githubusercontent.com/900690/58683811-392ada00-8376-11e9-8326-cca4cdf0c445.png)

vs stable:

![image](https://user-images.githubusercontent.com/900690/58683820-3fb95180-8376-11e9-9563-f41ba0a622ac.png)

I just checked and noticed that in the statusbar we seem to define a `font-size: 14px` but we are not doing that in other places where octicons can be used. There we seem to default to `16px`. Is this something we maybe need to define everywhere?

**Comment by bpasero** [comment]
Funky, it looks like the reason for the `font-size` not applying is the general `font` rule for octicon:

![image](https://user-images.githubusercontent.com/900690/58683892-8149fc80-8376-11e9-8856-322dc2d759b1.png)

So it is indeed set to `11px`, but not applied...

**Comment by misolori** [comment]
@bpasero I actually increased the size of the sync icon so that it was the same height as the rest (it was off by 1px) so this is a result of that. The icon in the SCM viewlet is now the same height:

<img width="497" alt="image" src="https://user-images.githubusercontent.com/35271042/58716300-95ddc300-837d-11e9-8e48-fe8c466feb86.png">

<img width="482" alt="image" src="https://user-images.githubusercontent.com/35271042/58716309-9c6c3a80-837d-11e9-9b09-f1a0bf673198.png">


I could revert the change, though that means the icon will be smaller everywhere else:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/35271042/58716228-6929ab80-837d-11e9-842b-d2c2da34e8ce.png">


<img width="477" alt="image" src="https://user-images.githubusercontent.com/35271042/58716223-662ebb00-837d-11e9-856e-a05899b916d8.png">

**Comment by misolori** [comment]
I'll revert this for now since endgame is almost over. If we want to make this the same height we can make the change in the next release.
