### ISSUE TITLE
Failed to install VS Code update

### ISSUE THREAD

**Issue by orhanncolak** [microsoft/vscode#74662]
Error while updating.

Updates may fail due to anti-virus software and/or runaway processes. Please try restarting your machine before attempting to update again.

If update fails repeatedly, please attach the following log file to a new issue on GitHub:

**Comment by kieferrm** [comment]
@orhanncolak you forgot to attach the log file. Thanks!

**Comment by KreciSie** [comment]
I had the same issue. When running code and trying to update it I get error pop out with "Failed to install VS Code update
Updates may fail due to anti-virus software and/or runaway processes. Please try restarting your machine before attempting to update again"

The pop out displays dir at C:\users\_username_\AppData\Local\Temp\vscode-inno-updater-1559394319.log.

The log contains the following:

Jun 01 09:05:19.932 INFO Starting: C:\Users\_username_\AppData\Local\Programs\Microsoft VS Code\Code.exe, false
Jun 01 09:05:19.933 ERRO Bad arguments: Code path doesn't seem to exist: C:\Users\_username_\AppData\Local\Programs\Microsoft VS Code\Code.exe

I have restarted the computer but update still failed. 
The directory C:\Users\_username_\AppData\Local\Programs\Microsoft VS Code\Code.exe does not contain code.exe 


I had my code started as administrator (Right  click the icon > Properties> Advanced > Run as administrator was checked) 

SOLUTION:
I have removed the check mark from "Run as administrator" and the VS Code updated to the latest version April 2019 (version 1.34)

**Comment by joaomoreno** [comment]
For people with User Setup issues, we recommend switching to the System Setup. 

> I have removed the check mark from "Run as administrator" and the VS Code updated to the latest version April 2019 (version 1.34)

Glad that solution worked.
