### ISSUE TITLE
wrong typing cursor position

### ISSUE THREAD

**Issue by nRewik** [Microsoft/vscode#747]
![animation](https://cloud.githubusercontent.com/assets/6581089/11443063/8c5c24de-954c-11e5-85af-85ce9837f9af.gif)

When typing in Thai language, the cursor position doesn't move as normal. It cannot navigate forward and backward.

I think this bug might also occur in some other languages.

**Comment by alexandrudima** [comment]
@nRewik This is a bug upstream in Chromium, see [#192](https://github.com/Microsoft/vscode/issues/192#issuecomment-166159048) and [Chromium issue 487028](https://code.google.com/p/chromium/issues/detail?id=487028).

Shipping this week is the January version of VSCode, where you can workaround this by using the setting `"editor.fontLigatures": true`. If that setting is on, some code on our side that workarounds the Chromium issue kicks in:

![thai-ligatures](https://cloud.githubusercontent.com/assets/5047891/12748185/fffe3338-c9a8-11e5-8577-55a397382f02.gif)

I cannot enable the workaround code all the time (it only kicks in if `"editor.fontLigatures": true`) because the workaround code assumes all text is Left-To-Right

**Comment by alexandrudima** [comment]
The workaround is no longer needed, we got the Chromium fix with our upgrade to Electron v0.37.6 which includes Chromium 49

**Comment by joaomoreno** [comment]
@alexandrudima a bit of help for verification?

**Comment by alexandrudima** [comment]
@joaomoreno Install Thai language, type on keyboard. Cursor should be at the end of the line.
