### ISSUE TITLE
Visual Code track changes in files that are not in a repository

### ISSUE THREAD

**Issue by MaxWhite20062003** [microsoft/vscode#74706]
Hi! Sorry waste your time with this, but, the Visual Code is tracking files that are not in a repository, there's a way to disable or hide that?
![Screenshot](https://i.ibb.co/5xnR84b/Capturar.png)

**Comment by kieferrm** [comment]
The git viewlet shows what git it seeing. Git thinks your home directory (if I interpret the screen shot correctly) is a git repository and that there are many untracked files in this repository. If your home directory is indeed a git repository, the `.gitignore` file is  how you tell git which files it should not consider untracked but ignore. Otherwise, make sure that your home dir is not a git repo (i.e. it should not have a `.git` folder (but be careful when deleting it).
