### ISSUE TITLE
Unicode Bangla doesn't work properly.

### ISSUE THREAD

**Issue by EmonHaque** [microsoft/vscode#74716]
While I was editing a latex document in Visual Studio Code v1.34.0, I noticed that some Bangla words hadn't been represented properly in VS Code text editor, however the PDF output from the latex file displays it correctly. MS Word also displays those words correctly. 

![Capture](https://user-images.githubusercontent.com/51259204/58745945-1f72bb00-847a-11e9-851c-f8f6586a0622.PNG)

On the left, VS Code editor broke down those words as I typeed and on the right, in the output PDF it is as it should be.

**Comment by kieferrm** [comment]
@EmonHaque does it make a difference if you add the following to your user settings?

```json
"editor.fontLigatures": true
```

**Comment by EmonHaque** [comment]
@kieferrm, no! It doesn't make any difference. Here in the last line I've added:

![1](https://user-images.githubusercontent.com/51259204/58834739-e737cc00-8675-11e9-944b-e57e21af95e4.jpg)

restarted after and and typed:

![2](https://user-images.githubusercontent.com/51259204/58834781-020a4080-8676-11e9-9150-956114339ce1.PNG)

**Comment by EmonHaque** [comment]
Have you fixed it already? I'm experimenting KDE Neon 5.16 and VS Code 1.35.1 renders all those words properly over there. Here's a screenshot from that Linux Distro

![Selection_001](https://user-images.githubusercontent.com/51259204/59742276-1e6dc600-928f-11e9-8ba8-77e7f9244d29.png)

I don't even have to enable Font Ligatures in VS Code!

**Comment by egamma** [comment]
@EmonHaque if I understand you properly this is now working in 1.35.1 and we can close the issue?

**Comment by EmonHaque** [comment]
@egamma, it works on Linux KDE Neon 5.16 but not on Windows 10. Here's how it is on Windows 10 1903:

![Capture](https://user-images.githubusercontent.com/51259204/59961084-09de3780-94f4-11e9-84de-e3b444e4b3c7.PNG)

**Comment by rebornix** [comment]
@EmonHaque could you please share the text you type into the editor to help me troubleshoot? I'd love to try that on my Windows box as well. BTW, do I need to install a specific language pack to ensure it being rendered properly?

**Comment by EmonHaque** [comment]
You could use any standalone Bangla font like [Kalpurush](https://www.omicronlab.com/bangla-fonts.html), that I'd used in Windows 10. I'm still exploring Linux distros, In all linux distros, I've tried so far (Fedora, Cent Os, Ubuntu, Debian, KDE Neon), these complex bangla words render properly.  

উদ্বৃত্ত
সঙ্কুলান
উদ্ধৃতি
বিস্তৃত

These 4 words have been typed in Arch Linux and it also renders those words correctly.

**Comment by rebornix** [comment]
@EmonHaque it looks like a browser rendering issue to me as when I open this issue in Edge on Windows, I saw exactly the same result as VS Code. Can you help confirm that the rendering is the same in both Edge/Chrome and VS Code?

**Comment by EmonHaque** [comment]
@rebornix,  I'd typed those 4 words in previous comment on VS Code in Arch Linux without changing `editor.fontFamily`. On both Windows 10 and Linux I use a software called Avro Phonetic Keyboard to type Bangla.

**Comment by rebornix** [comment]
@EmonHaque I found on Windows, to render `বিস্তৃত` it requires a good Bangla font installed and in a browser environment, we have to specify the right font family to use, otherwise browser will use the default system font to render it. VS Code is based on Electron which uses Chromium under the hood, we share the same experience. For typing, it doesn't actually a font to be installed, which means you can still type Bangla but the system can't guarantee that they are rendered properly.

I suppose if you install a language pack for Bangla through the system language setting, they can be rendered correctly but in VS Code, you might still need to specify a proper Bangla font. My suggestion is changing `editor.fontFamily` to `Kalpurush, Consolas, 'Courier New', monospace` to ensure it to be rendered correctly always.

**Comment by EmonHaque** [comment]
ok
