### ISSUE TITLE
Setting extensions path in settings.json

### ISSUE THREAD

**Issue by SupinePandora43** [microsoft/vscode#74718]
it can be useful with different workspaces

**Comment by SupinePandora43** [comment]
which info needed?!

**Comment by egamma** [comment]
@SupinePandora43 can you please provide an example of what you have in mind.

**Comment by SupinePandora43** [comment]
okay!
i have 2 different workspaces (first for Java, second for C#).
when i install new extension for C# (like auto-using), it will be also installed for java workspace.
but if i can set extensions path in workspace settings.json file:
i can set extension path (for java) to "E:/Extensions/Java",
and (for C#) "E:/Extensions/C#"
and now when i install new extension for C# workspace, it will not installed for java workspace

**Comment by egamma** [comment]
Thank you for providing more details. This is a valid feature request.

What you can do for know is to enable/disable extensions per workspace. So in the Java Workspace disable the C# extension in the extension viewlet.

**Comment by Sti2nd** [comment]
I thought it was weird that turning extensions on/off for a workspace isn't saved in the workspace settings.json. I don't want the Angular extension turned on when developing Java, but I don't want the Spring extensions on for all Java projects either. 

Could be seen as an inconsistency since pretty much all other settings are saved in some editable json file.

**Comment by Bessonov** [comment]
Isn't similar https://github.com/microsoft/vscode/issues/69958 ?

**Comment by SupinePandora43** [comment]
Ok
