### ISSUE TITLE
Image preview should only draw "transparent" checkered background for the size of the image

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#74710]
This image is quite small but the checkered background implies to me that all of that is part of the image.

<img width="904" alt="Screen Shot 2019-05-31 at 10 09 49 PM" src="https://user-images.githubusercontent.com/2193314/58744024-f2c69100-83f0-11e9-81dd-d09e693b313f.png">

**Comment by mjbvz** [comment]
Here's the code where we create the image for the resource viewer: https://github.com/microsoft/vscode/blob/3a054ddc9f63a14e651d0c349ca62d50acff0284/src/vs/workbench/browser/parts/editor/resourceViewer.ts#L536

We should be able to use css to add the checkbox  background

**Comment by bpasero** [comment]
I am no longer seeing a checked background:

Insiders
![image](https://user-images.githubusercontent.com/900690/60101930-f550a800-975c-11e9-931f-3ae9d3f3085c.png)

Stable
![image](https://user-images.githubusercontent.com/900690/60101944-faadf280-975c-11e9-8c6e-c7c6e8cece10.png)

I found the background a nice indication that I am indeed on a "canvas" kind of thing that can be zoomed in or out.

**Comment by mjbvz** [comment]
This is what this feature request changed. It is now more consistent with how programs such as photoshop display images with transparency, but it does mean that on non-transparent images, you will not see any checkerboard 

Any suggestions for how to make the "canvas" more clear

**Comment by Tyriar** [comment]
@bpasero photo editing apps definitely use a solid color for background and checkered for transparency. What you mentioned was by design as @mjbvz indicated. For those who use apps like gimp, photoshop, paint.net, etc. are used to this and having it the old way can incorrectly indicate that the image is larger than it is and is surrounded by fully transparent negative space.

@misolori opinions?

**Comment by misolori** [comment]
I agree that most apps do show the checkered only for the transparency portion instead of the entire canvas to show the dimensions of the image (the Preview app on Mac doesn't show transparency and is misleading/annoying). The GitHub desktop app also shows this (see below) so I'm in favor.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/35271042/60123640-cf1b1000-973c-11e9-8e89-1601c35d386a.png">

Keeping the same background as the editor is fine. Maybe a subtle border around the image could help in cases where the image blends with the canvas? We could try the same color as the panel border.

**Comment by Tyriar** [comment]
@misolori :+1: capturing that in https://github.com/microsoft/vscode/issues/76141 and closing this one off for verification again.
