### ISSUE TITLE
Enable the search box font to be enlarged

### ISSUE THREAD

**Issue by Mark-L6n** [microsoft/vscode#74799]
Please enable the search box font (and consequently the search box height) to be enlarged.  Currently it is very difficult for me to read regexes there.  While "editor.fontSize"  enlarges the main text, it does not also enlarge the search box text.
Perhaps you could add a setting "search.fontSize", or else make the search box font the same as "editor.fontSize".

**Comment by roblourens** [comment]
Does zooming in help? This will increase the size of everything in the UI. ctrl+plus or cmd+plus

**Comment by Mark-L6n** [comment]
Yes, this helps a lot (in conjunction with adjusting editor.fontSize smaller).  However, it's not ideal, as the zoom feature goes in large increments, and it would be nicer to be able to adjust the search box font relatively larger for working with a non-basic regex (which is harder to view than regular text).  I guess the best solution would be to have a setting something like "search.fontSize".

**Comment by roblourens** [comment]
I don't really want to add settings to adjust the individual sizes of different UI elements, this is very hard to maintain and test. But I can leave it open as a feature request.

**Comment by et304383** [comment]
Can we reopen this please?  My eyes struggle to see the text in the search box and I don't want to make the editor text larger.

**Comment by mike-clark-8192** [comment]
> I don't really want to add settings to adjust the individual sizes of different UI elements, this is very hard to maintain and test. But I can leave it open as a feature request.

I don't think this is necessarily a slippery-slope into adding configuration options for lots of disparate UI elements. Entering and editing complex search strings (especially regex) is very akin to the task of programming. We are allowed to configure the programming (editor) font face and size separately from the UI font because the level of visual resolution required for comfortably interacting with the UI is generally lower than the level of visual resolution required for comfortable interaction with program code. That, and variable width fonts are typically fine (even preferable, for compactness or in some cases natural-language readability) for interacting with the UI, whereas a majority of people prefer a monospace font for editing program code. Find Boxes exists in a sort of median space between having a UI role like a code editor, and having a UI role like a more standard UI element.

Perhaps a compromise would be to create a setting that tells VSCode to use (for search boxes where regex can be entered) the Editor's font and font size, rather than the UI's font and font size.
