### ISSUE TITLE
Intellisense, Add an option to delay validation (and thus wavy lines in code).

### ISSUE THREAD

**Issue by pr3tori4n** [microsoft/vscode#74798]
The intellisense validator is a bit too aggressive for typescript files. I haven't even finished writing my line of code before it starts flagging the current line I'm working on via a wavy underline (aka squiggly line).

Ideally, I could add a delay in milliseconds that will prevent the validator from running on the current file, something like **editor.validate.delay** with a default set to 50 or something small.

Alternatively, I'd settle for an option for JavaScript/Typescript similar to what exists only for PHP right now.
`"javascript.validate.run" = "onSave"`
`"typescript.validate.run" = "onSave"`
https://code.visualstudio.com/docs/languages/php#_linting

![exampleIntellisense](https://user-images.githubusercontent.com/12614215/58820737-3b946a80-85e8-11e9-893b-8ef596535c56.gif)

**Comment by mjbvz** [comment]
Keep in mind that this would also mean that squigglies that you fix would not go away until after the delay / save

**Comment by noppa** [comment]
+1 for this.

@mjbvz That's fine, since squigglies in code are normally a rare*ish* exception and not the normal state of the code. So I wouldn't mind it too much if the errors persisted until I saved, I'm usually pretty quick to hit that ctrl+s anyway :)  

@pr3tori4n's example is farily tolerable still, but when I have a bigger structure like an object expression or a class, TS can light up the whole editor in red while I'm just trying to figure out what I was supposed to write anyway, to the point where it's really distracting.

**Comment by mjbvz** [comment]
On second thought , this is exactly what [tasks](https://code.visualstudio.com/Docs/editor/tasks) already do. Just disable the built-in js/ts validator using `javascript.validate.enable: false` + `typescript.validate.enable: false` and setup a task to build your project instead. It should only update errors when the file on disk changes (i.e. you save it). You can also configure autosave if wish to have this happen after a delay

**Comment by noppa** [comment]
@mjbvz Is it possible to get the build output from typescript build somehow integrated with the Problems-tab and squiggly lines to the error locations instead of just printing errors to the Terminal-tab? I'm following the guide at [docs/editor/tasks](https://code.visualstudio.com/docs/editor/tasks) but can't quite get it configured nicely enough that the user experience would be as nice as with just `typescript.validate.enable: true`.
