### ISSUE TITLE
Can't open files or folders from server

### ISSUE THREAD

**Issue by azharameen** [microsoft/vscode#74835]
Issue Type: <b>Bug</b>

No files and folders from server is opening in vscode, same if i open from my system files I can able to work. What is the issue, kindly look into the issue and provide me a solution.

I was connected to an sftp server and trying to open files but It didn't opened.
Before 3 days this issue was not there, i can able to work from server files and folder.

Thanks.
Azhar Ameen

VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:55:35.507Z)
OS version: Linux x64 4.4.0-139-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz (4 x 2879)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.70GB (0.38GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.9.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.10
php-pack|fel|1.0.2
python|ms-|2019.5.17517
vscode-typescript-tslint-plugin|ms-|1.1.0

</details>

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
