### ISSUE TITLE
Minimap: support // Mark meta comments to support custom rendering in the minimap

### ISSUE THREAD

**Issue by pvinis** [microsoft/vscode#74843]
Take a look at the minimap of Xcode 11.
![Screenshot 2019-06-04 at 14 42 13](https://user-images.githubusercontent.com/100233/58880328-ef285800-86d7-11e9-8d28-b92f98f3410a.png)

- Nice and clean rectangles in the right size
- Colors from the syntax highlighting
- Titles/separators coming from `// MARK: UISceneSession Lifecycle` in this case, but it can be used in a bunch more languages

**Comment by egamma** [comment]
Have you tried the setting `editor.minimap.renderCharacters` to false?

Suggest to file a separate issue for separator support in the minimap.

**Comment by pvinis** [comment]
Hm nice. That fixed the nice and clean rectangles :D not great in size still. Also the colors I guess are correct too.

So actually what this issue is, is a way to configure the size of the rects, and the support for `// MARK` style separators.

**Comment by szotp** [comment]
Perhaps this could also support class and method names from file outline.

**Comment by rldaulton** [comment]
Ever since the release of XCode 11, I've wanted this. Really hoping this issue becomes a reality!

**Comment by mrousavy** [comment]
It's been moved to [here](https://github.com/microsoft/vscode/issues/95285), 4 more upvotes on the issue to move it to the backlog 😄

**Comment by mrousavy** [comment]
Can't find this in the backlog, is it already implemented in the current release? 🤔

**Comment by gcamp806** [comment]
I found it in the backlog. So glad this will be worked on!!

**Comment by mrousavy** [comment]
@gcamp806 do you have a link for the issue in the backlog?

**Comment by gcamp806** [comment]
@mrousavy the link on the backlog brings you back to this page... On the backlog page, I searched for "Mark meta" and had to keep scrolling for github to load more of the page. The issues are sorted by creation date, so scroll down to June 2019 and you should be able to see it.

**Comment by andyjeffries** [comment]
Any update on this? I keep thinking I'd really like to have this in VS Code...

**Comment by viniciusczanini** [comment]
I'm looking forward to this one!

**Comment by githubUnknownUser** [comment]
I'm looking forward to this one!

**Comment by sophiagatliff** [comment]
yes definitely want //MARKs! Super helpful.

**Comment by netgfx** [comment]
any info about this? It is really helpful especially in large files

**Comment by nxcco** [comment]
Is there any progress after 2 years?

**Comment by andyjeffries** [comment]
Not that I've seen. Super frustrating... I even tweeted saying I'd be happy doing the work on it if someone could point me in the right direction. https://twitter.com/andyjeffries/status/1399768200557088770

**Comment by andyjeffries** [comment]
Just to try to get some visibility, the main people that seem to have worked on the minimap are @alexdima and @RMacfarlane. Maybe tagging them may get the right eyes on this issue. Again, I've never used Typescript but I'm happy jumping in to help if I can just get some pointers on how to do it? Architecture guides on the minimap or VS Code in general? Any ideas for how you'd implement it, if you had time, etc.

**Comment by Guccifer98** [comment]
> Is there any progress after 2 years?

in settings:
      editor.minimap.renderCharacters to false is working great

**Comment by benjitusk** [comment]
Still holding on hope that this'll be included soon

**Comment by andyjeffries** [comment]
I agree, and as I said, if someone experienced in this area can give me some pointers - I'm happy to learn whatever is required to implement it. Let's hope someone jumps on this.

**Comment by DavidDHansson** [comment]
Is there any update for this?

**Comment by githubUnknownUser** [comment]
Sadly, no updates yet

**Comment by everdrone** [comment]
Would also love to see the `// MARK: -` with the 1px line separator in the editor view

**Comment by everdrone** [comment]
I'm trying to write an extension for `// MARK` comments but I can't find a way to only display a `border-bottom`, any extension developers know how? or is there an extension you know that already does something similar?

Also would be nice to have a way to make the decoration span the whole line, including the gutter/line number

**Comment by benjitusk** [comment]
Do u have a repo for this on GitHub? I’d love to see what u have so far.

**Comment by everdrone** [comment]
Not yet, still figuring out how to write extensions properly
But I'll link it here as soon as it's up

**Comment by everdrone** [comment]
@benjitusk here it is: https://github.com/everdrone/mark-meta-comments
Please feel free to try it out and open PRs!

So far it just adds a line above each `// MARK: -` comment, the objective is also to support decorators in the minimap.

**Comment by marcoslhc** [comment]
There is a hint to implement this in the Outline view: https://github.com/microsoft/vscode-cpptools/issues/7675

**Comment by ffernn-dev** [comment]
Still nothing on this? Would love to see it

**Comment by maxfierrog** [comment]
Coming from Xcode back to this and seeing that it still not up made my day a very sad one.

**Comment by reececomo** [comment]
It would be game changing to have rendered headings for `- MARK:`, `pragma` and `//#region`. Minimap hasn't received much love 🥲

Currently using the [Colored Regions plugin](https://marketplace.visualstudio.com/items?itemName=mihelcic.colored-regions) as a workaround, but would be amazing to finally see support for this added.

**Comment by glowcap** [comment]
Adding to this thread in hopes someone gets around to it. At this point, I'm almost bitter that there's anything in Xcode that I prefer over VSCode

**Comment by andyjeffries** [comment]
Me too, particularly bitter when I've already offered to help in doing it. I'll learn enough TypeScript to get it done. I just need a pointer in where in the codebase to start looking for it...

**Comment by dgileadi** [comment]
> Me too, particularly bitter when I've already offered to help in doing it. I'll learn enough TypeScript to get it done. I just need a pointer in where in the codebase to start looking for it...

I'm not a vscode developer but I have done some work to try to get this running. I don't have dedicated time to give to this so progress is slow and may fail entirely. In any case I can help point to where in the code to look.

The first main task seems to be detecting what should be displayed as a "section header" (which is what I'm calling the things that should be visible text in the minimap). I wrote some yet-untested code that uses vscode's built-in region regexes to detect region starts. I'm getting these regexes via `LanguageConfigurationService.getLanguageConfiguration(languageId).foldingRules`. Note that a single document may contain multiple languages, so the language ID comes from `ITextModel.getLanguageIdAtPosition(lineNumber, 0)` using the current line number. I also wrote yet-untested code for detecting `MARK:` comments with a simple regex. The main challenge here is detecting whether the line starts with a comment, and I do that by using `ITextModel.tokenization.getLineTokens(lineNumber)`, checking whether the first non-whitespace token is a comment, and then running the `MARK:` regex on the rest of the line if so.

The next main task seems to be rendering the section headers in the minimap as readable text. The minimap is coded to expect lines that are all the same height, which was quite reasonable until this change, and to render those lines using cached bitmapped font characters. These get rendered to an [ImageData](https://developer.mozilla.org/en-US/docs/Web/API/ImageData) and when the view changes only the necessary bits get re-rendered. This means that it's not super straightforward to add section headers since it's content with a different height and a different rendering method. In any case the starting point for all this rendering code is in [minimap.ts](https://github.com/microsoft/vscode/blob/main/src/vs/editor/browser/viewParts/minimap/minimap.ts).

There are also some new configuration options that will likely be needed, and they live in more than one place. Search the codebase for `minimapLineHeight` and you'll find where to put them.

Since someone will probably ask, I've pushed my changes to [a branch](https://github.com/microsoft/vscode/compare/main...dgileadi:vscode:minimap-sections). I'm well aware that my code is incorrect in some places (particularly my rendering code) and it currently doesn't even compile, so trying to run it will only end in tears.

**Comment by dgileadi** [comment]
I made [a PR](https://github.com/microsoft/vscode/pull/190759) but I guess I neglected to mention it in this issue. The minimap looks like the following with my PR:
![vscode-minimap](https://github.com/microsoft/vscode/assets/352830/96ccb921-1a35-4b20-b84f-e57d7124bd48)

**Comment by andyjeffries** [comment]
This looks absolutely epic @dgileadi !!! I assume it works with every language? (that reports comments as a syntax type)

**Comment by andyjeffries** [comment]
I don't know where comments should go, here or on the PR. I'll comment on the PR side though. Not working with one highlighting language.

**Comment by andyjeffries** [comment]
Wanted to publicly thank @dgileadi for this work!!!  Been a strong advocate of it for ages, and I'm so grateful for his efforts in the original PR, the reworked version and then keeping it up to date while waiting for it to be merged. Thank you!

**Comment by dgileadi** [comment]
> Thank you @dgileadi !

You're most welcome—thank you for helping it get all the way there!

**Comment by TylerLeonhardt** [comment]
Just stumbled upon this feature yesterday and really love it! 
<img width="892" alt="image" src="https://github.com/microsoft/vscode/assets/2644648/82ef6302-1e8a-4211-9194-d3cf78140e01">

Thanks @dgileadi!

**Comment by melroy89** [comment]
Thank you @dgileadi!

**Comment by melroy89** [comment]
One more thing.. what about also showing `TODO:`? Wouldn't that be great as well??

**Comment by dgileadi** [comment]
I think it would be awesome if there were an extension point for contributing "section header" items to the sidebar, but I didn't want to push this to be too complicated—it was already a lot of work to get this change in.
