### ISSUE TITLE
Add sideBarTitle.background color

### ISSUE THREAD

**Issue by xiongxliu** [microsoft/vscode#74958]
I want to set sideBarTitle's background, but only provide "sideBarTitle.foreground", I want a setting like "sideBarTitle.background".Please!!! I don't think it will take long.

**Comment by aeschli** [comment]
@bpasero Who owns the sidebar? IMO it's better if each view owner manages the colors of the part.

**Comment by bpasero** [comment]
@xiongxliu can you explain what you mean? A background color over the title of the viewlet?

**Comment by xiongxliu** [comment]
![image](https://user-images.githubusercontent.com/17661296/59170683-5d569a00-8b72-11e9-84f9-583e3fe9c94f.png)
I want to set the red block to be green. But I only find the sideBarTitle.foreground not sideBarTitle.background in setting.

**Comment by xiongxliu** [comment]
> ock to be green. But I only find the sideBarTitle.foreground not sideBarTitle.background in setting.

@bpasero  @aeschli

**Comment by jabacchetta** [comment]
Would also like to see this in order to create more separation between the title and the section headers.

**Comment by jabacchetta** [comment]
I was able to achieve this with the [Customize UI extension](https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui). Obviously this is a hack (and VSCode doesn't plan to support customizing the stylesheets), so this feature request is still needed eventually.

For anyone looking for a temporary workaround, install the extension and add the following to your `settings.json` file:

```jsonc
"customizeUI.stylesheet": {
    ".composite.title": "background-color: #1c252b; margin-bottom: 8px;",
},
```

**Comment by macintacos** [comment]
Just stumbled on this and honestly this just seems like a mistake/something that was left out. VSCode should add it so that there is parity with pretty much every other item that allows the background to be colored along with the foreground.

VSCode [recently made the the Customize UI extension basically irrelevant](https://github.com/iocave/customize-ui/issues/156) in newer versions of VSCode, so we can't even fix these issues manually with workarounds anymore (like @jabacchetta mentioned above), so these omissions are only going to get more bothersome as time goes on.

@bpasero can this be reopened? This doesn't seem "out of scope" considering all of the other properties one can edit in VSCode natively (hell, I can change the background color of the sections within the sidebar, but I can't change the color of the sidebar title itself, which just seems weird).
