### ISSUE TITLE
TypeScript syntax highlighting not working

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7496]
- VSCode Version:
  Version 1.3.0-insider
  Commit 2dbc938ccf6a985d4c474e28af54aff865f2ee46
  Date 2016-06-09T06:03:30.045Z
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Open code-insiders on vscode repo
2. Open terminalPanel.ts
  ![image](https://cloud.githubusercontent.com/assets/2193314/15945794/e6f836ea-2e48-11e6-852d-212cb1ca1526.png)

There is a module mismatch in the console as well, so `marked` is built with the wrong version of Electron? Also not sure why `marked` is being touched when opening a .ts file at all.

![image](https://cloud.githubusercontent.com/assets/2193314/15945857/22e85040-2e49-11e6-9c0f-75de4a78b3e9.png)

This is happening after closing and opening insiders again.

**Comment by Tyriar** [comment]
It's not happening anymore, I didn't update insiders or anything.

**Comment by alexandrudima** [comment]
That looks as if oniguruma was compiled natively with the wrong node version. I find weird that the error message shows `/node_modules/vscode-textmate/node_modules/oniguruma` instead of `/node_modules/oniguruma` given we now flatten the node modules.

@joaomoreno Do we delete the old node_modules folder before installing an update?

@Tyriar Can you check what your fs looks around the `node_modules` folder? I think it should be flat, otherwise it means the update is broken (leaving old nested `node_modules` behind).

**Comment by joaomoreno** [comment]
@alexandrudima Not sure what happens in Linux.

**Comment by Tyriar** [comment]
Seems fine (I've updated since I experienced this):

![image](https://cloud.githubusercontent.com/assets/2193314/16010611/e0424f3e-3136-11e6-80a8-74d774294826.png)

I'm going to close this as it hasn't happened since, will reopen if I see again.

**Comment by Tyriar** [comment]
This is happening again immediately after installing the latest insiders. Here's a full log after using it for 1-2 minutes http://pastebin.com/yS8pbwV5

JavaScript tokenizing was failing this time.

**Comment by Tyriar** [comment]
This is on insiders that's not working:

![image](https://cloud.githubusercontent.com/assets/2193314/16053098/3b151596-321c-11e6-9a1a-044efead590e.png)

So module flattening is not working.

**Comment by Tyriar** [comment]
Confirmed that deleting `vscode-textmate/node_modules` fixes the problem

**Comment by alexandrudima** [comment]
@Tyriar @joaomoreno 

I am sorry, I have no involvement in the update story.

This error appears when the build is broken (as in we ship and install on disk the **wrong** version of node oniguruma, compiled against the **wrong** electron/node native version). This might be caused by a number of factors, however none of those factors involve me :)

**Comment by Tyriar** [comment]
I haven't seen this since and it looks like it's due to the module flattening. I'll move to July for Joao to confirm then. We should see immediately by smoke testing the Linux packages.

**Comment by Tyriar** [comment]
See #8876 for the resolution on this.
