### ISSUE TITLE
Consider decreasing badge weight

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#74969]
Notice the badge in the activity bar. Previously the activiy bar icons were heavier and thus the badge fitted them quite well. The new icons look much lighter, and I argue that the badge is too strong. I would try to make it a bit lighter

fyi @bpasero

![Screenshot 2019-06-06 at 15 07 42](https://user-images.githubusercontent.com/1926584/59035133-e5842900-886c-11e9-8c5f-f316cd2e1140.png)

**Comment by bpasero** [comment]
Yeah maybe goes together with the idea of reducing the size of the activity bar?

**Comment by misolori** [comment]
I made the badge smaller:

<img width="25%" src="https://user-images.githubusercontent.com/35271042/59056222-91694c80-884c-11e9-9682-f404135ed0b1.png" />


This also matches what GitHub does on their badge on the desktop size:

<img width="25%" src="https://user-images.githubusercontent.com/35271042/59056185-7c8cb900-884c-11e9-8ae4-d7e26dcedd4b.png" />

Created #75013 to track reducing the width of the activity bar since I can't do this via CSS.

**Comment by isidorn** [comment]
Looks better now, thanks!
