### ISSUE TITLE
WE NEED OLD ICON BACK!

### ISSUE THREAD

**Issue by Rinimabi** [microsoft/vscode#75167]
Issue Type: <b>Feature Request</b>

WE NEED OLD ICON BACK!

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 6.1.7601

**Comment by gjsjohnmurray** [comment]
["Who Moved My Cheese?"](https://en.wikipedia.org/wiki/Who_Moved_My_Cheese%3F) @Rinimabi please help us understand why you NEED the old icon back.

**Comment by Rinimabi** [comment]
I think old icon was better.The new one was too similar to Visual Studio series products.

**Comment by AmirHosseinHmd** [comment]
#### The new icon is much better in each and every aspect. Such as:
1. Its difference with the icon of the Visual Studio IDE is now more recognizable.
1. It's modern-looking and prettier than the old one.
1. It matches the principles of Microsoft's Fluent Design.
1. It matches the new design of the Microsoft software family (e.g. Office, Microsoft To-Do, VS IDE, etc)
1. It's clearer on bluish backgrounds because it has shadows.
What your reason to say that the old one should be back?

**Comment by misolori** [comment]
@Rinimabi thanks for the feedback, this has already been captured in the comments of #71827.
