### ISSUE TITLE
Allowing extensions to solve conflicts / override TM Scope.

### ISSUE THREAD

**Issue by Huxpro** [microsoft/vscode#75176]
from https://github.com/jaredly/reason-language-server/issues/299 :
> I was trying to add `re` into the markdown embedded code block for Reason but found it's occupied by `regex_python`.
> I am not sure if this is injected by some third-party extensions or built-in. But Is there anyway we can override this?

<img width="1003" alt="Screen Shot 2019-06-09 at 10 14 30 PM" src="https://user-images.githubusercontent.com/5563315/59174062-8c362700-8b04-11e9-99fa-79cc4eab38f1.png">

Here I requested two features:
1. `Inspect TM Scopes` can provide information if the grammar is injected by some third-party extensions (so developers can know which extensions cause the confliction)
2. Provide a way for extensions to override the TM scopes  (on users allowance base)

---

Imaging we could have a dropdown menu in configuration to choose what language to use in fenced code block:

```
<Select name="re">
  <Item> regex-python (from Markdown Basics) </Item>
  <Item> reason (from Reason Language Server) </Item>
</Select>
```

**Comment by egamma** [comment]
>Inspect TM Scopes can provide information if the grammar is injected by some third-party extensions (so developers can know which extensions cause the confliction)

The recommend approach to track down whether an issue is caused by an extension, is to selectively disable extensions in the Extensions viewlet.

>Provide a way for extensions to override the TM scopes (on users allowance base)

TextMate grammars support customization, not clear what you are asking VS Code to do. Are you defining a grammar for Reason?

**Comment by msftrncs** [comment]
The construct
```
    ```re
    ```
```

is reserved for regular expressions (Python variety), in the Markdown syntax that VS Code uses:

https://github.com/microsoft/vscode/blob/673295580adb8fc4ebd70dcc38113e61ad491dba/extensions/markdown-basics/syntaxes/markdown.tmLanguage.json#L1322-L1325.

The Markdown syntax (in VS Code) has no support for Reason at all.  In order to override this I think you would have to provide a complete replacement for the Markdown syntax that included your own support for Reason fenced code blocks, or offer a PR to the repository that holds VS Code's Markdown syntax to add support (https://github.com/microsoft/vscode-markdown-tm-grammar).   According to GitHub's Linquist, the only supported name for Reason is `Reason`.  Linquist doesn't appear to support any language with the name `re` at all.

**Comment by Huxpro** [comment]
Thx @egamma @msftrncs !

> The recommend approach to track down whether an issue is caused by an extension, is to selectively disable extensions in the Extensions viewlet.

"selectively disable" doesn't sound like anything but pure manual bruteforce though.

> TextMate grammars support customization, not clear what you are asking VS Code to do. Are you defining a grammar for Reason?

> `re` s reserved for regular expressions (Python variety), in the Markdown syntax that VS Code uses:

Yep. The extension has supported `reason | reasonml` fenced code block in markdown. All of my concern is about if allowing extensions to "override" reserved grammar construct (e.g. `re` here) on user's allowance base could be good feature.

> According to GitHub's Linquist, the only supported name for Reason is Reason. Linquist doesn't appear to support any language with the name re at all.

`re` is the file extension for `Reason`, as `js` to `javascript` or `rs` to `rust`. Though they are not the official "display name" but users tend to use it in markdown though.

**Comment by msftrncs** [comment]
Markdown needs to be universal, one really should not go around amending it to suite a limited need, because later they will find undesirable results when they attempt to port their markdown file to another editor or viewer.  While Linquist can recognize the file extension '.re' it does not allow `re' as an alias in the fenced code block of a markdown file, for 'Reason', as far as I can tell.

I think I found what you might be looking for.  https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#injection-grammars.  This describes how you could create a injection to the a scope such as 'text.markdown' to add such support for Reason as part of the Reason extension.  Technically by using an injection, your injection would be usually detected before the existing grammar's own rules, as long as you use an `L:` at the start of the injectionSelector` property.

**Comment by msftrncs** [comment]
Clarification, that looks like what you are trying to do, but I don't know what your scope selector looks like.  That part is just off the edge in your image.   I'll do more research to try to see if you are missing something.

**Comment by msftrncs** [comment]
I looked at your repository's injection.

You are only attempting to perform your injection in to an 'unknown' code block.  To be more successful you should instead inject in to `text.html.markup`, and include the fenced block detection as well: `(^|\\G)(\\s*)(`{3,}|~{3,})\\s*`.  This is probably the only way to accomplish this.

**Comment by Huxpro** [comment]
@msftrncs thx for all your time providing all this information ;)

We actually injected to `text.html.markup` (https://github.com/jaredly/reason-language-server/blob/master/editor-extensions/vscode/package.json#L144-L152 and https://github.com/jaredly/reason-language-server/blob/master/editor-extensions/vscode/reason-markdown-codeblock.json#L11-L12)

But was trying to extend from `reason | reasonml` to `re | reason | reasonml` but found `re` doesn't work (because of the reserved `python-regex` TM scope).

**Comment by mjbvz** [comment]
Try copying your injection from [this example](https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example). If I change the example to use the `re` identifier, I can force `re` blocks to be highlighted as javascript:

![Screen Shot 2019-06-11 at 8 43 43 AM](https://user-images.githubusercontent.com/12821956/59286758-28574f80-8c25-11e9-8266-3c8d49e2

**Comment by Huxpro** [comment]
@mjbvz I cannot replicate your success. Did you just change from
```
"begin": "(?<=[`~])superjs(\\s+[^`~]*)?$",
```
to
```
"begin": "(?<=[`~])re(\\s+[^`~]*)?$",
```
?

To me, `inspect TM scope` still show `regex_python`

![Screen Shot 2019-06-11 at 11 43 31 PM](https://user-images.githubusercontent.com/5563315/59329043-c0dfe500-8ca2-11e9-851b-3302ad52d854.png)

**Comment by mjbvz** [comment]
Try with the update I just pushed to the fenced code block example: https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example/commit/e333677e840fd28f382935650553736aaebc2207

I confirmed it does work as expected with `re`

**Comment by Huxpro** [comment]
@mjbvz that's cool. Thx!
