### ISSUE TITLE
"Focus into Side bar" should be a toggle (switching focus to and back from side bar)

### ISSUE THREAD

**Issue by eyalroth** [microsoft/vscode#75183]
Action _Focus into Side Bar_ should be a toggle; i.e, when triggered from an open editor it should shift focus to the sidebar, but when triggered from the sidebar it should shift the focus back to the last focused editor.

This behavior is already implemented in regards to the _View: Show Explorer_ action, and it would be helpful (and more consistent) to implement it with regards to other types of views (such as search).

**Comment by isidorn** [comment]
I disagree. The action is called Focus into Side Bar, I do not think it should toggle it will be confusing.
Also you are the first user requesting this.
Due to the above I think you should just customise VSCode to do what you would like.

For example use the Ctrl/cmd + 0 shortcut to focuss into Side Bar which is default.
But also add a shortcut Ctrl/cmd + 0 to focus into editor when the focus is already in sidebar.
That way Ctrl/cmd + 0 will toggle as you want

```
{
            "key": "cmd+0",
            "command": "workbench.action.focusActiveEditorGroup",
            "when": "sideBarFocus"
      }
```

**Comment by eyalroth** [comment]
@isidorn That works too, thanks!
