### ISSUE TITLE
Extra pixels under status bar

### ISSUE THREAD

**Issue by yufw** [microsoft/vscode#75202]
There are some extra pixels under the status bar. Increase the font size to see it more clearly. Also, resizing the window vertically will change the width of the extra pixels.
![image](https://user-images.githubusercontent.com/3274661/59203055-65452700-8bd0-11e9-8722-0ef89264c822.png)

- VSCode Version: 1.35.0
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Launch VS Code

Does this issue occur when all extensions are disabled?: Yes

**Comment by yufw** [comment]
![image](https://user-images.githubusercontent.com/3274661/59203545-632f9800-8bd1-11e9-85b5-f57dff827f6d.png)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by yufw** [comment]
![image](https://user-images.githubusercontent.com/3274661/59265486-00dda280-8c78-11e9-9386-7dbda9499bf9.png)
Same problem with insider build, the extra pixels are dark, and the right boarder also gets some. If you resize the window, the extra pixels will also change.

**Comment by bpasero** [comment]
Yeah likely related to zooming, nothing we control as far as I know, but happy to learn otherwise.

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
