### ISSUE TITLE
Three click the line number to select a paragraph

### ISSUE THREAD

**Issue by yisibl** [Microsoft/vscode#7521]
- VSCode Version: 1.2.0 (1.2.0)
- OS Version: OS X 10.11.4 (15E65)

Steps to Reproduce:
1. Three click the line number
2. Select a paragraph

**Comment by yisibl** [comment]
@alexandrudima 

Or I think it would be better:

* Double click the  line number selected code block.
* Three click the line number Select a paragraph.

What do you think?

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

P.S. If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
