### ISSUE TITLE
Bug: Windows python launcher (py) in virtual environment in powershell has no command history 

### ISSUE THREAD

**Issue by BuongiornoTexas** [microsoft/vscode#75230]
- VSCode Version: 1.35.0
- OS Version: Windows 10

I've raised this issue here on advice of the python extension author (https://github.com/microsoft/vscode-python/issues/5718)

**Expected Behaviour**

If I launch python in a virtual environment in an external powershell using either:

```
py
python
```

I get a command history I can access using up arrow. I would expect the same behaviour using powershell in the integrated terminal.

**Actual behaviour**

I get the expected behaviour if I launch python with ``python`` in the the integrated terminal powershell.

However, if I launch using ``py``, the command history is not available. As this is very much an edge case, and there is a pretty straight forward work around, I'd regard this as a lowest priority bug. However, I'm reporting the issue as others may run into the same problem, and I'd rather they didn't waste as much time as I did trying to figure what the hell was going on!

``py`` works as expected outside of a virtual environment.

I haven't provided any logs, as the problem is an absence of history.

My apologies if this is known issue or problem - I did an extensive search and couldn't find any bug report matching this except for a reference to an up arrow problem that was closed for lack of reproducibility.

**Disabling extensions**

Does this issue occur when all extensions are disabled?:  N/A Python extension is required to allow selection of virtual environment.

**Comment by WSLUser** [comment]
I try running with both a python terminal and powershell. Sometimes by mistake since you can click on running either as the options are next to each other. I would still expect it to run properly including using the command history if I make a change to a dependency file that the py file runs through (such as reading through a json file).

**Comment by BuongiornoTexas** [comment]
@WSLUser  - I'm sorry, but I'm not sure if you are explaining a possible error on my part or a possible solution. 

To clarify my original, repeatable problem:

  1.  I start an integrated powershell terminal in vs code. 
  2. The python extension activates a virtual environment in the integrated shell.
  3. I start a python interactive session with ``py`` in the integrated shell. This session does not have a 
  command history.

If I use ``python`` instead of ``py``, the command history works correctly, and it always works as expected if I don't have a virtual environment active.

**Comment by WSLUser** [comment]
I was providing feedback for the maintainers. You mentioned this as low priority. I wanted to ensure it was treated otherwise and provided a use-case.

**Comment by Tyriar** [comment]
Our side just launches the process that the python extension says to launch, I do not think this is a problem with VS Code but rather with either python (since that is the program that manages the history, what's the difference between py and python?) or the python extension (which tells vscode what to launch and how).
