### ISSUE TITLE
Finalize runInBackground API

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#75278]
https://github.com/microsoft/vscode/blob/e50e16c9ecef21085adddee5c0098069a0b8ddba/src/vs/vscode.proposed.d.ts#L1087-L1096

@roblourens any feedback on this before we finalize?

**Comment by roblourens** [comment]
Nope it's worked great so far

**Comment by jrieken** [comment]
@Tyriar I know it's late but we might be able to find a better name here? I was a little confused at first because `background` has so many meanings. I wonder if we find something that describes better what's happening, e.g. the terminal is hidden from the UI. The hide/show-verbs are already used and talk about the terminal itself whereas this is about the "picker". Maybe `hideTerminalInUI` or `hideFromTerminalSelector`?

**Comment by Tyriar** [comment]
Going with `hideFromUser` after offline chat

**Comment by Tyriar** [comment]
Removed verified, new verifier please check that both `runInBackground` and `hideFromUser` work as expected.
