### ISSUE TITLE
ENOSPC errors not showing up on the gui, but breaks intellisense.

### ISSUE THREAD

**Issue by Jiyuu** [Microsoft/vscode#7528]
- VSCode Version: 1.2
- OS Version: Linux Mint 17.4 x64

When using vscode on Mint Linux the intellisense starts as broken.
with no clear indication of there being a problem.
only after toggling the developer tools and looking at the console is it clear some problem exists and googling it brings up the FAQ.

A user may just assume intellisense is not supported because no indication of an error is displayed on the GUI.

I believe such errors should be shown to the user with a link to the page explaining how adjust the configuration of the system to avoid them.

Steps to Reproduce:
1. install vscode on fresh vanilla mint 17.4 x64 (tested on 4gb ram , 2cpu core, 20gb ssd VMware player and virtualbox instances)
2. try to use intellisense functionality on a javascript project.

**Comment by alexandrudima** [comment]
@dbaeumer @Tyriar fyi

**Comment by dbaeumer** [comment]
@alexandrudima thanks.

**Comment by Tyriar** [comment]
@Jiyuu the fix was to increase the watch count in https://code.visualstudio.com/docs/setup/linux#_common-questions ?

I've been wondering how best to inform the user of this. As far as I'm aware, unless a Linux user explicitly has increased the limit in the past, this will always occur when opening a large folder in VS Code. The problem is that this error can also mean the disk has no space, not sure if there's a nice way to determine if so. It would certainly be awesome to have a popup with a button that opens https://code.visualstudio.com/docs/setup/linux#_common-questions

I recall @bpasero was working on some changes to not watch as many files which would lower the amount of users exposed to this. Did those changes go through?

**Comment by bpasero** [comment]
No.

**Comment by alexandrudima** [comment]
@dbaeumer we need to work together to figure out at least how to bubble this error back to the UI. I'm thinking it happens on TSServer start-up... ?

**Comment by Jiyuu** [comment]
@Tyriar Yup, that was the fix for me.
It should be mentioned that at least on my set up the project didn't need to be "big" at all, a simple folder with 2-3 files on the desktop already triggered this issue.

Obviously it would be best if it was possible to know what specifically is triggering that error, but even without knowing the exact cause, just knowing that there is some error is better than having things not working on the one hand but no indication of issue on the other.

**Comment by dbaeumer** [comment]
@alexandrudima I have https://github.com/Microsoft/vscode/issues/8716. However if the tsserver is not reporting the error back then I will not be able to do something.

**Comment by alexandrudima** [comment]
Tracking this in #8716 as @dbaeumer suggested
