### ISSUE TITLE
Auto suggestions stopped after latest version

### ISSUE THREAD

**Issue by tushargandhi23** [microsoft/vscode#75316]
VS code behaving strangely in terms of extensions. code errors are not being shown. 
I am not able to work on the vsCode as there is no intellisense.
When I restart VSCode it works fine for the first time then stops showing auto-suggestion and everything.

**Comment by axefrog** [comment]
Same issue here. I am developing an extension using Insiders and was experimenting with the official [code completion sample](https://github.com/microsoft/vscode-extension-samples/tree/master/completions-sample) and spending a lot of time trying to figure out why the `.` character wouldn't trigger the suggestions popup as per `provider2` in the sample code. It eventually turned out, after switching over to the stable VS Code installation and trying to run the sample from there, that there were no issues at all. For what it's worth, I did notice in Insiders that in my regular JavaScript code, method autocompletions were working when the window first loads, but stopped working in less than a minute, for no apparent reason.

**Comment by mjbvz** [comment]
Closing this as we need more information from the original poster about what is going wrong
