### ISSUE TITLE
all files appear empty after updating to version 1.35.0

### ISSUE THREAD

**Issue by Siddharthaghosal** [microsoft/vscode#75323]
Issue Type: <b>Bug</b>

This happened immadiately after update from  version 1.29

VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:17:12.481Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.67GB (1.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|6.2.1
es7-react-js-snippets|dsz|2.3.0
gitlens|eam|9.8.2
prettier-vscode|esb|1.9.0
js2chema|min|1.0.0
cpptools|ms-|0.23.1
Go|ms-|0.10.2
vscode-react-native|msj|0.9.3
vscode-docker|Pet|0.6.2
vscode-boot-dev-pack|Piv|0.0.8
vscode-concourse|Piv|1.7.0
vscode-manifest-yaml|Piv|1.7.0
vscode-spring-boot|Piv|1.7.0
quicktype|qui|12.0.46
java|red|0.46.0
shell-launcher|Tyr|0.3.0
vscodeintellicode|Vis|1.1.6
vscode-java-debug|vsc|0.19.0
vscode-java-dependency|vsc|0.5.0
vscode-java-pack|vsc|0.7.1
vscode-java-test|vsc|0.18.0
vscode-maven|vsc|0.17.1
vscode-spring-boot-dashboard|vsc|0.1.5
vscode-spring-initializr|vsc|0.4.5
markdown-all-in-one|yzh|2.3.1
vscode-proto3|zxh|0.2.2

</details>

**Comment by bpasero** [comment]
@Siddharthaghosal all files as in when you open a file or files that you had dirty? Is this a local file system?

**Comment by Siddharthaghosal** [comment]
@bpasero - all files as I open a file shows blank. Those files are not dirty. Its a local file system running Windows 10 . See an example
![vscode](https://user-images.githubusercontent.com/5062844/59409635-444d2380-8dd4-11e9-9237-b3377093b409.png)

**Comment by bpasero** [comment]
@Siddharthaghosal crazy, 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Siddharthaghosal** [comment]
@bpasero I will try that tonight. In the mean time does the following clue gives any idea of root cause ? I can see the error logg
![vscode2](https://user-images.githubusercontent.com/5062844/59419654-fdb5f400-8de8-11e9-973d-0007ae919028.png)
ed in developer console

**Comment by Siddharthaghosal** [comment]
@bpasero Bit more digging shows the following error during opening a ts file.  But no such error when opening a JSON file. Although the behavior is identical. Any ideas? 

 `ERR Unable to load and parse grammar for scope source.ts `

**Comment by bpasero** [comment]
@Siddharthaghosal looks weird indeed, another try is to run:

Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by Siddharthaghosal** [comment]
@bpasero : Thank you for the direction. But unfortunately still facing the same issue. 


![image](https://user-images.githubusercontent.com/5062844/59423185-48d30580-8def-11e9-87ee-e65357365da8.png)

**Comment by bpasero** [comment]
@Siddharthaghosal yeah these errors are weird, it almost seems like your installation might be broken. Give the insiders a try and if that works, do a full reinstall maybe.

**Comment by lostsaint25** [comment]
I'm also encountering this problem, but it only happens when I connect to a specific server. It worked fine before the update and everything appears to be fine on the server's end. Have tried uninstalling, purging, and reinstalling via repos and snap. 

Files open in other text editors and even in the terminal. 
Other servers are having no issues as far as I've seen.

![screenshot](https://user-images.githubusercontent.com/7665136/59632181-79bc7e80-90fe-11e9-8668-31b3ca7af50f.png)


Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:27:31.086Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-45-generic

Will try the nightly insiders build as suggested above.

**Comment by lostsaint25** [comment]
Tried running with `code --disable-extensions --user-data-dir emtpydir/`
Still empty. 
Saw this in the Output under Log(Window)
[2019-06-17 13:00:43.392] [renderer1] [error] Error: Error: ENOENT: no such file or directory, stat _'**workingdir**_/.vscode

I added a .vscode folder to the directory. When I reopened it again it just hung loading the file and folder contents on left sidebar.

Installed the insiders build. Still encountering same issues, nothing is in output or problems tab.

**Comment by bpasero** [comment]
@lostsaint25 how is that connection made to the server? Could I get some test access to try it out?

**Comment by lostsaint25** [comment]
@bpasero It's a client server so I can't give access, but I connect via sftp. Like I mentioned, it's working in other editors, file manager, and both OS and VSCode's terminal when if a display contents of the file.

Since my last comment, I tried the Remote Development extension pack but still having the same issues.

**Comment by lostsaint25** [comment]
@bpasero, I use the Linux Nemo file manager's "Connect to Server" feature to connect the server to my file manager. I then either open the folder through vscode's menu or right click and open with vscode. It mounts the server on my system to _/run/user/_UID_/gvfs/sftp:_server+user details_

The files showed up if I connected via FileZilla and right clicked a file and selected "View/Edit" but I think that's because FileZilla is creating a local temporary file and then reuploading it once it saves right?

I downloaded vscode and connected on a laptop and it worked without an issue. I created a new user on my PC and it was having the same issues. I removed the server from the file mananger's bookmark and removed it from my known_hosts file. I also removed my pc from the server's hosts.allow file.
I also did another uninstall/purge and reinstall of vscode (not insiders). When I reconnected, that seemed to do that trick, the files are showing up correctly now. 

Definitely weird, I'm not sure what part of all that fixed it, it was working before the update and other servers are not having any issues...

**Comment by bpasero** [comment]
@lostsaint25 you mean with the same setup but connecting to other servers it does not show these issues?

**Comment by lostsaint25** [comment]
@bpasero Yes, I was using that exact setup before the update and this server was working. After the update, I hadn't changed anything but it was having the issues, and nothing was changed on server side during all this.
Other servers using the same setup were fine before and after, it was only affecting this one for some reason.

**Comment by bpasero** [comment]
OK
