### ISSUE TITLE
Folding: C/C++: Can't fold entire function or #if - #endif when code is not aligned

### ISSUE THREAD

**Issue by Aukstkalnis** [microsoft/vscode#75338]
Issue Type: <b>Bug</b>

For example:
#if 0
// a lot of code...
#endif
You can not fold what is inside #if-#endif region, but all the code, that is inside is comment color. So I think it should be posible to fold entire block. 

Enother example is when folding blocks. Every block is folded by indentation. So if comment or some label is not indented in the block, folding is done only until that unindented line...

**Comment by gjsjohnmurray** [comment]
Anything smarter than indent-based folding is the responsibility of the extension that implements the language you're coding in. See [here](https://code.visualstudio.com/docs/editor/codebasics#_folding) for doc. Please raise this as an issue with whichever C/C++ extension you are using, and close this issue here because it's not a VSCode bug.
