### ISSUE TITLE
Tasks are not working at all on Linux after upgrade to 1.35

### ISSUE THREAD

**Issue by deitry** [microsoft/vscode#75498]
Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:27:31.086Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-48-generic

Steps to Reproduce:
1. Open new empty folder
2. Tasks: Configure task...
3. It doesn't show neither option to create new task, nor existing tasks that I manually add to tasks.json

Does this issue occur when all extensions are disabled?: Yes

The same bug in current Insiders version and 1.35.0 Stable. Bug is not present in code_1.34.0-1557957934 and code-insiders_1.35.0-1558329970

**Comment by alexr00** [comment]
How did you install VS Code? My steps to try to repro:
1. Create a new folder that is empty.
2. Open the folder in VS Code
3. Tasks: Configure Task
4. I was able to create a new task.
5. Tasks: Configure Task
6. I was able to select my new task from the quick pick to configure.

**Comment by deitry** [comment]
@alexr00 
I download .deb package through official download page and then install through `sudo dpkg -i <filename>`, the same way as usual. I have .debs of previous versions, If I install any of them before 1.35.0 Stable, tasks feature works as expected without any changes to settings. I use primarily Stable version, so I can't tell if feature became broken in one of 1.35 Insiders version.

**Comment by deitry** [comment]
This is how it looks.
v1.34.0 Stable.
In an empty folder:
![Screenshot_20190617_171804](https://user-images.githubusercontent.com/6714840/59611500-1cd3bf00-9124-11e9-9d67-6fe783003b05.png)
With a some added tasks:
![Screenshot_20190617_171303](https://user-images.githubusercontent.com/6714840/59611251-a3d46780-9123-11e9-99d9-3cf266cadc08.png)

v1.35.1 Stable. Blue progress thing just running forever and no entry is shown independentely of .vscode/tasks.json existence:
![Screenshot_20190617_171417](https://user-images.githubusercontent.com/6714840/59611253-a46cfe00-9123-11e9-86a6-f41d3e5e1256.png)

**Comment by alexr00** [comment]
Do you have any extensions installed? I'm wondering if one of them is providing tasks badly.

**Comment by TimMensch** [comment]
I'm seeing similar behavior on Windows, though in my case, only "detected" tasks are showing up in the "run build tasks." Custom tasks don't show up at all, and 90% of my Gulp tasks are undetected -- and as such they don't show up either.

In a completely empty folder, creating an "other" build task from the template results in a `tasks.json` with a task, but then "run build task" doesn't list anything.

Adding this to the `tasks.json` makes it appear and work, however:

```
"group": {
                "kind": "build",
                "isDefault": true
}
```

So it seems that a "build" task generated from the template doesn't actually default to being a "build" task now, whereas it did before?

Workaround is to add the `group` tag to the task.

**Comment by yuval-gilboa** [comment]
Same thing happened to me on Windows 64 bit.
I tried to fully re-install several times, using either User and System versions.
Setting typescript/npm auto-detect setting to false made the tasks visible, but executing them did nothing.
I noticed some error notifications regarding unrecognized tasks.

After reverting to previous version 1.34.0 all tasks returned to work as usual.

**Comment by deitry** [comment]
@alexr00 I have a lot, but running `code --disable-extensions` or moving `~/.vscode` to different location doesn't solve issue.

I tried to add `"group"` parameter as @TimMensch suggested, but it didn't changed anything, tasks are not visible and not executing through configured hotkeys. I am working with Python and C++ code so I have none "detected" tasks.

**Comment by alexr00** [comment]
@deitry @TimMensch @yuval-gilboa none of the behavior you're seeing is intended, but I can't reproduce any of it. Do you have a repository I can clone that shows the issues?

**Comment by alexr00** [comment]
One important note for typescript tasks: We now detect typescript tasks in a platform agnostic way so if you see "Error: The typescript task detection didn't contribute a task for the following configuration" if is probably that. In your task, you'll need to change your `tsconfig` attribute to use `/` instead of `\\`.
https://github.com/microsoft/vscode/pull/73001#discussion_r280155380

**Comment by deitry** [comment]
@alexr00
I didn't use Typescript and didn't use `\\` anywhere so it definitely not this issue.

I guess it's not repository problem because issue reproduces even with empty folder, with disabled extensions and with empty global `settings.json` (yes, I tried even this).

**Comment by deitry** [comment]
I remove ~/.config/Code folder manually and finally make it works again.
I will compare old and new folder and try to deduce what made it go wrong.

**Comment by deitry** [comment]
I move back old `~/.config/Code` folder and feature is still working. Hmm. I guess it was some weird cache files that made it broken. 

So, by now everything is working, though all my settings of which extensions should be disabled are seem to be lost

**Comment by yuval-gilboa** [comment]
@alexr00 
I get the error message you mentioned, but it's not due to slashes. We only use forward slashes.
We also only have shell/npm tasks, no typescript tasks with tsconfig attribute.

BTW, some of the developers on my team work on the same project on Mac and they don't experience these issues. Seems to only affect Windows.

**Comment by alexr00** [comment]
@deitry thank you for trying so many different things. It sounds like we don't have repro steps for it anymore. Is that correct?

@yuval-gilboa since your problem is only happening on Windows, can you open a new issue for it? If you have a repo I can clone to see the issue that would be ideal!

@TimMensch 
For your gulp detection and custom task problem, could you open another issue? This also sounds different from what @deitry describes. I'm not seeing any issues with gulp detection or with custom tasks, so if you have a repo I can clone that would really help.
> So it seems that a "build" task generated from the template doesn't actually default to being a "build" task now, whereas it did before?

For the Other task template, we never caused it to be a build task. However, it seems like a reasonable feature request to add that when the task is created from "Configure Default Build Task".

**Comment by deitry** [comment]
@alexr00 yes, it doesn't reproduces anymore. I believe there was some inconsistence in cached data or repo-wise settings which was not updated with the newer version of VSCode and then this somehow obstruct parsing of `tasks.json`.
