### ISSUE TITLE
Cursor position not maintained after returning TextEdit[] from provideDocumentFormattingEdits

### ISSUE THREAD

**Issue by lukehoban** [Microsoft/vscode#755]
I would have expected the cursor position to be maintained (as best it can in case it falls within a delete range) after applying a set of TextEdits returned by APIs such as `provideDocumentFormattingEdits`.  

Instead, I am seeing the cursor remain at the same absolute offset relative to the beginning of the source in the final result, which results in moving the logical location in source text where the user was editing.

Can Code automatically handle this when it applies `TextEdit[]` objects?  Or should extensions be adding their own logic to try and compensate for this?

**Comment by alexandrudima** [comment]
@lukehoban Can you please help me out with a specific before text, before selection and edit operations

**Comment by lukehoban** [comment]
I might not be able to, since we ended up using a pretty different approach to this.  I'll close this for now and will reopen if I'm able to recreate an example of the problem.

**Comment by yageek** [comment]
Would it be possible to reopen this ticket ? I think I am experiencing the same problem but with 
`provideOnTypeFormattingEdits`.

I would like to automatically add `//` after the user has returned `Enter`.

To do so, I subscribe with `registerOnTypeFormattingEditProvider` and I provide a listener with this implementation:

'use strict';

import { OnTypeFormattingEditProvider, TextDocument, Position, FormattingOptions, CancellationToken, TextEdit , Range} from 'vscode';

```
export class GoCommentsProvider implements OnTypeFormattingEditProvider {
	
	public provideOnTypeFormattingEdits(document: TextDocument, position: Position, ch: string, options: FormattingOptions, token: CancellationToken): Thenable<TextEdit[]>{
		
       //Detect if we are in a case of comments
		return new Promise((resolve, reject) => {
			
			let previousLine = document.lineAt(position.line - 1);
		
			if (previousLine.text.startsWith("//")) {
				let commentedAt = TextEdit.insert(position, "//");
				resolve([commentedAt]);
			}
		});
	} 
}
```

The problem here is that the final position of the cursor is the following:
```
// First line of comment -> Press entry
|//  Cursor is located before the addition
``` 

What I would like to achieve:

```
// First line of comment -> Press entry
// |  Cursor is located after the addition
```
