### ISSUE TITLE
Terminal doesn't respond after run an infinite bucle program

### ISSUE THREAD

**Issue by PeterMX** [Microsoft/vscode#7554]
- VSCode Version: 1.2.0
- OS Version: ubuntu 16.04

Steps to Reproduce:

1. Run a normal program, use "`Ctrl + c`" to close it, it works!
2. Run a program with an infinite bucle
     `while(true){print("bucle");}`
 
3. Use "`Ctrl + c`" to close it, it doesn't work, program is still working

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/126

**Comment by Tyriar** [comment]
pty.js issue: https://github.com/chjj/pty.js/issues/141

**Comment by Tyriar** [comment]
This was caused by the terminal doing DOM manipulation for all data that was coming in. Even for commands that completed in seconds, if they produced a lot of output, they would take a long time to display in the UI. https://github.com/sourcelair/xterm.js/pull/128 fixes this for the most part; the terminal will still take longer to execute for high-data commands than the pty, but it can be killed.
