### ISSUE TITLE
[debug] Jump to Cursor feedback

### ISSUE THREAD

**Issue by vadimcn** [microsoft/vscode#75578]
After having tried to implement the new "Jump to Cursor" functionality, I'd like to share some feedback:
- VSCode does not surface errors returned from `GotoRequest`.  Because `GotoTargetsRequest` does not specify which thread will be jumped, it is not possible to validate locations at that stage. (For example, language runtime may not allow moving execution point outside of the current function).
- The lifetime of `GotoTarget` not not clearly spelled out in the DAP spec.   Does adapter need to remember ids of all `GotoTargets` it had ever returned?   
- It would be helpful if `GotoTarget` contained adapter-defined data, that were round-tripped via subsequent `GotoRequest`.   This way adapter wouldn't need to remember GotoTarget<->id association at all.

**Comment by gregg-miskelly** [comment]
FYI the first issue is also a problem for the C# DA.

Also, I think the answer for the second question is that target ids should be valid until the next continue. Though specifying this in the spec sounds reasonable to me.

**Comment by isidorn** [comment]
@vadimcn @gregg-miskelly thanks for feedback.
I have pushed a commit which tackles the first issue. Please try it out and let me know how it behaves for you.

**Comment by weinand** [comment]
The general rule for ID lifetime in DAP is:

- IDs of "ephemeral" objects are valid while in the stopped state (or as Gregg said: "until the next 'continue'"). Examples are variable references, goto targets, step-in target, frames.
- IDs of long living objects are valid at least for the lifetime of the debug session (e.g. processes, threads), or even longer (breakpoints, data breakpoints).

I have created an issue in the DAP-repo for the clarification request: https://github.com/microsoft/debug-adapter-protocol/issues/60.

Round-tripping adapter-defined data is not an option any more because the DAP already uses IDs to  allow for communicating arbitrary data between "GotoTarget" and "Goto" requests. In addition it is cheaper to round-trip only an ID instead of the whole data.

**Comment by weinand** [comment]
Assigning to @isidor because he provided the only real code fix for the three issues.

**Comment by isidorn** [comment]
@vadimcn @gregg-miskelly can you please verify the 1) is fixed for you so I add a verified label. Thanks

**Comment by gregg-miskelly** [comment]
LGTM

**Comment by vadimcn** [comment]
Yeah, #1 looks fixed.

**Comment by isidorn** [comment]
Thanks. Adding verfieid label.
