### ISSUE TITLE
Icon align on mac  on "Open With" dialog

### ISSUE THREAD

**Issue by butuzov** [microsoft/vscode#75593]
- VSCode Version:  1.35.0 (1.35.0)
- OS Version: Mac - High Sierra 10.13.6 (17G6030)

Steps to Reproduce:

1. Click on associated file type and open "Open With" dialog

As you see - icon isn't really aligned with other icons.
![image](https://user-images.githubusercontent.com/651824/59566523-2c8ecd00-906a-11e9-9515-97f610863129.png)

**Comment by misolori** [comment]
I'm not seeing this reproduce on Mojave (10.14.3)

<img width="50%" src="https://user-images.githubusercontent.com/35271042/59614065-e02ca700-90d4-11e9-8c91-94b27fe8f240.png" />

@bpasero @deepak1556 does this sound like an electron or mac bug?

**Comment by bpasero** [comment]
Sorry I am not sure, @joaomoreno maybe?

**Comment by misolori** [comment]
I've got a High Sierra machine at home and interestingly enough this only happens on the stable build:

<img width="388" alt="Screen Shot 2019-06-17 at 8 42 00 AM" src="https://user-images.githubusercontent.com/35271042/59617968-2c2f1a00-90dc-11e9-9263-fa2ba66ee634.png">

**Comment by misolori** [comment]
Assigning to @deepak1556 to see if this is an electron related issue. I have a High Sierra machine if you want me to test anything.

**Comment by bpasero** [comment]
I kind of doubt this could be Electron related. Certainly could be an upstream issue or a bug with our icon.

**Comment by misolori** [comment]
Just inspected the two `.icns` (I extracted the pngs) files for Stable and Insiders and they are identical:

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/35271042/66344139-e6ec5d80-e901-11e9-8845-1625dd934c4f.png">

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
