### ISSUE TITLE
1.999.0 tag keeps getting added

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#75639]
Context: https://github.com/microsoft/vscode/commit/51245062b7615aea4c7eb900fea8fb91581482be

**Comment by octref** [comment]
This should be fine now.

**Comment by Ghostium** [comment]
I am so sorry to repeat myself but the tag exists again. Or have you changed something else?

**Comment by Tyriar** [comment]
@octref I wouldn't have thought people would be pushing tags mid iteration 😕

**Comment by octref** [comment]
@Tyriar The problem is I introduced a plague. Some of us might default to push with `--all` or `--tags`. When he pushes 1.999.0 back, everyone who pull will get the tag again...

I guess I'll create an Azure build that sends a warning in Slack when the tag gets pushed again.
If at a moment none of the tag-pushers have 1.999.0 tag locally and 1.999.0 doesn't exist on GitHub, the plague can be cured!

**Comment by octref** [comment]
After talking to GH support I know who's pushing the tag. I have messaged him and we should be good.

**Comment by Tyriar** [comment]
It's back

**Comment by octref** [comment]
Emailed GH support again. Lesson learned, will NEVER push a tag just for testing in the future...

**Comment by octref** [comment]
Found the guilty one, messaged him so his local tag is gone. I deleted the remote tag as well.

**Comment by Tyriar** [comment]
Well I have it now as well because I've pulled since it was added, so the next time myself or anyone else is the endgame master it back would be pushed back?

**Comment by octref** [comment]
So there could be timed bombs on anyone's machine...
OK, I'll make a bot that post a message any time this tag is pushed.

**Comment by octref** [comment]
The cop is in place:

![image](https://user-images.githubusercontent.com/4033249/64192565-d42cc780-ce2f-11e9-8caf-595adcc91018.png)

Hopefully no one get caught again!
