### ISSUE TITLE
Open In New Window from Explorer

### ISSUE THREAD

**Issue by kevinchatham** [microsoft/vscode#75652]
Often I need to open a workspace subfolder in a new window. Other editors have this option and it would be amazing to see this come to VSCode.

The user should be presented with an "Open In New Window" option when right-clicking a file or folder in the Explorer. Upon clicking it should open a new window with the folder / file loaded.

Recently I created [this extension](https://github.com/kevinchatham/VSCode-OpenWithCode)   to aide in the effort but it would be great if this option existed natively.

Right now the extension is launching a terminal and running `code -n --folder-uri ${folderUri}`. This is dependent upon code being registered in the system's path. There is probably a better way to do this and I will publish updates if suggestions are provided.

If this functionality exists and I missed it please leave a comment and close the issue. Thanks!

**Comment by isidorn** [comment]
The extension is the best way to go here.
Unfortunetly we will not add this to vscode, since we want to keep the product minimalistc and we like that users customise and install many extensions.
As for your implementation: that's sounds like the best approach for now.

Due to that closing as no plan to tackle this
