### ISSUE TITLE
File: Open Local is contributed in local workspaces

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#75737]
I just added a create new local terminal action in https://github.com/microsoft/vscode/commit/6520c22b83c0b6f168ba7de3309ffab42281e905, I delayed the action registration until after I verify whether it's a remote (non-web) workspace. Probably a good idea to do for the file ones as well?

**Comment by alexr00** [comment]
I updated it so they never show. There was not a good place to do delayed registration, so instead I am following the usual pattern to register them but not show them in the command palette. I also opted to never show them in the command palette (even on remote) because those commands were only added as a way to provide keyboard shortcuts while using the file picker. They were never intended to show.
