### ISSUE TITLE
Python Debugger closes after only 3 seconds

### ISSUE THREAD

**Issue by Bill-Fujimoto** [microsoft/vscode#75740]
Issue Type: <b>Bug</b>

1. open python file
2. Start debugger on current file
3.  After only 2-3 seconds, the debugger closes (control bar disappears and orange status bar goes back to blue)

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.5.18875
vscode-yaml|red|0.4.1

</details>

**Comment by gjsjohnmurray** [comment]
Sounds like an issue with an extension.

A plain install of VSCode does not include Python support, so you must have added an extension to give this. On the VSCode Activity Bar click the Extensions icon. Find the installed extension that's giving you your Python features. Look for the "Repository" link in its header. Click that. Go to the Issue section of its GitHub repo and open your ticket there. Then close this issue here, optionally including a reference to the issue you created in the other repo.
