### ISSUE TITLE
Ctrl + t not accurate

### ISSUE THREAD

**Issue by fatshi** [microsoft/vscode#75760]
Issue Type: <b>Bug</b>

when i use Ctrtl + t jump to a function define, VS just not give me the right position, eg: there are some function in a file(a python source file), i want jump to fun3, then I press Ctrl + t and input fun3, enter. result is VS jump to fun1

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.90GB (15.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2019.5.18875

</details>

**Comment by gjsjohnmurray** [comment]
A plain install of VSCode does not include Python support, so you must have added an extension to give this. On the VSCode Activity Bar click the Extensions icon. Find the installed extension that's giving you your Python features. Look for the "Repository" link in its header. Click that. Go to the Issue section of its GitHub repo and open your ticket there. Then close this issue here, optionally including a reference to the issue you created in the other repo.
