### ISSUE TITLE
Add option to drive breadcrumbs from view port top instead of current selection

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#75776]
This is related to https://github.com/microsoft/vscode/issues/26757 and the idea is to make breadcrumbs follow the view port and not the current selection. With that it will show the current context as you scroll, not just as you select/type.

**Comment by pr-yemibedu** [comment]
Hello,
 Not sure why it has to be mutually exclusive. Since both can be very informative. I don't always care what the next context is as i am just quickly glancing at other code. Once in a while, I do like to remember that another code block *is* still under the same parent and its indentation is not self explanatory. So having both is really the most ideal with an option for one of the four choices *`{none, cursor, viewport, both}`*. Thank you. Good day.

**Comment by jrieken** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/75645
