### ISSUE TITLE
Add "open JSON file" to UI settings

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#75855]
A lot of official and unofficial tutorials (as well as answers provided in Stack Overflow) reference settings to be added in the settings.json file, and on user studies we've seen people struggling to try to find where the settings.json file is stored. It'd be nice to have a "open JSON file" link in the UI settings page to improve discoverability.

**Comment by sandy081** [comment]
This action is available in the UI already.

<img width="954" alt="Screenshot 2019-06-21 at 12 44 52" src="https://user-images.githubusercontent.com/10746682/59917526-7852c500-9422-11e9-8946-3095f3b063f3.png">

**Comment by luabud** [comment]
I guess it could be more discoverable. In user studies no one noticed this option

**Comment by sandy081** [comment]
@luabud Is the problem is with the action icon?

**Comment by luabud** [comment]
Yes, I think it's not obvious what {} means. But then I can't think of any icon that would be more representative than that. I believe having a link with "open settings.json" would be more discoverable.

**Comment by sandy081** [comment]
Having a link is not good idea. It's a noise in the editor for lot of users who do not want to use the file. Showing it in the editor title area is consistent and discoverable, we have other similar actions in that area.

May be we should use a file icon instead of `{}`? We already use it at couple of places where we want to show the file behind

![image](https://user-images.githubusercontent.com/10746682/60087198-d17d6a00-973c-11e9-85df-9175696a8c82.png)

![image](https://user-images.githubusercontent.com/10746682/60087244-ed810b80-973c-11e9-8780-5ba1b96b0e5f.png)

![image](https://user-images.githubusercontent.com/10746682/60087281-01c50880-973d-11e9-832c-d96105af7480.png)


@misolori What do you think?

**Comment by luabud** [comment]
Oh I see! Yes, it does make sense. I like the file icon idea as well :)

**Comment by misolori** [comment]
We could use the "go to source" icon, we use a similar a file icon when you're in the json:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/35271042/60107933-98cd9880-971c-11e9-96a2-492f266ecb9d.png">

**Comment by misolori** [comment]
FYI @roblourens since this also affects Settings

**Comment by roblourens** [comment]
Would the icon change really make a difference? But it could make sense to use the same icon to toggle between the two editors. I will leave the decision to @misolori

**Comment by sandy081** [comment]
Verify https://github.com/microsoft/vscode/issues/75855#issuecomment-505476412
