### ISSUE TITLE
Poor UX for file refactorings

### ISSUE THREAD

**Issue by fgarcia** [microsoft/vscode#75877]
Moving and renaming files is one of my basic refactorings. I am so glad VSCode is capable of updating each import in my source code, however this task has to big pain points

1. There is no visual feedback/notification of what is going on. No "updating source code..." notification shown. I just found out the refactoring was done because lots of tabs open as modified suddenly 30 seconds later after I started working on something else.

PROPOSAL: show message on the status line, optionally pop a notification when done

2. File refactorings only work with a drag-drop action on the sidebar. That tends to be very painful on projects with a big tree layout or with limited screen space (ie: a laptop).

PROPOSAL: Add a context menu and/or a command reachable from "F1" where I can request to move file (makes the refactoring discoverable) and give the new path. It might be just typing a path, but also might be triggering a file explorer dialog

**Comment by sandy081** [comment]
@fgarcia What is the programming language of the files you are trying to refactor by moving?

**Comment by fgarcia** [comment]
@sandy081 Typescript

**Comment by mjbvz** [comment]
This slowness is https://github.com/microsoft/TypeScript/issues/30535. We do show a  message in the status bar while we are checking if a rename can be performed:

<img width="378" alt="Screen Shot 2019-06-21 at 2 13 58 PM" src="https://user-images.githubusercontent.com/12821956/59951798-d5ed0e80-942e-11e9-8b37-fda5aa54b9b6.png">

Unfortunately, even we a different UI, the rename operation would still be slow due to https://github.com/microsoft/TypeScript/issues/30535. We'll keep investigating the root cause of the slowness upstream.

**Comment by fgarcia** [comment]
My main concern was never the slowness. It was about how complicated it was to perform and discover the action.

It is not exposed as a command/action or a context menu. The only way to perform the action is through  drag and drop. Which is a big problem when working on a laptop (small screen) or big code trees (like a monorepo) 

@mjbvz Please, if you can, remove the "perf" tag. Also my status bar is not showing that notification, I might write another concern. Something like being able to type a path would ease so much using this refactoring

**Comment by fgarcia** [comment]
@sandy081 I've just re-edited the issue to focus on my concern. I hope it is clear now it was not really a typescript problem, but an issue with the editor interface
