### ISSUE TITLE
Document Formatter

### ISSUE THREAD

**Issue by mojtabakheyri1997** [microsoft/vscode#75889]
hello everyone
why vs code don't using default formatter for all kind of file types??
for example for PHP each extention php formatter not working
thanks

**Comment by DanTup** [comment]
@jrieken I don't know if it's the same as being reported here, but a Dart user was having issues with formatting not working:

https://github.com/Dart-Code/Dart-Code/issues/1822

It turned out to be that he had this in his user settings (and doesn't know where they came from):

```js
"editor.defaultFormatter": "vscode.configuration-editing",
"[html]": {
"editor.defaultFormatter": "vscode.html-language-features"
},
"[typescript]": {
"editor.defaultFormatter": "vscode.typescript-language-features"
},
"[scss]": {
"editor.defaultFormatter": "sibiraj-s.vscode-scss-formatter"
},
```

This of course breaks formatting for anything not listed above (since it tries to use the config formatter?). I wonder if whatever happened here may have happened to the OP here too, but I have no clue what it was. Does VS Code ever write global (non-language-specific) formatters after the user is prompted? All those configured are from VS code except one, and I checked it's repo but it doesn't seem to explicitly mess with the settings, and it only advertises formatters for css+scss.

**Comment by DanTup** [comment]
(cc @kdawg1406)

**Comment by DanTup** [comment]
Never mind, @kdawg1406 re-tested, and the config formatter was written in a `[jsonc]` section. It's not clear what happened for it to end up in the default space originally, but I'm sure if he sees it gain he'll open an issue :-)
