### ISSUE TITLE
[scss] linter update for variables in #{}

### ISSUE THREAD

**Issue by nagman** [microsoft/vscode#75905]
- VSCode Version: 1.35.1
- OS Version: Ubuntu 18.04

In this piece of SCSS code:
```
@for $i from 0 to 9 {
  .enterActive &:nth-child(#{$i}) {
    transition-delay: $i * 30ms;
  }
}
```

the `#{$i}` is parsed as an **id** (whether it's not), so the linter throws me that I shouldn't be using id selectors:

`Selectors should not contain IDs because these rules are too tightly coupled with the HTML`

![image](https://user-images.githubusercontent.com/16116486/59940091-1746e380-945a-11e9-85fa-01462e5dee45.png)

**Comment by octref** [comment]
Seems already fixed.

**Comment by aNickzz** [comment]
Running the latest build of insiders and this is definitely still happening

Version: 1.40.0-insider (user setup)
Commit: c58aaab8a1cc22a7139b761166a0d4f37d41e998
Date: 2019-10-22T05:27:32.053Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

![image](https://user-images.githubusercontent.com/15243523/67345525-e18a4680-f582-11e9-87fb-c8950ee19900.png)

**Comment by octref** [comment]
@aNickzz I can't repro from the original piece. Please open a new issue with reproducible steps.

**Comment by roblourens** [comment]
I also see this, I suggest that we reopen this and close the new issue to keep the history

**Comment by roblourens** [comment]
Make sure you enable that rule, `"scss.lint.idSelector": "error"`

**Comment by octref** [comment]
> Make sure you enable that rule, "scss.lint.idSelector": "error"

That's it. I didn't enable it explicitly.

**Comment by aNickzz** [comment]
Are you sure this should be labelled with `feature-request` instead of a `bug`? Maybe it would get a bit more attention with the correct label.

**Comment by aNickzz** [comment]
For my own reference, here's the source for this rule: https://github.com/microsoft/vscode-css-languageservice/blob/716292720c09f444167fd5528bcd4e6d1c6cc5db/src/services/lint.ts#L251

**Comment by aeschli** [comment]
It's a bug in the parser.

**Comment by aNickzz** [comment]
So, the linting rule checks for a `#` at the beginning of a SimpleSelector node. , this is a false positive because in this case the first (and only) descendent of the first identifier in the SimpleSelector is an Interpolation.

I would think that the linter could check for this and not add the Marker if the `#` is coming from an Interpolation. This is what I've done on [my fork](https://github.com/microsoft/vscode-css-languageservice/compare/master...aNickzz:master) and have had success running some new tests to check this.

As I'm not sure that the structure of the node tree will always be consistent with what I saw, so I did this by checking for an Interpolation at the first child of each node down the tree, rather than assuming that if an Interpolation node exists, it would always be the nth grandchild of the SimpleSelector.

![image](https://user-images.githubusercontent.com/15243523/100194767-3185ca80-2f46-11eb-8a21-9325590822b8.png)

However, if you're saying that this is rather a problem with the parser, rather than the linter, then I'm not really sure how to tackle this. I'd like to make a PR for this so please let me know what strategy you'd like to take for this.

---

Also, while looking through this I discovered that the SimpleSelector is checked as a whole as an ID selector, that is to say, only the first component of the SimpleSelector is checked for ID's

```scss
#id {} // This will raise a warning about an id selector
div#id {} // This will not raise a warning, as the id selector isn't at the front
```

Though that should be in its own issue I guess.

**Comment by aeschli** [comment]
Thanks @aNickzz for looking at this. Yes, I think you got this right, the linter check for `#` is too simple.
Instead of looking for a interpolation, what about looking for a IdentifierSelector node inside the SimpleSelector?

That would then fix the second point (no warning on `div#id {}`) as well.
