### ISSUE TITLE
mini map when I click on it does not redirect (INSIDER)

### ISSUE THREAD

**Issue by waguirre** [microsoft/vscode#75927]
- VSCode Version: 1.36-Insider
- OS Version: Windows 10

Steps to Reproduce:

1. When  click into minimap

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by chriswiley** [comment]
You can click and drag the highlighted area, but you can click in a non-highlighted area and have it move to that section of the code. I disabled the other extensions, reloaded the app and closed it out and re-opened it again. Still no go.

**Comment by alexdevero** [comment]
The same issue. Dragging the highlighted area on the minimap works. Click outside the highlighted area in order to move to that area doesn't work.
```
Version: 1.36.0-insider
Commit: 9ff8ae037e8e6109d65e4b5e3eb3dc60cc187e21
Date: 2019-06-21T07:52:00.716Z
Electron: 4.2.4
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by RicaBenhossi** [comment]
Just to add more information, it is also happening on VSCode Linux.

Version: 1.36.0-insider
Commit: e80dd4f217db6e230d311a87fdf4276f740f6445
Date: 2019-06-25T05:17:18.032Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-52-generic

**Comment by mikebronner** [comment]
I'm copying my info from the closed report at the top, as it's also happening on macOS (therefor across the board, it seems):

Issue Type: <b>Bug</b>

Since this build it is no longer possible to click on the minimap to jump to a position in code. Instead one is forced to drag the view-highlight in the minimap.

VS Code version: Code - Insiders 1.36.0-insider (9ff8ae037e8e6109d65e4b5e3eb3dc60cc187e21, 2019-06-21T05:18:36.348Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|32.00GB (10.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.0.14
vscode-tailwindcss|bra|0.2.0
npm-intellisense|chr|1.3.0
laravel-blade|cjh|1.1.2
vscode-markdownlint|Dav|0.28.0
vscode-eslint|dba|1.9.0
EditorConfig|Edi|0.13.0
vscode-npm-script|eg2|0.3.7
LogFileHighlighter|emi|2.5.0
file-icons|fil|1.0.17
auto-close-tag|for|0.5.6
gc-excelviewer|Gra|2.1.32
todo-tree|Gru|0.0.135
phpcs|ika|1.0.5
path-autocomplete|ion|1.13.3
sftp|lix|1.12.7
tailwind-sass-syntax|mac|1.1.1
dotenv|mik|1.0.1
vscode-duplicate|mrm|1.2.1
atom-keybindings|ms-|3.0.6
vetur|oct|0.21.0
code-settings-sync|Sha|3.2.9
vscode-wakatime|Wak|2.1.2

(1 theme extensions excluded)

</details>
