### ISSUE TITLE
Tab and backspace bug

### ISSUE THREAD

**Issue by Anekenonso** [microsoft/vscode#75939]
The backspace and Tab keys on the keyboard occasionally stop working. likewise some keys on the keyboard.

Does this issue occur when all extensions are disabled?: No

**Comment by Friksel** [comment]
I can confirm the TAB key 'randomly' stops working.

**Comment by rebornix** [comment]
Could you please follow https://github.com/microsoft/vscode/wiki/Keybinding-Issues to provide more information to troubleshoot when TAB stops working?

**Comment by Friksel** [comment]
> Could you please follow https://github.com/microsoft/vscode/wiki/Keybinding-Issues to provide more information to troubleshoot when TAB stops working?

I read the document you posted, but the tab-problem is not related to those troubleshoot-options. It's happening 'randomly'. Sometimes TAB stops working because something in the background is busy (sometimes we see for example the outline-panel showing a loading-bar). But it's also happening quite often that suddenly the TAB key stops working without any clue on why that is and than it never starts working again, so the only thing we can do is restart vs code!!

**Comment by Anekenonso** [comment]
since it's a general problem then!

**Comment by Friksel** [comment]
> since it's a general problem then!

So why did you close this important issue than? WIthout TAB key it's just impossible to have a fine workflow.

**Comment by Anekenonso** [comment]
I will just swap editor

**Comment by Friksel** [comment]
> I will just swap editor

Whatever you want, but I love VS Code, it's great and I'm not the only one loving it. This TAB thing just needs some love by developers to get it fixed. It's just a work in progress. Closing this issue just because you leave vs code doesn't help other users. Thanks for re-opening it.

**Comment by Friksel** [comment]
> I will just swap editor

Whatever you want, but I love VS Code, it's great and I'm not the only one loving it. This TAB thing just needs some love by developers to get it fixed. It's just a work in progress. 

Closing this issue just because you leave vs code doesn't help other users.
