### ISSUE TITLE
[debug] "Call Stack" viewlet shows terminated threads.

### ISSUE THREAD

**Issue by vadimcn** [microsoft/vscode#75980]
- VSCode Version: 1.35.1 (also tried current 1.36.0-insider)
- OS Version: Ubuntu 18.04

VSCode's `call stack` view seems to show all threads that ever existed, not just the ones returned by latest `threads` request.

Repro:
1. Build and run mock-debug extension from this branch: https://github.com/vadimcn/vscode-mock-debug/tree/repro-75980
2. Open the `debuggee` folder and start `test` configuration.
3. Expand all threads in the thread list and start stepping line by line.   After each step the adapter will reduce the number of active threads by one.   `stackTrace` requests for invalid thread ids will be failed.  By line 5, there will be only one thread remaining, yet VSCode tries to display all 5.

**Comment by weinand** [comment]
@isidorn make sure that only the threads returned by the last thread request (plus additional threads coming reported via the "thread" event) are shown.

**Comment by isidorn** [comment]
@vadimcn thanks for the nice repo steps.
I have changed that we now always respect the `threads` request as the absolute truth. So if a thread is not returned as part of the `threads` response we will delete it.
I have created a PR which tackles this and I will merge this PR in next week since now we are in endgame and I would like to get more insiders coverage so we catch potential extensions which might rely on the current bugy behavior.
