### ISSUE TITLE
WorkspaceStat.TAGS asks for trouble

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#76002]
I am not sure who added this, but I see access to `WorkspaceStat.TAGS` from some places (e.g. experiments). I find this a very weird way of reaching into something that should be internal. E.g. can we not have the diagnostics service expose this information as a method and then consumers use that service into having a dependency to workspace stats?

**Comment by sandy081** [comment]
Currently experiments service is depending on workspace stats and this dependency is very weird. Workspace stats is exposing a static constant which is used by experiments service.

For such usages we use services. So, please create a service for workspace stats and let experiment service depend on it.

It will also help in moving experiments service electron-browser namespace to browser namespace so that we can use it in web.

**Comment by sandy081** [comment]
Looks like WorkspaceStats is being used at multiple places. May be its best to have a WorkspaceStatsService.

@RMacfarlane FYI
