### ISSUE TITLE
deprecate 'useWSL' launch config attribute

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#76011]

**Comment by weinand** [comment]
- using the "useWSL" attribute in launch configs results in a deprecation squigglie.
- running a launch configs that uses a "useWSL" attribute results in a notification (with the option to turn future notifications off).

**Comment by isidorn** [comment]
This works just fine, adding verified label.
However in order to have this we have introduced a new setting
`debug.node.showUseWslIsDeprecatedWarning`
I am always against introducing settings for obscure scenarios that less than 0.1% of our users will hit.
My personal preference is to put this in workspace storage.
So if the user clicks ignore, he will no longer be reminded about the deprecation.
I can not imagine a scenario where a user would go to our setting file and be like "I would like to get that warning again" and change the value of this setting. If he remembers to do that he will actually just fix the thing and start using the extension, he will never change this setting imho. Thus it should not be a setting but in local storage per workspace.
