### ISSUE TITLE
Jump to cursor: doesn't show a warning if jumping to invalid cursor location

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#76079]
Testing https://github.com/microsoft/vscode/issues/76008

Title says it all.

**Comment by dbaeumer** [comment]
To reproduce try to jump to the end of the file.

**Comment by Tyriar** [comment]
Also saw this trying to jump to inside `Another`:

![image](https://user-images.githubusercontent.com/2193314/60123086-78610680-973b-11e9-8cdb-409144d297df.png)

**Comment by isidorn** [comment]
@gregg-miskelly it seems like the C# adapter is returing `gotoTargets` for the end of the file position. This appears to be wrong. Should we move this issue to the C# extension?
Also is it possible that you sent me via email a new version of your extension which does not require a handshake so I can eaisly test this when running vscode out of source? Thank you

**Comment by gregg-miskelly** [comment]
@isidorn I think you fixed this already in #75578.

The design of `gotoTargets` is that it will return all possibly valid targets -- any source location that has associated code will get a target. Then if you actually try to go to that target, now we have enough context to know that that location is invalid, and we will fail to the `goto` request. With your fix, I believe everything will now work properly as the test case in this issue is essentially identical to my test case when I validated your fix.

If you still want a debug build, I am happy to provide.

**Comment by isidorn** [comment]
@gregg-miskelly thanks. Yeah a debug build would be great for future stuff.
