### ISSUE TITLE
Debug: make "Attach to process" more prominent

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#76070]
I think the "Attach to node process" is one of the most useful actions in debug land. I love how it works and it is my favorite way how to start debug when I run a program from the command line.

However, this command is burried within the command palette and I guess one reason is that it is contributed from the node.js debugger extension.

Ideally I would want to see this action both in the launch dropdown as one of the last entries there as well as the debug menu. 

Could we turn this into a contributable mechanism? I imagine a generic "Attach to process" command that collects available targets from the installed debug extensions?

**Comment by isidorn** [comment]
Great feedback. Some random thoughts: 
* I think we should first check with out popular debuggers Python, C#, C++ if they can all support this. I think they can, if they do if we can think of moving this to the vscode side and a capability. We shuold also check if all these debuggers contribute these command and try to reduce duplication
* I like your idea of having a general command that collects available targets. So we would show in the quick pick seperated by a sepeartor a list of collected processes, based on the proces selected the call would be passed to the appropraite debugger extension

@weinand would know more since he implented the current Attach to process command

**Comment by isidorn** [comment]
I believe the javascript terminal somehow tackles this.
Thus assigning this to @connor4312 to decide if we should close as duplicate or if we could enhance the current funcitonality to also have this
