### ISSUE TITLE
Task errors don't show up after running a successful task

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#76138]
Testing #74824

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/35271042/60132494-76ee0900-9750-11e9-89bb-93752babf5e3.png">

Not sure if this is related to the test item, but I had `"fileLocation": ["autoDetect", "Parent"]` and ran the task, got the errors, then went back to change `fileLocation` and forgot to remove the brackets and had `"fileLocation": ["autoDetect"]` but the task ran normally and didn't prompt any errors. Upon reloading the editor I found the errors in my `tasks.json`.

Repro steps:
1. Set `"fileLocation": ["autoDetect", "ParentFolder"]`
2. Run tasks
3. Change `fileLocation` to `["autoDetect"]`
4. :bug: Tasks still runs while file is invalid

**Comment by alexr00** [comment]
It is intentional that the task still runs, since it is only the problem matcher that is incorrect. The problem does still show up in the output window, but there is no notification. We only show the notification when the error was triggered from the Run Task command. In this case, the error was triggered by the tasks.json file change. It might make sense to show the notification in this case too.

**Comment by misolori** [comment]
Yea, at the minimum I would expect the same notification to appear.
