### ISSUE TITLE
Edit files in SSHFS

### ISSUE THREAD

**Issue by Slamoth** [microsoft/vscode#76171]
Issue Type: <b>Performance Issue</b>

When working on a file in a drive connected with sshfs, if sshfs is closed before the script is closed in the VSCODE editor, it just hangs !

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:29:22.216Z)
OS version: Darwin x64 18.6.0

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
