### ISSUE TITLE
Can't connect to a debug adapter server when the extension isn't installed in ~/.vscode

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#7625]
- VSCode Version: 1.3.0-insider
- OS Version: Win 10

I have a debug adapter running in server mode, and an app that is set up to connect with "debugServer" in launch.json. If there isn't an extension that's actually installed, the app will fail to start, with "Configured debug type 'chrome' is not supported". I've been working around that but it's annoying for development. Seems like vscode should skip that check if "debugServer" is set. This isn't a new issue, I think it's always been this way.

**Comment by weinand** [comment]
@roblourens your proposal for allowing to run a debug session for a non-existing debug type would be problematic because you are missing out all the other contributions of the extension.
In addition it would be an effort (hack) for us to implement that.

Please consider these (existing) solutions:

1. Open the debug extension in VS Code and then run the extension with Control-F5. This will launch (not debug) another VS Code windows that 'knows' the debug type (and has all the associated contributions for that type) and you can then start your debug session against a debug server safely from there.

2. If you don't like the additional step to launch the debug extension, you can side install your debug extension in your ~/.vscode/extensions folder. This does not have to be the final extension. Just a folder with a package.json that contributes the new type is enough.

/cc @isidorn

**Comment by roblourens** [comment]
I didn't know about that first option, that's a great workaround. Thanks for the tip.

**Comment by weinand** [comment]
@roblourens actually, the first option is not a workaround, but the official way to run (or debug) any VS Code extension ;-) 
I hope it is OK if I close this issue?
