### ISSUE TITLE
终端出现问题了，初始不显示当前的地址路径，输入后才会显示

### ISSUE THREAD

**Issue by Ethan810** [microsoft/vscode#76273]
终端出现问题了，初始不显示当前的地址路径，输入后才会显示

**Comment by byyxx128** [comment]
1. English please.
2. Are you using  Windows 10 1809? It is of known bug in 1809 and has been fixed in 1903. Please update your operating system.
Maybe duplicate https://github.com/microsoft/vscode/issues/57803

**Comment by byyxx128** [comment]
1. English please.
2. Are you using  Windows 10 1809? It is a known bug in 1809 and has been fixed in 1903. Please update your operating system.

💢Maybe duplicate https://github.com/microsoft/vscode/issues/57803
***
（顺便说一句，下一次建议通过菜单栏的“帮助”下面的“![image](https://user-images.githubusercontent.com/20079289/60314810-fdae0c00-9931-11e9-8033-d7d881a18d97.png)”来反馈问题，这样便于收集你的信息。一定要讲英文，不然如果我不回复你，你的issue会直接关闭的……）

**Comment by Ethan810** [comment]
Sorry,I'll use English next time and see issue.
 yes,i am using  Windows 10 1809 now,i see, thanks。
