### ISSUE TITLE
Status bar: clicking shows blue default outline

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#76278]
Looks like a regression from adding `tabIndex:-1`

Steps:
* macOS
* click on a status bar entry
* 🐛 see the blue default outline appearing

I do not know why we do not see this in other places where we use `tabIndex:-1`. We probably need to update our rule in style.css to account for that:
* https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/media/style.css#L163
* https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/media/style.css#L176

Moving to June.

**Comment by isidorn** [comment]
@bpasero Thanks for the pointer. Fixed this with @alexr00 by updating the rules in `style.css` to also take into account `tabIndex = -1`. Seems to work just fine on my mac.

**Comment by bpasero** [comment]
@isidorn can you check all usages of `tabindex="0"` I think there are more.

**Comment by isidorn** [comment]
@bpasero There are only three more places
* https://github.com/Microsoft/vscode/blob/332aaba6ded659529a7ae91e6ae0071ff1ef6ae8/src/vs/workbench/browser/media/style.css#L191 this does not seem like it should be updated (since it is inside the tree)
* https://github.com/Microsoft/vscode/blob/332aaba6ded659529a7ae91e6ae0071ff1ef6ae8/src/vs/workbench/browser/style.ts#L97
* https://github.com/Microsoft/vscode/blob/332aaba6ded659529a7ae91e6ae0071ff1ef6ae8/src/vs/workbench/browser/style.ts#L117

In these last two I think it makes sense to update

**Comment by isidorn** [comment]
I have updated the last two. I think we are good now.
