### ISSUE TITLE
Pinning folders and files in explorer hierarchy 

### ISSUE THREAD

**Issue by hLudde** [microsoft/vscode#76302]
I tried to look if there is a feature request that requests this feature, but couldn't find one, please tell me if there already is 😅

I wonder if it is possible to pin folders and files in the explorer hierarchy window in vcs because sometimes projects can become very big and have complex structures.

What i mean with this is to have a function that does something like this (not the best example, but it hopefully explains what i mean):

**(before)**
![before1](https://user-images.githubusercontent.com/8746009/60352437-21239600-99c8-11e9-9f6f-90dcf380fe9d.png)

**(after)**
![after](https://user-images.githubusercontent.com/8746009/60352944-3947e500-99c9-11e9-8c05-2944519d3129.png)
_made in paint <3_

**Comment by isidorn** [comment]
We do not support this. And we do not have it on the immedatie plan, thus adding to backlog.
Though I am not convinced we would ever do that.
Our "pinned" concept of editors is the Open Editors view

**Comment by aymanredox** [comment]
**Actually**, the open editors is **not enough** to provide the pinning for two reasons. I may need to pin a folder even though all files are closed. and I want the pinning to survive restarts. I want pinning because my project is big (not even huge) and I usually work on the services folder and the components folder only. So I want to easily find them the next time I open vs code.

**Comment by 1138-4EB** [comment]
@hLudde, @aymanredox, what about using multi-root workspaces? It is a kind of 'folder pinning'.

**Comment by eine** [comment]
I believe that #76904, which is now a candidate for Backlog, would provide a solution to this issue. Hence, I would like to ask users that reacted in this issue to react to #76904 too.
