### ISSUE TITLE
Syntax errors are not showing

### ISSUE THREAD

**Issue by Malintha** [microsoft/vscode#76321]
![Selection_004](https://user-images.githubusercontent.com/3253761/60376569-c2105200-99c4-11e9-8390-7dd9c4cdb6ec.png)
Issue Type: <b>Bug</b>

Type any code snippet with erros in it. Errors will not be shown.  

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 4.15.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 2959)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.59GB (9.39GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.0
python|ms-|2019.6.22090
cpptools|ms-|0.24.0-insiders3

</details>

![Selection_004](https://user-images.githubusercontent.com/3253761/60376565-b755bd00-99c4-11e9-9f4c-c8a96774ea65.png)

**Comment by roblourens** [comment]
It looks like this is an issue with the cpp extension. Please file this on the vscode-cpptools repo.

**Comment by Colengms** [comment]
Hi @Malintha .  Is it possible there is a squiggle at the top of the file?  The default value of "C_Cpp.errorSquiggles" is "EnabledIfIncludesResolve".  When in this mode and includes are not found, we squiggle only the #include statement.  That is to avoid displaying many squiggles, all due to headers that could not be found.  

Are there any other errors displayed?  If there is a problem with the configuration, squiggles would not appear, as system headers would not be found.

**Comment by Malintha** [comment]
@Colengms Much thanks for your help. I have actually added all the headers to the include path and I could navigate to all the headers by Ctrl clicking on them. I just noticed that some of the headers were underlined with the message some of the headers of include files couldn't be resolved. It started to highlight the errors soon after I commented those includes out. 
But this happened when even the C_Cpp.errorSquiggles = Enabled, which can be quite confusing sometimes.

**Comment by Colengms** [comment]
@Malintha Do you have intelliSenseEngineFallback enabled?  If so, try disabling it.  This setting kicks in if #includes do not resolve, and uses the Tag Parser instead of the default IntelliSense engine.  Most features of the C/C++ extension will work in a less accurate or limited manner when in Tag Parser mode, which may be preferable if the default IntelliSense engine is unable to process sources (due to missing includes).  In Tag Parser mode, error squiggles are limited to unresolved headers.  We recently changed the default of intelliSenseEngineFallback to disabled, as feedback suggested people would prefer to see squiggles even if headers did not resolve.
