### ISSUE TITLE
[Feature Request] Line Numbers in Centered Editor Layout

### ISSUE THREAD

**Issue by duranivan** [microsoft/vscode#76338]
Basically I would like to have the line numbers and gutter moved to the far left (just next to the side bar), when the editor layout is centered, leaving only the text body being centered, just like in Sublime Text or in Jetbrain's editors free distraction mode.

At the moment the whole gutter and therefore line numbers are centered along with the text body.

**Comment by isidorn** [comment]
This is a fair feature request, however we do not have it on the plan for the future, thus assigning to backlog.
The issue here is that the line numbers are part of the editor (from the implementation standpoint) and are always tied to the editor. And this would not be easy to change due to our component structure.
