### ISSUE TITLE
Inline icons are rendered differently to titlebar icons

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#76412]
See the icon above the tooltip - I was expecting it to be the same as the one in the titlebar.

![image](https://user-images.githubusercontent.com/376658/60446687-cb462c80-9c19-11e9-941a-74c7baadac59.png)

**Comment by misolori** [comment]
This is from the [Todo Tree extension](https://github.com/Gruntfuggly/todo-tree) and not VS Code, please file an issue with that extension.

**Comment by Gruntfuggly** [comment]
I know it's from the Todo Tree extension as it's my extension - I've added the icon in both places and it is rendered differently!

**Comment by Gruntfuggly** [comment]
It seems that the width and height of the SVG is not being restricted when used in the inline icon, where it is for the titlebar icons.

**Comment by misolori** [comment]
@Gruntfuggly sorry, didn't realize you were talking about our extension api (great extension btw). You are correct in that we don't restrict the size of icons in the the titlebar, however we recommend you make your icons 16x16 as those are the standard sizes we use everywhere else.

**Comment by Gruntfuggly** [comment]
That's the odd thing though - the same icon in the titlebar is fine. It's only when I use the same icon "inline" that it doesn't resize it.

**Comment by misolori** [comment]
Ah, I see the problem. We apply a `background-size: 16px` on title bar actions so it gets resized appropriately. But we don't do this on inline icons, which is why it's oversized. Tested this with a large inline icon and can confirm:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/35271042/60528326-10656f80-9ca9-11e9-89ac-1388996b37ce.png">

I'll make a fix for this, FYI @sandy081
