### ISSUE TITLE
Mouse wheel is expected to scroll dropdown items on some operating systems

### ISSUE THREAD

**Issue by petarvukmirovic** [microsoft/vscode#76414]
I use several terminals in VSCode and quite often I miss the feature that I can scroll on the dropdown menu to switch the terminals.

**Comment by Tyriar** [comment]
Is this some OS feature? What OS?

**Comment by petarvukmirovic** [comment]
This is something that is available on some apps on elementaryOS.

I use multiple terminals all the time, so I would find it useful.

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
