### ISSUE TITLE
Cmd + number should focus editor at index and not focus groups or split

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7647]
1. Have multiple tabs open
2. Press cmd + 2 - expect that the second tab gets focus (like in all other aps)
3. Instead a new editor group gets created

While in tab mode cmd + number should always focus that tab. Opening a new group should have a stronger shorctur (more keybindings).

I think this could be solved by just adding additional shortcuts in keybindings.json on appropriate positions because Alex gives priority based on where in file it appears.

**Comment by rebornix** [comment]
+1

We are using ctrl+tab to switch tabs, then people will use ctrl+N by default, just like what they have in Chrome.

**Comment by bpasero** [comment]
Depends on https://github.com/Microsoft/vscode/issues/2211 actually which might end up being tricky because it involves creating dynamic keybindings.

**Comment by isidorn** [comment]
Can't you have a 'tabMode' and add a keybinding, something in the manner:

{ "key": "cmd+1",           "command": "workbench.action.focusTab",
                                     "when": "inTabMode" },

**Comment by bpasero** [comment]
@isidorn I think as a user you would not want to specify all the keybindings but just have them available dynamically based on the opened tabs.

@alexandrudima fyi maybe you have an idea if this is possible with our keybinding story somehow?

**Comment by isidorn** [comment]
@bpasero I thought that by default they are all in `keybindings.json` and the user does not have to specify anything additionaly.

**Comment by bpasero** [comment]
@isidorn :). so how many do we put in? 100? or do people open more than 100 tabs?

**Comment by bpasero** [comment]
Sublime seems to stop at 10, so we could maybe do the same:

![screen shot 2016-06-14 at 12 58 05](https://cloud.githubusercontent.com/assets/900690/16040416/ad2a2820-322f-11e6-95dc-c077afe077dd.png)

**Comment by isidorn** [comment]
Daaaa :) 
We should do the same as chrome from 1 to 9. With that cmd + 9 focuses last and not the ninth one

**Comment by sandy081** [comment]
IMO if we are changing Cmd + number short cut to focus tabs, then we should not use the same to split group when in non tab modes.

Also under the Go To submenu the switch groups sub section is still showing the same keyboard actions in tabs/ non-tabs mode

**Comment by isidorn** [comment]
Makes sense  - users who are passionare about cmd + 2 opening to the side can always bind a custom keybinding to it

**Comment by sandy081** [comment]
Also my 2 cents here that, IMO cmd + 1, cmd + 2, cmd + 3 are very familiar default keyboard short cuts for splitting and switching among groups. If majority of users (if it is true :)) are used to these actions I do not know if it will be really helpful to change them

**Comment by bpasero** [comment]
I have pushed a change to restore Cmd+1/2/3 functionality and instead add Cmd+Shift+[1-9] to navigate to the index independent of if tabs are enabled or not. 

We still have to decide about the default. However I already got a very surprising @Tyriar when he had tabs disabled and Cmd+1/2/3 was not doing what it used to do.

**Comment by Tyriar** [comment]
Yes I've become used to using <kbd>ctrl</kbd>+num to split as well as focus, instead of remembering a new keybinding.

<kbd>ctrl</kbd>+`num` makes more sense to focus tab number `num` when <kbd>ctrl</kbd>+<kbd>tab</kbd> is not a most recently used list, like in browsers. When it is a MRU list, if <kbd>ctrl</kbd>+`num` opens tab at `num` there are 2 different models for navigating your tabs; most recently used and the order in which they were created. Not sure about other people but trying to use both at the same time would be disorienting for me and slow me down.

**Comment by bpasero** [comment]
@Tyriar well I am not sure we can make people happy without having support for `Ctrl+<Number>` support to open a tab at index. You are quite right that there are different ways of navigating tabs. The complete list is:
* `Ctrl+Tab`: navigate in MRU order
* `Ctrl+PageUp/Down`: navigate in spatial order across all tabs in all groups
* `Ctrl+<Number>`: navigate in spatial order to tab in index in one group

A user is now free to change the keybindings to map `Ctrl+<Number>` back to navigating the index. We did not have these commands before.

Still, with tabs disabled, `Ctrl+<Number>` for focussing tabs in one group does not make so much sense to me because you do not see tabs. On the other hand, if you have "Opened Editors" view visible, one could argue that it is useful to be able to open a specific editor from that list with one keybinding.

**Comment by bpasero** [comment]
We decided to:
* Assign `Alt+[1-9]` on Windows and Linux
* Assign `Ctrl+[1-9]` on Mac

to not break too many users that expect our current behaviour.
