### ISSUE TITLE
Outline view doesn't remember sizing between restarts

### ISSUE THREAD

**Issue by davidhopkins** [microsoft/vscode#76494]
Steps to Reproduce:

1. Enable [centered layout mode](https://code.visualstudio.com/updates/v1_21#_centered-editor-layout)
2. Resize outline menu
3. Restart and outline menu will be near top of the page

Thanks

VSCode-Go: 0.11.0
Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:27:31.086Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-47-generic

**Comment by jeanp413** [comment]
This is caused by [centerEditorLayout function](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/workbench.ts#L417) which internally calls `layout` which calls [saveViewSizes](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/browser/parts/views/viewsViewlet.ts#L276-L283) from viewsViewlet.ts that saves the size of the outline view which occupies the whole `explorer-viewlet` space because the `explorer-folders-view` is still not created.
Created a PR to make `centerEditorLayout` not call layout, not sure if this is the right fix but it seems to not break anything.
