### ISSUE TITLE
vscode Version 0.10.2 (0.10.2) - no Intellisense in Razor files?

### ISSUE THREAD

**Issue by neilyoung** [Microsoft/vscode#765]
I can't get intellisense support in Razor files. On purpose?

To be more specific: JS intellisense is there. Missing support for @ tags

**Comment by egamma** [comment]
Not fully supported yet, sorry.

**Comment by rhires** [comment]
I got a similar response [here](https://github.com/Microsoft/vscode/issues/386)...It's frustrating because Razor is a distinguishing feature of Microsoft's MVC platform, and yet neglected on this product and I'm not totally sure why. I also know that it's not quite deprecated, but won't be grown/enhanced going forward, partly because of tag helpers, which I'm sure I will like once I get more comfortable with them...and if they get intellisense, too. :-\

**Comment by egamma** [comment]
It is on the backlog and we will collaborate with the ASP.net team on this feature.

**Comment by ErikHells** [comment]
This could be another kind of issue but I have problems with intellisense in razor files as well.

I can't get suggestions with intellisense when I'm writing angular in a razor-file (cshtml). I've loaded the correct typings and everything works perfectly if I change the language mode to HTML instead of razor.

If language mode is set to Razor when writing the code below. Intellisense will not suggest "ng-controller". But if changed to HTML language it will. 
```
<div ng-controller="myController as vm">
```

**Comment by egamma** [comment]
CC @aeschli

**Comment by rasmus91** [comment]
This might seem a bit pushy, but is there anywhere i can keep an eye on the progress of this?  (Can't seem to find anything newer than this)

It's a feature i really miss, as i'm starting to thoroughly enjoy VSCode on Ubuntu with .NET Core and so on. (Also useful whilst learning Mvc)

**Comment by NickCraver** [comment]
I'd also be curious of the plans here - our designers would love to use VS Code for quick editing on Razor files.

**Comment by winuxue** [comment]
+1

**Comment by willl** [comment]
From what I hear, it's not easy and will be a lot of work to implement. 

I know that @david-driscoll has been playing around with implementing a razor host as part of omnisharp-roslyn. There's still a long long way to go though.

See his comments here: https://github.com/OmniSharp/omnisharp-vscode/issues/168#issuecomment-247905206

> I have a branch that was the bare minimum to wire in the "basic" Razor runtime. It's available https://github.com/OmniSharp/omnisharp-roslyn/tree/razorhost.

> When I say bare minimum, basically I was able to get diagnostics returned from the Razor host, and there were a lot of them because we I hadn't wired in any of the references (including things like mscorelib, lol).

**Comment by uxsoft** [comment]
What is the status of this?:)

**Comment by jtheisen** [comment]
@uxsoft I bet it's you better don't bet on doing Razor in the world of VS Code...

**Comment by NickCraver** [comment]
Razor is being split out from MVC now, known as "Razor Pages". I have no idea how this will impact getting support into VS Code as far as timelines, but it certainly makes it much more *possible* to do it.

**Comment by fschwiet** [comment]
Linking to omnisharp-vscode's issue for this as reference: https://github.com/OmniSharp/omnisharp-vscode/issues/168

**Comment by neilyoung** [comment]
One and a half year later I almost forgot to have dealt with Razor at some point in time...
