### ISSUE TITLE
UI support for TimeTravel Debugging

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#7652]
https://github.com/Microsoft/vscode-node-debug/issues/72

**Comment by isidorn** [comment]
@roblourens I like how you implemented this in the prototpye. Would you like to create a PR with your changes + plus a small adition that you only instantitate that aciton if [stepBack](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L567) is supported 

And the label needs to be nls.localized

**Comment by roblourens** [comment]
Sure, I can do that

**Comment by weinand** [comment]
@roblourens I've added the 'step back' request and the capability to the debug protocol. It is already available in the latest VS Code. 
The mock-debug extension (available on the marketplace) implements step back and can be used to verify the UI.

**Comment by roblourens** [comment]
> plus a small adition that you only instantitate that aciton if stepBack is supported
@isidorn you're talking about DebugActionsWidget.getActions? I could instantiate it the first time a session starts that supports stepBack, and on subsequent calls, either include it or not in the array that's returned? Or, it is possible to just hide a debug action with a css class if it's not supported?

**Comment by isidorn** [comment]
The actions get instantiated every time the widget gets created, so just instantiate it or not every time based on the capability.
No need to hide imho

**Comment by roblourens** [comment]
If I understand correctly, it looks like the widget is created once for the lifetime of the Code instance, and the actions are created once and cached and reused for every debug session.

**Comment by weinand** [comment]
@roblourens @isidorn works great, thanks!

@aruneshchandra the TimeTravel UI is available in the next VS Code Insider build.

**Comment by aruneshchandra** [comment]
@weinand @isidorn @roblourens Thanx for a quick turnaround on this feature request!

**Comment by isidorn** [comment]
@aruneshchandra welcome. Is the chakra debug adapter extension published - I could not find it? Is there some way we can try this out - since we woudl ike to add it to our test plan.

**Comment by aruneshchandra** [comment]
@agarwal-sandeep can tell you more about this.

cc:@curtisman

**Comment by agarwal-sandeep** [comment]
@isidorn Node-ChakraCore is supposed to work with vscode-node-debug adapter as Node-ChakraCore will support the debugging protocol without extensibility. 

@roblourens had added a 'back' stepaction to 'continue' command in the vscode-node-debug adapter prototype. https://github.com/roblourens/vscode-node-debug/commit/fdc0ea24d08b5e0213642d048791ce2fd920216d that change needs to be in adapter if UI says stepback.

**Comment by aruneshchandra** [comment]
@agarwal-sandeep are you saying that the current VSCode implementation for stepBack functionality is not complete ?

**Comment by agarwal-sandeep** [comment]
node.exe (Chakracore) needs to know that step back is requested and it is not in debugging protocol so adapter needs to send a different action in continue command and I don't see it in https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/nodeDebug.ts

@roblourens @weinand how will adapter notify the process?

**Comment by weinand** [comment]
@agarwal-sandeep we have implemented the UI as requested in https://github.com/Microsoft/vscode-node-debug/issues/72. Currently the UI can be controlled by a capability returned from the debug adapter. Our assumption was that Chakra would have its own debug adapter and that would enable the capability and implement a 'step back' request. https://github.com/Microsoft/vscode-node-debug/issues/72 did not mention that we have to implement the 'step back' request.

Please create another feature request for vscode-node-debug so that we can enable the capability and implement the 'step back'. For the latter we need to know what the value for the `stepaction`of the `continue` request is.

I see one problem with this feature request: the debug-adapter has to return the 'step-back' capability from the 'initialise' request. But there we do not know whether the used node version supports 'step back' or not. This information is only available when the runtime is launched. But this is too late for returning the capabilities. We can address this sequence problem is the future, but for this release we have to find another way to determine early that chakra is used and supports 'step back'.

**Comment by agarwal-sandeep** [comment]
Thanks @Weinand, I have open issue https://github.com/Microsoft/vscode-node-debug/issues/77. 

For capability detection is it feasible to use some environment variable?

**Comment by weinand** [comment]
@agarwal-sandeep sure, node-debug could use an environment variable as an indicator that node.js is actually chakra.

Please suggest how the env var should be named.

Please note that this env var cannot be set in the launch config but must be set globally.
Let me know if this would work for you (until we've fixed the real issue).

**Comment by agarwal-sandeep** [comment]
@aruneshchandra @mrkmarron for their feedback. We can use NODE_DEBUG_SUPPORTS_STEPBACK=1

**Comment by aruneshchandra** [comment]
@agarwal-sandeep how is this supposed to get set ? Is the user is expected to set this ?

**Comment by weinand** [comment]
@agarwal-sandeep yes, the user would have to do this (which would be a pain). We are currently looking into how to fix this issue.

**Comment by weinand** [comment]
@agarwal-sandeep we are planning to enhance VS Code so that the `supportsStepBack` capability can be returned from the `launch` and `attach` requests.

**Comment by aruneshchandra** [comment]
@weinand yes that's much better than expecting users to set the env variable. Thanx!
