### ISSUE TITLE
Weired ctrl+z in "global search from the left panel".

### ISSUE THREAD

**Issue by vintzl** [microsoft/vscode#76588]
Say I have a file that have been lastly modified.

1. Then, I do a "global search from the left panel".
2. Inside this search panel. I tape or copy/paste some text, and hit ENTER.
3. Then I "edit" the searched terms by doing many Ctrl+z.

Now, why the cursor jump from the search field to the editor, and undo what have been typed in the file? (It does not do so when the file have no changes in the buffer…)

Again, I have noticed this from the beginning… And still annoying me with 1.36.0…

![Peek 2019-07-04 12-12](https://user-images.githubusercontent.com/44751088/60659821-a2f74180-9e56-11e9-9742-c211d34fdaef.gif)

**Comment by roblourens** [comment]
Which OS?

**Comment by vintzl** [comment]
Debian Stable amd64

**Comment by rebornix** [comment]
@roblourens after all redos in the search field, the next cmd+z will move the focus back to the editor area, any idea why that happens?

**Comment by roblourens** [comment]
It seems that the editor handles cmd+z even when it doesn't have focus, so I guess that if the native input box in search doesn't handle it, then the editor does.

**Comment by dorellang** [comment]
Can confirm this behavior on macOS High Sierra and VSCode 1.36.0

**Comment by alexandrudima** [comment]
That is the native `undo` behavior. It will "undo" the last possible edit by moving focus to the previous focused element. 

This reproduces in Chrome with the following page:
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
</head>
<body>
  <input type="text"></input>
  <input type="text"></input>
</body>
</html>
```

Here I type `qwe`, switch to another text input and type `rty`. Then I press Ctrl+Z twice:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/67587989-485f5980-f755-11e9-9ed8-5ef721df1a37.gif)

@vintzl VS Code is built on Electron, which is built on Chromium. The behaviour you are running into is implemented inside Chromium. If you feel that it should be changed, it needs to be changed in Chromium. Please create an issue against https://bugs.chromium.org/p/chromium/issues/list and post here the link. Personally, I would not file such an issue against Chromium because I believe the current behavior is reasonable and I don't have strong feelings against it.
