### ISSUE TITLE
New tree indent guides "onHover" does work

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#76672]
Under Ubuntu, the indent guides are either on or off. The onHover settings doesn't seem to work.

![image](https://user-images.githubusercontent.com/376658/60704839-7b0ee900-9efd-11e9-80dc-9c467db00566.png)

**Comment by gjsjohnmurray** [comment]
@Gruntfuggly it looks like your workspace root folder is libemcscms and Schedule.cpp is in that folder. I think the `hover` mode shows the line even when the mouse isn't over the tree because Schedule.cpp is selected. I suggest you try exploring a workspace root folder with several subfolders to see how `hover` mode gives you transient additional guidance as you explore. And notice how the transient guidelines are fainter than the one which persists even when you're not hovering over the tree.

**Comment by Gruntfuggly** [comment]
Yes, it looks like the guide showing the current focus is on always. That's not what I was expecting really. It seems pointless hiding the guides which are already fainter?

**Comment by joaomoreno** [comment]
> It seems pointless hiding the guides which are already fainter?

It just helps reducing noise. I'll close this for now. If more people file issues against it, we can add another mode for hover...
