### ISSUE TITLE
editor.trimAutoWhitespace doesn't re-indent on pressing Enter

### ISSUE THREAD

**Issue by AndrewRayCode** [Microsoft/vscode#7671]
- VSCode Version: 1.2.1
- OS Version: OSX

Steps to Reproduce:

![vscode-why](https://cloud.githubusercontent.com/assets/79215/16054262/334ecb36-3221-11e6-8aba-d61fb9d49650.gif)

When on an auto un-indented line, hitting enter should reset to the correct indent. Vim currently does this (although it might be a plugin I'm using?). I tested in Sublime too and was fairly surprised to find out Sublime doesn't correct the indent on hitting enter either.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

P.S. If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
