### ISSUE TITLE
Can't Exit by double-clicking top-left corner

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/vscode#76812]
Issue Type: <b>Bug</b>

- Double-click top-left corner of title bar
- VSC toggles between maximized and normal window size instead of exiting, like other Windows apps.

VS Code version: Code 1.36.0 (0f3794b38477eea13fb47fbe15a42798e6129338, 2019-07-03T13:25:46.372Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G620 @ 2.60GHz (2 x 2593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (13.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.13.0
python|ms-|2019.6.22090

</details>

**Comment by huntertur** [comment]
This also occurs on Linux when setting **Window: Title Bar Style** to `custom`, but works correctly when set to `native`.

**Comment by sbatten** [comment]
Use this setting to change this behavior: `window.doubleClickIconToClose`

**Comment by OlafvdSpek** [comment]
Requiring a setting for this is really annoying..

**Comment by sbatten** [comment]
@OlafvdSpek The icon provided by the custom title bar is not the same as the native one. This icon is an html element which requires us to get click events in order to handle the close action. We also expect to be able to drag the window from the icon as well and we can't do both because allowing this icon to be draggable means sending all events to the OS and thus we don't get the HTML events. We decided that more people expect drag to work than use the close action, but there is a setting if you are okay with the tradeoff.
