### ISSUE TITLE
Add custom highlight effects such as bold, italics, underline, color, instead of just a grey rectangle

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#7687]
Forked off as only remaining issue in https://github.com/Microsoft/vscode/issues/5620

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

P.S. If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
