### ISSUE TITLE
Change the icons back to the old style

### ISSUE THREAD

**Issue by zbot473** [microsoft/vscode#77004]
I don't really like the line style icons. Also, icons style isn't the same throughout. 
I circled the examples.
<img width="1024" alt="Screen Shot 2019-07-09 at 11 10 35 AM" src="https://user-images.githubusercontent.com/49821700/60909260-05778580-a23b-11e9-8d1d-9159519743e2.png">

**Comment by AssetKid** [comment]
The icons have been in the works for years now and they have been taking suggestions from the community all along. I don't think they will just jump ship and revert back to the old icons because you and a other few people don't like them. It doesn't work like that.

With that said, it might be **possible** to change them in the future.

See https://github.com/microsoft/vscode/issues/8017#issuecomment-452747614

**Comment by misolori** [comment]
We've been working on these new icons for the past few months (started late last year) and as @AssetKid has mentioned we've been iterating with the community in #8017. Once we release this update other extensions will also adopt the new style and then we will be continue to update our Octicons in the status bar (see #76909). 

If you'd like you can leave comments in #8017 or if you encounter bugs please file an issue. Otherwise I'll be closing this issue as we have other places to document the feedback. Thanks!

**Comment by zbot473** [comment]
@misolori So what you are saying is that the icons are basically just paths, and can be converted to the line style?

**Comment by misolori** [comment]
@zbot473 not sure I follow, what do you mean?

**Comment by zbot473** [comment]
How do you guarantee extension icons change? Is the icon an SVG or something?

**Comment by shanyujie** [comment]
<img width="52" alt="屏幕快照 2019-08-10 下午12 39 53" src="https://user-images.githubusercontent.com/22969676/62817619-23067a80-bb6c-11e9-86eb-5bce48795cee.png">
the icon is so ugly,please go back to the icon for the old version 1.36

**Comment by unixcow** [comment]
yeah icons feel so thin and they are harder to interpret than the previous more solid ones. it's a change that would've been better to be optional, i hope they add the ability to choose between new/old styled icons.

Again they aren't ugly just not everyone's cup of tea

**Comment by Pelerin88** [comment]
I feel it's bad idea to advice with community about such aspects as graphic design. Most people has a lack of taste even if they are great engineers. So icons should be developed by professional designer (even calligraphic designer). This one of the reasons I switched from Visual Studio - its horrible and unreadable UI with thin lines looking like a mess. So would also like to turn back to original icons, or atleast have some options, let's say, plugins pack.
