### ISSUE TITLE
Restored Windows after relaunch are not fitting display

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#77010]
Issue Type: <b>Bug</b>

Multi-display setup, all bottom-aligned.
display 1, left, built-in laptop
display 2, middle, 27"
display 3, right, 27"

Since forever I have the issue that windows on display 2 and 3 are getting restored in display 1 when I restart VS Code Insiders. This does not happen on Stable... When restoring, the window size was adapted to fit the window on display 1.

Now, windows are still restored on display 1 but only their height gets adapter to fit display 1. They retain the width they had on display 2 / 3. This is particularly unpleasant when switching from multi-display setup to laptop only.

VS Code version: Code - Insiders 1.37.0-insider (9296aaa2201b638e2b1dc71a9b9fe38c5ab2e904, 2019-07-09T05:24:16.868Z)
OS version: Darwin x64 18.6.0

This also happens when all extensions are disabled.

**Comment by bpasero** [comment]
> Since forever I have the issue that windows on display 2 and 3 are getting restored in display 1 when I restart VS Code Insiders. This does not happen on Stable...

I am not sure I understand that. Are you referring to our current stable or the previous one? Because both stable and insiders are now on Electron 4 and there have been issues around restoring window bounds (see https://github.com/microsoft/vscode/issues/74872).

> Now, windows are still restored on display 1 but only their height gets adapter to fit display 1. They retain the width they had on display 2 / 3. This is particularly unpleasant when switching from multi-display setup to laptop only.

This is probably a result of the OS trying to fit the window on display 1 when it has the bounds of the other displays that are probably larger and cannot fit. It would still be interesting why we fail to restore the window on the other monitors.

@kieferrm I am assigning you, since you could help out given you have this setup (and I don't). Throw some code around here: [`restoreWindowState`](https://github.com/Microsoft/vscode/blob/0197936b3ba39e9680d5db6d5f1ca483ed6add4e/src/vs/code/electron-main/window.ts#L679)

**Comment by bpasero** [comment]
I cannot reproduce. I just added a third monitor to my setup and opened Code (insiders) on each monitor with the full bounds of the display and then restarted. In all cases, the window size was restored to the size of the display.

In order to debug this further I would need the exact display resolution of each monitor and would probably also need to know what the primary monitor is (e.g. on which one do you see the dock).
