### ISSUE TITLE
"Save All" named files (ignore untitled files)

### ISSUE THREAD

**Issue by k3n** [microsoft/vscode#77023]
Request: Allow me to `Save All` files that are named, but ignore any untitled files (temp files/buffers).

Current behavior is that calling `Save All` prompts me to enter a name, location, etc. for the untitled files, and at the same time, steals focus from the currently active file. 

Workaround: Open a new instance of VSCode solely for temp files.

My typical workflow is to modify a set of files, and then `Save All` once I'm ready to proceed. As has been discussed in other issues re: `Save All`, it's much preferred for tooling's sake to batch-save so that your build process doesn't fire off once per modified file.

However, I often create temp files using `File: New Untitled File` so that I can take notes, etc.; these are fully ephemeral and I do not care to persist them (on the rare occasion that I do, I do so explicitly per file).

**Comment by brunolemos** [comment]
is this currently possible?

**Comment by usrlocl** [comment]
+1 Untitled files with hot exit is vscode way of providing scratch files. It defeats the purpose of scratch files if save dialog is frequently popped up.

**Comment by rafareino** [comment]
This issue should be considered once again.

It is a real need developers face, even so that it is alread addressed, in a different context, in vscode

<img width="217" alt="image" src="https://user-images.githubusercontent.com/1813322/166251446-8905e2ed-1c27-47fd-ad86-13ba8a5de275.png">

But instead of this very specific 'save for debug...', it should be moved and act as more global 'save all behaviour'.
This was a issue to those using debug and is a issue to those using solutions that integrate less brilliantly with debug.

**Comment by gthau** [comment]
This is so annoying that I had to create a small extension for it:
Marketplace: https://marketplace.visualstudio.com/items?itemName=gthau.vscode-enhanced-save-all
Code: https://github.com/gthau/vscode-enhanced-save-all

I just assign the keybinding of "Save All" to `vscode-enhanced-save-all.save-all-except-untitled` and problem fixed. Finally able to use scratchpads such as QuokkaJS without breaking my workflow.

Enjoy!

**Comment by std4453** [comment]
This issue now has 19 upvotes, I believe it should have crossed the criteria described [here](https://github.com/Microsoft/vscode/wiki/Issue-Grooming#out-of-scope-feature-requests)? Wish to see it reopened.
