### ISSUE TITLE
vscode fails to start offline after updateing windows to 1903

### ISSUE THREAD

**Issue by sam622** [microsoft/vscode#77167]
- VSCode Version: 2019
When I run code --version in cmd I get the error 
```
C:\Users\User> code --version

#
#Fatal error in , line 0
#Check failed: (i_isolate->snapshot_blob()) == nullptr. 
#
#
#
#FailureMessage Object: 000000D5A7CFF348
```
- OS Version: Windows 10 Pro 1903

Steps to Reproduce:

1.Open the vscode from start menu
When I open it from start, task bar or desktop no windows or error messages appear. This happens while offline and online

Does this issue occur when all extensions are disabled?: Yes the error message -
```
C:\Users\User> code --disable-extensions

#
#Fatal error in , line 0
#Check failed: (i_isolate->snapshot_blob()) == nullptr. 
#
#
#
#FailureMessage Object: 0000007C226FF4D8
```

**Comment by bpasero** [comment]
@sam622 weird, we had an issue like this before but it was resolved with our Electron 3 update as far as I remember.

Couple of ideas:
* does it reproduce with Electron itself ([download](https://github.com/electron/electron/releases/download/v4.2.5/electron-v4.2.5-win32-x64.zip))
* does it reproduce using our Exploration builds that come with Electron 6 ([download](https://az764295.vo.msecnd.net/exploration/360e4e4dfa989135f28edc0d6f7e42df33cddf87/VSCodeUserSetup-x64-1.37.0-exploration.exe)) (you need to run `code-exploration` instead of `code`)

Thanks

**Comment by sam622** [comment]
@bpasero thanks,
Exploration works and opens
I can't figure out how to run vscode with electron, I extracted the file from the downloaded .zip file and ran electron.exe and then electron starts.
![image](https://user-images.githubusercontent.com/52091960/61098750-a01dd180-a492-11e9-8867-eda67e6bdea3.png)
How do I run vscode with electron? 
And are there any disadvantages to using exploration instead of normal vscode?
Thanks

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by sam622** [comment]
@bpasero will try the insider builds, but how do I get an updated version of electron (that doesn't have his problem) for the stable release? I have searched online and couldn't find much.
Thanks
