### ISSUE TITLE
Freeze FF 67

### ISSUE THREAD

**Issue by tigo-di** [microsoft/vscode#77233]
When in use, freeze Firefox 67.0.4 (64-bit), cursor dont work. 

Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-54-generic

System Info

|Item|Value|

|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 3000)|
|GPU Status|
2d_canvas: enabled
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
multiple_raster_threads: enabled_on
native_gpu_memory_buffers: disabled_software
oop_rasterization: disabled_off
protected_video_decode: unavailable_off
rasterization: disabled_software
skia_deferred_display_list: disabled_off
skia_renderer: disabled_off
surface_synchronization: enabled_on
video_decode: unavailable_off
viz_display_compositor: disabled_off
webgl: enabled
webgl2: enabled|
|Load (avg)|7, 4, 3|
|Memory (System)|7.66GB (1.86GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

Extensions 
duplicate|gee|1.0.1
livereload|zii|0.2.5

**Comment by bpasero** [comment]
To be clear: you use VSCode and then FireFox becomes unusable? Maybe report that to them?

**Comment by tigo-di** [comment]
Exactly, the FF runs without problem until I open the VS code.

I'm going to report to Mozilla, but I think this started after an update of vs

**Comment by bpasero** [comment]
Yeah please do, I do not think we can do anything about it.

**Comment by zicklag** [comment]
I can't figure out whether or not it is VSCode or Firefox causing the issue, but I have the same issue with Firefox 65.0.1 and VSCodium 1.36.1. The problem *doesn't* happen with VSCode 1.32.3 from the official PPA. I'm on Ubuntu 16.04 64bit. I don't know whether or not the problem is VSCode or Firefox, so I'm fine if you can't do anything about this issue, but I wanted to put my experience here just in case it helps @tigo-di or anybody else figure out what is wrong.

For me, Firefox will only have problems if you start VSCode *after* you start Firefox. If you start VSCode and then you start Firefox, Firefox will work just fine. When Firefox freezes it will also use up 100% of the CPU on all cores on my machine and whenever you try to go to a tab it will just show the loading spinner.

The problem is not unique to VSCode, though because it also happens with a couple other Chromium/Electron based applications including Chromium 72.0.3626.121, [Mojibar](https://github.com/muan/mojibar/) and [ReLaXed](https://github.com/RelaxedJS/ReLaXed).

I have absolutely no idea how Chromium could cause Firefox to go crazy like that, I can't think of any reason it would be doing that.

**Comment by tigo-di** [comment]
Exactly @zicklag! I need open VSCode or VSCodium before FF.

Any new instance/window of VS open after will freeze FF.

Thank your attention.
