### ISSUE TITLE
Custom language file association doesn't work in GIT tab

### ISSUE THREAD

**Issue by Huachao** [Microsoft/vscode#7729]
- VSCode Version: 1.2.1
- OS Version: Windows 10 Enterprise x64

Steps to Reproduce:
1. Add a custom file association in settings.json like 

``` json
      "files.associations": {
            ".tmLanguage": "xml"
       }
```
1. It worked quite well in Explorer tab. However, in GIT tab, the language is still recognized as Plain Text. BTW I also have restarted the VS Code

**Comment by joaomoreno** [comment]
Uh. @bpasero any ideas? Should the git contribution just reach out to the files contribution?

**Comment by bpasero** [comment]
@joaomoreno that would be totally fine because you already depend on the file world. You could just let your IGitConfiguration interface for your settings (if you have such) extend from the files one in https://github.com/Microsoft/vscode/blob/master/src/vs/platform/files/common/files.ts#L433 which is API.

**Comment by joaomoreno** [comment]
Fixed.
