### ISSUE TITLE
getRecentlyOpened throws exception

### ISSUE THREAD

**Issue by embee8** [microsoft/vscode#77327]
After updating VS Code to the latest version it doesn't start anymore. Starting it from the command line in verbose mode shows this:

![VS Code issue](https://user-images.githubusercontent.com/12213984/61172093-d6814c80-a577-11e9-8eb8-84bd3d6e6372.png)

My theory is that I had a temporary file opened (through FileZilla) and after it became unavailable, VS Code crashed and refused to launch.

- VSCode Version: VS Code 1.36.1
- OS Version: Windows 10

Steps to Reproduce (not 100% confident that this led to the issue):

1. Open file
2. Close VS Code
3. Update VS Code
4. Delete file
5. Open VS Code

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
This was caused by changes to our URI library in 1.36 that were reverted in 1.36.1.
Maybe your recent entries were written with the problematic implementation.

For 1.37, I've added code to catch issues when restoring the recent entries.
Until then, the workaround is to delete the storage.json file:
`%appdata%\Code\storage.json`

**Comment by embee8** [comment]
Thanks @aeschli! 🚀
