### ISSUE TITLE
Auto Indent Support not working for select in Go

### ISSUE THREAD

**Issue by WhisperGoldstein** [microsoft/vscode#77379]
Auto indent moves case statements to the same level as the select when saving. Example: 

	select {
	case receivedMsg := <-msgCh:
		fmt.Println(receivedMsg)
	case receivedError := <-errCh:
		fmt.Println(receivedError)
	default:
		fmt.Println("no messages received")
	}

Running VSCode v 1.36.1

The language-configuration.json file for go shows:

...
`"indentationRules": {
		"increaseIndentPattern": "^.*(\\bcase\\b.*:|\\bdefault\\b:|(\\b(func|if|else|switch|select|for|struct)\\b.*)?{[^}\"'`]*|\\([^)\"'`]*)$",
		"decreaseIndentPattern": "^\\s*(\\bcase\\b.*:|\\bdefault\\b:|}[)}]*[),]?|\\)[,]?)$"
	},`
...

**Comment by ramya-rao-a** [comment]
Since the indentation rules for Go are in VS Code, moved this issue from vscode-go to vscode.

https://github.com/microsoft/vscode/blob/master/extensions/go/language-configuration.json

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules and only support limited code styles), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, if the indentation rules are leading to more trouble than having no auto indent, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment or use auto formatting (`editor.formatOnType`, `editor.formatOnPaste`). As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like (https://github.com/microsoft/vscode/issues/19847, https://github.com/microsoft/vscode/issues/34621 or https://github.com/microsoft/vscode/issues/66235).
