### ISSUE TITLE
[Settings GUI] String array: No help in filling enum values

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#77458]
#77427

```json
"type": "array",
"items": {
	"type": "string",
	"enum": [
		"error",
		"warning",
		"info",
		"hint"
	]
},
```

`settings.json`:

![Screenshot (29)](https://user-images.githubusercontent.com/9638156/61283443-d1194180-a7c5-11e9-8ddb-5994a4a19c0c.png)

`settings GUI`:

![Screenshot (30)](https://user-images.githubusercontent.com/9638156/61283450-d4acc880-a7c5-11e9-8389-8b8eaf4531dc.png)

**Comment by eamodio** [comment]
I think this is FAR worse than just not providing help when using enums, because as far as I can tell it doesn't even validate values against the allowed enum values. Which is basically inviting users to enter invalid/bad data which can cause extensions to not function properly.

While this was always possible before, the user would not only get intellisense on the allowed values you'd also get error warning about invalid values.

Can this be something that is prioritized for at least the next iteration (though IMO this should warrant a patch release when fixed)?

/cc @roblourens @kieferrm

**Comment by usernamehw** [comment]
Validation issue was closed `as-designed`: #77456

**Comment by roblourens** [comment]
@octref and I talked about this, I thought there was an open issue for validation somewhere.

**Comment by KamasamaK** [comment]
Additional validation wouldn't be as necessary if it just worked like standalone enums do with a drop-down instead of a text input.

**Comment by roblourens** [comment]
Validation is still necessary because you can type whatever you want or the validation criteria can change.

**Comment by octref** [comment]
Errors are added as part of #77459 (besides `enum`, `pattern`, `minItems`, `maxItems` are also supported).

![image](https://user-images.githubusercontent.com/4033249/63552651-0e6f9e00-c4ed-11e9-8232-693317af9320.png)

So I'm putting this one into backlog.

**Comment by rzhao271** [comment]
Just noting down some findings so far.

There are settings that are lists of enums, such as `git.checkoutType`, or `jupyter.widgetScriptSources`. `git.checkoutType` doesn't allow for duplicate elements (`"uniqueItems": true`), and the order of the elements matters. For example, if "remote" comes before "local" in the array, and a user runs the "Checkout to..." command, then the remote URLs show up first.
Therefore, one way to display a list of enum values would be as a list of dropdowns.

There are also settings of type `object`, where the keys and/or values are enums. These cases are actually rendered properly by the settings editor (https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/preferences/browser/settingsWidgets.ts#L908). Yet, the settings editor is still unable to currently render objects with primitive non-string values (i.e. booleans/numbers/integers) right now.

**Comment by rzhao271** [comment]
I was looking more into the ListWidget, and got confused by when `item.sibling` would be non-null in the following case: https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/preferences/browser/settingsWidgets.ts#L529

I noticed that the exclude widget set `sibling` here https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/preferences/browser/settingsTree.ts#L75, but I thought that even that code path wasn't being used, because the exclude widget didn't have the option to add a when clause. It turns out that one has to set the when clause in the json file first, and _then_ they can view and edit it in the settings editor.

**Comment by rzhao271** [comment]
\closedWith ff39a97

An enhancement would be adding a mechanism to help rearrange items of the array while in view mode.
