### ISSUE TITLE
single-line block comments incorrectly indented

### ISSUE THREAD

**Issue by JonathanMEdwards** [microsoft/vscode#77474]
Issue Type: <b>Bug</b>

create ts/js file:
```
class foo {
  /* */
}
```
place cursor to right of */
hit return
you get:
```
class foo {
/* */
  
}
```

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.20GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by joaomoreno** [comment]
I can't repro this, @JonathanMEdwards can you still see this?

**Comment by JonathanMEdwards** [comment]
Yes, still happens, exactly as described. 

CPUs	Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)
GPU Status	2d_canvas: enabled
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
metal: disabled_off
multiple_raster_threads: enabled_on
oop_rasterization: disabled_off
protected_video_decode: unavailable_off
rasterization: enabled
skia_renderer: disabled_off_ok
video_decode: enabled
viz_display_compositor: enabled_on
viz_hit_test_surface_layer: disabled_off_ok
webgl: enabled
webgl2: enabled
Load (avg)	3, 2, 2
Memory (System)	16.00GB (1.04GB free)
Process Argv	-psn_0_11037318
Screen Reader	no
VM	0%


Extension | Author (truncated) | Version
-- | -- | --
npm-intellisense | chr | 1.3.0
gitignore | cod | 0.6.0
vscode-npm-script | eg2 | 0.3.11
latex-workshop | Jam | 8.8.0
theme-dark-plus-contrast | k3a | 0.1.101
debugger-for-chrome | msj | 4.12.6
deepdark-material | Nim | 3.2.1
vscode-jest | Ort | 3.1.1
vscodeintellicode | Vis | 1.2.6
markdown-all-in-one | yzh | 2.7.0

**Comment by rebornix** [comment]
This is due to the limited architecture (regex based indentation rules and only support limited code styles), we may want to consider using formatters if they exist for indenation adjustment (if interested, we can discuss in https://github.com/microsoft/vscode/issues/19847).

For this particular issue, you can set `editor.autoIndent` to `advanced` to disable the regex based indentation adjustment or use auto formatting (`editor.formatOnType`, `editor.formatOnPaste`). As we don't have an easy good-enough fix for it, we close it for now and explore better solutions through issues like (https://github.com/microsoft/vscode/issues/19847, https://github.com/microsoft/vscode/issues/34621 or https://github.com/microsoft/vscode/issues/66235).

**Comment by mjbvz** [comment]
Closing this in favor of the other issues mentioned as I don't think it's possible to fix this without some new APIs
