### ISSUE TITLE
Resource icons are poorly optimized

### ISSUE THREAD

**Issue by ericlaw1979** [microsoft/vscode#77519]
- VSCode Version: (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open %USERPROFILE%\AppData\Local\Programs\Microsoft VS Code\resources\app\resources\win32

OBSERVE: 29 giant icon files of ~150KB in length each.

Run [PNGDistill ](https://t.co/nc74ugmhgF?amp=1) on each file.

OBSERVE: The PNG Resource in each file is poorly compressed, wasting ~20% of the bytes. In total, 60K is wasted.

The image icons should be optimized before inclusion.

**Comment by misolori** [comment]
We actually use [ImageMagick](https://imagemagick.org/) to do our converting, which already compresses the images. I couldn't get PNGDistill to work, but I attempted to compress the pngs further (using [ImageOptim](https://imageoptim.com)) before using ImageMagick and actually saw an increase. Also attempted to tweak the ImageMagick settings but didn't see any improvements. Thanks for the suggestion.

**Comment by ericlaw1979** [comment]
On one hand, I'm happy that someone took a look. On the other hand, it's absolutely possible to optimize these images further using ZopfliPNG or any of the other tools that use better deflate implementations, so I'm not sure why this was closed so quickly.

**Comment by misolori** [comment]
Well, I spent a couple of hours trying various options trying to get the most compression I can and didn't see anything fruitful come out of it. I also did try getting PNGDistill to work with no luck. 

And just now I spent sometime setting up [Zopfli to optimize our pngs](https://ariya.io/2016/06/using-zopfli-to-optimize-png-images) and got the same output as before, so that didn't make much of a difference.

We always try to compress our assets before hand ([and even had prs for this](https://github.com/microsoft/vscode/pull/62739)). If you see other ways that we can optimize other assets feel free to create a PR.
