### ISSUE TITLE
Integrated Terminal stopped working, opens externally

### ISSUE THREAD

**Issue by lvcz** [microsoft/vscode#77522]
/bug

Since Yesterday i try to Open Terminal in VSCode and it open Externally, using ctrl+j or ctrl+'. My settings are set to open integrated,

**Comment by efroim102** [comment]
This just started happening for me to, when opening the first terminal in a new instance, if opens a cmd line process as an external process instead of inline, with the integrated terminal having a blank cursor.

When closing the external process, I get the error `The terminal process terminated with exit code: 3221225786`.

When setting `wsl` as the default shell, it opens an external cmd line process with the error `Unsupported console settings. In order to use this feature, the legacy console must be disabled.`.

I'm on VSCode version 1.36.1

P.S. I actually have another instance of VSCode open from a couple of days ago that has 2 integrated terminals open that work fine, but when attempting to add a new terminal tab the same as above happens.

**Comment by efroim102** [comment]
I just noticed that Windows Terminal crashes right after launch, not sure if this is related.

**Comment by efroim102** [comment]
@lvcz I was just able to resolve this based on the error mentioned above (`Unsupported console settings. In order to use this feature, the legacy console must be disabled.`).

By right clicking on a cmd prompt instance, going to properties -> options and disabling the option `Use legacy console`.

Now everything works as expected, even Windows Terminal!

Note you will need to restart and open terminal instances.

If this resolves the issue for you too, consider closing it as I'm sure the team has plenty on their hands...

**Comment by lvcz** [comment]
as @efroim102  gave more details about my problem, basically the same here, but the terminal worked fine but externally.
This was basically turno off the legacy mode in powershell or cmd , and everything workd fine.

@efroim102  thanks for the help.

**Comment by lvcz** [comment]
I thinks this is an external change, does not affect the VScode scope.
