### ISSUE TITLE
Some suggestions missing in css, less, sass

### ISSUE THREAD

**Issue by linedotwww** [Microsoft/vscode#7754]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. when filling out the css rules, after adding a semicolon displays a popup that prevents the new line using the ENTER key

![- -1](https://cloud.githubusercontent.com/assets/15665678/16107730/f43b5a54-33a6-11e6-8dbc-f454173ddb8c.png)

**Comment by harriha** [comment]
The issue title might be a misaligned with the actual issue here, but confirming the actual problem. It appeared a couple of daily builds ago this week, and is quite annoying. Based on a quick experimentation, if the value before semicolon is not a number, then this problem appears. In other words, `margin: 0;` does *not* cause the issue, but `margin: 0px;` does.

A sample gif attached (I'm pressing enter after typing in the semicolon).
 To clarify, the `.border()` etc values in the auto-suggestions are LESS mixins I've got, in case the use of LESS might make a difference here.

![vs-code](https://cloud.githubusercontent.com/assets/101693/16108501/1aa36e70-33ac-11e6-915b-e51be8de3c42.gif)

**Comment by aeschli** [comment]
There was a problem with packaging the css extension at it was missing. This is fixed now.
