### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by omegapaulo** [microsoft/vscode#77547]
Issue Type: <b>Bug</b>

The VScode started behaving weird for the past days, every single time I close the extension when done working all is good until I open it again next time, it displays an error message saying ( Extension host terminated unexpectedly ) ( Open Developer Tools or Restart Extension Host ).
And the application itself is lagging so much that I can't use my mouse properly, I have a brand new laptop and quite powerful, but the computer lags when I have VScode installed and when I don't it works just fine. 

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
bracket-pair-colorizer-2|Coe|0.0.28
vscode-svgviewer|css|2.0.0
dart-code|Dar|3.2.1
flutter|Dar|3.2.0
vscode-markdownlint|Dav|0.28.0
jshint|dba|0.10.20
vscode-eslint|dba|1.9.0
es7-react-js-snippets|dsz|2.3.0
gitlens|eam|9.8.5
vscode-html-css|ecm|0.2.0
vscode-npm-script|eg2|0.3.8
prettier-vscode|esb|1.9.0
auto-rename-tag|for|0.1.0
rest-client|hum|0.21.3
html-tag-wrapper|hwe|0.2.3
Angular2|joh|8.1.1
chat|kar|0.15.5
vscode-gutter-preview|kis|0.19.4
vs-color-picker|lih|1.0.0
background-cover|man|2.2.0
python|ms-|2019.6.24221
vsliveshare|ms-|1.0.540
vsliveshare-audio|ms-|0.1.59
vsliveshare-pack|ms-|0.3.2
debugger-for-chrome|msj|4.11.6
vscode-react-native|msj|0.10.1
vetur|oct|0.21.1
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|3.8.1
vscode-css-peek|pra|3.0.2
live-sass|rit|3.0.0
LiveServer|rit|5.6.1
code-settings-sync|Sha|3.4.0
code-spell-checker|str|1.7.17
code-spell-checker-portuguese|str|0.1.0
unique-window-colors|stu|1.0.51
bootstrap4-vscode|the|6.1.0
highlight-matching-tag|vin|0.9.2
vscode-wakatime|Wak|2.1.2
quokka-vscode|Wal|1.0.236
JavaScriptSnippets|xab|1.7.2

(1 theme extensions excluded)

</details>

**Comment by clayms** [comment]
Same problem since updating to most recent version.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
macros|ged|1.2.1
vscode-peacock|joh|2.4.0
chat|kar|0.15.5
sftp|lix|1.12.7
python|ms-|2019.6.24221
Go|ms-|0.11.4
vsliveshare|ms-|1.0.540
vsliveshare-audio|ms-|0.1.60
vsliveshare-pack|ms-|0.3.2
vscodeintellicode|Vis|1.1.8


</details>

**Comment by softcoder** [comment]
Same problem here (using the latest Pop- OS) never had these problems until the last few weeks, especially once I open a JAva file in my Flutter project.

**Comment by jeremytbrun** [comment]
Same problem.

**Comment by alexandrudima** [comment]
It's the `kar... chat` extension
