### ISSUE TITLE
Support searches for CommonJS modules on Typescript

### ISSUE THREAD

**Issue by Himself65** [microsoft/vscode#77627]
When I code the following example, vs-code will not display the correct types
```ts
const Koa = require('koa')
const server = new Koa()

server.listen(3000)
```

![image](https://user-images.githubusercontent.com/14026360/61519060-928dbc00-aa3d-11e9-95d8-82b06f9237c5.png)

but when I code `import Koa = require('koa')` or `import Koa from 'koa'`, it works.

```json
{
  "name": "test2",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "koa": "^2.7.0",
    "typescript": "^3.5.3"
  },
  "devDependencies": {
    "@types/koa": "^2.0.49",
    "@types/node": "^12.6.8"
  }
}
```

```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "baseUrl": "."
  }
}
```

**Comment by mjbvz** [comment]
This is by-design for TS files. TypeScript requires using `import` for typed imports

**Comment by Himself65** [comment]
but `Webstorm` support this feature

**Comment by michaelkolber** [comment]
@mjbvz Could there perhaps be a warning that IntelliSense won't work for `const` requires? It took me a good amount of Googling just to find an answer that explained _how_ to import corectly using `import`, and only after finding that was I able to find this issue that explains that it's not supposed to work. I guess it's not abundantly clear why it works in JS files and not in TS files, and a quick Info in the Problems pane would be nice (especially since TS compiles the `import` to `const` for Node modules).

**Comment by mjbvz** [comment]
This is the designed behavior. It is perfectly valid to write `const x = require(...)` in TS, and in-fact this lets you import files that TS would otherwise complain about.

If you want to have type checking on the import, use `import x = require(...)` or the modern `import x from ...` form. `import from` is what you should probably be using in almost all cases anyways

**Comment by michaelkolber** [comment]
I understand that it's designed, but it's not consistent. Generally, anything valid in JS is also valid in TypeScript. So, one would assume that writing `const x = require(...)` would have the same effect on IntelliSense as `import x = require(...)`. They're both valid, but TS treats one as an import and one as...nothing, which seems inconsistent from my point of view. It's not just type checking, it's **all** IntelliSense. Methods and variables aren't suggested, VS Code just treats the object as if it's nothing, and it's not clear why to someone first stepping into TS on VS Code.
