### ISSUE TITLE
"Report Issue" should come up when I type "bug" into Help search

### ISSUE THREAD

**Issue by jcollum** [microsoft/vscode#77720]
Issue Type: <b>Feature Request</b>

Wanted to report a bug so I went to Help -> Search and typed in "bug". No results. Having the issue reporter come up when that search is triggered would be helpful.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 17.7.0

**Comment by roblourens** [comment]
Related to https://github.com/microsoft/vscode/issues/18697

**Comment by skprabhanjan** [comment]
@roblourens , I can pick it up.
Can you please help me get started with some code pointers ? ( I assume when we type "bug" and entry called "Open Issue Reporter" should come and clicking that should open the issue reporter )

**Comment by roblourens** [comment]
I have absolutely no idea, so rry.

**Comment by skprabhanjan** [comment]
@roblourens , FYI : This is an inbuilt feature into the OS and works for all apps.
The Menu Items Available outside of the Help Tab comes in the search result.
So I guess we have to use the "Report Issue" menu Item in help instead of searching for "bug" and honesty I think this is sufficient enough.

**Comment by jcollum** [comment]
Sure seems like there would be a way to add the word "bug" to a string to
get the OS to pick up that you can use "Report Issue" to report bugs.
