### ISSUE TITLE
Hide information using vsce

### ISSUE THREAD

**Issue by shanalikhan** [microsoft/vscode#77781]
Settings sync now uses Github application to allow users to get Github token.

Github application contains `Client ID` and `Client Secret` in order for authentication.
As the project is open source, the Client ID and secret is openly coded in Github Repo.

There should be any way to pass these values to `vsce` or using the debug mode to the application instead of writing in the code that is already open source, and allow extension to get those values while using the extension.

For example , in `vsce package` should be made something like

```
vsce package -encrypt --clientID "abc" --clientSecret 'Xyz'
```

While in code:

```
vsce.getState("ClientID")
```

In this way, these values are never out or written in open source extensions and only being used to build or debug the application.

Let me know if i can explain it further.

**Comment by joaomoreno** [comment]
An extension VSIX is a simple ZIP file. VS Code is OSS. VSCE is OSS. There is no encryption possible that an attacker won't be able to decypher since all the parts are open source. You might as well just inline the secrets.

There was some movement around supporting user credentials, but that might go around your scenario: https://github.com/Microsoft/vscode/issues/31131 cc @jrieken @chrmarti
