### ISSUE TITLE
Multi-target debugging: Avoid automatic switching debug console focus

### ISSUE THREAD

**Issue by bfelbo** [microsoft/vscode#77836]
Multi-target debugging was implemented in https://github.com/Microsoft/vscode/issues/13426 and it is glorious. Especially for server-client development. However, one tiny issue makes the flow more annoying than it has to be. 

When running server code + client unit tests, once the client unit tests are done, VS Code will automatically switch the focus of the Debug Console to the server. To see whether our tests failed, we need to manually go down to the console and select the client launch config in the dropdown on the top-right.

It would be amazing to be able to turn off this automatic change of focus for the debug console.

**Comment by isidorn** [comment]
This makes sense, and I can look into removing the automatic switching of debug console on shutdown of a session. Will probably do it next week to get feedback next milestone from users

**Comment by bfelbo** [comment]
Awesome. Excited for this!

**Comment by bfelbo** [comment]
Here's another issue somewhat related to this that would be amazing if you could look at: https://github.com/microsoft/vscode/issues/78232

**Comment by isidorn** [comment]
After looking into this it is not that trivial.
The issue here is that the the notiion of a "focused session" is centralised. So if you change the session which you inspect in the debug console, we will also switch what is in the debug toolbar.

Idealy we would not switch the debug console select box only when a session termiantes, however we react on seassion focus events, and currently those events do not have a reason attached to them what caused them. Just if they are explicitly caused by the user or not.

Due to this requiring some refacoring and potentially not be wanted by all our users I am assinging this to the backlog so we can futher discuss this in the future.

**Comment by bfelbo** [comment]
Thanks for looking into this. In terms of all users not wanting it, perhaps it could be added as a setting that defaults to false?

**Comment by isidorn** [comment]
@bfelbo yes that is one option. We try not to add settings for obscure behavior such as this. But we will keep this in mind.
