### ISSUE TITLE
Debug console stops autoscrolling when a line wraps around

### ISSUE THREAD

**Issue by banga** [microsoft/vscode#77837]
Issue Type: <b>Bug</b>

- Make sure the debug console is narrow enough that at least one line will wrap around
- Scroll all the way to the bottom of the debug console so it will autoscroll as more output is generated
- Run any task that produces output with long lines

Notice that when a line that wraps around is printed, autoscrolling stops working and you have to manually scroll to the end to resume it.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 5|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sguillia** [comment]
I can reproduce this, but only if the debug console panel is moved right, not bottom.

**Comment by JoshVarty** [comment]
I am also running into this.

Possibly related: https://github.com/Microsoft/vscode/issues/70331


- VSCode Version: 1.37.1
- OS Version: Ubuntu 18.04.3 LTS

Steps to Reproduce:

1. Create a new Python project (requires `numpy`)
2. Add the code:
```Python
import numpy as np
x = 5
```

3. Place a breakpoint on `x=5`
4. Run the code, allow the breakpoint to be hit.
5. In the debug console type: `np.ones((720,1))` 
6. In the debug console type: `4+4`
7. Observe that the scroll returns to the top of the debug console



Does this issue occur when all extensions are disabled?: **Yes**

![poor_scrolling](https://user-images.githubusercontent.com/1249087/63992938-3f873a00-cabc-11e9-9c9c-9ba9244b7c52.gif)

**Comment by isidorn** [comment]
@JoshVarty nice steps. Thanks. I plan to look next week into this.

**Comment by isidorn** [comment]
I can not reproduce this with node, even though I have multiple lines that wrap.
Unfortunetly I do not have pyhton setup on my machine to follow the exact python steps (after doing `pip install numpy` I get an exception when debugging the program `No module named 'numpy'`)

I believe the issue is [here](https://github.com/Microsoft/vscode/blob/5a9913099c077fe0c93abcdb88d0cb67169fefcf/src/vs/workbench/contrib/debug/browser/repl.ts#L794)

I am open for a PR which fixes this.
The solution would be to better aproximate the height based on the value length.
Due to this bad approximation the autoscrolling breaks.

**Comment by JoshVarty** [comment]
I'm away from my desk this week so I can't double check myself, but instead
of using numpy you could try '[i for i in range(20000)]' in the debugger.

That should return a list of 20,000 numbers and I would assume be long
enough to trigger the bug.

Sent from my iPhone

On Sep 10, 2019, at 9:01 AM, Isidor Nikolic <notifications@github.com>
wrote:

I can not reproduce this with node, even though I have multiple lines that
wrap.
Unfortunetly I do not have pyhton setup on my machine to follow the exact
python steps (after doing pip install numpy I get an exception when
debugging the program No module named 'numpy')

I believe the issue is here
<https://github.com/Microsoft/vscode/blob/5a9913099c077fe0c93abcdb88d0cb67169fefcf/src/vs/workbench/contrib/debug/browser/repl.ts#L794>

I am open for a PR which fixes this.
The solution would be to better aproximate the height based on the value
length.
Due to this bad approximation the autoscrolling breaks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/microsoft/vscode/issues/77837?email_source=notifications&email_token=AAJQ6P4DGKOFKAREKZDDHX3QI6SCBA5CNFSM4IGKQBP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6LF4AQ#issuecomment-529948162>,
or mute the thread

**Comment by isidorn** [comment]
Nope, this works for me

![heyThere](https://user-images.githubusercontent.com/1926584/64703629-1d72bc00-d4ad-11e9-8abb-81ff38d80b0f.gif)

**Comment by sguillia** [comment]
@isidorn 

The line doesn't wrap around because the output is trimmed. You might want to try this instead:
```
'-'.join([str(i) for i in range(2000)])
```

Also I can only reproduce with the debug panel on the right (Right click > Move panel right).

I can't reproduce the problem with that python line above though.

**Comment by bersbersbers** [comment]
In trying to come up with a `numpy`-free set of repro steps (see below), I noticed something unexpected. In the Python stand-alone console, `numpy.ones((5,1))` outputs
```
array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])
```
while in the Debug Console, it outputs
```
array([[1.],\n       [1.],\n       [1.],\n       [1.],\n       [1.]])
```

The same is not true for some other non-`numpy` multiline-output, such as the one from `print("a\nb")`, which is shown in two lines in both cases. Also, commands such as `print(str(numpy.ones((720,1))))` (not the extra `str`) do not cause this issue.

Based on this, consider the following *hypotheses* (speculative, but nevertheless):
1. This is a `numpy`-specific problem, so @isidorn might have a hard time reproducing it without setting up `numpy` in his Python environment.
2. VS Code uses a correct internal rendering of the output to estimate its height, but the actual output has a lower height due to `\n` being printed instead of converted into line breaks. This causes a height mismatch somewhere, leading to incorrect vertical scroll positions. This is somewhat supported by the "Copy All" command in the Debug Console copying line breaks, not `\n` characters.

**Comment by JoshVarty** [comment]
I think it has something to do with Python's `__repr__` (which might mean this isn't a VSCode bug, but a Python tools bug?)

I believe `__repr__` creates a representation of a Python object for use in things like debuggers. 

Anyways, I've got a numpy-free repro for you:

1. Create a new Python project
2. Add the code:
```Python
class Test:
    def __repr__(self):
        return "\n\t" * 10000
x = Test()

y = "this line is for your breakpoint"
```

3. Place a breakpoint on `y = "this line is for your breakpoint"`
4. Run the code, allow the breakpoint to be hit.
5. In the debug console type: `x`
6. In the debug console type: `4+4`
7. Observe that the scroll returns to the top of the debug console

What's interesting is that if you create `x="\n\t" * 10000` and then observe `x` in the debug console, you'll notice that it prints the value of `x` properly and has no problems with any subsequent commands in the debug console.

This only seems to reproduce for me within the context of `__repr__`.

**Comment by sguillia** [comment]
Can you all reproduce this with the debug console panel to the bottom? I can only when it's to the right.

Here are my steps to reproduce:
1. Run command `ext install ms-python.python`
2. Open [this extension sample](https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-sample) folder in vscode
3. Start debugging session (F5)
4. Open debug console on host
5. Move it to the right
6. Open a python file in the guest

And observe the scrolling problem.

This forces me to have the debug console at the bottom while developing an extension.

**Comment by isidorn** [comment]
@JoshVarty thanks for awesome repro steps. I can repro now, investigating...

**Comment by sguillia** [comment]
Thanks! :tada:

**Comment by alexr00** [comment]
I verified using the nice steps here: https://github.com/microsoft/vscode/issues/77837#issuecomment-534796235
I'm still seeing scroll return to the top of the console.

**Comment by isidorn** [comment]
Let's keep this closed since there is already a duplicate which I will look into next milestone.
Though it should behave a bit better now
Duplicate https://github.com/microsoft/vscode/issues/81951#event-2687450865

**Comment by isidorn** [comment]
Actually my fix just made it worse. Sorry about that. Reverting my fix and reopening this issue.
This milestone I will fix this proper, promise 🙏

**Comment by rickstaa** [comment]
@jeanp413  The fix is working. I now have the desired scroll behavoir back! @jeanp413 and @isidorn Thanks a lot!

**Comment by isidorn** [comment]
Thanks, adding verified label.
