### ISSUE TITLE
PCRE2 beginning/end of file anchors don't work properly

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#77947]
Issue Type: <b>Bug</b>

Using `\A` and `\Z` to match the beginning and end of the file don't work properly. Most of the time they act like `^` and `$` match every single line in the file. On the first result they appear to match the literal characters `A` and `Z` which has the appearance of matching in the middle of random lines.

![image](https://user-images.githubusercontent.com/484784/61895618-eed25f00-aec7-11e9-9ce0-33d44bb5c2a6.png)

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3598)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (19.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by roblourens** [comment]
A few things going on - we use ripgrep to search the workspace which uses the Rust regex engine, or you can force PCRE2 with a setting. Either way, `\A` seems to have the same behavior as `^`, I don't think that's wrong based on what I'm seeing: https://www.rexegg.com/regex-quickstart.html#anchors

Then open files we search using the JS regex engine which just does not support that escape sequence. So that explains the unfortunate discrepency.

**Comment by akbyrd** [comment]
This is with PCRE2 enabled because the ripgrep implementation doesn't support `\A` and `\Z` at all

The behavior where is \A matches _the literal character A_ is _definitely_ a bug, no matter whether you expect it to match the beginning of the file or the beginning of each line.

Also, the behavior does not actually match the document you linked. `^` is defined to match the "start of string" OR "start of line" based on the multiline setting. Assuming the vscode implementation defaults to multiline then `^` should indeed match on  every line.

However, `/A` is defined to match "beginning of string" only. That links to [this section](https://www.rexegg.com/regex-anchors.html#A) which clarifies that it should only match _at the beginning of the file_. Same with `\Z`.

This is corroborated [here](https://www.regular-expressions.info/anchors.html) where `\A` and `\Z` are defined as _never matching at line breaks_.

**Comment by roblourens** [comment]
Ok, I see that it has the behavior you describe if I force PCRE2 and also enable multiline mode. I think that what's happening is that when not in multiline mode, ripgrep invokes PCRE2 line by line so PCRE2 doesn't know about the beginning of the file anyway.

On vscode's side, as an optimization we only enable multiline mode when a `\n` literal is present. 

Thus if you enable PCRE2 and force multiline mode like with a `\n{0}` in your query, you get the behavior you expect.

This is not a nice workaround but I think the fact that it works at all is a quirk which you can't even necessarily depend on.

> The behavior where is \A matches the literal character A is definitely a bug

If so, it is a bug in the JS regex engine, and the fact that this only shows up sometimes is unfortunate due to us using mulitiple regex engines but we can't really do anything about it right now. Sorry I don't have a better answer.

**Comment by akbyrd** [comment]
Should this task be kept open since there are 2 confirmed bugs that presumably ought to be fixed? Regex is a pretty important editing tool and being able to rely on it in my editor is sort of critical.

**Comment by roblourens** [comment]
I don't think the JS regex issue is a bug, it's probably more of a design decision, but you can take that up with them if you want.

I think it's not likely that ripgrep will change how it interacts with PCRE2 just to get this flag to work. I'm not going to file an issue about it because we can't support it fully in vscode anyway (due to JS not supporting it)
