### ISSUE TITLE
Window shuts down when remote disconnects while debugging EH

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#77944]
- Debug the remote-ssh extension using the typical extensionHost debug launch config
- Set `"remote.SSH.showLoginTerminal": true` just to make this easier
- Connect to a remote
- Find the "install" terminal and kill it
- The extension development host window closes

This is due to this:

https://github.com/microsoft/vscode/blob/3b5ee24ca3e3eaf12d730a5ac9dd72f3669aa954/src/vs/workbench/services/extensions/common/remoteExtensionHostClient.ts#L120-L124

I don't know why we need this, it makes sense to test reconnection while developing an extension too.

**Comment by alexandrudima** [comment]
https://github.com/microsoft/vscode-remote/issues/178

**Comment by roblourens** [comment]
The debug service knows when the stop button was pressed. Can the debug service not be responsible for shutting down the window when debugging is done.

**Comment by alexandrudima** [comment]
@roblourens I think it's best we ask @weinand . 

I don't know all the cases, but the logic has been so far: the stop button kills the extension host process directly ==> when a renderer sees that the extension host process has exited and it is in debug mode, it closes.

I haven't defined this behaviour, I just had to maintain it once we went to remote...

**Comment by weinand** [comment]
The Stop button doesn't know anything about EH debugging and closing windows, it just uses the DAP's terminate/disconnect functionality to talk to the DA. The DA talks to the debuggee (which in this case happens to be the EH). Closing the window is done by VS Code which tracks the EH's lifecycle and knows best what to do. And VS Code thinks in this situation (extension debugging) it is best **not** trying to reconnect.
 
We let VS Code handle these decisions how to deal with the EH window because VS Code has to handle those cases anyway, e.g. for a crashing EH or a restarted EH or just the quit command.

If we want to change the behavior (e.g. reconnecting instead of disconnecting), we could introduce a VS Code option. Always enabling this option, doesn't really work because then pressing the debugger's Stop button would always end up in VS Code restarting and reconnecting.

/cc @isidorn

**Comment by roblourens** [comment]
Assuming you want this open since you assigned it @weinand?

**Comment by weinand** [comment]
@roblourens do you suggest that we add a new (optional) feature to make VS Code reconnect instead of disconnect in this case?

**Comment by roblourens** [comment]
Yes
