### ISSUE TITLE
[html] support script type="text/html"

### ISSUE THREAD

**Issue by nileio** [microsoft/vscode#77977]
- VSCode Version: 1.36.1
- OS Version: MacOS

Steps to Reproduce:

1. create a file with extension .html file
2. Include a script tag like the following
`<script type="text/html">`
<p
</script>
3. No auto-complete for html tag names

Does this issue occur when all extensions are disabled?: Yes

HTML inside a `<script type="text/html">` tag is recognised as html with syntax color highlights ok, but there is no intellisense autocomplete for html tags like in normal html only files.

**Comment by MadCoder253** [comment]
Would this feature request handle the following case?

`<script type="text/worker">`

This custom type is used by an roll20.net, an online Table Top RPG, when users are developing their own custom character sheets. Everything inside the script tag is still javascript. Would it be possible to have VS Code users define a custom type to be treated as javascript? From what I've read, it's possible to have Sublime treat text/worker as javasript.

**Comment by aeschli** [comment]
@MadCoder253 That should be a separate request.

**Comment by Sau64** [comment]
There is also no code folding. Removing type="text/html" enables code folding but html emmets are lost.

**Comment by aeschli** [comment]
For anyone interested in working on this: I good starting point for this is https://github.com/microsoft/vscode/blob/4fbb5f84857f07f7e66fc45da31e5c87136549d6/extensions/html-language-features/server/src/modes/embeddedSupport.ts#L59

**Comment by aliasliao** [comment]
Hi @aeschli , I'm working on this issue and found that the problem might be fixed by https://github.com/microsoft/vscode-html-languageservice/pull/102. I'm not sure if pr https://github.com/microsoft/vscode/pull/117360 is necessary since html code in `<script type="text/x-handlebars-template">` works pretty well without setting `languageIdFromType = 'html'` [like this](https://github.com/microsoft/vscode/pull/117360/files#diff-6e884c6844c77719f4fe0310a5b43780ae347b7926140df5d6d29fa08dd4ceebR64).

![image](https://user-images.githubusercontent.com/22636233/108833523-e8f2b180-7607-11eb-90f6-b265cf008625.png)

**Comment by aeschli** [comment]
You are right, that can be fixed in the HTML language service, I forgot about that. Thanks for the PR!
We can close #117360 then

**Comment by aliasliao** [comment]
@aeschli Could you please review my PR https://github.com/microsoft/vscode-html-languageservice/pull/102? Thanks a lot!
