### ISSUE TITLE
Starting with a TS/JS file is significantly file slower than opening other files

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#77990]
* start profiler
* reload with a TS file
* stop profiler
* 🔥 notice how all grammar files are read and processed
* start profiler again
* reload with a JSON file
* stop profiler
* 🚀 getting colors was much, much quicker

<img width="724" alt="Screenshot 2019-07-26 at 15 01 52" src="https://user-images.githubusercontent.com/1794099/61953295-54047e00-afb6-11e9-8685-779eba06756c.png">

The problem is the [jsdoc injection](https://github.com/microsoft/vscode/blob/a7122371aaa76237b155cd38c57e9d66a5f47637/extensions/typescript-basics/package.json#L81-L90) which itself drags in the MD grammar which drags in the world...

**Comment by alexandrudima** [comment]
root cause -- https://github.com/microsoft/vscode/blob/c94b2703c5d7688d74473b579844fcded5269589/extensions/typescript-basics/package.json#L81-L90

This injection drags in markdown, which drags in almost all our grammars...

Removing that reduces the time significantly.

**Comment by mjbvz** [comment]
I believe the core reason for this is the markdown grammar's fenced code block support. That ends up pulling in grammars for most of our builtin languages. Will see if including a subset of the markdown grammar fixes this or if we maybe need to split up the markdown grammar file in some way

**Comment by alexandrudima** [comment]
@mjbvz Good idea! I think going for a reduced subset is the right thing to do. 

I would also incorporate this into the TS grammar itself, the TS grammar already appears to do a lot of JSDoc parsing anyways, so why wouldn't Sublime and other editors where the TS grammar is used benefit from this... 

Also, IMHO we should avoid injection if possible and in this case I think it is possible because we can reach to the TS team who own the TS grammar and they can add the fenced block rule to their grammar if we would give them a PR.

**Comment by mjbvz** [comment]
It's a bit complicated since fenced code blocks can appear inside other markdown elements, like lists. 

Sublime doesn't support some of the rules we need to support the jsdoc highlighting feature (https://github.com/microsoft/TypeScript-TmLanguage/issues/693) so that why I went with the injection based approach

I think we either need to:

- Inline some basic parts of the markdown grammar
- Split all the fenced code block  into an injection grammar (these are not loaded for referenced grammars)

I'll be looking into the first approach today

**Comment by mjbvz** [comment]
After thinking about this more, I don't think we should do a js/ts specific fix. The same performance problem also exists when you load VS Code with a markdown file open.

I've opened https://github.com/microsoft/vscode-textmate/issues/106 that proposes loading referenced grammars lazily. This would fix the issue for js/ts and for normal md files too

**Comment by alexandrudima** [comment]
@mjbvz Let's remove the TS injection until we address https://github.com/microsoft/vscode-textmate/issues/106
(We have only added this a few months ago and IMHO is not critical to the TS experience)

**Comment by bpasero** [comment]
I am still seeing this in web. Steps:
* add a console.log statement where we load grammars using file service:

https://github.com/microsoft/vscode/blob/284355484923ab30340d0957a3108fcf67bb5a08/src/vs/workbench/services/textMate/browser/abstractTextMateService.ts#L195
* open a JS/TS file
* observe that every grammar seems to be loaded

**Comment by alexandrudima** [comment]
It is unfortunate how this was never verified because it didn't have a `bug` label :|

**Comment by alexandrudima** [comment]
The fix from @mjbvz in https://github.com/microsoft/vscode/commit/5c2738521209c6f026ce349495843f008c9a7d50 unfortunately had no effect because the grammar resolver was not written to only partially resolve grammars, so even if a small subset of markdown was included via injection, the entirety of it was loaded.

**Comment by bpasero** [comment]
Thanks!

**Comment by mjbvz** [comment]
Thanks @alexandrudima! Sorry, I thought I had profiled when I made the original fix but clearly was not look at the right thing. You change looks much better

**Comment by bpasero** [comment]
@mjbvz there are other languages that will suffer from this issue too, should we fix them as well? For example I think F#, PHP, Perl. Probably anything that depends on markdown.

**Comment by connor4312** [comment]
I gave a spin at verifying this by measuring the total time spent in `tokenize2` for a small JSON file and a small TypeScript file. Understanding that TypeScript will always be more complex than JSON, here's the results:

```
JSON:
 - 18.5ms
 - 20.6ms
 - 16.8ms

TypeScript:
 - 72.4ms
 - 76.1ms
 - 82.0ms
```

@alexandrudima @jrieken are these measurements within the bounds that you'd consider this resolved? (Unlabel if not 🙂 )

**Comment by jrieken** [comment]
Yeah, I have measure the same number. I think reasonable because the JSON grammar is trivial in comparison to the TS grammar. Tho, there is still https://github.com/microsoft/vscode/issues/77990#issuecomment-547291377 which we should probably move into a separate issue

**Comment by bpasero** [comment]
Opened https://github.com/microsoft/vscode/issues/83633 for @mjbvz

**Comment by alexandrudima** [comment]
This is all rather complicated, but we had to revert `vscode-textmate` to the last month's stable version, because of a flaw which was causing https://github.com/microsoft/vscode/issues/83541 .

That would technically mean that this issue is reopened (with the revert).

The lowest risk fix at this point is to revert `vscode-textmate` and delete the problematic injections.
