### ISSUE TITLE
Omit locations visited by incremental search from 'Go back' history

### ISSUE THREAD

**Issue by andrewsm80** [microsoft/vscode#78000]
Issue Type: <b>Feature Request</b>

I often use <kbd>CTRL + F</kbd> to repeatedly jump between two or more locations in a file.

I could be saved some typing if I could <kbd>CTRL+F</kbd> to the second location and then simply "Go back" (<kbd>ALT + Left Arrow</kbd>) to the first location. 

This currently doesn't work with incremental search enabled, because many unrelated locations are visited in the file as each character is typed into the search dialog. Especially the first few characters.

**I'd like to see a setting to omit locations visited as a result of incremental search from the 'Go back' history.**

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

**Comment by JasonWoof** [comment]
Why is this labeled a feature request and not a bug?

There's no way that the current behavior is useful or intended.

The current implementation of find breaks the go-back feature.

Just because it's been broken for a long time doesn't mean it's not a bug.

Find-then-go-back is a very common pattern for many programmers, and it doesn't work well. It is very distracting to have to hit go-back an arbitrary number of times while watching to see if the cursor has gotten all the way back yet. Distracting enough that I often forget what I was going to do when I got there.

Worse, there's another bug where it sometimes never goes back to where the cursor was when I pressed Ctrl-F, and jumps to some earlier remembered place, sometimes in a different file. Unrelated I know, but I just mention it because it makes this bug more frustrating. I'll report it when I can figure out how to reproduce it reliably.
