### ISSUE TITLE
Document fixing tslint with update to @types/vscode

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode#78019]
With the update to @types/vscode, the extension lint settings, which I pulled from another extension, causes the following error every time `vscode` is imported. 

`Module 'vscode' is not listed as dependency in package.json`

I am not a JS developer normally, so I had no clue how to fix this, and the release notes showed no way on how to do this either. Looking around, it looks like adding `"no-implicit-dependencies": [true, "dev"],` to my tslist settings, but I realized I already had that, and that doesn't work. What is the right way to solve this issue, and can a solution be added to either the release notes or documentation on building extensions?

**Comment by octref** [comment]
I think this would be an issue with the tslint extension you have. If running `npx tslint` locally doesn't yield any error, that's probably due to extension not resolving the config correctly.

Open an issue for https://marketplace.visualstudio.com/items?itemName=eg2.tslint or https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin, whichever you are using. (Also, try the deprecated one if the new one doesn't work).

**Comment by ThadHouse** [comment]
@octref  Its not caused by an extension, actually running `npm lint` directly from the command line causes the error. Its more of a documentation error for VS Code, because it updated how it provides itself to extensions, but not common issues that could occur, not this one.

**Comment by octref** [comment]
From other thread I saw `"no-implicit-dependencies": [true, "dev"]` was working. Is it not working for you? Then you should probably report an issue for tslint. Some global extension runtime such as vscode, chrome doesn't have direct dependencies as they are provided by the tool's runtime.

**Comment by Eskibear** [comment]
same here for me. 
`"no-implicit-dependencies": [true, "dev"]` is not working.
