### ISSUE TITLE
Few new commands for find/replace

### ISSUE THREAD

**Issue by Martin00001** [microsoft/vscode#78055]
Issue Type: <b>Feature Request</b>

Commands like editor.action.addSelectionToNextFind/editor.action.replaceOne add cursors or show a find/replace panel. I need simpler commands which do not do those things. I would like to find or replace simply. I would like use these commands: 

1. editor.action.addSelectionToFindVariable, 
2. editor.action.addSelectionToReplaceVariable, 
3. editor.action.FindVariable, 
4. editor.action.replaceOneWithVariable
5. editor.action.replaceAllWithVariable

The first one should copy a selected text in the editor to a find variable. The second one should copy a selected text in the editor to a replace variable. The third one should select each occurrence of a text equaled the find variable in the editor gradually. The fourth one should replace the selected text with the replace variable. The fifth one should replace all occurrences of a text equaled the find variable with the replace variable.

I will assign keyboard shortcuts to the commands.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17134

**Comment by rebornix** [comment]
We closed this issue because we don't plan to address it in the foreseeable future. You can find more detailed information about our decision-making process [here](https://aka.ms/vscode-out-of-scope). If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Thanks for your understanding and happy coding!
