### ISSUE TITLE
Cursor incorrect over code

### ISSUE THREAD

**Issue by Nokel81** [microsoft/vscode#78119]
- VSCode Version: 1.36.1
- OS Version: macOS 10.14.5 

Steps to Reproduce:

1. Have a file open (noticing that the cursor is the `I` meaning edit)
2. Right click 
3. Click away from the RC menu
4. Notice that the cursor is currently still on arrow mode. Even though it is over editable lines

**Comment by joaomoreno** [comment]
This seems to be Electron specific. I can't repro on Chrome.

**Comment by Nokel81** [comment]
Ah, yes it might be electron specific (I use firefox) because I seem to have the same behaviour on the slack client

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
