### ISSUE TITLE
Icons: Running Extensions arrow/circle icons look thicc

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#78149]
Testing #78113

Notice the play and record icons in the screenshot:

![image](https://user-images.githubusercontent.com/22350/62110382-911a8a00-b2ae-11e9-8301-8a3f86b02b3c.png)

They look thicc, not in a good way!

**Comment by misolori** [comment]
Made these the same pixel width. Also updated the record icon since it was just an empty circle, and updated the color for Start Debugging since it's the same icon in the npm script explorer:

<img width="175" alt="image" src="https://user-images.githubusercontent.com/35271042/62250392-a9b79c80-b3a1-11e9-8140-40749d2af8c8.png">
