### ISSUE TITLE
Typescript: unused variable false warning and incorrect Quick Fix option

### ISSUE THREAD

**Issue by dhananjay1405** [microsoft/vscode#78143]
- VSCode Version: 1.36.1
- OS Version: Windows 10 (x64)

tsconfig.json
"noUnusedLocals": true

Declaring multiple variables in typescript in a single let statement, produces a warning that variable is declared but never used. Now even after writing line further lines where variable is used, still the error persists.
![ts-unused-variable-warning](https://user-images.githubusercontent.com/43024754/62105833-2757ab80-b2c1-11e9-9ea3-6d29c4897d2a.png)

Add to it on clicking **Quick Fix**,  VS Code displays option of _Remove Declaration for_ that variable. Selecting that option removes all lines containing reference of that variable, which is a destructive action which may result to deletion of legible code too.
![vscode-typescript-quick-fix-issue](https://user-images.githubusercontent.com/43024754/62105848-30e11380-b2c1-11e9-8c2b-dec192e94fd5.gif)

Kindly refer screen-clipping of warning and GIF of Quick Fix action

**Comment by IllusionMH** [comment]
This is correct warning because variable is block scoped (declared with `let`) and there are no instances where it is used to calculate anything other - only reassignment later.

This error will go away as soon as you use it in expression, pass as an argument to a function etc.

If you look from other perspective - you remove come unnecessary call to a function from block. TS marks all variables that were passes to the function and not used anymore.
