### ISSUE TITLE
Extension API: Listen for CompletionItem selected

### ISSUE THREAD

**Issue by philipyun** [microsoft/vscode#78252]
I'd like to be able to know when a CompletionItem has been selected without creating a provider.  I do not wish to provide extra completion data, but instead hook into the data already being presented by the editor.

My use case is the following:

Take a React Component in TS or JS

for our example lets say we have a button
```
const Button = () => {
// button render
}

Button.propTypes = {
  onClick: PropTypes.function.isRequired,
  buttonText: PropTypes.string.isRequired,
  optionalParam: PropTypes.string
}
```

I begin to type `<But` in my render function of another component.  VSCode suggests the symbol, `Button`.  Once it is auto filled I would like my extension to provide the following blank props as so (notice the omission of `optionalParam`)

`<Button onClick={<cursor here>} buttonText={}`

Either having this capability so I can provide this as an extension, or having this support native to the React parser in the Editor would be much appreciated.

**Comment by philipyun** [comment]
I want to mention, that this feature is implemented natively in WebStorm. This is a great feature for React code, and can be leveraged by both propTypes and TypeScript prop declarations, and should be included (at least as an option) to VSCode

**Comment by jrieken** [comment]
>  I do not wish to provide extra completion data, but instead hook into the data already being presented by the editor.

The presentation data model is purely for representation purposes, that means you have no reliable way of knowing that a 'Button' suggestion is actually the thing you have in mind. It might be any symbol that's available (globally or via import) and that happens to be called 'Button' but it might not have such properties. 

Since the API and the LSP are designed to work by describing the UX data model (not the language model) there is no hope that you can correctly implement this.  

The feature you want is cool, but you should consider filing this against TypeScript as feature request, or write a plugin for the typescript server which has API for exactly this use-case: https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin
