### ISSUE TITLE
Handle failed commands when running code actions

### ISSUE THREAD

**Issue by sureyeaah** [microsoft/vscode#78287]
When the response to executing a command is an error, VSCode should display the error to the user so they know the command wasn't executed(and why).

For example, when a refactoring is too complex to perform, the user would want to know that it didn't happen and the reason behind it.

**Comment by jrieken** [comment]
> For example, when a refactoring is too complex to perform, the user would want to know that it didn't happen and the reason behind it.

Is this your concrete use-case for which you want a message to be shown? I am asking because commands are at the heart of VS Code and we cannot simply show a message from the command service whenever a command fails, it must be the consumers of such commands because they know the context in which to show such messages best

**Comment by sureyeaah** [comment]
My concrete use-case is letting the user know why a refactoring like 'Extract to Function' didn't execute. Kinda like how 'Go to definintion' shows 'No definition found for...' popup when it fails to do its job.

**Comment by mjbvz** [comment]
How specifically are you trying to extract a function? Keybinding?

**Comment by sureyeaah** [comment]
Not just 'extract function' but any codeAction that vscode notifies the user of through the light bulb.

**Comment by mjbvz** [comment]
`extract function` should only show up in the lightbulb menu if the action can be performed.  Please specifically describe how you are triggering the code action

**Comment by sureyeaah** [comment]
Okay, so basically the user selects the statements that need to be extracted and if it passes clangd's preliminary check, it send a codeAction to VSCode. The user sees it in the lightbulb and selects extract to function. VSCode sends executeCommand action to Clangd and if Clangd decides after a more rigorous analysis that it can be extracted, it sends the edits otherwise it sends an error.

**Comment by mjbvz** [comment]
It is up to extensions how to handle when a refactoring cannot be applied. JS/TS shows error notifications for example.

Please file an issue against the extension that provides these code actions

**Comment by sam-mccall** [comment]
@mjbvz Asking each extension (rather than the generic language client) to handle error UI for the code-action flow seems inconsistent with how other LSP features are handled.
For example:
 - when `textDocument/rename` encounters an error, VSCode will display it (through the generic language client)
 - within the code action workflow, extensions don't need to specify when the lightbulb menu should trigger, which actions should be shown in the lightbulb menu, what the labels should be, etc.

It seems that having a generic way of showing errors produced by the code action would be simpler and promote more consistency across extensions, too.

**Comment by jrieken** [comment]
@sureyeaah Do you have a LSP-case (as @sam-mccall suggests) or do you work against the extension API directly?

**Comment by sureyeaah** [comment]
@jrieken Yes I'm working with LSP.

**Comment by jrieken** [comment]
Adding @dbaeumer for the LSP aspect of this

**Comment by dbaeumer** [comment]
Currently executing a command only logs if the server fails to do so. I can easily rethrow the error. 

@jrieken what will VS Code do in that case. Show a notification? (e.g. when a command execution that is registered via `Commands.registerCommand` fails)

**Comment by dbaeumer** [comment]
I tested it and it shows a generic error message:

<img width="462" alt="capture" src="https://user-images.githubusercontent.com/1931590/63347231-fd8d2400-c356-11e9-90fe-03ee89b89be8.png">

@jrieken would it make sense for VS Code to include the message provided in the error. Will make it more user friendly for all command execution.

**Comment by jrieken** [comment]
> @jrieken what will VS Code do in that case. Show a notification?

It depends on the caller of `ICommandService#executeCommand`. The service itself implements no UI and leaves it up to the caller to show a (nice) message in context.

**Comment by dbaeumer** [comment]
But these commands are tricker by the user through the UI. The one I show is triggered through `Ctrl+Shift+P`. Shouldn't we in this case show a better message.

I do agree that if an extension uses `ICommandService#executeCommand` then the extension trigger the command is responsible for showing the error message.

**Comment by jrieken** [comment]
Yeah, this is about commands that are triggered for code actions, specifically from LSP. Now I understand that there is no way for LSP to catch those errors. 

Re-open so that the code action logic can do the error handling. @mjbvz I do think we should have a generic error handling, similar to rename, so that all failed code actions have the same UI. Failure should be defined as rejecting the promise returned from executing the command and we should do our best to extract a message from that rejection.

**Comment by mjbvz** [comment]
Fixed by b17e5587df7e3c7faf730e29e944820c6123dc34
