### ISSUE TITLE
Git submodule support

### ISSUE THREAD

**Issue by stofte** [Microsoft/vscode#7829]
- VSCode Version:
  1.2.1
- OS Version:
  Windows 8.1 x64

Steps to Reproduce:
1. git clone --recursive repo-with-sub-module
2. code .
3. Edit file in the submodule folder and save
4. Change to git panel
5. Click the changed file
6. VS Code warns "Can't open this git resource."

Is there support for this handy git feature?

**Comment by komakino** [comment]
@joaomoreno Any news or comments about this?

**Comment by joaomoreno** [comment]
Nothing.

**Comment by mwolfhoffman** [comment]
Hey,  Looks like I just solved this problem with a little experimentation. I'm using VS Code and could resolve all of my merge conflicts, except one file wouldn't open and just said "Can't Open This Git Resource". This was a new file I was merging into master from another branch, so it wasn't that it was a conflict but it just didn't exist on the other branch. I went ahead and staged the change then synced and it worked fine.

**Comment by kkukshtel** [comment]
Seconding sub-module support. VSCode is great otherwise but would love to see diffed files from included submodules (and even ability to push).

**Comment by xoniq** [comment]
Also want to request this feature. Had to disable Git support in VS Code because I need this in most of my projects, without it the Git support is useless.

**Comment by chrisjimallen** [comment]
+1 for submodule support.

**Comment by ZLima12** [comment]
+1 as well, it doesn't seem like Code can see node.js packages if they are in the submodule's root. (I am using TypeScript).

**Comment by kc-curefit** [comment]
+1 much needed for any large size project

**Comment by mateuszlewko** [comment]
+1 It's a really needed feature. Is there any chance we will see it near future?

**Comment by nkev** [comment]
+1 For most cases, this would make dedicated Git GUI Clients redundant when using Vs Code

**Comment by Franky47** [comment]
How does this interact with the newly proposed SCM API in #2824 ?

**Comment by LPCmedia** [comment]
+1

**Comment by antoine-pous** [comment]
bump

**Comment by jens1o** [comment]
@antoine-pous Feel free to provide a pr. :)

**Comment by daljaz** [comment]
+1 for submodule support

**Comment by evgenykovalyov** [comment]
+1

**Comment by unixs** [comment]
+1

**Comment by fshauge** [comment]
+1

**Comment by jhasse** [comment]
Please use GitHub's "+1" reaction for the first post instead of posting +1.

**Comment by kirtangajjar** [comment]
@joaomoreno Any updates ?

**Comment by jasonkotte** [comment]
+1

**Comment by yoyo837** [comment]
+1 for submodule support

**Comment by AaronDevaney** [comment]
+1

**Comment by Ash258** [comment]
Any news about submodules support?

**Comment by xoniq** [comment]
@Ash258, what do you expect after more then a year, no response at all, just laugh at it and use another editor. You cannot take this editor serious with missing such features.

**Comment by z-ax** [comment]
I'm really confused it's not supported.

**Comment by cassianomon** [comment]
+1

**Comment by erickarr** [comment]
+1

**Comment by petkahl** [comment]
So, for those of you who are requesting this, what does git submodule support look like? I've never used it much, but have started, so I was thinking of trying to implement it here.

**Comment by erickarr** [comment]
Inside a project, particularly one versioned with Git, you have add 'submodules', which are direct links to additional Git repositories. One may be using such a repository, as a dependency within their own project. You may also be a contributor to said submodule.

When you open a project in VS Code, it shows you the Git versioning for the current project you have opened. From there you can view your change history, make commits, etc. Often, you do development within your submodules too. Ideally, you would be able to _change_ to that submodules directory, and view the change history make commits, etc. Currently there is no support for doing so.

**Comment by petkahl** [comment]
@erickarr, so would automatically opening submodules similar to the way multiple git repositories are opened when you open a folder above them satisfy the need, for the most part? You still have to context shift to perform operations on these separate repositories, but you don't have to leave the editor?

**Comment by erickarr** [comment]
@petkahl Yes, exactly. As people have mentioned previously, currently when you click on the folder to open it, you get a 'Unable to open 'Specified Folder Name': File is a directory' error.

It would be **awesome**, to click on your submodules folder name, jump in there, make your commits etc., and jump back out. Because the developers have truly done a good job with the Git integration in VS code (compared to many alternatives), but the ability to do the same within submodules is missing.

**Comment by petkahl** [comment]
You're talking about the folder name in the source control context, not the Explorer, right? 
My thoughts were:

- When a repository is opened, it should scan for submodules in it and open those repositories as well (actually, I have this working already, although it looks like I lose the context menus for the Explorer view. I'm hoping that's just configuration)
- Clicking on a changed submodule should do something useful, rather than "Error: Unable to open 'Submodule (Working Tree)': File is directory." Perhaps open that submodule's repository? Or if that's not possible, maybe just do nothing?
- Maybe show changed submodules with a special icon to signify they are submodules? Or in a special group, or even both? 

I like the idea of submodules having a sort of tree structure, and when you're in a submodule, show a ".." submodule that is actually the parent. But as far as I can tell, there's no way to open a particular repository programmatically.

**Comment by petkahl** [comment]
If anybody's interested, https://github.com/petkahl/vscode/tree/git-submodules contains the first pass at my first bullet point above.

**Comment by easyrider** [comment]
+1

**Comment by johnnyhuy** [comment]
This can technically be done with a new feature introduced, [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces). Just add folders including the sub-modules to the workspace and both repositories should appear on the source control menu.

**Comment by cassianomon** [comment]
@johnnyhuy Awesome, gonna test this

**Comment by nunovieira** [comment]
@johnnyhuy Multi-root Workspaces doesn't fix this. In projects with git submodules, details of the submodules don't show on the Source Control pane. It treats the submodule as a file.
We should be able to select each submodule in the [SOURCE CONTROL PROVIDERS section](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_source-control) and act on it, like we do with the "parent" repository.
[Git status in File Explorer](https://code.visualstudio.com/updates/v1_18#_git-status-in-file-explorer) and [other Source Control goodies](https://code.visualstudio.com/updates/v1_18#_source-control) should also work with git submodules. 

This is a must-have for any project that uses git submodules.

**Comment by petkahl** [comment]
What's interesting is, when trying to use Multi-Root workspaces as a workaround, it is very significant what order you add the folders. In my experience, if you add the submodules first, then they show up in the source control pane, but if you add the parent folder, it never shows up. If you add the parent first, it shows up, but none of the submodules ever show up, probably because of the way it searches for repositories. 

#36313 is a pretty solid fix for this, hopefully it'll work its way through the process and get included.

**Comment by awidjaja** [comment]
**[git subtree](http://alistra.ghost.io/2014/11/30/git-subtree-a-better-alternative-to-git-submodule/)** is better than git submodule. 

Would it be possible to add the `git subtree` command in the git menu list item?

**Comment by BenjaminAbt** [comment]
subtree is maybe better for you - but not for all.
submodules are more common here.

**Comment by petkahl** [comment]
@awidjaja that sort of request seems pretty far from the scope of the request here. I'd search for and/or create a separate issue for it.

**Comment by joaomoreno** [comment]
Thanks to @petkahl, basic submodule support has landed in `master`! 🎆 

![kapture 2017-12-14 at 12 37 33](https://user-images.githubusercontent.com/22350/33990565-b318709c-e0cb-11e7-85f7-872cec7347ea.gif)

A bit more details:

- Submodules get an explorer decoration
- Submodules appear as separate repositories in the SCM view
- Submodule `HEAD` changes appear in the outer repository's status list; you can click them to see the diff which shows the `HEAD` change
- You can stage, unstage and revert submodule `HEAD` changes

We still need submodule management features (add, remove, update, init), but since the basic support is in, I'll close this and wait for feature requests!

**Comment by ultra2** [comment]
How can I use it?

**Comment by petkahl** [comment]
@ultra2, it just makes the submodule git repositories show in the source control sidebar (and highlighting in the file explorer). You still have to manage the submodule creation and init from the command line.

**Comment by white-hat** [comment]
@ultra2 the problem that it actually does not. I have several git repos with submodules, and I do not see behavior similar to a GIF above. while Sourcetree recognizes the submodule and allow to work with it as a repo, vscode does not do that. It does not mark submodule with 'S' in explorer, it tries to update submodule's root folder and fails with an error
`Unable to open 'common (Working Tree)': File is directory.` where `common` is a root folder of the submodule. 
I have 1.19.2 installed for MacOS

**Comment by nunovieira** [comment]
It's available on 1.20.0-insider.
