### ISSUE TITLE
DebugConfigurationProvider provideDebugConfigurations not getting called

### ISSUE THREAD

**Issue by cdturner** [microsoft/vscode#78362]
- VSCode Version: 1.37.insiders  (downloaded as of 8/1/2019 )
- OS Version: windows 7, 64 bit.

the package.json registers for the OnDebug activation.

the resolveDebugConfiguration gets called, but the provideDebugConfigurations does not.

Steps to Reproduce:
1. start from the vscode-mock-debug project.
2. add the following to the MockConfigurationProvider in extension.ts

```
provideDebugConfigurations(folder: vscode.WorkspaceFolder | undefined, token?: vscode.CancellationToken): ProviderResult<vscode.DebugConfiguration[]> {
	console.log("provideDebugConfigurations");
	return [];
}

```
3. Run the mock-debug project. 
4. open a sample markdown file.
5. hit F5 to start a debugging session. At this point the activation in the extension.ts is executed. and the MockConfigurationProvider is registered.

Before it displays the dropdown offering "Mock Debug" it should have called the provideDebugConfigurations.

although the code above returns an empty array. you can add any data you like in there. 
I've looked through your code base and can see no reason for it not to be called. !!provider.provideDebugConfigurations resolves to true.

I asked on stackoverflow but got no answer.

**Comment by isidorn** [comment]
Thanks for the steps. I will look into this next week.

**Comment by isidorn** [comment]
I have investigated this and it is expected behavior.

Namely, `provideDebugConfigurations` is only called then the debug configurations are needed to generate a `launch.json`file. If you click on the configure command the `provideDebugConfigurations` will get nicely called.
However if you do not have a launch.json and you simply press Debug Start, vscode will try to start debugging without using debug configurations, but using one on the fly provided by the `resolveDebugConfiguration` call.

More about this can be found in our docs https://code.visualstudio.com/api/extension-guides/debugger-extension

Thus closing this as designed.
