### ISSUE TITLE
Hide pruned git branches

### ISSUE THREAD

**Issue by BernieWhite** [microsoft/vscode#78366]
Issue Type: <b>Feature Request</b>

It would be great if was could hide pruned branches in the branch drop downs.

Also related it would also be nice to hide tags based on naming convention from the list to. I still want some tags, but if I could hide tags with a -Bnnnnn extension that would be awesome.

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

**Comment by joaomoreno** [comment]
What do you mean by pruned branches?

Is there an equivalent command line git command to show the branch list you want?

**Comment by BernieWhite** [comment]
```git remote prune origin```

Branches that exist locally but have been removed from the remote, for example after a squash merge.

**Comment by BernieWhite** [comment]
They are marked as `[gone]` by the local git client when using `git branch -v`.

**Comment by joaomoreno** [comment]
Right. The dropdown will show both local branches and remote branches (starting with `origin/`). When you prune, the `origin/` ones won't show anymore. But if you still have local branches which (used to) track those remote branches, then we must still show them since they still exist locally.

What you should do instead of filtering this at the tool level, you should simply clean your local branches. Something like this: https://stackoverflow.com/a/17029936/261019

**Comment by BernieWhite** [comment]
@joaomoreno Yeah, I got it. Actually I use PowerShell and am more then capable of cleaning local branches. The point is the drop down list can get quite noisy so the feature is to help reduce some of that noise.
