### ISSUE TITLE
Sometimes SVG icons do not show up on Windows 7

### ISSUE THREAD

**Issue by MikeVan1234** [Microsoft/vscode#7839]
- VSCode Version: 1.2.1
- OS Version: Win7

After installing latest, I noticed many items seen on site documentation are missing in my installed. I have now realized they are there I just can't see them. I am using the out of the box set up. Attached is a shot showing the debug menu (top), apparently there are other items along the top, and I have one or more break points set that also can’t be seen. How do I resolve this?

**Updated**: Missed this, at following Link Ref '_Icons are missing_':
-  https://code.visualstudio.com/docs/setup/windows
-  C:>REG ADD HKCR\.svg /f /v "Content Type" /t REG_SZ /d image/svg+xml

![vscodeissues](https://cloud.githubusercontent.com/assets/20009416/16169161/b2190c2e-34f1-11e6-9590-e68543aacba6.gif)

**Comment by dbaeumer** [comment]
@joaomoreno starting with you since it sounds like an update bug.

**Comment by joaomoreno** [comment]
cc @bpasero @alexandrudima a little help here? It seems the all the user's svgs are missing from the workbench.

**Comment by bpasero** [comment]
Yes, very likely the SVG issue (https://code.visualstudio.com/docs/setup/windows#_next-steps). The activity bar shows its icons because they are inlined as data URIs.

**Comment by alexandrudima** [comment]
Maybe we could inline our svgs in the css. I do that for monaco-editor

**Comment by bpasero** [comment]
Yes, we should inline all SVGs if possible. I also noticed once that Chrome would decide to load the images from disk later after the workbench was opened so it felt a lot like a webpage opening...

@alexandrudima if you did this already for the standalone editor, can you give pointers how to hook it into the workbench?

**Comment by alexandrudima** [comment]
Sure:
*1.* Go through all our CSS and remove duplicate references to the same svg file
 * e.g. https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/media/debugViewlet.css#L268
and https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/media/debugViewlet.css#L352
 * our code is littered with this everywhere

*2.* Go to [`gulpfile.common.js`](https://github.com/Microsoft/vscode/blob/master/build/gulpfile.common.js#L40) and add `result['vs/css'] = { inlineResources: true };`

When bundling, due to step number 2, all the duplicate references will be printed. They are in the low hundreds.

**Comment by bpasero** [comment]
@alexandrudima well what if actually we want to use the same SVG in 2 places in the CSS? Would be nice if we could define variables with data URLs but I think that is not possible.

**Comment by alexandrudima** [comment]
It would definitely work even today. It's just that the resulting css file size will be a lot larger for no good reason. On the bright side, I handled the duplicates in the CSS that is dragged in the monaco-editor :).

**Comment by bpasero** [comment]
@alexandrudima oh I see, of course we can solve this by tweaking the CSS selectors 👍

**Comment by bpasero** [comment]
Filed https://github.com/Microsoft/vscode/issues/8516

**Comment by bpasero** [comment]
We are now inlining SVG images during build time.
