### ISSUE TITLE
Very slow file search in huge codebase

### ISSUE THREAD

**Issue by Sharundaar** [microsoft/vscode#78401]
Since the last update (1.36.1), the file search have become insanely slow. Reverting VSCode to an earlier version (1.34 in my case) seems to fix the issue, so I assume the behavior have been introduced in 1.35 or 1.36.

I'm working on a very big codebase with 10k+ files that are stored locally on my hard drive (no connection or ftp shenanigans)

I've been able to reproduce the issue at large on my team (at least 5-6 different machines), so I don't think this is hardware related.

I can't really show the issue because of NDA reasons, but I just hit CTRL+P and start typing a file name, VSCode hangs for a while and finally get the files. In the older version it would have been instantaneous.

I'm on Windows 10.

If you need any additional details I'll see if I can get a localized repro environment going, thanks !

**Comment by Sharundaar** [comment]
I found a quick way to repro this, create an empty folder and past this .bat inside :

```
@echo off
for /L %%I IN (1,1,10000) DO (echo Hello>f_%%I.txt)
```

Running it will generate 10000 files named f_1 through f_10000, with VSCode 1.36.1 it's lagging a lot, but trying it with 1.34 it works like a charm.

**Comment by roblourens** [comment]
Can you try downloading the Insiders' build and tell me whether it happens there? https://code.visualstudio.com/insiders

**Comment by Sharundaar** [comment]
Looks alright on the Insiders version, it's still not as responsive as the 1.34 version though I feel but I need to make more tests to see if it's in my head or not. Also I need to test in a real environment, I'll keep you posted.

**Comment by roblourens** [comment]
Thanks for pointing out that this happens with lots of files at the top level. There is at least one real issue here.

@bpasero I see an issue after https://github.com/microsoft/vscode/commit/4b3340352fd68aa302e2686ec9b82da0dfb8ca15, we call `fileService.exists` on a folder containing 10000 files, which tries to stat all of them. That's not necessary, how can I avoid that?

**Comment by bpasero** [comment]
@roblourens that is unfortunate, I was not aware it had these implications. 

Unfortunately there is no API in file system providers to check if a file exists or not, I have to call `stat` (@jrieken can maybe further comment on whether we could introduce an optimization where we have a way to ask for existence without needing to stat).

You can revert my change, but that means we are not fit for remote scenarios in that particular case.

**Comment by jrieken** [comment]
> @jrieken can maybe further comment on whether we could introduce an optimization where we have a way to ask for existence without needing to stat)

There is only `stat` because node deprecated `exists` in favour of `stat` or `access` (https://nodejs.org/dist/latest-v12.x/docs/api/fs.html#fs_fs_exists_path_callback). Not sure if the latter is faster but if then we can consider adding something like `access`

**Comment by bpasero** [comment]
> Not sure if the latter is faster but if then we can consider adding something like access

@jrieken my understanding is that the origin of this issue is the fact that we call `provider.stat` and that the previous `fs.exists` was faster. I think it is reasonable that stat does a lot more compared to `exists/access` given it resolves metadata too. 

Maybe @roblourens could validate that theory if its really that or some other overhead we got. You can easily make our `FileService#exists()` method call into provider.stat directly without going through the `resolve` method we have. If you have a CPU profile that would even be better to see if the issue is coming from the use of `stat` or from the overhead of that method.

**Comment by bpasero** [comment]
@roblourens I pushed a [change](https://github.com/microsoft/vscode/commit/122615efeb30d205e11523007b73ca5c2abb136e) to make `IFileService#exists()` go directly to `provider.stat`. That is as fast as I can make it without introducing new file system provider capabilities. Can you check it out from `master`?

**Comment by roblourens** [comment]
Much better, thanks!
