### ISSUE TITLE
code -r true.txt fails

### ISSUE THREAD

**Issue by azdavis** [microsoft/vscode#78440]
Issue Type: <b>Bug</b>

1. open a terminal
2. type `code -r true.txt`

expected: vscode is activated and the file true.txt is opened

actual: vscode is activated, but the file true.txt is not opened

VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|16.00GB (2.65GB free)|
|Process Argv|-r true.txt|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
better-toml|bun|0.3.2
transformer|dak|1.6.0
prettier-vscode|esb|1.9.0
sml|fre|0.0.18
Go|ms-|0.11.4
rust|rus|0.6.1
rewrap|stk|1.9.1
code-spell-checker|str|1.7.17
change-case|wma|1.0.0
vscode-proto3|zxh|0.3.0

</details>

**Comment by bpasero** [comment]
@joaomoreno didn't we once have this issue where our CLI parser would choke over flags that have reserved JS words in them, as in this case "true"? I think we have this issue with numbers before if I remember correctly.

Anyhow, up for grab if someone wants to help out.

**Comment by skprabhanjan** [comment]
@bpasero , I would like to take this up.
Some code pointers would be helpful , Thanks :)

**Comment by bpasero** [comment]
@skprabhanjan thanks, a good start would be to try to reproduce running out of sources, I assume you are setup. Then I wonder why the second instance that is opening does not contain the proper environment from the command line (sends it over to the first instance [here](https://github.com/Microsoft/vscode/blob/41df3bcb7cec1ae80b11482207bb458a54f4cb19/src/vs/code/electron-main/main.ts#L299)).

**Comment by skprabhanjan** [comment]
Hi @bpasero , After debugging for long time this is what I found

-  This is where the problem is -> parsing the args [here](https://github.com/microsoft/vscode/blob/master/src/vs/platform/environment/node/argv.ts#L126)
- According to the npm library doc of [minimist](https://www.npmjs.com/package/minimist) , The `opts.boolean` should be used with double hyphen and clearly it is stated that single hyphen are not treated as boolean ( Which is the type used for `reuse-window` arg)
- The same issue occurs for ( `code -n true.txt` which is Force to open a new window. )
- The **ideal usage** should be `code --r true.txt` and it works perfectly ( As well as `code --reuse-window true.txt`)
- `code -r nottrue.txt` ( there is something happening in the call to minimist which does not return proper args when the txt file name is true )

So please go through this and get me know if this makes sense ( Not sure if we need to update the text that comes up when we type `code --help` or should we parse the args differently to make sure `code -r` works )

**Comment by bpasero** [comment]
@joaomoreno thoughts on https://github.com/microsoft/vscode/issues/78440#issuecomment-518653151 ?

**Comment by joaomoreno** [comment]
@skprabhanjan We can't force people to use `--r true.txt` and that is far from ideal usage, since `r` is a single dash boolean option, it should never be used with double dashes.

This is a bug on minimist. I've submitted a PR to fix it https://github.com/substack/minimist/pull/138, but since minimist seems dead I just published our own version of it: https://www.npmjs.com/package/vscode-minimist.

I've also added a test for this: https://github.com/microsoft/vscode/blob/56e836965104c8b76f65a76409c02cb44389e728/src/vs/platform/environment/test/node/environmentService.test.ts#L56

**Comment by skprabhanjan** [comment]
@joaomoreno , That regex fix was amazing , Cheers :)
