### ISSUE TITLE
Validate all editors in stacks after relaunch

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#785]
**Repro**

1. Open vscode on a folder
2. Open and edit some files (to add to working files)
3. Close vscode
4. Delete the working files
5. Relaunch vscode

**Expected**

The deleted files are not in working files

**Actual**

The deleted files are in working files, clicking them will give an unable to read error:

![s](https://cloud.githubusercontent.com/assets/2193314/11454798/d380d892-95f0-11e5-858b-e5100f2e68d8.png)

**Comment by bpasero** [comment]
@Tyriar given the tabs work would you expect all your tabs to go away on a restart if some files are gone? maybe they are only briefly gone because you did a branch switch. I think it would be harsh to force this onto the user (e.g. destroy his careful tab layout).

I think we should not tamper with the tabs arrangement the user did.

**Comment by Tyriar** [comment]
@bpasero seems reasonable to keep this behavior then.

It's not too big of an issue for me anymore since I can just clear them up using <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>w</kbd> then <kbd>esc</kbd> to dismiss the errors. It was a pain before I discovered `workbench.files.action.closeAllFiles` which is probably the default now?
