### ISSUE TITLE
Make Terminal.onDidWriteData a global event

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#78502]
This has been in for several months and is used by remote extensions:

```ts
	export interface Terminal {
		/**
		 * Fires when the terminal's pty slave pseudo-device is written to. In other words, this
		 * provides access to the raw data stream from the process running within the terminal,
		 * including VT sequences.
		 */
		readonly onDidWriteData: Event<string>;
	}
```

I might tweak the wording to indicate it will fire for extension/pty terminals as well.

**Comment by Tyriar** [comment]
Plan from meeting: Make it a global event and keep in proposed.

**Comment by roblourens** [comment]
It has worked fine for me

**Comment by jrieken** [comment]
Summary of the discussion during the API sync

* the current proposal violated the "public object, global event rule", see: https://github.com/microsoft/vscode/wiki/Extension-API-guidelines#global-events
* the private event approach was selected because there are strong performance concerns that forwarding events for all terminals is too expensive.
* however, users like LS, need to listen to all terminals so that they can be replicated,
* which means subscribing to all "private" events of all terminals is like a global events (and also rules out the possibility to only allow creators of terminals to listen)

Going forward

* the API will change to be a global event
* the API will likely stay proposed forever (which gives us more control)
* the API needs a fast and smart implementation
* we should gather telemetry data about how much data during a terminal session is usually produced (real world case)

**Comment by Tyriar** [comment]
Verifier: Try use the new API and make sure it works for terminals created before it was registered and after it was registered.

**Comment by Tyriar** [comment]
Update: This API is still proposed but we don't intent on promoting it to stable.
