### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#7854]
- [x] win - @alexandrudima 
- [x] mac - @isidorn 
- [x] linux - @Tyriar 

Enable tabs by setting the `workbench.editor.showTabs` setting to `true`. Verify:
* you see tabs for each opened editor and the active tab is always revealed and stands out from others
* you can interact with a tab from its context menu
* you can move tabs around with drag and drop
* when not all tabs can fit the available space you can scroll with the mouse to reveal all and the overflow action in the right corner enables and shows all opened tabs in a list
* dirty editors always show their indicator even when the tab is not active
* tabs are being reused as long as the editor inside is a preview editor (showing in italics)
* you can change where editors open by configuring `workbench.editor.openPositioning`
* you can disable preview editors by changing `workbench.editor.enablePreview` or `workbench.editor.enablePreviewFromQuickOpen`
* verify keyboard accessibility on tabs
* verify screen reader on tabs
* verify tabs are looking good in all themes including high contrast theme

**Comment by tkelman** [comment]
This is really wonderful so far. Is the state of which tabs are open saved somewhere persistent? Would be fantastic if the previously-open set of tabs could be reopened automatically without having to manually click through "Open Recent" for each one after restarting Code.

**Comment by bpasero** [comment]
@tkelman yes all view state is stored and restored when you restart as long as you open a folder with VS Code. We never stored any view state when you open Code empty and restart.

**Comment by tkelman** [comment]
Ah I see. I imagine many of us used to tabs-only workflows may not really notice the "open folder" so if we only have individual files opened in different tabs, does that count as what you called "empty"?

**Comment by bpasero** [comment]
@tkelman yes, we only associate view state with an opened folder. this is independent from using tabs or not.

**Comment by bgse** [comment]
- (...) the active tab is always revealed and stands out from others
- verify tabs are looking good in all themes including high contrast theme

Not sure how to answer these questions, personally I'd say tabs would need to stand out a little more in all color themes.

While it does work as intended, I find myself squinting my eyes a lot trying to make out tab boundaries.

Active tab is easy due to the "close" button (high contrast theme makes it stand out perfectly btw), but I feel that color differences between active/inactive need to be a little more pronounced, especially in the dark color themes.

Since touching things is often easier than listening to endless ramblings, do this:

1) set color theme "default light"
2) open a few tabs
3) switch color theme to "quiet light"
4) compare how easy it is to make out different tabs

Imho, "quiet light" is just about perfect, subtle and good-looking but yet easily discernable, while "default light" has some issues where active/inactive is pretty much no difference in visual appearance except the close button.

**Comment by bpasero** [comment]
Yeah I do agree that the colors needs more tweaking, we have this captured in https://github.com/Microsoft/vscode/issues/7649 and https://github.com/Microsoft/vscode/issues/7648

**Comment by Tyriar** [comment]
Didn't get to this today, will pick it up first thing tomorrow.

**Comment by alexandrudima** [comment]
:+1: `workbench.editor.openPositioning` works

**Comment by alexandrudima** [comment]
:+1: `workbench.editor.enablePreview` works
