### ISSUE TITLE
VS code search functionality freezes the screen

### ISSUE THREAD

**Issue by adharwadkar** [microsoft/vscode#78611]
Whenever I try to search anything,  vs code gets stuck in the middle of the search and the only option is Restart, it is extremely annoying, I am not even using beta version of the editor.

**Comment by roblourens** [comment]
Does your search return matches on extremely long lines? There is an issue with this currently.

**Comment by adharwadkar** [comment]
Hi,
Thank you for the quick response.
No, I am facing the issue while searching as small as a function name.

**Comment by roblourens** [comment]
Can you share a screenshot, or your repo?

**Comment by adharwadkar** [comment]
I can not share repo, but what exactly are you looking for in screenshot?
it is a typical Mvp application and everything was working fine one month back.

**Comment by jayden2** [comment]
Having same issue where searching will freeze VSCode and cause it to crash. Happening on a range of different sized projects.

```
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-55-generic
```

**Comment by jasonelston** [comment]
FWIW, it looks like this might be due to a change that's broken the default exclude list for searching. In a reasonable size react project that has a `build` folder and `node_modules`, searching for items shows results from both of those locations even though `build` is excluded in `.gitignore` and `node_modules` is excluded in `.gitignore` and 

In my project, the default excludes are not being honoured and neither is the `.gitignore` exclude option. I have to manually add them the search file exclusions.

![image](https://user-images.githubusercontent.com/436112/62699064-00684a80-ba22-11e9-85b8-9794126e1738.png)

---

![image](https://user-images.githubusercontent.com/436112/62699157-3efe0500-ba22-11e9-81f3-29323e7a70c7.png)

---

![image](https://user-images.githubusercontent.com/436112/62699179-4b825d80-ba22-11e9-9d7a-2c4b6d951a98.png)

**Comment by roblourens** [comment]
@jasonelston your screenshot shows that you have disabled the default excludes, click the button in the exclude input box to reenable them.

**Comment by jasonelston** [comment]
@roblourens Are you referring to the search excludes in the top two images (as opposed to the editor settings)? 

If there's exclude paths in the exclude field, the selector on the right doesn't make any difference - the search result set is the same in both those images. If I remove a string the results are then included in the search set. The exclude button does not seem to have an effect.

**Comment by roblourens** [comment]
Please see if anything in https://github.com/microsoft/vscode/wiki/Search-Issues#search-including-too-many-results helps and share your search logs, or the project if possible.

**Comment by fergalmoran** [comment]
For people who land here via search - I had the same issue so something definitely changed here recently. @roblourens is correct, this needs to be deselected (as per @jasonelston's screen shot)

![image](https://user-images.githubusercontent.com/309139/63808098-14afb100-c917-11e9-934e-61151bf178c6.png)
