### ISSUE TITLE
Show/hide open editors and/or tabs

### ISSUE THREAD

**Issue by eyalsk** [Microsoft/vscode#7865]
As previously discussed here #224 it was mentioned that we would have the ability to opt-in/out to/from both tabs and open editors but as far as I can see in the latest insider build there's only an option to show/hide tabs.

Is it something you're still working on? what's the progress on that?

**Comment by bpasero** [comment]
That is possible by configuring `"explorer.openEditors.visible": 0`

**Comment by eyalsk** [comment]
Okay thanks.

**Comment by MickeySegal** [comment]
It should be pointed out that the value of hiding of Open Editors is that when one is clicking on files in the current Project, since Open Editors is above the project, the list of files in the project keeps moving down.  If one is trying to click on multiple files in the project, the next file to click will move down as a result of clicking the previous files, and one can inadvertently click the wrong file.  One can avoid this problem by hiding Open Editors and relying just on the tabs at the top.

**Comment by canadaduane** [comment]
Note to future readers: the above setting only affects the explorer when a folder is open; it does NOT remove the "Open Editors" section of the sidebar when a loose set of files is open. See https://github.com/Microsoft/vscode-docs/commit/0385daf159043a762d6f2cd00c8a312fb83d5d29

**Comment by thomthom** [comment]
@MickeySegal - exactly that! Open Editors content shifting the content of the folder view below. Glad I finally found `"explorer.openEditors.visible": 0`. It doesn't appear under Default Settings so I wasn't able to discover it.

I really wish it could be permanently turned off though - even when you don't open a folder. Between the tabs and Ctrl+P I don't use the Open Editors panel at all - just gets in the way.
