### ISSUE TITLE
Add contextual help menu like jupyter lab

### ISSUE THREAD

**Issue by RensDimmendaal** [microsoft/vscode#78697]
In jupyter lab you can add a tab next to your editor which shows the function signature of the function you're currently writing / the one you clicked on latest. Pycharm has similar feature as well. I would love to be able to use it in vscode. 

Example:
![image](https://user-images.githubusercontent.com/9828683/62698384-4cdd6700-b9dd-11e9-94bb-47a7f50f0b82.png)

**Comment by hediet** [comment]
Function signatures are already shown in VS Code as tooltip: 
![image](https://user-images.githubusercontent.com/2931520/62701595-03911580-b9e5-11e9-91c6-8547bed64605.png)

If you want to have a larger window for that like in your screenshot, I think that should be provided through an extension rather than by VS Code itself.
The extension api certainly is extensive enough to implement that quickly (given that you already have a way to get the contextual help text).
