### ISSUE TITLE
Double click to highlight word should behave the same across all languages

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#787]
Might be considered a feature, but I find it disorienting how double click behaves differently in different languages. Could this be a setting to highlight a symbol/word on double click?

An example, double clicking `some-class` in the HTML below will highlight `some-class`

```html
<div class="some-class">
```

However double clicking `some-class` in the JavaScript below will highlight `some`, `-` or `class` depending on where you clicked.

```js
var x = document.querySelector('.some-class');
```

**Comment by alexandrudima** [comment]
@Tyriar 
The word highlighting is delegated to each language so it can have semantic meaning in languages that support it. Otherwise, if a language does not implement such semantic word highlighting, we fall back to a "non-semantic" one that uses the word under the cursor and highlights other occurences of the same word. Also notable, the word definition is contributed and varies across languages.

Here is a language that implements semantic word highlighting:
![image](https://cloud.githubusercontent.com/assets/5047891/11467920/c7ea82b0-974b-11e5-991c-88744110e891.png)

Here is the same text under plainText:
![image](https://cloud.githubusercontent.com/assets/5047891/11467946/0fa0ba5c-974c-11e5-82ee-745364eb9e75.png)

**Comment by Tyriar** [comment]
@alexandrudima Could there be an option to not use the language's definition of a word for the double-click highlighting?

**Comment by alexandrudima** [comment]
We have actually implemented this in February, and it is controlled by `editor.wordSeparators` (across all languages)

**Comment by Tyriar** [comment]
Verified: Added ``"editor.wordSeparators": "`~!@#$%^&*()=+[{]}\\|;:'\",.<>/?"`` and checked that `some-class` double click highlight was consistent over JS and CSS.

@alexandrudima just to confirm, this is no longer delegated to the language service and is control totally by the `editor.wordSeparators` value?

**Comment by alexandrudima** [comment]
@Tyriar `editor.wordSeparators` is honored by double clicking and word navigation (things that didn't go to the language service, but were using the language word definition regex).

The highlighting is delegated to the language service, since languages can do semantic occurrence highlighting.

**Comment by Tyriar** [comment]
Thanks for the clarification :)
