### ISSUE TITLE
"zoom in" vscode key mapping needs to be [Ctrl +] instead of [Ctrl =]

### ISSUE THREAD

**Issue by LarryWeiss** [Microsoft/vscode#7872]
- VSCode Version:1.2.1
- OS Version: Windows 7

Steps to Reproduce:

1. start a vscode edit session
2. use F1 with search term "zoom"

You see a mapping of [Crtl =] to zoom in.

It would be more consistent if this was mapped to [Ctrl +]
For example, zoom out is mapped to [Ctrl -]

Most keyboards have + and = on the same key-cap, but not all.

**Comment by bgse** [comment]
Bit confused here, zooming functions are mapped [Ctrl +] and [Ctrl -] out of the box for me, both on Linux and Windows10, german keyboard.

**Comment by coreh** [comment]
Ideally it should say `⌘+` on the menu, and be bound to both that and `⌘=`, that way you don't need to use shift.

**Comment by LarryWeiss** [comment]
Look at my "steps to reproduce" above.  I get   [Ctrl =]   for "zoom in"

Key mappings:
{ "key": "ctrl+=",                "command": "workbench.action.zoomIn" },
{ "key": "ctrl+-",                "command": "workbench.action.zoomOut" },

It should be
{ "key": "ctrl++",                "command": "workbench.action.zoomIn" },

**Comment by bgse** [comment]
@LarryWeiss With the german keyboard, while I do have the same default keymapping configuration as you have, I get the following using your steps:

![vscode_zoom](https://cloud.githubusercontent.com/assets/8385202/16299530/20ac9640-393b-11e6-83ee-0980e1c7877c.png)

The actual working keymapping is [Ctrl +], as advertised in the menus and the command palette.

This is imho the proper mapping for the german keyboard, since [Ctrl =] would require a very awkward shift-key combination.

**Comment by alexandrudima** [comment]
Does the doc page provide a good enough explanation? https://code.visualstudio.com/docs/customization/keybindings#_keyboard-layouts

If not, I can provide additional details
