### ISSUE TITLE
Fix failing webview integration tests

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#78729]
https://monacotools.visualstudio.com/Monaco/_build/results?buildId=54036

```
  1) Webview tests webviews should be able to send and receive messages:‌
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves.‌
  

  2) Webview tests webviews should have real view column after they are created, #56097:‌
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves.‌
```

Commenting out for now to get back to green build.

**Comment by octref** [comment]
Btw I manually tested first test with a sample extension. Seems to work fine for me.

**Comment by mjbvz** [comment]
@joaomoreno @bpasero Do you know what commit first broke this because I have not touched any code in two weeks.

**Comment by sbatten** [comment]
@mjbvz it happened because of enabling grid layout again. For some reason grid layout is not playing nicely. Grid layout is now disabled again, but could use some help investigating so we can turn it back on. When testing with the markdown preview, it seems the sizing and position of the webview in the editor are broken.

**Comment by mjbvz** [comment]
Thanks. Marking as important as webviews don't render at all when using the new grid layout
