### ISSUE TITLE
Nested Launch Configurations

### ISSUE THREAD

**Issue by jd-carroll** [Microsoft/vscode#7875]
Would it be possible to have VS Code scan for any child `.vscode` folders or other files named `launch.json` and include those in the debug configuration available?  I have a git project where there are many sub-modules and I would like to have the debug configuration contained in each sub-module.

I am happy to contribute this myself if someone could point me in the right direction.
(I think looking for all files named `launch.json` would be easiest/cleanest)

**Comment by isidorn** [comment]
There are some limitations in this approach - the user can not have an unrelated launch.json file anywhere as it will screw up the debug configurations.

If we were to do this we should do the same for tasks.json - as it also lives in the .vscode folder and it should have the same charateristics.

Both task service and the debug service use the configuration service here 
https://github.com/Microsoft/vscode/blob/master/src/vs/platform/configuration/common/configurationService.ts#L104
How to change the configuration service such that it would look for launch.json or tasks.json anywhere I am not completelty sure.

Due to the reasons above I am against this feature.
@bpasero @dbaeumer opinions welcome

**Comment by jd-carroll** [comment]
@isidorn How will this screw up the debug configurations? The clean way to implement this would be to also add a new variable like ${file-location} for use in the debug configurations. That way your configs are always relative to the location of the launch.json and not the workspace root.

**Comment by jcrben** [comment]
Somewhat similar: I'd like to put my `.vscode` file under a different file name or nested in a different folder, as I can ignore that folder with a global git config and not to have deal with it getting committed a shared repository. Is there a pattern for handling this? see also https://stackoverflow.com/questions/42631728/user-specific-workspace-settings-in-vs-code

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!

**Comment by jcrben** [comment]
You might consider a label to convey that message as well. Where I work we use the term icebox.
