### ISSUE TITLE
Snippet Variable Unix Timestamp

### ISSUE THREAD

**Issue by WORMSS** [microsoft/vscode#78798]
I would like a new Snippet Variable for time to be added to the variables listed here.
https://code.visualstudio.com/docs/editor/userdefinedsnippets

Something like `CURRENT_UNIX_SECONDS` or `CURRENT_SECONDS_UNIX`
Number of seconds since the unix epoch.

**Comment by AmmarHasan** [comment]
Nice. I would like to work on that

**Comment by SneakyFish5** [comment]
I've got a commit here that works on my local build. Does this look good to you? I just get the milliseconds since epoch using `new Date().getTime()` and divide by 1,000. However I use Math.round to round to the nearest integer so there aren't a bunch of decimals. If that's what you wanted, I'll go ahead and open the PR, but just wanted to share it for discussion before I go ahead and do that.

https://github.com/SneakyFish5/vscode/commit/acf6b3478ed6cd2726ccf7d320700987950ab6b5

**Comment by WORMSS** [comment]
@sneakyfish5 I thought `Date.now()` was the normal way of doing that?

**Comment by SneakyFish5** [comment]
Ah you are right, completely forgot about `Date.now()`. Definitely a cleaner look, and I've also changed round to floor.  The new commit is [here](https://github.com/SneakyFish5/vscode/commit/cafd7658a7835cf7cdf2a2f6b0391e4845f0b3aa) and local build works perfect. Was there anything else that crossed your mind?

**Comment by WORMSS** [comment]
@SneakyFish5 @jrieken tested this is a Snippet in Insiders edition today. Works as expected. Thank you very much.
