### ISSUE TITLE
1.3.0-insider breaks alt+left/right word skipping

### ISSUE THREAD

**Issue by CreepGin** [Microsoft/vscode#7883]
- VSCode Version: 1.3.0-insider
- OS Version: OS X El Capitan 10.11.3

Steps to Reproduce:

1. Create/open an empty file
2. Type the text "Hello World"
3. While the cursor is at the end of the line, press Alt-Left
4. Expected behavior is that the cursor will jump to the left of the letter 'W'
5. Actual behavior is that the cursor just jumps to the left of the letter 'd'

**Comment by yisibl** [comment]
Because now this shortcut into the text to move around(https://github.com/Microsoft/vscode/pull/6887)

I have said in issue(https://github.com/Microsoft/vscode/issues/5251), do not change the system level of general shortcuts. This will The loss outweighs the gain.

I think <kbd>control</kbd> + <kbd>cmd</kbd> + <kbd>←/→</kbd> is better(Atom 1.8). 

@alexandrudima @kisstkondoros Please change the shortcut key 😭 .

**Comment by yisibl** [comment]
You can modify the shortcut key configuration, this is a temporary solution.

    {
        "key": "alt+left",
        "command": "cursorWordStartLeft",
        "when": "!editorHasSelection && editorTextFocus"
    },
    {
        "key": "alt+right",
        "command": "cursorWordEndRight",
        "when": "!editorHasSelection && editorTextFocus"
    }

**Comment by alexandrudima** [comment]
Sorry about that, I merged a PR that overwrites the word navigation keys. Fixed in f81582e1925161700751638e26e85bd6e0048745

**Comment by CreepGin** [comment]
Went to bed, woke up, and there's a new vscode update. Problem fixed. Loving your iteration speed.
