### ISSUE TITLE
CLI accepts incorrect options

### ISSUE THREAD

**Issue by sirmspencer** [microsoft/vscode#78831]
- VSCode Version: 1.36.1
- OS Version: Kubuntu 19.04

Steps to Reproduce:

1. open terminal
2. type `code --disable-extentions` (notice the typo) or `code --disable-extension ms-python` (again not valid)  or  `code -lkoiukasldf ` (to be dramatic)
3. VSCode launched anyway with no warning that the option is invalid.

Does this issue occur when all extensions are disabled?: N/A

**Comment by sirmspencer** [comment]
A part 2, the correct way to disable an extension `code --disable-extension ms-python.python` also launces VSCode with out a sucess message.

**Comment by skprabhanjan** [comment]
@joaomoreno , I can try this !

**Comment by skprabhanjan** [comment]
@joaomoreno , there is one more Opts that can be sent to `minimist` called `unknown`,  a function which gets called when unknown options are passed. I am not able to find a proper way to use this in order to not call startup [here](https://github.com/microsoft/vscode/blob/master/src/vs/code/electron-main/main.ts#L85)
The only option I could think of is to return null when this function is called but I need to change the return type to `ParsedArgs | null` which would require more type changes in many other places. ( I tried doing this but requires lot of other changes)
Please let me know what can be done and thoughts on this :)

**Comment by skprabhanjan** [comment]
Hi @joaomoreno , I tried doing this with Opts.unknown in minimist which states the following
/**
		 * A function which is invoked with a command line parameter not defined in the opts
		 * configuration object. If the function returns false, the unknown option is not added to argv
		 */

But it is getting called for options which has values associated with it ( For example `-s` and `-v` does not invoke that function but `-abcd` will invoke that function , Until here it is fine but if I use some arg which accepts value ( like -r or --resuse-window ) then it will still call that function )
I guess this is a bug and still not fixed ( Reported [here](https://github.com/substack/minimist/issues/86) )

Please let me know what should be done here and help me here , Thanks :)

**Comment by skprabhanjan** [comment]
@joaomoreno , You had a chance to look at this ?

**Comment by aeschli** [comment]
There's now a warning when you use unknown options.
