### ISSUE TITLE
First hover is no longer syntax-highlighted again

### ISSUE THREAD

**Issue by Gama11** [microsoft/vscode#78946]
Recently, I've been noticing the exact same issue as described in https://github.com/microsoft/vscode/issues/53723 again. Possibly this has regressed in the 1.37 release.

![](https://i.imgur.com/N1xVG1x.gif)

**Comment by alexr00** [comment]
Leaving for @aeschli.

**Comment by aeschli** [comment]
I'm able to reproduce with the haxe sample.

@alexandrudima I believe the problem is here: https://github.com/microsoft/vscode/blob/b0d58e4fe6327250ef912a2ff8ea7e07251a54c5/src/vs/workbench/services/textMate/browser/abstractTextMateService.ts#L231

The _tokenizersRegistrations promise is only registered once the _getOrCreateGrammarFactory is completed. It also needs to go in the promise.

I can do the fix, if thats ok for you.

**Comment by alexandrudima** [comment]
@aeschli I think this was a regressions from my recent refactorings. I'd like to understand it...

**Comment by alexandrudima** [comment]
Repro steps:
1. Open a fresh VS Code with a `.js` file.
2. Be sure to not open by accident a TS file before or in parallel
3. Hover over something in the `.js` file
4. The first hover is not colored:
![image](https://user-images.githubusercontent.com/5047891/63927880-de754d00-ca4e-11e9-8d39-961bb6c9184e.png)
