### ISSUE TITLE
Allow to provide task definitions through DebugConfiguration.preLaunchTask

### ISSUE THREAD

**Issue by g-arjones** [microsoft/vscode#78948]
This is a follow-up from: #59337 

The goal is to provide a simple mechanism for a `DebugConfigurationProvider` to create task definitions and use them as prelaunch tasks. A `TaskProvider` would then be able to pick those up and fill the missing bits. Currently, there is no way to gather data from debugging configurations provided by the user through launch.json and pass it to a task provider so that prelaunch tasks could be created dynamically off the debug configuration.

I will be glad to hear workarounds as well..

**Comment by g-arjones** [comment]
Not a duplicate.

**Comment by isidorn** [comment]
fyi @weinand @alexr00

**Comment by weinand** [comment]
A `TaskProvider` can easily access the current debug configuration by registering for the start of a debug session via the `onDidStartDebugSession` API. 
@g-arjones have you tried this?

**Comment by g-arjones** [comment]
No, because my understanding was that the preLaunchtask is launched before the session starts and that onDidStartDebugSession is called after. My goal is to create a task to be used as a prelaunchTask. Am I missing something? @weinand

**Comment by adriancostin6** [comment]
> No, because my understanding was that the preLaunchtask is launched before the session starts and that onDidStartDebugSession is called after. My goal is to create a task to be used as a prelaunchTask. Am I missing something? @weinand

Hello @g-arjones, did you manage to do this? I want to do the same thing now and I am stuck. I want to define a preLaunchTask without having to write a tasks.json file, and would like the extension I write to register this automatically. I am not sure whether this is possible. Any insights?

**Comment by adriancostin6** [comment]
> A `TaskProvider` can easily access the current debug configuration by registering for the start of a debug session via the `onDidStartDebugSession` API. @g-arjones have you tried this?

@weinand Could you please elaborate on this, if you have the time? 

I am trying to start a debugging session by first running a `gdbserver` instance locally, and then connecting to it with a client. I am doing this to bypass a limitation on Cygwin/MinGW where `gdb` does not bind breakpoints as it [cannot stop a running process](https://code.visualstudio.com/docs/cpp/cpp-debug#_known-limitations), but `gdbserver` on the other hand works just fine. 

I would like to abstract this away from the users of my extension so they do not have to define a task for it in the `tasks.json` file, and register it as a preLaunchTask in `launch.json`. The behavior I am seeking is for the user to hit the debug button, a server to start automatically on a local port and then have a client attach to it, all in one go. 

The solutions I have explored so far are:
- registering a custom task, with a task provider, then somehow specifying it as a preLaunchTask for my debug configuration
- registering a custom task with a task provider, and adding an extra step, for the user to run the task inside vscode (not ideal, same as starting a debug server from the command line as it involves an extra step)
- define a tasks.json file with the preLaunchTask (unlikely that people will do this, rather than complain)
