### ISSUE TITLE
Horrible new left bar icons on version 1.37

### ISSUE THREAD

**Issue by dmvvilela** [microsoft/vscode#78971]
OMG! This left bar icons is ugly af.. This is a feature request so that AT LEAST you give us an option to use the last version icons.. 

I mean the left bar icons (explorer, search, debugger, extensios, etc)..

Really.. It was awesome before so i have two questions.
1. WHY would you change that and
2. HOW COME you decided on these new ones.. like really?

Thanks.. That would be all. Love vs code still S2

**Comment by dmvvilela** [comment]
The config icon is also horrible.. Maybe this squared icons work on Windows.. But at least here on a mac it is HORRIBLE!!!

**Comment by gjsjohnmurray** [comment]
Per https://github.com/microsoft/vscode/issues/78748#issuecomment-519989407 the only way back at the moment is to revert to 1.36.1

More conversation is going on at #8017 despite that already being closed.

Open issue #78024 is collecting upvotes specifically about the code folding/unfolding icons.

@dmvvilela maybe focus your input on one of those rather than the new one you just opened?

**Comment by dmvvilela** [comment]
Yeah, i saw about those icons, but did not see about these ones, so i opened this :) But really.. why change a winning team?

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode/issues/78875#issuecomment-520373220 gives a pointer.

**Comment by misolori** [comment]
Please leave comments regarding the new icons in https://github.com/microsoft/vscode/issues/8017 and please see https://github.com/microsoft/vscode/issues/8017#issuecomment-476044257 for details on why we made the change.
