### ISSUE TITLE
Ability to contribute context menu entries for Terminal

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#79034]
I want to contribute menu items for Terminal. Doesn't look like it's possible now:

https://code.visualstudio.com/api/references/contribution-points#contributes.menus

**Comment by Tyriar** [comment]
I guess `terminal/context` makes sense given the other keys

**Comment by Tyriar** [comment]
Adding to October to discuss, this won't be implemented in October.

**Comment by Tyriar** [comment]
Brought up in API sync today, approved to go ahead for a proposed API using `terminal/context` and passing the underlying `Terminal` object to the callback.

**Comment by nickyhajal** [comment]
Looking forward to using this for an extension, thanks for moving it forward.

Might it be possible to include context menu contribution points for `problems/context`, `output/context`, `debug-console/context`, etc?

Also, is support for passing or accessing currently selected text in those views possible?

**Comment by Tyriar** [comment]
> Might it be possible to include context menu contribution points for

That would need to be separate feature requests.

> Also, is support for passing or accessing currently selected text in those views possible?

That's not the current thinking.

**Comment by Kingwl** [comment]
I'd like to work on this.

**Comment by Tyriar** [comment]
@Kingwl sounds good 👍 I haven't actually dealt with adding something like this yet so I would search the codebase for similar context menu contributions for other components like the explorer.

**Comment by gar1t** [comment]
I would add, also, that menu support ought to be available for `termina/title` to provide more visibility into actions/commands available for a terminal session. Context menus are great but my concern is that since this would be new functionality, users might not have any idea that there are useful functions hiding in the already pretty full context menus. Having menus visible in the title area would be important I think.

+1 to extend this to output, problem, etc. as per @nickyhajal's suggestion.

My extension makes extensive use of system commands via the terminal that tie user work via editors to a CLI based program. A particular terminal is associated with a particular operation/goal, which may have various other VS Code commands associated with it. There's currently no decent way to tie commands to that terminal/operation. It seems that the menu facility that's widely available in other areas (editors, explorer, source code, etc.) is painfully missing for terminals, output, problems, etc.

**Comment by Tyriar** [comment]
Proposal:

- The terminal context menu `terminal/context`
  - Right clicking in the terminal area.
  - One complication here is that certain platforms don't open a context menu on right click, for those shift+right click? This may happen already, need to confirm.
- The terminal title menu bar `terminal/title`
  - Clarify this is about contribution to the actions in the top-right
- The terminal title context menu `terminal/title/context`
  - Clarify this is for terminal tabs

The `Terminal` that it is triggered on is pass in to the command that is executed.

**Comment by Tyriar** [comment]
This is done and TPI is created, so moving this to next iteration
