### ISSUE TITLE
Cursor can sit in between characters and combining diacritics

### ISSUE THREAD

**Issue by vomout** [microsoft/vscode#79067]
Some combining unicode characters are displayed incorrectly, for example σ̃, which is a valid variable name in e.g. Julia. Sometimes they are displayed by themselves, sometimes combining with the next character instead of the previous one.

- VSCode Version: 1.37.0
- OS Version: MacOS 10.14.5

Steps to Reproduce:

1. Open a new buffer/document (cmd-n)
2. Enter σ followed by a combining-~ (Alternative 0: copy-paste from right here: σ̃. Alternative 1 (MacOS): ctrl-cmd-space, search for “sigma”, followed by another ctrl-cmd-space, search for “combining tilde”; Alternative 2: for the σ use the Greek keyboard, for the combining tilde follow Alternative 1; Alternative 3: having installed the Julia support packages, switch language to Julia, and type \sigma[tab]\tilde[tab]; Possible (untested) alternative 4: using the Unicode LaTeX package with LaTeX escapes similarly to the Julia package.)
3. Observe that the tilde is incorrectly displayed after the “σ”, not above it.
4. Follow by typing another character, e.g. “a”. 
5. Observe that the tilde is displayed above the “a”, incorrectly.
6. Clear the buffer and repeat steps 2-4 but in place of “σ”, enter “b”, the follow by the combining tilde (copy-paste route: b̃).
7. Observe that the tilde is displayed above the “b”, correctly.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
I can't reproduce exactly what you are describing with the rendering of `σ`, but I can confirm that we allow for the cursor to sit in between the `σ` and the combining diacritic. 

The sitting of the cursor in between is reproducible with latin letters and can be observed in the status bar, as well as by editing. Simplified steps:

* paste `ã`
* place cursor at the beginning of the file
* press right arrow once. this should advance past the combining diacritic, but the cursor is now sitting "in between" `a` and the combining diacritic mark.
* type `b`
* the desired output is `ãb` but it is `ab̃` because the cursor was adding the `b` in between `a` and the combining diacritic mark.

![Kapture 2019-08-14 at 12 27 52](https://user-images.githubusercontent.com/5047891/63014492-f9f92900-be8e-11e9-9e11-5aeb2c3bc92e.gif)

**Comment by alexandrudima** [comment]
Let's track in #15622
