### ISSUE TITLE
Expose terminal scroll position and allow extension change it

### ISSUE THREAD

**Issue by IlyaBiryukov** [microsoft/vscode#79063]
Some of Live Share customers want to follow other participants in shared terminals (https://github.com/MicrosoftDocs/live-share/issues/2671). 
One feature that is missing in VSCode is getting and controlling terminal scroll position. Can VSCode expose current scroll position and allow extension changed it in a given pseudo terminal window?

**Comment by Tyriar** [comment]
I suppose next would be supporting listening to the selection and drawing decorations 🤔

@IlyaBiryukov what APIs are used to follow in the editor?

**Comment by IlyaBiryukov** [comment]
We use `vscode.window.onDidChangeTextEditorSelection` and `vscode.window.onDidChangeTextEditorVisibleRanges` to track selection and scroll position changes.

**Comment by waterlink** [comment]
@Tyriar Selection makes total sense: very useful for pairing and for having a conversation about some output in the terminal.

I’m not sure what’s a drawing decoration in the terminal—What is it?

**Comment by Tyriar** [comment]
@waterlink doesn't exist yet. It gets extra complicated as the terminal is a separate project, unlike monaco which is contained within the vscode repo, so sharing things like this is difficult.

**Comment by Tyriar** [comment]
Had a chat about this in the API call today, the API would probably look something like this:

```ts
export interface window {
	export const onDidChangeTerminalVisibleRange: Event<TerminalVisibleRangeChangeEvent>;
}

export interface TerminalVisibleRangeChangeEvent {
	readonly terminal: Terminal;
	readonly visibleRange: Range;
}

export interface Terminal {
	readonly visibleRange: Range;
	revealRange(range: Range, revealType?: TerminalRevealType): void;
}
```

However, it's a lot more complicated than initially expected because of how the terminal trims content away from the top. For example:

- If the scrollback setting differs between clients it could cause issues
- Does counting happen from the bottom on the terminal?
- Internally the terminal treats the very top row as index 0 and counts down, it has the concept of "markers" which are essentially ranges that are aware of trimming on the top and will amend their line index when this happens. I suspect even if we adopted this system it would all come crashing down once the markers are passed to clients asynchronously as more could things could have been written to the terminal.

**Comment by sourishkrout** [comment]
@Tyriar any chance this proposal could make it back onto the agenda? I've checked `vscode.proposed.d.ts` but it's not included yet.

**Comment by Tyriar** [comment]
Considering the technical challenges with this and the little interest I don't think this will get prioritized any time soon.
