### ISSUE TITLE
Allow configuration of product icons

### ISSUE THREAD

**Issue by schtauffen** [microsoft/vscode#79130]
The new expand/collapse icons are jarring for me and I would like to return to the smaller triangles. 

I apologize if this is already doable, but I was unable to find it in the settings.

<img width="82" alt="Screen Shot 2019-08-14 at 10 50 50 AM" src="https://user-images.githubusercontent.com/8205935/63036553-de882100-be82-11e9-90ef-9b490b615610.png">

**Comment by gjsjohnmurray** [comment]
Not already doable, but already requested in https://github.com/microsoft/vscode/issues/78024#issuecomment-520266795 so marking this as a /duplicate

**Comment by ErikHumphrey** [comment]
Would adding this level of theming heavily increase load times?

**Comment by misolori** [comment]
@ErikHumphrey we already do this with file icons so it shouldn't impact performance

**Comment by Hum4n01d** [comment]
I would really appreciate an option to used the filled versions of the icons, maybe create an official icon extension with them?

**Comment by sarpik** [comment]
If we can have a filled-in version of the current icons, how about also having the old icons available?

Or maybe allowing users to choose their own icons, so that you could cherry-pick from the new ones, the old ones and even select your own?

The activity bar would be a great start IMO, because I dislike the new ones, and would love the option to switch back.

**Comment by lllopo** [comment]
Hopefully, if you revert to the old triangles, you make it optional, as the chevrons are much, much better looking to me. Actually the triangles were most ugly thing in the whole VS Code interface overall. The chevrons are great, they just need to be a bit smaller as currently are too imposing.

**Comment by unixcow** [comment]
filled version of current icons sounds like a legit one, it will keep product identity the devs are looking for while make it more enjoyable for people who enjoyed the old (more solid) look

**Comment by danielsig** [comment]
I just want to put it out there that these new icons are a complete dealbreaker for me. No feature can be added to VS code (not even multiple windows) that can convince me to put up with icons that are so thin that I literally **can't see them** without peering at them (I'm nearsighted). I really hope icon customizaction will become an option or at least a way to go back to the old icons. If not, I will eventually be forced to stop using VS code since I can't update it.

**Comment by Servail** [comment]
Personally I like the new icons. But feature to change their appearance is a must-have!
P.S.: I hope there will be more attention to code folding in general, and we'll see VS-like functional in future, like [here](https://github.com/microsoft/vscode/issues/2948#issuecomment-183540068)).

**Comment by zkriszti** [comment]
Are there any advancements on this? Removing of + and - icons and forcing the user to use chevrons (which is, by the way, completely against traditionally accepted industry standards for IDEs) is a nightmare...

**Comment by aeschli** [comment]
I created https://github.com/microsoft/vscode/issues/92791 as the plan item implementing this.

**Comment by aeschli** [comment]
dup of https://github.com/microsoft/vscode/issues/92791
