### ISSUE TITLE
Allow reloading / stopping / pausing sessions inline in the tree

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#79189]
Today we support controlling sessions via context menus:

![2019-08-15_10-34-57](https://user-images.githubusercontent.com/1898161/63083232-83206680-bf48-11e9-8bb0-8777cc34a1a4.png)

![2019-08-15_10-35-18](https://user-images.githubusercontent.com/1898161/63083219-7bf95880-bf48-11e9-8522-151cb982a73f.png)

Using inline actions on the debug session tree node is a more direct and discoverable way to achieve the same.

**Comment by isidorn** [comment]
If we were to render this for all threads and all sessions it would be too much noise.
Thus I suggest to only render them on hover for both sessions and threads.
We would only show the actions which are currently enabled.

I can look into this milestone, and I can also bring it up in the ux meeting today.

**Comment by weinand** [comment]
yes, rendering actions only on hover makes sense.

Only showing enabled actions might be problematic because it prevents a stable UI: if I do not move the mouse, clicking it should always result in the same action being pressed. I do not want to suffer from a "moving target" problem.

**Comment by isidorn** [comment]
After discussing in the UX call we decided to:
* Show only the inline actions on hover
* When hovering hide the "Paused" label to save on space and show actions
* When there are no threads, show all 6 actions on the debug session (continue, step over, step in, step out, restart, stop)
* When there are threads, show 4 actions on the threads (continue, step over, step in, step out) and show 2 actions on the debug session (restart, stop)
* try to keep stable position when changing from paused / running state so actions do not jump a lot

fyi @pavelfeldman @dgozman

**Comment by pavelfeldman** [comment]
@isidorn This sounds fantastic!

**Comment by isidorn** [comment]
We have a first version of this working in vscode insiders. 
The only thing we were discussing is if we should show some actions in the title of the CALLSTACK view when no sessions are shown. For now we decided not to do this, but we can add this if we think it is necessery.

Please try it out and provide feedback. THanks!

![hello](https://user-images.githubusercontent.com/1926584/64431730-495ffd00-d0bb-11e9-9577-b14747046482.gif)

**Comment by dgozman** [comment]
I tried this out, and it works great!

However, the debug toolbar is empty now. Perhaps related?
<img width="519" alt="Screen Shot 2019-09-09 at 11 20 17 AM" src="https://user-images.githubusercontent.com/9881434/64556306-0341ae00-d2f4-11e9-8405-ff8a2f3af808.png">

In our usecase, not every session can be restarted, for example web workers. Should we expose a way to control that? Note that DAP capability `supportsRestartRequest` does not help, since it merely changes `restart` request to a pair of `terminate` and `launch/attach`. Perhaps the solution should be similar to issue #62419? @isidorn, @weinand what do you think?

**Comment by isidorn** [comment]
@dgozman Debug toolbar is fixed in latest - sorry about that (captured in https://github.com/microsoft/vscode/issues/80563)

As for the disabling `Restart` this is currently not possible. I suggest you create a new feature request, since the session needs to specify that it can not be restarted. In the meantime I suggest that you turn on capability `supportsRestartRequest` - that will make VS Code send a restart request to your adapter which you can ignore - thus making the command a no-op.

As for pairing it up with #62419 this does not sound related to me. Feels like two different capabilities that just luckly apply to the same type of sessions in your use case.

**Comment by isidorn** [comment]
Adding verfied per @dgozman comment
Also I regularly use it when self hosting and am happy with the experience thus far.
