### ISSUE TITLE
REPL: render evaluation results in a visually distinct manner

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#79197]
e.g. color-coding, crlf character

**Comment by isidorn** [comment]
We could birng this up in the next ux meeting. Since we already do some color coding as shown in the attached picture

fyi @misolori 

I think @roblourens also had some feedback in the past how we should better differentiate between input and output.

![Screenshot 2019-08-15 at 15 53 33](https://user-images.githubusercontent.com/1926584/63099220-f344e180-bf74-11e9-9064-49c021328c24.png)

**Comment by roblourens** [comment]
Inspiration from chrome devtools:

![image](https://user-images.githubusercontent.com/323878/63227308-c32a5800-c199-11e9-94f5-f8f44e8768eb.png)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/37363
