### ISSUE TITLE
Support more trigger characters for debug console completions 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#79195]
Today VS Code has a hardcoded "." trigger character for debug console completions.
Some debug extensions would like to use additional trigger characters, e.g. "[".

We should consider to allow for announcing trigger characters as DAP capabilities.

This item is for the VS Code side, the corresponding DAP feature request is https://github.com/microsoft/debug-adapter-protocol/issues/71.

**Comment by weinand** [comment]
@isidorn I've added a new optional capability `completionTriggerCharacters` that lists the trigger characters to use:
```
  /**
   * The set of characters that should trigger completion in a REPL. If not specified, the UI should assume the '.' character.
   */
  completionTriggerCharacters?: string[];
``` 

Please make the debug console use them (and fall back to '.' if they are missing).

**Comment by isidorn** [comment]
The debug console now supports `completionTriggerCharacters` as specified by @weinand in the debug adapter protocol.
It would be cool if the node adapters jumps on this and adds `"` and `]` as @pavelfeldman suggested.

fyi @roblourens

**Comment by weinand** [comment]
I've added sample code for completions to mock-debug and verified that more trigger characters work.

**Comment by pavelfeldman** [comment]
Happy to see this moving along. I still can't use it for `[` and for `"` in my extension though, please see details below.

When I type `window[`, VS Code completes it to be `window[]`. At this point, I have hard time distinguishing between `window[|]` and `window[]|`, i.e. I can't tell where the caret is in my DAP handler. Completion's `line` and `column` parameters always point to the expression end, i.e. to after `[]`.

Same happens when I type `window["`, I'd like to know where exactly the caret is.

**Comment by pavelfeldman** [comment]
@weinand, @isidorn : still need help with the ^^!

**Comment by pavelfeldman** [comment]
Tried using it end-end, there is still a wrinkle: when the user types `window['do<|>]`, I would like to end up with the `window['document']<|>` as I accept the completion. Could not quite achieve it yet. The best one I got so far was `window['document']<|>]`. This has an extra `]` in the end, but allows for continuity in typing `window['document']['body']`

**Comment by pavelfeldman** [comment]
Sorry for the spam around this one, I again can't get it to work. My goal is to have it suggest me `window['document']` when I hit Enter in the `window['docu<|>]` state. What are the start / length values that I need to provide so that it worked?

**Comment by isidorn** [comment]
@pavelfeldman first of all thanks for trying it out immediatly.
I have to confess that I never fully understood all our completion item attributes even though @jrieken explained it to me numerous times. What you want should be possible. We are doing some fine tuning [here](https://github.com/Microsoft/vscode/blob/7621355f7e0c560dc30ad0c04f62d30bc1659b61/src/vs/workbench/contrib/debug/browser/debugSession.ts#L558) which might effect this.

@pavelfeldman can you share your extension and easy repro steps so I can experiment with this on my machine? Since the current node debug does not propose `document` in that case. It proposes a lot of other things and they all complete just fine for me

Also pressing Enter is accepting the completions, it is not triggering completions. Are you trying to accept the completion or just get it listed in the suggest box?

![repl](https://user-images.githubusercontent.com/1926584/63418252-1226f600-c403-11e9-8b4e-734dbe7cd81c.gif)
