### ISSUE TITLE
 Lines separating splitted terminal disappear when enable/disable menu bar

### ISSUE THREAD

**Issue by alanlivio** [microsoft/vscode#79226]
- VSCode Version: 
$ code -version
1.37.0
036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8
x64
- OS Version:
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco

- Steps to Reproduce:

1. use integrated terminal at right and splited
2. enable and disable menu bar
3. the lines separating the splitted terminal disappear (see figures)
![Screenshot from 2019-08-15 12-42-20](https://user-images.githubusercontent.com/604808/63107118-bbc93b80-bf5a-11e9-9eb4-bc6a20d1fc01.png)
![Screenshot from 2019-08-15 12-42-42](https://user-images.githubusercontent.com/604808/63107119-bc61d200-bf5a-11e9-9aa2-cf44b9a915bf.png)

- Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by Tyriar** [comment]
This appears to happen only when the first row of the lower split pane sits on top of the sash. I guess it's a problem with the internals of the pane not sizing correctly.

**Comment by jeanp413** [comment]
This is caused by the border-top in `split-view-view` from this css rule 
https://github.com/microsoft/vscode/blob/2d3727b3b19538e149b51d6c3f857636076c1e94/src/vs/workbench/contrib/terminal/browser/media/terminal.css#L83-L86

which isn't taken into account when calculating the height of the terminal
https://github.com/microsoft/vscode/blob/2d3727b3b19538e149b51d6c3f857636076c1e94/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L432

Seems there's no easy way to get that value, maybe just always subtract 1 px from the total height `const innerHeight = height - bottom - 1; `
