### ISSUE TITLE
Ability to restart task from the terminal

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#79238]
After a task is terminated, and I see the message in the terminal which says:

```
Terminal will be reused by tasks, press any key to close it.
```

I often would like to restart the task.

It'd be great if there was a "restart" or "play" button somewhere there. At the moment, I have to use the command palette to restart the task, which can sometimes be slower if my hand is already on the touchpad or mouse. It'd be good to have that extra option.

**Comment by trusktr** [comment]
For example, here's what it currently looks like:

<img width="836" alt="Screen Shot 2019-08-15 at 10 55 16 AM" src="https://user-images.githubusercontent.com/297678/63115053-34c09700-bf4b-11e9-8b33-10a9be9f7617.png">

The top right has some icons. It'd be neat if there were icons for controlling tasks there too (f.e. start, stop, restart, etc).

**Comment by ArturoDent** [comment]
There is a command `workbench.action.tasks.reRunTask` which you might find helpful.  Not a button but you could make it a keybinding.

**Comment by alexr00** [comment]
Since we already have a convenient command for this that you can hook a keybinding up to, I don't want to clutter up the UI by adding another button. If adding a keybinding to the `reRunTask` command doesn't solve your issue feel free to ping this issue again and we can talk about how else it could be solved without adding more buttons.
