### ISSUE TITLE
Support `-r` flag when combined with `-w`

### ISSUE THREAD

**Issue by coreh** [Microsoft/vscode#7929]
- VSCode Version: 1.2.1
- OS Version: OS X 10.11.5

Steps to Reproduce:
1. Have an existing VSCode window open
2. Run `code -w -r file.js`
3. Only the `-w` flag gets honored, but not `-r`. (So file opens in a separate window)

In that circumstance `-w` should probably wait for the _editor_ to be closed (and not the window, since that's reused)

**Comment by dbaeumer** [comment]
@joaomoreno not sure if you or @bpasero

**Comment by ThisIsMissEm** [comment]
I have a similar case here, excepting, doing interactive git rebases; If I'm to use VS Code to perform these, then I'm drastically slowed down, as I'm constantly waiting for editor windows to open, after having to close them in order to get `code` to exit for `git rebase` to continue.

If any VS Code developers can point me to the right place in the code to work on fixing this functionality, I'd almost definitely send you a pull request.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/24327
