### ISSUE TITLE
Initializing js/ts language features never completes

### ISSUE THREAD

**Issue by brunoscopelliti** [microsoft/vscode#79380]
I've just installed version 1.37.1.
It seems there has been a regression on this issue: https://github.com/microsoft/vscode/issues/68896.

**Comment by brunoscopelliti** [comment]
Hi @mjbvz ,
What kind of info do you need?
The issue is exactly the same of https://github.com/microsoft/vscode/issues/68896.

**Comment by electric-skeptic** [comment]
VS Code version:  1.37.1
Windows 7 Starter 32 bit

Extensions (problem exists with all disabled):
vscode-eslint	dba	1.9.0
githistory	don	0.4.6
gitlens	eam	9.9.3
vscode-settings-cycler	hoo	1.0.1
git-graph	mhu	1.13.0
vscode-typescript-tslint-plugin	ms-	1.2.2

Steps to reproduce:
open any JavaScript or TypeScript file

Symptoms:
The application starts responding very slowly and 
> "Initializing Js/TS language features"

 appears in the statusbar, which never disappears.

As @brunoscopelliti mentioned the issue presents with the exact same symptoms as all of the other times it's been reported and closed previously (normally for insufficient information, or just locked with no explanation).

**Comment by mjbvz** [comment]
Have you configured a custom TypeScript version in your workspace? Are you loading a file on a network drive?

**Comment by electric-skeptic** [comment]
Hi @mjbvz No, the files are all on the local hard drive. There aren't any workspace settings at all, nor have I made any effort to set up TypeScript beyond installing the TSLint extension.
It's also a clean install of VS Code on a laptop not previously used for any development

**Comment by mjbvz** [comment]
Please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by mjbvz** [comment]
Also @electric-skeptic, open a separate issue

**Comment by electric-skeptic** [comment]
> 
> 
> Also @electric-skeptic, open a separate issue

I'll stop helping so you can resolve the issue with the OP, or filibuster and close another thread about it, but there's little point in opening a separate issue while one is already open ([https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#look-for-an-existing-issue](url)) with what is plainly the same problem, only to have someone get irritated and close it as a duplicate.

**Comment by remychvn** [comment]
I confirm, I have the same problem.

**Comment by electric-skeptic** [comment]
I'm sure we all have the same symptoms, as of the same version. Opening new issues divides the attention each issue gets, so it seems like we should [contribute data to the same issue](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md#look-for-an-existing-issue), otherwise devs get annoyed and close them as duplicates, which even the bot is noticing, or due to lack of further detail. We end up with the situation where people can see [dozens of inadequately addressed, closed issues about this problem](https://www.google.com/search?q=%22Initializing+js%2Fts+language%22) and [are complaining about poor issue moderation](https://github.com/Microsoft/vscode/issues/65178#issuecomment-447688244) instead of contributing to progress on it.
I'll stop trying to help so @mjbvz can pursue it with OP, but I'll definitely abstain from opening _another_ issue about it.

**Comment by mjbvz** [comment]
Generic problems like this often have multiple different root causes and it is much easier for us to track each one individually. Otherwise we end up in exactly the situation we have now where multiple chime in with +1 without providing any additional context and it is difficult to track their individual problems or follow up with them properly

So instead of complaining, please open a separate issue and share the logs on it as I requested

**Comment by brunoscopelliti** [comment]
I am sorry, I cannot share the log cause it is proprietary code.

**Comment by mjbvz** [comment]
@brunoscopelliti 

1. Have you configured a custom TypeScript version in your workspace?
1. Are you loading a file on a network drive?
1. Does this happen for all projects?
1. If not, can you provide details on the type of project it does happen for
1. Can you share the last 20 or so lines of the logs

**Comment by brunoscopelliti** [comment]
> Have you configured a custom TypeScript version in your workspace?

No

> Are you loading a file on a network drive?

No   

> Does this happen for all projects?

Don't know, at the moment I'm working full time on a single project.
   
> If not, can you provide details on the type of project it does happen for?

React web app, backend is in node

> Can you share the last 20 or so lines of the logs

It's not that simple, cause I don't immediately notice the error. But I can try.

**Comment by mjbvz** [comment]
Can you please try opening some other simple js projects to see if the issue is specific to the project you are working on?

Also, can you  share the logs privately with us? Without logs or repo steps, it is not really possible to investigate this effectively

**Comment by brunoscopelliti** [comment]
> Also, can you share the logs privately with us? 

How?
Next time the issue occur to me, I'll consider this option.

**Comment by atlefren** [comment]
I have this issue as well (if anyone is interested?)

Occurs in: 

Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18922

Using: WSL 2 with Ubuntu and the remote - WSL extension (0.39.2)

output of log: https://gist.github.com/atlefren/0d261c06fc609d32f43a1c016f8c2921

seems to work sometimes, other times not..

Also tried to reproduce in Insiders, but there the WSL remote is borked atm..

**Comment by atlefren** [comment]
Follow up: 

Now testing with a fresh install of Insiders (1.38.0-insider) (all config wiped, both on win and wsl side). Code reports ts v 3.6.1-rc, but I've also tried the "workspace version" (3.3.3333).

Everything seemed to work fine untill npm install completed, which immediately triggered the "Initializing js/ts language features" message. I would not say I have an unreasonable amount of dependencies (for a typescript project), about 40 or so..

It seems like the log from ts server has this as its last line:

`Info 200  [9:44:16.425] DirectoryWatcher:: Added:: WatchInfo: /mnt/d/code/wadmin/node_modules 1 Project:  WatchType: node_modules for closed script infos in them`

My guess is that the ts analyzer (or whatever it's called) has a hard time reading all the contents of node_modules due to _some_ issue. Not sure if it's that fact that the folder is large (318 MB), or that WSL2 is slow, or that the disk itself is slow.

One thing worth mentioning is that the folder is on my win drive, mapped to wsl. Things seems to work as expected when I checkout the repo in wsl and run it from there. Thus: my guess is that the issue is related to the combination of a slow wsl2 disk access to a win drive and a (rather) large and complex node_modules

**Comment by hisankaran** [comment]
It is possible that you are experienceing this because of https://github.com/microsoft/TypeScript/issues/21136. Thanks @mjbvz!

**Comment by atlefren** [comment]
@hisankaran Not sure if this question is directed at me, but unless some of my dependencies downloads this kind of file it is not the case.

**Comment by hisankaran** [comment]
@atlefren No, that was a general suggestion for anyone who are landing on this issue. I got the exact same logs that you posted, and my node_modules is excluded for explorer. my test dir had all sorts of sample videos and audios, I tried moving that away from project and it worked. So, may be you should try excluding your node_modules from explorer.

**Comment by atlefren** [comment]
@hisankaran I understand. 

What do you mean by "excluded for explorer"?

**Comment by hisankaran** [comment]
Sorry that as confusing. I mean, try watcher.exclude setting.
<img width="982" alt="Screenshot 2019-09-20 at 9 46 37 AM" src="https://user-images.githubusercontent.com/501259/65299069-9946c580-db8b-11e9-87c0-a6972db929c6.png">

**Comment by atlefren** [comment]
Got you. My watcher exclude is similar to your screenshot, but thanks for the suggestion. In my case I am rather certain that this has something to to with WSL2 interop in some way

**Comment by mjbvz** [comment]
Closing as we have not heard back from the OP recently and cannot investigate without more information
