### ISSUE TITLE
When word wrap is disabled text still wraps until word wrap is toggled on and off again

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#7943]
- VSCode Version: Code - Insiders 1.3.0-insider (5474147bb83618975409dad7d8aa96151d7d1ea1, 2016-06-21T19:35:37.900Z)
- OS Version: Windows_NT ia32 10.0.14342

Steps to Reproduce:
1. Open VS Code
2. Ensure that word wrap is already not set (otherwise set it and reopen VS Code)*
3. Paste a large amount of text (over 300 columns long)
4. Observe that the text DID wrap at some arbitrary length (at some word break near 300 columns)

\* It seems to do the right thing if word wrap is turned off _after_ the text is pasted.

![image](https://cloud.githubusercontent.com/assets/494055/16250357/9452d1ec-37d1-11e6-9622-fe6bcf6ef7f0.png)

Workaround seems to be to toggle word wrap and then things work correctly.

![image](https://cloud.githubusercontent.com/assets/494055/16250426/266a3822-37d2-11e6-804e-07786cd16f2a.png)

**Comment by atorres76** [comment]
I have also had this exact issue. I do the same workaround described.

**Comment by billyzkid** [comment]
Yes, I have confirmed this bug still exists in v1.7.1

**Comment by dmaltsiniotis** [comment]
Confirming this issue still exists in 1.8.1. This issue persists after VS Code restarts as well, so I have to enable, then disable word wrap every time I open a file.

**Comment by alexandrudima** [comment]
### Mastering line wrapping

There are two important settings in VS Code that control word wrapping.

* `editor.wrappingColumn` (300 by default)
* and `editor.wordWrap` (false by default)

It is important to understand the need for two distinct settings and how to tweak them to suit your use-case:

Examples (with explanations):

| `wordWrap` | `wrappingColumn` | Explanation |
|---|---|---|
| false | 300 | Lines will wrap at <code>300</code> |
| false | 0 | Lines will wrap at <code>viewport_column</code> |
| false | -1 | Lines will never wrap. |
| true | 300 | Lines will wrap at <code>min(viewport_column, 300)</code> |
| true | 0 | Lines will wrap at <code>viewport_column</code> |
| true | -1 | Lines will never wrap. |

**Comment by dmaltsiniotis** [comment]
Thanks for the clarification, this makes much more sense now. Followup question: Isn't having wordWrap: false and a wrappingColumn > 0 confusing? Maybe I should ask this question on a different UI issue, or perhaps it's more a default configuration setting issue. If the default for wordWrap is "false" then it stands to reason the wrappingColumn should also be 0 (unless otherwise overridden.) Thoughts?

**Comment by alexandrudima** [comment]
Having no wrapping by default (i.e. shipping with wrappingColumn = 300 by default) is a conscious decision:
* rendering really long lines makes the editor slow (e.g. opening a 1MB minified JS file that consists of one line and wrapping is turned off). By slow I mean it doesn't do 60 FPS on good hardware. i.e. the time taken to paint a frame by us + the browser is definitely longer than 16ms
* the reason the editor is slow on really long lines is that we don't have virtual horizontal rendering. e.g.
  * if a line has 1 million characters and wrapping is completely off, we will "paint" 1 million characters (i.e. give 1 million characters to the browser, grouped in hundreds of thousands of `span`s)
  * the JS code doing the "painting" is not problematic, we can generate HTML for those 1 million characters quite quickly
  * but browsers (Chromium in VSCode's case) don't like to get hundreds of thousands of dom nodes, the browsers become slow for everything, especially in cases where that specific line is scrolled in the viewport, then scrolled out again, etc. Besides everything taking longer, it also generates a lot of DOM node garbage for the GC
  * we don't have virtual horizontal rendering because we support non monospace fonts and RTL, bidi, emoji, CJK, etc. We let the browser paint the entire line, since we do not make any assumptions regarding the pixel offset where a character ends up painted. To be able to do virtual horizontal rendering, we would need to implement all the font layouting logic in JavaScript
* we therefore came up with the following:
  * by default we cut off at 300 chars. If you are writing source code in "source", probably 99.9% of the time your source code will contain lines shorter than 300 chars.
  * if you open some file that contains a very long line, the editor will be perfectly responsive.
  * if you don't like that the line is wrapped, you can look into the settings and change them
  * if the editor gets slow after you've changed the setting, you can hopefully correlate the slowness with the fact that you have a very long line and with the fact that you changed a setting. i.e. in a way, by changing the setting, you become more tolerant to the slowness, since you sort of opted into it. I'm not sure how to explain in better, except to mention that I know the editor is slow on very long lines and yet nobody is complaining about it, since everybody needs to "opt in" for the slowness to occur.

**Comment by atombender** [comment]
I was getting random wrapping on opening files until I put `"editor.wordWrap": false` in my settings. Not sure whether VSCode is remembering the word-wrap setting on a per-file basis, or whether it's applying a default dynamically based on the file being opened (because the global default for `editor.wordWrap` _is_ `false`).

I have to say that this is behaviour is confusing. At least I'd expect the editor to say something like: "Looks like this file has some very long lines! We've automatically enabled word wrapping for you."

**Comment by alexandrudima** [comment]
Wrapping settings are getting an overhaul with #21262
