### ISSUE TITLE
Visible output channel output is delayed

### ISSUE THREAD

**Issue by NikGovorov** [microsoft/vscode#79431]
Version: 1.38.0-insider (user setup)
Commit: 4fa08902f7845050a948d3d74e3b836276fa613a
Date: 2019-08-19T05:39:53.031Z
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Please see https://github.com/microsoft/vscode/issues/59209#issuecomment-424547740 for the steps to reproduce and more details.

CC: @sandy081

**Comment by NikGovorov** [comment]
Stable:
![vscode-failing-tests-pane-stable](https://user-images.githubusercontent.com/129254/63245203-d9700b00-c2a2-11e9-8180-04b4446adf7f.gif)
Insiders:
![vscode-failing-tests-pane](https://user-images.githubusercontent.com/129254/63244953-27d0da00-c2a2-11e9-873e-2bd8e58bd500.gif)

**Comment by sandy081** [comment]
@NikGovorov Is that the latest stable? If so there are no changes done in output channel. Please file an issue against the extension to check if it is caused by the extension.

**Comment by ArtemGovorov** [comment]
@sandy081 It is reproducible in the latest insiders and is not caused by the extension.

Here is the easiest way to reproduce it: 
- install [Quokka extension](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode),
- in latest stable here is how it responds to changes:

![q1](https://user-images.githubusercontent.com/979966/63731708-37f54480-c8b4-11e9-8546-3e153739f963.gif)

- in the latest insiders:

![q](https://user-images.githubusercontent.com/979966/63731717-44799d00-c8b4-11e9-9d20-59d2033b5741.gif)

Looks like this change of yours https://github.com/microsoft/vscode/issues/59209#issuecomment-424674048 is not applied anymore in insiders. Maybe it is the result of these changes https://github.com/microsoft/vscode/blob/26b10b2d01d62b47d9b14622558893a04ef5dabc/src/vs/workbench/api/node/extHostOutputService.ts#L48 (cc @jrieken ) ?

**Comment by sandy081** [comment]
@ArtemGovorov Thanks for info.

Yes, it is broken by our recent changes. @jrieken FYI

Fixed.

**Comment by jrieken** [comment]
Thanks @sandy081
