### ISSUE TITLE
js lint fail

### ISSUE THREAD

**Issue by GamesThatWork** [microsoft/vscode#79436]
Issue Type: <b>Bug</b>

in this class method definition, the js linter
fails to catch the extra ` {  `on fourth line
which is not only imbalanced but also creates an orphan`  else  `

```

start(){
    console.log( "this.preloaded="+this.preloaded );
    if( this.preloaded )      
            this.game.scene.start( this );{
    else    
            this.latentStart = true;
    }
```

VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.0.0
rainbow-csv|mec|1.2.0
debugger-for-chrome|msj|4.11.7
LiveServer|rit|5.6.1

</details>

**Comment by IllusionMH** [comment]
As I can see - VS Code reports problem with your code.
![image](https://user-images.githubusercontent.com/1312662/63253331-5044de00-c27a-11e9-8f40-677208465d21.png)

Similar error will be reported by browsers
`Uncaught SyntaxError: Unexpected token 'else'` and `SyntaxError: expected expression, got keyword 'else'`.

You see this error because it is first syntactically invalid piece - `{` can be placed in the end of the line.

If you remove `else` than code can be valid, because 
```
{
   // else   - removed
            this.latentStart = true;
    }
```
is just code block and then missing `}` will be reported.
![image](https://user-images.githubusercontent.com/1312662/63253594-d06b4380-c27a-11e9-96c9-099c2ababbef.png)

**Comment by mjbvz** [comment]
Please share a complete code example

Also test this using the latest VS Code version

**Comment by GamesThatWork** [comment]
will do this evening
i am very impressed by your rigor!

**Comment by GamesThatWork** [comment]
I have had trouble creating reproduction steps in latest Code
so I suppose we ought to close this ticket

THANKS

Dov Jacobson
Managing Director
GamesThatWork.com
404 806 5428

**Comment by GamesThatWork** [comment]
thx
