### ISSUE TITLE
Code actions are not reset after application

### ISSUE THREAD

**Issue by OmarTawfik** [microsoft/vscode#79491]
### Build

```
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```

### Description

I'm working on a language server that lints user code. The server returns code actions for various issues. I noticed that if a user chooses to apply a code action (for example, that deletes a line), the editor doesn't clear the diagnostic, or ask the server again for updated code actions. This results in the user being able  to apply the code fix again and again, deleting more valid lines.

### Steps to Reproduce:

I've wrote a small repro [here](https://github.com/OmarTawfik/vscode-extension-samples/commit/050a3ce18b3def49c3f551e07e8472fbd21ac891). Simply open the extension and run using `Client + Server` launch configuration.
The sample provides code actions to delete duplicate empty lines. The user is able to delete more valid lines by re-applying the code action. Here is also a video of this happening:

![code-action-repro (1)](https://user-images.githubusercontent.com/15987992/63326726-b0bb3600-c2e1-11e9-9f2f-0dc0884009ce.gif)

Unless there is something wrong with the sample server implementation, the editor shouldn't allow applying the same code action twice to the same document, as it produces invalid contents.

**Comment by solomatov** [comment]
My first idea for how to fix it, is to store a document version (or document hash) with each diagnostic. However, there's no such information in Diagnostic objects. 

Even worse situation than what's on the screen is possible:
- User saves the document. LSP, starts checking document.
- User edits files even more.
- The LSP is pretty slow, it finishes checking on saves, and sends results
- Error messages are irrelevant, and error markers are in incorrect positions

Is it really possible or is it just me who wasn't able to find the right code handling this situation?

@jrieken @mjbvz What do you think?

**Comment by solomatov** [comment]
To add more context, the extension provided by @OmarTawfik checks only on saves, and ignores in memory changes. That's why we have stale documents.

**Comment by solomatov** [comment]
I want to fix this issue. My plan is the following:
- add to IDiagnostic a version field to store a version of a file to which diagnostic was reported
- when providing code action, compare this field to the current version of document. If they don't match, don't provide code actions.
- when diagnostic is provided, save the version of the document. It's unsound, but it's the only thing which is possible to do in the current situation
- create an API to provide a document version to which diagnostic was produced for

@mjbvz Does it look reasonable and implementable to you?

**Comment by jrieken** [comment]
Unsure about this. The whole point of diagnostics is that they come in via a push model (as opposed to the pull model that we usually use). That means extensions must update diagnostics at their own rhythm and once that happens the UI reacts, e.g. re-request code actions. That also means that an extension can compare the version before and after the diagnostics computation and that the extension is the best at making the call to discard them or not.

**Comment by solomatov** [comment]
@jrieken As far as I understand, due to asynchronous update, extensions can't compare the current version, since while they are comparing it, a new change might be in transit, and it might lead to problems. So, a version or a hash seems to me as an optimal solution here. Also, instead of discarding, we might transform diagnostics through deltas so that they are correct.

Also, there're problem matches based on command line tools, which definitely won't be able to discard anything.

What do you think?

**Comment by jrieken** [comment]
>  since while they are comparing it, a new change might be in transit,

Yes, everything constantly changes and one cannot know what's happening or about to happen in the renderer process. That's why there is eventing that informs you about everything that's happening. 

The problem with diagnostics and documents/versions is that there must not be a correlation. You can make a change in file A and get an error in unchanged file B, you make an edit in file B and also get an error in file A. That's why we stay out of this business and leave it up to extensions - helping them with events. 

What we don't have (but maybe should have) is a way for extensions to signal that they the are currently computing diagnostics. We could use that to (1) show some kind of indication and (2) to synchronise code action and other features on that. However, that would require that the extension can precisely tell what files it currently "reasons" about.

**Comment by solomatov** [comment]
>Yes, everything constantly changes and one cannot know what's happening or about to happen in the renderer process. That's why there is eventing that informs you about everything that's happening.

@jrieken And what do you think about at least adding optional hash of a file in Diagnostics? In this way, at least some extensions, which want to be consistent can be so, and for such extensions we can transform their annotations to take into account recent changes.

>What we don't have (but maybe should have) is a way for extensions to signal that they the are currently computing diagnostics. 
It won't help. Due to asynchrony and to the fact that we aren't sure whether extensions take stuff from memory or from disk, it's pretty hard to sync here and be 100% sure. But, AFAIU, it's a pragmatic choice to ease integration with external tools, and this is what makes vs.code so compelling compared to other IDEs.  However, it would be nice if it was possible to provide more consistency at least for extensions whose authors are willing to do so.

**Comment by solomatov** [comment]
@jrieken I thought about it more. The only place where such Diagnostics are applicable are extensions which perform checks on save. But most of such extension, invoke external tool, and it's impossible to get a consistency there, and we definitely can't make them provide a hash. 
Other extensions, which continuously react to user input, eventually will become consistent after the user stops typing, and there's no need to do anything there. So, it makes very little sense to provide hashes or version or something.

**Comment by solomatov** [comment]
I read LSP specification, and it seems that LSP works on editor range, not on diagnostics: https://microsoft.github.io/language-server-protocol/specification#textDocument_codeAction

So, it's impossible to implement such a feature in vs.code. It's possible to change node-lsp library which provides code actions based on Diagnostics, though.

**Comment by solomatov** [comment]
It seems I am wrong. Everything is available there.

**Comment by mjbvz** [comment]
I believe that this is probably better left up to extensions. An extension can track if a diagnostic is stale or not and choose not to return code actions for ones that have already been fixed

It's difficult to come up with a VS Code api solution that would work well for all the different ways extensions implement diagnostics and code actions
