### ISSUE TITLE
Feature Request: Allow passing args inside entries of Npm Scripts Explorer

### ISSUE THREAD

**Issue by dsych** [microsoft/vscode#79509]
If you have an npm script that requires passing arguments to the binary being ran, normally the way you would pass args would be:
` npm run script -- -a -b `
However, running scripts through Npm Scripts Explorer would yield an error, since additional arguments are missing.

## Suggestion
Maybe we can have an additional action when right-clicking a script entry that will allow us to append args.
![npm_args](https://user-images.githubusercontent.com/16144679/63351481-56e05d80-c32d-11e9-8060-ca257f16bc56.png)

**Comment by dsych** [comment]
Nope, they do not appear to be duplicates...

**Comment by dsych** [comment]
@egamma I am willing to work on this as long as there is some agreement on what this feature is supposed to look like.

**Comment by egamma** [comment]
@dsych thanks for offering help, but before proceeding we need to clarify the feature as you suggest.

Since both 'Run' and 'Debug' should be able to take arguments. I would suggest adding two commands:
- 'Run with Arguments...'
- 'Debug with Arguments...'

This commands would show an input box using `vscode.window.showInputBox`. The input box would show the previously used arguments (globally, not for this particular script).

**Comment by dsych** [comment]
@eamodio 
> The input box would show the previously used arguments (globally, not for this particular script).

By this you mean that if I have two scripts e.g. `build` and `deploy` they will share the same arguments?

**Comment by egamma** [comment]
>By this you mean that if I have two scripts e.g. build and deploy they will share the same arguments?

I see that in this case the proposed solution is oversimplified. To support a 'mini history' per script we can store the last arguments used for a script in the workspace state and show this value.
