### ISSUE TITLE
URLService: should it handle vscode.env.openExternal / opn() too?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79506]
We have a `URLService` that [registers](https://github.com/microsoft/vscode/blob/63fe017/src/vs/platform/url/electron-browser/urlService.ts#L27) an opener with `IOpenerService` to handle schemas of `product.urlProtocol`. 

I recently added changes so that each `vscode.env.openExternal()` or the related usage of the `opn` module from an extension also goes through the opener service. 

Today we always send those things to `shell.openExternal()`, however for the case of a `vscode://` URL I wonder if we need to do that? It seems like a unnecessary hop that will start a VSCode instance only to send the data over. 

Thus, my question: should the `URLService` also handle each incoming open call from extensions if the `product.urlProtocol` is being used? Currently I explicitly opt-out of that by checking for [`options.openExternal`](https://github.com/microsoft/vscode/blob/63fe017/src/vs/platform/url/electron-browser/urlService.ts#L31) and thus keeping todays behaviour.

**Comment by joaomoreno** [comment]
Not sure. I think that service is tricking you due to its generic name: URLService. If it was called ProductProtocolHandlerService, the distinction would be more obvious.

I like to think about it as a router for `product.urlProtocol` URLs within the product... while the OpenerService can handle **any URL**, including `product.urlProtocol` URLs in which case it should just forward to the former.

**Comment by bpasero** [comment]
I pushed the original intent of this issue.
