### ISSUE TITLE
SCM: repository view order is upside down

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79519]
See:

![image](https://user-images.githubusercontent.com/900690/63361116-da22a300-c36f-11e9-99ec-a65e70b1eb6a.png)

**Comment by joaomoreno** [comment]
@sandy081 This is a problem with the views model: https://github.com/microsoft/vscode/blob/b3f85bc76d4332e3605b49c6f5cacf08f7a248f3/src/vs/workbench/browser/parts/views/views.ts#L385

I can't do anything since if I provide an order, it will eventually override whatever the user changed manually. So I can't provide an order, so the views get sorted by `id`. Why are they sorted by `id` anyway? If they don't have an order they should stay in the order they got registered.

**Comment by sandy081** [comment]
Makes sense.

**Comment by sandy081** [comment]
Reopening this as the fix causes views to be created twice.
