### ISSUE TITLE
A reload or restart option could be great.

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#7953]
- VSCode Version:1.2.1
- OS Version:arch linux

when i updated some definition files or some path it does not show in vscode instantly so i have to close vscode and reopen .
If there is a reload option like just after installing extensions it would be great

**Comment by rebornix** [comment]
Invoke command palette and type `reload` then you can reload JavaScript/TypeScript/Window :)

**Comment by Vishal-Isharani** [comment]
but a button on side pane would be great

**Comment by NikosEfthias** [comment]
@rebornix well i didint know that thanks :)

**Comment by Tyriar** [comment]
It's a very destructive action that is only really needed for developers of vscode or users that install an extension and dismiss the dialog. I'm going to close this off since I don't see this happening.

If you need to use it more frequently for some reason I recommend either adding a keybinding or accessing it via command palette (I use <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>, "rew", <kbd>enter</kbd> on Linux)

**Comment by rebornix** [comment]
I had no idea about this command until I saw @Tyriar used it. A button on the side pane would be intuitive but we can't move all commands to it, @Vishal-Isharani right?

Maybe we can have something like Ubuntu hot key map when you press `Windows` button for a few seconds, this might be a good extension, what do you think @Tyriar

**Comment by Tyriar** [comment]
@rebornix I don't think it's a common case for users to need to reload outside of the extension install prompt. If they do you can always add a simple keybinding to make it easy:

```json
{ "key": "alt+ctrl+r", "command": "workbench.action.reloadWindow" }
```

On adding it to the side panel, we need to be *very* careful when adding buttons to the UI, especially prominent places like on the activity bar. The UI is intentionally minimalistic in order to keep the UI lightweight, both in performance and perceived 'heaviness'. Doing something like this would be going against that design decision.

**Comment by Vishal-Isharani** [comment]
i got it thank you @Tyriar  and @rebornix
