### ISSUE TITLE
vscode:// protocol should allow a `windowID` parameter to forward to that window, instead of the last focused one

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#79635]
Now that we have support for [`IURLService#create()`](https://github.com/Microsoft/vscode/blob/a06015b53693d2f8a5a83cacff0da25b025f9e6f/src/vs/platform/url/common/urlService.ts#L19) we should try to get the window ID into the URI so that we can prefer to open the link in that window.

Today it seems we simply open in the last active window, which might not be right.

//cc @alexandrudima

**Comment by joaomoreno** [comment]
We gotta pass the command id and args down to the StaticRouter fn, such that it could potentially parse them and make a decision accordingly.

**Comment by RMacfarlane** [comment]
I'm still seeing the callback being triggered on the last focused window. Steps:

1. Open multiple windows
2. From one window, use the `GitHub Pull Requests: Sign in to GitHub` command
3. Browser window should be opened, note that the url does have the windowId as part of the "callbackUri" query parameter
4. Focus a different VSCode window than the one that started auth
5. Click "Continue" on the auth page in the browser and then click "Open" when prompted to open VSCode

The "Allow an extension to open this URI?" dialog appears on the last focused window instead of the window that started the auth flow

**Comment by bpasero** [comment]
I can reproduce and suspect an issue with that URL forwarding in electron-main. I am passing this on to @joaomoreno who implemented that.

The callback URL correctly carries forward the window ID parameter it seems:

`vscode-insiders://github.vscode-pull-request-github/did-authenticate?windowId=3&code=<CODE>&state=<STATE>`

**Comment by bpasero** [comment]
@joaomoreno is this an issue with the active client ID? The window ID is just the number (as string), but [`getActiveClientId()`](https://github.com/microsoft/vscode/blob/f78117edcf957b1af972724f19e9d43b37164746/src/vs/code/node/activeWindowTracker.ts#L46) returns `window:<number>`?

**Comment by joaomoreno** [comment]
Yes, you must be aware that the `ctx` is whatever you pass in here: https://github.com/microsoft/vscode/blob/ad9bce89782a7badd56ab3654a167727f6f1b033/src/vs/platform/ipc/electron-browser/mainProcessService.ts#L33

**Comment by joaomoreno** [comment]
@RMacfarlane Could you re-verify this this week? Thanks!
