### ISSUE TITLE
This snippet has no sense

### ISSUE THREAD

**Issue by sguillia** [microsoft/vscode#79648]
I am writing Typescript code with all extensions disabled on code-insiders.

I wanted to call my function `openSite()`.
When typing `openSite`, I have some weird autocompletion suggestion.
When typing the open bracket `(`, it replaces my function call to something I didn't expect, and automatically adds an import to my file.

![Capture du 2019-08-22 16-34-29](https://user-images.githubusercontent.com/15984272/63523840-2b12d280-c4fb-11e9-8c34-5e37e41d48c9.png)
![Capture du 2019-08-22 16-35-04](https://user-images.githubusercontent.com/15984272/63523848-2cdc9600-c4fb-11e9-8dce-785c165ac338.png)

I don't know about `SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION`, never heard about it.

I don't know what causes that autocompletion: an alias? a snippet? something else?

Since I don't know what causes it, I can't disable it. I would have expected to find a button `disable`, or to be able to disable _aliases_ or something. After 5 minutes of googling, I failed to disable that undesirable completion.

1. How is this features called?
2. How can I disable it?
3. Can I disable it globally / only for Typescript / only for `SSL_...`?
4. Why do I have that completion?
Look at the screenshot, it matches `openSite` with random unordered letters in the constant.
5. Can I force completion to only show suggestions when what I type starts with the constant?
Example: Suggest `SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION` only if I start typing `SSL_`...

Feel free to update the title of this issue

Thank you

**Comment by usernamehw** [comment]
https://github.com/microsoft/vscode/issues/75500#issuecomment-507172728

**Comment by IllusionMH** [comment]
1. This is type alias from package or module `constants` (you should check your `node_modules` folder or files that are referenced in your `baseUrl` or `paths` sections)
2. and 3. If `constants` is file in your project - exclude it if needed, otherwise it will stay. If its from `node_modules` but not referenced in`package.json` - wait for https://github.com/microsoft/TypeScript/pull/32517
4. Because it was resolved by TS and `openSite` wasn't (you should be sure that TS includes file with `openSite` in program).
Suggestions, Quick open, highlight/filter in explorer use fuzzy match which requires that string contain all characters in same order as query, but doesn't require exact substring match (it saves a lot of time if yo have long name like `createConnectorForSelector` so you can type `ccfs` and most likely it will be near the top of matches)
5. Not sure if it is optional

As for accepting completion on `(` - most likely you have **Editor: Accept Suggestion On Commit Character** (`editor.acceptSuggestionOnCommitCharacter`) enabled

Are you sure that TS Program includes your file with `openSite`? It would be first in list, but not matches at all.

**Comment by andrewbranch** [comment]
@IllusionMH is correct. Also, if you want to disable auto-imports entirely, you can search for this in VS Code settings:

![image](https://user-images.githubusercontent.com/3277153/63546193-0825f580-c4de-11e9-871c-f55fc1a23b0f.png)

**Comment by sguillia** [comment]
Thank you, your answers are useful
