### ISSUE TITLE
Can't peek, find all, go to definition/references across project.

### ISSUE THREAD

**Issue by ShaCP** [microsoft/vscode#79656]
- VSCode Version: 1.37.1
- OS Version: Windows 10

Steps to Reproduce:

1. Try to use any of these features on a variable/function with definition or references in a different file.

It will only find them if they are on the current file.

Does this issue occur when all extensions are disabled?: Yes/No

Yes.

I tried using a jsconfig.json to include all js files like I've seen suggested but it did not work.

**Comment by RMacfarlane** [comment]
@ShaCP I'm having trouble reproducing this, can you give a small code sample of what the files look like?

**Comment by ShaCP** [comment]
@RMacfarlane 

This is the code:
https://github.com/tastejs/todomvc/tree/gh-pages/examples/vanillajs

If I go to view.js in VS Code and try to go the definition of $delegate, it won't give me any results.

I downloaded Sublime Text 3 just to see if it has a similar feature, and it correctly shows where $delegate is defined and where it's referenced.

**Comment by mjbvz** [comment]
As your code seems to use global variables to manage references instead of imports, as a first step try creating create a [jsconfig.json](https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson) file.

However even this will probably not fix cross file the intellisense for that project as the code is quite dynamic (such as taking `window` as a parameter and setting globals on this value). Supporting proper intellisense for cases like that is very difficult and we do not think it is worth the investment (sublime's out of the box behavior essentially does fancy symbol matching, which can provide an acceptable user experience sometimes but is very different than the more comprehensive way in which our intellisense works).

**Comment by ShaCP** [comment]
I already said I tried creating a jsconfig.json and it did not work. I saw in the VS code page that it might not work if the code was "too dynamic", but wasn't sure if this code was considered dynamic enough to break intellisense. Guess it was. Thanks.
