### ISSUE TITLE
Test multi select in custom trees

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#79819]
Test for #76941

- [x] AnyOS @alexandrudima
- [ ] AnyOS @isidorn

Complexity: 3

The `TreeViewOptions` `canSelectMany` API was finalized this iteration. See the documentation in vscode.d.ts.
Tree view sample to use a starting point if you want: https://github.com/microsoft/vscode-extension-samples/tree/master/tree-view-sample
- Verify that by default, custom tree views do not have multi select enabled and that commands on the tree items still work.
- Verify that if you enable multi-select in a tree view using the API but otherwise don't change the tree, that the commands that work for the tree without multi select still work with multi select. Verify that the commands still work even when you select multiple.
- Verify the parameters to commands when selecting multiple and then executing one of the tree commands. The first parameter should be the item that the command was executed on. The second parameter should be an array of all other selected items. Verify that the documentation is vscode.d.ts makes this clear.
- Verify that you can execute commands on multiple items through the context menu.
- Verify that you can execute commands on multiple items through the inline actions.

**Comment by isidorn** [comment]
The works nice overall. Filled some issue regarding command arguments which I think we should tackle.
Also note that multi selection and passing focus is a bit hard. So if the custom tree never preserves focus it is very hard for it to support multi select.
And on top of that we do not differentiate between double vs single click in custom views, so a lot of extensions like to pass focus on single click (since they do not know if it is a double click).
That is not a good combination with multi select so we should just keep that in mind.

Maybe it is time to revisit if we expose double click to custrom trees. I am not sure what was the original design decision @sandy081

**Comment by sandy081** [comment]
Yeah we do not expose double click gesture to extensions and no plans to do that. 
I think during multi-select we shall not be running single node select command.

**Comment by isidorn** [comment]
@sandy081 I know we don't expose the double click, but I do not know why? What is the decision behind this?

It is very hard to even get into the mutli-select situation with this, so heuristics while in multi-select do not really make sense.

**Comment by sandy081** [comment]
Here is the issue for double click and we closed https://github.com/microsoft/vscode/issues/39601. There is no ask for this 

> There should be only one command and executing this command on single click or double click is up to application. There is a setting workbench.list.openMode to configure this behaviour.

But if it is needed after enabling multi-select we can revisit.
