### ISSUE TITLE
Scrollbar does not hide when the mouse leaves the window through the right edge

### ISSUE THREAD

**Issue by eldenchen** [microsoft/vscode#79857]
Issue Type: <b>Bug</b>

Steps to Reproduce:
1. open a project/folder
2. move mouse into Editor and then move it out from right edge of the window
3. hide Activity Bar
4. move mouse into Side Bar and then move it out from left edge of the window

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:16:34.800Z)
OS version: Darwin x64 18.7.0

**Comment by itamark** [comment]
The issue seems to be in `addDisposableNonBubblingMouseOutListener`, but I am not sure what the difference is between that edge of the editor and the others. For some reason the mouseLeave event is not being fired on the right-hand side. It seems it thinks the `toElement` is the same as the `node` initially given - which means the leave event is never fired.
@alexandrudima I'm happy to keep digging into this if that's ok.
