### ISSUE TITLE
Text in integrated terminal is not a good color with Solarized Light theme

### ISSUE THREAD

**Issue by kylrth** [microsoft/vscode#79905]
Check this out:

![bad_color](https://user-images.githubusercontent.com/5044802/63769918-995bea00-c899-11e9-8da6-946896a71786.png)

I can barely see the text from the terminal. I'm using bash, and here are the lines from my `.bashrc` having to do with coloring:

```bash
# session coloring
cyan=$(tput setaf 6)
blue=$(tput setaf 4)
white=$(tput setaf 7)
PS1='\[$blue\]\u@darwin: \[$cyan\]\W\[$white\]\$ '
```

You can see that any text after the prompt will be colored white as well, which is what's causing the issue. Adding `\[\033[00m\]` after the `$` fixes this problem, but what's strange is that this is the only light theme that does not override my bad setting. If I switch to Quiet Light, Light+, or any of the others, the terminal text color is black despite my settings.

- VS Code version: 1.37.1
- Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
- Date: 2019-08-15T16:17:25.463Z
- OS: Linux x64 4.15.0-58-generic snap

**Comment by Tyriar** [comment]
You're setting the text to white:

> white=$(tput setaf 7)

So it's displaying in what the solarized theme defines as white, see the table in "The Values" section which defined what is displayed in the terminal https://ethanschoonover.com/solarized/ (#e4e4e4).

In general you should stay away from using black and white because contrast could be bad like this. Prefer default and inverse instead.
