### ISSUE TITLE
[html][css] [custom data] Custom data settings: User level setting

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#79911]
Testing microsoft/vscode#79843

- no indication that the setting can only be in the workspace settings
   - html custom description mentions it (css does not), but that's very hidden
   -> I suggest to also allow if for user settings
- no indication if path needs to be relate, absolute or URI
- no indication that reload is needed

**Comment by aeschli** [comment]
> What's a case when this would be useful in a user setting?

The main motivation is to simplify the setting. Both me and @egamma struggled when trying the setting as we tried it first as a user setting and nothing happened.
Can be useful for users that use VSCode as single file editor (no workspace), don't work in teams and for demoing and testing purposes. 
User will figure out how to use this setting.

**Comment by octref** [comment]
@aeschli I feel a better way is to guide them to open a [sample folder](https://github.com/microsoft/vscode-custom-data/tree/master/samples) to play around. That's not much harder than crating a JSON file somewhere, figuring out its path and add it to settings (after which you'll have to clean it out when writing real HTML, since `<foo` is an invalid tag).

There's no way to add workspace-only settings, and as a result you see no warnings and could wrongly use this setting. I opened #80073 for another setting scope.

**Comment by aeschli** [comment]
Custom data is really just assisting the user in code assist or hover. It's the user that decides what tag or attribute (s)he picks. No harm when there's a proposal that doesn't apply as with other (static) proposals we already give as we are not context sensitive. 
It's the same when adding custom data through an extension. You will see certain proposals in files where they don't necessarily apply.

Getting custom data through an extension is similar to getting it from a user settings.

I don't think having it as a user setting is a good idea, but maybe that's exactly the user wants, or if not, he will figure it out and only set the paths in workspace settings or switch to extensions.

What we currently have is just unnecessarily limiting and adds confusion.

**Comment by aeschli** [comment]
a while back I changed that the setting can also be a user setting and reload is o longer necessary

https://github.com/microsoft/vscode/commit/2e5b0824d1d3c1114a6f7fc36f9694723c86fc9c#diff-dddc60db8e61be98e3b09ace91b34114c8bef6e4386da4742c000c38da3fccf5
