### ISSUE TITLE
Deprecated completions: Show strikethrough across icons or don't show at all

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#79945]
Testing #79814:

![image](https://user-images.githubusercontent.com/4033249/63810050-ab10b200-c8d8-11e9-9c00-58d77debd432.png)

These strikethroughs are too thing and don't go all the way through. If we do add a strikethrough I hope it can be more clear.

Alternatively we can also remove it for now, so they stay consistent with deprecated symbols where the icons are not affected by `deprecated`.

![image](https://user-images.githubusercontent.com/4033249/63810157-eca15d00-c8d8-11e9-97a6-c32954abccfb.png)

![image](https://user-images.githubusercontent.com/4033249/63810161-f0cd7a80-c8d8-11e9-997c-b56a94ae05a3.png)

**Comment by jrieken** [comment]
Yeah, that half strikeout shouldn't happen. Today it should only be the word, that's because the icons comes as background images of a ::before-elements which text content isn't wide enough. For now, I will make sure that suggest looks like the others, later, once we have an icon font, we can revisit this.
