### ISSUE TITLE
Support pasting a file into VS Code

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#79978]
- in macOS Finder select a file and from the context menu do a `Copy "file"`
- in the VS explorer select a folder and open the context menu

Observe:
the "Paste" action is dimmed (disabled)

Since it is possible to drag-n-drop a file from the Finder into VS Code, doing the same with "Paste" should be supported as well.

**Comment by isidorn** [comment]
I think there is not electron api for us to do this.
Since dragging a file from the finder fills in the correct drag data which we can extract.
However the `Copy "file"` command does not do that, and we have no access to the copy clipboard from electron.

Though I might be wrong so assignign to September to investigate

fyi @bpasero @deepak1556

**Comment by bpasero** [comment]
I have not looked into this for a while, but see https://github.com/microsoft/vscode/issues/164 as related/duplicate.

**Comment by isidorn** [comment]
Yeah dup of that. Assigning myself to that one and to September to investigate if we can improve seomthing there
