### ISSUE TITLE
Close dirty editors: Provide fast action to save all or revert all

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#8009]
- VSCode Version: Latest insiders
- OS Version: OS X

Steps to Reproduce:
1. I have quite number of dirty files in the editor (say > 10)
2. When I use Close All action, I am getting a confirmation dialog for each file. Instead, I should be able to close all files at once with/without applying edits.

**Comment by bpasero** [comment]
Not trivial with our current model of handling dirty editors.

**Comment by bpasero** [comment]
@sandy081 @alexandrudima ping, since you reported this and similar issue. I decided to change the way our "Close All Editors" action work and instead of asking for individual files to confirm saving, show the combined confirmation dialog (the same you get on shutdown without hot exit enabled).

I am not 100% sure this is the best fix because some people might expect our current behaviour and would want a separate action for it. Though I find it elegant to show the combined confirmation when you actually invoke the "Close All Editors" action.

Note that this does not change the behaviour of the "Close All Editors in Group" action, nor the other close related actions (e.g. "Close Others").

/cc @Tyriar since this is for a better hot exit experience

**Comment by Tyriar** [comment]
I like it, if people need to discard some at this point they can cancel and discard.

**Comment by bpasero** [comment]
* [ ] **To verify:** 
Invoking the "Close All Editors" command shows you a prompt for any dirty file that can quickly be used to dismiss or save all dirty.

**Comment by Tyriar** [comment]
Works great :+1: 

@bpasero the message box may look better if the list of files is in the description part of the message box rather than the title?

**Comment by bpasero** [comment]
Yeah good point, I can look into that. Might only have a visual difference on macOS though.

**Comment by xconverge** [comment]
Unfortunately this still doesn't fix the desired use for the vim plugin

q! should quit no matter what is dirty or not dirty

Do you have any reccomendations for this?

**Comment by xconverge** [comment]
@bpasero Any ideas on how I can do this and skip the prompt entirely?

**Comment by bpasero** [comment]
@xconverge that should work as long as hot exit is enabled in settings

**Comment by xconverge** [comment]
But I want the feature of hotexit + revert all changes so that's why I don't think hot exit is the solution. 

In vim q! Is quit no matter what, if documents aren't saved then they are reverted and closed automatically

**Comment by bpasero** [comment]
@xconverge I see, you want a command that quits the application after reverting all dirty changes?

**Comment by xconverge** [comment]
Yes and quits silently. In vim you can do quit and have it prompt you to save dirty editors OR you can do a force quit which just closes everything silently and does not remember any of the unsaved changes at all.

**Comment by bpasero** [comment]
@xconverge ok this sounds like a new feature request that should get a separate issue, can you create one with a good description?

**Comment by xconverge** [comment]
Sure, this was the issue that was referenced before you guys implemented hotexit, you can see the VSCodeVim ticket referenced in October up above. I can create a new ticket though

**Comment by bpasero** [comment]
It seems to me this issue has nothing to do with the VIM use case (hence all my questions).
