### ISSUE TITLE
Visualize Linebreaks With "CRLR" or "LR"

### ISSUE THREAD

**Issue by YuriySamorodov** [Microsoft/vscode#801]
Hello,

Please add option to visualize line breaks with CRLR or LR as it is done in Notepad++

Thank you,
Yuriy

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

P.S. If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
