### ISSUE TITLE
Opening settings editor with prefilled query is broken

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#80134]
- Open extension viewlet
- Right click an extension
- "Configure Extension Settings"
- Settings editor opens with no query prefilled

Broken by https://github.com/microsoft/vscode/commit/e02ccd0715c8d8ada53eac2c83160e90f66d2b53, now the editor service is stricter.

So the preferences service was basically doing

`editorService.openEditor(input, { query: query })`

Now this only works with properties that are in IEditorOptions or ITextEditorOptions, or an instance of EditorOptions. I have SettingsEditorOptions which is a subclass of EditorOptions and am using that everywhere else that the prefs service opens the settings editor. Or I would need the editor service to know about SettingsEditorOptions specifically but I don't want to do that.

In theory this could affect something else but I looked around and don't see other editor options types to worry about.

**Comment by roblourens** [comment]
FYI @bpasero, I think the editor service change is fine, if you disagree we could fix that end instead.

**Comment by bpasero** [comment]
@roblourens I don't think that commit has any impact, but I remember another one where you were using `IEditorGroup.openEditor()` instead of `IEditorService.openEditor()` and that change probably requires you to pass in typed options, which I think is a good change. 

Do not forget to push this to `master` as well.
