### ISSUE TITLE
VS-Code recommends PowerShell extension when 'PowerShell Preview' extension is installed

### ISSUE THREAD

**Issue by bergmeister** [microsoft/vscode#80178]
This is a follow up from the PR comment below of PR #77573 as changes need to be made outside this repository. cc @sandy081 @TylerLeonhardt 
https://github.com/microsoft/vscode/pull/77573#issuecomment-513157642

**Comment by sandy081** [comment]
@bergmeister As already asked before, have you guys thought about using same extension for preview/insiders instead of separate extension. 

We follow a similar approach for our remote container and remote wsl extensions. @chrmarti @aeschli Is there a wiki/documentation on how we do preview for these extensions?

**Comment by chrmarti** [comment]
I don't think we have documented this:

We have published extensions for VS Code Insiders only by requiring the VS Code Insiders version in the extension's package.json's `engine` property. That version of the extension then cannot be installed into VS Code Stable and VS Code Stable simply keeps (or installs) the last version of the extension that required a compatible VS Code engine. When the VS Code Insiders version number then is released as the new VS Code Stable, these extension versions immediately become available for VS Code Stable too.

There is currently no way to hold back some versions of an extension as 'VS Code Insiders only' when the version number of the current Insiders becomes available as VS Code Stable.

**Comment by TylerLeonhardt** [comment]
>  As already asked before, have you guys thought about using same extension for preview/insiders instead of separate extension

It's all a part of [this issue on release channels](https://github.com/microsoft/vscode/issues/15756#issuecomment-457010235)

The VS Code marketplace and/or VS Code itself do not offer a friendly way to release an "insiders" version of extensions and the best way of doing it is to ship another extension called "Preview" or "Nightly" or similar.

> We have published extensions for VS Code Insiders only by requiring the VS Code Insiders version in the extension's package.json's engine property. That version of the extension then cannot be installed into VS Code Stable

I think @sandy081's question is more so "how does the VS Code team implement 'preview' or 'nightly' versions of extensions?" Rather than "how do we only ship for insiders?"

@sandy081 not sure who it is but the VS Code team ships a [js/ts nightly extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) in the same fashion. This seems to be the best option today... But from experience, it's very painful to maintain, confuses customers, and isn't very discoverable.

**Comment by sandy081** [comment]
> I think @sandy081's question is more so "how does the VS Code team implement 'preview' or 'nightly' versions of extensions?" Rather than "how do we only ship for insiders?"

Yes, at present we ship some of our extension previews only for insiders. I agree that there needs to be a support for this feature in VS Code. Here is an open request for that - https://github.com/microsoft/vscode/issues/15756

w.r.to recommendations we will see if we can implement to check if one of the extensions is already installed.

**Comment by TylerLeonhardt** [comment]
> Here is an open request for that - #15756

Yeah this the the big one that would save extension devs a lot of time. Our team was burned by that recently when we slipped and accidentally released a preview extension to the stable extension - I had to get ahold of the marketplace team and everything to mitigate the issue. Our extension was unlisted for like 3 days.

That said, this issue is not about that. This issue is requesting something like this:

"VS Code should _not_ recommend anything if EITHER _-this-_ extension or _-that-_ extension"

does that make sense? It's a generic problem. Might be worth changing the title.

**Comment by TylerLeonhardt** [comment]
@bergmeister I just meant that the title is specific to PowerShell but this issue is generic.

**Comment by bergmeister** [comment]
Yes, but since VS Code already has custom code hard coded to the PowerShell extension I'd like to get this fixed quickly by adding the preview extension as well.
The higher level issue with preview extensions is already in another issue that will probably take a long time to get resolved....
Can we please get traction on this issue.

Generally speaking, I am very annoyed by a handful of notifications by VS-Code that I cannot turn of. When I open a repo, I get about 5 notifications, this being just one of them (I had to disable other extensions like the terraform extension that keeps asking me to install preview features, many other extensions have similar noisy behaviour as well).

**Comment by chrisdias** [comment]
There is no custom/hard coded support for the PowerShell extension, it uses the same recommendation system as every other extension we recommend. In this case, we recommend only 1 extension based on `.ps1` files and that is the `ms-vscode.PowerShell` extension.  It is an "important" recommendation so you get a prompt immediately.

Now, I could prompt for the PowerShell "Insiders" extension instead of Stable in VS Code Insiders if you want, i just need the extension ID please. So in this case, VS Code Insiders users would be prompted for the PS Insiders extension and the VS Code Stable users would be prompted for the PS Stable extension.

**Comment by bergmeister** [comment]
yes, please. This would be a small but useful improvement to the situation

**Comment by chrisdias** [comment]
id is `ms-vscode.PowerShell-Preview`

**Comment by BoSorensen** [comment]
When backing up settings from both VSCode and VSCode Insiders with [the Settings Sync extension](https://github.com/shanalikhan/code-settings-sync) to the same Gist, that seems to be a bad idea in part due to VSCode that will suggest 'PowerShell' extension and VSCode Insiders that will suggest 'PowerShell Preview' extension.

So i guess settings from VSCode and a VSCode Insiders can not be stored in the same Gist ?

**Comment by bergmeister** [comment]
@BoSorensen Can you expand please. It suggest to put the union of setting for normal and preview extension in your synced settings because if a setting does not exist in either version, it should not cause a problem. I am not aware of a setting that would need to be different depend on whether one uses the normal or the preview version of the PS extension

**Comment by BoSorensen** [comment]
@bergmeister You are right, in VSCode insiders 1.44.0 it will suggest the PowerShell Preview extension when the PowerShell extension is already installed. While somewhat annoying, that message can be hidden, so its entirely possible to store settings for both Insider and non-Insider builds in same Gist.

**Comment by sandy081** [comment]
I would still think the right way here is to wait until Marketplace supports for beta extensions and they are thinking about it.

Regarding recommendation notifications, we have changed them to be less aggressive. For eg., when you receive a recommendation after opening a file and checking for the extension is enough to not to show this notification again. So in this case, when you receive a recommendation for Powershell extension, click on show recommendations button in the notification and you do not see it again.

Please revalidate the scenario with above flow and reopen the issue if you still see concerns.
