### ISSUE TITLE
[FIX] MacOS: "shift+cmd+left/right" not recognized [Dup #62810]

### ISSUE THREAD

**Issue by brucejo75** [microsoft/vscode#80182]
This is a solution to #62810 (which is closed and locked).
On MacOS I was not getting the `shift+cmd+left/right/up/down`to work.

### Environment
MacOS: 10.14.6 Mojave
VSCode: 1.37.1

### Repro:
1. Open VSCode
2. Go to `Code->preferences->keyboard shortcuts`
3. Click on keyboard symbol on far right.
4. press `shift+cmd+left/up/down/right`.

**Result**: none of them are interpreted. All that is displayed is `shift+cmd+`

### Fix:
Hunted around...
Discovered that Mission Control was using all of these keys.  So I remapped them all to other Function keys (that I do not use in editing).

There are 2 places to check:

1. `System preferences->Mission Control`
2. `System preferences->Keyboard->Shortcuts->Mission Control`

After remapping, it still did not work!

Close and **restart Visual Studio Code** and then it works!

Posted here so others do not have to struggle with this.

**Comment by brucejo75** [comment]
This is a posted fix, so it can be closed.

**Comment by mergesort** [comment]
@brucejo75 @alexandrudima Thank you for the suggestion! I wish I could say that was the fix, but it did not fix it for me in fact, probably because I don't use the default bindings for Mission Control. I've searched all my keyboard shortcuts and haven't found one that conflicts with VS Code.

On top of that, I suspect it's VS Code specific, because when I go to keyboard shortcuts and enter record mode, tapping "right" works fine. But tapping "cmd + shift" it refuses to register left or right afterwards. This is a screenshot of what I see when doing that.

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/716513/64479654-edaf7580-d187-11e9-9867-03865b695ffb.png">

**Comment by brucejo75** [comment]
@mergesort, bummer!

I had **exactly** the same symptoms.

Once I removed all conflicts in programs here `System preferences->Keyboard->Shortcuts` the keys started passing into VSCode.

In `System preferences->Keyboard->Shortcuts` did you select `All controls`? v. `Text boxes and lists only`?  To make sure you are searching for all shortcuts?

**Comment by brucejo75** [comment]
PS: the fact that VSCode is not showing the full keystroke is an indicator that the Mac is somehow intercepting it.  Maybe another program elsewhere...

**Comment by brucejo75** [comment]
Plus remember to stop VScode and restart it!

**Comment by mergesort** [comment]
Well I'll be damned. Even though it wasn't set to a conflicting key command, I remapped Mission Control's spaces switching from `⌘ + left` and `⌘ + right` to nothing, then set it back to those settings and now it works after all this time. Thanks a ton @brucejo75!
