### ISSUE TITLE
"initializing the JS / TS language resources" stuck

### ISSUE THREAD

**Issue by mydmdm** [microsoft/vscode#80183]
Issue Type: <b>Bug</b>

The status stucks on "initializing the JS / TS language resources" for a long while, and it disable other linting features such as python linting

VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
alignment|ann|0.3.0
spellright|ban|3.0.46
markdown-mermaid|bie|1.2.0
vscode-pandoc|Dou|0.0.8
gitlens|eam|9.9.3
vscode-toggle-column-selection|eri|1.0.6
gc-excelviewer|Gra|2.1.32
markdown-extended|jeb|1.0.11
markdown-index|leg|0.0.8
restructuredtext|lex|114.0.0
align-vertically|mat|0.2.0
prettify-json|moh|0.0.3
python|ms-|2019.8.30787
remote-wsl|ms-|0.39.2
autodocstring|njp|0.3.0
tabnine-vscode|Tab|2.1.11
vscode-icons|vsc|9.3.0
markdown-all-in-one|yzh|2.4.2

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all extensions disabled?

**Comment by Vigasaurus** [comment]
From my testing - this issue seems to only be related to WSL (maybe 2.0) and `node_modules` together.

In Insiders v1.39.0 on a fresh install there were no issues on a specified project of mine (about 1GB, 60MB `node_modules`), as well as a smaller project (no `node_modules`, only about 15MB). 
Once loaded into WSL with `Remote WSL` extension, a small project (no `node_modules`, only about 15MB) worked perfectly. The same first project (about 1GB, 60MB `node_modules`), didn't load (over 15 minutes). This is the tail of the Typescript server logfile
![image](https://user-images.githubusercontent.com/19434157/64529777-3fafe280-d2d1-11e9-832a-2dbb95e9e730.png)

**Comment by mjbvz** [comment]
@Vigasaurus Please open a separate issue. Can can email the log to: matb at microsoft

**Comment by mjbvz** [comment]
Closing as more information is needed from the original poster
