### ISSUE TITLE
Why does --inspect-brk=port automatic add to console?

### ISSUE THREAD

**Issue by KhalitovAdel** [microsoft/vscode#80224]
- VSCode Version: 1.37.1
- OS Version: UBUNTU 19.04

Steps to Reproduce:

1. I have some launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Start",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/server.js",
            "stopOnEntry": false,
            "runtimeExecutable": "${workspaceRoot}/node_modules/nodemon/bin/nodemon.js",
            "restart": true,
            "runtimeArgs": [
                "--exec", 
                "${workspaceRoot}/node_modules/.bin/babel-node --max_old_space_size=2000 --es_staging --inspect",
            ],
            "console": "internalConsole",
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Listen",
            "restart": true,
            "env": { "CI": true },
            "disableOptimisticBPs": true
        },
    ],
    "compounds": [
        {
            "name": "Do it",
            "configurations": ["Start", "Listen"],
        }
    ]
}
```
2. When I start "Start" debug script in my console I see that:
```
/home/adel/Documents/Projects/mobishop/mobishop.server/node_modules/nodemon/bin/nodemon.js --exec '/home/adel/Documents/Projects/mobishop/mobishop.server/node_modules/.bin/babel-node --max_old_space_size=2000 --es_staging --inspect' --inspect-brk=15227 server.js 
```

When I comment all in runtimeArgs tag, I can see that:
```
/home/adel/Documents/Projects/mobishop/mobishop.server/node_modules/nodemon/bin/nodemon.js --inspect-brk=33855 server.js
```
How I can fix it?

**Comment by weinand** [comment]
What do you want to achieve?

**Comment by weinand** [comment]
The purpose of launch configurations is debugging. For that reason debug extensions have to pass all the necessary arguments to the target in order to enable debugging.
That's the reason why the Node debug extension passes by default a `--inspect-brk=nnnnn` to the target.
If you want to override this behavior, you can manage the debug port yourself: just add a `"port": nnnnn` attribute to your launch config and communicate that port to your traget program yourself.

See https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-support-for-npm-and-other-tools:
> If you specify a debug port via the port attribute, VS Code will not automatically add the --inspect-brk=nnnn attribute because the debug port is typically specified by the npm script or other tool as well.
