### ISSUE TITLE
[git extension] open a file when double clicked in the source control view

### ISSUE THREAD

**Issue by ryenus** [microsoft/vscode#80307]
For changed files in the **Source Control (Git) view**, when a file is clicked, currently there's no difference between single-click and double-click, both open the diff view for that file.

It would be nice if the file can be opened when **double-clicked**, as if **`command.openFile`** is triggered, rather than `command.openChange`.

**Comment by joaomoreno** [comment]
> It would be nice if the file can be opened when double-clicked, as if command.openFile is triggered, rather than command.openChange.

This is impossible to do without adding a delay to the single click... otherwise we would always open two editors on double click. Additionally, the open file action is there on every row specifically as a single click action. Closing this as won't implement. Sorry!

**Comment by ryenus** [comment]
@joaomoreno 

I guess single-click and double-click are already differentiated by the operating system, isn't it?

And yes, I know there's a little icon I can click to open the file. The reason I'm proposing this is that it's much easier to double-click on the entry row in contrast to click on the little icon.

Would you please consider? I'm thinking we just need to register a double-click event in the right place,  just I've not yet figured where it is. If that's the case. Could you please share some tip so maybe I can give it a try?

Nevertheless, being proved wrong to me is not a bad thing at all, thank you all the same.

**Comment by joaomoreno** [comment]
> I guess single-click and double-click are already differentiated by the operating system, isn't it?

They are, that's not the problem. Here's the classic description of the click vs double click problem: once a click happens, how long does the application wait for another click in order to understand the whole action is indeed a double click? This is OS specific, but let's say it's 200ms. This means that either:

- Once the user clicks we must wait 200ms to *Open Changes* because another click might come and we should *Open File* instead;
- Or, we simply *Open Changes* on first click and bite the bullet if another click comes in under 200ms and *Open File* as well then, thus doing much more than the user intended.

Neither is a good solution, that's why it's always a bad idea to assign different actions to both click and double click.

This problem is noticeable in macOS for example: two-finger tap opens a context menu. But you should notice the lag when one enables two-finger double tap to zoom-in (Smart zoom) in the Trackpad settings; suddenly the two-finger tap feels sluggish and slow.

**Comment by ryenus** [comment]
May be this helps?
```js
const isDoubleClick = (origin === 'mouse' && event.detail === 2);
```

Source: https://github.com/microsoft/vscode/blob/871a6fefd79df1266d39e3f66d324d528ea1f2e6/src/vs/base/parts/tree/browser/treeDefaults.ts#L206
