### ISSUE TITLE
Add Mac OS Services menu option to Explorer right click menu

### ISSUE THREAD

**Issue by jreljac** [microsoft/vscode#80345]
[Mac OS Services](https://developer.apple.com/design/human-interface-guidelines/macos/extensions/services/) "let people access functionality in one app from another"

Currently I have a number of file related services that are available when I am in Finder that would be even more useful if I could access right from Visual Studio Code's Explorer panel.

Currently, the work flow I use is
- Edit code
- Open explorer
- Right click...Reveal in Finder
- Right click in Finder...Services...select the desire service.

It would be snazzy if I could
- Edit code
- Open Explorer
- Right click...Services...select the desired service

**Comment by isidorn** [comment]
For me this feels out of scope and will not be a part of vsode.
Extensions should look into adding this to the explorer context menu since it is contributable. However I am not sure if and how the extensions can trigger the Mac OS Services.
Anyways vscode can not trigger the Mac OS Services since this is not supported by Electron as far as I know.
