### ISSUE TITLE
Name is not suitable to be abbreviated

### ISSUE THREAD

**Issue by MortimerJarasemy** [microsoft/vscode#80367]
- VSCode Version: unrelated
- OS Version: unrelated

Steps to Reproduce:

1. Look at program tittle

The issue is the following the abbreviation **VS** is far too culturally extended that **VS stands for versus**, not visual studio and hence, me and what I figure is also many other people read Versus Code, this is so ingrained in our culture I am suprised nobody has signaled this before.

I think it is an error to present this in such manner.

**Comment by chrisdias** [comment]
We try to use the full name `Visual Studio Code` wherever possible in the product itself and on the website. In the documentation we try to use `Visual Studio Code` first, and then we sometimes abbreviate it to "VS Code" after that. 

If you find places we use `VS` instead of `Visual Studio` please let us know exactly where.
