### ISSUE TITLE
API: Allow extensions to provide file watching on file:// scheme

### ISSUE THREAD

**Issue by pelmers** [microsoft/vscode#80431]
Context:
I am working with a network-based filesystem mounted locally that does not support file watching through the builtin `diskFileSystemProvider`. Therefore I would like to provide watch() functionality through my extension.

Currently the only way an extension can provide file watching capability is through the FileSystemProvider API. Today, attempting to add a FileSystemProvider for the file:// URI scheme leads to an error: `a provider for the scheme 'file' is already registered`.

Proposal:
I can picture a couple of ways to enable my use case:
1) (I prefer this one) Lift the FileSystemProvider's restriction on the 'file' scheme. This would involve removing 'file' from the list of pre-registered schemas [here](https://github.com/microsoft/vscode/blob/b283b2978139ea12cee702164bd991f055e3fb92/src/vs/workbench/api/common/extHostFileSystem.ts#L168) on extHostFileSystem.ts. I believe the provider itself is registered  at `electron-main/app.ts`:
https://github.com/microsoft/vscode/blob/b283b2978139ea12cee702164bd991f055e3fb92/src/vs/code/electron-main/app.ts#L430-L431

2) Add a new 'registerFileWatcher' proposed API, similar to the existing textSearch/fileSearch proposals, to enable an extension to solely provide the file watching capability for a given scheme.

Tradeoffs:
Approach 1 offers the most generic approach that I believe would be useful to other extension authors as well. However it requires an extension to implement all FileSystemProvider methods, even if it only needs to replace default behavior for a subset of them. It also could lead to the possibility of extensions conflicting and fighting to register the 'file' provider. Approach 2 lessens these downsides but it leads to ambiguity in resolving the watch capability, since it could be provided in 2 places in the API.

cc @aeschli

**Comment by jrieken** [comment]
> Approach 1 offers the most generic approach that I believe would be useful to other extension authors as well.

TBH we aren't very keen on that because we load files (from disk) before loading extensions and will add the possibility for extensions to slow everything down. While that is possible for other files it's not as severe (because less common).

> I am working with a network-based filesystem mounted locally that does not support file watching through the builtin diskFileSystemProvider.

It looks like that's the problem here and I don't believe exposing more or different API is the answer. Why don't you contribute back your watch logic? Is that so special that it only applies to your machine/setup?

**Comment by pelmers** [comment]
> Why don't you contribute back your watch logic? Is that so special that it only applies to your machine/setup?

My project uses [watchman](https://github.com/facebook/watchman) for file watching, I'd be happy to contribute a new WatchService to DiskFileSystemProvider, does that sound reasonable?

**Comment by jrieken** [comment]
Letting @aeschli, @bpasero, and @Tyriar decide. They were all in the file watching business...

**Comment by Tyriar** [comment]
We considered using watchman briefly, I think at that point we already had 3 file watchers and no resources to look into it further, one thing I recall is that we would need to do some additional packaging work to get watchman to work as the JS lib expected the native lib to be installed separately.

Related: https://github.com/microsoft/vscode/issues/77143

**Comment by bpasero** [comment]
@pelmers 

> My project uses watchman for file watching, I'd be happy to contribute a new WatchService to DiskFileSystemProvider, does that sound reasonable?

Last I checked, watchman is quite a big binary to run (even a Windows Service on windows?). Can you share more details about the distribution size of such an approach?

**Comment by pelmers** [comment]
@bpasero My initial thought is this watcher would only be used if we detect watchman already installed on the system, or if the user sets in their config a path to the binary.

**Comment by Tyriar** [comment]
@pelmers that would make our problem of too many file watchers even worse.

**Comment by pelmers** [comment]
@Tyriar  thanks for your feedback, which do you think is the best way to support the watchman use case: extension-provided watch capability or built-in watchman support? 
cc @mostafaeweda

**Comment by wez** [comment]
(Hello, I work on Watchman and EdenFS at FB!)

Just to clarify; vscode doesn't need to (and honestly, really should not) ship the `watchman` binary.  The [fb-watchman](https://www.npmjs.com/package/fb-watchman) client package has no native code to compile and is pretty small and should be easy to embed.   Its only dependency is [bser](https://www.npmjs.com/package/bser) which also has no native code to compile.

The strategy used by most consumers is to try using `fb-watchman` first and then fall back to an alternate watcher if `watchman` isn't installed.

It's probably also worth explaining why we care about using watchman, so here's a bit of context:

Watchman is critical for us in our very large repos because it has important properties that matter most when looking at the combined set of tools used against the watched project:

 * Running in a long-lived process allows factoring out the watch resource utilization to one service, so that rather than having every watch-capable tool duplicating watch resources for the same portions of the filesystem, there can be a single entity managing those.  For context, we have more than 20 widely used tools that have some sort of watch functionality enabled against our big repos.  
* The long lived watchman process allows short-lived clients (such as Mercurial and Git with the fsmonitor extension enabled) to reason about changes that happened between command invocations and accelerate `status` in the repo
* Watchman has mechanisms to handle notification queue overflow cases (which are easy to trigger on laptops when building in a giant repo) and not miss changes that occurred during the overflow condition
* Watchman is aware of our [EdenFS source control virtual filesystem](https://github.com/facebookexperimental/eden) solution and can work with it optimally.  This is very important to us because the OS file watchers are `O(repo-size)` and will materialize the entire repo on local storage as part of monitoring the repo.  That is highly undesirable because the size and number of files is so large and continually growing; it takes too much time to download and too much space to store them on local storage.

Not everyone has a scale large enough to *need* to use watchman, so I wouldn't advocate for making it a requirement, but for those that do, it is the only practical solution.

With that in mind, it really would make things nicer for our engineering population if we had a supportable path for using watchman in place of the default watcher implementation in vscode.  If that happens to be supported out of the box then that's great, but it's also fine if we have a supported way to override it in our local deployment as @pelmers suggested in the original post.

**Comment by DavidGoldman** [comment]
> (Hello, I work on Watchman and EdenFS at FB!)
> 
> Just to clarify; vscode doesn't need to (and honestly, really should not) ship the `watchman` binary. The [fb-watchman](https://www.npmjs.com/package/fb-watchman) client package has no native code to compile and is pretty small and should be easy to embed. Its only dependency is [bser](https://www.npmjs.com/package/bser) which also has no native code to compile.
> 
> The strategy used by most consumers is to try using `fb-watchman` first and then fall back to an alternate watcher if `watchman` isn't installed.
> 
> It's probably also worth explaining why we care about using watchman, so here's a bit of context:
> 
> Watchman is critical for us in our very large repos because it has important properties that matter most when looking at the combined set of tools used against the watched project:
> 
> * Running in a long-lived process allows factoring out the watch resource utilization to one service, so that rather than having every watch-capable tool duplicating watch resources for the same portions of the filesystem, there can be a single entity managing those.  For context, we have more than 20 widely used tools that have some sort of watch functionality enabled against our big repos.
> * The long lived watchman process allows short-lived clients (such as Mercurial and Git with the fsmonitor extension enabled) to reason about changes that happened between command invocations and accelerate `status` in the repo
> * Watchman has mechanisms to handle notification queue overflow cases (which are easy to trigger on laptops when building in a giant repo) and not miss changes that occurred during the overflow condition
> * Watchman is aware of our [EdenFS source control virtual filesystem](https://github.com/facebookexperimental/eden) solution and can work with it optimally.  This is very important to us because the OS file watchers are `O(repo-size)` and will materialize the entire repo on local storage as part of monitoring the repo.  That is highly undesirable because the size and number of files is so large and continually growing; it takes too much time to download and too much space to store them on local storage.
> 
> Not everyone has a scale large enough to _need_ to use watchman, so I wouldn't advocate for making it a requirement, but for those that do, it is the only practical solution.
> 
> With that in mind, it really would make things nicer for our engineering population if we had a supportable path for using watchman in place of the default watcher implementation in vscode. If that happens to be supported out of the box then that's great, but it's also fine if we have a supported way to override it in our local deployment as @pelmers suggested in the original post.

In addition, watchman seems useful for anyone who is looking to add built-in support for their FUSE or NFS based storage system. It's infeasible to add in support to every single tool, but if those tools support using watchman then building in support to watchman for your case is sufficient.

In general, watchman will help solve the `M:N` problem that LSP tries to solve, but in regards to file watching. For some LSPs, watching only the open directories in VSCode is not sufficient to detect all changes, so the LSP is forced to watch the file system themselves. This potentially leads to a waste of system resources as multiple processes watch the file system for the same events, with each watcher having some additional overhead.

It's also worth noting that watchman already has significant engineering work behind it, potentially solving some common issues that may arise when you use native file watching APIs (e.g. inotify, FSEvents). e.g. handling folder [deletion and restoration](https://github.com/Axosoft/nsfw/issues/31) on macOS. File watching is incredibly hard to get perfect.

**Comment by GitMensch** [comment]
That would be marvelous in a multi-user scenario. We have > 80 devs working on a network share, if there could be an extension which connects to a server-side watcher this would free up a lot of resources that are otherwise wasted.
