### ISSUE TITLE
The "cancel search" icon could be improved

### ISSUE THREAD

**Issue by gianpaj** [microsoft/vscode#80437]
In my opinion, the new icon for "cancel search" looks like a person icon.

A suggestion would be a "stop sign". Maybe something like this?

![EDuP9n2WkAADMPg](https://user-images.githubusercontent.com/899175/64372184-f474a600-d02a-11e9-95ab-b9ea6c2546ae.jpeg)

PS: thanks for working VSCode and keep improving the UX for millions of developers out there! ✨

**Comment by gianpaj** [comment]
cool. thanks for sharing the iterations and reconsidering this.

As you know, this icon is not that important since icon appears only when the search is taking a long time - usually when the computer is a bit slow or you're searching in huge folders.

All the best

**Comment by misolori** [comment]
@gianpaj Thanks again for the feedback. I'm going close this issue since this is as-designed and to also keep the number of issues in our inbox on a manageable level. We look at the number of votes an issue has received and the number of duplicate issues filed. More information can be found on our [issue grooming post](https://github.com/microsoft/vscode/issues/82032).
