### ISSUE TITLE
Use the launch configuration name as the terminal name

### ISSUE THREAD

**Issue by cameronbraid** [microsoft/vscode#80442]
Currently when running or debugging a launch target, the default terminal names are generic and don't reflect the launch target.  

This makes it hard to know which terminal relates to which launch, particularly when you have 3 or more launches running.

Example

a Java launch target named `Debug (Launch) - webapp` results in a terminal named `2: Java Debug Console`  .  I suggest that the terminal name becomes `Debug (Launch) - webapp` or alternatively support an override field in the launch.json to configure per launch target.

**Comment by weinand** [comment]
If a terminal is not busy, we are reusing it across launch configs. This feature request would require that the terminal's name changes over time.

**Comment by cameronbraid** [comment]
An alternative to that would be to create a new terminal for the debug session, then re-use it.

**Comment by cameronbraid** [comment]
The re-use seems to be keyed of the terminal name

for example, launching java it uses the name `Java Debug Console` and it does the following
* looks for terminal that is not busy named `1: Java Debug Console` 
* looks for terminal that is not busy named `2: Java Debug Console` 
* and so on, finally creating one

It could be changed to use the launch config name instead of the generic name

for example, launching `Debug (Launch) - webapp` it could do the following
* looks for terminal that is not busy named `1: Debug (Launch) - webapp` 
* looks for terminal that is not busy named `2: Debug (Launch) - webapp` 
* and so on, finally creating one

**Comment by AmirNamdar** [comment]
Hi @weinand 
Sharing my experience to perhaps help push this request forward
this SUCKS:
![image](https://user-images.githubusercontent.com/90144822/152685544-1d9bf1f4-b306-492f-abd6-c7580e3ad462.png)

**Comment by MiguelGuthridge** [comment]
Bumping this one - I have a similar experience to Amir currently.

**Comment by ps2goat** [comment]
I have a pretty similar use case. My terminals are all named after my launch config, but I use the same launch config for multiple apps. It's a mono repo that is not opened as a workspace  because I usually need to access files at the root.

My launch config asks the user to pick the app to debug, and uses the value in the launch command (all commands are similar). It would be nice if I could use that selected app value in the  terminal window.

Present state:
Debug app
Debug app(2)
Debug app(3)

Proposed state, where the part after `Debug app -` is a value that comes from my picker. I would provide the actual value to use:
Debug app - my-cool-api
Debug app - my-cool-service
Debug app - my-cool-web-backend

This would also be nice to get into the drop down list of running apps in both the debugger toolbar and debug console!

**Comment by roblourens** [comment]
The terminal title actually comes from the debug adapter, so the Python or Java extensions have full control over this. I agree that a more specific name might be more useful, but you'll have to file this on the repos for those extensions.

**Comment by AlbertoFabbri93** [comment]
Has anybody filed a feature-request for the Java extension?
