### ISSUE TITLE
Failure message from SetVariable request is not surfaced

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#80464]
Similar to #80452 but for the `SetVariableRequest`. The target environment of my debugger can only change a variable value at the stack level of the execution point, so I want to notify a user if they try to make a change when they have selected a different stack level.

VS Code version: Code 1.38.0 (3db7e09f3b61f915d03bbfa58e258d6eee843f35, 2019-09-03T21:49:13.459Z)
OS version: Windows_NT x64 10.0.17134

**Comment by isidorn** [comment]
I think you can just throw an error in `setVariable` and it should hopefully be nicely handled [here](https://github.com/Microsoft/vscode/blob/b5b8c4d716358243a27b538b9118aff25e136e52/src/vs/workbench/contrib/debug/common/debugModel.ts#L230)
Did you try that? Does that not work?

**Comment by gjsjohnmurray** [comment]
I don't think I tried throwing an error. I expected it to respect the following in my DebugProtocol.SetVariableResponse reply:
`{success: false, message: 'Unable to set that value', ... }`

`

**Comment by gjsjohnmurray** [comment]
@isidorn I have prepared a branch at https://github.com/gjsjohnmurray/vscode-mock-debug/tree/show-80464 in which I always throw an error [here](https://github.com/gjsjohnmurray/vscode-mock-debug/blob/3d6e356989b718054d0f5eac4f29c4e9d32064b3/src/mockDebug.ts#L261) in setVariableRequest, but don't see my message surface in the UI.

**Comment by isidorn** [comment]
Great find, thanks for providing nice repro steps.

First of all, I was wrong you can not just throw an error from the debug adapter, you always have to return a response. Just the `response.success` has to be `false` - as you were originally doing.

Now I fixed in issue on the VSCode side that we were not showing an error returned. Now we keep the input box shown and the user can see the error.
Please try it out in Monday's vscode insiders and let us know if the issue is nicely fixed for you.
Thanks!

![Screenshot 2019-09-20 at 11 14 39](https://user-images.githubusercontent.com/1926584/65315170-ecbf1080-db97-11e9-8dc6-94ec8f3ccc52.png)

**Comment by gjsjohnmurray** [comment]
@isidorn thanks for this. I have verified it.

**Comment by isidorn** [comment]
Thank you, adding verified label.
