### ISSUE TITLE
"Could not identify extension for 'vscode' require call from <file>" when using vscode-dts master

### ISSUE THREAD

**Issue by sherryyshi** [microsoft/vscode#80498]
After implementing the suggested mitigation steps in #80428, I get the following output when running tests:

```
Could not identify extension for 'vscode' require call from <project-root>\out\test\fileReporter.js. These are the extension path mappings:
        <%userprofile%>\.vscode\extensions\microsoft.devinsights-2019.8.23-1 -> Microsoft.devinsights
        <%userprofile%>\.vscode\extensions\microsoft.vscode-nmake-tools-2.0.190830005 -> Microsoft.vscode-nmake-tools
        <%userprofile%>\.vscode\extensions\ms-vscode.cpptools-0.25.1 -> ms-vscode.cpptools
....
```

I'm using `vscode-test` for my tests.

**Comment by Tyriar** [comment]
@octref please advise

**Comment by octref** [comment]
@jrieken Seems you know where it comes from https://github.com/microsoft/vscode/blame/master/src/vs/workbench/api/common/extHostRequireInterceptor.ts#L115. This seems to happen no matter if you are using `vscode` or `vscode-test`.

Repro:

```
git clone git@github.com:microsoft/vscode-test.git
cd vscode-test
yarn install && yarn compile && yarn test
```

**Comment by jrieken** [comment]
@octref I don't see `yarn test` in that repo? 

Tho, generally this error occurs when we cannot locate an extension within the list of extensions, e.g whenever a file requires the `vscode` module we lookup the file making the request in the extensions tree so that we give a unique instance of the `vscode` module to the extension (each extension gets a unique instance). The error means that a file makes a request to `vscode` which isn't known as extension. This usually happens when path normalisation is missing (casing, sym-links, etc) but it might be a different thing here...

**Comment by octref** [comment]
@jrieken Forgot, sorry, it's in the `sample` folder so should have been `cd vscode-test/sample`.

**Comment by jrieken** [comment]
Yeah, what's happening is that a file makes a request to `vscode` and that files isn't inside any extension. In that case we cannot associate a file to an extension and the message is printed. This isn't failure but means a default extension description is used (which cannot use proposed API for instance).

**Comment by jrieken** [comment]
@octref Is that something you can tweak in your setup?

**Comment by octref** [comment]
@jrieken I tweaked the setup in the sample. The issue was that I gave a wrong `--extensionDevelopmentPath` in the sample.

@sherryyshi What's the `extensionDevelopmentPath` you are passing in? I see the file being reported is `<project-root>\out\test\fileReporter.js`. If `<project-root>` is where your extension's package.json lives, you should pass that in `extensionDevelopmentPath` and these warnings should be gone.

**Comment by roblourens** [comment]
@octref this is what I get when running the tests in vscode-test/sample:

```
Error: Error: Cannot find module '/Users/roblou/Downloads/vscode-test/sample/out/test'
	at t.ExtHostExtensionService._doHandleExtensionTests (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:671:756)
```

**Comment by octref** [comment]
@roblourens That's a different issue — I fixed it in another commit.

Anyway, to next verifier next month:

- Clone https://github.com/microsoft/vscode-test
- Run `yarn` at root and `/sample`
- Run `yarn compile` at root and `/sample`
- Open `/sample` VS Code
- Run the launch config `Extension Tests - Suite 1` or `Extension Tests - Suite 2`
