### ISSUE TITLE
Auto Formatting SCSS or JSX files does not work

### ISSUE THREAD

**Issue by realseanp** [Microsoft/vscode#805]
Shift + Option + F does not auto-format .scss or .jsx files. It should format similar to CSS and JS.

**Comment by enmodus-rocketmakers** [comment]
+1 for this. Used it all the time in visual studio. One of the few things I'm really missing :(

**Comment by vmachacek** [comment]
yup

**Comment by Maximaximum** [comment]
There are lots of extensions to VS Code that claim they can format scss, but still none of them seem to be working well, especially together with EditorConfig

**Comment by mjbvz** [comment]
JSX formatting should work now. If you see any issues formatting jsx or tsx files, please open a bug so that we can investigate.

SCSS formatting is not included in VSCode. We would expect an extension to provide this sort of functionality. This one may be worth checking out:

https://marketplace.visualstudio.com/items?itemName=michelemelluso.code-beautifier
