### ISSUE TITLE
Shorter prefix to quickly navigate to terminal

### ISSUE THREAD

**Issue by solomatov** [microsoft/vscode#80519]
Currently, to quickly open terminal, I have to press: 
- Cmd + P
- term 
- name of the terminal

What do you think about replacing term with ` (Cmd+` opens the terminal pane)?

**Comment by Tyriar** [comment]
Add this to your keybindings.json file:

```
{ "key": "ctrl+`", "command": "workbench.action.quickOpenTerm" }
```

**Comment by solomatov** [comment]
@Tyriar Your suggestion fixes the problem, but it does it only for me. I think, it would be nice to have defaults settings in vs.code so that people can do everything from keyboard quickly.

**Comment by Tyriar** [comment]
@solomatov it's not that easy, if that default changed I'm pretty sure an enormous amount of people would complain about it. The terminal keybindings are very minimal because there aren't that many good options available for most keybindings; kill, focusNext, focusPrevious are much more important than quickOpenTerm but remain unbound by default. Getting comfortable with the keybindings system allows you to customize VS Code to your liking.

**Comment by solomatov** [comment]
@Tyriar I disagree with you. We already have Cmd+P. Then, we can type `, it doesn't take any shortuts. If after this we show the list of terminals, with the current one selected, we don't need focus next/prev. If we make a delete shortcut there, say Cmd+Delete, we don't need kill. As a result, with such a minor addition, we can introduce a way to execute a lot of actions quickly without bloating the list of shortcuts.

My idea was not to introduce Cmd+tilde but to have tilde as a prefix for the commands. I see that formatting was not what I meant in the original post.

What do you think?
