### ISSUE TITLE
Code folding wrong on triple double quote string with unindented lines

### ISSUE THREAD

**Issue by tweakimp** [microsoft/vscode#80528]
It seems the indentation of triple double quote strings messes up the folding logic.

- VSCode Version: 1.38.0 and 1.39.0-insider
- OS Version: Win10

Steps to Reproduce:

This Python code:
```python
def test():
    some_long_string = """

text
text
text
"""

    something_else = 1+1
```
Trying to folde the function does not work properly:
![gif](https://i.imgur.com/QniCWZV.gif "gif")

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
Do you use a extension for Python? If yes, please file the issue against the extension. Language folding ranges are provided by extensions.

If you don't use any extension or the extension you use has no folding range provider, then what you see is purely based on indentation and has no understanding of language syntax.

**Comment by tweakimp** [comment]
@aeschli I was sent back here: https://github.com/microsoft/vscode-python/issues/7309

**Comment by kimadeline** [comment]
Hi @aeschli, @tweakimp 's issue could be replicated with the Python extension disabled (also reported up there with `Does this issue occur when all extensions are disabled?: Yes`), hence why my best guess was that it wasn't caused by the extension. The Python extension has an issue tracking the second part of your comment though (https://github.com/microsoft/vscode-python/issues/1847), so no further action is needed.

Thank you all for your help!
