### ISSUE TITLE
Monaco Editor API feedback

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#8057]
Monaco editor core 0.4.0

- [x] `IEditor.onDidChangeModelRawContent` is already marked as deprecated. We should better ignore it right away. That would make `IModelContentChangedEvent` and subtypes obsolete

- [x] Don't give out `IHTMLContentElement` but rather something like `MarkedString`. `IHTMLContentElement` is very powerful but also crazy complex. `MarkedString` is clearly too limited. but a good starting point.

- [postponed] rename `MarkerData` to `Diagnostic` (minor)
- [postponed] rename `ISingleEditOperation` to `TextEdit` (minor)

- [postponed] `IModel`, `IReadOnlyModel`, `IEditableTextModel`, `ITextModelWithMarkers`, `ITokenizedModel`..
The current model hierarchy is very complicated with several interfaces adding nothing:
`ITextModelWithMarkers`, `ITextModelWithTrackedRanges`, `ITokenizedModel` don't add anything really.
Maybe it would be better to consolidate this and remove the types that don't add anything.

**Comment by alexandrudima** [comment]
Nice thoughts!

* `onDidChangeModelRawContent` - we can probably remove those immediately

* `IHTMLContentElement` vs `MarkedString` - +1 - definitely something to do. But only if we eliminate `IHTMLContentElement` from our codebase. I would not go for adaptor funny business. Do you wanna do it?

* the model hierarchy comes from our codebase. Things are empty because the methods are marked internal. the .d.ts is not designed, it is generated. I can probably remove a couple of interfaces in there, but yes, there is a distinction between IReadOnlyModel and IModel (probably the most useful).

**Comment by aeschli** [comment]
I can look at 'IHTMLContentElement'. Probably I won't be able to eliminate it all together, but replace the occurrences in Hover and IModelDecorationOptions with MarkedString to it doesn't appear in monaco.d.ts anymore

**Comment by alexandrudima** [comment]
:+1: Removing it from Hover and IModelDecorationOptions might mean it is entirely not needed anymore
