### ISSUE TITLE
Close all extension resources when extension viewlet goes away

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#8060]
From @jrieken 

We'd like to avoid this:

![image](https://cloud.githubusercontent.com/assets/22350/16307816/f2ca05b4-3962-11e6-8356-e93b20ad521d.png)

For that I'd like to close all extension resources when the viewlet goes away. I tried doing it through the `setVisible` call and through the `IEventService`... but both approaches fail when the sidebar simply closes: the extensions shouldn't go away on that situation. I need an event for when *another* viewlet opens, and I couldn't find it.

@bpasero need your help here.

**Comment by jrieken** [comment]
How about [`getVisibleEditor`](https://github.com/Microsoft/vscode/blob/joh/menus/src/vs/workbench/services/editor/common/editorService.ts#L39) when your viewlet is set visible=false?

**Comment by joaomoreno** [comment]
The problem is that hiding the sidebar is a false positive I can't distinguish from the real thing.

**Comment by jrieken** [comment]
yeah, end of my knowledge

**Comment by joaomoreno** [comment]
We can wait for @bpasero to fix it next week, should be easy for him.

**Comment by bpasero** [comment]
This is a consequence of introducing panels and having just one `COMPOSITE_OPENED` event instead of distinguishing between viewlets and panels. 

@isidorn can we bring back a way to distinguish viewlets and panels when opening?

@joaomoreno once we have that back, the simple solution would be to check on this opening event if the id of the viewlet that opens is the extensions viewlet or not and make the call based on that.

**Comment by isidorn** [comment]
After discussing with @bpasero we agreed this is nothing we want to do this endgame -> July

**Comment by joaomoreno** [comment]
Ok, but what do we do in July?
