### ISSUE TITLE
Git: sort remotes by last actively used

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#80620]
I am not sure if that is possible but I am having 2 remotes for my Git setup and the one I actually rarely push to. Still it appears first because of what seems to be alphabetic sorting.

Is there any way remotes could be sorted by date of last usage, similar to how we sort branches?

**Comment by joaomoreno** [comment]
`git remote` gives me no `sort` option. Also, branches are easy to sort since they point to a commit which has a timestamp. Remotes don't have timestamps. We'd have to keep track of the remotes you last picked... which would possibly be a feature of the quick input instead of having Git implement and store a pick preference. What do you think?

**Comment by bpasero** [comment]
Yeah last picked might work for me.

**Comment by joaomoreno** [comment]
Should it be a quick open feature then?

**Comment by bpasero** [comment]
This is quick input right? @chrmarti would maybe know if this exists as a reusable thing.

**Comment by chrmarti** [comment]
Quick Input has no support for MRU sorting. (It has no notion of identifying an entry nor does it store any information between invocations.)

If you can sort branches quickly, maybe you can use that order to sort their remotes too?

**Comment by joaomoreno** [comment]
Closing this as won't fix.
