### ISSUE TITLE
Create separate config option for autoClosingCommentBlocks

### ISSUE THREAD

**Issue by AndrewInside** [microsoft/vscode#80622]
The "editor.autoClosingBrackets" option in config is currently (version 1.38.0 - it was not the case previously) affecting auto completion of comment blocks after typing /** for example in PHP. It would be nice to have the option of disabling auto closing braces while still have auto completing comment blocks.

**Comment by sbossarte** [comment]
I also prefer auto-closing comments, but not any of the other brackets, to help with some boilerplate documentation in languages that support it. In case anyone else is looking around, removing all but the comment `autoClosingBrackets` pairs from the `language-configuration.json` file of a language can give this behavior.

This is only temporary, because these changes will be lost on update for any natively supported languages. With the configuration options and extensibility of VS Code, there may be a better place to override this, but I've only briefly looked into it and stuck with the simple ""fix"" above.
