### ISSUE TITLE
Unnecessary code and decoration with :after prevents dnd

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#80666]
Issue Type: <b>Bug</b>

1. Have unused variable in the first line of the file `const asdf = 0;` (any line tbh, just an example)
2. Create decoration on the same line with the `after` property specified
```ts
const decorationType = vscode.window.createTextEditorDecorationType({
	isWholeLine: true,
});
const decorationOptions: vscode.DecorationOptions = {
	range: new vscode.Range(0, 0, 0, 0),
	renderOptions: {
		after: {
			contentText: 'random',
		},
	},
};
editor.setDecorations(decorationType, [decorationOptions]);
```
3. Try to drag-n-drop text to that line

If I reference that variable (remove unused status) - then dnd works fine again.

VS Code version: Code - Insiders 1.39.0-insider (55825e9ad2aa4b4b3f8b2290a54a517bc454a7a5, 2019-09-10T05:25:22.729Z)
OS version: Windows_NT x64 10.0.18362

**Comment by alexandrudima** [comment]
I can reproduce. I cannot drop on the line:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/64940375-17d9f500-d864-11e9-9942-442b9b2788e6.gif)

**Comment by rebornix** [comment]
Weird bug. While `mouseDownAndMove`, the mouse event target is `span <- span <- view line <- view lines <- ...`. However once it stops, the last cached mouse event target is `span <- span <- view line  <- null` when dropping in above case. The mouse target somehow gets unconnected from view lines.

**Comment by alexandrudima** [comment]
@rebornix That might happen because the line gets redrawn. In that case, the line becomes orphaned. I think the line might get redrawn due to inline decorations getting added/removed as drop feedback or as hover range feedback.

**Comment by KapitanOczywisty** [comment]
@rebornix @alexdima  Since this is pretty annoying bug when using [Error Lens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens) extension, I spend some time and found what exactly is wrong. Basically lines with `after` decorator are redrawn because `lineDecorations` has the same elements, but in different order. I'm pretty sure order is messed by [DragAndDropController._onEditorMouseDrag]( https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/src/vs/editor/contrib/dnd/dnd.ts#L138-L144) combined with some other regular task, but this is not important for the actual fix.

Meanwhile event used for drop target is gathered when mouse is still on the move
https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/src/vs/editor/browser/controller/mouseHandler.ts#L302
and the render cycle passes before this event is used
https://github.com/microsoft/vscode/blob/f74e473238aca7b79c08be761d99a0232838ca4c/src/vs/editor/browser/controller/mouseHandler.ts#L359

---

To fix this, `lineDecorations` have to be sorted here: (before condition [here](
https://github.com/microsoft/vscode/blob/29e9717d340f439057527fbadc2a3642d2481c9f/src/vs/editor/browser/viewParts/lines/viewLine.ts#L235-L237)):
https://github.com/microsoft/vscode/blob/29e9717d340f439057527fbadc2a3642d2481c9f/src/vs/editor/common/viewLayout/viewLineRenderer.ts#L130

Or this function has to ignore elements order
https://github.com/microsoft/vscode/blob/29e9717d340f439057527fbadc2a3642d2481c9f/src/vs/editor/common/viewLayout/lineDecorations.ts#L31-L43

I've tested both options in DevTools and this fixes issue. Since this is rather crucial part of code I'll leave proper implementation to you.

**Comment by alexdima** [comment]
To verify:

* `package.json`:
```
{
    "publisher": "alex",
    "name": "80666",
    "version": "1.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "main": "main.js",
    "activationEvents": ["*"]
}
```
* `main.js`:
```

const vscode = require('vscode');

exports.activate = function() {
    const decorationType = vscode.window.createTextEditorDecorationType({
        isWholeLine: true,
    });
    const decorationOptions = {
        range: new vscode.Range(2, 1000, 2, 1000),
        renderOptions: {
            after: {
                contentText: 'random',
            },
        },
    };
    vscode.window.activeTextEditor.setDecorations(decorationType, [decorationOptions]);
}
```
* `file.ts`:
```

function x() {
    const asdf = 0;
}

```

**Comment by usernamehw** [comment]
/verified Tested by using Error Lens extension decorations
