### ISSUE TITLE
ITextModel.findMatches is incorrect in this case

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#80707]
* create a new file
* type bar
* do shift+alt+down 5 times (to duplicate line down 5 times)
* click on one of the duplicated lines
* observe that the first instance is not highlighted due to `findMatches` being incorrect

![image](https://user-images.githubusercontent.com/5047891/64696045-c74a4c80-d49d-11e9-8b39-381a380a2cc4.png)

If you do a reload (the text buffer is read from disk) the issue does not reproduce:

![image](https://user-images.githubusercontent.com/5047891/64696079-d6c99580-d49d-11e9-9a87-5e5be5af727d.png)

**Comment by rebornix** [comment]
🚀  Really good catch! I definitely saw it a couple of times but didn't find good ways to reproduce it.

The root cause is we didn't respect how `Searcher` validates the search result. If word patterns are provided, we will check if the search result is inside a pair of word boundaries. However in above case, we attempt to search `/bar/gu` in `barbar\nbar\nbar\nbar\nbar\n` from offset 3. The first result is `[3, 6)` but `Searcher` thinks it's invalid as it's part of word `barbar\n`.

**Comment by rebornix** [comment]
Verify: 

1st, the same as what @alexandrudima described:

* Open an untiled file
* Type `bar`
* shift+alt+down 5 times
* move the cursor to left once
* all `bar` should be highlighted

2nd. Finish above steps first

* add `2` at the end of `bar` of the 4th line
* add `2` at the end of `bar` of the 2nd line
* Please verify
  * move cursor into any `bar` highlights all `bar`
  * move cursor into any `bar2` highlights all `bar2` but no `bar`
  * open find widget, search `bar` w or w/o `Toggle Whole Word` works as expected.
