### ISSUE TITLE
VSCode steals nautilus windows from nautilus icon in Ubuntu favorites bar

### ISSUE THREAD

**Issue by willyd** [microsoft/vscode#80799]
- VSCode Version: 1.38.0
- OS Version: Ubuntu 18.04.3 LTS

It seems that I need to open a nautilus window before clicking on `Open Containing Folder` otherwise all nautilus windows get associated with the VSCode icon in the favorites bar. This is a bit annoying

Steps to Reproduce:

0. Close all nautilus and VSCode windows
1. Kill nautilus with command `nautilus -q`
2. Start VSCode
3. Right click on any file and select `Open Containing Folder`
4. Orange dot for the nautilus window appears next to the VSCode icon
5. Exit VSCode
6. Kill nautilus with command `nautilus -q`
7. Open a nautilus window by clicking on the nautilus icon in the favorites bar
8. Start VSCode
9. Right click on any file and select `Open Containing Folder`
10. Orange dot appears as normal next to the nautilus window

Example:
![vscode_nautilus_bug](https://user-images.githubusercontent.com/628693/64785177-c830bc00-d539-11e9-8e21-fe23e9bdd317.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to the code. As such, I will go ahead and close it. If you can identify the component that is causing the issue, please report it upstream:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
