### ISSUE TITLE
Extentions won't show/download

### ISSUE THREAD

**Issue by wael-zaki** [microsoft/vscode#80808]
Issue Type: <b>Bug</b>

i have vscode 1.38.1 on both windows 10 and manjaro linux, and i have an issue getting extentions, searching for them or downloading them.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz (4 x 2794)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (3.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by sandy081** [comment]
Are you behind any proxy set up? Are you able to access Marketplace from browser?

Is it a DNS issue. #78783 #78872
Can you try to access this image? 
https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default
If not, can you try changing your DNS setting, like pointing to `1.1.1.1` as suggested here? https://1.1.1.1/dns/

Can you please share the logs from following locations

- Dev tools console. Use command `F1 -> Toggle Developer Tools`
- Window log. Use command `F1` -> View: Open View -> Window (Log)`
- Shared process log. Use command `F1` -> View: Open View -> Shared (Log)`

**Comment by wael-zaki** [comment]
![Annotation 2019-09-20 205403](https://user-images.githubusercontent.com/55249588/65351609-d42b1680-dbe8-11e9-824d-3320cf236328.png)
Link not accessible for me.
I already have DNS set.
tried "1.1.1.1" didn't work. set it back to DNS i was provided by ISP.
still can't connect. older version worked fine though.

**Comment by sandy081** [comment]
@kesane-msft We are seeing many users hitting this issue and everybody has the issue accessing the following link

https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default

We suspect this a DNS issue but users say they are not having this issue with old VS Code. Do you see any issues with this link?

**Comment by wael-zaki** [comment]
> @kesane-msft We are seeing many users hitting this issue and everybody has the issue accessing the following link
> 
> https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default
> 
> We suspect this a DNS issue but users say they are not having this issue with old VS Code. Do you see any issues with this link?

yes i have tried it and it's not accessible even after changing DNS. and I checked other posts for the issue and none of the solutions there worked.

**Comment by kesane-msft** [comment]
@sandy081 - the link that you have shared looks good.

@wael-zaki - could you please reach out to vsmarketplace@microsoft.com with details so that we can investigate the issue in more details?
It would be great if you could share the logs requested by @sandy081 . In addition, it would help us in our investigations if you could share fiddler traces of sessions - 
1. Where you are using old VSCode version and not hitting issue.
2. Using new VSCode version and facing the issue.
3. Navigate to https://marketplace.visualstudio.com/items?itemName=ms-python.python in any browser.

Here’s how to capture a fiddler trace ,
a. Download & install Telerik Fiddler from here - https://www.telerik.com/download/fiddler
b. Close all browsers and start Fiddler.
c.Go to Tools menu -> Options -> HTTPS tab in dialog box -> Check ‘Capture HTTPS connects’ and ‘Decrypt HTTPS traffic’ and click OK. If it prompts to install a root certificate at this point or later, please select ‘yes’ or ‘OK’ and install it.
![image](https://user-images.githubusercontent.com/28951219/65954129-03504c00-e463-11e9-8322-5f1c3d264188.png)

d. Now start fiddler
e. With fiddler running, open a browser and try to reproduce the issue again
f. After the issue is reproduced, in Fiddler, go to File -> Save -> All sessions
Save the trace file on your computer and send that back to us.
