### ISSUE TITLE
"Open Symbol By Name" is not working properly in multipy typescript projects.

### ISSUE THREAD

**Issue by heroboy** [Microsoft/vscode#8081]
- VSCode Version:1.2.1
- OS Version: windows 8.1

Steps to Reproduce:
1. create a project like:
```
a/a.ts
a/tsconfig.json   => files:["a.ts"]
b/b.ts
b/tsconfig.json   => files:["b.ts"]
c.ts
```
2. Ctrl+P and type "#" to search some symbols in "a.ts" "b.ts" or "c.ts". You will expect they will be seached. But the search result is depend on which file is currently opening or something else maybe open file order.

For exmaple:
open "c.ts" and insert:
```
import "./b.ts"
```
Then you can search symbols in "b.ts". Then comment it, and if symbols in "b.ts" can be searched is undetermined, sometime can and sometime can't.

And in my another project, only symbols in ".d.ts" can be searched.

And another problem is I can't search variable names in global scope, even I export it.

**Comment by zhengbli** [comment]
In this case we do only build projects for opened files. So if you open "c.ts" and add the `import`, what happens is:
[Open c.ts]
1. The server opens c.ts, didn't find a tsconfig.json file for it, so creates an inferred project for it
[Add `import`]
2. The server opens b.ts, and found a tsconfig.json file, so creates a configured project according to tsconfig.json. 

However, after you commenting of the `import` clause, you shouldn't be able to search for the symbols in b.ts, and this should be consistent. The "undetermined" behavior you described is problematic.

What is the setup of your other project which only ".d.ts" symbols can be searched? We recently added test infrastructure for the project system, this should be able to help us eliminate problems.

**Comment by zhengbli** [comment]
In addition, the order in which the files are opened matters by design. When one file belongs to multiple projects, we try to resolve the conflict by determining which types of project has a higher priority. But sometimes there are no ways to know which one the file is "intended" to belong to. So in cases like these, it goes to the first project created.

**Comment by heroboy** [comment]
@zhengbli 
My another project layout is just like the above project I described. 
I setup another project to test:
```
a/a.ts => function afunc(){}
a/main.ts => import "./a.ts"
b/b.ts => function bfunc(){}
b/main.ts => import "./b.ts"
```
Then I tried several times, each time I close all working files and restart vscode.
1. open "a/main.ts".
2. "afunc" found, and "bfunc" not. It's ok.
3. open "b/main.ts"
4. "afunc" found, and "bfunc" not. I think "bfunc" should be found.
5. close all files
6. "afunc" and "bfunc" not found. It's ok
7. open "b/main.ts"
8. "bfunc" found, and "afunc" not. It's ok.
9. open "a/main.ts"
10. "bfunc" found, and "afunc" not. I think "afunc" should be found.

**Comment by heroboy** [comment]
When "bfunc" can't be found, even I opened "b.ts", it still can't be found.

**Comment by zhengbli** [comment]
Thanks for the detailed repro procedure! Indeed I see this on my machine too. I'll dig deeper tomorrow, it could be either the project system or the navBar APIs.

**Comment by heroboy** [comment]
> "We do only build projects for opened files in tsserver."

If I don't open the project entry ts files, tsserver will not known "all files" in the project. And can't implment a reasonable "Open Symbol By Name".For exmaple, if I close all files,and create a new ts file in the project. Then no symbol will found. It looks not good.

Will tsserver search all tsconfig.json to build projects? I think this is the right way.

**Comment by zhengbli** [comment]
Indeed this is not ideal for features like "Go to anything" in sublime. We are working on supporting the "Open Project" api, which will keep the project alive regardless of the opening files, though it will likely land after 2.0 release.

Actively searching for all tsconfig.json by default can be resource-intensive, because for each project we have to open all the files and watch the files and directories etc, we want to be efficient about the resource allocation. Currently in most cases users open the editor at one project root, so it may not be worth it to eagerly build everything by default. Though we can think about adding configuration to enable such scenarios if the user really wants to. This also align to the suggestion we had about extend our definition of projects on tsserver to support "mid-sized" scenarios (https://github.com/Microsoft/TypeScript/issues/3469).

**Comment by zhengbli** [comment]
So I took a further look of the request / response records, and it seems that VSCode is not sending the correct file name for the `navto` command:

[open a/main.ts, and try to search the `afunc` symbol]
```
Sending request: navto (33). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "c:/Users/zhengbli/Documents/playground/testMultipleProjects/a/main.ts",
    "searchValue": "afun"
}
```
This is the correct behavior.

[Then open b/main.ts, and try to search the `bfunc` symbol]
```
Sending request: navto (37). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "c:/Users/zhengbli/Documents/playground/testMultipleProjects/a/main.ts",
    "searchValue": "bfun"
}
```
This doesn't seem right, as the `file` argument is still the a/main.ts instead of the current file. Then the symbol search won't be in the right project.

**Comment by dbaeumer** [comment]
@zhengbli thanks. I will have a look.

**Comment by dbaeumer** [comment]
I fix this by taking the active document as the context. However TS still doesn't provide a global workspace search. The search is always limited to a TS project.

**Comment by dbaeumer** [comment]
Opened https://github.com/Microsoft/vscode/issues/11026 to see if we can fake this.
