### ISSUE TITLE
"Terminal Editor Window" should switch focus to terminal panel

### ISSUE THREAD

**Issue by jbaileyashe** [microsoft/vscode#80897]
Issue Type: <b>Bug</b>

I use "Toggle Editor Window" to quickly give me a full-screen terminal. However, the input focus is not on terminal after toggling. I have to click in the window or execute "Toggle Integrated Terminal" to get focus there. Please let input focus switch to the maximized panel.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.18362

**Comment by jbaileyashe** [comment]
Similar to request in https://github.com/microsoft/vscode/issues/72090

**Comment by Tyriar** [comment]
Not terminal related imo, whether we should focus the active panel or not when the editor is hidden.

**Comment by isidorn** [comment]
Not related to terminal.
Where should the focus go when the editor is no longer visible? Why not in the sidebar.
Ideally it would go where it was before the focus moved to the editor area.
Though leaving this up to @sbatten and the new layout

**Comment by sbatten** [comment]
Toggling the editor area is not an explicit operation to state that focus should go to the terminal. 2 things provide a better experience around this with one being new since the issue was reported.

1) Use `Toggle Maximized Panel`... this explicitly maximizes the panel (even if hidden) and focuses.
2) A new setting has been introduced `workbench.panel.opensMaximized`. This setting controls if the terminal should open maximized. if you like a full screen terminal, you can set this to preserve or always which will allow you to simple toggle the terminal can get a maximized focused terminal.
