### ISSUE TITLE
Multiple Search and Replace at once.

### ISSUE THREAD

**Issue by hareshambaliya** [microsoft/vscode#80926]
I am looking for the feature to search multiple terms at replacing it with replacing terms. Here is the screenshot of that feature that explains everything.

![image](https://user-images.githubusercontent.com/619323/64909236-0b03b700-d727-11e9-981c-1e607ed1ffbd.png)

And, there should be one replace button that replaces all search text with replacing text. I can add as many search and replace groups I want, which will replace all at once.

**Comment by golayp** [comment]
Sad to see this feature is closed.
I had similar needs and have to do it by script.
My need is to change on every files from a list of corresponding replace like this:

match1	replace-1
match2	other-replace
match3	something-else
...
matchX	xyz

Update in every files every couple: match by replace-1 and so on for every line.
This is not possible through more abstract search and replace because every line is different and more every replace can be drastically different from source.

**Comment by overtomanu** [comment]
Even i had stumbled into this kind of requirement. You have to also take care that bigger strings are replaced first as smaller strings might be prefix or suffix of bigger strings. Below is the Java code to just get it done. I know it is not convenient but it is a option if you are in a hurry and there are a lot of strings to be replaced.

https://github.com/overtomanu/java-util-code/blob/master/src/util/ReplaceListOfWordsInFile.java

**Comment by overtomanu** [comment]
Below is simple shell script which replaces strings in file "EnglishCols.txt" with strings from "FrenchCanadianColumns.txt" in the file "GenCSVFrenchCanadian.txt"

`for i in $(seq $(cat EnglishCols.txt|wc -l));
do
  toBeReplaced=$(head -$i EnglishCols.txt|tail -1);
  replacementValue=$(head -$i FrenchCanadianColumns.txt|tail -1);
  echo replacing \"$toBeReplaced\" by \"$replacementValue\"
  sed -i '' "s|$toBeReplaced|$replacementValue|g" GenCSVFrenchCanadian.txt
done`
