### ISSUE TITLE
API request: Live Positions

### ISSUE THREAD

**Issue by johnfn** [Microsoft/vscode#8094]
In the process of working on a [Vim plugin for VSCode](https://github.com/VSCodeVim/Vim) I've run into a number of areas where I need a little bit of API help. Apologies if any of my suggestions already exist!

Vim has the concept of marks, which are positions in the document that you can jump to from anywhere. They're like the Positions the API provides, but if you delete text from before the mark, the position of the mark will change. 

It seems highly likely that you guys have something like this internally, and I think it would be disappointing (and possibly difficult) to roll my own. Help?

**Comment by jrieken** [comment]
Yeah, our decorations are implemented like that

**Comment by alexandrudima** [comment]
The challenge here is that we don't sync decorations back to the extension host. We could do that proactively in case someone wants to read them and then provide synchronous read API. IMHO async read API would be unsuitable in this case.

**Comment by siegebell** [comment]
At least, I would like to see the API provide utility data structures that manage sets of ranges and sets of positions, *allows updating them in response to a `TextEdit`*, and provides some basic functions like searching for intersecting ranges.

I've written this myself, but it is easy to get wrong, I imagine a bunch of extension authors would also find the functionality useful, and counting the line delta in a `TextEdit` is a pain in the butt because you have to parse the line endings yourself.

Then vscode would not have to directly provide the updated decorations to the extension, which I imagine raises some asynchrony issues because decorations tend to be updated well before the extension is done processing edit updates.
