### ISSUE TITLE
Source code management cannot display Chinese （源代码管理不能显示中文）

### ISSUE THREAD

**Issue by sudazzk** [microsoft/vscode#80954]
The data required is too large to be sent directly. We have already written it to the clipboard, please paste it.

**Comment by sudazzk** [comment]
源代码管理，点击三个点那里 ... ，为什么显示的是英文，我已经安装了中文插件了。

**Comment by fengrenxin** [comment]
> 源代码管理，点击三个点那里 ... ，为什么显示的是英文，我已经安装了中文插件了。

我也出现了, 卸载了, 又清空了插件数据, 重装才好,

**Comment by sudazzk** [comment]
> > 源代码管理，点击三个点那里 ... ，为什么显示的是英文，我已经安装了中文插件了。
> 
> 我也出现了, 卸载了, 又清空了插件数据, 重装才好,

**Comment by sudazzk** [comment]
> > 源代码管理，点击三个点那里 ... ，为什么显示的是英文，我已经安装了中文插件了。
> 
> 我也出现了, 卸载了, 又清空了插件数据, 重装才好,

好的，谢谢，我试一下。

**Comment by fengrenxin** [comment]
> > > 源代码管理，点击三个点那里 ... ，为什么显示的是英文，我已经安装了中文插件了。
> > 
> > 
> > 我也出现了, 卸载了, 又清空了插件数据, 重装才好,
> 
> 好的，谢谢，我试一下。

更新了个vscode版本, 我这又出现了这问题,

**Comment by sudazzk** [comment]
> > > > 源代码管理，点击三个点那里 ... ，为什么显示的是英文，我已经安装了中文插件了。
> > > 
> > > 
> > > 我也出现了, 卸载了, 又清空了插件数据, 重装才好,
> > 
> > 
> > 好的，谢谢，我试一下。
> 
> 更新了个vscode版本, 我这又出现了这问题,

那等官方解决这个bug吧~

**Comment by aeschli** [comment]
Can you add a screenshot?

**Comment by sudazzk** [comment]
> Can you add a screenshot?

![image](https://user-images.githubusercontent.com/15663622/64953801-63b58a00-d8b6-11e9-8a37-a28184eac959.png)

i have installed Chinese (Simplified) Language Pack for Visual Studio Code extension

**Comment by byyxx128** [comment]
@sudazzk 把你标题和一楼内容编辑（Edit）下都改成英文，以免被关闭。
***
Many times after VS Code upgrading to a new major version, I found some strings are not in my local
language although thoes are not new strings. Sometime reinstalling the language pack would be helpful. It happened for many times. I didn't report because I thought the language pack was not ready. However, the author @sudazzk met the similar issue again, so I think I need to report here.

**Comment by joaomoreno** [comment]
This is the missing NLS issue. cc @dbaeumer
