### ISSUE TITLE
API Request: Control over history

### ISSUE THREAD

**Issue by johnfn** [Microsoft/vscode#8096]
In the process of working on a [Vim plugin for VSCode](https://github.com/VSCodeVim/Vim) I've run into a number of areas where I need a little bit of API help. Apologies if any of my suggestions already exist!

Vim's undo/redo history diverges from VSCode's almost immediately, since multiple changes in Vim can be considered a single undo step. This is very important just about everywhere in Vim, and is especially important in things like macros which combine multiple actions into a single step.

**Comment by alexandrudima** [comment]
The edits coming in from the extension host (i.e. `textEditor.edit`) eventually reach https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/commonCodeEditor.ts#L599

It was not always like that. I changed it due to feedback from extension writers - https://github.com/Microsoft/vscode/issues/4313

I have a feeling that neither way makes everyone happy (i.e. some prefer to have undo stops before and after their commands, and some prefer not to), and we need additional options to `textEditor.edit`

That being said, you could try to workaround it. From your example about macros, why not make all the edits caused by a macro in a single `textEditor.edit` call...

**Comment by johnfn** [comment]
@alexandrudima 

> That being said, you could try to workaround it. From your example about macros, why not make all the edits caused by a macro in a single textEditor.edit call...

If I understand right, that's not possible, because a macro could insert and delete in overlapping regions, which is something the TextEditorEdit doesn't support.

**Comment by alexandrudima** [comment]
Indeed, the `TextEditor.edit` can handle multiple edits, but their semantic is that they are "parallel" (all applied at once), not "sequential" (applied in strict order with side-effects to the ones following).
