### ISSUE TITLE
Simpler way to downgrade to previous version(from Today's install to Yesterday's build)

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#81024]
Issue Type: <b>Feature Request</b>

Sometimes (once out of 100 updates) there is some breaking change in the Insiders installation. once the buggy version is installed there is no way to undo this breaking change (or may be i am not aware of such way).
i have to be patient and  wait for the next update which comes in ~24 hours or in case very critical issues 3-4 hours.
or 
i have to downgrade the version to n - 1th version (if current is 1.39, downgrade to 1.38).

is there any way to have a "Undo Latest Install" kind of option where Insiders build will go back from taday's release to yesterday's release.  

VS Code version: Code - Insiders 1.39.0-insider (d157c2e941cae17acb79bf26a70bbfad732bdc83, 2019-09-16T06:06:10.647Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kieferrm** [comment]
@sanket-bhalerao sorry we broke you. 

We support side by side installs between insiders and stable for this reason. If the issue is severe and we know about it then we usually push a new insiders build to fix it. 

We have no plans to support to go back in time with insider installs. That would be a considerable amount of work without reasonable payoff.

**Comment by sanket-bhalerao** [comment]
@kieferrm i completely understand 😊.
If i want to explore this option could you point me in the direction where i should start?
