### ISSUE TITLE
No IntelliSense with aliased directories

### ISSUE THREAD

**Issue by nmalyschkin** [microsoft/vscode#81033]
- VSCode Version: 1.38.1
- OS Version: Debian 9

Steps to Reproduce:
WHEN using jsconfig.json
WHEN using paths
IntelliSense DOES NOT resolve a aliased directory path to the index file.

```js
// IntelliSense does not work
import { Test } from "test/path/to/Components"

// IntelliSense works
import { Test } from "test/path/to/Components/index"

// IntelliSense works
import Test from "test/path/to/Components/Test"

```

**Comment by IllusionMH** [comment]
Looks like you don't have anything that will match path `test/path/to/Components` because most likely you have
```json
"paths": {
    "test/path/to/Components/*": ["./nested/comp"]
}
```

but your first import doesn't have trailing `/`, so it won't be matched (`"test/path/to/Components/" will be`)

You need to explicitly specify mapping for exact match 

```json
"paths": {
    "test/path/to/Components": ["./nested/comp/index.js"],
    "test/path/to/Components/*": ["./nested/comp/*"]
}
```
or use path for 1 folder higher in tree (`"test/path/to/*": ["./nested/*"]`) but will require adding `Components` by hand.


I guess it's because you can override exact matches as you want otherwise
![image](https://user-images.githubusercontent.com/1312662/65058575-25cf6900-d97d-11e9-9204-7b298758c455.png)

**Comment by nmalyschkin** [comment]
@IllusionMH Thank you for your answer!

this is how my jsconfig.json looks like
```json
{
  "compilerOptions": {
    "target": "es6",
    "baseUrl": ".",
    "paths": {
      "test/*": ["./test/*"],
      "Components/*": ["./src/client/App/Components/*"],
      "wp/*": ["./webpack/*"],
      "public/*": ["./public/*"],
      "commons/*": ["./src/commons/*"]
    }
  },
  "exclude": ["node_modules", "dist", "build"]
}
```

In `Components` there is a directory `HOC` with multiple high order components, which are exported through a `index.js`.

I would like to import multiple HOCs like that:
```js
// does not work
import { hoc1, hoc2, hoc3 } from "Components/HOC";

// this does work
import { hoc1, hoc2, hoc3 } from "Components/HOC/index";

// this works aswell, but really not how it should be
import hoc1 from "Components/HOC/hoc1";
import hoc2 from "Components/HOC/hoc2";
import hoc3 from "Components/HOC/hoc3";
```

**Comment by IllusionMH** [comment]
@nmalyschkin you should explicitly specify `"moduleResolution": "node"` to make TS check for `index.js` files in this way.

![image](https://user-images.githubusercontent.com/1312662/65067070-553aa180-d98e-11e9-8831-e08ebc3e16b3.png)

**Comment by nmalyschkin** [comment]
@IllusionMH Yes, this worked for me!! Thank you!

Sadly this is not mentioned in the docs :/
