### ISSUE TITLE
Linting and file format issue with #!/usr/bin/env node

### ISSUE THREAD

**Issue by ludohenin** [Microsoft/vscode#811]
When declaring a bin file with `#!/usr/bin/env node` it forces the document type to `javascript` where I have a `typescript` one. It breaks `tslint` and asks for enabling ES6 in `jsconfig.json` file.

**Comment by alexandrudima** [comment]
@ludohenin 

VSCode uses the first line `#!/usr/bin/env node` as a hint that this is a JavaScript file (since node can only run javascript). I think this is a fair assumption and holds true in most of the cases, except ones like this where a different language (typescript) is used to generate javascript.

Given most of the times this hint is correct, in the times when it is not, please use the switcher in the bottom right to manually change the language to TypeScript.
