### ISSUE TITLE
Never-ending LOOKUP for node_modules and bower_components from mount folder.

### ISSUE THREAD

**Issue by pairwiserr** [microsoft/vscode#81121]
I have a remote server that I mount to my local machine using `sshfs`. Every time I open a js file to edit, VS Code does a `LOOKUP` for `node_modules` and `bower_components` inside subdirectories, sister directories . I've tried excluding these search rules in setting, thinking it might be the cause of the issue, but it doesn't stop the issue.

- VSCode Version: 1.28.1
- OS Version: Ubuntu 16.04 Xenial

Steps to Reproduce:

1. Run `sshfs -o Ciphers=chacha20-poly1305@openssh.com,compression=no,allow_other,debug,reconnect user@1.2.3.4:~/ /mnt/`
2. Open a javascript file from mount in vscode.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This issue is similar to https://github.com/microsoft/TypeScript/issues/30817

In order to provide good intellisense, the builtin js/ts extension needs to look into the node_modules folder. There is no good way to disable this behavior as it is essential to how our intellisense works. 

You can disable the built-in `JavaScript and TypeScript language features` extension entirely if this is causing serious problems for you. Search `@builtin javascript` in the extensions view to do this
