### ISSUE TITLE
Some breakpoint icons too small and not clear

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#81151]
The log point icon looks a bit smaller than the breakpoint icon

![Screenshot 2019-09-17 at 16 18 44](https://user-images.githubusercontent.com/1926584/65231777-54118d80-dad0-11e9-8774-3e72fc0a7684.png)

The unsported breakpoint icon is also very small and more looks like a glitch than something meaningful
Can we somehow make them a bit larger (more clear)?

![Screenshot 2019-09-19 at 11 24 40](https://user-images.githubusercontent.com/1926584/65231745-45c37180-dad0-11e9-8c5e-c9640992a08a.png)

fyi @weinand

**Comment by misolori** [comment]
The log point icon is currently the same size as the other ones. Because of its shape (diamond) there is a bit of an illusion that it's smaller. I can make this icon a bit bigger:

<img width="194" alt="image" src="https://user-images.githubusercontent.com/35271042/65278427-f6d20800-dae0-11e9-8a54-116ee0a0715b.png">

But the unsupported icon is also the same size as the rest, and if we increase the size of that one it will look larger than the rest:

<img width="139" alt="image" src="https://user-images.githubusercontent.com/35271042/65279080-482ec700-dae2-11e9-9ac4-1a7501790592.png">

Thoughts?

**Comment by isidorn** [comment]
I like the logpoint size increase.
For the unsupported icon, we should not increase the size but somehow make the ! more clear. So it does not look like a glitch. Though the unsuported one does not really appear that often, so I can survive with the current one for now.

**Comment by misolori** [comment]
This is now updated. I also made the unsupported `!` icon a little bigger:

|Before|After|
|---|---|
|<img width="88" alt="image" src="https://user-images.githubusercontent.com/35271042/65525095-d1a81580-dea3-11e9-93c4-34f1506513dd.png">|<img width="83" alt="image" src="https://user-images.githubusercontent.com/35271042/65525305-23e93680-dea4-11e9-8c9a-2c84f434a621.png">|

**Comment by isidorn** [comment]
Lovely. Look's better on this picture. I'll try it out..
