### ISSUE TITLE
SetVariable doesn't trigger reevaluation of stale variables

### ISSUE THREAD

**Issue by wesrupert** [Microsoft/vscode#8118]
- VSCode Version: 1.3.0-insider, 2016-06-23

Assigning to a variable doesn't prompt a reevaluation of any variables that depend on it. Variables can be stale after setting a variable in languages such as C# (e.g. a property in the locals window), and watch expressions can be stale in all languages since they can be arbitrary expressions dependent on the changed variable.

**Comment by isidorn** [comment]
June to investigate

**Comment by wesrupert** [comment]
In general, this issue can be expanded to evaluating any expression. I hadn't even thought of the repl in the debug console, but you can trigger expressions such as `a = 3`, and `a` won't update in the locals / watches that depend on `a` won't reevaluate. I'm not seeing a way for a debug adapter to work around this issue either, since afaik VS Code needs to send a variables request first in order to care about a variables response. VS Code needs to either handle stale expression reevaluation, or add something to the protocol where a debug adapter can notify VS Code that its variable state is stale.

**Comment by isidorn** [comment]
Ok I have pushed a fix that the watch expression are always up to date (when evaluting from repl or changing variable values).

Now we have the issue that the local variables can be outaded if an evaluation happens in the repl, or if a variable that is dependent upon is changed via setVariable.
This issue is already captured in #2399 thus closing this as duplicate.

@wesrupert @weinand please comment on that issue with ideas on how to update variables after evaluation. VSCode can send the variables request again (but that seems to heavy to be done on each repl evaluation) - or the adapter could somehow notify vscode that a variables inside locals has updated. I am open for suggestions

**Comment by ansyral** [comment]
@isidorn seems right now the code to trigger an event to re-evaluate expressions in watch window is removed. See [setVariable](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L289). And  if I set a variable, its value in watch window is still out of sync. Any idea about this?

**Comment by isidorn** [comment]
@ansyral thanks for pointing this out, I have pushed a fix which takes care of this issue cd79dfce70
