### ISSUE TITLE
Edit and continue [Node.js] 

### ISSUE THREAD

**Issue by sant123** [Microsoft/vscode#8127]
Hi, is it possible to add edit and continue in Node.js instead of using Nodemon? This feature can be appreciated in Node.js tools for visual studio. 

Thanks.

**Comment by weinand** [comment]
No, this is not yet possible.

**Comment by sant123** [comment]
@weinand thanks for your answer, but would you consider it right? 😊

**Comment by weinand** [comment]
@sant123 sure, that's the reason for the little work 'yet' 😊

**Comment by sant123** [comment]
Thanks, I really appreciate it!

**Comment by eladnava** [comment]
I second this, adding Edit and Continue (the ability to make changes to the Node.js source code while the debugger is in break mode) as implemented in Visual Studio will make VS Code the damned best Node.js development tool out there (not that it isn't already -- but this will definitely make a huge difference).

The ability to modify your code in the middle of debugging has always been a huge time-saver for those working with Visual Studio. And the ability to modify the current executing statement (by dragging the yellow arrow in Visual Studio) is just as important.

Did you know that Node.js Tools for Visual Studio already supports edit-and-continue?

> Enjoy stepping through your code with breakpoints and automatic exception notifications in Visual Studio's interactive debugger. Advanced features include conditional breakpoints, tracepoints, hit counts, edit-and-continue, and cross-OS (Linux/MacOS/Windows) remote debugging.
https://www.visualstudio.com/en-us/features/node-js-vs.aspx

I wonder how difficult it would be to get VS Code to support this as well. It seems that the Node.js debugger already supports this feature, otherwise, NTVS would not be able to implement it.

Also, according to a recent Node.js survey conducted by RisingStack, the biggest pain-point in Node.js today is debugging. I think that the introduction of this feature will definitely change that, as well as mitigate the use of `console.log`:

> The results also tell Node developers major pain-point: debugging.
https://blog.risingstack.com/node-js-developer-survey-results-2016/?utm_source=nodeweekly&utm_medium=email

Tagging @bpasero and @joaomoreno as I really think they should seriously consider and prioritize this.

**Comment by sant123** [comment]
Any advance on this? Just asking :stuck_out_tongue_closed_eyes:

**Comment by weinand** [comment]
see #6930
