### ISSUE TITLE
Scrollbar represents current view inaccurately

### ISSUE THREAD

**Issue by KoBeWi** [microsoft/vscode#81366]
Issue Type: <b>Bug</b>

I can't believe no one reported it yet (I searched though >_> ), but the white rectangle on the scrollbar representing current view is bigger than what is being displayed. It makes it really hard to navigate to e.g. code diffs, because each time I need to scroll up and down multiple times until I find the actual line, even though according to scrollbar it should be on screen.

Just see here:
![image](https://user-images.githubusercontent.com/2223172/65507390-1f397800-dece-11e9-943f-50f4aac39157.png)
Compare the yellow lines on the left (added code) with the small blue rectangle on the scrollbar. The particular code portion occupies almost whole view, while according to scrollbar it's just a small part of the screen.
It should probably display something more like that:
![image](https://user-images.githubusercontent.com/2223172/65507559-78091080-dece-11e9-9893-03203e10df06.png)

I have DPI scalling enabled in my OS, if that's relevant.

VS Code version: Code 1.38.1 (b37e54c98e1a74ba89e03073e5a3761284e3ffb0, 2019-09-11T13:35:15.005Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (9.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by IllusionMH** [comment]
I think it is by design, and therefore wasn't reported or already closed.
There is minimum slider size (20px) otherwise it will be hard to use it with mouse for large files.
Decorations has min height 6px.
Therefore for big file you'll still see noticeable decorations (instead of nothing that takes 1/300px) and still be able to use slider with mouse (without need to hit that 1px unnoticeable slider), but they won't align.

**Comment by KoBeWi** [comment]
So maybe the slider's top and bottom could be dimmed, to represent that this part is "out of screen"? Dunno, it's just totally unintuitive and unreliable.

Is there maybe a better way to seek to the parts marked as diff? (other than going out of the way to Working Tree and back)

**Comment by IllusionMH** [comment]
Using `>Move to next Change`/`>Move to Previous Change` in Command palette or <kbd>Alt+F5</kbd> / <kbd>Shift+Alt+F5</kbd>

**Comment by alexandrudima** [comment]
Indeed, the scrollbar is artificially increased to allow to be gripped with the mouse. This is pretty standard behavior of scrollbars... all the scrollbars I have seen, native or otherwise have a min height / min width... I agree this could become confusing but I wouldn't want to change the rendering, as the slider is already quite tiny for large files and overloading the rendering of it wouldn't bring a lot IMHO.
