### ISSUE TITLE
trimAutoWhitespace doesn'n work on Windows 7

### ISSUE THREAD

**Issue by miguelchico** [Microsoft/vscode#8145]
- VSCode Version: 1.2.1
- OS Version: Windows 7

Steps to Reproduce:
1. Open code in an empty folder.
2. Configure trimAutoWhitespace to true
3. Create a new js file and fill with some valid code.
4. Add some whitespaces at the end of some lines or at beggining.
5. Save the file.

It should remove unnecessary  whitespaces but it doesn't.

I tried with all autoSave options

**Comment by bpasero** [comment]
@miguelchico can you try setting `files.trimTrailingWhitespace` instead?

@alexandrudima fyi I think this might confuse more users and we might want to rename this setting to make this more obvious?

**Comment by miguelchico** [comment]
@bpasero that works! But... I don't understand because I found this option here https://code.visualstudio.com/Updates#_editor.

What I should do? Keep both properties? But keep trimAutoWhitespace and don't is the same for me right now...

Anyway thank you for the quick response.

**Comment by alexandrudima** [comment]
The `editor.trimAutoWhitespace` trims automatic whitespace inserted by the editor when you press `Enter` or `Tab`. 

The editor inserts automatic whitespace to help you align your code. e.g. if a line is indented with `\t\t` and at the end you have a `{`, and you press `Enter`, most likely on the next line you'd wanna have 3 indents, so instead of inserting only `\n`, the editor inserts `\n\t\t\t`. The last `\t\t\t` is marked as automatic whitespace that will get removed automatically if `editor.trimAutoWhitespace` is on and if you don't use the automatic whitespace (i.e. do not type at that location).

But ... it will not remove "non-auto" whitespace such as that you insert with `Space` because in that case the editor is asked to insert `<space>` and it inserts `<space>`, hence no automatic whitespace.

Sorry for the long and complicated explanation, I hope it makes sense!

**Comment by miguelchico** [comment]
Oooook, now I understand.
There is a different between the white spaces included by the editor and by the user.

Thank you very much!
