### ISSUE TITLE
Suggestion list for launch.json is inaccurate in some cases

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#81459]
@karrtikr commented on [Wed Sep 25 2019](https://github.com/microsoft/vscode-python/issues/7612)

## Environment data

- VS Code version: 1.38.1
- Extension version (available under the Extensions sidebar): 2019.10.38352-dev
- OS and version: Windows

## Expected behaviour

![image](https://user-images.githubusercontent.com/13199757/65645901-10c28d80-dfae-11e9-8791-de0015478e5a.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/13199757/65645867-f7b9dc80-dfad-11e9-8ed4-dc88d57933e3.png)

When pressing `CTRL + SPACE` to pop up suggestions after the very last curly bracket, it shows the wrong things in the list.

cc @luabud 

---

@luabud commented on [Wed Sep 25 2019](https://github.com/microsoft/vscode-python/issues/7612#issuecomment-535274542)

I can repro it with 2019.8.29288. I think this is reason-preexisting 

---

@karrtikr commented on [Wed Sep 25 2019](https://github.com/microsoft/vscode-python/issues/7612#issuecomment-535275520)

It worked before AFAIC recall. This maybe upstream VSCode issue which is why you're able to repro it with the older versions.

---

@DonJayamanne commented on [Wed Sep 25 2019](https://github.com/microsoft/vscode-python/issues/7612#issuecomment-535341943)

Isn't this an upstream issue?

**Comment by isidorn** [comment]
Yes, I can reproduce this.
@aeschli the issue is that triggering inteli-sense on the last bracket shows items as if the inteli-sense is triggered inside an object, not outside it.

Repro steps. Have a `launch json` with the following content
```
{
    "configurations": [
        { }*
    ]
}
```
Trigger intelistense where I put the star ( do not actually have a *). Notice that you get suggestions as if you were inside the bracket, not outside.

@karrtikr for the future please concise and precise bug descirptions, not a log of your discussion in the other repo. My description from above is a good example which does not require any extensions or anything. Thanks

**Comment by isidorn** [comment]
@aeschli ping for this. Let me know if you need more details from me.
