### ISSUE TITLE
Markdown preview incorrectly renders nested lists

### ISSUE THREAD

**Issue by 560889223** [Microsoft/vscode#8146]
- VSCode Version: 1.2.1
- OS Version: MacOS X 10.11.5

Steps to Reproduce:
1. Create a new .md file (Markdown fiile)
2. Put the following Markdown content (see "Non-working Code" attached) in the file.
3. Preview the Markdown doc.

"Non-working Code":

```
1. A (0 leading spaces)
  2. B (2 leading spaces)
    * C (4 leading spaces)
    * D (4 leading spaces)
      * E (6 leading spaces)
```

"Working Code":

```
1. A (0 leading spaces)
  2. B (2 leading spaces)
    * C (4 leading spaces)
    * D (4 leading spaces)
       * E (7 leading spaces) // this line has one more space than the "non-working code"
```

**Comment by mjbvz** [comment]
We use markdown-it for rendering, which targets the common mark spec. I think this is the expected behavior according to the spec, but the rules lists and indentation are complicated so I could be wrong.

If you believe the rendering is incorrect, please open a bug against markdown it so that they can investigate: https://github.com/markdown-it/markdown-it

Thanks
