### ISSUE TITLE
Wrong report for [Extension causes high cpu load]

### ISSUE THREAD

**Issue by formulahendry** [microsoft/vscode#81466]
In https://github.com/microsoft/vscode-azure-iot-toolkit/issues/375, we receive a user report the issue of [Extension causes high cpu load].
However, after investigating the [vsciot-vscode.azure-iot-toolkit-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-azure-iot-toolkit/files/3600824/vsciot-vscode.azure-iot-toolkit-unresponsive.cpuprofile.txt) file, we find there is no relation the the extension. 
We think there would be a wrong report for [Extension causes high cpu load].

**Comment by jrieken** [comment]
The profile points at code loading, e.g takes a long time to load the code of the extension. That's either because the extension file is huge (iff bundled), there are many, many files to load (iff not bundled), or if the user's machine is slow.

<img width="1066" alt="Screenshot 2019-09-30 at 14 18 00" src="https://user-images.githubusercontent.com/1794099/65877939-27415e00-e38d-11e9-939a-7cc3adb4e4ed.png">
