### ISSUE TITLE
click+click select word with dot

### ISSUE THREAD

**Issue by kongdd** [microsoft/vscode#81461]
For example, vscode can't select `panel.poly_grid` automatically, only select words before dot (panel) or after dot (poly_grid).

**Comment by IllusionMH** [comment]
/question

AFAIK the only action on double click in editor is select word, which in turn uses settings ``"editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"`` to determine word boundaries. As you can see dot is also included.

So you can remove `.` from global setting or provide separate settings for each language in User or Workspace `settings.json`

```json
{
    "[python]": {
        "editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",<>/?" // no .
    },
    "[javascript]": {
        "editor.wordSeparators": "`~!@#$%^&*()=+[{]}\\|;:'\",.<>/?" // no -
    }
}
```

If you are sure that this issue is closed by mistake provide more details why proposed solution doesn't work.
