### ISSUE TITLE
Untangle electron parts from update contribution

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81477]
Most of the pieces in `src/vs/workbench/contrib/update/browser/update.ts` are useful in the web as well, but there is one dependency to the Electron window ID that we should take out to a `electron-browser` only piece. 

I pushed https://github.com/microsoft/vscode/commit/156b5fd4f55acf12dc89506331f969d4c46fd2c4 to adopt a new `IElectronEnvironmentService` that carries this ID. Ideally we could move that piece out.

**Comment by joaomoreno** [comment]
That `windowId` is there to prevent showing errors in all windows when checking for updates results in "no updates available".

It's tricky to solve since the `checkForUpdates` method doesn't return the result of the operation since deep down everything is a state machine. We could easily make it return the result on Windows and Linux but it's harder to do on macOS since we don't own that state machine deep down. But we can sketch something up foh sho.
