### ISSUE TITLE
launch.json environment not working as expected

### ISSUE THREAD

**Issue by crazydef** [microsoft/vscode#81488]
Ubuntu, VSCode v1.38.1

Environment variables set in launch.json cannot be referenced through ${env:...} in launch.json.

I.e., the following doesn't work:

environment: [
  { "name": "ROOT", "value": "${WorkspaceFolder}" },
  { "name": "EXT", "value": "${env:ROOT}/extensions" },
  { "name": "PATH", "value": "${env:ROOT}/bin:${env:EXT}/bin:${env:PATH}" },
]

results in PATH being set to:

/bin:/bin:/sbin:/bin:/usr/bin:/usr/local/bin:/snap/bin

**Comment by isidorn** [comment]
@crazydef What happens if you just have a `program: ${env:ROOT}`. Does it get replaced properly?
Assigning also to @alexr00 since she owns the configuraiton resolver service now.

Code pointer https://github.com/Microsoft/vscode/blob/c2997da2ac72121a46e8e6ce504d5f47495b9ff5/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L229
@crazydef in case you want to debug just put F1 > developer tools > put a breakpoint to the code poitner and figure out the replacment.

**Comment by alexr00** [comment]
Would require work in variable resolver and debug.
