### ISSUE TITLE
Breakpoint locations don't work while remote debugging

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#81567]
- Debug a node app on a remote
- Set a breakpoint
- See this error: `Error processing "breakpointLocations": Error: Breakpoint ignored because generated code not found (source map problem?).`

First off the error shouldn't show up in the console and that's on my end. But the real problem is that we get the remote path for that request:

```
From client: setBreakpoints({"source":{"name":"main.js","path":"/datadrive/testapp-node/main.js"},"lines":[2],"breakpoints":[{"line":2}],"sourceModified":false})
[...]
From client: breakpointLocations({"source":{"name":"main.js","path":"vscode-remote://ssh-remote%2Brobfast/datadrive/testapp-node/main.js","origin":"read-only core module"},"line":2})
```

**Comment by roblourens** [comment]
I realized that I am marking all script with an origin in the loadedSource event, which should be fixed, and checked whether this is due to that, but it doesn't seem to be related. Here is the request without the origin.

`[21:05:51.629 UTC] From client: breakpointLocations({"source":{"name":"main.js","path":"vscode-remote://ssh-remote%2Brobfast/datadrive/testapp-node/main.js"},"line":2})`

**Comment by isidorn** [comment]
@roblourens yeah I also saw the console warnings, would be great to get rid of those.
The breakpoint and breakpoint locations uses absolutely the same logic to get the source as can be seen [here](https://github.com/Microsoft/vscode/blob/c2997da2ac72121a46e8e6ce504d5f47495b9ff5/src/vs/workbench/contrib/debug/browser/debugSession.ts#L382)
I believe the issue is that the breakpointLocations uri I get from the workbench, and the breakpoint uri I somehow get from the adapter. Not sure how this happens.
I can setup remote debugging and investigate on wednesday (since tomorrow I am out).

**Comment by isidorn** [comment]
Strangely I setup SSH debugging and I see the errors, however from my investigation it looks like I am sending the same path for both setBreakpoints and breakpoint locations. Please note that I was unable to set this up from source, so I tried from insiders, thus my findings might not be correct since the source is minified and I might have missed something

**Comment by roblourens** [comment]
![image](https://user-images.githubusercontent.com/323878/65902195-ad9a7780-e36e-11e9-8954-93c6421e6575.png)

It looks like you are sending the remote URI here but I don't really know what to look for, so tell me what you need to see if you want me to look into it more.

**Comment by weinand** [comment]
@isidorn There is no way to find "Source" objects dynamically in DAP requests as they are coming from DAs implemented in any language and they don't include any meta information about classes like "Source". They only way to address the issue is by generating the implementation of "fixSourcePath" from the DAP schema.
