### ISSUE TITLE
Opening a file now often causes the last file opened to close

### ISSUE THREAD

**Issue by marsjupiter1** [microsoft/vscode#81650]
Issue Type: <b>Bug</b>

If I open one file and do not edit it, when I open another file the unedited file closes.

VS Code version: Code - Insiders 1.39.0-insider (817eb6b0c720a4ecbc13c020afbbebfed667aa09, 2019-09-25T05:27:57.484Z)
OS version: Linux x64 5.0.0-29-generic
Remote OS version: Linux x64 3.16.0-4-amd64

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
lex-flex-yacc-bison|fau|0.0.3
remote-containers|ms-|0.78.0
remote-ssh|ms-|0.46.1
remote-ssh-edit|ms-|0.46.1
remote-ssh-explorer|ms-|0.46.1
remote-wsl|ms-|0.39.7
vscode-remote-extensionpack|ms-|0.17.0
Go|ms-|0.11.7

</details>

**Comment by IllusionMH** [comment]
/question

This feature is called "Preview". File name will be in italics for preview tabs.

You can disable this feature by disabling **Workbench › Editor: Enable Preview** (`workbench.editor.enablePreview`) in settings.
If you don't want to disable this feature - use double click to open files.

Please let developers know if you are sure that this issue was closed by mistake.
