### ISSUE TITLE
[BUG] Weird Issues

### ISSUE THREAD

**Issue by angelhdz** [microsoft/vscode#81682]
- VSCode Version: 1.38.1
- OS Version: Windows 10 Pro 64bit

Steps to Reproduce:

1. Writing code or text in any file (JSON config files, classes files, etc.)
2. Get this annoying error 
`{
	"resource": "/c:/Users/Angel/Documents/Programming/Dart/projects/Test Web/test_routes/test_routes/lib/route_generator.dart",
	"owner": "languageErrors441",
	"severity": 8,
	"message": "Parse error on line 1:\n\n^\nExpecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got '1'",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}`
3. Reload VSCode
4. Error goes away

![image](https://user-images.githubusercontent.com/10191085/65913582-2b29ac00-e39e-11e9-9efc-c500fdbef8a8.png)

It happens in every Workspace, every language I'm working with (Dart, C#, Python, AS3, Javascript). Also happens with extensions disabled. This looks like the issue I've been reporting lately that Intelli-Sense just stop auto-completing object members or built-in functions/properties/keywords after a while of working on VSCode. This other issue also gets solved by reloading the workspace.

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by sandy081** [comment]
It does not look to me that this is caused by VS Code. I suspect an extension is causing this. Please try following:

- Disable all installed extensions. Reload window and check if this error occurs
- Go to built in extensions view in VS Code and disable extension by extension and reload window. Please check if this error occurs and let us know which extension is causing this.
