### ISSUE TITLE
Search viewlet right padding is incorrect

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8169]
Seems closer to the right hand side than to the left:

![image](https://cloud.githubusercontent.com/assets/900690/16369028/96c966a8-3c35-11e6-8ff7-128d93670ad7.png)

**Comment by joaomoreno** [comment]
All viewlets except Search behave this way. There is always more margin on the left hand side. `12px` more to be precise, due to the viewlet title:

![image](https://cloud.githubusercontent.com/assets/22350/16563087/6ad607e2-4200-11e6-8141-06943ce35440.png)

Take the git viewlet:

![image](https://cloud.githubusercontent.com/assets/22350/16563037/2b4d3528-4200-11e6-85f6-d13123374565.png)

Notice how the fonts of the viewlet title and the search box are left-aligned. Notice how the search box is right-aligned with the last action's bounding box.

The Search viewlet is full of lies and falsely aligns to the right of the clear icon's **content**. It should align to the right of the **whole** clear icon, including its padding.

![image](https://cloud.githubusercontent.com/assets/22350/16562951/c6825074-41ff-11e6-8570-9dbf11751f25.png)

**Comment by bpasero** [comment]
@joaomoreno this issue was about the fact that the git input field has more margin to the left than to the right. Would we not just center the input fields we have across viewlets? 

Only looking at:

![image](https://cloud.githubusercontent.com/assets/900690/16563335/b5c234dc-4201-11e6-9505-eb5becbd97c1.png)

**Comment by joaomoreno** [comment]
You can't just look at one thing at a time. There are left and right paddings along the whole viewlet's content. If we were to increase the right padding, we'd be lying about the alignment with the actions above and we'd have to move them as well, in _every_ viewlet.

**Comment by bpasero** [comment]
Well today the input box is neither aligned in the center nor is it aligned to anything in the title area :)

**Comment by joaomoreno** [comment]
Of course it is.

![image](https://cloud.githubusercontent.com/assets/22350/16565882/ac8801a8-4210-11e6-9ed5-5004472f5b4d.png)

**Comment by joaomoreno** [comment]
You might think that, for instance, the Explorer title area is aligned to the center:

![image](https://cloud.githubusercontent.com/assets/22350/16565919/ec62aa58-4210-11e6-87e8-47c6218427b9.png)

But it's not, since the title has additional left padding:

![image](https://cloud.githubusercontent.com/assets/22350/16565927/f91fd892-4210-11e6-8b72-ba83f97b89db.png)

Which forces its content to have it too:

![image](https://cloud.githubusercontent.com/assets/22350/16565937/07647598-4211-11e6-8e0e-8d5824f74bb1.png)

The explorer too, has more left padding than right. This has been constant throughout our whole design.

**Comment by bpasero** [comment]
That overflow icon does not really need all the margin/padding to the right I guess.

**Comment by joaomoreno** [comment]
I personally think it looks good as it is. Center alignment is not important. Left and right alignment of all items is, though. But the only way to fix this and have _center_ alignment would be to add margin to the right to **everything**, including the title actions.

The icon needs the padding because it's a click area. Make it smaller and it will be less _clickable_ than all the other actions.
