### ISSUE TITLE
Aux window: Allow to control drag and drop operations out of the window for e.g. opening new windows

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#8171]
This issue is for the user gesture of dragging a file or tab out of the window to have it open as separate window. This likely requires some changes in Electron to get working, since the target of the drag and drop operation is outside of the window.

For the request to open an editor in multiple windows easily, see https://github.com/microsoft/vscode/issues/10121

**Comment by eyalsk** [comment]
@bpasero DND can be pretty great but how about starting from something more primitive? like right click on a tab and create a new window? right click on a folder in the explorer and create a new window? I imagine you can pass all the information you need through IPC (Inter-Process Communication) but first you need to have this infrastructure.

**Comment by bpasero** [comment]
Yes, all related scenarios.

**Comment by eyalsk** [comment]
Okay, thanks. :)

**Comment by lostpebble** [comment]
As far as IDE's go, this is a very important feature for me - the ability to quickly and easily space out my workspace across screens, and view multiple parts of the code at once.

"Split Editor" doesn't cut it because one screen is two small and stretching the entire VS Code app across multiple screens is rather messy (code getting cut in the gutter of screens etc.)

I've been using the new instance method (Ctrl + Shift + N) and dragging windows into that - except it seems my settings and project context gets lost which makes it not a real a solution at the moment.

I understand there may be window management limitations with Electron holding this back (I remember Atom having this problem too), but I feel it at least warrants a comment and hope that there is a still a push to resolve this.

**Comment by WhatIfWeDigDeeper** [comment]
The work-around I discovered was to open a sub-directory first, like `src`, and then open the main directory, so you get two instances of VS Code so as to have the same project open in multiple windows.  This also works for single files like `> code readme.md`.  It's important to open the file or subdirectory first, otherwise Code is smart enough to detect that it is under the same project that is already open so it will not open another instance.

**Comment by siriuscc** [comment]
I have the same problem, and now dragging tab causes files to be copied, which is not what I want at all.

**Comment by tiagosiebler** [comment]
Shameless bump - any plans on getting this added. I'd even be happy with a "right-click -> open tab in new window" item.

**Comment by saulotoledo** [comment]
The extension suggested by @tiagosiebler above is helpful. However, you still lose context. The debugger, for example, does not work.

I understand there may be limitations to implement this feature, but I also vote for it. Working with multiple screens in VSCode is still painful. I have no experience with the project's source code, but ... would something like [this] (https://golden-layout.com/) be useful as a good start?

**Comment by WhatIfWeDigDeeper** [comment]
See this [stackoverflow answer](https://stackoverflow.com/a/43362800/753279)

"On Windows and Linux, press Ctrl+K, then release the keys and press O (the letter O, not Zero).

On macOS, press command+K, then O (without holding command).

This will open the active file tab in a new window/instance."

**Comment by yihuang995** [comment]
> As a work-around, see this [stackoverflow answer](https://stackoverflow.com/a/43362800/753279). I'm on a Mac and it works for me. I haven't tested Windows.
> 
> "On Windows and Linux, press Ctrl+K, then release the keys and press O (the letter O, not Zero).
> 
> On macOS, press command+K, then O (without holding command).
> 
> This will open the active file tab in a new window/instance."

Thanks, it is an alternative way but not best.

For example, when I use the official Extension Remote - SSH, these operations will create a new SSH connection, which produce new processing and need litlle time for connecting. And the development environment is initialized to default setting but not us currently used.

**Comment by Kurohyou** [comment]
Would love to see this! Especially since the behavior of copying a file to the desktop when you drag a tab out is not behavior I have seen in any other application which makes it extremely unintuitive.

**Comment by ubieda** [comment]
I'd really love to see this implemented. Are there any updates?

**Comment by oliverdrummond** [comment]
> I'd really love to see this implemented. Are there any updates?

+1

**Comment by Chan0081** [comment]
2023
still expecting this!

please!

**Comment by bpasero** [comment]
A first version of this is pushed to insiders that allows to drag an editor tab or tab group out of the window to open into a floating window (leveraging the new floating window support). 

Please try it out and let me know how it goes.

![Recording 2023-11-11 at 07 21 17](https://github.com/microsoft/vscode/assets/900690/3da8ecc9-e704-40a8-ace6-29e9cce8d2ad)


You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Seraphli** [comment]
I have a question. When a tab is dragged to create a new window, is it using the same session as the previous window? I'm wondering if when I'm debugging a program, the breakpoint information can be shared between windows. The current "duplicate current workspace" doesn't seem to achieve this.

**Comment by bpasero** [comment]
@Seraphli yeah it should, give it a try in insiders!

**Comment by bpasero** [comment]
Btw happy for some help with https://github.com/microsoft/vscode/issues/198128
