### ISSUE TITLE
Context key button doesn't work in explorer with native title bar

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#81766]
native title bars on windows, in the following state:

![image](https://user-images.githubusercontent.com/2193314/65979069-8d7bbe80-e429-11e9-894b-95af00681320.png)

Pressing the context key button will focus the outer explorer:

![image](https://user-images.githubusercontent.com/2193314/65979110-9bc9da80-e429-11e9-91c9-394e422a3760.png)

Pressing again will open the context menu for the outer explorer, not the item I focused.

**Comment by sbatten** [comment]
@Tyriar showed this reproduces only on native titlebar. Interestingly, the native menu did flash and disappear before switching focus in one example

**Comment by sbatten** [comment]
The list widget is firing twice in the native case from here:
https://github.com/microsoft/vscode/blob/6f7c9f38b6ab8b0d8ea5cf4fb7eb89f63863e22d/src/vs/base/browser/ui/list/listWidget.ts#L1153-L1182

The custom case probably handles this because focus is removed from the element before the next event is fired.

But, in the native case the following events are triggered at this layer:
1. keyup
2. keydown
3. keyup (resets the did just press context menu key variable)
4. contextmenu (is not filtered because of event order)

Since no one is complaining today and @joaomoreno is out, I will leave it. But it seems the fix should be in the list widget.

**Comment by joaomoreno** [comment]
Hm... I don't have such a key on my keyboard... but <kbd>Shift F10</kbd> works fine...

Can you still repro it?

**Comment by Tyriar** [comment]
It's still buggy, it now focuses `.gitattributes` for some reason and flashes the loading sign on the cursor (for 1 frame?):

![a2e1eeb5-bbbb-422d-8828-3e34bdb3ce57](https://user-images.githubusercontent.com/2193314/78386576-ac9f0880-7592-11ea-8fe3-0039e8510e4c.gif)

Shift+F10 works fine.

**Comment by joaomoreno** [comment]
Since I won't have such a key any time soon, this is up for grabs.

I can't reproduce using the OnScreen Keyboard, which has a context menu key.
