### ISSUE TITLE
Search / Replace: editors do not open when auto save is enabled

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8176]
This makes it impossible to undo a replace operation. Need to investigate why editors do not open when auto save is enabled.

**Comment by bpasero** [comment]
@sandy081 actually I think you should explicitly call openEditors() with the files to be replaced from the search land.

**Comment by sandy081** [comment]
@bpasero This issue is not specific to Search/Replace. It is also true for all bulk edit functionalities. Eg: Rename also does the same thing if auto save is enabled. I admit that behavior is not correct and not helpful especially if you want to undo. This again exposes the problem of global undo.

IMO, we should fix this in bulk edit infrastructure - to open edited files always. We can either leave this as is or change after we have global undo functionality.

@jrieken What do you say?

**Comment by bpasero** [comment]
+1 for opening editor before doing the bulk edit, independent from how auto save is configured. this also allows the user to undo the change in each editor if needed.

**Comment by bpasero** [comment]
I actually found a bug in my implementation of opening editors (https://github.com/Microsoft/vscode/issues/8354) that causes this to fail when auto save is enabled. 

I am also easy to fix this on my end if we decide against doing this on the bulk edit level.

**Comment by bpasero** [comment]
Fix pushed, should work now also when auto save is enabled, but please verify for both cases.
