### ISSUE TITLE
Default discretion does not work as expected for image editors

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#81784]
#81698

`"discretion": "default"` in package.json, I expect this new extension to replace the built-in image preview but it doesn't seem to work, instead I get the option like when I leave discretion out:

![image](https://user-images.githubusercontent.com/2193314/65986169-33362a00-e438-11e9-9c7c-0f80226b991f.png)

If both are marked as default the non-built-in extension should win.

**Comment by mjbvz** [comment]
Yes we need a new level called `"builtin"` or similar that would behave as you describe. I remember us talking about this but I didn't have time to implement it. Will look into for October

**Comment by mjbvz** [comment]
Fixed by f462eab9694a944fdd0c65dbe3fb7b2774ee3092

On the expected behavior of new priority, custom editors marked `builtin`:

* Should still show up in the `reopen with` menu
* Should be selected by default if they are the only custom editor (or if all the other editors has a priority of `option`)
* However, if another editor exists with the priority of `default`, then that editor should automatically be chosen.
