### ISSUE TITLE
Avoid synchronous WebContents calls in webview editor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#81783]
#81698

Related: https://github.com/microsoft/vscode/issues/81780

`getOwnerBrowserWindow` and `isDestroyed` are 2 synchronous calls that happen on layout that can be expensive (seems around 0.5-8ms on my Windows box). I think we can cache the owner browser window object and listen to `on('destroyed')` instead.

https://github.com/microsoft/vscode/blob/9c1fa6f48e19e6424fe082e870317de10dbf6b38/src/vs/workbench/contrib/webview/electron-browser/webviewElement.ts#L578-L581

**Comment by mjbvz** [comment]
Marking for october since it is not a regression

These checks were added to fix some crashes we were hitting so we need to be careful here. If you call certain webview methods  without knowing if the webview was destroyed (which we used not to be able to determine reliably) things can go very wrong

**Comment by Tyriar** [comment]
@mjbvz tracking whether it's destroyed via the `destroyed` event and remembering it will likely be faster for that though.

**Comment by mjbvz** [comment]
Seems like this code isn't even required anymore... 

Let me know if you notice anything weird with webview scaling in the 1.40 insiders
