### ISSUE TITLE
Blinking block cursor can obscure inline breakpoint

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#81800]
Testing https://github.com/microsoft/vscode/issues/81175

1. Set cursor to blink and cursor style to block
2. Start debugging
3. On a line with inline breakpoints, place cursor directly before an inline breakpoint indicator

![blinkingBlockCursor](https://user-images.githubusercontent.com/3672607/66003048-e9f6d200-e459-11e9-80fb-19e831473866.gif)

**Comment by isidorn** [comment]
The issue here is that the blinking block cursor goes over the decoration.
The decoration is actually empty and on top of my empty decoraion I have a conent widget. This seems to not play weel with the cursor block style. Since the block seems to go from one character to the other by definition and thus overlaps the inline breakpoint.
fyi @alexandrudima
