### ISSUE TITLE
When two editors are contributed for the same file, neither gets chosen

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#81828]
Testing https://github.com/microsoft/vscode/issues/81698

This happens even if I make one of them `"discretion": "default"`

This first time I opened a .png with two editors to handle png installed, I was shown an editor that had a message about the file being binary. 
I opened the file as binary.
Then I ran the reopen command to open with one of my image editors. That worked and activated the editor extension.
After that, when opening pngs they opened as binary then asked me to pick which editor to use.

This seems like an awkward flow. 
- I shouldn't have gotten the binary message, just immediately show me the quick pick with editor options.
- Later, I don't think the file should open as binary first then offer the quick pick. Only show the quick pick, and offer to make one of the editors default.

**Comment by mjbvz** [comment]
Ok, so the clarify the expected behavior now: if there are 2+ editors and we can't pick one to show, we still show the default editor plus the quick pick. I found it confusing if we only show the quick pick in such cases as it looks like the file open did nothing. 

Based on your feedback, I've added a button in the quick pick that will set the selected editor as the default. This currently is drawn using a setting gear but we can discuss this further in one of the UX syncs. 

If others feel strongly about not showing the default editor on first open, we can also revisit that decision
