### ISSUE TITLE
Source control view: On Command+Enter in Source Control, run git push after a commit was done

### ISSUE THREAD

**Issue by zemiak** [microsoft/vscode#81836]
It's really convenient to write a commit message and then just press Command+Enter to commit the changes. After that, for a push, I need to go to the ... menu with a mouse and select the Push menu item.

Allow a second Command+Enter to push the changes to the default origin.

**Comment by nguyenkhois** [comment]
I think it's not a good choice when you combine "commit + push" at one time. I use "Keyboard Shortcuts" in VSCode and it works fine. I redefine my shortcuts:

- Ctrl+Alt+G to open Source Control and I do what ever I need (write message, choose files for commit because I don't want to commit all files,...).
- Ctrl-Enter to commit.
- Ctrl-Alt-P to push -> Done

It's enough and fast for me! :-)

**Comment by Tyriar** [comment]
You can also use the command palette (F1 or cmd+shift+p) or setup a custom keybinding.

**Comment by zemiak** [comment]
Just for the record and maybe for anybody who will look for it: Keyboard Shortcuts, look for Git: Push, assign Shift + Command + Enter, When expression: scmRepository
Almost as good :)
