### ISSUE TITLE
Debug: improve path conversion in dap arguments

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#81848]
Our current approach is very error prone since we hard code all the requests that have uris and try to fixSourcePath them. 
I think we should just go through all the requets and look for `Source` objects and convert them all similar to how vscode is converting URIs.

Code pointer to the current approach 
https://github.com/Microsoft/vscode/blob/2943151b3aecaef0bb5ebec2c7188495df0cbfaf/src/vs/workbench/contrib/debug/common/debugUtils.ts#L194

**Comment by weinand** [comment]
There is no way to find "Source" objects dynamically in DAP requests as they are coming from DAs implemented in any language and they don't include any meta information about classes like "Source". They only way to address the issue is by generating the implementation of "fixSourcePath" from the DAP schema.
