### ISSUE TITLE
Debug smoke tests broken

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#81872]
It's getting stuck when looking for "Port: " in the output because this sourcemaps error is appearing:

<img width="729" alt="Screen Shot 2019-10-02 at 3 14 37 PM" src="https://user-images.githubusercontent.com/2193314/66085912-61defe00-e527-11e9-8154-8cfe64300c29.png">

@roblourens tells me @isidorn fixed this but it's still happening here?

**Comment by isidorn** [comment]
@Tyriar thanks for filling. I can repro this. What I filled was for the remote breakpoint Locations. This is unrelated to that.

@roblourens the issue seems to be that the node2 debug adapter is throwing here. Issue being that the breakpoint is probablly not yet bound (since the code is probably not yet lounded and is done lazily)
Can we change the node2 debug adapter such that if there is an error in the breakpointLocations you do not throw but just return an empty array of possible locations? That sounds more safe to me and should cover this case.
Let me know what you think.

**Comment by roblourens** [comment]
Oh sorry I was thinking these were remote smoke tests or something. Yeah I guess the debug adapter should swallow that error entirely.

**Comment by isidorn** [comment]
Thanks @roblourens !
