### ISSUE TITLE
javascript.suggest.names doesn't work if javascript.implicitProjectConfig.checkJs is enabled

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#81895]
This issue also happens in Insiders v1.39.0

- VSCode Version: 1.39.0
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Set `"javascript.suggest.names": true`
2. Set `"javascript.implicitProjectConfig.checkJs": true`
3. Notice that word based suggestions (in JS files) does not work
4. Set `"javascript.implicitProjectConfig.checkJs": false`
5. Notice that word based suggestions (in JS files) now work

Expectation:
Type checking (`javascript.implicitProjectConfig.checkJs`) should not have anything to do with word based suggestions (`javascript.suggest.names`).

Does this issue occur when all extensions are disabled?
Yes

**Comment by mjbvz** [comment]
This is by design but I'll update the documentation to make this more clear.

The reason: checkJs requires performs semantic analysis of the code. This means it needs to understand where symbols are defined and verify that they are used in a way that makes sense. For the example, consider the js:

```js
//@ts-check
{
	const foo = 123;
}
{
	foo // trigger suggest here
}
```

Check js will consider the second usage of `foo` to be an error because it cannot find any variable called `foo` that is valid in the second scope.

However `suggest.names` is designed to suggest names of symbols from the entire file, even if they are not valid in the current location (such as suggesting `foo` inside the second block). That makes its behavior incompatible with checkJs. So rather than showing suggestions that would produce an error, we drop them
