### ISSUE TITLE
IExternalTerminalService should move into electron-browser or node

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#81989]
This service is currently not implemented in the web and if it cannot, the interface should move into `electron-browser` or `node` to signal this.

**Comment by Tyriar** [comment]
`IExternalTerminalService` is used optionally by 2 commands that should work in web, remote and local:

https://github.com/microsoft/vscode/blob/207a00c7f688813eea1db7c5aee09829911e281a/src/vs/workbench/contrib/externalTerminal/browser/externalTerminal.contribution.ts#L36

I'm going to leave this as is because this seems preferable to duplicating these commands and having 2 contribution files. Let me know if you disagree.
