### ISSUE TITLE
Feature-Request: cursorRedo / Soft Redo

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode#82007]
There is a command called "cursorUndo" (name in command palette: "Soft Undo") that undo's cursor and selection movements.

There should be a matching "cursorRedo" (name in command palette: "Soft Redo") to redo those movements after undoing with "cursorUndo".

VSCode Version: 1.38.1
OS: Windows

**Comment by NotWearingPants** [comment]
It is not related to the suggested duplicates.

**Comment by NotWearingPants** [comment]
I am working on this. PR will be submitted soon.

**Comment by ejazr83** [comment]
I would like to propose a feature request to allow use of remote development feature of VScode when using remote Jupyter notebooks

Currently, to be able to execute remote Jupyter notebooks in VSCode, you need to have the Python runtime installed on your local machine.

To get the same benefits of remote VS Code development such as not requiring to install Python runtime, the Python Jupter remote execution should be able to run similar to a remote VS Code development environment.

Currently this works when you SSH to a box but it would be helpful if this can also be initiated when a remote Jupyter notebook is connected to so that the cells are run remotely rather than in local runtime

This will effectively make VS code use the remote runtime for the Jupyter notebooks rather than the local runtime removing the need to have Python installed locally for this use case.

**Comment by NotWearingPants** [comment]
@ejazr83
Cool cool but what does it have to do with my cursor redo feature request?
Did you mean to report a new issue?
