### ISSUE TITLE
Context menu is positioned wrongly when zoomed in

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#821]
> When I zoom in (using Ctrl+Shift++) the context menu that is shown when I right click somewhere is displayed in the wrong place. I attached two images one without any zoom where the menu is displayed correctly in the second one how is displayed after pressing Ctrl+Shift++ twice. In both cases the click is where the text cursor is. 

> Some information about my environment: This is under Windows 10. I'm using two monitors both with scaling of 125% (by that I mean the option named "change size of text apps and other items" in the diplay settings ) and the resolutions of the displays are 2560x1440 and 1080x2024.

**Comment by massimocode** [comment]
I can confirm this happens for me as well. I am using Mac OS X. The operating system's display scaling is off (i.e. 1:1). I have been experimenting and it seems as though the bug is that the right click menu is displayed according to the cursor position, but this calculation is not adjusted to take into account zoom.

The reason I say this is because if I right click near the top left of the editor, the cursor is quite close to the top left of the menu. But if I right click near the bottom right of the editor, the cursor is much further away from the top left of the menu. The misalignment is proportional to the distance from the top left of the editor.
