### ISSUE TITLE
Multi-Root Workspace: Exclude Subfolders

### ISSUE THREAD

**Issue by chriszwickerocteris** [microsoft/vscode#82145]
Similar to what #45470 is asking for, I would like to exclude certain folders from my multi-root workspace layout, mainly those subfolders that are mounted as root folders themselves, but sometimes also other files  / folders.

I suggest simply adding an `ignore` section, e.g.

```
{
  "folders": [
    {
      "path": "foo",
      "ignore": [
        "baz/"
      ]
    },
    {
      "path": "bar"
    },
    {
      "path": "foo/baz"
    },
    {
      "name": "Root",
      "path": ".",
      "ignore": [
        "foo/",
        "bar/",
        ".git/"
      ]
    }
  ],
  "settings": {}
}
```

**Comment by chriszwickerocteris** [comment]
I'm a bit confused by how this is being handled:

* this feature request suggests a way to handle what #45470 requests ***and additional requirements*** in a way that seems much simpler to implement than what is suggested in #45470.
* the issue is closed as "out of scope", but there's no information as to why - I understand everyone has very limited time available, but some kind of feedback would be helpful...

**Comment by rucoder** [comment]
up vote for the feature

**Comment by pacifier007** [comment]
These feature requests keep getting marked as out-of-scope with no explanation. It's a perfectly valid and needed feature. Example, my use-case here: https://github.com/microsoft/vscode/issues/91102#issuecomment-589244585

Related tickets:
#50638
#48262

**Comment by gnowland** [comment]
I agree, it would be great to be able to add a folder but exclude its sub-folders if we only want to work with the \*files\* within said folder, but not sub-folders.

**Comment by dfoverdx** [comment]
I figured out the solution that's mentioned in [the documentation](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_add-folder-to-workspace) but poorly (arguably never) explained.  I leave a comment here for the next sorry dev that comes looking for it.

In the root of the workspace folder in which you want to exclude files, create the `.vscode/settings.json`.  In this file, you can set `files.exclude` and it will only apply to that workspace folder, even if other workspace folders are subdirectories.

### File tree ###
```none
/
┣ .vscode/
┃ ┗ settings.json
┣ sub-dir/
┃ ┗ index.js
┗ workspace.code-workspace
```

### `workspace.code-workspace` ###
```json
{
  "folders": [
    { "path": "./", "name": "root" },
    { "path": "./sub-dir" },
  ]
}
```

### `./.vscode/settings.json` ###
```json
{
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true,
    "sub-dir": true,
  },
}
```

The explorer will now show two workspace roots: *root* and *sub-dir*.  Under *root*, `./sub-dir` is not listed.  Under *sub-dir*, all of its files are listed.

![File explorer screenshot](https://user-images.githubusercontent.com/3087358/116578842-a9c23480-a8c6-11eb-9148-809466aaeee3.png)

**Comment by Axelfoley85** [comment]
It is also possible to include these settings into the workspace configuration
```
{
	"folders": [
		{
			"path": "sub-fold"
		},
		{
			"name": "root",
			"path": ".",
		},
	],
	"settings": {
		"files.exclude": {
			"sub-fold": true,
		},
	}
}

```

**Comment by stratboy** [comment]
I think this issue is still not addressed very well. 
And guys, I think we all want just the same settings syntax that Sublime Text has.
Or, anyway, what chriszwickerocteris is suggesting on his original post.

**Comment by FedericoBiccheddu** [comment]
I did resolve the issue following dfoverdx's instructions.

My goal was to hide `source` folders in the root, but keep them in their own sub-folder because the have the same name:
```
.
├── config
├── Makefile
└── source
    ├── sub-folder-1
    │   ├── package.json
    │   ├── source
    │   └── tsconfig.json
    └── sub-folder-2
        ├── config
        ├── package.json
        ├── source
        └── tsconfig.json
```

Adding `files.exclude` in the workspace, setting is propagated to sub-folders. In my case `source` folder was hidden in both root and sub-folders. Adding it in `settings.json` resolved this issue.

**Comment by thomasoatman** [comment]
It is nice that the exclude setting was added.  But I can't figure out how to ignore only Folders.
I have too many folders (and they can get added and removed at any time) to name each of them.
Using glob wildcards though hides FILES too.
Frankly I would love a setting to not show subfolders at all.
But if there is a way to tell am Exclude entry to only match folders, that would be wonderful too.

I tried this expression hoping it would only exclude names that include a '.':
`"**/[/[,_,0-9,A-Z,a-z]*[^.]*": true,`

but it effectively hid everything.

Would also be cool to exclude 'empty' folders.  For instance, I have a subfolder 'graphics' that has jpg files.  I exclude `*.jpg`, but the graphics folder (now empty) still shows -- kindof useless....

**Comment by studgeek** [comment]
@Axelfoley85 I'm sorry, I'm not following how your example works in practice. For example given the following I still see `roota/subfold` in my vscode explorer. Thx!

```
"folders": [
		{
			"path": "../../roota"
		},
		{
			"path": "../../rootb"
		}
	],
"settings": {
        "files.exclude": {
              "../../roota/subfold": true,
       }
```

**Comment by Axelfoley85** [comment]
> @Axelfoley85 I'm sorry, I'm not following how your example works in practice. For example given the following I still see `roota/subfold` in my vscode explorer. Thx!
> 
> ```
> "folders": [
> 		{
> 			"path": "../../roota"
> 		},
> 		{
> 			"path": "../../rootb"
> 		}
> 	],
> "settings": {
>         "files.exclude": {
>               "../../roota/subfold": true,
>        }
> ```

Ok, @studgeek 

not sure but would it be a difference if you did this instead?

```
"folders": [
 		    {
 			"path": "../../roota/subfold"
 		},
		{
 			"path": "../../rootb"
 		}
 	], 
"settings": { 
"files.exclude": { 
"../../roota/subfold": true, 
}

```

**Comment by studgeek** [comment]
Thanks. I still want to view the rest of roota in the workspace though. To be honest, I'm not seeing what the value is of adding a folder to a multi-root workspace and then excluding that whole folder?

**Comment by AQuackenbos** [comment]
Found this thread while trying to solve the problem and determined the solution thanks to @f15u 's example.  To clarify further for anyone else looking, this is *not possible* using only the workspace file, but *is possible* (at least for common use-cases) via combining the workspace file with individual folder `settings.json` files.  This works due to scoping, as VSCode's settings scope operates in 3 levels (User, Workspace, Folder).

1. Build your workspace file as normal, adding all folders desired
2. In each folder that contains another root folder, create a .vscode/settings.json file, containing an entry for files.exclude that specifies the paths to hide.

*I've saved the reference below to a [gist](https://gist.github.com/AQuackenbos/80c5479aa2aa570e71b7479604e98b64) as well, for reference.*

# Example

## Use Case
You have a project or monorepo, `example`, that contains configs, build tools, etc for two distinct and separate projects, `folder-a` and `folder-b`.  Additionally, `folder-b` generates compiled data and placed it into `folder-c`, so it is useful to view that separately in the editor.

## Demonstration

The example files below produce the following output workspace from the provided input directory and config structure.

| Directory Structure | VSCode Workspace |
| --- | --- |
| <img width="187" alt="Image" src="https://github.com/user-attachments/assets/30e8f608-aa91-415f-8578-b977d1e2871d" /> | <img width="202" alt="Image" src="https://github.com/user-attachments/assets/a48ce012-abec-402a-8bb3-b0938e81d58f" /> |

### `example.code-workspace`
```json
{
  "folders": [
    {
      "path": "example",
      "name": "MonoRepo Root",
    },
    {
      "path": "example/folder-a",
      "name": "Project A",
    },
    {
      "path": "example/folder-b",
      "name": "Project B",
    },
    {
      "path": "example/folder-b/folder-c",
      "name": "B - Generated Data",
    },
  ],
  "settings": {},
}
```

### `example/.vscode/settings.json`
```json
{
  "files.exclude": {
    "folder-a": true,
    "folder-b": true
  }
}
```

### `example/folder-b/.vscode/settings.json`
```json
{
  "files.exclude": {
    "folder-c": true
  }
}
```
