### ISSUE TITLE
Rename never cancels progress

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#82146]
* have a rename provider that never finishes (e.g latest c/cpp extension)
* start rename
* close editor
* :bug: the progress stays forever...

![Oct-09-2019 10-20-44](https://user-images.githubusercontent.com/1794099/66464142-b1b94a00-ea7e-11e9-9c27-2d7f03a5f7c4.gif)

**Comment by Colengms** [comment]
FYI, the image above is showing the expected behavior.  The rename is still in progress.  The UI to the left shows confirmed references at the top, and potential references below.  The UI is used to indicate which found results you actually want to rename, if there is ambiguity.  (If there were no ambiguity, the rename would complete immediately).  The progress indicator is correctly indicating that a rename is still in progress.

The fix made to correct this issue breaks the feature.  We rely on being able to successfully complete despite cancellation being requested (as the cancellation token gets triggered merely clicking anywhere, such as in the editor or in the tree view).  With the fix to this issue, it is no longer accepting our completed edits.

If the only issue you see here is with the progress indicator itself, we could easily avoid it by completing the actual rename operation (with no results), and issuing the edits ourselves when the user completes the UI.  However, the progress indicator would actually correctly indicate that the rename operation is still in progress.

**Comment by Tyriar** [comment]
@jrieken sounds like it's breaking the C++ ext now? Need a response before verification.

**Comment by Colengms** [comment]
We have a work-around in PR, here: https://github.com/microsoft/vscode-cpptools/pull/4517

We will complete the Rename promise (with no results) as soon as the 'find reference' step is complete.  The progress indicator is displayed for that duration, but is not displayed while our rename UI is visible.  After the user has completed the rename UI, we use workspace.applyEdit() to do the actual rename.
