### ISSUE TITLE
No syntax highlighting for Unity

### ISSUE THREAD

**Issue by shaneparsons** [Microsoft/vscode#8216]
This may have to be implemented in the future, once you guys have further unity support, but basically no matter which theme I use, Unity specific variables / types / classes do not have syntax highlighting.

- VSCode Version: 1.2.1
- OS Version: OSX 10.11.5

Steps to Reproduce:

1. Open unity project with VS Code
2. Use some unity specific variables / types / classes (e.g Camera, Vector3, etc..)
3. Observe no syntax highlighting

**Comment by bgse** [comment]
This isn't limited to Unity, there is no special syntax highlighting for e.g. the System namespace either, unless I'm suffering from a misconfiguration of course.

Pretty sure that it is intended this way though, since intellisense and such work fine for Unity or otherwise here, just the highlighting is limited to primitive types, keywords, and depending on the theme method return types and such.

**Comment by bpasero** [comment]
Assuming this is about C#, please report this to https://github.com/OmniSharp/omnisharp-vscode
