### ISSUE TITLE
Source control showing nothing

### ISSUE THREAD

**Issue by alvin30595** [microsoft/vscode#82203]
source control showing nothing after the latest update (September 2019 version 1.39)

**Comment by fr43nk** [comment]
It is the same here. I maintain the clearcase scm plugin, but my SourceControlResourceGroup isn't shown in the scm viewer. There is no exception at first glance. Is there anything new to do?

**Comment by admir86** [comment]
same problem using the [TFVC](https://github.com/Microsoft/azure-repos-vscode/issues) extension

**Comment by funkhu** [comment]
Same issue with Azure Repos, blank screen. Pending changes number on source control icon is showing correctly however.

**Comment by roldeguz** [comment]
Just upgraded VSCode, I am also experiencing this issue. It correctly displays the number of files with pending changes but nothing is being displayed regardless if its tree or list view.

Running
OS: Windows_NT x64 10.0.17763
VSCode: 1.39.0
Source Control: SVN

**Comment by CoreyBlair** [comment]
Mine is showing the same thing.  It will show changes the first time but eventually it all disappears and any new files will never show.  My changelists are shown but anything outside a changelist is empty.

**Comment by joaomoreno** [comment]
Not good, sorry for the breakage everyone! A fix is coming asap.

@alvin30595 @CoreyBlair Which SCM provider are you using?

@roldeguz I can't repro this with the SVN SCM provider, seems to work for me.

I'll give TFVC a try.

**Comment by joaomoreno** [comment]
The issue here is that these SCM providers provide folders as resources, which breaks the tree rendering. Unfortunately there's no better fix but to block the tree usage from the API and only allow Git for now. I'll fix this in `master` and create a candidate PR for a recovery release asap.

Too bad this wasn't caught in our [insider release](https://code.visualstudio.com/insiders). :cry: 

Until the recovery build is released, there is no workaround but to use 1.38, here are the links:

- [Windows](https://az764295.vo.msecnd.net/stable/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/VSCode-win32-x64-1.38.1.zip)
- [Windows 32 bit](https://az764295.vo.msecnd.net/stable/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/VSCode-win32-ia32-1.38.1.zip)
- [macOS](https://az764295.vo.msecnd.net/stable/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/VSCode-darwin-stable.zip) (don't forget to disable updates, as this will auto update itself)
- [Linux](https://az764295.vo.msecnd.net/stable/b37e54c98e1a74ba89e03073e5a3761284e3ffb0/code-stable-1568209119.tar.gz)

**Comment by roldeguz** [comment]
Thanks for the update @joaomoreno 

I already downgraded to 1.38 and will be monitoring this for future announcements.

**Comment by Yanpas** [comment]
@joaomoreno Does that mean that tree view will be available for git only (in 1.39.2 or in future releases too?)? Can there be any workaround e.g. like `.` file?

**Comment by alexandrudima** [comment]
We discussed in the stand-up and we must take it.

**Comment by joaomoreno** [comment]
*Verification:*

- Install SVN and the SVN extension
- Run `svn co https://svn.apache.org/repos/asf/subversion/site/staging/docs/release-notes/` to checkout that repository
- Open the `release-notes` folder in VS Code
- Make a change

The changes should appear fine in the SCM view and there should not be a button to toggle to tree view.

**Comment by timdang** [comment]
Looks like this issue is back in Nightly be68a4e14c28cc81cdf422739af23123b3c91fd2

**Comment by roldeguz** [comment]
Upgraded to 1.39.2 and can confirm that its working for me now.

**Comment by timdang** [comment]
@joaomoreno Looks like this is broken again in the newest Insiders 5aec74ad3b55bb9463e717ec950e665288accd0f

**Comment by joaomoreno** [comment]
@timdang What do you mean? What are the steps to reproduce?

**Comment by timdang** [comment]
@joaomoreno The issue went away for a few builds after your commit (#82275), but then came back a few days later after a few updates to the insiders branch.

Source Control panel is once again blank.

Version: 1.40.0-insider
Commit: 82ca6ba87f450245f665ab7a5f3a686e2cd00045
Date: 2019-10-21T05:39:31.415Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

<img width="1680" alt="Screen Shot 2019-10-21 at 9 16 18 AM" src="https://user-images.githubusercontent.com/7561014/67223238-c03f2400-f3e3-11e9-9f18-4c9085db4953.png">

Might be specific to this particular SCM extension?
[-1571674770228.log](https://github.com/microsoft/vscode/files/3751890/-1571674770228.log)

**Comment by joaomoreno** [comment]
@timdang Yes that seems unrelated to our changes, but specific to that extension.

**Comment by ar-jan** [comment]
I updated to 1.39.2, but using a git repo I still don't see the git options when making a change (also checked 1.38.1 to see that it is working correctly there).

> Version: 1.39.2 (system setup)
> Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
> Date: 2019-10-15T15:35:18.241Z
> Electron: 4.2.10
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.17134

**Comment by timdang** [comment]
@joaomoreno No. Not the whole UI. Source Control Panel is blank again, just like it was due to this issue.

**Comment by donalffons** [comment]
Hmm, I had the same issue as shown in @timdang's image on the left - the source control panel was blank and didn't show anything. For me the fix was as simple as right clicking on the panel. This brought up a context menu, in which I could select my repository. Now it seems to be back to normal again.

Might not be a fix for everyone's problem, but could be worth a try :-).

**Comment by joaomoreno** [comment]
@timdang Can you check @donalffons suggestion?

Also can you open **exactly** the same repository in our latest stable 1.39.2? Does the issue reproduce there?

**Comment by timdang** [comment]
@joaomoreno Per @donalffons - Contextual menu only shows: 
<img width="193" alt="Screen Shot 2019-10-23 at 10 00 57 AM" src="https://user-images.githubusercontent.com/7561014/67416962-a71dab00-f57c-11e9-8d86-7f9919f9a799.png">
The rest of the Extension is working (albeit the icons are broken). The status bar menu at the bottom still links to the repo, gives me build status, links to work items.

Same repository is open in 1.39.2 stable, which works fine. As I previously mentioned, as soon as you committed the last fix, Insiders was working for me. Then, a few days later, (after some other changes I guess), Insiders is not working again.

Do you know if there was any changes to when `onDidModelChange` gets called on these types of extensions? Cause that's when the extension throws an error in the console.

**Comment by joaomoreno** [comment]
@timdang I'm having an **incredibly** hard time getting a local workspace in TFS. I have an Azure DevOps account. I have Java. I have TEE. I can't create a local workspace. How did you create yours?

**Comment by timdang** [comment]
I set up the workspace using the command line following these instructions:
https://docs.microsoft.com/en-us/visualstudio/mac/tf-version-control

**Comment by joaomoreno** [comment]
@timdang I gave up trying to reproduce this. I decided to simply read the source. The error you show in the screenshot seems unrelated to our SCM changes. It shows a real issue they have in their sources: there is no guarantee that [this](https://github.com/microsoft/azure-repos-vscode/blob/master/src/tfvc/tfvcscmprovider.ts#L143) won't be `undefined` when `onDidModelChange` fires. I've given them a PR: https://github.com/microsoft/azure-repos-vscode/issues/586

I don't think this will fix what you're seeing though...

**Comment by timdang** [comment]
@joaomoreno I appreciate all your efforts. Guess I'll try to play around with it more and see what I can figure out.

Tried your PR locally, and you're right - it doesn't fix the blank panel issue for me. Thank you so much anyway!

**Comment by zatchgordon** [comment]
@joaomoreno This article helped me out setting up TF
[https://gist.github.com/counterlogik/8191caf05ee119b93073c6dd14c0c7fa](https://gist.github.com/counterlogik/8191caf05ee119b93073c6dd14c0c7fa)

**Comment by joaomoreno** [comment]
Thanks for that link @zatchgordon. I was stuck in the correct `tf workfold` command syntax and was able to pull through thanks to that link. I can now reproduce the issue! Looking a bit more into it now.

**Comment by joaomoreno** [comment]
Moving discussion to https://github.com/microsoft/vscode/issues/83440

**Comment by jmurty** [comment]
I know this issue is closed, but I am still experiencing it with VSCode version 1.39.2 and Git repositories: the "Source Control" pane is empty with no obvious error logging in Output.

I found that I could reliably fix the problem by unsetting `"scm.alwaysShowProviders": true` or by explicitly setting it to `false`.

**Comment by jmurty** [comment]
Hi @joaomoreno I could not reproduce this in the insider release, the source control panel worked fine with or without the `scm.alwaysShowProviders` setting. Insider release details:
```
Version: 1.40.0-insider
Commit: 93ee2fc3121b7f66ddf568c051f3bfff7db8d618
Date: 2019-10-31T05:39:25.980Z
```

I double-checked version 1.39.2 to make sure I wasn't misreporting and the issue is still there, including when I reload the app with all extensions disabled. I did notice this error notification when the issue occurred in my 1.39.2 version, which I had missed previously:
<img width="461" alt="Screen Shot 2019-10-31 at 9 28 07 pm" src="https://user-images.githubusercontent.com/65604/67939588-012a0a80-fc26-11e9-949e-c3fe100e7297.png">
Clicking on the notification did nothing, but it only appeared when the SCM panel failed to load correctly.

**Comment by traed** [comment]
Just encountered this issue too. One minute it was working, the next it wasn't. `"scm.alwaysShowProviders": true` seems to work. I'm not getting any errors either.

Version: 1.40.1
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by gnbaron** [comment]
I just faced this issue as well. Toggling `scm.alwaysShowProviders` on and off again fixed the problem for me.

> Version: 1.40.1
> Commit: 8795a9889db74563ddd43eb0a897a2384129a619
> Date: 2019-11-13T16:47:44.719Z
> Electron: 6.1.2
> Chrome: 76.0.3809.146
> Node.js: 12.4.0
> V8: 7.6.303.31-electron.0
> OS: Darwin x64 19.0.0

**Comment by bradfox2** [comment]
> I just faced this issue as well. Toggling `scm.alwaysShowProviders` on and off again fixed the problem for me.
> 
> > Version: 1.40.1
> > Commit: [8795a98](https://github.com/microsoft/vscode/commit/8795a9889db74563ddd43eb0a897a2384129a619)
> > Date: 2019-11-13T16:47:44.719Z
> > Electron: 6.1.2
> > Chrome: 76.0.3809.146
> > Node.js: 12.4.0
> > V8: 7.6.303.31-electron.0
> > OS: Darwin x64 19.0.0

Thanks so much, works for me too.
