### ISSUE TITLE
Command line error - "Option 'proxy-server' is unknown. Ignoring."

### ISSUE THREAD

**Issue by astrowonk** [microsoft/vscode#82253]
- VSCode Version: 1.39.0
- OS Version: Linux RHEL 7

Steps to Reproduce:

1. Launch code with --no-proxy-server flag
2.  "Option 'proxy-server' is unknown. Ignoring." error appears.

I think the proxy is still disabled, the error message is simply wrong? If I run without the flag, I get prompted to log into the proxy, if I run with the flag, the proxy appears disabled (no log in prompting) but the error appears on the command line.

**Comment by aeschli** [comment]
I suggest to include that fix in the recovery builds to avoid any confusion due to the message printed by the cli.
The cli says `Option 'xy' is unknown. Ignoring.` for all chromium options, but in fact, they are used. My understanding is that most of the chromium options are not for the end-user except `--inspect` and the proxy settings, so I added these to the list of the valid (supported) args. @joaomoreno @bpasero Please speak up if I missed one of the options.
PR is https://github.com/microsoft/vscode/pull/82486

**Comment by alexandrudima** [comment]
This is not fixed in the latest stable release candidate.

**Comment by alexandrudima** [comment]
The discussion in yesterday's standup was to take this, so we've now merged the PR...
