### ISSUE TITLE
makefiles should always have insertSpaces:false

### ISSUE THREAD

**Issue by dimar81** [Microsoft/vscode#8227]
- VSCode Version:  1.2.1
- OS Version: Ubuntu 14.04 LTS

Steps to Reproduce:
1. Open makefile
2. Edit make file, create a new command using <tab> for indentation
3. run the make file -> will cause ":makefile:X: **\* missing separator.  Stop." error, as hard tab is not created.

**Comment by dilijev** [comment]
To add to this, I've had this problem with other editors where you would normally want to have tabs replaced by spaces but for certain formats where TAB is a specific syntactical requirement, like Makefiles, you need a way to insert the literal TAB character.

Other editors usually have some kind of "solution" to this:

Notepad++ has the ability to insert bytes for non-printable characters like TAB (x09) because Ctrl+Shift+[Letter] inserts a byte with the numerical value of the ordinal location of the [Letter] in the alphabet. So Ctrl+Shift+I = \x09 = {TAB}. I remember this particular combination via the coincidental mnemonic "I for Indent".

Vim lets you insert verbatim characters with Ctrl+V while in insert mode. (So Ctrl+V followed by the TAB key on the keyboard inserts a \x09.)

I don't feel that either of those is especially user-friendly so I'm not sure either is the right solution for VS Code.

A possibility is to have certain filetypes (Language Modes) always treat the TAB key as a literal TAB even if the user chose to insert spaces instead of tabs in general, or to have a hotkey insert a literal TAB. (Although, obvious candidates like Ctrl+T and Ctrl+Shift+T are already mapped.) Maybe Ctrl+Shift+I which is unmapped would still make sense for this.

**Comment by alexandrudima** [comment]
We don't yet support per language indentation settings. The only decent workaround is the status bar. Would that help in this case:

![image](https://cloud.githubusercontent.com/assets/5047891/16411288/9dc05722-3d26-11e6-81b1-d14467f6a1c5.png)

which is clickable and allows you to switch between inserting spaces or tabs:

You can either just change the setting (blue actions) that means from now on pressing `Tab` will do x or y etc. Or you can change the buffer too (red actions) that means convert existing indents and from now on pressing `Tab` will do x or y etc.

![image](https://cloud.githubusercontent.com/assets/5047891/16411319/cd8156aa-3d26-11e6-8bed-06e411408f66.png)

**Comment by nuest** [comment]
+1 would be great to create Makefiles in vscode in a "fool proof" manner.

**Comment by siegebell** [comment]
related issue: #10432

**Comment by bpasero** [comment]
Closing:

![image](https://cloud.githubusercontent.com/assets/900690/26462602/bfb0e832-4181-11e7-8a27-7cc90c69e489.png)
