### ISSUE TITLE
API Request: Move Tab

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#8234]
- VSCode Version: 1.3.0-Insiders
- OS Version: OSX

Per https://github.com/Microsoft/vscode/issues/6605 , we already exposed APIs to move active editors across groups. And we do support drag and drop tabs so I'm thinking can we expose tabs moving functionalities as API, then people can move tabs by commands.

This will benefit Vim extensions as moving tabs is a useful often-used command. For now only the last four commands can be implemented with existing APIs.

```
:tabs         list all tabs including their displayed windows
:tabm 0       move current tab to first
:tabm         move current tab to last
:tabm {i}     move current tab to position i+1

:tabn         go to next tab
:tabp         go to previous tab
:tabfirst     go to first tab
:tablast      go to last tab

```

@bpasero @kieferrm

**Comment by rebornix** [comment]
I'd like to leverage `workbench.action.showEditorsInGroup` for `:tabs` but seems it's still not exposed publicly yet.

**Comment by bpasero** [comment]
👍 
related: https://github.com/Microsoft/vscode/issues/8185

**Comment by bpasero** [comment]
@egamma @sandy081 I could look into this, since VIM is on the plan for July, do you think we should have it?

@jrieken any objections adding more API commands like that to our API? This command imho does not make much sense as a global command (e.g. in F1) so I would only add it as parameterized API command.

**Comment by rebornix** [comment]
@bpasero yes you are right! It's all about moving tabs within a group. I would be really happy to see this feature go with July :+1:

**Comment by jrieken** [comment]
Yeah, make sense to have that as a command tho I am not sure how you want to parameterise them. Do you have the `ViewColumn` and then `from: number` and `to: number` where the number values represent a tab?

Like `executeCommand('moveTab', ViewColumn.One, { from: 1, to: 3 })`

Problem I see is that we don't expose in what tab an editor is, only in what view column

**Comment by bpasero** [comment]
I was about to ask the same question. @rebornix would the use case be to move the active tab that has keyboard focus or any tab (active and inactive) opened anywhere?

**Comment by rebornix** [comment]
@bpasero , moving current (active) tab is enough. Besides,  Editor Group is a VS Code concept so moving active to other groups is not a Vim thing. All Vim users care about is just re-ordering tabs IMHO.

**Comment by bpasero** [comment]
Ok since this is very specific I also suggest an explicit command like:
* `executeCommand('moveActiveTab', to: <enum>)`

Where the to `<enum>` argument is `BEGINNING, END, LEFT, RIGHT.` With that we avoid the problem that we do not have API to find the current index of the tab.

@rebornix would you need a command to move 2 indexes to the left or right or is this enum enough?

**Comment by jrieken** [comment]
What would this command do when tabs aren't enabled? Should we strive for a command that handles both cases?

**Comment by sandy081** [comment]
Why not using string constants for arguments instead of enums. We cannot know what a number means while consuming in

- Extensions (If we do not expose it)
- Key bindings

The cursor commands which I am writing are string based. I think we should be consistent here either string or enums.

**Comment by bpasero** [comment]
@sandy081 @rebornix I suggest you guys add this command based on the pattern you find best suitable for VIM. It is very easy to move a tab to another index:

You can get hold of the `IEditorGroupService` in the commands accessor and call `moveEditor(input: IEditorInput, from: Position, to: Position, index?: number): void` to move a tab. 

Use `IEditorService.getActiveEditor()` (note this is another service, still some debt here to align both) to get the currently active editor. This editor can be **NULL** if there is no active one!!!

As for the arguments:
* `input`: use `activeEditor.input`
* `from`: use `activeEditor.position`
* `to`: use `activeEditor.position` to move within the same group
* `index`: see below how to compute the index and do the right thing

You can use `IEditorGroupService.getStacksModel().groupAt(activeEditor.position)` to get the `IEditorGroup` of the editor. With this interface you can find out the index of it `IEditorGroup.indexOf(activeEditor.input)` as well as find out the number of opened tabs in the group (`IEditorGroup.count`).

The place where we add and document API commands is: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostApiCommands.ts#L212

**Comment by bpasero** [comment]
If tabs are disabled, maybe you should actually move the editor between the groups? The API allows this easily and in order to find out that tabs are enabled or disabled, you could just go to the configuration service:

`const useTabs = configuration.workbench.editor.showTabs`

**Comment by rebornix** [comment]
@bpasero didn't notice you asked me a quesiton about this feature. Moving tabs by specifying the index instead of `<enum>` is easier for implementing Vim commands:

```
:tabm 0       move current tab to first   -> executeCommand('moveActiveTab', to: 1)
:tabm         move current tab to last     -> executeCommand('moveActiveTab', to: 999)
:tabm {i}     move current tab to position i+1  ->  executeCommand('moveActiveTab', to: i+1 )
```

It's also easy to implement this command as we just need to pass the index to `moveEditor(input: IEditorInput, from: Position, to: Position, index?: number): void`. 

When the Tab feature is disabled, we can use `to` index to decide which editor group that the tab should be moved to.

Sould good to you all?

**Comment by sandy081** [comment]
@rebornix Implemented `activeEditorMove` command, following is the documentation:

Usage:
- Command Id: `activeEditorMove`
- Arguments: `{to: $Position, by: $By, amount: number}`

**Position**
- `first`
- `last`
- `left`
- `right`
- `center`
- `position`

**By**
- `tab`
- `group`

Default: If tabs are enabled `tab` otherwise `group`

In Tabs mode:
- `first`: Moves to first position in the current group
- `last`: Moves to last position in the current group
- `left`: Moves to left by given amount in the current group. Default is 1.
- `right`: Moves to right by given amount in the current group. Default is 1.
- `center`: Moves to center of the group.
- `position`: Moves to the `amount` position in the current group. Default is 1. **Note**: value is Zero index based.

In Groups mode:
- `left` | `first`: Moves to Left group
- `right` | `last` | : Moves to Right group
- `center`: Moves to center group
- `position`: Moves to the `amount` group. Default position is 1. 

0: Left, 1:Center, 2:Right

Vim Usage for moving current active editor to:

```
:tabm 0     first               ->  executeCommand('activeEditorMove', to: 'first')
:tabm        last               ->  executeCommand('activeEditorMove', to: 'last')
:tabm {i}   position i+1  ->executeCommand('activeEditorMove', to: 'position' amount: i)
```

**Comment by sandy081** [comment]
@rebornix Please note following changes to the API to make it neat and consistent with existing 

- Renamed the command name to `moveActiveEditor`
- Renamed the argument property from `amount` to `value`
- Positions are made `1` based. First position is 1 and so on...

**Comment by rebornix** [comment]
@sandy081 thanks, I've updated with the new signature. They worked.
