### ISSUE TITLE
Bug in version 1.39: vscode reports "no debug adapter found" when click "start without debugging"

### ISSUE THREAD

**Issue by 520Chris** [microsoft/vscode#82354]
- VSCode Version: Latest
- OS Version: win10

Steps to Reproduce:

1. Create a python file
```
print("hello")
```
2. Click "Start without debugging".

3. Then vscode reports "no debug adapter found"
![image](https://user-images.githubusercontent.com/39628662/66650829-1da8d780-ec64-11e9-8623-9f1ef8308fe5.png)

Does this issue occur when all extensions are disabled?: Yes/No
No

This is the log:
```
[2019-10-11 20:21:21.113] [renderer1] [error] no debug adapter found: Error: no debug adapter found
    at t.RawDebugSession.handleErrorResponse (file:///C:/Users/zjli1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2751:326)
    at Promise.then.e (file:///C:/Users/zjli1/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2750:738)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by 520Chris** [comment]
I have downgrade vscode to 1.38, and the error disappears.

**Comment by isidorn** [comment]
Please file this against the python extension https://github.com/microsoft/vscode-python

**Comment by 520Chris** [comment]
@isidorn  Thanks for your response.
1. After downgrade vscode to 1.38, the error has gone.
2. The output panel of the python extension has no error information.
3. the log I posted above has not mentioned python extension

So I think the issue is more likely related to the vscode itself.

**Comment by ivankravets** [comment]
@isidorn Why did you close this issue? VSCode 1.39 broke a lot of 3rd party debug extension. We have the same problem with PlatformIO IDE Debugger. I tried to resolve this issue and don't have idea what VSCode wants from me. 

```
notificationsAlerts.ts:38 Error: no debug adapter found
    at t.RawDebugSession.handleErrorResponse (rawDebugSession.ts:693)
    at Promise.then.e (rawDebugSession.ts:665)
```

Everything works great with VSCode <1.39

**Comment by isidorn** [comment]
You are correct, this is an issue on the vscode side. And I can not repro with Node, but only with Python.
Problem being the start without debugging usually finishes fast and the debug adapter goes down before we can send the `configurationDone` request. When we try to send the `configuratinoDone` request the adapter is already down thus the error message.
Since this is only an error shown, and the start without debugging still works this is not a candidate, and we will ship the fix only to the insiders, not to the recovery release. The stable release will have the fix in one month.

Please use vscode insiders if you would like us to catch breakaeges like this earlier. Thanks

fyi @DonJayamanne

**Comment by ivankravets** [comment]
@isidorn thanks for the fast fix!

> Please use vscode insiders if you would like us to catch breakaeges like this earlier. 

Yes, I know :( This is the 3rd time when something is broken with a new release. We need to add some reminders to test our base functionality with each new release.

**Comment by 520Chris** [comment]
@isidorn Thanks for the fix!!!

**Comment by weinand** [comment]
no error reported when using "start without debugging" for a Python program.
