### ISSUE TITLE
Failed to open V8 file \natives_blob.bin

### ISSUE THREAD

**Issue by cgmerida** [microsoft/vscode#82382]
I got an error while trying to launch vscode, and when I tried launching it from the terminal I got the next:

$ code -v
[1011/111946.687:FATAL:v8_initializer.cc(185)] Failed to open V8 file 'C:\Program Files\Microsoft VS Code\natives_blob.bin' (reason: -4)

- VSCode Version: 1.38.1
- OS Version: Windows 10

Steps to Reproduce:

1. open the terminal
2. run code --verbose

**Comment by deepak1556** [comment]
That error means the file is not found. @cgmerida can you paste a screenshot of the folder that has VSCode executable `C:\Program Files\Microsoft VS Code`.

**Comment by cgmerida** [comment]
Here is a screenshot of the folder.

![vscode folder](https://user-images.githubusercontent.com/25395641/66693346-42ea1580-ec65-11e9-9f26-e552ffe3dc7a.jpg)

**Comment by deepak1556** [comment]
@cgmerida thanks for the screenshot, it looks like some of the files are missing from the installation, not sure why that would happen, can you remove this folder and reinstall latest stable from here https://code.visualstudio.com/ ?

**Comment by cgmerida** [comment]
I copied the content of the folder named "_" inside the root folder C:\Program Files\Microsoft VS Code and it is working now.

This is the content of the folder "_"
![folder _](https://user-images.githubusercontent.com/25395641/66709010-733ebc00-ed18-11e9-93de-09c6830f693a.JPG)

And this is now my folder C:\Program Files\Microsoft VS Code\
![vscode folder now](https://user-images.githubusercontent.com/25395641/66709016-82256e80-ed18-11e9-83ab-ed0630c59b97.JPG)

now when I type code -v I get
![vscode version](https://user-images.githubusercontent.com/25395641/66709019-90738a80-ed18-11e9-8172-cf920ba6d268.JPG)

**Comment by 4wrxb** [comment]
I just encountered the mysterious "_" folder creation as well. Some details are blow, but I don't really know if this can properly be declared an "issue" for vscode or if it should be reopened. A cursory search didn't turn up any known issues for auto-updating during a windows shutdown.

1) This is caused by an incomplete update install.
1) I was able to fix this by re-running the user installer (without an uninstall) since the corrupt was simply missing files.
1) This correlates to a shut-down of my PC as I know I left work around this time, but I can't remember if I had closed vscode before initiating the shutdown (and thus when the botched update actually began).

There are no errors in the log, it simply ends before the final steps are completed (see below or attached logs).

[BAD-vscode-inno-updater-1571191966.log](https://github.com/microsoft/vscode/files/3745417/BAD-vscode-inno-updater-1571191966.log)
[LastGood-vscode-inno-updater-1570829377.log](https://github.com/microsoft/vscode/files/3745418/LastGood-vscode-inno-updater-1570829377.log)

Bad log ends here:
```log
Oct 15 19:12:52.807 INFO Rename: "locales" (attempt 1)
```

Good log only has a few more lines:
```log
Oct 11 14:29:41.409 INFO Rename: "locales" (attempt 1)
Oct 11 14:29:41.409 INFO Rename: "natives_blob.bin" (attempt 1)
Oct 11 14:29:41.411 INFO Rename: "osmesa.dll" (attempt 1)
Oct 11 14:29:41.412 INFO Rename: "resources" (attempt 1)
Oct 11 14:29:41.416 INFO Rename: "resources.pak" (attempt 1)
Oct 11 14:29:41.417 INFO Rename: "snapshot_blob.bin" (attempt 1)
Oct 11 14:29:41.418 INFO Rename: "swiftshader" (attempt 1)
Oct 11 14:29:41.420 INFO Rename: "v8_context_snapshot.bin" (attempt 1)
Oct 11 14:29:41.421 INFO Delete: "C:\\Users\\$env::UserName\\AppData\\Local\\Programs\\Microsoft VS Code\\_"
Oct 11 14:29:41.472 INFO header: Header, id: Inno Setup Uninstall Log (b) 64-bit, app id: {771FD6B0-FA20-440A-A002-3B3BAC16DC50}, app name: Visual Studio Code, version: 1048, num recs: 38441, end offset: 9019019, flags: 0x34, crc: 0xae323e1
Oct 11 14:29:41.473 INFO num_recs: 38441
Oct 11 14:29:41.561 INFO Updating uninstall file "C:\\Users\\$env::UserName\\AppData\\Local\\Programs\\Microsoft VS Code\\unins000.dat"
Oct 11 14:29:41.663 INFO Update was successful!
```
