### ISSUE TITLE
Markdown: open preview to the side should be Ctrl/Cmd click, not Alt

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8255]
Refs: https://github.com/Microsoft/vscode/issues/7945

At least that would be consistent with other places where we open to the side and matches old behaviour.

**Comment by jrieken** [comment]
Yeah, I don't like ctrl/cmd but I take the consistency point...

**Comment by jrieken** [comment]
Actually, I take that back ;-) The <kbd>Alt</kbd> modifier is a menu item modifier and not an argument to the command. Since, it's the _alternative_ action for a menu item I think the _alt_-key is a good choice. In that respect it also different ctrl/cmd click on tree items which we lend from hyperlinks in browsers. The point of _Alt_ is to show an alternative less common version of a menu. 

@bgashler1 I know you wanted to join in this discussion. Please go ahead ;-)

**Comment by jrieken** [comment]
Also, while we only honour `Cmd/Ctrl` at the time of the click, `Alt` is being honoured while being over the menu item.

**Comment by bpasero** [comment]
Fyi, using Cmd/Ctrl in trees is also not a good idea because when multi select is on, Cmd/Ctrl is reserved for multi select.

So, having Alt everywhere is maybe a good idea, but will break existing assumptions.

**Comment by bgashler1** [comment]
Thanks for including me in.  I think this would be good to discuss in UX meeting.  I personally don't think it's very discoverable to use an <kbd>Alt</kbd> key to change a command.  It's not a bad idea by any means, but I think it's unlikely many people will ever know about it.

**Comment by bpasero** [comment]
I do think it is common for Mac users but not for Linux/Windows users.

**Comment by jrieken** [comment]
After the discussion I opt to leave this with <kbd>Alt</kbd>

**Comment by jrieken** [comment]
let's leave it by alt
