### ISSUE TITLE
Web: Webview scroll sync not smooth enough

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#82591]
Linux, chrome

Open a markdown file and a preview to the side
Scroll in markdown -> notice the scroll sync in the webview preview is not smooth
I would expect the same experience as with vscode stable where the scroll sync is much smoother and I never encounter a lag.

**Comment by mjbvz** [comment]
I looked into this and don't see a huge latency. There will be at least some latency because we need to communicate from the client back to the workspace extension host for this case. The only way we could improve that would be to split markdown into a workspace and a UI extension, but the issue does not seem severe enough for that
