### ISSUE TITLE
Web: Zen mode and refresh is stuck in centered layout

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#82597]
- Toggle Zen mode
- Reload window
- You are out of Zen mode, but the editor is still in centered layout. I'd expect myself to be either 1) completely out of Zen mode without centered layout 2) completely in Zen mode with centered layout

![image](https://user-images.githubusercontent.com/4033249/62164844-ffbd0f00-b2d1-11e9-93ea-540be12690b6.png)

@isidorn reply:

> The issue is that zenMode is potentially toggling zen mode on onWillSaveState to cleanse the state here
> 
> This is an ugly approach which does not work in the web

**Comment by isidorn** [comment]
I actually have no better idea when should I clean the zen mode state.
@bpasero is there a better time to do this in the web? Currently I listen to `onWillSaveState`

An ideal option is that zen mode just stores that it is active in memory and next time we start eveyrthing is clean. However zen mode is piggy backing on a lot of other features which need to be cleaned since they are stored across reloads (for example activity bar gets hidden)

Thus zen mode has to do something on shutdown.

Alterantive woudl be to change the whole zen mode implementation.

**Comment by bpasero** [comment]
@isidorn you will have to find a solution that does not require any long running operations on reload or shutdown, there is no way in the web to support this currently. If you must persist state on shutdown, `window.localStorage` is an option. I think it is fine to be used if we do not store too much in it. I use it already in another case for other reasons.

**Comment by BearPro** [comment]
I have the same issue **on a stable standalone version** after my laptop with windows been hibernated due to this battery run down.

Version: 1.42.1 (system setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by SpicyPete** [comment]
it's out of scope, but how do I get VS Code to not be stuck centered again?
