### ISSUE TITLE
Create gulp tasks to compile/watch changed sources using gulp-changed

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode#82632]
The current compile/watch tasks remove the entire `out` directory and recompile all the sources, which is a waste of time and resources.
There should be gulp tasks that compile only the TypeScript files that have changed.
There should also be a matching watch task.

We can use the `gulp-changed` plugin to filter the source files that don't need recompiling:
https://www.npmjs.com/package/gulp-changed

**Comment by jrieken** [comment]
Yeah, that the design. We don't check-in or keep the `out` folder but pay the initial cost for compiling fresh. Since we have a custom compile logic (which is free of flaws) we have this safe guard that we can get to a clean state once in a while

**Comment by NotWearingPants** [comment]
Once the `watch` task compiles fresh, it watches for changes and compiles only the difference.

If I start the `watch` task, wait for it to finish compiling, and then accidentally Ctrl+C, I can't run it again to watch for changes without it recompiling again.

You are wrong that this is by-design, as this is already happening just without being able to restore it if I accidentally quit the task.

Please reopen this issue.

I am willing to submit a PR for this.

**Comment by jrieken** [comment]
Please don't accidentally press Ctrl+C... I think that's a weak argument. How about accidentally deleting the out-folder. What then? We compile with [`gulp-tsb`](https://github.com/jrieken/gulp-tsb) which is a plugin to gulp and which support incremental compilation. It needs the full init phase because it keeps declaration files in memory in order to seed up compilation. This is a highly optimised workflow which enables us to have fast incremental compilation - at the cost of high startup costs which are willing to pay.
