### ISSUE TITLE
Splitting an editor too many times can cause first editor's contents to become hidden

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#82653]
Issue Type: <b>Bug</b>

**Repo**
1. Open a text editor on the left and a blank editor on the right of the workbench
1. Repeatedly split the blank editor

**Bug**
At a certain point, the first editor (the text editor) gets shifted to the left and becomes hidden.

![Oct-15-2019 22-09-29](https://user-images.githubusercontent.com/12821956/66889776-8069de00-ef98-11e9-9d8b-ca43d694122a.gif)

This causes problems for webviews as we attempt to lay the webview element over the oddly positioned editor, causing a big visual glitch where the webview is drawn on top of the other workbench elements (we have to absolutely position the webview on the page in order to make sure it does not get reparented)

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_17039423|
|Screen Reader|no|
|VM|18%|
</details>

**Comment by sbatten** [comment]
@joaomoreno recent opinion was that the parts are responsible for keeping inside their bounds?

**Comment by joaomoreno** [comment]
@sbatten Correct!

**Comment by sbatten** [comment]
@bpasero @mjbvz we should discuss how the editor part can handle this itself better. I've been thinking about various ideas to improve editor splitting problems and haven't found anything that I really like.

Ideas include:
* Having the editor part merge editor groups in limited space temporarily
* Having the editor part prevent creation of new groups when space is unavailable
* Having the editor part snap away editor groups that can't be displayed right now

**Comment by bpasero** [comment]
@sbatten @joaomoreno I think this is not as easy to fix because you can start with a large window, split many times, then reduce window size and you would still hit this issue right?

I kind of like the idea to prevent splitting when space is not enough, if the grid widget can give me this information as a method I would be happy to adopt it. Still, it would not solve the issue for when the user makes the window smaller.

I do not like the idea of automatically merging groups on smaller window size, unless we could undo this once the window gets larger (which is tricky I guess).

Could the grid widget at least not get into a broken state? E.g. if the grid hits its size constraints, grid elements become hidden automatically?

**Comment by joaomoreno** [comment]
The grid does not get into a broken state. It just doesn't have an overflow scrollbar. The broken state happens because views need `overflow: hidden;` and we can't do it for all of them because of the menus. Now I'm actually considering doing them and just making an exception for the menubar view. cc @sbatten

**Comment by mjbvz** [comment]
For webviews specifically, no matter how we handle this casr I believe I‘ll need a way to get the visible editor‘s size. If the editor is somehow pushed off the screen, then this would be zero

**Comment by sbatten** [comment]
@joaomoreno special casing the menubar is a possible solution to the more generic issue and I'm not opposed but as @mjbvz suggests, this doesn't actually solve the problem for webviews.

The editor itself knows its bounds from the layout call. It should provide some mechanism for overflow and can provide api for @mjbvz to get visibility information. If the editor propagates the layout information down, all of this can be self-contained IMO.

**Comment by bpasero** [comment]
@joaomoreno didn't you fix this with your new overflow behaviour? I see a scrollbar appearing now.

**Comment by joaomoreno** [comment]
Boom
