### ISSUE TITLE
Debug Console duplication

### ISSUE THREAD

**Issue by vigneshshankar96** [microsoft/vscode#82662]
When I press 'Start Debugging' for a Python script it opens a new Python Debug Console terminal. This is expected. But when I press the restart button for the same Python script, it opens a new Python Debug Console terminal occasionally. The previous console is not closed and populates the terminal drop-down. I have not tried the same with other languages.

![image](https://user-images.githubusercontent.com/50376081/66896707-01fe5200-f013-11e9-9713-3e323ee352ff.png)

**Comment by isidorn** [comment]
I believe this is being done from the python extension by sending a `runInTerminal` request which is handled [here](https://github.com/Microsoft/vscode/blob/3fc780dc7caf63ffd23ed1664cdfe17029f2d28d/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L549) which at the end gets [here](https://github.com/Microsoft/vscode/blob/3fc780dc7caf63ffd23ed1664cdfe17029f2d28d/src/vs/workbench/api/node/extHostDebugService.ts#L332)
Assigning back to @weinand since he introduced that and might be better to check if we can reuse temrinals there. Feel free to assign back so I can investigate more.

**Comment by weinand** [comment]
Oh I see, the Python extension calls the Integrated Terminal "Python Debug Console" which is misleading.

**Comment by weinand** [comment]
@vigneshshankar96 VS Code tries to reuse an existing Integrated Terminal for a new debug session if nothing is running in that existing Integrated Terminal.
If something is running in the existing Integrated Terminal (e.g. the last debug target), VS Code creates a new session.

Could this explain the behavior you are seeing?

**Comment by int19h** [comment]
"Python Debug Console" is by analogy with Node, which uses "Node Debug Console" for integrated terminal.

Could it be that restart is asynchronous to such an extent that the program in the previous session has not exited before a new session is started, and the terminal is considered "in use"?

**Comment by maxgubler** [comment]
I've noticed this behavior on Windows [using git bash](https://code.visualstudio.com/docs/editor/integrated-terminal#_windows) as the integrated terminal, but attributed it to lack of support for git bash. What OS / terminal is this @vigneshshankar96 ?

**Comment by vigneshshankar96** [comment]
@weinand Not exactly
@maxgubler I am using Windows 10, with a Conda environment.

Here are the steps I followed to replicate the problem.

1. I am currently running a debug session on third terminal tab [**3: Python Debug Console**]
![image](https://user-images.githubusercontent.com/50376081/67070439-ac09e580-f19d-11e9-931c-154a1c9c36bf.png)

2. I click on Restart for the debug session. A new terminal is opened [**4: Python Debug Console**], and a new debug session is started
![image](https://user-images.githubusercontent.com/50376081/67070667-4cf8a080-f19e-11e9-9511-1865ddb8972d.png)

3. The previous debug session's terminal tab [**3: Python Debug Console**] is still open with the session closed as expected, but why did it open the new [**4: Python Debug Console**] terminal in the first place
![image](https://user-images.githubusercontent.com/50376081/67070870-cee8c980-f19e-11e9-9558-bb7986eac769.png)

**Comment by narfanar** [comment]
Happens consistently when default is Git Bash. And about once every 20 times when default is Powershell 5.1.

**Comment by kishankarun** [comment]
> Happens consistently when default is Git Bash. And about once every 20 times when default is Powershell 5.1.

I too face this problem with Git Bash

**Comment by iand66** [comment]
Ditto. Worked just fine prior to 1.49.3. Green 'arrow' (top right) still seems to work OK. Had more hangs today than last year combined

**Comment by connor4312** [comment]
This can still happen if the debug adapter acknowledges the restart or terminate before the process is completely shut down, about which there's little we can do -- at the point in time at which we get a `runInTerminal` request, we want to check that there's no running process in the terminal when deciding when to create a new one.

But as of https://github.com/microsoft/vscode/commit/591039e34c44fd4bfd2807c589ea10933d2feb3e we will keep track of the terminals, so even if this happens you'll get at most two terminals (since next restart the process will presumably have finished shutting down and we'll be able to reuse it.)

**Comment by codeinflash** [comment]
This is A thing that must be fixed. I can do CTL+P and then Reload Window to kill all previous terminal sessions but it's pain in the ass.

**Comment by roblourens** [comment]
I see this

![image](https://user-images.githubusercontent.com/323878/101414944-de900980-389b-11eb-9417-b590e06eede8.png)

```json
{
	"name": "Python: Current File",
	"type": "python",
	"request": "launch",
	"program": "${file}",
	"console": "integratedTerminal"
}
```

**Comment by connor4312** [comment]
@roblourens what did you use to get into that state?

**Comment by roblourens** [comment]
Just the above launch config and this file


```py
print("hi")
```

**Comment by connor4312** [comment]
Screenshared, it doesn't look like the same issue. Will create a new one, for that, and close this issue so someone else can verify it.

**Comment by aeschli** [comment]
I'm not seeing duplicate `Python Debug Console` Terminals when running a Python files multiple times.
Marking as verified.
