### ISSUE TITLE
javascript.suggest.names still working in object literal when disabled

### ISSUE THREAD

**Issue by iar5** [microsoft/vscode#82716]
- VSCode Version: Version: 1.39.1
- OS Version: MacOS 10.15

Steps to Reproduce:

1. "javascript.suggest.names": false (abc suggestion)
1. declare object literal e.g. var foo = {  }
2. when you type something inside the brackets the abc suggestion is still working

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
You are likely seeing VS Code's default word based suggestions. Set `"editor.wordBasedSuggestions": false` to disable these

These are separate settings because their functionality is somewhat different:

- Word based suggestions only show up when JS provides no suggestions. They contain all the words in the current document.
- Suggest names is provided by JS when we know you are somewhere where an identifier could be used. It should only contain symbol names from the current document
