### ISSUE TITLE
Maximize-Minimize-Show Terminal does not show terminal maximized 

### ISSUE THREAD

**Issue by lambainsaan** [microsoft/vscode#82722]
Issue Type: <b>Feature Request</b>

After maximizing the terminal, if I hide the terminal(`ctrl + j`), and then I spawn the terminal once again(``ctrl + ` ``), the terminal is not in maximized mode, but rather the previous un-maximized size. Which is not really user-friendly, IMHO it should maintain the previous size, set by the user, in this case, the maximized state.

I would like to take up the issue if the feature request is approved. :smile: 

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 5.0.0-31-generic

**Comment by sbatten** [comment]
@lambainsaan thanks for the feedback. the behavior you are seeing is intended and your request was under consideration when I added the "fully maximizable" panel. However, since the majority of work in VS Code centers around the editor, I felt the user should explicitly bring the panel back maximized by default.

To get the behavior you desire: when the the panel is hidden and you want it to come back maximized, you can simply run the command: `F1` >  `Toggle Maximized Panel`. You could map this to a keybinding with a when clause to make this more useful to you as well.
