### ISSUE TITLE
VS Code fonts don't seem to be using system antialiasing on Windows

### ISSUE THREAD

**Issue by tgani-msft** [microsoft/vscode#82733]
Issue Type: <b>Bug</b>

The same font used in VS Code renders fuzzier than in VS. It looks like system anti-aliasing is not being used on Windows.

I have JPG's from screenshots to share which I can add later.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.76GB (4.75GB free)|
|Process Argv|firstsets.cpp|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.39.9
cpptools|ms-|0.26.0
perl|ric|0.9.0

</details>

**Comment by tgani-msft** [comment]
@roblourens, I'm on the same floor as you if you want to take a look in person.

**Comment by roblourens** [comment]
Screenshots might help for @deepak1556 to identify it. Also you can compare it to text you see in Chrome.

**Comment by tgani-msft** [comment]
![vs-text](https://user-images.githubusercontent.com/45886079/67234478-17e88a00-f3fa-11e9-9cfc-405d72fce353.JPG)
![vs-code-text](https://user-images.githubusercontent.com/45886079/67234479-17e88a00-f3fa-11e9-99d0-ddbcf6fa4fc1.JPG)

Open the above files in mspaint and enlarge to 300% to see the difference.

**Comment by tgani-msft** [comment]
The first one is for VS. It's interesting to note that if font scaling is used in VS, it resembles VS Code exactly.

**Comment by roblourens** [comment]
To me, it sort of looks like a different font. But even if it's the same, the font rendering will always be slightly different. It should be the same as what you see in Chrome. From the screenshot, I can't tell whether it's wrong.

**Comment by varunj166** [comment]
@deepak1556 Instructed from #84154 to add information here. I had opened a separate issue #84214 because I hadn't seen any Windows users reporting what I was seeing, but #84154 tells me I'm not alone:

Version: 1.40.0
OS: Windows 7 64 bit

There has been a very clear loss of editor text sharpness from 1.39.2 to 1.40.0. Downgrading back to 1.39.2 solves the issue. A gentleman on #84214 tells me this is because VS Code switched from RGB subpixel antialiasing to grayscale subpixel antialiasing, perhaps because of Electron 6.

Whatever the reason, it made looking at the editor window very unpleasant, forcing me to downgrade to 1.39.2 until (if) the issue is fixed.

Screenshots:

1.39.2
![vs-code-1 39 2](https://user-images.githubusercontent.com/42119852/68470658-7f6c4b00-01ea-11ea-8094-b3c5c76eecde.png)

1.40
![vs-code-1 40 0](https://user-images.githubusercontent.com/42119852/68470667-84c99580-01ea-11ea-8395-e07d1bb8e07b.png)

**Comment by bhughes339** [comment]
I was instructed to leave a comment here. I'm having this issue on Windows 10, starting with v1.40.

![video](https://user-images.githubusercontent.com/16418739/68427693-ab4ee880-0178-11ea-9043-ab1b4f2e43f3.gif)
