### ISSUE TITLE
Replace the terminal with alacritty?

### ISSUE THREAD

**Issue by mkpankov** [microsoft/vscode#82763]
Hey,

I regularly notice how slow the built-in terminal on Linux is. It's output throughput is much lower than native terminal, and sometimes it even has noticeable latency of 200+ ms on input.

When using native [alacritty](https://github.com/jwilm/alacritty/) and then coming back to built-in terminal it's such a far cry in performance, it almost justifies the ergonomic hit of switching back-and-forth between VS Code and terminal windows.

So, the suggestion is, wouldn't it be cool to embed alacritty instead of current terminal? It's fast and super smooth, it's small, it doesn't support superficial features like tabs, it's the only terminal with hardware accelerated rendering, and it supports all the major platforms.

**Comment by Tyriar** [comment]
@mkpankov vscode's terminal is built on web tech just like the rest of vscode and it will remain that way.

The terminal's performance is actually really awesome with the webgl renderer which does very similar stuff and has similar perf to alacritty, I haven't had any time recently to stabilize it though https://github.com/xtermjs/xterm.js/issues/2033

You can also look at https://github.com/microsoft/vscode/wiki/Terminal-Issues#rendering-problems to see if you can overcome your latency problems, chances are since you're on Linux that for your hardware, drawImage in Chromium is taking abnormally long.
