### ISSUE TITLE
Change Editor background based on Language

### ISSUE THREAD

**Issue by AlexFiliakov** [microsoft/vscode#82773]
I'm using a dark VSCode Theme and I really like the new Python capability to work natively with Jupyter Notebooks.

Unfortunately, the default Notebook theme is a light background, and default matplotlib theme is dark text on transparent background. Same thing for Pandas tables. This means my VSCode renders many diagram labels and table data as dark-on-dark and impossible to read.

Would it be possible to support something like this:

```
    "workbench.colorCustomizations": {
        "[Material Theme Darker]": {
            "[jupyter]": {
                "editor.background": "#f1f1f1"
            }
        }
    }
```

I realize the usual counter-argument to supporting language-specific **workbench.colorCustomizations** goes something like "workbench themes more than the editor, so what if you have two languages open side-by-side?", but it would be very useful to at least support **language-specific editor theming**

The Extension "Theme by language" currently doesn't support defining a custom theme for Notebook Preview since it doesn't have an associated language.

Here is how most of my Jupyter Notebooks render now:
![](https://i.imgur.com/tRlsbiY.png)

**Comment by AlexFiliakov** [comment]
I realize the usual counter-argument to supporting language-specific **workbench.colorCustomizations** goes something like "workbench themes more than the editor, so what if you have two languages open side-by-side?", but it would be very useful to at least support **language-specific editor theming**

**Comment by AlexFiliakov** [comment]
May be duplicate of: https://github.com/microsoft/vscode/issues/54507

May be resolved by this proposal: https://github.com/microsoft/vscode/pull/82781

**Comment by aeschli** [comment]
The request to have language specific colors is #20652. It's not likely to happen due to the issue you mentioned above (theme also defined workspace colors) and the way our theming is implemented

However, for your example, I think this needs to be fixed in the Jupiter extension.

The Jupiter extension should
- make sure that tables and graphs use colors that go well with the current theme
- define a separate color for Jupiter notebooks so users can change the notebook background color 

Can you file an issue against the extension that you use?
