### ISSUE TITLE
Unified debug console does not have a control to select a session for evaluation

### ISSUE THREAD

**Issue by dgozman** [microsoft/vscode#82784]
When using unified console between multiple debug sessions via `vscode.debug.startDebugging` option, console is merged and there is no way to select a session for evaluation in the console itself. Clicking in the call stack pane works fine for that. This is sometimes annoying to use.

Perhaps, there could be a way to select "where to evaluate" closer to the repl prompt. If VSCode will support multiple global objects (see microsoft/debug-adapter-protocol#57), we can easily combine the two - select session and a global object (belonging to that session) in a single drop down, which affects evaluations and completions.

**Comment by isidorn** [comment]
Agree that there is currently a limitation regarding this.
And yeah selecting where to evaluate shuold be closer to the repl input since it is in that context. However this would require us to introduce new UI. Thus for now I will assign this to the backlog since we should tackle, however it is a corner case I believe and there should be no rush here.
