### ISSUE TITLE
Do not show me a file if there are no results

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8278]
#8184

Steps to Reproduce:

1.  Search / replace for a something
2. Replace all inside a file
3. Notice we still show that file with 'no matches'. I would expect that file is no longer in the list

![screen shot 2016-06-28 at 11 36 40](https://cloud.githubusercontent.com/assets/1926584/16410830/9bbf1186-3d24-11e6-904f-b35abb04987d.png)

**Comment by sandy081** [comment]
@bpasero @isidorn 

Following are the reasons, I want to retain the empty file
- It is consistent with Search results - When a file entry is modified to not have search results
- During replace, if user undo then file with results should be shown back. If we remove the entry then this will not happen.

**Comment by bpasero** [comment]
Maybe change the wording if you are in replace mode so that it is more obvious?

**Comment by sandy081** [comment]
I am thinking of removing this `no matches` in both Search and Replace and introducing following behavior

In Search results, 
- Editing a file so that it does not have any search results, will remove the file
- Doing an undo will put it back in the results

In Replace results
- Replacing all entries in a file (one by one or using replace all on a file) removes the file
- Doing an undo will put it back in the results

Removing
- File entry will not be added back if removed explicitly (Current behavior)

**Comment by bpasero** [comment]
I like that 👍

**Comment by isidorn** [comment]
Sounds good - would like to try it out before giving more feedback

**Comment by sandy081** [comment]
Pushed the changes, Feedback is welcome. Thanks.
