### ISSUE TITLE
javascript and javascriptreact are the same language

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode#82793]
I assumed this issue was spotted before, but I couldn't find any issues regarding this.

1. Open a new file
2. Set the language to `javascript` (**not** `javascriptreact`)
3. Type:

```jsx
const x = <div></div>;
```

There is no syntax error, even though I selected JavaScript *without* React.

Looking at the source code of vscode, the syntax of these 2 languages is identical - [link to the code that generates the language file](https://github.com/microsoft/vscode/blob/ac719087ef99fe95ed1555da517b040a7e83e3d5/extensions/typescript-basics/build/update-grammars.js#L63-L64).
You can see that the resulting `javascript` language file [admits it supports React](https://github.com/microsoft/vscode/blob/ac719087ef99fe95ed1555da517b040a7e83e3d5/extensions/javascript/syntaxes/JavaScript.tmLanguage.json#L8).

I understand that many React JSX projects use the `.js` file extensions when they should be using `.jsx`, so it might be desirable for the JS language to support JSX.
But then why does the second language exist (`javascriptreact`) if it is *identical*?

I suggest making `javascript` not support React. This will force existing React devs who are using VSCode to configure their file association of `.js` to `javascriptreact`, and regular JS devs know when they have a syntax error in their code before they run it.

---

- VSCode Version: 1.39.2
- OS Version: Windows 10
- Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
This is intentional. React previously encouraged using the `jsx` but now many developers use just plain `js` files for react components, so we just always have react support enabled. Removing react support from normal `js` files and requiring developers to specify a file associations would cause a lot of pain with no real benefit

We still have the javascriptreact mode:

- For historical reasons and to match the `typescript`/`typescriptreact` language setup
- For advanced use cases, users can enable different settings for `javascript` and `javascriptreact` (such as emmet)
- Extensions may want to target `javascriptreact` specifically in some cases
