### ISSUE TITLE
Uncentered SCM sync icon rotation in status bar

### ISSUE THREAD

**Issue by letmaik** [microsoft/vscode#82827]
It's hard to capture this in an image but I find that when the SCM sync icon rotates then the rotation is not around the center point and it kind of looks off.

![image](https://user-images.githubusercontent.com/530988/67082757-b58d5080-f191-11e9-834e-b838c409c089.png)

**Comment by misolori** [comment]
We actually improved this in #75446 and you can see the icon is actually centered and evenly round: 

![image](https://user-images.githubusercontent.com/35271042/71689545-20910100-2d57-11ea-87f6-b59b015a4d2c.png)

But due to the nature of the icon and the font-size we use in the status bar being smaller than the default (14px instead of 16px) there isn't much else we can do here. Will close this as as-designed.
