### ISSUE TITLE
Faulty popup help for comma inside a string in an array

### ISSUE THREAD

**Issue by MrAndersen1** [microsoft/vscode#82825]
Issue Type: <b>Bug</b>

Step 1:

```ts
const test: string[] = [];
test.concat([""]);
```

Step 2:

add ", " (comma + space) inside the string to get the popup about array elements (that you should get when pressing comma after the string) even though this comma is inside the string.
test.concat([", "]);

It only happens if i press comma + space in fast succession however. Typing comma then space slowly doesn't trigger the issue.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|24.00GB (1.99GB free)|
|Process Argv|-psn_0_22095121|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by mjbvz** [comment]
Good find.

The root cause is:

* `,` triggers signature help
* There is a slight delay before we actually show the help (this is intentional for cases where the user is typing quickly).
* Before the help is shown, space is typed.
* When help is actually shown sometime later, we incorrectly have now marked the space as what triggered the signature help instead of the `,`

Will look into fix
