### ISSUE TITLE
Win + Right stopped working if you launch VSCode that was exited in a state that its window snapped to screen's left half

### ISSUE THREAD

**Issue by be5invis** [microsoft/vscode#82910]
- VSCode Version: 1.39.2
- OS Version: Windows 10, Version 18362.418

Steps to Reproduce:

1. Launch VSCode
2. Hit <kbd>Win+Left</kbd> to snap the left of the screen
3. Exit Code.
4. Launch VSCode again
5. Hit <kbd>Win+Right</kbd>. It won't work now.

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
I wonder if this issue is reproducible when running VSCode in a browser or bare Electron. For that purpose, can you please:
* install `git` if not installed already (https://git-scm.com/)
* install `node.js` if not installed already (https://nodejs.org/en/download/)
* install `yarn` if not installed already (https://yarnpkg.com/lang/en/docs/install)
* `git clone https://github.com/bpasero/vscode-runner.git`
* `yarn`
* Web (Chrome only): `yarn web`
* Electron: `yarn electron`

And report back if you still reproduce the issue **in either or both web and Electron**?

**Comment by be5invis** [comment]
@bpasero I cannot reproduce either. Neither Chrome nor bare Electron remember the window position and size if the window is snapped, so after a relaunch it would be placed as a normal window.

**Comment by be5invis** [comment]
UPDATE: Chrome seems remember the window size and placement if it is snapped, so Win-Right does not too. I suspect it applies to all Windows applications...

**Comment by bpasero** [comment]
VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

Reading this issue, it seems to originate not from VSCode itself but rather one of these upstream components. As such, in order to resolve it, it would need to get fixed in the upstream component. I will go ahead and close this issue and kindly ask to report this issue to the upstream component if possible:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
