### ISSUE TITLE
Add a default keybinding for `cursorRedo`

### ISSUE THREAD

**Issue by NotWearingPants** [microsoft/vscode#82932]
`cursorRedo` is bound by default to <kbd>Ctrl</kbd>+<kbd>U</kbd>
This short keybinding also shows that this is a commonly used shortcut.

`cursorUndo` should also have a default keybinding as it is complementary to `cursorUndo`.

I suggest <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>J</kbd> because it is the shortest keybinding I could find that wasn't taken when the editor is focused (except <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Q</kbd> which could also be an option).

**Comment by alexandrudima** [comment]
Thank you for the suggestion, but I don't think `cursorRedo` should get a proeminent keyboard shortcut by default. 

The reason is simple, `cursorUndo` is an important keybinding, especially in the use-case of <kbd>ctrl</kbd>+<kbd>D</kbd>, when it is easy to press one <kbd>ctrl</kbd>+<kbd>D</kbd> too many when selecting multiple words. It is then possible to undo the last <kbd>ctrl</kbd>+<kbd>D</kbd>. In this case, `cursorRedo` can be mimicked by applying the cursor operation again, like pressing <kbd>ctrl</kbd>+<kbd>D</kbd> again... So IMHO `cursorRedo` is much more useful than `cursorUndo`.

I would leave it up to end users to configure their keybindings, especially since it is so easy to do. We can definitely accept PRs for different keymap extensions if we want to align with other editors.
