### ISSUE TITLE
Configure trust domains not working from Preview of Readme file

### ISSUE THREAD

**Issue by banothurameshnaik** [microsoft/vscode#82954]
Issue Type: <b>Bug</b>

Open preview of any `Readme.md` file (Shortcut **ctrl+shift+v**)

and click on any links from it, then following pop-up shows

![image](https://user-images.githubusercontent.com/25602365/67183933-36ea1a80-f400-11e9-8831-db7bef724e45.png)

But even we click on Configure Trust domains, it won't open trust domain list to add

**It simply ignores and nothing happens**

Please check

Thanks Ramesh

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 4.15.0-65-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 2399)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.53GB (0.29GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.31.1
vscode-eslint|dba|1.9.1
gitlens|eam|10.1.1
vscode-great-icons|emm|2.1.47
vscode-todo-plus|fab|4.14.1
dotenv|mik|1.0.1
vscode-docker|ms-|0.8.1
python|ms-|2019.10.41019
Go|ms-|0.11.7
material-icon-theme|PKi|3.9.1

</details>

**Comment by octref** [comment]
@banothurameshnaik If you use the command "Manage Trusted Domains", what's being shown there?

**Comment by banothurameshnaik** [comment]
@octref 
Using the command **"Manage Trusted Domains"** and adding the domain into the list manually

and then coming back to the Preview Page of Readme file to click on the link it works and opens the link into the browser.

But it could be better it automatically adds into a trusted domain list by clicking of **Configure Trusted Domains** as in other files.

**Comment by octref** [comment]
The issue: Try adding a domain by clicking link -> clicking Configure Trusted Domains -> Add domain -> Then run command "Manage Trusted Domains" -> you don't see it updated

The reason is when doing https://github.com/microsoft/vscode/issues/81843, I made the source and parsed content separate. The flow above updates the parsed content but not the source.
But as the source might contain errors, comments, etc, there's no way to 100% update it correctly. So I reset it to a fresh state.

Verifier:

- Verify that after clicking "Configure Trusted Domains" and then adding a domain:

    ![image](https://user-images.githubusercontent.com/4033249/67814488-684a9200-fa61-11e9-9449-19512e34d286.png)

    You should see it newly added when running "Manage Trusted Domains"

- Verify that if you run "Manage Trusted Domains", comment out one line with a domain, run the flow above, then run "Manage Trusted Domains" again, you should see the commented-out line gone (with new domain correctly added). This is intended as it's less wrong.
