### ISSUE TITLE
Command-C & Command-V does not duplicate the whole line

### ISSUE THREAD

**Issue by iandees** [microsoft/vscode#83003]
Issue Type: <b>Bug</b>

Previously, Command+C would copy the entire line behind the caret to the clipboard (including the newline). Pasting that line with Command+V would insert the line on the next line.

Today, when I tried to perform the same action, it seems to copy the entire line and then paste it on the same line.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.5.0

<details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
vscode-markdownlint|Dav|0.31.1
rainbow-csv|mec|1.3.1
prettify-json|moh|0.0.3
vscode-docker|ms-|0.8.1
vscode-kubernetes-tools|ms-|1.0.5
python|ms-|2019.10.41019
Go|ms-|0.11.7
java|red|0.51.0
vscode-yaml|red|0.5.3
vscode-open-in-github|sys|1.13.0
vscodeintellicode|Vis|1.2.0
vscode-java-debug|vsc|0.22.0
vscode-java-dependency|vsc|0.6.0
vscode-java-pack|vsc|0.8.0
vscode-java-test|vsc|0.20.0
vscode-maven|vsc|0.19.1
vscode-proto3|zxh|0.3.0

</details>

**Comment by shelbykauth** [comment]
Same.
Tested after "Developer: Reload With Extensions Disabled" as well, behaves the same.
<details>
  <summary>Copied "About Visual Studio Code" info</summary>
  
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 17.7.0

</details>

Definitions:
 - Good="Pastes whole line and new line from the furthest left position on the line your cursor is on".
 - Bad="Pastes whole line and new line from where your cursor is currently"

The first copy&paste after a reload is Good, IF you don't click anywhere in the editor.
Reload -> Paste -> Bad
Reload -> Copy -> Paste -> Good
Reload -> Copy -> Move -> Paste -> Good -> Move again -> Paste -> Bad.

False positives for Good if your cursor happens to be at the beginning of the line.  Therefore I cannot test...
Reload -> Copy -> Paste -> Good -> Copy -> Paste -> ???

**Comment by shelbykauth** [comment]
It does seem highly related.
Testing with reloading window.

Good: Replaces all occurrences / Pastes at all cursors
Bad: Replaces just one occurrence / Pastes at one cursor.

Note: This is in more rapid succession because it doesn't involve moving the cursor

Cmd+D multiple times -> Reload (cursor stays in multiple places) -> Paste -> Good -> Paste -> Good -> Paste -> Good -> Undo, Undo, Undo -> Paste -> Good -> Wait -> Paste -> Bad -> Paste -> Bad -> Paste -> Bad

**Comment by shelbykauth** [comment]
So it seems to be tied into something loading.

**Comment by DwaynesWorld** [comment]
Since I have disabled and re-enabled the extensions, I have not been able to reproduce either issue.

**Comment by shelbykauth** [comment]
Hm... I was able to reproduce both issues with extensions disabled the first time.  But now they won't work while extensions are disabled.

Reloading normally will bring the issue back after a few seconds.  I'll grab the list of extensions.

**Comment by shelbykauth** [comment]
I believe the bug can be described something akin to vsCode's smart pasting not working, and vsCode's pasting behaving like a more standard text editor (NP++ or Window's Notepad, for instance)

**Comment by tbriggs707** [comment]
I have been seeing similar issues. Here, all I am doing is `Ctrl+C` and `Ctrl+V` to copy/paste the entire line.

Expected:
![Expected Behavior](https://user-images.githubusercontent.com/2791682/67248276-2a29ee80-f421-11e9-9066-3231d661249a.gif)

Actual:
![Actual Behavior](https://user-images.githubusercontent.com/2791682/67248804-cb657480-f422-11e9-935c-24f023383b83.gif)

**Comment by peterneely** [comment]
I had this problem too. The "language support for java" extension was causing it. When I disabled it, no more drunken copy/paste. https://marketplace.visualstudio.com/items?itemName=redhat.java

**Comment by alexandrudima** [comment]
This seems to be caused by the `redhat.java` extension which overrides the paste implementation [here](https://github.com/redhat-developer/vscode-java/blob/4a9389e580b9f7c7fa8c4d2e0140e7a588fffcf0/src/settings.ts#L154). I have opened [an issue](https://github.com/redhat-developer/vscode-java/issues/1115) directly against the extension.

Possible workarounds: configure `"java.actionsOnPaste.organizeImports": false` or disable/uninstall the `redhat.java` extension.

**Comment by eliyo** [comment]
Not sure if this is the same issue, but when writing Python code on VS 1.39.2 an copying/pasting a set of multiple lines, the end-of-line does not get pasted so we have manually go back to the beginning of each line to copy another block.

**Comment by shelbykauth** [comment]
@eliyo I don't __think__ that's the same issue, but it's hard to tell from the description.  A set of multiple lines does not do the same smart-paste thing, because multiple lines together has to be highlighted, typically.  And I'm not sure what you mean about manually going to the beginning of each line to copy another block.  Do you mean "copy one line, paste it where it should go, copy the next line, paste it just below the previous paste, copy the next line, paste it just below the previous paste", etc?  If so, that's confusing that you must do that even with normal text editors.

If you're referring to multiple separated lines (multiple cursors, one on each line), then yeah, the line end doesn't work normally.  Try this.  After you have a multi-cursor on each line, hit `Home`, then hit `Shift` + `Down`.  Then make sure you either have a cursor on the exact same number of lines or are pasting into one place.  And again hit `Home` before pasting.
