### ISSUE TITLE
Linux: Multiple Cursor Copy/Paste

### ISSUE THREAD

**Issue by tbriggs707** [microsoft/vscode#83017]
I am trying to copy/paste several lines of code, but it appears that the behavior for this has changed and I'm not sure how to correct this.

When I select multiple words (cursor on each word). Copy. Place the same number of cursors somewhere else. Paste. Instead of pasting one word with each cursor, it is pasting all words where the last cursor is located.

![Example](https://user-images.githubusercontent.com/2791682/67247291-22b51600-f41e-11e9-8ec0-9a64b404094d.gif)

Versions:
- VS Code Version: 1.39.2
- Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
- OS: Linux x64 4.15.0-65-generic (Elementary OS 5.0)

I discussed this on [StackOverflow](https://stackoverflow.com/questions/58492730/vscode-multiple-cursor-cut-paste-behavior-changed/58492958?noredirect=1#comment103316886_58492958). Please read through the comments on Mark's answer for more details and things I tried in troubleshooting this.

**Comment by AndiDog** [comment]
For me, this bug was introduced around 1.39 or 1.39.1.

Also – tested on macOS – Cmd+C followed immediately by Cmd+P does not work (no matter if I leave the finger on Cmd or not)... I first have to put the cursor somewhere else before pasting. This is a quite typical action for instance to duplicate selected text right at the spot.

Probably related to #83002?

**Comment by AndiDog** [comment]
Another bug: if you use the "Copy" action somewhere in a line (without having selected characters), the whole line would be copied. That's still the case. However, previously, pasting that line somewhere would prepend the whole line from the clipboard before the line of the cursor, but this has now changed to insert the line content right where current cursor is.

**Comment by alexandrudima** [comment]
@tbriggs707 I cannot reproduce:

![Kapture 2019-10-22 at 14 27 56](https://user-images.githubusercontent.com/5047891/67285623-30c76d00-f4d8-11e9-9528-56622074843d.gif)

Have you tried to disable all extension? Do you have any relevant customizations to your `keybindings.json` ?

**Comment by alexandrudima** [comment]
@AndiDog Can you please open a separate issue, I don't believe you have the same issue.

**Comment by bartstudios** [comment]
I've the same issue even when disabling all extensions.

**Comment by bartstudios** [comment]
Ok, I think I was not up-to-date.  I've been updated yesterday to a previous version that had the bug.  Now it seems okay with 1.39.2

**Comment by tbriggs707** [comment]
Keybindings for `Ctrl+V`:
![keybindings](https://user-images.githubusercontent.com/2791682/67305890-58580e80-f4b3-11e9-8058-173173b14f48.png)

When I disable all of my extensions, the behavior is as expected (no issues). So I enabled the extensions one by one to see which was the cause. And I found that it was the Java Extension Pack.
When I disable this extension, the following are also disabled:
![disabled extensions](https://user-images.githubusercontent.com/2791682/67307591-fe0c7d00-f4b5-11e9-94a6-74157bfbc769.png)

Also, the second answer on [StackOverflow](https://stackoverflow.com/questions/58492730/vscode-multiple-cursor-cut-paste-behavior-changed/58496522#58496522) suggested that I use `Ctrl+Shift+V` and this worked as well.

**Comment by alexandrudima** [comment]
This seems to be caused by the `redhat.java` extension which overrides the paste implementation [here](https://github.com/redhat-developer/vscode-java/blob/4a9389e580b9f7c7fa8c4d2e0140e7a588fffcf0/src/settings.ts#L154). I have opened [an issue](https://github.com/redhat-developer/vscode-java/issues/1115) directly against the extension.

Possible workarounds: configure `"java.actionsOnPaste.organizeImports": false` or disable/uninstall the `redhat.java` extension.
