### ISSUE TITLE
Multicursor - on paste 

### ISSUE THREAD

**Issue by gregcousin126** [microsoft/vscode#83063]
I have a problem with my vscode. when i try to copy multiple lines and paste them onto the editor it wont paste the multiple lines in any other way than paste the copied lines on the first cursor. even if i copy one word and then use the multicursor tool to select/highlight multiple sequences of the same word and try to paste what i copied... it will only copy the word on the first cursor selected.

**Comment by gletthereblight** [comment]
Me either,I also discovered it earlier. #83057 is my issues,but in Chinese.This is the same problem,especially affecting me to write sql code.

**Comment by ruffson** [comment]
Same issue here. On `1.39.2`.

**Comment by dhairyanadapara** [comment]
@gregcousin126 can you please share steps to reproduce it. The video will help more to understand the issue. Thanks

**Comment by peterneely** [comment]
I had this problem too. The "language support for java" extension was causing it. When I disabled it, no more drunken copy/paste. https://marketplace.visualstudio.com/items?itemName=redhat.java

**Comment by ruffson** [comment]
@peterneely 

Seems to be a problem on macos and linux.
Maybe an extension is causing this?

![](https://i.ibb.co/dmRsQhC/demo.gif)
Here I selected several lines and try to paste `1`. Then, I just __type__ a `2` which works fine and then I delete the 2s and try again to paste the `1` again. You can see that only in the last line code gets pasted.

**Comment by alexandrudima** [comment]
This seems to be caused by the `redhat.java` extension which overrides the paste implementation [here](https://github.com/redhat-developer/vscode-java/blob/4a9389e580b9f7c7fa8c4d2e0140e7a588fffcf0/src/settings.ts#L154). I have opened [an issue](https://github.com/redhat-developer/vscode-java/issues/1115) directly against the extension.

Possible workarounds: configure `"java.actionsOnPaste.organizeImports": false` or disable/uninstall the `redhat.java` extension.
