### ISSUE TITLE
Multiple cursor experience is getting worse

### ISSUE THREAD

**Issue by qiumo** [microsoft/vscode#83080]
When I use multiple cursor, I just copy 1 line text, it should be paste at all of the cursors, but it's not work, it only paste at first cursor.

So, you tell me, why I use multiple cursor when I just copy 1 line text? Just for the first cursor?

**Comment by peterneely** [comment]
I had this problem too. The "language support for java" extension was causing it. When I disabled it, no more drunken copy/paste. https://marketplace.visualstudio.com/items?itemName=redhat.java

**Comment by qiumo** [comment]
> I had this problem too. The "language support for java" extension was causing it. When I disabled it, no more drunken copy/paste. https://marketplace.visualstudio.com/items?itemName=redhat.java

Wow, exactly solution the problem, thank you very much!!
I think I misunderstood VScode developers, and I shoud say "sorry".

**Comment by alexandrudima** [comment]
This seems to be caused by the `redhat.java` extension which overrides the paste implementation [here](https://github.com/redhat-developer/vscode-java/blob/4a9389e580b9f7c7fa8c4d2e0140e7a588fffcf0/src/settings.ts#L154). I have opened [an issue](https://github.com/redhat-developer/vscode-java/issues/1115) directly against the extension.

Possible workarounds: configure `"java.actionsOnPaste.organizeImports": false` or disable/uninstall the `redhat.java` extension.
