### ISSUE TITLE
Autosave toggle should tell me weather is on off

### ISSUE THREAD

**Issue by b-hayes** [microsoft/vscode#83102]
Issue Type: <b>Feature Request</b>

I can hit cmd+shift+p and type autosave and toggle it but I have no idea weather I just turned it on or off.

There seem to be no visual indicator that i can spot that tells me if its on or not.

Please show the status of the toggle in the command.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:00.827Z)
OS version: Darwin x64 18.7.0

**Comment by Ragnoroct** [comment]
It turns out it just changes the config value files.autoSave between off and afterDelay.

**Comment by Ragnoroct** [comment]
![vscode_action_toggle_auto_save](https://user-images.githubusercontent.com/19155205/67342057-e0133c80-f4f6-11e9-8662-49578ec1e298.gif)

**Comment by b-hayes** [comment]
Yeah I dont see those message pop up on macos.

**Comment by sbatten** [comment]
the status of autosave is in the menu: 
![image](https://user-images.githubusercontent.com/6561887/67416968-aab13200-f57c-11e9-993a-0a904905db47.png)

**Comment by b-hayes** [comment]
Ah right lol. I dont use the menu much I search for everything. Feel silly now that its right ther ein file menu.

Would be nice to see what the change is when using the command search tho. I wasn't seeing notifications pop up as @Ragnoroct displayed

I don't see the notifications on macos or windows witch means using the command search is pointless if you have to then go to the menu to check what it has done.

I know its a small issue but would make sense to display information on what a toggle run form the command search is doing.

**Comment by sbatten** [comment]
@b-hayes You don't see the notification because that was from OP's PR which was not merged. I don't think the command should be used as a check for whether or not auto-save is enabled. I believe the user should know before they run the command, otherwise they might turn it on and accidentally save a bunch of stuff unintentionally. Another quick check is to just type some changes into a file and see if the dirty icon remains after a second or unfocusing the editor. My main point is that a user should not have to wait until after they run the command to find out the setting and therefore I believe the notification does not fit.

**Comment by b-hayes** [comment]
> My main point is that a user should not have to wait until after they run the command to find out the setting and therefore I believe the notification does not fit.

I agree. Would be good to see its status in the command search.

**Comment by Ragnoroct** [comment]
I think that makes sense too. That would stay consistent with the File menu check mark for toggling autosave.
