### ISSUE TITLE
Web: allow to run extension tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#83145]
Currently seems to not set the extension tests path properly.

**Comment by weinand** [comment]
There are two issues:
- the environment attribute 'extensionTestsPath' needs to be passed properly.
- when running VS Code in the web UI or in a remote setup, the value of the 'extensionTestsPath' attribute must be a valid path that exists in the filesystem. This is a problem because for historical reasons the path generated by yeoman is `${workspaceFolder}/out/test/suite/index` which does not exist in the filesystem (because it lacks the file extension `.js`). When running tests locally, the non-existing path is not an issue because mocha will find the tests anyway. 

The first problem has been fixed in VS Code.
The second problem requires a change in "node-debug2".

**Comment by bpasero** [comment]
**Verification:** open a hello world extension in the web and run its unit tests.

**Comment by weinand** [comment]
The tab where the VS Code instance runs the tests is not closed automatically at the end.

**Comment by roblourens** [comment]
I hadn't published node2 with the fix. Doing that now, we can reverify this tomorrow.

**Comment by weinand** [comment]
Verification is trivial:
- open a hello world extension in the web and run its unit tests.

**Comment by alexr00** [comment]
Verified using https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-test-sample and running the tests.
