### ISSUE TITLE
Attaching the process gives different errors in different platforms

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#8315]
#8196

- VSCode Version: Insiders
- OS Version: Windows

Steps to Reproduce:

1. Open VSCode for a sample folder
2. Create a new launch config to pick a node process
3. Open VSCode for vscode-node-debug
4. Run Server in launch config
5. In Sample folder workspace, Run 'Attach a process'
6. Select the node process which is from vscode-node-debug

In Windows, I get an error that 
Attach to process: cannot enable debug mode for process 'id' (reason: Error: T) : Reason does not makes sense.

In Mac, I get a timeout error

May be it would be useful to provide some information or a link why this is not enabled.

**Comment by weinand** [comment]
@sandy081 A great find: attach to a node process didn't work on Windows at all because the electron based node doesn't have a working implementation of process._debugProcess(<pid>). This didn't show up in development because we are using a regular node there.
The fix is to run the process._debugProcess in a regular node.
