### ISSUE TITLE
Limited FPS in full screen

### ISSUE THREAD

**Issue by kamenminkov** [microsoft/vscode#83163]
Issue Type: <b>Performance Issue</b>

VS Code version: Code - Insiders 1.40.0-insider (f5d3ffa6a0d655c87e1eb0e1e90773df58f7ff25, 2019-10-23T05:25:50.857Z)
OS version: Windows_NT x64 10.0.19002

Note: also happens with latest stable as of now (1.39.2) on the same system.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz (12 x 3300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>
Extensions: none

Steps to Reproduce:

1. Open `Developer Tools -> Rendering` and tick `FPS meter`.
2. Open a blank file.
3. Enter full screen.
4. Hold down a key on your keyboard so that a character gets inserted into the file repeatedly.
5. Exit full screen and try step 4 again.

Notes:
- 1 is optional, just used to verify this. There's the same perceived lag without Devtools open.
- The issue happens in any scenario when there's a more intensive animations going on, holding down a letter is probably the simplest to reproduce assuming a fast enough repeat rate (another example is dragging the minimap slider to scroll through a large file).

**Expected result**: both scenarios should show the same performance.
**Actual result**: Judging by the FPS meter, full screen framerate tops out at about 36-37 FPS, windowed mode reaches 59-60 FPS (on a 60 Hz screen).

Does this issue occur when all extensions are disabled?: Yes
Does this issues occur with an empty `settings.json` file? Yes

**Edit: the issue seems to be affected by resolution. Initial testing (when the issue occurred) was done on a WQHD (2560x1440) screen. The issue does not manifest on a smaller (1680x1050) screen.**

**Comment by bpasero** [comment]
VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

Reading this issue, it seems to originate not from VSCode itself but rather one of these upstream components. As such, in order to resolve it, it would need to get fixed in the upstream component. I will go ahead and close this issue and kindly ask to report this issue to the upstream component if possible:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.

**Comment by kamenminkov** [comment]
Thanks for the pointer.
I think I managed to narrow down the issue to some extent. It seems that this is indeed a Chromium bug - as it turns out it also exists in several Chromium-based browsers.
Running VSCode with a `--use-angle=d3d9` as a command line argument (that's a Chromium flag) seems to be a workaround at the expense of slightly different rendering.

**Comment by kamenminkov** [comment]
Turns out it might have been a Windows issue. Just updated from 19008 to 19013 and saw the changelog mentioning a fixed issue about full screen apps and frame skipping. Both browsers and VSCode are now running fine in full screen without any flags.
