### ISSUE TITLE
Markdown preview: does not preview the file I picked?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8317]
When I have tabs disabled and I jump between 2 markdown files to preview, always the first one is previewed. Is this an issue with contexts?

Video:

![untitled](https://cloud.githubusercontent.com/assets/900690/16413093/1d11d13c-3d30-11e6-97ae-4eae39bd0678.gif)

**Comment by bpasero** [comment]
Seems to be related to using the actions in the editor action bar top right.

**Comment by jrieken** [comment]
The menu item uses the wrong `resource`. It gets that from the keybindings service...

**Comment by jrieken** [comment]
Underlying issue was that the editor title action bar considers an action to be equal if the `id` didn't change. Now, the menu keeps the same action instances (since they are already scoped to 'this' menu) and updates them with the proper context instead of re-creating them. 

Tho it is somewhat unexpected @bpasero that `id` means equality

**Comment by bpasero** [comment]
No real reasoning behind it other than I did not want to recreate the toolbar when nothing changed. My weak attempt for not having react components...

**Comment by jrieken** [comment]
:-) maybe the toolbar should diff what did and will render

**Comment by bpasero** [comment]
Yeah, putting it on the toolbar would make more sense. However it gets ugly and tricky when you have an action that points to an action item that can custom render what it wants.

**Comment by jrieken** [comment]
oh, yeah
