### ISSUE TITLE
Scrolling too fast

### ISSUE THREAD

**Issue by Gustavo-Sz** [microsoft/vscode#83184]
There is no steps to reproduce. 

Since i have activated the windows touchpad gestures, i got this problem on scrolling. It was normal before, when i had it deactivated. I can't scroll because , no matter how small is the distance i move my fingers up/down on the touchpad,  the editor seems to jump to the start or end of the lines due to the high sensibility of the scroll. i also saw that this problem was already reported in here, but the solution given makes no sense at all, at least those i have read. 

Details:
- Happens only in vscode;
- When the touchpad gestures fails (that happened 2 times), the scrolling backs to normal, in other words: there is a correlation;
- With a normal mouse, the scrolling is perfect;
- I have already decreased to the maximum all the scrolling speed settings, whether in vscode or windows.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2019.10.41019
vscode-yaml|red|0.5.3

**Comment by alexandrudima** [comment]
@Gustavo-Sz I am not sure what we can do in VS Code, since we simply react to the scroll events that come in. The only knob we have is perhaps `editor.mouseWheelScrollSensitivity`, which is used to multiply the incoming scroll event `deltaX` / `deltaY`. Have you tried tweaking that as a possible workaround?

VS Code is built with Electron, which is built on top of Chromium. I think this might be an issue with Chromium, so could you please try opening https://microsoft.github.io/monaco-editor/ in Chrome. Does the scroll issue reproduce there as well?

**Comment by Gustavo-Sz** [comment]
Thank you so much !!!!!! editor.mouseWheelScrollSensitivity at 0.005 solved the problem. Funny, because i'm pretty sure i have tried once before and nothing happened. Also, it worked normally on that site you linked.
