### ISSUE TITLE
Webview bleeds on top of statusbar

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#83209]
Notice the status bar in the bottom of the workbench:

![image](https://user-images.githubusercontent.com/22350/67466375-460ed980-f647-11e9-94cc-3141dcfdc43a.png)

**Comment by sbatten** [comment]
@mjbvz let me know if investigation suggests you are getting the wrong dimensions somehow

**Comment by mjbvz** [comment]
@joaomoreno Any reliable repo steps?

**Comment by joaomoreno** [comment]
This is weird, but surely reproducible. I can reproduce on my Windows 10 VM (running in QEMU/KVM, Linux host), screen resolution set to 1440x1050:

1. Launch Code. Make sure window is full screen. If it isn't, make it fullscreen, close it and launch Code again.
2. Go to extension viewlet, search for Azure Repos extension and open it.
3. Wait for it to load and close it.
4. Open it again.

![Peek 2019-10-31 09-15](https://user-images.githubusercontent.com/22350/67930068-3ea77d00-fbbf-11e9-9caa-25bb93974503.gif)

**Comment by pxohlqo** [comment]
Not only status bar...
<img width="1268" alt="截屏2019-11-22上午11 45 08" src="https://user-images.githubusercontent.com/17199052/69396656-f55dcf80-0d1d-11ea-9a1b-1300c3414328.png">

**Comment by hobeas** [comment]
My console also disappeared. This only happens when opening extensions with suggestions.
1. normal
<img width="987" alt="normal" src="https://user-images.githubusercontent.com/41267951/69918746-e7901300-14b0-11ea-9f58-80369e4fff77.png">

2. Click on extension that contains suggestions (Star mark in upper right corner).
<img width="987" alt="contains-suggestions" src="https://user-images.githubusercontent.com/41267951/69918925-4904b180-14b2-11ea-8844-2f38fa2af742.png">

3. Console buttons are overwritten if there is too much suggestions text.
<img width="810" alt="console-disappeared" src="https://user-images.githubusercontent.com/41267951/69918961-bdd7eb80-14b2-11ea-9312-f6aa62cf6cd2.png">

4. I guess the problem is from div `z-index`. I open the developer tools. add `z-index: 1`, can make console buttons reappear.
<img width="1445" alt="try-to-fix" src="https://user-images.githubusercontent.com/41267951/69919095-38553b00-14b4-11ea-8d2c-3f036c68db31.png">

**Comment by OutOfFocus4** [comment]
Reproduced using Visual Studio Code for MacOS

System Info:
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0
```

**Comment by mjbvz** [comment]
To repo, open the Chrome extension page. It seems to reliably trigger this
