### ISSUE TITLE
Broken status bar octicons

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#83210]
The [Azure Repos](https://marketplace.visualstudio.com/items?itemName=ms-vsts.team) extension looks like this in the latest insiders:

![image](https://user-images.githubusercontent.com/22350/67466857-13b1ac00-f648-11e9-81bc-38737ac55d98.png)

Did we break them somehow?

**Comment by misolori** [comment]
Someone else reported this in https://github.com/microsoft/vscode/issues/82511 and I’m not sure why the extension is referencing icons this way since our [documentation](https://code.visualstudio.com/api/references/icons-in-labels) says to use ‘$(icon-name)’, @bpasero does this sound familiar?

Looks like https://github.com/microsoft/azure-repos-vscode/issues/572 already has a PR that fixes this.

**Comment by bpasero** [comment]
No, never heard of, but did we change the names of icons?

**Comment by misolori** [comment]
We didn’t change any icon names, but we did switch from Octicons to use Codicon. I did a search on GitHub for the use of `$(icon octicon-)` to see if others use it and the azure repos extension appears to be the only one.

**Comment by joaomoreno** [comment]
Then we can just give them an issue for them to start using codicons?

**Comment by misolori** [comment]
I [left a comment](https://github.com/microsoft/azure-repos-vscode/issues/572#issuecomment-545976829) on https://github.com/microsoft/azure-repos-vscode/issues/572 since that's tracking the issue on their side.
