### ISSUE TITLE
when window.onDidWriteTerminalData could be stable?

### ISSUE THREAD

**Issue by zsytssk** [microsoft/vscode#83224]
I write a extension rely on this api.

**Comment by Tyriar** [comment]
The current plan is for it not to go stable.

**Comment by znorman-harris** [comment]
Any update on this becoming stable and not just in insiders? I was planning on using terminal.onDidWriteData, but I just found out that had been deprecated. I saw #78574 from August and was curious after I saw this saying there is no plan on it becoming stable.

Related question: when I was using this with insiders I was wondering if there was a built-in method for clearing out the ANSI formatting from the event data? I found a regex that does the trick [here](https://stackoverflow.com/questions/25245716/remove-all-ansi-colors-styles-from-strings/29497680) after a slight modification, but didn't know if there was something that already exists to do that.

**Comment by Tyriar** [comment]
No change, there's performance concerns with letting anyone hook into this especially since it's a global event now (listening to one terminal means sending _all_ terminal data to the extension host).

> when I was using this with insiders I was wondering if there was a built-in method for clearing out the ANSI formatting from the event data

This was a problem with tasks too, internally the terminal sends tasks lines when they're finished (the cursor moves or a LF is added):

https://github.com/microsoft/vscode/blob/d386b49dee6267238389c0a616af2be89726a4e3/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1155-L1161

If we wanted to give extensions access we might want to expose that as well (but it means even more data jumping processes).

**Comment by zsytssk** [comment]
@Tyriar I understand vscode team concern, onDidWriteTerminalData has its issues.
but it's function is complete and very useful. maybe could create something like
"unsafe api" just like proposal api. the extension author can choose this api and user will get alert information about this api issue when install the extension.

**Comment by Tyriar** [comment]
@zsytssk we could always add a warning to the API, but if it's there then extensions will use it, and VS Code's performance will be perceived as worse as a result. Forcing notifications is also a very bad pattern that we avoid wherever possible.

**Comment by znorman-harris** [comment]
@Tyriar So, if performance is that much of a concern, why not revert the change back to a terminal-by-terminal capture? Otherwise anyone who was planning on using the terminal capture (or anyone who did use it in an extension) has no solution/workaround.

**Comment by Tyriar** [comment]
> why not revert the change back to a terminal-by-terminal capture

The old model was also proposed and was not meant to be used in extensions, I think the guard was missing.
