### ISSUE TITLE
editor.fontLigatures: false doesn't disable all ligatures

### ISSUE THREAD

**Issue by nathan-rogers** [microsoft/vscode#83273]
Using PragmataPro Mono, ¯1 (high minus and any character) are joined together to look like a single character so that ¯ appears directly above the subsequent character. "editor.fontLigatures" is set to false, and I've closed and reloaded the window several times. 

¯1 appears correctly in the terminal with the same font. 
¯1 appears correctly in other editors I've tried (atom, notepad++, emacs, vim) with the same font.

**Comment by alexandrudima** [comment]
@nathan-rogers First, I recommend that you switch to Insiders until the next stable realease because on Insiders -- https://code.visualstudio.com/insiders/ -- it is now possible to manually specify the [`font-feature-settings`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings).

Once on Insiders, when you configure `"editor.fontLigatures": false`, we actually generate behind the scene `font-feature-settings: "liga" off, "calt" off`, but it is possible for you to manually specify the font feature settings. So you could write in your `settings.json`:

```
"editor.fontLigatures": "'liga' off, 'calt' off"
```

Once you are doing this, you need to look into the font itself (maybe there is some README when you buy it?) and find out under what name it is possible to disable those ligatures in that specific OpenType font.
