### ISSUE TITLE
Mac: Restore last minimized window when clicking on app icon in the dock

### ISSUE THREAD

**Issue by yourfavorite** [microsoft/vscode#83272]
When minimizing multiple windows to the dock the application should restore the most recently minimized window but instead it somehow chooses a window to be THE window and that window will always be the one restored when you click on the icon in the dock.

*Currently:*
Minimize window A then B then C.
Click on VSC icon in dock.
Window A is restored.

Minimize window B then A then C.
Click on VSC icon in dock.
Window A is restored.

*Desired:*
Minimize window A then B then C.
Click on VSC icon in dock.
Window C is restored.

**Comment by bpasero** [comment]
VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

Reading this issue, it seems to originate not from VSCode itself but rather one of these upstream components. As such, in order to resolve it, it would need to get fixed in the upstream component. I will go ahead and close this issue and kindly ask to report this issue to the upstream component if possible:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
