### ISSUE TITLE
Terminal link hover position is inconsistent with editor

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#83293]
![image](https://user-images.githubusercontent.com/2193314/67565291-ead9f700-f6d9-11e9-80df-d9757c3d5f55.png)

Expected:

![image](https://user-images.githubusercontent.com/2193314/67565317-f9281300-f6d9-11e9-8056-8376d4291d86.png)

**Comment by Tyriar** [comment]
Fixed in https://github.com/microsoft/vscode/pull/83175

Verifier please test only the position of the hover, not the content/style, that's covered in https://github.com/microsoft/vscode/issues/78647

**Comment by connor4312** [comment]
Looks good overall.

There seems to be one edge case where if the top of the link is above the screen, we wrap

![](https://memes.peet.io/img/19-10-d0372d78-e261-4de0-9c27-ca1b32fcd3f2.png)

Whereas vs code prefers to show it on the left side underneath the cursor

![](https://memes.peet.io/img/19-10-2c60b2e7-2326-4fef-8cd3-46bb98de9782.png)

Marking this as "found" since it is an inconsistency, but feel free to mark verified if you think the implemented behavior is satisfactory. (and vscode has a [different edge case here](https://memes.peet.io/img/19-10-1c0cec17-52c4-465f-841c-f1a3ab524a28.webm) it looks like, which I'll open an issue for...)

**Comment by Tyriar** [comment]
@connor4312 nice find 👍 I guess if the link starts above the viewport we should position is just below the (0,0) cell
