### ISSUE TITLE
Replace: Replace button should be outside of input field

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8329]
Refs: https://github.com/Microsoft/vscode/issues/8184

I think this would make it easier to discover that you have to press the action to replace all. It also moves the design closer to the editor find widget:

![image](https://cloud.githubusercontent.com/assets/900690/16414909/c38fb556-3d3a-11e6-81ad-09603404c2f5.png)

**Comment by sandy081** [comment]
@bpasero True, idea is to make Find and Replace, Search and Replace look similar. Currently, we just have Replace all button in Search view. Since it is just a single button I placed it inside the input. I felt having it outside would make it left out from the rest of the Search UI. 

Anyway, I would try that and see if it looks good.

**Comment by bpasero** [comment]
Yes it might look weird if it is alone, I wonder if we eventually have more buttons outside like the previous/next arrow?

**Comment by sandy081** [comment]
Yeah that is down the line. Once we have more I would relayout them nicely.

**Comment by bpasero** [comment]
Works for me now.

![image](https://cloud.githubusercontent.com/assets/900690/17619572/746d2e3a-6086-11e6-88d0-acc07b849ddc.png)
