### ISSUE TITLE
Code actions can be requested on document that is not yet opened

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#83338]
Issue Type: <b>Bug</b>

**Repo**
1. Create a ts file `a.ts` with the content `const i = error`
1. rename the file to `b.ts`
1. Rename it back to `a.ts`
1. Then back to `b.ts`

**Bug**
See `unexpected resource` printed in the dev tools console

The root cause seems to be that we end up requesting code actions for `b.ts` before it that file is properly reopened. I added logs in `onDidAddTextDocument` and `provideCodeActions`. Here's what they show:

![Screen Shot 2019-10-25 at 5 26 44 PM](https://user-images.githubusercontent.com/12821956/67611189-c408d880-f74c-11e9-9a39-477dbd5964f2.png)

Noticed how in the last few frames actions are requested for `b.ts` before the `open` for `b.ts` is fired

VS Code version: Code - OSS Dev 1.40.0 (Commit unknown, Date unknown)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.23GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|25%|
</details>

**Comment by mjbvz** [comment]
I've starting debugged this and it looks like `onDidAddTextDocument` is never fired for the last rename. I added a logpoint in [`ModelService.createModel`](https://github.com/microsoft/vscode/blob/7ba9113425fc05ef442421cd251eacdb9e2ad837/src/vs/editor/common/services/modelServiceImpl.ts#L350) and here's what I see happening:

![Screen Shot 2019-10-25 at 5 47 23 PM](https://user-images.githubusercontent.com/12821956/67611606-c02a8580-f74f-11e9-8fe0-a12f72f5ec68.png)

Starting with a file `a.ts`:

1. On the rename of `a.ts` to `b.ts`, `createModel` is invoked for `b.ts` 
1. On the rename of `b.ts` back to `a.ts`, `createModel` is invoked for `a.ts` 
1. On the rename of `a.ts` to `b.ts` again, `createModel` is not invoked 

@alexandrudima or @bpasero: Do you know why this may be happenig? Is it expected?

**Comment by bpasero** [comment]
I cannot reproduce this, I get 3 `createModel` calls properly:

![image](https://user-images.githubusercontent.com/900690/67615286-cb6ec700-f7ca-11e9-9d6f-ebbbea47e638.png)

**Comment by mjbvz** [comment]
@bpasero I can confirm this does not happen for plain text files. Can you test using a TS file containing a quick fix. I just tested this using the oss build (no extensions) in an empty workspace and can still repo this in a TS file using my original repo steps:

<img width="376" alt="Screen Shot 2019-10-28 at 8 04 56 PM" src="https://user-images.githubusercontent.com/12821956/67734460-624fa500-f9be-11e9-9094-8d3934d06e63.png">

**Comment by bpasero** [comment]
> Can you test using a TS file containing a quick fix.

How?

**Comment by alexandrudima** [comment]
@bpasero I think the workbench is acting a bit funny around renaming, but I am not sure if it is necessarily a bug... On the second rename the workbench no longer disposes the old model, but it decides to keep it around, even if the file is deleted on disk... which is a bit bizarre. 

I have disabled git to reduce noise with text models.

---

### Here is how things look like for an extension:

@mjbvz Here is how it looks from an extension point of view

I have done the following diff to TS in `extension.ts`:
![image](https://user-images.githubusercontent.com/5047891/67771804-477e3e80-fa59-11e9-822e-39a57f6ef1df.png)

And in `features/quickFix.ts`:
![image](https://user-images.githubusercontent.com/5047891/67771844-582eb480-fa59-11e9-9790-3de4c64284e8.png)


Rename `a.ts` to `b.ts`.:
* `onDidCloseTextDocument: file:///c%3A/Alex/src/working_dir/a.ts`
* `documents: `
* `onDidOpenTextDocument: file:///c%3A/Alex/src/working_dir/b.ts`
* `documents: file:///c%3A/Alex/src/working_dir/b.ts`
* `TypeScriptQuickFixProvider.provideCodeActions for file:///c%3A/Alex/src/working_dir/b.ts`

Rename `b.ts` to `a.ts`. Note how `b.ts` is not closed:
* `onDidOpenTextDocument: file:///c%3A/Alex/src/working_dir/a.ts`
* `documents: file:///c%3A/Alex/src/working_dir/b.ts file:///c%3A/Alex/src/working_dir/a.ts`
* `TypeScriptQuickFixProvider.provideCodeActions for file:///c%3A/Alex/src/working_dir/a.ts`

Rename `a.ts` to `b.ts`. Note how no open/close text document events are emitted, since `b.ts` was not closed so it is still open:
* `Unexpected resource file:///c%3A/Alex/src/working_dir/b.ts`
* `TypeScriptQuickFixProvider.provideCodeActions for file:///c%3A/Alex/src/working_dir/b.ts`

---

### Here is how things look like in our `IModelService`:

I have added logging in two places in `src/vs/editor/common/services/modelServiceImpl.ts`

![image](https://user-images.githubusercontent.com/5047891/67772325-29fda480-fa5a-11e9-9312-a3218819fdde.png)

![image](https://user-images.githubusercontent.com/5047891/67772349-3550d000-fa5a-11e9-8e8e-23362a2f3374.png)


Open workbench with `a.ts`:
* `createModel file:///c%3A/Alex/src/working_dir/a.ts`
* `==> models alive: file:///c%3A/Alex/src/working_dir/a.ts`

Rename `a.ts` to `b.ts`. Note how `a.ts` is disposed and `b.ts` is created:
* `destroyModel file:///c%3A/Alex/src/working_dir/a.ts`
* `==> models alive: `
* `createModel file:///c%3A/Alex/src/working_dir/b.ts`
* `==> models alive: file:///c%3A/Alex/src/working_dir/b.ts`

Rename `b.ts` to `a.ts`. Note how now the workbench decides to keep `b.ts` around and not dispose it.
* `createModel file:///c%3A/Alex/src/working_dir/a.ts`
* `==> models alive: file:///c%3A/Alex/src/working_dir/b.ts,file:///c%3A/Alex/src/working_dir/a.ts`

Rename `b.ts` to `a.ts`. Note how no events are generated because `b.ts` was around, but the following exception appears from TS:
* `[Extension Host] Unexpected resource file:///c%3A/Alex/src/working_dir/b.ts `

**Comment by bpasero** [comment]
> @bpasero I think the workbench is acting a bit funny around renaming

I am not convinced. This must be something else. We have a very simple ref-counting model of text editor models. The editor will try to dispose the model when it gets closed, but if someone else managed to get hold of the model (via `ITextModelResolverService`), the model will not be disposed until the last reference is freed. 

This smells like the extension host asking for a reference to the model (for the quick fix?) and then holding onto the model for a while (@jrieken might know) and only then dispose it.

I think the issue here is that the extension host is not disposing the reference at the time it is not needed anymore, but only after a delay.

**Comment by bpasero** [comment]
PS: the reason why I think another party is involved is that I still cannot reproduce this when simply having an empty file `a.ts`. Just give that a try. 

```
createModel: file:///Users/bpasero/Desktop/modeldispose/a.ts
modelServiceImpl.js:262 models alive: file:///Users/bpasero/Desktop/modeldispose/a.ts
modelServiceImpl.js:277 destroyModel: file:///Users/bpasero/Desktop/modeldispose/a.ts
modelServiceImpl.js:284 models alive: 
modelServiceImpl.js:252 createModel: file:///Users/bpasero/Desktop/modeldispose/b.ts
modelServiceImpl.js:262 models alive: file:///Users/bpasero/Desktop/modeldispose/b.ts
modelServiceImpl.js:277 destroyModel: file:///Users/bpasero/Desktop/modeldispose/b.ts
modelServiceImpl.js:284 models alive: 
modelServiceImpl.js:252 createModel: file:///Users/bpasero/Desktop/modeldispose/a.ts
modelServiceImpl.js:262 models alive: file:///Users/bpasero/Desktop/modeldispose/a.ts
```

**Comment by alexandrudima** [comment]
:+1: Yeah, I'm pretty sure the fact that we see code actions (which must be disposed!!) has something to do with it... So the ball moves to @jrieken to investigate who is doing model references which prevent the model from getting disposed.

**Comment by jrieken** [comment]
<img width="1015" alt="Screenshot 2019-10-29 at 15 49 44" src="https://user-images.githubusercontent.com/1794099/67778841-1bb48600-fa64-11e9-8698-c7fa48d63165.png">

So, looks like TS itself is calling `openTextDocument` when a rename happens. That would explain why the model isn't disposed immediately (references created on behalf of extensions are auto disposed after a short while).

Tho, I don't know where tsserver is missing the document. The extension host has it, otherwise the call to the code action provider wouldn't event happen (see my previous comment).

**Comment by alexandrudima** [comment]
Perhaps tsserver is listening to file change events from the disk and on the disk the file is deleted ?

**Comment by mjbvz** [comment]
Thank you for looking into this. I now have a better understanding of what is going on.

I think the root cause is that the lifetime of a `TextDocument` does not have to match the lifetime of an document in the VS Code editor. The JS/TS extension only cares about `TextDocuments` that users see in the editor. If an extension holds on to a `TextDocument` that the user then deletes it (or renames it), we generally don't want to keep synchronizing the old document with the tsserver. 

Here is the sequence of events:

1. Starting with a file `a.ts`
    - TS extension creates a synchronized buffer for `a.ts`. This buffer is synchronized with tsserver

1. Rename `a.ts` to `b.ts`
    - First we see `onDidCloseTextDocument` fired with `a.ts`. This causes the js/ts extension to close the  synchronized buffer for `a.ts`.
    - Then we see `openTextDocument` fired for `b.ts`. This creates a synced buffer for `b.ts`
    - Then we hit the [`updatePaths` rename logic in `flushRenames`](https://github.com/microsoft/vscode/blob/73b3fc434823c7580b27db13c7cf033c1af3ad20/extensions/typescript-language-features/src/features/updatePathsOnRename.ts#L103). This calls `openTextDocument` on `a.ts` (which also should be a noop I believe since the document is already open?) It also again tries to close the  synchronized buffer for `a.ts` (which is a noop since we already closed it). 

1. Rename `b.ts` to `a.ts`
    - **There is no `onDidCloseTextDocument` for `b.ts`** (This likely means someone is holding on to a reference to `b.ts`)
    - Then we see `onDidOpenTextDocument` fired with `a.ts`. This causes the js/ts extension to create anew synchronized buffer for `a.ts`
    - Then we hit the updatePaths rename logic in `flushRenames`. **This closes the buffer for `b.ts` (however the `TextDocument` for `b.ts` is still live)** 

1. Rename `a.ts` back to `b.ts`
    - **No events are triggered this time.** This means that a `TextDocument` for `b.ts` already exists, and that someone is holding on the the `TextDocument` for `a.ts`.
    -  Now the code action provider is fired on `b.ts`. It tries to ensure that tsserver has a synchronized buffer for `b.ts`, however it does not so we log this error.
    - A little while later, `flushRenames` kicks in and explicitly opens a buffer for `b.ts`, which is why you only see the error once.

I'm going to look into who is holding on to these text documents that prevents the `open` and `close` events from firing. I'm also going to see if our TypeScript code can be more robust and check the list of TextDocuments before complaining that no syncrhonized  buffer exists.
