### ISSUE TITLE
Horizontal resize screws up horizontal terminal layout

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#8336]
#8222
1. Open integrated terminal - run some scripts which uses all the horizontal space
2. Resize vscode window horizontaly - notice how the terminal will shrink but will never re-grow
3. I would expect the terminal grows horizontally as do the other terminals

![terminalresize](https://cloud.githubusercontent.com/assets/1926584/16415218/77d8f06c-3d3c-11e6-83b5-f6a56c4554f4.gif)

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/sourcelair/xterm.js/issues/103

**Comment by Tyriar** [comment]
I've consolidated all issues related to horizontally resizing the viewport under this one.

**Comment by lrs** [comment]
Several months later and no update? What does "upstream" mean in this context by the way?

I only add a comment because the integrated terminal feature seems to be a major factor when considering whether to go with Code or not.

Is this a problem with Windows installations only? I can use and resize an external cmd window just fine when I exec `npm run build` that is watching for changes for example.

**Comment by Tyriar** [comment]
Upstream means xterm.js. There is a community member who has a PR out at the moment but it needs to be reworked after some big performance related improvements. It applies to all operating systems.

**Comment by lrs** [comment]
OK, thanks for the update.

**Comment by Tyriar** [comment]
The resize discarding data is fixed in Insiders, the data will now reappear when resized back thanks https://github.com/sourcelair/xterm.js/pull/616 from @LucianBuzzo.

@LucianBuzzo also has a PR out that isn't merged just yet that adds support for reflowing the lines so they will get wrapped when the horizontal size is reduced! This is tracked in https://github.com/Microsoft/vscode/issues/23688
