### ISSUE TITLE
[web] VS Code UI breaks on non-Chromium based UAs

### ISSUE THREAD

**Issue by sr229** [microsoft/vscode#83397]
We're building a product using the VSCode codebase with almost no changes with codebase except for some patches to make it work better to our needs.

However, we're getting some reports that users are getting broken UI elements. Links are provided for  everyone to investigate. This concerns VSCode Web since the diversity of UAs can break the styling.

https://github.com/cdr/code-server/issues/1104
https://github.com/cdr/code-server/issues/1110
https://github.com/cdr/code-server/issues/1097
https://github.com/cdr/code-server/issues/1079
https://github.com/cdr/code-server/issues/1063

Will add more issues when we find them.

**Comment by egamma** [comment]
@sr229 thank for this issue. We are interested that VS Code Web works across different browsers.

However, it is painful to track compound issues and it is even more painful to do this in another repository... Therefore please file separate issues and also make these issues self contained so that they have enough context so that we can track them in the vscode repository.

**Comment by sr229** [comment]
No problem! I'll forward this to interested parties.
