### ISSUE TITLE
After accepting suggestion with "overwriteOnAccept" one (next) char is removed

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#83400]
- VSCode Version: 1.40.0 (`29ffbfe3f1c21b01a2d0670170855669dd2b3b4f`)
- OS Version: macOS

Steps to Reproduce:

1. Add `"editor.suggest.overwriteOnAccept": true` in settings.
2. Use suggestion widget to auto-complete existing code and you will see that very often it will remove next char.

For e.g. write `document.()` and move cursor between `.` and `(` and try to auto-complete something for e.g. `getAnimations` instead of `document.getAnimations()` you will get `document.getAnimations)`

Remember this happens often, but not every time, just try and I'm sure you will be able to reproduce the problem.

/cc @jrieken

**Comment by jrieken** [comment]
I cannot reproduce... (tried with JS)

**Comment by jrieken** [comment]
never mind - I can reproduce...

**Comment by jrieken** [comment]
This is actually very similar to https://github.com/Microsoft/vscode/issues/66187. The issue is that the default replace/insert ranges are computed "after" the completion have be computed. If you are either typing fast or if completions are slow then the document contains one more character after completions have been computed. That breaks things. The fix is to compute the default ranges upfront.

**Comment by svipas** [comment]
Thanks for explaining it and fixing. Good work!

**Comment by svipas** [comment]
@jrieken Unfortunately issue still exists.

![Screen Recording 2019-10-29 at 16 24 05](https://user-images.githubusercontent.com/10441177/67776261-c4fd7b00-fa68-11e9-8cc5-d812a2295433.gif)

**Comment by jrieken** [comment]
Unfortunately I cannot use a gif as input. I also wonder what version of TypeScript (I assume) offers word base suggestions at that place? Is that an extension?

**Comment by jrieken** [comment]
I stil don't see word based suggests there. Sure that there is no other extension involved?

**Comment by svipas** [comment]
Yes.

<img width="260" alt="Screenshot 2019-10-29 at 18 00 05" src="https://user-images.githubusercontent.com/10441177/67785514-f597e180-fa75-11e9-9adb-3c2b131c5077.png">

**Comment by jrieken** [comment]
> Try now to remove totalPrice from interface and use auto-complete.

Not sure what that means. Can provide step by step what you are doing?

**Comment by svipas** [comment]
1. Create a new Untitled TS file.

2. Copy-paste this:
```ts
interface Props {
  totalPrice: string;
}

const totalPrice = `${totalPrice}`

```
3. Remove `totalPrice` from interface to look like this:
```ts
interface Props {
 : string;
}

const totalPrice = `${totalPrice}`
```

4. Use suggestion widget to auto-complete the `totalPrice` near `: string`.

Try 3 and 4 step several times.

GIF:

![Screen Recording 2019-10-29 at 18 28 25](https://user-images.githubusercontent.com/10441177/67787888-034f6600-fa7a-11e9-99a5-191e6f8f423a.gif)

**Comment by jrieken** [comment]
idk what's going on here, I don't get word based suggestions because typescript always proposed `readonly` which then mutes word based suggestions. Any change you have those filtered?

<img width="1076" alt="Screenshot 2019-10-29 at 17 39 30" src="https://user-images.githubusercontent.com/1794099/67788682-11e64f00-fa73-11e9-98c1-6ba3d54746d6.png">


Anyways, I do have a theory. This is the same problem just in a different place. Word based suggestions are computed on a web worker (not on the extension host process) and there we have the same problem: first suggestions, then defaults are computed and therefore words from a later state are used.

**Comment by jrieken** [comment]
Pushed another change. Next try tomorrow

**Comment by svipas** [comment]
I'm using VS Code Insiders (`b7b21844e760e632f39bedf651da2bc93f54b0cc`) with extensions mentioned above. I don't have any custom configurations, etc.

Thanks, I will try to test it tomorrow.

**Comment by svipas** [comment]
<img width="912" alt="Screenshot 2019-10-29 at 18 56 32" src="https://user-images.githubusercontent.com/10441177/67790100-d7ce7a80-fa7d-11e9-9458-9fa657f2f45a.png">

I don't know if this helps in any case, but seems I don't get kind 17 or label readonly.

**Comment by jrieken** [comment]
That's just the first round: It's usually snippets, then extensions (TS in this case), then and only when the former didn't produce a result it's word-suggestions

**Comment by aeschli** [comment]
Feature that caused the issue got reverted.
