### ISSUE TITLE
Window.nativeTabs on Windows and Linux

### ISSUE THREAD

**Issue by Hobart2967** [microsoft/vscode#83415]
Like on macOS, where I can enable the Sierra window tabs feature, I would like to use this on Windows and Linux too. This eases the use of multiple windows of VSCode, while I dont have to use the taskbar in order to switch between the windows. 

This feature should create another tab bar showing all windows of vscode. Selecting a tab switches the window.

**Comment by bpasero** [comment]
@Hobart2967 shouldn't you convince Windows and Linux to provide this natively? I do not think VSCode should build this if the OS does not provide it otherwise?

Btw I think Windows was close to having it but then decided to not ship it: https://www.howtogeek.com/352109/how-to-use-sets-in-windows-10-to-organize-apps-into-tabs/
