### ISSUE TITLE
Wrong word order [Arabic] [RTL]

### ISSUE THREAD

**Issue by rofazayn** [microsoft/vscode#83429]
- VSCode Version: 1.39.2
- OS Version: Microsoft Windows [Version 10.0.18945.1001]

I am having a problem inserting Arabic in my code, example:

![Screenshot_1](https://user-images.githubusercontent.com/37586909/67680614-de7cc500-f98b-11e9-92af-0d658ffd44b8.png)

It should be: `مرحبا بك` not `بك مرحبا` my vscode is trying to render Arabic words the same way it renders Latin ones (Left to right). Although, the order of the letters is correct, but the order of the words is reversed.

PS: this only happened after the latest update.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexandrudima** [comment]
@rofazayn Can you please provide the text in a copy-paste friendly format?

**Comment by rofazayn** [comment]
> @rofazayn Can you please provide the text in a copy-paste friendly format? (the entire HTML file)

Sure

```<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="A firebase with redux application." />
    <title>My App</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>

    <p>مرحبا بك</p>
  </body>
</html>
```

And this is how vscode shows it:
![Screenshot_1](https://user-images.githubusercontent.com/37586909/67804223-d6597e00-fa8e-11e9-8dc0-3123e431168d.png)

**Comment by alexandrudima** [comment]
@rofazayn Thank you for the clipboard friendly text. I don't believe this to be a regression, I think what is interesting is that the "render whitespace" toggle influences the way the text is layouted:

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/67840277-c4f78c80-faf5-11e9-8a20-2c20758eec85.gif)

Since this is not a regression, but a feature request to better support Arabic, I would suggest that we track it in #11770 , which has a lot more upvotes.
