### ISSUE TITLE
Test: Git untracked files setting

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#83442]
Refs: #35480, #80083

- [x] anyOS @bowdenk7
- [x] anyOS @sana-ajani

Complexity: 3

There's a new `Git: Untracked Changes` setting which allows to treat git untracked files differently. You can now have them mixed (default), in a separate section or even hide them. Please try a bunch of git commands across all 3 values of that setting:

- Commit (it will automatically stage changes when none are staged, should behave according to setting)
- Stage All Changes (should behave according to setting)
- Stage All Tracked Changes
- Stage All Untracked Changes
- Discard All Changes (should behave according to setting)
- Discard All Tracked Changes
- Discard All Untracked Changes

**Comment by sana-ajani** [comment]
In the mixed setting, when I "discard all changes", the dialog message says the **untracked** file will be discarded but there is a button action to discard the **tracked** file instead of the untracked file. 

<img width="583" alt="Screen Shot 2019-10-29 at 10 52 49 AM" src="https://user-images.githubusercontent.com/9721254/67794669-44278a80-fa3a-11e9-939c-16504305afa1.png">

**Comment by sana-ajani** [comment]
Oh I was slightly confused...that's just a warning for if I were to discard all files.
