### ISSUE TITLE
Completing a rename after cancellation no longer successfully completes the operation in 1.40.0-insiders

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#83459]
This looks directly related to the fix here: https://github.com/Microsoft/vscode/issues/82146

This fix break the Rename feature in the C/C++ Extension, due to VS Code no longer accepting results after a cancellation.  We display UI to disambiguate symbols to be renamed.  VS Code will attempt to cancel the Rename operation if the users clicks in the editor, or clicks on an item in our tree view (which selects the associated content in the editor).  This was not an issue previously, as we could still complete the original Promise.  VS Code no longer accepts that completed promise.

Alternatively, we could display the disambiguation UI outside of the lifecycle of the Rename operation.  We could complete the initial rename request with no results then issue the final edits ourselves.  However, the fix made due to https://github.com/Microsoft/vscode/issues/82146 was unnecessary, as it was in response to functionality that was working as designed (see notes in that issue).  We would prefer to display the progress indicator when a rename operation is indeed still in progress.

Could we get the unnecessary fix in https://github.com/Microsoft/vscode/issues/82146 reverted?  Or, should we work around it?

**Comment by jrieken** [comment]
I believe that discarding an operation's results after cancelation is the correct thing to do. In the special case of #82146 even more so because it causes screen cheese with an out-of-context progress bar. We will not revert the fix for #82146. 

The rename-solo of the c/cpp extension has already been discussed with @bobbrow. The right thing to do here is https://github.com/microsoft/vscode/issues/77728 and you are invited to contribute.
