### ISSUE TITLE
Activity bar items should always focus on child elements

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#83483]
Currently if you activate the explorer sidebar when there is no folder/workspace open the focus isn't set to the `Open Folder` button. Additionally when an extension contributes a view that has no items (say the Bookmarks extension when you have no bookmarks yet), the focus isn't placed into the view.

Originally reported: https://github.com/microsoft/vscode/issues/83328

**Comment by misolori** [comment]
This is because the explorer doesn't focus on the child elements, like the other views, and the focus is on the activity bar element. Notice the focus border:

![image](https://user-images.githubusercontent.com/35271042/67604076-77fb6b00-f72f-11e9-90fa-9e0a645a39e0.png)

When in an empty explorer view, the focus should change to the "Open Folder" button.

**Comment by misolori** [comment]
GIF from @Guema:

![image](https://user-images.githubusercontent.com/8943532/68486571-a144ec80-0241-11ea-89a5-da5084f73b2d.gif)

**Comment by isidorn** [comment]
Yeah, makes sense that the no folder explorer gets focused in this case. I can look into this

**Comment by isidorn** [comment]
Fixed via 655e3b3e99
