### ISSUE TITLE
Perform terminal resizes synchronously

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#83558]
Version: 1.37.0-insider
Commit: f0058ed0d43dc58620abc65570719d06e1e67c76
Date: 2019-07-30T16:57:58.561Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.15.0-55-generic

Make sure there's enough space for 1 terminal, not 2:

![image](https://user-images.githubusercontent.com/4033249/67791604-f52b2680-fa34-11e9-8168-81c7ad76b1b0.png)

Split:

![image](https://user-images.githubusercontent.com/4033249/67791400-99f93400-fa34-11e9-8c9e-48ac20a42a95.png)

**Comment by Tyriar** [comment]
Can you share the output of `echo $PS1`?

**Comment by octref** [comment]
`\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$`

**Comment by Tyriar** [comment]
So things will never be perfect when resizing because of the way that shells reprint the prompt and sometimes resizing will insert lines that the shell doesn't know how to handle, for example in Terminal.app after resizing a bit:

<img width="574" alt="Screen Shot 2019-10-29 at 12 14 58 PM" src="https://user-images.githubusercontent.com/2193314/67801137-cbc6c680-fa45-11e9-92a8-f5ce0dadbfcc.png">

However I think we can do better than we are currently by making resizes synchronous, to do this we would need flow control (https://github.com/microsoft/vscode/issues/74620) and then do something like this when resizing:

1. renderer: Tell node-pty to block for a resize
2. node-pty: block the pty and resize
3. node-pty: Tell renderer that it's been blocked and resized
4. renderer: Ensure messages from pty have been parsed
5. renderer: Resize terminal
6. renderer: Tell node-pty to unblock

**Comment by ayyash** [comment]
not sure if my issue is related to that, when I split the terminal, the statements start piling up instead of appearing on the same line... have a look: https://drive.google.com/file/d/1u8tVLEcXXF2ckh4OvN55x1zggga9Dn7X/view

**Comment by octref** [comment]
No longer an issue for me. I'm not even sure now what exact behavior I'd be asking for. So closing.

**Comment by ayyash** [comment]
lucky you, it still does that on my end

**Comment by octref** [comment]
OK, I'll leave this open then

**Comment by Tyriar** [comment]
Here's one of the resize problems below.

Resize down:

<img width="126" alt="Screen Shot 2021-07-22 at 9 14 06 AM" src="https://user-images.githubusercontent.com/2193314/126672795-d247efc3-fe59-4341-adc1-9b98a70b5304.png">

Resize up:

<img width="412" alt="Screen Shot 2021-07-22 at 9 14 11 AM" src="https://user-images.githubusercontent.com/2193314/126672823-cf71ac9e-0b46-42b7-9e7d-b2a09ed98f75.png">

Incoming data from bash:

<img width="582" alt="Screen Shot 2021-07-22 at 9 15 06 AM" src="https://user-images.githubusercontent.com/2193314/126672878-3d13e94d-0be8-491b-b34f-259f6693b03e.png">

Resize events:
<img width="589" alt="Screen Shot 2021-07-22 at 9 15 43 AM" src="https://user-images.githubusercontent.com/2193314/126672955-d33190b4-4be3-42ed-884b-ccf3c9aed474.png">

**Comment by Tyriar** [comment]
In the above example it goes [K [A [A which is clear (bottom) line, move cursor up, move cursor up. xterm.js looks to be behaving as expected here.

Resizing Terminal.app by contrast ends up keeping the prompt on the same line which results in this. Might be because it's not unwrapping the lines?

<img width="364" alt="Screen Shot 2021-07-22 at 9 19 45 AM" src="https://user-images.githubusercontent.com/2193314/126673493-f54f0ec1-f8a2-42f4-823c-f1d70927e383.png">

**Comment by Tyriar** [comment]
I updated bash (3->5) and it didn't make a difference. I think this is acting as expected and we seem to do as good of a job if not better than other terminals.

I remember thinking Windows Terminal did a better job than us in this regard but that appears to only be when it's behind conpty in a Windows environment, when wsl is used it can really mess up easily as well.
