### ISSUE TITLE
Organize imports and formatters are conflicting due to a race condition

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#83586]
https://github.com/microsoft/vscode-python/issues/6933

This is not an extension issue though. 

- VSCode Version: 1.39.1
- OS Version: Windows 10

Steps to Reproduce:

1. Have Black installed
2. Set config options as such:

```json
{
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.organizeImports": true
  }
}
```

3. Create a python file with the following contents:

```py
from something import (
    aaaaa,
    bbbbb,
    ccccc,
    ddddd,
    eeeee,
    fffff,
    ggggg,
    hhhhh,
    iiiii,
    jjjjj,
    kkkkk,
)
```
4. Save the file multiple times and watch it dance

Does this issue occur when all extensions are disabled?: No

The problem is that there's a race condition  since there are two formatters being used when saving changes to a file. The results vary based on which formatter completes first. I.e. if black formats first, then you see one result, then isort formats the imports and changes the imports and you see another set of changes.
As you keep hitting save both trip on one another.

The Python extension wants to organize formatters and isort to be ran consistently, but we don't have control over that as VS Code is doing the excutions.

**Comment by baolsen** [comment]
I know this issue is closed but it is the closest I found to an issue I have with isort.
Did you have any setup.cfg files to configure isort?

I was struggling to get it to work with the setup.cfg files in my project directory.
isort -sp .\setup.cfg <file>
Produces a different sorting than if I use the editor's on-save formatting.

Looking at your description of this issue it is possible that it is actually using setup.cfg but the race condition is messing up my imports. 

In your journey with VSCode + isort did you find that it checked for and respected any setup.cfg file?

If not (or you are unsure) then at least I can open a new issue to be investigated.

**Comment by luabud** [comment]
@baolsen sorry I don't think I understand what you mean, this issue is open, not closed.

**Comment by pydolan** [comment]
@baolsen – I don't think the race issue is related to VS Code not reading isort settings from setup.cfg.  At least for me, I can consistently get import sorting to work as expected if I specify the settings file in my VS Code settings:
```
  "python.sortImports.args": [
    "--settings-path=/path/to/my/setup.cfg"
  ],
```

Why the above doesn't happen automatically is unclear to me, but that is for a different Issue.

**Comment by reywood** [comment]
@pydolan's suggestion did seem to make the behavior consistently correct for me. I recommend using the `${workspaceFolder}` var like so instead of hard coding a path.

```
"python.sortImports.args": [
    "--settings-path=${workspaceFolder}/setup.cfg"
]
```

As an aside, I also had to add `"editor.codeActionsOnSaveTimeout": 2000` to my config in order to extend the timeout beyond the default 750ms. Otherwise, my file was showing as unsaved after isort had sorted the imports. Seems like isort is taking more than 750ms to complete. See issue #72496 for a better description of the problem. This problem may only occur on larger projects.

**Comment by Spenhouet** [comment]
I really hope that this gets addressed soon. It keeps us from being able to sort imports on save.

This race condition leads to deleted or duplicated code. That feels quite significant to me for this issue to be fixed.

Code actions should run before the code formatter.
They should run strictly sequentially.

**Comment by Spenhouet** [comment]
@mjbvz The comments made by @baolsen @pydolan and @reywood seem to address an issue unrelated to this issue. For clarity: Can these comments be removed from this issue?

**Comment by mjbvz** [comment]
Here's what I see debugging this setup for JS/TS:

1. Organize imports is called. It returns a code action with a command: https://github.com/microsoft/vscode/blob/c0c9e0043ce6133042268f22847021ad9a1ce410/extensions/typescript-language-features/src/features/organizeImports.ts#L76
1. That command is then invoked and edits the document (making sure to await the result in the command) : https://github.com/microsoft/vscode/blob/c0c9e0043ce6133042268f22847021ad9a1ce410/extensions/typescript-language-features/src/features/organizeImports.ts#L55
- Then the formatter is called. At this point the formatter has the updated document that organize imports just changed

From this, it seems to me that VS Code calls things in the correct order and does correctly await the result of organize imports

@luabud  Can you please share a link to the python extension's implementation of organize imports?

**Comment by luabud** [comment]
I actually can't repro the race condition anymore, it's consistently organizing the imports first and then triggering the formatter. And it seems that if we wanted to change the order, we could do it in the extension side, so I'm closing this issue.

FWIW the code for sorting imports is here: https://github.com/microsoft/vscode-python/blob/master/src/client/providers/importSortProvider.ts

**Comment by Spenhouet** [comment]
I can very much still reproduce this. I just used the `settings.json` from above:

```
{
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.organizeImports": true
  }
}
```

and opened a random python file. Directly on the first one **it dances and deletes lines of code**.

I extracted these lines of code into an empty python file ans pressed STRG + S multiple times (nothing else):

![race_condition](https://user-images.githubusercontent.com/7819068/78188024-cf84cc00-746f-11ea-881b-0cd758dfbb42.gif)

**Comment by luabud** [comment]
@Spenhouet Oh that's weird! I can't repro this behaviour with the sample code you proved. I tried it with black, autopep8 and yapf. 

I opened an issue on the Python extension repo so we can investigate it  (https://github.com/microsoft/vscode-python/issues/10923), as it may not be due to a race condition.  It'd help immensely if you could fill up our bug report template there providing your environment information, the formatter you're using as well as the contents of the Python channel in the Output:

![image](https://user-images.githubusercontent.com/45497113/78198716-4f923e00-743e-11ea-9a79-f617338837ec.png)

**Comment by Spenhouet** [comment]
@luabud Sorry, I was mixing up issues. I was actually referring to this: https://github.com/microsoft/vscode/issues/90220

**Comment by copdips** [comment]
same issue here, the worst thing is that it even deletes some imports

**Comment by luabud** [comment]
@copdips do you see the import deletion behaviour consistently? I wasn't able to reproduce it.

**Comment by copdips** [comment]
@luabud 

Yes, as per the GIF in https://github.com/microsoft/vscode/issues/83586#issuecomment-607497052, it deletes imports. 
But I managed to find a workaroud from: https://github.com/microsoft/vscode/issues/90221#issuecomment-583664840 by using `source.organizeImports.python` instead of `source.organizeImports`

**Comment by Spenhouet** [comment]
@luabud I can reproduce this again with the following import:

```
from transform_data import (preprocess_continous_image, transform_image_parallelized,
                            weighted_majority_resampling)
```

![format_issues](https://user-images.githubusercontent.com/7819068/82044600-ebee6800-96ad-11ea-8da6-9e019d567c18.gif)

Maybe you could try if you can also reproduce it with that import.
Formatter is yapf.
