### ISSUE TITLE
Bad scrollbar rendering in Firefox windows

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#83592]
Testing https://github.com/microsoft/vscode/issues/83296

Manifests in terminal and extension description pages.

![image](https://user-images.githubusercontent.com/6561887/67815394-0f302d80-fa64-11e9-8f22-a0024c88bd00.png)

**Comment by bpasero** [comment]
I think the terminal is worse, so starting with that. I am not sure we can do anything about the iframe-based views (@mjbvz fyi - not sure you are embedding custom scrollbars).

**Comment by mjbvz** [comment]
Webviews use native scrollbars. Unfortunately Firefox doesn't support the css scrollbar styles we need (namely an equivalent to `-webkit-scrollbar`). However there may be a partial workaround now: https://stackoverflow.com/questions/6165472/custom-css-scrollbar-for-firefox/54101063#54101063

**Comment by connor4312** [comment]
Firefox 64+ supports a `scrollbar-color` property https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color

**Comment by Tyriar** [comment]
@mjbvz terminal is done and it looks pretty good, you can probably copy what is done there otherwise can you fork off the extension description/webview into a separate issue?

**Comment by mjbvz** [comment]
Thanks @connor4312 and @Tyriar for the tip about `scrollbar-color`!

I pushed a fix for webview too. Note that it doesn't exactly match webkit's scrollbar but it looks much better now

<img width="1123" alt="Screen Shot 2020-11-10 at 3 10 08 PM" src="https://user-images.githubusercontent.com/12821956/98744597-d610e580-2366-11eb-8c8a-5551ff6820aa.png">

Two known limitations:

- I haven't found a way to set the active / hover colors for the scrollbar thumb (the webkit specific css does allow this)
- The scrollbar always have rounded corners instead of being square (at least on MacOS)

**Comment by sbatten** [comment]
This is much better, but I notice that on Windows+FF, the scrollbars have arrows where they do not anywhere else in the product.

**Comment by mjbvz** [comment]
As far as I can tell, the standard css scrollbar properties do not give us that level of customization. Tentatively closing hidding the arrows as  `out-of-scope` but if anyone knows how to fix this, just let me know
