### ISSUE TITLE
Cannot edit search string effectively on Windows with up arrow

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#83644]
Open the search viewlet
* paste a string like `src/vs/base/common/buffer.ts`
* have the search viewlet be small such that the text wraps
* try to press up arrow to go up inside the string to reach its beginning and remove `src/`

![image](https://user-images.githubusercontent.com/5047891/67846466-91bafa80-fb01-11e9-967e-46113f66679f.png)

Observe that the up arrow does not move the cursor up, but changes the text input to the previous searched string.

**Comment by sashikanth1994** [comment]
The search text is in a single line so we don't expect the up arrow to work.

**Comment by alexandrudima** [comment]
@sashikanth1994 The search text is multiline, please see the screenshot, and the up arrow should work.

**Comment by alexandrudima** [comment]
Ok, now I see where the difficulty comes from... Perhaps the following could be done:
- when the selection changes, 
- only if the selection is collapsed,
- and only of the `<textarea>` is multiline (height can be checked),
- then [read the client rect](https://github.com/microsoft/vscode/blob/b7e9344c5de8d87d92751d9eef867b2a42d5f1c1/src/vs/editor/browser/viewParts/lines/rangeUtil.ts#L51-L64) and determine if it on the first or last line of text by comparing the rect with the <textarea> rect

Based on the above, set the context keys for enabling `up`/`down` to go through history...

**Comment by romainHainaut** [comment]
I could reproduce the exact same bug, so i will be looking if i can fix it

**Comment by romainHainaut** [comment]
Hey again, so i could find everything and know how to correct the bug but the only things i need to have is the height of the Search when it is one line to avoid hardcoding a value that only work for my spec. And i don't know where it is and if the Search height change from different spec.

Anyways here is how i will correct the bug:
So the bug is in this file: [https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/search/browser/searchWidget.ts#L83](url)
the current function only look for /n , so the equivalent of manually adding a line.
To correct just need to modify the line by
`if (textarea &&( isMultiline || textarea.clientHeight>THE_HEIGHT_OF_A_SINGLE_LINE) && textarea.selectionStart > 0) {
`
The some for the downward, has you can see i don't have "THE_HEIGHT_OF_A_SINGLE_LINE", in my case it is 24 but has previously said i don't know if it is for my spec or for everyone.

**Comment by romainHainaut** [comment]
Ok so after looking into the CSS file of the search widget i have fin that the maxheight value was the same has the value clientHeight return. As i dont master CSS i could play with the file to see if it was the same for the height but i assume it is (would be weird if the fonctionnality is diffirent). So i assume it is the same value for all spec.

So i have put the value 24 and commit.
I have debug for the up ward and down ward

I hope my assumption are right :)
