### ISSUE TITLE
Make sure that no parallelism has been eliminated by the "async/await" effort

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#83661]
Recently our Promise-based code has been rewritten to use lots of awaits.

Since there is a chance that this change has replaced (desired) parallelism by strict sequential code, this refactoring might have resulted in slower behavior.

(This problem has been observed in some other places in VS Code where Promise-based code was replaced by lots of awaits).

We should review all changes to make sure that no parallelism has been eliminated.

**Comment by isidorn** [comment]
I have reviewed all the changes that touched the `Promise.all` call which makes the promises run in parallel. And all 17 of them are still in place and the funcionality seems to be there.
Of course there might be other places where parallelism was eliminated, but these were the most highly suspects, and other places I suggest we treat as bugs if any appear. And I am confident the changes were good.

Due to the above I am closing this issue.

![Screenshot 2019-11-27 at 12 58 09](https://user-images.githubusercontent.com/1926584/69721764-d98b6c80-1115-11ea-8da2-94b01a4522ad.png)
