### ISSUE TITLE
Explorer icons show up briefly when resizing down

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#83726]
![icons](https://user-images.githubusercontent.com/2193314/67915291-c48bdf80-fb4f-11e9-808f-93919a1c2ec7.gif)

Version: 1.40.0-insider (user setup)
Commit: 31f577ec88dc96ad2028699fb597b19022224b46
Date: 2019-10-30T05:39:27.063Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by misolori** [comment]
Interesting, I think this is happening because the mouse is extending into the explorer area, causing it to trigger a hover event for the explorer (which shows the icons). @isidorn, we should probably set a condition to not show when a drag event is happening.

**Comment by isidorn** [comment]
This is not explorer specific but happens with all split views.
Forwarding to @sandy081 

And yes @misolori you are probably right, the mouse goes over the view triggerin the css rule to show the action in the action bar on hover.

**Comment by joaomoreno** [comment]
This applies to any hoverable element inside each splitview view: explorer action bars, debug breakpoint markers, line hovers, editor hovers, etc.

I've pushed a change which sets `pointer-events: none` in splitview views during sash resizes. cc @bpasero @sbatten for awareness, since it also affects the grid.
