### ISSUE TITLE
Markdown preview scrolling can be jumpy/jerky

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#83735]
- VS Code version: Code - Insiders 1.40.0-insider (31f577ec88dc96ad2028699fb597b19022224b46, 2019-10-30T05:39:27.063Z)
- OS version: Windows_NT x64 10.0.19013

![markdown-scroll](https://user-images.githubusercontent.com/641685/67920315-28c39900-fb7a-11e9-8e54-622627f26e02.gif)

**Comment by mjbvz** [comment]
Please share the markdown source

**Comment by eamodio** [comment]
@mjbvz 
https://github.com/eamodio/vscode-gitlens/blob/master/README.md

It also happens on the vscode release notes

**Comment by mjbvz** [comment]
Minimal repo:

```md
- **Remotes** &mdash; lists the remotes in the repository
  - Provides the name of each remote, an indicator of the remote's direction (fetch, push, both), remote service (if applicable), and repository path
    - An inline toolbar provides quick access to the _Fetch_, and _Open Repository on Remote_ (if available) commands
    - A context menu provides access to more common repository and remote commands
    - Each remote expands to list its remote branches
      - See the **Branches** above for additional details
```

**Comment by eamodio** [comment]
@mjbvz I still see the issue with the same file -- specifically around images and tables.

**Comment by mjbvz** [comment]
There will always be some jumping with images (and a few other md elements). The reason is that the text for an image in an `.md` file takes up ~20px of vertical space while in the hover it may take up the entire viewport. Does that explain what you see?

The problem I fixed with this bug was the as you scrolled through the file, it would sometimes jump backwards slightly and then go forward again
