### ISSUE TITLE
Telemetry seems disabled in Preferences, but still used

### ISSUE THREAD

**Issue by mariusa** [microsoft/vscode#83754]
- VSCode Version: code-1.39.2-1571154220.el7.x86_64
- OS Version: Fedora

Steps to Reproduce:

1. Disable telemetry in preferences
2. Restart 
3. Help > Open process explorer
4. See process running with --enableTelemetry

![Screenshot from 2019-10-31 14-54-23](https://user-images.githubusercontent.com/1283842/67948622-c8bb0a00-fbee-11e9-8cc5-fae78a8a3366.png)
![Screenshot from 2019-10-31 14-57-04](https://user-images.githubusercontent.com/1283842/67948623-c953a080-fbee-11e9-8928-f337a63e6e7e.png)

**Comment by IllusionMH** [comment]
/duplicate

See comment https://github.com/microsoft/vscode/issues/79703#issuecomment-524512338 for more details.
TL;DR; tsserver sends telemetry events only back to VS Code which respects telemetry settings and doesn't post them anywhere.

If you are sure that this issue is closed by mistake - let maintainers know with more details.
