### ISSUE TITLE
Disabling console.debug.wordWrap strips newlines and whitespace

### ISSUE THREAD

**Issue by rjgotten** [microsoft/vscode#83753]
- VSCode Version: 1.39.2
- OS Version: win 10 1803

**Expected Behavior:**
The debug console stops automatically inserting linebreaks to fit messages to screen width.
The debug console *does not* remove linebreaks and any other white-space that may already be present in the log messages.

**Actual Behavior:**
It just strips everything, including what was already present in the log messages itself.

**Steps to Reproduce:**

1. Disable debug console line wrapping using the `console.debug.wordWrap` setting introduced for https://github.com/Microsoft/vscode/issues/72210
2. Restart VSCode to apply the setting.
3. Load up and debug an ASP.NET Core solution.
4. Note that in the debug console all newlines inside a single log message are now removed. (And it also seems to strip atleast leading whitespace.)

**Does this issue occur when all extensions are disabled?**
Can't verify. Above reproduction needs the Omnisharp extension installed.

**Comment by jamesgregson** [comment]
I see this behaviour with the Python extension as well so it seems more general than ASP.NET.

Here's a minimal example case, set a breakpoint where indicated and debug to reproduce:

````python
string_to_print = '   this   is   a   string   to   print'
print( string_to_print )

print('set breakpoint here')
````

'Debug Console' output is:

````
this is a string to print
````
while 'Terminal' output is correct:

````
   this   is   a   string   to   print
````

I don't think this is specifically an issue with 'debug.console.wordWrap' since it occurs regardless of the value of that setting.

VSCode: Version: 1.40.0
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Python: 3.5.2
Ubuntu 16.04

Unfortunately it makes debugging numerical code nearly impossible since numpy arrays all print as a single line, regardless of dimension and number of elements. Ironically the debug.console.wordWrap feature is why I upgraded to get unwrapped printing of large arrays.

Cheers and thanks for all your work on this great tool!

**Comment by isidorn** [comment]
@jamesgregson thanks for the nice steps. I have pushed the fix to vscode insiders and you can try out in tomorrow's vscode build. 

To verify, `debug.console.wordWrap:false` and debug the following nodejs program and make sure the string is correctly rendered in the debug console
```
var string_to_print = '   this   is   a   string   to   print'
console.log(string_to_print);
```
