### ISSUE TITLE
Markdown viewer headings ignored

### ISSUE THREAD

**Issue by john-goodrich-allegion** [microsoft/vscode#83763]
Issue Type: <b>Bug</b>

If there is no space after a heading (#, ##, ###, etc.) definition, the Markdown Viewer doesn't recognize the heading an shows the # characters.  In-panel view of .md files in Azure DevOps handles this properly.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.17763

**Comment by IllusionMH** [comment]
I think that VS Code uses markdown-it which follows CommonMark spec which in turn [requires space](https://spec.commonmark.org/0.29/#atx-headings) is required between `#` and content.

It's not that "Azure DevOps handles this properly" but implementation may vary because there is no single standard. CommonMark is an attempt to standardize this syntax.

Headings with spaces are safe bet (should be parsed correctly independently of implementation) so its easy to make 1 time conversion and stick to it.

If support is really needed - most likely it should be an extension that uses  [markdown-it-lazy-headers](https://www.npmjs.com/package/markdown-it-lazy-headers) package. See https://github.com/markdown-it/markdown-it/issues/240 for more details (however GitHub now requires space).
