### ISSUE TITLE
Allow text-based exclusion of problems

### ISSUE THREAD

**Issue by tfenster** [microsoft/vscode#83775]
As described [here](https://code.visualstudio.com/updates/v1_23#_problems-view-filtering) we can include and exclude files from the problems view. However the text search in the problems view only allows inclusion. It would be nice to have exclusion there as well, e.g. something like `!"abc123"` would hide everything with the text `abc123`

**Comment by aninditkarmakar** [comment]
@sandy081 - I would like to tackle this issue. Do you have anything for me before I start?

**Comment by aninditkarmakar** [comment]
@sandy081 - I submitted a PR for this feature. With this addition, the user can do text-based exclusion by having the filter string begin with "@!".

**Comment by tommai78101** [comment]
@aninditkarmakar May I ask why it needs to have both "@!" characters? Would it be possible to use 1 character, regardless if it's a hyphen, exclamation mark, or a caret symbol?

**Comment by aninditkarmakar** [comment]
@tommai78101 - the reason why I chose"@!" was because when we do a [Ctrl]+[Shift]+[O] in the text editor, VSCode opens up the 'Go to symbol in file...' dialog box and the search string there begins with "@".

To keep consistency with that, my reasoning was that the added "!" to the "@" would denote the opposite of filtering by searching for a string in the Problems list.

The added benefit of using "@!" as the starting symbol is that I don't think the user would need to use escape characters in the search string that follows the "@!". (But maybe I'm missing something here? The problems list would most likely not have any strings that start with @! anyway.)

**Comment by tommai78101** [comment]
@aninditkarmakar No, it's because I thought you're adding the functionality to this filter here in versino 1.40.2

![image](https://user-images.githubusercontent.com/6444116/70681625-f8d3df00-1c69-11ea-8d02-3883b514e286.png)
