### ISSUE TITLE
when i save auto go to last line

### ISSUE THREAD

**Issue by ABU-HASANm** [microsoft/vscode#83804]
Sir, i am a new user in this editor, 
Really its a very nice editor, live server and other extension is really great, 
But, sir 10-31-2019 i have a problem , the problem is when i save my desing auto go to html closing tag. that's mean.
<html>
<body>
 <div> wirte something</div>( if now i save auto go to last line)
</body>
</html>

sir, plase halp me what can i do now.

**Comment by gjsjohnmurray** [comment]
Can you reproduce the issue after [disabling all extensions](https://code.visualstudio.com/docs/editor/extension-gallery#_manage-extensions)? If not, re-enable each one in turn until you find the one causing your problem.

If it still happens when all extensions are disabled, add information about your VSCode version and platform. The About box gives you this.

**Comment by ABU-HASANm** [comment]
Tnx sir for halp me
