### ISSUE TITLE
Window doesn't retain location and moves down on subsequent launches in Linux

### ISSUE THREAD

**Issue by sprite-1** [microsoft/vscode#83880]
Issue Type: <b>Bug</b>

As you can see from the GIF below, whenever I close VS Code and then open it again, it moves the position lower and lower until it finally covers my dock instead of sticking to the last window position I closed it at.

![Screen record from 2019-11-03 07 48 26-min](https://user-images.githubusercontent.com/33685433/68078332-e5ce2380-fe0e-11e9-9768-125934bf56ea.gif)

As you can expect, this is really annoying because I have to move t up every time when it shouldn't be occurring in the first place.

I don't have a multi-monitor setup either.

VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:33:40.634Z)
OS version: Linux x64 4.15.0-66-generic

Extensions: none

**Comment by bpasero** [comment]
VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

Reading this issue, it seems to originate not from VSCode itself but rather one of these upstream components. As such, in order to resolve it, it would need to get fixed in the upstream component. I will go ahead and close this issue and kindly ask to report this issue to the upstream component if possible:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
