### ISSUE TITLE
Minor: default split editors and split terminals do not align

### ISSUE THREAD

**Issue by warpdesign** [microsoft/vscode#83890]
- VSCode Version: 1.39.2
- OS Version: macOS Catalina

Steps to Reproduce:

1. Split editor
2. Split terminal

Both should split at the same position (ie: both left editor and left terminal should have the same with by default).

![image](https://user-images.githubusercontent.com/199648/68085640-58f18d00-fe43-11e9-8c01-323c3a34c5c2.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by usernamehw** [comment]
Aren't your theme just missing border?

**Comment by sbatten** [comment]
@usernamehw great eyes :)

@warpdesign, the "border" you are seeing in the editor is actually the left edge of the scrollbar. the theme you are using doesn't define a border for editor groups and that's why you are seeing what looks like misalignement.

Add the following to your settings.json to see the actual borders lining up. 
```
"workbench.colorCustomizations": {
	"editorGroup.border": "#ff0000",
	"terminal.border": "#ff0000"
}
```

![image](https://user-images.githubusercontent.com/6561887/68233597-519dc100-ffb4-11e9-9741-072675273360.png)
