### ISSUE TITLE
Debug console stop listening output

### ISSUE THREAD

**Issue by itsnuba** [microsoft/vscode#83906]
- VSCode Version: 1.39.2, 1.40.0-insider
- OS Version: Windows 10.0.18362

Suddenly the debug console stop listening to output changes, restarting application, vs code, OS didn't help.
I suspect it related to "Clear Console" button in the debug console windows, since as far as i know the problem starting after i click it.
Im developing dart 2.5.0 application, using aqueduct 3.0.0 which using dart isolate (which may be contributing to the issue)

Steps to Reproduce:
1. Init aqueduct default project
2. When i start the debugging (using f5) only the first row is displayed on debug console:
![image](https://user-images.githubusercontent.com/13597103/68104457-b3572000-ff0d-11e9-8a02-bc1c90719355.png)
3. After invoking something in debug console, console, the rest output will be shown:
![image](https://user-images.githubusercontent.com/13597103/68104548-0f21a900-ff0e-11e9-98e5-162c29de54ad.png)
4. Any later output will not be shown until you triggering debug console, or stopping debugging process.

For sanity check, i try manually running the application via terminal, using `pub run ./bin/main.dart` and it seems running normally.

Edit:

When application outputing error 'debug console' able to immediately show the message. Maybe it's related to what message is send to output.

**Comment by itsnuba** [comment]
Its seems, that closing "debug console" panel, than open it again also updating the output in "debug console"

**Comment by Sen-real** [comment]
@mjbvz : 
I have the same problem with 1.39 too.  It doesn't reproduce with 1.38.1.

In my code, I send [output events](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Output) to VS Code. After triggering a breakpoint, VS Code debug console stops updating. 
If I switch to "Terminals" window, then switch back to "Debug Console" window, all missing messages show up.
The problem happens on OS X. It also happens on Windows that is used via. Remote Desktop.

**Comment by Sen-real** [comment]
Hi, @mjbvz and @isidorn ,

I have similar problem with 1.39 too.  It doesn't reproduce with 1.38.1.

In my code, I send [output events](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Output) to VS Code. After triggering a breakpoint, VS Code debug console stops updating. 
If I switch to "Terminals" window, then switch back to "Debug Console" window, all missing messages show up.
The problem happens on OS X. It also happens on Windows that is used via. Remote Desktop.

**Comment by DanTup** [comment]
I just discovered this too (after some time of debugging my extension assuming I've broken it, since I recently added output buffering!).

I'm logging when I sent `OutputEvents` like this:

```ts
protected logToUser(message: string, category?: string, colorText = (s: string) => s) {
	console.log(`Sending ${JSON.stringify(message)} to ${category}`);
	const output = new OutputEvent(message, category);
	this.sendEvent(output);
}
```

And they show up in the Chrome dev tools console, but not in the VS Code Debug Console. As mentioned above - switching to the terminal and back causes them to appear. This seems like a fairly serious regression in the current stable build @isidorn.

![Screenshot 2019-11-11 at 10 30 35 am](https://user-images.githubusercontent.com/1078012/68580506-6a075300-046e-11ea-9522-fbdbdd52742b.png)

**Comment by whlkw** [comment]
we also hit the issue too in version 1.40.0

**Comment by isidorn** [comment]
Based on the comments. Seems to be only happening with dart.
@dantup can you please create a reproducable sample with Mock Debug so I can reproduce this on my machine and investigate further into this issue. Concise repro steps without aqueduct would be great. Thanks

**Comment by DanTup** [comment]
@isidorn I tried to make a small repro but could not - I think timing may be a factor, but I'm not sure exactly what the implementation of this looks like.

I don't believe this is specific to Dart, @Sen-real mentions having this problem in his extension above too (and some of the other commentors might not be using Dart, they didn't say).

**Comment by Sen-real** [comment]
@isidorn and @DanTup : I'm not working with Dart. My extension works with my debug adapter exe, which communicates with VS Code via STD IN / STD OUT. As debug adapter isolates debugee from VS Code, it could be reproduced with any kind of language running on debugee.

Hope this could be helpful to identify the source of this regression - VS Code Debug Console will refresh on time, as long as the message text to print ends up with '\n'.

**Comment by itsnuba** [comment]
I could reproduce using while loop returning output to console with interval (using vscode 1.40.0), [https://github.com/itsnuba/vs-dart-issue](url)
i could reproduce the issue in different machine using this method, but not using different language (i've test it in nodejs)

this only affecting debugging using f5, there is no issue directly running the script using terminal.

Maybe like @Sen-real said, it has something todo with how dart debugee comunicate with vs, but im sorry, im lacking expertise in this matter to test it further.

**Comment by DanTup** [comment]
@isidorn here's a simple repro using Mock Debug:

https://github.com/DanTup/vscode-repro-83906

The code change is just inserting this:

```ts
setTimeout(async () => {
	this.sendEvent(new OutputEvent("\none"));
	await new Promise((resolve) => setTimeout(resolve, 1000));
	this.sendEvent(new OutputEvent("\ntwo"));
	await new Promise((resolve) => setTimeout(resolve, 1000));
	this.sendEvent(new OutputEvent("\nthree"));
	await new Promise((resolve) => setTimeout(resolve, 1000));
	this.sendEvent(new OutputEvent("\nfour\n"));
	await new Promise((resolve) => setTimeout(resolve, 1000));
	this.sendEvent(new OutputEvent("five"));
	await new Promise((resolve) => setTimeout(resolve, 1000));
	this.sendEvent(new OutputEvent("\nsix"));
}, 2000);
```

Open a `.md` file, place a breakpoint somewhere (to stop the process exiting when you run), hit run, and you'll see `one`/`two`/`three`/`four`/`five` all appear at once instead of 1 second apart, because they're not rendered until the first output event that ends in a newline. Switching to the Terminal and back to Debug Console will then cause `six` to appear.

**Comment by isidorn** [comment]
@dantup Thanks for the nice repro steps. I was able to reproduce and fix the issue.
You can try vscode insiders tomorrow which should have the fix. Thanks a lot!

**Comment by DanTup** [comment]
@isidorn will the fix require that the message start with a newline? Although I used that as an example, I can't make guarantees about the output events since they come from an external process which could send whatever characters it wanted chunked however it wants - (for example there could be newlines in the middle of messages, or even none at all)?

**Comment by isidorn** [comment]
No, the fix does not require that the message starts with a newline.
The fix should work for all output events. Thanks

**Comment by DanTup** [comment]
Ok great, I must've read too much into the change :) I'll test in insiders tomorrow - thanks!

**Comment by isidorn** [comment]
No, you were on a good track. Just the change consists of two parts
Make sure to split if new entry starts with \n and make sure to fire change event if we append (which we were not doing previously)

**Comment by DanTup** [comment]
@isidorn thanks! The buffering is fixed, however now there are unexpected newlines. In the source there is exactly one newline between each message, but the output in Insiders looks like this:

![Screenshot 2019-11-21 at 8 23 58 am](https://user-images.githubusercontent.com/1078012/69320057-5c08bd80-0c38-11ea-8ec2-799ad680a7d0.png)

Because the data is coming from an external process, we can't ensure that the output events will have newlines in any particular place, so I think it's important VS Code doesn't add new ones. This might mean VS Code needs to append an OutputEvent into an existing line if there was new newline sent at the end of the previous one or the start of the new one?

**Comment by isidorn** [comment]
@dantup thanks for letting me know. I had word wrap disalbed in the debug console and thus I did not see this one.
However I have pushed a fix now. You can try it out tomorrow and let me know. Sorry about that

**Comment by DanTup** [comment]
Great, will do - thanks!

**Comment by DanTup** [comment]
Fix looks good (with and without newlines), thanks!

**Comment by isidorn** [comment]
Thanks, adding verified label
