### ISSUE TITLE
Debug: Improve Call Stack UI/UX

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#83986]
Sorry for creating this kitchen sink issue... :cry: 

A few UX issues in the current Call Stack view:

- It's hard to differentiate between launch targets and stack frames, since both render with exactly the same font family and style and they all have a grey label on the right hand side. We can maybe explore different font styles and/or icons.
- It's hard to understand that `Load More Stack Frames` is an action. We should definitely not use a row's click handler for representing this action. We should instead drop the row click handler and simply render a clickable button in that row, a la Explorer's `Open Folder` button.
- The `async` separators should not take the same height as a regular row. They can be much shorter and draw a separator much like what `@:` does in Quick Outline.

![Screenshot from 2019-11-05 15-16-24](https://user-images.githubusercontent.com/22350/68215316-4e6bfa80-ffdf-11e9-93cc-5b02f09853e8.png)

cc @misolori

**Comment by isidorn** [comment]
Thanks for the nice feedback. Let's assign to November so wee see what we can improve.
fyi @weinand @roblourens

**Comment by isidorn** [comment]
Will not have time this milestone, thus pushing out to December.

1) Different font styles might look ugly. Icons might help. How I currently easily differentiate is via the expando. @misolori let me know what you think and if you have ideas for icons fonts that might help here
2) This makes sense, we can render it as a button. The explroer open button might be a bit too strong (since that button begs to be clicked upon, and the Load More Stack Frames is something optional)
3) Yes. They can have smaller height and draw a separator left and right of the label. However the quick outline is not a good example for this imho. We would do this for StackFrames that have a `presentionHint = label` Which should be fine based on how we define this proprety [here](https://github.com/Microsoft/vscode/blob/bee5357bedae47c11a631eacaa59a05e4dc4508c/src/vs/workbench/contrib/debug/common/debugProtocol.d.ts#L1541)

![Screenshot 2019-11-29 at 11 01 03](https://user-images.githubusercontent.com/1926584/69860958-922ce980-1297-11ea-8f1e-bbcfc9e923fd.png)

**Comment by isidorn** [comment]
Not a fan of a strong blue button (picture 1)
What might work is a less strong gray one (picture 2) - note that we do not use this style of button anywhere atm. And also take into account there may be multiple of these buttons for multi thread debugging.
I actually do not mind the current solution that much.Since it is not noisy.

@weinand @roblourens @connor4312 @misolori let me know what you think about the load more icon. And if you have ideas what we could use as an Icon to be rendered in front of the session in the call stack view to diferentiate the sessions.

![Screenshot 2020-03-13 at 18 05 17](https://user-images.githubusercontent.com/1926584/76643409-40158880-6555-11ea-9e67-3ddff8348480.png)

![Screenshot 2020-03-13 at 18 10 24](https://user-images.githubusercontent.com/1926584/76643822-1d37a400-6556-11ea-92e4-8216580efe9f.png)


To tackle 3. I have reduced the height of deemphasized elements and I think it looks neat (in the picture timeout is 12px high comparing to the normal 22px)

![Screenshot 2020-03-13 at 18 20 26](https://user-images.githubusercontent.com/1926584/76644871-245fb180-6558-11ea-83b2-4d5736c0db91.png)

**Comment by roblourens** [comment]
I think the gray button looks disabled. A blue button which is not full-width might be fine. But I always thought the current experience is okay too.

The row height doesn't seem like a big deal? But it might be easier to see the impact of the change if you show it in a narrower view with text directly above and below it.

**Comment by misolori** [comment]
We do have https://github.com/microsoft/vscode/issues/58399 that proposes a secondary button color that we can implement for this:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/76771055-ffd42700-675b-11ea-89eb-d1163c325196.png" >


Thoughts on using a regular link? Could look simpler:

<img width="50%" src="https://user-images.githubusercontent.com/35271042/76771031-f8148280-675b-11ea-886b-685b3670e9ba.png">

**Comment by isidorn** [comment]
Regular link + Non verbatim font looks sexy. Great idea.
Also we will go with the Bug icon for debug session thanks to @weinand and @misolori ideas
I think the bug icon works because it is only displayed there if you are stopped -> thus it means you are debugging and not running

![image (1)](https://user-images.githubusercontent.com/1926584/76791689-bae2db80-67c1-11ea-9d0a-34f5b82d6ced.png)

**Comment by misolori** [comment]
One thing we might want to extend the icons for is when clustering call stacks appear as it can get quite messy. In Joao’s post above, imagine that multiplied with a cluster. Wondering if makes sense to add an additional one for each cluster?

**Comment by isidorn** [comment]
@misolori each cluster is actually a subsession so there should be some structure to help with the clutterted content. Also each subsession would also get a bug icon.
Let's go with the current proposal and if needed we can optimise the display of subsessions.

**Comment by isidorn** [comment]
Thanks for great feedback. Here's the final solution

![Screenshot 2020-03-17 at 11 19 05](https://user-images.githubusercontent.com/1926584/76846841-6f701200-6841-11ea-878a-b534e412a6a1.png)

Alternative design with using the activity bar icon

![Screenshot 2020-03-17 at 11 16 11](https://user-images.githubusercontent.com/1926584/76846877-7d259780-6841-11ea-968c-e0642fda18fe.png)

**Comment by isidorn** [comment]
Take note that we use a smaller height now for presentation hint = label, to save on vertical space and becasue it looks nicer.

@roblourens @connor4312 please note that I also changed the Show More action to be aligned with the Load MOre Stack Frames, so now it is blue and centereted

![Screenshot 2020-03-17 at 11 36 37](https://user-images.githubusercontent.com/1926584/76848249-a9daae80-6843-11ea-9be7-00b6f7969e76.png)

**Comment by weinand** [comment]
@isidorn 
- I still prefer the bug icon for debug sessions
- the monospaced font used for the function names on the left hand side of the stack appears to be smaller than the font of the source location on the right hand side.
With this the line spacing on the left hand side looks unnecessarily large in comparison to the spacing on the right hand side.

**Comment by isidorn** [comment]
@weinand agree, bug icon is good.
For the second point, we could increase the font on the left hand size. If I increase it by 1 it looks a bit ugly imho. Also then it is not aligned with all the other debug trees - where we use the same font / font size. Changing the font size might have other ripple efects.
I am open for suggestions.

![Screenshot 2020-03-17 at 11 51 48](https://user-images.githubusercontent.com/1926584/76849447-b6f89d00-6845-11ea-9355-01fc89ada97c.png)

**Comment by weinand** [comment]
I've merged the two images so that they can be compared:

![76847916-1bfec380-6843-11ea-8bde-8c55da5609ee](https://user-images.githubusercontent.com/1898161/76852930-ad266800-684c-11ea-87c4-d025e7971db6.png)

IMO the bottom image is more balanced, the spacing is better, and the function names get more emphasis.

But I agree, we should use the same font size everywhere.
An alternative to increasing the font size would be to make the spacing smaller...

@misolori what's your verdict?

**Comment by misolori** [comment]
- I agree that the bug icon looks better than the alternate
- The title should always be at least the same size, if not higher. I think the problem we run into here is that the `font-family` is different for the title and filename. The title uses monospace (which can appear larger) and the filename is the system font. I would maybe try to make the filename a little smaller to match the heights of the others:
![image](https://user-images.githubusercontent.com/35271042/76869040-f2cf3a80-6824-11ea-9ea3-07ca303bd505.png)


- The background row hover on the load more + labels feels out of place, we should probably hide it:
![image](https://user-images.githubusercontent.com/35271042/76868978-dfbc6a80-6824-11ea-9052-ba37a60f1a28.png)

**Comment by isidorn** [comment]
1) Ok, going with the bug
2) I tried this on my machine and not impressed with the results. Due to how it looks with the rest of the workbench. Since we use the same font size everywhere, and this would be the only location where we use a smaller font
3) This makes perfect sense, I was also thinking about this, however the tree does not support this ATM, and I would not like to do a CSS hack. Due to that I have created this feature request against the Tree and once we have that we can look into this https://github.com/microsoft/vscode/issues/92872
