### ISSUE TITLE
FR: Make VSCode's configuration more amenable to traditional build systems

### ISSUE THREAD

**Issue by anatolyburakov** [microsoft/vscode#84001]
In many IDE's supporting traditional build systems such as Make/CMake/Meson etc., the configuration, build and debug steps are often inextricably linked, such that for each configuration, there may be different debug steps.

Yet, currently VSCode does not support this mode of operation, and assumes that "build" is a simple step (or a series of interlinked simple steps) that has only one path to follow. My use case is working on an open-source project that supports two different build systems, which have two completely different configure/build/debug steps, as well as multiple architectures support.

With the above in mind, it is a hassle to use VSCode's build/debug tasks because all of them are visible at once. I cannot "select a configuration" and have predefined build/debug steps that i can run seamlessly; instead, i have to pick the correct "Configure" task, followed by picking the correct "Build" task every time, followed by picking the correct "Debug" task every time.

It would be nice if VSCode had an option to act more like a traditional IDE would, where it would be possible to bundle together Configure/Build/Debug tasks. I can't really think of a nice way to implement that on top of existing infrastructure, but one way to do that would've been to 1) have an actual "configure" step (as opposed to lumping it in with build tasks), and 2) have multiple tasks.json files (e.g. "tasks.config1.json", "tasks.config2.json", etc.), which the user could "switch" to and use only tasks defined in those files, and ignore the rest (aside from maybe the global one).

**Comment by weinand** [comment]
"Debug" already supports to have "preLaunchTasks" and "postLaunchTasks". In addition Debug allows to have multiple configurations that the user can "switch" to. So I do not see anything actionable for Debug.

**Comment by alexr00** [comment]
@weinand I think for debug this mean the user selects exactly one "build + debug configuration" then starts it. 

Could this be done in an extension? The extension could have configurations file, which associates "configuration labels" with tasks and launch configs. From the tasks side, this is possible with the existing API since you can enumerate all tasks with `fetchTasks`. Such an extension could provide UI to set the current configuration and provide a "run" button which kicks it all off.

**Comment by weinand** [comment]
There is specific [debug API](https://github.com/microsoft/vscode/blob/4ec6717139357f3e96c51ddd8d5ef601af31f737/src/vs/vscode.d.ts#L9207-L9215) for contributing debug configurations dynamically if the "launch.json" is missing. But this does not easily support to swap-in/out debug contributions from an existing "launch.json" based on some other configuration.

However, since debug configurations are just "settings" (see Configuration API), it is possible to create an extension that swaps debug and tasks configurations based on a "select a configuration" action.

**Comment by alexr00** [comment]
Ok, it sounds like this is doable in an extension, which I think is where it belongs as it is more of an IDE feature than an editor feature.
