### ISSUE TITLE
Increase available tab area

### ISSUE THREAD

**Issue by ali80** [microsoft/vscode#84010]
Area to show currently opened tabs is small and can get even smaller since VSCode allows some of its own functionality as well as third party extensions to use this precious tab space. 
so GIMME MY TAB AREA BACK

![image](https://user-images.githubusercontent.com/6554605/68244328-d840b580-0029-11ea-9f67-7a11b7805ab7.png)
above nearly 50% of tab area is used by other things

1. add option to block all extensions from using tab space (the area used only by tabs)
2. shift sidebar title down, or remove it all together to provide more tab space

**Comment by mmzoo** [comment]
I would also like to point out that when icons are added dynamically based on the file type (such as split pane or show git history), the tabs jump around depending on the number of icons .

![tabs](https://user-images.githubusercontent.com/1029840/74744147-0311eb00-5262-11ea-98e1-626c8c37114f.gif)

This happens when every tab is assigned the same horizontal space using "`workbench.editor.tabSizing": "shrink"`. When the available space changes, all tabs change their size accordingly.

**Comment by alkaliphile** [comment]
I got rid of most of that junk by installing the Customize UI extension and adding this to my settings.json:

```
"customizeUI.stylesheet": {
  ".editor-actions": "display: none !important;",
  ".tabs-and-actions-container > .monaco-scrollable-element": "{ height: auto !important; }",
  ".tabs-and-actions-container > .monaco-scrollable-element > .tabs-container": "{ height: auto !important flex-wrap: wrap; }"
},
```

**Comment by KevKeating** [comment]
This looks like it's pretty similar to #46403.
