### ISSUE TITLE
Improve discoverability of 'Restart Frame'

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#84045]

**Comment by isidorn** [comment]
Currently we show the restart frame in the context menu when the debug adapter supports the restart frame request.
However we show this on every stack frame in the call stack. For node I get an error whenever I try to execute this command on any stack frame that is not top level.

1. Should we show this action only on the top stack frame? Since it does not make a lot of sense to me that a user can restart any other stack frame than the top


How to improve its discoverability? My idea is the following:
* Similar to the inline thread and session actions in the call stack view, we would on hover and focus render a restart icon. It would be rendered instead of line and column infomation. In case we go down this approach we would could use our old restart icon, or a new one to distuingish that this does not actually restart the whole program. So the icon should have a meaning of "mini restart" @misolori 

Let me know what you think @weinand @roblourens @connor4312

**Comment by connor4312** [comment]
Showing it on hover makes sense to me. My once concern would be accidentally clicking it since it's a new clickable area that shows up only on hover. Maybe having the icon to the left of the location would be less likely to have misclicks.

Being in or beside a stack frame the standard restart icon conveys the message to me. Or alternately something like this would also work:

![image](https://user-images.githubusercontent.com/2230985/69258447-7461d500-0b71-11ea-9fea-8b35745ad6db.png)

**Comment by isidorn** [comment]
Fancy design skill and a good idea. 
Let's see what others have to say. New icon, or old icon + hover text explanation

Having the action left of the tree item is not really aligned with what we do in other parts of our UX (open editors being the only exception). And I am not worried about people accidently clicking on it, since that area is not really clickable so far (why would a user click there)

**Comment by misolori** [comment]
This is merely for illustration purposes, but something like this?

![image](https://user-images.githubusercontent.com/35271042/69288371-3afb8a80-0bae-11ea-88e0-e805befd8f06.png)

**Comment by isidorn** [comment]
@misolori that is pretty awesome

**Comment by isidorn** [comment]
I have pushed a change to show the restart frame icon on hover and on row focus. When the adapter does not support restartFrame action everything behaves as before. So on hover no change

Some follow up work:
1. @misolori once we have a new icon can you just update the codicon used [here](https://github.com/Microsoft/vscode/blob/8f02213d4e6cbd917c0079bad2ddd536a3484e2f/src/vs/workbench/contrib/debug/browser/callStackView.ts#L501)
2. @weinand @roblourens @connor4312  can we decide if we need this action for not top stack frames. In theory this makes sense, however I am not sure if debuggers can support this in practice
3. @misolori once I focus on the action, it jumps up a bit. And stays vertically not centered. I believe this is nothing special for this icon, but a general codicon action bar issue. Can you look into this ( I can also create a new issue)

Try it out and let me know how you feel about it. Thanks!
I had an alternative solution where I would just hide the line numbers for the action but after discussion with @weinand we decided on the curren solution

![restartFrame](https://user-images.githubusercontent.com/1926584/69355324-e0cbf980-0c81-11ea-8c9b-eef90bd1f3fc.gif)

**Comment by connor4312** [comment]
It looks like the chrome devtools can, so in js-debug/PWA we may be should to restart frames anywhere in the current stack. But with async stack traces we won't be able to restart frames that happened on a different stack that the current one (even though it's displayed as the 'same' call stack in the UI).

I think it would make sense for a 'restartable' flag to to be annotated on breakpoints sent back down the DAP.  And other languages might only be able to restart the top stack frame / only be able to restart under certain conditions.

**Comment by misolori** [comment]
Icon is now in via https://github.com/microsoft/vscode/commit/b24775ae6dd719148a299d325466dbec3db0c4cf:

![image](https://user-images.githubusercontent.com/35271042/69359074-cae81580-0c3c-11ea-9bf3-cec0ae584cec.png)

**Comment by isidorn** [comment]
Thanks @misolori 
Let's close this one for now. And we can create follow up items.
@weinand would you like me to create a new issue for the "restartable" discussion?

**Comment by isidorn** [comment]
Verifier: start debugging and verify that when you hover over a call stack item you see the restart frame icon. Clicking on it restarts the frame (note that Node only supports restartgin the top frame currently)

**Comment by jrieken** [comment]
Verified tho I have noticed that this makes the call stack view quite nervous - I believe that's because the hide the filename and line/column information on hover

**Comment by isidorn** [comment]
Yes, the view is now more nervous. I could show this with a timeout. However we do not do this in other views. Open to suggestions.

**Comment by jrieken** [comment]
Would it be possible to not have either or but to have the restart button push the details to the left?

**Comment by isidorn** [comment]
Makes sense. Created a follow up item for this https://github.com/microsoft/vscode/issues/86248
