### ISSUE TITLE
I cannot register a shortcut for editor.unfold

### ISSUE THREAD

**Issue by aymericbouzy** [microsoft/vscode#84051]
- VSCode Version: 1.39.2 (also reproduced with insider)
- OS Version: Darwin x64 19.0.0, macOS 10.15.1 (19B88) (Catalina)
- keyboard configuration: AZERTY (french)

Steps to Reproduce:

1. open keyboard shortcuts
2. search for "unfold"
3. `editor.unfold` is missing from suggested choices

<img width="1136" alt="Screenshot 2019-11-06 at 14 48 56" src="https://user-images.githubusercontent.com/8168981/68303964-2d6ddd00-00a5-11ea-95ea-eb6545cded49.png">

Does this issue occur when all extensions are disabled?: Yes

I want to be able to configure a keyboard shortcut for the `editor.unfold` action : is it expected that it is not available when searching for unfold in the keyboard shortcuts section?

Possibly related:
* https://github.com/microsoft/vscode/issues/24054
* https://github.com/microsoft/vscode/issues/1240

**Comment by aymericbouzy** [comment]
Using `Preferences: Open Keyboard Shortcuts (JSON)` allows me to set the shortcut, and once set, it does show up in the search results. So the issue is only related to search I assume.

**Comment by sandy081** [comment]
I could see it

![image](https://user-images.githubusercontent.com/10746682/68399572-e05a3b80-0176-11ea-8d3e-ce0201a506a9.png)

Are there any specific steps you are following that I might be missing?

**Comment by aymericbouzy** [comment]
Are you using an AZERTY keyboard?

**Comment by aymericbouzy** [comment]
It doesn't look like it, regarding the keybinding you have for the command : the `]` is not available on mac AZERTY keyboards.

**Comment by sandy081** [comment]
Assigning to @alexandrudima as it is related to keyboard layout

**Comment by alexandrudima** [comment]
@sandy081 

Our default keybinding for unfold (`cmd+option+]`) cannot be mapped under the French keyboard layout. That is OK because our default keybindings are optimized for the US keyboard layout, and it is not always possible to map them to a keybinding on a different keyboard layout. That is OK. Improving the default keybindings for other languages is tracked in https://github.com/microsoft/vscode/issues/1240.

---

I think this bug is more about the fact that the search in the Keybindings Editor does not render actions without a keybinding. If the search string is empty, then actions without a keybinding are rendered.

**Comment by aymericbouzy** [comment]
@alexandrudima I think you nailed it 👍

**Comment by SillyFreak** [comment]
It's not just the search (at least not filtering the Keyboard Shortcuts). Also in the complete list, Fold/Unfold did not appear for me.

I'm using a QWERTZ (German) keyboard, and added both keybindings manually in the JSON editor. Scrolling to "Unfold", for example, shows it. Removing the keybinding from JSON makes the whole line disappear. The search box was empty at that time.

**Comment by sandy081** [comment]
This is not rendered in the editor because this command can take args and currently commands with args are not shown - 

https://github.com/microsoft/vscode/issues/84072
