### ISSUE TITLE
Cannot resize VS Code anymore

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#84134]
This is a regression and I personally find the new min size very annoying. I often like to resize VS Code and make it small, especially when taking screenshots.

I used to be able to resize VS Code, e.g.:

![image](https://user-images.githubusercontent.com/5047891/68396552-07623e80-0172-11ea-99a2-9559155babb6.png)

Now I cannot get anything smaller than this:

![image](https://user-images.githubusercontent.com/5047891/68396607-1fd25900-0172-11ea-86ac-e1987ea94197.png)

**Comment by sbatten** [comment]
resulting from https://github.com/microsoft/vscode/issues/78165

/cc @joaomoreno @bpasero

**Comment by eamodio** [comment]
Yeah, I don't mind the min width, but the min height seems too big imo.

**Comment by sbatten** [comment]
@alexandrudima @eamodio would 400px height be acceptable?

**Comment by alexandrudima** [comment]
I have tested on my machine and even 300px height lays out correctly. I would suggest the smallest number that still has a correct layout... Also keep in mind that #78165 was not real user feedback, it was a test assignment, and those issues are sometime not realistic, i.e. it was us testing corner cases that might never happen in the real world intentionally...

**Comment by sbatten** [comment]
While #78165 was a test issue, it was not the first time I have had an issue filed that resulted from unrealistic window sizes. The current min may be too large but the previous size was not realistic. though you can just say just don't make it that small, making a sensible minimum imo avoids the product looking unpolished.

**Comment by sbatten** [comment]
Additionally, the width is usually the problem dimension, the min height was chosen because it felt small enough at the time but doesn't suffer as much.

**Comment by alexandrudima** [comment]
I have a 4K monitor and Windows is configured at 200% scale:
<img width="200" src="https://user-images.githubusercontent.com/5047891/68463305-a3418800-020e-11ea-99e7-d0e6a08b8046.png"/>

I don't think necessarily a minimum is a bad idea, but the current value, or the bug in Electron + the current value results in IMHO unacceptable effective minimums. 

Here is the smallest I can make VS Code on my machine:
![image](https://user-images.githubusercontent.com/5047891/68463414-da179e00-020e-11ea-9fec-464ecb4d9d04.png)

**Comment by sbatten** [comment]
Totally agree @alexandrudima ... I would like to use your perspective to find the right number. 400px would be just over 1/3 of your display height at that scaling. I think the current value is so bad because it is over half the display height which harms tiling users. 350px, while a strange number is very close to 1/3 which feels like a good target portion of the screen.

**Comment by dlewis-ald** [comment]
This issue is more sevear if you have multiple monitors with mixed DPI settings. The min-height is calculated from the HDPI monitor, that when I move to the low DPI screen, I can not reduce the height to fit on one monitor (see picture)

![screenshot](https://user-images.githubusercontent.com/22496454/68464144-01b73800-0208-11ea-9176-05abe3b1b1a1.PNG)

The screenshot above shows a monitor at above another, with the low DPI on top.

**Comment by sbatten** [comment]
We are tracking the mixed dpi issue separately but it is indeed on top of mind at the moment.

**Comment by sbatten** [comment]
Updated the insiders build to have minimums of 600 by 270. This is the minimum size that makes a re-connection dialog look correct still.

**Comment by sbatten** [comment]
I put this in November but technically the fix is attached to the candidate issue for recovery.
