### ISSUE TITLE
Minimap - highlight all instances of selected word

### ISSUE THREAD

**Issue by stiegi** [microsoft/vscode#84151]
When you doubleclick and select a word, all instances of this word should be highlighted, not just the selected word itself.
Right now you'd have to press CTRL+F and use the search functionality, but the highlighting of other instances should show up in the minimap the moment you selected the word.

Already discussed in #20853

**Comment by alexandrudima** [comment]
fyi @RMacfarlane

**Comment by chavlji** [comment]
It would increase productivity for sure!

**Comment by engineerbaraazakariya** [comment]
This feature is good and useful but I hope it can be done on all minimaps of splitted views so we can check if a word is in other splitted view or not as we select it in any of views, i.e. I am checking the used/not-used classes, so I open the html file side by side with the scss file to check if a class in css is used in html by selecting and highlighting it in scss file side and them scroll the html for any highlight then the class is used else not used, I am using an extension for this, while if the minimap already show highlights on the other side then there won't be a need to scroll from top to bottom of the all other views if needed, this feature would be very appreciated.
Thanks for the great MS.Code I am using it since the beginning

**Comment by Callendor** [comment]
I would love to see this feature as well.

**Comment by kenma9123** [comment]
I just shifted from sublime to vscode, so far all the features I want is still there thanks to plugins. But this one is missing hope to see it soon.

**Comment by stinos** [comment]
This is *the* missing feature from the minimap for me, I'm so used to it from Subime Text that I use it often (e.g. for quickly finding references: double-click on word, all occurrences get clearly highlighted in minimap, just scroll). Alternatives for VSCode currently are selecting word then Alt-F3 to select all occurrences of Ctrl-F to seach occurrences, since selections and search results are shown in minimap, but that's extra work. (also, VSCode highlights complete lines instead of matches only, but that's some other issue I think?)

**Comment by VelocityRa** [comment]
Is this possible in Visual Studio?

**Comment by dan0705** [comment]
This is a missing feature which I really need.

**Comment by raphaelquast** [comment]
... any updates on this? is it going to be implemented any time soon?

**Comment by Goldman1337** [comment]
are there any plans to implement this?

**Comment by utajum** [comment]
Yeah, cmon dudes, it's been like 4 years

**Comment by debdude** [comment]
if you need it today, see https://marketplace.visualstudio.com/items?itemName=mde.select-highlight-minimap

**Comment by stinos** [comment]
The screenshot shows highlighting in the sidebar though, not the minimap?

**Comment by Santinell** [comment]
> The screenshot shows highlighting in the sidebar though, not the minimap?

Right, this plugin don't show highlighting in minimap, and this is sad ((

**Comment by utajum** [comment]
Looks like the job was 99% done.

Let's hope it gets merged. 🤞

**Comment by stiegi** [comment]
> Looks like the job was 99% done.
> 
> Let's hope it gets merged.

It is incredible that only 6 lines of code were missing! Really hope they will merge this soon!

**Comment by dannyxnda** [comment]
I saw the pull request was merged to `main` but still wonder when we can use that. Can't wait to have this feature.

**Comment by stiegi** [comment]
> I saw the pull request was merged to `main` but still wonder when we can use that. Can't wait to have this feature.

You can already use it in the insiders version. I guess it will be part of their next release, in the beginnig of October. In the Insiders version the color of the markings is a light grey, I still could not figure out how to customize the new minimalSelectionHighlight key though

**Comment by stiegi** [comment]
FYI, it works great in the insiders version, except for html files. In html files, if you mark for example an opening tag, only the closing tag is marked too. If you mark an html attribute, nothing else is highligted in the minimap even if other html tags also do have that attribute.
I tested js, ts, tsx, css and vue files - workes great and as expected there. HTML files however - not so good.

**Comment by alexdima** [comment]
That is because `html` has semantic highlighting support, which wins over the (weak) built-in textual based highlights. In the case of `html`, the language has found useful to highlight the matching open-close tags, and not all tags of the same type.

**Comment by stiegi** [comment]
I understand, thank you for clearifying!
