### ISSUE TITLE
VSCode sorts text in xml tags incorrectly

### ISSUE THREAD

**Issue by AndrewRayCode** [microsoft/vscode#84157]
- VSCode Version: 1.40.0
- OS Version: Sierra

Paste this code into a new editor:

```xml
<members>Some_String</members>
<members>Some_String_Long</members>
<members>Some_String_Long_Er</members>
```

command-a and sort lines ascending, it incorrectly reverses the order

Now paste in this code:
```
Some_String
Some_String_Long
Some_String_Long_Er
```

command-a and sort lines ascending. the correct sort order is preserved

I don't think this is a dupe of https://github.com/Microsoft/vscode/issues/48123 ?

**Comment by alexandrudima** [comment]
I agree this is super weird, but that is what v8 does:

This can be executed in nodejs/Chrome/FF as well
```js
function sort(lang, letters) {
  letters.sort(new Intl.Collator(lang).compare);
  return letters;
}

console.log(sort('en', ["<members>Some_String</members>", "<members>Some_String_Long</members>", "<members>Some_String_Long_Er</members>"]));
// ["<members>Some_String_Long_Er</members>", "<members>Some_String_Long</members>", "<members>Some_String</members>"]

console.log(sort('en', ["Some_String", "Some_String_Long", "Some_String_Long_Er"]));
// ["Some_String", "Some_String_Long", "Some_String_Long_Er"]
```

What is very interesting is that I can reproduce this in Firefox as well, so I guess that is just how sorting is defined for the English language?

I also don't see what else we should do on our side. We must use the `Intl.Collator` in our implementation to sort lines, in order to pick up the OS locale and use the rules of the OS language.

See also https://github.com/microsoft/vscode/issues/70920#issuecomment-546405072

If you feel strongly about this, then please open an issue directly against v8 at https://bugs.chromium.org/p/v8/issues/list and link to it here.
