### ISSUE TITLE
Add more functionality to the "vscode.workspace.fs" API.

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/vscode#84175]
I'm working on using the new "vscode.workspace.fs" API in the Python extension.  There are some things we do for which we'd like to use the new API, but it doesn't provide the needed functionality.  I'll list them here, but would be glad to open a separate issue for each if that would help.

* `chmod()` - currently using node's `fs.chmod()` #84513
* `lstat()` - currently using node's `fs.lstat()` #84514
* `createWriteStream()` - currently using node's `fs.createWriteStream()` #84515
* ~`statSync()` - currently using node's `fs.statSync()`~ #84518
* ~`readFileSync()` - currently using node's `fs.readFileSync()`~ #84518
* `mkdirp()` - currently wrote a wrapper around the new `createDirectory()` #84516
   * was using fs-extra's `mkdirp()`, but could have used node's `mkdir()` with the "recursive" option set to true
* `mkdtemp()` - currently using ["tmp"](https://www.npmjs.com/package/tmp) (`tmp.file()`), but could have used node's `fs.mkdtemp()` #84517
* ~`glob()` - currently using ["glob"](https://www.npmjs.com/package/glob)~
* ~probably others~

(Also see #84177 for possible bugs in the new API.)

**Comment by jrieken** [comment]
* ~~`chmod()` - currently using node's `fs.chmod()`~~ dupe of https://github.com/microsoft/vscode/issues/73122
* ~~`lstat()` - currently using node's `fs.lstat()`~~ dupe of https://github.com/microsoft/vscode/issues/71204
* `createWriteStream()` - currently using node's `fs.createWriteStream()` -> we have some [proposed api](https://github.com/microsoft/vscode/blob/1d60909d1f273d3a4fdbfaba656048856057d36f/src/vs/vscode.proposed.d.ts#L89-L96) but nothing is final yet. @ericsnowcurrently What is the used for? Real big files or just because?
* ~~`statSync()` - currently using node's `fs.statSync()`~~
* ~~`readFileSync()` - currently using node's `fs.readFileSync()`~~ Our design/architecture prohibits anything sync here. This will not happen. 
* `mkdirp()` - currently wrote a wrapper around the new `createDirectory()`
   * was using fs-extra's `mkdirp()`, but could have used node's `mkdir()` with the "recursive" option set to true
* `mkdtemp()` - currently using ["tmp"](https://www.npmjs.com/package/tmp) (`tmp.file()`), but could have used node's `fs.mkdtemp()`
* ~~`glob()` - currently using ["glob"](https://www.npmjs.com/package/glob)~~ - use [`findFiles`](https://github.com/microsoft/vscode/blob/58479e80ab899402283b522da173c34867d7c78f/src/vs/vscode.d.ts#L8262)
* probably others

**Comment by jrieken** [comment]
@ericsnowcurrently for the future: **one ask -> one issue**.

**Comment by ericsnowcurrently** [comment]
Sorry about that, @jrieken.  I've opened separate issues for the various items.
