### ISSUE TITLE
Mac OS touch bar

### ISSUE THREAD

**Issue by luannguyend86** [microsoft/vscode#84189]
Issue Type: <b>Bug</b>

Hi Vs Code Team,
Have just update to the latest version: 1.40.0
It seems the touch bar issues when debugging is returned after fixed by previous one.
Have to use the mouse to click on the control button instead.

Please help :(.

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:09:34.601Z)
OS version: Darwin x64 19.0.0

**Comment by bpasero** [comment]
> It seems the touch bar issues when debugging is returned after fixed by previous one.

@luannguyend86 can you explain exactly what the issue is?

**Comment by eedwards-sk** [comment]
I'm having a sudden issue with the touch bar, as well, maybe the same?

The "Run / Run Debug" buttons used to always be visible.

Now, they're only visible if I put focus into the navigation bar (e.g. the folder view). The moment my focus is on the editor (any open file), it switches back to "suggested words" in the touchbar, which are not only completely irrelevant, but disrupts the workflow.

**Comment by luannguyend86** [comment]
@bpasero  thanks for replying,

The issue is the debugging navigation buttons (Step in,...) on the touch bar does not appear automatically once a breakpoint is hit. I can only Step in... by using the navigation on the screen with the mouse clicking. After clicking somewhere on the navigation bar on the screen, the buttons will appear on the touch bar but will disappear once you clicking somewhere else on the screen (ex: text editor,..)
I believe that the previous version (sorry, cannot remember correctly version number) of VSCode has no that issues.

The step to reproduce maybe:
Attach to progress for debugging and try to get a breakpoint is hit
- Expect: the debugging navigation buttons is displayed on the touchbar 
- Actual: there is no any navigation button is displayed on the touchbar, it would be displayed once using mouse to click on the debug navigation bar on the screen

Hope that help giving more information.

**Comment by isidorn** [comment]
Yes I can reproduce this issue. The problem is when focus is in the Editor the Debug touch bar items are not visible. When anything else is focused in VSCode all is good.

Looking at the code [here](https://github.com/Microsoft/vscode/blob/8013616a328d760a68a6cf84df7813e614beb418/src/vs/workbench/electron-browser/window.ts#L116) it seems like we update the whole `touchBar` menu when the active editor changes.
Since we also updated to Electron 6 last milestone by guess would be that when we update the touchbar based on the active editor change the timing is off and the touch bar menu gets disposed somehow (since it is empty).

Unfortunetly I do not have a mac with a touch bar to try out this theory and my touch bar simluator does not work.
@bpasero did we do some changes in this area except Electron 6 adoption?

**Comment by bpasero** [comment]
@isidorn make sure you have the latest version of the simulator installed, possibly it does not run in Mojave without update.

Also, Jo now has a macBook with touchbar, Alex too.

**Comment by bpasero** [comment]
I am not sure there is a timing issue involved, keep in mind that the renderer sends data to the main side for updating touchbar, so the update was always async already before.

**Comment by Alexzanderk** [comment]
I have the same issue!

**Comment by canpoyrazoglu** [comment]
This bug is also occuring on 1.40.1. On 1.39, it was working perfectly while debugging.

**Comment by luannguyend86** [comment]
The issue seems disappeared after upgrading to version 1.40.2.
Thanks VSCode team for the fixing.
I will now close the tickets

**Comment by roblourens** [comment]
Doesn't look like there were any changes here, removing from the milestone, reopen if it should be open @isidorn

**Comment by isidorn** [comment]
This works fine now, I can no longer reproduce.
