### ISSUE TITLE
Tooltip Does Not Go Away

### ISSUE THREAD

**Issue by rmorshea** [microsoft/vscode#84208]
# Summary

- VSCode Version: 1.40.0
- OS Version: Ubuntu 18.04.3 (GNOME 3.28.2)

Steps to Reproduce:

I never seem to be paying close enough attention to catch exactly when it happens (I must be typing or not paying attention to where my mouse is), but here's my best guess:

1. Hover over something
   - A file from the explorer maybe? Though the location of the tooltip in the example below doesn't seem to be from the file explorer.
2. Wait until tooltip pops up
3. Unsure of this step...
   - maybe wait till computer sleeps (could explain why I never seem to catch it)
   - switch to new window
4. Sometimes the tooltip will persist
5. It goes away
    - sometimes when I switch back to vscode
    - always, *but temporarily* when entering the "activities" menu
    - sometime requires restart (the below example required a restart)

Does this issue occur when all extensions are disabled?: Not sure

# Screenshot

![bad-tool-tip](https://user-images.githubusercontent.com/4041990/68453637-ff72c080-01aa-11ea-9c79-50f1daafb8cd.gif)

**Comment by bpasero** [comment]
VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

Reading this issue, it seems to originate not from VSCode itself but rather one of these upstream components. As such, in order to resolve it, it would need to get fixed in the upstream component. I will go ahead and close this issue and kindly ask to report this issue to the upstream component if possible:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
