### ISSUE TITLE
input cannot focus when switching webview

### ISSUE THREAD

**Issue by roguexiaohuihui** [microsoft/vscode#84216]
Issue Type: Bug
I created a webview with just an input tag in it, and I just asked input.focus()

1、The first time you open the webview you can focus properly
![image](https://user-images.githubusercontent.com/22930711/68458508-f5e66880-023d-11ea-8601-7fa23123085e.png)
2、Switch to another document or webview
![image](https://user-images.githubusercontent.com/22930711/68458606-2c23e800-023e-11ea-941c-e94c1ffa965d.png)

3、So let's go back to the first step, the webview，the focus is gone，just click the mouse down the webview and the focus will work

VS Code version: Code 1.39.0 
OS version: Windows10

**Comment by mjbvz** [comment]
I can't repo in the current insiders builds (1.41). Please share the example extension

**Comment by roguexiaohuihui** [comment]
> I can't repo in the current insiders builds (1.41). Please share the example extension

https://github.com/roguexiaohuihui/input-focus

**Comment by roguexiaohuihui** [comment]
when switching webview, the plug-in transmits a signal to webview through message and actively asks the input of webview to focus again. Instead of the input being focused after the mouse click on the screen

**Comment by roguexiaohuihui** [comment]
@mjbvz I hope you can take a look at this problem when you are free

**Comment by mjbvz** [comment]
There are are few different issues here:

- The example extension calls `this._update();` which reload the webview every time the focus changes.
- However even if you fix that, the bug still exists. 
- I then pushed a fix for this issue, but that fix only work with iframe based webveiews
- It is not fixed for normal electron based webviews. The root problem is that we see the following sequence of actions when switching focus:

    - The extension's focus message is received by the extension's JS
    - This focuses the input element
    - Our `host.onMessage('focus', () => {` event handler is then invoked 
    - At this point, the `document.activeElement` is now pointing to the wrong element (it's not on the input element anymore). 

Since this works fine with iframe based webviews, I assume there is some weird electron specific behavior going on here. I can't track down who is setting the focus here between the extension code running and `host.onMessage` running

I'm going to close this issue since we have not seen many other reports of it. Hopefully it will be fully fixed on desktop VS Code by #83188
