### ISSUE TITLE
Debug Toolbar Shown Immediately

### ISSUE THREAD

**Issue by jaqra** [microsoft/vscode#84228]
- VSCode Version: 1.40
- OS Version: Windows 10

~~This happened after upgrade to 1.40~~

Actually i am not sure. __I realized after upgrade to 1.40__

_Could be behind as position before_ 😕 

Steps to Reproduce: Press F5 when no .vscode folder

![vs](https://user-images.githubusercontent.com/48099350/68462811-5f567f00-021e-11ea-8bef-4bdc6b302997.gif)

**Comment by isidorn** [comment]
This is not a regression and we were behaving like this for maybe a year.
The issue being is wheter to show the debug toolbar in the initalisation phase or not.
Some users want to see it as soon as they click the play button to get feedback (you can search for older issues regarding this).
Some users like you do not want to see it imediattly.

In the case you are presenting it is clear the toolbar should not be shown, however we do not distuingish between mulitple initialisation phases.
A proper fix would probabyl be to introduce multiple initialisation phases which I do not plan to do this milestone, thus pushing out of this milesont
@weinand feel free to assign back if you are passionate about this.

**Comment by weinand** [comment]
@isidorn yes, VS Code has this behavior for quite some time.

But the the behavior is ugly. Especially because you can already stop the session by pressing the stop button but the drop down menu but doesn't go away.

**Comment by isidorn** [comment]
The downside of not showing the debug toolbar as soon as the user starts debugging is that it is impossible to stop a long running prelaunch task by clicking on the stop action. Yes the user could execute it via command palette / keyboard shortuct but it does not work that nicely.

What I propose is the following:

1. We only show debug toolbar once debug started sucessfully (preLaunchTask done and so on)
2. As soon as user starts debugging while we are in the INIT phase (preLaunchTask is running) we replace the start action in the debug viewlet with STOP. So users can cancel preLaunchTask
3. As soon as we have properly started we show the start again - so users can start additional sessions

As a result this looks something like

Alternative idea: instead of replacing actions in Debug View Bar use a progress notification bottom right, which the user can cancel.

@weinand @connor4312 let me know what you think

![recording](https://user-images.githubusercontent.com/1926584/90648830-4e6d7c00-e23a-11ea-90aa-3101fb34246c.gif)

**Comment by isidorn** [comment]
Since there was no negative feedback I decided to push this to insiders so we try it out and get feedback.

**Comment by weinand** [comment]
Showing regular progress notification for the preLaunchTask (after some delay) seems to be the best way to allow for cancellation. Repurposing another debug UI for this, feels a bit strange...

**Comment by isidorn** [comment]
@weinand I also like that approach with the progress notification. Let me present in the standup and we can decide then.

**Comment by weinand** [comment]
I've verified that QuickPicks (which includes "input" prompts) are closed when a debug session is stopped.
