### ISSUE TITLE
Maybe Odd Behavior or the Norm When mispelling Python in Execution of code.

### ISSUE THREAD

**Issue by RobFosterNYC** [microsoft/vscode#84229]
When I type in for example: 
C:\Code Files\Project Files>py myFileNameHere.py
instead of:
C:\Code Files\Project Files>python myFileNameHere.py

Another IDE interpreter opens wanting to open the specific file I just typed in VS-Code.
A bit odd I believe.  I dont know if this is normal behavior, so I thought I would report it.
Also:
Seriously, its getting really annoying having to constantly type 
python  (then the name of the file).py
Even though im working in Python, its annoying having to constantly type python to execute something.

- VSCode Version:
Version: 1.40.0 (system setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5

- OS Version:
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:
type this:
1.  py myFileNameHere.py
instead of this:
2. python myFileNameHere.py

Executes and launches a different IDE in the system,
if you have a different IDE installed such as JetbBrains PyCharm.

**Comment by Tyriar** [comment]
It sounds like `py` is installed by PyCharm or something as a shortcut to open it there? If I don't think we can't do anything about this.

cc @DonJayamanne

**Comment by RobFosterNYC** [comment]
But its being triggered from within Visual Studio Code.
Is there anything I can turn off in VSC that would prevent this from triggering outside applications such as PyCharm ?
Just curiously asking  :)

**Comment by DonJayamanne** [comment]
Unfortunately the python extension doesn't trigger such a thing. Please remember what you type in the terminal is out of the control of the extension. If the same problem exists outside VSCode, then it's caused by an external application. In this case it sounds like you may have installed something in the global path (py) that launched pycharm or the like.
You might want to try to uninstall that.

Please note, `py.exe` is a Windows launcher for python. Again the extension isn't in control of this.
