### ISSUE TITLE
Find All Implementations: shows even a single result as collapsed

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#84222]
![image](https://user-images.githubusercontent.com/172399/68460836-1942f080-0209-11ea-8b7d-c9d02c2e30f0.png)

In general we should probably stop this auto collapsing in search results and defer this to the user.

**Comment by jrieken** [comment]
Yeah, that's bug. Most likely because don't find the current result. Note tho that for perf reasons we cannot expand all notes here. It's different from search which computes the preview has its result, here we only have locations (uri+position) and need to load each and every file on expand.

**Comment by egamma** [comment]
>Yeah, that's bug. Most likely because we don't find the current cursor position in the results.

yes, it doesn't always happen. On the line linked below, when executing a 'Final All Implementations' for `config` then the result is expanded, when doing this for `getParseDevContainerAuthority` then the node is collapsed.

https://github.com/microsoft/vscode-remote-containers/blob/145797abd6e417d9426d785085691ee3583b2850/src/extension.ts#L281

**Comment by jrieken** [comment]
I put my money on this: When updating the tree we try to reveal [`model.first()`](https://github.com/microsoft/vscode-references-view/blob/db6dcec8ef4228597aef0f093d14df54d3254a58/src/extension.ts#L94) but its implementation always tries to find an item in the model at which [search started](https://github.com/microsoft/vscode-references-view/blob/db6dcec8ef4228597aef0f093d14df54d3254a58/src/model.ts#L98) - since we now have the shortcut (e.g not showing the definition when there is only a single reference) this isn't always true anymore... I will push a fix
