### ISSUE TITLE
Can we present multiple search results on the same line more effectively?

### ISSUE THREAD

**Issue by JK-mber** [microsoft/vscode#84234]
This is a duplicate of an issue #31817 closed in 2017 due to high rendering times and apparently being "out of scope". I am confused by this UX issue on a daily basis. 

Would you consider reopening and considering this issue? - If not, is there any possibility of casting a vote on it, to see if it could be considered at a later time?

**Comment by NotWearingPants** [comment]
> I am confused by this UX issue on a daily basis
+1

But I would also be interested to discuss more solutions.

The trivial UX solution would be to add a setting that would control if matches on the same line appear as such in the search viewlet.
To me that will also confuse some times, for example when counting the matches manually (maybe because I got more results than I wanted and need to filter them manually).

So I propose that this optimization should be reflected in the UI, perhaps with an icon next to the contracted search result indicating it is actually more than one.
Also a button that would expand the search result into the multiple results it really is (next to the X button on hover), because I sometimes want to initially see contracted results, and expand those I am interested in. Maybe also two buttons on the top to "expand all" and "collapse all", but for matches in the same line (like the existing buttons for collapsing file results).

**Comment by roblourens** [comment]
I think that what you really want is something like https://github.com/microsoft/vscode/issues/23931. The current search view is not a good place for reading code or seeing multiple matches on one line, it's only intended to show you that there is a match, so you can open the file to actually read your code.

FYI @JacksonKearl
