### ISSUE TITLE
Typescript task provider slow

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#84278]
With 0.140 I am now getting warnings that the Typescript Task Provider is slow.  I don't use typescript, so why it this happening? How to I disable the Typescript Task Provider?

**Comment by alexr00** [comment]
This warning is intended to help you disable any task providers you don't care about that might be slowing down your Run Build Task or Run Task command.
You can disable the typescript task provider with 
```
	"typescript.tsc.autoDetect": "off"
```
Or, you can disable the warning for typescript with the setting: 
```
	"task.slowProviderWarning": [
		"typescript"
	]
```

Finally, if you really truely do not want _any_ task providers to run and only want tasks from your tasks.json, then you can do
```
	"task.autoDetect": "off"

```

If there is a task provider you want to keep using but it often shows this notification, you could reach out to the extension author (which could be VS Code since we have built in task providers for typescript, gulp, grunt, and npm) and see if there is something that can be done to speed it up.

**Comment by alexr00** [comment]
@mjbvz it's interesting that the typescript task provider would be slow if there isn't any typescript. On a different note, I've noticed that if typescript is showing the "initializing typescript" message in the status bar then the typescript tasks take a "long" time to compute too.

**Comment by mjbvz** [comment]
As part of TS task resolution, we attempt to find the `tsconfig` for the active file. To do this, we ask the typescript server but the server may be busy for several seconds while it is initially loading. This means that can end up taking several seconds for us to respond to `provideTasks`.

I'll add a timebox to the tsserver request to fix this

**Comment by DanTup** [comment]
I just hit this too. This feels like a weird fix - VS Code warns when something is slow, so it ends up just being cancelled. What if the user wants to run a TS task? I'd much rather wait with some progress indicator and have it work than have it just fail. Some people have slower machines and are more likely to hit this - it seems really frustrating to be told "your machine is running so slow that rather than wait for the thing you want to finish, we just aborted it".

I understand VS Code wants to be fast, but what's the point of being fast if you're not doing the job required?

I'm not saying don't prompt the user if things are slow so they can disable them - but I don't think extensions should start implementing short timeouts just to avoid showing up in VS Code warnings.. If this is happening for a typical MS-made extension, maybe the warnings are a bit aggressive?

**Comment by alexr00** [comment]
The timeout is currently 4 seconds. I can up it to 7 if you think it's appropriate, but ideally the typescript extension would be faster.

**Comment by DanTup** [comment]
> ideally the typescript extension would be faster

Sure, but presumably here it's hitting the file system and the extension code is also sharing a single thread with other extensions (of which many may all be activating/starting up at the same time, which may - rightly or wrongly - include sync fs access). This introduces a lot of variability. I think the best UX is to tell users when things are slow and let them cancel and/or disable them, not abort them automatically. There's nothing worse as a user than waiting for something and then it being terminated as taking too long - what if it was only 10ms from finishing? Any arbitrary timeout is going to fire for some users at some point where they'd have preferred to wait and gotten the correct results/behaviour.

When investigating reports of "Extension causes high CPU" I found that some users had fs access taking over 1s to do a few `fs.exists` checks that took less than 10ms on my MacBook. That's a very significant difference.

FWIW, my complaint isn't about how quickly the warning is shown - just the behaviour of things being cancelled just because they're taking a few seconds - however the former may encourage the latter. The priorities seem wrong - performance is important, but not at the expense of breaking things. TS aborting scanning for tasks when it's likely to succeed seems crazy - sometimes things take longer than usual. Automatic timeouts should be for catching things that are broken, not just running a little slowly.

(I'm only one user, don't feel obliged to change anything - I just wanted to provide some food for thought 🙂)

**Comment by mjbvz** [comment]
The fix only timeboxes the typescript server request. This request is only one way we find the tsconfigs in your project to generate task for. We do not timebox the other ways (which use a file system check instead of the server). In most cases—but not all—the two return the same config file. The timebox lets us return a result that is mostly correct in a consistent amount of time. You should usually not notice any difference in actual results 

Let me know if you don’t see that happening as expected

**Comment by DanTup** [comment]
@mjbvz thanks for the info - that doesn't seem as bad as I thought (at least if you're not in the edge case where the results are different) then :-)

**Comment by mjbvz** [comment]
To verify:

1. Open VS Code.
1. Open a TS file in core
1. While TS intellisense is starting
1. Bring up task selector

The tasks should show relatively quickly and not be blocked until TS intellisense completes (keep in mind that other extensions, such as java, may slow tasks down too)

**Comment by dbaeumer** [comment]
Verified that task show up before the language server initialization in the status bar has completed.
