### ISSUE TITLE
Seeing random text output in integration tests

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#84283]
* run only `\extensions\vscode-api-tests\out\singlefolder-tests` by commenting out the rest of the `test-integration.(bat|sh)`
* observe random output:
![image](https://user-images.githubusercontent.com/5047891/68490841-0270be00-024a-11ea-88ab-5342cae31208.png)

I have tracked this down to this line:
https://github.com/microsoft/vscode/blame/617a3387d41c2df65a899e8aaea773d8057751fc/src/vs/workbench/services/bulkEdit/browser/bulkEditService.ts#L430

It would be good when the integration tests have a clean human readable output to make it easy for us to spot things in there.

**Comment by alexandrudima** [comment]
Hm, maybe we can add an environmental variable to indicate integration tests running and then we can disable the error logging for this case if integration tests are running...

**Comment by alexandrudima** [comment]
I see all kind of other "useful" crap in there:
- `The task [customTesting, First custom task] uses an undefined task type. The task will be ignored in the future.`
- `[Deprecation Warning] method 'TextEditor.hide' is deprecated and should no longer be used. Refer to the documentation for further details.`
- `vscode.vscode-api-tests created a webview without a content security policy: https://aka.ms/vscode-webview-missing-csp`

**Comment by jrieken** [comment]
Yeah, not so easy... Things that are on the renderer should use the log service and for that could do something, e.g. mute it or at least not print it to the console. In the extension land we do use the console to "communicate" with extension developers. The easiest might really be to disconnect the extension host console when running tests. I do believe that extension host already know when it being run tests - @bpasero can you confirm that?

**Comment by bpasero** [comment]
Yeah, ext host does know via the --extensionDevTestPath CLI thingy.

**Comment by jrieken** [comment]
Adding people based on `console.[log|warn|...]` usages. Please replace usages with `ILogService` which can get injected

- [ ] /src/vs/workbench/api/common/extHost.api.impl.ts @jrieken
- [ ] /src/vs/workbench/api/common/extHostConfiguration.ts @sandy081 
- [ ] /src/vs/workbench/api/common/extHostDecorations.ts @jrieken 
- [ ] /src/vs/workbench/api/common/extHostDiagnostics.ts @jrieken 
- [ ] /src/vs/workbench/api/common/extHostDocumentData.ts @jrieken 
- [ ] /src/vs/workbench/api/common/extHostExtensionActivator.ts @alexandrudima 
- [ ] /src/vs/workbench/api/common/extHostExtensionService.ts @alexandrudima 
- [ ] /src/vs/workbench/api/common/extHostLanguageFeatures.ts @jrieken 
- [ ] /src/vs/workbench/api/common/extHostMessageService.ts @jrieken
- [ ] /src/vs/workbench/api/common/extHostRequireInterceptor.ts @jrieken 
- [ ] /src/vs/workbench/api/common/extHostSCM.ts @joaomoreno  
- [ ] /src/vs/workbench/api/common/extHostTask.ts @alexr00 
- [ ] /src/vs/workbench/api/common/extHostTextEditor.ts @jrieken 
- [ ] /src/vs/workbench/api/common/extHostTreeViews.ts @alexr00 
- [ ] /src/vs/workbench/api/common/extHostWebview.ts @mjbvz 
- [ ] /src/vs/workbench/api/node/extHostCLIServer.ts @chrmarti 
- [ ] /src/vs/workbench/api/node/extHostDebugService.ts @weinand 
- [ ] /src/vs/workbench/api/node/extHostExtensionService.ts @alexandrudima 
- [ ] /src/vs/workbench/api/node/extHostOutputService.ts @isidorn 
- [ ] /src/vs/workbench/api/node/extHostStoragePaths.ts @jrieken 
- [ ] /src/vs/workbench/api/node/extHostTask.ts @alexr00

**Comment by jrieken** [comment]
@bpasero re https://github.com/microsoft/vscode/issues/87414#issuecomment-567863703 - it seems that calling `ILogService#error` during integration tests prints to the console? As the "runner" of tests can you prevent that from happening?

**Comment by bpasero** [comment]
@sandy081 can that be configured somehow?

Tests are executed from here:

https://github.com/microsoft/vscode/blob/4858143eb5c2f3b7c855462c21ea7895f9f5d28f/src/vs/workbench/api/common/extHostExtensionService.ts#L535

**Comment by bpasero** [comment]
So, commenting out the following line removes various output for me:

https://github.com/microsoft/vscode/blob/ecc140e81dc5f2934181ddd40ff733a68646e149/src/vs/platform/log/common/logIpc.ts#L40

However, this is also the place where we report the output from the test run itself (e.g. if a test succeeds or not) so it may be a bit risky to simply block everything.

**Comment by sandy081** [comment]
AFIK it cannot be configured

**Comment by jrieken** [comment]
re https://github.com/microsoft/vscode/issues/84283#issuecomment-567887284 it feels like test results and logging should be separated. I don't see another way of getting this fixed. Now, the logging service instead of `console` is used (and believe that's a good thing) but ironically that made those console messages worst

**Comment by bpasero** [comment]
I have pushed a small change which will make errors render properly when logged. Instead of seeing the raw file operation error as JSON, the output is now easier to read using the message of the error:

![image](https://user-images.githubusercontent.com/900690/71810111-e767d200-3071-11ea-9b3b-04c095228b10.png)

Still, I am not seeing a good way to prevent this output from showing up in the integration tests. The integration tests run VSCode in full and as such there is potential for a lot more output in the tests compared to normal unit tests. If we had `console.log` usages in our unit tests we would see the same. I think this output is still useful to diagnose issues from users so just removing it does not seem like a good option either.

I ran a quick test how the integration tests looked like in earlier versions (prior 1.39) and I am seeing the same output, though well hidden, similar to this output which seems to be coming from the renderer Chrome console:

![image](https://user-images.githubusercontent.com/900690/71810963-e172f080-3073-11ea-9669-6d8ebe1bc834.png)

I think the move towards `ILogService` is good anyway and there are still some usages looking at `vs/workbench/api` (@jrieken not sure if your list in https://github.com/microsoft/vscode/issues/84283#issuecomment-552337183 covered them already): 

![image](https://user-images.githubusercontent.com/900690/71810072-ce5f2100-3071-11ea-9dd6-e5c8685b4224.png)

@alexdima since you are the author of the issue, I am open for ideas how to improve this further if you have any.

**Comment by bpasero** [comment]
There is now a way in extension tests to disable logging for the duration of the test ([`withLogDisabled`](https://github.com/microsoft/vscode/blob/2af91664d482c6065f7a0d589823ec115a65ec10/extensions/vscode-api-tests/src/utils.ts#L74)). Using this for some of the tests, the file service output is no longer printed.

Filed https://github.com/microsoft/vscode/issues/88671 and https://github.com/microsoft/vscode/issues/88672 for remaining output.
