### ISSUE TITLE
Accessibility: Dropdown lists don't announce the correct ordering when using Narrator

### ISSUE THREAD

**Issue by corivera** [microsoft/vscode#84306]
When using Narrator on an item in a dropdown list, the ordering it reports doesn't reflect the actual number of items in the list. Using the Command Palette as an example, Narrator will announce items like "1 of 19, level 1", but there are way more than 19 items in the dropdown list. This count seems to correlate with the height of the dropdown, so I'm guessing it's related to removing items from the DOM when they aren't visible.

We looked into it briefly and found some code that sets aria-setsize and aria-posinset in the Tree code, but it appears like the AccessibilityProvider in the Dropdown code doesn't define methods for setting those.

**Comment by isidorn** [comment]
The issue here is that the list / tree is virtualised, so the narator probably reads out the number of elements present in the dom.

The recommendation here is to use the [IAriaProvider](https://github.com/Microsoft/vscode/blob/6245d67152fd77ac7560f62a58a58cdeaf4a9047/src/vs/base/browser/ui/list/listView.ts#L44) when creating your List.

If you are using the old tree you should use the [IAccessibilityProvider](https://github.com/Microsoft/vscode/blob/6245d67152fd77ac7560f62a58a58cdeaf4a9047/src/vs/base/parts/tree/browser/tree.ts#L317)

Since this issue is about the Command Palette I am forwarding it to @chrmarti to adopt the accessibility provider. @chrmarti if you do not have time, feel free to assign the issue back to me.

@corivera let us know if you see this in other areas, for now we will only tackle the command palette. Thanks.

**Comment by chrmarti** [comment]
The Command Palette is using an AccessibilityProvider: https://github.com/microsoft/vscode/blob/1876ce6361634423d0d5534b12dad1270c1373ff/src/vs/base/parts/quickopen/browser/quickOpenViewer.ts#L49

**Comment by isidorn** [comment]
Then this might be a narrator issue.
@corivera can you reproduce this issue also with NVDA? Since we only test on NVDA we can only confirm that it works there.
Can you reproduce this somewhere else, or only in the command palette?

**Comment by corivera** [comment]
This issue repro'd with every dropdown we tried. Command palette was just an easy repro.

**Comment by corivera** [comment]
Doesn't look like NVDA announces any ordering at all. Here's the output from an NVDA test @Charles-Gagnon did:

Quick Picker  tree view
Format Document, Shift+Alt+F, commands, picker  level 1
Preferences: Open Settings (UI), commands, picker  level 1
Preferences: Open User Settings, commands, picker  level 1
Convert Indentation to Spaces, commands, picker  level 1
Change Language Mode, Control+K M, commands, picker  level 1
Convert Indentation to Tabs, commands, picker  level 1
