### ISSUE TITLE
Dragging the window border to resize the window randomly fails

### ISSUE THREAD

**Issue by pedrogarcia** [microsoft/vscode#84315]
Issue Type: <b>Bug</b>
Another issue that only ever happens because this is an electron app. 
Gif demonstrating the issue:
![2019-11-08-17-31-01](https://user-images.githubusercontent.com/2473545/68508801-1cac9b00-024e-11ea-9b59-6eada3d34144.gif)

VS Code version: Code 1.40.0 (86405ea23e3937316009fc27c9361deee66ffbf5, 2019-11-06T17:02:13.381Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
matlab-formatter|Aff|2.4.12
vscode-dash|dee|2.2.0
EditorConfig|Edi|0.14.2
terminal|for|0.0.10
matlab|Gim|1.4.0
latex-workshop|Jam|8.3.1
python|ms-|2019.10.44104
remote-ssh|ms-|0.47.2
remote-ssh-edit|ms-|0.47.2
remote-wsl|ms-|0.40.2
sublime-keybindings|ms-|4.0.3
latex-utilities|tec|0.3.4
latex-support|tor|3.1.0

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
I'm having trouble reproducing this. Can you confirm a few settings: 
1. window.titleBarStyle
2. Your screen resolution
3. Multi-monitor?
4. OS Scaling settings

**Comment by pedrogarcia** [comment]
The sidebar is hidden, I don't expect it to show up from dragging what looks like the window border. 

I don't know if this is just a "feature" that feels like a hack, or if it is an actual bug. If this is really what's supposed to happen, how the fuck would I ever know this without feeling annoyed or without having some UI hint in the window, like a drag handle or something else. 

This really just feels like it shouldn't work to me.

**Comment by sbatten** [comment]
can reproduce

**Comment by joaomoreno** [comment]
@pedrogarcia Please mind your manners, there's no need for that kind of language. As you can tell, you're getting direct support from the actual engineers on the project within hours of you filling the issue. Please try to show some appreciation simply by behaving cordially. Thanks.

---

@sbatten I wonder if we should disable the snapping out mechanism on the far edges of the window?

**Comment by pedrogarcia** [comment]
@joaomoreno I updated the comments to remove the lack of cordiality.

**Comment by sbatten** [comment]
@joaomoreno I thought it was disabled. I think it should be.

**Comment by joaomoreno** [comment]
It's not. The splitview doesn't know anything about the _far edges of the window_.

**Comment by sbatten** [comment]
@joaomoreno remind me why the edges of a grid or splitview would have sashes. In cases I can think of, they are always within some other view that has its own sashes, right?

**Comment by joaomoreno** [comment]
Snapping...? :laughing:

**Comment by sbatten** [comment]
I thought we discussed that snapping sashes should not work if touching the edge of the containing view.

**Comment by joaomoreno** [comment]
That can't be the rule, otherwise the panel sash wouldn't work at all, since it's the last sash of that splitview. The rule must be set at the grid level and state something like _snapping sashes should not work if at the edge of the grid_. And even then it must be an option, since not all grids would behave in such a way (imagine @bpasero introduces snapping in his layer). I'm sketching something up. :+1:

**Comment by sbatten** [comment]
Ah that's what I was trying to recall, thanks. Snapping in the editor grid could get pretty dicey. What would happen if you snapped an editor away next to the sidebar? What would that sash represent? I think at that point we would need some multi sash disambig UX. But this is all theoretical.

**Comment by joaomoreno** [comment]
Let's write a paper for it first!

**Comment by joaomoreno** [comment]
OK that was a lot more work than expected, https://github.com/microsoft/vscode/pull/85698, since basically I had to propagate dimensions and positions down the grid node tree in order for each splitview to know whether it is at an edge of the grid. On top of that I had to have properties to disable snapping on each end of any given splitview. This behavior is now hardcoded in every grid: if a view is snapped right at the one of the edges of the grid's full dimensions, it won't be possible to drag it out into view using the mouse. This is hardcoded since we only have two grids in the workbench and only the outer one uses snapping, so it matches the desired behavior.
