### ISSUE TITLE
Monaco: improperly initializing embedded modes object

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#84394]
The following line is problematic:

https://github.com/microsoft/vscode/blob/bb384a83e586dda0e42227d55813c7ce744fc99b/src/vs/editor/standalone/common/monarch/monarchLexer.ts#L424

As `this._embeddedModes` is an object without a prototype:

https://github.com/microsoft/vscode/blob/bb384a83e586dda0e42227d55813c7ce744fc99b/src/vs/editor/standalone/common/monarch/monarchLexer.ts#L392

And therefore has no property called `hasOwnProperty`.

I'm not sure these sorts of performance tricks are worth the chance of these kinds of bugs sneaking in.

**Comment by alexandrudima** [comment]
It's not for performance. We used to use `Object.create(null)` because that didn't suffer from the prototype polution problem, where an embedder web page can define additional properties on `Object` and everyone gets them...

We now try to use `Set` and `Map` in cases where iterating elements is not crucial, as that (element iteration via a for loop) is not supported in IE11.

**Comment by fabiospampinato** [comment]
Oh I see, thanks for the explanation 👍
