### ISSUE TITLE
Allow to configure a list of encoding-confidences to use when guessing

### ISSUE THREAD

**Issue by sunbohong** [microsoft/vscode#84503]
Since there were so many encodings issues,I plan to upgrade the code guessing workflow to V2. 

- First, jschardet will be upgraded and multiple results will be returned. For example,` [{encoding: 'UTF-8', confidence: 0.95}, {encoding: 'GBK', confidence: 0.95}]`.

- Then, we will support the configuration of multiple sets of coding confidence in the settings.`files.encodingInitConfidences`。
`[{encoding:'utf-8',confidence:0.01},{encoding:'GBK',confidence:0.03}]。`

- Finally,add the two together to get the final result, because `GBK` has the highest confidence, so the file is recognized as `GBK`
`[{encoding:'utf-8',confidence:0.06},{encoding:'GBK',confidence:0.08}]`。

**Comment by bpasero** [comment]
> First, jschardet will be upgraded and multiple results will be returned

@sunbohong are you planning to contribute to JSChardet?

**Comment by sunbohong** [comment]
> > First, jschardet will be upgraded and multiple results will be returned
> 
> @sunbohong are you planning to contribute to JSChardet?

I found that  https://github.com/runk/node-chardet can meet my requirements.

**Comment by bpasero** [comment]
I am not sure VSCode would move off `jschardet` to another module, seems rather risky. I would suggest you try to become a contributor on `jschardet` to improve it if possible.

**Comment by sunbohong** [comment]
I tried to add some logs to `jschardet`, but it failed the following test. https://github.com/aadsm/jschardet/issues/48


`node-chardet` works well with this test.
The best is `utf-8`
![image](https://user-images.githubusercontent.com/7285119/68694348-f2dbd700-05b3-11ea-9303-389ea48a16af.png)



`jschardet` cann't pass this test.

`windows-1252 confidence 0.95`
![image](https://user-images.githubusercontent.com/7285119/68694323-ea839c00-05b3-11ea-94cd-eeeb90702982.png)
`UTF-8 confidence = 0.505`
![image](https://user-images.githubusercontent.com/7285119/68694972-1ce1c900-05b5-11ea-8516-f2969415f1d1.png)

**Comment by sunbohong** [comment]
@bpasero


Since jschardet  can't provide the expected results.
We can provide node-chardet as an optional option. If there are enough people to choose the new switch in the future, we can remove the jschardet  in the future

**Comment by byyxx128** [comment]
I like the mode provided by [node-chardet](https://github.com/runk/node-chardet). Just a friendly reminder that please always use `GB18030` to replace `GB2312` or `GBK` regardless of the confidence value.

Reasons:
- New characters in a file encoded in `GB18030` will lose if the file is edited in lower encoding.
- New characters cannot be displayed normally with lower encoding (nothing will lose if it is just opened, but if it is saved with lower encoding, information will be destroyed)
- A file encoded in `GB2312` or `GBK` can be decoded as `GB18030`. Even new characters would lose if it is decoded in lower encoding again, nothing is wrong at least.

All in all, the safest way is always using `GB18030` instead of `GB2312` or `GBK`.

**Comment by byyxx128** [comment]
I like the mode provided by [node-chardet](https://github.com/runk/node-chardet). Just a friendly reminder that please always use `GB18030` to replace `GB2312` or `GBK` regardless of the confidence value.

Reasons:
- New characters in a file encoded in `GB18030` will lose if the file is edited in lower encoding.
- New characters cannot be displayed normally with lower encoding (nothing will lose if it is just opened, but if it is saved with lower encoding, information will be destroyed)
- A file encoded in `GB2312` or `GBK` can be decoded as `GB18030`. Even new characters would lose if it is decoded in lower encoding again, nothing is wrong at least.

All in all, the safest way is always using `GB18030` instead of `GB2312` or `GBK`.

Here is a file encoded by GB18030 for your test.
[test_GB18030.txt](https://github.com/microsoft/vscode/files/3866398/test_GB18030.txt)

**Comment by byyxx128** [comment]
A terrible situation is that so many Chinese users use GitHub as Baidu Tieba as they always reported an issue in Chinese without any detailed description, and they will not check the status as well. When next time they meet the same problems again, they will always open new issues and won't follow up anymore... Among those issues reported these Chinese users, many are decoding issues. However, they will not vote your issue (because they even do not read any sentence besides their own contents).

I really have no effective solutions to this point.

**Comment by bpasero** [comment]
@sunbohong please merge this with https://github.com/microsoft/vscode/issues/36951, I feel the 2 suggestions are very similar.

**Comment by sunbohong** [comment]
> I am not sure VSCode would move off `jschardet` to another module, seems rather risky. I would suggest you try to become a contributor on `jschardet` to improve it if possible.

When we use the new version of `jschardet `, we are also taking risks.
So, why not try the `node-chardet`?

**Comment by bpasero** [comment]
Some requirements to go with another library such as `node-chardet` imho are:
* it runs in web too (that is a requirement that is relatively new)
* tests of `jschardet` work in `node-chardet` (this would give some confidence)
