### ISSUE TITLE
vscode.workspace.fs.stat(): FileStat only has 1 second resolution.

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/vscode#84526]
VSCode Version: 1.40.0
OS: linux
(working on an extension remotely over SSH; haven't tried local)

`FileStat.ctime` and `FileStat.mtime` have granularity of 1 second (rather than 1 millisecond like `node's fs.Stats` does).  The docs say ["The modification timestamp in milliseconds elapsed since ..."](https://code.visualstudio.com/api/references/vscode-api#FileStat).

@jrieken

**Comment by bpasero** [comment]
This is due to this:

https://github.com/microsoft/vscode/blob/9b620f43def06692d006f63af991c59fb40bb459/src/vs/platform/files/node/diskFileSystemProvider.ts#L83

https://github.com/microsoft/vscode/blob/9b620f43def06692d006f63af991c59fb40bb459/src/vs/platform/files/node/diskFileSystemProvider.ts#L84

Not using the `ctimeMs` and `mtimeMs` equivalent. We could change it but it is somewhat a breaking change for extensions that maybe rely on the current way of things.

**Comment by bpasero** [comment]
This took me a while to understand, but I cannot reproduce the 1s resolution as you can see from the following example:

![image](https://user-images.githubusercontent.com/900690/68663347-c6d23e80-053e-11ea-940d-367ee1866dcd.png)

It is true that node.js provides nano-second resolution with their mtimeMs property but I would not expose this.

What am I missing?

**Comment by ericsnowcurrently** [comment]
Yeah, that was my fault for mis-interpreting the decimal part as milliseconds.  We're good to go. :)
