### ISSUE TITLE
codicons force grayscale text rendering

### ISSUE THREAD

**Issue by alexandrudima** [microsoft/vscode#84584]
* on Windows
* run `yarn run web`
* open in Edge Dev
* look at the text inside a tab with the magnifier
* observe it uses grayscale antialising

![image](https://user-images.githubusercontent.com/5047891/68669116-0e11fc80-054a-11ea-9770-e55fb875c214.png)

This is caused directly by the following CSS - https://github.com/microsoft/vscode/blob/8013616a328d760a68a6cf84df7813e614beb418/src/vs/base/browser/ui/codiconLabel/codicon/codicon.css#L23-L26

fyi @aeschli @bpasero @deepak1556

**Comment by alexandrudima** [comment]
After removing that CSS:
![image](https://user-images.githubusercontent.com/5047891/68669310-87115400-054a-11ea-8082-acc050dae556.png)

**Comment by alexandrudima** [comment]
@misolori It is not clear to me why that CSS with the rotation was added. It came in recently via https://github.com/microsoft/vscode/commit/ef84173ea6e64ee8f7126bbf3f5dc2c51eff798b. It has bad effects on grayscale vs lcd text antialising, so I will push a removal for now.

**Comment by misolori** [comment]
@alexandrudima the CSS transforms were a hack to get the icons to align to the pixel grid and not render blurry ([codicons PR](https://github.com/microsoft/vscode-codicons/pull/2)). However, now that these are removed I'm not seeing this pixelation out of sources, which may have been fixed with our recent electron/font smoothing changes? Sorry you had to spend so much time investigating this 🙈.

I'll also link to the commits from the [vscode-codicons](https://github.com/microsoft/vscode-codicons/) repo that explain more about the changes next time so everyone knows what the commits are about.

**Comment by alexandrudima** [comment]
No problem! I think the blurry rendering codicons were suffering from 100% the same issue as the text. Since codicons are fonts they go through the same rendering pipeline as text. So, if Chromium would make a layer to render with grayscale text, then both the text itself and codicons would render with grayscale and appear "blurry".
