### ISSUE TITLE
Touch bar mac disabled on focus file

### ISSUE THREAD

**Issue by Alexzanderk** [microsoft/vscode#84692]
So I updated to 1.40.0
And have this issue:
my touch bar on mac hide! What I mean 
When I write code **this is showing my touch bar** 
![image](https://user-images.githubusercontent.com/16296369/68769368-d7f97900-062c-11ea-8bc5-c94c8f50201e.png)

but early it was 
![image](https://user-images.githubusercontent.com/16296369/68769570-358dc580-062d-11ea-9f3b-28560705a268.png)

**My settings**
![image](https://user-images.githubusercontent.com/16296369/68769520-20b13200-062d-11ea-8199-71643bf3e43a.png)

When the focus is down from the code window
touch bar show
![image](https://user-images.githubusercontent.com/16296369/68769570-358dc580-062d-11ea-9f3b-28560705a268.png)

I expected behavior on the focus code window 
this 
![image](https://user-images.githubusercontent.com/16296369/68769570-358dc580-062d-11ea-9f3b-28560705a268.png)
but have  this 
![image](https://user-images.githubusercontent.com/16296369/68769368-d7f97900-062c-11ea-8bc5-c94c8f50201e.png)

What happened with the touch bar?

**Comment by Alexzanderk** [comment]
Who could help with this problem?

**Comment by luannguyend86** [comment]
@Alexzanderk yes, it is the same to me at #84189

**Comment by bpasero** [comment]
@Alexzanderk what are these other items in the touchbar you show, are they coming from macOS?

**Comment by guidobouman** [comment]
The words you see are the spelling autocomplete words provided by Apple. They are coming from macOS as autocorrect. As soon as the with of the spell check hits an otherwise visible button, that button is hidden.

You can check that behaviour by collapsing the autocomplete through tapping on the (small) arrow on the left.

In my case: On a 13" MacBook pro I can start the project, but I can't stop the project. The start state on the touch bar is small enough to show, but the debugging state is wider, and hits the collapsed autocomplete, and is thus always hidden.

**Comment by bpasero** [comment]
VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

Reading this issue, it seems to originate not from VSCode itself but rather one of these upstream components. As such, in order to resolve it, it would need to get fixed in the upstream component. I will go ahead and close this issue and kindly ask to report this issue to the upstream component if possible:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.

**Comment by Alexzanderk** [comment]
@bpasero I downgrade to 1.39
and on this version, everything is fine to work like expected

**Comment by guidobouman** [comment]
It's a thing in a Chromium release. I'm wondering if it's configurable to remove text suggestions on an input field.

Adding `autocomplete="off"` on the textarea I'm typing this in does not remove the suggestions.

**Comment by bpasero** [comment]
If someone is willing to report this issue to Electron we can reopen this one and link to the issue. But there is currently probably nothing we can do in VSCode given that `autocomplete="off"` does not seem to help.

**Comment by Alexzanderk** [comment]
> It's a thing in a Chromium release. I'm wondering if it's configurable to remove text suggestions on an input field.
> 
> Adding `autocomplete="off"` on the textarea I'm typing this in does not remove the suggestions.
> 
> Tracking issue for Electron:
> [electron/electron#9349](https://github.com/electron/electron/issues/9349)
> 
> Tracking issue for Chromium:
> https://bugs.chromium.org/p/chromium/issues/detail?id=717553

Chromium?? Why do you think that issue with chromium?

**Comment by guidobouman** [comment]
> Chromium?? Why do you think that issue with chromium?

Did you read the links I attached? macOS provided a feature that Chromium later implemented. VS Code updated their version of Electron, which in turn updated their version of Chromium in the meantime. So we need to find a way to disable this in Chromium through an HTML attribute or in Electron through config, if that is even possible.

@bpasero The chromium team picked this up rather quickly; A fix already landed in their repo. See https://bugs.chromium.org/p/chromium/issues/detail?id=1024914 for more tracking info.

This should hide the spell suggestion when adding `autocomplete="off"` on a textarea. Would that work for VS Code?

**Comment by guidobouman** [comment]
@bpasero The chromium team picked this up rather quickly; A fix already landed in their repo. See https://bugs.chromium.org/p/chromium/issues/detail?id=1024914 for more tracking info.

This should hide the spell suggestion when adding `autocomplete="off"` on a textarea. Would that work for VS Code?

**Comment by bpasero** [comment]
@deepak1556 can we possibly backport this change for Electron 6?

**Comment by deepak1556** [comment]
@bpasero yup seems simple enough to target recovery release.

**Comment by bpasero** [comment]
@deepak1556 I think November is fine, I was not suggesting recovery :)

**Comment by deepak1556** [comment]
Electron PR https://github.com/electron/electron/pull/21191

**Comment by Alexzanderk** [comment]
> This should hide the TouchBar suggestions when adding `autocomplete="off"` on a textarea. Would that work for VS Code?

Where is I need to add `autocomplete="off"`?

**Comment by guidobouman** [comment]
This needs to be done by the VS Code team. Probably as a setting to, keep users, who prefer autosuggest, happy.

**Comment by bpasero** [comment]
I don't think we want a setting for this, the editor disables autocomplete by default for various reasons.

**Comment by alexandrudima** [comment]
autocomplete is off in the editor `<textarea>` for performance reasons. We don't have the actual file content in the `<textarea>`, we only have the previous character and suggestions wouldn't be helpful. We only place the previous character because everything more we place in there will cost in terms of performance.

**Comment by guidobouman** [comment]
Sure, but I also remember seeing an issue that requested the feature in this repository. (Can't seem to find the issue right now...)

**Comment by deepak1556** [comment]
Fixed with https://github.com/microsoft/vscode/pull/85266
