### ISSUE TITLE
"Help: Report Issue" does not use issue templates for extensions

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#84738]
We get users regularly using the "Help: Report Issue" feature to report bugs on the Python extension. Unfortunately that means they are completely ignoring our issue template which asks a lot of key details that always lead to us having to round-trip back on them asking for them to fill out our issue template to get the information back.

I would normally ask to just grab an issue template, but we have 4 different templates, so that's not so straightforward for us. So maybe a way to specify what template to use by default or to allow us to opt-out of "Report Issue" and have it just open the browser to our repo?

**Comment by byyxx128** [comment]
I don't use the Python extension, but I have same feeling with this case.
So I have some possible solutions here for reference. You may have better ideas.

1. VS Code provides a webview to allow users to login GitHub accounts and type directly like VS 2019 does. It will be easy to use the templates because it's actually typing in GitHub directly. The issue reporter can print basic information in issues rather than sending via URL and jumping to a browser. This issue #73921 will be avoided as well because users will not be asked to paste anything (as VS Code will already have done in the webview)
2. Jumping to browsers after selection of issue sources. (This is an alternative by the author)
3. The issue reporter can be redesigned to be compatible with the GitHub reporter format.

All of the solutions above are independent. You can choose one you like or consider a better one.

**Comment by brettcannon** [comment]
Another option is to allow us to provide our own hook or "Report Issue" flow that the "Help: Report Issue" command defers to. (See microsoft/vscode-python#1119). Currently there's https://github.com/microsoft/vscode/issues/46726 which has a specific potential solution while this issue has other ones.
