### ISSUE TITLE
Not possible to define location of argv.json

### ISSUE THREAD

**Issue by hajdamak** [microsoft/vscode#84808]
- VSCode Version: 1.40.1 (commit: 8795a9889db74563ddd43eb0a897a2384129a619) and insiders 1573725034
- OS Version: Ubuntu 16.04 - Linux x64 4.4.0-168-generic

Steps to Reproduce:

1. Start vscode with command line options `--user-data-dir ~/.config/vscode --extensions-dir ~/.config/vscode/extensions`
2. File `argv.json` is created in `~/.vscode` instead of `~/.config/vscode`

Does this issue occur when all extensions are disabled?: Yes
Does this issue occur on insiders version?: Yes

**Comment by bpasero** [comment]
@hajdamak as a workaround, you can use portable mode (https://code.visualstudio.com/docs/editor/portable) and it should put this file at the location you provide, can you try that?

**Comment by hajdamak** [comment]
@bpasero Am I missing something? Doesn't portable mode require `data` directory to be placed inside VSCode directory? I just want to have setup that follows [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) where only applicaton config is in `.config/vscode` . VSCode itself is somewhere else.

**Comment by bpasero** [comment]
@hajdamak we are using `os.homedir()` from node.js in the end which seems to pick up on these environment variables:
* Posix: `HOME`
* Windows: `USERPROFILE`

Can you not simply change this variable prior to launching VSCode as a workaround? This would even ensure that any code that wants to write into home directory would follow the path you specify.

**Comment by hajdamak** [comment]
@bpasero What do you exactly mean by changing `os.homedir( )`? 
From my POV creating `argv.json` outsisde of `--user-data-dir ~/.config/vscode` seems like a bug.

**Comment by hajdamak** [comment]
Why it was closed?
Isn't it an obvious bug?

**Comment by freed00m** [comment]
@hajdamak 

Well technically it's not a bug, it's just a hardcoded path that annoys few users.

I subscribe to the xdg "ideology" as well so for linux I just made myself a handy wrapper, it still uses the classic ~/.config and ~/.cache ( assuming XDG_vars are read ) correctly.

```
#!/bin/sh
VSCODE_NON_COMPLIENCY_MITIGATION="$HOME/.local/share/code-fakehome"
HOME=$VSCODE_NON_COMPLIENCY_MITIGATION

if [ ! -d $VSCODE_NON_COMPLIENCY_MITIGATION ]; then
	mkdir -p $VSCODE_NON_COMPLIENCY_MITIGATION
fi
nohup /usr/bin/code > /dev/null 2>&1 & 

```

**Comment by ChrisDenton** [comment]
> Can you not simply change this variable prior to launching VSCode as a workaround? This would even ensure that any code that wants to write into home directory would follow the path you specify.

Incidentally this workaround doesn't work on Windows. Changing `USERPROFILE` results in the error "Failed to get 'appData' path".

I'm also perplexed as to why this was closed with no mention of why. Is it not considered a bug? Is it being addressed in another issue? Is VS Code reluctant to support directories other than the hard coded ones?

Giving any reason would be useful even if it might not be what I'd want.

**Comment by MicahZoltu** [comment]
https://github.com/microsoft/vscode/issues/3884

**Comment by 0xabcdead** [comment]
Write protecting your home directory also works. Overriding `HOME` requires a fair bit of setup because when you open the terminal inside vscode it uses the `HOME` that you passed to vscode. inb4 the dev team would rather make everything work with a custom home path instead of just following the XDG spec :rofl:. Looks like the file is only written on startup, so could also try a wrapper script that schedules deleting it using `at` shortly after start.

**Comment by morenathan** [comment]
I've been wondering about this argv issue myself, and now I see why with the overwriting of HOME being offered as a solution. That's not a solution.

XDG defines two user-provided, system-provided separately, or sensible defaults for things being discussed.

$XDG_DATA_HOME defines the base directory relative to which user-specific data files should be stored. [...] a default equal to $HOME/.local/share should be used.

$XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. [...] a default equal to $HOME/.config should be used.

My reading of argv.json says it's for user configuration, so that would go under XDG_CONFIG_HOME/code/argv.json as would anything configured with the --user-data-dir (at this time since VS Code doesn't offer proper XDG compliance).

Anything we can configure with --extensions-dir should be configured to go to XDG_DATA_HOME since these are just program data files that are easily re-downloaded from the internet. I'm not sure if the configuration of an extension goes with it but it wouldn't seem it should. 

I'm just a new-ish user of code on Linux and frustrated by this lack of proper desktop protocol support.
