### ISSUE TITLE
Reference sub-tasks in multi-root workspaces

### ISSUE THREAD

**Issue by felwolff** [microsoft/vscode#84800]
If I define a workspace wide task, I would like to specify that it depends on tasks defined in the `tasks.json` files of the folders inside the workspace. Example: I develop a program and a library, which is used by the program, inside the same workspace. Now I want to build the program and specify that the library must be built first. I have build tasks for both inside their respective `tasks.json` files, but I cannot make one depend on the other.

One possibility would be to have a build-all tasks in `.code-workspace` that depends on those sub tasks and it should resolve the sub-task names just like it resolves launch names of sub-launch files.

Also see [this](https://stackoverflow.com/questions/51600546/how-to-share-tasks-between-vscode-workspace-folders/58853570#58853570) Stackoverflow post.

**Comment by EternalPhane** [comment]
I do agree with @alexr00 that a task defined in one folder should not be referenced in another folder (https://github.com/microsoft/vscode/issues/83065#issuecomment-549285996). However, since workspace is used to manage folders, I think it reasonable to allow task in folders to be referenced in `.code-workspace` (and maybe vice versa).
