### ISSUE TITLE
Touchpad Srcolling Moves Cursors Instead of Scroll Bar on Some Devices

### ISSUE THREAD

**Issue by AeneasZhu** [microsoft/vscode#84879]
![gifhome_1920x1032_8s](https://user-images.githubusercontent.com/44701446/68907701-acd56d80-0783-11ea-8496-dc23af4f9559.gif)

I scroll up and down with the laptop's touchpad on the vscode, but it moves the cursors instead of scrolling bar. This causes great unconvenience when using Python Interactive Window or Notebook.https://github.com/microsoft/vscode-python/issues/8556

https://stackoverflow.com/questions/52559043/vs-code-touchpad-scrolling-moving-cursor-instead-of-page

This happens on many Lenovo's Devices where touchpads are Elan Pointing Devices.

Can this problem be fixed?

**Comment by alexandrudima** [comment]
@AeneasZhu Sometimes, these trackpads/touchpads have drivers that implement a certain gesture (like two fingers scroll) by sending arrow up/arrow down keyboard events instead of mouse wheel events. To test my hypothesis, can you please try the following:

Please try in both Edge and Chrome:
* open https://microsoft.github.io/monaco-editor/ and click inside the first editor
* use the scroll on your trackpad/touchpad
* what happens?

**Comment by AeneasZhu** [comment]
@alexandrudima Thanks for help. I have installed monaco editor. But I don't know how to use it and how to open it. I installed monaco editor through npm install.

**Comment by AeneasZhu** [comment]
@alexandrudima 

![gifhome_1920x1040_4s](https://user-images.githubusercontent.com/44701446/69146990-f61f1780-0b0b-11ea-973a-469357910a12.gif)


The touchpad of my laptop can move the scroll bar inside the first editor

**Comment by alexandrudima** [comment]
@AeneasZhu That is good news. The editor you have tried in is using the same source code as the editor in VS Code. VS Code is built with Electron, which is built with Chromium. Currently, VSCode uses Chromium version 76.0.3809.146.

Chrome is also built with Chromium, the latest is version 78.0.3904.108. I think this is the one you might have tried. So if all things are equal, then once we adopt Chromium 78 your trackpad should work with us. 

For completeness sake you could also try to download Chromium at a version close to ours from https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/665006/ and check how the trackpad works there at https://microsoft.github.io/monaco-editor/ .

So I hope once we adopt Chromium v78 everything will work fine. Perhaps we can find a specific issue being fixed in Chromium from v76 to v78 targetting your trackpad. But... there is also another more unhappy possibility... which I have heard before. Your trackpad driver could be looking at the current focused window, and if the ImageName of the process the current focused window belongs to is equal to "Chrome.exe", then they send mouse wheel events, otherwise they send arrow down events. So it is possible that even if we do eventually update to the latest Chromium, your trackpad might still not work. To check this hypothesis, you could try to download VS Code as a zip (https://code.visualstudio.com/insiders/) and then rename the `.exe` to `Chrome.exe` and try to see how the trackpad works then...

**Comment by AeneasZhu** [comment]
@alexandrudima  Amazing!!! After renaming the name to  `chrome.exe`, the touchpad can work and move the scroll bar instead of cursor, as I did what you suggest.  Shall I just rename the `code.exe` to `chrome.exe` for the installed version to fix this 'bug'?

**Comment by AeneasZhu** [comment]
Thanks for help!!! @alexandrudima

**Comment by alexandrudima** [comment]
@AeneasZhu This unfortunately points to the fact that the driver for your touchpad/trackpad is doing some very nasty stuff! Depending on the focused window, it will send different UI events, either arrow up/arrow down keyboard events, either mouse scroll events. 

I think it is best to contact the driver manufacturer and file an issue with them. They can add `Code.exe` and `Code - Insiders.exe` to their list of processes that support mouse scroll events.

Unfortunately, there is no possible code change I can do in VS Code to address this, as it is an issue with the driver.
