### ISSUE TITLE
Cannot distinguish different files with the same path.filename(x)

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#8499]
Testing #7854

![image](https://cloud.githubusercontent.com/assets/5047891/16450701/bf02f8f8-3dfe-11e6-9d78-abd055b8087e.png)

**Comment by alexandrudima** [comment]
I had both the user settings and the workspace settings ...

**Comment by bpasero** [comment]
Interesting what ST does in this case:

![image](https://cloud.githubusercontent.com/assets/900690/16452144/420f9aa0-3e07-11e6-99d2-0691cb9a99af.png)

**Comment by bgashler1** [comment]
As originally designed, we did something very similar: whenever something is opened that is not in the root of the folder, then we show it's parent folder below the file name in smaller text.

![tabs-01c](https://cloud.githubusercontent.com/assets/11839736/16469427/be904ec8-3e05-11e6-8f57-988dd9202dac.png)

**Comment by stevencl** [comment]
If we showed the path to the file in the status bar would this resolve this issue?

Is there enough horizontal and vertical space in the tab to be able to show the path to the file?

**Comment by bpasero** [comment]
We should talk about this when I am back from vacation, a user posted a PR that does the simple thing: Just add the path of the file to the tab if another tab has the same name.

**Comment by ecraig12345** [comment]
What about showing the path to the file in the window title like ST does? Often I would like to see the full path (for various reasons) even when I don't have multiple files by the same name open. (Since this is a slightly different issue, I can open a separate issue report if that seems more appropriate.)

**Comment by bpasero** [comment]
Please use the search feature before filing new issues:

![image](https://cloud.githubusercontent.com/assets/900690/16864703/2fc4c17c-4a5f-11e6-9045-bd2a2c8313ef.png)

**Comment by ecraig12345** [comment]
@bpasero If the request to use the search feature was directed at me, I did that already and didn't find anything... My question was whether the idea merits a separate issue (since it's one potential solution to this issue), not whether an issue has already been opened for it.

**Comment by ligaz** [comment]
I would personally vote for something similar to what Sublime is doing. It is smart about it and if the parent folders have the same name it prepends their parent names and so on.

**Comment by bpasero** [comment]
@ligaz yes I like that too.

@ecraig12345 https://github.com/Microsoft/vscode/issues/1723 (you owe me 2 minutes of my morning)

**Comment by bpasero** [comment]
Also related: https://github.com/Microsoft/vscode/issues/3119

**Comment by bpasero** [comment]
I think this needs some design work first. Assign to me once we made a decision please. I am not sure we plan this for August.

**Comment by stevencl** [comment]
Will discuss again tomorrow. I forgot to add notes from our discussion last week. We agreed that we should show the name of the parent folder whenever there are two files opened with the same name.

**Comment by rmunn** [comment]
This is especially needed when working on Ansible scripts: I have a whole folder tree full of files with names like `role1/defaults/main.yml`, `role1/handlers/main.yml`, `role1/tasks/main.yml`, `role2/defaults/main.yml`, `role2/handlers/main.yml`, `role2/tasks/main.yml`, and so on for about a dozen different roles. It's tedious to hover over each tab trying to find out which `main.yml` it is.

**Comment by bpasero** [comment]
@stevencl @bgashler1 I pushed this with some changes to our initial discussions. 

First of all this is how it looks:

![screen shot 2016-08-12 at 11 50 02](https://cloud.githubusercontent.com/assets/900690/17618972/f06c0fd2-6082-11e6-9400-09c4d3509a19.png)

For one, I decided to use the same UI for showing the path that we already have when disabling tabs: That is, smaller font, some margin and a different color so that the file name is still standing out strong.

And then I am always showing the full path of the file and not just its parent for several reasons:
* this is consistent with our non-tabs UI and any other place throughout the UI
* this will work for any editor opened and not just files (we could have name collisions also for other editor types and making it specific to files is bad)
* this helps the user to see the full context of a file because I argue that the parent folder might not be enough to understand where the file is coming from (e.g. in the case of Alex the parent folders are "code" and ".vscode"

**Comment by ligaz** [comment]
Is there a reason to show the full path instead of just the difference as Sublime does it? Showing the full path will widen the tab which might be good for users with 13' displays.

**Comment by jhofker** [comment]
+1 to "just the difference" -- I was starting to write an extension before I found this issue to help solve this type of this:
![image](https://cloud.githubusercontent.com/assets/812787/17637105/06f54e84-60a7-11e6-9df6-419ea5da63e0.png)

I don't need the full path, I just need to know the name of the folder it's in, as they're all just React components. If this had an extension api I'd probably keep going with what I was doing, but I can't seem to find it.

**Comment by bpasero** [comment]
I had a longer discussion with @stevencl on this and maybe we can discuss it here so that more people can chime in. If we decide to only show the parent name of the folder, things are maybe OK and expected, but what happens if the parent names are also identical? You start going up one level so you might have a description of "foo/bar" and "some/bar" next to the file name. Would that not draw the impression that the file is within a folder "foo/bar"?

I think to solve that confusion, at the very minimum we should show the last portion of the folder with a leading "../" so that people understand, the folder is not the absolute path to the file.

**Comment by jhofker** [comment]
@bpasero -- personally I'd be down with that. My goal is to be able to distinguish identically-named files from each other in as little space as is required to do it.

If I open `foo/bar/index.js` and `cat/bar/index.js`, seeing `index.js | foo/..` and `index.js | cat/..` as tabs would work well for my needs.

Also, I think this is similar to #8501 (just so they get linked up)

**Comment by bpasero** [comment]
I pushed a change to show the name of the folder to distinguish tabs with the same file name but I am falling back to showing the full path as soon as the parent folder is also identical. I think that is a good solution.

@stevencl fyi, this solution is closer to what you suggested in the first place.

**Comment by jhofker** [comment]
Good stuff!
![image](https://cloud.githubusercontent.com/assets/812787/17667273/d6a2b774-62c9-11e6-9b35-1b45a6556840.png)

But multiple files in one folder matching multiple files in another gets hairy:
![image](https://cloud.githubusercontent.com/assets/812787/17667316/0d579262-62ca-11e6-850a-3ddefaebae81.png)

**Comment by bpasero** [comment]
@jhofker yeah, nice finding, and I saw this today this morning and pushed a fix after our nightly was already running.

The really only situation you should ever see a full path (that is: workspace relative if the file is from an opened folder) in a tab is when both files have the same parent folder. But that seems to be happening in ST as well:

![image](https://cloud.githubusercontent.com/assets/900690/17667789/ae85753c-6306-11e6-890c-52a593096489.png)

**Comment by jhofker** [comment]
@bpasero just updated to last night's build and this is working great. Thank you!

**Comment by steve-ross** [comment]
Know this is closed (and working fine) however, is there a way to force setting to always on? Would be useful if i have the editor split so I can tell the following apart easily:

![screen shot 2016-11-01 at 8 54 53 am](https://cloud.githubusercontent.com/assets/297351/19890402/e60d49c0-a010-11e6-8ba3-03c74ebfaa50.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13350

**Comment by peabnuts123** [comment]
+1 for a setting to force this always on, but for a different use-case than @steve-ross. Working in a project that has many of the same filenames (e.g. Ember, where filenames are relatively semantic, or many NodeJS apps where `index.js` has an important role) produces strong usability issues as you often don't need to edit two files with the same name at the same time, but may lose track of which file you have open. It would, personally, make my life a lot easier if I could set a minimum value for tab path (i.e. always show at least the parent folder name, or more if you have multiple instances open) or perhaps a setting similar to `window.title` wherein you could supply a magic string for tab title and subtitles. I find in Ember especially (where I have many different `application.js` files and forms and routes with the same name) I have to hover over the tab to see the full path quite often.

**Comment by steve-ross** [comment]
@peabnuts123 same use case :) as in my screen shot (react / redux app) maybe that approach makes more sense. Guess we should really dig in and see if we could contribute. Special thanks to all you open source contributors. Don't let our "complaints" & feature requests diminish the fact that you all kick ass for bringing us tools.

**Comment by orangemooncreative** [comment]
+1 i am working on a react/redux app and would love an always on option as @steve-ross mentioned.

**Comment by matthewrbrooks** [comment]
Another +1 for exactly the same reasons as @orangemooncreative @steve-ross ...

And another +1 for 'it's a great tool'!
