### ISSUE TITLE
Inserting a new line doesn't work after Find (Firefox)

### ISSUE THREAD

**Issue by waclaw66** [microsoft/vscode#85033]
- VSCode Version: code-server2.1692-vsc1.39.2-linux-x86_64 and a few previous
- OS Version: Fedora 31

Firefox 70 @ Windows 10 1909

## Description
I am running VS Code remotely via code-server.
When I use Find function to search something, then press Esc to exit search field and try to insert a new line by Enter, the search field is opened instead of inserting a new line.
It works fine in Chrome though.

## Steps to Reproduce

1. Ctrl+F, type a text, press Enter
2. press Esc to exit search field, eventually press End to deselect found text
3. press Enter
4. search field is opened again instead of inserting a new line

Does this issue occur when all extensions are disabled?: Yes

**Comment by spahnke** [comment]
A similar issue was reported for the monaco-editor. The cause and fix should be the same, so I'm linking it here:
https://github.com/microsoft/monaco-editor/issues/1637

**Comment by waclaw66** [comment]
> 
> 
> A similar issue was reported for the monaco-editor. The cause and fix should be the same, so I'm linking it here:
> [microsoft/monaco-editor#1637](https://github.com/microsoft/monaco-editor/issues/1637)

Yes, monaco playground behaves the same on my side.

**Comment by bpasero** [comment]
@waclaw66 
I wonder if this issue is reproducible when running VSCode in a browser. We allow to run VSCode in a very simplified form in a browser following these steps:
* setup to be able to run VSCode out of sources: https://github.com/microsoft/vscode/wiki/How-to-Contribute
* run `yarn web` from a command line
* it should open a browser with VSCode running

If you are not able to set this up, we also provide a hosted version of VSCode for Web at: https://vscode-web-test-playground.azurewebsites.net

Does the issue reproduce in that setup in the browser?

**Comment by spahnke** [comment]
I just tried the web version and it reproduces there, too.

**Comment by waclaw66** [comment]
@bpasero I have tested the playground on azurewebsites and the issue is reproducible.
![code-ff](https://user-images.githubusercontent.com/15554561/69072481-065fc580-0a2c-11ea-9ee4-ca4a5852183a.gif)

**Comment by bpasero** [comment]
Thanks for testing 👍

**Comment by kennu** [comment]
This problem happens to me too, when using codercom/code-server:2.1688-vsc1.39.2 in Firefox Linux. Enter starts working again when you close the Find box enough times by clicking it instead of pressing Escape.
