### ISSUE TITLE
Screen Reader + 

### ISSUE THREAD

**Issue by dalongi** [microsoft/vscode#85050]
This week I was working with a co-worker who was using VS Code via a ScreenReader. (OSX)

I noticed that anytime extensions use the Status Bar or `window.show[Information|Warning|Error]Message` to communicate status of an operation, those status updates were not flagged by the screenreader and so the person was unaware of them.

Internally we have some of our own extensions that use both of these patterns for reporting start/progress on longer running actions.

Is this expected behavior? If so, is there a better practice extension developers should follow to share status?

**Comment by isidorn** [comment]
@dalongi hi, I tried to reproduce this and I could not. Notice that in the gif I am showing the Hello World is read out as an information by the screen reader.
Can you reproduce your issue with the VSCode starter extension (since it uses notifications) and VS Code insiders?

![notifications](https://user-images.githubusercontent.com/1926584/69140559-03fc7a80-0ac3-11ea-8c5f-f66589d75b0c.gif)

**Comment by dalongi** [comment]
I tried reproing using the specific workflow and I believe I understand: the flow does showInformationMessage but [in some conditions] immediately requires user input using showQuickInput.

In that case, the screen reader preempts itself and reads the quick input prompt instead of the info message.

I think this is probably expected behavior then, though if you have any suggestions for showing progress in a case like this. Maybe we just delay the info message until after the input.
