### ISSUE TITLE
Pressing Esc does not cancel debugging

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#85078]
Originally reported in Python extension https://github.com/microsoft/vscode-python/issues/8626

Version: 1.41.0-insider (user setup)
Commit: fdeb9aa9b8306a2d3da989ccb9d2ad288d0ae347
Date: 2019-11-08T05:28:30.394Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

### Steps to Reproduce:

1. Open a workspace. Delete `.vscode/launch.json` if any.
2. Install the python extension. Open a python file which activates the extension.
3. Debug - Start Debugging (or press F5)

<img width="604" alt="屏幕快照 2019-11-16 下午4 55 18" src="https://user-images.githubusercontent.com/11925432/68990752-ebf1e480-0891-11ea-872f-a42adbec6258.png">

4. press ESC to cancel

But python debugging will be started.

### Reason:

When there is no launch configuration present, and we press F5, vscode calls [DebugConfigurationProvider.provideDebugConfigurations()](https://code.visualstudio.com/api/references/vscode-api#DebugConfigurationProvider) API for fetching the debug configurations. In the python extension, that shows a quick pick of options. But on cancelling on the quick pick, debugging is not cancelled.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
I have investigated this. And the issue seems to be that the `resolveDebugConfiguration` of the python extension opens the quickPick. The quickPick is cancelled by the user, and the `resolveDebugConfiguration` should return `undefined`. However the `resolveDebugConfiguration` does not return `undefined` it returns the `config` object and VS Code happily continues with debugging.
ANd this is designed behavior. More about this can be found in the comments [here](https://github.com/Microsoft/vscode/blob/66f6fe0f547c9cb41fe4e2f04a4b4f479baf92a6/src/vs/vscode.d.ts#L9252)
So please fix this on the Python side by return undefined.
If there is something else that VS Code needs to do please let me know and I can reopen this issue. Thanks

**Comment by karrtikr** [comment]
Thanks a lot @isidorn . Btw the link you mentioned points to a 404 page.

**Comment by isidorn** [comment]
Appolgoies. Here's the correct link
https://github.com/Microsoft/vscode/blob/65050271c24788f74456cc9210931dbecf9c79c5/src/vs/vscode.d.ts#L9252
