### ISSUE TITLE
Settings: Fix subpixel AA issues

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#85106]
Each TOC entry which is not bold doesn't have subpixel AA. This doesn't repro once commenting out this opacity value: https://github.com/microsoft/vscode/blob/db597dff739d46d487499c93fb765f6d98447ef4/src/vs/workbench/contrib/preferences/browser/media/settingsEditor2.css#L219

![Screenshot from Tue 19 Nov 2019 10:31:02 AM CET](https://user-images.githubusercontent.com/22350/69134609-10c7a100-0ab8-11ea-9f1b-83aaf135375f.png)

**Comment by roblourens** [comment]
Is this for the search box too? @JacksonKearl did you look into that already, here or in the extension viewlet search? I can't remember who just mentioned it.

**Comment by JacksonKearl** [comment]
I fixes search the other day, on current insiders both search and the toc are subpixel AA'd.

**Comment by roblourens** [comment]
So the settings tree is correct but the TOC tree is wrong, right? I can't figure out what the difference is because they are set up exactly the same with backgrounds and an opacity. And I don't really want to get rid of the opacity because it looks nice. 

Trying to remove the things that are different about the TOC tree like absolute positioning and z index, it doesn't make any difference. Some combinations fix it for some rows but not others randomly?

![image](https://user-images.githubusercontent.com/323878/69498914-ebfd7000-0ea1-11ea-9616-ca226bb63437.png)

Any idea what else affects this?

**Comment by JacksonKearl** [comment]
Currently on my machine, on Insiders, the TOC has working subpixel AA. Is it different on yours?

**Comment by roblourens** [comment]
On windows, the latest insiders, the toc is not correct. This is over RDP, does that affect it?
