### ISSUE TITLE
Breakpoint decoration isn't visible for the line I am paused on

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#85148]
![Nov-19-2019 10-38-03](https://user-images.githubusercontent.com/323878/69175482-b67b1000-0ab8-11ea-80a6-8f998f88045e.gif)

If it is an inline breakpoint, then I see the breakpoint inline, but here I am missing any breakpoint decoration.

This is the new debug adapter which supports inline breakpoints but I think not getBreakpointLocations yet @connor4312

**Comment by connor4312** [comment]
I added breakpoint locations last week, if you're on a new build they should be there.

**Comment by isidorn** [comment]
This glyph margin actually has the correct class of `codicon-debug-breakpoint-stackframe`
However the codicon which we use is wrong "\eb8b".
@misolori  I think we broke this with breakpoint codicon PR, since this was working last week. I am not sure if the idea for the breakpoint + stack frame icon is a composition of icons, or do we have one special codicon for this. Can you maybe look into this one?

**Comment by misolori** [comment]
@roblourens do you have repro steps?

**Comment by isidorn** [comment]
@misolori sorry, here are the steps. Put a breakpoint on this line and start debugging
```
console.log('Hello from Zurich')
```

**Comment by misolori** [comment]
Well I did try the basic breakpoint test and see this working:

![image](https://user-images.githubusercontent.com/35271042/69272406-6e78ed80-0b8b-11ea-9d4c-8f258368b8ac.png)

So not sure if there are other steps to get into the state from above.

**Comment by misolori** [comment]
Tried this out debugging a react app using the Chrome debuger and I think I see the problem now:

![image](https://user-images.githubusercontent.com/35271042/69273374-193ddb80-0b8d-11ea-9879-3a9b94c303e7.png)

**Comment by misolori** [comment]
So this issue is due to the fact that we try compose two icons as one (as an overlay using psuedo elements) because we use different colors for the stackframe + breakpoint icons. We can do this for inline breakpoints but it gets complicated in the gutter because the class `codicon-debug-breakpoint` is always set. 

@isidorn can we setup the glyph margin classes to only ever show a single class? That would help me make it possible to do the icon overlay. We'd also need to have separate state of a `stackframe` and `stackframe-and-breakpoint` which i don't think we currently have.

**Comment by isidorn** [comment]
@misolori we could fix the maring classes to only ever show a single breakpoint class.
However due to the architecture of the current approach this is not so nice to do on my end (I have two editor contributions, one is only aware of breakpoints, only is one aware of stack frames).
Though if this is the only way we get this right, than I can do some refactoring and cleanup the class names (though that is more realistic for December)

**Comment by misolori** [comment]
I do think cleaning up the class names is the right way to do it, my only fear is having to wait two months for this since we don't have a release in December. It's not like this completely broken because we still show the stackframe icon on the line you are paused on. I'm ok waiting in order to get it right.

**Comment by isidorn** [comment]
Let's leave it for November for now and I might look into this next week. Thanks

**Comment by roblourens** [comment]
Any way this can get in to November? I think it's not a very good user experience currently, didn't we handle the same bug as a candidate last month?

**Comment by misolori** [comment]
@roblourens @isidorn I took another stab at this and think I have it working, can you both test this out using my branch `misolori/debug-breakpoint` and let me know if this solves this issue?

![gif](https://user-images.githubusercontent.com/35271042/70191303-2ee2f300-16ad-11ea-8b6b-d9da90766ae8.gif)

**Comment by eamodio** [comment]
@misolori From your video, I would still expect that after you toggle the first BP off and then back on, that the gutter would have the red dot. Basically, IMO, there should be no case where there is a BP on a line that the gutter doesn't have a BP dot

**Comment by misolori** [comment]
@eamodio my video mirrors what happens on Stable right now, but I do see what you are saying.

**Comment by isidorn** [comment]
@roblourens agree, we should get this into novemer.
@misolori thanks for looking into this, I'll check out your PR. And build up from there if needed.

**Comment by isidorn** [comment]
@misolori I have tried out your branch and the issue is not fixed for me. My program is 
`console.log('hello there');`
If I set the brekpoint on the line once the program is stopped the breakpoint red dot will not be decorated.
I have a couple of issues still on my plate, once I get rid of them I can look into this.

**Comment by isidorn** [comment]
Follow up work https://github.com/microsoft/vscode/issues/86469

**Comment by gjsjohnmurray** [comment]
Still seems to be broken if the breakpoint is conditional, e.g.

![image](https://user-images.githubusercontent.com/6726799/70444901-86f56d00-1a92-11ea-8a87-91747c833709.png)

Here's the correct appearance when the stack pointer is elsewhere:

![image](https://user-images.githubusercontent.com/6726799/70445054-c91eae80-1a92-11ea-9717-03e780f22cfc.png)

**Comment by isidorn** [comment]
@gjsjohnmurray  Thanks for pointing that out. I plan to fix that issue as part of https://github.com/microsoft/vscode/issues/86469
