### ISSUE TITLE
Debug console twisties no longer(?) change cursor type to pointer on hover

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#85152]
Break in some app and log some object. Hovering the lines/twisties currently uses the text cursor but should use `pointer`:

![image](https://user-images.githubusercontent.com/2193314/69180011-648ab800-0ac1-11ea-8c50-f0a049a2713e.png)

**Comment by misolori** [comment]
It appears that the margins around the icon are what cause the pointer to not show up, because it adds it space outside of container as opposed to around it like padding:

![image](https://user-images.githubusercontent.com/35271042/69194233-7a0ddb00-0add-11ea-8773-c7353ddf8988.png)

Will see if I can adjust the CSS to get this to work.

**Comment by misolori** [comment]
I swapped the margins out for padding, this should fix the issue now.

FYI @joaomoreno since this for the tree widget, I double checked all of our trees to make sure nothing was impacted.

**Comment by joaomoreno** [comment]
Let's keep an eye out for bugs in the upcoming days. :+1:

**Comment by isidorn** [comment]
@misolori thanks for pushing a fix for this.

**Comment by misolori** [comment]
Verification steps: when hovering over items in the debug console, ensure that hovering from the text the to icon/twisties doesn't make the cursor change.
