### ISSUE TITLE
Variable Substitution in launch.json not visible in debug configuration provider

### ISSUE THREAD

**Issue by mike-lischke** [microsoft/vscode#85206]
Issue Type: <b>Bug</b>

According to [this paragraph](https://code.visualstudio.com/docs/editor/debugging#_variable-substitution) variable substitution is supposed to work also in launch.json, used to configure debug sessions. However it appears not to work, at least I don't get the resolved variables in my `DebugConfigurationProvider.resolveDebugConfiguration` function. The passed in options still contain the unresolved variables, making it so impossible to use the given values (e.g. the current file, given as `${file}` to set up my debugger.

Here's a sshot that shows the extension host with the launch setting and the debug config resolver:

<img width="2294" alt="var-substitution" src="https://user-images.githubusercontent.com/2398704/69246518-2963b400-0ba9-11ea-9b62-5cb01fa1fa73.png">

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (9.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
dot|Ste|0.0.1
numbered-bookmarks|ale|6.2.1
spellright|ban|3.0.48
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|1.9.1
xml|Dot|2.5.0
vscode-wasm|dts|1.2.1
gitlens|eam|10.2.0
tslint|eg2|1.0.44
php-intellisense|fel|2.3.13
vscode-mysql|for|0.4.0
duk-debug|Har|0.5.6
live-html-previewer|hdg|0.3.0
vscode-auto-open-markdown-preview|hnw|0.0.4
beautify|Hoo|1.5.0
svg|joc|1.0.5
vscode-phpfmt|kok|1.0.30
vscode-antlr4|mik|2.2.3
prettify-json|moh|0.0.3
debugger-for-chrome|msj|4.12.1
vscode-yacc|se2|1.1.0

</details>

**Comment by weinand** [comment]
Variable substitution occurs after `DebugConfigurationProvider.resolveDebugConfiguration` and before passing the launch config to the debug adapter.

**Comment by mike-lischke** [comment]
But how can I then determine the actual values for the variables if not in that method, which is **supposed** to resolve the configuration?

**Comment by weinand** [comment]
All resolved values are available in your debug adapter which is part of your extension.

**Comment by mike-lischke** [comment]
Hmm, sorry, that makes not much sense given the description of the resolve function:

> Resolves a [debug configuration](#DebugConfiguration) by filling in missing values or by adding/changing/removing attributes.

How can I change attributes, if I cannot understand them? Seems there is a discrepancy between the purpose you intent and what can be understood from the description.

That bears a side question: if the resolve function is not intented to validate configuration values (and cancel the debug session if something is wrong), what else should we use instead for that kind of processing?

**Comment by weinand** [comment]
The description of `resolveDebugConfiguration` makes a lot of sense since "filling in missing" values and "adding/changing/removing attributes" can be done without a need to see the "final" values.

Evidence for this you can see in node-debug's [resolve method](https://github.com/microsoft/vscode-node-debug/blob/ba9bf6e900e38dcaeaef25221427739f5da24c54/src/node/extension/configurationProvider.ts#L60-L174).

Any validation that can only be performed on the final values can be done (and is actually done) in the debug adapter (see [`launchRequest`](https://github.com/microsoft/vscode-node-debug/blob/ba9bf6e900e38dcaeaef25221427739f5da24c54/src/node/nodeDebug.ts#L857-L990) in the node-debug DA).

Having said this, I can still imagine to introduce a new `aboutToLaunch` method on the `DebugConfigurationProvider` that receives the "final" fully resolved debug configuration.

I've changed this issue into a feature request and I'm now waiting for upvotes...

**Comment by mike-lischke** [comment]
I see your points, however launching the debug adapter might involve quite a few things to do, which are unnecessary when there are problems with the files being debugged. Hence my original idea was to figure out everything in the resolve function upfront, before I even create the debug adapter. I'll move my validation logic to `launchRequest` then. Thanks for the hint.

A new validation function might still be useful (be it named `aboutToLaunch` or `validate` or whatever).

**Comment by weinand** [comment]
We will add another hook `resolveDebugConfiguration2` to the `DebugConfigurationProvider` that receives the debug configuration with all variables resolved.

I've created an extension API req for this: https://github.com/microsoft/vscode/issues/87450

**Comment by mike-lischke** [comment]
That's great news @weinand! As for the naming I suggest `processResolvedDebugConfiguration` to indicate this something that follows the resolution step. Another name could be `validateDebugConfiguration` which also indicates that this is a step after resolution and should be used to check all final values for their correctness (do file exists? etc.). I prefer the second name, now that I found it :-)

**Comment by connor4312** [comment]
I think `processResolvedDebugConfiguration` works. `validateDebugConfiguration` implies what logic the debug adapter is doing in that method, which may not be the same in all cases. For instance I can image we might use that step in js-debug to resolve read the environment file, if provided, into inline environment variables, which would streamline some of our internal logic.

**Comment by isidorn** [comment]
`resolveDebugConfiguration2` works best for me. The name is clear that it does the same thing as `resolveDebugConfiguration` with minor differences.
`processResolvedDebugConfiguration` is also ok for me.

Some other naming ideas: `handleResolvedDebugConfiguration`, `resolveResolvedDebugConfiguration` (sounds funky)

`validateDebugConfiguration` does not work for me since it sounds like it does more than what it actually will do

**Comment by weinand** [comment]
@jrieken `processResolvedDebugConfiguration` or `resolveDebugConfiguration2`?

**Comment by weinand** [comment]
After talking to @jrieken we agreed on the expressive `resolveDebugConfigurationWithSubstitutedVariables` (which becomes a nominee at the VS Code longest-variable-name contest).

**Comment by isidorn** [comment]
Works for me. At least it is clear what it does exactly.

**Comment by mike-lischke** [comment]
If it's only about the variables substitution you could go another route: provide an API to resolve the values. It would be totally fine for me to call that to resolve all variables and act on them in the original `resolveDebugConfiguration`. You probably already have such a function interally. Just make it public and you you will not need that new hook.

**Comment by weinand** [comment]
@mike-lischke yes, we've considered this as well but providing (and using) a variable resolver function as API is tricky because variables can be tied to commands which might result in arbitrary user interactions (e.g. if an interactive variable is used more than once, we only show the UI once and apply the resulting value in different places). So we really want to stay away from that approach and the two-phase approach instead.

**Comment by weinand** [comment]
I've added a new optional hook `resolveDebugConfigurationWithSubstitutedVariables` to the `DebugConfigurationProvider`. 
Support for it will be available in the next Insiders (or immediately if you are running out of source).

Please note: this is proposed API which might still change until the end of this milestone (January).

**Comment by weinand** [comment]
@mike-lischke the new API is now official and in vscode.d.ts.
