### ISSUE TITLE
'Peek Definition' missing from context menu

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#85218]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.41.0-insider (bd8425fa9b6427dca51e882d39b9ae764c55e08c, 2019-11-20T09:17:36.311Z)
OS version: Windows_NT x64 10.0.17763

![image](https://user-images.githubusercontent.com/6726799/69251308-1f41b580-0ba9-11ea-93b4-f6ff229bdfbb.png)

The keyboard equivalent (Alt+F12 on Windows) **does** still work.

On 1.40.1 it is there:

![image](https://user-images.githubusercontent.com/6726799/69251194-f8837f00-0ba8-11ea-9d52-fdd1320d5b49.png)

**Comment by jrieken** [comment]
We have done that on purpose in an effort to cleanup the context menu. All peek-commands are still there, e.g accessible via keybindings or via the command palette but we redesign the context menu like this... Two options that I see

1. Add another group to the context menu which contains peek commands, like Peek Definition, Peek Declaration, Peek Implementation, Peek References, 
1. Toggle commands when holding `alt`, similar to editor title actions, e.g when hold <kbd>alt</kbd> while the menu shows goto-commands would turn into their *alt*ernative peek-commands

Personally, I'd prefer option 2 because it will keep the context menu small and gives all the power, however at the cost of being harder to discover.

**Comment by jrieken** [comment]
For completeness - this has been mentioned before here: https://github.com/microsoft/vscode/issues/83752#issuecomment-553127061

**Comment by gjsjohnmurray** [comment]
How about grouping them all on a "Peek" submenu? That'd make them discoverable to folk who rely on right-click to find out what they can do on things (as opposed to reading the doc).

**Comment by gjsjohnmurray** [comment]
Maybe this case can get some activity underway on #9827 🙏

**Comment by jrieken** [comment]
Yeah, it would require to implement sub menus. I'll do some exploring

**Comment by jrieken** [comment]
I have pushed this to master

<img width="635" alt="Screenshot 2019-11-21 at 12 26 41" src="https://user-images.githubusercontent.com/1794099/69334798-d991f500-0c5b-11ea-8186-5de0e9e8faa6.png">

**Comment by gjsjohnmurray** [comment]
I like this. Just wondering why the sequence of "Peek" options differs from the sequence of "Go to" options.

**Comment by jrieken** [comment]
The order should now be the same... Anyways, we aren't sold on the sub menu approach yet. There are concern about this being too noisy and therefor some questions why you have missed "Peek Definition". Is that something you simply noticed? Is that something you use (regular/rare) but only through the context menu and not via keybinding or F1? Is the only peek command that you are missing?

**Comment by jrieken** [comment]
We will stick with the sub context menu for now.
