### ISSUE TITLE
Debugging EH opens large.ts with Mankala contents and loads mock debug

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#85230]
Can not repro in insiders, only latest out of source.

1. `scripts/code.sh`
2. Get the starter extension sample
3. Debug extension
4. Notice that the `large.ts` file gets opened with the Mankala contents. And the mock debug debugeer seems to be registered

This is breaking my flow of out of source eh debugging.

fyi @bpasero

**Comment by weinand** [comment]
@bpasero I believe this problems occurs because I've added "onDebug" to the "activationEvents":
```json
	"activationEvents": [
		"onFileSystem:memfs",
		"onDebug"
	],
```
And now the "vscode-api-tests" extension interferes with running out of source.

I think keeping "vscode-api-tests" in the VS Code extensions folder is not a good idea.
The Web app should have its own extension folder.

**Comment by bpasero** [comment]
@weinand understood, not good. The advantage of reusing the same extensions folder for web version is that all extensions will just work out of the box because we can load them all at once. 

If you want to take a stab at this while I am out, there is just one place where we hardcode the folder:

https://github.com/microsoft/vscode/blob/a825aaaa909ef33eee11cb1d322e9a64981978d2/scripts/code-web.js#L19

We would need to somehow add another folder with additional extensions to load for this one extension and then could move the things over.

**Comment by isidorn** [comment]
Thanks for the fix. This works as expected now, adding verified label.
