### ISSUE TITLE
Editor icons (SVG): alignment and rendering issues

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#85297]
Noticed this on Windows when zooming in on an opened editor (on todays insider build):

![Screenshot 2019-11-21 at 13 21 40](https://user-images.githubusercontent.com/900690/69337769-f7625880-0c61-11ea-807f-141028a2c006.png)

The 2 first icons are coming from extensions and thus are SVGs. I see 2 issues:
* the alignment seems off, they do not look like belonging to the other icons
* they render with greyscale anti-aliasing (for some reason) and not nicely like the others with LCD rendering

**Comment by misolori** [comment]
I’ll look into why they aren’t aligned. And the grayscale rendering is likely due to the fact that the extension icons are rendered as an Image while the action bar icons are rendered as text (icon font).

**Comment by misolori** [comment]
So the icon alignment is correct here:

![image](https://user-images.githubusercontent.com/35271042/70255973-87150600-173c-11ea-9129-1db4032b382d.png)

In order for the split icon to be aligned to the grid it needed to be placed off-centered. This is due to the composition of the icon and to have the split line centered:

![image](https://user-images.githubusercontent.com/35271042/70256214-f3900500-173c-11ea-93e2-28100079acd6.png)

**Comment by misolori** [comment]
Already fixed via https://github.com/microsoft/vscode/commit/7cdd76d68935eef96f027ebe11c9a53976aee581
