### ISSUE TITLE
VS code launch problem

### ISSUE THREAD

**Issue by MugeshBTech** [Microsoft/vscode#8532]
- VSCode Version: V1.1.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. Not able to run the vs code with chrome debugger
2. Getting error - > [debugger-for-chrome] Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222
3. Find the attachment, i have used many config in launch.json
4. Help me on this
![image1](https://cloud.githubusercontent.com/assets/16976667/16464030/01b75368-3e56-11e6-9753-b7d7432d21f0.png)
![image2](https://cloud.githubusercontent.com/assets/16976667/16464031/01c0ecd4-3e56-11e6-9d1b-ed004b7a4939.png)

**Comment by MugeshBTech** [comment]
can anyone help me on the above issue

**Comment by bgse** [comment]
The error message suggests that the remote debug port you specified is not open.

Maybe you have Chrome already open when launching, I think there was an issue where it would not accept remote debugging port when it is already open.

So you could try to close all Chrome instances you have open, and then try the launch.

I personally only use remote-attach, e.g. launch Chrome from the command line, and then use an attach configuration with VSCode, you could try that if the above does not help.

Otherwise, your question might be better placed here:

https://github.com/Microsoft/vscode-chrome-debug/issues

**Comment by bpasero** [comment]
Please report this to the chrome debugger extension.

@weinand fyi
