### ISSUE TITLE
RegEx

### ISSUE THREAD

**Issue by byronferguson** [microsoft/vscode#85337]
Issue Type: <b>Bug</b>

While trying to clean-up a SQL file to createt he `DROP` statement from a series of `CREATE` statements I needed to remove the body. My intention was to use the Find/Replace with RegEx to select the body and replace it with an empty string. The RegExp below works successful for the provided example; however, VSCode does not find any matches on the file.

`\s\([\s\S]*?\)`

```
DROP TABLE abilities (
    id bigint NOT NULL,
    name character varying,
    subject character varying,
    "create" boolean DEFAULT true,
    read boolean DEFAULT true,
    update boolean DEFAULT true,
    delete boolean DEFAULT true,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone
);
```

*Expected Result*
`DROP TABLE abilities;`

[RegEx Storm - Example](http://regexstorm.net/tester?p=%5c%28%5b%5cs%5cS%5d*%3f%5c%29&i=DROP+TABLE+abilities+%28%0d%0a++++id+bigint+NOT+NULL%2c%0d%0a++++name+character+varying%2c%0d%0a++++subject+character+varying%2c%0d%0a++++%22create%22+boolean+DEFAULT+true%2c%0d%0a++++read+boolean+DEFAULT+true%2c%0d%0a++++update+boolean+DEFAULT+true%2c%0d%0a++++delete+boolean+DEFAULT+true%2c%0d%0a++++created_at+timestamp+with+time+zone%2c%0d%0a++++updated_at+timestamp+with+time+zone%2c%0d%0a++++deleted_at+timestamp+with+time+zone%0d%0a%29%3b)

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.43GB free)|
|Process Argv|--max-memory=4096|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|2.0.1
TabOut|alb|0.1.6
flutter-snippets|ale|2.0.0
expressjs|ama|2.0.0
vscode-tailwindcss|bra|0.2.0
bracket-pair-colorizer-2|Coe|0.0.28
vscode-svgviewer|css|2.0.0
dart-code|Dar|3.6.0
flutter|Dar|3.6.0
vscode-eslint|dba|1.9.1
vscode-coffeescript-preview|dre|1.0.1
es7-react-js-snippets|dsz|2.4.4
gitlens|eam|10.2.0
EditorConfig|Edi|0.14.2
docker-explorer|for|0.1.6
html-slim-scss-css-class-completion|gen|1.5.23
mysql-syntax|jak|1.3.1
vscode-gutter-preview|kis|0.23.0
vusion-peek|lin|0.1.2
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
vscode-docker|ms-|0.8.2
vsliveshare|ms-|1.0.1293
debugger-for-chrome|msj|4.12.1
awesome-flutter-snippets|Nas|2.0.3
vetur|oct|0.22.6
vscode-versionlens|pfl|0.24.0
material-icon-theme|PKi|3.9.1
quicktype|qui|12.0.46
LiveServer|rit|5.6.1
sass-indented|rob|1.5.1
vue-vscode-snippets|sdr|1.8.0
code-settings-sync|Sha|3.4.3
nativescript|Tel|0.11.0
vscode-icons|vsc|9.5.0
vscode-todo-highlight|way|1.0.4
codedox|wig|1.3.0
vscode-import-cost|wix|2.12.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.7.2
markdown-pdf|yza|1.4.1

(4 theme extensions excluded)

</details>

**Comment by IllusionMH** [comment]
Yep, VS Code works a bit strange with RegExps that should match multiline text (especially global search, see #75265)

In your case you can workaround it with explicit `\n` in characters class `\s\([\s\S\n]*?\)`

**Comment by alexandrudima** [comment]
@IllusionMH suggestion is correct. When you want to do a multiline regex search with us, it is best to include `\n` in there. And now, for the long explanation:

In the editor, in the text buffer, the text of the file is not normally available in a single JS string. We use a piece tree datastructure to hold the text, it is basically a tree of smaller strings... Without going into too much details, this is a good thing to do (you can read more if you want to [here](https://code.visualstudio.com/blogs/2018/03/23/text-buffer-reimplementation)).

When dealing with regex find, we need to delegate the regex matching to the regex implementation built-in to JavaScript. But the native built-in regex cannot accept as input a piece tree text buffer, so we need to allocate a native JS string from our text buffer.

We would prefer to search for the regex line-by-line, because then we can loop through all the lines, allocate a string for the line content, match it using the provided regex, and then stop referencing it, which will make it be GCed quite quickly (as a short lived object) and which does not pose big problems because lines are typically short.

But when a regex is multiline, we basically need to create a single huge string with all the content of the file, and match all the content of the file using the provided regex.

When having a large file (GBs), creating a single JS string with the contents of the file, could be very slow and causing freezes or could even lead to OOM situations.

So, given all of the above, we try really hard to avoid allocating the huge string of text of all the file and we will do so only when we are certain the intent of the regex  was to match multiline text. The presence of `\n` in the regex will trigger us to go to this multiline / full file mode.

Given these complications ... We think it is not that big of a deal that we want regexes in the find widget to be explicit about multiline and include a `\n` in there...

**Comment by IllusionMH** [comment]
@alexandrudima thanks for the details here!
I found and used workaround, however din't grasp that pierce tree storage means that there is no single string storage that is easy to match against. Now its clear why it is this way.
