### ISSUE TITLE
UX to show replace/insert behaviour for extensions

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#85376]
![image](https://user-images.githubusercontent.com/3372902/69415208-7e700900-0d14-11ea-885f-ab73ee19bc3e.png)

//cc @joaomoreno

**Comment by joaomoreno** [comment]
@jrieken I can repro on Windows. A strange horizontal line appears under the closing quote character.

**Comment by jrieken** [comment]
Yes - that's a strikeout showing you what text will be overwritten to the right. Having this with quote is a little unfortunate because it looks weird... Open for suggestions. This is the current approach explained

**Insert-mode** `("editor.suggest.insertMode": "insert")`

User wants insert, but suggestion will *not* insert (it replaces), show a strikeout for the text that will be removed

<img width="403" alt="Screenshot 2019-11-22 at 10 48 19" src="https://user-images.githubusercontent.com/1794099/69415860-aad85500-0d15-11ea-8019-96847149bae4.png">


**Replace-mode** `("editor.suggest.insertMode": "replace")`

User wants replace, but suggestion will *not* replace (it inserts), show the text that won't be replaced italic. 

<img width="379" alt="Screenshot 2019-11-22 at 10 50 41" src="https://user-images.githubusercontent.com/1794099/69416002-ef63f080-0d15-11ea-9784-c48977004c55.png">

**Comment by jrieken** [comment]
Modifying the text rendering is the alternative for tweak the foreground color - something that doesn't work well because there is already symbol-highlight colors. If we wanna stick to text decorations we could only do italic for the "unexpected case"

**Comment by joaomoreno** [comment]
I have thought about something else I should've said in the standup: could/should these UI affordances be opt-in? I wonder if the average user is really interested in knowing what suggest will effectively do? Personally, I always feel that if suggest somehow does something I didn't expect it to, it's always easy to just delete some text and try again or simply type it myself.

I see some users would find it useful, but maybe we make them opt in to it via a setting?

**Comment by jrieken** [comment]
Sure, adding a setting is easy (indeed I had one when this was even more prominent) but I think we should still be designing a good solution for those that have this turned on. So, quid pro quo: let's come up with a good design and then with a setting to hide it

**Comment by jrieken** [comment]
related item: https://github.com/microsoft/vscode/issues/10266
