### ISSUE TITLE
Copy Paste Doesnt work

### ISSUE THREAD

**Issue by abhiatg777** [microsoft/vscode#85446]
Issue Type: <b>Bug</b>

Copy Paste doesnt work

VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:47:44.719Z)
OS version: Darwin x64 18.7.0

**Comment by bmtdh** [comment]
This is a valid problem. Happening for multiple people in the office using MacOS Mojave. If you have something in your clipboard, a string of text for example and you double click to highlight another string of text and paste it no longer replaces it just pastes what you were trying to replace in the middle of the highlighted word. I have to manually highlight the word I want to replace, no longer able to double click to highlight.

<img width="268" alt="Screenshot 2019-11-25 at 09 13 18" src="https://user-images.githubusercontent.com/44874175/69527267-dbadc980-0f63-11ea-94e4-aab2a1ad626a.png">


Above image shows it now pastes the new item in the middle of the highlight area after selecting via double click rather than replacing.

Thanks!

**Comment by egamma** [comment]
@bmtdh thanks for adding more details, but please provide individual steps so that we can precisely reproduce the problem. For example,

1. this is the contents of the document, this the text in the clipboard
2. this is the current selection
3. now you paste
4. this is what I get
5. this is what I expect.

**Comment by bmtdh** [comment]
1. Document in my case is any .js or .ts or .tsx file 
2. Current selection can be any string, in my case it is a variable name. I double click a varable name that I want to copy and replace via pasting
<img width="188" alt="Screenshot 2019-11-25 at 09 46 26" src="https://user-images.githubusercontent.com/44874175/69529576-78726600-0f68-11ea-9be2-8a1228c63ba8.png">

3. Now I press cmd + v
4. The location where my mouse was when I double clicked to make my current selection is where the clipboard data gets pasted, rather then replacing the selection
<img width="192" alt="Screenshot 2019-11-25 at 09 46 56" src="https://user-images.githubusercontent.com/44874175/69529636-9213ad80-0f68-11ea-91b1-955a8ba0d51d.png">
It looks like the entire word is selected.
But in reality when I paste it pastes in the location I performed the double click
<img width="268" alt="Screenshot 2019-11-25 at 09 13 18" src="https://user-images.githubusercontent.com/44874175/69529710-afe11280-0f68-11ea-8396-64a5ea20ffe6.png">
5. I expect the paste to replace the selected content.


It seems like the issue is actually the selecting of content not the pasting because if I manually select a word by clicking and dragging it works fine.

Thanks!

**Comment by glarivie** [comment]
Same issue for me ✋ 
Same OS, same behavior.

**Comment by rebornix** [comment]
I'm using 1.40.2 and tried following with content 

```javascript
const stringToCopy = ""
const stringToPaste = ""
```

* Double click `stringToCopy` and press `Cmd+C`
* Double click `stringToPaste` and press `Cmd+V`

![Kapture 2019-11-26 at 11 11 18](https://user-images.githubusercontent.com/876920/69664750-d4f38500-103d-11ea-98c9-7883f91fc55e.gif)

but I didn't reproduce this issue. Did anyone know what I miss here?

It would be great if you can try follow to help narrow down the issue

* Disable all extensions by `code --disable-extensions` and see if you can reproduce
* Go to Settings (JSON) and comment out all custom settings and see if you can still reproduce  

Thanks!

**Comment by jwthomp** [comment]
Using code-insiders I am able to reproduce with --disable-extensions

```
$ code-insiders --disable-extensions .
  [Able to repro]

$ code-insiders --version
1.41.0-insider
a63d88ec550107a66c08d813fb5d3c32c9e131a7
x64
```

**Comment by bmtdh** [comment]
It is intermittent for sure, doesn't happen all the time. I am also now noticing then when I do double click to copy, it highlights a single word but actually it is copying the entire line... Intermittent again.

Thanks!

**Comment by glarivie** [comment]
Same issue with Catalina...

**Comment by rebornix** [comment]
@bmtdh @glarivie could you check the status bar and check the selection status to see if it's correct or not?

![image](https://user-images.githubusercontent.com/876920/69987510-8427d480-14f4-11ea-83d1-7b12ca6a1869.png)

**Comment by bmtdh** [comment]
Always seems to be correct for me.

Thanks,

**Comment by jwthomp** [comment]
I do not see (# selected) when I've gone to paste and had my selection insert in between where my cursor was rather than replace the selection. My double-clicked selection shows itself as highlighted when this happens.

**Comment by apbendi** [comment]
I'm seeing this behavior as well on macOS Mojave. As far as I can tell, here is what is happening: when I double click an identifier, like a variable name in a JS file, there is a slight delay before the text is "actually" selected.

You can tell because once it's "actually" selected the highlight color changes (becomes slightly darker). If I'm fast enough and happen to hit cmd-V before that occurs, it seems to copy the whole line, rather than just the identifier I'm expecting.

You can see the color-change delay here:

![selection-delay](https://user-images.githubusercontent.com/1479802/69994405-d16b6c80-151b-11ea-9178-103cf9dae578.gif)

**Comment by jwthomp** [comment]
@apbendi I've seen that behavior as well. The other one where you highlight the text but insert it inside seems to happen more if you double click between two letters. It's not consistent, but highly reproducible.

**Comment by rebornix** [comment]
This looks like caused by https://github.com/microsoft/vscode/issues/83150 and tomorrow's Insiders should have this issue fixed.
