### ISSUE TITLE
Panel size is not remembered correctly when panel is moved to the right

### ISSUE THREAD

**Issue by klaussner** [microsoft/vscode#85451]
- VSCode Version: 1.41.0-insider
- OS Version: macOS 10.15

Steps to Reproduce:

1. Open a new window and the panel.
2. Move the panel to the right.
3. Make the panel bigger.
4. Close the window and open a new one.
5. Open the panel.
6. The panel opens at the bottom instead of on the right and it's too big.

Video of the reproduction steps: https://streamable.com/fkcox.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sbatten** [comment]
The problem is that the panel position is not being saved on window close but on shutdown. This won't reproduce on Windows or Linux for that reason (window close = shutdown).

**Comment by sbatten** [comment]
Ignore my previous statement, the correct root cause is that when a new empty window is created on macOS and VS Code is already running(even without a window), the new window is always a new workspace id. However, from a cold start (VS Code is not running), the new empty window uses the same workspace id as before.

Panel position and visibility are stored in workspace storage and therefore in the repro case, do not exist. The size is written to global storage so it is restored. 

@bpasero Does this workspace id generation sound correct? It seems strange that a new window from cold and hot starts give differing results if no windows are open from the beginning.

For the panel state, I could check if this is an empty workspace and just ignore workspace storage and revert to defualts. But, I want to check that this is how storage is expected to work.

**Comment by bpasero** [comment]
This is correct, macOS has the concept of running apps even without windows. If you then go and click the app, it will open a new empty window with new workspace id. Starting VSCode when it is not running will restore any previous workspaces, including empty ones.

**Comment by sbatten** [comment]
Still seems strange to treat clicking the app icon differently when no windows are open based on the app running in the background. But perhaps that's what Mac users expect

**Comment by bpasero** [comment]
@sbatten my understanding is that clicking on the app icon when no window is open acts like "New Window" and not "Restore Window from Previous Session".

**Comment by sbatten** [comment]
I've updated the restoration logic to ignore the global storage panel size when we aren't restoring positions but rather just using defaults.

**Comment by sbatten** [comment]
new fix is similar but will restore size if the position matches the last saved panel size

**Comment by RMacfarlane** [comment]
@sbatten What's the expected behavior now?

Following the original repro steps, I still see the panel being restored to the bottom instead of the right

**Comment by sbatten** [comment]
@RMacfarlane Following the original steps should show the panel at the bottom, but the size should be appropriate.
