### ISSUE TITLE
Can't install any of plugins from store. It's always showing notification on bottom-right side "Failed to install"

### ISSUE THREAD

**Issue by Toomavic** [microsoft/vscode#85489]
![image](https://user-images.githubusercontent.com/10185045/69492919-f6733600-0eb0-11ea-846c-d7ad8988480b.png)

![image](https://user-images.githubusercontent.com/10185045/69492934-186cb880-0eb1-11ea-9903-871372eb82b6.png)

I had a powerful internet connection. I really don't know what is blocking VScode from installing the plugins.

I have to manually download them from store then install them locally. I had to to this for each plugin!! That's not acceptable I think

**Comment by sandy081** [comment]
Please follow these steps and provide us necessary info

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - Help -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by Toomavic** [comment]
@sandy081 

Hi Sandeep Bhai, Thanks for information. Unfortunately, I can't access the above link. 


and this is what I got when I opened the console
![image](https://user-images.githubusercontent.com/10185045/69563656-2ce8a800-0fba-11ea-8940-fbe403da1fb9.png)

**Comment by sandy081** [comment]
So it looks a DNS issue, can you please try configuring your DNS like pointing to 1.1.1.1 as suggested here? 1.1.1.1/dns. Otherwise please contact your network administrator.

**Comment by Toomavic** [comment]
@sandy081 I can't connect to 1.1.1.1/dns eithr. My network Admin says that he has nothing to do with it !!

The problem is that, I was able to install plugins 4 months ago.

**Comment by Toomavic** [comment]
Hi @sandy081 

I managed to solve this problem by setting DNS settings to 8.8.8.8 and 8.8.4.4 

I think this is caused by network admin in some countries including mine. 

Please refer to this solution in the documentation.
