### ISSUE TITLE
Vertical tab bar

### ISSUE THREAD

**Issue by Freerider689** [microsoft/vscode#85527]
Allow to display the open tabs on either the left or right side, as already existing in 
https://marketplace.visualstudio.com/items?itemName=pzuraq.vertical-tab-bar

but without out the need for the custom CSS and JS extension
https://github.com/be5invis/vscode-custom-css

**Comment by sbatten** [comment]
fyi @bpasero

**Comment by DarceyLloyd** [comment]
how do you up vote?

**Comment by ArturoDent** [comment]
@DarceyLloyd Click on the thumbs up on the top post.

**Comment by iniatse** [comment]
Wow pretty annoying if you open more then 4-5 files. That feature is a very basic feature for every IDE if you ask me.

**Comment by DarceyLloyd** [comment]
> Wow pretty annoying if you open more then 4-5 files. That feature is a very basic feature for every IDE if you ask me.

I agree, that files open thing on the left is just annoying for file explorer and the tabs scroll bar is almost un-clickable with the mouse. 80% chance to drag the tab not the 2 pixel scroll bar. This and auto import detection is one of the main reasons I still use PHP/WEB Storm. NOTE: Atom can do vertical tabs.

**Comment by iniatse** [comment]
Yes Atom can do this, but Atom does not have many extensions and features which I like from vscode.

**Comment by DarceyLloyd** [comment]
> Yes Atom can do this, but Atom does not have many extensions and features which I like from vscode.

Personally I'm not a fan of Atom, which is why I use PHP/Web Storm, also VSCode can't format php & html correctly, often till you use the code format shortcut but sometimes live typing keeps putting indents in where none should be and only code format can fix and sometimes that doesn't fix it either, but for JS its fine, TS even better, seems to pick up imports better for TS.
