### ISSUE TITLE
CallHierarchyProvider#prepare should allow to return multiple symbols

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#85533]
This is TS feedback. When you invoke call hierarchy on a symbol that has multiple definitions that the prepare call should allow to return all definitions 

/cc @rbuckton

**Comment by jrieken** [comment]
Proposal is to over this signature with an array return type:

```ts
prepareCallHierarchy(...): ProviderResult<CallHierarchyItem | CallHierarchyItem[]>;
```

**Comment by jrieken** [comment]
@rbuckton this is a follow up from https://github.com/microsoft/TypeScript/issues/31863#issuecomment-553609269. When drilling into a call hierarchy, e.g when calling `provideCallHierarchy[Incoming|Outgoing]Calls`, then the provider can return multiple items for multiple definitions but call hierarchy cannot start like that. Tho, I am unsure if that's actually an issue, e.g does the case in TS (or other languages) exist that there multiple call'ables with the same name?

**Comment by mjbvz** [comment]
Hey @rbuckton, can you please provide some example TS where there may be multiple definitions? We tried coming up with one but couldn't. If there are multiple definitions, shouldn't TS server always be able to resolve which definition is being invoked?

**Comment by rbuckton** [comment]
This issue is something like this:

```ts
// a.d.ts
declare function foo(x?: number): void;

// b.d.ts
declare function foo(x?: string): void;

// main.ts
foo(); // <-- Inspect call hierarchy here
```

For a Call Hierarchy item we normally would choose the actual definition of `foo` if we can find one, however in this case all declarations of `foo` are ambient and are split across multiple files. Which one do we pick? If we don't have a way to indicate multiple locations for a call hierarchy item, then we will likely have to resort to overload resolution to pick a declaration, yet *both* declarations will end up having the same incoming/outgoing calls (since we don't limit a call-hierarchy to a specific overload).

**Comment by jrieken** [comment]
Alright - thanks for the clarification. I'll update the API as outlined above

**Comment by jrieken** [comment]
fyi @dbaeumer

**Comment by dbaeumer** [comment]
Thanks!

**Comment by jrieken** [comment]
To verify: get latest vscode.d.ts and check that `prepareCallHierarchy` allows to return one or N items

**Comment by jrieken** [comment]
fyi - use the [vscode-dts](https://www.npmjs.com/package/vscode-dts)-utility to use the latest version of `vscode.d.ts` and/or `vscode.proposed.d.ts`

**Comment by dbaeumer** [comment]
Created https://github.com/microsoft/vscode-languageserver-node/issues/559 in LSP land to adopt when we have released stable
