### ISSUE TITLE
show clock in zen mode

### ISSUE THREAD

**Issue by CWempe** [microsoft/vscode#85540]
It would be nice if you could (optionally) enable a clock to show the current time.

There was a similar feature requested [here](https://github.com/Microsoft/vscode/issues/45528), but I want it separated from the task bar.

I like the idea to configure the position of the clock.
But just bottem right would be ok for me.

Zen mode is great to not get distracted from other things.
But you still might want to check how much time you have left till the next meeting (or the end of the current meeting). ;)

**Comment by isidorn** [comment]
I understand your request, however we will not make this as part of the core product since it is very specific behavior that not a lot of users want.

What I suggest instead is that you configure zenMode to not hide the status bar "zenMode.hideStatusBar": false,
And then install an extension which adds a clock to the status bar https://marketplace.visualstudio.com/items?itemName=Compulim.vscode-clock

Alternative is to enable zenMode to not go full screen.

Closing as we will not tackle this in another way and I believe this workarounds are just fine
