### ISSUE TITLE
Code insiders Git commit error

### ISSUE THREAD

**Issue by Danny-Dasilva** [microsoft/vscode#85569]
- VSCode Version: 1.41.0-insider
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. Add git credentials eg. user.name, password
2. add a commit to source control
3. git push with the arrow in the bottom left

this error message appears
![Screenshot from 2019-11-25 19-59-21](https://user-images.githubusercontent.com/32214239/69590635-16445000-0fbe-11ea-934c-f0267913900e.png)

git log shows this 
`fatal: cannot run /snap/code-insiders/317/usr/share/code-insiders/resources/app/extensions/git/dist/askpass.sh: No such file or directory
fatal: could not read Username for 'https://github.com': No such device or address`

git pushing from terminal works fine

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
Does such a file exist in disk?

```
/snap/code-insiders/317/usr/share/code-insiders/resources/app/extensions/git/dist/askpass.sh
```

What about this?

```
/snap/code-insiders/317/usr/share/code-insiders/resources/app/extensions/git/dist/askpass/askpass.sh
```

**Comment by PleaseStopAsking** [comment]
I just updated my insiders install this morning and am seeing the same failure on MacOS Catalina. Checking the below location shows no askpass.sh file present.

`fatal: cannot run /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/git/dist/askpass.sh: No such file or directory`

**Comment by joaomoreno** [comment]
Yup, great catch, found the issue!

**Comment by Light-Wizzard** [comment]
I see this is closed, but do not see a resolution, I have this same issue, it seems that when installing using snap, it puts the file in a folder called askpass, so the program is pointing at the wrong folder:

`/var/lib/snapd/snap/code-insiders/317/usr/share/code-insiders/resources/app/extensions/git/dist/askpass.sh`

`/var/lib/snapd/snap/code-insiders/317/usr/share/code-insiders/resources/app/extensions/git/dist/askpass/askpass.sh`

Is this just a snap installation issue?

Is there a configuration variable to change this?

**Comment by PleaseStopAsking** [comment]
@Light-Wizzard A new insider build was already released today which seems to include the fix @joaomoreno added. The issue is gone on MacOS. Check to see if a new update is available for your install.

**Comment by Light-Wizzard** [comment]
I was referencing the fix, from what I see it was a path issue:

```
From this:
../util
../ipc/ipcServer
To this:
./util
./ipc/ipcServer
```

What I am asking is, does this have a configure variable in the settings, so I can set the path to askpass, like in Qt Creator, or is this just a snap issue?

It seems that if you could set it in settings, this would fix this issue, but if it is only a snap issue, then I understand the fix, I just switched to using snap in Arch Linux Manjaro, but noticed this issue in AUR, but it was flaged as out of date, so I am asking is this just a Snap issue, if so then the fix is great when it shows up, a snap refresh right now does not pick it up, but it seems that giving you a way to edit the path would be a better solution, unless you need to run that verion of askpass, then it needs to be hard coded, otherwise this fix seems to be only a snap issue.

**Comment by joaomoreno** [comment]
It is not a snap issue. This affects all platforms. Fix is in, Insider builds are coming out now. Simply moving the file doesn't address the whole issue, as you can see from the commit. Just update to the latest Insider and confirm whether it's fixed.
