### ISSUE TITLE
Quit debug when excuting StepIn continuously

### ISSUE THREAD

**Issue by caboom04** [microsoft/vscode#85573]
I'm developing a debug server.

I implement the requets(Next, StepIn, Threads, StackTrace, etc.), event(Stopped), and it works fine when I excute step action separately. 
But when I excute StepIn continuously, by holding F11, VS Code sometimes exit debug state. According to the log, it happens when the second StepIn request returns true before Threads/StackTrace requests have done.
While I do the same action with Next, it works ok and the debug server never receive Next request between Stopped event and StackTrace request.

I solve the problem temporarily by delaying StepIn response after Stopped event.

So, is there some different between StepIn and Next, I mean VS Code debug status control.

**Comment by isidorn** [comment]
I can not reproduce this with node debug.

VS Code will only quite debug is the adapter is telling vscode that debugging is done in some way. So please check all the events / responses that your adapter is sending.

If you would like us to investigate further, please fork https://github.com/microsoft/vscode-mock-debug 
Make changes to that repositroy such that the issue is reproducable and then we can investigate on our side. Thanks

**Comment by caboom04** [comment]
Thanks, isidorn.
I have found the real reason is that the debug server run into an exception and quit itself in that state.

But, as I said above, there is some different between Next and StepIn. 
Now let the debug server do same operations for Next request and StepIn request, press F10 or F11 without release, VSCode will send much more StepIn requests than Next requests. 
In my opinion, VSCode has no need to differentiate between Next and StepIn except the request type.
Here is the log:
[stepin.log](https://github.com/microsoft/vscode/files/3894709/stepin.log)
[next.log](https://github.com/microsoft/vscode/files/3894710/next.log)

**Comment by isidorn** [comment]
@caboom04  Yes, you are correct. Step_in was enable more easily.
You can try vscode insiders tomorrow and verify if the issue is fixed for you now. Thanks
