### ISSUE TITLE
Cannot use right click in editors

### ISSUE THREAD

**Issue by tylerliu1998** [microsoft/vscode#85576]
After the latest upgrades, there is some terrible problem. It seems right-clicking the mouse would not work in any editors or terminals, which is really annoying. Yet it still works in the activity bar and panels.

**Comment by tylerliu1998** [comment]
Note that I have both the Insider and Stable release installed. The Stable version works fine.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo Have you reproduced the issue when running with all extensions disabled?

**Comment by gjsjohnmurray** [comment]
Also, you didn't post platform or version info.

**Comment by tylerliu1998** [comment]
Sorry. I just checked the extensions one by one and it should be caused by LaTeX Workshop. But I have the same version of this extension installed in the stable release of VSCode and there is no problem there.

Platform: Mac OS X
Version: 1.41.0-insider (Have problem), 1.40.1 (No problem)
LaTeX Workshop Version: 8.4.1 (both)

**Comment by gjsjohnmurray** [comment]
Please report this to the extension author for investigation by them.

**Comment by jlelong** [comment]
> This issue is caused by an extension.

I am a maintainer of [LaTeX-Workshop](https://github.com/James-Yu/LaTeX-Workshop) and there is nothing suspicious in our logs to explain the issue. As the extension works flawlessly with the stable version of VSCode, I suspect that the problem comes from a recent change in VSCode Insiders. Then, I have no idea how to help.
