### ISSUE TITLE
Path is hidden in call stack selected frame

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#85626]
![image](https://user-images.githubusercontent.com/323878/69667075-2a319580-1042-11ea-903e-7c0548091894.png)

**Comment by isidorn** [comment]
This is how all inline actions are behaving in all our views.
On hover the action is shown and on focus.
Another reason for doing this is accessibility, such that the users can tab to the action. The path is still read out to screen readers due to the aria label.

I understand that this might be an issue, since we are auto focusing stack frames when a break point is hit, so users will not see the path.

We can say that call stack behaves special and only shows the inline action on hover. And the restart frame is accessibile via context menu.

Let me know what you think
also fyi @weinand

**Comment by roblourens** [comment]
Which other views do this? Search has inline actions that show on hover, but it still shows the file path on the right side.

> We can say that call stack behaves special and only shows the inline action on hover.

I like that.

**Comment by isidorn** [comment]
Call Stack does this for threads and sessions.
Git does this.


However let's go with your suggestion, since frames get auto focused, this might be strange. Adding bug label so we get this verified
