### ISSUE TITLE
Wrong deDE keybind mapping ( key: "... [" -> key: "... ü" )

### ISSUE THREAD

**Issue by HatiEth** [Microsoft/vscode#8568]
- VSCode Version: 1.2.1 ( 2016-06-14T12:54:38.105Z )
- OS Version: Arch Linux 4.4.14-1-lts
- Keyboard Layout: de

Problem:

VSCode shows that the keybinding is mapped to `shift+k ü`, If i press this it says no shortcut available.
However `shift+k ß` the so defined shortcut works.

Steps to Reproduce:
1. Add keybinding { key: "shift+k [", command: "cursorRight" }
2. Test in any Text-editor (expected to move right on `shift+k ü` as shown rather than `shift+k ß`)

**Comment by alexandrudima** [comment]
I have validated that we now (i.e. after PR #22894 aka #17521 -- in tomorrow's Insiders build) appear to behave correctly for this keyboard layout

![image](https://cloud.githubusercontent.com/assets/5047891/24255431/caba90b6-0fe5-11e7-9727-cb6615c65830.png)

---
### Analysis of key code binding `shift+k [`
* I have added the rule `{ "key": "shift+k [", "command": "cursorRight" }` to my `keybindings.json`
* the key code binding `shift+k` is mapped to scan code binding `Shift+[KeyK]` (I will not go to great detail to explain why, the reason is that `[KeyK]` produces `k`)
* the key code binding `[` is more interesting.
* `[` can be produced through a single scan code combination: `` Ctrl+Alt+[Digit8] ``. i.e.:
![image](https://cloud.githubusercontent.com/assets/5047891/24255662/663fbf16-0fe6-11e7-9e10-33259fdc8da5.png)
* therefore, the key code binding `[` is mapped to the scan code combination `` Ctrl+Alt+[Digit8] ``
* this is now correctly reflected in the info hover:
![image](https://cloud.githubusercontent.com/assets/5047891/24255805/bfb3652a-0fe6-11e7-9406-32df16445e04.png)
![image](https://cloud.githubusercontent.com/assets/5047891/24255749/97c211ba-0fe6-11e7-9fc3-85be8d890ed7.png)

---
### Analysis of pressing `[Minus]`

![image](https://cloud.githubusercontent.com/assets/5047891/24255839/d3985b5e-0fe6-11e7-995a-fcaa34263b97.png)

We now correctly label it:
![image](https://cloud.githubusercontent.com/assets/5047891/24255863/e3e6635c-0fe6-11e7-9b49-3face30f0d97.png)

And it is possible to bind it to the desired command e.g. with following keybinding rule:

```
{ "key": "shift+k [minus]", "command": "cursorRight" }
```

VS Code will now also correctly label it in the info tooltip:
![image](https://cloud.githubusercontent.com/assets/5047891/24255942/22c957e6-0fe7-11e7-9cd1-65a9b9041ccc.png)


---
This makes me believe the fix in PR #22894 aka #17521 resolves this issue. Please double check in tomorrow's insiders build.

**Comment by roblourens** [comment]
The first part works as expected, but I see something different for the second. Not sure if it's a problem.

If I press `ß` while creating a key combo, I just see `-`, not `[minus]`.

![image](https://cloud.githubusercontent.com/assets/323878/24563444/29fa3e50-1603-11e7-9385-2ac1e9145daa.png)

And if I create a shortcut for `shift+k [minus]`, I can't trigger it. The info hover says 
![image](https://cloud.githubusercontent.com/assets/323878/24563493/4f9e72f2-1603-11e7-8c36-72da299333bb.png)
