### ISSUE TITLE
Get task definition with completed variables

### ISSUE THREAD

**Issue by Hezkore** [microsoft/vscode#85702]
When using something like `vscode.tasks.OnDidStartTask`, the execution is passed, and inside that you can access the task definition with something like `e.execution.task.definition`.
But doing so will only provide you with variable substitutions such as `${relativeFile}` and `${selectedText}` and not the actual completed/parsed variables.

Let's say the task definition has `outDir`, and the user inputs `${workspaceFolder}/output/${fileBasenameNoExtension}`; there is no way for the extension to know the _actual_ output directory during the `vscode.tasks.OnDidStartTask` stage.
I would like to get something like `home/your-username/your-project/output/file` in return.

**Comment by ClockworkV** [comment]
+1 for this

**Comment by Hezkore** [comment]
This will obviously not meet the required 20 upvotes it needs.
But I find it quite odd that there's no way to resolve task variables.
What if the extension needs to know the specified output path?

**Comment by ClockworkV** [comment]
I wonder how difficult it would be to just make the change and make a pull request...
@alexr00 , how would you estimate the amount of work it would take? It doesn't seem like it should be too difficult, but my work experience is mainly C++ and python.

**Comment by Hezkore** [comment]
Perhaps exposing the already existing VSCode variable resolver might be best?

**Comment by ClockworkV** [comment]
Maybe. I'm completely unfamiliar with the code base, and the extension I wrote is pretty basic. 
It does seem pretty useful to be able to access resolved variables in general, even outside the context of task definition completion.

**Comment by alexr00** [comment]
There are a few problems that make this non-trivial to do:
- We haven't actually resolved any of the `${}` variables at the point that the start event is fired. However, we have resolved them when the `StartTaskProcess` event fires, so this isn't a big problem.
- If we just swap in the resolved values, we could be breaking any extensions that rely on the unresolved variables being present. 
- Because of the previous point, we might need additional API. API tends to be challenging to do through an PR since it is usually a long process to come up with good API.
- Then there's the question of whether it's better to add to the existing tasks API so that the task event or task contains info about the resolved task definition, OR provide new API that lets you resolve variables in arbitrary strings.

Given the API decisions that need to be made before work on this should even start, it's not a good candidate for a PR right now.

**Comment by Hezkore** [comment]
>However, we have resolved them when the `StartTaskProcess` event fires, so this isn't a big problem.

I can't get the resolved variables even at `onDidStartTaskProcess`.
```
vscode.tasks.onDidStartTaskProcess( t => {
	console.log('Source: ' + t.execution.task.definition.source )
})
```
The above code still logs `Source: ${relativeFile}`

**Comment by alexr00** [comment]
I mean that internally we know the values.

**Comment by Hezkore** [comment]
But wouldn't the easiest, and best solution, just be to expose the internal resolver?
That way the extension could resolve the variables any time it needs to, not just during tasks or debugging, and it wouldn't break anything previously created.

**Comment by alexr00** [comment]
From my above comment:

> Then there's the question of whether it's better to add to the existing tasks API so that the task event or task contains info about the resolved task definition, OR provide new API that lets you resolve variables in arbitrary strings.

This has it's own set of questions. We have several variable types that require user interaction. It wouldn't be a good experience to ask the user for the same input multiple times. And the user could provide different input each time. 

My only point with all the above is that this is a non-trivial problem.
