### ISSUE TITLE
Add X button to remove a breakpoint

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#85708]
I always expect there to be an `x` when I hover over a breakpoint to remove it.

![image](https://user-images.githubusercontent.com/641685/69746280-e908b680-1111-11ea-9f88-34c133f9a48c.png)

**Comment by KarlaChen** [comment]
Hi, @eamodio . Can I have a try?

**Comment by adelphes** [comment]
Related: https://github.com/microsoft/vscode/issues/25071

**Comment by eamodio** [comment]
@isidorn any objection to @KarlaChen taking a shot at this one?

**Comment by isidorn** [comment]
We already had this and I removed it in the past and nobody complained. I do not like action duplication and I do not see any particular value this brings. This can already be achieved via context menu, keyboard shortcuts, command palette, editor gutter.
So I would prefer to leave this open and if it gets enough feature reqeusts we can accept PRs.
Hope that makes sense.

**Comment by eamodio** [comment]
@isidorn Can we revisit this now that we have an edit action? I would love to have a quick click remove action.

**Comment by isidorn** [comment]
Yeah. We can look into this. Assigning to this milestone, and if I do not have time I will push out to march.

**Comment by isidorn** [comment]
We now render the remove breakpoint action inline.

To verify:
1. Make sure that clicking on this icon remove the breakpoint
2. Make sure that this icon appears on regular breakpoint, function breakpoints and does not appear for exception breakpoints


fyi @misolori if we potentially need a bit larger icon since it looks kind of small next to the edit

![Screenshot 2021-02-19 at 15 37 34](https://user-images.githubusercontent.com/1926584/108518171-8d9f8700-72c8-11eb-9763-7c3d1329195c.png)

**Comment by misolori** [comment]
That looks good to me, we do the same in the Settings UI:

![image](https://user-images.githubusercontent.com/35271042/108547293-26211180-729f-11eb-8d37-cde7d516a054.png)

**Comment by isidorn** [comment]
That's fair.
