### ISSUE TITLE
Keyboard shortcuts to toggle debugger "All Exceptions" and "Uncaught Exceptions"?

### ISSUE THREAD

**Issue by Ziriax** [microsoft/vscode#85700]
```
Version: 1.40.2 (user setup)
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:45.096Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```

When debugging Jest unit tests using the [excellent `vscode-jest` extension](jest-community/vscode-jest), I find myself constantly toggling the checkboxes `All Exceptions` and `Uncaught Exceptions`, and I can't find any keyboard shortcuts for these.

I uncheck these boxes before starting the debugger, and when my breakpoint is hit for the unit test that fails, I check these boxes again, and continue running. The debugger will stop when something crashes, or when an `expect` fails. Then I can easily inspect the variables and callstack to see what went wrong. I need to uncheck these boxes before running because JEST/webpack/etc seem to throw a lot of exceptions when starting.

If these shortcuts are indeed missing, this might be a good way to start my firstt `vscode` PR, but maybe a workaround already exists?

An ideal workflow would be to automate this of course :)

Thanks!
Peter

**Comment by isidorn** [comment]
There are no keyboard shortcuts for this. The issue here is that vscode ui is language agnostic, which means that vscode is not aware of caught and uncaught exceptions, extensions contribute this.
The best way to do this via keyboard is to Focus Breakpoints View and press down and then space to toggle.
So just assign a shortcut for the Focus Breakpoints View

I will still leave this feature request open. Even though we do not want to tackle it right now.
Thanks!
