### ISSUE TITLE
Improve Run Experience

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#85759]
As @weinand pointed out 

Today VS Code does not support generic "Run" functionality!

What we currently support is the optional "noDebug" attribute of launch configurations:
VS Code's "Run" is basically the same as "Debug" but with a "noDebug": true added to the launch configuration.

VS Code does not know whether a debug adapter obeys the "noDebug" hint. So the VS Code debug UI will switch to debug mode and show a debug toolbar in any case.

To improve the Run experience we should:
* Look into improving the UX when a program is running (for example the toolbar does not make a lot of sense, neither does most of the debug viewlet views)
* Look into improving the extension contribution points shuch that the extension can specify if it can run and how

**Comment by luabud** [comment]
One thing that might be worth mentioning is that there are two ways to "run" Python files with the Python extension. We have a "run Python file" command that basically calls the Python interpreter to run a file (and we recently added a run button to improve its discoverability for new users), and then the Start Without Debugging option. Right now there isn't a lot of confusion since not a lot of our users are aware of the start without debugging option, but once this is improved we may need to rethink the UX in the Python extension to avoid confusion.

**Comment by weinand** [comment]
@luabud yes, aligning the "Run" stories of individual extensions is one goal covered by this item.

**Comment by weinand** [comment]
Nothing planned here.
