### ISSUE TITLE
[json] improve anyof handling

### ISSUE THREAD

**Issue by Sequoia** [Microsoft/vscode#8582]
- VSCode Version: Version 1.2.1 (1.2.1)
- OS Version: 10.11.5 (15F34)

Steps to Reproduce:
1. Download [test.json](https://gist.github.com/Sequoia/d86032bff4413759c2f27e9cf852817b) and load it into VS Code
2. Delete & recreate the `"test"` property

Problems:
1. It does not prompt you for an object type, indicating null & string are the only valid types:
   ![screenshot 2016-06-30 13 01 37](https://cloud.githubusercontent.com/assets/317498/16497226/e1253f84-3ec3-11e6-92f7-f6ffdbd22929.png)
2. If the object type is invalid, **intellisense defaults to the first available type**. What it should do is say, approximately: "there is an object type available but you have illegal keys in it."
   ![bad-type](https://cloud.githubusercontent.com/assets/317498/16497282/1779fe1c-3ec4-11e6-8492-2deb00ff8b1a.gif)
3. Does the same if string is not a legal string (from `enum`):
   ![bad-type](https://cloud.githubusercontent.com/assets/317498/16497518/6ac4c826-3ec5-11e6-9067-0d5fdb0668da.gif)

**Comment by aeschli** [comment]
Sorry for the late reply: To get the object proposed, you need to give the object a 'default' (or if you don't mind using vscode internal properties: defaultSnippets).
Having proposals for `{}` and '[]' everywhere they can appear is too much. Often they add no value but clutter the proposals. We only show them if there are no other proposals.

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Maybe you want to give it a try yourself and provide the feature through an extension or a PR: We're happy to give advise and get you started.
Thanks for your understanding. Thanks for helping and happy coding!
