### ISSUE TITLE
Opening remote file from cli is opening folder

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#85883]
Testing microsoft/vscode-remote-release#1526

`code-insiders --remote ssh-remote+ubuntu16 /home/sandy081/work/vscode/package.json` is opening folder `package.json` 🐛 

![image](https://user-images.githubusercontent.com/10746682/65955172-d3477f80-e447-11e9-85a6-e33d672ff367.png)

**Comment by aeschli** [comment]
Verify that when opening a remote resource, the folloeing rules are used:
- it's a file if it ends with a file extension, but no trailing slash\backslash
- it's a workspace file it it ends with `.code-workspace`
- otherwise it's a folder

e.g.
code-insiders --remote ssh-remote+ubuntu16 /home/sandy081/work/vscode/package.json

**Comment by connor4312** [comment]
The guessing logic in general is rather unfortunate; I'm unable to open dotfiles or extension-less file, like `Makefile`, and with this folders that have a dot in their name will be opened as file. We do detect these after we connect, maybe we can automatically re-open the file or folder correctly if we guessed incorrectly?

![image](https://user-images.githubusercontent.com/2230985/70171266-38effc00-1683-11ea-88c9-fb3895846f42.png)

Anyhow, I'm able to verify that the described behavior works, so I'll leave it as 'verified'.
