### ISSUE TITLE
Key Binding for Activating the Help Menu

### ISSUE THREAD

**Issue by cprovatas** [microsoft/vscode#85901]
On macOS, it's fairly standard  for '⌘ + ⇧ + /'   (cmd + shift + backslash) to activate the menu bar help search menu, where the user can quickly search the available menu item actions for a given application.

This does not appear to be the default key binding in VSCode and I was having trouble finding an equivalent action in the Keyboard Shortcuts panel to map this shortcut to.

Does this functionality exist already and if not, would it be possible to support it?

Thanks,
\- Charlton

**Comment by ultraGentle** [comment]
I am able to use the "view help menu" shortcut successfully within VSCode, though mine is rebound to "Opt+Space."  

Also, as far as I know, the Command Palette (Cmd+Shift+P) fully duplicates the functionality of the Mac help menu, and more.  You open it, type, and see a list of all matching commands, which you can then execute by pressing Return.  

If the Help menu can do something *not* available in the Command Palette, maybe that could be a feature request, so that all commands are accessible from one place.

**Comment by cprovatas** [comment]
Thanks for your response @ultraGentle 

<img width="950" alt="Screen Shot 2019-12-02 at 1 26 23 PM" src="https://user-images.githubusercontent.com/14881080/69996655-59934700-1507-11ea-9051-0e7270c62a8e.png">

I search for 'view help menu' in the keyboard shortcuts menu and I'm not seeing it. 

Im on 1.40.2

**Comment by sbatten** [comment]
I am able to focus the help menu within macOS using `Cmd+Shift+/`. It is not a keybinding within VS Code but an OS level shortcut I believe.

**Comment by cprovatas** [comment]
@sbatten interesting, even with that key shortcut disabled for all commands in VSCode, in never invokes the help menu for me.  It works fine with most other applications.  

Does Electron expose `NSMenu` or `NSMenuItem` at all? It should be trivial to wire up if so...

**Comment by sbatten** [comment]
@cprovatas hmm tried on catalina and am seeing the same issue.

@deepak1556 i tried with electron fiddle and can reproduce this issue on multiple versions of electron.

**Comment by esambo** [comment]
`⌘ + ⇧ + /` works fine for the [Brave-Browser](https://github.com/brave/brave-browser)

**Comment by esambo** [comment]
Seems related to #68604

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/68604
