### ISSUE TITLE
No 'Stage Selected Lines

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#8592]
- VSCode Version: insider 6/30
- OS Version: MacOs

Steps to Reproduce:

1. enable tabs
2. change a file
3. switch to the Git perspective
4. select the changed file
5. select lines in the right pane of the diff viewer
-> no 'Stage Selected Lines' available in the editor menu bar.

**Comment by bpasero** [comment]
@kieferrm those actions are now in the context menu of a tab and we have a UX item to improve discoverability of those actions.

**Comment by kachkaev** [comment]
@bpasero is `Stage Selected Lines` in the tab's context menu supposed to stage by hunks? I can't find out how to select just two deleted lines out of 5 going sequentially and stage only the ones I want. Any time I select something and click that menu items, the whole block gets staged. The same happens when unstaging

**Comment by bpasero** [comment]
@isidorn can you comment?

**Comment by isidorn** [comment]
@kachkaev that is a bug, I have created a seperate issue for it here #9475
