### ISSUE TITLE
Second delete folder operation does not work in Insiders 1.41.0

### ISSUE THREAD

**Issue by ZaJarv** [microsoft/vscode#85938]
Hei!👋

Found issue with folder delete operation. The point is, when you delete folder (first time), no matter how, via mouse or keyboard combination, then select another folder and try to delete it, you will get popup message saying "Cannot read property 'isDirectory' of undefined"🤔🧐
Only when you select another folder again (second time), delete operation will be successful.

Tried several times with same results.
And as i remember, this bug i found some time ago, so it is not introduced exactly in last insiders build.

Visual Code Insiders 1.41.0 from 2019-12-02, commit: 7cf4cca47aa025a590fc939af54932042302be63
macOS 10.15.1

**Comment by isidorn** [comment]
@ZaJarv thanks for filling this great issue. You should have the fix tommorrow in vscode insiders

**Comment by isidorn** [comment]
@joaomoreno the problem was that it was happening that the tree would sometimes set the trait on one element two times.
In this particular case Selection would be set on the element A and A. So if I say tree.getSelection I would get the same item twice. Instead of the array with one item.
I decided to fix this with a workaround on the trait level. 

Repro steps: set compact tree to true. Go up and down with the focus always ending up with the focus on the one select item. 
Put a conditional breakpoint [here](https://github.com/Microsoft/vscode/blob/6d2eeee28aba86c329ac659acf8bfe2ab0390ab9/src/vs/base/browser/ui/tree/abstractTree.ts#L1000) tree will try to set the double selection trait

**Comment by jzyrobert** [comment]
@isidorn This seems to be coming from [here](https://github.com/microsoft/vscode/blob/6d2eeee28aba86c329ac659acf8bfe2ab0390ab9/src/vs/base/browser/ui/tree/asyncDataTree.ts#L1193)

Where the selection would already contain the folder, but as oldSelection/oldFocus also has the id, it will push the same object to the selection again.

You could also fix it there by doing some sort of duplicate filtering or selection.indexOf to prevent duplciates being added

**Comment by isidorn** [comment]
@jzyrobert great pointer. I think you are right, give me a sec and I will push a better fix. Thanks a lot!

**Comment by jzyrobert** [comment]
@isidorn I was planning to submit something along the lines of
`if (oldSelection.has(id)) {
						const element = compressedNode.elements[compressedNode.elements.length - 1].element as T;
						if (selection.indexOf(element) === -1) {
							selection.push();
							didChangeSelection = true;
						}
					}

					if (oldFocus.has(id)) {
						const element = compressedNode.elements[compressedNode.elements.length - 1].element as T;
						if (focus.indexOf(element) === -1) {
							focus.push();
							didChangeFocus = true;
						}
					}`

But I'm not sure if this is considered good code, it might be better to create a set of Ids (like oldSelection) does, but as selection is of type T, I could not access the id parameter.

**Comment by isidorn** [comment]
@jzyrobert  If you would like to create a PR you are more than welcome to! It would be great if you could do it today since we are wrapping up the milestone and we need this fix.
Just make sure to remove my wokraound introduced with https://github.com/microsoft/vscode/commit/6d2eeee28aba86c329ac659acf8bfe2ab0390ab9

Thanks!
