### ISSUE TITLE
Allow omitted default excludes in proposed search API

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#85946]
In PWA we want to be able to use vscode's search to look through compiled files and find sourcemaps. However, users usually exclude built files from search, and we've no way to ask vscode to drop its exclusions while still applying some of our own--@roblourens:

> if you set exclude  to null, it won’t use any excludes. If you set some excludes, they will always be merged with the defaults. Needs better solution

The simplest solution would be some `useDefaultExcludes?: boolean` flag, which defaults to true and we could set to false in PWA.

**Comment by roblourens** [comment]
I think js-debug should really be using findFiles since the majority of files matched by the glob will be proper matches and we have to read all the matches later anyway. But what I would like to do is get the proposed api findTextInFiles right then introduce a findFiles2 that matches it with new options so I'll do this in findTextInFiles.

**Comment by roblourens** [comment]
Verified since this works in js-debug
