### ISSUE TITLE
Improve the Code update experience

### ISSUE THREAD

**Issue by Serjster** [Microsoft/vscode#8595]
The current Code Updates are highly annoying and highly intrusive! Please find a way to make the updates less intrusive... the Visual Studio way with a flag and number is sooo much better! I can understand that your policy is constant updates, but it feels like part of me starting up Code is to do an update first! It is uber annoying. Then after the update, I still have to see that annoying update bar about what the update did... seriously just get out of the way and let me work!

**Comment by bpasero** [comment]
@Serjster are you on the insider channel or stable?

**Comment by rozzzly** [comment]
I know how annoying it can be to receive _up to date_ software, and especially having to _click-close_ a notice explaining important changes/bug fixes/new functionality. I mean come on! 

## Here's how you can fix that: :wink:

###### Method 1
Edit _`project_root/.vscode/settings.json`_, add this line
```js
{
    // ...
    "update.channel": "none",
    // ...
}
```
Now vscode shouldn't contact the server to looks for updates... But want a more concrete solution? 

###### Method 2
Follow this tutorial on how to block specific applications. Via the windows firewall. 
![windows firewall](http://pad3.whstatic.com/images/thumb/2/2c/Block-a-Program-With-Windows-Firewall-Step-5Bullet2.jpg/aid1879550-728px-Block-a-Program-With-Windows-Firewall-Step-5Bullet2.jpg.webp)
http://www.wikihow.com/Block-a-Program-With-Windows-Firewall

**`[PROTIP]:` Instead of `BitTorrent` you will want to block `Visual Studio Code`!**

Now `VS Code` is incapable of connecting to the internet so you can rest assured that there won't be any prompts to update. This way, you can go months or even years using the same outdated software :sunglasses:  No need to (click) :point_up: any message boxes!

###### Method 3

Finally if you're still having trouble, I might suggest this: [amazon sells this amazing device](https://www.amazon.com/Fluke-Networks-D-Snip-Cable-Scissors/dp/B000E5VAXM) which is specifically designed to prevent unwanted internet traffic. This is the foolproof way to ensure you'll never see on of those windows again.

---

Oh, and don't ever try arch. you wouldn't like it.

**Comment by Serjster** [comment]
Hey @rozzzly thanks for your smartass and useless reply. Your perspective of how things should be is not the ultimate right perspective. In fact quite the opposite! I work in a size-able group of developers and most of us have raised the concern of the annoyance of the update notification in Code. Furthermore, I don't want to not know or be able to update at all! I want to do it on MY preference, not yours! Just move it up into the title bar like VS does and tell me how many versions I'm behind instead of continually annoying me that your weekly update is out! When I'm ready maybe a month from now, or some other time when I'm not in the middle of my very intensive task that I just need Code to do its thing... open my file so I can edit it! Instead of being intrusive, be helpful!

@bpasero Stable.

**Comment by bpasero** [comment]
@Serjster so this should happen at most once per month or do you see it more often?

**Comment by remcoros** [comment]
A configurable update interval could be a possible solution.

For example, on startup, once a day, once a month, never

**Comment by Serjster** [comment]
@bpasero I am not certain. It feels like more often than that. This is coupled with the fact that I have an installation of Code at work and also at home.

@remcoros I still think that an option to make the Update notifications be less intrusive is a better solution.

**Comment by bpasero** [comment]
@Serjster if you are on stable (blue icon) you get updates once per month, on insider (green icon) you get updates once per day. Maybe you are on the green VS Code icon.

**Comment by joaomoreno** [comment]
Insider builds get daily updates. Stable builds get at least monthly updates. That will never change.

What can change is how we present updates to you. That can be much improved and there were already some discussions among the team about how to do that. A good example is the Spotify app.

**Comment by joaomoreno** [comment]
Won't fix while we are with Inno Setup.
