### ISSUE TITLE
Debugger issue with Node.js/TypeScript code

### ISSUE THREAD

**Issue by karabaja4** [Microsoft/vscode#8597]
- VSCode Version: 1.2.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:

I came across an issue with VS Code debugger when debugging Node.js/TypeScript code in a specific situation described below.

In TypeScript, when using "let" to declare a variable inside a try/catch block, and when using that variable inside a callback within the same try/catch block, the debugger won't read the variable, instead it appends "_1" and displays a variable copy in the Variables window. The code works, it's just the debugger that's acting strange.

When using var instead of let, or when not using try/catch, there is no problem.

Screenshot of the described situation:
http://take.ms/a2iJC

I compiled an example Node.js project which reproduces an issue, you can open it in Visual Studio Code, Run Build Task, place a breakpoint in test.ts and just start debugging. Download it here:
https://www.dropbox.com/s/jxk0upjppqkiunw/example.tar.gz?dl=1

This could very well be a Node.js bug, but I am not sure. Please advise.

Regards,

Igor

**Comment by bpasero** [comment]
@karabaja4 what is your node version?

**Comment by karabaja4** [comment]
Node.js version: v6.2.2

**Comment by weinand** [comment]
@karabaja4 it is not the debugger that is acting strange here. It is the TypeScript transpiler that translates the TypeScript source to JavaScript and it has to rename variables in certain situations.
When running (or debugging) you are actually executing the generated JavaScript but thanks to 'source maps' you don't see the JavaScript because it is always mapped back to the original TypeScript source.
But the source maps do not cover variables so the generated names are not mapped back to the original names.

To verify this, please locate the generated JavaScript file (test.js). You should find the 'A_1' there.
If you set the 'sourceMaps' attribute in your launch config to false, you can debug through the JavaScript and you will see why the 'A_1' makes sense.
