### ISSUE TITLE
Adapt serverReadyAction to js-debug

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#86035]
Testing #85984:

Adapt serverReadyAction to js-debug

**Comment by connor4312** [comment]
This mostly worked, just made a few changes -- 
- it spawns as a separate rather than child session of the debug target. The old debuggers didn't care, but js-debug manages its session tree closely and having an 'external' session caused issues
- removed the check for the extension/wsl since it's now built in

**Comment by isidorn** [comment]
@connor4312 can you please add steps for verification

**Comment by connor4312** [comment]
You can follow the docs example for the `serverReadyAction` -- verify that it still works https://code.visualstudio.com/docs/editor/debugging#_remote-debugging

**Comment by isidorn** [comment]
Thanks for the doc pointer. I have verified it still works -> adding verified label.
