### ISSUE TITLE
No link to open a file 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#86046]
Testing https://github.com/microsoft/vscode/issues/85774

- Open a folder that has no launch.json
- Open debug viewlet

![image](https://user-images.githubusercontent.com/10746682/70046366-324f7f00-15c6-11ea-9542-4d675c2897ba.png)

🐛 Message `Open a file...` does not have a link to open file.

**Comment by isidorn** [comment]
As designed.
We agreed that the `open a file` will only have a link if you are in the No Folder vscode. Since in this case you should open a file within your workspace which you already have. Using a native dialog does not make a lot of sense imho. However for consistency I do not mind changing.

As with other issues I am flexible and can change it. Just pointing out that this was done on purpose

fyi @weinand @roblourens @connor4312 @chrisdias @misolori

**Comment by sandy081** [comment]
How is this helping for new users without guiding them with actions. Open file message was more confusing to me when I transitioned from empty window debug view to folder debug view. We might have to change the wordings to tell user to open a file in the folder user has opened and have a link that can open quick pick.

**Comment by isidorn** [comment]
After discussions with @weinand we decided to leave it as it is now. And we are open to change it in the future.
The open a file action could potentially open the explroer. And then the user could chose from there.
Though let's wait for feedback.
