### ISSUE TITLE
Save All vs Save All Files

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#86061]
re https://github.com/microsoft/vscode/issues/85144

There is `Files: Save All` and `Files: Save All Files` and I can't say what the difference is... I believe this has something to do with custom editors and iff I would talk about text editors, e.g "Save All Text Files'

<img width="762" alt="Screenshot 2019-12-03 at 14 06 05" src="https://user-images.githubusercontent.com/1794099/70053620-1e137e00-15d6-11ea-86f2-d982331b76fc.png">

**Comment by bpasero** [comment]
@jrieken no, this command was there from a long time ago, the intent is to have a command that saves all files that are not untitled files so that no save prompt appears. Custom editors are supported as well though I did not want to rename this command because it is well established across users (and I think other editors too). I would like to keep it as is.
