### ISSUE TITLE
Sync: Notification after start

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#86088]
Testing #85944

As soon as I chose what to sync I got this notification:

![image](https://user-images.githubusercontent.com/22350/70060514-fbd42d00-15e2-11ea-8ff9-44b7655e1f2c.png)

Is it really needed? Shouldn't sync have its own status bar contribution where I could click and see its status, instead? As soon as I close that notification, there's nothing in VS Code telling me that I'm all _synced up_.

**Comment by sandy081** [comment]
Is not that it is always synced once it is turned on and not sure how helpful the status is in such case. I think it is important for user to know when there is an action to be taken like resolving conflicts or sign in required.

**Comment by sandy081** [comment]
Regarding the notification, I thought it will help user to know that sync has started. But I am open to remove this.

**Comment by Tyriar** [comment]
I called this out when I saw it too

**Comment by connor4312** [comment]
I think showing a status on the first sync is useful to confirm to the user that things are wired up and working, since there's no other way to tell that the operation was successful short of trying on another machine. But I was also confused when I saw the "started" within a "completed" message, I had to open the output log to know that the sync actually worked.

**Comment by Tyriar** [comment]
@connor4312 the other way to look at it is to not bother the user unless something went wrong, so if the first sync failed for some reason show a warning icon on the gear menu.

**Comment by connor4312** [comment]
I generally agree with that philosophy. But in this scenario I don't expect that UI-heavy flow (going through quickpicks, MSA sign-in and callback) to end with a silent success, my mind expects to see some UI for the result of that process--particularly since I can't readily validate whether it was a silent success or silent failure. Maybe that's just me though 😛 

Showing a success toast could also be an opportunity to indicate the further syncing will happen in the background/automatically.

> Sync successful. We'll your configuration in sync automatically from now on.

**Comment by sandy081** [comment]
Good output. 

Summarising:

- No extra UI
- Show the success message only once with addition info as mentioned above.

**Comment by sandy081** [comment]
It's not known whether sync is successful or not when sync is turned on because there can be conflicts or some local errors. By turning on, we will start syncing automatically. So, I would like to show following message which is helpful to know when user turned on sync

<img width="495" alt="image" src="https://user-images.githubusercontent.com/10746682/74988008-ec73bb80-543c-11ea-85d8-674d95d1c6ae.png">
