### ISSUE TITLE
Accessibility Support is breaking the magnifiers caret following

### ISSUE THREAD

**Issue by anthonykozak** [microsoft/vscode#86105]
- VSCode Version: 1.40.2
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open VS Code and the windows magnifier app (type "magnify" in windows menu)
2. In Magnify settings, check the options to follow keyboard input
3. In VS Code, create a new file, type several lines of text, then play with the arrow keys to move the caret backward and upward, notice how the magnifier is following properly.
4. Go to your VS code settings and turn the accessibility support ON
5. Play with the arrow keys again and notice its loosing the caret

**Comment by isidorn** [comment]
@anthonykozak Thanks for filling this issue. I will investigate next milestone into this.

**Comment by isidorn** [comment]
@anthonykozak first of all sorry for the slow response (holiday break).
I just tried reproducing this on windows and I could not. The Magnifier properly follows my cursor both if I have `"editor.accessibilitySupport": "on"` and `"editor.accessibilitySupport": "off"`.

Can you reproduce with latest vscode insiders https://code.visualstudio.com/insiders/
Since we updated to Electron 7 and the latest electron might contain a fix for your issue and thus I can not see it?

Thanks!

**Comment by lavilaso** [comment]
@isidorn  I confirm that the problem is present in vs 1.41.1 and Windows 7 Ultimate with the latest updates applied

**Comment by isidorn** [comment]
@lavilaso ok, but you can you please try to reproduce with latest vscode insiders? Not vsode stable?
https://code.visualstudio.com/insiders/

**Comment by lavilaso** [comment]
> @anthonykozak Gracias por completar este problema. Investigaré el próximo hito en esto.

I have checked it and in this version the problem is not solved.
