### ISSUE TITLE
Semantic tokens: Tokenization appears to be really slow

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#86165]
Testing https://github.com/microsoft/vscode/issues/85976

It appears colors are not updated until typing has stopped for around 500ms, being this slow seems like a problem?

![Kapture 2019-12-03 at 12 32 01](https://user-images.githubusercontent.com/2193314/70087322-f538bc00-15c8-11ea-9051-3e4790f6fc22.gif)

I'm not typing particularly fast in the above gif, compare this to today with tm grammars where the colorization is instant.

**Comment by alexandrudima** [comment]
TM grammars are interpreted synchronously in the renderer process, and in most typing situations, while actually typing. (the exception would be when opening a very large file and typing at the bottom of it before tokenization has reached the bottom). So, in most cases, the TM grammar is running synchronously on typing...

Today, the request is made 500ms after the last typing stops. Since we never actually cancel the request (to simplify a server implementation which now only needs to remember the last result), I think we could change this in two directions:
1. reduce the delay.
2. do not always postpone the request on typing, i.e. make the request at X ms after the first typing, not after the last typing.

**Comment by octref** [comment]
> Today, the request is made 500ms after the last typing stops. Since we never actually cancel the request (to simplify a server implementation which now only needs to remember the last result)

But even if you do 2, server can still be simple and only remember last (latest) result, can't it?

Naive server always parse all and return all tokens so this is not a concern.

An incremental server could:

- Put content change events and semantic token requests in a queue
- When popping a content change, apply it to AST
- When popping a semantic token request, answer it by computing answer from AST
- Drop the semantic token request if cancelled

Currently the typing experience in TS is ok since it still has TM grammar. For languages that's completely using semantic highlighting, I imagine it would be annoying if when I go from `func()` to `func(a: b, c: d, e: f)` I see `a: b, c: d, e: f` all in white until the very end.

**Comment by alexandrudima** [comment]
> For languages that's completely using semantic highlighting

IMHO I would not want that we ship languages only with semantic highlighting because that means color/style flashing all the time while typing. I think there is a fine balance between what one puts in the TM grammar and between what one puts in the semantic tokens, but IMHO they are two stories that work together and not exclusive.
