### ISSUE TITLE
Semantic tokens: Use of array buffers with wrapping objects

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#86174]
Testing #85976

For an extension that wants to be as performant as possible they would want to provide a set of token edits using the following API:

```ts
	export class SemanticTokensEdits {
		readonly resultId?: string;
		readonly edits: SemanticTokensEdit[];

		constructor(edits: SemanticTokensEdit[], resultId?: string);
	}

	export class SemanticTokensEdit {
		readonly start: number;
		readonly deleteCount: number;
		readonly data?: Uint32Array;

		constructor(start: number, deleteCount: number, data?: Uint32Array);
	}
```

It's mentioned in the provider docs:

> Therefore, to improve the memory consumption around describing semantic tokens, we have decided to avoid allocating objects and we have decided to represent tokens from a file as an array of integers.

But this doesn't really seem to be the case for edits as you need to create an "edits" object, an extra array and an "edit" object for every single change, this could be a huge amount of edits if a line is removed on a large file for example as all tokens after it would need their line number updated. Additionally `SemanticTokensEdit` is essentially just reinventing splice in the API but this means that the other ArrayBuffer helpers aren't available like `fill`, `copyWithin`, `transfer`, etc.

Have you considered an API that allows providing the full array buffer that the extension host holds on to, the active length and then sending back updated ranges instead of edit objects? This would eliminate all the extra object/array creation at the cost of a little more complexity but also allows extensions to reuse the array buffer and manipulate it using the extremely fast native APIs.

```ts
// buffer can be grown if needed
let buffer = new Uint32Array(5 * 100);
// Reuse this object to save creating new ones every update
const semanticTokens = new SemanticTokens(buffer);
provideSemanticTokens() {
    // Fill tokens
    buffer[0] = x;
    buffer[1] = y;
    buffer[2] = z;
    buffer[3] = a;
    buffer[4] = b;
    // VS Code knows only to look at indexes 0 to (length * 5 - 1)
    semanticTokens.length = 1;
    // Indicate which parts of the array buffer have updated, this could also
    // be an array containing several ranges [start, end, start, end, ...]
    semanticTokens.updateStart = 0;
    semanticTokens.updateLength = 4;
    return semanticTokens;
}
```

**Comment by alexandrudima** [comment]
Thank you for the very good feedback!

> But this doesn't really seem to be the case for edits as you need to create an "edits" object, an extra array and an "edit" object for every single change, **this could be a huge amount of edits if a line is removed on a large file for example as all tokens after it would need their line number updated**.

Exactly **that** is the reason why tokens are delta encoded relative to the previous tokens. I was hoping the toy example of 3 tokens to do a better job at showing that, but I should have called it out perhaps more explicitly, or perhaps the example is too condensed and I should break it up in more steps, perhaps with 3 total requests.

In any case, suppose there are 100 tokens on lines 1-100 in a file. Those tokens would look like. I am using `c`, `l`, `tt`, `tm` for numbers which don't help with the reasoning:
```
- (first token on the first line)    0, c1, l1, tt1, tm1
- (second token on the second line)  1, c2, l2, tt2, tm2
- (third token on the third line)    1, c3, l3, tt3, tm3
- (fourth token on the fourth line)  1, c4, l4, tt4, tm4
- (fifth token on the fifth line)    1, c5, l5, tt5, tm5
...
```

Now suppose <kbd>Enter</kbd> is pressed at the beginning of the file, so all the tokens need to move down by one line, which is kind of the worst case. The delta encoding becomes:
```
- (first token on the second line)    1, c1, l1, tt1, tm1
- (second token on the third line)    1, c2, l2, tt2, tm2
- (third token on the fourth line)    1, c3, l3, tt3, tm3
- (fourth token on the fifth line)    1, c4, l4, tt4, tm4
- (fifth token on the sixth line)     1, c5, l5, tt5, tm5
...
```

Notice how the only thing that changed is the delta line of the first token, all the other delta lines are basically unaffected because the subsequent tokens maintain relative position to one another when a `\n` is inserted at the beginning of the file.

So the entire delta in this worst-case scenario would be `{ start: 0, deleteCount: 1, data: [1] }` to change the first `0` to a `1`.

---

> Additionally `SemanticTokensEdit` is essentially just reinventing splice in the API but this means that the other ArrayBuffer helpers aren't available like `fill`, `copyWithin`, `transfer`, etc.
> Have you considered an API that allows providing the full array buffer that the extension host holds on to, the active length and then sending back updated ranges instead of edit objects? This would eliminate all the extra object/array creation at the cost of a little more complexity but also allows extensions to reuse the array buffer and manipulate it using the extremely fast native APIs.

That is exactly the desire, the edit API should feel familiar, so it is a descriptive form of the imperative `Array.splice`, with the arguments named in the same way, etc...

The reason why the delta API is descriptive and not imperative (like giving a `Uint32Array` over to an extension) is because semantic tokens are actually not useful on the extension host process. Semantic tokens need to travel to the renderer process. So anything saved by having an imperative API would be lost again by computing a diff and sending the edits in a descriptive format to the renderer process.

In a good end-to-end implementation (which does not exist today -- the TS implementation from the branch is a naive implementation that always gives the full result), the extension host would do nothing more than forward the edits it receives. In such a good implementation, the extension host does not even hold in memory the semantic tokens.

For naive semantic tokens providers that give always the entire file, I have implemented that the extension host holds on to the previous result and computes a diff behind the scenes such that communication to the main process is reduced, but as soon as a semantic tokens provider returns a delta encoded result, it will no longer hold on to the data, so the actual data will live only on the renderer process.

Perhaps a different way to look at the problem is to think of the extension host as a simple hop. Semantic tokens are not consumed on the extension host process, they need to be consumed on the renderer process (by the editor rendering code), and semantic tokens are not produced on the extension host process, they need to be produced by a smart language server, by C# in the omnisharp server, by TS in the tsserver, etc. So the extension host should offer API that allows as easily as possible to simply forward things between the producer and the consumer.

**Comment by Tyriar** [comment]
Makes sense, thanks for the detailed write up. I'll reread the docs today and see if i just missed something of if we can call it out better.

**Comment by Tyriar** [comment]
Yeah I must have just skimmed over that part, looks good 👍
