### ISSUE TITLE
Clicking into the hatched area in a diff doesn't focus the editor

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#86175]
![image](https://user-images.githubusercontent.com/641685/70092295-fa5b3280-15eb-11ea-9078-e17627db894a.png)

I would expect clicking in the hatched area would focus the editor and put the cursor at the end (or beginning) of the hatched area.

**Comment by alexandrudima** [comment]
This is broken because the view zone configures `supressMouseDown: false` [here](https://github.com/microsoft/vscode/blob/41e5936b45e07ec74cfe8a05c8a47dcb18a1105a/src/vs/editor/browser/widget/diffEditorWidget.ts#L131).

@rebornix This came in via https://github.com/microsoft/vscode/commit/c9042cb5210290a9a3c88c463c10b2ea4e4923d5 . Can you please take a look?

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/commit/bc2fbe2893daf00b0b3ef9bd6ff326a5ddfd933f
