### ISSUE TITLE
SCM: Support `scmResourceState` in `when` clauses 

### ISSUE THREAD

**Issue by DavidGoldman** [microsoft/vscode#86180]
See also #27946 for a related request/question.

The SCM API described [here](https://code.visualstudio.com/api/extension-guides/scm-provider#menus) allows you to conditionally add commands to the SCM menus based on the `scmProvider` and `scmResourceGroup`, but not based on the  `scmResourceState`.

Conditions on the `scmResourceState` would be valuable for mercurial extensions (which differentiates between behavior for modified files vs. added files vs. untracked files) without needing to use separate groups for all of them.

**Comment by DavidGoldman** [comment]
Here's an example of how specific commands make the SCM more intuitive for the user

For a modified file:
* Revert: undo changes
* Remove --force: remove the file even though it is modified

For an added file:
* Untrack: forget the add (`hg forget` == `hg revert` == `hg remove --force`)

For a removed file:
* Restore: restore the file


Using terms instead like `revert` or `remove` may be confusing for the user based on the resource state

**Comment by mjcrouch** [comment]
I'm not sure if this will reach 20 upvotes because the people upvoting this will mostly be limited to scm provider extension developers, but this would be a big deal for the perforce extension (or at least [my fork of it](https://marketplace.visualstudio.com/items?itemName=mjcrouch.perforce)

Files in perforce can be shelved, and these are represented in the extension with an additional ResourceState for the shelved file. However the set of commands you can run on a shelved file is very different to the set of commands you can run on a normal file. At the minute, the menu is cluttered up with both, and there's no way to prevent this.

**Comment by llgcode** [comment]
We also need it to add/remove menu conditionally on ScmResourceGroup or ScmResource. It will help us organize our menu efficiently

**Comment by toja83** [comment]
Agree, please fix this issue!

**Comment by aeschli** [comment]
Verified in source by having the built-in git provider's resource implementing a `contextValue` and contributing a command to it:
```
      "scm/resourceState/context": [
        {
          "command": "xy.hello",
          "when": "scmResourceState == modified"
        },
```

**Comment by joaomoreno** [comment]
@DavidGoldman Could you verify this issue? Please check the previous comment for instructions. Thanks!

**Comment by mjcrouch** [comment]
@joaomoreno if it helps I can verify it is working in today's insiders build:

![recording (5)](https://user-images.githubusercontent.com/49367953/94456967-d9cc1c80-01ab-11eb-9df7-dfdf843379ce.gif)
