### ISSUE TITLE
Git status add and modified decorations in minimap too narrow on high contrast theme

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#86197]
- VSCode Version: 1.41 Insiders
- OS Version: Windows, macOS

Found while testing #85952

Tomorrow Night Blue:

![image](https://user-images.githubusercontent.com/12818376/70096660-6f267080-15dc-11ea-80fa-898c8dcf2305.png)

High Contrast:

![image](https://user-images.githubusercontent.com/12818376/70096707-89604e80-15dc-11ea-9c56-2da85dbe7ff1.png)

Compared to the red deleted content decoration, the added and modified decorations look thinner.

Screenshots are from a Windows machine. More noticeable on macOS.

**Comment by RMacfarlane** [comment]
@joaomoreno @misolori I reused the same colors as the editor gutter scm decorations for this, it looks like these currently only have a contrast ratio of around 2:1 on the high contrast theme. I've now changed them so that they meet a 7:1 contrast ratio:
![Screen Shot 2019-12-04 at 9 57 46 AM](https://user-images.githubusercontent.com/3672607/70168673-29ba7f80-167e-11ea-81c1-0d1dd4b127c4.png)

I'm updating the editor gutter scm decorations to match this as well, feel free to tweak these further
