### ISSUE TITLE
Problems: change color when item is selected

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8620]
As you can see in light theme it is hard to read all text. I suggest to change the color to white for all text for the selected item:

![image](https://cloud.githubusercontent.com/assets/900690/16522006/1b5e2904-3f9b-11e6-9362-20cf3ae7eeb5.png)

**Comment by sandy081** [comment]
Issue was I was using a different color for source label. Instead, I would use opacity of 0.7 so that other information is not as as prominent as problem description. At the same time, they are readable in all themes and when selected. 

Since this is similar to file path, it will be consistent with how we render file path in the tree.

<img width="398" alt="screen shot 2016-07-07 at 11 33 37 am" src="https://cloud.githubusercontent.com/assets/10746682/16648950/b81abf42-4436-11e6-8aa8-270fbd90e694.png">

<img width="460" alt="screen shot 2016-07-07 at 11 33 58 am" src="https://cloud.githubusercontent.com/assets/10746682/16648959/c1d71aa8-4436-11e6-85fb-ab85859a72c6.png">

<img width="391" alt="screen shot 2016-07-07 at 11 34 31 am" src="https://cloud.githubusercontent.com/assets/10746682/16648974/d67aa1aa-4436-11e6-8b94-0f3ebbb85ce8.png">

<img width="440" alt="screen shot 2016-07-07 at 11 34 47 am" src="https://cloud.githubusercontent.com/assets/10746682/16648984/df33b4a8-4436-11e6-9315-6355805c820e.png">
