### ISSUE TITLE
Reduce files in vscode remote distro

### ISSUE THREAD

**Issue by taiyosogawa** [microsoft/vscode#86204]
The vscode remote distro currently has many small files, which causes unzipping the archive to be slow. Would it be possible to pack the dependencies into fewer files?

**Comment by aeschli** [comment]
I investigated if we can use ASAR on the server as well. 
https://www.npmjs.com/package/asar-node gave me the impression that this is possible.
It is done by patching `fs` to handle `asar` files like folders and by patching the code that computes the node_module lookup paths.

Turns out that what https://www.npmjs.com/package/asar-node promises doesn't work (anymore?).
The NodeJS loader uses internal API to make `stat` calls that can not be patched in NodeJS. See https://github.com/nodejs/node/issues/33423
Electron patched the Node runtime to get access to the internal API (https://github.com/electron/electron/blob/master/lib/asar/fs-wrapper.ts)

**Comment by aeschli** [comment]
So instead I went the traditional way of improve the filters used by the build script and filing issues against extensions that contain a lot of files (with the request to package their sources)

**Comment by aeschli** [comment]
| files / folder          |  1.50.1 stable     | 1.51 insiders | 
| -------------- | -------------- | -------------- |
| bin             | 1                | 1              |
| extensions             | 865                | 778              |
| node_modules          | 917                | 436
| out         | 24                     | 24
| total files            | 1813              | 1245
| total size             |  113 M                     | 105 M

**Comment by aeschli** [comment]
1.51 insiders:
Extensions:
configuration-editing/: 7
css-language-features/: 10
debug-auto-launch/: 6
debug-server-ready/: 5
emmet/: 5
extension-editing/: 5
git-ui/: 5
git/: 35
github-authentication/: 5
github/: 5
grunt/: 7
gulp/: 7
html-language-features/: 13
image-preview/: 13
jake/: 7
json-language-features/: 10
markdown-language-features/: 14
merge-conflict/: 7
microsoft-authentication/: 7
ms-vscode.js-debug-companion/: 6
ms-vscode.js-debug/: 89
ms-vscode.node-debug/: 19
ms-vscode.node-debug2/: 354
ms-vscode.references-view/: 6
ms-vscode.vscode-js-profile-table/: 7
node_modules/: 76
npm/: 8
php-language-features/: 7
python/: 6
search-result/: 8
typescript-language-features/: 19

**Comment by aeschli** [comment]
- open a remote window (wsl, containers or ssh)
- in the integrated terminal find the server location with `which code-insiders`
- count files with `find -type f | wc -l`

Verifiy that it is now around 1245 files.

![image](https://user-images.githubusercontent.com/6461412/97464161-d8c01380-1940-11eb-810a-b8d6c442e213.png)
