### ISSUE TITLE
Bad state while resolving keybindings conflicts

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#86214]
Testing #85941

- Change keybindings, get conflicts
- Open the json editor to resolve conflicts
- Resolve the conflicts (but don't click the checkmark)
- Reload the window
- Click the checkmark
- Get an error "new data exists"
- Close the `.keybindings.json` editor, run "Sync: Resolve Conflicts" again
- Click the checkmark
- Now I get the error `Unable to write file (Error: File Modified Since)`

I'm actually not sure how to get out of this state

![image](https://user-images.githubusercontent.com/323878/70103268-84f16100-15ef-11ea-9700-52eb9d6f48e0.png)

**Comment by sandy081** [comment]
When changes are applied from conflicts diff editor

* If local contents have changed, conflicts are computed with new local content and content gets merged if there are no conflicts, otherwise the diff editor is updated with new conflicts.

In all other cases, applied contents are synced and pushed.
