### ISSUE TITLE
Search result in editor tab: Configure what to show

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#86244]
#23931 Just an idea. The syntax is just an example of modified a bit `window.title` setting.

Default config:
```
# Query: ${query}

${eachFile}
${path}:
${eachMatch}  ${lineNumber}:${line}
```
Default result:
```js
# Query: false

.eslintrc.js:
  217: 		"before": false,
  234: 		"beforeColon": false,

postcss.config.js:
  7:        warnings: false,
```

---

Zen-like config:
```
${eachFile}${eachMatch}${line}
```

Zen-like result:
```js
 		"before": false,
 		"beforeColon": false,
        warnings: false,
```

File before each match:
```
${eachFile}${eachMatch}${path}${line}
```
File before each match result:
```js
.eslintrc.js 		"before": false,
.eslintrc.js 		"beforeColon": false,
postcss.config.js        warnings: false,
```

Other possible variables:

- `${absolutePath}` - show absolute path instead of relative
- `${lineUp}` - show some context
- `${lineDown}` - show some context

**Comment by JacksonKearl** [comment]
While I agree that adding some configuration to the syntax would be nice, it comes with a lot of difficulty in parsing for purposes of extracting file path info for linking to the actual result.

Rather than the current two regex's, we'd suddenly need a parser for the configuration grammar, which we'd then pipe to a parser generator in order to dynamically generate a correct search result parser for the config. 

In the end I think this idea, while cool, would bring in far too much complexity for the utility it provides. If we do end up providing for alternate syntaxes it will likely be from a fixed set that we can manually create parsers for.

As for context, we have "Search Result: Search Again (Wth Context)" (typo fix coming soon)
