### ISSUE TITLE
Settings UX allows user selection

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#86254]
* Mac
* triple click selects works, dragging selects more

<img width="665" alt="Screenshot 2019-12-04 at 11 33 55" src="https://user-images.githubusercontent.com/1794099/70135252-f847b100-1689-11ea-9ddf-4a00f99175d8.png">

**Comment by IllusionMH** [comment]
Same on Windows, dragging after third (or second click for double click selection) allows to select more.

I hope that expected fix is not to disable selection at all because I find myself copying settings items labels often instead of Command ID's(which might look cryptic). But this might be a special case of [xkcd:Workflow](https://xkcd.com/1172/)

**Comment by roblourens** [comment]
This is by design. I think that copying settings names and descriptions is sometimes useful. But this has been reported as a bug more than once. Do you think it's a big problem?

**Comment by jrieken** [comment]
The confusing bit is that this works across many settings. What happens to the values that sit intebween? Are they are also copied? Can this be limited to only a single setting?

**Comment by roblourens** [comment]
I don't think it's possible to limit it to a single element (without hacks in js)
