### ISSUE TITLE
Support for string case handling (ie: pascal, camel, kebab...)

### ISSUE THREAD

**Issue by rosyatrandom** [microsoft/vscode#86272]
Because some frameworks are insensitive to some case variants, or coerce case types depending on context, it would be handy to be able to find/replace these variations more easily.

For example, frontend frameworks that turn camelCase js properties into kebab-case HTML attributes can be a pain point when having to convert the text yourself, both when writing it and searching for the variant

In-place transformation can be handled by extensions, but having an option in the Find/Search features to also look for case variants would be great

**Comment by roblourens** [comment]
Interesting idea, so you want a search for `foo-bar` to also match `fooBar` and so on? I'm not sure that it's possible to write a regex that does that, and we are limited to regex search. I would rather leave something like this up to the user, rather than cram another option into the crowded search view.
