### ISSUE TITLE
VSCode becomes unresponsive when reordering files in Working Files list

### ISSUE THREAD

**Issue by siirila** [Microsoft/vscode#8629]
- VSCode Version: 1.2.1
- OS Version: Windows 7

Steps to Reproduce:
This is happening in a React project with JS and JSX files

1. Have several files open in the Working Files list
2. Click and drag one of the files to a different location in the list.
3. The editor window becomes unresponsive for a long time (10 seconds or more). When viewing Resource Monitor at this time a Code.exe process is pegged at 25% CPU usage.

This has just started recently, but I can't be sure if it has been happening since the last update to VSCode or something after that caused the change.

![image](https://cloud.githubusercontent.com/assets/4274032/16524702/1edc77f8-3f77-11e6-8b75-b1c1c25a9d22.png)

**Comment by bpasero** [comment]
That is weird indeed. Since the working files list is removed in our upcoming 1.3 release I wonder if you could give our insider build a try?

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by siirila** [comment]
Thanks for the prompt reply. I'll try out the current build on a different computer and see if I am getting the same results, and then once I get back on my other system I will try out the preview release and respond with my results.

**Comment by siirila** [comment]
Testing on a second computer with the same 1.2.1 version of VSCode and the same project didn't produce the slowdown, and trying out 1.3 on the initial system didn't have performance issues either.
