### ISSUE TITLE
Semantic Tokens: Embedded languages

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#86329]
Ref: #85976

@alexandrudima, what's your plan for embedded languages? Today a grammar can mark a region as a language and hand it off for VS Code to highlight with TM grammar.

How should a HTML server implement semantic highlighting for html/css/js? Although we have all 3 servers written in JS in this case, there are cases when parent and children language servers are written in different languages and cannot inter-operate.

Do we expect embedded language servers do what we told Intelliphense to do — forward requests in PHP to HTML server with virtual documents?

Or should we allow semantic token providers to return some ranges as another language, and VS Code automatically query other semantic token providers for results?

This is complicated by the fact that we'd be stuck with a mix of TM grammar and semantic tokenizers for the foreseeable future...When one is synchronous and the other one async.

/cc @aeschli

**Comment by alexandrudima** [comment]
@octref Thanks for the great questions! Let me try to answer and provide a bit of context.

---

The first thing I thought about semantic tokens related to embedded languages is: should semantic tokens be allowed to redraw the embedded language boundaries?

That is to say, given something like:
```html
<button onclick="return false;">
```
And suppose there is a TM grammar that would tokenize `return false;` as an HTML attribute i.e. it doesn't switch languages to JS... Should a semantic tokens provider be allowed to change things, to mark `return false;` as embedded JavaScript?

I have given this quite some thought and have come to the conclusion that it would not be wise to do so. The reason lies in some typing features that we have. Namely, brackets and auto closing pairs are language specific, so the fact that `{` gets auto-closed with `}` is something that is defined via language configuration. So it is possible that in some languages typing `{` does not auto-close with `}`. 

Having the language be changed asynchronously would make typing non deterministic. If you would open a file and very quickly type in the `"return false;"` portion (you would type before the semantic tokens request has resolved), that body of text would be identified as HTML and would use the rules for auto-closing pairs / brackets from HTML. Then, once the request would resolve, that part would be turned to JavaScript and all a sudden the rules of JS would apply. This situation could repeat while typing other constructs, etc, and sometimes it would use the embedded language defined by the TM grammar, and, in a non deterministic fashion the language would change, and then new rules would apply. IMHO we must avoid at all cost non-deterministic typing, so to me it became clear that redefining embedded language borders via semantic tokens is not something we should do.

---

Embedded languages are difficult. But the only one that knows what to do is the embedding language itself. Here is a PHP example:

```php
...
<script>
function getTimeDiff() {
  const serverDate = "<?php
	if ($something) {
      echo $yesterday;
    }
    echo $today;
?>";
  return computeTimeDiff(Date.now(), serverDate);
}
</script>
...
```

The only one that knows how to create something out of the above is the PHP language server. JS wouldn't be able to handle the illegal multiline string with `<?` in the middle of it. The only chance to get semantic tokenization is for PHP to create a virtual document like e.g. (perhaps a good strategy is to strip PHP blocks and replace them with an empty string):
```JS
function getTimeDiff() {
  const serverDate = "";
  return computeTimeDiff(Date.now(), serverDate);
}
```
Only PHP would know it substituted its dynamic output for a fake output in order to get things rolling for JS. Then PHP would ask JS for semantic tokens and JS could say that `serverDate` is a constant on line 3 (in `computeTimeDiff(Date.now(), serverDate)`). But only PHP would then know how to *massage* semantic tokens results coming in from JS to remove the fake things it did and bring back positions and ultimately return the correct `serverDate` positions...

IMHO semantic tokens of embedded languages must be entirely handled by the embedding language itself. The editor has IMHO no chance to do the right thing directly. In my mind, semantic tokens are even "less mergeable" than completion items, since merging them always requires processing, at least to adjust positions, etc.

So overall, I believe in the case of embedded languages, it is the outer most language that should own semantic tokens completely.
