### ISSUE TITLE
Git: Stash Staged Changes

### ISSUE THREAD

**Issue by dzienisz** [microsoft/vscode#86384]
@joaomoreno: User wants a command to stash staged changes.

---

- VSCode Version: 1.40.2
- OS Version: MacOS

Steps to Reproduce:

1. Slick Source Control -> three dots -> Stash
2. It's stashing also "untracked" files
3. It's working like "Stash (Include untracked)

Feature request: Rename button "Drop Stash" to "Clear Stash"

<img width="278" alt="Screenshot 2019-12-05 at 11 13 43" src="https://user-images.githubusercontent.com/3521624/70226404-15938280-1751-11ea-978a-2a3f42db5fc0.png">

**Comment by Wowol** [comment]
I've checked it locally and it seems to work in my repo:
**Stash** command works like 
> git stash push

And **Stash (Include Untracked)** works like:
> git stash push -u

Can you provide more details, how to reproduce this issue?

About renaming button - let's wait for @joaomoreno for decision :)

**Comment by dzienisz** [comment]
@Wowol ok I probably mixed up word untracked with staged. I want to stash only stashed files.

**Comment by le0tan** [comment]
@joaomoreno I'm willing to try out this issue, is that OK?

**Comment by joaomoreno** [comment]
@le0tan You have to add a new command somewhere around [here](https://github.com/microsoft/vscode/blob/830e3c1d1e48358b89ba6befca99f96a09ecde78/extensions/git/src/commands.ts#L2221-L2290).

**Comment by sombhotlu** [comment]
I am still not able to stash changes in vscode. I think it is not solved, right ?

**Comment by kirosc** [comment]
It works for me sometimes

**Comment by akinuri** [comment]
I was thinking about opening an issue about this, but this one seems to be related to the one I'm thinking about.

Will there be an option to stash staged changes only?

The current options "Stash" and "Stash (Include Untracked)" seem to stash both staged and unstaged. This makes it hard to split changes.

I came across this [answer](https://stackoverflow.com/a/70231955/2202732) on SO, and git seems to support this since Dec 2021.
