### ISSUE TITLE
Explorer: button is not same width anymore

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#86380]
Insiders left, stable right:

![image](https://user-images.githubusercontent.com/900690/70220706-45d62380-1747-11ea-9733-0e5c51761886.png)

**Comment by bpasero** [comment]
Specifically looks odd because the button used to start directly under the label and now does not anymore.

**Comment by isidorn** [comment]
Yes. I changed that on purpose because feedback from @alexandrudima was that it is too wide - gets especially ugly when the sidebar is wider.
Also note that we now also use these buttons in the Empty Debug view (delete your launch.json to get it)
I actually also prefer it centered, but I do not mind changing back.
Let me know what you think

**Comment by ishidex2** [comment]
to be honest, in my opinion it could've been the width insiders version provide, but positioned on the left.

**Comment by bpasero** [comment]
Maybe a solution where it stays as it was up until the sidebar has a certain size and then moves into the center? Not sure.

**Comment by isidorn** [comment]
The current solution is what you describe Ben, since the default sidebar size the button is all the way to the left. It only starts moving to the center once there is space (user resized sidebar)
I'll go loco and release it to stable like this and we see.

**Comment by bpasero** [comment]
Oh yeah I see, fine for now.
