### ISSUE TITLE
Add "breakpoint created/deleted" notifications.

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#8642]
Some debuggers have much more flexible ways of setting breakpoints than VSCode currently supports (e.g. set breakpoints by regex).  Would be nice if breakpoints created via commands in debugger console were reflected in the UI.

I'd suggest adding a new notification message to the protocol, which adapter can send when a  breakpoint is created/deleted.  It should include a "cookie" that needs to be passed back to the adapter in order to re-create the breakpoint.

**Comment by weinand** [comment]
@vadimcn the protocol has already a BreakpointEvent for this. Please see: https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts#L135

@isidorn are you already tracking this event?

**Comment by isidorn** [comment]
@weinand yes [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L304)

**Comment by vadimcn** [comment]
@weinand: But does VSCode support creation/deleteion?  Sending a BreakpointEvent with reason = 'new' doesn't seem to have any effect. 
Your [comment](https://github.com/Microsoft/vscode/issues/2013#issuecomment-182291463) from February says "VS Code now listens on breakpoint events with reason update and updates the verification state and location".  If I read the [relevant code](https://github.com/Microsoft/vscode/blob/b99e6614a58dccb372d1eab604491286f9a5f9e2/src/vs/workbench/parts/debug/common/debugModel.ts#L501), correctly, it indeed only deals with updates of existing breakpoints.

**Comment by vadimcn** [comment]
Also, please note that currently the [Breakpoint](https://github.com/Microsoft/vscode-debugadapter-node/blob/661032a4234ef69e01a7751fe5246604da95867c/protocol/src/debugProtocol.ts#L776) does not provide a way to preserve custom information (such as condition, hit count, etc) across debugging sessions.

**Comment by isidorn** [comment]
@vadimcn you are right, there is no code for dealing with Breakpoint event = 'new' or 'deleted' (@weinand do we want to call this 'deleted'?). Thus reopening this

**Comment by isidorn** [comment]
Assigning first to @weinand since this needs a couple of more additions to the protocol:
* How do we call an event when a breakpoint got deleted?
* Do we add a possibility that a adapter can also add / remove function breakpoints - if yes we need a way to distinguish those events from adding/removing regular breakpoints
* As mentioned by @vadimcn currently it is not possible for the debug adapter to send a breakpoint with a condition to vscode, so we might need to introduce the condition to the Breakpoint interface in the debug protocol

Once that is done we just need to handle those events [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugService.ts#L308) for which a pull request is welcome @vadimcn.

**Comment by daviwil** [comment]
Hey guys, the PowerShell extension is really in need of this behavior now since we're able to interactively debug PowerShell scripts using our new Integrated Console feature.  I've started trying to implement the add/delete behavior for BreakpointEvent in debugService so that I can send you a PR for it to go into the release at the beginning of June.  Once I get something basic working I'll send a WIP PR so we can discuss the implementation.

I also noticed the lack of support for the debugger sending condition and function breakpoints to the client.  Is that something we could potentially add to the protocol soon?  Any way I could help with that?

**Comment by isidorn** [comment]
After discussing with @weinand we decided to introduce 3 different breakpoint events
`"new"`, `"changed"` and `"removed"`. @weinand will update the debug protocol and will probably also cover the case that the adapter can update the condition of a breakpoint.

For  compatibiliy reason if a breakpoint event has no `reason` (which is required) I will handle it as a "changed" event.
@roblourens please update the node2 adapter to always send the appropriate reason for breakpoint events(which is currently not the case)

**Comment by isidorn** [comment]
Now vscode will react to breakpoint events. 
Please note that a `"new"` `BreakpointEvent` requires that a [`Source`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1328) is passed. In the future we can consider if adapters can add new function breakpoints with this "new" event.

Unassigning myself and assigning to @weinand to update the protocol and @roblourens to adopt this in node-debug2 adapter.
Even though `condition` is not specified in the protocl for `BreakpointEvent` yet vscode should proparly react to this.

@daviwil  please try it out and let me know how it goes

**Comment by weinand** [comment]
For verifying this feature, I've added REPL command to mock-debug:
- `new 12` adds a new breakpoint in line 12 of the source file and returns the breakpoint id.
- `del 4` deletes a breakpoint with id 4 

I found these issues:
- for a newly created breakpoint the "verified" attribute is ignored
- I could not delete a breakpoint

**Comment by isidorn** [comment]
@weinand thanks for verifying and for nicely updating the mock debug so this is easy to try out.
I have pushed a fix for both issues specified here, as for the section being empty I will tackle that in that seperate issue.

**Comment by weinand** [comment]
Now its working fine.
