### ISSUE TITLE
Actions and menu items on the UI are not localized

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8650]
- VSCode Version: Code - Insiders 1.3.0-insider (a2b9738a942237b59cb920940b93a0206f1b61d0, 2016-07-01T19:24:33.352Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04

Actions that are surfaced through the UI should be localized. Many seem to have been overlooked.

Here's an example (`--locale=ko`):

English x2 in command palette:
![image](https://cloud.githubusercontent.com/assets/2193314/16535557/34d54514-3f9d-11e6-9549-9ec860994fe0.png)

Korean translations in menu:
![image](https://cloud.githubusercontent.com/assets/2193314/16535560/3aa4a67e-3f9d-11e6-8231-8843bd67aac8.png)

Here's another one in the search viewlet, all `title` attributes feature English:

![image](https://cloud.githubusercontent.com/assets/2193314/16535601/819ff998-3f9d-11e6-92ee-7c5cab1336bd.png)

**Comment by bpasero** [comment]
I think we just have not yet made a NLS input.

**Comment by dbaeumer** [comment]
That is true. I did an input on Friday and it takes a week to get them localized. In general our statement is that Insider and Milestones builds partly show English strings because of the time delay of localization. 

Moving to @sandy081 to ensure that the strings are proper localized. If so please close.

**Comment by sandy081** [comment]
All strings are properly localized, once we have nls build we can see locale specific strings.
