### ISSUE TITLE
alt property of a context menu item contributed by an extension has no effect

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#86591]
Issue Type: <b>Bug</b>

Based on https://github.com/microsoft/vscode/commit/c0caab4d8ccd67424ef2f57abd5a4a12275fb4d7 and https://github.com/microsoft/vscode/issues/85218#issuecomment-556074372 I expected to be able to add an `alt` property to entries that my extension's package.json contributes to the editor/context menu

```json
        "menus": {
            "editor/context": [
                {
                    "command": "thefoldingstuff.fold",
                    "alt": "thefoldingstuff.foldRecursively",
                    "title": "Fold",
                    "group": "thefoldingstuff"
                },
                {
                    "command": "thefoldingstuff.unfold",
                    "alt": "thefoldingstuff.unfoldRecursively",
                    "title": "Unfold",
                    "group": "thefoldingstuff"
                },
```

But when I run my extension the command invoked from my entries in the context menu is always the one specified in the `command` property, even if I hold down the <kbd>Alt</kbd> key when picking the option.

VS Code version: Code - Insiders 1.41.0-insider (87c2e0be5d7359ce110c4c9ec9f6df71be996f8a, 2019-12-06T21:36:11.793Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sbatten** [comment]
The alt key is not something that can be pressed with Windows native context menus.

macOS: allows option + click in context menu
windows: allows alt + click in context menu with custom (not native)
linux: allows alt + click in context menu

So, yes, we could theoretically support this, but since it is a foreign concept to native windows, I'm not super sure we should.

/cc @bpasero
