### ISSUE TITLE
Debugger variables UI should highlight changed variable values

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#866]
In Visual Studio, variables shown in the Locals window are marked with a red foreground color when they change between two debugger stop events:  

![image](https://cloud.githubusercontent.com/assets/79405/11505040/28b83234-97fd-11e5-8617-62fc22bc7c15.png)

It would be great to also have this functionality in VS Code.  Even better if the debug adapter could send some kind of `isChanged` field back on individual variables when they are requested.

cc @rkeithhill

**Comment by rkeithhill** [comment]
+1 for this feature.

**Comment by isidorn** [comment]
If the adapter could send it to VSCode it would be pretty trivial for me to implement this.
Though I have the model on the vscode side so I could also check for the variable change - might not be so trivial since I get all new variables on each stop event and I am not aware what variables existed in the previous step.

@weinand what do you think? On which side should this logic live? Adapter or VSCode

**Comment by weinand** [comment]
@isidorn I do not have the old state and I do not want to introduce a new model for preserving the old state. Since the UI has the old state by definition (it's visible in the UI), it makes more sense to implement this feature there. In addition we can offload repeated implementations of this feature from debug-adaptor authors.

**Comment by isidorn** [comment]
Makes sense. I can look into this over holidays :santa:
