### ISSUE TITLE
Undo unicode typing is incorrect

### ISSUE THREAD

**Issue by tsctao** [microsoft/vscode#86640]
- VSCode Version: 1.40.2
- OS Version: macOS 10.14.6

Steps to Reproduce:

1. Type `Hello` in the editor
2. Move cursor to begining of the line
3. Type `ดีดีดีดี`
4. Press Ctrl+Z (undo)

Expected behavior: It should only delete `ดีดีดีดี` and remains `Hello`.

Actual behavior: Only `o` left.

![vscode-issue](https://user-images.githubusercontent.com/4986616/70507779-aad2b480-1b5f-11ea-87a5-37b270ea05b9.gif)

Does this issue occur when all extensions are disabled?: Yes

I'm not sure this issue related to #84897. Because the number of characters deleted by undo action depends on the number of combined unicode characters in the deleted characters.

**Comment by alexdima** [comment]
@tsctao Can you please explain in detail how to type `ดี` to be able to reproduce? I have a QWERTY keyboard, what keyboard layout should I press and what QWERTY keys should I press to be able to type `ดี` ?

**Comment by tsctao** [comment]
> 
> 
> @tsctao Can you please explain in detail how to type `ดี` to be able to reproduce? I have a QWERTY keyboard, what keyboard layout should I configure in macOS and what QWERTY keys should I press to be able to type `ดี` ?

Use Thai keyboard layout and type f and u key.

**Comment by alexdima** [comment]
@tsctao I could reproduce on stable:

![Kapture 2020-01-24 at 8 39 44](https://user-images.githubusercontent.com/5047891/73052295-21fca780-3e85-11ea-8c5a-f72d1f5c58bb.gif)

ฺBut I could not reproduce on [insiders](https://code.visualstudio.com/insiders/):

![Kapture 2020-01-24 at 8 41 41](https://user-images.githubusercontent.com/5047891/73052410-6425e900-3e85-11ea-94b7-7a3e3b485f10.gif)

So it must be that one of the changes we have pushed to `master` has fixed the issue, but I don't really know exactly which one, because we pushed multiple changes in this area...
