### ISSUE TITLE
Support synchronising global state

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#86679]
Support synchronising global state

- locale (display language)
- other UI state (activity bar icons, status bar entries, views layout, donotaskagain options...)

**Comment by sandy081** [comment]
@dbaeumer How feasible it is to move locale configuration to settings?

**Comment by dbaeumer** [comment]
The biggest problem moving it to settings is performance. It is its own file since we need to read that file early on in the startup process and we didn't want to read large files and parse them. So would we be able to sync it separately ?

**Comment by sandy081** [comment]
You are right and it might impact the performance. If so, lets not move it to settings and I can sync locale separately.

**Comment by dbaeumer** [comment]
Thanks!

**Comment by gandalfsaxe** [comment]
There are two issues I think are relevant to this:

**1. Sessions across machines:** You might want to think about how you want to handle session restores across different machines that doesn't have access to the same files, perhaps by design (e.g. work machine, home machine). I encountered this issue a while back in the portable version of VSCode, which actually prompted me to stop using the portable version: https://github.com/microsoft/vscode/issues/81340

**2. Settings across machines:** This is also part of a bigger problem of `User/settings.json` not being able to import other settings files. Ideally you should be able to set up a hierarchy of settings:
1. The global settings that applies to all machines
2. Work/Home machine specific settings that only applies to work machines or personal machines.
3. Project specific settings (e.g. `.vscode/settings.json` in project folders).
This issue is being tracked here, and I can see you're already aware of it :) https://github.com/microsoft/vscode/issues/17634

**Comment by sandy081** [comment]
> Sessions across machines:

Can you please elaborate more about the issue?

**Comment by gandalfsaxe** [comment]
I'm not 100% sure how this is relevant to this issue since not many details are provided. Perhap you could elaborate beyond the title "Support synchronising global state" what this means?

I just meant everything I said in https://github.com/microsoft/vscode/issues/81340 - but I can re-iterate it here if necessary. If you're looking for VSCode to restore editor session across different machines, as the portable version inherently does, you're going to have potentially not access to the same files. So you get errors that you cannot open file X, Y and Z when you open VSCode on another machine.

For example, I'm on machine A and have files X, Y and Z open.
Then I start machine B and only files X are available, but Y and Z are not (e.g. some Cloud app not installed). I will then get errors that these files are not available on machine B. If I then continue to work, and restart machine A, it might lose files Y and Z being open because they were not part of the latest session on machine A.

**Comment by sandy081** [comment]
I see your use case. We have plans to sync open editors state but definitely not in scope of this issue.

**Comment by gandalfsaxe** [comment]
Fair enough 🙂So though the title of this issues says "Support synchronising global state", your inital post seem to suggest this is just about the locale setting for now (e.g. country + language)?

**Comment by sandy081** [comment]
Yeah currently we only support syncing display language as part of global state. Planning to extend it to more global state like activity bar icons, views visibilities etc.,

**Comment by gandalfsaxe** [comment]
Makes sense to add the basic functionality first 👍

I hope that somewhere down the line that grouping of session will be considered at some point (Group A will share these states, Group B will share these states, all groups will share these states etc.).

**Comment by sandy081** [comment]
Syncing global state (core) is supported now. Next step is to let state owners to opt in to sync the state - #93332

**Comment by eamodio** [comment]
@sandy081 how will extensions opt-in or out of this?

**Comment by sandy081** [comment]
Currently it is only supported for core. Planning to extend this to extensions in next milestone.
