### ISSUE TITLE
overwrite mode

### ISSUE THREAD

**Issue by blackshadev** [microsoft/vscode#86671]
Are there any plans for adding an overwrite mode (toggled by the insert key).

Most editors do have them so I was quite surprised monaco (and thus VSCode) doesn't.

**Comment by hilari0n** [comment]
I'm not sure why this was moved from [microsoft/monaco-editor](https://github.com/Microsoft/monaco-editor/issues) to [microsoft/vscode](https://github.com/microsoft/vscode/issues), as vscode already had this issue reported  #1012, and it [was explained](https://github.com/microsoft/vscode/issues/1012#issuecomment-474150574), that implementing this in vscode is a problem due to the monaco editor limitation. And the [monaco-editor](https://github.com/Microsoft/monaco-editor/issues) repo [READ.me](https://github.com/Microsoft/monaco-editor/blob/master/README.md#issues) says:

> Create issues in this repository for anything related to the Monaco Editor.

**Comment by hilari0n** [comment]
> This feature request is now a candidate for our backlog. The community has 60 days to upvote the issue. If it receives 20 upvotes we will move it to our backlog. If not, we will close it. To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Does anyone know if this mean 20 new upvotes? Don't the existing ones count?

**Comment by hilari0n** [comment]
To all those, who wrote "+1", "must have", "I second this", etc. in separate comments, please remember to actually click the 👍 emoji on the original comment. That's the accepted way of expressing support here and the only one, the  vscodebot is recognizing.

**Comment by nurbles** [comment]
Can the 238 votes from the original (FOUR YEAR OLD) report [#1012](https://github.com/microsoft/vscode/issues/1012) be added to this duplicate report?

Regardless, voting for the same issue AGAIN.  Sigh.

**Comment by meustrus** [comment]
I'll upvote this to support the many others who have demanded this feature. But please, give some consideration to user training - VS Code should either provide extra visibility of the feature for at least the first time it's turned on (for new users that may have hit the key by accident and don't know what's going on), or turn off the ability to toggle overwrite mode be default.

Also, I will point out that a markdown formatter (like the one included in [yzhang.markdown-all-in-one](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one)) is vastly superior to overwrite mode for editing ASCII tables because it works much better to grow and shrink column widths.

**Comment by mwpowellhtx** [comment]
I find this pretty funny, considering "most" editors worth their salt respond accordingly to the `Insert` key in *overwrite* mode.

**Comment by tig** [comment]
Shocked to discover INS doesn't work to toggle overwrite mode as expected. Shocked. Please fix.

**Comment by coder0xff** [comment]
@kburtram please close this as a duplicate of #1012

**Comment by cyraid** [comment]
> I'll upvote this to support the many others who have demanded this feature. But please, give some consideration to user training - VS Code should either provide extra visibility of the feature for at least the first time it's turned on (for new users that may have hit the key by accident and don't know what's going on), or turn off the ability to toggle overwrite mode be default.
> 
> Also, I will point out that a markdown formatter (like the one included in [yzhang.markdown-all-in-one](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one)) is vastly superior to overwrite mode for editing ASCII tables because it works much better to grow and shrink column widths.

Which non web editors don't support INS mode? In visual studio, jetbrains, I mean every other editor supports INS overtype and some type of overtype mode yet I'm not aware of new users having an issue with that on those editors? Not meaning offense here but, I'm not sure those new users should be using any editor yet at this point if they're not aware of that.

... Even Windows Wordpad has overtype with INS key..

**Comment by alexdima** [comment]
Let's track in #1012
