### ISSUE TITLE
Hovering only possible on current "active" file

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#86684]
Hi,

don't know if this is intended behavior or a bug. If it's intended then please turn this into a feature request.

I'm using the evaluateRequest to be informed about the cursor hovering about some string in the editor.
This is working if the file is the current file being debugged. I.e. the one where the program counter is.
Hovering in other source code files doesn't show any effect. evaluateRequest isn't even called.

**Comment by weinand** [comment]
No, the `evaluate` request is not "called from the debug adapter protocol".
`evaluate` is **part** of the protocol and it is "called from a client".
Since I assume that this client is VS Code, I've transferred the issue to the VS Code repo.

**Comment by isidorn** [comment]
Your explanation is correct.
I would just like to add that we evaluate on hover on source editors in scope only if the capability [`supportsEvaluateForHovers`](https://github.com/Microsoft/vscode/blob/15c35f55668e822c39fa9797722bd321cadaf8ab/src/vs/workbench/contrib/debug/common/debugProtocol.d.ts#L1347) is set. If this capability is not set, we will not evaluate but search for the variable in the variables view.

**Comment by weinand** [comment]
@isidorn good point!

**Comment by maziac** [comment]
OK, so this is "by design".

But what is the reason to only evaluate the source "in scope"?
As pointed out I could also hover over global variables in other files.

**Comment by isidorn** [comment]
Debug hover has the following heuristic:
* We only show the debug hover when the user is in a file that is the focused stack frame. The reason for this is that we do not want to agressivly show the hover and that the users usually have the stack frame focused that they are interested in. Agressivly showing the hover has the downsides of it being in the user's face when not needed and if evaluation is done it might have side effects.

We could change this to show the debug hover for any file that is part of the call stack however none of the users complained thus far at the current heuristic.
I do not mind keeping this issue open as a feature request since we might consider changning in the future that we show the debug hover for all files that are part of the call stack.

**Comment by maziac** [comment]
For my particular case it would not help much to allow hover on all files being part of the callstack.
I'm writing a debug adapter for assembler, i.e. everything is more or less global and there it would make sense to allow hovering on any file.

I understand your idea behind it. For modern languages it's most probably OK.
I just want to point out that if you change something, it would only help me if you allow any file, not just those being part of the callstack.

**Comment by isidorn** [comment]
Ok makes sense. 
In theory we could add a capability that debug extensions can control this.
Or a debug setting.
However nothing currently planned. We can look into this in the future

**Comment by maziac** [comment]
OK.

**Comment by weinand** [comment]
@maziac would you really need hovers on "any" file, or would files of a specific file type sufficient?

I'm asking because we already have a "language" sub-contribution for the "Debuggers" contribution that defines where breakpoints can be set. We could re-purpose this contribution for establishing a "global" scope.
