### ISSUE TITLE
Inline unfold not working on Firefox

### ISSUE THREAD

**Issue by EAlexRojas** [microsoft/vscode#86696]
**monaco-editor version:** 0.18.1
**Browser:** Firefox 70.0.1
**OS:** MacOS 10.14.6

**Steps or JS usage snippet reproducing the issue:**
It can be reproduced in the playground: https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-hello-world

![monaco-ff](https://user-images.githubusercontent.com/2373303/69563439-67017c00-0fb1-11ea-8083-1608c1e4c385.gif)

**Comment by aeschli** [comment]
The problem is that with FIrefox, the mouse event (IEditorMouseEvent) of a click in the text are doesn't have a target.range and folding relies on it to know which line was clicked.

Difference to Chrome is here:
https://github.com/microsoft/vscode/blob/806f1e51428aeaebe67974f1a34ba61c1cab445f/src/vs/editor/browser/controller/mouseTarget.ts#L992
