### ISSUE TITLE
Starting client failed: Couldn't start client Aura Language Server

### ISSUE THREAD

**Issue by neelgo** [microsoft/vscode#86717]
- VSCode Version: 1.40.2
- OS Version: windows 10

Steps to Reproduce:
I am using it for salesforce development and install salesforce extension pack
I am getting error from Aura Language server
[Error - 11:36:05 AM] Starting client failed
Error: spawn C:\Users\.....\Microsoft VS Code\Code.exe ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
	at onErrorNT (internal/child_process.js:456:16)
	at processTicksAndRejections (internal/process/task_queues.js:84:9)

*Tried reinstalling extension it failed shows same error
and reinstalled vscode also still same.
* Not sure but it is happening after last update. how I can go back to last version?

Does this issue occur when all extensions are disabled?: Yes/No
* Not sure how to do that and also I have to use it with extenstion for salesforce development
if it works without them still it is not useful.

![image](https://user-images.githubusercontent.com/9036100/70596788-c051e800-1c0c-11ea-95ac-05b5bf671432.png)

**Comment by RMacfarlane** [comment]
> Not sure but it is happening after last update. how I can go back to last version?

If you click the gear icon by the extension, you can use "Install Another Version" to go back to a different version:
![Screen Shot 2019-12-11 at 8 07 35 AM](https://user-images.githubusercontent.com/3672607/70638234-5d048d80-1bed-11ea-8df4-83a23fba57f3.png)

Since this is a problem with the Aura extension, please report it there: https://github.com/forcedotcom/salesforcedx-vscode
