### ISSUE TITLE
warning: matches multiple schemas when only one must validate

### ISSUE THREAD

**Issue by Zx-EvM** [microsoft/vscode#86738]
I use VSCode to edit `profiles.json` settings file for [Windows Terminal](https://github.com/microsoft/terminal).

My config looks this:

```
// To view the default settings, hold "alt" while clicking on the "Settings" button.
// For documentation on these settings, see: https://aka.ms/terminal-documentation
// https://github.com/microsoft/terminal/blob/master/doc/cascadia/SettingsSchema.md

{
    "$schema": "https://aka.ms/terminal-profiles-schema",

    "defaultProfile": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",

    "initialCols": 120,
    "initialRows": 30,

    "requestedTheme": "system",

    "profiles":
    [
        {
            // Make changes here to the powershell.exe profile
            "useAcrylic": true,
            "acrylicOpacity": 0.5,
            "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
            "name": "Windows PowerShell 6",
            "commandline": "C:\\Program Files\\PowerShell\\6\\pwsh.exe",
            "colorScheme": "Solarized Dark cmd-colors",
            "padding": "20, 10, 20, 20",
            "fontFace": "Cascadia Code",
            "fontSize": 12,
            "cursorShape": "filledBox",
            "hidden": false
        },
        {
            // Make changes here to the cmd.exe profile
            "guid": "{0caa0dad-35be-5f56-a8ff-afceeeaa6101}",
            "name": "cmd",
            "commandline": "cmd.exe",
            "hidden": false
        },
        {
            "useAcrylic": true,
            "acrylicOpacity": 0.5,
            "guid": "{c6eaf9f4-32a7-5fdc-b5cf-066e8a4b1e40}",
            "hidden": false,
            "name": "🤘 Ubuntu-18.04",
            "commandline": "wsl -d Ubuntu-18.04",
            "snapOnInput" : false, // scroll back to the command input line when typing
            "cursorColor": "#FFFFFF",
            "colorScheme": "UbuntuLegit",
            "source": "Windows.Terminal.Wsl",
            "padding": "20, 10, 20, 20",
            "fontFace": "Cascadia Code",
            "fontSize": 12,
            "cursorShape": "filledBox"
        },
        {
            "guid": "{b453ae62-4e3d-5e58-b989-0a998ec441b8}",
            "hidden": true,
            "name": "Azure Cloud Shell",
            "source": "Windows.Terminal.Azure"
        },
        {
            "guid": "{574e775e-4f2a-5b96-ac1e-a2962a402336}",
            "hidden": true,
            "name": "PowerShell Core",
            "source": "Windows.Terminal.PowershellCore"
        }
    ],

    // Add custom color schemes to this array
    "schemes": [{
        "background" : "#002B36",
        "black" : "#073642",
        "blue" : "#268BD2",
        "brightBlack" : "#002B36",
        "brightBlue" : "#839496",
        "brightCyan" : "#93A1A1",
        "brightGreen" : "#586E75",
        "brightPurple" : "#6C71C4",
        "brightRed" : "#CB4B16",
        "brightWhite" : "#FDF6E3",
        "brightYellow" : "#657B83",
        "cyan" : "#2AA198",
        "foreground" : "#839496",
        "green" : "#859900",
        "name" : "Solarized Dark",
        "purple" : "#D33682",
        "red" : "#DC322F",
        "white" : "#EEE8D5",
        "yellow" : "#B58900"
    },
    {
        "background": "#002B36",
        "brightBlack": "#073642",
        "brightBlue": "#268BD2",
        "black": "#002B36",
        "blue": "#839496",
        "cyan": "#93A1A1",
        "green": "#586E75",
        "purple": "#6C71C4",
        "red": "#CB4B16",
        "white": "#FDF6E3",
        "yellow": "#657B83",
        "brightCyan": "#2AA198",
        "foreground": "#839496",
        "brightGreen": "#859900",
        "name": "Solarized Dark cmd-colors",
        "brightPurple": "#D33682",
        "brightRed": "#DC322F",
        "brightWhite": "#EEE8D5",
        "brightYellow": "#B58900"
    },
    {
        "background" : "#FDF6E3",
        "black" : "#073642",
        "blue" : "#268BD2",
        "brightBlack" : "#002B36",
        "brightBlue" : "#839496",
        "brightCyan" : "#93A1A1",
        "brightGreen" : "#586E75",
        "brightPurple" : "#6C71C4",
        "brightRed" : "#CB4B16",
        "brightWhite" : "#FDF6E3",
        "brightYellow" : "#657B83",
        "cyan" : "#2AA198",
        "foreground" : "#073642",
        "green" : "#859900",
        "name" : "Solarized Light",
        "purple" : "#D33682",
        "red" : "#D30102",
        "white" : "#EEE8D5",
        "yellow" : "#B58900"
    },
    {
        "background" : "#2C001E",
        "black" : "#4E9A06",
        "blue" : "#3465A4",
        "brightBlack" : "#555753",
        "brightBlue" : "#729FCF",
        "brightCyan" : "#34E2E2",
        "brightGreen" : "#8AE234",
        "brightPurple" : "#AD7FA8",
        "brightRed" : "#EF2929",
        "brightWhite" : "#EEEEEE",
        "brightYellow" : "#FCE94F",
        "cyan" : "#06989A",
        "foreground" : "#EEEEEE",
        "green" : "#300A24",
        "name" : "UbuntuLegit",
        "purple" : "#75507B",
        "red" : "#CC0000",
        "white" : "#D3D7CF",
        "yellow" : "#C4A000"
    }],

    // Add any keybinding overrides to this array.
    // To unbind a default keybinding, set the command to "unbound"
    "keybindings": []
}
```

I noticed that VSCode shows warning in status bar:

```
{
	"resource": "/c:/Users/User/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/profiles.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "Matches multiple schemas when only one must validate.",
	"startLineNumber": 17,
	"startColumn": 5,
	"endLineNumber": 17,
	"endColumn": 6
}
```

Screenshot:

![WARNING](https://user-images.githubusercontent.com/20873402/70596057-b2ae5980-1c30-11ea-8db2-cff4c71688a0.png)

Is there something wrong with my `profiles.json`? Or it's just bug?

Related issue in WT repo: https://github.com/microsoft/terminal/issues/3909

**Comment by RMacfarlane** [comment]
@Zx-EvM I'm unable to find the string "Matches multiple schemas when only one must validate." in the VSCode code base, so I believe this diagnostic is coming from an extension.

**Comment by Zx-EvM** [comment]
@RMacfarlane issue reproduced with all extensions disabled

**Comment by IllusionMH** [comment]
@RMacfarlane I can repro this issue with latest insider and all extensions disabled.

VS Code version: Code - Insiders 1.42.0-insider (cbeff45f80213db0ddda2183170281ed97ed3b12, 2019-12-13T07:08:57.560Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (17.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-toc|Ala|1.5.6
vscode-css-modules|and|1.1.4
markdown-preview-github-styles|bie|0.1.6
vscode-css-modules|cli|0.2.3
bracket-pair-colorizer-2|Coe|0.0.29
gitlens|eam|10.2.0
remotehub|eam|0.5.0
toggle-excluded-files|eam|1.7.0
EditorConfig|Edi|0.14.3
LogFileHighlighter|emi|2.6.0
vscode-pull-request-github-insiders|Git|2019.12.15362
vscode-test-explorer|hbe|2.15.0
rest-client|hum|0.23.0
vscode-peacock|joh|3.2.0
code-fragments|mar|1.2.0
remote-wsl|ms-|0.41.5
debugger-for-chrome|msj|4.12.3
debugger-for-edge|msj|1.0.13
material-icon-theme|PKi|3.9.2
copy-relative-path-posix|rss|0.0.4
vscode-jest-test-adapter|rtb|0.2.0
code-settings-sync|Sha|3.4.3
quokka-vscode|Wal|1.0.265
markdown-pdf|yza|1.4.1


</details>


Most likely this issue came from JSON Schema validator (might be earlier [bundled with monaco monaco](https://github.com/search?q=%22Matches+multiple+schemas+when+only+one+must+validate.%22&type=Code)).

However other cases in the internet were caused by problems with schema and fixes there. Will try to check if Windows Terminal has problems with linked schema

**Comment by Zx-EvM** [comment]
@RMacfarlane reopen issue maybe?

**Comment by IllusionMH** [comment]
@Zx-EvM no reason to open this issue because problem is with schema

Linked schema is `"$schema": "https://aka.ms/terminal-profiles-schema"`.
Can be fixed by adding `"type": "object"` to `ProfilesObject` definition.
