### ISSUE TITLE
Feature request: Trigger quick action anywhere in line

### ISSUE THREAD

**Issue by vasiltabakov** [microsoft/vscode#86730]
We're looking into programatically solving this but it would be better if this was a feature of the editor, that is for a cursor positioned on a line with 1 or more quick fixes but not exactly in a quick fix range:
- if only one quick fix exists for a line trigger it (via Ctrl + .) for a cursor anywhere in the line
- if more than one quick fixes exist on the same line trigger the first from left to right or maybe have a widget listing them all with some kind of context info (e.g. column number)

For a cursor on the same line of the quick fix the demo below shows :
- Ctrl + . when cursor is inside the quick fix range
- Ctrl + . when cursor is outside the quick fix range 
![2019-06-07_08-32-40](https://user-images.githubusercontent.com/1178309/59083158-e82f5e80-88fe-11e9-98c5-5c3cc8960800.gif)

**Comment by mjbvz** [comment]
This is best left up to code action providers. Rational: we pass along the current cursor position to the code action providers. It makes more sense to me that these providers can look at that passed in position and decide to check a broader range, rather than us passing some already transformed range and requiring providers work backwards to get the current cursor position / selection

Also keep in mind that code actions are are used for refactoring as well
