### ISSUE TITLE
Minimap doesnt render cursor wordmatch highlights

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#86750]
Place cursor on a symbol, notice occurences of that symbol appear in ruler, with different colors for read and write access. Those decorations should appear in the minimap as well, but dont.

Here, the gray highlights in the ruler are occurences of the `meta` symbol.
![image](https://user-images.githubusercontent.com/8586769/70635740-48be9180-1be9-11ea-83b7-529ed536a47e.png)

**Comment by stinos** [comment]
This is *the* missing feature from the minimap for me, I'm so used to it from Subime Text that I use it often (e.g. for quickly finding references: double-click on word, all occurrences get clearly highlighted in minimap, just scroll). Alternatives for VSCode currently are selecting word then Alt-F3 to select all occurrences of Ctrl-F to seach occurrences, since selections and search results are shown in minimap.

**Comment by alexdima** [comment]
This has been implemented in the meantime
