### ISSUE TITLE
VSCode Python 3.7 unable to run code

### ISSUE THREAD

**Issue by FlowMeister** [microsoft/vscode#86774]
So when I type code, the text does not change color like it is supposed to (for example, writing 'if'). it also does not let me run code, as the green arrow in the top right isn't there like it's supposed to. And finally, the 'Python IntelliSense' system does not function in any way. When I write code, all of the text is grey. From looking at the startup tutorial I checked the python interpreter to see if it was selected, and as far as I know, it is working correctly. bear in mind that I am very new to VSC as well as programming in general  (taking computer science for GCSE), so any help would be much appreciated :)
example below:
![example](https://user-images.githubusercontent.com/58793330/70667559-19e80000-1c69-11ea-8516-ff486852d6a7.PNG)

**Comment by RMacfarlane** [comment]
Hey @FlowMeister, just to confirm, have you installed the Python extension? (https://code.visualstudio.com/docs/languages/python#_install-python-and-the-python-extension)

**Comment by FlowMeister** [comment]
@RMacfarlane Yep, I followed the guide on the VSCode page :)

**Comment by RMacfarlane** [comment]
@FlowMeister Looking at your first screenshot again, I suspect the issue there is that since this file has not been saved, it's marked as being plaintext rather than Python. In the statusbar in the lower right hand corner, there should be an indicator of what the current language is for the document. Once you save the document with a `.py` extension it should automatically update, you can also change it by clicking on that indicator or running the `Change Language Mode` command. You can also change what the default language is for untitled files with the `files.defaultLanguage` setting.

**Comment by FlowMeister** [comment]
@RMacfarlane Thank you so much! it's working properly now, I changed it from plaintext to python like you said and everything is fixed. Really appreciate the help.
