### ISSUE TITLE
Automatic extension installation feature

### ISSUE THREAD

**Issue by acidiney** [microsoft/vscode#86779]
Greetings to all, I would like to suggest a new feature to vscode.

Problem:
Every time I install vscode, I need to reinstall all the extensions I normally use.
As an example, I recently switched computers and had to manually install all the dependencies I already had on my old computer.

Solution:
One of the solutions that I found interesting is maybe having some optional authentication feature for the user. once it is authenticated all extensions that it installs will be registered. so in a new install of vscode the user would only need to log in that he would already install all extensions. (Verbose)

A less verbose solution is the possibility for the user to make a backup (such as a .vsix list) with all extension references that the user has already exported.

Thanks,

**Comment by RMacfarlane** [comment]
Hi @acidiney! We have actually started working on this feature, allowing users to login to automatically copy extensions and settings across computers: https://github.com/microsoft/vscode/issues/2743#issuecomment-560116420

We hope to have a preview version of this within the next couple of months.

Since there's already an existing issue for this, I'll close this as a duplicate. Thanks!
