### ISSUE TITLE
Mouse pointer in the hand shape jagged and unclear

### ISSUE THREAD

**Issue by Zhou-Yucheng** [microsoft/vscode#86825]
- VSCode Version: 1.40.2
- OS Version: Windows 10 1909

When I put my mouse pointer to a tab bar, the pointer will change to be a hand, like the following figure shows, and that's fine.
![_20191212225129](https://user-images.githubusercontent.com/36097684/70722344-13718b00-1d32-11ea-8914-ffeb6c350081.jpg)

Strangely, the hand will be extremely jagged and unclear when the place of it has no tab! As shown in the figure below.
![_20191212225133](https://user-images.githubusercontent.com/36097684/70722347-153b4e80-1d32-11ea-8005-48ce063b5bf9.jpg)

That's very annoying! 
Hope it can be fixed quickly.

The following information of my PC may be useful:
- Screen resolution: 3840 x 2160
- Scale: 200%

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@Zhou-Yucheng please report this to Chrome (http://new.crbug.com), we are using a simple CSS property to get that cursor and on Windows it seems they decided to draw it like that.

https://github.com/microsoft/vscode/blob/cbeff45f80213db0ddda2183170281ed97ed3b12/src/vs/workbench/browser/parts/editor/media/titlecontrol.css#L63-L65

**Comment by bpasero** [comment]
VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

Reading this issue, it seems to originate not from VSCode itself but rather one of these upstream components. As such, in order to resolve it, it would need to get fixed in the upstream component. I will go ahead and close this issue and kindly ask to report this issue to the upstream component if possible:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.

**Comment by Zhou-Yucheng** [comment]
OK, thank you for your reply

**Comment by bpasero** [comment]
@Zhou-Yucheng that was a bit quick, sorry. Can you open https://vscode-web-test-playground.azurewebsites.net/?enter=true and see if you see the same? I wonder if more recent versions of Chrome fixed this.

**Comment by Zhou-Yucheng** [comment]
I opened this link, and see the same (the unclear hand) again...

**Comment by bpasero** [comment]
@Zhou-Yucheng so I assume you see the same when you run this fiddle and move the mouse over the white rectangle bottom right: https://jsfiddle.net/cu1z65fp/ ?

**Comment by Zhou-Yucheng** [comment]
I'm sorry, I have tried several times but cannot open this link. Chrome said: Unable to access this site jsfiddle.net, the response time is too long.

Below is the screenshot about the previous link.
![微信图片_20191218000415](https://user-images.githubusercontent.com/36097684/71012473-2cab7a80-212a-11ea-935a-aa2ef3c77ccf.jpg)

**Comment by bpasero** [comment]
Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1035285

**Comment by bpasero** [comment]
Since this issue has a linked upstream issue referenced, I am going ahead to close this issue as part of our issue grooming effort: https://github.com/microsoft/vscode/wiki/Issue-Grooming
