### ISSUE TITLE
Strange behavior when completing JSON with schema

### ISSUE THREAD

**Issue by Fer0x** [microsoft/vscode#86824]
monaco-editor version: 0.14.3
Browser: Google Chrome 68
OS: macOS 10.13.5

I have a strange issue for completing JSON keys/values with schema: when your completing value and type `comma`, then some unexpected selection is starting. 
The issue can be reproduced on playground example https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults

Screencast: https://monosnap.com/file/99Bm90ybmClAzHqcuCgp8rqRWroMOV

**Comment by jrieken** [comment]
This is because JSON uses snippet completions and snippets don't end when pressing enter for a placeholder

**Comment by aeschli** [comment]
@jrieken Would it make sense to end snippet mode on enter?

**Comment by jrieken** [comment]
The standard behaviour of other editors (TextMate, Sublime) is not to do that we have aligned with them (years back). I am unsure if we should make an exception for snippet mode in IntelliSense because it will be confusing.

**Comment by aeschli** [comment]
I don't think we should change anything here
- you are completing a property and we guess the value. That's why the cursor is still at the value, as you still have to correct the value.

![image](https://user-images.githubusercontent.com/6461412/71812842-81327d80-3078-11ea-9db5-0558e4072c2c.png)

- Code complete brings you into the state above. The value is selected. As normal, any key will replace the selected range with the new key. And enter will add an enter.

So I think this is consistent. Not sure how we can improve it.

Note, command no longer is a completion character, I had to remove that for other reasons. Maybe that helps?
