### ISSUE TITLE
Block select with Shift-Alt

### ISSUE THREAD

**Issue by danbord** [microsoft/vscode#86831]
Issue Type: <b>Feature Request</b>

I often use the block select fucntionality.  to achieve that in Visual Studio (not VSCode) I used to use the Alt key with the mouse click&drag and it worked like a charm.

Now must combine Shift-Alt keys for that.  In Windows that key comibation switches the keyboard language when you have more than one!  Which is pretty annoying.

I strongly think that shortcut should be configurable.

Thanks

Daniel

VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.14393

**Comment by alexdima** [comment]
@danbord In VS Code, we call that column selection. Here is what I recommend:
1. install the [VS keymap](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vs-keybindings), which defines the keybindings `shift+alt+arrows` to do column selection.
2. free up `alt` for column selection mouse gestures. Configure `"editor.multiCursorModifier": "ctrlCmd"` which will make it that mouse selection + alt will switch to column selection mode.

Once you do these, column selection should hopefully feel similar to the one in VS. But there are still caveats, and some things do not work in the same way, mainly because VS Code does not have virtual spaces. You can find the existing issues [here](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aeditor-columnselect)
