### ISSUE TITLE
Ctrl+Shift+T should reopen release notes just as any other tab

### ISSUE THREAD

**Issue by thavlik** [microsoft/vscode#86864]
Sometimes when I open up my workspace, the release notes appear and get in the way. So I Ctrl+W the tab, only to remember that I actually wanted to read them! My expectation is somehow always that I can reopen the tab with the usual Ctrl+Shift+T combo, but it doesn't work like it does with normal editor tabs. It seems like it should, and this catches me off guard nearly every release cycle. While a silly thing, I probably haven't read half a dozen release notes because of it. The projected benefit is that us impulsive forgoers of release notes would have additional opportunity to read them.

**Comment by thavlik** [comment]
Whoops, wrong button. The above issue linked by vscodebot is not the same issue.

**Comment by ashuadh** [comment]
Hey I wanted to look into the bug and tried to reproduce the issue in the development version of vscode. However it gives the following error: Failed to fetch release notes and This version of Code - OSS Dev does not have release notes online. 
Could you tell me how to proceed? I would like to work on this bug 
PS- I'm new here.

**Comment by mjbvz** [comment]
Try running this again. The 1.49 release notes placeholder page should now be live

**Comment by jppianta** [comment]
Hi @ashuadh, do you need any help? I am looking to start contributing I thought this issue would be a nice start as well

**Comment by jppianta** [comment]
So, I was looking a lit bit further into the issue and I believe the issue is because the `release-notes` `webviewInput` instance is not serializable, which means that it is not added to the history on the `onEditorClosed` function.

I was trying to replicate the issue with other instances of `webviewInput`, for example the markdown preview, and found out that `mainThreadWebviewPanel`s are serializable, so I guess making the release notes a mainThreadWebviewPanel would be a solution, just not sure if a good one yet (I am still very new to the code). End it finding that reopening a markdown preview also leads to an error, but it is a different bug that I shall open later on.

**Comment by jppianta** [comment]
Also discovered that doing these steps with an extension webView also leads to the same issue as the release notes

**Comment by AbduAmeen** [comment]
Does this need to be open? There is already a binding that could be set.
