### ISSUE TITLE
Dependency cycle between remote and tunnelView

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#86924]
1. Start vscode out of source
2. Open developer tools > open console > notice warning

```
/Users/isidor/Development/vscode/out/vs/loader.js:1591 There is a dependency cycle between 'vs/workbench/contrib/remote/browser/remote' and 'vs/workbench/contrib/remote/browser/tunnelView'. The cyclic path follows:

vs/workbench/contrib/remote/browser/remote => 
vs/workbench/contrib/remote/browser/tunnelView => 
vs/workbench/contrib/remote/browser/remote
```

**Comment by sbatten** [comment]
I notice that a few things are defined in `remote.contribution.ts` and then imported into remote. Should there be a `remote.ts` file in common that houses these things including the forwardedPorts context key that is the issue here?

e.g. Look at `viewsExtensionPoints.ts`. the other views export their `VIEWLET_ID` from a common folder in the form `<view>.ts` and the `<view>.contribution.ts` file is in browser. I think the pattern is supposed to be that `contribution.ts` files are only referenced from the `main.ts` files.

**Comment by alexr00** [comment]
Fixed with https://github.com/microsoft/vscode/commit/c1b74a9cff9a1f3225fe040d8cda319aefcef13a
