### ISSUE TITLE
HTML mirror cursor Ctrl+Enter Problem

### ISSUE THREAD

**Issue by tajpouria** [microsoft/vscode#87016]
- VSCode Version: 1.41
- OS Version: Windows 10

### See the following gif:
![vscodeMirorCursor](https://user-images.githubusercontent.com/46822325/70859537-73cb1d00-1f2a-11ea-972d-b0cdc12a7ad5.gif)

Steps to Reproduce:
1. Put the cursor in the **middle** or **end** of the tag then hit Ctrl+Enter (in my case O cuz I'm using Vim extension)

I Believe current behaviour is a bug because when I tried the same action by hitting just Enter (and not Ctrl+Enter) it makes **one line space** and not two,

Does this issue occur when all extensions are disabled?:  YES

**Comment by gavin310** [comment]
I'm having a similar issue on OS X, however when I put the cursor inside any opening HTML tag and begin typing, it applies the text to both the opening and closing tag. For example on the tag `<div>` if I put my cursor between the `v` and the `>` and begin typing ` class="test"`, the opening tag will be `<div class="test">` and the closing tag will now be `</div class="test">`.

**Comment by javislaterlp** [comment]
I really think that attribute should be off by default. It gives many problems and awkward behavior for such small benefit (we already have matching tag highlighting, ctrl + D, replace, etc). It can even break temporarily some extensions by assuming they expect automatic mirror.

**Comment by gavin310** [comment]
@javislaterlp I agree. Even if it wasn't buggy, I don't think it should be a default feature.

**Comment by octref** [comment]
This is how multi-cursor behaves:

![newline](https://user-images.githubusercontent.com/4033249/71025814-b91f5400-20bc-11ea-996c-f6e167a402e6.gif)

If you have it enabled, you should move out of the mirror region before pressing `o`. Pressing ESC can't exit mirror mode because Vim extension handles ESC. With this feature, you get the benefits of easily doing `dw` or `cw` to change the tag.
If you don't have it enabled, you can open new line normally. But you don't get the benefit to edit beginning and ending tag at the same time.

> we already have matching tag highlighting, ctrl + D, replace, etc

None of them are semantic, so they don't work for structures like this:

```html
<div>
  <div></div>
</div>
```

I don't think we can just change how multi-cursor works. You can either:

1. Use this feature and be careful to go out of mirror mode before opening new line.
2. Turn off this feature and use F2 to rename.

**Comment by octref** [comment]
@gavin310 This doesn't happen to me. Please open a new bug report with repro steps.
![repro](https://user-images.githubusercontent.com/4033249/71026530-4a42fa80-20be-11ea-8b15-c7c32cdb098d.gif)

**Comment by gavin310** [comment]
@octref I can't get it to happen consistently. If I figure out how to repeat it I'll open a bug report. Thanks
