### ISSUE TITLE
HTML CSS Class Completion: Fetching info message causes lock up.

### ISSUE THREAD

**Issue by demyte** [Microsoft/vscode#8702]
- VSCode Version:1.3.0-insider (a2b9738a942237b59cb920940b93a0206f1b61d0)
- OS Version: Windows 10 (14376)

Steps to Reproduce:

1. Open CSS file
2. When the Info message comes up for HTML CSS Class Completion.. please wait..
3. Window becomes unresponsive and the Reopen or keep waiting dialog appears
4. Pressing re-open does not kill the processes and restart VSCode
5. I have to kill all the tasks manually in task manager.

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by demyte** [comment]
Hi @bpasero 

You are correct, sorry I didn't notice that myself.

Thanks for the quick response.
