### ISSUE TITLE
Cursor over line numbers is oversized (Chrome 51)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8708]
Seems like the same issue as https://github.com/Microsoft/monaco-editor/issues/5

![editors](https://cloud.githubusercontent.com/assets/900690/16552321/5f9cd436-41c0-11e6-831a-a668276e0054.gif)

**Comment by alexandrudima** [comment]
@bgashler1 For the standalone editor, I removed this style. As you added these CSS rules, maybe you know what's going on?

**Comment by bgashler1** [comment]
@alexandrudima it seems that we've gone back to an older Electron version and that this is not currently an issue?  Will close for now, since I cannot reproduce in VS Code on Mac with a Retina display.  Please reopen if it's still an issue.

**A little background:** the CSS rules with the 2x sized image was a workaround for this [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=325565), which causes SVG cursors to be pre-rasterized (as if they were a png) before being rendered, causing pixelation on hdpi screens.

**Comment by bpasero** [comment]
@bgashler1 we will hit this issue again eventually once we update. Note that the next jump would be to Chrome 52, not sure if that would make a difference.

**Comment by bpasero** [comment]
Still happens in Chrome 52, reopening.

**Comment by bpasero** [comment]
No Electron update for August...

**Comment by brunnopleffken** [comment]
@bpasero Not trying to ignore the issue, but just giving my two cents: really worth being stuck in an old version of Chromium and an equally old "zero-point-x" version of Electron because of an inverted cursor?

Reading their changelog, you're missing a bunch of new features and improvements: https://github.com/electron/electron/releases

**Comment by bpasero** [comment]
@brunnopleffken this issue does not block our Electron update, but this one https://github.com/electron/electron/issues/5715

Feel free to provide a PR to fix this issue for them 👍

**Comment by Emeryao** [comment]
I got a TEMPORARY solution  for this issue:
change the css class of `.monaco-editor .margin-view-overlays .line-numbers` in file `workbench.main.css`
with the style below:
```css
cursor: -webkit-image-set(url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' height='45' widht='30' viewBox='0 0 15 21'%3E%3Cpath fill='%23fff' stroke='%23000' d='M14.5 1.2L1.9 13.8h5.2l-2.6 5.3 3.2 1 2.6-5.2 4.2 3.1z'/%3E%3C/svg%3E") 2x) 30 0,default;
```
the key of this TEMPORARY solution is the `height` and `width` attribute of the svg tag.

**Comment by bgashler1** [comment]
@Emeryao thanks for discovering the width and height issue.  Pushing a commit that fixes this at the root of the problem.
