### ISSUE TITLE
Ctrl+click twice in file explorer does not open file "To the side"

### ISSUE THREAD

**Issue by thernstig** [microsoft/vscode#87082]
With file explorer open, one has the option to right-click and select "Open to the side".

If a user ctrl+clicks a file in the file explorer, it first gets selected. I expect a second ctrl+click to "Open to the side", as explained above. What happens instead is the file that was selected first in the explorer is the one that gets opened to the side.

**Comment by isidorn** [comment]
This is a fair feature request. However we currently move focus to the file if it is double cliked.
Changing this would be breaking behavior, thus we will not do anything here atm

**Comment by thernstig** [comment]
@isidorn I am not sure I follow. I am not doing a normal double-click, I am doing a double-click with ctrl held down.

**Comment by isidorn** [comment]
It works great for me. Opens to the side and the focus is moved.
![doubleClick](https://user-images.githubusercontent.com/1926584/70918589-95f29700-201f-11ea-9a6a-e7ed86c9fc05.gif)

**Comment by thernstig** [comment]
Strange, I am using the currently upgraded version to 1.41.0. I will have to try to disable plugins and all and try to see if I can replicate on a bare minimum and get back to you.

**Comment by jzyrobert** [comment]
I can repro this on 1.41.0 with no extensions.

- Reload with extensions disabled
- Single click one file
- Ctrl double click another file
- The originally focused file will open _again_ in the side editor

![2019-12-16_21-54-54](https://user-images.githubusercontent.com/20613660/70946522-2eecd680-204f-11ea-9c31-768321a50092.gif)

**Comment by thernstig** [comment]
@jzyrobert I just made a recording myself haha, but thanks for beating me to it. That's exactly what I am experiencing.

**Comment by thernstig** [comment]
@isidorn Just pinging you again to see if this should be changed to a bug instead of feature request?

**Comment by isidorn** [comment]
I can reproduce this also in the previous stable. So not a regression.
But I do agree it is a bug.

**Comment by jzyrobert** [comment]
@isidorn 
The above commit results in the second file you ctrl + click (After one file has focus) opening to the side, which I believe is unintended.

From some testing, I think this is both a bug and a feature request!
When you ctrl + double click a second file, what happens is:

- The first click adds the file to the selection but (before the above commit) did not trigger an open.
- The second click removes the file from the selection!
- However, because the event is a double click, `onSelection` in `listService.ts` will still trigger a open request, due to `if (this.tree.openOnSingleClick || isDoubleClick || isKeyboardEvent)`
- The `open` function assumes that the first file in the selection is the one you want `element: this.tree.getSelection()[0],`, and incorrectly opens the originally selected file to the side.

So I think what could be added is on ctrl+double click keep the file in the selection but trigger an open event anyways?

**Comment by isidorn** [comment]
Yes that was not my intention. So reverting my commit, and yes we agree the real fix is that ctrl+ double click should not change the selection.

**Comment by jzyrobert** [comment]
So if I understand, Ctrl + double click should:

- Add the file to selection
- AND open it to the side?

**Comment by jzyrobert** [comment]
Also @isidorn 
I don't think you need to revert the commit.
It is part of a larger bug where `onSelection` calls `open` when it shouldn't.
Before, the code inside `onDidOpenResource` caught that case, but the underlying issue is that the function shouldn't be called.

**Comment by isidorn** [comment]
Yeah, ctrl + double clik should add it to the selection and open to the side ideally.
The revert does not hurt.

**Comment by thernstig** [comment]
@isidorn Should this really be closed? I get stuck on this like every week trying to ctrl+left-click a file every now and then to try to open it to the right side.

**Comment by thernstig** [comment]
This was fixed in release 1.52.0.

**Comment by isidorn** [comment]
Thanks for letting us know
