### ISSUE TITLE
no conecta

### ISSUE THREAD

**Issue by Marcos-Antoni** [microsoft/vscode#87132]
Hemos escrito los datos necesarios en su Portapapeles porque eran demasiado grandes para enviarlos. Ahora debe pegarlos.

**Comment by dbaeumer** [comment]
Translated: 

We have written the necessary data on your Clipboard because they were too big to send. Now you must stick them.

Looks like the auto generated performance bug. I will close it since without the data there is nothing we can act on. @Marcos-Antoni if you see that again please attach the data from the clipboard.
