### ISSUE TITLE
Mirror cursor makes extra copy when duplicating row

### ISSUE THREAD

**Issue by SavchukSergey** [microsoft/vscode#87161]
- VSCode Version: 1.41
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. Write **singleline** html tag, e.g.:
 ```html
<div></div>
```
2. Put cursor inside tag name. Cursor is mirrored as expected
3. Press duplicate line (alt+shift+down). This results in three html line
 ```html
<div></div>
<div></div>
<div></div>
```
When cursor is not inside tag name everything is ok

Does this issue occur when all extensions are disabled?: Yes

**Comment by octref** [comment]
@alexdima Would you take a PR that makes "duplicate line" only duplicate one line when both cursors are on the same line?

**Comment by SavchukSergey** [comment]
> @alexdima Would you take a PR that makes "duplicate line" only duplicate one line when both cursors are on the same line?

Or it might be more generic solution. Group all cursors by line number and then duplicate each line only once. If I add 3 cursors on first line, 5 cursors on second line and so on then press duplicate I do not need so much copies.

**Comment by hamzahamidi** [comment]
I don't think this is can be considered a bug. Double cursors create double duplicates. This is the normal behavior.

**Comment by Errors4l** [comment]
@hamzahamidi That'd be fine if the user created the mirror cursor with an action (keyboard shortcut). Now you have to make sure where your cursor is located _within a line_ before duplicating it, because the mirror cursor is created automatically when your main cursor is within a html tag.

It is possible to get rid of the mirror cursor with <kbd>Esc</kbd>, but that's an additional action to work around the problem. I find it hard to think of use cases where you would want to duplicate a line as many times as there's a cursor in that line (and then there's also a difference between multiple cursors and mirrored cursors).

**Comment by hamzahamidi** [comment]
The automatic double cursor is needed to edit the tag just once.

**Comment by Errors4l** [comment]
Couldn't agree with you more. That's the entire point of the feature shipped in this months update. That said, the duplicate (and other) behaviour seems like an oversight during development.

The mirror cursor is meant to simplify modification of the tag. Duplicating the line with the mirrored cursor (be it on the same or other line) is a bit strange, as the intent was to duplicate the line and not the tag (note the command name is `Copy Line Down`).

I feel like the mirror cursor is something unique and different from multiple cursors. It shouldn't follow the same behaviour as the normal cursor(s). Differentiating between them with visual styles would also communicate that better to the user (https://github.com/microsoft/vscode/issues/85630).

**Comment by octref** [comment]
In tomorrow's insiders `html.mirrorCursorOnMatchingTag` is replaced with `editor.renameOnType`. The new implementation fixes this issue. You can find more details here: https://github.com/microsoft/vscode/issues/88424#issuecomment-600840619
