### ISSUE TITLE
Cannot connect to the Extensions Marketplace if opened as administrator

### ISSUE THREAD

**Issue by keithlockeaf** [microsoft/vscode#87194]
If I open VSCode as an administrator, I cannot access the extensions marketplace.  However, if I open it not as an administrator, I can access the extensions marketplace just fine.  I did not have this issue before I updated to the latest edition of VSCode.

Opened as Administrator:
![image](https://user-images.githubusercontent.com/23314283/71022140-cbee5480-20cd-11ea-958f-fa0f3afeec9e.png)

Opened as a normal user:
![image](https://user-images.githubusercontent.com/23314283/71022180-e294ab80-20cd-11ea-8738-a379f51ed481.png)

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)
