### ISSUE TITLE
"convertToDto unexpected type" not helpful error message

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#87196]
![image](https://user-images.githubusercontent.com/323878/71026066-3f3b9a80-20bd-11ea-9bb9-ef270eec5992.png)

I've seen this error message many times while working on the new DA and have to remind myself what it means every time. Not many people will see it but maybe it could be more useful. But it essentially means that the extension which provides a DebugAdapterDescriptorFactory is not activated when we are trying to start a debug session with its debug type. Either because the activationEvent was wrong, or it failed to activate for another reason. It could say "couldn't find a DebugAdapterDescriptor for type xyz" or something like that. Thanks

**Comment by isidorn** [comment]
This is coming from [here](https://github.com/Microsoft/vscode/blob/26f5dfcd76c9a02f116a706844611aeb09ae8c0b/src/vs/workbench/api/common/extHostDebugService.ts#L718)
Forwarding to @weinand since the introduced the convertion
And I do agree we could tune the message. Also the message needs localization.

**Comment by weinand** [comment]
@roblourens I never saw that message (and I was not expecting that anyone would see it).
But you are right: if activation does not happen for some reason, there will be no DA.

An end user should never see this, but a debug extension author might see it.

Rob, after adding an `onDebug` or `onDebugAdapterProtocolTracker` or `onDebugAdapterProtocolTracker:type` event, did the problem disappear? Or is there another lurking issue?

**Comment by roblourens** [comment]
Yeah it only shows up when the activation events are wrong or when the extension throws during activation. I don't see it when the extension does everything correctly.

**Comment by weinand** [comment]
I've improved the error reporting in this area. The original error now uses this wording:

![2020-01-08_16-56-12](https://user-images.githubusercontent.com/1898161/71993726-df598f00-3237-11ea-9462-8808030f93bb.png)

Since these errors are not visible to end users, I did not bother with localisation.
