### ISSUE TITLE
Disable Windows system sound triggered by a failed Debug task

### ISSUE THREAD

**Issue by chylex** [microsoft/vscode#87213]
Hi, when I run Debug with a failing prelaunch task on Windows, VS Code shows an error message that plays a system sound.

I would like to have an option to disable these sounds. They are categorized under *system sounds* in Windows Volume Mixer, so I cannot simply mute just VS Code because it doesn't show up in there at all. **I don't want to disable all system sounds**, just those played by VS Code.

If you cannot control the dialog box sounds, perhaps it'd be good to have an option to bypass this dialog completely and set a default action instead (such as showing the Problems or Terminal panel if there were any errors). In any case, thanks for looking into it!

![error message example](https://user-images.githubusercontent.com/3685160/71046309-3936cf80-2138-11ea-9846-5677d768bfae.png)

**Comment by isidorn** [comment]
This is fixed in latest. Just update vscode and now there is a checkmark that will remember your choice, that way you will not see that dialog again.
Configuring if the native dialog should emit a sound is a feature request against Electron and you can file it there if you are pasisonate about this.
