### ISSUE TITLE
Debug: opened "launch.json" after clicking "Configure" should be pinned

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#8727]
Noticed the file opens non-pinned. But since it is being created it should open pinned.

**Comment by bpasero** [comment]
Same for workspace settings actually. Maybe assign to me once you did it for debug. I can also check how it behaves for tasks.

**Comment by isidorn** [comment]
Both [debug](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/node/debugConfigurationManager.ts#L355) and [tasks] (https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/tasks/electron-browser/task.contribution.ts#L258) use the same API. So not sure if the editor service `openEditor` api should automatically pin if somebody calls the openEditor that is already opened, or should each api consumer first check if the editor is visible in order to pass `pinned: true`.
Let me know what you prefer and I can adopt it.

**Comment by isidorn** [comment]
If I understood your original reasoning you want the file pinned if it is being created, or if already opened and user clicks configure?

**Comment by bpasero** [comment]
@isidorn I thought the file should get pinned if we actually create it. I thought we would create it in these cases.

**Comment by isidorn** [comment]
@bpasero if the file is already created, clicking on the configure action just opens the file. File only gets created if it is nonexistent and I can pin it in that case - let me do that for tasks and debug

**Comment by bpasero** [comment]
@isidorn yes that would be great and follows our pattern of what should get pinned by default. I can then look into pinning the settings file when it is being created.

**Comment by isidorn** [comment]
@bpasero did it for launch and tasks, forwarding to you so you can investigate settings

**Comment by bpasero** [comment]
Decided to always open all settings files pinned (also "Default Settings"). Why? Because this does not destroy any preview editor the user might have so you can nicely escape settings by closing 2 editors and restore the previous view state.
