### ISSUE TITLE
Panel Restoration is at wrong height

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#87294]
This only started to happen since the Insiders 2 days ago.

I'm not sure what changed, but the restored panel height in new workspaces and old workspaces are both below what I usually see.

<img width="839" alt="Screen Shot 2019-12-18 at 3 35 54 PM" src="https://user-images.githubusercontent.com/4033249/71132492-7c328a80-21ac-11ea-98e7-39d742bf2bb2.png">

**Comment by pdanpdan** [comment]
On Windows 10 (at least) the bottom Problems panel loses the top border (and I think some top padding) when changed from it to another panel (say Output) and then back to Problems panel.

Resizing the bottom panel fixes it until the next tab switch.

In order to reproduce the height of the bottom panel should be small (the sweet spot seem to be 156px).

Might be related to this, #87242 and to the fix for #87173 (as it appeared after the fix).

**Comment by sbatten** [comment]
@octref please recheck this in today's build as I made some changes yesterday.

**Comment by octref** [comment]
LGTM now.
