### ISSUE TITLE
Subfolder Structure

### ISSUE THREAD

**Issue by randal923** [microsoft/vscode#87292]
- VSCode Version: 1.41.0
- OS Version: Windows 10 10.0.18362

My VS Code is not showing the sub folders when there is only one folder, it only shows when there is 2 or more. I attached a screenshot to show an example. I would like to make it show all the folders. I have been looking for how to make it go back to showing all the folders but could not find how.

https://i.stack.imgur.com/qOH6n.png

If I add more folders it goes back to normal. I would to make it show the Search folder even if it is the only folder inside Input.

 https://i.stack.imgur.com/yhSOL.png

I'm not sure if this a bug or not, but I have asked a couple of friends and this does not happen to them. 
Steps to Reproduce:
1. Create a folder with only one subfolder

Does this issue occur when all extensions are disabled?: Tried to open it with extensions disabled but my project doesn't even work. I guess it is because I use WSL.

**Comment by IllusionMH** [comment]
This is new feature Compact folders. Please see feature description and how to turn it off in Update post [Compact folders in Explorer](https://code.visualstudio.com/updates/v1_41#_compact-folders-in-explorer)


/cc @isidorn for visibility since this is not the first similar report for this feature.
Probably new features enabled by default need more visibility (same happened to another new feature #87271)

**Comment by isidorn** [comment]
@IllusionMH thanks a lot for ansewering. 
So just use:
`"explorer.compactFolders": false`
