### ISSUE TITLE
Santa Hat removal on vscode insiders and bending to one jew is very offensive to me

### ISSUE THREAD

**Issue by nymda** [microsoft/vscode#87291]
There is no reason to remove a feature that thousands of people got enjoyment from because one guy got offended by it. Put the hat back.

**Comment by bhack** [comment]
History of culture Is full of cross-pollination, overlaps, new meanings on old symbols and so on...
It Is like to avoid to use eggs or rabbits at easter time or to forbid the use of easter eggs in the code cause easter was early connected to Pesach that has still symbologies related to the death of all the Egyptian first-born and so It could offensive for Egyptian.
Where does freedom really end?

**Comment by wmDevCodes** [comment]
Wow.... I'm offended by this [guy's](https://github.com/microsoft/vscode/issues/87268) offensiveness.

**Comment by bhack** [comment]
And honestly the modern standardization of Santa and his hat It Is more related to coca-cola brand than the differnt historical rappresentations (so how much religion do you see in that hat symbology?): https://www.coca-cola.co.uk/faq/is-it-true-santa-is-red-because-of-coca-cola

**Comment by JaDaar** [comment]
Put the hat back

**Comment by wmDevCodes** [comment]
Who is David Ben Mesecke? [https://www.thurrott.com/users/DavidBenMesecke/](https://www.thurrott.com/users/DavidBenMesecke/)

**Comment by bhack** [comment]
> I don't know what is worse.... this [guy](https://github.com/microsoft/vscode/issues/87268) seeing a swastika in a santa hat, or Microsoft capitulating within minutes because "muh feelings"

Nazi corrupted Swastika symbology [in 1930s](https://en.m.wikipedia.org/wiki/Swastika).
As I told It is a very common process in cultural dynamics but so the process could have many flow directions in centuries. See also the historical evolution of (Fasces symbology) and its meanings [https://en.m.wikipedia.org/wiki/Fasces].

**Comment by bhack** [comment]
I wanted you to clarify these points even if I don't know if I would like a defacto vscode doodlesim as proposed in https://github.com/microsoft/vscode/issues/87293

**Comment by VitAndrGuid** [comment]
OYYYYYYYYYYYYY VEYYYYYYYYYYYYYYYY

**Comment by cellycell** [comment]
I'm crying

**Comment by KamranMackey** [comment]
Jumping in to share my stance on the matter. The fact that the Santa Hat was removed over one complaint instead of getting opinions from the entire user base is absurd. The Santa Hat should be reinstated. Millions upon millions of people take part in Christmas holidays. I understand that some 
(in certain religions) find it offensive, but that doesn't mean something should be removed based on one complaint. I'd really like to see the Santa Hat reinstated.

**Comment by Cellomonster** [comment]
This is so dumb it makes me mad. MS, please just add the hat back. It's hurting literally no one but that one guy.

**Comment by carverh** [comment]
Microsoft if thou art not adding the Santa hat back I am afraid thou hath to be declar'd LOW CHURCH PURITANS!
![image](https://user-images.githubusercontent.com/7690997/71147357-71dcb480-21dd-11ea-9529-15c46f834bd2.png)

**Comment by foxabilo** [comment]
You folded and removed the Santa hat that represents the majority of your users faith after a single user made a complaint. Shame on you.

**Comment by foxabilo** [comment]
I just contacted Linus Tech Tips, get ready for some very unwelcome publicity.

**Comment by Anonimista** [comment]
Santa did nothing wrong. He's always been like a son to me and he's a great kid. I'd never seen him do anything offensive - kids that don't get their presents may get offended but that's not really Santa's fault. There's nothing offensive about Christmas either although the two are not really related.

**Comment by Anonimista** [comment]
Please guys, that Christian Shiffer person has nothing to do with Jews, he's just a troll.

**Comment by carverh** [comment]
> Please guys, that Christian Shiffer person has nothing to do with Jews, he's just a troll.

The page he quoted was a Jewish site but yeah, probably he is offended on others' behalves.

**Comment by bweigel** [comment]
Why don't you put in a (supposedly) religious symbol for every major religious holiday of any religion? That way everyone can be offended once.

**Comment by Techman** [comment]
Well, the issue I originally commented on was closed so I'll put my comments here since this is considered to be the "responding issue."

---
Specifically regarding #87268:

Please reinstate the Santa hat. I am almost certain that it was a holiday gesture to have it included in the first place, and is not an attempt to inject religiously-charged themes into the editor. I appreciate the slight touch of the developers by adding a very small festive decoration to the editor.

**Comment by MaurogDark** [comment]
> > Please guys, that Christian Shiffer person has nothing to do with Jews, he's just a troll.
> 
> The page he quoted was a Jewish site but yeah, probably he is offended on others' behalves.

In a comment since deleted by the mods, he put it thusly:

"Here we go again, I am so disgusted with people who want to have "fun" dancing on the grave of others. I am not Jewish by the way, I am German, a Noahide. As a German I do have a responsibility to speak out against things like that. Yet, the level of dismay and disgust I feel when reading such comments, I am not able to try to help people who do not want to see the light. This will be my last comment, downvote it as much as you like. It speaks about nothing else then your character or rather, lack thereof"

**Comment by americanhawk1** [comment]
My post was closed because it was a "duplicate" of this post, so I will post it here:


I'm deeply offended that the Santa hat was removed.

It's a disgrace to the Christmas holiday and to what it represents. "The most important thing about Christmas is that it invites us to reflect on the most important things in our life — our faith, our family, and our freedom. Our faith gives us hope, our family gives us love, and our freedom gives us the opportunity to practice our faith and to love each other — and of course the Holy Family."

In removing this hat, you're deeply offending all Christians and their faith, as well as non-believers who look up to the Christmas holiday as much more than a holiday, but a symbol for love and passion as well as bringing family together. We are representing the "good" side of what Christmas and Santa represents. It's unbelievable that one person got offended and the hat was removed... at least make it a toggle... You guys probably made more people mad than you did happy about this decision.

**Comment by plasticuproject** [comment]
My post was closed because it was a "duplicate" of this post, so I will post it here:

Shame on you for removing the festive hat. It's a hat, it doesn't represent any of that garbage the requester said. I'd argue that the hat represents keeping your head warm in cold weather. The hat is equally as unoffensive as the cog that it was set upon. You all shouldn't just add or remove a feature just because one person, out of tens of thousands, claims to be unreasonably offended. You should have done due diligence and researched on your own to see if it was a valid criticism.

**Comment by egamma** [comment]
The red hat icon was actually reused from last year and this was good reminder to try something different. I love the snow flake, let's stick to that:

<img width="220" alt="image" src="https://user-images.githubusercontent.com/172399/71155878-0aefe780-223f-11ea-9095-0199e0c87d0f.png">
