### ISSUE TITLE
consider separating URI fragment before passing to TextDocumentContentProvider.provideTextDocumentContent

### ISSUE THREAD

**Issue by akosyakov** [microsoft/vscode#87332]
From https://tools.ietf.org/html/rfc3986#section-3.5:
> As such, the fragment identifier is not used in the scheme-specific processing of a URI; instead, the fragment identifier is separated from the rest of the URI prior to a dereference, and thus the   identifying information within the fragment itself is dereferenced solely by the user agent, regardless of the URI scheme.

Right now VS Code as a user agent resolves different primary content for the very same URIs with only different fragments, leading to opening different editors for example. According to the definition above semantic of `fragment` is not defined by scheme,  but a user-agent. Maybe there should be another way to dereference a separated fragment later after resolving the primary content without fragment?

Currently VS Code extensions are misusing `fragment` when they are better to use `query`: https://github.com/WebFreak001/code-debug/blob/f46a821ad9faf3491d65f899bc7c77500039d15b/src/frontend/extension.ts#L95

**Comment by jrieken** [comment]
What you say makes sense but I think it's too late to change the URIs that get passed to providers. In fact, this was a deliberate choice because it allows context providers to pass along data that's useful for generating contents. So, there is a purpose and on top of that we cannot break the semantics here. 

However, we can consider to exclude the fragment when comparing URIs to "input" equality (cc @bpasero). That would mean `foo://bar#baz` and `foo://bar#bang` would be considered to be one editor despite it causing to calls to the content provider. However, it needs careful design and thinking as such changes often cause carnage.

**Comment by bpasero** [comment]
Isn't this piece covered when we do https://github.com/microsoft/vscode/issues/93368 ?

**Comment by jrieken** [comment]
Not sure - it's kind of a different bucket because it affects extensions and how stable we keep these things. @akosyakov sample above is scary

**Comment by jrieken** [comment]
@bpasero fyi - I have pushed a telemetry event that fires whenever the text model resolver sees a uris with query or fragment. The former is OK, the latter isn't

**Comment by bpasero** [comment]
Anything actionable here?

**Comment by colin-grant-work** [comment]
Another example of a plugin relying on fragments to identify documents is Redhat's YAML plugin:

https://github.com/redhat-developer/yaml-language-server/blob/cb688a6a7ff8612d78c85a083515c1f6b2a0522b/src/languageservice/services/yamlCommands.ts#L19-L24

If the fragment is stripped away before the call to provide content, even though all the information necessary to identify the intended schema is present in the path, content loading fails.
