### ISSUE TITLE
Split Editor asks if I want to save the file

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#8733]
- VSCode Version: 1.3.0-insider
- OS Version: Windows 10

Can be with "workbench.editor.showTabs": true or false

Steps to Reproduce:

1. Open a file for example in html.
2. Activate the Split Editor.
3. Modify the left file or direct.
4. Close the Split Editor.

The VSCode asks if I want to save.

- VSCode Version: 1.2.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a file for example in html.
2. Activate the Split Editor.
3. Modify the left file or direct.
4. Close the Split Editor.

It seems that the VSCode see that are not the same file and asks if I want to save.

This behavior is correct or is a new specific configuration?

The only way I found to close without saving the file would be dragging the Split tab to the same file from the internal window.

**Comment by bpasero** [comment]
This was an explicit UX decision because we think a user might be confused why closing an editor does not ask for confirmation. It might not be so obvious that the dirty editor is opened in more than one group because it could be well hidden in one group among many other tabs.

@stevencl @bgashler1 fyi

**Comment by Tekbr** [comment]
Sorry, but if I close the editor completely, he asks me if I want to save the changes.

VSCode keeps opened and modified files are in the "Working Files - stable" or "Open Editors - insiders" in Explorer. I liked to show seperate, even though the same file.

If closing a group of tabs I agree with this behavior, but closing this single file, seems strange this new behavior.

![capturar1](https://cloud.githubusercontent.com/assets/19866231/16567644/6177d738-41f7-11e6-9845-6a2bef73b3b2.JPG)


Is there no way to verify if they are the same file, regardless of whether you are the right or left side of the editor? If the same file, do not ask the question until the latter is closed. In the last ask me if I want to save.

At least one setting in User Settings, so you can choose the behavior of this situation.

Anyway thanks.

**Comment by bpasero** [comment]
No, we cannot. See attached picture:

![image](https://cloud.githubusercontent.com/assets/900690/16568472/d7b7fb70-422a-11e6-9c5a-e125f0700b2f.png)

Closing "Untitled-1" we have to ask you to save the file even if it is opened in the left hand group. The user does not know that the file is opened in the left hand group because there are many files open. The user might wonder why he was not asked to save the file on close.

I am not sure how I can explain myself better...

**Comment by Tekbr** [comment]
Thanks for the clarification and sorry for being slow to respond. I'll have to adapt to the new functionality.
