### ISSUE TITLE
"Light themes" section comes before "Dark themes" in settings dropdown which is very offensive to me

### ISSUE THREAD

**Issue by jablpiotrek** [microsoft/vscode#87345]
Version: 1.41.0
Commit: 9579eda04fdb3a9bba2750f15193e5fafe16b959
Date: 2019-12-12T20:38:10.027Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

Steps to reproduce:
1. Download November 2019 release of Visual Studio Code
2. Search for "Color theme" in settings dialog

![Zrzut ekranu 2019-12-19 11 34 54](https://user-images.githubusercontent.com/25666892/71167051-3b8e4c00-2254-11ea-985f-c680a7976b1d.png)

For some reason, "Light themes" comes before the "Dark themes" list while searching for, in the settings search dialog. I find this very offensive.  Not only Dark Themes section is separated with a disgusting, racist line from the Light Themes, but (of course!), Light Themes come before the Dark Ones. 
We should ask a serious question, why, in such an inclusive and compassionate environment which we try to create in the Community, there is still space for such disgusting practice, reminding me of the darkest times of human history? I, on behalf of all who have been offended and have no courage to oppose such an outrageous example of Light Theme Supremacy, demand that themes should be listed according to alphabetical order, rather than to ones distorted and repelling personal beliefs.

Solution idea:
In the listing, themes should be sorted either alphabetically or randomly, and color scheme should be no factor.

**Comment by Danielx64** [comment]
My vote goes for alphabetically.

**Comment by Hissvard** [comment]
Ordering them alphabetically might open another whole can of worms. Am I less of a human just because my surname starts with Z? Should people whose names start with B be given that much power over the largely oppressed R people?

I say we shuffle them every time to prevent initial-shaming of differently-named people.

**Comment by ip413** [comment]
@Hissvard is completely right, we have to shuffle commands and also colors. VSC should start with random theme. I mean... not completely random, should adjusted to number of people with specific colors in your country... or maybe on the globe, because we don't want to leave anybody out.

I'm thinking also about plugins... I don't think that ordering them in any specific direction does anything good. Rather not!

**Comment by about-code** [comment]
I suggest allowing theme selection by terminal command, only. Then maybe code editors are being used by people, again, who are in need of a technical solution not in need of a therapy. But I already hear social justice warriors screeming "giving computers commands is immoral because it manifests a culture a master-slave thinking".

**Comment by sunriseiscool** [comment]
Racism in a code editor. Disgusting. Unacceptable.
