### ISSUE TITLE
The removal of Santa Hat on vscode insiders is very offensive and has nothing to do with religion 

### ISSUE THREAD

**Issue by Danielx64** [microsoft/vscode#87342]
Steps to Reproduce:
Install latest build of insiders.

Does this issue occur when all extensions are disabled?: No

Sorry but the guy who created https://github.com/microsoft/vscode/issues/87268 has it all wrong. Having a santa hat on a cog icon (to go to settings/options) has nothing to do with religion in any shape or form.

I find it offensive that the hat was removed and it should never have been removed in the first place.

**Comment by arkadiuszwojcik** [comment]
Two more things to add. @Christian-Schiffer have something against santa hat and releats it to religion. Pardon me but he dosn't distinguish between Saint Nicholas that was bishop and had totally diffrent hat and Santa Claus from popular culture who have other hat. Besides his name "Christian" smells like some kind of religious agitation and I think he should remove his account or be baned by highter autorities using his own argumentation preented in issue #87268 . Should I create separate issue for that?

**Comment by MaKiPL** [comment]
User Christian-Schiffer offends many users and Microsoft just standing there like nothing happened. Bring back the Santa's hat!

**Comment by MaKiPL** [comment]
to also add to that- The original requestor for this ridiculous change has 14 repositories from which 13 are forks. I doubt he's even a developer, just random troll that you- Microsoft fell for. Shame

**Comment by prometheus61** [comment]
I liked the santa hat, it brought a little joy to my day. Very sad that it has been removed.

**Comment by Hissvard** [comment]
I demand syntax highlighting be removed, as it reminds me of the other night when I puked out the three plates of ravioli I'd eaten. It is very offensive to me and instantly brings back memories of a very bad stomachache.

See this? That's how silly that was. We can't take people seriously just because they slap religion on something completely unrelated and pretend it's a serious issue.

That's offensive to **real** religious issues if anything. That's how real issues end up being taken as jokes.

**Comment by Phillipus** [comment]
I find the "V" in "VS Code" offensive. It represents two fingers being held up in an obscene gesture and could be read as "F*ck You".

**Comment by danielhoset27** [comment]
![Screen-shot-2012-06-18-at-10 32 45-AM](https://user-images.githubusercontent.com/20308061/71171259-3e3d7100-2255-11ea-943f-60bbf1c82230.png)

**Comment by kIllmEpLz-dev** [comment]
I agree. Nowadays everyone is offended by everything. The fact that he doesn't like the hat has nothing to do with religion. I find Hissvard's comment "That's offensive to real religious issues" completely right. There are real religious issues by now, and classifying such a thing (the hat) as "offensive" should be considered shameful.

**Comment by ip413** [comment]
Sad thing is that some of us are afraid of writing anything about it and they are writing from newly created accounts and... and I understand it. No one know who will be targeted and his life/career be destroyed by "tolerance troops" which have nothing to do with tolerance.

We are going into very, very gloomy era. Chinese government is doing very same thing as "political correctness" is doing to us. 

**Whoever is afraid is a slave** - Seneca the Younger
And we all are afraid - especially MS, as we could see.

**Comment by wolfensg** [comment]
UpVote for Santa Hat! 🎅 Bring it back! Don't fall for the troll!

**Comment by dioptryk** [comment]
We're moving to digital totalitarianism, pure and simple. In totalitarian state, anyone who voiced a different opinion than the state's, was forcibly silenced or 'disappeared'. Now, we have threads locked, accounts banned and single people deciding what's best for entire communities based on their 'feelings'. Well, I 'feel' it's pure evil masquerading as tolerance.

**Comment by shakeyourbunny** [comment]
It is very telling the true colours on the side of the Microsoft team that this is still up in the air instead of making - as it would be a proper reaction - to write a short apology for the mistake, revert the change and be done with it. 

Added bonus would have been that the whole issue would be forgotten very everyone in some days. 

So, this leaves a very sour taste regarding the whole thing and it has already the very opposite intented effect of "quick political correct reaction and stay clean" for the whole Microsoft and only will be worse if this will not be corrected and sit out.

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. 

Happy Coding!
