### ISSUE TITLE
Please rename "Terminal" section of menu, because it's offensive to me

### ISSUE THREAD

**Issue by dsemennyuk** [microsoft/vscode#87351]
When I was young, we've traveled with my parents to Russia. 
One time in the Siberian city - "Novosibirsk", I got lost at the airport. There was a nightmare. I was cold and scared. The bears and drunk Russians were all that was what I saw.
And I remember big nameplate "TERMINAL C".
And now when I'm looking at the terminal section in VS code it's offending me.

**Comment by hugmouse** [comment]
I think it is necessary to **remove** this "Terminal" word, as it can really offend someone's feelings in some country at some time. Additionally "Terminal" has cost millions of Jews their lives over the centuries because the word "terminal" could also mean ["Extermination Camp"](https://en.wikipedia.org/wiki/Extermination_camp).

---

Please remove it immediately and make it your top priority.

**Comment by hugmouse** [comment]
I also want to apologize for what I said from above, because I could have insulted someone with it. 

I also didn't want to insult those who don't know English. We need to get rid of the language barrier, so I translated the text into other languages. To be exact, it's 8. It's not all languages in the world, so I apologize for that too.

There's also no menu navigation because I forgot how to do it in markdown. I apologize for that too, if someone was insulted by the fact that there is no navigation menu.

## Translations

### Русский

Я думаю, что необходимо убрать это слово "Терминал", так как оно может действительно обидеть чьи-то чувства в какой-то стране в какой-то момент времени. Кроме того, слово "Терминал" на протяжении веков стоило миллионам евреев их жизни, потому что слово "Терминал" также может означать "Истребительный лагерь".

### Deutsch

Ich denke, es ist notwendig, dieses "Terminal"-Wort zu entfernen, da es in manchen Ländern irgendwann wirklich die Gefühle von jemandem verletzen kann. Zusätzlich hat "Terminal" über die Jahrhunderte Millionen von Juden das Leben gekostet, weil das Wort "Terminal" auch "Vernichtungslager" bedeuten könnte.

### Français:

Je pense qu'il est nécessaire de supprimer ce mot "Terminal", car il peut vraiment offenser les sentiments de quelqu'un dans un pays à un moment donné. De plus, le mot "Terminal" a coûté la vie à des millions de Juifs au cours des siècles, car le mot "terminal" pourrait aussi signifier "camp d'extermination".

### Español

Creo que es necesario eliminar esta palabra "Terminal", ya que puede ofender realmente los sentimientos de alguien en algún país en algún momento. Además, "Terminal" ha costado la vida a millones de judíos a lo largo de los siglos porque la palabra "terminal" también podría significar "Campo de exterminio".

### Português:

Eu acho que é necessário remover esta palavra "Terminal", pois ela pode realmente ofender os sentimentos de alguém em algum país em algum momento. Além disso, "Terminal" tem custado a vida de milhões de judeus ao longo dos séculos porque a palavra "terminal" também pode significar "Campo de Extermínio".

### Italiano

Penso che sia necessario rimuovere questa parola "Terminale", in quanto può davvero offendere i sentimenti di qualcuno in qualche paese in un certo momento. Inoltre "Terminale" è costato la vita a milioni di ebrei nel corso dei secoli, perché la parola "terminale" potrebbe significare anche "Campo di sterminio".

### Nederlandse

Ik denk dat het nodig is om dit "terminaal" woord te verwijderen, want het kan echt beledigend zijn voor iemands gevoelens in een bepaald land op een bepaald moment. Bovendien heeft "Terminal" door de eeuwen heen miljoenen Joden het leven gekost, omdat het woord "terminal" ook "vernietigingskamp" zou kunnen betekenen.

### Polski

Uważam, że należy usunąć to słowo "Terminal", ponieważ może ono naprawdę urazić czyjeś uczucia w jakimś kraju w pewnym momencie. Dodatkowo "Terminal" kosztował miliony Żydów życie na przestrzeni wieków, ponieważ słowo "Terminal" może oznaczać również "Obóz Zagłady".

**Comment by ivanpopelyshev** [comment]
Rejoice, Terminal C victim!

That nightmare was closed, there are only Terminals A and B in airport.

**Comment by hckr** [comment]
"Terminal" might also remind someone about a terminal illness they are facing

**Comment by dsemennyuk** [comment]
@ivanpopelyshev Oh my god! Man! It's something that I wish for the years! Christmas miracle literally exists!

**Comment by kieferrm** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
