### ISSUE TITLE
Question: are new downloads in the extension folder deleted at extension update/removal?

### ISSUE THREAD

**Issue by davidanthoff** [Microsoft/vscode#8736]
My [extension](https://github.com/JuliaEditorSupport/julia-vscode) downloads additional code into the extension folder at first run. So in addition to the files that are packaged in the extension itself (i.e. published to the gallery), there will be more files in the folder of the extension once it has run once.

I'm trying to figure out how those files will be treated when the extension is updated or removed from the system by a user. Will the whole extension folder just be deleted, and all those additional files will be gone? That would actually be my preferred option. Or is there any other implication of such a design? Should I really store those additional files somewhere else? But then how can I delete them when the extension is removed, there is no "uninstall" hook in the extension API where I could delete those files, right?

**Comment by joaomoreno** [comment]
In Windows, the entire `extensions` folder is wiped out. Not sure about OS X or Linux. A good fallback would be to scope the downloaded files into a folder named with the Code version.

**Comment by davidanthoff** [comment]
@joaomoreno Could you leave this issue open until it is fully resolved? I.e. until there is also a response for macOS and Linux?

Also, just to confirm: when I *update* an extension, the previous version of that extension will be removed by deleting the whole folder for that extension, including any new files the extension might have written into that folder, correct? It was not clear to me from your response whether you were talking about extension uninstall or update, or both.

**Comment by davidanthoff** [comment]
Oh, and just naming the download folder by including the version of the extension would work, but if these folders don't get removed I would leave lots of stranded files on user's system, which seems less than ideal.

**Comment by joaomoreno** [comment]
I just realised I gave you a wrong answer: I had built-in extensions in mind, not regular extensions installed via the marketplace. I also had in mind Code's update, not the extension itself... Apologies, got it completely wrong.

Here's the behaviour you can count on:

- An extension is always installed to a folder scoped with its version name, eg: `ext-1.0.0`.
- Thus, an update will always hit another folder, eg: `ext-2.0.0`.
- A removal will wipe out the entire extension folder, so it would also delete any extra files you downloaded there.
- There is periodic garbage collection to remove old versions left behind due to updates. Eg: when the user installs `2.0.0`, the `1.0.0` folder can't be removed since it's still being used by the running instance; it will be deleted eventually, once `2.0.0` is used.

**Comment by davidanthoff** [comment]
Perfect, thanks!
