### ISSUE TITLE
Stop fixing bugs

### ISSUE THREAD

**Issue by Meithal** [microsoft/vscode#87365]
It is a weird request but when I was a child my stepfather used to beat me all the time for no reason, he was also a math teacher, so today when I see a computer working flawlessly it reminds me of him and I feel oppressed.

So please keep some bugs and let your program do some mistakes so I can relate to him more easily.

Fix steps:
- create tag "will maybe fix" (actually means "will never fix")
- assign it to random critical issues

This will ensure the program will Always remain full of bugs.

Thank you.

**Comment by Hulkstance** [comment]
Lmao. Use a hammer then. It immediately adds an additional critical issue report.

**Comment by OctavioCore** [comment]
I'd like to see this implemented - as a matter of fact, I did have many traumatic events in my past, related to computers. When I was in school, I've been asked by IT teachers to "fix something cause it's not working" countless times. When I've diagnosed the issue, it always came out that it's the teacher's incompetence fault, and the computer is operating normally.

If the computers wouldn't work, we could spare people like me the horrific experience of explaining that "It's just done wrong, you have to do it like this [...]" and also save the teachers from the feelings of obsolescence, incompetence and weak knowledge/depression incurred by those feelings.

No one should ever feel miserable because of devices and software working as intended, and if we, as a civilization, can do anything to extinguish the possibilities of traumatic experiences and horrific pain that lingers for life when something "just works fine", we should do it. We should act now. 

Somewhere in the world, there is a boy, a girl, or anyone, who's currently dealing with operational software or hardware. Let's stop it, and end the nightmare.
