### ISSUE TITLE
Please change the debugger icon

### ISSUE THREAD

**Issue by hckr** [microsoft/vscode#87376]
I'm an entomophobe and the debugger tab icon causes me much pain every time I have to use VS Code.

![obraz](https://user-images.githubusercontent.com/1078650/71176580-71d6c600-226a-11ea-9492-8f30d0d43366.png)

**Comment by nkkollaw** [comment]
🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅 🎅

**Comment by hckr** [comment]
Please don't laugh. It's a serious matter for me.

**Comment by x1024** [comment]
It's actually pretty bigoted to imply that removing bugs is a good thing, as though bug lives don't matter? What is going on here?

**Comment by hckr** [comment]
I don't intend to cause bugs any harm. To be honest, I've never even used a debugger. I'm just very afraid of this icon.

**Comment by karevn** [comment]
It also offends insects for sure

**Comment by theonemcdonald** [comment]
I agree, this icon keeps me awake at night. I've had to seek professional help because of this icon.

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!

**Comment by hckr** [comment]
@chrisdias All joking aside, how is my issue different than infamous #87268?

**Comment by TheAifam5** [comment]
@hckr check https://github.com/microsoft/vscode/issues/87440
Still, for me is an unacceptable behavior from Microsoft side.

**Comment by hckr** [comment]
@TheAifam5 Thanks, I've already read it. I have an honest question, why this issue was flagged as off-topic and the one with "Santa Hat" didn't. Maybe the context was obvious, but I still see this as a double standard within the process.

**Comment by chrisdias** [comment]
@hckr sorry about this.  we had many issues be reported that were sarcastic in nature, such as "I'm a non programmer I find 'code' offensive" and this issue came in around the same time and followed what we saw was a similar pattern. It looks like someone making a joke about the debug icon, in much the same way some were making jokes about the gear icon. As a result, we closed this one too.

You can right click on the activity bar on the left and uncheck "Debug":

![image](https://user-images.githubusercontent.com/1487073/71283568-786e4780-2315-11ea-85b4-87f7a5d22e1f.png)

That will hide the icon from the activity bar. You can still debug from the menu, by pressing `F5` or by bringing up the debug viewlet through the command palette (`F1`) or the keyboard shortcut `CTRL+SHIFT+D` on Windows/Linux, and `CMD+SHIFT+D` on Mac.
