### ISSUE TITLE
Santa hat removal

### ISSUE THREAD

**Issue by Asgoret** [microsoft/vscode#87389]
Are you happy @Christian-Schiffer? Your behaviour offence a lot of people around the world.  
I think you must apologize to these people and @egamma must do it too.

**UPD#1:** Christmas, like Hanukkah, is a great time of the year. When people give each other a little love, warmth and kindness. Trying to be better than they were during the year. So why spoil this wonderful moment of world peace with unfounded accusations, old insults and other unpleasant things? I don’t understand, and you?

Assign: 
https://github.com/microsoft/vscode/issues/87268
https://github.com/microsoft/vscode/issues/87386

**Comment by virgiliu** [comment]
Assuming he wasn't just trolling: if one gets butthurt and triggered over an emoji or icon, then the internet is not really the place where one should hang around.
Assuming he was trolling: troll successful, gg


Pandering to icon haters seems to be high on Microsoft's list instead of handling actual bug fixes or feature requests.

**Comment by appgurueu** [comment]
I'm also not happy that the santa hat was removed, completely ignoring the public opinion here on GH.

**Comment by chrisdias** [comment]
Thanks for creating this issue. We think this issue is unactionable or unrelated to the goals of this project. Please follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
