### ISSUE TITLE
Update: The repository is open again

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#87440]
_Update: 12/20/2019_

Well, that was unexpected. 
 
If you didn’t notice, we locked down the `vscode` repository for the last ~24 hours because of what some are calling "SantaGate”. We learned a lot, made some changes, and now we want to share with everyone what happened, how we handled it, and how we will handle this going forward. 
 
#### A little background… 
 
For the past few Decembers we changed the settings gear in the Insiders build to have a red hat with a white pom-pom (aka a Santa hat). To the gear menu we add a “Happy Holidays” command that shows an overlay (with snow!) and wish the community a happy holiday season as we wind down, take time off to spend with family and friends, and get ready for the new year. 
 
#### What happened… 
 
Earlier this week, we were notified through an issue (and on twitter) that the design of the gear with the Santa hat was divisive and offensive to some of our users (even a single person being offended is one too many), meaning it represented the opposite of what we wanted to convey to our users. In the spirit of the season, and to practice inclusiveness, we reverted the gear to something (hopefully) less controversial (a snowflake) and checked it into the Insiders build. 
 
There were a few “thumbs down” on the issue, which is a common and respectful way to disagree, but we decided the change kept the spirit and conveyed our best wishes for the holidays, without offending any of our users. 
 
Much to our surprise, many people were fond of the holiday treatment, so when we changed it, they were a little disappointed with us. Someone filed an issue, and we closed it pointing to the original issue that was raised. Someone else filed a new issue. And then another. And another. 
 
Some agreed with what we did, some did not, and many tried to make their point using humor. Now, we love humor (especially the references to Monty Python movies), but unfortunately a few went well beyond tasteful, were directed at people rather than the product, and violated our [Code of Conduct]( https://opensource.microsoft.com/codeofconduct/). 
 
To adhere to our values and the Code of Conduct, we had to delete a handful of comments, which is unfortunate but not uncommon. Our responses triggered more responses. Bots were being employed to create issues and comments. Temporary accounts were being created to spam the system. Offensive issues were being created. The repository was filling up with issues which, frankly, were uncalled for, and we needed to do something, fast. 
 
It was at that point we decided to lock the repository down to contributors using the Moderation feature of GitHub, so that we could clean up the backlog and let emotions settle. We posted this issue (which was titled “Why can’t I file an issue right now?”), locked it, and then went to work cleaning up the backlog. 
 
#### Cleaning up issues… 
 
We follow Microsoft’s Code of Conduct here, which means we can and do remove issues and comments that we believe do not follow the guidelines. At the same time, we want to be transparent. We were sensitive to some comments that suggested we were “censoring” feedback, which is an unfortunate interpretation of what we had to do, which was to delete offensive content targeted at individuals or racial or religious groups. 
 
In a nutshell, we did the following: 
- Created a new label called `*off-topic` and tagged issues with it, which caused our triage bots to close the issue, making it easier for us to go through the backlog more quickly. 
- If the issue was already closed by a team member, we added the `*off-topic` label and added the reason for closure manually. 
- To allow people to see what we closed, we left the issues unlocked, and decided we would only lock it if necessitated by later Code of Conduct violations. 
- We deleted a handful of comments which we deemed too offensive to leave as-is (foul language, racist remarks, etc.). We also deleted a few issues that were overwhelmingly offensive. Unfortunately, that resulted in some non-offensive comments within those issues being deleted as well. 
 
#### The feedback… 
 
As you can imagine, we heard a lot of feedback in these issues. Some were upset at the original issue, but the majority were upset at us in how we responded. The icon change, locking of issues, removing comments, not responding (until now obviously), and more. Some even felt that we were violating our own Code of Conduct. 
 
All good feedback, thank you, and we apologize to everyone offended by the product or by our responses. 
 
#### Looking forward… 
 
If you’ve looked at our settings, you know that you get a lot of choice with VS Code. We decided to follow this pattern and let users configure how the gear looks. We’ve added a new setting to [Insiders](https://code.visualstudio.com/insiders/) that lets you choose the icon. If you like the red hat, go for it! Maybe you live in the southern hemisphere or you are heading to the beach during the holidays, there’s an icon for you too. 
- Open settings (Mac: CMD+, Windows/Linux: CTRL+,) and search for “Holiday Gear Icon Style”, and choose your icon 
- If you love editing `settings.json`, set `holiday.gearIconStyle` 
 
You will still find the “Happy Holidays” command which will bring up the overlay, snow, and message. 
 
And finally, as we did in previous years, we will remove this little treat around the first week of January. In the meantime, download Insiders now and have a happy holiday season from all of us in Redmond and Zurich. 
 
#### In conclusion… 
 
Having a community as large as ours is an interesting challenge, especially once you step out of the boundaries of "business only". This pause allowed us to get back to what we do best - develop software for you - and we implemented a solution that we hope can be enjoyed by everyone. 
 
Thanks, and #HappyCoding, 
The VS Code team

-----

_12/19/2019_

This repository is temporarily limited to collaborators as a result of a number of issues being submitted containing content which violates the [Microsoft Code of Conduct](https://opensource.microsoft.com/codeofconduct/).  

We will remove the offending issues and comments which we determine do not adhere to the Code of Conduct. 

We apologize for the inconvenience this creates for our contributors.

**Comment by cfanoulis** [comment]
just wanted to pass by and say thanks for handling this so well :)

**Comment by levkach** [comment]
So what's the drama thing here please?

**Comment by gabrieltaets** [comment]
Well, perhaps the initial handling of the issue could have gone better but I suppose it's all good now. A new preference seems fit, and lessons have been learned, not only by the maintainers but hopefully by all the community.
What I feel that still needs to be said is whether a claim of "being offended" should qualify for a Change Request. You're free to "feel offended" by whatever you want. But feeling offended by something as small as a Santa Hat says a lot more about you than it says about the product carrying it.
And once you hear the people claiming to be offended by arbitrary changes, you open precedents to the insane amout of unreasonable complaints we have been seeing around here (since feeling offended is such a personal matter, how do you tell which claim is genuine and which isn't?)

Even though the maintainers were receiving feedback from other sources, it was unfortunate to reply to that single (possibly troll) issue which made it look like the sole reason for the removal of Santa's hat was because one single person felt offended.

**Comment by Potherca** [comment]
As someone who has not been following the "drama", I really appreciate the background provided by this issue. 

The only thing that seems to have gone "wrong" was the omission of the reason why the change was made (i.e. not as a response to an individual complaint). Everything after that was just a pile-on.

Somehow I am reminded of the proverb "For want of a nail the war was lost."

But correlation is _not_ causation and the lessons seem to have been learned. 
Lets hope the  normal program(ming) can now resume.

Again, thanks for keeping us informed @chrisdias!

And to everyone, especially contributors and maintainers:

**Have a Happy (and well deserved) Holiday!**

**Comment by MartinX3** [comment]
I can confirm @gabrieltaets and wish everyone a Merry Christmas.

**Comment by egee-irl** [comment]
I'd love to see an official answer to @chrisdias 's question

> And once you hear the people claiming to be offended by arbitrary changes, you open precedents to the insane amount of unreasonable complaints we have been seeing around here

There are already dozens of bogus issues claiming various things about VSCode are offending people, likely because of this drama.

And in the update post, OP says:

> even a single person being offended is one too many

So, what would happen if someone submitted an issue claiming to be offended by the VSCode icon itself? Or maybe some of the tooltip icons look a bit too divisive and someone requests change to those too?

Now that the precedent has been set, where does it end? At what point do we stop coding new features and spend all our time fixing old ones because ~~trolls~~ people are getting "offended" by them?

**Comment by AgelStrong** [comment]
sorry

**Comment by AgelStrong** [comment]
bat not stopid live... black is deat of eart

**Comment by sarpik** [comment]
How about linking to *this* issue from the one that caused all of this (https://github.com/microsoft/vscode/issues/87268)?

I would've definitely missed this response if I didn't happen to just randomly open the issue tracker itself. Thanks.

**Comment by puppy0cam** [comment]
Twitter is not real life, it barely even resembles it and is largely used to propagate controversy and misleading information.
It is _**IMPOSSIBLE**_ to please everyone. If it will have no impact on the majority, it's fine to add a small thing for a minority. But if it is actively against the majority, it just doesn't make sense to go with that minority opinion.

**Comment by virgiliu** [comment]
> even a single person being offended is one too many

are you fuckin serious?

**Comment by AgelStrong** [comment]
,realfine:)25 дек. 2019 г. 21:52 пользователь Virgiliu <notifications@github.com> написал:
even a single person being offended is one too many

are you fuckin serious?

**Comment by Jarrich** [comment]
> > even a single person being offended is one too many
> 
> are you fuckin serious?

That is indeed a bit worrying.

**Comment by mike-code** [comment]
Here's product that doesn't offend anyone

![image](https://user-images.githubusercontent.com/2964642/71517611-2bf3b080-28af-11ea-8685-73601655f066.png)

seriously the only thing this planet deserve is a giant meteor

**Comment by limonte** [comment]
> Here's product that doesn't offend anyone

It does offend me with its sharp corners! People were killed with sharp heavy objects like that one! How dare you?! Please round the corners asap!!11

**Comment by Atulin** [comment]
> Here's product that doesn't offend anyone

How dare you post such a racist image, it's all white! When I take it to Twitter you're getting cancelled!

**Comment by nm111** [comment]
The snowflake is a metaphor for the snowflakes that were offended by a santa hat

**Comment by Tameflame** [comment]
I find it ironic that more people were enraged by the removal of the Santa hat than by it being there in the first place.

However, ultimately the icon is irrelevant, but when it comes to functional changes / features, I hope the team doesn't give in to the demands of a few over the interests of everyone else.

**Comment by lucasbasquerotto** [comment]
> I find it ironic that more people were enraged by the removal of the Santa hat than by it being there in the first place.

I think that most people don't care so much about the Santa Hat per se, it's more about the removal of it because someone (supposedly) [felt offended](https://github.com/microsoft/vscode/issues/87268) by something so irrelevant, which could be applied to basically every other thing, and life would become inviable because [anything can offend anyone](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aclosed+offensive+).

**Comment by GrimTheReaper** [comment]
I love how the troll who felt offended deleted their account (or at least, it looks like it?)

**Comment by lunarthegrey** [comment]
Microsoft, you are literally spineless for giving into this silly behavior. I could point at any object and claim it's offensive.

**Comment by lviggiano** [comment]
I'm offended by the removal of Santa Hat, and so many Santa believers.

**Comment by mkaito** [comment]
I'm pretty squarely agnostic. I don't perceive Christmas in a religious context whatsoever. For me, it's about family, goodwill, and sharing. It's my favorite time of the year.

I'm appalled that the idea of Christmas or Santa's hat could construed as pushing a religious agenda. That is narrow sighted, fallacious, regressive and very self-centered. Maybe some people just have so much hatred and pain in their lives that they can't help but share it with everyone else.

Why can't we all just get along, respect one another, and get on with life, instead of wasting time and energy on these petty squabbles?

**Comment by bdrtsky** [comment]
Thank you Microsoft for fueling the upcoming Race War.

**Comment by tvanrielwendrich** [comment]
Pretty sure that Santa Claus as currently portrayed was an image of Coca Cola ([Wikipedia backs this up](https://en.wikipedia.org/wiki/Santa_Claus)), not a religious thing at all. Which supports the idea this was entirely caused by a troll.

**Comment by rcuza** [comment]
In the future, perhaps the Santa hat and other colorful features can be added as easter eggs.  With this method, you have to opt in to be offended.

**Comment by RedVinchenzo** [comment]
@chrisdias , was mentionned  

> We will remove the offending issues and comments which we determine do not adhere to the Code of Conduct.

But I still can find [original issue](https://github.com/microsoft/vscode/issues/87268), with as offensive as agressive terms :

>  To me this is almost equally offensive as a swastika.

Don't want to talk about religious people, but comparing Christmas to that, is not offensive for all person celebrating Christmas ? Religious or not ?

So if you really remove offending comments, please delete (forever) this issue.

**Comment by moongoal** [comment]
Today everyone wastes everyone else's time with the "feeling offended" trend. Just grow up, you little flowers. <- I hope nobody gets offended by being called a little flower as they are little, beautiful, delicate living things.

> Pretty sure that Santa Claus as currently portrayed was an image of Coca Cola ([Wikipedia backs this up](https://en.wikipedia.org/wiki/Santa_Claus)), not a religious thing at all. Which supports the idea this was entirely caused by a troll.

Indeed.

**Comment by pajasevi** [comment]
I feel offended by you putting your time to even consider making up for these lunatics who are offended by literally anything.

**Comment by cope** [comment]
I have a serious question here, given that I am extremely offended by your removal of the Santa Hat, and especially by the comparisson of the Santa Hat with swastika, what will you do to remedy that offence?

I am actually not joking, I find your reaction and your removal of the hat immensly offensive.

So, how do you plan to handle this issue?

**Will you tell me that his offense is more important than mine?**

**Comment by R2D221** [comment]
I just want to add a final opinion on the matter.

I didn't like the fact that you added a setting to change the holiday icon. The whole point of Easter eggs like these are to greet the user with a pleasant surprise, right? Well, then, how can the surprise work if you have to open up the config file and set up the icon you want to be "surprised" with? I think it defeats the purpose of this little feature.

I couldn't comment while the drama was happening because, well, it was happening. But I still wanted to say it, so that people don't forget the point of the features they're implementing, even if they're just for fun.

You don't configure a surprise.

**Comment by RinzlerTron** [comment]
I'm not Christian, but I do hate seeing these issues politicized so someone can claim offense to ruin things for other people. These inane issues should be left out of products and engineering culture in general, because they ruin user experience and often times force engineers into a corner thereby victimizing them for only wanting to focus on their job/purpose/task at hand. 

![image](https://user-images.githubusercontent.com/1425261/71864881-7a713c80-3144-11ea-8dbb-4332b63ef4e8.png)

**Comment by enjikaka** [comment]
A few others has kind of pointed this out already. But I think it's important to note that the santa hat origins are from the nordic [Nisse](https://en.wikipedia.org/wiki/Nisse_(folklore)). This was in Scandinavian folklore a small bearded gnome that helped around the farm. The Nisse with his iconic hat was later the inspiration of [Jenny Nyström](https://en.wikipedia.org/wiki/Jenny_Nystr%C3%B6m) when she illustrated [a poem about the Nisse](http://www.tomtenposter.com/Tomten.html) by [Viktor Rydberg](https://en.wikipedia.org/wiki/Viktor_Rydberg).

The Coca Cola santa illustrated (without a hat!) by Thomas Nast is the one with ties to Rome and jewish oppression. On the contrary, the scandinvian originiated santa hat has no ties there and was even a symbol [against nazi German opression in the 40s](https://no.wikipedia.org/wiki/Nisselue#/media/Fil:Norway's_WW2_Resistance_Museum,_Oslo_(Hjemmefrontmuseet)._The_Austerity_of_Occupation_-_red_woolen_caps_outlawed_1942-02-26_as_symbols_of_national_unity_(%22r%C3%B8de_toppluer%22,_from_exhibition)._Photo_2017-11-30.jpg).

Hope everyone had a happy Yule, and a happy new year. :)

**Comment by w0rldart** [comment]
Does that mean that I cannot dress as Santa either whilst I'm viciously coding the presents? My minions will hear about this.

**Comment by viktor-ku** [comment]
unbelievable
