### ISSUE TITLE
Saving huge files flashes the dirty circle indicator in open editors rapidly until it is saved to disk

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8744]
- VSCode Version: Code - Insiders 1.3.0-insider (0c5f6e8867fb117b6fa41cc647dc650bb9856dc4, 2016-07-04T09:39:57.773Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04

Steps to Reproduce:

1. Turn on open editors if not already
2. Open a huge file (mine was 18000 lines)
3. Dirty
4. Save, observe the circle indicator flashing rapidly, presumably until it is actually saved to disk. I saw this on an SSD, it will probably be a lot worse on a HDD. I also noticed that the save trimmed a bunch of whitespace, so that may be related.

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by Tyriar** [comment]
This issue was moved to editorconfig/editorconfig-vscode#58
