### ISSUE TITLE
"...even a single person being offended is one too many"

### ISSUE THREAD

**Issue by adamwday** [microsoft/vscode#87459]
I am offended that the Santa hat was removed and based on the quote from the team [https://github.com/microsoft/vscode/issues/87440](url), I have full confidence it will be returned since "even a single person being offended is one too many".

**Comment by cfanoulis** [comment]
Dude. It's back. You can configure it to be a santa hat, or whatever you want

**Comment by kieferrm** [comment]
Try the latest insiders.

**Comment by Isuru-Nanayakkara** [comment]
That line alone destroyed all the credibility of that response. By the same logic, what about all the people offended by the decision to remove the hat? This whole thing is one big social justice joke.

**Comment by SRGOM** [comment]
> Dude. It's back. You can configure it to be a santa hat, or whatever you want

What are my options ? Are there b**bs for the austere religious scholars among us?

**Comment by Tynach** [comment]
@kieferrm I think this bug report might qualify as off-topic, but it's not necessarily about the santa hat being there or not. It's about the mindset of even one person being offended is too many.

Quite frankly, I agree both with the idea that we should strive to make everyone happy, and with the idea that it is probably impossible to actually achieve that goal. In the real world, you almost never will find a way to satisfy absolutely everyone... But that doesn't mean we shouldn't try.

However, in this particular case... Just.. Read the original bug report that started this. Everyone knows that Santa hats are not related to religion... In fact, I've known many Christians who dislike Santa Claus because he represents, to them, the world 'secularizing' their religious holiday. And to top it all off, the last sentence is, "To me this is almost equally offensive as a swastika."

I don't know how it could be a more obvious example of trolling. I'm about 98% sure the person was never serious, and just wanted to see what would happen if he made a stupid bug report for a reason that was as absurd as possible.

I don't want to participate in what is sometimes called 'outrage culture', so I'm not going to drag myself down to the level of angrily ranting or making satirical jokes. On the surface, this whole situation might seem ridiculous and silly, or enraging and moronic... But it caused a real, tangible problem for many people, especially those of you who work on and develop this software. And that means it is a legitimate and serious problem.

Now, I don't blame you or any other developer for not wanting to take time out of your day to look into whether or not any of the claims about religion, or whether something is offensive, etc. in a bug report are legitimate. Simply changing the Santa hat is a pretty safe path to take, and in case there are others who feel the way the original reporter claims to have, it's best to be proactive.

But I think that's also where your guys' response could have been improved. Instead of simply taking them for their word from the start, perhaps inquire more, and wait to see if anyone else agrees with the bug's reporter. For example, a post saying little more than,

> I'm sorry for any offense this change may have caused. We were wanting to portray something festive for the holiday season, and were unaware of any religious significance attributed to Santa hats. Could you elaborate on that, and perhaps also give some ideas for what else it could be changed into?

Perhaps not that exact wording, but the idea would be to be polite, receptive, and open to changing things... But still erring on the side of caution and making sure it wouldn't be a pointless change that would just upset more people than it placates.

I believe a policy like this would help engage the community, letting other people who contribute to development (whether with code, or just bug reports) feel like they truly matter in the larger picture. It would also help weed out trollish bug reports like the one that started this, and make it possible to gauge the community's overall reaction to a potential change *before* making it.

The only downside I can think of, is that in the event of a legitimate concern it might delay the takedown of seriously offensive content. To that concern, I would propose that if the person handling the report considers the complaint to be *obviously* valid, then action should be taken immediately - as was the case in this incident.

However, if the complaint is *not* obviously valid, then the person handling the bug report should err on the side of caution and attempt to gather more information and details, until either many more people have come to a consensus, or until the reporter explains their position adequately enough that it *is* obvious.

Just my opinion, but I figured I'd share it since I saw this bug report didn't have its comments locked.

**Comment by Tynach** [comment]
I should also say, that I am a *huge* fan of giving as many options to users as possible. Ultimately, the end result (providing an option that allows users to configure it to have whichever icon they prefer) is ideal, and I 100% approve the outcome of this debacle.

My above post is solely about how/why the debacle happened in the first place, and one possible way it could have perhaps been avoided. I don't personally believe it should've been necessary to add the configuration option to begin with (even if I *do* consider it a good thing), and I have a feeling that having to spend time implementing it may have at least slightly soured someone's day.

As such, even though the outcome of this incident was a good thing, it's still worth considering ways to prevent further incidents from occurring. After all, it's good to still strive to make everyone happy - and 'everyone' includes both users *and* developers.

**Comment by kieferrm** [comment]
@Tynach thanks for sharing your thinking. We wanted to try to address the concerns you raised by providing more information on what happened last week. This turned out to address questions raised across other issues, so we put the response in https://github.com/microsoft/vscode/issues/87440#issue-540437717. Please take a look there. Thanks!
