### ISSUE TITLE
Possible violation of Microsoft Open Source Code of Conduct

### ISSUE THREAD

**Issue by therealparmesh** [microsoft/vscode#87476]
- VSCode Version: *
- OS Version: *

Steps to Reproduce:

1. Read https://github.com/microsoft/vscode/issues/87268, etc.
2. See results of disagreements

Does this issue occur when all extensions are disabled?: Yes

# Issue

Please review the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). Specifically:
> Understand disagreements: Disagreements, both social and technical, are useful learning opportunities. Seek to understand the other viewpoints and resolve differences constructively.

Based on what we saw happen with https://github.com/microsoft/vscode/issues/87268, I do not think there was an adequate effort put forth by the collaborators of this repository to "resolve differences constructively". Just because one person - whose intentions were not verified - makes demands based on a disagreement does not necessarily mean that collaborators should bend over backwards to accommodate them. This is a terrible and unsustainable precedent that will allow intolerance to triumph over tolerance.

To prevent this waste of time and energy in the future, I propose that we amend the COC to either:
1. improve clarity around what a best effort for understanding and resolving disagreements looks like - so as to promote a healthier, more tolerant environment where we do not assume the worst possible version of someone else's contribution
2. explicitly spell out a requirement that if even one person feels uncomfortable, no disagreement should be had at all and their demands should be satisfied if possible - so as to avoid any interactions that may lead to more discomfort

**Comment by GiorgioG** [comment]
From #87440 "...meaning it represented the opposite of what we wanted to convey to our users. In the spirit of the season, and to practice inclusiveness, we reverted the gear to something (hopefully) less controversial (a snowflake)..." 

I dunno, if I were the offended party that snowflake might represent what people think I am - https://en.wikipedia.org/wiki/Snowflake_(slang)

Seriously, this stinks.  Santa may have christian origins, but he considered to be more commercial than anything else in modern times.  Plenty of folks I know that have given up religion still celebrate Christmas, the holiday where 'Santa' brings gifts. 

You can't make everyone happy all the time, and by backtracking on this you folks just made it worse.

**Comment by dreamsComeTrue** [comment]
Yes, totally agree - if VSCode should be a community effort to make best IDE out there - then ONE person's opinion can not affect whole community - that one decision made by single repo commiter caused flamewar throughout whole Internet and divided developers more than ever :(

**Comment by globules-io** [comment]
Trolled hard
https://www.thurrott.com/users/DavidBenMesecke/

**Comment by simis2626** [comment]
Also would like to add that down in Australia, we're sweltering through 42°C (108°F) in the middle of our Summer, and so the snowflake makes very little sense to us! You could even argue it ins't very inclusive of southern hemisphere residents.

This whole debacle is ridiculous, inclusivity in this case could have meant people accepting that the Santa hat wasn't spruiking a particular religion, it was a single of good will and cheer and a way for us to feel like part of a community with the developers. The handling of this is going to make us all pump out entirely neutral, robotic grey software with no fun or joy. Good job World!

**Comment by omdran** [comment]
To ensure the integrity of this repository, issues arising from opinions or beliefs that are completely unfounded and untraceable should not be accepted. If we do so, we fall into a spiral of being offended. If there is no limit to this, then this trend will most likely spread to other repositories.

Briefly a bit off topic because the original issue was closed: in Isreal, especially Tel Aviv, Jews, Muslims and Christians live next door. It is an open and compassionate culture where even the different holidays are celebrated together, even partly Christmas! And objectively speaking, the name "Christian" is a Christian name, which is why one must now even assume that he must feel offended by his own name (https://en.wikipedia.org/wiki/Christian_(given_name)).
Honorable mention: https://github.com/Christian-Schiffer/servicelayer.chat/issues/45#issuecomment-568090200

What does all this have to do with this now? This is an example of an issue which obviously contains an opinion which is not justifiable, comprehensible and applies to a handful of users. That this was quickly "waved through" is simply the wrong way to handle it and we need to make sure that this doesn't happen again in the same way.

**Comment by Xaekai** [comment]
@GiorgioG 
> but he considered to be more commercial than anything else in modern times

May I suggest the word [secular (1b)](https://www.merriam-webster.com/dictionary/secular) over commercial?

**Comment by dylib** [comment]
For what it’s worth I reported the COC violation hours earlier, so we’ll and see what the response is or what happens (if anything).

It’s somewhat ironic that the person who was so offended by supposed Christian symbolism is named “Christian”; maybe he consider a name change above all.

Merry Christmas Github! 🎅

**Comment by adih2001** [comment]
I do agree with what has been said above. It's outrageous that just because one person feels offended by something it had to be removed.

I think the developers should add back the christmas hat icon and in the future add or remove content based on user feedback from multiple people not just because one person got triggered.

If they don't respect this then this definitely destroys what it means to work in a community together even if it's a minor thing. Some other time it could be about major content not just an icon.

**Comment by Panguins** [comment]
We were all under the impression vscode was community driven but alas, it is a clever ploy by microsoft to get us all to contribute and lock us out when they've gotten what they want. This is only the beginning, welcome to toxic corporate culture. 

Look no further than the Microsoft code of conduct.

**Comment by chrisdias** [comment]
@therealparmesh

We wanted to try to address the original issue raised here about the Code of Conduct by providing more information on what happened last week. This turned out to address questions raised across other issues, so we put the response in https://github.com/microsoft/vscode/issues/87440#issue-540437717.

Please take a look there, we hope this answers your question. If it does, please close this issue.

**Comment by apap04** [comment]
Just add the Santa hat back! 🙂

**Comment by lviggiano** [comment]
The Code of Conduct is offensive against Santa, please fix it.

**Comment by pankaj-webkul** [comment]
I am an irreligious Indian and don't particular care for holiday icons either way (specially santa, because cultural insgnificance) as long as it doesn't clutter my widow. My suggestion would be to make it configurable to hide holiday icons.

**Comment by chrisdias** [comment]
Closing this as I believe this issue is behind us we all certainly learned a lot from it.
