### ISSUE TITLE
I just tested and I'm able to type "hitler" in various places in the app.

### ISSUE THREAD

**Issue by nzalog** [microsoft/vscode#87504]
- VSCode Version: ALL
- OS Version: ALL

Steps to Reproduce:

1. Yeah just go anywhere to any area where you can type text and type Hitler. It literally lets you just do it.

I understand this is probably just overlooked and silly but I'm from Poland and had family die because of Hitler... So each time I can type it it really bothers me. Hope to hear back soon.

Does this issue occur when all extensions are disabled?: Yes

**Comment by lambainsaan** [comment]
Not funny.

**Comment by nzalog** [comment]
> Not funny.

I agree, seriously offensive.

**Comment by SRGOM** [comment]
Shit. I think the editing capabilities of this otherwise amazing software need to be curtailed

**Comment by nzalog** [comment]
> Shit. I think the editing capabilities of this otherwise amazing software need to be curtailed

Only logical conclusion, what's next? People using this software to write _fascist_ application? You'd think Microsoft of would be more socially responsible.

**Comment by nikandlv** [comment]
Just tested it out
same issue here.

**Comment by SRGOM** [comment]
Be

> > Shit. I think the editing capabilities of this otherwise amazing software need to be curtailed
> 
> Only logical conclusion, what's next? People using this software to write _fascist_ applications? You'd think Microsoft of would be more socially responsible.

I think maybe Microsoft can use their telemetry experience to somehow stop this behavior rather than trying to improve features. For once people will actually appreciate telemetry .

**Comment by dmarkhas** [comment]
I wonder, if a Microsoft committer picks up this "issue", blocks the ability to write "hitler" in VSCode, and then closes this issue and prevents all further discussion on the matter - would you be mad at the OP for "pressuring" Microsoft to block the word "hitler", or at Microsoft for taking such a cowardly, spineless approach?

The issue reported at https://github.com/microsoft/vscode/issues/87268 is a valid opinion, that you don't have to agree with and Microsoft did not have to "fix" so "urgently". Instead of being mad at Microsoft for making such an utterly foolish and rushed decision, you are mad for someone who simply voiced his own opinion and you don't even notice how convenient that is for Microsoft, who simply turned him into a scapegoat.

**Comment by nzalog** [comment]
> I wonder, if a Microsoft committer picks up this "issue", blocks the ability to write "hitler" in VSCode, and then closes this issue and prevents all further discussion on the matter - would you be mad at the OP for "pressuring" Microsoft to block the word "hitler", or at Microsoft for taking such a cowardly, spineless approach?
> 
> The issue reported at #87268 is a valid opinion, that you don't have to agree with and Microsoft did not have to "fix" so "urgently". Instead of being mad at Microsoft for making such an utterly foolish and rushed decision, you are mad for someone who simply voiced his own opinion and you don't even notice how convenient that is for Microsoft, who simply turned him into a scapegoat.

At that point we keep moving on to other offensive words. Until we are all finally safe from every possible thing anyone in the world finds offensive. This is the way.

**Comment by deitry** [comment]
Did you thought about French developers who use R language? Because fixing this issue will hit le R.

**Comment by nzalog** [comment]
> Did you thought about French developers who use R language? Because fixing this issue will hit le R.

Glad you pointed out how fascist the French are. If MS doesn't remove the French language as well as stop making vcode available in France, I think it will be very clear that MS supports and enables fascism. SMH
#BeBetter

**Comment by deitry** [comment]
@nzalog 
dude

**Comment by Rexogamer** [comment]
Guys. This is obviously a reference to the Santa hat issue... which has been resolved.
> **Looking forward…**

> If you’ve looked at our settings, you know that you get a lot of choice with VS Code. We decided to follow this pattern and let users configure how the gear looks. We’ve added a new setting to Insiders that lets you choose the icon. If you like the red hat, go for it! Maybe you live in the southern hemisphere or you are heading to the beach during the holidays, there’s an icon for you too.

> `Open settings (Mac: CMD+, Windows/Linux: CTRL+,) and search for “Holiday Gear Icon Style”, and choose your icon`
`If you love editing settings.json, set holiday.gearIconStyle`
You will still find the “Happy Holidays” command which will bring up the overlay, snow, and message.

> And finally, as we did in previous years, we will remove this little treat around the first week of January. In the meantime, download Insiders now and have a happy holiday season from all of us in Redmond and Zurich.

Now while I found this somewhat amusing and agree that the removal was a bit ridiculous, can we drop this before something bad happens?

**Comment by s9w** [comment]
But something bad DID already happen. MS got played by a troll, gave into his ridiculous demands and put a rule in writing that automatically accepts any possible demand. You guys have no idea what kind of gates you opened. So many software projects were captured by those people in recent years. And vscode just jumped headless into the abyss without any need.

**Comment by Rexogamer** [comment]
I meant anything *else* bad happening. I’m not sure if he’s a troll, but he’s definitely not a Jew. I agree that Microsoft’s response was poor.

**Comment by s9w** [comment]
This needs to be addressed and ridiculed. If this goes unchanged, this project is dead. Not yet, but it will be within a year.

**Comment by Rexogamer** [comment]
Fair.

**Comment by joaoportela** [comment]
Let's please stop opening issues related to this. 

I believe the situation has already gotten out of hand (see https://github.com/microsoft/vscode/issues/87440) 

Let's move on and focus on what matters.

**Comment by Wagnerp** [comment]
There's only one solution to solve 'santagate'. Microsoft allow users to choose from a selection of icons, such a feature can't be too hard to implement! Such ideas could include hanukkah candles, Christmas tree, star etc.

**Comment by joaoportela** [comment]
> There's only one solution to solve 'santagate'. Microsoft allow users to choose from a selection of icons, such a feature can't be too hard to implement! Such ideas could include hanukkah candles, Christmas tree, star etc.

That's what they did. Read the issue I linked to.

**Comment by Wagnerp** [comment]
@joaoportela 

I think that if they're not careful the issue thread on here could end up like what happened to Notepad++'s repo a few months back.

**Comment by fonix232** [comment]
> The issue reported at #87268 is a valid opinion, that you don't have to agree with and Microsoft did not have to "fix" so "urgently". Instead of being mad at Microsoft for making such an utterly foolish and rushed decision, you are mad for someone who simply voiced his own opinion and you don't even notice how convenient that is for Microsoft, who simply turned him into a scapegoat.

The problem with the issue was that it's nothing more than an opinion. It's not the official stance of the religion, it was literally a single dude reading some extremist religious BS (check out the link he posted and how it twists historical facts into pseudo-science to further victimise Jews.  His false equivalence of "santa hat = swastika" and "Christmas = Holocaust" already show that it's either a troll, or a religious nutjob, and in either case, Microsoft should've reviewed internally the case before acting so hastily. This is a PR disaster waiting to happen this way, as any one person could claim a symbol or phrase used in the app is against their religion and should be removed.

The moment we introduce religious arguments to an objectively religion-free tool used worldwide, we also introduce a wide-open backdoor for any religious nutjob to try and rape the project into submission to their ideals.

And before someone claims a santa hat is a religious element - no it isn't. In fact the official stance of the Vatican is that the Santa picture as we know it from the 15th-16th century has nothing to do with their St. Nicholas (apart from the legend of Father Christmas stemming from the fragments of historical records about this saint), and Santa itself is NOT a religious icon - rather, it's a folklore that happened to develop in Europe over time, and is an amalgamation of Father Christmas, St. Nicholas, and even old Nordic god Odin.

Now if it was an actual religious icon - say, a menorah, a cross, and so on - I'd agree with the decision. But the santa hat for centuries has transcended all of its religious meanings, and has become part of tradition regardless of religion. My family is NOT religious, I am an atheist, yet I celebrate Christmas. Why? Because it's a nice tradition that has little to do with religion (even here in Hungary where Santa comes on 6th December, and 24th evening it's "Little Jesus" that delivers the gifts with angels), and helps people connect with each other - which is extremely important for most software engineers, as we tend to be somewhat asocial.

**Comment by SRGOM** [comment]
I just want to warn Microsoft preemptively not to mention a happy "new year". Because the so called new year is actually Christian in origin and I don't have to mention how bad bad Christian's can be, some other dude has already detailed it. I will be fully prepared to be offended will get into action as soon as I see any mention of new year.

**Comment by Goubeling** [comment]
![1477667033-issou-noel](https://user-images.githubusercontent.com/50884525/71310144-cd42b880-2410-11ea-8cb2-d1b8dc054669.png)

**Comment by nzalog** [comment]
Let me get serious for _only_ a few paragraphs...

The only solution for this is to not be scared of negative PR, and not just giving into a social terrorist every demand. Learn to have a backbone, some common sense and understand that the alternative is to have your project turn into a platform for Twitter warriors to earn some internet points and popularity on.

Right now most people here are just pointing out that you can literally find anything offensive and that the more you give in to stupid requests that are non-Issues, the more it will attract people that will post these non-issues because again anything can be offensive in the right eyes. Being offended seems to be a shortcut for gaining internet popularity. I think the stuff you've seen so far is nothing compared to how bad things can get when people start posting shit like this and they're 100% serious about it. Each time you oblige, they'll push the boundaries of being offended further and further because they can see you're giving them control. You'll never please everyone, and if you try, it will just ruin you sooner or later. 

Now, as far as what has already happened (with the Santa hat/snowflake thing). I don't know what to do, that should not have been taken seriously to begin with. All you can do now is take your "internet beating" and learn from it. People being upset isn't going to kill you. Just remember, Twitter is not how normal people think, don't take your sense of reality from it.

**Comment by SRGOM** [comment]
Microsoft listen to this guy. A sensible voice finally. (also, please change your name according to my other issue)

**Comment by Xaekai** [comment]
To reduce this to the succinct: This is a demonstration of _reductio ad absurdum_; that if a project removes a santa hat at the bequest of the professionally-offended, it only snowballs from there.

Well done.

**Comment by nzalog** [comment]
> To reduce this to the succinct: This is a demonstration of _reductio ad absurdum_; that if a project removes a santa hat at the bequest of the professionally-offended, it only snowballs from there.
> 
> Well done.

Guess you've never heard of Twitter and the backwards shit companies do to satisfy offended nutjobs.

**Comment by Xaekai** [comment]
I believe you may have misunderstood me. My statement of "well done" was not sarcasm. Invoking Godwin's law on text inputs is in effect using _reductio ad absurdum_ to explain why you should never give even an inch to, as you call, "nutjobs"

A lot of the other issues about the same thing have a serious [verbosity](https://knowyourmeme.com/photos/1026537-reaction-images) problem.

**Comment by nzalog** [comment]
> I believe you may have misunderstood me. My statement of "well done" was not sarcasm. Invoking Godwin's law on text inputs is in effect using _reductio ad absurdum_ to explain why you should never give even an inch to, as you call, "nutjobs"
> 
> A lot of the other issues about the same thing have a serious [verbosity](https://knowyourmeme.com/photos/1026537-reaction-images) problem.

Thanks for clarifying.

**Comment by MaurogDark** [comment]
Honesty, the original #87268 is already as absurdum as they get and can't be reductio it any further

**Comment by basisbit** [comment]
This issue can be closed - reason "As designed". This project is about developing and improving great open source software. Please keep politics / your personal opinions out of the issue tracker.

Regarding the described issue: this is as designed because there is nothing wrong. At most, your description prooves that apparently the text input boxes work in all vsc versions and on all targeted OS. nzalog thank you for doing all the effort of testing so many versions on so many target platforms!

**Comment by nikandlv** [comment]
@basisbit the issue from the original Santa hat should have been closed and not fulfilled
either everyone's opinion should be satisfied or no ones

**Comment by basisbit** [comment]
@nikandlv this is not how software development projects work. Whoever owns the project repository and maintains it and whoever actually does the code work gets to decide stuff. Outside participants can nicely ask for something but thats it. This is not a democracy and you are not a shareholder of the project. The only thing you guys are doing is harming open source software development, possibly resulting in big companies favoring to develop closed source software again.

**Comment by nikandlv** [comment]
> and whoever actually does the code work gets to decide stuff

Thats the point. its discrimination. big companies always supported open source and they will keep it going.
whats the point when you start censoring and favoring some people over others because of being bullied

**Comment by basisbit** [comment]
Whats the point? Huh, you should read about basics of open source software development. If you don't like what is being done in this repository here, feel free to just fork the project and do there as you like. Read the license - you are actually allowed to take the code, modify it as you like and have fun because the project is MIT licensed.

**Comment by nzalog** [comment]
>   @nzalog thank you for doing all the effort of testing so many versions on so many target platforms!

I sense sarcasm, sorry was I not thorough enough? I must've missed the version where you guys broke writing text in text fields.

I really thought Microsoft cared and not just callously allowed hate speech on their programming platform. I'm very sad and disappointed that you guys will choose not to fix this. I'd hate to post about this on Twitter and give you the negative PR but seems like you're not giving me much of a choice. Supporting and allowing Nazi terminology isn't a good look.

#BeBetter
