### ISSUE TITLE
Auto-hide sidebar

### ISSUE THREAD

**Issue by lllopo** [Microsoft/vscode#8750]
- VSCode Version: 1.3.0-insider
- OS Version: Win 10

Currently, when you open a side panel and then click back in the editor area, the side panel remains open. 
It would be rather handy to add a button (pin or something) which changes this behavior for each panel, allowing to either keep the current way of working or making the side panel auto-collapse when you click outside.

**Comment by joaomoreno** [comment]
cc @bpasero @stevencl @bgashler1

**Comment by bgse** [comment]
For the git-panel, it could be useful to have something like "auto-hide if there is nothing to show", or even better yet "go back to last side-panel if there is nothing to show".

I'm often finding myself switching from explorer-panel to git-panel, after my commit I am being left with an empty git panel, and have to click the explorer panel again to get back into my workflow.

This would be a lot more comfortable if the git-panel would yield automatically to the explorer-panel.

I realize this is rather unconventional from the UX perspective, even more so since there isnt (at least for me) any other panel apart from git-panel where this would make sense.

Just throwing the idea out there, maybe an UX expert can make something out of it.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/3742

**Comment by lllopo** [comment]
Well, I'm refrencing more to the Visual Studio panels 'auto-hide' : you click on it  - it shows, you click outside - it goes ... simple as that. Hovering/timeouts etc. are not really necessary, but anyway - #3742 is similar, I must admit.
Btw., the GIT sidepannel must be totally hidden (no icon on the bar at all) when git is disabled in settings, I think.

**Comment by Venryx** [comment]
Went ahead and made an extension for this: https://marketplace.visualstudio.com/items?itemName=venryx.vscode-vtools

It's not perfect -- it only closes the side-bar when the user changes the selection (eg, clicking or dragging at a new location) -- but it achieves the basic function.

Built-in support is still ideal, but this should help until then.
