### ISSUE TITLE
unable install extensions

### ISSUE THREAD

**Issue by Kuloud** [microsoft/vscode#87503]
Issue Type: <b>Bug</b>

unable install extensions

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.59GB free)|
|Process Argv|-psn_0_8243164|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aabounegm** [comment]
I have the same issue. For almost all extensions (installed or not), I get a screen similar to the following, with no icon or description:
![image](https://user-images.githubusercontent.com/11016151/71314399-385faf80-2450-11ea-90ed-8eaf8f9d594d.png)
Doesn't matter if I press "install" on an extension I don't have, or "update" on one that is installed, I get a similar error. For example: `Failed to update 'ms-vsliveshare.vsliveshare'`. I cannot find any useful logs in the "Output" tab
Same VS Code version as OP.
Windows 10 Pro version 1909 (Build 18363.535)

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by Kuloud** [comment]
Sorry, I uninstall and then install vscode, is Ok now.

**Comment by aabounegm** [comment]
For me it was indeed a DNS problem. Thank you for your help
