### ISSUE TITLE
Could not find the task 'tsc: build - tsconfig.json' when configuring to display Chinese

### ISSUE THREAD

**Issue by kennethzhu** [microsoft/vscode#87525]
- VSCode Version:  1.41.1 system setup
- OS Version: Windows 7

Steps to Reproduce:
1. ctrl+shift+x， and install Chinese (Simplified) Language Pack for Visual Studio Code
2. ctrl+shift+p, configure display language  to choose zh_cn
3. try to run/debug helloworld.ts,  then the diagbox shown :Could not find the task 'tsc: build - tsconfig.json'.

When the display language changed to en, it works well.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alexr00** [comment]
This actually works for me:
![image](https://user-images.githubusercontent.com/38270282/71822642-a386c400-3095-11ea-977f-055cffad75d7.png)

I'm guessing you have a tasks.json that configures tsc: build - tsconfig.json. Since Typescript localizes the word "build" (as you can see in the screenshot), your tasks.json would also need to localize the task name.

**Comment by alexr00** [comment]
This actually works for me:
![image](https://user-images.githubusercontent.com/38270282/71822694-d3ce6280-3095-11ea-9c03-e91b8807c928.png)

I'm guessing you have a tasks.json that configures tsc: build - tsconfig.json. Since Typescript localizes the word "build" (as you can see in the screenshot), your tasks.json would also need to localize the task name.

**Comment by shengcanxu** [comment]
I encounter this  issue with chinese language pack installed. and  when i uninstall chinese language pack and rerun it again, everything works.
