### ISSUE TITLE
Dependency on node-gyp alienates contributors from most of the worlds regions

### ISSUE THREAD

**Issue by Entomy** [microsoft/vscode#87538]
While trying to contribute to this project and running into problems as described in another unrelated issue report, I had come across this section of of the wiki.

> Make sure your profile path only contains ASCII letters, e.g. John, otherwise it can lead to node-gyp usage problems (nodejs/node-gyp/issues#297)

ASCII is basically a subset of the Latin group of alphabets primarily oriented around English and not particularly well suited for representation of most Latin group languages. Furthermore, the Latin group comprises only one of eight total alphabet based language groups, with the others being Arabic, Aramaic, Armenian, Brahmi, Cyrillic, Georgian, and Greek. Furthermore, many groups of people do not use alphabet based languages, and instead rely on syllabaries, such as the Cherokee or Japanese, logosyllabaries, such as the Chinese, abugidas, such as many Canadian Aboriginals or Etheopian, and much more language writing systems.

I believe this dependency on outdated, anglocentric, and non-globalized software unfairly increases the barrier to contribution from most of the world's people. Creating a new user account solely to develop for one product, requiring switching between user accounts just to do so, leaving behind all user settings and user specific software, imposes a burden on people because of their primary language; something very obviously tied to race and nationality. Surely this project should be equally as easy to contribute to for everyone?

**Comment by Entomy** [comment]
This isn't an attempt to troll given the recent controversy. I've seen first hand how these kinds of inconveniences can discourage non-English-primary-speakers such as in [this instance](https://github.com/AdaCore/gps/issues/5).

**Comment by Xaekai** [comment]
Technically, this problem lies in gyp directly, not node-gyp.
https://github.com/nodejs/node-gyp/issues/297#issuecomment-39591925

Someone made a patch and was told it should be sent to gyp directly and never bothered
https://github.com/nodejs/node-gyp/pull/945#issuecomment-222313951

Looks like the issue has been around for quite a while
https://bugs.chromium.org/p/gyp/issues/list?q=ascii%20latin&can=2

And it also looks like you can make your PRs directly on Github and googlebot facilitates them.
https://github.com/chromium/gyp/pulls

So this is something that could be fixed by any interested party without having to reinvent the project build system wheel yet again .

**Comment by Entomy** [comment]
@Xaekai oh okay, thank you for the direction. I have some experience with implementing full Unicode support in libraries (a language runtime, in fact), so I can look into this.

**Comment by egamma** [comment]
Closing as an upstream issue.
