### ISSUE TITLE
Terminology - Zen Mode

### ISSUE THREAD

**Issue by Jojoshua** [microsoft/vscode#87557]
The goal of this Github issue is to have a conversation about the term **"Zen"** used in "Zen Mode".

As software professionals we love expressing our creativity and we love connecting to our users even at a personal level. I find it fun to introduce cool terms and icons into my software but this term could possibly be misconstrued. 

Could we as a community decide on if this is the best term? Here are a few suggestions to get discussion going.

- Focused Mode
- Distraction Free Mode (taken from the explanation https://code.visualstudio.com/docs/getstarted/tips-and-tricks)

**Comment by brlebtag** [comment]
Yeah I feel offended too by "Zen Mode". I hope they fix it as fast they fixed https://github.com/microsoft/vscode/issues/87268. Please remove it immediately and make it your top priority. To me this is almost equally offensive as a swastika.

**Comment by David-Else** [comment]
MS need to go back on their 'one person being offended' statement and change to a more reasonable and balanced approach. If that doesn't happen then VS Code is done for.

All this is a disaster for MS, but they brought it on themselves by politicizing their software. Society is split on these bigger issues, MS can't have their cake and eat it.

**Comment by brlebtag** [comment]
![3k891b](https://user-images.githubusercontent.com/7052344/71325652-82877600-24ce-11ea-86f5-aeca053d7c2f.jpg)

**Comment by CuBeRJAN3** [comment]
Lmao guys you such soi-boi F A G S.
>Oh no, someone offended me, better call my SJW twitter gang.
BTFO R e t a r d s.

**Comment by alexandernst** [comment]
I'm very concerned about all this.

**Comment by CuBeRJAN3** [comment]
@alexandernst There's nothing to be concerned about, they're just trolling and imitating the recent santa hat situation

**Comment by chrisdias** [comment]
The terminology for "Zen Mode" is a good issue, and we're open to change this based on feedback to improve the product.  The challenge we have with this issue is that it combines two topics, settings icon debate and zen mode, which makes it hard to have a single conversation about "Zen Mode".  

I would like to suggest that you please update the issue to focus on Zen mode with concrete proposals.

**Comment by Jojoshua** [comment]
You're right @chrisdias . There was too much in the original issue and I've updated it.

**Comment by egamma** [comment]
Assigning to @isidorn he has investigated into the 'zen mode' terminology in the past.

**Comment by isidorn** [comment]
@Jojoshua  Thanks a lot for your feedback. We have considered different naming in the past like Focused Mode and Distraction Free Mode. However we have settled on Zen Mode since the Ctrl K, Ctrl Z keybinding was free and Z for Zen was very distuingishable. In the mean time this name has caught on and the users have tied the keybinding to their muscle memory.
Thus I would not change this name at the moment. However leaving this open as we might reconsider in the future.

Thanks a lot
