### ISSUE TITLE
vscode is bossy and I find it offensive

### ISSUE THREAD

**Issue by samomar** [microsoft/vscode#87675]
Greetings,

The interface is written in a rude and bossy language, for example:

Please check the help menu:
**Help** > _Check for updates..._

It doesn't say please, and the `...` at the end is very passive aggressive.

Sometimes a pop-up tells you to straight up "Update", no "excuse me", no... "Please update vscode"

We should let the Canadians be in charge of the UI.

Please update vscode to be more polite and less offensive.

Thank you.

**Comment by samomar** [comment]
Yes please, install-update.

**Comment by sanket-bhalerao** [comment]
let me start with "I could be wrong with this" and then proceed.
I checked a few of the software on my system and none of them has "Please" in them for any of the commands. 
Moreover, I find that it's not the software that's asking you to "check for updates..." its more on the grounds of "VSCode, check for updates...". 
I feel this bug is more from VSCode's point of view as in "_Humans as bossy bums_" 🤣  .

**Comment by virgiliu** [comment]
Since they clearly stated that "even a single person being offended is one too many", not having basic courtesy in the pop-ups and dialogs is highly offensive. We're civilized people, not cavemen banging bits together!

**Comment by bradisbell** [comment]
Menu items are commands, not asks.  Saying "please" when you're really issuing a command that must be followed is one of the most insincere and impolite things you could possibly do.

Additionally, the ellipsis `...` is a standard UI indication that a dialog box will be launched, rather than a command that will be immediately followed before confirmation.  This standard has been around at least for decades, and is not intended to be passive aggressive.

If you find yourself offended by your own reading-in of an unintended tone of voice in a trivial menu item, I'd politely suggest contributing a UI translation that you find less offensive.  You can find information here:  https://github.com/Microsoft/Localization/wiki/Visual-Studio-Code-Community-Localization-Project

**Comment by Tyriar** [comment]
Yes this is a pretty standard UI paradigm.
