### ISSUE TITLE
Debugging with multiple arrays in a row

### ISSUE THREAD

**Issue by hardik-singhal** [microsoft/vscode#87705]
During debugging the code in vscode whenever we have multiple arrays with different indexes and we want to work on the last array in the code we can not see its value by debugging as the debugger only allows us to first array with index it finds in the code. It would be more easier to work with debugging in vscode if this feature will be released.
please find attachment 
Thanks!
![vscode1](https://user-images.githubusercontent.com/22071153/71460504-270cff00-27d2-11ea-80bc-5c39dbacb3b6.png)

**Comment by isidorn** [comment]
If I understand correctly you are trying to evaluate an array inside an array. That should be supported, however the debugger extension that you are using seems to hit some issue.
Due to that I suggest that you create an issue in the github repository of the extension which you are using (looking at the snippet you attached I am not sure which language is that)
