### ISSUE TITLE
Can not install Extensions (Even after add DNS) 😓

### ISSUE THREAD

**Issue by Muhammad-Moftah** [microsoft/vscode#87747]
- VSCode Version: 1.41.1 (user setup)
- OS Version: Windows 10 pro 64bit

I can't install any extension, VScode forcing me to install it manually  
I tried to change DNS like (GoogleDNS - OpenDNS - 1.1.1.1 DNS - etc...)
and still cannot install extensions directly

![rwefs](https://user-images.githubusercontent.com/37259640/71496238-edcca180-285a-11ea-8f04-a5fbacc3154d.PNG)

Kindly help me
Thanks 🌹

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by Muhammad-Moftah** [comment]
> Please follow these steps
> 
> * Help -> Toggle Developer Tools -> Network
> * Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
> * To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
> * If it is not a network issue, please share the logs from the following locations
>   
>   * Help -> Toggle Developer Tools -> Console
>   * View -> Command Pallette... -> Toggle Shared Process -> Console
>   * View -> Open View… -> Log (Shared)
>   * View -> Open View… -> Log (Window)

Yes it's network issues
and I changed my DNS and still print these errors 
What should I do, please
![Capture](https://user-images.githubusercontent.com/37259640/71594122-4d6acb80-2b3f-11ea-8b1c-f249ae801979.PNG)

**Comment by sandy081** [comment]
I am not sure how I can help you with your network issues... please contact your network administrator.
