### ISSUE TITLE
New windows terminal (https://github.com/microsoft/terminal) does not start integrated

### ISSUE THREAD

**Issue by kuskmen** [microsoft/vscode#87792]
Hi, I am not sure if this is the right place to report, but surely is the right place to start.
I am trying to use the new windows terminal (https://github.com/microsoft/terminal) with VSCode as integrated terminal, unfortunately, when I try to run it it starts as separate window rather than integrated.

This is my user settings file:
```
{
    "editor.tabSize": 4,
    "editor.insertSpaces": true,
    "editor.detectIndentation": true,
    
    "terminal.integrated.shell.windows": "C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_0.7.3451.0_x64__8wekyb3d8bbwe\\WindowsTerminal.exe",
}
```

as you can probably tell I installed it via windows store apps (not sure if relevant).

**VSCode Version:**
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Install new windows terminal via windows store apps 
2. Launch vscode and amend terminal.integrated.shell.windows option to the place your windows terminal is installed.
3. Hit ctrl + ` after you selected this to be your default terminal.

Does this issue occur when all extensions are disabled?: Yes

**Comment by IllusionMH** [comment]
Do you have examples on any app that can launch Windows Terminal "integrated"?
I doubt that WT can be run as shell, because it's primary role  - terminal - UI over different shells (CMD, PowerShell etc.).
And that's what VSCode's integrated terminal does - it allows to launch any shell inside.

Not sure what do you expect from launching WT "integrated" in VS Code. Is it tabs, easy to create tab with different shell, your option?

Also see https://github.com/microsoft/vscode/issues/79211#issuecomment-540709609

**Comment by kuskmen** [comment]
Hi @IllusionMH, thanks for clarifying. You're right, it appears that I misunderstood WT, I thought it is a superset of functionalities from cmd and powershell.
