### ISSUE TITLE
[Feature request] Import React in .jsx and .tsx files

### ISSUE THREAD

**Issue by streamich** [microsoft/vscode#87825]
When user creates a new `.jsx` or `.tsx` file, populate the file with this import automatically.

```tsx
import * as React from 'react';
```

**Comment by wizzard0** [comment]
I vote for a quick-fix instead of an automatic template (can a quick fix be conditionally assigned to an empty line in file?), and also respect [configurable JSX factories](https://mariusschulz.com/blog/per-file-jsx-factories-in-typescript) from tsconfig.json or from files in the same/enclosing folder
