### ISSUE TITLE
go to reference doesn't change the window focus in multiple windows scenario

### ISSUE THREAD

**Issue by ctf0** [microsoft/vscode#87846]
### Env
```
Version: 1.42.0-insider
Commit: 7c0095ee2d064033fc13184127a9adc603454729
Date: 2019-12-20T07:55:38.353Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

### Steps to Reproduce:

1. open 2 windows with 2 editors
2. focus the second editor
3. press `alt/meta + click` on the first editor to `go to reference`
4. use `alt/meta + w` to close the editor
5. the second window editor will be closed

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
@ctf0 having trouble understanding how you can do anything on the first window while the second window has focus? If focus is always in the second window, then doing any keybinding will operate on that focused window.

**Comment by ctf0** [comment]
here is a gif to better illustrate 
![Untitled](https://user-images.githubusercontent.com/7388088/71772211-f5bdcd00-2f4f-11ea-8042-c3ca6ae3114e.gif)

**Comment by bpasero** [comment]
@ctf0 how are you able to "go to reference" in that first window while the second window has focus?

And unrelated: VSCode looks customized (telling by the looks of tabs), what extensions are you running with?

**Comment by ctf0** [comment]
> how are you able to "go to reference" in that first window while the second window has focus?

am not sure but i believe this is similar to scrolling the window without actually focusing it like in chrome browser.

> what extensions are you running with?

its a personal mod https://gist.github.com/ctf0/ddefea0628fbde32efafa3e3b7ca6470 using https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css

**Comment by bpasero** [comment]
Without this information I cannot help you sorry. I cannot make the first window accept any keyboard input without focusing it, so I cannot reproduce this. 

If this is a special OS or tool that enables this I would assume a lot of things would not work properly because not every command that changes something in VSCode will turn the window to receive focus.

**Comment by ctf0** [comment]
i honestly dont know what other information i could provide to help, if there's something i could provide plz tell me

**Comment by bpasero** [comment]
@ctf0 sorry, I understand now. Somehow I thought you would not use the mouse at all. Makes more sense to me now.

**Comment by bpasero** [comment]
I tested this a bit and it seems to be standard behaviour on macOS independent from that setting. When I Alt+click e.g. in a browser to a non-active window, I can execute that action without having the window focused. I would not want to change this, nor do I know how to since it impacts pretty much every clickable thing in a window.

**Comment by ctf0** [comment]
i thought we can override the native OS functionality like
- using home/end buttons to go to start/end of line/text, which mac doesn't support natively
- styling numerous parts of the editor, which mac doesn't support natively 
- etc...
