### ISSUE TITLE
show type for all suggestions

### ISSUE THREAD

**Issue by temoto** [microsoft/vscode#87882]
Current behavior: vscode intellisense only shows type for currently selected item.

![now suggest only shows type for currently selected item](https://i.stack.imgur.com/ccL77.png)

Goal: see helpful types for all suggestions, like in Atom and vim at least. Types play crucial role in my everyday work.

![expected show type for all items](https://i.stack.imgur.com/E3OKx.png)

Solution: https://github.com/temoto/vscode/commit/2f0a502e756ab22eecd848b9ae204e9ccd9f41c4

I absolutely understand this behavior is by design with best intentions of human attention or machine performance in mind. Thanks to culprit being in CSS, I am quite happy to modify a file in vscode installation and ignore integrity check (having troubles with build). Please help me construct acceptable patch making this into configuration switch, because I'm pretty sure there are more users who want to see more helpful information in suggestions.

**Comment by IllusionMH** [comment]
I think that removing styles won't be enough because it really depends on implementation.
For example TSServer doesn't provide this text on call for list of entries, but instead on separate call for single entry details (only for current entry because returning this for all entries will be performance hit).

Other languages might provide or not provide this data with singe call.

**Comment by temoto** [comment]
Duplicate of which one?
