### ISSUE TITLE
VS code fails to download updates for extensions

### ISSUE THREAD

**Issue by Andrew-Bekhiet** [microsoft/vscode#87881]
Whenever I click update on any extension it says: failed to update {extension name}.
At first when I first installed vs code installing extensions was going all right, now it doesn't even show info about them.
![image](https://user-images.githubusercontent.com/40571928/71585856-b55de980-2b20-11ea-950f-83eed62b51c0.png)

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by Andrew-Bekhiet** [comment]
Thank you so much
I did the steps and it was a dns problem
