### ISSUE TITLE
An event that fires prior to a text document opening

### ISSUE THREAD

**Issue by parithon** [microsoft/vscode#87897]
I have a use case where I need to _do a thing_ before the text editor is opened and the document is displayed. Unfortunately it appears the only event available is the `onDidOpenTextDocument` which allows the document to display prior to _doing my thing_.

Would it be possible to get an event that fires prior to the document opening?

**Comment by jrieken** [comment]
What is it that you want to do *before* opening/showing a document? We aren't very keen on adding such a thing because it allows to delay/prevent showing a document because I assume you need this to be blocking, e.g. it must finish before showing the document

**Comment by parithon** [comment]
For my scenario I need a way to change scenes while streaming live if I accidentally open a _secrets_ file. Unfortunately right now all I can do is send a "scene" change request _after_ the TextDocument is opened and hope that the change occurs prior to the file being shown.

**Comment by jrieken** [comment]
> For the blocking of the document opening, perhaps a notice could be given if a timeout occurs which names the extension blocking the document from opening with actions to disable the plugin.

It unfortunately not that simple. Just that fact that an extension is listening/intercepting the opening of a document, means that we need to roundtrip to the extension host. And that enables *any* extension to delay opening, e.g one that's totally unrelated to this request but blocking the extension host atm. While that's undesirable too, it's often unnoticed because we don't wait for the extension host before opening files (and other "vital" things)
