### ISSUE TITLE
task dependsOn with dependants that have input only executes one dependant

### ISSUE THREAD

**Issue by vim-daniel** [microsoft/vscode#87927]
- VSCode Version: 1.41.1
- OS Version: macOs Mojave 10.14.6 (18G87)

Steps to Reproduce:

1. create 2 tasks that use input, like
```javascript
 {
  "tasks":  [
  {
      "label": "a",
      "type": "shell",
      "command": "echo ${input:pickEnv}"
    },
    {
      "label": "b",
      "type": "shell",
      "command": "echo ${input:pickEnv}"
    }],
"inputs": [
    {
      "id": "pickEnv",
      "description": "Select Environment",
      "type": "pickString",
      "options": ["env1", "env2"],
      "default": "dev"
    }
 ]
}
```
2. add a task that depends on them
```javascript
{
      "label": "both-env",
      "type": "shell",
      "dependsOn": ["a", "b"],
    },
```
3. run 'both-env' task and select from the input, and only one task is getting executed

Expected outcome:
both task (a, b) should be run with the selected choice of the input modal

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexr00** [comment]
Parallel task execution (which is the default when you do `dependsOn`) is fundamentally incompatible with inputs. Since both of your tasks are started in parallel, there is a race for the task to get its input. Because of this, _both_ tasks end up showing showing a quick pick, and one ends up cancelling the other.
To work around this, add `"dependsOrder": "sequence"`
