### ISSUE TITLE
Sidebar icons are offensive to me in many ways.

### ISSUE THREAD

**Issue by lukelex** [microsoft/vscode#87982]
# WTF am I talking about?
* **Number 13** is often used to refer to the Texas Aryan Circle prison gang. Please make it impossible to write this number in the editor. Refer to: https://www.adl.org/hate-symbols for more information.
* **Magnifier icon** alludes to the Windows magnifier app used as a cheat mechanism in Counter Strike to improve your in game Field Of View. As Microsoft's values include `Corporate Social Responsibility` we should not support irresponsible gaming.
* **Source Control Symbol icon** is a mockery of all the slaves that got whipped by Scourges. Refer to https://en.wikipedia.org/wiki/Scourge for more info (and more offensive images).
* **Bug icon** incites violence against animals by having the `X` marked on its back, often used as for target practicing.
* **Building blocks icon** alludes to all the Pyramids that were built using slave work. As a person with African Lineage, I find this offensive.
* **Cogwheel icon** I often used as the symbol of Capitalism and we all know it's EVIL. Refer to Erich Fromm: Man is a cog in the vast economic machine.

# Info
- VSCode Version: 1.41.1-1
- OS Version: Manjaro 18.1.5

Steps to Reproduce:

1. Install latest arch build.

Does this issue occur when all extensions are disabled?: Yes

![triggered](https://user-images.githubusercontent.com/842850/71662747-da39a300-2d52-11ea-8520-23d8bbc0b82f.png)

**Comment by sdaitzman** [comment]
Hi Lukas,

I can understand the urge to post something like this. It's really scary and frustrating to feel like the world is changing in ways we didn't expect.

I thought you might be interested to know the origin of the meme you're referencing. The "triggered"/"offended" meme is a response to trigger warnings in university courses, but a lot of people don't know the origin of those.

A number of conditions (most often post-traumatic or acute stress disorder) can make it so that reminders of a past trauma activate a severe neurological fight-or-flight state. Not discomfort, but a 100% convincing, brain-level *understanding* that the traumatic past experience is happening, again, right this instant.

Some university professors realized that (1) an extremely high percentage of people have experienced trauma (in a lecture of 300, it'll be ~30 on average), often connected closely to domestic violence, suicide, or sexual abuse or related issues and (2) studying such content can still be valuable. So, they decided to give everyone a heads-up when covering content that could trigger a flashback (which, again, is a neurological state in which a person's brain trauma causes their neurons and synapses to *believe*, at a physical level, that the traumatic event is happening again).

Then, some people on a web forum found out about this and thought it would be funny to try to cause some of those flashbacks, and were upset about the idea that people could be warned before viewing content like this.

All humor does some work in the society we live in. It defines what is normal and what is not. The idea you're producing satire about is not actually that people are banning things because it's offensive to them, because that doesn't usually happen.

Intentionally or not, you're mocking people with real trauma.

With love,
Sam

**Comment by lukelex** [comment]
> I thought you might be interested to know the origin of the meme you're referencing. The "triggered"/"offended" meme is a response to trigger warnings in university courses, but a lot of people don't know the origin of those.
>
> A number of conditions (most often post-traumatic or acute stress disorder) can make it so that reminders of a past trauma activate a severe neurological fight-or-flight state. Not discomfort, but a 100% convincing, brain-level understanding that the traumatic past experience is happening, again, right this instant.
>
> Some university professors realized that (1) an extremely high percentage of people have experienced trauma (in a lecture of 300, it'll be ~30 on average), often connected closely to domestic violence, suicide, or sexual abuse or related issues and (2) studying such content can still be valuable. So, they decided to give everyone a heads-up when covering content that could trigger a flashback (which, again, is a neurological state in which a person's brain trauma causes their neurons and synapses to believe, at a physical level, that the traumatic event is happening again).

Thank you for history lesson.

Now for the maintainers, I'd like my concerns to be addressed.

With love,
Myself
