### ISSUE TITLE
Go To Anything (command-P) can't find obvious files - what am I doing wrong?

### ISSUE THREAD

**Issue by jeanrajotte** [microsoft/vscode#88048]
Is it just me?

I've several folders in the workspace:
./X-API/...
./X-Biz/...
./X-Lib/...

There's a file: `X-Biz/Module/Vendors/Bob/Api.php`

Can't GO TO it via cmd-P, no matter what I type. This happens a lot. What am I doing wrong?

Why isn't the full file path just rendered in the dropdown and filters on the space-separated text I type? It seems to me the dropdown is trying to be too smart for its own good, with the rendering the file path in some funky order, like filename + the main folder + the other folders all separated.

e.g. typing "biz vend api" ought to find the above (as well as, say, `X-Biz/Module/Vendors/Mary/Api.php`).  But no, "biz vend api" returns an empty list.  

e.g. Sublime's Go Anywhere, Atom's Go Anywhere - they all find my file.  The MacOs Finder's search finds my file.  VsCode doesn't.

**Comment by roblourens** [comment]
If the file doesn't show up at all, check https://github.com/microsoft/vscode/wiki/Search-Issues#missing-search-results

If it just doesn't show up with that search that's trying to match the root folder name ("biz"), that's because the root folder names in a workspace aren't included when searching: https://github.com/microsoft/vscode/issues/32444

**Comment by jeanrajotte** [comment]
Thanks for spelunking  @roblourens . It's not perfect, but good enough to close this issue, in that I understand better.
