### ISSUE TITLE
Can't forward candidate ports

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#88060]
![image](https://user-images.githubusercontent.com/323878/71745130-24d42180-2e1e-11ea-910c-f938186e664e.png)

- Click the `+`
- Nothing happens
- I don't see any obvious error messages. The extension has not implemented `forwardPort` so the core should be forwarding it

**Comment by alexr00** [comment]
@roblourens I tested with Containers and candidates are still forwarding correctly there. How can I reproduce this with SSH?

**Comment by roblourens** [comment]
It's now in the SSH nightly build

**Comment by alexr00** [comment]
Looks like a few things are going on here:
🐛 The host for the detected port is 0.0.0.0. This should be shown in the UI because it isn't localhost and it isn't. 
🐛 Apparently `npx http-server -p 8080` exposes the server on 127.0.0.1 and 10.0.0.4, which the candidate detection isn't actually seeing.
- The core can only forward when the host is localhost, (in this case it is, which is covered by the second bug), so since the host is showing up as not local host this is expected.
