### ISSUE TITLE
Source control is not working with the latest VS Code November 2019 Update

### ISSUE THREAD

**Issue by rajesh996** [microsoft/vscode#88079]
After updating the VS Code to the latest version, Source Control is not working and not showing files tree. It is empty.

**Comment by twlatl** [comment]
I am having the same issue. MacOS Catalina (10.15.3). VS Code version:

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

Running the Insiders build, Source Control works. Hoping whatever the fix is will land in stable soon.

**Comment by twlatl** [comment]
Also, FWIW, I was able to get this working again by deleting the Code folder in ~/Library/Application Support, and the preferences file in ~/Library/Preferences
