### ISSUE TITLE
Hover does not adress Language Servers Correct

### ISSUE THREAD

**Issue by cdietrich** [Microsoft/vscode#8808]
- VSCode Version: 1.3.0 Insider 2016-07-01T05:29:54.785Z
- OS Version: Mac 10.11

Steps to Reproduce:
1. take the language server node example and adapt it as follows

```
capabilities: {
            // Tell the client that the server works in FULL text document sync mode
            textDocumentSync: documents.syncKind,
            // Tell the client that the server support code complete
            completionProvider: {
                resolveProvider: true
            },
            hoverProvider : true
        }
```

```
connection.onHover(
    (p : TextDocumentPositionParams) : Hover => {
        console.log(p.position.character);

        return {
            contents: "xxxxx" + p.position.character,
            range : {
                start : {line: 0, character: 0},
                end : {line: 0, character: 10}
            }
        }

    }   )
;
```
1.  using the hover and hovering in the middle of the first character gives offset 1 instead of 0

**Comment by cdietrich** [comment]
<img width="356" alt="screenshot" src="https://cloud.githubusercontent.com/assets/238736/16619659/559669a4-438f-11e6-86b6-4524259938df.png">

**Comment by cdietrich** [comment]
see https://github.com/Microsoft/language-server-protocol/issues/26 as well

**Comment by jrieken** [comment]
> using the hover and hovering in the middle of the first character gives offset 1 instead of 0

I believe that's because we 'round' up/down depending on how you hover over the character

**Comment by cdietrich** [comment]
well when implementing languageservers this behaviour is a bit bogus. at least if you hover on the last character of a Symbol

**Comment by cdietrich** [comment]
i had a quick look at the code. the mouse range is truncated from a 1 length to a zero length if you go over the half of the letter. maybe this error can be corrected inside IHoverComputer (if startColumn == endColumn), startColumn = startColumn -1

**Comment by alexandrudima** [comment]
Maybe `provideHover` is misleading by accepting a `position` and it should accept a `range`. In fact, even the name of the member `Position.character` is misleading.

In VS Code, positions always fall between (or before/after) characters. 
Some examples:

`{ lineNumber:7, column: 1} ---> { line: 6, character: 0 }`
![image](https://cloud.githubusercontent.com/assets/5047891/16765204/65d1648a-483b-11e6-9d3c-fd176d6359d1.png)

`{ lineNumber:7, column: 2} ---> { line: 6, character: 1 }`
![image](https://cloud.githubusercontent.com/assets/5047891/16765570/80139e92-483d-11e6-9353-576faefc96b2.png)

`{ startLineNumber:7, startColumn:1, endLineNumber:7, endColumn: 2} ---> { start: { line: 6, character: 0 }, end: { line: 6, character: 1} }`
![image](https://cloud.githubusercontent.com/assets/5047891/16765592/9c7773d8-483d-11e6-8674-68035b2dd8c6.png)

IMHO when talking about the character `i` we should use a range, but given we don't want to break the API I guess we could by convention always use the position before the character when hovering over a character, but we'd need to make the change only for the place where we call the hover providers in order to not mess up the other users of mouse move events that don't have this problem and work OK.
