### ISSUE TITLE
Linux: keyboard shortcut refactoring

### ISSUE THREAD

**Issue by anton-marchenko** [microsoft/vscode#88083]
VSCode has next keyboard shortcuts for copying lines in Windows:

`
Shift+Alt+DownArrow,
Shift+Alt+UpArrow
`

![001](https://user-images.githubusercontent.com/45929621/71765536-38a78280-2f07-11ea-8183-6c5fa3b0fea2.png)

VSCode has next keyboard shortcuts for copying lines in Linux :

`
Ctrl+Shift+Alt+DownArrow,
Ctrl+Shift+Alt+UpArrow
`

![002](https://user-images.githubusercontent.com/45929621/71765588-d4d18980-2f07-11ea-92d7-b35716fe39d7.png)

But often this keyboard shortcuts (Ctrl+Shift+Alt+DownArrow, Ctrl+Shift+Alt+UpArrow)  [has a conflict with Linux OS](https://github.com/microsoft/vscode/issues/88081) and do not work.

By the same token VSCode has duplicated keyboard shortcuts for some operations. For example, for adding cursor below / above:

![003](https://user-images.githubusercontent.com/45929621/71765648-78bb3500-2f08-11ea-9295-fd68a0ca3537.png)

I propose make refactoring for Linux default keyboard shortcuts:

1. Remove default keyboard shortcut "Add cursor Above" with keybinding Shift+Alt+UpArrow and leave just keybinding Ctrl+Shift+UpArrow,
2. Remove default keyboard shortcut "Add cursor Below" with keybinding Shift+Alt+DownArrow and leave just keybinding Ctrl+Shift+DownArrow,
3. For command "Copy Line Up" replace keybinding Ctrl+Shift+Alt+UpArrow to keybinding Shift+Alt+UpArrow,
3. For command "Copy Line Down" replace keybinding Ctrl+Shift+Alt+DownArrow to keybinding Shift+Alt+UpArrow.

Then:

1. we will have more compatibility with Windows keyboard shortcuts,
2. we will exclude current conflict Ctrl+Shift+Alt+Up(Down) Arrow with Linux OS.

What do you think about it?

**Comment by alexdima** [comment]
I am not selfhosting on Linux, so I am not the best to drive this because I don't really know what the OS eats up nowadays. Also, since I am often running Linux in a VM, some keybindings are eaten up by the VM host...

@aeschli @joaomoreno @Tyriar What distros are you selfhosting on? Are any of the arrow keybindings reserved for OS operations nowadays?

**Comment by joaomoreno** [comment]
Out of the box, both `Ctrl Shift`  and `Alt Shift` add multiple cursors. So I always have this in my settings:

```json
  {
    "key": "shift+alt+up",
    "command": "editor.action.copyLinesUpAction",
    "when": "editorTextFocus"
  },
  {
    "key": "shift+alt+down",
    "command": "editor.action.copyLinesDownAction",
    "when": "editorTextFocus"
  },
```

I didn't know about `Ctrl Shift Alt`, just seems like such a contrived key combination,  definitely getting muscle cramps from it.

I am on i3, which isn't really widely used. For confirming conflicting keybindings we should look at KDE and Gnome.

**Comment by Tyriar** [comment]
I moved over to remote wsl instead of a full Linux desktop quite a while ago.

I know ctrl+shift+alt is bad in general but that may not apply to all desktop manager, I would exercise a lot of caution if you change long standing shortcuts like this as you will undoubtedly break _some_ people by changing things.

**Comment by alexdima** [comment]
@anton-marchenko Frankly, I have concerns to tweak the defaults at this point, given that many of our users might have gotten used to them. This is also something almost impossible to test, because linux is so rich of desktop managers, even if we change the defaults, there will be combinations which we don't take into account, where default keybindings might change and now clonflict with something.

Given how easy it is for users to change things on their side, and how easy it is to create and publish an extension that improves things for a certain distro, I would not do anything here...
