### ISSUE TITLE
[Screencast Mode] Allow users to customize font sizes for displaying keyboard shortcuts

### ISSUE THREAD

**Issue by tommai78101** [microsoft/vscode#88097]
Currently, these are the settings for Screencast Mode:

![image](https://user-images.githubusercontent.com/6444116/71773508-08260f80-2f2c-11ea-9eb4-23b8db26319c.png)

I would like for the ability to allow users to choose how large or small the keyboard shortcuts are displayed on the screen when Screencast Mode is enabled.

Personally, I felt the font sizes of the keyboard shortcuts to be a bit too large in Screencast Mode, so I wanted to change it up. If an option allows me to set the font sizes exists, then may I request that option to be added to the Settings menu page?

**Comment by lszomoru** [comment]
**Verification:**
A new setting (`screencastMode.fontSize`) was added in order to control the size of the font used in screencast mode.

Steps:
- Enable `Screencast mode`
- Change the value of the `screencastMode.fontSize` and confirm that the font size changes
- Enter a value smaller than 20 and confirm that the font size will be 20
- Enter a value greater than 100, and confirm that the font size will be 100

**Comment by isidorn** [comment]
I have verified this works as expected.
Feels like bloat though.
