### ISSUE TITLE
Support opening the same folder or workspace in more than one window

### ISSUE THREAD

**Issue by eine** [microsoft/vscode#88108]
Currently, the only workaround seems to be https://code.visualstudio.com/updates/v1_24#_duplicate-workspace-in-new-window. However, that feature asks the user where to save the duplicated workspace; which might be misleading. On the one hand, the user might unwantedly overwrite the existing workspace file, incorrectly believing that (s)he actually did some modification to it. On the other hand, when a single folder is open, asking about the workspace file is misleading.

**Comment by eine** [comment]
@egamma, I think that #10121 is quite different to this feature request. Precisely, I'd be ok with having two instances of VSCode running in parallel. Alternatively, I'd be glad to see a message/warning when the user attempts to do it, instead of *silently failing* by just changing focus.

Conversely, most of the comments in #10121 seem to seek an opposite implementation: dettaching some parts/views of a single main instance to floating windows with limited UI features.

**Comment by egamma** [comment]
@eine the command 'Duplicate Workspace in New Window' is a workaround for #10121 which has the limitations that you point out in the description. Addressing these limitations is non trivial. The issue is that the duplicated Window needs to store its UI state somewhere and it needs a unique location, which is the untitled workspace. Therefore rather than improving the workaround it will be better to invest into #10121 for this reason I've closed it as a duplicate.
