### ISSUE TITLE
VS Code Crashes When SMB Volume Gets Disconnected

### ISSUE THREAD

**Issue by theodormarcu** [microsoft/vscode#88101]
Issue Type: <b>Bug</b>

If VS Code opens a file from a SMB Volume (say /Volumes/mounted_drive/*), and the respective Volume gets disconnected (e.g. network outage, timeout), then VS Code will freeze and crash. In the past, this also led to problems with the Finder, which meant that my Mac needed a hard reboot (Force Kill wouldn't work). I assume this is because of how VS Code deals with deleted files, but I don't know enough about the source to have an opinion. 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0
Fetching remote diagnostics for 'ssh-remote+tigergpu.princeton.edu' timed out.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Fetching remote diagnostics for 'ssh-remote+tigergpu.princeton.edu' timed out.
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.0.11
gitlens|eam|10.2.0
beautify|Hoo|1.5.0
vscode-map-preview|jum|0.4.8
python|ms-|2019.11.50794
remote-ssh|ms-|0.48.0
remote-ssh-edit|ms-|0.48.0
Go|ms-|0.12.0
material-icon-theme|PKi|3.9.2
java|red|0.55.1
markdown-all-in-one|yzh|2.6.1
material-theme|zhu|3.2.1

(2 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by oehoe** [comment]
Same problem, this is the info from the console application

Process:               Code Helper (Renderer) [2633]
Path:                  /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)
Identifier:            com.github.Electron.helper
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        Electron [2626]
Responsible:           Electron [2626]
User ID:               501

Date/Time:             2020-01-09 13:32:01.768 +0100
OS Version:            Mac OS X 10.15.2 (19C57)
Report Version:        12
Bridge OS Version:     3.0 (14Y908)
Anonymous UUID:        39B90B9D-92DB-4634-9889-F5C50E50410D

Sleep/Wake UUID:       E5AF2BA5-7101-4B5D-89E5-0AB7B60F88D4

Time Awake Since Boot: 13000 seconds
Time Since Wake:       36 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrRendererMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0 Crashed:: CrRendererMain  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff658647fa __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff65921bc1 pthread_kill + 432
2   libsystem_c.dylib             	0x00007fff657eba1c abort + 120
3   com.github.Electron.framework 	0x0000000105ed8b51 0x100543000 + 93936465
4   com.github.Electron.framework 	0x0000000105ed868c 0x100543000 + 93935244
5   com.github.Electron.framework 	0x0000000105ec8041 uv_run + 401
6   com.github.Electron.framework 	0x00000001028b6fd1 0x100543000 + 37175249
7   com.github.Electron.framework 	0x000000010293bfd0 0x100543000 + 37720016
8   com.github.Electron.framework 	0x000000010294b4bb 0x100543000 + 37782715
9   com.github.Electron.framework 	0x000000010294b997 0x100543000 + 37783959
10  com.github.Electron.framework 	0x00000001029aa103 0x100543000 + 38170883
11  com.github.Electron.framework 	0x00000001028e199a 0x100543000 + 37349786
12  com.github.Electron.framework 	0x00000001029a9a6f 0x100543000 + 38169199
13  com.apple.CoreFoundation      	0x00007fff2e25bb21 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
14  com.apple.CoreFoundation      	0x00007fff2e25bac0 __CFRunLoopDoSource0 + 103
15  com.apple.CoreFoundation      	0x00007fff2e25b8d4 __CFRunLoopDoSources0 + 209
16  com.apple.CoreFoundation      	0x00007fff2e25a740 __CFRunLoopRun + 1272
17  com.apple.CoreFoundation      	0x00007fff2e259bd3 CFRunLoopRunSpecific + 499
18  com.apple.Foundation          	0x00007fff308fd188 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
19  com.github.Electron.framework 	0x00000001029aa611 0x100543000 + 38172177
20  com.github.Electron.framework 	0x00000001029a9438 0x100543000 + 38167608
21  com.github.Electron.framework 	0x000000010294be68 0x100543000 + 37785192
22  com.github.Electron.framework 	0x000000010291dbc7 0x100543000 + 37596103
23  com.github.Electron.framework 	0x0000000105c3b270 0x100543000 + 91193968
24  com.github.Electron.framework 	0x0000000101c7cdcf 0x100543000 + 24354255
25  com.github.Electron.framework 	0x000000010401a960 0x100543000 + 61700448
26  com.github.Electron.framework 	0x0000000100f073d4 0x100543000 + 10240980
27  com.github.Electron.framework 	0x0000000100545854 AtomMain + 84
28  com.github.Electron.helper    	0x00000001004fa705 0x1004f9000 + 5893
29  libdyld.dylib                 	0x00007fff6571d7fd start + 1

**Comment by theodormarcu** [comment]
Here are my log files! I actually have two crash files in the console. Here is the info:

[Crash_Archive.zip](https://github.com/microsoft/vscode/files/4050160/Crash_Archive.zip)

**Comment by antoniomacri** [comment]
I'm also encountering this issue, almost every day since I work on network files.

Please fix it, and tell me if you need some more info.

**Comment by deepak1556** [comment]
@antoniomacri can you check the latest insiders https://code.visualstudio.com/insiders and if the crash happens, please attach the crash report following the steps at https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues

**Comment by ajs256** [comment]
I am still bumping into this issue often, since I work mainly with files on a removable drive. Is a fix in the works?

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/106879
