### ISSUE TITLE
Find in files (workbench.view.search) command opens terminal if Search: Location is set to panel

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#88132]
Issue Type: <b>Bug</b>

Happened in `master` during holidays, but I thought that it was my local problem.

1. Add `"search.location": "panel"` to `settings.json`
1. Use shortcut <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd> or **Edit** > **Find in Files** from menu
1. Terminal panel is opened instead. Moreover Search panel title is not visible at all.

I don't see any errors in DevTools console

**Workaround**: use `"search.location": "sidebar"` instead

VS Code version: Code - Insiders 1.42.0-insider (9349e9a2fdbd1d92824ce99af4a50b6785351b11, 2020-01-06T10:40:10.218Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (19.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by roblourens** [comment]
I can't repro it, but basically the search view doesn't show up anywhere for you?

If you right click in the panel title area, is the search view unchecked? 
![image](https://user-images.githubusercontent.com/323878/71837782-1418eb00-306c-11ea-9f28-5ed78c251772.png)

**Comment by IllusionMH** [comment]
Can't see it in panel context menu
![image](https://user-images.githubusercontent.com/1312662/71837943-566c1780-30c0-11ea-87b8-e5295e185600.png)
and not in Activity Bar context menu as well.

**Comment by IllusionMH** [comment]
Bisected and looks like it's 57c30ddb82979a58a40441c02568a865da63285e
```
# first bad commit: [57c30ddb82979a58a40441c02568a865da63285e] Port view container logic from activitybarpart to panelpart (#87444)
```

/cc @sbatten

**Comment by IllusionMH** [comment]
Reproduced on Ubuntu and MacOS as well. See #88165

**Comment by roblourens** [comment]
Thanks! I actually can repro after all. I thought I had updated but wasn't on the new Insiders...

**Comment by roblourens** [comment]
I have a workaround which I think is ok for now but, please review @sandy081 and @sbatten when you're back. 

This is from both https://github.com/Microsoft/vscode/commit/2def84c1e2e84b2d85f5330e5864514500ecdabf and  https://github.com/microsoft/vscode/commit/57c30ddb82979a58a40441c02568a865da63285e

We register the sidebar view container with hideIfEmpty set: https://github.com/Microsoft/vscode/commit/2def84c1e2e84b2d85f5330e5864514500ecdabf#diff-6c358dac4832779e39f087c84137742eR336

But then we find that descriptor when looking for the panel's viewContainer: https://github.com/microsoft/vscode/commit/57c30ddb82979a58a40441c02568a865da63285e#diff-cd026e7ca90d9b77a81766f73c99e98cR186 

Because they have the same IDs?
https://github.com/microsoft/vscode/blob/629a08ed6231d7af269ae61a5cc610490d1f7f5d/src/vs/workbench/services/search/common/search.ts#L20-L22

Maybe these things should have different IDs?

**Comment by roblourens** [comment]
Actually I don't have a workaround - if I set hideIfEmpty to false, then the activitybar icon won't go away when the view is in the panel.

We could get rid of this but I don't know if it's safe: https://github.com/microsoft/vscode/blob/629a08ed6231d7af269ae61a5cc610490d1f7f5d/src/vs/workbench/browser/parts/panel/panelPart.ts#L297-L302

@sandy081 please take a look and see if you have any ideas.

**Comment by sandy081** [comment]
Our changes to adopt panels to use views infrastructure has broken this. The right fix here is to use latest infra to move search views which is very easy now.

Working on fix.

**Comment by roblourens** [comment]
> Renaming the id has a side affect that the search view's state (position/visibility) is reset

Does that mean it's reset across upgrading vscode, so it will lose its configured position? I think that's not ideal

**Comment by sandy081** [comment]
Yeah it does. The state that gets reset is only visibility and order. Re visibility, I do not think user hide search panel. So, I do not think its major impact.

**Comment by IllusionMH** [comment]
Configured position in question is position in panel (reordered via drag'n'drop)?

Search correctly appeared as panel, but can't provide any info about changes in order, because search was first

**Comment by sandy081** [comment]
> Configured position in question is position in panel (reordered via drag'n'drop)?

Yes.

**Comment by roblourens** [comment]
I still think people use these features and will be affected by it. Is the problem sort of that there is no longer a concept of the view descriptor being "for" the panel vs the viewlet? Or is there still any way we can keep the persisted data for the panel while it also has the same ID as the viewlet's descriptor?

**Comment by sandy081** [comment]
We are moving everything into view containers and views. View containers are the containers that holds views (as the name says). In side bar/activity bar and panels section view containers viewlets and panels respectively. It is required that these containers have unique ids otherwise you will have issues like this. 

To be clear, the only state that gets reset is the position of the search panel in the panel bar. How about adding this to the release notes, If you consider this as a major impact?

**Comment by roblourens** [comment]
I don't think that having it in the release notes makes it any less annoying. Ideally users wouldn't have to notice this change under the hood, like maybe we could port the persisted data over from the old ID to the new one, but I have no idea how difficult that is.
