### ISSUE TITLE
Search seeding is inconsistent

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#88160]
Issue Type: <b>Bug</b>

Invoking `workbench.action.findInFiles` when you have no text selected will seed the search text with the word closest to your cursor. Sometimes.

If the search box is empty it will be seeded with the word under your cursor. If the search box is not empty it is not seeded.

This makes it impossible to know what invoking `workbench.action.findInFiles` will actually do unless you remember what text is present in the search panel, which probably isn't even open.

Expected result is that the behavior is consistent. Probably that the search box is _always_ seeded when `editor.find.seedSearchStringFromSelection` is enabled.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

**Comment by roblourens** [comment]
Really the problem is overloading that keyboard shortcut to mean "search with this text" and also just "focus the search view". I didn't want it to be too aggressive when using ctrl+shift+f just to focus the search view, especially now that changing it would trigger a search. I will leave this open for suggestions but I'm nervous about changing this now.

Original discussion was here https://github.com/microsoft/vscode/issues/17974#issuecomment-297452167

**Comment by eamodio** [comment]
Maybe it can be a setting if we don't want the change the current behavior? But at least for me, I always want `Ctrl+Shift+F` to search seeded with the text

**Comment by akbyrd** [comment]
@roblourens Since there's a separate option for whether to seed or not the overloading isn't terrible. I could imagine there being separate commands for "focus with seed" and "focus without seed", but it's not something I need personally.

I'm not particularly concerned with whether the focus command seeds when there's no selection or not. I'm only advocating for it being _consistently_ one or the other.

**Comment by akbyrd** [comment]
Another option is to promote `editor.find.seedSearchStringFromSelection` to a enum: never, selection, nearestWord.

**Comment by roblourens** [comment]
Out of curiosity do you two not use that keyboard shortcut to focus/reveal the search view?

**Comment by eamodio** [comment]
Hrm, I don't think I really ever use it for show/focus. Maybe a compromise, is to show/focus the view if its hidden, and always overwrite if its visible. Then you can at least just hit it twice to overwrite if that is what you want.

**Comment by akbyrd** [comment]
I use `workbench.action.findInFiles` to both show the the panel and to focus it.

**Comment by bronson** [comment]
I'm glad this issue is open. I spent quite a while trying to figure out how to use Cmd-F and Cmd-Shift-F: https://stackoverflow.com/questions/59888563/how-to-find-selection-in-files It's confusing!

Personally, I don't think it matters too much if they both pre-seed or not, as long as they behave consistently. That said, I hope you choose to either always pre-seed or never pre-seed. Pre-seeding only when it's blank is difficult to figure out when you're not expecting it.

**Comment by roblourens** [comment]
I have been thinking about this and related issues again lately https://github.com/microsoft/vscode/issues/91901

And I am interested in your feedback on this suggestion https://github.com/microsoft/vscode/issues/91901#issuecomment-593526895

**Comment by roblourens** [comment]
Merging into https://github.com/microsoft/vscode/issues/91901
