### ISSUE TITLE
Can't create new debug Watch expressions while search is active

### ISSUE THREAD

**Issue by ariffjeff** [microsoft/vscode#88242]
Issue Type: <b>Bug</b>

In the debug Watch dropdown, make sure it is in focus. Type anything so that the search is activated (orange box with text in the top right corner). Now try to create a new Watch expression. You shouldn't be able to (via both the plus button and double clicking in empty space in the dropdown).

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
extendscript-debug|Ado|1.1.2

</details>

**Comment by isidorn** [comment]
I acknowledge the issue and I can reproduce it.
I first thought that the problem is that the tree filters out the input box, however fixing that [here](https://github.com/Microsoft/vscode/blob/b3d45da5833e4c6455a256af2b87b9dc28fde4ed/src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts#L72) does not fix the whole problem.
Another issue seems to be timing related, since the input box gets the blur and disposes iteself.
For now leaving this open and if users have ideas on how to fix I am open to suggestions. Thanks
