### ISSUE TITLE
Slow to create many Watch dropdown expressions 

### ISSUE THREAD

**Issue by ariffjeff** [microsoft/vscode#88240]
Issue Type: <b>Bug</b>

The Watch dropdown in the Debug tab becomes slow to respond to user input when there are many expressions being watched in it.

To reproduce (I'm using node js for debugging):
New js file...
Create lots of variables (I don't know if the size of the information in the variables matters or not so I just added a decently sized array):
`a=b=c=d=e=f=g=h=i=j=k=l=m=n=o=p=q=r=s=t=u=v=w=x=y=z= [12,253,5,457,32,3647,48,56,679,567,45]`

Then in the Watch dropdown, create a separate expression for every variable.
i.e.
a
b
c
d
...

Since I've done the whole alphabet you should have 26 individual Watch expressions. You should notice that the dropdown starts to take longer and longer to respond as you add more and more expressions.

VS Code version: Code - Insiders 1.42.0-insider (629a08ed6231d7af269ae61a5cc610490d1f7f5d, 2020-01-07T05:28:24.258Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by isidorn** [comment]
Yes I can reproduce this.
And this behavior is not new. The issue is that when a new watch expression is added we have to re-evaluate each watch expression.
I have pushed some improvments that we do not re-evalaute each expression 3 times, but onle 1. So it should be 3 times faster.
Please note that apart from this we are seeing some slowdown in the processing of messages caputred with this issue https://github.com/microsoft/vscode-js-debug/issues/206
Once we fix that, this one might get even better

fyi @connor4312

**Comment by ariffjeff** [comment]
Sounds good, thanks for explaining!
