### ISSUE TITLE
Copy bettween two window

### ISSUE THREAD

**Issue by phuc2401** [microsoft/vscode#88261]
Issue Type: <b>Bug</b>

s1. copy one file from 1 window
s2. paste to other window
--> the file in first window is deleted?

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17763

**Comment by gjsjohnmurray** [comment]
Previously reported several times (#83335, #80330, #81594) but not reproduced on any of those.

**Comment by bpasero** [comment]
@gjsjohnmurray thanks for your helpful comments on the issues, I appreciate you taking the time to find the related issues 👍

**Comment by bpasero** [comment]
@phuc2401 does this consistently reproduce for you? And if so, how exactly do you do the copy operation?

//cc @isidorn

**Comment by phuc2401** [comment]
hi @bpasero , it seem like I cannot reproduce this bug. I tried to close and reopen 1 of the 2 windows, the problem was still there. only when I close and reopen both windows then that problem is resolved.
About how i copy, I right-click file and select Copy -> swtich to the other window -> select the folder to paste -> right-click paste -> switch to the previous window -> the file I chose to copy is now deleted --> must go to Source control to Disacard change.

**Comment by bpasero** [comment]
Ok, this seems to be file explorer commands. @isidorn can you check if you possibly invoke the `move()` method and not the `copy()` method from the file service in certain cases?

**Comment by isidorn** [comment]
Yes, this issue can happen due to how copy  / cut is implemented [here](https://github.com/Microsoft/vscode/blob/fd1a44238f75296babd5ea644598a6eff99a020e/src/vs/workbench/contrib/files/browser/fileActions.ts#L1088)

To reproduce from before:
Cut and paste some thing in Window 1
Copy something from Window 2
Paste something from Window 1 -> it will be moved.

Idealy I would have to write in the `ClipboardService` if it is a cut or copy.
For now I have just changed it to less aggresivly cut. What now will not be possible is to cut from one window to another. It will still copy. Let's go with this approach and see if users hit issues
@gjsjohnmurray thanks for finding potential duplicates!
