### ISSUE TITLE
Back off from successive requests when sync results in a 401

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#88317]
Currently it appears that when settings sync gets a 401 unauthorized it will continue to sync (and fail) on the standard interval. We should instead stop syncing immediately and show a warning that there is a problem with auth. If the server gives a 401 that means it's available and function and the token failed verification, it is guaranteed to continue to fail verification if the same token is used.

Related https://github.com/microsoft/vscode/issues/85211 (this is more appropriate for 50x and 404s)

**Comment by gjsjohnmurray** [comment]
Looks like a dup of #86298

**Comment by Tyriar** [comment]
It is indeed lol, I thought it was a regression. Closing the other one as this has more info.

**Comment by sandy081** [comment]
I would not disable sync immediately in this case because auth token is managed by extension and so I would give some chances before stopping sync. Strategy that is followed in this case is mentioned [here](https://github.com/microsoft/vscode/issues/85211#issuecomment-578294177). 

Reiterating here:

Error handling strategy:

- Sync is disabled automatically for specific errors (large resources - 413)

<img width="452" alt="image" src="https://user-images.githubusercontent.com/10746682/73102103-6faef980-3ef1-11ea-8f81-e66dd804abc7.png">

- Auto sync interval increases by number of failures every time there is an error (other than above)
- Sync is disabled when there are consecutive 5 failures 

<img width="538" alt="image" src="https://user-images.githubusercontent.com/10746682/73102610-83a72b00-3ef2-11ea-8b7c-bb08585b8ae8.png">

I think this should not happen, if happens it should be a bug some where (sync, auth or server)

**Comment by sandy081** [comment]
Fixed by a27c9fc6b18f5235aa0a457f5deae69e77499e47
