### ISSUE TITLE
Settings sync while resolving conflicts doesn't work well

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#88324]
- Trigger sync conflicts
- Open the conflict resolution json editor on computer A
- Make another change on computer B
- Resolve the conflicts on A
- An error pops up, "New data exists"

**Comment by sandy081** [comment]
When changes are applied from conflicts diff editor

* If local contents have changed, conflicts are computed with new local content and content gets merged if there are no conflicts, otherwise the diff editor is updated with new conflicts.

In all other cases, applied contents are synced and pushed
