### ISSUE TITLE
Feedback on extension syncing UX

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#88322]
@rebornix gave me feedback that he would have wanted a warning or something when syncing so many extensions. Additionally cancellation and a progress bar would have been good as syncing 100 extensions take quite a long time.

First time experience where a user wants to ignore extensions is also tough.

Some random ideas:

![image](https://user-images.githubusercontent.com/2193314/72027929-956fa980-3235-11ea-8601-7846c893b8c7.png)

Or after pressing OK and you have selected Extensions present a dialog saying which extensions you want to sync?

> Themes
  > blah 1
  > blah 2
> Languages
  > blah 1
  > blah 2

**Comment by rebornix** [comment]
I'd like to share a bit more about the _bad_ experience I got for syncing extension the first time across machines. When it asks me if I want to sync Extensions, my first impression is _why not_. However since I have 100 extensions installed on another machine, my workbench exploded

  * Vim and Atom keymap tries to beat each other
  * Multiple custom Welcome page
  * Tons of first time usage notifications
  * Error/Warning for missing dependencies
  * C++ extension immediately starts to download C++ tool chain.
    * This also leads to noise running fans

It's way beyond my expectation as firstly I forgot that I have so many extensions and at least half of them were no longer used. They were not uninstalled as I didn't know they exist. Secondly, I can't stop the whole syncing process, installing an extension is not an atomic operation/transaction so there is no easy way to **undo**. Lastly, extension storages are not synced, so they all think I'm a fresh new user.

Considering that side effects of installing an extension is not controlled by us, we may want to give users enough information about what they are syncing and _warn_ that it might be costly.

BTW, we may also want to call out that for extensions, this feature is *Automatic Downloading* instead of syncing.

**Comment by sandy081** [comment]
Thanks for the ideas, I will think about these.

**Comment by Tyriar** [comment]
👎 on the "automatic downloading" wording part, to me they mean the same thing and we should be consistent.

**Comment by sandy081** [comment]
Some of the issues you mentioned should be addressed not through UX but fixing themselves.

For example, some of the issues like (Vim vs Atom) go away when we sync enablement state of extensions. I am sure you would have one disabled in your first system - #86916

Multiple extension pages and notifications should go away when we sync UI state of extensions or provide a way not to trigger welcome experience by extensions.

Extensions downloading runtime deps might expected or not. If it is not expected then the extension should not be activated in the current window.

Until then, I would plan to show a picker to pick extensions to install when you are setting up sync for the first time on a machine.

**Comment by Tyriar** [comment]
> show a picker to pick extensions to install

Wouldn't this complicate what you're syncing as the source of truth and the local machine now use a different set of extensions?

**Comment by sandy081** [comment]
Good point, but extensions which user does not want to sync can be added to the ignored list that is local to that machine.

**Comment by rebornix** [comment]
@sandy081 yes once enablement and UI states of extensions can be synced, then the extension syncing can be silent and transparent to users a lot more.

> 👎 on the "automatic downloading" wording part

@Tyriar I just learnt that what I understand was wrong, it's actually not "automatic downloading" as if I remove an extension from one, it will be removed from other machines which are being synced.

However, since that's the current behavior, I'll recommend to provide this option. I want VS Code to track the extensions I installed but I don't want auto installation or removal, before I attempt to do so.

**Comment by Tyriar** [comment]
> I want VS Code to track the extensions I installed but I don't want auto installation or removal, before I attempt to do so.

@rebornix we talked about that earlier, to give a prompt for installed. I think that topic just ended up disappearing in favor of always installing. Not sure how we got there.

**Comment by sandy081** [comment]
> However, since that's the current behavior, I'll recommend to provide this option. I want VS Code to track the extensions I installed but I don't want auto installation or removal, before I attempt to do so.

Its a fair but advanced request which is P2. Idea is that a user can disable syncing extensions, but can have a view in extensions viewlet to manually pull, push & remove the extensions in cloud - #88825

Regarding this request - I am not thinking of doing any changes in favour of syncing enablement and UI states and thereby would like to close this.

**Comment by sandy081** [comment]
Closing this as per above comment.
