### ISSUE TITLE
Git: using SCM panel to commit makes pre-commit hook fail

### ISSUE THREAD

**Issue by reedham1** [microsoft/vscode#88454]
- VSCode Version: 1.40.2
- OS Version: MacOS 10.14.6 

I use Husky to run git hooks, including a pre-commit hook. Making any commit with the SCM UI (check button) fails the pre-commit hook with error message `tput: No value for $TERM and no -T specified`. Those same commits that fail, when made in any other terminal, including the VS Code terminal, succeed with the pre-commit hook. When made in the VS Code terminal, $TERM is set to `xterm-256color`. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by joaomoreno** [comment]
It seems the tool you are using `tput` expects `TERM` to be set, which is pretty bad behavior since when committing via Code there is indeed no terminal involved. Two solutions for you:

- Adjust your hooks to accommodate for the fact that they might run headless (no `TERM` defined)
- Simulate a terminal and set `TERM` in your scripts before calling `tput`
