### ISSUE TITLE
Search in Panel broken by Progress bar

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#88461]
Issue Type: <b>Bug</b>

* Have Search in the Panel, reload the window for a fresh state
* Search for something which has more than 3 results
* The search results are not complete 

![Kapture 2020-01-10 at 16 05 53](https://user-images.githubusercontent.com/876920/72194602-23c56600-33c3-11ea-9523-3c179ea65401.gif)

It seems rendering progress bar in panel breaks it

```
  ERR Bad progress location: workbench.view.search: Error: Bad progress location: workbench.view.search
    at y.withProgress (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5014:438)
    at e.doSearch (file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6258:623)
    at file:///Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6258:527

```

VS Code version: Code - Insiders 1.42.0-insider (960cddb992cc96d47f56b633b361909f1b5b3353, 2020-01-10T05:35:27.119Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (2.31GB free)|
|Process Argv|-psn_0_6473260|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
comment-tagged-templates|bie|0.3.0
github-markdown-preview|bie|0.0.2
markdown-emoji|bie|0.0.9
markdown-preview-github-styles|bie|0.1.6
gitlens|eam|10.2.0
vscode-pull-request-github-insiders|Git|2020.1.11042
remote-ssh-edit-nightly|ms-|2020.1.11041
remote-ssh-nightly|ms-|2020.1.11041
debugger-for-chrome|msj|4.12.5

(2 theme extensions excluded)

</details>

**Comment by JacksonKearl** [comment]
Previously in 1.41 this call gave us a indicator like this in search 
![image](https://user-images.githubusercontent.com/8586769/72194937-c92d0980-33c4-11ea-94f8-3a6d5fb1b89a.png)
(oof)


and it rendered the progress indicator in whatever viewlet happened to be open. Did something change here?

**Comment by IllusionMH** [comment]
> he search results are not complete

Actually if you use Copy all - it copies all entries.

@sbatten 
It worked fine when I changed location from `panel` to `sidebar` so I guess it's related change of `PANEL_ID` https://github.com/microsoft/vscode/commit/19c07c0c0e8ba16804b6834df3029305f91c100c

(probably it leads to another issue - last search query is not restored when location is `panel` and works fine when it's in `sidebar`. Will investigate and report later if will confirm findings)

As for broken position of indicator - was it fixed? I've tried to fix it locally and only position centering left (needs 2px shift for panel instead of 1px for action bar).

**Comment by JacksonKearl** [comment]
No longer able to reproduce either the missing results or the progress indicator error message.

**Comment by IllusionMH** [comment]
Tried latest build just now and looks like problem is still there.
<details>
<summary>Build info and trace</summary>

Version: 1.42.0-insider (user setup)
Commit: 33c79d5ad447956814a2a3658029dffb9e28bae6
Date: 2020-01-15T09:36:35.018Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

```
ERR Bad progress location: workbench.view.search: Error: Bad progress location: workbench.view.search
    at y.withProgress (file:///C:/Users/<user>/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5075:438)
    at e.doSearch (file:///C:/Users/<user>/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6345:623)
    at file:///C:/Users/<user>/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:6345:527
```

</details>

--- 
I suppose that's because after it's incorrect to [unconditionally use `VIEWLET_ID`](https://github.com/microsoft/vscode/blob/3ae460476f94a5911d691dcbbbb2ad45dc648306/src/vs/workbench/contrib/search/browser/searchView.ts#L1350) when `"search.location": "panel"` and instead use either `PANEL_ID` or `VIEW_ID` depending on `search.location` value.

**Comment by sbatten** [comment]
no repro in latest insiders for me either, @IllusionMH your version info is for stable build.

Version: 1.42.0-insider (user setup)
Commit: 33c79d5ad447956814a2a3658029dffb9e28bae6
Date: 2020-01-15T09:36:35.018Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by IllusionMH** [comment]
@sbatten how 1.42 is stable build?

![image](https://user-images.githubusercontent.com/1312662/72458646-a0947d80-37d1-11ea-8511-268300360e3e.png)

Same commit as you mentioned 10h ago.

@sbatten @JacksonKearl are you using `"search.location": "panel"`? Because this is required to reproduce this issue.

**Comment by JacksonKearl** [comment]
Able to reproduce now. It seems it only reproduces if you reopen the window after moving search to the panel.

**Comment by sbatten** [comment]
https://github.com/microsoft/vscode/commit/06cf7fbc1d25f4dd90fed2f448a9a603148c75cf should have the fix for the bad progress location which should resolve the issue.

**Comment by IllusionMH** [comment]
@sbatten thanks, just got latest build and both problems are reolved.
