### ISSUE TITLE
Confusing error prevents mocha tests from running yet it still passes

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#885]
`mocha` was breaking, saying it can't find a module but still passing the test suite. If this happened on CI, it would not pick this up.

Run tests in vscode:

```
[13:35:19] Using gulpfile ~/workspaces/forks/vscode/gulpfile.js
[13:35:19] Starting 'test'...
No define call received from module vs/workbench/test/browser/parts/editor/resourceEditorInput.test. This might be a problem.
No define call received from module vs/workbench/test/browser/parts/editor/resourceEditorModel.test. This might be a problem.
```

Output of `mocha`:

```
~/workspaces/forks/vscode @master
$ mocha
No define call received from module vs/workbench/test/browser/parts/editor/resourceEditorInput.test. This might be a problem.
No define call received from module vs/workbench/test/browser/parts/editor/resourceEditorModel.test. This might be a problem.

~/workspaces/forks/vscode @master
$ echo $?
0
```

This started happening in a workspace with several changes but after switching branches back to master, it continued to happen. I fixed the issue by doing a `gulp clean`.

**Comment by joaomoreno** [comment]
Very good catch!

**Comment by joaomoreno** [comment]
@alexandrudima here's what's happening:

- build somehow leaves a file empty (eg `vs/workbench/test/browser/parts/editor/resourceEditorInput.test.js`)
- running `mocha` will simply output `No define call received...`
- node will exit successfully since there is nothing left to do

I've pushed 271135 which fixes this in a lame way: I trap the process from exiting during the loading phase and exit the process with a proper error code.

I feel like the loader should provide us a better way to handle this, though. Could we get the loader to support error callbacks, like [requirejs](http://requirejs.org/docs/api.html#errbacks)?

**Comment by alexandrudima** [comment]
@joaomoreno The loader supports that, the error callback is the third argument in a require call:

```javascript
require([...], function() { /* yay */ }, function(err) { /* bubu */ });
```

**Comment by joaomoreno** [comment]
I'm not getting called in the case that there is no define call in the module. :-1:

**Comment by alexandrudima** [comment]
Indeed, there is no real loading error, instead the file is empty. Maybe we can hook up https://github.com/Microsoft/vscode-loader/blob/master/src/loader.ts#L1466 to generate an error. I think "This might be a problem" is more like "This definitely is a problem"

**Comment by joaomoreno** [comment]
:+1:

I will leave this issue open, so I revert the commit and use the error callbacks instead when we get the fix in the loader.

**Comment by alexandrudima** [comment]
Pushed Microsoft/vscode-loader@ae37fe0 and adopted it in 41568f6

Double checked and now I get the error callback invoked.

**Comment by joaomoreno** [comment]
Awesome, adopted in the test scripts in a436a25.
