### ISSUE TITLE
Honour the optional `endLine` and `endColumn` attributes of `StackFrame` and `Breakpoint`

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#8851]
If a StackFrame or a Breakpoint has an optional end location, show the character range instead of the full line.

**Comment by isidorn** [comment]
Was last week on vacation, it is better to move this to may than to work on it in endgame week.

**Comment by isidorn** [comment]
Now we are respecting the `endColumn` and `endLine` number on the VSCode side.
If an adapter provides an `endLine` and `endColumn` for a stack trace we will decorate it with a stronger color such that it is clear for the user the exact range a stack frame has. Note that I have hacked the node debugger to return `endColumn` and `endLine` to produce this gif.

If a breakpoint has an `endColumn` and `endLine` upon clicking on it in the breakpoint view we will now select the whole breakpoint range.

@gregg-miskelly let us know if this works for you since as far as I understand the C# adapter provides endLine and endCOlumn.

![stackframeranges](https://cloud.githubusercontent.com/assets/1926584/25942058/f58ddb82-363b-11e7-8973-35f139b8b205.gif)

![bpsselection](https://cloud.githubusercontent.com/assets/1926584/25942291/c1c5d8b2-363c-11e7-8b2b-3bf33a536711.gif)

**Comment by gregg-miskelly** [comment]
@isidorn Thanks! It looks great. I am assuming this should go out in the stable channel in early June. Is that correct?

![cs-column-range](https://cloud.githubusercontent.com/assets/11078489/26008377/60f2508e-36f9-11e7-9eb4-0655608085b8.PNG)

**Comment by isidorn** [comment]
@gregg-miskelly yes that is correct. Feel free to provide additional issues with feedback.
