### ISSUE TITLE
Custom editor: is hijacking all editors opening

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#88525]
Steps to Reproduce:

1. open a file
2. run find references and get results from the same file
3. click on the results

=> :bug: nothing happens

I think the problem is in the options conversion here: 

https://github.com/microsoft/vscode/blob/17d6b13a35344ba36a4aad6d7dbbc77359f137b3/src/vs/workbench/contrib/customEditor/browser/customEditors.ts#L357

**Comment by bpasero** [comment]
Ok there was clearly a bug in editor options that I fixed with https://github.com/microsoft/vscode/commit/b84d08be70d1efe55d6097d3badcc03297a27635

I still wonder if custom editors should hijack every editor opening and look for an existing editor being open based on the resource? Let's walk through this in our call.

**Comment by mjbvz** [comment]
Thank you for the fix! 

Just as some background, I added this code to handle the following case:

1. User opens an image in a custom editor but then reopens it as a normal text file
1. They then switch to a different editor (keeping the image tab open)
1. And then use quick open to switch back to the image editor

In this case, we want to make sure that we continue using text editor and not the custom editor. That's what https://github.com/microsoft/vscode/blob/17d6b13a35344ba36a4aad6d7dbbc77359f137b3/src/vs/workbench/contrib/customEditor/browser/customEditors.ts#L357 was trying to achieve.

However I should have better scoped that change. I'm going to add logic so that we only return an override if there are any custom editors available for the resource 

We can discuss if we need to make any additional fixes during the call

**Comment by mjbvz** [comment]
Closing this based on our discussion today. 2bbe9c5 scoped the logic to only apply to files that may have a custom editor
