### ISSUE TITLE
VS Code for Windows remains to generate temporary file in portable mode

### ISSUE THREAD

**Issue by tonyank** [microsoft/vscode#88562]
I noticed by accident that VS Code for Windows remains to generate temporary file in portable mode although I made a protable version by creating a tmp folder and a data folder in the root of VS Code.Is it normal? Thx.

 Directory of C:\Users\**\AppData\Local\Temp\VSCode Crashes

2019/12/24  13:25    <DIR>          .
2019/12/24  13:25    <DIR>          ..
2019/12/24  13:25         1,048,576 CrashpadMetrics-active.pma
2019/12/24  13:25                 0 metadata
2019/12/24  13:25                 0 operation_log.txt
2019/12/24  13:25    <DIR>          reports
2019/12/24  13:25                40 settings.dat

**Comment by bpasero** [comment]
It looks like there is a `crashesDirectory` option in `crashReporter.start` to control this but the docs read:

> Directory to store the crashreports temporarily (only used when the crash reporter is started via process.crashReporter.start).

We do however to my knowledge not start the crash reporter for child processes (even though @alexdima eventually wanted to enable it for the extension host).

@deepak1556 can you check in Electron where this directory is being set and if there is a way to change it?

**Comment by deepak1556** [comment]
@bpasero in electron the crash directory location is defaulted here https://github.com/electron/electron/blob/master/lib/browser/crash-reporter-init.js#L18 ,  we can override the location with `crashesDirectory` option.

**Comment by bpasero** [comment]
@joaomoreno moving to you since you seem to be configuring the temp path in portable already:

https://github.com/microsoft/vscode/blob/bf350ef870f229b334d3f54a7cc81a7e73841c3b/src/bootstrap.js#L265-L271

You possibly need to all [`app.setPath`](https://github.com/electron/electron/blob/7-0-x/docs/api/app.md#appsetpathname-path) for this one to work. The list of possible names for paths is here: https://github.com/electron/electron/blob/7-0-x/docs/api/app.md#appgetpathname

**Comment by tonyank** [comment]
I see, the temporary files are tenerated by windows, not vscode. It's an OS behavior.
