### ISSUE TITLE
REPL console by default + clear the Terminal

### ISSUE THREAD

**Issue by yalajules** [microsoft/vscode#88624]
Sorry if this features request was already open.
I'm a french teacher (with 16 years students, first experience of computer science) and we need an IDE that supports collaborating (with Live share) for the student Python projects.
First, we used Thonny IDE which is greatful for beginners in Python but does not support collaborating. So we turn to VS Code.
Our first impressions were : 
Not easy to simply find the console (REPL in english langage ?) : why not to put it by default in the view menu ?
Not easy to clear the Terminal : why not to put a default command somewhere (in the panel, and/or in the view menu, and/or right click button etc.)
Thanks for reading.

**Comment by isidorn** [comment]
Hi, thanks for providing feedback!

1) Under the view menu there is Debug Console (picture attached)
2) There is a context menu action to clear the terminal (picture attached)

I am closing since I feel like we already have what is requested in this feature request.

![Screenshot 2020-01-15 at 10 00 32](https://user-images.githubusercontent.com/1926584/72419856-e45d9780-377d-11ea-9b6d-8a11b2c6b9f2.png)

![Screenshot 2020-01-15 at 10 01 13](https://user-images.githubusercontent.com/1926584/72419903-ff300c00-377d-11ea-8e45-edfeff6f1c26.png)

**Comment by yalajules** [comment]
Hi,
Tx for response.
1) I'm not talking about a debug console but a simple console to evaluate quickly expressions outside any programs or files (like Python REPL)
2) On Windows, I have not any context menu in the Terminal.

**Comment by isidorn** [comment]
1) Please file that against the Python extension here https://github.com/microsoft/vscode-python
2) fyi @Tyriar for context menu to clear on Windows

**Comment by Tyriar** [comment]
Use this setting to show the context menu on Windows:

```
"terminal.integrated.rightClickBehavior": "default"
```

Note that the clear command has issues on Windows 10: https://github.com/microsoft/vscode/issues/75141
