### ISSUE TITLE
Issue Reporter: Extension under test does not appear in the Issue Reporter's extension list

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#88641]
Issue Type: <b>Bug</b>

I was trying to check how vscode's Issue Reporter determines where to file the issue, and realized that the issue reporter is missing the extension under test from the list completely. 

Repro:
1) checkout any extension source code (I tested with github.com/Microsoft/vscode-extension-samples/helloworld-sample)
2) open vscode
3) Then, launch "Run Extension".
4) From the extension development host, ensure the extension is activated, and choose "Help: Report Issue" from the command pallette. 
5) Select File On: an Extension, and see the Extension drop down menu. The tested extension is missing.

I guess this is because the tested extension is not registered at all. See the attached extension info - the extension under test (helloworld-sample in my case) is not included.

VS Code version: Code - Insiders 1.42.0-insider (7c0095ee2d064033fc13184127a9adc603454729, 2019-12-20T07:58:23.119Z)
OS version: Linux x64 5.2.17-1rodete3-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 1593)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.39GB (2.59GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.0
vscode-docker|ms-|0.9.0

</details>

**Comment by RMacfarlane** [comment]
This is currently by design - the issue reporter populates the list of extensions from installed, active extensions. The reasoning behind this is that if you're only running an extension locally, it is likely to be something under development that isn't yet published. Though this isn't true for the extension samples, I don't think there are many other use cases for reporting on an extension that's being debugged but is not installed.

As for where the reporter files the issue - it uses the "bugs.url" property from the `package.json` of the extension if it exists, or the `repository.url` property.
