### ISSUE TITLE
Allow "inline" menu contributions to quick pick items

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#88716]
Similar to tree items, it would be great to be able to contribute commands to quick pick items

It is possible internally -- see:
![image](https://user-images.githubusercontent.com/641685/72477316-3b369180-37bd-11ea-8576-9cb3ccf09a66.png)

Example use-case:
I would like to remove that button on top (since it is dependent on selection) and instead have it available on each stash entry. There are many other quickpick lists in GitLens where I would like to do a similar thing.

![image](https://user-images.githubusercontent.com/641685/72477556-c9ab1300-37bd-11ea-962c-d73f7f88f111.png)

**Comment by TylerLeonhardt** [comment]
API proposal (is basically just exposing the existing internal API):

```ts
	interface QuickPickItem {

		label: string;

		// ...

		/*
		NEW
		
		*/
		buttons?: QuickInputButton[];
	}
```

```ts
	export interface QuickPick<T extends QuickPickItem> extends QuickInput {

		/**
		 * Current value of the filter text.
		 */
		value: string;

		// ...

		/**
		 * Buttons for actions in the UI.
		 */
		buttons: readonly QuickInputButton[];

		/**
		 * An event signaling when a button was triggered.
		 */
		readonly onDidTriggerButton: Event<QuickInputButton>;

		/**
		 * NEW
		 */
		readonly onDidTriggerItemButton: Event<IQuickPickItemButtonEvent<T>>;
		// ...
	}
```

New type:
```ts
interface IQuickPickItemButtonEvent<T extends QuickPickItem> {
	button: QuickInputButton;
	item: T;
}
```

**Comment by alefragnani** [comment]
That’s great to see this feature request being reopened and moving to API proposal stage. I have opened a similar request last year (#96147), but just like this one, was closed due to not enough upvotes.

Similar to this request, but on a _keyboard approach_, maybe https://github.com/microsoft/vscode-remote-repositories-github/issues/2 could also take advantage if you expose Alt Modifiers, as requested in #18064. I know the Alt modifier is a _not so powerful idea_, but at least for those ` in New Window` commands, it would follow VS Code behavior. 

Looking forward for testing this API 😬

**Comment by TylerLeonhardt** [comment]
Reopening for finalization

**Comment by TylerLeonhardt** [comment]
Finalized in f8ed49c5d331378dfed8f31a6360bac76329bed4

**Comment by nturinski** [comment]
@isidorn Wow! You work really fast!

Just kidding, I didn't realize that this was already in.  So I guess don't worry about this request 😄

**Comment by isidorn** [comment]
@nturinski hahaha, as I said I am not aware of all the Quick Pick api features :)
Let us know how it goes.
