### ISSUE TITLE
VSCode doesn't recognize standard shell change on macOS, tries to load old shell.

### ISSUE THREAD

**Issue by Helmi** [microsoft/vscode#88736]
- VSCode Version: 1.41.1 (also tested Insiders 1.42.0)
- OS Version:

I have been using fish shell for a while on macOS and was switching back to zsh yesterday, removing all fish related stuff from my system. this works quite well except vs code doesn't seem to recognize the standard shell change.

I checked the settings where not specific shell is set. The error i'm getting when trying to launch the terminal window is: 

```The terminal shell path "/usr/local/bin/fish" does not exist```

My system shell:

```
> echo $SHELL
/bin/zsh
```

I tried it with everything updated and also without any extensions on insiders but it happens reproducably. Error message is the same on both.

**Comment by kbd** [comment]
Came here to see if anyone had a similar issue. All of a sudden vscode started defaulting to regular `sh` for the integrated terminal, even though my login shell is zsh.

It turns out it's only when I launch vscode from Alfred that vscode gets it wrong, even though the "Code" process is owned by my user, while other apps opened from Alfred, like the built in Terminal, use the correct shell.

It's fixed by specifying "terminal.integrated.shell.osx", but I don't know why that's necessary.

@helmi what is your login shell set to under System Preferences -> Users & Groups -> Advanced Options? ([This article](https://www.howtogeek.com/444596/how-to-change-the-default-shell-to-bash-in-macos-catalina/) shows how to get there, under the "From System Preferences" header. You have to "unlock" the settings with your password before the right click menu will even come up, fyi).

Here is my version info, fwiw:

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by Helmi** [comment]
@kbd not sure about the setting but I set the default shell to zsh via the command line and every other app recognizes it. But I‘m using Alfred too to launch so that might be a similarity. Will check setting the shell in vscode manually tomorrow and recheck if that helps. Not at the machine now anymore.

**Comment by kbd** [comment]
> But I‘m using Alfred too to launch so that might be a similarity.

Interesting. Try quitting vscode, launching from the Dock or Spotlight, and see if you have the same problem as when launched from Alfred.

My login shell is correctly set to zsh in that System Preferences pane (though I, too, set it from `chsh`) but I'm wondering if there could be a discrepancy.

**Comment by Tyriar** [comment]
This is where the shell detection stuff in VS Code is:

https://github.com/microsoft/vscode/blob/2524412d5c400f94f75e5e4098e8d65654837e58/src/vs/workbench/contrib/terminal/node/terminal.ts#L35-L51

So it should be picking up whatever is in `$SHELL`. Note that when VS Code launches it will do one of two things:

- If it was launched initially from a terminal, it will retain that environment
- If it was launched initially from the dock, it will fetch a "shell environment" by running `$SHELL ilc`

Maybe the latter is causing problems if you're fiddling with $SHELL inside your terminal start up scripts?

**Comment by kbd** [comment]
> Maybe the latter is causing problems if you're fiddling with $SHELL inside your terminal start up scripts?

I'm definitely not doing that.

FWIW, if I launch vscode from the terminal or from the dock, when I go to the the integrated terminal in vscode, I get:

```
$ echo $SHELL
/usr/local/bin/zsh
```

If I launch from Alfred, I get:

```
$ echo $SHELL
/bin/sh
```

even though I'm actually in zsh since I set "terminal.integrated.shell.osx" to zsh.

I read the code you linked, and all it's doing on Mac is pulling from `$SHELL`, and if `$SHELL` isn't set it just defaults to `sh`. Alfred must not be launching apps with the typical environment.  Apparently [the right way to find out the current user's login shell on Mac](https://stackoverflow.com/a/41553295) is with `dscl . -read ~/ UserShell`. That's effectively [how iTerm2 figures out the user's shell](https://github.com/gnachman/iTerm2/blob/5549cf6f68e0eeb2216726cfd3588bc0a2bf7a02/sources/iTermOpenDirectory.m#L17) (see the comment).

**Comment by Tyriar** [comment]
@kbd if `$SHELL` is set to `/usr/local/bin/zsh` it's something in your environment that's doing that, not VS Code. Setting `"terminal.integrated.shell.osx"` to `zsh` will override the auto-detected $SHELL value to `"zsh"`

**Comment by kbd** [comment]
> if $SHELL is set to /usr/local/bin/zsh it's something in your environment that's doing that, not VS Code. 

That's the correct path to my shell. In a freshly launched Terminal.app:

```shell
Last login: Mon Feb  3 12:40:36 on ttys013
~$ echo $SHELL
/usr/local/bin/zsh
~$ dscl . -read ~/ UserShell
UserShell: /usr/local/bin/zsh
```

Maybe I'm misunderstanding you.

> Setting "terminal.integrated.shell.osx" to zsh will override the auto-detected $SHELL value to "zsh"

I [have mine set](https://github.com/kbd/setup/blob/d49b07f254a60e596ddf07b0f8b05c046302a2a0/HOME/Library/Application%20Support/Code/User/settings.json#L21) to `/usr/local/bin/zsh`.

**Comment by jarvisuser90** [comment]
@kbd Did you ever find a solution? I’m running into a similar problem. All the sudden vs code integrated terminal is defaulting to `she when i launch from dock or terminal.

**Comment by Tyriar** [comment]
These sorts of problems are all related to user environment setups. To help you investigate this is roughly how it works:

- Launching VS Code will run `env` in a login shell using `$SHELL` to source the shared window environment
- `$SHELL` may change depending on your shell launch scripts
- You problem is likely in .bashrc, .bash_profile, .zprofile, etc. or a dependent script run by those.
