### ISSUE TITLE
Searched term replaced with current selection when toggling sidebar

### ISSUE THREAD

**Issue by MartialSeron** [microsoft/vscode#88745]
Issue Type: <b>Bug</b>

When toggling sidebar visibility <kbd>Ctrl</kbd>+<kbd>B</kbd> with "Search" tab activated, the searched term is replaced by current selection in a file no matter if there is an ongoing search already or not.

Steps to reproduce
1. Open a file
2. Select the "Search" tab on the sidebar <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F</kbd>
3. Make a search
4. Hide the sidebar <kbd>Ctrl</kbd>+<kbd>B</kbd>
5. In the opened file, highlight/select a word 
6. Show the side bar <kbd>Ctrl</kbd>+<kbd>B</kbd>
7. The searched term is now the selection you made in step 5

I don't know if it's a bug or not but this is an unwanted behavior.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.70GB (2.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|2.0.5
vscode-devdocs|akf|1.0.3
Bookmarks|ale|10.6.0
alignment|ann|0.3.0
swagger-viewer|Arj|2.2.2
sqlformatter|bre|0.0.7
gitignore|cod|0.6.0
sql-formatter|cym|1.0.2
vscode-eslint|dba|2.0.11
vscode-quick-select|dba|0.2.8
githistory|don|0.4.13
vscode-html-css|ecm|0.2.3
gc-excelviewer|Gra|2.1.32
randomeverything|hel|0.0.3
vscode-sshfs|Kel|1.16.3
sftp|lix|1.12.9
slugify-vscode|max|1.1.0
rainbow-csv|mec|1.4.0
gitignore|mic|1.0.1
xml-format|mik|1.0.2
dotenv|mik|1.0.1
vscode-oracle-format|mp|0.1.5
nunjucks|ron|0.2.3
vscode-nginx|sha|0.6.0
vscode-fileutils|sle|3.0.0
unique-window-colors|stu|1.0.51
bootstrap4-vscode|the|6.1.0
es-quotes|vil|0.2.6
vscode-redis|vit|1.2.0
gitblame|wad|3.0.1
highlight-bad-chars|wen|0.0.3

</details>

**Comment by gjsjohnmurray** [comment]
Related to #88686. It's apparently intentional that <kbd>Ctrl+Shift+F</kbd> takes the current selection and starts searching. It's even justifiable that this happens when I click on the magnifier in the Activity Bar while the Side Bar is hidden. But I agree it's odd that the same happens when the Side Bar is currently hidden and the generic <kbd>Ctrl+B</kbd> shortcut is used to reveal it. If I'd consciously wanted to search for my current selection I would have used <kbd>Ctrl+Shift+F</kbd> or clicked the magnifier. I used <kbd>Ctrl+B</kbd> to merely say that I'd like the Side Bar to reappear.

**Comment by gjsjohnmurray** [comment]
There's also a [setting](https://github.com/microsoft/vscode/issues/87217#issuecomment-567162827) to disable this.

**Comment by MartialSeron** [comment]
> If I'd consciously wanted to search for my current selection I would have used Ctrl+Shift+F or clicked the magnifier. I used Ctrl+B to merely say that I'd like the Side Bar to reappear.

That's exactly what I expected. It would be great to have this behavior.

**Comment by roblourens** [comment]
I can see it but we don't really distinguish between the ctrl+b case and the clicking on the search icon case right now. There was also this discussion. https://github.com/microsoft/vscode/issues/88160

**Comment by Finkleberry** [comment]
I find this new behavior very frustrating because I routinely use the search results to keep track of edits I'm making in multiple files. So of course the selected text will have changed when I click back on the search tab, and then the results are lost. And not having the Seed Search String setting checked means I have to replace what's in the clipboard to initiate a new search.

**Comment by andreamah** [comment]
We currently program it to update the text input when the search viewlet is focused. Since the setting is `seedOnFocus`, I would think that this is expected. 

Aside from that, there doesn't seem to be a simple way to update the text input when the sidebar icon for search is clicked (without detecting the focus right now, as we do). I get that it's annoying, but I don't think this particular case warrants extending a call from the viewpane to change what we listen to when we update the text input.
