### ISSUE TITLE
Local language support for Version 1.3

### ISSUE THREAD

**Issue by xyyjk** [Microsoft/vscode#8875]
- VSCode Version: 1.3
- OS Version: OS El Capitan 10.11.5

The new version features great, but ignoring the local language translation, if I wanted to go to adjust how to do that?

![](http://i.niupic.com/images/2016/07/08/ZRMehl.jpg)
![](http://i.niupic.com/images/2016/07/08/Rw4bv7.jpg)

**Comment by dbaeumer** [comment]
@xyyjk your translation process usually needs a week to translate new drops. This is why milestone builds might partly be in English (especially new features) since we don't want to hold a release until the translations into all language have finished. These strings should however be translated in the next milestone.

@sandy081 assigning to you to ensure the strings are localized in code correctly.

**Comment by dbaeumer** [comment]
@sandy081 if so, please close.

**Comment by sandy081** [comment]
Strings are localized correctly. Hence closing this.
