### ISSUE TITLE
VSCode cannot update nor connect to Extension Marketplace even though network is fine

### ISSUE THREAD

**Issue by bandzaw** [microsoft/vscode#88754]
- VSCode Version: 1.41.1
- OS Version: Ubuntu 18.04.3, x64

So, from within VSCode I cannot update it nor connect to the Extension Marketplace, instead an error message popup window informs me that the name cannot be resolved. My connection to the internet is fine otherwise, for example I can wget from VSCode's terminal without any problems.

Running VSCode using:
`code --verbose`  
then when clicking Checking For Updates, it results in:  
```
[main 2020-01-16T11:34:47.430Z] update#checkForUpdates, state =  idle  
[main 2020-01-16T11:34:47.430Z] update#setState checking for updates  
[main 2020-01-16T11:34:47.430Z] RequestService#request https://update.code.visualstudio.com/api/update/linux-x64/stable/24356a4ab774ea123f97692a0d34560d731115d7  
[main 2020-01-16T11:34:47.433Z] [Error: net::ERR_NAME_NOT_RESOLVED]  
[main 2020-01-16T11:34:47.433Z] update#setState idle
```

However, in my host/network environment that name can be resolved, e.g. when running wget in VSCode's own terminal, I get this output:
```
mm@xx:~/myp$ wget https://update.code.visualstudio.com/api/update/linux-x64/stable/24356a4ab774ea123f97692a0d34560d731115d7  
--2020-01-16 12:37:51--  https://update.code.visualstudio.com/api/update/linux-x64/stable/24356a4ab774ea123f97692a0d34560d731115d7  
Resolving host.srv.company.com (host.srv.company.com)... 123.456.78.9  
Connecting to host.srv.company.com (host.srv.company.com)|123.456.78.9|:8080... connected.  
Proxy request sent, awaiting response... 204 No Content  
2020-01-16 12:37:52 (0,00 B/s) - ‘24356a4ab774ea123f97692a0d34560d731115d7’ saved [0]
```

Ok, I get a 204, i.e. HTTP_NO_CONTENT, which I guess is fine and indicate that there are no updates. 
So my environment seems fine to me but still VSCode says it cannot resolve the name - why?

Of course, I tried all possible combinations of various proxy settings multiple times. I also erased almost everything cached in ~/.config/Code folders but now I'm out of ideas...

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)
