### ISSUE TITLE
[json] Ensure that the 'json'  basic extension runs as a UI extension

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#88835]
The json basic extension contributing the grammar currently runs as a workspace extension in the remote case. 

It runs as a workspace extension since it contributes a `jsonValidation` rule. This rule contribution should be moved to the json language features extension. So that the basic extension runs as a UI extension.

**Comment by aeschli** [comment]
Complicated issue, but I strongly feel this the wrong direction. We should not ask all users of the`jsonValidation` contribution point to move them to a 'rich' language extension. That diminishes the JSON editing experience and will lead to bugs when two extensions contribute schemas for the same file.

`jsonValidation` is intended to be part of the basic language configuration. Mostly relevant for languages that have JSON configuration files like Typescript and Python. Users should get JSON schema support without the need to install a rich language extension. I see that typescript has it as part of the typescript-language-features, but that only doesn't hurt as it is a built-in extension. We don't want users to force a to install a rich user extension. Also we don't want that every rich extension repeats the schema association, This will lead to duplicated and in the worst case contradicting schemas. If there are two schemas contributed for the same file, we combine them. (That's an important feature to allow extending schemas such as package.json)

Instead of shuffling around contributions, we need to add a new extension API 
`extensions.getContributions(contributionName): Contribution[]`
This will give extensions access to all contribution point, regardless of ui and workspace location.
Contribution will contain a extension location, so the FS provider can be used to load referenced resources.

With that API:
- extensions that provide `jsonValidation` no longer need to be a `workbench` extension as now we can use the new API to get all jsonValidation contributions
- the new API also allows to finding all contributed grammars, regardless whether in a UI a or workspace extension.

Note:
- while it's a good thing, there's no real necessity nor guarantee that all grammars come from a UI extension. We have various ways of influencing where a extension is located (e.g. user settings).
- the use case of queering all grammars to instantiate them on the EH should not be propagated by us. We prefer language servers for preciseness and no heavy work on the EH for long lines.
