### ISSUE TITLE
Editor icons not aligned in this case

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#88843]
Saw this from my new macOS machine today in insiders opening a markdown file:

![image](https://user-images.githubusercontent.com/900690/72614987-e5382a00-3933-11ea-9b70-508e4287b612.png)

**Comment by bpasero** [comment]
I think I would expect the "Open to Side" icon to be centered between the 2 lines I drew.

**Comment by misolori** [comment]
This is actually intentional, the split icons are the ones that have to be offset by 1px so stay on the grid and avoid pixelation. Our icons are 16x16 with a 1px gap:

![image](https://user-images.githubusercontent.com/35271042/72926869-04ef9980-3d0a-11ea-9c8f-b68f9f31f1eb.png)

And because the split icon appears next to others that are similar (like the preview icon), we can't shift it down 1px as it will then throw off the others. We can maybe play around with moving the "go to" icon so it matches the split icons but that would place it off-center.

**Comment by misolori** [comment]
Closing as-designed since this is intentionally off-grid by 1px as mentioned above.
