### ISSUE TITLE
Class explorer for JavaScript

### ISSUE THREAD

**Issue by Legends** [microsoft/vscode#88867]
I have a JavaScript class with about 50 methods.
Now I don't want to use `ctrl+f` and search for the method or whatever method.

I tried outline, but there just shows up the class name and not its methods (properties would be nice too!)

Also outline should be sorted... a..b...c
![image](https://user-images.githubusercontent.com/966368/72632969-c055ae00-3957-11ea-81ce-045faed40142.png)

**Comment by IllusionMH** [comment]
What version are you using?

VSCode Insiders with TS 3.8 (have nested methods, alphabetical sort etc.)
![image](https://user-images.githubusercontent.com/1312662/72635111-b1292d00-3964-11ea-9228-94a67821ee8b.png)
Same for TS3.7 with only difference for private prop.

And what are you using for outline? Because built-in outline view doesn't have refresh button.

**Comment by Legends** [comment]
@IllusionMH  Aaaa thanks.

A long time ago I installed this outline extension (I thought it was the default one), because there was none by default at the time I needed it.
