### ISSUE TITLE
VS code search functionality freezes the screen

### ISSUE THREAD

**Issue by semarche-kaltura** [microsoft/vscode#88865]
Whenever I try to search anything, vs code gets stuck in the middle of the search and the only option is a laptop restart. It is extremely annoying, I'm using:
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Similar bug-report was closed by inactivity but issue hasn't fixed.
https://github.com/microsoft/vscode/issues/78611

Steps to reproduce:
1. Take a huge JS project and make a search thru the project (Use Exclude Settings and Ignore Files should be ON)
2. Leave project opened for some time 2-4 hours
3. Clean current search and try to make one more searching

Actual result:
VS code stuck and in ~10 seconds laptop stops responsible and only cursor can move, fans starts working on maximum, CPU temp grows quickly.
Only manual reboot of laptop helps.

Reproduced on MacBook Pro "15 2018

**Comment by JtMotoX** [comment]
I am also having the same issue and it is very frustrating.

- Version: 1.41.1
- OS Version: macOS Mojave (10.14.6)
- System: MacBook Pro (15-inch, 2016)

## Description

System crashes/locks-up when performing search from search pane.
- Network connectivity goes down.
- Not pingable.
- Not reachable via ssh.
- Does not respond to mouse or keyboard input.

## Steps to Reproduce

1. Navigate to a fairly large directory tree or project
1. Open the search pane (CTRL+Shift+F / Command+Shift+F)
1. Type in something to search.
1. Within 5 seconds, my Mac completely locks up and the fan goes to 100%.  I am then forced to hold down the power button.

**Comment by JtMotoX** [comment]
I removed my `~/.vscode` and `~/Library/Application\ Support/Code` directories and launched a clean instance of VSCode.  I opened the directory of an ansible playbook project and tried to search for "get kubectl binary" but before I could even finish typing that, my system completely locked up and the fan ramped up to 100%.  Took a pic of it with my phone (since I couldn't take a screenshot) before holding down the power button.

![IMG_6846](https://user-images.githubusercontent.com/7191259/73036302-f5eb1300-3dff-11ea-9283-c2ee02565234.jpg)

**Comment by roblourens** [comment]
Hi, there are a couple open issues around this, such as https://github.com/microsoft/vscode/issues/88385. I don't have a solution yet but some reports say that disabling `search.searchOnType` fixes it.
