### ISSUE TITLE
Can't Install VSCode Marketplace Extensions

### ISSUE THREAD

**Issue by jurildd** [microsoft/vscode#88946]
Version: 1.41.1
Date: 2020-01-20
OS: Ubuntu 18.04

Steps to reproduce:
1. Choose any extension from the extensions tab
2. Click "Install" button

Expected output:
Extension installs and requires a reload if necessary

Actual output:
Error messages as seen below:

For the in-client extension installation, I'm getting this error:
`Failed to install 'ms-python.python'.`

Upon checking the developer tools, I get this:
![Screenshot from 2020-01-20 11-48-24](https://user-images.githubusercontent.com/22167897/72697400-d8594780-3b7a-11ea-8984-efea6ee43561.png)

If I try to manually install an extension, this is what I get:
![Screenshot from 2020-01-20 11-50-15](https://user-images.githubusercontent.com/22167897/72697483-0e96c700-3b7b-11ea-9d5c-1c50435be54b.png)

For what it's worth, I've tried changing my DNS to 8.8.8.8 and 8.8.4.4 but it still did not work.

If you need any more details, please do tell so I can provide them. Thank you.

**Comment by jurildd** [comment]
bump :/

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by jurildd** [comment]
I'm getting a 200 on the network tab when trying to install extensions. I'm also pretty sure that it isn't a DNS issue because the [link you just sent](https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default) works fine on my end.

> Help -> Toggle Developer Tools -> Console

Already posted above (in my initial post)

> View -> Command Pallette... -> Toggle Shared Process -> Console

![Screenshot from 2020-01-22 09-53-57](https://user-images.githubusercontent.com/22167897/72858892-28f8ae00-3cfd-11ea-8f90-02aaae8a9ec0.png)

> View -> Open View... -> Log(Shared)

![Screenshot from 2020-01-22 09-57-28](https://user-images.githubusercontent.com/22167897/72859091-a3293280-3cfd-11ea-9ff9-a62fad277c11.png)


> View -> Open View... -> Log (Window)

![Screenshot from 2020-01-22 09-56-22](https://user-images.githubusercontent.com/22167897/72859035-855bcd80-3cfd-11ea-9bde-7642e6f33c10.png)

@sandy081

**Comment by sandy081** [comment]
Looks like there are permission issue with your extensions directory. Can you please check that.

**Comment by jurildd** [comment]
How can I check it?

**Comment by jurildd** [comment]
On further checking, it is indeed a problem with the extensions directory. For some reason the permissions for the vscode directory weren't set to me by default. Closing this.
