### ISSUE TITLE
splitting the terminal then closing changes cursor position

### ISSUE THREAD

**Issue by xq114** [microsoft/vscode#88949]
VS code version: 1.41.1 (user setup)
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. open the terminal
![image](https://user-images.githubusercontent.com/42310255/72702464-c0d78a00-3b8d-11ea-9261-e690757fb434.png)

2. execute a command with long output
the number of output lines should be more than that of a screen.
![image](https://user-images.githubusercontent.com/42310255/72702542-0300cb80-3b8e-11ea-9575-05a464a01c1b.png)

3. split the terminal
![image](https://user-images.githubusercontent.com/42310255/72702613-507d3880-3b8e-11ea-8ed5-019b8fea3b6a.png)

4. close the terminal just opened and input something
![image](https://user-images.githubusercontent.com/42310255/72703090-9f779d80-3b8f-11ea-9492-bd7c3bf0a15e.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Tyriar** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

Thanks for understanding.
