### ISSUE TITLE
Random freezes when debugging code-oss using VS Code

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#89023]
I started getting many freezes while debugging code-oss (F5) from our sources, using VS Code. Never saw this before I went on vacation (Dec 10) and I hit this at least 5x per day now. Could be related to Electron 7 update.

The only way I've found to get out of the situation is to run `killall code-oss` on a terminal twice. The first call is a no-op.

I'm on Linux btw. I haven't found reliable repro steps.

cc @JacksonKearl @aeschli @connor4312 @bpasero

**Comment by paulobichara** [comment]
I'm facing this issue not only debugging but randomly, using VSCode.
Also saw other issue reporting the same behavior when using the embedded terminal.
Whole machine freezes. I'm also on Linux.

At this point, it's impossible to use VSCode. I'm temporarily moving to WebStorm.
Unfortunately, I'm not able to provide steps to reproduce this as it happens randomly.

**Comment by JacksonKearl** [comment]
Reliable repro for me on MacOS Mojave:

1. In Insiders, open vscode repo and run "Launch VS Code" (build step running somewhere in background)
2. In the spawned window, navigate to the `vscode` repo.
3. Reload a couple times. For me, the window freezes on the second reload very reliably. 

I haven't been able to repro on any workspace besides `vscode`. I've tried empty workspaces, small, and chromium. One thing I have noticed is that if I reload in some other workspace a few times, then open `vscode`, it will either freeze instantly on open, or after only a single reload instead of the usual two.

**Comment by bpasero** [comment]
Given this, should we remove the `electron-7-update` label to not confuse this with a Electron 7 related issue?

**Comment by joaomoreno** [comment]
@bpasero I haven't seen this at all since we reverted back to Electron 6.

**Comment by askvortsov1** [comment]
Not sure if changes have been pushed, but this has been a consistent issue for me across both code and code insiders, installed via snap.

**Comment by bpasero** [comment]
@JacksonKearl can you give more instructions what you do that leads to the freeze? Are you using `pwa-debug`?

@joaomoreno curious if you also see these freezes if you are NOT using VSCode from Snap.

**Comment by joaomoreno** [comment]
@bpasero I actually haven't had a single freeze since we moved forward to 7 again. Also, not using new debugger.

**Comment by bpasero** [comment]
Ok then I suggest we wait for feedback from @JacksonKearl and then close this one.

**Comment by JacksonKearl** [comment]
My previous repro no longer repros for me. I'll open a new issue if I get caught again.
