### ISSUE TITLE
Sync setup improve wording

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#89047]
![image](https://user-images.githubusercontent.com/2193314/72836151-eec9d680-3c40-11ea-87ae-e8970b7e51e1.png)

Suggestion: Turn off sync on all your devices and clear the data from the cloud.
(It would be nicer if it was 1 line on standard scale setup though)

Also "and more" is very ambiguous, why not list _exactly_ what is not synced?

![image](https://user-images.githubusercontent.com/2193314/72836288-22a4fc00-3c41-11ea-9566-e9934f3642e5.png)

The grammar for the description(?) isn't the best but it doesn't seem to be necessary at all as it's just a combination of the title (Turn on sync) and the text box (Choose what to sync). I suggest removing it and change the placeholder to something like "Choose what to sync across your devices"

The display language only bit is weird because of the casing and why it's called out at all, if display language is the only thing it should say "[x] Display language"

![image](https://user-images.githubusercontent.com/2193314/72836854-474da380-3c42-11ea-8c61-65cb893b0433.png)

Show sync conflicts and Turn off sync isn't capitalized like everything else

**Comment by sandy081** [comment]
Thanks for the feedback

- [x] Turn off sync on all your devices and clear the data from the cloud.
- [x] and more" is very ambiguous, why not list exactly what is not synced - Changed to `Your settings, keybindings, extensions and UI State will no longer be synced.`. 
- [x] Removed the description from Turn On sync picker and left everything else same. This picker is not part of the start up experience as for the first time user see sign in picker. So I do not think it is needed to be descriptive for this picker.
- [ ] Display language is called out because to let user know what is included in UI state - https://github.com/microsoft/vscode/issues/88274
- [x] Show sync conflicts and Turn off sync isn't capitalized like everything else
