### ISSUE TITLE
Tab does not insert tab in debug console

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#89073]
Version: 1.42.0-insider
Commit: 68615717819b3731705d92ec06b52edd47665291
Date: 2020-01-22T05:26:38.760Z
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

---

- Start debug session
- Press `tab`
- Focus is lost

Also, if I do a snippet, such as `function`, I would expect tab to go to the next completion point, but it doesn't do that.

**Comment by isidorn** [comment]
Yeah tab always moves focus due to accessibility reasons.
Most integred editors in our repository do the same thing (scm, extensions input).
I would dislike that the user has to switch Tab key moves focus to move the focus out of the debug input.

For now keeping it open for discussion purposes and we can change this in the future.
