### ISSUE TITLE
[Regression 1.3] Command palette no longer mouse-accessible

### ISSUE THREAD

**Issue by lucideer** [Microsoft/vscode#8913]
- VSCode Version: 1.3
- OS Version: various

Steps to Reproduce:

1. Click the filename of the currently open file (at the top of the editor pane)
2. Nothing happens (previously the Command Palette opened)

This is related to my previously opened Feature Request: #8576 in which I requested that this functionality would also work on a blank screen (with no editor open). However, now with the 1.3 update it appears the functionality has disappeared completely in all contexts.

_Note: I have `"workbench.editor.showTabs"` set to `false` since 1.3 to match the (far superior) pre-1.3 functionality._

**Comment by bpasero** [comment]
I took it out because we also don't have it when tabs are enabled. Maybe we should open this to the context menu on tabs and the file name?

**Comment by lucideer** [comment]
Just to give a bit more context: the primary use case here is switching between files in the history with the mouse (both for this, and also for #8576)

- Click top-left
- See file history dropdown list
- Click file in list

There's no need to type, so no need to move from mouse to keyboard. So losing this (i.e. having to switch to keyboard to trigger a shortcut to open the dropdown) is a major usability regression for mouse use.

This is possibly mitigated by using tabs, but I think the previous paradigm of history navigation (with this dropdown feature available via mouse) was far more usable than the new tabbed interface.

Re-introducing any way to open the history dropdown with a single mouseclick, without keyboard usage, would be great.

**Comment by bgashler1** [comment]
Thanks for the feedback.

@bpasero we could talk more about this at UX sync, but just as an initial idea, could we distinguish between one click and a double click on just the file name (for tabs-disabled only)?  If so, a single click could open the recent files list, and we could still use the double click to "Keep Editor."  I think it's worth adding back myself, because I actually remember using it myself before we introduced tabs.

**Comment by bpasero** [comment]
That is up for discussion because initially we wanted to make the file name area rich and clickable to do some actions on it when tabs are disabled. however, this did not make it into the release and we might need to revisit what to do then. note that this does not help in the case where tabs are enabled.

**Comment by bgashler1** [comment]
**UX Meeting Summary:**
We will add this functionality back for tabs-disabled, as it was before tabs were introduced.
