### ISSUE TITLE
Source Control select default setting show/hide untracked changes tab

### ISSUE THREAD

**Issue by DanielHammerin** [microsoft/vscode#89145]
I'd like to request the ability to set a default value for whether the "untracked changes"-tab is expanded or minimized. 

As it is now, the tab is always open to show the files. I'd like to be able to change my default to minimized to reduce clutter and noise when looking at the changes I actually care about.

**Comment by joaomoreno** [comment]
We could simply remember the collapse state and preserve it across sessions, would that work? I'm not too keen on adding a setting for it.

**Comment by DanielHammerin** [comment]
After reading your suggestion I realize that it is exactly what I actually want. So much better.
Excellent!

**Comment by hypercubestart** [comment]
This sounds like a great idea! Can I work on this?

**Comment by jeanp413** [comment]
@hypercubestart I did a fix for this yesterday and was about to summit a PR. Sorry for not commenting about it beforehand

**Comment by AAraKKe** [comment]
This was open on January, is there any plan to merge the PR for the upcoming versions? I have like aleph-0 untracked files I do not want to delete because I do not know if I am going to need some of them in the future and I do not want to commit because they are only interesting for me. Being able to collapse the tab is great but 99% of the space of the sidebar is untracked files and every time I open it I think: when did I modify that many files? oh wait... Find the untracked changes collapse bar (there is little discussion about how invisible this can be depending on your theme xD) and collapse it.

This is such a small thing that would make a great difference.

**Comment by Trass3r** [comment]
Yes hasn't even been reviewed yet 😕
@joaomoreno maybe?

**Comment by AAraKKe** [comment]
So, does this mean we are not getting this? It is in the backlog for November but the PR is closed 🤔

**Comment by jeanp413** [comment]
The PR got merged https://github.com/microsoft/vscode/pull/89313

**Comment by AAraKKe** [comment]
> The PR got merged #89313

Great, I am unable to properly navigate GitHub on the phone it seems xD

Thanks a lot!
