### ISSUE TITLE
Extra new line at the end of files

### ISSUE THREAD

**Issue by estensen** [microsoft/vscode#89165]
- VSCode Version: 1.41.1
- OS Version: Darwin x64 19.2.0

Steps to Reproduce:

1. `$ printf "\n" >> file`
2. Open empty in vscode
3. Observe that there are two empty lines, not one
4. Double check that file contains one empty line `$ cat file`

Does this issue occur when all extensions are disabled?: Yes

**Comment by gjsjohnmurray** [comment]
What is your `editor.renderFinalNewline` setting? Maybe toggle it?

**Comment by estensen** [comment]
`editor.renderFinalNewline=true`
Setting it to false removes the last line number, but the line is still there.

This is confusing to me, especially when you work with files where you don't want a new line at the end of your file.

**Comment by rebornix** [comment]
@estensen thanks for your feedback

> Setting it to false removes the last line number, but the line is still there.

The line is there as it contains a line break, with the second line in the editor you can click on it and insert content after the line break directly. If you run `printf "a" >> a.txt` and then open the text file in VS Code, you will see that VS Code only renders one line in the editor.

**Comment by estensen** [comment]
I still disagree that this is a feature and not a bug. It is different behavior from other editors and confuses end-users.
It is very normal to add a blank line at the end of files commited to git and those will be displayed as double-lines in VSCode.

**Comment by gjsjohnmurray** [comment]
@estensen maybe what @glen-84 proposed in a screenshot in [this comment](https://github.com/microsoft/vscode/issues/1027#issuecomment-473514394) on another issue would help you.

As I understand that proposal, an N-line file whose line ends with a line terminator could optionally display a right-pointing arrow glyph in the line number region of the (N+1)th line that the editor provides instead of the N+1 (when`editor.renderFinalNewline=true`) or blank (when `editor.renderFinalNewline=false`) that we can currently achieve.

**Comment by estensen** [comment]
It is the same issue as the one from the issue you linked (did not find it while searching). But nothing there really helps solving this issue, except that it shows that a lot of people thinks this is an issue.
