### ISSUE TITLE
Broken syntax highlighting overall

### ISSUE THREAD

**Issue by markovicdenis** [microsoft/vscode#89227]
Issue Type: <b>Bug</b>

1. Open any file (ts, js, css...)
2. No syntax highlighting

<img width="598" alt="Screenshot 2020-01-24 at 14 51 45" src="https://user-images.githubusercontent.com/6482823/73074257-7883d900-3eb9-11ea-973b-d81f14f58fb7.png">

<details>
<summary>Developer tools console error</summary>
ERR Missing color in color map - #000000: Error: Missing color in color map - #000000
    at ColorMap.getId (/Users/Shared/Apps/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:357:19)
    at resolveParsedThemeRules (/Users/Shared/Apps/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:323:81)
    at Function.Theme.createFromParsedTheme (/Users/Shared/Apps/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:381:16)
    at Function.Theme.createFromRawTheme (/Users/Shared/Apps/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:378:21)
    at Registry.setTheme (/Users/Shared/Apps/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:3663:51)
    at o.setTheme (file:///Users/Shared/Apps/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4040:323)
    at C._doUpdateTheme (file:///Users/Shared/Apps/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4925:634)
    at C._doUpdateTheme (file:///Users/Shared/Apps/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4932:888)
    at C._updateTheme (file:///Users/Shared/Apps/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4925:545)
    at C._getOrCreateGrammarFactory (file:///Users/Shared/Apps/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4924:277)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async file:///Users/Shared/Apps/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:4924:625
</details>

VS Code version: Code - Insiders 1.42.0-insider (f3dbcea32a6b52ce819dc863e778fb8517357f61, 2020-01-24T05:33:35.045Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Raydir** [comment]
same here. may be same issue as https://github.com/microsoft/vscode/issues/89212

**Comment by risenforces** [comment]
I'm experiencing the same issue

**Comment by aeschli** [comment]
Anything in the dev console (`Developer: Toggle Developer Tools`) or the logs (`Developer: Show Logs...` - `Window`)?
Is it with every theme? Any theme customisation in the settings?

**Comment by Raydir** [comment]
@aeschli  does that help?

TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///c%3A/Users/romanvonwil.OPACC/.vscode-insiders/extensions/redhat.vscode-yaml-0.6.1/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:45
o @ TMGrammarFactory.ts:73
_getOrCreateGrammarFactory @ abstractTextMateService.ts:194
async function (async)
_getOrCreateGrammarFactory @ abstractTextMateService.ts:187
(anonymous) @ abstractTextMateService.ts:219
_registerDefinitionIfAvailable @ abstractTextMateService.ts:217
(anonymous) @ abstractTextMateService.ts:143
_handle @ extensionsRegistry.ts:142
acceptUsers @ extensionsRegistry.ts:133
_handleExtensionPoint @ abstractExtensionService.ts:382
_doHandleExtensionPoints @ abstractExtensionService.ts:328
_rehandleExtensionPoints @ extensionService.ts:242
_deltaExtensions @ extensionService.ts:229
async function (async)
_deltaExtensions @ extensionService.ts:186
_handleDeltaExtensions @ extensionService.ts:166
(anonymous) @ extensionService.ts:118
fire @ event.ts:582
setEnablement @ extensionEnablementService.ts:86
async function (async)
setEnablement @ extensionEnablementService.ts:83
doSetEnablement @ extensionsWorkbenchService.ts:993
checkAndSetEnablement @ extensionsWorkbenchService.ts:920
promptAndSetEnablement @ extensionsWorkbenchService.ts:899
setEnablement @ extensionsWorkbenchService.ts:812
run @ extensionsActions.ts:871
runAction @ actions.ts:198
run @ actions.ts:190
runAction @ contextmenuService.ts:196
click @ contextmenuService.ts:170
l @ contextmenu.ts:19
onceWrapper @ events.js:288
emit @ events.js:200
onMessage @ C:\Program Files\Microsoft VS Code Insiders\resources\electron.asar\renderer\init.js:48
webviewElement.ts:241 [Embedded Page] Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'nonce-b50c1a9b-736d-4018-83d2-f1b68c7f2199'". Either the 'unsafe-inline' keyword, a hash ('sha256-nMxMqdZhkHxz5vAuW/PAoLvECzzsmeAxD/BNwG15HuA='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by Raydir** [comment]
the last one occures in webviewElement.ts:241

> [Embedded Page] Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'nonce-b50c1a9b-736d-4018-83d2-f1b68c7f2199'". Either the 'unsafe-inline' keyword, a hash ('sha256-nMxMqdZhkHxz5vAuW/PAoLvECzzsmeAxD/BNwG15HuA='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by EddyVinck** [comment]
Same here! My `.js` files are messed up.

**Comment by markovicdenis** [comment]
> Anything in the dev console (`Developer: Toggle Developer Tools`) or the logs (`Developer: Show Logs...` - `Window`)?
> Is it with every theme? Any theme customisation in the settings?

In my case it happens with every theme, and this is the console error:

<img width="1449" alt="Screenshot 2020-01-27 at 10 17 24" src="https://user-images.githubusercontent.com/6482823/73162550-4f985980-40ee-11ea-8cdd-914b5598d87a.png">

(already posted the text version of the error in the first post)

**Comment by bbqsrc** [comment]
Suddenly hit by this, though I have nothing in the logs.

**Comment by markovicdenis** [comment]
Seems to be fixed in latest insiders build.

**Comment by Raydir** [comment]
working for me again also.

**Comment by EddyVinck** [comment]
My imports are still kind of messed up 
![image](https://user-images.githubusercontent.com/23434753/73187491-c733ac00-4121-11ea-8587-dd6ae20594ea.png)

**Comment by aeschli** [comment]
@EddyVinck Can you open the inspect hover `Developer: Inspect Editor Tokens and Scope` to see where the color come from.

**Comment by bbqsrc** [comment]
Fixed for me too.

**Comment by EddyVinck** [comment]
@aeschli 

```js
import React, { useState } from "react"; // namespace, function
import { Text, Button } from "@deity/falcon-ui"; // variable, variable
import { Formik, Form, Field, ErrorMessage } from "formik"; // class, variable, variable, variable 
import * as Yup from "yup"; // variable
import { NewsletterCheckbox } from "./Newsletter/Newsletter"; // variable
import { FormStyles } from "./index.js"; // variable
import { SubscribeMutation } from "./Newsletter/MailChimp/MailChimpMutation"; // class
import classNames from "classnames"; // variable
import PrivacyMessage from "./PrivacyMessage"; // variable
import { MandrillMutation } from "../graphql/MandrillMutation"; // class
import { FormSubmitStatus } from "./FormSubmitStatus"; // variable
import { withRouter } from "react-router-dom"; // function
```

Also, it is worth noting that they all go turn pink when I'm typing. Before the update they were always pink, so maybe something is overriding them once I'm done typing. Some things marked as `variable` are also arrow functions like `const PrivacyMessage = () => {/* stuff */}`

![image](https://user-images.githubusercontent.com/23434753/73190786-cbae9380-4126-11ea-9f54-90772d6147c3.png)

![image](https://user-images.githubusercontent.com/23434753/73190755-bfc2d180-4126-11ea-88de-dac31bced4da.png)

![image](https://user-images.githubusercontent.com/23434753/73190813-d79a5580-4126-11ea-9906-a000c027ae9d.png)

**Comment by risenforces** [comment]
@EddyVinck Looks like semantic highlighting.

**Comment by markovicdenis** [comment]
@EddyVinck yep, this is probably semantic highlighting. You can disable it in your VSC settings:

<img width="543" alt="Screenshot 2020-01-28 at 18 59 35" src="https://user-images.githubusercontent.com/6482823/73291452-7777e200-4200-11ea-9b49-147a1013e42b.png">


Closing since the original issue is resolved.
