### ISSUE TITLE
Font ligatures doesn't work well with Hangul

### ISSUE THREAD

**Issue by dasolyn** [microsoft/vscode#89271]
- VSCode Version: 1.41.1
- OS Version: Windows 10 1903 (18362.592)

Steps to Reproduce:

1. Install 'D2Coding Ligature' font. (https://github.com/naver/d2codingfont/releases/tag/VER1.3.2) 
2. Turn on font ligatures and input texts with hangul and latin.

Does this issue occur when all extensions are disabled?: Yes

![Turn on font ligatures in setting.json.](https://user-images.githubusercontent.com/6274747/73122471-a99eff00-3fc8-11ea-8ce7-4a2df8d85614.png)

![Perhaps it cause problem when Hangul came before Latin alphabet.](https://user-images.githubusercontent.com/6274747/73122569-e7505780-3fc9-11ea-815a-f171db1c95b0.png)

**Comment by alexdima** [comment]
@dasolyn I could not copy paste your exact characters, but I tried with "Fira Code" and could reproduce.

VS Code is built with Electron, which is built with Chromium. The editor uses Chromium for font rendering. I have created a standalone example at https://jsfiddle.net/y28ewdvm/ and I tried it up in Chrome / new MS Edge:

![image](https://user-images.githubusercontent.com/5047891/73215666-cec07880-4154-11ea-83f0-27d1a6236511.png)

I also tried in Firefox:

![image](https://user-images.githubusercontent.com/5047891/73215690-dc75fe00-4154-11ea-92ee-a728193ee219.png)

In this case, both rendering engines render things in the same way, so I believe this might be intentional. I am sorry, but I am not an expert in this matter and cannot really explain why this is happening. My recommendation is to search for or create an issue on the Chromium issue tracker and find out if this is intentional or not, but IMHO it looks intentional since 2 rendering engines agree.

**Comment by dasolyn** [comment]
@alexdima I confirmed your example occurs issue in D2Coding Ligature fonts, too. It seems there is problem if a ligature comes after Hangul. And a logic used by web renderer occurs the problem. (Notepad works well) I'll create an issue on Chromium and Firefox to resolve this issue. Thanks for your works.
