### ISSUE TITLE
Expose in the API whether Zen Mode is enabled

### ISSUE THREAD

**Issue by sketchbuch** [microsoft/vscode#89278]
I think it would be great if extension developers had a way in the API to find out if Zen Mode is currently enabled, or add an event that fires when Zen Mode is toggled.

**Comment by usernamehw** [comment]
Might be related: #10471

**Comment by sketchbuch** [comment]
I'm not sue if it is related, but it looks interesting too. Would the 10471 give extensions acess to check if VSC wen Mode?

**Comment by isidorn** [comment]
This is a fair feature request. HOwever we do not currently have it on the plan, thus assignig to the backlog.

**Comment by hediet** [comment]
@isidorn Are you open for a PR that implements an undocumented `getContext` command similar to the already existing command `setContext`?
Is there something where the community can help to make such an API reality?

**Comment by isidorn** [comment]
@hediet this is unrelated to this issue. I believe there is already a feature request for the `getContext` to be added to the API. You can check open issues, and if there is not you can file a new one. Thanks

**Comment by hediet** [comment]
@isidorn as far as I understood, an API for `getContext` would allow to query whether the Zen Mode is active as @usernamehw suggested. I wanted to add another usecase of why such a `getContext` API might be reasonable.

#10471 is in discussion since 2016 with no real progress. My own issue regarding a setContext API was flagged as duplicate about a year ago (#77630). I thought this issue could add some momentum to it.

**Comment by isidorn** [comment]
Got it. This issue is a small subset of that, and I would tackle it independtly (if we ever decide to do it). Thanks
