### ISSUE TITLE
Empty custom view filter generates spurious error

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vscode#89295]
Use the built in filter (set to filter, not find) in a custom tree view and enter text so that the filter becomes empty, i.e. no items shown with the message "No elements found" being displayed, then press Enter, the following popup is displayed:
![image](https://user-images.githubusercontent.com/376658/73136498-35a33c00-4046-11ea-9d7c-dd77454ee325.png)

This is misleading as the extension providing the tree view hasn't done anything wrong.

If you try the same thing in the explorer view it actually tries to show an item that should be filtered out at the same time as the "No elements found"::
![image](https://user-images.githubusercontent.com/376658/73136479-fe348f80-4045-11ea-9057-69977f4af788.png)

**Comment by alexr00** [comment]
@joaomoreno since both the file explorer and custom views see this it might be best to fix it in the tree. The throw is coming from here
https://github.com/microsoft/vscode/blob/be9fd1ffc0565f06b6193ed3806f204cfd25b634/src/vs/base/browser/ui/list/listWidget.ts#L1606-L1614
It looks like the tree still thinks that at least one element has focus.
