### ISSUE TITLE
Error Installing extensions after DNS change...

### ISSUE THREAD

**Issue by haywood-d-johnson** [microsoft/vscode#89315]
- VSCode Version: Version 1.41.1
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Change DNS to 1.1.1.1; extension request return 200 but still cannot access extensions
2. Windows Home, no gpedit.msc to allow VS Code

Does this issue occur when all extensions are disabled?: Yes

![Screenshot (1)](https://user-images.githubusercontent.com/9458780/73150658-0237d000-408d-11ea-9802-a73ad8894749.png)

I just need a little help. I have switched to 1.1.1.1, disabled the firewall temporarily, tried without extensions, but still get the same results. I have exhausted all other fixes from threads here and everywhere else, could there be anything I missed?

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)
