### ISSUE TITLE
Refactor preview should confirm when dropping another refactor preview

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#89416]
Testing https://github.com/microsoft/vscode/issues/89331

1. Run refactor preview
2. Run it again

The second overwrites the first and drops whatever checkbox state I may have spend time setting. Should we have a confirmation dialog when we're about to drop a refactor preview?

**Comment by jrieken** [comment]
Yeah, make sense. Tho, it's also tricky because applying the first refactoring is very likely invalidating the changes that have already been computed for the second refactoring, e.g if applied inside the same file... That might be be an artificial case tho and in the real world an confirmation might be best, maybe one which is either or, e.g either accept the old and cancel the new, or cancel the old and continue with the new

**Comment by jrieken** [comment]
That's what you now get. I didn't do the 'I feel lucky' option which is apply preview refactoring and also this one, it's now either or

<img width="566" alt="image" src="https://user-images.githubusercontent.com/1794099/74145902-2e605e80-4c00-11ea-9f31-f49b4fa4ce7b.png">

**Comment by joaomoreno** [comment]
The grammar feels weird... maybe

```
Press `Continue` to discard the previous refactoring and continue with the current refactoring.
```

**Comment by jrieken** [comment]
check - lets go with that
