### ISSUE TITLE
double typing in html tags

### ISSUE THREAD

**Issue by andreypost** [microsoft/vscode#89425]
Issue Type: <b>Bug</b>

When i copy paste classes in some tags, it puts class in first & second closed tag also.
It happans also when just typing.
How can l remove or deactivate this.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
/duplicate

This is a new 1.41 feature called HTML mirror cursors. See https://code.visualstudio.com/updates/v1_41#_html-mirror-cursor for details, including how to turn it off. Several issues with this feature have been reported since its release. A filter of label:mirror-cursor will find many of them, and some should be resolved in the upcoming 1.42,
