### ISSUE TITLE
some discrepancies with untitled file names derived from first line contents

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#89453]
Refs: #89274

on macOS:

- create a new untitled file and enter `foo/bar` into the first line 

Observe: the editor tabs says "foo/bar"

- save the file (cmd-S)

Observe: the file name in the save dialog says only "bar"

---

- create a new untitled file and enter `foo:bar` into the first line 

Observe: the editor tabs says "foo:bar"

- save the file (cmd-S)

Observe: the file name in the save dialog says "foo/bar"

**Comment by bpasero** [comment]
I think this is not something we can easily change as the platform has certain reserved characters that cannot be used in a file name. Since an untitled file may never be saved and always kept open, I do not think that reflecting these OS-filesystem quirks is something the untitled editor should do too.
