### ISSUE TITLE
Debug batch shows 2 when only 1 target is being debugged

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#89475]
#89393 

Debugging 1 target:
![image](https://user-images.githubusercontent.com/9205389/73270008-2d7e0480-41de-11ea-8e51-1add3f10f63e.png)

'Stop' makes the batch disappear (expected).

**Comment by connor4312** [comment]
Thanks for the issue--this one is "as designed".

The new debugger has more intrinsic support for multi-target debugging, but it's also naive in some ways. For instance, one thing you can do is spawn a native binary that launches Node.js child processes. Because of the way we attach the debugger, we can actually track these spawned processes, and they should be children of the same debugging tree. But we also will not be aware of the parent native binary, the debugger just sees that eventually N child processes come in without any other Node.js parent debug process. For this reason, we have everything for a debug session homed under a 'virtual' top level session.
