### ISSUE TITLE
Restart Frame icon overlaps with stacktrace

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#89472]
#89393

When there is no line:column indicator:
![image](https://user-images.githubusercontent.com/9205389/73269809-cc563100-41dd-11ea-947e-d049b668bf5d.png)

**Comment by isidorn** [comment]
To work around the screen cheese in the most simple way I decided to not render the action on hover when the line number is not present. It is still possible to trigger ti via context menu. And in practice I think users will not notice this since the stack frames without line numbers are not really targets for restarting.

**Comment by roblourens** [comment]
I think the line number was probably sent (I think it always is?) but isn't being shown due to running out of room. I can still repro this in that case, if I just make the callstack narrow enough to hide the numbers:

![image](https://user-images.githubusercontent.com/323878/73498052-086dcb00-4371-11ea-9249-c60df73ffc6b.png)

**Comment by connor4312** [comment]
The icon now gradually disappears if the text is too long:

![](https://memes.peet.io/img/a3dbc6c7-426e-4402-b9c8-ff650c9d8996.gif)

adding `flex-shrink: 0` on the monaco-action-bar seems like it should fix it

**Comment by isidorn** [comment]
Not for last day of endgame. Moving to March.
@connor4312 do you want to submit a PR?

**Comment by connor4312** [comment]
Sure

**Comment by isidorn** [comment]
@connor4312 thanks for the idea for the fix. Went ahead to no longer have this issue in my to-do list.
