### ISSUE TITLE
IPreferencesService.openSettings does not work with text based settings editor

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#89512]
Refs: #89272

If the settings UI is not used pressing the gear button in the "Failed to save.." notification does not insert or locate the "files.preventSaveConflicts" setting in the settings.json file. This lets the user clueless about the name of the setting.

**Comment by bpasero** [comment]
@weinand it should open the settings editor and fill in the settings name automatically:

![image](https://user-images.githubusercontent.com/900690/73280996-9c178e00-41ef-11ea-9056-cfdb1449c6e9.png)

Could it be that you have disabled the settings UI editor?

**Comment by weinand** [comment]
Yes, that's why the sentence starts with "If the settings UI is not used"...

**Comment by bpasero** [comment]
@roblourens I am using this method: 

`this.preferencesService.openSettings(undefined, 'files.preventSaveConflicts')`

I think this should work even if you have configured a settings text editor?

**Comment by roblourens** [comment]
`undefined` as the first parameter means to use the user's configured settings editor. You can force it to pick one or the other by passing a boolean.

**Comment by bpasero** [comment]
@roblourens well I would not want to force it to the user, I would think this method needs to support both textual settings editor and UI editor.

**Comment by roblourens** [comment]
It does, I'm not sure what you're asking for.

**Comment by bpasero** [comment]
@roblourens yes it does open the settings text editor, but the settings key I am passing in is not being used. Wouldn't it make sense to maybe put in the key and open intellisense automatically?

**Comment by roblourens** [comment]
I don't think it makes sense to have this in the plan json editor, it will leave your settings file in an invalid state unless the user cleans it up. Which is very different from just searching for the setting.

**Comment by bpasero** [comment]
Yeah, that is true. Feel free to close, I don't have a better suggestion just now.

**Comment by roblourens** [comment]
@octref is there a way to open the suggest widget with a certain row focused, without actually inserting any text into the editor?

**Comment by bpasero** [comment]
@roblourens just as a reference, this flow is implemented with debug launch configurations and imho works nicely:

![Kapture 2020-02-04 at 7 18 13](https://user-images.githubusercontent.com/900690/73719079-8f7ac480-471e-11ea-8896-c08cd37e9652.gif)

**Comment by octref** [comment]
What @bpasero mentioned seems to be effect of running command `editor.action.triggerSuggest`.

I think you can set the selected value and trigger a completion at this position, which should trigger a replace completion with current value focused:

```
  "files.saveConflictResolution": "|askUser"
```

![image](https://user-images.githubusercontent.com/4033249/73772136-7aa92b80-4734-11ea-93a5-c5564cf62d6e.png)

**Comment by roblourens** [comment]
@bpasero right but I need it to reveal a particular item

@octref I want to do this without writing anything into the user's settings

**Comment by octref** [comment]
@roblourens 


```ts
export class CompletionItem {

  /**
   * Select this item when showing. *Note* that only one completion item can be selected and
   * that the editor decides which item that is. The rule is that the *first* item of those
   * that match best is selected.
   */
  preselect?: boolean;
}
```

**Comment by roblourens** [comment]
Hm, that's it but the provider doesn't know that we are in this particular context. I think that telling the provider to do something different would be hacky.

@bpasero what do you think about @octref's suggestion, do you think it's ok to actually write the default setting into the settings file? If so I would implement that.

**Comment by octref** [comment]
If it's side-by-side, then you can just select the setting on the left side. But if there's only one single editor, I think my suggestion is reasonable.

**Comment by bpasero** [comment]
@roblourens yeah I think that makes good sense as long as you write the key and value fully so that the settings editor is left in an OK state.

**Comment by sandy081** [comment]
This issue came up during the settings sync user testing. 

FYI, this feature is already supported from another place -> Configuring language specific settings.

When a language is selected, this action opens the settings.json file and reveals the selected language setting. If language setting does not exists then it will add an entry and reveals it. 

![Kapture 2020-03-03 at 12 24 08](https://user-images.githubusercontent.com/10746682/75771309-01f4b980-5d4a-11ea-937d-5d67e3d6fb0c.gif)

It was supported only for language specific settings using the following API

https://github.com/microsoft/vscode/blob/90f33ddc6dacb25a2c54135e5914dfea86f440f3/src/vs/workbench/contrib/preferences/browser/preferencesActions.ts#L273

I removed this API and adopted it work for all settings by introducing `editSetting` option in Settings options.

https://github.com/microsoft/vscode/blob/4f6b67691d5bb0f849d70985a958fa44bb74398a/src/vs/workbench/contrib/preferences/browser/preferencesActions.ts#L273

In addition I also enhanced it to show suggest widget (as mentioned in this issue) - Here is new behaviour

![Kapture 2020-03-03 at 14 12 06](https://user-images.githubusercontent.com/10746682/75779385-ceba2680-5d59-11ea-913e-4e8f27fb65ad.gif)

**Comment by sandy081** [comment]
@roblourens Using this from settings editor looks like follows:

![Kapture 2020-03-03 at 14 22 17](https://user-images.githubusercontent.com/10746682/75779762-82231b00-5d5a-11ea-9428-a3d42d725a86.gif)

Created a PR to adopt this in settings editor

**Comment by sandy081** [comment]
Verification Steps:

- Open Settings UI Editor 
- Use the action `Edit in settings.json` for eg on Sync > Ignored Settings / Ignored Extensions settings
- Make sure the settings file is opened with IntelliSense triggered
