### ISSUE TITLE
"files.defaultLanguage" setting should have validation

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#89527]
Testing: #89233

I know this isn't related to the `${activeEditorLanguage}` setting, but it feels like there should be better validation on this input. I accidentally wrote `javscript` and couldn't figure out why it wasn't working:

![image](https://user-images.githubusercontent.com/35271042/73287106-8bdebf00-41ad-11ea-8541-9be65dfc026d.png)

Since we know the languages from the language mode list, we should either validate the input based on this or provide a dropdown and include `Active Editor Language`.

**Comment by bpasero** [comment]
Unfortunately I am not aware of a way to do this because the list of languages is dynamic. In fact, if you use the settings editor as JSON editor we contribute intellisense help dynamically:

![image](https://user-images.githubusercontent.com/900690/73337490-b778ac80-4274-11ea-8d48-9db723cdab4c.png)

But I am not aware of doing dynamic things like that for the settings UI editor unless @roblourens has an idea.

**Comment by roblourens** [comment]
Yeah it's not part of the settings schema, it's a one-off intellisense helper for that setting. We can add that sort of ability to the UI but it doesn't exist yet.
