### ISSUE TITLE
Use content hash to detect save conflicts and do not rely on size

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#89537]
testing #89272

This only happens in some cases... 
```
Editor 1:
  type "test1"
Editor 2:
  type "test2"
  save
Editor 1:
  save
  choose 'overwrite'
  change to "test2"
Editor 2:
  change to "test3"
  save
Editor 1:
  save
  🐛> no resolve conflicts shows, overwrites existing contents without warning
```

This seems to only happen if the conflict is in entirely contained within the range of the past conflict.

**Comment by bpasero** [comment]
Yes, you found my small optimization in our conflict detection logic: instead of just relying on the modification timestamp for finding out if the file changed on disk, I also check for the size. The reason for that is that I am too worried that in some file systems the modification time may advance for whatever reason without the content actually changing. With this, I reduce the likelyhood of a false save conflict warning.

In the end what we need is something like https://github.com/microsoft/vscode/issues/919 proposes: a hash of the file contents that we compare to the local saved one to truly detect if there are changes.
