### ISSUE TITLE
Restarting a debug preLaunchTask alerts that it terminated with exit code undefined

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#89566]
While verifying https://github.com/microsoft/vscode/issues/84794

Restarting a debug preLaunchTask alerts that it terminated with exit code undefined

![image](https://user-images.githubusercontent.com/2230985/73309296-ce68c180-41d6-11ea-9502-173dc455067b.png)

Maybe in this scenario the debug session should automatically be cancelled?

**Comment by isidorn** [comment]
All the debut ask handling is in this file https://github.com/microsoft/vscode/blob/103d07939be1f05d336defccb2ec346605e2f3fa/src/vs/workbench/contrib/debug/browser/debugTaskRunner.ts#L39

Pull Request that fixes this is very welcome @connor4312 
It seems like the error messsage is picked up [here](https://github.com/microsoft/vscode/blob/103d07939be1f05d336defccb2ec346605e2f3fa/src/vs/workbench/contrib/debug/browser/debugTaskRunner.ts#L76) and we could be smarter

**Comment by isidorn** [comment]
Why do you think @connor4312 @weinand this case should be handled differently? 
Do you restart the task while debug has not yet started? If yes I think it is a legitimate question to ask the user if he still wants to debug.
@alexr00 in case we decide to treat this scenario differently how can I know if a task terminated due to user initiation or not?

**Comment by weinand** [comment]
**Problem 1:** I think the message "prelaunchTask 'xxx' terminated with exit code undefined" is bad in general (independent from the "restart" context).

Even if a user understands the Unix concept "exit code", it does not make sense to talk about "exit code undefined" because "undefined" is not a part of the Unix concept but is an implementation detail (or better: a bug) of VS Code. A user cannot fix his prelaunchTask to stop returning "undefined".

So we need to fix the error message by something like this: "execution of prelaunchTask 'xxx' failed". With this we would not bother the user with unnecessary implementation or Unix details.

**Problem 2:** should we really show this alert in this "Restart" context or should we silently cancel or continue the Restart?

Assume that a given prelaunchTask works perfectly fine but when being cancelled (e.g. as part of the Restart) fails. Showing always the alert in this case would result in a bad user experience.

From this perspective I think it would make sense to ignore a failing prelaunchTask if it was cancelled as part of a Restart. The subsequent prelaunchTask will succeed (because it is not cancelled) and the debug session will start without problems.

**Comment by alexr00** [comment]
@isidorn the `exitCode` of the `ITaskSummary` from running the task will be undefined if the task is canceled by the user.

**Comment by isidorn** [comment]
For **problem 1** I have pushed a fix.
@alexr00 thanks, I can use that
@weinand please note that @connor4312 is restarting a task, not a debug session. Restarting a debug session produces no dialog message, it just works

**Comment by weinand** [comment]
How do I "restart a debug preLaunchTask"?

**Comment by isidorn** [comment]
`F1 > tasks: rerun running task`

**Comment by weinand** [comment]
But this will only result in an Alert with an "Debug Anyway" button if the original task was a prelaunch task, correct?

If yes, it still makes sense to ignore an error (exitCode of the ITaskSummary from running the task will be undefined if the task is canceled by the user).

**Comment by isidorn** [comment]
Correct, that is how I understood this issue. @connor4312 can correct me if I am wrong.

**Comment by weinand** [comment]
So bottom line: don't annoy the user with an "task fail" alert if the task fails because she has cancelled (or restarted) the task.

**Comment by isidorn** [comment]
Exactly.
