### ISSUE TITLE
AbstractSynchronizer.getRemoteUserData is called without lastSyncData seemingly on every sync

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#89623]
This is causing syncs to have an initial request that returns a 200, followed by another that returns 304, for every resource. So double the requests are going to the server which essentially renders the caching/304 mechanism useless as the DB always gets hit for every resource on a sync anyway.

If seems like this this signature should use `lastSyncData: IUserData | null` (no `?`) to ensure that `IUserData` or `null` is always explicitly passed in to avoid this error.

https://github.com/microsoft/vscode/blob/1b00acf16141e25a112226ea9397562cec7f011d/src/vs/platform/userDataSync/common/abstractSynchronizer.ts#L80-L81

Here's an example of a bad call that I see causing this:

https://github.com/microsoft/vscode/blob/1b00acf16141e25a112226ea9397562cec7f011d/src/vs/platform/userDataSync/common/abstractSynchronizer.ts#L56-L59

Stack:

![image](https://user-images.githubusercontent.com/2193314/73369122-f4d63d80-4266-11ea-9afb-d411b972a4d3.png)

**Comment by sandy081** [comment]
Yes, there are some requests which I thought I do not need to send the last sync data the client has for eg:

- Overriding local data (Pull)
- Overriding remote data (Push)
- Checking if remote data exists or not (to turn off completely).

But I agree that I should be using the last sync data always so that caches can be involved more efficiently.

Thanks for finding this glitch.

**Comment by Tyriar** [comment]
Problem still remains for global state, it appears it's checking `.sync/GlobalState/` but the actual file is in `.sync/UI State/`

**Comment by Tyriar** [comment]
Fixed with https://github.com/microsoft/vscode/commit/8d04692b23834d606e9aa038d4197aca26cdf9c7
