### ISSUE TITLE
Cannot set breakpoints in skew source

### ISSUE THREAD

**Issue by alecazam** [Microsoft/vscode#8963]
- VSCode Version: 1.2.1
- OS Version: OSX 10.11.2

I'm trying to step debug through skew language files in VSCode using the chrome-debugger extension. These have the .sk extension.   I can't set any breakpoints on these files, but I can step through/break into the source with source maps enabled.   VSCode debugger occasionally jumps back to compiled.js file and then I can set breakpoints in the js code.  I could turn off sourceMaps, but I want to work with the original source.

remote-debugging chrome launch at 9222
webRoot www
url           http://localHost:8000/...../www/index.html

on my drive
www
source <- renamed from src due to other VSCode bug
www/source  <- symbolic link up from webRoot, only way sourceMaps are matched up

I tried setting the webroot one level up, but then even though diagnostics reports the correct sourceMap full path, break/step only occurs in the compiled.js.  This is the only method I've found to step through the .sk files.

Why can't I even set breakpoints in source files?  They're not gray, they're not red, I just cannot set them in the source.  That's with debugging enabled/disabled.

**Comment by evanw** [comment]
I haven't tried this out personally but my guess is that this is because Skew uses the sourcesContent feature of source maps and VSCode has made a decision not to support debugging in this scenario (https://github.com/Microsoft/vscode-chrome-debug/issues/60).

Skew uses sourcesContent both because it keeps everything self-contained (you don't have to resort to brittle solutions like symlinks if the sources are embedded) and because the standard library sources are embedded in the compiler and don't exist on disk.

**Comment by alecazam** [comment]
I've verified that the sourceMaps work fine in Chrome, so it's just VSCode that won't set breakpoints.  It appears to break/step and display the variables just fine in the .sk files.

**Comment by weinand** [comment]
@alecazam @evanw source map handling is the responsibility of individual debug extensions and has nothing to do with VS Code. So VS Code is not in the position to make any decisions to **not** support specific debugging scenarios. The node.js debugger extension supports `sourcesContent` (aka inlined content) just fine.

Since you are using the [Debugger for Chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) extension I will move this issue to the corresponding repository.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-chrome-debug#195
