### ISSUE TITLE
Toggle comment do not grey-out semantic tokens immediately

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#89640]
Version: 1.42.0-insider
Commit: be9c72410acc677070685a616773b122f4c5e141
Date: 2020-01-29T05:35:51.712Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0

---

- Have a line with semantic highlight tokens
- Toggle line comment

![bug](https://user-images.githubusercontent.com/4033249/73386535-d9c5f680-4283-11ea-88f8-56f1114b69c8.gif)

**Comment by alexdima** [comment]
I don't really know what we can do in this case. As far as the editor is concerned, an insertion of two characters took place and the semantic tokens are shifted to the right by two characters. Then, a semantic tokens request is made and eventually (with a total delay of 1-2s in your gif), semantic tokens return.

It is unfortunate. I will think a bit more about what I could do given the tokens adjuster must be language agnostic (I shouldn't treat `//` in a special wa).

**Comment by gundermanc** [comment]
FWIW, in the VS editor, classifications are ordered relative to one another so that when they overlap, you can order the one you want to 'win' before the other, and then the presentation details are merged.

Though semantic tokens can't overlap, could similar rules be implemented in the VS Code themes for TextMate scope name themes so that you can effectively say `comment.*` scope name always supersedes presentation details of some set semantic tokens?
