### ISSUE TITLE
If there are multiple formatters defined for a file type no prompt happens on save

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#89655]
Refs: #89330

While testing #89330, I noticed that for files that had a 1 existing formatter (and no default set), and then I registered my new slow formatter, then I wouldn't get a prompt on save saying there were multiple providers. It would seemingly keep using the previous provider. Although if I used `Format Document` then I would get a prompt.

Seems like save should cause the same prompt in this case.

**Comment by jrieken** [comment]
Format on Save is a "silent format", e.g there isn't a user interaction (save on focus loss or after timeout) and the current file must not be the one that's being saved. Because of that, e.g not to interrupt you while doing something else, we don't show the "pick formatter dialog". That's only showing when "explicit" formatting via Format Doc/Selection
