### ISSUE TITLE
Extension search box suggestion overflows from editor

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#89675]
Issue Type: <b>Bug</b>

**Repo**
1. Open extensions view
1. Trigger suggestions in search box

**Bug**

![Screen Shot 2020-01-29 at 4 23 23 PM](https://user-images.githubusercontent.com/12821956/73409347-d9ddea80-42b3-11ea-8c93-90014084eeb3.png)

VS Code version: Code - Insiders 1.42.0-insider (be9c72410acc677070685a616773b122f4c5e141, 2020-01-29T05:35:51.712Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (3.93GB free)|
|Process Argv|-psn_0_3793822|
|Screen Reader|no|
|VM|14%|
</details>

**Comment by JacksonKearl** [comment]
@sbatten @rebornix  there wasn’t any more layering work this iteration, correct? Any idea what this might be ?

**Comment by sbatten** [comment]
@JacksonKearl it seems different than our previous issues, it's like the calculation for position is being determined by the area of the sidebar only. notice if you make the sidebar bigger, the widget slides into place and then stays.

**Comment by JacksonKearl** [comment]
Does not reproduce in stable.

**Comment by rebornix** [comment]
It's a regression. Not sure yet why it no longer aligns to the left.

**Comment by rebornix** [comment]
It might be introduced by https://github.com/microsoft/vscode/commit/04009e1ec45728711bcb5665b3791f2a1984e529 or https://github.com/microsoft/vscode/commit/c09fa2163acede0e1c9a369b6d1ee0efa47869e0 . @alexdima it looks like the change is related to the optimization you did for word wrapping, I'll leave it to you instead of pushing a potential buggy fix ;)

**Comment by sbatten** [comment]
still seeing this issue in todays insiders

**Comment by alexdima** [comment]
@sbatten What version specifically?

**Comment by sbatten** [comment]
@alexdima yep,
```
Version: 1.42.0-insider (user setup)
Commit: be0aca7188ec6a76e7c2379758c0fbc1e9c21f7b
Date: 2020-01-31T13:53:58.701Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by alexdima** [comment]
After https://github.com/microsoft/vscode/commit/92da5890d8c30dd9b4410e7d0f2f8ef819e8ec97, the issue is now that the suggest widget is rendered completely, but in stable it was left-aligned with the cursor and now it is not:

| STABLE | INSIDERS |
|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/73554126-71297600-444b-11ea-81e1-fac199208119.png) | ![image](https://user-images.githubusercontent.com/5047891/73554145-78508400-444b-11ea-8638-33f65b4169e5.png) |

**Comment by LouisianaNutSack49** [comment]
There is a of overcloxking on the primary PC Ram/processor/Visio card that hasnt been tested, when stability of programs are concerned taking it down to factory with increased reliability  might be best practice

**Comment by JacksonKearl** [comment]
@sbatten bugged behavior rendered parts of suggest completely out of viewport.

**Comment by JacksonKearl** [comment]
Never mind, missed that we are going to restore Stable's behavior.
