### ISSUE TITLE
Don't disable settings sync when the server is returning 403

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#89698]
![image](https://user-images.githubusercontent.com/10746682/73444314-a86b2a80-4358-11ea-9c80-8bffcf47b3de.png)

**Comment by Tyriar** [comment]
The app service is stopped atm, this should be handled gracefully (just retrying periodically like normal).

**Comment by sandy081** [comment]
/duplicate 

#89538

Ok, this is similar to offline case.

**Comment by sandy081** [comment]
Changed the strategy:

- Do not disable the sync for known errors when server or client are offline or for unauthorised requests. Disable sync for unknown or major errors.

- In case of failures, do not change regular auto sync interval. Instead delay the sync triggered by changes or events. Sync triggered by opening or changing settings or keybindings or extensions is delayed by number of seconds as number of failures up to 1 minute.

**Comment by sandy081** [comment]
@Tyriar Please verify.

**Comment by Tyriar** [comment]
I think this is fine, I didn't wait 20 minutes or something to check if it automatically disables itself though. You should consider changing the log to mention what the problem likely is, eg

```
[userDataSync] [error] The settings sync server is likely down temporarily.
[userDataSync] [error] Error: Request '.../resource/settings/latest' is Forbidden (403).
```

This will hopefully save people from creating issues when this happens if they go and investigate why it's not working.
