### ISSUE TITLE
Go Back command collapses selections

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#89699]
* in file A select multiple lines
* reveal file B
* invoke Back-command (ctrl+-)
* :bug: the selection file A is now collapsed/empty

**Comment by bpasero** [comment]
Looks like I am doing this on purpose:

https://github.com/microsoft/vscode/blob/c4309702c525d61b34bb6403a121a0595a473974/src/vs/workbench/services/history/browser/history.ts#L49-L52

This might break people's assumptions if we are going to change it because a user may expect that "Go Back" can be invoked and you can type without deleting whatever was in the selection.

However I should probably revisit using the start line/column and not the end line/column.

**Comment by bpasero** [comment]
Let's just do it. **Verification:** going back/forward restores selections as they were. Note that in order to get a history entry there needs to be at least 10 lines between the positions to consider the entry as new entry.

![Kapture 2020-02-04 at 10 01 53](https://user-images.githubusercontent.com/900690/73729489-6ca7da80-4735-11ea-9345-1228f0302110.gif)

**Comment by ArturoDent** [comment]
Works well except with the new `Column Selection Mode` turned on.  Then going back only selects the last line of the previous column selection.

**Comment by bpasero** [comment]
Yeah,  I think the history is currently NOT multi-cursor aware.
