### ISSUE TITLE
I want snippets syntax that get the directory name of the current file 

### ISSUE THREAD

**Issue by Candane** [microsoft/vscode#89700]
My programPath : D://vueProgram/mall/detail/DetailGoods.vue
WORKSPACE_NAME is vueProgram，TM_DIRECTORY is D://vueProgram/mall/detail，but I only want to get "detail"

Sometimes I want to use it in my code snippets

**Comment by IllusionMH** [comment]
You already can achieve that using [Variable transforms](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variable-transforms)

In this case it can be achieved using `"${TM_DIRECTORY/.*\\\\([^\\\\]*)$/$1/}"` (4 `\` because you need to escape backslash with another back slash for regexp first, and then escape each of them for string) a bit simpler form `"${TM_DIRECTORY/.*\\\\(.*)$/$1/}"`

For Posix paths it will be` "${TM_DIRECTORY/.*\\/(.*)$/$1/}"`
Universal snippet will be `"${TM_DIRECTORY/.*[\\\\\\/](.*)$/$1/}"` (we need to go deeper with backslashes 🤣)

**Comment by Candane** [comment]
🤣ok,Thank you for your answer
