### ISSUE TITLE
Change the default Korean font

### ISSUE THREAD

**Issue by deunlee** [microsoft/vscode#89710]
Hi,

I am Korean and often use Hangul(Korean characters) in VSCode.

However, the default font family are Consolas, CourierNew and the first and second do not contain Hangul. So, when coding with Hangul, the last monospace is applied. In this case, Gulim is used as the default Hangul font. But Gulim is old and BITMAP, so it's very ugly.

There are some great free fonts for Hangul coding like NanumGothicCoding and D2Coding, but they need to be downloaded and installed by the user. However, there is a pretty nice font MalgunGothic. It is the default font included in the Korean Windows. It supports both Korean and English, English is not fixed-width. But, Hangul is fine and I would like to put it in the editor default font for Korean Windows users.

The right side of the picture below is an ugly bitmap font and the left side is MalgunGothic. There are a lot of Korean users who use this editor. Some of them install and use good Korean fonts, but many still do not. Many Koreans will like it if this applies.

![test](https://user-images.githubusercontent.com/54697735/73454901-5c4cd400-43b2-11ea-815a-57940ae12fc0.png)

```
"editor.fontFamily": "Consolas, 'Courier New', 'Malgun Gothic', monospace"
```

Thanks.

**Comment by alexdima** [comment]
@deunlee Tweaking the default font family is risky, because I don't really know what will be the complete effects of the change. Will other glyphs now come from `Malgun Gothic` ?

The easiest is to make an extension that changes the default and provide that in the marketplace. See https://code.visualstudio.com/api/references/contribution-points#contributes.configurationDefaults
