### ISSUE TITLE
Add {structure} in debug [suggest]

### ISSUE THREAD

**Issue by djmisterjon** [microsoft/vscode#89727]
Any chance or way to add the `Structure tool`  inside Debug tool ?
I use it a lot during the debugging phase to navigate in big code.
Maybe a way to allow this also inside debug tool for help navigation?
![image](https://user-images.githubusercontent.com/24865815/73471670-c2f0d400-4357-11ea-881c-6244b37b81a8.png)

thanks for all crazy work on vscode.

**Comment by isidorn** [comment]
Thanks for the suggestion.
As far as I understand you want to move the Outline to the debu view. This will be possible in the future and @sbatten is already working on this.

If you want another view, a potential extension can contribute this.
Point being we can close this issue since for outline it is already in progress and extensions you can file in their reporistories.

**Comment by djmisterjon** [comment]
thanks, i think i found the tread about it.
https://github.com/microsoft/vscode/issues/89729

if I understood correctly, we can customize the panels to our liking.
This will a good idea.

**Comment by isidorn** [comment]
Yeah.
