### ISSUE TITLE
VSCode should follow .lnk

### ISSUE THREAD

**Issue by runxel** [microsoft/vscode#89743]
VSCode should be able to resolve `.lnk` files, if this link leads to a file on the users hard drive.
Thus the user can open the file right away by clicking on the link file in the sidebar.

**Comment by RuizuKun-Dev** [comment]
> VSCode should be able to resolve `.lnk` files, if this link leads to a file on the users hard drive.
> Thus the user can open the file right away by clicking on the link file in the sidebar.

I would like this functionality as well, is it possible to reconsider this?

**Comment by martin-zima** [comment]
Hi guys,

I was having difficulties opening files from some shortcuts in VS Code so did some searching but have to admit I was quite surprised to find this page, essentially saying it's a known issue and there are no plans to fix it. 🙁

I understand you have a lot of issues to triage, but do think this one may be worth re-considering...
- .lnk files have been part of Windows for 25 years (since Win95) and are used by users every day
- They are handled (resolved) by pretty much every other application (I literally can't think of another app that has tried to open the shortcut file itself, rather than the target)
- (rhetorical) Is this feature/fix really going to be that hard to implement?... I don't know the code/effort involved, but would like to think this would be a fairly straight-forward fix (<5 lines) by a simple if check on the file extension, or something similar(?)

I appreciate the issue is currently closed, but hope the above outlines the case for implementing this feature. Thanks!

**Comment by htchaan** [comment]
reopen please

**Comment by henryfung3a27** [comment]
To work around it, try `mklink` with `cmd`.

`.lnk` is created by right-clicking the file / folder and select `create shortcut`. It is not exactly a symlink but a file with pointer to the actual file and other details. If you run `dir` from cmd, you'll see it has no difference with other files except with the file extension being `.lnk`.

To create an actual symlink, you can run [`mklink`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink) from cmd or [`New-Item`](https://stackoverflow.com/a/34905638/6625422) from Powershell. Both methods require **privilege escalation**.

CMD
```cmd
mklink [/D] <new_symlink_name> <source_of_symlink>
```
where the `/D` flag is needed for symlink-ing a folder.


PowerShell
```powershell
New-Item -Path <new_symlink_name> -ItemType SymbolicLink -Value <source_of_symlink>
```

Now when you `dir` the directory, you will see `<SYMLINK>` or `<SYMLINKD>` property in CMD or the `l` mode flag in PowerShell.

Back to VSCode, you'll see the nice drop-down button on the new symlink folder with the little arrow symbol!

![symlink folder](https://code.visualstudio.com/assets/updates/1_21/symlink.png)
> image from [VSCode update notice](https://code.visualstudio.com/updates/v1_21#_symbolic-link-indication-in-explorer)

**Comment by gaiking-uk** [comment]
Thanks @henryfung3a27 -- your workaround should hopefully help a few people out! 👍🏼

Side note: Unfortunately, it doesn't work for me (I did already consider this option) as my code directories are inside OneDrive and .symlinks aren't supported / synced with OneDrive... Once again, I would ask the VS Code Team to re-open/re-assess this issue -- thanks guys!

**Comment by gaoqiangks** [comment]
reopen, please.

**Comment by mogggen** [comment]
Greetings, coder!

I have thrown together vscode extension that solves this: https://github.com/mogggen/LNK_file_Redirect_Windows
Only tested it on single files. Only on Windows.
It doesn't make sense on other platforms either. But though I mention that since VSCode is a Cross-platform app after all.

**Note**: It opens the orignal file that the .lnk file points at. Instead of opening the .lnk file. It requires more testing, obviously. But it solved my problem, personally. No batteries included.

I have not implemented nor tested the '[Open with Code](https://github.com/microsoft/vscode/issues/324353)' or '[Open with Zen](https://github.com/zed-industries/zed/issues/60407)' shortcut issues.
