### ISSUE TITLE
Turning off sync for all devices doesn't actually do what it says

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#89750]
Refs: #89358

So as I understand it, the UI option to "Turn off sync on all your devices and clear the data from the cloud." basically just deletes all the data from the cloud. And vscode then detects this no data state on each device and takes it to mean that sync should be turned off. Meaning that there is not currently a notion of sync actually being turned off for a device(s). This causes issues especially with low/no connectivity devices.

For example, say you have 2 machines A & B. You have sync on for both. Now put B to sleep, turn it off, or otherwise have a network issue where it can't currently reach the sync server. Then,

- On A, turn sync off and select the option to turn it over everywhere
- On A, turn sync back on
- On B, wake/boot up and sync will still be on (because B never saw the no data state)

Ideally, we would add the ability for the server to somehow enforce this "turn off sync everywhere" command regardless of no/low connectivity.

**Comment by sandy081** [comment]
I don't know how we can get this if the machine is off or something like that. In this case machine B gets synced with the new data that is pushed from machine A which sounds ok right?

**Comment by Tyriar** [comment]
The problem is when you hit that checkbox you expect that it will be turned off on machine B, even if you turn it back on for machine A afterwards. We can solve this in multiple ways:

1. Change the text to not mention it will turn off on other machines and clarify in docs
2. Storing a disable event with a timestamp on it on the server and store the timestamp of the event sync on the client,

I'm not convinced it's that big of a problem and am leaning towards 1, at least for the mvp.

**Comment by sandy081** [comment]
Agreed to update the text and not to do heavy changes for minimal value

**Comment by eamodio** [comment]
My vote would be to keep the ability to turn off sync for all devices. I think it is important to be able to at least manage devices in that way. As you may lose control of a device, forget where you've set things up and just want to reset.

**Comment by Tyriar** [comment]
Actually, I'm not sure we can do the timestamp thing. Doesn't that mean we would still have user data in the cloud in the form of a userId -> delete timestamp 🤔

**Comment by eamodio** [comment]
Couldn't you just do it another way -- the existence of a userid->timestamp/record means sync is on, no  userid data means its off?

**Comment by Tyriar** [comment]
@eamodio that's how it works now.

**Comment by eamodio** [comment]
Sorry, I meant a per-machine record, not per-user

**Comment by Tyriar** [comment]
@eamodio not sure what you mean exactly but I did just realize if we added a timestamp for when sync was enabled that could work.

Machine A turns off sync -> server data is deleted
Machine A turns on sync -> new data is created with "enableTimestamp" for when it was turned on
Machine B turns on and tries to sync -> sees that "enableTimestamp" is not what it was when it originally synced, so it is turned off

**Comment by eamodio** [comment]
Yeah, that works too. I was just saying that each time you turned on sync for a machine, have a record/timestamp/something pre-user per-machine.

**Comment by Tyriar** [comment]
@eamodio if you're talking about on the client, that's no good as clearing data and adding another record looks the same as a new version being added.

**Comment by eamodio** [comment]
No, on the server. The server could store a some data per-user, for each machine where sync it turned on. And the non-existence of that per-machine data would turn off sync for that client machine

**Comment by Tyriar** [comment]
@eamodio ah understood, yeah that would work too but not quite as minimal as the timestamp approach.

**Comment by sandy081** [comment]
Actually, I am thinking of including the machine id as part of the request so that it will be useful in future if user wants to diagnose which machine of user has pushed the data.

**Comment by sandy081** [comment]
Sending machine id will be tracked here https://github.com/microsoft/vscode/issues/90074

**Comment by Tyriar** [comment]
I believe https://github.com/microsoft/vscode/issues/90106 happened for the same reason as this issue, but in a different order:

1. Machine A: Synced
2. All data was cleared on server
3. Machine B: Turned on sync, added first record
4. Machine B: Synced a bunch more times
4. Machine A: Synced again, found there is a new record so it deleted all local extensions

Note that this only happened because of the manual DB clear in step 2, normally the only way this will happen is if the data is cleared on the server in which case it will also be turned off on machine A.

**Comment by Tyriar** [comment]
This is unblocked for the client now; `/v1/manifest` will return an object containing a `session: string` that is set when the manifest is initially created. When this comes back different to what is expected, settings sync should turn off.

**Comment by sandy081** [comment]
In the case, when the session on the client is expired (different session on server) I do not think turning off sync on the client is expected. Instead, sync shall happen as if it is happening for the first time from the client.

**Comment by Tyriar** [comment]
We should be doing what the user said to do and turn it off:

![image](https://user-images.githubusercontent.com/2193314/74744164-9ae9e780-5216-11ea-820b-1cb07be875fb.png)

This will typically be used when the user wants to delete all their data and not turn it back on, why annoy the user by not turning it off and throwing a merge notification their way?

**Comment by sandy081** [comment]
If user turns off sync in all devices, then we turn it off when other machines tries to sync. Following is the special case where sync continues as if it is syncing for first time from the machine:

- User syncs on machine A
- User syncs on machine B 
- User turns off sync on machine A
- User turns on sync on machine A after
- User log into machine B

Turning off sync on this machine B is not correct, because user turned on sync on other machine. User expects to to continue syncing on machine B but it should not consider last sync state while syncing. It means it will sync as if it is first time sync on this machine.

**Comment by Tyriar** [comment]
> Turning off sync on this machine B is not correct

I disagree. As soon as the session changes all clients should immediately stop querying the server. If the session changed, why would it behave differently? Machine B should act consistently whether the step is this:

- User turns off sync on machine A
- User turns on sync on machine A
- User log into machine B

Or this:

- User turns off sync on machine A
- User log into machine B
- User turns on sync on machine A

The dialog says "Turn off sync on all your devices", not "Turn off sync on all your devices (except maybe turn it back on right after)". We can discuss this in the sync tomorrow.

**Comment by eamodio** [comment]
100% agree with @Tyriar 

It also seems like that could be a reasonable pattern:
- turn everything off everywhere (so I reset everything on every device I've ever synced with)
- then turn it back on to set it up with a new set of known/new devices

If those old devices came back on that would not only be unexpected, imo that would be very broken

**Comment by sandy081** [comment]
In both cases sync is turned off on machine B with following notification

<img width="561" alt="image" src="https://user-images.githubusercontent.com/10746682/74985736-5f2e6800-5438-11ea-9c66-69fdc56356ca.png">

**Comment by Tyriar** [comment]
@sandy081 wording suggestion:

> Sync was disabled because is was turned off from another device.
> 
> [Re-enable. sync]

**Comment by sandy081** [comment]
We do not use enable/disable sync hence I was hesitant to use that. How about

> Sync was turned off because it was turned off from another device
> 
> Turn on Sync

**Comment by eamodio** [comment]
How about
>Sync was turned off from another device
>
>Turn Sync Back On

**Comment by Tyriar** [comment]
Personally enable/disable reads a lot better than "turn on/off". Also "turn sync on/off" sounds better than "turn on/off sync" imo.

**Comment by eamodio** [comment]
IMO, if we switched to enable/disable (which I do like better) we should change it everywhere.

**Comment by Tyriar** [comment]
@misolori any opinions? Here are other places we're communicating similar things about enablement in menus:

<img width="248" alt="Screen Shot 2020-02-21 at 7 02 58 AM" src="https://user-images.githubusercontent.com/2193314/75045543-51003c00-5478-11ea-9389-ef3a9d766c30.png">
<img width="226" alt="Screen Shot 2020-02-21 at 7 03 13 AM" src="https://user-images.githubusercontent.com/2193314/75045546-53629600-5478-11ea-94ce-9521fce44582.png">
<img width="240" alt="Screen Shot 2020-02-21 at 7 03 21 AM" src="https://user-images.githubusercontent.com/2193314/75045551-55c4f000-5478-11ea-91e3-4e5c8032aa37.png">

**Comment by misolori** [comment]
My first impression is to use "Sync is disabled because it was turned off from another device." but when you think about, we don't use the term "enable/disable" for sync, it's always on/off. So I would rather go with @eamodio's suggestion of `Sync was turned off from another device` but I would have the button say `Turn on sync` to match what we already say in the gear menu.

**Comment by misolori** [comment]
Also, not sure why but the term "Enable Sync" feels weird/unnatural to me.
