### ISSUE TITLE
"Cannot apply refactoring because 2 other files have changed in the meantime" but only 1 file open and no apparent change

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#89776]
While verifying https://github.com/microsoft/vscode/issues/89506

Setup as instructed in test plan: #89335. My file content was:

```
createNewFile
createNewFileWithContent
deleteThisFile
editAndRenameThisFile
renameAndEditThisFile
```

I clicked into `renameAndEditThisFile`, hit F2 and added a `2` at the end. Opened preview and accepted the change. It worked the first time, but every other time after (even after reload) I got this:

![image](https://user-images.githubusercontent.com/38270282/73532866-dd8d8080-441d-11ea-8a14-2038689c3466.png)

I don't actually have 2 files open.

**Comment by alexr00** [comment]
Screenshot from debugging
![image](https://user-images.githubusercontent.com/38270282/73536659-ad96ab00-4426-11ea-8cda-ef1bf1fcb069.png)

**Comment by jrieken** [comment]
This is the conflict detector being too sensitive. While code actions are being previewed we listen for changes of files that are part of the refactoring *and* for changes of other files (could be your tsconfig.json etc). However, the check for changes in other files is often leading to false positives, e.g. on windows (screen shot above) it seems that save global-state save different so that it very often conflict with code actions...

**Comment by jrieken** [comment]
I have pushed a small, endgamey change and will revisit this during Feb debt week
