### ISSUE TITLE
package.json dependency hover can break with links

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#8977]
![image](https://cloud.githubusercontent.com/assets/2193314/16701773/e05c75d2-4516-11e6-8db4-19e70fcee6a4.png)

npm module https://www.npmjs.com/package/angular-ui-bootstrap

via https://twitter.com/zwacky/status/751394828844400640

**Comment by aeschli** [comment]
Normally node modules have a description field (defined as text), but in this case it looks like they took it from the README. However it's just a fragment, that's why it can't be rendered correctly.
I'm now make sure that the description is forced to be rendered as text (not markdown).
Doesn't help much for the angular-ui-bootstrap node module, they need to fix the description.
