### ISSUE TITLE
Feature: In source control view: alt + click on file should open said file directly

### ISSUE THREAD

**Issue by keith0305** [microsoft/vscode#89775]
![image](https://user-images.githubusercontent.com/5112337/73534815-05500900-445d-11ea-95fa-feadb6db7e3e.png)

**Current behavior**: Clicking on a file would open its changes. Alt + click does the same.
**Proposed addition**: Alt + click on a file would open the file directly, instead of having to right-click and select "Open File".

Since ctrl and shift key were already used as selection modifier, alt seems to be perfect for this.

**Comment by IllusionMH** [comment]
You can set `"git.openDiffOnClick": false` to open files with click and diff with "Open Changes" action.

**Comment by keith0305** [comment]
@IllusionMH Yes I am aware but what I was suggesting was to add a modifier key to do that, without having to open context menu (right-click).

**Comment by IllusionMH** [comment]
I see your point, and just suggested this flag because I didn't know if you tried it.

Just in case: you don't need to trigger context menu - actions are available on hover (you still need to hover over file to Alt + Click).
![image](https://user-images.githubusercontent.com/1312662/73562534-0173b500-4464-11ea-9d0b-9033920bbdc4.png)
Left action will open diff.

But there is drawback - more precision needed to hit them instead of (almost) full row.

**Comment by keith0305** [comment]
Omg, didn't know about the hover icon. Thanks a lot! That will certainly help.
Anyway, I still think alt + click is a decent QoL enhancement. What do you think?

**Comment by joaomoreno** [comment]
I think this is a concept which isn't spread across the workbench. Since we already support settings as well as inline and context actions, I think it's fine to keep it this way. Thanks for the suggestion though!
