### ISSUE TITLE
GitHub Bot: /needsMoreInfo command not working for me

### ISSUE THREAD

**Issue by sportshead** [microsoft/vscode#89833]
- VSCode Version: N/A
- OS Version: N/A

Steps to Reproduce:

1. Go to a issue
2. Comment `/needsMoreInfo`

Does this issue occur when all extensions are disabled?: N/A

I've seen other people use the command `/needsMoreInfo` and vscodebot automatically adds the `~needs more info` label. But when I use the command [here](https://github.com/microsoft/vscode/issues/89828#issuecomment-581006060) it doesn't work.

**Comment by gjsjohnmurray** [comment]
These commands are only available to specific people, known as Community Issue Trackers. See https://github.com/microsoft/vscode/wiki/Community-Issue-Tracking

cc @chrmarti

**Comment by sportshead** [comment]
@gjsjohnmurray How can I be a Community Issue Tracker?

**Comment by sportshead** [comment]
Is there a specific requirement or something?

**Comment by gjsjohnmurray** [comment]
> 
> 
> @gjsjohnmurray How can I be a Community Issue Tracker?

I don't know if there's a formal procedure. @chrmarti perhaps the wiki page I referenced could benefit from an extra paragraph answering @sportshead's question.

**Comment by chrmarti** [comment]
@sportshead There is no formal process, you can start by helping out on incoming issues. Those with special powers were recommended by the development team because they demonstrated great motivation to contribute and detailed knowledge about current and recurring issues with VS Code.

Thanks for your interest!
