### ISSUE TITLE
Zen Mode soft-wrap broken

### ISSUE THREAD

**Issue by artagnon** [microsoft/vscode#89859]
I have soft-wrap set at 140 columns, but Zen mode doesn't take into account the fact that the display-size of the window itself has changed. As a result, text overflows, and there is a horizontal scrollbar present, which destroys the usability of Zen mode.

**Comment by isidorn** [comment]
Thanks for filling this issue. Can you reproduce using Visual Studio Code Insiders https://code.visualstudio.com/insiders/

Also what are your settings and can you post a photo of this in vscode insiders?

**Comment by artagnon** [comment]
Yes, I'm using vscode Insiders with `editor.wordWrapColumn` set to `140` and `editor.wordWrap` set to `wordWrapColumn`.
<img width="1440" alt="vscode-zen" src="https://user-images.githubusercontent.com/37226/73757912-38024600-476a-11ea-8c14-0348d615036b.png">

**Comment by isidorn** [comment]
Ok I understand the issue.
The problem seems to be that the centered editor layout does not properly notify the editor of the new layout or the editor does not properly recompute word wrapping
Code pointer if you would like to investigate more https://github.com/microsoft/vscode/blob/1e057b73930c16738d31278a068b0d50eb476c28/src/vs/base/browser/ui/centered/centeredViewLayout.ts#L79

Maybe setting `"editor.wrappingStrategy": "advanced"` might help.
