### ISSUE TITLE
ignoreRecommendations setting not working

### ISSUE THREAD

**Issue by sdailey** [microsoft/vscode#89875]
<img width="744" alt="Screen Shot 2020-02-02 at 2 33 33 PM" src="https://user-images.githubusercontent.com/1734174/73615009-1ec29380-45ca-11ea-9e08-d291476390c6.png">
Issue Type: <b>Bug</b>

Hi there, I'm still getting popups for extension recommendations despite Ignore Recommendations setting being checked/enabled. 

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.2.0

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2020.1.58038
Go|ms-|0.12.0

(3 theme extensions excluded)

</details>

**Comment by sdailey** [comment]
Just now seeing the "Show Recommendations only on Demand" setting, which seems redundant for what I want, but maybe this will solve my issue, so closing.

**Comment by sdailey** [comment]
Even with "Show Recommendations only on Demand" enabled and restarting VSCode, it's still recommending extensions, so reopening as Bug.
<img width="803" alt="Screen Shot 2020-02-02 at 3 11 24 PM" src="https://user-images.githubusercontent.com/1734174/73615593-d3f74a80-45ce-11ea-8ff2-ca1ae8d877e7.png">

**Comment by IllusionMH** [comment]
/causedByExtension

`extensions.ignoreRecommendations` controls whether VS Code will show you recommendations to install new extension(s) based on file type etc.

What you see is just notification triggered by an extension which may not be able to start/work correctly because required command in missing in your setup.

You need to discuss whether this notification should or shouldn't be show in extension repo https://github.com/microsoft/vscode-go/issues
