### ISSUE TITLE
Git open repositories order differ from UI

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#89965]
Issue Type: <b>Bug</b>

VS Code version: Code - Insiders 1.42.0-insider (705f01577dd37d6f17eaa683ab89b0c392fa1a7c, 2020-02-03T13:59:34.701Z)
OS version: Darwin x64 19.2.0

I have a multiple root workspace with VS Code repo and a small git repo, the workspace file is like below

```json
        "folders": [
                {
                        "path": "vscode"
                },
                {
                        "path": "prototype/notebook-test"
                }
        ],
```

When the workspace is loaded and the current view container is not SCM, `vscode` is the active repository (based on the info from status bar).

However git extensions API gives GHPR an ordered list of repositories which are all unselected. The order is 

```
[
  prototype/notebook-test, unselected
  vscode, unselected
]
```

From above list, we **can't** figure out which repository is the active repository in the workspace. The order of repositories is not the same as the UI due to the fact that we don't `await` for repository registration https://github.com/microsoft/vscode/blob/1d71d49864791541a5d18c1190da3c310b22dc7c/extensions/git/src/model.ts#L134 (not sure if this is intentional for performance), so we can't simply choose the first one as the active one.

Once SCM view container is opened, `vscode` shows before `notebook-test` and triggers a selection change event and from that moment, git extensions can provide information about *active* repository.

**Comment by joaomoreno** [comment]
I think the order should not matter, since the user can easily reorder them in the view.

But the `selected` attribute should be properly set... checking...

**Comment by joaomoreno** [comment]
Oh I see... currently the `selected` attribute matches to which repository is visible in the SCM view. Until the viewlet renders, no repository is visible, so none is selected.

The status bar state matches the `focus` attribute, which we do not expose in the UI...

**Comment by joaomoreno** [comment]
@rebornix After looking at this once again, I've decided not to do anything.

The right fix here would be to open up another proposed API representing the state of the active repository in the status bar, which differs from the selected repositories in the SCM viewlet. We'd then need to propagate this over to the git extension API. I don't think it's worthwhile tackling this since it was never my goal to have a single repository active in the status bar but rather an affordance which would accommodate every repository.

The other change we can do here is make sure the order is correct, that way you can always pick the first one if no one is selected. Mind you that the status bar can still show a repository which is not selected, if the user opens a file within that repository. But let's leave it at that.

**Comment by joaomoreno** [comment]
@rebornix After investigating I can't seem to get the wrong order like you do. Do you still repro this? I don't remember if I fixed this already.
