### ISSUE TITLE
Markdown preview lost after updating to v1.3

### ISSUE THREAD

**Issue by HIROSN** [Microsoft/vscode#8996]
- VSCode Version: 1.3.0
- OS Version: OS X 10.11.5

Steps to Reproduce:

1. Open README.md in VS Code
2. No preview button in upper right corner

**Comment by tony19** [comment]
I noticed the same problem. If the removal was intentional, I would've expected a release note on it with the reason (the 1.3.0 notes don't actually mention anything about the *Preview* button going away).

Please bring it back. I'm seeking alternate solutions [here](http://superuser.com/q/1098819/68227).

**Comment by bpasero** [comment]
It moved into the context menu of a tab until we have resolved this via https://github.com/Microsoft/vscode/issues/7666

Alternatively you can disable tabs to get the old action bar back.

**Comment by HIROSN** [comment]
It works. Thank you Benjamin!
