### ISSUE TITLE
Add visual indicator for extension packs in extension search results

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode#89962]
Today, it's possible to see the extensions that are part of an extension pack, but that requires that I click on the extension then click the "extension pack" header. I'd like to know, without clicking, that an extension is an extension pack via some kind of icon in the header. 

It would be nice to link directly to the extension pack details (list of extensions in the pack) if the extension pack icon is clicked.

**Comment by sandy081** [comment]
@misolori Any suggestions for visual indications?

**Comment by misolori** [comment]
Here's a couple of ideas:

### 1. Multiple tile thumbnail

We could load the various thumbnails of the other extensions into a grid

![image](https://user-images.githubusercontent.com/35271042/74211350-6a1d1780-4c44-11ea-9966-c55ce45e6830.png)

### 2. Stacks view

We can try and make the image look like a "stack" of icons so that it appears to be many

![image](https://user-images.githubusercontent.com/35271042/74211389-9a64b600-4c44-11ea-8381-56925df9c707.png)

### 3. Number badge

We could re-use our badge and append the total number of extensions in the pack. This could get a little busy with remote extensions since those have a remote badge in the bottom right.

![image](https://user-images.githubusercontent.com/35271042/74211462-e0217e80-4c44-11ea-8f68-b492ec39e58e.png)

### 4. Icon badge

This could also get busy with the remote badge but provides an entry point into the extension pack.

![image](https://user-images.githubusercontent.com/35271042/74211849-8a4dd600-4c46-11ea-8875-30b5b059bf24.png)

**Comment by fiveisprime** [comment]
I like the number badge since it doesn't obscure the icon and clearly shows what you're getting into. 

I'd also like to see the extension pack prioritized in the search results with all extensions in the pack nested underneath. Something like this

![image](https://user-images.githubusercontent.com/1186948/74258135-b26f2080-4caa-11ea-84d3-42fcdf80ad93.png)

That way, I can see what exactly is included in the tiles and even install just a couple of what's included without grabbing the pack and uninstalling/disabling things I don't want.

**Comment by misolori** [comment]
Placing the extensions under the pack like that would take up a lot more space. What if we added a small row under the extension pack author and placed the icons there like:

![image](https://user-images.githubusercontent.com/35271042/74260908-2f03fe00-4caf-11ea-8933-d9b89a1345d0.png)

**Comment by fiveisprime** [comment]
Okay, yeah. I like that.

Next, is there any way to make the "Extension Pack" menu more obvious after clicking into and extension pack? The detail I'm looking for exists, but it's not super obvious.

![image](https://user-images.githubusercontent.com/1186948/74261991-ea796200-4cb0-11ea-9c73-7eab9493dc09.png)

**Comment by misolori** [comment]
We could try to bring in that content closer to the details page:

![image](https://user-images.githubusercontent.com/35271042/74265503-87d79480-4cb7-11ea-822c-5d9196ac7769.png)

**Comment by fiveisprime** [comment]
I'm definitely feeling that 👍

**Comment by misolori** [comment]
And here's what it would look like if you did a search for all extensions packs, to see how busy it could get. This means we'd need to cap the number of extensions we show for each pack:

![image](https://user-images.githubusercontent.com/35271042/74268444-b99f2a00-4cbc-11ea-90dd-5c629283b492.png)

**Comment by sandy081** [comment]
Great ideas. I like the last proposal.

**Comment by misolori** [comment]
After getting feedback from the team, it appears the first option (tiles) is the favorable one since it doesn't feel too "heavy" compared to the extra row of icons.

**Comment by sandy081** [comment]
Deferring the implementation to next milestone.

**Comment by jwarkentin** [comment]
It would be nice to have collapsible groups of extensions in general. The extensions in a given group wouldn't have to be indented, taking more space to show. Instead, when expanded the group underneath could just share a slightly different background color and maybe an inset shadow to show the grouping. I just created a quick [CodeSandbox here](https://codesandbox.io/s/material-demo-xgx6t) based on the TreeView from material-ui to demonstrate the concept. Here's a picture too:

![Screenshot from 2020-03-27 22-33-33](https://user-images.githubusercontent.com/1084024/77815904-c6fd5180-707b-11ea-89e1-cec8cc0c0ed0.png)

My extension list is already so cluttered, it's hard to manage. Ultimately, I'd love to see grouping based on package and/or user-defined tags but at least being able to group and collapse extension packs would be amazing!

**Comment by sandy081** [comment]
Even though the `tiles` option is favourable, it is complex to implement and also not efficient. Because there is no information about the icons. It needs multiple queries. Hence I took the `badge` option.

<img width="426" alt="image" src="https://user-images.githubusercontent.com/10746682/77850565-c081ed80-71d3-11ea-9358-8a447e5220ef.png">

Enhanced extension editor to show extension packs in the main page

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/10746682/77850588-df807f80-71d3-11ea-8bdd-30d8d29a9594.png">

**Comment by connor4312** [comment]
my $0.02 when verifying: it feels weird to have multiple scrollable regions together like this. Does that region need to scroll? I don't imagine we'll have packs with a dozen extensions to the point that it becomes overwhelming

![](https://memes.peet.io/img/20-04-98e39c8b-1a1e-422d-b4bc-963e24dd936e.png)

**Comment by sandy081** [comment]
Yeah there are enough number of extension packs with atleast more than 4 extensions. I do not want read me to be pushed much further down. Above is the ideal proportional size for extensions and read me. 

Agree that two scroll bars is not ideal but not odd :)

**Comment by misolori** [comment]
I think it would be worthwhile to update the extension pack items from the mockups above:
- Reduce the width of the extension packs so we can fit three in a row
- Hide extra meta data clutter (description, install button, install count, etc.)

If you do happen to get into a place where there are more extensions and you need to scroll, it can look like like there is only a certain amount and can be misleading (see below). And double scroll bars is something we intentionally avoid so we should allow the height to be dynamic.

![image](https://user-images.githubusercontent.com/35271042/78192828-ce32af80-742d-11ea-9a43-9d002e8f5aef.png)

**Comment by sandy081** [comment]
- ✅  Reduce the width of the extension packs so we can fit three in a row 
- ✅  Hide extra meta data clutter (description, install button, install count, etc.) (**Except install button**)

I am not comfortable to have dynamic height for extensions, because this will push read me to bottom. See the following screen shot - Extension pack with many extensions (ignore the overlay)

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/10746682/78243595-570c2280-74e4-11ea-9eac-f30239ba7b3b.png">

**My suggestion**: Show scroll bar if an extension pack has more than 9 extensions. I think its a fair middle ground.

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/10746682/78244464-fa116c00-74e5-11ea-92d9-ec6c2838da85.png">


<img width="1362" alt="image" src="https://user-images.githubusercontent.com/10746682/78244446-efef6d80-74e5-11ea-9d36-f007adc2d8f3.png">


<img width="1389" alt="image" src="https://user-images.githubusercontent.com/10746682/78244433-e7973280-74e5-11ea-9f68-3ecf7df585b6.png">

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/10746682/78244496-07c6f180-74e6-11ea-932b-b0d60ba8fdbe.png">

**Comment by misolori** [comment]
Ok let’s try that limit to see how it goes. Would be nice to set the height so that if there are more than 9
The next row is partially visible to indicate more. 

For showing the install button, why is this useful in this case? Isn’t the point and the guidance to install the extension pack which install all the extensions? I don’t see the point of having that button visible.

**Comment by sandy081** [comment]
> Would be nice to set the height so that if there are more than 9
The next row is partially visible to indicate more.

Good idea.

> For showing the install button, why is this useful in this case? Isn’t the point and the guidance to install the extension pack which install all the extensions? I don’t see the point of having that button visible and defeats the purpose of the extension pack.

Don't want to limit and also want to give consistent representation of extension. Manage action is also available if the extension is already installed.

**Comment by sandy081** [comment]
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/10746682/78261541-a6ac1780-74ff-11ea-8c66-e85e2efdea0f.png">

**Comment by misolori** [comment]
> Don't want to limit and also want to give consistent representation of extension

But we've never showed this additional info before on the extension pack view, here is stable:

![image](https://user-images.githubusercontent.com/35271042/78261724-6ffcdf80-74b4-11ea-92da-edf6eef715bf.png)

IMO, the additional meta data feels unnecessary adds more visual noise to an already busy page.

**Comment by sandy081** [comment]
> But we've never showed this additional info before on the extension pack view, here is stable:

Its an improvement from stable. It will make it easy for me to browse an extension pack and install the extensions I want from that pack individually. Also the same for uninstalling.

**Comment by jwarkentin** [comment]
Instead of a double scrollbar, wouldn't it make more sense to make the section expandable with a button/link at the bottom middle or left of the list of extensions that just says "Show more" or "Show all extensions" or something to that effect? That way the readme is still visible but the user can choose to expand the extension list as part of the one scrollable content area.

**Comment by mattacosta** [comment]
Another option is to just have the list overflow horizontally and scroll left and right, instead of up and down.

**Comment by sandy081** [comment]
Filed https://github.com/microsoft/vscode/issues/94346 for expandable/collapsible section.

**Comment by connor4312** [comment]
It seems we determined the expandable/collapsible section wasn't feasible. Are there other approaches? I was watching Clarkio's stream today and he ran into this issue: https://clips.twitch.tv/CharmingLivelyPrariedogRiPepperonis

**Comment by jwarkentin** [comment]
@connor4312 I hadn't noticed the comment on the other issue that was opened to track it but it seems there was a misunderstanding based on the comment and the screenshot. There shouldn't be any feasibility problem as long as the expandable area is inserted at the top of the readme in the same scrollable area instead of expanding above the scrollable area and shrinking it.

**Comment by sandy081** [comment]
Lets continue the discussion in #94346
