### ISSUE TITLE
Optionally open clickable links in terminal without cmd/ctrl

### ISSUE THREAD

**Issue by reklamehusetwera** [microsoft/vscode#89982]
I think it was better before when you didn't have to hold cmd/ctrl to open links in terminal.

When developing nodejs software like servers with express, vuejs apps etc, the ui is almost always available by clicking a link in the terminal.

I am doing this all the time and it is annoying to always have to hold cmd/ctrl just to open a link.
Can you please add an option in the settings to turn the cmd/ctrl function off?

**Example:**

```bash
npm run serve
 DONE  Compiled successfully in 6028ms                                                         08:26:17


  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://10.0.1.141:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.
```

Then I am always trying to click the link and the notice `cmd + click to open link` pops up & is just freaking me out 😆.

Thank you very much.

Ref. https://github.com/microsoft/vscode/issues/23129

**Comment by Tyriar** [comment]
Sorry, we can't change this because we need to know when we can and can't send mouse events to the terminal. Additionally I hope to change the terminal to no longer validate links before hand but instead either validate while ctrl/cmd is held and hover happens or just not validate at all and allow ctrl+clicking anything for performance reasons.

**Comment by steffanhalv** [comment]
> Sorry, we can't change this because we need to know when we can and can't send mouse events to the terminal. Additionally I hope to change the terminal to no longer validate links before hand but instead either validate while ctrl/cmd is held and hover happens or just not validate at all and allow ctrl+clicking anything for performance reasons.

I understand that performance is important, but so is functionality and ui.
It would be nice if you could just drop sending mouse events to the terminal when clicking links and just open the link, then you could send mouse events to the terminal otherwise.

As you already have a check for this I dont think it would be a big deal to implement this as an option in settings. Then users chan choose between better performance or better ux.

**Comment by Tyriar** [comment]
@steffanhalv while I get where you're coming from, there are very good reasons not to add a setting for this:

- Just adding more settings for everything makes the product more complex for the user and us
- Links in the terminal behave inconsistently with basically everywhere else in the product
- Terminal mouse support would get weird and more complex, a hybrid approach of regular clicking links when not in mouse mode would confuse users
- The future will likely be not validating links at all and instead allowing ctrl+clicking on anything
