### ISSUE TITLE
Save functionality not working through shortcut

### ISSUE THREAD

**Issue by neerajsatineosoft** [microsoft/vscode#89992]
Issue Type: <b>Feature Request</b>

while saving from keyword by control+s. It is not saving my changes.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.
