### ISSUE TITLE
OneDrive can't merge changes

### ISSUE THREAD

**Issue by Omglolyes** [microsoft/vscode#90014]
We have written the needed data
Issue Type: <b>Bug</b>

Very often when i edit files in VSC that are located in my OneDrive folder, OneDrive will delete the the content of the file I'm workingon and create a file like: "[originalfile.basename] - [computername].[extension]"

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (1.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.7.0
php-debug|fel|1.13.0
php-intellisense|fel|2.3.14
remote-wsl|ms-|0.41.9
notepadplusplus-keybindings|ms-|1.0.5
powershell|ms-|2020.1.0

</details>
 into your clipboard because it was too large to send. Please paste.
Here is an example from explorer:

![image](https://user-images.githubusercontent.com/58954125/73757356-6b90a080-4769-11ea-95fb-d13484a8d842.png)

![image](https://user-images.githubusercontent.com/58954125/73759690-99c3af80-476c-11ea-80eb-291b052545cc.png)

**Comment by bpasero** [comment]
VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

Reading this issue, it seems to originate not from VSCode itself but rather one of these upstream components. As such, in order to resolve it, it would need to get fixed in the upstream component. I will go ahead and close this issue and kindly ask to report this issue to the upstream component if possible:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
