### ISSUE TITLE
Never surface the task.autoDetect setting somewhere it might accidentally be clicked on

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#90015]
This has proven to be a dangerous setting and shouldn't be offered to any user as a solution to a problem. Instead, the slow task provider notification should allow the specific task provider to be canceled on a one-off basis.

Alternatively, the quick pick could support streaming the entries as they become available.

**Comment by sandy081** [comment]
Accepted as candidate given that this  issue is impacting a popular extension and fix is low risk

**Comment by ivankravets** [comment]
Thank you so much for the quick fix! I'm really impressed.

Could we also ask you to take a look at https://github.com/microsoft/vscode/issues/65452? 80% of our instruments are implemented in [PIO Home](https://docs.platformio.org/en/latest/home/index.html) and we show them via WebView. Thre is a known issue where hotkeys do not work on macOS.
Thanks in advance!

**Comment by Gama11** [comment]
_(sorry if this is too off-topic, but it does seem somewhat related)_

Speaking of dangerous settings that can be set from a popup notification - there's also one for switching the terminal renderer to DOM, which can lead to problems as well.

>The standard renderer for the integrated terminal appears to be slow on your computer. Would you like to switch to the alternative DOM-based renderer which may improve performance?

This popup has always felt a bit "flakey", it shows up for me every now and then but I always ignore it. I think the following situation was almost certainly caused by it:

https://twitter.com/ManuelBieh/status/1225098833786437633

**Comment by alexr00** [comment]
@Tyriar for the previous comment.

**Comment by Tyriar** [comment]
@Gama11 the flakiness was just fixed recently https://github.com/microsoft/vscode/issues/86440
