### ISSUE TITLE
vscode.workspace.fs.readDirectory() ignores broken symlinks.

### ISSUE THREAD

**Issue by ericsnowcurrently** [microsoft/vscode#90031]
(for use in the Python extension)

If a directory has a broken symlink (target does not exist) in it then that symlink does not show up in the results from `vscode.workspace.fs.readDirectory()`.  I'd expect it to show up with a file type of just SymbolicLink.  Otherwise how would you know that the symlink is in the directory.

**Comment by bpasero** [comment]
`readdir` will now return symbolic links that are pointing to non existing paths as `FileType.SymbolicLink | FileType.Unknown`. Since we do not have any other way how to express an invalid symbolic link, I decided to go with that. Let me know if you have other thoughts.

Visually this means that broken symlinks now show up in the explorer and when you click, an error occurs:

![image](https://user-images.githubusercontent.com/900690/73834826-b1527500-480c-11ea-8e1a-78ee26f30a2e.png)

But as a user at least you can delete those now or at least be aware of them.

**Comment by bpasero** [comment]
Please verify in our next insiders release if possible.

**Comment by roblourens** [comment]
It looks like a broken symlink has type `64` which is `FileType.SymbolicLink`, and a non-broken symlink has type `65`, is that correct? `Unknown` is 0 so we can't do bitmask math with it.

**Comment by roblourens** [comment]
Looks like I double verified it with Connor, thanks Github for not refreshing the page

**Comment by bpasero** [comment]
@roblourens not sure I follow, if you found a bug, can you open a new issue? Bonus points for a failing test case.

**Comment by roblourens** [comment]
Maybe this was the expected result, but you can double check my work - https://github.com/microsoft/vscode/issues/91771
