### ISSUE TITLE
Integration Test: flaky debug breakpoints

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#90047]
From https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=66506&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=a83823bd-5dbd-5313-d0d6-a425f162cca0

```
 1) Debug breakpoints:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

```

**Comment by isidorn** [comment]
@bpasero thanks for filling this.
I pushed a potential fix for this. The problem is that I am using a command palette action that needs the editor to have focus, and I believe when integration tests are running that the editor can loose focus.
Now I am just reasgning focus to the editor to make sure.

If the fix does not solve the issue I am fine with removing testing this focus related commands, since they might not be the best thing for integration tests.
