### ISSUE TITLE
horizontall scroll bar on bottom of the editor screen is too small

### ISSUE THREAD

**Issue by tntc4** [microsoft/vscode#90071]
Issue Type: <b>Feature Request</b>

horizontall scroll bar on bottom of the editor screen is too small.
please give us option to setup the width / height of the scroll bars.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 6.1.7601

**Comment by tntc4** [comment]
@vscodebot it's not duplicate

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/30191#issuecomment-321554033 reveals that there's an undocumented setting to alter the vertical scrollbar size. Turns out there's an equivalent one for the horizontal one, e.g.

`"editor.scrollbar.horizontalScrollbarSize": 50`

In the JSON view of settings it is displayed faded and given a hover tip saying it's not known, but it does work:

![image](https://user-images.githubusercontent.com/6726799/73863687-5a629500-4838-11ea-9f2d-bccb81fd02f1.png)

**Comment by gjsjohnmurray** [comment]
See also #32192

**Comment by tntc4** [comment]
@gjsjohnmurray thank you, it works perfectly for my needs.
