### ISSUE TITLE
Improve quick pick for tasks since task providers can make it too slow.

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#90087]
We have a temporary fix for the release for https://github.com/microsoft/vscode/issues/90015 but we need to do something better long term.

**Comment by bpasero** [comment]
@alexr00 while working on quick access for tasks I noticed that we seem to be having 2 pickers for the same thing (?): 

**Task quick open:**
![image](https://user-images.githubusercontent.com/900690/76730180-fbf3d500-675a-11ea-9e44-2d62b0a617f8.png)

**"Run Task" picker:**
![image](https://user-images.githubusercontent.com/900690/76730194-02824c80-675b-11ea-9920-5e85f9373c57.png)

Is that intentional? Should the one be merged into the other?

**Comment by alexr00** [comment]
Yes, they do not share much code :( as part of improving the quick pick I will converge them.

**Comment by bpasero** [comment]
@alexr00 sounds good, please only change [`taskQuickAccess`](https://github.com/microsoft/vscode/blob/7f18a4bfeeb6374ea2e6c9f1c11ef8e29097fb2f/src/vs/workbench/contrib/tasks/browser/tasksQuickAccess.ts#L20) and leave the other one because I plan to delete those old ones soon.
