### ISSUE TITLE
Unable to "Save Workspace As..." deleted workspace

### ISSUE THREAD

**Issue by irvnriir** [microsoft/vscode#90090]
Issue Type: <b>Bug</b>

1. open Workspace file .
2. delete the file .
3. try "Save Workspace As..." .

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sandy081** [comment]
Is not this expected to fail if the workspace file is deleted?

**Comment by irvnriir** [comment]
@sandy081 , the workspace is loaded, isn't it the layout, foldings, .. ? its what you try to save .

**Comment by sandy081** [comment]
Its more than that, a workspace has settings, tasks, launches and some can have additional stuff in its workspace file.

**Comment by irvnriir** [comment]
@sandy081 , even if there is something that stay unloaded, in the file, after the VSC start . its still more logical to save the data that VSC have even without it, instead of just failing .

**Comment by sandy081** [comment]
Can be handled gracefully.

**Comment by bpasero** [comment]
Fixed via https://github.com/microsoft/vscode/commit/007d686e8b4c185462d1c4415342aa85e51fa363 

**Verification:** make sure you can "File" > "Save Workspace As..." picking the same name as the workspace that is opened in that window after it was deleted. If the workspace is not opened as file, it will create an empty workspace, otherwise it will preserve the contents.

**Comment by irvnriir** [comment]
@bpasero it doesn't allow to save, if you try to do so with the same name, it shows "File already opened", otherwise "Unable to read file <<old path>>" .

**Comment by sbatten** [comment]
@bpasero as soon as I delete the `.code-workspace` file on disk, the opened workspace becomes empty.

**Comment by bpasero** [comment]
@sbatten I think this is expected, but I let @sandy081 comment: when the workspace file gets deleted, we probably have a file watcher event that will cause the workspace service to update and then find no more workspace folders. I am not sure we can or should change that because essentially at that point the workspace has no folders anymore. If we think this is an issue, I would suggest to file a separate issue and still leave this one for verification.

**Comment by sandy081** [comment]
Agree with @bpasero

**Comment by chrmarti** [comment]
Works as per verification steps in https://github.com/microsoft/vscode/issues/90090#issuecomment-641112068. What is a bit unexpected is that the Explorer does not revert from empty to the workspace view when the content was preserved in an editor. Reloading makes the workspace folders appear in the Explorer.
