### ISSUE TITLE
Each automatic "on save" formatting preference appears to push a new entry onto the undo stack

### ISSUE THREAD

**Issue by jscheel** [microsoft/vscode#90100]
- VSCode Version: 1.41.1
- OS Version: macOS 10.15.2

Steps to Reproduce:

1. Enable trim trailing whitespace
2. Enable add trailing new line
3. Enable format on save
4. Type code into file that triggers each bit of formatting (add some whitespace at end, no newline, etc)
5. Save
6. Have to hit undo multiple times to get back to the last user-initiated change

Does this issue occur when all extensions are disabled?: Yes (Also on insiders)

I know there has been plenty of discussion about this in the past, but if feels like this changed again recently. Now I have to undo multiple times to get back to my last interaction. After testing enabling and disabling certain formatting features, it seems like each change is pushing a new entry onto the stack, instead of "do all on save formatting" being a single entry in the undo stack.

**Comment by jrieken** [comment]
This is fixed for trimming whitespace and formatting but not for code actions or the `onWillSaveTextDocument`-api because the latter two use the `WorkspaceEdit`-api which can make changes across multiple files. Anyways, I believe the concern is addressed and I am taking the freedom to close this with that

**Comment by jscheel** [comment]
@jrieken awesome, thanks for looking into this!
