### ISSUE TITLE
Allow custom editors to hook into Edit menu actions such as copy, undo, redo, ...

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#90110]
**Problem**
For custom editors, we currently support `undo`/`redo` using keyboard shortcuts. However you cannot undo and redo using the `Edit` menu in VS Code. 

Other commands like `copy` and `paste` only work in webviews because we do a `execCommand('copy')` call. This ends up copying the correct text but bypasses the custom `copy` command we have for webviews:

https://github.com/microsoft/vscode/blob/27a33ee6fe445094693df778ccec10f16a41deba/src/vs/workbench/contrib/webview/electron-browser/webviewCommands.ts#L59

**Proposal**
I believe that we need a way to either:

- Have the global `undo` / `redo` commands from the menu bar call into our webview specific code if a webview is focus

- Or allow webview to register replacement `undo` / `redo` commands in the `edit` menu when they are focused

/cc @bpasero, @alexdima, @sbatten

**Comment by mjbvz** [comment]
Also adding @kieferrm and @rebornix for notebooks

**Comment by bpasero** [comment]
I would think that Undo/Redo should use some global (workbench level?) thing that keeps track of all the undos/redos that are possible and then run them. This would be the beginning of workspace-level undo/redo. We can start simple and only let the text and custom editors add edits (e.g. not the file explorer which we could do later).

**Comment by alexdima** [comment]
Currently, `undo` and `redo` are completely owned by the editor, with a small workaround where they check if the current focused element is a `<textarea>` or `<input>` and then they invoke `document.executeCommand('undo')` and `document.executeCommand('redo')`.

To get a more collaborative story, I believe the best way would be to have a workbench service where various places can contribute undo/redo stack elements. This needs to be thought through such as to not disrupt the current undo/redo behaviour and IMHO this needs to be adopted somehow by the editor.

Here is the current undo/redo implementation for the editor (this is stored per text buffer): `vs/editor/common/model/editStack.ts`. By looking at the way that class is used already some requirements for such a workbench service can be devised:
1. the ability to remove everything. Currently, when someone calls `model.setValue()`, the undo/redo stack for that text buffer is removed entirely.
2. the ability to push a stack element and have it be "opened" such that subsequent edits can go in the same stack element.
3. the ability to undo/redo based on a resource, because as the focus moves in the workbench, undo/redo will work on the focused resource, and not on the chronological operations. i.e. typing in `a.ts`, then in `b.ts` and then moving focus to `a.ts` and running `undo` will undo the edits in `a.ts` and leave the edits in `b.ts` untouched.

To prevent disruption, I suggest that any work done here is done via a PR which we can test and merge in only when things work smoothly.

**Comment by mjbvz** [comment]
@alexdima I'm going to look into adopting the UndoRedoService within the model layer of custom editors, similarly to how you've adopted it in `TextModel`. Will copy you on the PR

**Comment by mjbvz** [comment]
Custom editors are now be using the `UndoRedoService`. I've also exposed a way for extensions to contribute the `label` used for changes

**Comment by mjbvz** [comment]
I know you've been working on workspace undo so I'm adding you to this issue. We can discuss how we would like to handle this for April

**Comment by mjbvz** [comment]
Fixed by #98288

**Comment by mjbvz** [comment]
To verify:

1. Use the custom editor samples: https://github.com/microsoft/vscode-extension-samples/tree/master/custom-editor-sample
1. Test both the text based and binary custom editor
1. Try using the menu to trigger actions such as undo, redo, copy, paste, and select all work
1. Also quickly test this in a normal webview (you can use the markdown preview and create a `<textarea>` html element in it)

**Comment by caponetto** [comment]
@mjbvz 
I can confirm that undo and redo from the File menu are working on the latest insiders build. 
However, cut, copy, and paste don't.
Are there any plans to support those operations and others that could be relevant for custom editors (e.g. Find and Select All)?

**Comment by mjbvz** [comment]
@caponetto Which operating system are you on? I see this working as expected on MacOS using a `<textarea>`  inside a custom editor

**Comment by caponetto** [comment]
@mjbvz Sorry, I meant for the custom editor that I'm working on, which deals with diagram components, not text.
These operations are working fine (on Fedora 32) for a `textarea` inside a custom editor.

I just wonder how can we leverage from these menus on other types of custom editors.
Currently, Ctrl+C and Ctrl+V are handled by us but Edit->Copy doesn't do anything because we don't have such a handler.

**Comment by mjbvz** [comment]
@caponetto Can you please file a new feature request for that. It sounds like a good use case that will likely require some new APIs for custom editors

For copy and paste, you could try using the [`copy` event](https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event) inside the webview

**Comment by lramos15** [comment]
@mjbvz Trying to verify this with the hex editor extension which listens to the undo and redo events which get fired for custom editors. I can execute undo and redo via keyboard shortcut, but not via the command palette. When you mean edit menu do you mean the right click menu?

**Comment by connor4312** [comment]
I was able to test the binary pawdraw editor but undo/redo didn't have an effect in the cat scratch editor. I'm not sure if I'm testing this correctly...

**Comment by mjbvz** [comment]
@lramos15 Thanks for testing. This is for the undo/redo commands in the edit menu from the title bar. I've opened #101553 to track the undo/redo command palette not working

**Comment by mjbvz** [comment]
@connor4312 Were you following https://github.com/microsoft/vscode/issues/90110#issuecomment-647822447?

I just tried on MacOS but see it working properly:

![Jul-01-2020 17-34-57](https://user-images.githubusercontent.com/12821956/86303647-52c5d300-bbc1-11ea-9957-24512e438bd1.gif)

**Comment by connor4312** [comment]
Yea. Actually testing it some more it looks like _can_ redo, but it's inconsistent, video: https://memes.peet.io/img/20-07-4a124599-3ddf-4c7a-aba0-8313019828bd.webm

Might an issue with the sample rather than vscode

**Comment by mjbvz** [comment]
I can't repo on windows either, even if trying to trigger these actions quickly. @connor4312 Can you make sure you have the latest extension sample version? Any specific repo steps?
