### ISSUE TITLE
Simple file dialog missing drive letter on windows local

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#90116]
- Normal non-remote window
- Enable the simple file dialog
- Save an untitled file
- The suggested path is missing the drive letter

![image](https://user-images.githubusercontent.com/323878/73906550-2c8d4880-4858-11ea-95eb-249ad86b6097.png)

**Comment by alexr00** [comment]
Only happens when saving a new file in an empty window.

@bpasero I think this is coming from the new filename for untitled files. In the past, the uri that made it to the file picker was of scheme "untitled" and the path didn't have a preceding slash. The simple file dialog then handled the untitled schema.

**Comment by bpasero** [comment]
This is a good catch, as a fix I am now falling back to `IRemotePathService#userHome` as suggested folder for untitled files.
