### ISSUE TITLE
UI Selection Duplication Issue HTML Tags

### ISSUE THREAD

**Issue by dhananjay1405** [microsoft/vscode#90146]
Whenever any HTML tag is selected, and cursor is moved using shift plus left/right key, a mirror selection of text happens in editor from position where it finds HTML end tag, thereby selecting non-continuous region

3-4 seconds GIF of screen potion is attached for precise understanding of issue

- VSCode Version: 1.41.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Just place cursor anywhere in HTML tag start
2. Press Shift + Right key
3. Go on selecting few character
4. Editor starts selecting text simultaneously from the HTML tag end position too

Does this issue occur when all extensions are disabled?: Yes
![vs-code-selection-bug](https://user-images.githubusercontent.com/43024754/73946289-ae927580-491b-11ea-95c6-5018d032b830.gif)

**Comment by bergamin** [comment]
Having the same issue:

Shift+End:

![image](https://user-images.githubusercontent.com/14339291/74258290-d8111f80-4cd4-11ea-9255-8562eb024078.png)

Shift+Arrow:

![image](https://user-images.githubusercontent.com/14339291/74258415-0858be00-4cd5-11ea-953f-6ff78b55c1ed.png)

Which will cause a mild rage after hitting delete in such a situation when the end tag is not visible

**Comment by octref** [comment]
This is a feature called "Mirror Cursor", which adds a multi-cursor when you are inside a HTML tag, and this is the expected behavior of multi-cusor.

You can turn this feature off by `"html.mirrorCursorOnMatchingTag": false" or press ESC to dismiss the multi-cursor before selection.

Or you can wait for implementing #88424 which will duplicate content changes, but not selection.
