### ISSUE TITLE
Running web out of sources is broken

### ISSUE THREAD

**Issue by jmbockhorst** [microsoft/vscode#90162]
Running web out of sources does not work as of b1c5e2f19b7c905f830388e823c9e12f33aab2ad because the `vscode-api-tests` extension cannot activate. When removing the changes from this commit to `extensions\vscode-api-tests\src\extension.ts` it works as expected. 

![folder](https://user-images.githubusercontent.com/44308390/73968383-3c03a480-48df-11ea-86e9-bec9336b37fa.png)

![notification](https://user-images.githubusercontent.com/44308390/73968389-3efe9500-48df-11ea-9db7-03e59e8f99d7.png)

Version: 1.42.0-insider (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
OS: Windows_NT x64 10.0.19546

Steps to Reproduce:

1. `yarn web`
2. The extension doesn't load and you cannot view any files.

**Comment by bpasero** [comment]
@mjbvz can you check

**Comment by bpasero** [comment]
Pushed https://github.com/microsoft/vscode/commit/df3764ab52029838a7a95ccba99cf85c50d72c9c as workaround.

**Comment by mjbvz** [comment]
Thanks for the quick workaround @bpasero! 

This was caused by b1c5e2f19b7c905f830388e823c9e12f33aab2ad.  `Url` and `TextEncoder` are  both global types in node but unfortunately the node TypeScript typings don't mark them as such. That's why I added the import instead.

I'll push a fix tomorrow so that we can properly run the extension in both browsers and node.

**Comment by Chatina73** [comment]
HP Steam, i have 2 os boot image not loadi5
