### ISSUE TITLE
"Auto Find in Selection = never" is ignored

### ISSUE THREAD

**Issue by rstarkov** [microsoft/vscode#90170]
- VSCode Version: 1.41.1
- OS Version: Win10

Steps to Reproduce:

1. Start code without extensions
2. Double check that Auto Find in Selection is set to "never"
3. Select two words
4. Press Ctrl+F

Expected: "find in selection" is off

Actual: "find in selection" is on, meaning I'm going to find exactly one match. Moreover, "find in selection" is just always on. Even when there is no selection. In 1.37.1 the button was disabled when there was no selection. Now the button is always enabled, and always activated.

Does this issue occur when all extensions are disabled?: Yes

**Comment by rstarkov** [comment]
The most recent version in which this setting worked the way I'd expect it to is 1.39.2.

**Comment by xgdgsc** [comment]
I also started noticing this annoying regression recently.

**Comment by xgdgsc** [comment]
This seems only happens for me on win10, ubuntu doesn' t have this issue.

**Comment by rebornix** [comment]
I didn't reproduce this issue on Windows or other platforms. Do you run into the same issue if you comment out all the settings temporarily?

**Comment by xgdgsc** [comment]
Removing `    "editor.find.autoFindInSelection": true,` from config works. Don' t remember when added that.

**Comment by rebornix** [comment]
@xgdgsc thanks, it means our code is not backwards compatible, will look into why that happens, thanks!

**Comment by rstarkov** [comment]
@rebornix did this get closed by mistake? I can confirm that this was exactly like xgdgsc described.

**Comment by Will-W** [comment]
I had the same issue, having never set this setting. Specifically:

Steps

- editor.find.autoFindInSelection set to its default value (never)
- Select a word (that appears multiple times on the page)
- Press ctrl+f to bring up the find box

Expected:

- `Find in selection` unchecked, and multiple results are found

Actual

- `Find in selection` is checked, and only one result is found (because it's searching in the one word selection).

If I explicitly set the setting to any of the three values (multiline, never or always), I get the correct result (as I understand it). _If I now reset the setting in the settings UI, I still get the correct behaviour_.

**Comment by greggman** [comment]
This is broken for me (although it's never worked for me). Wound up here looking for a solution

Here you can see nothing is selected. I press Cmd-F to find and search in selection is on. I turn it off, close the box., search again, it's back on. At the end I verify that auto-find-in-selection is set to never. I also testing with all extensions disabled.

![ScreenFlow](https://user-images.githubusercontent.com/234804/77521025-64625500-6ec5-11ea-8d8c-5efbf1b5e57a.gif)

**Comment by rebornix** [comment]
Root cause: Settings Editor (UI) doesn't support raw value validation. Please check the JSON content of your settings, you can find `editor.find.autoFindInSelection: true`, removing it can solve the problem. 

Internally in Editor, we will convert `true` to `always` thus it always take effect but the settings editor will not do validation/convert.

https://github.com/microsoft/vscode/blob/0e91558b2957b168189e48925e3085981a08b007/src/vs/workbench/contrib/preferences/browser/settingsTree.ts#L1037-L1043

**Comment by greggman** [comment]
Well I checked my settings.json and you're correct it was set to `true` even though the setting UI claimed it was set to `"never"`. I did not set it to true so some flow from where I started to now VSCode made it `true`.

Let me also point out though that right after I made that video I noticed the "search in selection" icon in the search UI doesn't always match the behavior of search. There were several times the button was highlighted "search in select" and yet it was not searching in just the selection.

![ScreenFlow](https://user-images.githubusercontent.com/234804/78323549-1fb57880-75ad-11ea-8393-a51704d2c3b7.gif)

**Comment by TobiasSekan** [comment]
~Same here~

~1. `Double left click` a word, to mark it~
~2. Press `Ctrl+F`~
~3. `Find in selection` is always active (and is reactivated)~

~Option: `never` or 'multiline`~

~* Still present min. since Version 1.43~
~* Same in Version 1.44 from 09.04.2020~

Oh :see_no_evil: , I found the Problem on my PC

The `user` and `workspace` settings was not the same as the `global` setting.

After correct this, it's work perfectly 👍

**Comment by roblourens** [comment]
Added generic checks that a setting value matches its schema type. If there is a mismatch it will look like this:

![image](https://user-images.githubusercontent.com/323878/78917001-e6b95000-7a53-11ea-8d1a-f284d3ef523a.png)
