### ISSUE TITLE
Can't install any extensions

### ISSUE THREAD

**Issue by DrDearg** [microsoft/vscode#90247]
- VSCode Version: version 1.42
- OS Version:Ubuntu 18.04

Steps to Reproduce:

1.Installed VSC as per https://linuxize.com/post/how-to-install-visual-studio-code-on-ubuntu-18-04/ 
2.Select Extension in activity bar
3. select any extension and install 
        Example result: Failed to install 'formulahendry.code-runner'.
4. does not matter what extension I try similar notification results

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)
