### ISSUE TITLE
Small but strange syntax highlighting bug (or feature)?

### ISSUE THREAD

**Issue by alexcheninfo** [microsoft/vscode#90279]
- VSCode Version: VSCode Insiders 1.43.0.
- OS Version: Ubuntu 16.04

When you open a file, the syntax highlighting is okay:

![Screenshot from 2020-02-08 14-02-10](https://user-images.githubusercontent.com/1061237/74080140-a18c9800-4a7b-11ea-9d2d-ff3787161e5e.png)

After a few seconds, some words change color (this happens with every theme):

![Screenshot from 2020-02-08 13-57-21](https://user-images.githubusercontent.com/1061237/74080182-19f35900-4a7c-11ea-9f12-d40536a2aac6.png)

Steps to Reproduce:

1. Install VSCode Insiders 1.43.0.
2. Open any file (e.g. `extension.ts`).

> Does this issue occur when all extensions are disabled?: Yes

**Note:** This doesn't happen with VSCode Insiders 1.42.0 or stable branches.

**Comment by usernamehw** [comment]
It's `unused` code decoration.

You can disable it:

```js
"editor.showUnused": false,
```

**Comment by usernamehw** [comment]
Might be https://code.visualstudio.com/updates/v1_42#_semantic-highlighting-for-typescript-javascript

**Comment by eamodio** [comment]
I looks like those lines are getting dimmed out because those imports are not used. Can you confirm that is the case?

**Comment by madiodio** [comment]
@eamodio I doubt OP's code snippet is getting because of unused import (spot the `vscode` import). Anyway @usernamehw pointed out the right setting to disable it. IMHO this should be disabled by default, the syntax highlighting was so off and confusing I thought the whole VSCode was broken. In screenshots below, notice how it _arbitrarily_ chooses to tokenize React Components when enabled:

<img width="961" alt="Screen Shot 2020-02-18 at 11 20 14" src="https://user-images.githubusercontent.com/15022248/74732328-e4036100-5241-11ea-85cf-b7c45fb2281b.png">

<img width="956" alt="Screen Shot 2020-02-18 at 11 20 52" src="https://user-images.githubusercontent.com/15022248/74732333-e665bb00-5241-11ea-844c-4f50e1429b6c.png">

Also related to #90853, #89337 and #90379
