### ISSUE TITLE
Config to limit/disable the new Untitled tab auto-naming

### ISSUE THREAD

**Issue by Kowbell** [microsoft/vscode#90378]
It would be nice if we could disable or set a shorter limit for the the new [untitled editor titles improvement](https://code.visualstudio.com/updates/v1_42#_untitled-editor-improvements) in 1.42. I've seen a few requests for a way to disable this behavior[1][2]. I'd also request a config option to set a limit shorter than the default 40 characters we have right now - I appreciate being able to distinguish between untitled tabs, but as they are now they can take up a _lot_ of space.

1 - https://github.com/microsoft/vscode/issues/90339#issuecomment-584129058
2 - https://github.com/microsoft/vscode/issues/89751#issuecomment-583726368

**Comment by akbyrd** [comment]
I'd also like to disable this. It's a pointless distraction for me personally.

I use untitled files as a scratch space and I'm frequently pasting log snippets and such into them. I have no need for that to be the name of the editor.

![image](https://user-images.githubusercontent.com/484784/74288851-6049f180-4ce2-11ea-863a-238e9e879caa.png)

**Comment by yankyhoffman** [comment]
Not only is having the first line of a file in the file tab not visually appealing. It also expands the tab and makes it harder to navigate all other opens tabs

**Comment by IvanShvetsAMD** [comment]
Disabling would allow at least for:
1) Keep the contents hidden from view
2) Allow more tabs to be opened within the same size of the VS Code window
3) Keep the layout simpler

**Comment by bpasero** [comment]
I added a new setting: `workbench.editor.untitled.labelFormat` with these possible values:
* `content` (default): The name of the untitled file is derived from the contents of its first line with a fallback to the name in case the line is empty or contains no word characters.
* `name`:  The name of the untitled file is not derived from the contents of the file.

I am open for suggestions about the name of this setting and the possible options.

**Comment by jpark-mdsol** [comment]
This was a bit of a jarring UI change, which prompted me to search for reported issues. Happy to see your PR is up, thank you @bpasero .

The previous behavior of naming unsaved files `Untitled-1,2,3`, etc resulted in a consistent tab width size. I have the misfortune of a legacy codebase, and in tracing through code I have a lot of open tabs. Navigating visually became harder when fewer tabs are able to be displayed, because I now have to remember order of tabs which are scrolled horizontally offscreen. (I use ctrl+tab in left-to-right order, and have two split panes each taking half the screen)

Could `option 2 (name)` be reinstated as the default? Then the new behavior is effectively feature flagged.
