### ISSUE TITLE
Failed to connect to the remote extension host server (Error: ) 1.43 Version

### ISSUE THREAD

**Issue by ebadilla10** [microsoft/vscode#90387]
Issue Type: <b>Bug</b>

I'm getting "Failed to connect to the remote extension host server (Error: )" when I try to access via ssh to a remote server.

I use VSCode Insiders 1.43. (It was working well on Friday and now Monday it's not working). Co-worker next to me doesn't have  the problem and he's using 1.41 version. We both use Insiders because need to connect to a arm server.

VS Code version: Code - Insiders 1.43.0-insider (beaf391bc53136912e4f0bbdfb7844ad954247db, 2020-02-07T05:29:40.363Z)
OS version: Windows_NT x64 10.0.17134
Fetching remote diagnostics for 'SSH' failed.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

Fetching remote diagnostics for 'SSH' failed.
</details>Extensions: none

**Comment by maxned** [comment]
I am also running into this issue. I traced the issue to the corporate proxy blocking access to the HTTPS version of `az764295.vo.msecnd.net`. With the new VS Code update it seems that the remote development extension tries to update the vscode-server on a VM using the URL [https://az764295.vo.msecnd.net/stable/ae08d5460b5a45169385ff3fd44208f431992451/vscode-server-linux-x64.tar.gz](https://az764295.vo.msecnd.net/stable/ae08d5460b5a45169385ff3fd44208f431992451/vscode-server-linux-x64.tar.gz). 

I was able to manually update the server extension using instructions found [here](https://github.com/microsoft/vscode-remote-release/issues/78#issuecomment-522210474, placing the new files into the `~/.vscode-server/bin/<commit-id>` folder.

I presume that VS Code previously used HTTP instead of HTTPS.

**Comment by roblourens** [comment]
Nothing has changed with the url or the server as far as I know. And if the download fails, then it should download the server locally instead.

@ebadilla10 could you share the output of the Remote-SSH output channel?

**Comment by thernstig** [comment]
@roblourens I got this error message when `AllowTcpForwarding no` had been set, changing it to `AllowTcpForwarding `local` made it disappear.

Could it be that some recent changes in VS Code has made the error `Failed to connect to the remote extension host server` show up in incorrect `AllowTcpForwarding` config? (I know from experience that the error was something else a couple of months ago, but maybe something recent changed so that this new error message is also tied to local forwarding being disabled.)

**Comment by roblourens** [comment]
I think it makes sense to get that error when `AllowTcpForwarding` is disabled. Was it different before?

**Comment by thernstig** [comment]
Personally, it was a long time ago for me I had to change `AllowTcpForwarding`. This was against a new host where I saw this and immediately checked `AllowTcpForwarding`. My vague memory tells me however that the past times I had problem with `AllowTcpForwarding`, the message was something different. So I have no idea :)

**Comment by roblourens** [comment]
No response from OP, closing this one
