### ISSUE TITLE
It's hard to move from parent folder in nested collapse folder.

### ISSUE THREAD

**Issue by mnini** [microsoft/vscode#90436]
When you have collapsed folder with longer path, it's trouble to move to some folder on the path...

**Comment by isidorn** [comment]
Can you be more specific and suggest a potential sollution?
I have no clue what exactly are you reffering to.

**Comment by mnini** [comment]
project/i18n/help/lang/stuff
if it's the only file in tree ( stuff ), then there is problem with moving it into /help/ directory, and it impossible to create file in help folder in this tree without using terminal, atleast I didn't found out.

**Comment by mnini** [comment]
Potential solution is to have right click and expand folder...

**Comment by xendren** [comment]
Any way to upvote this?  So the only work around is to train myself to always create the folders in a specific order and remember to add a dummy file in each folder or the UI forgets the folder hierarchy?  Back in the stoneage, this type of file manipulation was the centerpoint of why any user would choose Windows over command-line.  Thirty years later the feature isn't worth adding?  This is still Microsoft, right?  It feels like a slap in the face since my file tree ALWAYS defaults to collapsed yet someone spent the time to add a button to the right-click menu to allow me to "Collapse Folders in Explorer".  <sarcasm>Wow. Thank you to the bored guy on the 3rd floor that gave us that button.  That one kept me up at night. </sarcasm>

**Comment by mnini** [comment]
Just use OS native thing to brow directories and add button open in current window of VSCode in context menu...

Ouch my god. It's terror.
