### ISSUE TITLE
Investigate into Linux Orca screen reader

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#90446]
Should work nicely with Electron 7, might need `--force-renderer-accessibility` flag  passed.

Reference: https://github.com/microsoft/vscode/issues/88893

fyi @jvesouza @webczat @ndarilek

**Comment by jvesouza** [comment]
Version: 1.43.0-insider
Commit: 8d17dc1e84d53f5fd4ed0d05fabaa3062259633d
Date: 2020-02-10T10:04:08.445Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.5.2-arch1-1

Maybe I'm doing something wrong, but I couldn't find in the file explorer a simple way to identify the name of the folder being displayed.
I can navigate the files with the arrows, expand, colapse and open folders without problems.

To identify the name of the displayed folder I use an orca feature called flat review mode. It works, but it is not in my opinion very natural.

**Comment by webczat** [comment]
and there are some slowdowns like when closing editors. but note that both of that could be chromium related and it is even possible they are already fixed. I do not usually experience such things in actual google chrome, but it is version 80 (stable) or 81 (unstable).

**Comment by jvesouza** [comment]
It would be great if VSCode could adopt version 8 or perhaps version 9 
of electron since they use more recent versions of chromium.

**Comment by isidorn** [comment]
We always try to update the use the later chromium and electron version. However Electron usually has some issues that are blockers so it takes quite some time before we test, fix and make sure an Electron version is working fine. Thus we do want to use Electron 8 and 9, but that will happen in one of the following milestones.

As for the name of the explorer: you can focus on the title area of the explorer via Shift + tab to read that out. Or you could `Ctrl + R` to browse through recent workspaces, just press up and the current one should be read out.

For the slowdownes: if you also see this in previous Chrome versions than that is probbly the same issue and should be fixed once we adopt to later Electron.

I just tried our Orca on Linux with VS Code (with the flag `--force-renderer-accessibility`) and I have some questions for you:
1) When you focus on the Editor is the text nicely being read out when you navigate left, right, up? It is not being read out for me, only when I do some editing the edited characters get read out. Do I have to setup Orca specially or what am I missing here?
2) Is it possible to configure Orca that it just display what it reads and that it does not read it out? This is just easier for me, since I use NVDA and VoiceOver like that
3) Reading in other parts of the UX outside the Editor seems to work fine

**Comment by webczat** [comment]
Hmm if you enable accessibility in editor settings it should work fine provided you are on electron 7. on 6 it has some issues because it didn't read when pressing up/down arrows.
But you have to enable it explicitly in addition to adding the --force-renderer-accessibility flag.
Things work fine except that sometimes it seems to join adjacent lines when reading by up/down arrows. not quite sure how it is possible and what it is about, try editing xml files.

**Comment by isidorn** [comment]
I have accessibility enabled via vscode setting, i am on electron 7, and I have passed the `--force-renderer-accessibility` when launching vscode from the command line.
Looking at the docs here https://wiki.gnome.org/Projects/Orca/Chromium
I seem to be missing having ACCESSIBILITY_ENABLED=1 in my environment.
Trying it out...

**Comment by ndarilek** [comment]
Also note that you have to be on Orca master. The version shipped with 
your distro packages likely won't work.

**Comment by webczat** [comment]
oh sorry, forgot about that detail. :) yes, it needs to be orca master. not necessarily latest commit, but definitely would be the best.

**Comment by isidorn** [comment]
@ndarilek @webczat ok thanks. I was just trying the orca that I have as part of my Ubuntu 18.04.
Let me search for how to get latest orca. If you have some pointers let me know :)

**Comment by ndarilek** [comment]
Sorry for the reply spam. Probably should have bunched the last two, but 
I'm only now drinking my coffee and increasing the number of cylinders 
my brain is firing on. :)


The editor area works very well overall for me, with a couple 
exceptions. I hesitate to report them primarily because Chromium support 
is so new, I know you're stuck on Electron, and my assumption is that 
issues will go away as the Electron version bumps. Not sure how to pin 
down root causes in that environment, but in any case:


1. I also notice the off-by-1 line reads. This happens primarily in the 
SCM commit message editor for me. I also sometimes have the entire 
commit message read when arrowing between lines. I think this happens 
when I hit the end of the text region, so if I write a commit message 
and attempt to read the last line, I'll hear the entire message.


2. I can't use Alt-# to navigate between editors in a group if the 
editor widget has focus. Even if I switch to browse mode in Orca, Alt-# 
doesn't switch editors unless I move the cursor out of the editor 
widget. This is probably the biggest feature I miss, since Ctrl-tab is 
slower and requires many more keystrokes.


Thanks.

**Comment by webczat** [comment]
first issue confirmed here.

**Comment by webczat** [comment]
Issue with alt+# not working is not confirmed for me, although the change of editor is not announced.

**Comment by ndarilek** [comment]
You're right. If I alt-tab out and back in, I do discover that I'm in a 
new editor by virtue of the window title being read. It is automatically 
read if focus is outside the editor window, though.

**Comment by isidorn** [comment]
1. Do you also see that behvior with a simple Chrome textArea, in this example site for instance? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea  If yes that means it is a Chrome bug and I can file it against the Chromium repository
2. I personally always use `Ctrl + E` to navigate between editors. Since after that command I can type to filter editors or go up / down to go through the open ones. Not sure if that works for you. Alt-# navigation I am not aware of, is that something which is Orca specific?
3. I am having issue setting up Orca with latest from master since I am not a Linux user primarily. If there are steps for this let me know.

**Comment by webczat** [comment]
note that the bug, even if it is chrome specific, could disappear already. none of us is using chromium 78.x, and that is the one underlying electron 7.

**Comment by isidorn** [comment]
@webczat we can easily double check that if you try to open that site with different Chrome versions and check how the `<textarea>` is read out between versions. Or if I succesfully setup latest Orca :)

**Comment by ndarilek** [comment]
With regard to 2: Alt-1, Alt-2, etc. are VSCode keybindings for jumping 
to the specific editor at that position. So definitely not an Orca 
issue, though maybe there's something about not speaking window title 
changes when a textarea has focus. I'd be interested in knowing whether 
that works under NVDA.

**Comment by isidorn** [comment]
@ndarilek it works fine on Windows and NVDA. However I use the shortcut Ctrl-1, Cltr-2 there. Once the Editor gets focus NVDA properly reads out the content.

**Comment by ndarilek** [comment]
Isn't ctrl-1, ctrl-2, etc. for jumping between editor groups rather than 
instances within a group?


Right now I have a project with subsystems in Kotlin and Elixir. I have 
Kotlin files in group 1, Elixir files in 2, and .eex files (Embedded 
Elixir, HTML templates essentially) in group 3. So if I'm editing the 
Kotlin subsystem, I press Ctrl-1, then Alt-1, Alt-2, Ctrl-tab, whatever, 
to navigate between Kotlin files. Ctrl-2 brings me to my Elixir source, 
and Ctrl-3 to my templates. This is a nice setup, since generally I'm 
working on a specific area of the project, so I can pop into an editor 
group and have all my files for a given subsystem open. Previously, when 
working in Gedit, I just had a giant sprawl of tabs open, with HTML 
templates interspersed with several different language files for several 
different microservices. Quickly became an unmanageable mess.


It's great that there are multiple workflows. I guess my point is that, 
if Alt-1, Alt-2, etc. is a usable command and works under NVDA, it 
should also be made to work under Orca. That there are workarounds and 
alternatives is a nice thing, but they're there to support multiple 
workflows, and I'd very much like to see this way of doing things made 
accessible.


Thanks.

**Comment by jvesouza** [comment]
> I just tried our Orca on Linux with VS Code (with the flag `--force-renderer-accessibility`) and I have some questions for you:
> 
>     1. When you focus on the Editor is the text nicely being read out when you navigate left, right, up? 
It is not being read out for me, only when I do some editing the edited characters get read out. Do I have to setup Orca specially or what am I missing here?
Yes, I have no dificulties to access the editor.
Probably you're using aa wrong version of orca. I don't use ubuntu so I don't know how to get the most current version of orca for this distro. I can however ask on the orca list if anyone has any tips on how to do it.
If I'm not mistaken you are using Ubuntu 18.04 version, are you?> 
>     2. Is it possible to configure Orca that it just display what it reads and that it does not read it out? This is just easier for me, since I use NVDA and VoiceOver like that
> Orca has a series of options that can be configured with, for example, verbosity, punctuation, speed and much more. These settings are on the orca preferences screen which can be accessed by pressing the orca key together with the space bar.
>     3. Reading in other parts of the UX outside the Editor seems to work fine
> 
> 
> We always try to update the use the later chromium and electron version. However Electron usually has some issues that are blockers so it takes quite some time before we test, fix and make sure an Electron version is working fine. Thus we do want to use Electron 8 and 9, but that will happen in one of the following milestones.
> 
> As for the name of the explorer: you can focus on the title area of the explorer via Shift + tab to read that out. Or you could `Ctrl + R` to browse through recent workspaces, just press up and the current one should be read out.
> 
> For the slowdownes: if you also see this in previous Chrome versions than that is probbly the same issue and should be fixed once we adopt to later Electron.

**Comment by jvesouza** [comment]
>     1. Do you also see that behvior with a simple Chrome textArea, in this example site for instance? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea  If yes that means it is a Chrome bug and I can file it against the Chromium repository
Using version 82.0.4055.0 of chromium I have not found any problems on this site.> 
>     2. I personally always use `Ctrl + E` to navigate between editors. Since after that command I can type to filter editors or go up / down to go through the open ones. Not sure if that works for you. Alt-# navigation I am not aware of, is that something which is Orca specific?
> I can use ctrl + e to select the editor, but it seems that it does not display only active editors, I need to understand it better. I can also use alt + 1, alt + 2 and etc., but orca does not announce the name of the editor in focus when I use these keys.

**Comment by isidorn** [comment]
@jvesouza yes I am on Ubunutu 18.04.
I have issues triggering the Orca preferences menu since it requires the Orca modifier key + space. Since I am using a Linux VM on my Mac the Orca modifier key is either Ctrl or Insert + space. However whatever I press the preferences are not triggered. And to change this modifier key I have to open the preferences. My questions is: is there any other way to open the preferences?

Ctrl + E shows the whole editor history, not only the open editors.
I do not know why orca would not announce when using alt + 1, alt + 2. I can investigate further, though that does not seem like something that is under our control (since we properly set the ariaLabel on the item that gets focus). So I think this is an Orca issue.
Another alternative to achieve this is: F1 > focus on open editors view than navigate through the via via up / down and press Enter to open the editor you are interested in.

**Comment by ndarilek** [comment]
Interestingly enough, if the editors are empty, it seems to speak new 
titles just fine.


I sent a message to the Orca mailing list. Hopefully we'll get more help 
figuring this out.

**Comment by isidorn** [comment]
Great thanks. I can also join the Orca mailing list if you think that makes sense.

**Comment by ndarilek** [comment]
Up to you. It's fairly low-volume, and not the dumpster fire many 
blindie lists turn into. :) Joanmarie is super responsive, so if you're 
actively working to improve this, it would definitely shorten the 
iteration cycle on fixing issues in either Orca or Chromium.

**Comment by jvesouza** [comment]
You can start orca using the -s switch to activate the preferences.


Use the terminal or press alt+f2,  type 'orca -s' without the quotes and 
press the enter key.

**Comment by jvesouza** [comment]
I am configuring VSCode to work with dotnet projects. Now, when I start VSCode, I get the following alert:

Warning: Required assets to build and debug are missing from 'vscode.dotnet'. Add them?

I just can't find a place that I can click to have the assets installed.

**Comment by ndarilek** [comment]
Not sure if this is the same thing, but I use VSCode to develop Godot 
games, and every time I open a project, I get an error about the 
GDScript language server not being available and asking if I want to 
start the editor. I reach this alert by pressing Ctrl-End, then I can 
usually tab or arrow to a button to start the editor and close the 
notification.


This is probably a more generic accessibility issue, and it definitely 
confused me for a time. Not sure if those alerts are modal dialogs or 
something else.

**Comment by jvesouza** [comment]
In fact, ctrl + end puts the focus on the alert and after that I can use 
tab or shift + tab to navigate between the possible actions.

**Comment by jvesouza** [comment]
; With regard to identifying the folder being explored, I found the following behavior:

* I press crl + shift + e and the focus jumps to the file explorer. However, the name of the focused file is not announced by orca.

* I press shift + tab and the focus jumps to the file explore session, at least it is what orca announces.

* I press CapsLock + i, which on my machine is the command used to announce the current line in flat review mode. Orca announces the name of the folder being explored and also announces several buttons.

**Comment by isidorn** [comment]
@ndarilek I have joined the list. I will send an email there introducing myself once I am added by the admin.

@jvesouza 
* those are notifications, which are not blocking modal dialogs. Once you hear them you can focus on them via the command `notifications.focusToasts`. Please note that this command does not have a default keybinding, so you will have to assign something to it via Preferences > Keyboard Shortcuts. In tomorrow's vscode insiders this "Focus Toasts" command will also be in the F1 command palette to make it more discoverable. Once the focus is on the toasts you can navigate up / down and 
tab to focus into a toast and go throught the buttons.
* For the explorer: I have changed the aria label of the explorer from "File Explorer Section" to "File Explorer: NAME_OF_FOLDER", so now it should be better. Check it out in vscode insiders tomorrow. And let me know.

Please let me know if there are more issues / blockers.

**Comment by isidorn** [comment]
`orca -s` works for getting to preferences - thanks!

**Comment by jvesouza** [comment]
Regarding install the latest orca, I received the following response:

For Orca master in Ubuntu 18.04 I copied from this mailinglist the following:


1. Enable the Canonical repositories.
* Open software updater.
* Click the Ubuntu tab.
* Check the box source repositories.
* Click the other software tab.
* Check the boxes next to Canonical partners and Canonical partners source repositories.
* Click close.
* When requested, click reload cache.

2. Open a terminal window, press Alt+Control+T.

3. Install git, type or copy and paste the following command and press Enter.
sudo apt-get install git

4. Install build dependencies. Type or copy and paste the following command and press Enter.
sudo apt-get build-dep gnome-orca

* Answer yes to the ‘do you want to continue?’ prompt.

5. Get the orca source code. Type or copy and paste the following command and press Enter.
git clone https://gitlab.gnome.org/GNOME/orca.git

6. Build and install orca.
!!WARNING!!
Follow the steps below exactly as typed. Doing something else will mess up your environment and cause file permission problems.
* Change to your orca repository created in step 5. Type the following and press Enter:
cd orca

* Configure orca source. Type or copy and paste the following command and press Enter.:
PYTHON=/usr/bin/python3.6 ./autogen.sh

* build orca. Type or copy and paste the following command and press Enter.:
make

* Install the built binaries. Type or copy and paste the following command and press Enter.: :
sudo make install

7. When install is complete, restart the system.

After you can keep up with Orca master by executing the following commands in a terminal:
* first change to the orca folder
cd orca
* look for uptdates
git pull
* to see what changes are made
git log
* to update
PYTHON=/usr/bin/python3.6 ./autogen.sh
make
sudo make install



Also you can read more in the following link:
https://mail.gnome.org/archives/orca-list/2014-September/msg00221.html

**Comment by isidorn** [comment]
@jvesouza awesome steps! I did it and now it works great!

I can reproduce the issue that Orca does not read the editor title when navigating via alt + 1, 2...

So I see two issues with the Orca experience which we can try to fix on the VS Code side:
1. VS Code does not detect when Orca is attached, thus you have to manually set 	`"editor.accessibilitySupport": "on"`. If VSCode auto detected Orca this would not be required
2. You have to pass the `--force-renderer-accessibility `. We could automatically pass this flag to Electron from VS Code on Linux always. I can also look into this.
3. Might you know when does Orca plan to release the current Master version? Asking because I am thinking of updating our Accessilibity Docs for Linux so we have this covered. I can also ask this on the mailing list.

As for other minor issues, it would be great if we open seperate issues and ping me on them. In this issue I would like to focus on the general getting started experience.

**Comment by isidorn** [comment]
Edit: first 2 issues are acutally the same issue. Chrome does not detect Orca, and thus you have to pass one flag for chrome and one flag for VS Code. Unfortunetely we can not fix this on the VS Code side.

Do any of you know if this is still the issue with latest Chrome, that this `--force-renderer-accessibility` flag is needed? If yes I can file an issue to Chromium though I would be surprised if they are not aware of this.

**Comment by ndarilek** [comment]
I think the deeper issue is that there isn't a way to detect screen 
reader use under Linux. So until there is, the flag is necessary. But 
this is all very new, and many of us who use Orca don't necessarily know 
much about the Chromium support, so I'd recommend asking on the mailing 
list.


Thanks for all the work on this!

**Comment by webczat** [comment]
note that the accessibility work for linux at chromium side is not finished. There is actually a way to detect screenreader being enabled using gsettings, I am almost certain QT does this because I saw the effect of this once. Even if I am wrong, the fact that --force-renderer-accessibility has to be passed may be intentional like guarding the whole accessibility stuff between something like --enable-experimental flag, until the support matures. So I wouldn't necessarily make that go away.

**Comment by jvesouza** [comment]
The orca is updated along with the gnome. The next update to gnome is 
scheduled for March 11, when it will move from version 3.34 to 3.36. The 
same must happen with the orca.

To check the current version of orca we can use the -v switch when 
running orca.

orca -v


Orca also has a help mode activated by combining orca_key + h.

When this mode is activated the orca version is announced.


On 2/13/20 1:03 PM, Isidor Nikolic wrote:

>  > @jvesouza <https://github.com/jvesouza> awesome steps! I did it and > 
now it works great! > > I can reproduce the issue that Orca does not 
read the editor title > when navigating via alt + 1, 2... > > So I see 
two issues with the Orca experience which we can try to fix > on the VS 
Code side: > > 1. VS Code does not detect when Orca is attached, thus 
you have to > manually set |"editor.accessibilitySupport": "on"|. If 
VSCode auto > detected Orca this would not be required 2. You have to 
pass the > |--force-renderer-accessibility |. We could automatically 
pass this > flag to Electron from VS Code on Linux always. I can also 
look into > this. 3. Might you know when does Orca plan to release the 
current > Master version? Asking because I am thinking of updating our > 
Accessilibity Docs for Linux so we have this covered. I can also ask > 
this on the mailing list. > > As for other minor issues, it would be 
great if we open seperate > issues and ping me on them. In this issue I 
would like to focus on > the general getting started experience. > > — 
You are receiving this because you were mentioned. Reply to this > email 
directly, view it on GitHub > 
<https://github.com/microsoft/vscode/issues/90446?email_source=notifications&email_token=AAPRNESG74BIVHMO4Y3KYB3RCVVNFA5CNFSM4KS7QFK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELVRW6Y#issuecomment-585833339>,

**Comment by jvesouza** [comment]
A feature that the orca has and that can help in identifying problems is 
the debug option.

When debug is activated, orca writes to a file all events received from 
the accessibility layer.


To activate debug, execute the following command at the terminal:


orca -r --debug-file = <filename>

where <fileName> is the name of the file to which events will be recorded.

**Comment by isidorn** [comment]
Thanks a lot for all the help and the details.
So it seems like orca version `3.35.4`is required for all to work.

I plan to do the following change:
If `editor.accessilibtySupport` is turned on in VS Code that we automatically forward the `–force-renderer-accessibility` flag to Chrome. So the users would no longer have to pass the –force flag. That should make it easier imho.

**Comment by ndarilek** [comment]
Hey, asking this here because users of accessibility are likely to need 
the keyboard more, and this issue is a bit odd.


After I install extensions, I'm told to reload the VSCode window. If I 
use the command pallet, Orca tells me that the Reload Window command is 
bound to Ctrl-R. But Ctrl-R does something that isn't reloading the 
window. It seems to open a list of recent projects.


I know that keyboard commands can be conditional. I'm wondering if a 
condition of some sort is attached to Ctrl-R, and that isn't being 
reflected in the command pallet? Would be nice if I could reload my 
window with a key, particularly as I try to figure out which extensions 
I want for my workflows.


Thanks.

**Comment by webczat** [comment]
if you do something with some extension and it says that it requires reload, then the button used to install/manage extension turns to "reload required". Also I believe installation of an extension usually does not require a reload.

**Comment by ndarilek** [comment]
Huh, they all generally tell me a reload is required. Interesting.


Anyhow, thanks, I'll just use the command pallet for now as it's quicker 
than finding a button.

**Comment by isidorn** [comment]
Yes installing extensions usually does not require the reload, however sometimes it does.

For the reload and recent workspaces overload on keybindings I have created this issue https://github.com/microsoft/vscode/issues/90698 
You can follow it for more details.

As a workaround for now you can Preferences > keyboard shortucts and assign a keybinding to the Relaod Window one. Or just remove the keybinging from the recent workspaces command.

**Comment by ndarilek** [comment]
In the keyboard shortcut list, Orca speaks "when is is development" for 
the reload keybinding. At the risk of sounding like a lolcat, when is 
development? :) Anyhow, that the command pallet presents the keyboard 
shortcut is a bit misleading. Not sure how "is" conditions can be 
handled there, but as a new user, it definitely seemed like something I 
should be able to use everywhere.

**Comment by isidorn** [comment]
Ok, I have pushed the following change:
If a user on linux sets `"editor.accessibilitySupport": "on"` we will ask him to restart vscode and we will automatically pass the `force-renderer-accessibility` flag to VSCode.
So now the setup should be simpler IMHO. You can try out this flow from Monday.

Thus I am closing this issue. For other feedback feel free to continue commenting here, or also feel free to create new issues. Thanks a lot!

**Comment by isidorn** [comment]
@ndarilek haha, yeah that is quite confusing for all users. IsDevelopment is an internal out of source version of vscode that we reload a lot.
And that is one of the reasons why we do not have a keybinging actually for Insiders and Stable, since Reload should not happen that often. But you can always assign a custom keybinding.

The `is` pronaucting is our when clauses for keybindings.

**Comment by isidorn** [comment]
Also I plan to update our accessibiltyDocs with the Linux Orca setup once decide if we will ship next stable with Electron 7.

**Comment by isidorn** [comment]
One more question:
I was checking out how Orca is handling word navigation in VS Code. And everytime I navigate by word via `Ctrl + Left / Right` Orca would only read the character after the cursor not the whole word. How do you make Orca read the whole word I just navigated to?
Also do you see issues with Word navigation in VS Code while using Orca?

**Comment by webczat** [comment]
definitely not. although that said it seems like it often reads more than it should. When focusing on first or last word of a line it seems to also read the part of previous/next line. but not quite sure

**Comment by ndarilek** [comment]
Is there a recommended, accessible way to use terminals? There seems to be an input area, and an area where terminal output is rendered, but they aren't always adjacent. Does this work well under NVDA and need adaptation for Orca, or is it awkward there too?

**Comment by webczat** [comment]
Actually in NVDA I would just be using the numpad keys. In orca it seems to also work to some degree except you are not focused correctly in flat review, and you see other things in the window that way.

**Comment by isidorn** [comment]
Adding @tyriar for the terminal accessibility question.
When I use our terminal with VoiceOver the input is nicely read out, and the output is only read out when it comes. Not sure how to re-read it later. @Tyriar might know more.

**Comment by alex19EP** [comment]
hello @ndarilek. you can use Ctrl with up or down arrow to read lines.

**Comment by alex19EP** [comment]
also @isidorn. is force-renderer -accessibility is needed in current insiders? i want to ditch my code wrapper.

**Comment by isidorn** [comment]
@alex19EP no, it is not needed.
If for some reason it does not work please let me know. Thanks!

**Comment by Tyriar** [comment]
Updated the docs to mention terminal navigation mode (ctrl+up/down) https://github.com/microsoft/vscode-docs/commit/3c0e8d4c62c49c44abb8becdbb8528613709a4e3

**Comment by ndarilek** [comment]
Cool. Another thing, and sorry if this shouldn't be a grab bag of random 
accessibility quibbles. :)


I'm working on a fairly complex project with microservices in a few 
different languages. Sometimes I make several sets of changes, and want 
to split them into logical commits. It can be hard to limit a set of 
changes to a single logicl commit because often they need to be tested 
together, and one won't make much sense if another is impractical or 
unneeded. Right now I:


1. Press Ctrl-Shift-G to jump to the VCS changes view.

2. Tab to my changes.

3. Find a change in the tree.

4. Press the Applications key.

5. Arrow down to Stage Changes.

6. Press Enter.

7. Repeat 4-6 a few times...


Is it possible to stage changes just by pressing Enter on an item? That, 
to me, seems most logical, with Discard and other operations remaining 
reachable through the context menu. More often than not, I'm in this 
view wanting to stage changes.


Yes I can set up Smart Commit to stage everything, but I've already 
accidentally committed secrets that way. :) Yes I can group untracked 
files and not Smart Commit those, but that took a bit of digging to set 
up. I just think that the default in this view will almost always be to 
stage the currently-selected change, so Enter should do that, though I 
certainly won't bikeshed it if there are good reasons not to do this. 
Just felt like I had to dig a git to find this, and VSCode nudged me 
toward a behavior that, in its default configuration, probably isn't 
wise (at the very least, Smart Commit shouldn't default to also adding 
untracked files.)


Thanks.

**Comment by ndarilek** [comment]
Oh, and thanks for the terminal tip, BTW. I'd have never thought to use 
Ctrl-up/down arrow. Working very nicely here. :)

**Comment by jvesouza** [comment]
Great tip! thanks.

What if I wanted to read word by word or character by character? Or even 
select some text displayed in the terminal?

This is certainly not the appropriate place for this type of question, 
but honestly I am in the learning phase of using vscode.

**Comment by Tyriar** [comment]
@jvesouza the screen reader's feature to read by word or character should work when using the navigation mode.

**Comment by isidorn** [comment]
@ndarilek this is very good feedback for the SCM viewlet. And I 100% agree, to track this I have created https://github.com/microsoft/vscode/issues/90893 feel free to comment there if I did not cover the issue nicely.

**Comment by jvesouza** [comment]
Regarding the file explorer:


1. If I am in the file explorer and press shift + tab, the focus is 
moved to the session explorer and orca announces the name of the folder.

2. When the focus is moved to the file explorer, the name of the file in 
focus is not announced. I just hear a message stating that I must use 
the navigation keys to navigate.

**Comment by isidorn** [comment]
@jvesouza 1) sounds expected 
2) Yeah when focus is moved to the file explroer for the first time we first focus the overall tree. Once you have acutally set the focus in the tree to something every other focus in the explorer will move there. If you find this annoying and counter intuitive please file a new issue :)

**Comment by webczat** [comment]
generally the rule is that what was selected in the tree should be selected/announced when I return to it. othervise I don't know where I am, and have to press down/up arrow for example to reread. and imagine if there is only one item in the whole tree...

**Comment by isidorn** [comment]
Well the focus should always be preserved when you return to the file explroer.  We only focus the whole tree if nothing was focused before.
If that is not the case we would need a new issue with reproducable steps..

**Comment by webczat** [comment]
it may be it is indeed preserved, but that screenreader does not get enough info to know what is the focus in tree. it is quite common bug in my experience :)

**Comment by isidorn** [comment]
@webczat when I try it on the Mac with VoiceOver it works just fine. I believe we are doing the correct thing with `ActiveDescendent` inside the tree. It might be an Orca issue.

Since this turned into a chat room, if you have feedback on word navigation feel free to chime in here https://github.com/microsoft/vscode/issues/90578

**Comment by alex19EP** [comment]
hello @isidorn. unfortunately --force-renderer-accessibility still required. i installed current insider build (595f98455be0aac7372a0ae7841efae9b91b848e)

and added in settings.jsong

"editor.accessibilitySupport": "on"

wen i launch code-insiders from the terminal i get nothing.

**Comment by isidorn** [comment]
@alex19EP good catch. I was doing something stupid and was only writting it on setting change. So can you please try it out tomorrow and let me know if it works for you then. Thanks a lot!
Already it should work if you just toggle on and off your editor.accessibilitySupport setting. Though please try it out tomorrow.

**Comment by alex19EP** [comment]
> @alex19EP good catch. I was doing something stupid and was only writting it on setting change. So can you please try it out tomorrow and let me know if it works for you then. Thanks a lot!
> Already it should work if you just toggle on and off your editor.accessibilitySupport setting. Though please try it out tomorrow.

yay. now it works like a charm! thanks @isidorn 

i tested all cases.

**Comment by isidorn** [comment]
@alex19EP awesome, thanks a lot for trying it out.

Next week we plan to do some testing in our team of Orca screen reader with VS Code. For reference here's the test plan item https://github.com/microsoft/vscode/issues/91063

Also I tried sending some email to the Orca mailing list, not sure if you recieved them or they are still waiting for administration?

**Comment by jvesouza** [comment]
@isidorn I did not receive any email from you on the orca list.
It may be worth sending an email to Joan Marie Diggs <diggs@igalia.com> because if I am not mistaken, she is the administrator of the list.

**Comment by webczat** [comment]
on the other hand I am surprised that the list requires admin approval...

**Comment by isidorn** [comment]
Ok, I will send her an email. Thank you

**Comment by isidorn** [comment]
What Linux version are you all using?
For us all seems to work nicely on Ubuntu 18.04, but on Ubuntu 19.10 does not seem to work...

**Comment by jvesouza** [comment]
I am using arch Linux.

Em qua, 26 de fev de 2020 10:12, Isidor Nikolic <notifications@github.com>
escreveu:

**Comment by webczat** [comment]
same here. archlinux seems quite popular among us. It definitely has newer packages than even ubuntu 19.10 and things work here.
