### ISSUE TITLE
Cancel task detection does not run task

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#90474]
Issue Type: <b>Bug</b>

I have a workspance in which the typescript task protection runs for a long time.  My steps:

1) "Run tasks" from command palette
-> quick pick with cancel button shows
2) "Cancel" 
3) Select one of the tasks shown
-> nothing happens
4) Wait
5) after around 1 minute the task is actually run

While in step 4) I can select "Run Task" and select a task again which will also wait until the first task ran.

After step 5) task running works as expected.

VS Code version: Code - Insiders 1.43.0-insider (8d17dc1e84d53f5fd4ed0d05fabaa3062259633d, 2020-02-10T10:42:15.424Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.0.0-1022-azure
Remote OS version: Linux x64 5.0.0-1022-azure

**Comment by alexr00** [comment]
Fixed by reverting the changes to the quick pick.

Details:
This milestone I worked on streaming the tasks into the quick pick, but after some discussion we decided that an even better experience would be to show the recently used tasks, the tasks.json tasks, then each _task provider_ instead of all the tasks they provide. However, there wasn't time to make this change. Instead of having a task quick pick UX that changes every month for several months, I matched the experience of 1.42 and will have the new quick pick at some point in the future.

**Comment by alexr00** [comment]
The "stop detecting" is back again.

**Comment by alexr00** [comment]
To verify, open the vscode repo. In the project settings, remove `"gulp.autoDetect": "off"`. Run "Run Task". When the "stop detecting" button appears, click it immediately. Quickly after that, run any task. Verify that it starts right away.
