### ISSUE TITLE
Same folder starts in uncollapsed state in both root folders although it was collapsed when VSCode closed

### ISSUE THREAD

**Issue by jirsbek** [microsoft/vscode#90473]
- VSCode Version: Stable 1.42.0
- OS Version: macOS 10.15.3

Steps to Reproduce:
![ezgif-7-49ddc0f7067f](https://user-images.githubusercontent.com/8224496/74265225-77004080-4d02-11ea-8323-53218be7ff57.gif)

Expectation:
I expect having the same state of tree view when I closed the VSCode.

**Comment by IllusionMH** [comment]
@jirsbek do you have any editors open?
Especially with files from this folder and `"explorer.autoReveal": true` (default value)

**Comment by jirsbek** [comment]
Nope, no editor is open and I've got `"explorer.autoReveal": false`

**Comment by isidorn** [comment]
I acknowledge this issue. The problem is that you have the same Folder in two explorer items. Since we use resource URI as identifiers there is probably an issue where we call expand two times.
Potential code poitner https://github.com/microsoft/vscode/blob/33d3f3ae4b348e62087fb24b0db796215a7f0758/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L616
