### ISSUE TITLE
Editors show generic icon until they are loaded

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode#90486]
Version: 1.42.0 (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

1. Create two new untitled editors
2. Switch one of them to a language mode with a non-default icon (such as C#)
3. Bring the other editor into focus
4. Close and restart VS Code

Expected : Icons show correctly for the specified language

Actual : Icon is default editor icon until the editor is selected

![Capture](https://user-images.githubusercontent.com/28519865/74286010-d139db00-4cdb-11ea-8ae4-90526881dd1b.gif)

**Comment by bpasero** [comment]
Yes I looked into it and the problem is only showing up for untitled files that do not have any contents: we use some code to detect the file icon based on the resource of the file and for untitled files there is no file extension associated. Even though we know the language mode in the editor, we do not know it for the label because the label is only concerned about the associated resource.

**Comment by bpasero** [comment]
This actually applies to file editors as well if the language mode is changed from the default.
