### ISSUE TITLE
Single file open per editor

### ISSUE THREAD

**Issue by BrandonShega** [microsoft/vscode#90535]
So I really like the new open editors limit that was introduced in the January 2020 build and I thought it would solve my problems of having to close many files when opening a split, but it doesn't.  When I use Emacs and I'm editing say an HTML file and I want to check out the CSS, I open a new vertical split and then open the CSS file in question.  When I'm done, I close the file and the split goes away.  In Code, when I do the same thing, the split will contain the file I'm working on currently, then I open the CSS file, when I want to close the split, I have to close both files.  If I open even more files in that split, I have to close all of them just to get the split to go away.

I thought by enabling the editors limit and setting it to 1, this would alleviate this issue but now I can no longer split the editor since the limit is 1.  What I'd like is to only have a single file open in a given editor at a time (even in splits), is this possible in any way or can it be implemented?

**Comment by BrandonShega** [comment]
Oh! I think the `"workbench.editor.limit.perEditorGroup": true,` option is what I was looking for.  Not sure if this gets exactly what I want (might be a limitation of Code) but it's close.

**Comment by JacksonKearl** [comment]
Is the issue that when you perform a split your active editor gets but in both the new and old groups? You can use the commands `View: New Editor Group [Below/Above/etc]` to create a new empty editor group and open the file in that. The group would then close after you close the single editor instead of both the new editor and the duplicate editor formed on the split.
