### ISSUE TITLE
Cannot update any extensions

### ISSUE THREAD

**Issue by pstewartextron** [microsoft/vscode#90536]
1. Use VSCode with extensions.
* Notice that there are updates available. (they didn't update automatically).
2. On the extensions view, click "Update to <version>" on any of the available updates.
* Notice that it will say installing for a while then a toast message will pop up saying it failed to update and provides a button to manually install.
3. Manually install the update the extension.
* Manually installing works.

**Comment by pstewartextron** [comment]
Update:

Live Share extension was able to update on its own to 1.0.1587 today.

Still won't update:

- LaTeX Workshop
- Python
- Remote - Containers
- Remote - SSH
- Remote - WSL

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by pstewartextron** [comment]
So, switching to a different proxy resolves the issue; however, I can access both of the links you provided through the other (bad) proxy.  It's probably a problem with my proxy, but I don't know what it would be.  Nothing has changed.
