### ISSUE TITLE
running Save Participants for

### ISSUE THREAD

**Issue by IbrahimCanKALYA** [microsoft/vscode#90542]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by CodingReaction** [comment]
VSCode Version: 1.42.1
OS Version: Windows 10 Home
Steps to Reproduce:

1. Inside the body section of a .html document, add a <p> tag with no particular text.
2. Add a <span> tag inside the paragraph that encloses at least 1 word.
3. The doc doesn't seem to save anymore and live server enters in a infinite loop if active.

Does this issue occur when all extensions are disabled?: No

Additional info: the problem stop persisting when the following extension was disabled:
"Auto rename tag" (check the screenshot for more info about the extension).
![auto rename tag](https://user-images.githubusercontent.com/54866449/74779607-96581a00-527c-11ea-9557-3846725c3790.png)

**Comment by demiro** [comment]
auto rename tag causing a lot of issues lately.. :'(

**Comment by nikoksr** [comment]
@CodingReaction can confirm, disabling the extension "Auto Rename Tag" immediately solved it for me.

VSCode Version: 1.42.1
OS Version: Arch Linux 
Kernel Version: 5.5.5

**Comment by Lietsaki** [comment]
Auto Rename Tag was causing the problem in my case as well.

**Comment by Left4Dev** [comment]
Please fix, I am not able to work with this $§"!%"$$%§!
Windows10, Latest version of VS, all extensions disabled. 

It seems like the good times are over and there we are again in visual studio hell. Loading, waiting and guessing what it could be;)

**Comment by Jihun0109** [comment]
It happened to me and @CodingReaction comment made it fix. Thank you.

**Comment by davidkartuzinski** [comment]
I encounter "Running Save Participants for 'src/styles/global.css': Formatting" when I use HTML in an MDX file. It's seems prettier is having a hard time formatting it, but sometimes can and sometimes can't. And now always takes forever.

**Comment by teds31** [comment]
> I encounter "Running Save Participants for 'src/styles/global.css': Formatting" when I use HTML in an MDX file. It's seems prettier is having a hard time formatting it, but sometimes can and sometimes can't. And now always takes forever.

if you have the auto rename tag extension, then disable it. worst case trying restarting your windows or do an nvram reset on your mac

**Comment by davidkartuzinski** [comment]
@teds31 - you're suggestion of restarting the computer seems to be working. I am on mac. I basically restarted everything, and its seems to be behaving.  Thank you.

**Comment by zebralight** [comment]
I'm seeing this issue on macOS Catalina when saving Go files.  I don't have auto rename tag installed and I tried resetting to no avail.

**Comment by rdrgmnzs** [comment]
@zebralight I downgraded the Go extension to 0.12.0 and things are working ok again for me. That may be worth a shot.

**Comment by markchagers** [comment]
In addition to the issue that files can't be saved anymore, which can be temporarily fixed by clicking the Cancel button inside the running save participants notification, I have had several occurrences of files getting mixed up with the content of another file when doing a Save all. The files that cannot be saved get contaminated with (parts of) the content of files that can.

**Comment by andrewbaisden** [comment]
Disabling Auto rename tag also fixed this issue for me. Using macOS Catalina.

**Comment by lovekaizen** [comment]
Got the same issue, without Auto Rename Tag installed, need to investigate issues with other installed plugins though:
![image](https://user-images.githubusercontent.com/12876691/76266292-e7957100-625e-11ea-8eaf-981178710886.png)

**Comment by nikoksr** [comment]
So it does not necessarily have to be an extension problem? 

Has the problem occurred to someone who did not have any extensions enabled?

**Comment by photocurio** [comment]
The issue is NOT limited to Auto Rename Tag.  I don't use that one.  I have a slow problem if I try to run PHP Code Beautifier.

**Comment by nikoksr** [comment]
Since I have uninstalled 'Auto Rename Tag', the problem hasn't occurred for days. 

Right now I have tried to import a large (~41k lines) Javascript document into my project and the problem has reappeared.

I have disabled and tested all extensions one by one. The only two extensions where the problem occurred were [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) and [Bracket Pair Colorizer 2](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2), whereas the problem occurred only for a very short time with `Prettier` and for a very, very long time with `Bracket Pair Colorizer 2`.

Other extensions, which did not seem to have any negative effects:
-   [Color Highlight](https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight)
-   [CSS Peek](https://marketplace.visualstudio.com/items?itemName=pranaygp.vscode-css-peek)
-   [EJS language support](https://marketplace.visualstudio.com/items?itemName=DigitalBrainstem.javascript-ejs-support)
-   [ES7 React/Redux/GraphQL/React-Native snippets](https://marketplace.visualstudio.com/items?itemName=dsznajder.es7-react-js-snippets)
-   [JavaScript (ES6) code snippets](https://marketplace.visualstudio.com/items?itemName=xabikos.JavaScriptSnippets)
-   [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
-   [Import Cost](https://marketplace.visualstudio.com/items?itemName=wix.vscode-import-cost)
-   [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)
-   [Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense)
-   [VSCode React Refactor](https://marketplace.visualstudio.com/items?itemName=planbcoding.vscode-react-refactor)
-   [React PropTypes Generate](https://marketplace.visualstudio.com/items?itemName=suming.react-proptypes-generate)
-   [Visual Studio IntelliCode](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode)
