### ISSUE TITLE
Large JSON file don't even recognized

### ISSUE THREAD

**Issue by kristofzerbe** [Microsoft/vscode#9058]
In 2016 it is really disappointing when a new editor don't even recognize the format of a large JSON file (6.5 MB)

- VSCode Version: 1.3.0
- OS Version: Windows 10

Steps to Reproduce:
1. Create a new minified JSON file and fill it with data > over 5+ MB
2. Open in VS Code
3. Facepalm

**Comment by weinand** [comment]
@kristofzerbe I cannot reproduce this problem.
From the 190MB sized citylots.json from here https://github.com/zemirco/sf-city-lots-json I extracted a 15 MB sized json and opened that with VS Code.
It opened in < 1 sec and edition works without problems. Only the syntax coloring needs some time until it reaches the end.

Please provide more details about what problem you are seeing and how to reproduce.

**Comment by weinand** [comment]
@kristofzerbe please explain what "minified JSON" means, e.g. eliminating all line breaks?
What tool did you use to minify JSON?

**Comment by weinand** [comment]
@alexandrudima I believe the issue is a 5+ MB json file that has a single long line.

**Comment by alexandrudima** [comment]
@kristofzerbe we don't colorize lines over 20k chars with TextMate grammars because TextMate grammars are built with regular expressions and each regular expression check takes a minimum of O(N) where N is the string length and some, due to how they are spelled out can lead to O(N^2) or even worse. I had to make a decision between executing arbitrary regexes that colorize from TextMate grammars on arbitrary length strings and introducing a cut-off point so the UI has less chances of freezing waiting for a regex to match. It is still possible to craft bad regular expressions in the TextMate grammars that lead to O(2^N) complexity levels -- see [here](http://www.regular-expressions.info/catastrophic.html). I chose to introduce an arbitrary cut-off point of 20k chars above which lines don't get colorized.

It is definitely possible to colorize gigabytes of JSON in a very fast way, but IMHO not with TextMate grammars.

**Comment by kristofzerbe** [comment]
Hi,

sry for the late response ... yes, the JSON is one line, generated by
System.Web.Script.Serialization.JavaScriptSerializer.

Problem is, that under some circumstances I have to check or edit some
attributes manually and therefore I need some basic formatting. There are
some formatting plugins out there, like 'beautify', but the JSON file isn't
recognized by VSC as JSON in the first place ... so, no chance to format
and no chance to review or edit. I had to switch to the good old Notepad++
to get my job done, because VS 2014 is able to do it, but it is to slow.

Kristof

2016-07-14 12:24 GMT+02:00 Alexandru Dima <notifications@github.com>:

**Comment by weinand** [comment]
@kristofzerbe you can always set the 'language' of a file explicitly from the status line:

![2016-07-14_14-46-21](https://cloud.githubusercontent.com/assets/1898161/16839883/c96f224c-49d1-11e6-90ef-dfcc5e202282.png)

Click on the 'Plain Text' and then pick 'JSON' and do the 'Format'.

**Comment by alexandrudima** [comment]
Let's track in #9832
