### ISSUE TITLE
How to show errors in the editor

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#9062]
Followup from #8836:

@isidorn we have already examples for how to show these kind of errors. 
When trying to open a huge file, the error is shown like this:

![2016-07-11_11-22-21](https://cloud.githubusercontent.com/assets/1898161/16725950/0ab2069a-475a-11e6-9f91-e3c01e29b172.png)

We should align with that approach; ideally we should share the implementation.

**Comment by isidorn** [comment]
The current [code](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/resourceviewer/resourceViewer.ts#L168) is special for showing binary editors so it can not be reuesed nicely atm.
I will bring this up in the UX meeting tomorrow

**Comment by isidorn** [comment]
Will wait for @bpasero to be back so we can discuss and not urgent -> August

**Comment by stevencl** [comment]
We discussed during our UX meeting and agreed that this seems like the right approach.

**Comment by bpasero** [comment]
This editor UI is used for files that are binary or have other limitations when opening, I am not sure we should reuse the same for your case. You are free to create your own editor input and editor and open it and you have DOM access to do whatever you want in there. There are some actions that target this editor that might expect it to be about a real file on disk and it does not sound like your scenario is about that.

**Comment by stevencl** [comment]
Is this an implementation issue or a UX issue? I'll add it to the agenda for tomorrow in case it is UX.

**Comment by isidorn** [comment]
@bpasero so I can create my own editor the same way you do for the [binary resource editor](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/binaryEditor.ts#L23). However I am not sure how to wire in my editor, since you just register it for certain mime types [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/files.contribution.ts#L95).
Optimally I would just like to use the editor service and tell it to use my custom editor, since it should also belong to a group and so on but that API is missing so is there some nice alternative?

**Comment by bpasero** [comment]
@isidorn you can bring in new editors to the workbench without having to register a mime. The way it works is that you register an editor and then make sure that you have at least one editor input support this editor. I suggest you add your own editor and input to show a message (or anything you need to show).

The HTML preview editor is a good example: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/html.contribution.ts#L21

It connects an editor with an input. Everytime this input is opened via our APIs, this editor is being used and so you control the entire lifecycle end to end.

**Comment by isidorn** [comment]
We are now using a custom editor to render debug errors.
Open to feature requests on how to style these errors better since we are now in charge of rendering this.

![screen shot 2016-09-07 at 18 16 41](https://cloud.githubusercontent.com/assets/1926584/18319809/a1b36e62-7527-11e6-9cb3-0fe46cf80e28.png)

**Comment by bpasero** [comment]
@isidorn maybe at the minimum try to copy the styles from the binary editor 👍
