### ISSUE TITLE
Keyboard Shortcuts' (sic) keybinding dialog box shows modifier key names in wrong initial case

### ISSUE THREAD

**Issue by chrisjj** [microsoft/vscode#90677]
e.g.

![image](https://user-images.githubusercontent.com/6157073/74521610-899c9480-4f11-11ea-8bf7-b13818a1ee58.png)

Ctrl, Shift and Alt initials should be upper-case..

The same dialog appears from keybindings.json:

![image](https://user-images.githubusercontent.com/6157073/74521706-c36d9b00-4f11-11ea-83da-66f314143c86.png)

**Comment by JacksonKearl** [comment]
Why do you keep adding `sic`? "Shortcuts" is a correctly spelled word.

**Comment by chrisjj** [comment]
sic doesn't just refer to spelling. "Keyboard Shortcuts" is an erroneous title for this UI page.

**Comment by alexdima** [comment]
That is as designed. That is the casing in which these get written to the user `keybindings.json` file. They are also not localized in that input for the same reason.

**Comment by chrisjj** [comment]
> That is as designed. That is the casing in which these get written to the user keybindings.json file.

I can't imagine anything that constrains or even recommends the UI to use the casing of a config file designed for reading by machine.

Esp. since the standard UI casing does appear in the dialog.

**Comment by alexdima** [comment]
The user friendly rendering is the one below. In the input box there is the machine readable rendering. The machine readable rendering is stable across languages, so if someone uses VS Code in Chinese or Russian and provides us a screenshot we can understand what is going on. The machine rendering can be hovered to provide more debug information about the keybinding, like key codes and more. This is useful for troubleshooting keyboard input.

Your request is not to fix the casing, but to remove that rendering. I don't want to remove it because it is helpful to troubleshoot things. Once we build another troubleshooting UI we can remove the machine readable rendering from this input box, but at this point this input box is the only way to troubleshoot keyboard input issues.

**Comment by chrisjj** [comment]
> Your request is not to fix the casing, 

My request: ["Ctrl, Shift and Alt initials should be upper-case.."](https://github.com/microsoft/vscode/issues/90677#issue-565225193)

> but to remove that rendering.

Oh? Where's that request of mine?
