### ISSUE TITLE
Autocomplete messes up when adding (async ...) to a dynamic import()

### ISSUE THREAD

**Issue by brunocangs** [microsoft/vscode#90695]
Issue still persists on Insiders as of February 14th 2020 (Day of testing)

- VSCode Version: 1.42.1
- OS Version: Darwin x64 19.0.0

Steps to Reproduce:

1. Write two dynamic import lines
2. Set a cursor at the end of each one
3. Use Intelisense to import a field

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/30100875/74538061-22cfa900-4f1a-11ea-8b60-e6e87b173d80.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by JacksonKearl** [comment]
We get all our TypeScript functionality from a separate repository. Please file an issue over on https://github.com/Microsoft/TypeScript. Thanks!

**Comment by brunocangs** [comment]
@JacksonKearl I don't see how this is a Typescript problem. It's related to there being a second cursor and using a functionality that's editor related. Should I still open the issue over there?

**Comment by JacksonKearl** [comment]
@mjbvz would know better

**Comment by mjbvz** [comment]
Please provide example code to repo this issue

**Comment by brunocangs** [comment]
Code example:
foo.js
```javascript
const foo = 3;
export { foo };
export default foo;
```

bar.js
```
const bar = 3;
export { bar };
export default bar;
```

foobar.js
```
const test = async () => {
  const a = import('./foo');
  const a = import('./bar');
};
```

With this setup, if you create a cursor after each `import()` and use the autocomplete it will behave like the GIF attached to the initial comment.

It doesn't happen when it's two variables importing from the same origin, so you need to be importing from two different sources

**Comment by mjbvz** [comment]
@jrieken Do you have any suggestions on how extensions should handle multicurors for suggestion accept? TS only knows about the primary cursor and returns a replacement range for that and returns an `insertText` for that range.

I don't know what we can reasonably handle multiple cursors this way

**Comment by jrieken** [comment]
There is no good fix for this. We don't expose multiple cursors to language features like completions. That's because  we wanna keep things simple and we don't wanna leak this into LSP which talks to majority of single-cursor-only editors. 

What happens is that upon insertion we compare the selected text from the primary cursor (using the range, e.g `import('./foo')`) with the prefix of secondary cursors. When equal we will replace, otherwise insert the text. 

E.g. having the snippet below and accepting `bar`

```
foo|
foo|
```

will become

```
bar|
bar|
```

However, with 

```
foo|
bazz|
```

it will become 

```
bar|
bazzbar|
```

Given that we don't want make to completion providers more complex we have the option of dropping cursors with a different prefix. E.g the last sample will become this (only one replacement, only one cursor after accepting): 

```
bar|
bazz
```

However, that would be change in behaviour and I don't know how multicursor suggestion is currently used and what the expectation are. Needs some thing before making a change, but this is definitely something that TypeScript can not (should not) fix.
