### ISSUE TITLE
DAP completions request line is 0-based from the debug console

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#90727]
I was debugging and noticed that the `line` in the `completions` request appears to be 0-based. The column is 1-based. DAP doesn't specify the base of the completions request, so I assume it should respect `linesStartAt1`  given in the initialize request, which vscode sets as true.

**Comment by isidorn** [comment]
I tried reproducing this and I could not.
My steps use the new node debugger to debug the following file:
`debugger; console.log('hello');`
Once stopped, open debug console and type `con` and notice how the lineNumber: 1 is sent to the debug adapter for the `completions` since I am in the first line.
If I try it for other lines in a multi line console input it works just fine. 0 is never sent.

**Comment by connor4312** [comment]
Nevermind, we converted internally to 0-based for some reason 🤦‍♂
