### ISSUE TITLE
Dragging and Dropping a folder from file explorer doesn't work.

### ISSUE THREAD

**Issue by tim-comer** [Microsoft/vscode#9073]
- VSCode `Version:1.3
- OS Version:Win 7 64bit

Steps to Reproduce:

1. Open VS Code
2. Open File Explorer
3. Drag a folder from file explorer to VS Code editor pane.

In previous versions of VS Code you could drag and drop folders to the editor pane in VS Code to open them.  As of 1.3 this functionality no longer works.  Nothing in the release notes says that this was removed, only that the drag and drop was enhanced.

**Comment by bpasero** [comment]
This has been fixed in insiders already. 

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
