### ISSUE TITLE
Vs Code unable to determine  multiple github user and not prompting  to enter credential

### ISSUE THREAD

**Issue by DebashishSaha** [microsoft/vscode#90828]
- VSCode Version:1.42.0 (user setup)
- OS Version:
Version	10.0.18362 Build 18362

Steps to Reproduce:

1. Clone one repo with one github user account , vscode pops up with github UI to enter credentials
2. try to clone other repo with another user account ,vscode does not  pop up with github UI to enter credentials
3. Now delete key from windows credential manager and try to clone second one. It works . 

Does this issue occur when all extensions are disabled?: Yes/No -- YES

**Comment by joaomoreno** [comment]
VS Code simply invokes Git. Your git installation seems to use a GitHub credential helper, maybe https://github.com/Microsoft/Git-Credential-Manager-for-Windows or GitHub for Windows...? This issue is related to whatever credential helper you have installed, not VS Code. Please file an issue on the respective project.
