### ISSUE TITLE
Feature Suggestion: Cloning a repo

### ISSUE THREAD

**Issue by jsloyer** [Microsoft/vscode#9085]
In VSCode it requires you to open a folder to use it.  Instead of clicking open folder it would be nice to be able to clone a git repo from the Git viewlet on the left.  Instead of the message that says you must open a folder I am suggesting adding a button that you can click to have vscode clone a repo for you.

@bpasero thoughts?

I am volunteering to add this as well...

**Comment by bpasero** [comment]
**Disclaimer:** This is my personal opinion and should not be taken as opinion from the team or Microsoft

-1 from me. I would like to not add such functionality because imho it belongs more to the IDE space and not the editor space. I am very happy with cloning etc. from the terminal (either integrated our outside) and never miss to have such thing from the git viewlet. 

@joaomoreno as the git viewlet author can also comment.

**Comment by joaomoreno** [comment]
Yeah mixed feelings here, although I do see the value.

You're gonna need

- UI for the user to input both the repo's url and the location in the file system, where to put that?
- UI to handle authentication, we have it but you need a workspace open.
- Code to switch to that workspace, not sure whether we have this from the renderer process.

**Comment by slowmove** [comment]
@bpasero though that mind set can be applied on the entire Git implementation in VSCode. I would say that you either shouldn't have any Git integration to let that be handled in terminal or by plugins, or you implement "all" the Git functionality.

**Comment by bpasero** [comment]
That is a perfectly valid statement and I disagree with that statement.

**Comment by jsloyer** [comment]
@joaomoreno the UI could go in the viewlet...

**Comment by pcgeek86** [comment]
@joaomoreno Any updates on this? I went looking for `git clone` in the Command Palette, but can't find it.

**Comment by joaomoreno** [comment]
Nothing, it's in the backlog.

**Comment by bpasero** [comment]
@joaomoreno can be closed I think?
