### ISSUE TITLE
Focus Assist activates when maximised on secondary screen

### ISSUE THREAD

**Issue by ntw-au** [microsoft/vscode#90850]
Issue Type: <b>Bug</b>

Visual Studio Code activates Focus Assist when maximised on a secondary screen.

Steps to reproduce:
1. OS: Windows 10 1909
2. Dual display, equally sized, primary on left
3. Windows Settings>Taskbar>Multiple displays>Show taskbar on all displays>Off
4. Ensure Focus Assist is inactive
5. Drag VS Code to the secondary monitor
6. Maximise VS Code

Expected: Focus Assist remains inactive
Actual: Focus Assist is active. Focus Assist is inactivated again when the VS Code window is restored.

This behaviour does *not* occur when:
* The taskbar is shown on all displays (Windows Settings>Taskbar>Multiple displays>Show taskbar on all displays>On)
* VS Code is maximised on the primary display (where the taskbar is)
* VS Code is maximised on either display when the taskbar is set to auto-hide in desktop mode (Windows Settings>Taskbar>Automatically hide the taskbar in desktop mode>On)

This behaviour occurs with extensions both enabled and disabled.

VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:34.058Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-7900X CPU @ 3.30GHz (20 x 3312)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (18.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-postgres|cko|1.1.11
vscode-jq|dan|1.2.0
gitlens|eam|10.2.1
python|ms-|2020.2.63072
remote-wsl|ms-|0.42.3
cmake-tools|ms-|1.3.0
cpptools|ms-|0.26.3
powershell|ms-|2020.1.0
rust|rus|0.7.0
vscode-wl|shi|1.7.3
cython|tcw|0.1.0
jinja|who|0.0.8

</details>

**Comment by isidorn** [comment]
Doing some googling Focus Assist seems to be a Win10 feature that helps with users get focused - if I understood correctly.
This seems to be an electron issue, thus forwarding to @deepak1556

**Comment by jpodpro** [comment]
it's not just VS Code. lots of other apps trigger this when maximized on my second monitor (chrome, firefox, slack). however many don't (explorer, VLC). of course this all depends on whether the focus-assist setting "when i'm using an app in full-screen mode" is on. but something is wrong with the actual detection of app-full screen because it correctly detects the difference between VLC maximized vs full-screen mode.

**Comment by yea55** [comment]
I did a little experimentation with this focus assist issue after it kept happening on my zenbook duo. It turns out the check windows uses to determine that a program is fullscreen is a little too simple and can get tripped up under the wrong circumstances. All a program needs to do for focus assist to consider it fullscreen is draw to an entire display, which means that programs that draw their own title bars instead of letting windows do it for them (e.g. most modern browsers, discord, and presumably VS code) can erroneously be considered fullscreen if they are maximized on a display without a taskbar.
Again, the simplest solution to this is to turn off the "when I'm using an app in full-screen mode" switch in focus assist settings, but an alternate solution might be to enable the taskbar on your secondary display(s) to ensure that programs don't fill the entire display like this unless they actually are in fullscreen.

**Comment by Jaswir** [comment]
@deepak1556 

Just starting out exploring first issues to pick up. 
Are electron issues hard? Not familiar with electron. Is VS Code build with electron? I understand Electron is a way to build desktop apps using just JavaScript with Node.js and VS Code is a desktop app so. 
Or is it like partly built with Electron?  Label Electron means the issue is due to something with electron so not an issue with VS Code? More like an Electron Issue??

**Comment by deepak1556** [comment]
Is this still an issue with latest stable ?

**Comment by ntw-au** [comment]
@deepak1556, it doesn't seem to still be an issue, using VS Code 1.85.0 and Windows 11 23H2. I set the Do Not Disturb settings to turn on automatically when using an app in full-screen mode, and Do Not Disturb did _not_ activate when the VS Code window was maximised.

**Comment by deepak1556** [comment]
Thanks for confirming
