### ISSUE TITLE
Improve logging when terminal process dies

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9087]
A `console.error` should print stdout/stderr when a terminal exits with a non-0 exit code. The end result we want is an error message on the UI explaining there was an exit code (potentially mentioning to check the developer tools console for more detail), and the output of the process in the console such as:

```
zsh: command not found
```

**Comment by brennanMKE** [comment]
For my issue with my Mac being configured with `/bin/false` for the shell and VSCode using it for the app settings there could be a better way to handle it. The default shell on the Mac is `/bin/bash` so if it is `/bin/false` and VSCode is launched the first time perhaps that setting could be rejected and revert to `/bin/bash` instead. This way the integrated shell will always work when that alternate shell is set.

**Comment by Tyriar** [comment]
`/bin/false` is very specific to your organization, it wouldn't make sense to add a special case for all the possible weird cases. A friendly message indicating your shell and args should be enough to diagnose in the general case.

**Comment by brennanMKE** [comment]
I do not believe it is an uncommon case. That `false` shell is used intentionally to prevent remote access to the shell for the purpose of making a computer more secure. This is done on Linux as well. Simply detecting that is the configured shell is set that way would be a good indication to revert to the default shell for a local, interactive shell.

Another common option is `nologin` which can also be set for a user's shell to block remote access. And while my shell was set to `false` I was able to open the Mac Terminal which is considered a local, interactive shell.

You can see these shell configurations are common from this answer on Stack Exchange. The answers there explain very good reasons why IT departments would change the default shell. And since VSCode only needs a local shell it would be alright to instead revert to a reasonable default.

http://unix.stackexchange.com/questions/55106/disable-user-shell-for-security-reasons

Setting the user's shell should not prevent the integrated shell in VSCode from working just as the Terminal app still works locally on the Mac when the shell is set to `false`.

**Comment by brennanMKE** [comment]
You can read `/etc/shells` for a list of shells and perhaps use the first one as the default if the currently configured shell is set to block remote access.

**Comment by Tyriar** [comment]
@brennanMKE good to know :smile: I created https://github.com/Microsoft/vscode/issues/14817 to follow it up independently of this issue.

**Comment by Tyriar** [comment]
A better message coming in v1.8:

![image](https://cloud.githubusercontent.com/assets/2193314/19902812/631af77e-a029-11e6-8d5d-95d811e9b9d3.png)

**Comment by brennanMKE** [comment]
👍

**Comment by Tyriar** [comment]
To verifier: An error can be easily simulated by adding custom shell/shellArgs in the settings.
