### ISSUE TITLE
Opening Playground page logs a TypeError to the browser

### ISSUE THREAD

**Issue by rcjsuen** [microsoft/vscode#90894]
**Operating system:** macOS 10.15.1
**Browser:** Chrome 80.0.3987.87 (Official Build) (64-bit)

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/15629116/74750324-8ec35180-5239-11ea-9b18-7f0f10abdf57.png">

**Comment by alexdima** [comment]
@jrieken The problem is that the code [here](https://github.com/microsoft/vscode/blob/acb9817a8d7607ca2a62c05a3ee8b723ab4020ee/src/vs/editor/contrib/suggest/suggestRangeHighlighter.ts#L97-L126) assumes that `document.body` is available, but that might not be the case, the `js` could be loaded before the `onload` event.
