### ISSUE TITLE
Multicursors aren't rendered perfectly straight when whitespace render is enabled with Consolas font

### ISSUE THREAD

**Issue by mcornella** [microsoft/vscode#90915]
- VSCode Version: 1.43.0-insider (6ec6f9e3f4d17f0cef0480688a1f350b9141e567)
- OS Version: Windows 10 Pro build 19564.1000

Steps to Reproduce:

```
# These are almost the same, cursors in different position                                                     
                                   git reset origin/(git_current_branch) --hard                                
                                   git reset origin/(git_current_b       --hard                                
# These are almost the same but with an extra matching r, cursors in same position                             
                                   git reset origin/(git_current_branch) --hard                                
                                   git reset origin/(git_current_br      --hard                                
# These are almost the same but with an extra space before them, cursors in same position                      
                                    git reset origin/(git_current_branch) --hard                               
                                    git reset origin/(git_current_b       --hard                               
# Another sample that doesn't match                                                                            
| grt                  | cd "(git rev-parse --show-toplevel \|\| echo .)"                                      
| grv                  | git remote -v                                                                         
```

1. Use `Consolas` as font
2. "Toggle render whitespace"
3. Copy and paste the text above (keep the trailing whitespace)
4. Activate multiple cursors on a straight line and put them at the end (column 112), it only happens at column 112.

Does this issue occur when all extensions are disabled?: Yes

I know this is an insane amount of detail for such a small thing but I couldn't let it go.

## Screenshots

Cursors at column 112
![image](https://user-images.githubusercontent.com/1441704/74770094-de326d80-528b-11ea-955a-273c49d9440c.png)

Cursors at column 111
![image](https://user-images.githubusercontent.com/1441704/74770101-e12d5e00-528b-11ea-8ddf-979df2bcd48a.png)

**Comment by alexdima** [comment]
@mcornella Is there a specific font size of Consolas that you are using? Are you using window zooming via `window.zoomLevel` or have you configured display scaling from the Windows display settings? I could not reproduce on my machine:

![image](https://user-images.githubusercontent.com/5047891/74828525-89d0d180-530f-11ea-8773-a7cb574b0df8.png)

**Comment by mcornella** [comment]
Font size: 14, no zoom level, no display scaling:
![image](https://user-images.githubusercontent.com/1441704/74831734-1f6f5f80-5316-11ea-98b2-06969f946ad7.png)

**Comment by mcornella** [comment]
I have updated to the latest insider version (c94724193451009962e2c116808f71a3328a9836). Now, to reproduce it I have to zoom the text via CTRL+scroll until the developer tools shows a font size of 15.4 px.

**Comment by alexdima** [comment]
Thanks for the extra info, but I still cannot reproduce. The ctrl+scroll is just a multiplier to the fontsize, so can you please try to reproduce with setting the fontSize directly. What precise settings help to reproduce?

I have tried:
```
{
    "editor.renderWhitespace": "all",
    "editor.fontFamily": "Consolas",
    "editor.fontSize": 15.4,
}
```

![image](https://user-images.githubusercontent.com/5047891/74836594-f9e75380-531f-11ea-9a6e-b9f62b945a9b.png)

**Comment by mcornella** [comment]
Try also with `"editor.fontLigatures": true,`. If I disable that, the problem goes away.

**Comment by alexdima** [comment]
Ok, I can now reproduce when using `"editor.fontLigatures": true`. This is what is going on:
* the font is identified by VS Code as being monospace.
* when leaving `"editor.fontLigatures": false` (the default), VS Code can make some monospace assumptions. So it will assume that the offset of character 112 is 112 times the character width. This assumption works across all lines and the cursors are aligned.
* when using `"editor.fontLigatures": true`, VS Code can no longer make these monospace assumptions, because often ligatures result in characters combining, so the cursor offset is not computed by multiplication, but the browser is queried for each position.

The character to render the whitespace, `&middot;` is not perfectly equal to the other characters, so we need to define its width on the `span`s. After a while some rounding errors sneak in and the browser gives different values for offset 112 depending on the count of `&middot;` used in each line. 

I will push a change where I try to correct things if possible.

**Comment by alexdima** [comment]
Complete settings to reproduce:
```
    "editor.renderWhitespace": "all",
    "editor.fontFamily": "Consolas",
    "editor.fontSize": 15,
    "editor.fontLigatures": true
```

**Comment by mcornella** [comment]
Thanks!
