### ISSUE TITLE
Transforms in snippets only work for first parameter

### ISSUE THREAD

**Issue by garyking** [microsoft/vscode#90922]
Issue Type: <b>Bug</b>

This snippet works:

`${1:item} -> ${1/(.*)/${1:/capitalize} ${1:/upcase}/}$0`

This snippet, when tabbing on the second parameter, will cause the transform to result in a tab character:

`${1:thing} ${2:item} -> ${2/(.*)/${2:/capitalize} ${2:/upcase}/}$0`

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 18.7.0

**Comment by ArturoDent** [comment]
Your second non-working example should be:

`"${1:thing} ${2:item} -> ${2/(.*)/${1:/capitalize} ${1:/upcase}/}$0"`

The `2`'s within the transform `/${2:/capitalize} ${2:/upcase}/` do not refer to any tabstop but to regex capture groups.  Since your regex is `(.*)` there is only a capture group 1.  

From https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variable-transforms:

> A "format string" that allows to reference matching groups from the regular expression.

`${tabstop#/regex/format string/options}`

**Comment by garyking** [comment]
Thanks, that did it.
