### ISSUE TITLE
Asked to sign in whenever turning on sync

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#90924]
Repro:

- Turn on sync
- Do sign in flow
- Turn off sync
- Turn on sync, I'm presented with the sign in window

Sync is separate to login, shouldn't the auth session be retained between turning off and turning on sync? Saw this a lot in UX study, people were confused why they kept having to sign in.

Note that we may want to sign out when clearing all the server data, but I don't think it makes sense when just turning off regularly.

**Comment by RMacfarlane** [comment]
Caused by https://github.com/microsoft/vscode/issues/90867

I would also expect to stay signed in when turning off sync, especially as sign in may eventually be used by other things

**Comment by sandy081** [comment]
I changed the behaviour to sign out because I remember few of us expected to sign out (@joaomoreno @misolori ) when turned off sync.

I will revert it to what it is originally - do not sign out. I had this because of the reason that login and sync are independent. Some other feature might be still using the account. 

@RMacfarlane currently sign out is a core command which I think should not be and hence removing it. Feel free to add it as a command in the extension.

**Comment by Tyriar** [comment]
> @RMacfarlane currently sign out is a core command which I think should not be and hence removing it. Feel free to add it as a command in the extension.

Does this meant that every extension needs to create their own sign out? Shouldn't it be a core command with an account selector if there are multiple accounts?

**Comment by sandy081** [comment]
Not sure who provides this command, but definitely not part of settings sync.
