### ISSUE TITLE
Incorrect Breakpoint bindings when using source maps

### ISSUE THREAD

**Issue by rbuckton** [Microsoft/vscode#91]
I’m seeing an issue in VS Code when debugging a TypeScript file with Source Maps that uses TypeScript Async Functions. When I set a breakpoint on the first line of the function body, the breakpoint moves to the first executable line following the end of the function body. I’m trying to determine if this is an issue with TypeScript’s SourceMap output, with VS Code, or with the version of V8 used by VS Code.  I’ve tested the same scenario in Chrome Canary and breakpoints seem to bind correctly, which leads me to believe the issue may not be with TypeScript.

After further discussion, it looks like the issue is in the `node-debug` extension. Changing the default from `Bias.GREATEST_LOWER_BOUND` to `Bias.LEAST_UPPER_BOUND` seems to solve the problem.

CC: @weinand

**Comment by andrew-w-ross** [comment]
I'm just going to add to this issue as I'm also getting breakpoint errors. When doing the [word count extension tutorial](https://code.visualstudio.com/docs/extensions/example-word-count) setting a breakpoint inside of `updateWordCount()` doesn't hit even though it must be working as the extension works as expected. I'm on osx if that helps.

**Comment by bpasero** [comment]
Have also seen this...

**Comment by buzinas** [comment]
Still talking about breakpoints and source maps: when we're not in debug mode, we can't put breakpoints in our `.ts` files, because they won't get caught, so, we must put them in the generated js file, so we can debug our files.

Is there any other way to achieve that? Am I missing anything?

Btw, isn't it possible to VSCode handle that automatically?

Thanks in advance.

**Comment by weinand** [comment]
@buzinas putting breakpoints in your .ts files should always work, not only when in debug mode. If it doesn't then this is a result of one or more of the following problems:
* you haven't turned on "sourceMaps" in you launch config,
* you didn't specify where the generated code lives via the "outDir" attribute in the launch config,
* there are no source maps,
* the source maps have "holes" (i.e. they do fully cover the full source),
* a bug in VS Code node debugging

In order to help me investigate the problem, it helps immensely if you could:
* use node-inspector to verify that source-maps work fine there, but not in VS Code,
* make a reproducible test case available to me.

**Comment by buzinas** [comment]
@weinand not sure if that's the reason, but I'm trying to debug mocha tests in VSCode.

My current workaround is to type `debugger;` in the place I would have a breakpoint, and then, add more breakpoints when the debugger gets caught.

I don't think it's a problem with the sourcemaps, because when I use the `debugger;` statement, I can debug the `.ts` files smoothly.

To reproduce the behavior I'm mentioning, you can follow the steps:
* Clone my repo (https://github.com/buzinas/tslint-eslint-rules)
* Run `npm install` and then `npm test`
* You'll see the `launch.json` configuration. You'll be able to debug TypeScript if:
  - You place a breakpoint in the equivalent JS file; or
  - You put a `debugger;` where you want to break;

If you put a debugger, then you must run `gulp build` (or ctrl+shift+b).

**Comment by rbuckton** [comment]
My simplest repro is:

**sample.ts**
```ts
async function main() {
  await Promise.resolve(1); // bp on this line
  console.log("later");
}
main();
```

Compiled with:

```
tsc sample.ts --sourceMap --target ES6 --module commonjs
```

**Comment by weinand** [comment]
@buzinas thanks for providing steps that helped me investigating the problem. The problem was the value of "outDir": it should be the path to the **generated code** not the source. So after changing it to "dist" setting breakpoints in *.ts files worked for me.

**Comment by weinand** [comment]
@rbuckton yes, changing the default from Bias.GREATEST_LOWER_BOUND to Bias.LEAST_UPPER_BOUND seems to solve the problem. I will test this a little more and then push a fix. Thanks.

**Comment by buzinas** [comment]
@weinand whoa, what a silly mistake hehe
Thanks very much, this will improve my productivity a lot!

A little off topic here, only a question:
- Are we getting conditional breakpoints available anytime soon?

**Comment by weinand** [comment]
@rbuckton the sourcemap for your async/await case is a bit 'spotty':

![2015-11-20 00-37-01](https://cloud.githubusercontent.com/assets/1898161/11299331/36b76cd0-8f86-11e5-84e8-50c19f98568b.png)

It does not cover column 0. Using Bias.LEAST_UPPER_BOUND seems to help with that.

**Comment by rbuckton** [comment]
As a test, I modified TypeScript to not indent so that column zero was mapped and still saw the same issue.

**Comment by weinand** [comment]
@andrew-w-ross this bug is about source maps, your problem with the wordcount example seems to be more fundamental. Could you please create a new bug for your problem and include detailed repro steps, since I wasn't able to reproduce the problem. Thanks.

**Comment by andrew-w-ross** [comment]
@weinand Sure thing

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-node-debug#7
