### ISSUE TITLE
Can not select \n\t

### ISSUE THREAD

**Issue by s50600822** [microsoft/vscode#91000]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. See the screeenshot, I can't seem to be able to select "\n\t"
<img width="969" alt="Screen Shot 2020-02-20 at 3 17 58 am" src="https://user-images.githubusercontent.com/5586453/74851878-f1c6fc80-538f-11ea-819b-6415b116698e.png">

<img width="905" alt="Screen Shot 2020-02-20 at 3 18 04 am" src="https://user-images.githubusercontent.com/5586453/74851896-f8ee0a80-538f-11ea-8fa8-fde608fbcd64.png">

<img width="907" alt="Screen Shot 2020-02-20 at 3 18 10 am" src="https://user-images.githubusercontent.com/5586453/74851908-fe4b5500-538f-11ea-8b49-d29b344e0d3c.png">

This is quite popular and straight forward in sublimeText, to replace such pattern with newline to make the callstack look friendly to the eyes.

**Comment by JacksonKearl** [comment]
What version of vscode are you on? I am able to search for this pattern:
![image](https://user-images.githubusercontent.com/8586769/74889916-4a1de000-5337-11ea-9bf9-843c2aebe175.png)

**Comment by s50600822** [comment]
<img width="1128" alt="Screen Shot 2020-02-20 at 11 51 19 am" src="https://user-images.githubusercontent.com/5586453/74890181-64a79600-53d7-11ea-9e25-6dc4100ba59e.png">

**Comment by roblourens** [comment]
I think the "whole word" toggle is probably messing you up here. You can see that @JacksonKearl's results are all bordered by punctuation marks (non word characters) while yours are followed immediately by `at`, word characters.

The interpretation of the "whole word" flag can be confusing but I think this is essentially by design. Let me know if that doesn't help.
