### ISSUE TITLE
Don't attempt sync when a machine is not being used

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#91020]
Consider a user whose computer does not sleep (or does not for a long time) where VS Code is opened. I think right now regardless of focus or inactivity polling will still occur.

**Comment by Tyriar** [comment]
Actioning this could also help with this scenario:

The user has 2 machines opened, installs C# on one, waits 10 minutes and then marks to not sync. Ideally the second machine would never have installed the C# extension.

**Comment by sandy081** [comment]
Not sure if it is intended but I like my machine gets synced automatically. If user does not want that then he/she should pause the sync. 

I think this was brought up because of the scenario - user wants to try out an extension which is getting installed on all machines automatically. IMO it is a different issue than this which has to solved differently.

**Comment by Tyriar** [comment]
@sandy081 maybe this should be 2 issues, there's the ignore extension flow issue that was identified by the majority of the ux study participants and then there's the more pressing performance problem of machines that go unused still try to sync every 5 minutes, only stopping when VS Code is closed.

**Comment by sandy081** [comment]
Closing it as this might not be relevant anymore. Please try out latest state and file a new issue if needed.
