### ISSUE TITLE
[semantic] [typescript] classify callbacks as function instead of parameter

### ISSUE THREAD

**Issue by SPGoding** [microsoft/vscode#91038]
Issue Type: <b>Bug</b>

A **variable** whose type is function is colored as a function as the fix of ~~#89337~~, however a function **parameter** whose type is function is still colored as a parameter.

![image](https://user-images.githubusercontent.com/15277496/74897833-d9d68500-535d-11ea-9a5f-53809828cb45.png)

```typescript
type F = () => ''

let func: F
func()         // This is colored correctly as a function.

function _(func: F) {
    func()     // This is colored incorrectly as a parameter.
}
```

Also relates to #90853.

VS Code version: Code - Insiders 1.43.0-insider (13d7b3066ab6e8993f12c28b0ced297781055ffc, 2020-02-19T17:43:05.977Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
language-mcfunction|arc|0.16.0
npm-intellisense|chr|1.3.0
vscode-autohotkey-plus|cwe|2.0.2
vscode-eslint|dba|2.0.15
ghlink|dt|1.2.0
vscode-npm-script|eg2|0.3.11
rainbow-csv|mec|1.5.0
python|ms-|2020.2.63990
vscode-typescript-tslint-plugin|ms-|1.2.3
java|red|0.57.0
shader|sle|1.1.4
datapack-json|SPG|2.0.5
vscode-mc-shader|Str|0.8.5
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.9.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0
vscode-icons|vsc|10.0.0
markdown-all-in-one|yzh|2.7.0

</details>

**Comment by aeschli** [comment]
Hm, that's actually intentionally. Parameters are always parameters.
It's only variables that can be functions, and properties will become members.

Id like to keep parameters as parameters.

**Comment by dannymcgee** [comment]
@aeschli Any chance you might be open to persuasion? There are situations where this can be pretty weird, for example:

```typescript
return new Promise((resolve, reject) => {
    const data = await this.tryRetrieveData();
    if (data) {
        resolve(data);
    } else {
        reject("No data!");
    }
});
```
My instincts tell me that the `resolve` and `reject` calls (though probably not the declarations on line 2) should really be highlighted as functions, but instead they get the "parameter" type for the duration of their existence. This is a pretty similar situation to /issues/91847

Maybe a more expressive way to deal with parameters vs variables vs properties, etc. is to have something like a modifier that represents scope? To me, "parameter" and "variable" are really just contextual modifiers that don't do anything to describe the _semantic role_ of any given identifier.

To stretch the analogy with human languages -- a noun can serve as a subject, a subject complement, a prepositional object, an _object_ complement, and many other roles within a sentence. The classification of _noun_ is really the least descriptive taxonomy you could assign, and if you were trying to highlight a sentence in a way that makes it easier to understand the semantics of it, one of the more descriptive classifiers would probably be more useful.

But maybe I actually have it backwards, and "noun" is analogous to the base token type while "subject" is more like a modifier. In that case, I do think we need much more fleshed-out modifiers for TypeScript (and maybe several different _types_ of modifiers for the spec in general, instead of lumping them all into one big "modifiers" bucket).

Obviously this feature is still in its infancy, so don't take this as a complaint or criticism. Really appreciate the work you've been doing on this and really thrilled to see it all finally coming together. I've been dying for this feature in VS Code for years and I'm absolutely loving it so far.

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/78169752-c3185900-7406-11ea-97ab-98dfae87a0da.png)
Still seeing parameter colors applied. Also, I remember seeing semantic tokens in the inspect widget, is that removed now?

**Comment by aeschli** [comment]
@JacksonKearl That's a weird state you are. The inspect window should show the semantic tokens. Instea it looks like semantic highlighting is not enabled here.
Are you sure this theme has semantic colors enabled?
If yes, would you mind filing a separate issue with all the info (sample source, what theme...)

**Comment by aeschli** [comment]
Version: 1.44.0-insider
Commit: 20b88fa0694cae8e46ffd305a1450ba58ae6065b
Date: 2020-04-01T08:29:34.507Z
With Dark+ theme

![image](https://user-images.githubusercontent.com/6461412/78183517-50d86080-7468-11ea-8de8-fa4185dd7566.png)

**Comment by JacksonKearl** [comment]
verified in Dark+.
