### ISSUE TITLE
Automatic Fetch Run Or F5 debug/run button based on application type.

### ISSUE THREAD

**Issue by ankitkanojia** [microsoft/vscode#91040]
Actually, when create a react application from Visual studio code, we get successfully created the react project within the desired place, But the most difficult issue is we need to run the whole application either by the command(from the terminal) or need to install the appropriate plugin for the same.

Is that possible that whenever the project is rendered or selected it should automatically render the configuration for run/debug?

This feature provided by other editors, but I loved **vscode** so I think the community should integrate or upgrade this feature. if possible.

**Comment by isidorn** [comment]
This is currently not possible due to the debug architecture on the vscode side. We can not automatically infer what debugger to use etc 
However soon the extensions will be able to contribute actions to the debug start view and potentially the angualr extension could  contribute an action there to make this experience better.
Due to that closing this issue
