### ISSUE TITLE
Multiline Comments not rendering Correctly in Python (Request for change... not explicitly a bug)

### ISSUE THREAD

**Issue by PlanMan1717** [microsoft/vscode#91041]
I am using version 1.42.1 of VS Code, on Windows 10 Home.
If it is a problem with my editor theme -- well, i'm using the very popular One Dark Pro theme.
It may not be a problem with the theme. Because _`/*...*/`_ is recognised when I program C++
and _`<!-- ... -->`_ in HTML. And so forth.

I wish that I could have them rendered as the fancy comment style.
_`#i want this this`_ `'''but it's kind of like this'''`
Kind of hard to look at a wall of bright green strings everywhere.

I hope you can understand my frustration.

**-PlanMan1717**

**Comment by gjsjohnmurray** [comment]
Please paste screenshots of what you're getting and a mockup of what you want. Most web browsers can paste a clipboard image direct into the GH comment input field. Please also test with the default schemes (Dark+ or Light+).

**Comment by PlanMan1717** [comment]
As far as getting the screenshots:

I have the screenshots...
The first is with _One Dark Pro_
![Annotation 2020-02-20 153258](https://user-images.githubusercontent.com/51730258/74976384-a72c9b00-53f6-11ea-8f6c-624bcffbe951.png)
The second with _Dark+_ aka. _"Default dark"_
![Annotation 2020-02-20 1532582](https://user-images.githubusercontent.com/51730258/74976512-da6f2a00-53f6-11ea-8de1-8c03b453d08c.png)
The second with _Light+_ aka. _"Default light"_
![Annotation 2020-02-20 153828](https://user-images.githubusercontent.com/51730258/74976633-1d310200-53f7-11ea-911a-1611fce1d5a5.png)

**Comment by PlanMan1717** [comment]
As far as the mockup... Here is the best I could do.
![Annotation 2020-02-20 154347](https://user-images.githubusercontent.com/51730258/74976994-d1cb2380-53f7-11ea-878a-f6641e66bbff.png)
But of course with the `#`'s removed.

**Comment by gjsjohnmurray** [comment]
@alexr00 is this your field?

**Comment by alexr00** [comment]
Thanks @gjsjohnmurray for triaging this to me!

@PlanMan1717 based on the Python style guide, that's not recommended way to do a multiline comment: https://legacy.python.org/dev/peps/pep-0008/#block-comments
Because of that, we won't change it in the built in themes.
However, I get that this is common practice. It is tokenized as  `string.quoted.docstring.multi.python`. You have two choices from here:
1. Ask the owners of the One Dark Pro theme to color `string.quoted.docstring.multi.python` as a comment.
2. Add something like the following to your settings.json:
```
	"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"scope": "string.quoted.docstring.multi.python",
				"settings": {
					"foreground": "#7F848E",
					"fontStyle": "italic"
				}
			}
		]
	},
```
You can see the scope and token coloring info for various tokens by running the Inspect Editor Tokens and Scopes command.
