### ISSUE TITLE
Cannot edit in "Open Changes" diff-view

### ISSUE THREAD

**Issue by RodrigoRoaRodriguez** [microsoft/vscode#91065]
- VSCode Version: 1.42
- OS Version: macOS Catalina 10.15.3

Steps to Reproduce:

1. Open a file with changes
2. Press on the "Open Changes" icon 
3. Try to edit either the left or the right side 

Expected behavior:
Both sides of the diff-editor are editable

Actual behavior:
Neither side is editable.  Both editors are read only and display a "Cannot edit in read-only editor" tooltip 

![image](https://user-images.githubusercontent.com/6189778/74923191-a3861d80-53d0-11ea-8dff-ab90f876391b.png)

Does this issue occur when all extensions are disabled?: Yes
![Screenshot 2020-02-20 at 10 48 29](https://user-images.githubusercontent.com/6189778/74921963-cd3e4500-53ce-11ea-8ac9-5cc3ce08c7c9.png)

Not only did I disable all extensions but also deleted all settings

![image](https://user-images.githubusercontent.com/6189778/74923309-d7f9d980-53d0-11ea-9932-21f4049d58d4.png)

**Comment by mjcrouch** [comment]
The title of the diff says `(Index)` - this means you have staged the changes, and you are diffing the staged changes against the head revision

You can never edit the left side as this is a read only file from the git history
You cannot edit the right side because the changes are staged - you need to edit the working copy and stage those changes as well, or unstage and edit the file
