### ISSUE TITLE
Wrong Cursor column numbers

### ISSUE THREAD

**Issue by rexx6** [microsoft/vscode#91060]
- VSCode Version: 1.42.1
- OS Version: windows7

Does this issue occur when all extensions are disabled?: Yes

![foo1](https://user-images.githubusercontent.com/28583017/74920455-86247400-540f-11ea-95bd-7ebfb0471f74.gif)

Hello!

As shown in the attached figure,

the cursor is in the same position but the numbers are wrong.

How can I solve this?

In the case of 2-byte characters, that phenomenon seems to occur.

Please answer. Thank you.

**Comment by alexdima** [comment]
@rexx6 I am sorry, but I don't quite understand from your screenshot what the problem is. Please consider I am not familiar with the characters you use. Can you please explain in greater detail what the problem is and what you would expect? Also, can you please include copy-paste friendly variant of the text?

**Comment by rexx6** [comment]
ㅁ
