### ISSUE TITLE
Extension dependency check doesn't check remote extensions

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#91109]
js-debug is going to depend on its [companion extension](https://github.com/microsoft/vscode-js-debug-companion). The readme in the companion extension has more details around our scenario.

js-debug is a workspace-only extension, and its companion is a UI-only extension. It seems like the extension dependency checking code isn't aware of this. Although I have the companion installed locally (and installed, but not active, in the remote)...

![image](https://user-images.githubusercontent.com/2230985/74970864-fe6d4400-53d3-11ea-8203-24645fd4af12.png)

The dependency check fails and always prompts me to reload the window:

![image](https://user-images.githubusercontent.com/2230985/74970884-088f4280-53d4-11ea-804b-90bada6e0167.png)

**Comment by alexdima** [comment]
@connor4312 Usually, when an extension (`A`) depends on another extension (`B`), this might mean that `A` will use API exported from `B`. The problem is that this is a synchronous API which was defined before we supported a remote extension host and many extensions were written with this in mind. So they expect `vscode.getExtension('B').exports` to work in `A`.

The solution is for you to "promise" that you never use sync API. You can achieve that by using `"api": "none"` in the `package.json` of `B`.

**Comment by connor4312** [comment]
Yep, that works, thanks! I'll open an issue to mention that on the docs--didn't see any mention of this on the remote extension authoring or extension management page.
