### ISSUE TITLE
Terminal weirdness on Windows remote

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#91119]
- SSH from Mac to Windows remote
- I am just collapsing and expanding the panel with cmd+J

![Feb-20-2020 17-07-34](https://user-images.githubusercontent.com/323878/74994818-ec0afe80-5403-11ea-951d-bc0ac8d04b39.gif)

**Comment by IllusionMH** [comment]
Looks like behavior described in https://github.com/microsoft/vscode/issues/91135#issuecomment-589616853

**Comment by Tyriar** [comment]
So remote terminals are still stuck on winpty due to https://github.com/microsoft/vscode/issues/76548, so behavior is expected to be a little different. Additionally resizing terminals can often cause weird wrapping problems for Windows, but it looks like collapsing the panel is causing a resize to fire with small dimensions which isn't expected.

This might be different to #91135, that may be a race with the viewport not updating when resizes happen in quick succession?

**Comment by Tyriar** [comment]
While this bug may only be visible on Windows, the resize it likely also happening on Linux and mac which is redundant.
