### ISSUE TITLE
Can't Download or Update any Extension.

### ISSUE THREAD

**Issue by hazemessam** [microsoft/vscode#91113]
- VSCode Version: 1.42.0
- OS Version: Windows 10 18362

I can't update or download any extension from my vs code in addition to its icons and description doesn't appear. But when I use 4G connection from my phone they appear.
![vscode-error-1](https://user-images.githubusercontent.com/49886457/74973057-73b83380-542b-11ea-81a5-2ddd9aeaf41d.jpg)
![vscode-error-2](https://user-images.githubusercontent.com/49886457/74973062-74e96080-542b-11ea-855f-3a091327c447.jpg)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by hazemessam** [comment]
I changed the DNS to 1.1.1.1. the Icons and description appear but I still can't download any extension. 

![vscode-error-3_LI](https://user-images.githubusercontent.com/49886457/75200093-8b662380-576d-11ea-881b-865826ed9bc0.jpg)

**Comment by hazemessam** [comment]
Help -> Toggle Developer Tools -> Console
![err-0](https://user-images.githubusercontent.com/49886457/75201406-0846cc80-5771-11ea-92ed-6922959426e7.jpg)

View -> Command Pallette... -> Toggle Shared Process -> Console
![err-1](https://user-images.githubusercontent.com/49886457/75201408-0977f980-5771-11ea-9f08-ced9d9395961.jpg)

View -> Open View… -> Log (Shared)
![err-2](https://user-images.githubusercontent.com/49886457/75201414-0b41bd00-5771-11ea-8d1a-2455664a4a42.jpg)

View -> Open View… -> Log (Window)
![err-3](https://user-images.githubusercontent.com/49886457/75201415-0c72ea00-5771-11ea-9f5d-2dc15d6074fe.jpg)

**Comment by sandy081** [comment]
Are you behind any proxies?

**Comment by hazemessam** [comment]
No

**Comment by sandy081** [comment]
Looks like your network problem. Not sure how we can be helpful. Please contact your network administrator.

**Comment by hazemessam** [comment]
Ok, Thanks for your time.
