### ISSUE TITLE
Drag and drop tabs from this window to other one

### ISSUE THREAD

**Issue by tungvn** [Microsoft/vscode#9111]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Open a new file in new window
2. Can not drag and drop this tab to old window

**Comment by bpasero** [comment]
Already fixed in master, you could give it a try from insiders:

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
