### ISSUE TITLE
';' will be removed after executing formatting

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#9112]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:52:42.674Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:

1.  open a file, right click the content.
2. select formatting

**Comment by weinand** [comment]
@calidion formatting depends on the type (language) of the file. What type of file are you referring to?

**Comment by calidion** [comment]
@weinand 
javascript

**Comment by weinand** [comment]
@calidion cannot reproduce. Please provide a file where we can try to reproduce the issue.

**Comment by calidion** [comment]
@weinand 
is is very simple to reproduce.
a single code snippet will do.

before:

```js
module.exports = function (model) {
  return {
    list: function (req, res, model) {}
  };
};
```

after:

```js
module.exports = function (model) {
  return {
    list: function (req, res, model) {}
  }
}
```

**Comment by weinand** [comment]
@calidion thanks, for the snippet, but I still cannot reproduce it.

It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by calidion** [comment]
seems caused by extension.
thanks.
