### ISSUE TITLE
Save appears to work but is inconsistent with filesystem

### ISSUE THREAD

**Issue by monsieursheep** [microsoft/vscode#91149]
Issue Type: <b>Bug</b>

Editing files on macOS in Documents folder that is iCloud synced.  Issue has happened regularly but not predictably based on action.

- Save button appears to work but is inconsistent with filesystem
- Spinning circles appears in Explorer view and save doesn't work (doesn't give an error either)
- Trying to quit the application doesn't work, force quit is required.

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:57:51.166Z)
OS version: Darwin x64 19.0.0

**Comment by bpasero** [comment]
VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

Reading this issue, it seems to originate not from VSCode itself but rather one of these upstream components. As such, in order to resolve it, it would need to get fixed in the upstream component. I will go ahead and close this issue and kindly ask to report this issue to the upstream component if possible:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.

**Comment by monsieursheep** [comment]
Are there any notes on how to debug the platform or get more diagnostics to narrow down the cause of hangs with filesystem writes?

It's making the product unusable - I have to force quit the application every ~10 minutes.

I also get the same behaviour on the insiders edition.

**Comment by bpasero** [comment]
My feeling is that this is an issue with how VSCode talks to the file system for reading and writing files. Under the hood we use node.js (https://github.com/nodejs/node) for reading and writing files (https://nodejs.org/docs/v12.8.1/api/fs.html). It would be interesting if a standalone node.js sample for reading and writing files exhibits similar issues.

**Comment by bpasero** [comment]
We also have some log files that we accumulate, maybe you can check if something spurious shows up.

**Comment by monsieursheep** [comment]
When it locks up I just see this in the Explorer view. It appears to be transient and sometimes recovers (after a few minutes)

<img width="44" alt="Screenshot 2020-02-27 at 16 39 59" src="https://user-images.githubusercontent.com/4751964/75465054-02730600-5980-11ea-9cb6-6d891eb3866c.png">

**Comment by bpasero** [comment]
Yeah this indicates that a call to the file system for resolving the children of a folder just takes very long. I doubt there is anything VSCode can do better, we really just rely on the OS to give us the folders.
