### ISSUE TITLE
cant drag the folder to the editor. 

### ISSUE THREAD

**Issue by cray2015** [Microsoft/vscode#9116]
- VSCode Version: Code 1.3.0 (e724f269ded347b49fcf1657fc576399354e6703, 2016-07-07T16:56:12.476Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. open a new window in VS code
2. try to drag and drop the folder in the editor, the window flickers but it shows No folder in the left panel.

**Comment by bpasero** [comment]
Fixed in insiders.

We are releasing preview releases of the next stable VS Code version for everyone to try and give feedback. These preview releases are not 100% tested and might be unstable but contain our latest features and bugfixes. You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
