### ISSUE TITLE
Allow to rename untitled editors

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#91191]
If you go File > New File..., it will create a file called Untitled-1. But because it doesn't have that circle mark next to it, it looks like it's saved. We did user studies with students and two participants were really confused as why they couldn't rename it. It seems they assumed it was auto saved in the workspace:

![image](https://user-images.githubusercontent.com/45497113/75082270-a3b51480-54c7-11ea-9bb2-aa66adb8daab.png)

The bullet only appears when you start typing:
![image](https://user-images.githubusercontent.com/45497113/75082348-fabae980-54c7-11ea-864a-83a30cceeae0.png)

I think that keeping the bullet on file creation could be less confusing.

**Comment by misolori** [comment]
I'm curious where they were trying to rename this from? Or what they were trying to do/achieve? We don't offer any renaming options except in the explorer. 

If we show the dot, then that means that we show the confirm dialog because it's closing a dirty file:

![image](https://user-images.githubusercontent.com/35271042/75083885-25f60680-54d1-11ea-8a96-16afe425e6f3.png)

I guess one could add the option to rename an untitled file?

**Comment by luabud** [comment]
Hm that's a good point, I actually thought we could rename by right clicking on the file name in the editor, but we can't:

![image](https://user-images.githubusercontent.com/45497113/75084175-28596000-54d3-11ea-8d29-91195c32d312.png)

That's what two of them tried to do. And then one of them also tried it by right-clicking on the file in the open editors window:

![image](https://user-images.githubusercontent.com/45497113/75084197-59399500-54d3-11ea-877b-3dda395ec2f5.png)

**Comment by bpasero** [comment]
There are two things being asked here:
* show dirty for untitled right from the beginning
* allow to rename untitled files

Since we typically do not allow to have 2 things asked for in 1 issue, I have picked the one that I thought was the final verdict of the discussion, to allow for renaming untitled editors.
