### ISSUE TITLE
Allow modifying right side in Source Control -> changes view

### ISSUE THREAD

**Issue by eduherminio** [microsoft/vscode#91274]
When comparing changes before committing, it would be extremely useful to be able to work in the right side of the comparison, as it can be done in Visual Studio.
Currently, the following message is shown: `Cannot write in read-only editor`.

Related to #66196, but different use case IMO.

**Comment by IllusionMH** [comment]
You can do that if you open changes from Changes or Untracked changes, however it's impossible to do that for Staged changes (because they should display actual staged changes which can't be updated until you edit, save, and stage new edits). 

However you can quickly navigate to regular edit tab (preserving cursor position) using Open file button (`>Git: Open File` or `git.openFile` for keybinding).
![image](https://user-images.githubusercontent.com/1312662/75173954-5ee3e480-5738-11ea-80f2-a08d6f61844f.png)
