### ISSUE TITLE
feature parity between DecorationRenderOptions and ThemableDecorationAttachmentRenderOptions

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#9129]
- VSCode Version: 1.3.0

I would like to see more feature parity between `DecorationRenderOptions` and `ThemableDecorationAttachmentRenderOptions` to whatever extent is possible.

If there is a particular reason why one supports a styling property that the other does not, what are the limitations and is overcoming them on the roadmap? (Some differences, like `contentText`, are obvious and do not need an explanation.)
1. `DecorationRenderOptions` allows setting all of the various border styles independently, while `ThemableDecorationAttachmentRenderOptions` provides only a `border` property, which does not allow different styles for top, left, right, and bottom.
2. Only `DecorationRenderOptions` has outline styles.
3. Only `ThemableDecorationAttachmentRenderOptions` has `margin`.
4. Only `ThemableDecorationAttachmentRenderOptions` has `height` or `width`; are these solely used for the dimensions of `contentIconPath`?

**Comment by alexandrudima** [comment]
In general, I think we are open to add more custom (per decoration instance) render options.

But we try to limit them -- the reason is simple: we want to encourage folks to not customize each decoration instance's style, because for each custom decoration instance style, we end up creating/writing CSS on-the-fly, which is costly. 

If an extensions has 3-4 different types of decorations, it is (performance-wise) vastly preferable to create 3-4 decoration types (creating/writing CSS once) and then create decorations (with the same style) for each type.

**Comment by siegebell** [comment]
@alexandrudima It doesn't seem that performance is related to getting a consistent interface across all of the decorations, then :)

I'll paraphrase what I think your concern is:
> Each call to `createTextEditorDecorationType` is expensive. Try to avoid allocating decoration types and reuse them whenever possible. We discourage overuse of decorations because they slow down all of vscode, not just the extension.

I've also noticed that `setDecorations` is a little slow (starting at ~20ms baseline on my computer, and *much* slower if given a large array of ranges, say > 5000).

Once allocated, are there any additional performance penalties for having many decoration types? When multiple extensions use decorations, does the slowdown scale worse than linearly? *Ignoring decoration-type allocation costs*, is it better to 1) allocate a few small decoration types (i.e. few properties per type) and combine them together in different ways via overlapping their ranges in multiple calls to `setDecorations`, or to 2) allocate all the needed permutations of properties as separate decoration types, not overlap them, and thus make fewer calls to `setDecorations`?

Thanks in advance!

**Comment by alexandrudima** [comment]
Decoration types, once created IMHO do not have anymore a performance impact (if we ignore the cost the browser rendering engine incurs in having one more css rule to match against).

The slowdown with decoration instances is at worst case linear (which is already too high), but most of the times the cost is localized to the number of decorations in the viewport. There are many aspects to the costs decorations in general incur:

When editing the buffer:
* the markers that represent the decorations must be updated (decorations are live)
* an event describing the changed decorations is generated and propagated to the view model
* the view model converts the new decorations ranges from model coordinates to view model coordinates
* the view needs to invalidate and repaint all the changed decorations in the viewport

When rendering a frame:
* for each decoration, we need to go and ask the browser where it ended up painting the text the decoration sits on because we don't do text layout (think bi-di, right-to-left), the browser does that
* so when painting we paint the text in the viewport
* and then for each decoration that is in the viewport we ask the browser where the text the decoration is supposed to sit on landed
* then we finally paint the decorations
* if there are 10k decorations in the viewport, it is very easy to go above the budget of 10ms to paint a frame.

It is not clear to me what you want to do. What is the specific thing you're trying to accomplish and maybe I can give better answers than in general ...

**Comment by siegebell** [comment]
@alexandrudima I'm very satisfied by your answer, thanks!

I've written a prettify-symbols-mode extension (#2402, [marketplace](https://marketplace.visualstudio.com/items?itemName=siegebell.prettify-symbols-mode)), and my performance concern is that it relies on decorations much more than a typical extension.

In practice, I do not expect many decorations to be visible in the same viewport, but the user has the ability to control where the decorations appear so it is possible. My extension creates the many decorations (one for each user-defined substitution) only at initialization or configuration-change, so I think I'm safe :).

Back to why I created this issue in the first place: Instead of (or in addition to) replacing some text with a symbol, I want the user to also be able to apply some subset of CSS styles to the matched text or symbol. Because the decoration might be applied to a `ThemableDecorationAttachmentRenderOptions` or `DecorationRenderOption`, it is easier for me if all the types of decorations support similar CSS properties.

**Comment by aeschli** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: There hasn't been any other request for the API and we'd rather keep the APIs minimal.
If you disagree and feel that this issue is crucial: We're happy to listen and to reconsider.
Thanks for your understanding. Thanks for helping and happy coding!
