### ISSUE TITLE
Exploratory test: Updated webview editor proposal

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#91325]
Test for #77131 

- [x] any @bpasero
- [x] Any @alexr00

Complexity: 5

**(Note: please hold off on testing this until Wednesday. We will be reviewing the API at the API sync and it may change before then)**

**Background**
We've made some significant changes to the webview editor API proposal this iteration:

- There are now two types of webview editors and two contributions for them:

    - Text based webview editors use a `TextDocument` as their model.

    - Custom webview editors let extensions provide their own model. This is provided using a `WebviewEditorCustomDocument`

- We've also added a `backup` method for custom editors to support hot exit

You can find examples of these two editors types here: https://github.com/mjbvz/vscode-experimental-webview-editor-extension

**Testing**
Try implementing both a text based webview editor an a fully customizable editor.

With the text based webview editor, some areas to explore:

- You can register your webview editor, it is activated as expected, and it receives the expected `TextDocument` object
- You can use the `Reopen with...` command to switch between your webview and the text document. No content should be lost during this change.

With the custom webview editor, verify that:

- Your custom documents have the expected lifecycle
    - A custom document should be created when you first open a file.
    - That document should be re-used as more editors are opened for that resource
    - If you close all editors, the custom document should be disposed of
    - At which point, opening the resource again should trigger a new document to be created.
- Your webview gets the expected undo, apply, save events.
- Your extension is called as expected to perform hot exit actions

Overall, looks to see:

- Does the api documentation make sense
- Are there any apis you wish you had to implement your extension?

**Comment by mjbvz** [comment]
I pushed the API update from our discussion so you should be good to start testing

**Comment by alexr00** [comment]
@mjbvz when testing the `CustomEditorProvider` I can't add `userData` to the `CustomDocument` in `resolveCustomDocument`. Is this just because I need to wait for the next insiders update to test that?

**Comment by mjbvz** [comment]
@alexr00 Good catch, that's a real bug. I experimented with using `Object.seal` on the returned custom document but forgot in the case of userData that that prevents you from first setting the property value :(

**Comment by bpasero** [comment]
I finished testing custom text editor API. I did not finish testing custom non-text editor API, but filed a few issues. I am OK if someone else wants to continue the non-text custom editor API testing.

**Comment by alexr00** [comment]
I'm going to call my testing for this done since it has to stop at some point. However, I feel that you could spend days testing this and the testing will still be useful.

**Comment by bpasero** [comment]
I am also going to call it OK for now. If I had to summarize: custom text editors are a pleasure to work with and the model makes sense for me. Custom non-text editors are very very hard to get right imho because of the complexity of having to deal with everything through post message calls from the webview and then expressing changes as edits. 

I ended up keeping the entire buffer of the file in memory for each change that was made to be able to undo/redo. And even that was hard to get right because the undo is started from the extension host, going to the webview and then for that duration I have to make sure that I am not accidentally treating that change as another edit.

My 2 cents: I wonder if we should trim the custom editor proposal down to the custom text editors and leave the non-text based editors to use just webviews as today. In that world, every change that you do to such an editor would have to be saved immediately and there would be no dirty reporting. But we can discuss that when we pick up discussion again.
