### ISSUE TITLE
Support Markdown relative path to folders

### ISSUE THREAD

**Issue by sonofachamp** [microsoft/vscode#91336]
If I have a `[relative path folder link](path/to/something/interesting)` it'd be sweet if clicking that link in Markdown preview opened that folder in the VSCode explorer (not Windows). Right now these types of links work on GitHub, but they don't work when `Ctrl + clicking` them within the Markdown preview in VSCode.

**Comment by mjbvz** [comment]
Is this the same request as #90956?

**Comment by sonofachamp** [comment]
@mjbvz I don't think so. The paths being relative to the `.md` file location is fine, but if I link to a folder instead of a file I'd like that folder to open in the Explorer window within VSCode.

**Comment by mjbvz** [comment]
Thanks for the clarification. PRs welcome for this

**Comment by dormesica** [comment]
I would like to help with this.
Can I get some direction on where to start looking?

**Comment by mjbvz** [comment]
Here's the code the I believe handles this: https://github.com/microsoft/vscode/blob/2fe62e7dfec6fcff6e037e5fbc12082d43d98c0e/extensions/markdown-language-features/src/commands/openDocumentLink.ts#L46

You likely need to check if the link points to a folder and handle that case. Try debugging through to see if that's the case

**Comment by dormesica** [comment]
I think I undersand what's happenings there:
https://github.com/microsoft/vscode/blob/14b5afc0ecfd2908e5f853a97117fa984bbd633d/extensions/markdown-language-features/src/commands/openDocumentLink.ts#L50-L53

The first call to `tryOpen` fails because because `targetPath` points to a folder not a file. Then, there is an attempt to add the `.md` extension to the path which fails bacause there is not such flie which causes something like unhandled promise rejection.

I didn't find any command that reveals the folder row in the explorer. Using `vscode.commands.executeCommand('vscode.open', uri);` works but shows a notification error saying "Unable to open ... file is a directory".

**Comment by mjbvz** [comment]
@isidorn Is there a command that reveals a folder in the explorer?

**Comment by isidorn** [comment]
@mjbvz no, there is only `Reveal Active File in SideBar`.

**Comment by dormesica** [comment]
@isidorn Is it possible to expose such a command? I wouldn't mind giving a hand.

**Comment by isidorn** [comment]
@dormesica not right now, but we might consider adding it in the future if there appear more use cases for it.

**Comment by mjbvz** [comment]
Ok, I'm unmarking this as help wanted then and marking as a feature request so we can gauge interest.

Thanks for investigating this @dormesica!

**Comment by memark** [comment]
@mjbvz This issue still shows up under "Good first issues", which I assume it shouldn't since you removed those tags.
