### ISSUE TITLE
minimap's "cover" mode no longer faithfully represents the file's content

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#91365]
testing #91250:

- set "editor.minimap.mode" to "cover"
- set "editor.minimap.renderCharacters" to true
- open vscode.d.ts
- scroll to line 7068

Observe: 
editor contents:
![2020-02-25_12-43-12](https://user-images.githubusercontent.com/1898161/75244706-92704e80-57cc-11ea-9219-b3ef77b5b18e.png)

minimap (at 400%) shows:
![2020-02-25_12-54-09](https://user-images.githubusercontent.com/1898161/75245414-f34c5680-57cd-11ea-8ed0-e929379a79f8.png)

The grey lines (the viewport) indicate that the editor viewport contains no code. But this is not true - the viewport is full of code.

Typing in that area does not have any effect on the minimap (which is probably a good thing but does not strengthen the confidence that the minimap faithfully reflects the editor content).

**Comment by alexdima** [comment]
I am afraid this is a result of sampling...

I have tried vscode.d.ts with word wrap on and with a height similar to the one in your screenshot (around 30 lines visible). The sampling ratio I got was around 10, so for every 10 lines in the editor, one line will be selected and rendered in the minimap and 9 lines will be ignored (complete information loss). The initial selection is not based on anything except a multiple of the ratio and some rounding, so it is possible that out of 10 lines, where 9 lines contain code and 1 line is empty, precisely the empty line is chosen...

So if there are 3 empty lines in your viewport, it is possible that exactly those 3 empty lines were the ones chosen for sampling. 

This can be taken to the extreme and I can offer a much simpler case for worst-case scenarios, like the following file where 1 line has content and 1 line is empty and this alternates. Then, I resize the height of the editor, such that the sampling ratio is a bit higher than 2. This results (based on rounding) on patches where odd lines are selected continuously, and patches where even lines are selected continuously:

![image](https://user-images.githubusercontent.com/5047891/75395323-6ea72880-58f2-11ea-900c-77c46f78782e.png)

So the minimap makes it appears that the middle of the file does not contain any text, but that is simply selection bias of the empty lines due to the rounding.

I have considered this, and I agree that it is unfortunate, but this is a direct limitation of the sampling technique. Anything else I can come up with results in paying the cost of the entire file, i.e. today, opening a file of 100k lines now pays the cost of sampling 1k lines, opening a file of 1MM lines also pays the cost of sampling 1k lines... That sampling is flawed, and the sampled lines might not be representative of all the lines, etc...

But anything else I can think of would be also imprecise (after all, there will be information loss regardless when painting 100 lines in 1px)... but will also be computationally expensive.

All in all, I think I am saying that this is a limitation and I won't fix it unless some brilliant idea comes along :).
