### ISSUE TITLE
Global undo dialog feedback

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91368]
Refs: https://github.com/microsoft/vscode/issues/91248#event-3067581636

About this dialog:

![image](https://user-images.githubusercontent.com/900690/75247488-4d4f1b00-57d2-11ea-8761-25fd34bccbf0.png)

I personally find the use of "Yes/No" followed with a comma for a button a bit weird.

Suggestions:
* No, change only this file => Undo This File
* Yes, change N files => Undo All Files

As for the message, then maybe we should list the file names explicitly to make things more obvious? Take for example our combined close dialog:

![image](https://user-images.githubusercontent.com/900690/75247654-b59dfc80-57d2-11ea-91ef-66ec0613a705.png)

Lastly I would expect a "Cancel" button so that this dialog essentially becomes very similar to the combined close dialog.

//cc @weinand as good source for naming

**Comment by alexdima** [comment]
Thank you, very good suggestions.
* I've added the Cancel for #91388
* I would not list the files because at one point we want to have more than text edits, such as file deletions, file renames, and IMHO representing those in this dialog would not work well.
* I will push a tweak to the label of the buttons:
  * "Yes, change 3 files" => "Undo in 3 files"
  * "No, change only this file" => "Undo this file"

**Comment by bpasero** [comment]
@alexdima better, but I find 2 issues still:
* there is a trailing dot it seems in button labels
* I would use capital casing for buttons

![image](https://user-images.githubusercontent.com/900690/75416363-6b319280-592e-11ea-8ec1-42d8996893f5.png)

Also looks like a clash in quotes because the label includes quotes. Maybe strip quotes from the label and then surround it?

**Comment by alexdima** [comment]
:+1: I liked all of your suggestions, so I pushed them.
