### ISSUE TITLE
Let showTextDocument always create a new tab

### ISSUE THREAD

**Issue by jaydenlin** [Microsoft/vscode#9138]
I used `showTextDocument` in my extension.
```
vscode.workspace.openTextDocument(filePath).then(doc=> {
     vscode.window.showTextDocument(doc);                   
});
```
However when the `filePath` changes, it always refreshes the same tab for the new doucument.
Is it possible to create a new tab for the new doucument ?
Thank you in advance.

**Comment by bpasero** [comment]
@jrieken the related editor option is `pinned: true`

**Comment by jaydenlin** [comment]
Hi @bpasero,
Thank you for the reply.
But how do I apply `pinned: true` to my code ?
Could you kindly provide some examples ?

**Comment by jrieken** [comment]
@bpasero what are the semantics of `pinned` when no tabs are used?

**Comment by bpasero** [comment]
@jrieken we have `preview` and `pinned` editors also when tabs are disabled. when tabs are enabled it just becomes more obvious which editor is open but the concept of having a preview editor applies also when tabs are disabled. so it is perfectly valid to have this option when tabs are disabled.

When I think about the API, maybe it would be wise to introduce an overload of `showTextDocument` that takes an option bag as second argument, instead of adding more and more boolean flags to the method. If in the future we decide to add more options, we could just add more optional things to the bag.

As for the naming, I am not sure we want to drag `pinned` into the official API. In the UI we show "Keep Open" to pin it as name, we never talk about "pinning".

**Comment by jrieken** [comment]
+1 for having an overload with a property bag

**Comment by jrieken** [comment]
The problem with this `keepOpen` flag is that it gives the impression the editor (as the object you program against) will be kept open (as in active/not disposed) but that's not true since in the API world models that are bound to an editor are considered an 'editor'. Maybe we should just change the default to be pinned always.

**Comment by jrieken** [comment]
this got implemented via: https://github.com/Microsoft/vscode/pull/23641
