### ISSUE TITLE
Improve naming of "editor.minimap.mode" setting and its values

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#91405]
Testing #91250:

When reading the following in my settings file, I have no idea what this means:
```
"editor.minimap.mode": "actual",
```

And I have a hard time understanding what the other two "modes" "contain" and "cover" really mean.

So I tried hard to understand what is controlled by the "mode". On a mathematical level it is a "projection", but this is not something to "throw" at users.

On a simpler level it is the "size" of the minimap.

Based on this we could rename "mode" to "size" and use these values and descriptions:

- "sameSize": Minimap has the same size as the editor contents (and might scroll).
- "shrink": The minimap will shrink as necessary to never be larger than the editor (no scrolling).
- "shrinkOrExpand": The minimap will stretch or shrink as necessary to fill the height of the editor (no scrolling).

**Comment by alexdima** [comment]
| | `actual` | `contain` | `cover` |
|---|---|---|---|
| small | ![image](https://user-images.githubusercontent.com/5047891/75426604-53193d80-5945-11ea-85da-b9e36d163a01.png) | ![image](https://user-images.githubusercontent.com/5047891/75426684-747a2980-5945-11ea-9c1f-73068d63de8a.png) | ![image](https://user-images.githubusercontent.com/5047891/75426865-c327c380-5945-11ea-934a-3b427a272e3f.png) |
| large | ![image](https://user-images.githubusercontent.com/5047891/75426630-5c0a0f00-5945-11ea-9a89-bec6572d94cd.png) | ![image](https://user-images.githubusercontent.com/5047891/75426799-aa1f1280-5945-11ea-946f-7a68dcbf7671.png) | ![image](https://user-images.githubusercontent.com/5047891/75426890-cf138580-5945-11ea-9373-779dae042b2c.png) |
| current | `minimap.mode: actual` | `minimap.mode: cover` | `minimap.mode: contain` |
| opt1 | `minimap.size: sameSize` | `minimap.size: shrink` | `minimap.size: shrinkOrExpand` |
| opt2 | `minimap.height: proportional` | `minimap.height: fit` | `minimap.height: fill` |

**Comment by alexdima** [comment]
We decided in the standup to go with `minimap.size` and the values `proportional`, `fit` and `fill`.

**Comment by gjsjohnmurray** [comment]
> 
> 
> We decided in the standup to go with `minimap.size` and the values `proportional`, `fit` and `fill`.

Is it too late to lobby for this to be changed to `minimap.height` rather than `minimap.size`? Reason being, I'd like to request a future enhancement that'd allow me to set a maximum pixel width for the minimap. On wide screens the way the minimap width increases proportionally to the display width of the file means it can become unnecessarily wide. 

Narrow:
![image](https://user-images.githubusercontent.com/6726799/75539787-bc1ab700-5a12-11ea-8b33-81bdf1000947.png)


Wide:
![image](https://user-images.githubusercontent.com/6726799/75539871-dfddfd00-5a12-11ea-8eaf-f8faa970b84b.png)


Seems to me that the left-side portion of the minimap is often sufficient to give me a sense of where I need to scroll to.

**Comment by gjsjohnmurray** [comment]
Nevermind. I've just noticed `editor.minimap.maxColumn` already exists.

With `"editor.minimap.maxColumn": 30` my wide screen layout becomes:
![image](https://user-images.githubusercontent.com/6726799/75540277-9e018680-5a13-11ea-98dd-53510c57c395.png)
