### ISSUE TITLE
Notifications UX feedback

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#91446]
Refs: #91163

There are some things which I dislike about the notifications UX:
1. Top level hide uses the Escape icon, same as the icon per notification which has a stronger meaning. Suggestion -> we should use a different icon for the top level action
2. The difference between an unread and a hidden notification is not very clear to me and I think it can be confusing to our users. When do I actually see a badge in the notification bell? Since I do not see it if I just hide all my notificaitons with ESC. Do you treat them as read then? 
3. There should be clearer UX indication that the top level actions are run on everything, Currently that is not the case as they look tied to the top level notification.

**Comment by bpasero** [comment]
> Top level hide uses the Escape icon, same as the icon per notification which has a stronger meaning. Suggestion -> we should use a different icon for the top level action

@isidorn to clarify, you mean that the top level X just closes the center while the notification X deletes it. I think one suggestion was to use the arrow down icon from the panel:

![image](https://user-images.githubusercontent.com/900690/75317578-a8cbe800-5868-11ea-9945-212399b26231.png)

> When do I actually see a badge in the notification bell? Since I do not see it if I just hide all my notificaitons with ESC. Do you treat them as read then?

No, pressing ESC or waiting until the toast is removed does not mark it as read. The reasoning is that ESC can be pressed accidentally without paying attention to notifications and since the hide after timeout, we also do not know if they were read. This is consistent with what Windows does for notifications afaik.

> There should be clearer UX indication that the top level actions are run on everything, Currently that is not the case as they look tied to the top level notification.

I think the icon for dismissing all notifications is consistent with other places like search results. I am not sure what you mean with the X icon running on everything, that one simply closes the notification center. Please clarify.

**Comment by misolori** [comment]
I’d be in favor of using the down chevron to hide the notification center (pretty sure we’ve discussed this before)

**Comment by bpasero** [comment]
I can do that change for Feb if we think it is the right way.

**Comment by isidorn** [comment]
1. Yes I mean the top level x. Using the chevron makes more sense here, agree
2. Ok. This makes sense, issue https://github.com/microsoft/vscode/issues/91444 was confusing me
3. I meant that it is a global action and visually it looks more tied to the top most notification than to the whole notification center. I believe the top level actions need some more ux polish to make them look more global.

**Comment by bpasero** [comment]
Fixed the close icon to show like this:

![image](https://user-images.githubusercontent.com/900690/75339244-70400480-5890-11ea-83be-2b1077e9ccae.png)

As for making the actions look more global I am open for suggestions. Maybe you can bring it up at the next UX call with ideas if you have any.

**Comment by isidorn** [comment]
My idea is to use the border left and right around notification such that they look like they are floating in the Notifications area.
The top bar  and this border woul use the same darker background color.
