### ISSUE TITLE
Settings reordered by resolving conflicts

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#91484]
Testing https://github.com/microsoft/vscode/issues/91226

I set up sync in window A, set some settings, then set one setting in window B, enabled sync, and was confused by the conflict resolution diff.

Window A settings:

![75291846-e3d20b00-57d7-11ea-9d2b-5ee7e6a64df9](https://user-images.githubusercontent.com/10746682/75320033-16c6de00-586e-11ea-82e2-0511baaed01b.png)

Window B settings, I just set one:

![75291863-e896bf00-57d7-11ea-91c0-ef8b550fb82b](https://user-images.githubusercontent.com/10746682/75320041-1f1f1900-586e-11ea-90a7-b9011c108ca3.png)

And I got a conflict resolution prompt as expected, and clicked the button to see the diff, which is confusing. I expect to just see the one fontSize setting on the right. Or, I expect to see the merged settings on the right with just the one fontSize setting in conflict. Instead it reordered autoSave and autoSaveDelay:

![image](https://user-images.githubusercontent.com/323878/75291924-0e23c880-57d8-11ea-93f3-2cce9ccd4d66.png)

**Comment by sandy081** [comment]
Agree that this is confusing but can be explainable. Order of a setting is tried to retained while merging. It is retained by it's previous setting or by its next setting. 

Since `files.autoSave` and `files.autoSaveDelay` are after `editor.fontSize` they are tried to place under it when merged. Order of `editor.fontSize` is retained in the local (machine B) as it is the file that is getting merged and hence it is respected.

**Comment by roblourens** [comment]
I see, I'm not sure how it could be improved but yeah it's confusing that the result doesn't really match either the local or the remote settings.
