### ISSUE TITLE
Split Search Editor search box display not kept in sync

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#91492]
- VSCode Version: 1.43 Insiders
- OS Version: Windows 10

Found while testing #91331

Steps to Reproduce:

1. Open the vscode-docs repo and create an empty Search Editor
2. Search for "VSCode" and set Match Case and Match Whole Word
3. Split the Search Editor and change the right side to "VSCodex"

You see no results in either Search Editor but the left search box is not updated and still shows "VSCode". If you go to another editor and come back to the left Search Editor is correctly shows "VSCodex" used for the search.

If you change the right side back to "VSCode", the right side displays matches but the left side stay empty.

**Comment by gregvanl** [comment]
The left side empty results is scrolled up slightly and you can't see the "No Results" message

![image](https://user-images.githubusercontent.com/12818376/75297078-c6a33980-57e3-11ea-8d06-97e9413a1735.png)

**Comment by JacksonKearl** [comment]
Yeah, splitting a search editor is strange. I almost feel like it should just create two identical but non-synced editors.

**Comment by gregvanl** [comment]
Yep, that is what I initially expected, that the two would be decoupled. Split text editors are coupled so I then assumed that was the working model.

**Comment by JacksonKearl** [comment]
Splitting a search editor is a strange operation and I'm as of yet not sure what the desired outcome should be. In my mind, you'd split the search editor to maybe compare results between two similar searches, or keep one set intact while removing results from the other. So the contents should be initially the same, but not synced. Unfortunately thats not really possible with the current model of splitting, and I don't want to special case search editors into the core editor split logic. 

The weirdness where the other editor will sometimes scroll all the way down is unfortunate but looking at it I believe it will require quite a bit more work than it's worth to fix, again because of the lower-level nature of the split editor code.

Going to keep this open for now and see if more users hit it.

**Comment by JacksonKearl** [comment]
With 379e732 the editor can no longer be split. (split command will open an empty group instead)
