### ISSUE TITLE
Debug start view: Not shown after deleting launch.json

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#91499]
Testing https://github.com/microsoft/vscode/issues/91143

1. Open a new folder that doesn't have a launch.json
2. Go to the debug view and use the "create a launch.json file" command from there
3. Delete the generated `.vscode` folder that has the new `launch.json` file

I expected at this point that the view would revert back to the start view. Instead, it allows me to start running, which of course results in "Configuration 'Launch Program' is missing in 'launch.json'.", and then reverts back the start view:
![Screen Shot 2020-02-25 at 3 33 26 PM](https://user-images.githubusercontent.com/3672607/75297247-2f8ab180-57e4-11ea-99b4-58ddd65e8373.png)

(https://github.com/microsoft/vscode/issues/91426)

**Comment by isidorn** [comment]
This only happens if the `.vscode` folder is deleted.
Does not happen if you just delete the `launch.json`

The actual issue is that the deletion of the `.vscode` is not picked up by the `configurationService` and the configuration service does not fire a `onDidChangeConfiguration`.
Assigning also to @sandy081 

We were always behaving like this thus removing from February milestone.

**Comment by isidorn** [comment]
@sandy081 unassigning myself since this is in the `configurationService`.
imho we always beahved like this and we do not have to fix this milestone, though it would be nice.

**Comment by sandy081** [comment]
@isidorn This is working for me. I did some changes in configuration service especially in the area of listening and reacting to file change events. May be this would have fixed it. 

Closing this.

**Comment by isidorn** [comment]
Yeah it works great now, thanks @sandy081 . It would be great if @RMacfarlane also tries it out so we add a verified label.
