### ISSUE TITLE
Regression: No indication at all for long running task providers

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#91517]
With https://github.com/microsoft/vscode/issues/90087 we had a temporary fix for the long running task provider issue. This is no longer working. Now, I neither get the quick pick that allows me to cancel the detection nor do I get the notification we had before. I now have to wait for however long it takes.

1.43.0-insider
89cafb24e5d75a0c8d561a6cdd95e93b5679e152
x64

on macOS

**Comment by alexr00** [comment]
This is the correct behavior right now. I reverted all recent changes to the task quick pick.

The thought process behind this was that the intermediate quick fix I had done had some problems, which I had fixed in the streaming solution. However, we decided not to go with the streaming solution and instead go with a solution that shows the recent tasks, configured tasks, and then the individual task providers. This solution will have better performance than even the streaming solution since we are only asking for the tasks from the providers when the user picks which provider they want.

Instead of merging the streaming solution and having a task quick pick solution that changed dramatically for 3 releases, I reverted to what we had in the last release.
