### ISSUE TITLE
Custom editor: intellisense for provider is misleading

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#91560]
Refs: https://github.com/microsoft/vscode/issues/91325

![image](https://user-images.githubusercontent.com/900690/75341458-c9119c00-5894-11ea-9edb-498f5bcc4c0b.png)

This looks like I have to implement all methods, which is not true.

**Comment by mjbvz** [comment]
I believe this is a TS limitation (or by-designed).

TS shows those suggestions because for empty object, the type has not been determined yet so you can use any of those property names. Once you add a method for `CustomEditorProvider` or  `CustomTextEditorProvider`, then it locks the type to either `CustomEditorProvider` or  `CustomTextEditorProvider` and should only suggest methods from that type
