### ISSUE TITLE
Single quotes not escaped in debug commands

### ISSUE THREAD

**Issue by gasteigerjo** [microsoft/vscode#91578]
- VSCode Version: 1.42.1
- OS Version: Ubuntu 19.10

There is no way to use a raw double quote in `launch.json` (since it's json), but escaping it with `\"` keeps the escape character `\` in the executed command. Hence there is no way of just using a double quote in a debugging argument. The same is true for escaping any other character in JSON (e.g. it's not possible to get a single backslash, since `\\` produces a double backslash).

Steps to Reproduce:

1. Start a debugging session with
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "test",
            "type": "node",
            "request": "launch",
            "runtimeExecutable": "echo",
            "console": "integratedTerminal",
            "args" : ["ab\\c\"def\""]
        },
    ]
}
```
2. The executed command is `cd /path/to/dir ; /bin/echo --inspect-brk=28605 ab\\c\"def\"`. Expected would be `cd /path/to/dir ; /bin/echo --inspect-brk=28605 ab\c"def"`.

**Comment by roblourens** [comment]
I think we are escaping it for the shell - This looks correct to me because an item in the 'args' array needs to be a single arg. Can you explain more about what you are trying to do?

![image](https://user-images.githubusercontent.com/323878/75367660-85f40080-5875-11ea-9786-73defe9fde90.png)

**Comment by klicperajo** [comment]
I see. So my current solution approach was a bit misguided.

So after more testing I found that my issue is actually something different: The single quote `'` does not get escaped in the shell, as opposed to double quotes `"` etc.

**Comment by roblourens** [comment]
I think that seems wrong? 

![image](https://user-images.githubusercontent.com/323878/75473992-00428480-594b-11ea-97e0-6811e20e0940.png)

**Comment by roblourens** [comment]
Possibly here https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/debug/node/terminals.ts#L167

**Comment by thomas6g** [comment]
> I see. So my current solution approach was a bit misguided.
> 
> So after more testing I found that my issue is actually something different: The single quote `'` does not get escaped in the shell, as opposed to double quotes `"` etc.

I think your initial description is still correct. There seems to be a problem with escaping. I'm currently try to test the wildcard implementation of a Pyhton tool I wrote. Therefore I need to escape the * for the shell, but that doesn't work.

`"args": ["mine", "${workspaceFolder}/data/\\*.xml"]`

ist translated into:    `mine /Users/tom/Documents/evaluate/data/\\*.xml`

I actually expect:  `mine /Users/tom/Documents/evaluate/data/\*.xml`

**Comment by weinand** [comment]
With VS Code 1.48.2 and this launch config:
```
		{
			"type": "node",
			"request": "launch",
			"name": "simple",
			"program": "${workspaceFolder}/simple.js",
			"args": [
				"-foo",
				"-bar",
				"${workspaceFolder}/data/\\*.xml"
			],
		},
``` 
and this node.js program:
```js
for (var i= 0; i < process.argv.length; i++) {
	console.log(process.argv[i]);
}
``` 
I see this on the debug console:

<img width="1024" alt="2020-08-31_09-26-19" src="https://user-images.githubusercontent.com/1898161/91693948-1a645600-eb6c-11ea-848a-b8fb1155dfc1.png">

**Comment by thomas6g** [comment]
It depends if you're using Windows cmd or zsh.
My config:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: evaluate",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/exec_evaluate.py",
            "console": "integratedTerminal",
            "args": ["mine", "${workspaceFolder}/data/\\*.xml"]
        }
    ]
}
```

Windows cmd:
`PS C:\Users\tom\Projekte\evaluate>  & 'C:\Users\tom\AppData\Local\pypoetry\Cache\virtualenvs\evaluate-gzJA505A-py3.8\Scripts\python.exe' 'c:\Users\tom\.vscode\extensions\ms-python.python-2020.8.105045\pythonFiles\lib\python\debugpy\launcher' '64738' '--' 'C:\Users\tom\Projekte\evaluate/exec_evaluate.py' 'mine' 'C:\Users\tom\Projekte\evaluate/data/\*.xml'`

zsh:
`tom@Thrud evaluate %  env /Users/tom/Library/Caches/pypoetry/virtualenvs/evaluate-i9NAUR7e-py3.8/bin/python /Users/tom/.vscode/extensions/ms-python.python-2020.8.105045/pythonFiles/lib/python/debugpy/launcher 49969 -- /Users/tom/Documents/evaluate/exec_evaluate.py mine /Users/tom/Documents/evaluate/data/\\*.xml `

Because of the double escape the zsh doesn't find any files and fails before calling my script:
`zsh: no matches found: /Users/tom/Documents/evaluate/data/\*.xml`

I need a single escape to protect the * for the shell in order to test the globbing implementation of my script.

Background: My script shall run on Windows and Linux. On Windows cmd the script needs to implement the globbing.

**Comment by weinand** [comment]
@thomas6g as a workaround you could remove/comment out the `"console": "integratedTerminal"` in order to use the debug console.
With that you do not even have to escape the "*" in "args".

**Comment by thomas6g** [comment]
Thank you for the hint. 

Because `"integratedTerminal"` is the default for Python I needed to set either `"internalConsole"` or `"externalTerminal"`, both works.

Finally I'm looking forward how it will be solved. On the one hand it seems handy to have some auto quoting of the whole argument like it is done by "externalTerminal", but on the other it limits my possibilities. 

Actually, I think, I would prefer more direct control what is quoted and escaped.

**Comment by thecriticalpoint** [comment]
I really want to apologize if my comment doesn't belong here but I feel like I'm having a similar problem creating a task with arguments that run in WSL. [I created a thread here on stackoverflow](https://stackoverflow.com/questions/66978610/tasks-json-i-cant-figure-out-how-to-use-escaping-characters-using-wsl-as-a-sh) but wanted to cross post it here just in case it can end up helping someone else. This thread is was the most current one I could find that I was still allowed to comment on.

**Comment by weinand** [comment]
The July release has a [new feature](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_70.md#javascript-debugging) that helps debug extension authors to solve the problem.
