### ISSUE TITLE
Add support for symlinks in remoteRoot of launch configuration for remote debugging

### ISSUE THREAD

**Issue by Wenzil** [Microsoft/vscode#9158]
- VSCode Version: 1.3.1
- OS Version: OS X

Currently, breakpoints are not triggered when using a file path containing symlinks as the remoteRoot of an `attach` launch configuration.

For instance, if `current` in `/opt/myproject/current/app` is a symlink pointing to the directory of the last deployed build, the debugger will successfully attach to the process, but breakpoints will not trigger:

``` json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to remote process",
      "type": "node",
      "request": "attach",
      "address": "my-remote-host.com",
      "port": 5858,
      "remoteRoot": "/opt/myproject/current/app",
      "localRoot": "${workspaceRoot}"
    }
  ]
}
```
#8955

**Comment by weinand** [comment]
VS Code cannot understand that the remote system uses a symbolic link. VS Code can only talk to the remote node; it does not have access to the file system.

**Comment by Wenzil** [comment]
Could there be another way to map the debugged source to the local source that would not require knowing about symlinks? I know that with Webstorm there's no need to specify the remoteRoot.

**Comment by Wenzil** [comment]
The "Remote Debugging Node.js" section in https://code.visualstudio.com/docs/editor/debugging says I should see the debugged source in read-only mode if there's something wrong with the mapping with the local source. It's not the case on my end.

Thoughts?

**Comment by weinand** [comment]
The doc is correct but probably a "Please note" section is missing:

In your case the mapping between 'local' and 'remote' seems to work (otherwise you would not get editable source), and when registering breakpoints with a path that contains a symbolic link segment, node.js does not complain (because the path leads indeed to a valid JavaScript file).

The problem is that node does not hit the breakpoints because the node runtime (actually the loader) sees the JavaScript files in a different location than where the breakpoints were registered.
(you could probably verify this by adding `"trace": "all"` or `"trace": "bp"` to your attach launch config and then watch the paths showing up in the debug console).

How do you start node on the remote host? As the entry point do you pass a path with or without the symbolic link?

**Comment by Wenzil** [comment]
The node process is started in this way:
`cd /opt/myproject/current/app`
`NODE_ENV=development /opt/myproject/current/nodejs/current/bin/node --debug lib/server.js`
where "/opt/myproject/current" is a symlink pointing to the folder of the last deployed build and "/opt/myproject/current/nodejs/current" is a symlink pointing to the folder of the latest installed nodejs runtime

**Comment by weinand** [comment]
Starting with node.js 6.3 it is possible to pass a `"--preserve-symlinks"` as a runtime argument to node.js. This fixes the issue.
See #23753.
