### ISSUE TITLE
Accessibility: Can not jump out of nested editors in Interactive Playground

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#91604]
Re #91063

- OS: Ubuntu 18.04

Bug:

* Turn on Accessibility Mode
* Open Interactive Playground
* Press Tab to jump between links until it focuses into a Monaco Editor
* Can not jump out of the the editor anymore

**Comment by jvesouza** [comment]
I may be writing a lot of nonsense, but I imagine you must have used the tab key to jump out of the editor. The key is probably interpreted as something to be inserted in the editing area. If this is the case, I think it would be necessary to press the  ctrl + m before pressing the tab key.
I'm sorry if I'm wrong.

**Comment by isidorn** [comment]
@jvesouza you are not writing nonsense, what you are saying is pefectly valid.
@rebornix this is expected behavior that our accessiblity users are aware off, you have to manually press ctrl +M, or (ctrl+ shift + M on mac) to switch to mode that tab moves focus.
Closing as designed for now. The alternative that this mode is the default in the playground editors does not make a lot of sense to me

**Comment by rebornix** [comment]
Thanks to both of you, now I know a bit better about how to navigate in accessibility mode.
