### ISSUE TITLE
Comments panel default message

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#91623]
I was confused about where this panel came from and what would go in here. If I don't have the GHPR extension installed or a PR checked out, users might be confused by the message of this. Can we edit the message to reflect that certain extensions will contribute to this panel?

![image](https://user-images.githubusercontent.com/9721254/75395481-61188100-58a7-11ea-9f1f-0e06219974b4.png)

**Comment by RMacfarlane** [comment]
The comments panel should only show up when there is an extension that registers a "CommentController" that could be used to add comments. Any chance you remember if you had something like LiveShare installed at this time?

I'll update the text to match the Problems panel, so that it says there are no comments in the workspace, rather than referencing a "review"

**Comment by sana-ajani** [comment]
Yeah, I think I did have Liveshare installed.
