### ISSUE TITLE
'ENOENT: no such file or directory, mkdir' while installing extension 

### ISSUE THREAD

**Issue by lakxraju** [microsoft/vscode#91671]
Got this error while installing extension: 'ENOENT: no such file or directory, mkdir' 

- VSCode Version: 1.42.1
- OS Version: Windows 10 Enterprise (10.0.17134)

Steps to Reproduce:

1. Install extension

Does this issue occur when all extensions are disabled?: Not sure

This issue got resolved by reinstalling VSCode and removing .vscode folder where extensions are installed. 
![9b3a1f2a-215c-4eec-9897-6e5d6405e604(1)](https://user-images.githubusercontent.com/4449275/75434515-f53f2280-5951-11ea-8543-d38afab8323f.PNG)

**Comment by sandy081** [comment]
I guess this is because VS Code would not have permissions to create or remove folders in the extensions folder. When you deleted that folder and reinstalled VS Code permissions would have got reset. 

If you can repro it

Please provide logs from following locations 

    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by wska** [comment]
Hi!

While I am not the OP, I do have a similar issue and it throws the same error message in the logs. I think you are absolutely right in that it has something to do with user permissions since I seem to be able to download extensions when launching vscode as a superuser(though they seem to have issues working after I exit superuser mode). 

I have attached my own log files for the locations you mentioned, but the shared-process had no log output when attempting to install an extensions, so I excluded that. 

The developer logs also show my red hat server extensions crashing repeatedly but that may stem from the same cause. 
[developerConsoleLogs.log](https://github.com/microsoft/vscode/files/4286567/developerConsoleLogs.log)
[sharedView.log](https://github.com/microsoft/vscode/files/4286568/sharedView.log)
[windowView.log](https://github.com/microsoft/vscode/files/4286569/windowView.log)

**Comment by sandy081** [comment]
> I think you are absolutely right in that it has something to do with user permissions since I seem to be able to download extensions when launching vscode as a superuser(though they seem to have issues working after I exit superuser mode).

Yes it is expected as extensions folder is created by the root user and hence you do not have permissions as normal user.
