### ISSUE TITLE
[scss] Auto complete bug when editing a SASS file

### ISSUE THREAD

**Issue by saharso** [Microsoft/vscode#9168]
- VSCode Version: 1.3.1
- OS Version:

After the latest update, after writing a semicolon, an auto complete window pops up for no reason, and because I hit enter as usual after typing a semicolon, that window's first option is selected, which in my case is this hex color code: #16baba, which I am foreced to manually delete every time.

This happens usually after writing a value with only zero in it, such as "left: 0;".

![bug](https://cloud.githubusercontent.com/assets/19216444/16792457/5a14c38a-48d1-11e6-93ad-fc3cf21d211a.jpg)

**Comment by wUFr** [comment]
same bug appears in Less.

Looks like it does only when format is: "parameter: [number]" no matter number lenght even 

``color:000000000000;``

and when you hit after ";" it will end up in

``color:000000000000;#178fcf`` (first color in autocomplete window)

*i know its not valid value, just for test*

**Comment by wUFr** [comment]
does not appear when editing CSS file tho

**Comment by aeschli** [comment]
#178fcf are word based proposals that show up automatically because the the proposals to enter a value ('0', or '000') are marked incomplete (CSS offers proposals that combine the number with the current value).
For now all you can do is to turn off all textual proposals in the settings: "editor.wordBasedSuggestions": false.
@jrieken FYI.

**Comment by aeschli** [comment]
This got fixed in the meantime
