### ISSUE TITLE
TimelineOptions is confusing/difficult to work with

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#91722]
currently: 
```ts
  export interface TimelineOptions {
		/**
		 * A provider-defined cursor specifing the range of timeline items that should be returned.
		 */
    cursor?: string;

		/**
		 * A flag to specify whether the timeline items being requested should be before or after (default) the provided cursor.
		 */
    before?: boolean;

		/**
		 * The maximum number or the ending cursor of timeline items that should be returned.
		 */
    limit?: number | string;
  }
```

It's hard to tell if, for instance, a cursor will always be defined if `before` is defined? And when is limit a number vs a string?

Quick sketch of something that might be easier to work with:

```ts
export type TimelineOptions = 
  | { type: "initialize", limit: number}
  | {type: "addPage", cursor: string, before: boolean, limit: number  /* or  string | number, not sure how this works */   }
```

**Comment by JacksonKearl** [comment]
In use, it seems like the only two types it uses are `{limit: number}` when starting up and `cursor: string, limit: number` when paging. When user actions would cause `limit` to be a string or `before` to be defined? Also is there ever a time when `limit` wont be defined?

**Comment by eamodio** [comment]
Right now I think these are main cases (if we forget about `before` altogether, since I'm thinking of removing it):

- `{ limit: number }` — to get the first page (most recent)
- `{ limit: string }` — to get the most recent items, up to a point (cursor) -- we use this for providers with mutable histories (think git -- reset, rebase, etc), so when they tell us to update the timeline we can ask for all our current visible data. If I remove `before` then we would also use this to ask a provider for newer information
- `{ cursor: string, limit: number }` — to get the next page of data starting at a specific point (cursor)
- `{ }` — to get all items in one shot (no paging)
- `{ cursor: string }` — to get all items in one shot starting from a specific point (we don't have to use this, since we can just use the above to get everything again).

**Comment by JacksonKearl** [comment]
Those cases make sense to me. I do think providing a `requestType` field would be nice for ergonomics, manually type checking everything to decide code paths is a bit cumbersome.

**Comment by eamodio** [comment]
I agree with `before` in the mix it gets much more confusing, but I'm not yet convinced it is without it. Basically you look at `cursor` to see if you are starting at a specific point or not, and then you look at limit to see if you should be getting only X items, all items, or all items up to a specific point. IMO, trying to distill that down to discreet request will limit flexibility and not sure it really provides clarity.

**Comment by eamodio** [comment]
Maybe for a bit more clarity -- I should change limit to be:
`limit?: number | { cursor: string }` rather than just `number | string` to make it much clearer what it can be

**Comment by eamodio** [comment]
`TimelineOptions` is now much simpler:

```ts
export interface TimelineOptions {
	/**
	 * A provider-defined cursor specifying the starting point of the timeline items that should be returned.
	 */
	cursor?: string;

	/**
	 * An optional maximum number timeline items or the all timeline items newer (inclusive) than the timestamp or id that should be returned.
	 * If `undefined` all timeline items should be returned.
	 */
	limit?: number | { timestamp: number; id?: string };
}
```

So here are the combinations:
- { limit: number } — to get the first page (most recent)
- { limit: { timestamp: number; id?: string } — to get the most recent items, up to a set timeline item (or timestamp) -- we use this for providers with mutable histories (think git -- reset, rebase, etc), so when they tell us to update the timeline we can ask for all our current visible data
- { cursor: string, limit: number } — to get the next page of data starting at a specific point (cursor)
- { } — to get all items in one shot (no paging)
- { cursor: string } — to get all items in one shot starting from a specific point (we don't have to use this, since we can just use the above to get everything again).

As part of this I've also simplified the `paging` property of the `Timeline` as well:

```ts
export interface Timeline {
	readonly paging?: {
		/**
		 * A provider-defined cursor specifying the starting point of timeline items which are after the ones returned.
		 * Use `undefined` to signal that there are no more items to be returned.
		 */
		readonly cursor: string | undefined;
	}

	/**
	 * An array of [timeline items](#TimelineItem).
	 */
	readonly items: readonly TimelineItem[];
}
```

Now you only return `paging` if the results are paged, and you must either return a cursor to get the next set of items or `undefined` if there are no more items.
