### ISSUE TITLE
Breakpoint on first line of Nodejs code is not hit upon Debug Launch

### ISSUE THREAD

**Issue by paritosh149** [Microsoft/vscode#9174]
- VSCode Version: 1.3
- OS Version: Windows 7 SP1

Steps to Reproduce:

1. Go to https://code.visualstudio.com/docs/runtimes/nodejs
2. Follow the instructions
3. Place a breakpoint on line 1.
4. Launch Debugger
5. The program should pause execution due to breakpoint on line 1, but the breakpoint is not hit and code executes without pausing.

**Comment by weinand** [comment]
Seems to be an issue with node 6.x on Windows.
Does not occur with node 5.x and does not occur on OS X.

**Comment by weinand** [comment]
In node 6.x drive letter case in break events has changed from lower to uppercase.

**Comment by paritosh149** [comment]
Thanks. Indeed this was working as expected with node 5.x. I should have added this info along with the issue details. What's confusing me about your reason as to why this errant behavior, is why this change in node 6.x has its effect while debugging and breakpoint on first line only?

**Comment by weinand** [comment]
@paritosh149 it is not the first line but the 'entry point' (which happens to be the first line in your sample. VS Code node-debug needs some special logic here because it is always launching the debug target with '--debug-brk' which would stop it on entry. And the special logic hides this behaviour for the user. The only exception is when there is an explicit breakpoint at the entry point.
And this is the case you are hitting.

**Comment by paritosh149** [comment]
Thanks. You explained the reason very well.
