### ISSUE TITLE
cant find c/c++ extension on visual studio marketplace

### ISSUE THREAD

**Issue by shaikhs234** [microsoft/vscode#91748]
when i start the marketplace on the visual studio application, i cannot find the extension. when i searched for it through my browser, i got it but im not able to install it from the marketplace. how do i fix this?

**Comment by shaikhs234** [comment]
i downloaded the .vsix file and now it says "one or more extensions are for visual studio code. try installing them in visual studio code". theres no solution for this online, what do i do?????

**Comment by IllusionMH** [comment]
Looks like you are using Visual Studio 2019/2017/2015 etc. is it correct?

Most likely you need to search in https://marketplace.visualstudio.com/vs (however it has built-in [support for C++](https://visualstudio.microsoft.com/vs/features/cplusplus/))
instead of marketplace for VS Code (different editor that shares part of the name)

**Comment by roblourens** [comment]
Thanks @IllusionMH!
