### ISSUE TITLE
Fix suggest widget hiding `type` field when `label` is too long

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#91785]
From:

https://github.com/microsoft/vscode/issues/90552#issuecomment-586150833

![74374388-27b62080-4d93-11ea-84d1-1e9498c78071](https://user-images.githubusercontent.com/1794099/74513989-0dec1900-4f0c-11ea-84a6-2eb015207189.png)

**Comment by jrieken** [comment]
Looks like this is actually fixed

<img width="540" alt="Screenshot 2020-10-02 at 14 39 08" src="https://user-images.githubusercontent.com/1794099/94924012-0c805880-04bd-11eb-9b41-3aa041a921f1.png">

**Comment by mjbvz** [comment]
@jrieken Using @octref's example from https://github.com/microsoft/vscode/issues/90552, I believe I still see the bug:

<img width="1008" alt="Screen Shot 2020-10-28 at 2 18 22 PM" src="https://user-images.githubusercontent.com/12821956/97497919-8541cb80-1928-11eb-9699-8084465d24e4.png">

Not entirely sure about the expected behavior but reopening for you to take a look

**Comment by jrieken** [comment]
Fiddled around and gave it some thought. I think the current behaviour is actually good because things hide in order of reading (left to right). Adding min-widths for the type label isn't really helpful and always a dance for how long wide should the min-width be.
