### ISSUE TITLE
Memory leak of diff preview editor

### ISSUE THREAD

**Issue by Veetaha** [microsoft/vscode#91782]
- VSCode Version: checked on both `1.42.0` and `1.42.1-1581432938`
- OS Version: `Ubuntu 18.04.3 LTS`

Steps to Reproduce:

1. Open the [repository with the reproducation](https://github.com/Veetaha/report-vscode-memory-leak-of-diff-preview-editor)
2. Follow the steps in `README.md` of that repo to behold the bug.

You should see the following proof:
<details>
<summary> Demo gif image </summary>

![](https://user-images.githubusercontent.com/36276403/75583141-bacea600-5a75-11ea-9bb3-514a38596d82.gif)

</details>

Also, notice that text documents have no public identity (i.e. text editors don't have a unique identifier), so that I can't easily take apart different editors in the extension code. Anyway, this is yet another complaint, that  deserves a separate issue, or am I wrong, might I ask you to elaborate on this, guys? Pretty please!

Does this issue occur when all extensions are disabled?: **Yes**

References

* Original use case issue that revealed the bug: https://github.com/rust-analyzer/rust-analyzer/issues/3008

**Comment by Veetaha** [comment]
Also, take a not on that weird `main.rs.git` non-existent file that is added to active editors each time you open the diff preview.
Also, notice that each time you open the diff preview you get `onDidChangeVisibleTextEditors` triggered two times: first with `main.rs.git` file added, then with `main.rs` file.

**Comment by rebornix** [comment]
> Also, take a not on that weird main.rs.git non-existent file that is added to active editors each time you open the diff preview.
Also, notice that each time you open the diff preview you get onDidChangeVisibleTextEditors triggered two times: first with main.rs.git file added, then with main.rs file.


Reading this again and I found it's not a bug but how we implement the diff editor. The diff editor consists of two normal editors, the left side one for the original content (before the change) and the right side one is the current file. That's why you will see two visible editors open event as technically they are two files.
