### ISSUE TITLE
change duplicate line shortcut 

### ISSUE THREAD

**Issue by AbdKayali3** [microsoft/vscode#91789]
change duplicate line shortcut to  **CTRL + SHIFT + Up/Down** instead of **ALT + SHIFT + Up/ Down**
because the  **ALT + SHIFT** shortcut is for change between languages if you have more than one.
and that will effect the productivity of the programmer and bothers him.

**Comment by gjsjohnmurray** [comment]
I think it's unlikely that the default settings will be changed.

Assuming you're on Windows, one solution is described here:

https://superuser.com/questions/698037/can-i-disable-the-altshift-shortcut-to-change-language-in-windows-8-1-or-win

Alternatively, change your own VSCode settings.

**Comment by AbdKayali3** [comment]
I know that's hard to do 
so i suggest to make both shortcuts works so that people with multi languages can work comfortable 
and then after many updates you can remove the old shortcut safely or leave both works 

 i checked right now that  **CTRL + SHIFT + Up/Down** don't do any thing so you won't break any other feature

**Comment by IllusionMH** [comment]
Looks like this is first request to change this shortcut because of this specific reason (request for <kbd>Ctrl</kbd>+<kbd>D</kbd> is just because other used to it) ([Request](https://github.com/microsoft/vscode/issues?page=5&q=is%3Aissue+%22duplicate+line%22&utf8=%E2%9C%93)). 

You can easily reassign keybindings for these commands through UI (Right click and Change Keybinding) or copy next config to your `keybindings.json`
```json
{
    "key": "ctrl+shift+up",
    "command": "editor.action.copyLinesUpAction",
    "when": "editorTextFocus && !editorReadonly"
},
{
    "key": "shift+alt+up",
    "command": "-editor.action.copyLinesUpAction",
    "when": "editorTextFocus && !editorReadonly"
},
{
    "key": "ctrl+shift+down",
    "command": "editor.action.copyLinesDownAction",
    "when": "editorTextFocus && !editorReadonly"
},
{
    "key": "shift+alt+down",
    "command": "-editor.action.copyLinesDownAction",
    "when": "editorTextFocus && !editorReadonly"
}
```

P.S. Proposed change will break workflow for others: <kbd>Ctrl</kbd>+<kbd>Shift</kbd> to change language and muscle memory for <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>↑</kbd>/<kbd>↓</kbd>

**Comment by AbdKayali3** [comment]
thanks for **reassign keybindings method**
change the shortcut to anything else will be good,
 but change it to something familiar like **CTRL + D** (in Brackets) or like **CTRL + SHIFT + Up/Down** (in sublime) will be better

**Comment by IllusionMH** [comment]
<kbd>Ctrl</kbd>+<kbd>D</kbd> is popular request, however it's already used for creating multiple-selections. So this will be a big snow ball of breaking changes to avoid overlaps (and then a lot of issues with a lot of ! in title).

Just in case - VS Code supports keymaps that help to bring most of keyboard shortcuts for other popular editors https://marketplace.visualstudio.com/search?target=VSCode&category=Keymaps&sortBy=Installs

**Comment by alexdima** [comment]
We will not change the default keybinding for this action. In fact, it is highly unlikely that we will change any default keybindings... The reason is simply that the disturbance and frustration caused to those who are used to the current default would not be worth it.

That being said, it is trivial for you to change the keybinding on your machine or you can use one of the keymap extensions.
