### ISSUE TITLE
Editor should not handle all draggable objects

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#9179]
![gif](http://g.recordit.co/wftqIpi4fN.gif)

**Comment by joaomoreno** [comment]
I can still repro this.

**Comment by bpasero** [comment]
@joaomoreno show me

**Comment by bpasero** [comment]
@joaomoreno I see what is happening and I think you changed something that now causes this again. my check simply looks if the dragged URI has the `file://` scheme and previously you used `http://` scheme.

Now I see you put a `href="#"` which seems to get converted to a full `file://` URI (I guess appended with the base URI of the application).

Can you try to not set the href to see if that makes it any better?

I cannot prevent the dropping of file URIs after all because to me that looks like a file to drop.

**Comment by jrieken** [comment]
![Uploading Sep-01-2016 15-58-47.gif…]()

**Comment by bpasero** [comment]
Haha, can we not sell this as feature ;)?

![editors](https://cloud.githubusercontent.com/assets/900690/18170679/74a28f74-705f-11e6-91e5-7da61e1c0391.gif)

**Comment by joaomoreno** [comment]
Maybe `draggable=false`.
