### ISSUE TITLE
[Arch Linux]: Flutter extension hangs forever during Install

### ISSUE THREAD

**Issue by jchand99** [microsoft/vscode#91825]
- VSCode Version: 1.42.1
- OS Version: Linux x64 5.5.1-arch1-1 (Arch Linux)

Steps to Reproduce:

1. Install vscode 'visual-studio-code-bin' package from AUR
2. Try to install Flutter extension and watch it hang on install.

Does this issue occur when all extensions are disabled?: Yes/No

This can be done with no installed extensions so not sure how much --disable-extensions would change things (don't think it would matter, if it does I can test it with --disable-extensions).

Flutter extension is also supposed to install the Dart extension with it, but after closing and re-opening vscode the Flutter extension is installed by itself without Dart.

I am unable to see the console with Developer Tools because of this bug:
https://github.com/microsoft/vscode/issues/91824

Post relating to flutter/dart on Dart extension repo:
https://github.com/Dart-Code/Dart-Code/issues/2279

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by jchand99** [comment]
Due to bug https://github.com/microsoft/vscode/issues/91824 I cannot check what the error is inside the Developer Tools. Although it does seem to install (after substantially longer time than on windows machine) in VSCode Insiders.

**Comment by sandy081** [comment]
But I think you can access logs from our Output views. Can you please provide them?
