### ISSUE TITLE
Wrong setting name editor.fontLigatures for actual font features

### ISSUE THREAD

**Issue by baco** [microsoft/vscode#91870]
User's setting `editor.fontLigatures` has misleading name.  It insinuates that only font ligatures can be turned on with that setting; but instead all OpenType features of a font can be turned on/off from that setting. A more proper name for the setting would be `editor.fontFeatures`.

- VSCode Version: 1.42
- OS Version: Debian (sid/unstable)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
I agree, but we initially only had `fontLigatures` to be on or off. We would then, behind the scene, generate the `font-features` CSS to turn `liga` and `calt` on.

After 2 years, we have opened up the `font-features` to the point where users can now simply write the `font-features` CSS string by themselves, e.g. `liga 'on', calt 'on'`. 

Introducing a new setting would have been confusing in the presence of both settings, e.g. `fontLigatures: true and fontFeatures: 'liga' off`. What should happen in this case, since the settings are literally conflicting with one another? There is also the fact that the vast majority of people are not familiar with the `font-features` string format or the options available to them from their font, they just want to turn on ligatures...

All in all, a compromise was reached, and that is to support the simple case via `true/false` and the advanced users where they can write the `font-features` string by themselves. I will push a commit to improve the description of `fontLigatures`.

**Comment by dbaeumer** [comment]
@alexdima verified that the string has improved in the settings UI. However in thge JSON editor it still only talks about enable / disable

![capture](https://user-images.githubusercontent.com/1931590/78247793-c89b9f00-74eb-11ea-82d5-f462a06da3dc.png)

**Comment by dbaeumer** [comment]
Leave it up to you to decide what to do :-)

**Comment by alexdima** [comment]
:+1: I will leave like it is. When you use a boolean value, it has a different hover description than when using a string value:

I think that's OK given font features is an advanced feature that is font dependent and highly unlikely that someone can just "type in" without reading a doc explaining it.

![image](https://user-images.githubusercontent.com/5047891/78252682-82e2d480-74f3-11ea-9e70-23be60a3a404.png)

**Comment by dbaeumer** [comment]
@alexdima cool, I didn't know that.
