### ISSUE TITLE
Not able to launch Code Editor

### ISSUE THREAD

**Issue by PRDinesh** [Microsoft/vscode#9191]
- VSCode Version: **1.3.1**
- OS Version: **Ubuntu 14.04.4 LTS**

Steps to Reproduce:
I am not able to launch the visual code editor neither from the gui nor from the command line

Logs below :
demosite$ code --version
1.3.1

demosite$ code . --verbose
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[SyntaxError: Unexpected end of input](2:06:12 AM) ### VSCode main.js ###
(2:06:12 AM) /usr/share/code/resources/app { pathArguments: [ '/ws/demosite' ],
  programStart: 0,
  enablePerformance: false,
  verboseLogging: true,
  debugExtensionHostPort: undefined,
  debugBrkExtensionHost: false,
  logExtensionHostCommunication: false,
  debugBrkFileWatcherPort: undefined,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  diffMode: false,
  extensionsHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  disableExtensions: false,
  locale: undefined,
  waitForWindowClose: false }

demosite$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

demosite$ cat /etc/issue
Ubuntu 14.04.4 LTS \n \l

**Comment by Tyriar** [comment]
Did you experience this issue on any earlier versions?

**Comment by PRDinesh** [comment]
I experienced the same issue with one before version too. 1.3.0

**Comment by Tyriar** [comment]
Did you have 1.2.0 installed fine or was 1.3.0 your first?

**Comment by nostradamnit** [comment]
I have the same issue on Debian 8. It didn't work with the previous version either, though I don't remember which version it was...

debian:~$ code --version
1.3.1
debian:~$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by PRDinesh** [comment]
No I have never tried with 1.2.0

**Comment by PRDinesh** [comment]
Attaching the verbose info, Please let me know if any other information required

code --verbose
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[SyntaxError: Unexpected end of input]
(9:59:30 PM) ### VSCode main.js ###
(9:59:30 PM) /usr/share/code/resources/app { pathArguments: [],
  programStart: 0,
  enablePerformance: false,
  verboseLogging: true,
  debugExtensionHostPort: undefined,
  debugBrkExtensionHost: false,
  logExtensionHostCommunication: false,
  debugBrkFileWatcherPort: undefined,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  diffMode: false,
  extensionsHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  disableExtensions: false,
  locale: undefined,
  waitForWindowClose: false }

**Comment by Tyriar** [comment]
@joaomoreno @bpasero have you seen this before?

**Comment by bpasero** [comment]
`SyntaxError: Unexpected end of input ### VSCode main.js ###`
Corrupt install?

**Comment by joaomoreno** [comment]
Yeah that is suspicious.

**Comment by Tyriar** [comment]
In that case I'd recommend uninstalling fully and reinstalling. To get a clean slate:

```
sudo apt-get remove code
rm -rf ~/.config/Code ~/.vscode # remove extensions, cache and config
```

**Comment by PRDinesh** [comment]
I didnt install vscode via apt-get, I installed by downloading the install. 
I will try your steps and update here.

**Comment by PRDinesh** [comment]
Downloaded the latest from the following link

> wget https://go.microsoft.com/fwlink/?LinkID=760868

Installed using the following command

> sudo dpkg -i vscodee
> Selecting previously unselected package code.
> (Reading database ... 410319 files and directories currently installed.)
> Preparing to unpack vscodee ...
> Unpacking code (1.4.0-1470329130) ...
> Setting up code (1.4.0-1470329130) ...
> Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
> Rebuilding /usr/share/applications/bamf-2.index...
> Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
> Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
> Processing triggers for mime-support (3.54ubuntu1.1) ...
> 
> 

Again got the same error, 
Is there any issue in my download link?

r:~$ code .
r:~$ code --version
1.4.0
r:~$ code --verbose
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
[SyntaxError: Unexpected end of input]
(1:59:53 AM) ### VSCode main.js ###
(1:59:53 AM) /usr/share/code/resources/app { pathArguments: [],
  programStart: 0,
  enablePerformance: false,
  verboseLogging: true,
  debugExtensionHostPort: undefined,
  debugBrkExtensionHost: false,
  logExtensionHostCommunication: false,
  debugBrkFileWatcherPort: undefined,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  diffMode: false,
  extensionsHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  disableExtensions: false,
  locale: undefined,
  waitForWindowClose: false }

**Comment by manimuthu-m-a** [comment]
I am also facing similar issue

After installing, when i ran code, no response was found, later i tried code --verbose I got the following output

`code --verbose
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
{ [Error: ENOENT: no such file or directory, open '/users/mamani/.config/Code/storage.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/users/mamani/.config/Code/storage.json' }
(2:32:10 AM) ### VSCode main.js ###
(2:32:10 AM) /usr/share/code/resources/app { pathArguments: [],
  programStart: 0,
  enablePerformance: false,
  verboseLogging: true,
  debugExtensionHostPort: undefined,
  debugBrkExtensionHost: false,
  logExtensionHostCommunication: false,
  debugBrkFileWatcherPort: undefined,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  diffMode: false,
  extensionsHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  disableExtensions: false,
  locale: undefined,
  waitForWindowClose: false }
`

Since it complained about a missing file "storage.json", I just touched the required file
`touch /users/mamani/.config/Code/storage.json`

Later when i ran, I got the error as mentioned in this issue

`code --verbose
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
{ [Error: ENOENT: no such file or directory, open '/users/mamani/.config/Code/storage.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/users/mamani/.config/Code/storage.json' }
(2:32:54 AM) ### VSCode main.js ###
(2:32:54 AM) /usr/share/code/resources/app { pathArguments: [],
  programStart: 0,
  enablePerformance: false,
  verboseLogging: true,
  debugExtensionHostPort: undefined,
  debugBrkExtensionHost: false,
  logExtensionHostCommunication: false,
  debugBrkFileWatcherPort: undefined,
  openNewWindow: false,
  openInSameWindow: false,
  gotoLineMode: false,
  diffMode: false,
  extensionsHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  disableExtensions: false,
  locale: undefined,
  waitForWindowClose: false }
`
`code --version
1.4.0
`
`cat /etc/os-release 
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"`

**Comment by Tyriar** [comment]
@manimuthu-m-a that's a separate issue, trying removing storage.json and/or making sure your user has permissions to create a file in that directory. If that doesn't work create a new issue.

**Comment by PRDinesh** [comment]
@Tyriar where you able to reproduce this issue?  Please let me know if you need any data to be collected from my end.  

Thank you

**Comment by Tyriar** [comment]
@PRDinesh I'm pretty stumped on this, I've been using vscode on Ubuntu across several computers since it was released and haven't seen this error.

**Comment by PRDinesh** [comment]
can i attach it to gdb and try to get some callstack and share you? will that be of any help?

**Comment by andrewv99** [comment]
I have the same issue on Kubuntu 14.04.

**Comment by PRDinesh** [comment]
Please let us know if we can provide any more info to add your debugging

**Comment by Tyriar** [comment]
@alexandrudima any ideas around the loader or something? This is the only real clue we have so far:

```
SyntaxError: Unexpected end of input ### VSCode main.js ###
```

**Comment by andrewv99** [comment]
If I run it like this:
$ strace VSCode-linux-x64/bin/code --verbose 2>&1|tee err.log
err.log attached
[err.zip](https://github.com/Microsoft/vscode/files/476726/err.zip)

Maybe you can spot something there ..

**Comment by Tyriar** [comment]
I see this onein your logs:

```
wait4(-1, { [Error: ENOENT: no such file or directory, open '/home/andrewv/.config/Code/storage.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/andrewv/.config/Code/storage.json' }
```

Have either of you tried deleting your user data directory located at `~/.config/Code`? If you have settings, keybindings, snippets, etc. you can make a backup of `~/.config/Code/User` before deleting it.

**Comment by andrewv99** [comment]
This has been the very first time I have tried using this software. `~/.config/Code/User` was created upon startup of `code,` but it was empty, as was `~/.config/Code`. I deleted both directories and restarted, and empty ones were re-created. I could not find any storage.json under the software package install directory to try and use. How is this file supposed to be initially created ? I couldn't see any command line options to create default any such file (or similar). Just to confirm the version I am running:
./VSCode-linux-x64/bin/code -v
1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b)

**Comment by Tyriar** [comment]
The file is meant to be created initially. Are you running as root by chance?

**Comment by andrewv99** [comment]
No, definitely nothing at all was done as root. I installed (unpacked the tarball) in a directory under my home directory, and am running as myself. Are there any environment variables (or other settings) that might make it behave this way ? Could you possibly attach a sample storage.json here which I could try ... are there any (many?) other files that are supposed to be defaulted ?

**Comment by Tyriar** [comment]
@andrewv99 everything is meant to be created on the first run. You could check you permissions on `~/.config` and `~/.config/Code`?

```
ls -la ~ | grep .config
ls -la ~/.config | grep Code
```

**Comment by andrewv99** [comment]
Nothing is created (as per the strace output), and the permissions are ok:

`$ ls -laR ~/.config/Code
/home/andrewv/.config/Code:
total 12
drwx------  3 andrewv nogroup 4096 Sep 17 09:14 .
drwx------ 34 andrewv nogroup 4096 Sep 17 08:32 ..
drwxr-xr-x  2 andrewv nogroup 4096 Sep 18 08:01 User

/home/andrewv/.config/Code/User:
total 8
drwxr-xr-x 2 andrewv nogroup 4096 Sep 18 08:01 .
drwx------ 3 andrewv nogroup 4096 Sep 17 09:14 ..
$ ls -la ~ | grep .config
drwx------  34 andrewv nogroup       4096 Sep 17 08:32 .config
drwxr-xr-x   2 andrewv nogroup       4096 Jul 29  2014 .fontconfig
-rwxrw-r--   1 andrewv nogroup        117 May 31  2014 .gitconfig
$ ls -la ~/.config | grep Code
drwx------   3 andrewv nogroup  4096 Sep 17 09:14 Code
$
`

**Comment by mdeter** [comment]
I am seeing this same issue since 1.3.  Was hoping 1.5 fixed it, but it has not.

I have tried all of the above tricks to no avail.  Bottom line is code fails to init files correctly for some reason on first run.  Would be nice to get some progress on this, it's been DOA for months now.

$ code -version
1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27)
$ code --verbose
{ [Error: ENOENT: no such file or directory, open '/users/user1/.config/Code/storage.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/users/user1/.config/Code/storage.json' }
(2:13:20 PM) ### VSCode main.js ###
(2:13:20 PM) /usr/share/code/resources/app { _: [],
  paths: [],
  performance: false,
  verbose: true,
  debugPluginHost: undefined,
  debugBrkPluginHost: undefined,
  logExtensionHostCommunication: false,
  'new-window': false,
  'reuse-window': false,
  goto: false,
  diff: false,
  extensionHomePath: undefined,
  extensionDevelopmentPath: undefined,
  extensionTestsPath: undefined,
  'disable-extensions': false,
  locale: undefined,
  wait: false }
$

**Comment by Tyriar** [comment]
@mdeter did you try clearing out your user data dir? `/users/user1/.config/Code` (will delete your settings/keybindings/etc.)

Or just deleting the storage file? `/users/user1/.config/Code/storage.json`

**Comment by mdeter** [comment]
@Tyriar Thanks for your reply.

1) Clearing or rm -rf'ing /users/user1/.config/Code has no effect.  2) storage.json is never created, so there is no opportunity to delete it.  I have checked permissions and even set them wide open (777) on the Code dir but storage.json is never created.  If I manually create storage.json with "touch" then when I run code I get "[SyntaxError: Unexpected end of input]" presumably because it's reading a null stream from the empty file.  Something is interfering with the creation of the storage.json file.  Is there a template file I can copy manually?  Maybe it will work if I get valid content created manually?

Is there any additional tracing or logging (other than --verbose) which might indicate why storage.json isn't created?

**Comment by andrewv99** [comment]
My experience is consistent with what @mdeter described.

**Comment by alexandrudima** [comment]
From searching our codebase for `storage.json`, I would say the `storage.json` error message is simply misleading us down the wrong path here. Check out the code, nothing bad happens if the file is unreadable except the logged message:

https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/storage.ts#L75

![image](https://cloud.githubusercontent.com/assets/5047891/18888275/47942fdc-8500-11e6-89d6-aaea308675a5.png)

I agree with @Tyriar the interesting error message is `SyntaxError: Unexpected end of input ### VSCode main.js ###`

I have proceeded to search our codebase for a `main.js` file and I could only find this one:

https://github.com/Microsoft/vscode/blob/master/src/main.js#L1

Possibly in the zip/installed version this file will be minified.

@mdeter @andrewv99 
Can you please check the file and see if it looks fishy? Maybe you can upload it here -- it is found in `resources/app/out/main.js`.

Sadly, I think it is also possible that this is also misleading and that `VSCode main.js` is simply the name of the window, as `main.js` is the first script we load.

My next attempt at debugging this would be to download electron from atom/electron and see if that runs on your machines in its initial form. Sorry I don't really know what this could be, lots of things can cause `SyntaxError: Unexpected end of input`, but I've personally only seen this error when dealing with invalid JavaScript files. 

I can continue to give some hints if you wanna keep debugging this issue. My next stop after electron would be replacing loader.js with an unminified version and logging to see if it is able to load/read files in NodeScriptLoader. If that doesn't help, I would try compiling and running vscode from source.

**Comment by mdeter** [comment]
Thanks, ended up upgrading Ubuntu to 16.04 and the issue went away.

-Matt

**Comment by winterismute** [comment]
Just FYI, I am still having the error:
[Error: ENOENT: no such file or directory, open '/users/mamani/.config/Code/storage.json']
with the last VSCode version, 1.9.1 (-1486597190).
I am too on Ubuntu 14.04 LTS and can not upgrade the machine :(
Moreover, compiling is not an option for me because the repo version of node (and npm) is very old, something like 1,x, and because of policies it is not easy at all for me to add newer repos.
Not sure if you consider this issue something still relevant but I decided to try anyway :D

**Comment by Tyriar** [comment]
@winterismute did you run code the first time with sudo?

**Comment by winterismute** [comment]
@Tyriar thanks for answering! Well, no, I did not know I had to... But if you are worried about permissions o the folder .config/Code/, I checked the permissions and they seemed fine.

**Comment by winterismute** [comment]
I have tried today downloading again the 64bit tar from the website and to launch it with sudo and --verbose the first time. This is the full error log:


myuser@mypc:~/Downloads/VSCode-linux-x64$ sudo ./code --verbose

(code:10889): IBUS-WARNING **: The owner of /home/myuser/.config/ibus/bus is not root!
Home directory not accessible: Permission denied
{ Error: ENOENT: no such file or directory, open '/home/myuser/.config/Code/storage.json'
    at Error (native)
    at Object.fs.openSync (original-fs.js:640:18)
    at Object.fs.readFileSync (original-fs.js:508:33)
    at e.load (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:8:23208)
    at e.getItem (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:8:22746)
    at e.handleUpdated (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:9:18889)
    at new e (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:9:18790)
    at v (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:5:6439)
    at t._createInstance (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:9:4882)
    at t._createAndCacheServiceInstance (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:9:5857)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/myuser/.config/Code/storage.json' }
[main 12:06:42] Starting VS Code in verbose mode
[main 12:06:42] from: /home/myuser/Downloads/VSCode-linux-x64/resources/app
[main 12:06:42] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'new-window-if-not-first': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
ome/myuser/Downloads/VSCode-linux-x64/code --verbose: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
myuser@mypc:~/Downloads/VSCode-linux-x64$ ./code --verbose
{ Error: ENOENT: no such file or directory, open '/home/myuser/.config/Code/storage.json'
    at Error (native)
    at Object.fs.openSync (original-fs.js:640:18)
    at Object.fs.readFileSync (original-fs.js:508:33)
    at e.load (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:8:23208)
    at e.getItem (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:8:22746)
    at e.handleUpdated (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:9:18889)
    at new e (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:9:18790)
    at v (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:5:6439)
    at t._createInstance (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:9:4882)
    at t._createAndCacheServiceInstance (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/electron-main/main.js:9:5857)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/myuser/.config/Code/storage.json' }
[main 12:07:16] Starting VS Code in verbose mode
[main 12:07:16] from: /home/myuser/Downloads/VSCode-linux-x64/resources/app
[main 12:07:16] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'new-window-if-not-first': false,
  'reuse-window': false,
  r: false,
  performance: false,
  p: false,
  verbose: true,
  logExtensionHostCommunication: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false }
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
ome/myuser/Downloads/VSCode-linux-x64/code --verbose: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
myuser@mypc:~/Downloads/VSCode-linux-x64$ Error: channel closed
    at process.target.send (internal/child_process.js:540:16)
    at /home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcessMain.js:11:1497
    at new n.Class.derive._oncancel (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcessMain.js:6:11063)
    at R (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcessMain.js:11:1410)
    at /home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcessMain.js:11:1599
    at Object.m [as _notify] (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcessMain.js:6:3879)
    at Object.enter (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcessMain.js:6:7457)
    at _run (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcessMain.js:6:9285)
    at _completed (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcessMain.js:6:8726)
    at Server.<anonymous> (/home/myuser/Downloads/VSCode-linux-x64/resources/app/out/vs/code/node/sharedProcessMain.js:7:9846)

**Comment by Tyriar** [comment]
@winterismute there is a known issue where if you run under sudo initially `~/.config/Code` will have the wrong permissions. We generally don't support running via sudo.

Have you tried removing the problem file(s)? `/users/mamani/.config/Code/storage.json` or `/users/mamani/.config/Code`?

**Comment by Tyriar** [comment]
Closing this off, the situation with the OPs problem has likely changed in 10 months.
