### ISSUE TITLE
cursorColumnSelectDown/Up does not expand box selection to the line below/above

### ISSUE THREAD

**Issue by keremispirli** [microsoft/vscode#92015]
- VSCode Version: 1.42.1
- OS Version: Win 10 Ent 1607

Steps to Reproduce:

1. Select 3 characters to right with 3x `Shift+Right`
2a. Try to expand selection to the same three characters in the line below with the `cursorColumnSelectDown` keyboard shortcut (default `Ctrl+Shift+Alt+Down`, un-mapped and re-mapped to `Shift+Alt+Down` in my system)
**OR**
2b. Try to expand selection to the same three characters in the line above with the `cursorColumnSelectUp` keyboard shortcut (default `Ctrl+Shift+Alt+Up`, un-mapped and re-mapped to `Shift+Alt+Up` in my system)
3. Be disappointed with losing your selection and having a new cursor right below/above the starting point instead

![columnselection](https://user-images.githubusercontent.com/661967/75875322-c1fa0900-5e13-11ea-9612-a5a04ce8ce2f.gif)

Does this issue occur when all extensions are disabled?: Yes

**Note:** If you use `Shift+Alt+Left Click` instead, then it correctly selects the block of (2 lines)x(3 characters).

**Comment by alexdima** [comment]
By default, `Shift+Right` is not running in column selection. This can be seen when selecting an passing over a line ending:
![image](https://user-images.githubusercontent.com/5047891/76204022-e846ec80-61f7-11ea-9fb1-2b2702bb3d79.png)

So the column selection commands cannot take as a start the existing selection done via `Shift+Right` because it is not clear if the selection on line 5 or the selection on line 6 should be used as the beginning of column selection. That is the reason why column selection commands do not start from an existing regular selection.

With the upcoming release, VS Code will ship a new mode that can be entered from the `Selection > Column Selection Mode`. Once this mode is activated, even `Shift+Right` creates column selections. You can download the insiders version of VS Code to try it out.

**Comment by keremispirli** [comment]
This issue seems to be fixed in 1.43.0.
