### ISSUE TITLE
Column selection is broken when having reserved keywords

### ISSUE THREAD

**Issue by renanwillian** [microsoft/vscode#92016]
- VSCode Version: 1.41.1
- OS Version: Linux Mint

Steps to Reproduce:

Using mouse drag and pressing shift+alt on the following text:
```
test                               test
test                               test
date/­tim­e/d­ate­tim­e                 test
testtesttest                       test
_­if_­                               test
test                               test
testtesttest                       test
test                               test
```
![Peek 2020-03-04 09-50](https://user-images.githubusercontent.com/30376796/75881374-ac79e480-5dfd-11ea-8ed4-fd2afef92d95.gif)

The same happens with shift+alt+arrow.

Does this issue occur when all extensions are disabled?: Yes

## Expected behavior
It should get multi-cursors in a line, like this in sublime text:
![image](https://user-images.githubusercontent.com/30376796/75881587-20b48800-5dfe-11ea-84bc-6fbbcd768ac9.png)

**Comment by alexdima** [comment]
This happens due to the presence of `U+00AD` in your text. I have copy-pasted your text and used a binary viewer to look at it:

![image](https://user-images.githubusercontent.com/5047891/75901076-49f50880-5e3e-11ea-9e7e-4e56f3203a4d.png)

**Comment by renanwillian** [comment]
Should the selection be broken in the presence of `U+00AD`?

**Comment by alexdima** [comment]
This is as designed, the editor cursor operations do not use glyph/font rendering information. In this case, this font renders `U+00AD` as a character of 0 width. Other fonts might render this differently.

The editor cursor movement operations, like column selection or arrow up/down assume a monospace font which would render all characters with equal width. The reason is that text layout is delegated to the browser and the editor renders only visible sections of the screen.

**Comment by alexdima** [comment]
I agree that this works better in Sublime Text, they might have text layout information computed for all of the text buffer, not just the visible ranges, like we do.
