### ISSUE TITLE
Windows: Allow Pasting Multi-Line Scripts/Functions into the Terminal Window

### ISSUE THREAD

**Issue by gw-bcharboneau** [microsoft/vscode#92021]
OS: Windows 10 build 18362
VSCode: 1.42.1
Powershell: 5.1 and core 7.0.r3

When Pasting a multiline function or script into the terminal window within VSCode it appears to have hard line breaks even though powershell supports code block pasting natively.
for example, if you paste the following function into the terminal within vscode, it will complain that it is missing a closing } since it is not on the end of line 1. however if you paste it into the native powershell console (regardless of version) it handles the line continuation properly.

example function provided will not run in PSCore as it is unable to import the System.Web Assembly. but you can test with any function, the result is the same.

```
function New-Password {
    Add-Type -AssemblyName 'System.Web'
    $length = 16 ## characters
    $nonAlphaChars = 5
    $pass = [System.Web.Security.Membership]::GeneratePassword($length, $nonAlphaChars)
    return $pass
}
```

**Comment by Tyriar** [comment]
With help understanding this from @TylerLeonhardt, I got this:

```
if($true)
{
# asdf
}
else
{
}
```

From this:

![image](https://user-images.githubusercontent.com/2193314/78586312-1ff18600-77f0-11ea-859d-c3ea43efc8b0.png)

To this:

![image](https://user-images.githubusercontent.com/2193314/78586295-19fba500-77f0-11ea-89ef-2ea08f622621.png)

**Workaround:** By unbinding this keybinding (paste into keybindings.json):

```json
{
	"key": "ctrl+v",
	"command": "-workbench.action.terminal.paste",
	"when": "terminalFocus"
}
```

This happens because PowerShell's PSReadLine handles ctrl+v. Thinking about a way to solve this generically now.

**Comment by Tyriar** [comment]
Proposal to fix: New built-in keybinding rule like this:

```json
{
	"key": "ctrl+v",
	"command": "-workbench.action.terminal.paste",
	"when": "terminalFocus && !terminalShellType == 'pwsh'"
}
```

`terminalShellType` would be of the shape: `'cmd' | 'pwsh' | 'wsl' | 'gitbash' | 'unknown'` currently Windows only using the shell detection logic we already have:

https://github.com/microsoft/vscode/blob/dfb7a5ebd3ad07208974286ea13d88c87960fddf/src/vs/workbench/contrib/terminal/electron-browser/windowsShellHelper.ts#L149-L169
