### ISSUE TITLE
Distinguish commented code from other comments   

### ISSUE THREAD

**Issue by ElchananBS** [microsoft/vscode#92070]
In PHP, for example, 
Colorizing # comments differently  from // and /**/, to help distinguish descriptions and explanations  from commented code.

**Comment by alexr00** [comment]
@ElchananBS you can change you theme to do this since PHP tokenizes # comments differently from // comments

Check out the Developer: Inspect Editor Tokens and Scopes command to get the textmate scope, then you can use that scope in a setting like this:
```
	"editor.tokenColorCustomizations": {
		"textMateRules": [
			{
				"scope": "keyword.operator",
				"settings": {
					"foreground": "#FF0000"
				}
			}
		]
	},
```

You can also create your own theme that does this.
