### ISSUE TITLE
Explorer should show hidden files and their path if they are opened

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#92090]

**Comment by isidorn** [comment]
To verify:
make sure to have some files and folders hidden via `files.exclude`
Open some of the files in an editor. For example via quick open by setting `search.exclude` to contradict the `files.exclude` setting
Make sure that while those files are visible in the editor area they are shown in the explorer. As soon as they are no longer visible the explorer no longer shows them.

**Comment by isidorn** [comment]
Added deemphasize color via 89e1209b33

**Comment by IllusionMH** [comment]
> files are visible in the editor area

To clarify if I had folder that has `a.css.d.ts`, `b.css.d.ts`, ans `c.css.d.ts` in a folder with other files.

I've opened files `a.css.d.ts` and `b.css.d.ts` (tabs in editor), but only `a` is currently active - should I see only `a.css.d.ts` in explorer or all open tabs?

Because I think both options are usable, however it's hard to say which will be preferable.


Checked on 
VS Code version: Code - Insiders 1.44.0-insider (b7bfce30be3c30aa2c33fbe94fe82b81d4105668, 2020-03-17T07:17:39.113Z)
OS version: Windows_NT x64 10.0.18363

Works as expected in files that "hidden" near not excluded files (e.g. `*.css.d.ts`). Shows 2 or 3 "hidden" files if I have 2 or 3 groups in editor that have them active.

However behavior a bit unexpected *for me* if I got to definition of React module - whole `node_modules` folder is expanded (which is huge), `@types` is expanded, and I can see all files in `react` folder.

In this example it would be nice to have behavior similar to Compact folders to folder that contains opened file `node_modules/@types/react` and single `index.d.ts` (open file) inside.

**Comment by isidorn** [comment]
@IllusionMH you should only see `a.css.d.ts` if that is the only one visible.
Agree the other approach also makes sense but for now we went with this.
Let me try to clarify your other point:
Folder `A` is hidden. You open `A/b.txt`, and now you see all children of `A` instead of just `b.txt`? If this is the case can you please create a new issue and ping me on it. Thank you!

**Comment by IllusionMH** [comment]
OK, may be not everything is how I expected.

I've tested on files/folders that are in `.gitignore` and foreground color was dark gray so I thought that this is expected behavior to distinguish them, but in clean repo - I can't distinguish between excluded and not excluded files/folders in explorer at all.

I've checked markup and can't find `#8C8C8C` anywhere on tree items (would be really noticeable and not sure if it's good pick for background in dark theme)
