### ISSUE TITLE
JSDoc Header @file will move cursor one space after Enter

### ISSUE THREAD

**Issue by thanpolas** [microsoft/vscode#92094]
Issue Type: <b>Bug</b>

When a JSDoc header exists on a module, there is a bug where the cursor jumps a space after Enter is pressed.

## Replication

1. Create a new JS file in any project.
1. Enter the following JSDoc Header.
1. Press Enter after positioning the cursor under the header.

```js
/**
 * @file File Description.
 */
```

Screencast with the issue on an empty document: https://d.pr/i/XvJqiF

Screencast with the issue on a document with requires: https://d.pr/i/fUnF2i

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 18.7.0

**Comment by thanpolas** [comment]
Actually it doesn't need to be at the header, any expanded JSDoc block at any point in the document will have the same issue.

Also, let me know if I need to close from here and repost on the TS repo.

**Comment by rebornix** [comment]
The default `autoIndent` setting value is `full`, which will keep the current line's indentation, honor language defined brackets, invoke special onEnterRules defined by languages, and lastly honor indentationRules defined by languages. The catch here is indentations rules are the most powerful one but also problematic sometimes as it's regular expression based rules instead of being real context-aware.

We will explore how we can improve regex based onEnter and indentation rules but for now, please use `"editor.autoIndent": "advanced"`.
