### ISSUE TITLE
Wrong Windows Explorer Icons for VSCode

### ISSUE THREAD

**Issue by midou35000** [microsoft/vscode#92098]
- VSCode Version:1.42.1
- OS Version:Windows 10

![Screenshot_1](https://user-images.githubusercontent.com/6606027/76007300-1e415380-5f0e-11ea-9b94-db8294c5c5f0.png)
![Screenshot_2](https://user-images.githubusercontent.com/6606027/76007309-226d7100-5f0e-11ea-9689-c01f2928fa63.png)
![Screenshot_3](https://user-images.githubusercontent.com/6606027/76007312-24373480-5f0e-11ea-8716-2a87944ebfad.png)

As you can see in the screenshots, I can't see the right icons for .cpp files, it shows the default ones. It works for .json files tho.

Does this issue occur when all extensions are disabled?: Yes/No Yes

**Comment by midou35000** [comment]
![cppfil](https://user-images.githubusercontent.com/6606027/76309275-c2d7e280-62cc-11ea-838b-83ce47f82d97.png)

Note that my system language is set to Norwegian. That's why you see "cpp-fil".

**Comment by midou35000** [comment]
Alright so apparently the issue was my windows display language.
After changing the language of the system to English all the icons are showing now after opening them.
Maybe this could be a bug submission as well?

![icons](https://user-images.githubusercontent.com/6606027/76401572-62a37800-6382-11ea-9398-e709ffe8f28d.png)

**Comment by misolori** [comment]
@bpasero this appears to be a display language bug

**Comment by bpasero** [comment]
VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

Reading this issue, it seems to originate not from VSCode itself but rather one of these upstream components. As such, in order to resolve it, it would need to get fixed in the upstream component. I will go ahead and close this issue and kindly ask to report this issue to the upstream component if possible:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
