### ISSUE TITLE
[Feature Request] NPM panel (similar to Visual Studio nuget package manager)

### ISSUE THREAD

**Issue by rajeshaz09** [Microsoft/vscode#9211]
It would be nice, Node Package Manager panel , similar to the Visual Studio nuget package manager.

**Comment by coldacid** [comment]
Better would be a generic package/component manager panel that extensions can plug into. Not everyone uses npm -- even in the JS world there are alternate package systems that some projects might use instead.

**Comment by bgse** [comment]
Agree with @coldacid here, should keep in mind that in many cases, npm as a package manager is actually just working "under the hood" and you don't really interact with it at all.

**Comment by FabianLauer** [comment]
I've thought about this feature for a bit and a few ideas and questions come to mind. I dig @coldacid's idea about package manager *extensions*, so from here on out I'm just going to assume that package managers will be implemented by extensions. Package manager extensions could also be used for adding [TypeScript definition management](https://github.com/typings/typings) or even commercial sources (think [codecanyon](https://codecanyon.net/), [telerik](http://www.telerik.com/) and what not) if VS Code is open to that. A similar idea is already in the [roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap#typescript-javascript-and-node-development) (*"Improved npm support..."*) and it might be yet another reason for people to switch from Sublime to VS Code.

Again, I'm just writing down ideas based on the assumption VS Code will use extensions for package managers. Correct me if I'm wrong though, no hurt feelings :wink:

### Contributions that Package Manager Extensions would have to make

- **Dependency Types**
  Different package management systems have different types of dependencies, for example npm's `dependencies`, `devDependencies`, `peerDependencies`, `optionalDependencies` and global dependencies, each of which fulfil their specific purpose. Package Management Extensions would have to contribute a list of their specific dependency types.

- **Installers**
  Usually, dependency types are installed in a specific way. With npm for instance, there's `npm i typescript -g` or `npm i typescript —save-dev`. Every Package Manager Extension would have to provide at least one installer, but one installer should be able to install multiple dependency types if their installation procedures are similar.

- **Uninstallers**
  Packages have to be uninstalled too, so similar as with Installers there should be a way to uninstall packages with the click of a button.

- **Error Recovery Helpers**
  If installations go wrong, the UI should assist in resolving the installation problems. In npm for example, there's the `npm-debug.log` file — maybe error recovery help could also be printed in the output console.

- **Meta Data Providers**
  Descriptions, thumbnails, download statistics etc would have to be available in the UI. Such meta data must be provided via extensions because the sources for this data differ vastly between package managers. Extensions could easily wrap around libraries like [npm-registry-client](https://github.com/npm/npm-registry-client) and similar.

  ​

### User Interface Ideas

#### Package Details Tab

##### Header

![package-details-header](https://cloud.githubusercontent.com/assets/2205595/19327484/80df5b74-90cf-11e6-8678-25ffbf5a058c.png)

Something else that came to mind here is a UI element that indicates whether a package is compatible with your project's license.

##### Meta Data Tabs

![tabs](https://cloud.githubusercontent.com/assets/2205595/19327707/97d0ef9a-90d0-11e6-8c01-61d21ce693e4.jpg)

The ideas I've had so far for "Meta Data" tabs:

- **Details**
  A description of the package, similar to the details tab for extensions.
- **Statistics**
  How often has the package been downloaded today, this month, this year, in total, etc. Maybe a downloads per time graph similar to [the one on the Sublime Text Package Control website](https://packagecontrol.io/packages/CoffeeScript).
- **Dependencies**
  A list of dependencies, like Visual Studio's "Manage NuGet Packages" window. Maybe a dependency tree?

#### Failed Installations

There should be a way to recover if something goes wrong during installation. A UI such as the following would address the best case scenario in which errors might be resolved by simply trying the installation again.

![failed-install](https://cloud.githubusercontent.com/assets/2205595/19327497/8a5e644c-90cf-11e6-89f8-80569f657a0a.png)

### Putting it together

Here's my two cents on the workflow. Not all too detailed, but maybe its a start. These are just mockups BTW, no code was written :wink:

#### Installing Package Managers
![Package Manager Extension Install](https://cloud.githubusercontent.com/assets/2205595/19327957/e06a7216-90d1-11e6-9120-afaa04941142.gif)
[higher resolution](https://vid.me/BHDv)

#### Package Search
![Package Search](https://cloud.githubusercontent.com/assets/2205595/19328239/039e31e0-90d3-11e6-8052-00ba5797c5ed.gif)
[higher resolution](https://vid.me/hEzY)


#### Install & Uninstall Package
![Install & Uninstall Package](https://cloud.githubusercontent.com/assets/2205595/19328360/90c40432-90d3-11e6-8acc-e0afbfd9a570.gif)
[higher resolution](https://vid.me/urZC)

#### Failed Installation
![Failed Installation](https://cloud.githubusercontent.com/assets/2205595/19328280/393d02e0-90d3-11e6-8add-734d6291b188.gif)
[higher resolution](https://vid.me/cb2J)

### Some more Questions

A few more things that aren't in the UI mockup:

- Should VS Code ask to install missing package dependencies automatically when opening a project?
- How to represent dependency versions in the UI (`npm i typescript@2.0.0` vs `npm i typescript@2.0.2`).
- Should VS Code come with widely used package managers preinstalled?
- How to (or, should VS Code) deal with potentially complex error recovery?

**Comment by coldacid** [comment]
@FabianLauer that is amazingly well thought out, thanks! 😃

**Comment by Charlkie14** [comment]
This would be very very cool and useful! I think its a brilliant idea.

**Comment by gyansoft786** [comment]
specially in entity framework core, lots of commands requires **nuget package manger console**,
e.g.  install entityframework, update-database, migrations etc. 
Most of tutorials on ASP.NET Core uses NPM, specially for database (entity framework).
A windows user can easily download VS Community version and use NPM Manager.
But what about mac and linux user. 
Yes i know there are alternate ways (_using terminal command, or download manually a package and install_). 
But VS Code should have NPM Manger for dot net developer, it'll be a thumbs UP if..

**Comment by mjbvz** [comment]
The [tree view api](https://code.visualstudio.com/docs/extensionAPI/vscode-api) would work well for this. One of our tree view extension samples even implements a basic version of this feature: https://github.com/Microsoft/vscode-extension-samples/blob/master/tree-view-sample/src/nodeDependencies.ts

If you are interested in creating this, let me know if you have any questions about the VSCode APIs

**Comment by mjbvz** [comment]
Closing as extension-canidate
