### ISSUE TITLE
Opening a file marks it as dirty though no changes have been made

### ISSUE THREAD

**Issue by chambleton** [Microsoft/vscode#9216]
- VSCode Version: 1.3.1
- OS Version: Windows 7 sp1

Steps to Reproduce:

1. Open any file in the editor
2. Note the file is marked as modified though no edits or changes have been made
3. Close the file; user is prompted to save.

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by chambleton** [comment]
That did the trick -- thanks!

**Comment by thirdwaffle** [comment]
@chambleton I'm getting this issue occasionally. Were you able to determine which extension was causing this?
