### ISSUE TITLE
Implement a node.js-free, sandboxed, context isolated renderer 

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#92164]
We want to explore a model where the workbench in Electron does not access node.js APIs. In that model the Electron renderer process runs in sandboxed mode, much like any browser tab would do. Privileged code has to either move into a backend process and be accessible via IPC communication or into a preload script that exposes certain methods to the page.
 
# July
- [ ] :runner: https://github.com/microsoft/vscode/issues/154006 @bpasero @deepak1556
- [ ] :runner: https://github.com/microsoft/vscode/issues/154007 @deepak1556 

# Backlog
- Tests: 
  - `common/browser`: run in `BrowserWindow` with `sandbox: true`
  - `node.js/electron-browser`: run in `ELECTRON_RUN_AS_NODE`

# Architecture
![image](https://user-images.githubusercontent.com/900690/130733006-2ee57050-5525-4edc-8cca-8d68cd74ecd6.png)

**Comment by jrieken** [comment]
An "implict" node-dependency that's not listed here is code loading. Today, the loader uses the `fs` and `vm`-modules which allows for v8 cached data usage.

**Comment by bpasero** [comment]
Bootstrap **sandboxed workbench** code pointers:
* enable `sandbox` & `contextIsolation` in [`window.ts`](https://github.com/microsoft/vscode/blob/a906625efbc2d0b19ff27eb870e478a047e431e3/src/vs/code/electron-main/window.ts#L125)
* load something like a `workbench-sandboxed.html` from [`doGetUrl`](https://github.com/microsoft/vscode/blob/a906625efbc2d0b19ff27eb870e478a047e431e3/src/vs/code/electron-main/window.ts#L708)
* this will likely fail early on because of our AMD loader requiring node.js for cached data etc. and some other things we depend on from [`window.js`](https://github.com/microsoft/vscode/blob/a906625efbc2d0b19ff27eb870e478a047e431e3/src/vs/code/electron-browser/workbench/workbench.js) so we need something like `workbench-sandboxed.js` and possibly `workbench-preload.js` that work properly in this mode
* instead of `vs/workbench/workbench.desktop.main` load a `vs/workbench/workbench.desktop-sandboxed.main` [here](https://github.com/microsoft/vscode/blob/a906625efbc2d0b19ff27eb870e478a047e431e3/src/vs/code/electron-browser/workbench/workbench.js#L22) with those things commented out that are not yet adopted
* instead of `vs/workbench/electron-browser/desktop.main`, require a `vs/workbench/browser/desktop-sandboxed.main` [here] (https://github.com/microsoft/vscode/blob/a906625efbc2d0b19ff27eb870e478a047e431e3/src/vs/code/electron-browser/workbench/workbench.js#L33) that brings up the workbench without depending on node.js

**Comment by dbaeumer** [comment]
@bpasero we shouldn't mix localization support in the Web with support for Node free renderer. We need a very different story for the Web whereas for a node free renderer we can still install the LP on the local disk. We can simply not access them from the renderer. So I will change the item (I have discussed it that way with @egamma as well)

**Comment by bpasero** [comment]
A minimal workbench in `sandbox` and `contextIsolation` mode can now be run via `scripts/code.sh  --__sandbox`. It provides a in-memory file system and stubbed services for many things that are not yet adopted:

![image](https://user-images.githubusercontent.com/900690/91577170-a138e900-e948-11ea-90ff-5a9b43707d8d.png)

**Comment by deepak1556** [comment]
Some notes about `vscode-ripgrep` from Rob:

- It is not a native node module, 
- Its just a container for ripgrep binary
- The module is not used from the render process but rather from the search process where it spawns the ripgrep binary.
- From the remote scenario it is launched from the extension host process.

@bpasero given this we can move out the module from the transition list

**Comment by deepak1556** [comment]
Notes from discussion with Daniel:

`node-pty`

* Plan is to move to a pure nodejs process host that would allow the capability to use worker threads, as currently there is a potential deadlock issue https://github.com/microsoft/node-pty/pull/415
* Electron needs to provide this option, currently there is render <-> render api but we need nodejs host <-> renderer
* We don't want to host this module in main or extension host

`xterm`, `xterm-addon-*`

* These are just frontend to the terminal
* There are no node components here and they already run on the web

`windows-process-tree`

* This is used by the terminal to get the process names
* It is ideal for this module to live wherever `node-pty` lives

**Comment by Tyriar** [comment]
A few more notes on `node-pty`:

- This cannot live only under the extension host as that will impact terminal launch time.
- Perhaps we need a general pure node process (off main or shared) which hosts native modules like `node-pty`, file watchers, etc.
- Issue to move node-pty out onto another process https://github.com/microsoft/vscode/issues/74620 - this idea is also related to potentially keeping terminal processes around after VS Code is closed, if we went this route the general node process above wouldn't work.

**Comment by bpasero** [comment]
@deepak1556 

> @bpasero given this we can move out the module from the transition list

Sort of, are we saying that search can move 100% into the extension host? If so, we should do this on `master` already and thus the ripgrep dependency would move out of the renderer into the extension host.

**Comment by bpasero** [comment]
> Perhaps we need a general pure node process (off main or shared) which hosts native modules like node-pty, file watchers, etc.

Would the shared process not be sufficient for this already? Does it have to be a child-process of the shared process?

I agree that e.g. the file watcher must be a child-process simply because it uses a lot of CPU cycles potentially, but not sure about others.

**Comment by Tyriar** [comment]
@bpasero it would be for most things. In order to fix this bug on Windows where closing a terminal can deadlock the UI thread https://github.com/microsoft/node-pty/pull/415,  we need node-pty to support workers. Doing it with a web worker is an option, but node-pty is a node library and supporting web workers is a hack that I'd rather not do.

That was just an idea though, it probably makes more sense to have a node process just for managing terminal processes to consolidate logic between main (local terminals) and ext host processes (remote terminals).

**Comment by mjbvz** [comment]
https://github.com/microsoft/vscode/commit/368f44e07bcaf6aa9e81d76a08dbe72e0aabf26c enables iframe based webviews on desktop when search functionality is not required. We'll get testing of the iframe based webviews during 1.56 insiders

**Comment by gs271** [comment]
Hi,
I am unable to launch the terminal since morning.
it doesn't open up every time I open it get below error.

![image](https://user-images.githubusercontent.com/84413640/121016727-1d0a7080-c7ba-11eb-90c2-f463f5ec76bc.png)
![image](https://user-images.githubusercontent.com/84413640/121016772-2b588c80-c7ba-11eb-8f74-3496ec594efc.png)

**Comment by metmeylmz** [comment]
> Elektrondaki tezgahın düğüme erişmediği bir modeli keşfetmek istiyoruz.js API'leri. Bu modelde, Electron renderer işlemi, herhangi bir tarayıcı sekmesinin yapacağı gibi korumalı modda çalışır. Ayrıcalıklı kodun ya bir arka uç işlemine geçmesi ve IPC iletişimi yoluyla erişilebilir olması ya da belirli yöntemleri sayfaya sunan bir ön yükleme komut dosyasına girmesi gerekir.
> 
> # Kasım
> * `electron-browser`To'dan daha fazla bağımlılık kaldırın `electron-sandbox`
>   
>   * [ ]  [İşlemi yeniden kullanmak için uzantı ana bilgisayarını tezgahın dışına taşıyın # 123592](https://github.com/microsoft/vscode/issues/123592) @ alexdima @deepak1556 @bpasero
> * Modern elektron özelliklerini etkinleştirme ve doğrulama 
>   * [ ]  [Elektron: Rzhao271'de #120431](https://github.com/microsoft/vscode/issues/120431) @renderer işleminin yeniden kullanımını etkinleştir
>   * [ ]  [`contextIsolation`Tüm pencereler için etkinleştir # 128099](https://github.com/microsoft/vscode/issues/128099)
> 
> # Güvertede
> * `electron-browser`To'dan daha fazla bağımlılık kaldırın `electron-sandbox`
>   
>   * [ ]  [Sanal alan: uzantı ana bilgisayar iletişimini etkinleştir #135268](https://github.com/microsoft/vscode/issues/135268)
>   * [ ]  [Sanal alan: v8-ınspect-profiler'ı işleyiciden taşıma #111211](https://github.com/microsoft/vscode/issues/111211)
> 
> # Birikim
> * Tam etkin sanal alana doğru 
>   * [ ]  `sandbox: true`Bir dev ayarının arkasında etkinleştirmeye izin ver
>   * [ ]  `electron-sandbox`Yeniden adlandır `electron-browser` ❓ & sıkı katmanlama kurallarını geçir
>   * [ ]  Daha fazla yok `TODO@Sandbox`
>   * [ ]  Güvenlik: Dev araçlarını varsayılan olarak devre dışı bırakmak için araştırın?
>   * [ ]  Performans doğrulama ve ayarlama 
>     * Fazla kullanmak zorunda kalmanın etkisini anlayın`Uint8Array` `Buffer`
>     * Yerel çözüme kıyasla IPC üzerinden dosya hizmetinin verimini ölçün
>     * Yeni pencereler için soğuk başlatma sonrasında ısınmış Chrome işlemlerinden yararlandığımızı doğrulayın
>     * macOS: Akışlardaki 8kb yığın sınırını araştırın ([Değişiklikleri açın ve büyük bir json dosyasındaki Sahne Alanı Değişikliklerine hızlı bir şekilde tıklamak 10 saniye boyunca engellenir / kilitlenir # 40681](https://github.com/microsoft/vscode/issues/40681))
>   * [ ]  💪 korumalı ortamda çalıştırmak için birim, entegrasyon, duman testlerini benimseyin
> 
> # Mimari
> ![görüntü](https://user-images.githubusercontent.com/900690/130733006-2ee57050-5525-4edc-8cca-8d68cd74ecd6.png)

[]() 

> `
Yinelenen #`

**Comment by sandy081** [comment]
`CachedExtensionScanner` is owned by @alexdima and hence removing my name.

**Comment by wendellhu95** [comment]
Will floating window get supported under this new architecture?

**Comment by bpasero** [comment]
No, it should not have any impact on that.

**Comment by bpasero** [comment]
I think it is about time to close this one, insider builds are out on all platforms that allow to enable the sandbox via `"window.experimental.useSandbox": true` and https://github.com/microsoft/vscode/issues/155827 is a test plan item to verify it works.

Remaining issues are tracked with `sandbox` label: https://github.com/microsoft/vscode/labels/sandbox

**Thinking on the timeline:**
* enable sandbox by default in insiders in August
* enable sandbox by default in stable in September/October pending issues found

🥇
