### ISSUE TITLE
Cannot assign custom hotkey to "Clear filter" in Problems pane

### ISSUE THREAD

**Issue by pe224** [microsoft/vscode#92189]
- VSCode Version: 1.43.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:
1. Go to Problems pane, enter some text into filter box.
2. `Escape` clears the filter box. I tried every command which is assigned to `Escape` in default keybindings and assigned each to `ctrl+c`. However, I could not clear the input box that way.
`Escape` seems to be special-cased somehow, maybe due to [this](https://github.com/microsoft/vscode/blob/14657a93e945d98d1da18722f1a0ae20385387a4/src/vs/workbench/contrib/markers/browser/markersViewActions.ts#L388-L397)?

Expected behavior:
I can assign the custom keybinding `ctrl+c` to clear this filter.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
Yes, this is not exposed and its true for all input boxes and `esc` is hardcoded to clear the input box. This is done because of some limitations.

So it is not possible to remove the `esc` key to clear, instead I can provide an action to clear filter input. This is unbound to any key by default and you can bind it to the key you like.

`problems.action.clearFilterText`
