### ISSUE TITLE
List: Implement `list.clearFilter` command

### ISSUE THREAD

**Issue by pe224** [microsoft/vscode#92187]
- VSCode Version: 1.43.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:
1. Add `{"key": "ctrl+a", "command": "list.clear"}` to your keybinding
2. Focus Panel -> Debug console (can be empty)
3. Open search with `ctrl+f` and enter some text
4. Press the key combination of 1. to call `list.clear`. Nothing happens.

Expected:
Same behavior as manually clicking on `x` next to search box: search is deleted, focus back on debug console command line.
![image](https://user-images.githubusercontent.com/8567333/76128049-90e02b00-6003-11ea-95d6-d4c856413bb3.png)

Note that (hardcoded?) `Esc` key does delete text, but does not return focus to the command line, so it is also not completely the intended behavior.

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
list.clear does not clear the search term, it clears the foucs in the list. Thus the selection and focus get cleared and focus gets passed to the list/tree.
This is not specific to the debug console, but is specific to the list. 
Unforutnetly it is not possible to customize the keybinding of clearing the filter in the list/tree.

Since this is a list issue forwarding to @joaomoreno
I agree that the command has a confusing name.
