### ISSUE TITLE
when using a screen reader, saying "command is" in the keyboard shortcuts list is inefficient

### ISSUE THREAD

**Issue by camlorn** [microsoft/vscode#92212]
The point of interest is the command, and when I arrow through lists of hundreds of items having to listen to "command is" to find out what the current item is is very inefficient.  I would drop "command is" all together.

There's other issues like this one.  Do we have somewhere to track inefficient speech labeling?

**Comment by isidorn** [comment]
@camlorn thanks a lot for providing this feedback. I think it makes sense, since the repeatition does not bring any value. We have pushed a fix for this and you can see the changes in VS Code insiders in a couple of days
For inefficient speech labeling please ping me on existing issues or create new issue for things which are not covered and we can look into improving them. Thanks a lot!

fyi @sandy081 
https://code.visualstudio.com/insiders/

**Comment by isidorn** [comment]
@camlorn did you get a chance to try this out with vscode insiders? Asking because we would like to add a verified label to this issue if it got fixed for you.
