### ISSUE TITLE
JavaScript: Union Types don't appear to be correctly supported

### ISSUE THREAD

**Issue by WolfieZero** [microsoft/vscode#92235]
- VSCode Version: 1.42.1
- OS Version: macOS 10.15.3

![2020-03-08 at 18 23](https://user-images.githubusercontent.com/648761/76168714-1251cd80-616a-11ea-89f9-3414380d35c9.png)

From the code snippet above (with `checkJs: true` set in the jsconfig.json file) I'm being told that the type is a number but the JSDoc I've set to be a union type of either a number or string. I've tried various ways of formatting the `@param` definition such as (including the reverse):

- `{string | number}`
- `{string|number}`
- `{(string|number)}`

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by spahnke** [comment]
That's because `identifier` could still be a string **or** a number after the first `if` statement. Since numbers don't have the `length` property or a `toUpperCase` function you get an error. Your code treats `identifier` as a string after the if, which could lead to a runtime error. Your default case catches this case right now, but in principle it could be an error.

**Comment by WolfieZero** [comment]
Ah, so it should be parsed to a string afterwards the initial check?

**Comment by spahnke** [comment]
Yeah, either that or you could add another check using `typeof`. Whatever makes more sense for your domain logic.

**Comment by WolfieZero** [comment]
Not an issue with VS code then but my code >.< 

Closing this now. Thanks for the advice @spahnke.
