### ISSUE TITLE
Clicking on links in the update toast message opens blank browser window

### ISSUE THREAD

**Issue by openJT** [Microsoft/vscode#9225]
- VSCode Version: All, 1.3.0
- OS Version: Ubuntu 16.04
- Default browser: Chrome

Steps to Reproduce:

1. Click on links in the update toast message.

Description:
 
 - All links open a blank new Chrome window.

**Comment by weinand** [comment]
@openJT what is a "update toast message."?

**Comment by openJT** [comment]
When there is an update to vscode, a message appears at the top: there is an update! You have 3 choices: downlad now, later or see releases notes. If I click any of those links.

**Comment by joaomoreno** [comment]
I can't reproduce with Ubuntu 16.04 and Chrome as a default browser.

Do you have any extensions installed? Any plugins installed in Chrome?

What happens if you do the following steps?

1. Download the latest [vanilla Electron release](https://github.com/electron/electron/releases/download/v1.2.6/electron-v1.2.6-linux-x64.zip),
2. Run it
3. Open the Console in the Devtools (<kbd>Ctrl Shift I</kbd>)
4. Run `require('electron').shell.openExternal('http://code.visualstudio.com')`

**Comment by openJT** [comment]
It opens a blank page. I tried disabling all extensions, same thing. Firefox as the default works.

**Comment by joaomoreno** [comment]
You might want to track and keep those guys informed at electron/electron#6531

**Comment by Tyriar** [comment]
There are a few issues in Electron around shell.openExternal and admin, you're not running under `sudo` are you?

**Comment by openJT** [comment]
@Tyriar I am not.
