### ISSUE TITLE
Autocompletion for {}, [], () is very intrusive

### ISSUE THREAD

**Issue by d180cf** [Microsoft/vscode#9226]
vscode autocompletes the closing ), ] or } even when there is no need to (the need is determined by my subjective preferences to write code, not by syntax). This becomes especially inconvenient when I need to wrap an existing chunk of code:

```js
function () { // <-- I've started typing this to wrap the three vars below
var a = 1;
var b = 2;
var c = 3;
```

At this point vscode inserts the closing } so I need to remove that } and insert it at the right place.

**Comment by Displace** [comment]
This is how both Sublime and Microsoft Visual Studio works as well.  

The problem here is that the auto complete doesn't know that you want to wrap that particular block of code in a function.  I'm not sure if this is possible, but is there a way to turn off auto complete in the settings?  

The only other recommendation is that an enhancement is requested to add a "Surround With" option like Microsoft Visual Studio has.

**Comment by d180cf** [comment]
Not sure about MSVS - their JS editor was pretty good and didn't insert these closing braces. I'm pretty much asking to get the same experience in vscode.

**Comment by alexandrudima** [comment]
@d180cf You can disable the feature with the setting `"editor.autoClosingBrackets": false`

**Comment by d180cf** [comment]
This works nicely. Thanks!
