### ISSUE TITLE
visual studio code opens ttwo windows when i open the ws code

### ISSUE THREAD

**Issue by clintbingo** [microsoft/vscode#92368]
Issue Type: <b>Bug</b>

When i click on the vs code shortcut on my taskbar it opens to instances of the vs code editor with two different projects in each window. Obviously i only want one window open the first time and open more if needed.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 6.3.9600

**Comment by VAggrippino** [comment]
I seem to be having this problem too. I usually open VSCode from the WSL command line, but it occurs when I open it using the icon too.

I think this started after I updated to the latest version yesterday.

From the command line (`code .`) it opens one window for the intended project and the other window for an old project that I have since deleted. So, the second window actually shows the name of the (deleted) workspace folder with a tooltip error saying "Unable to resolve workspace folder"

When starting VSCode from the icon, pretty much the same thing happens. One window is for the most recent project (as expected) and the other window is from the same deleted project.

**Comment by bpasero** [comment]
@clintbingo @VAggrippino there is a setting `window.restoreWindows` that you can set to `one`. Does that help?

**Comment by VAggrippino** [comment]
> @clintbingo @VAggrippino there is a setting `window.restoreWindows` that you can set to `one`. Does that help?

No difference.

It doesn't seem like that would address the problem anyway. If it was restoring a previously closed window, it should match the first or second entry in File -> Open Recent.

This is attempting to open some random folder that hasn't even existed for over a week.

**Comment by bpasero** [comment]
@clintbingo @VAggrippino this sounds like https://github.com/microsoft/vscode/issues/92318 where beginning with this new version we try to restore all windows that had dirty files in them. We are thinking to revert back to how it was and then it would not happen anymore.

Can you confirm that you see dirty files in the extra windows that open?

**Comment by VAggrippino** [comment]
I was able to fix the problem by creating the folder again and opening VSCode from the command line within that folder (`code .`).

When I did that, it showed a file with unsaved changes. I closed the file without saving changes, then closed VSCode. Now it doesn't try to open the folder any more.

**Comment by VAggrippino** [comment]
> @clintbingo @VAggrippino this sounds like #92318 where beginning with this new version we try to restore all windows that had dirty files in them. We are thinking to revert back to how it was and then it would not happen anymore.
> 
> Can you confirm that you see dirty files in the extra windows that open?

Yes... sort of. In my case, the files didn't actually exist, but after I created an empty folder with that name I saw the "dirty" file in the editor.
