### ISSUE TITLE
Enable JS/TS language features change the assets of VS Code

### ISSUE THREAD

**Issue by Whitefox98** [microsoft/vscode#92360]
- VSCode Version: 1.43.0
- OS Version: Windows 10

Steps to Reproduce:

It happens with all custom themes in my case Material Theme but also I try with other themes and and it happens with all themes. This is happening since I update the VS to february version.

1. Open some TS/JS file with imports, routering...
2. It seems to be correctly but after Initializing JS/TS Features load, seems completely another theme.

Look pictures:
1) Previous Initializing (correct)
![imagen](https://user-images.githubusercontent.com/47216398/76319962-40f1b480-62e0-11ea-8894-d0bdbe031abd.png)

2) After Initializing (incorrect)
![imagen](https://user-images.githubusercontent.com/47216398/76319973-46e79580-62e0-11ea-900e-c64b517f7a5f.png)

Does this issue occur when all extensions are disabled?: Yes (except the theme obviously)

**Comment by MatiasOlivera** [comment]
Duplicate of #92308

**Comment by rebornix** [comment]
thank you for the feedback, it's caused by the semantic syntax highlighting and for now you can turn off the semantic syntax highlighting feature by changing below setting:

```
"editor.semanticHighlighting.enabled": false
```

@aeschli I didn't close this issue as duplicate as this one is also talking about slow js/ts initialization leading to theme change, which I don't know how we can solve properly.

**Comment by aeschli** [comment]
Duplicate of #92308
