### ISSUE TITLE
Debug picker: consider to show a gear icon to configure config

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#92378]
Compare with tasks:

![image](https://user-images.githubusercontent.com/900690/76331840-eb250880-62ef-11ea-9ebd-19f9ee6b1ab8.png)

I wonder why debug does not have this action:

![image](https://user-images.githubusercontent.com/900690/76331867-f37d4380-62ef-11ea-8e48-8b03901fcf57.png)

With the new quick access, this is trivial to add and I would only add it there since we go with it soon. Here is how tasks does it, I literally just need the code to configure a debug config:

https://github.com/microsoft/vscode/blob/cb361ac3a4d9a4fee8443690cdf98efd4f4af626/src/vs/workbench/contrib/tasks/browser/tasksQuickAccess.ts#L128-L136

Challenge is there seems to be 2 entries in debug quick open:
* `ILaunch`
* config `{ launch: ILaunch, name: string, presentation?: IConfigPresentation }`

**Comment by isidorn** [comment]
`OpenConfigFile` would have to add an argument to open on a specific name [here](https://github.com/microsoft/vscode/blob/89e1209b3326c1d0a932468155f844094b0cb5a1/src/vs/workbench/contrib/debug/browser/debugConfigurationManager.ts#L576)
So that opening config files opens on the correct location.
Not sure how tasks does it, and if they can open on the exact line number. Because without the line number the experience is not that neat.

And you would just use `launch.openConfigFIle` if it is just an `ILaunch`, or `launch.openConfigFile(name)` if there is a `name`

For now opening to PRs. If nobody does it I can look into it in a couple of weeks.

**Comment by bpasero** [comment]
@isidorn opened https://github.com/microsoft/vscode/pull/92382. This was actually easier than I thought. Let me know why `openConfigFile` would not focus on the launch I picked, I would probably expect that. Otherwise seems to work fine.

To try it out you can do F1 > Quick Access > Debug

**Comment by isidorn** [comment]
Commented on the PR, thanks a lot for creating it.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/commit/b8c1023dd8114b8821c28ce558634fe8c0f5d04d
