### ISSUE TITLE
Opening multiple vscode on simple call because of the cache file.

### ISSUE THREAD

**Issue by renjeeshn** [microsoft/vscode#92422]
when try to open the current directory of the project using vscode it opening the other opened projects are opening that time.

**Comment by ryuukibeat** [comment]
I think it's because you are connected to WSL. Let it open, and then "close remote connection".

I had multiple open too before, one window is my opened project folder, another one is the WSL project. I just close the remote connection from that opened folder, then whenever I open new vscode window or open project folder, it no longer launch double window in my case.

**Comment by renjeeshn** [comment]
Im not running on WSL 


it is opening this file files when I launch the code 
"telemetry.machineId": "",
    "openedPathsList": {
        "workspaces3": [
            "file:///home/user/personal/messagemanagerrestapi",
            "file:///home/user/personal/usermanagement",
            "file:///home/user/.config"
        ],
        "files2": [
            "file:///home/user/.config/.shutdown"
        ]
    },
and im using ubuntu

**Comment by gjsjohnmurray** [comment]
What is your `window.restoreWindows` setting?

**Comment by MatheusJacob** [comment]
I'm having the same problem , with ubuntu.
my "window.restoreWindows": "all",
I'm not running WSL either
