### ISSUE TITLE
Terminal: the "+" could be a dropdown when asking for cwd?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#92432]
In a multi-root workspace when I click on the "+" in the terminal panel to open a new terminal, the picker opens to ask for the cwd far away from the "+" action location.

Wouldn't it make more sense to simply show a dropdown at the "+" where I can pick the CWD folder from?

![image](https://user-images.githubusercontent.com/900690/76390874-8066e200-636e-11ea-9053-600655d67c2f.png)

**Comment by Tyriar** [comment]
There's already a request to change the + into a shell selector dropdown to align with Windows Terminal, cmder, etc. https://github.com/microsoft/vscode/issues/45444

Since this is often requested and we'd be optimizing for the more common case (non-multi root workspaces) I think we should use the dropdown for that.
