### ISSUE TITLE
Sluggish Powershell Terminal Behavior 

### ISSUE THREAD

**Issue by motowilliams** [Microsoft/vscode#9244]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

"terminal.integrated.shell.windows": "C:\\Users\\Eric\\Documents\\WindowsPowerShell\\vscode-startup.cmd"
where **vscode-startup.cmd** only contains `C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\powershell.exe -ExecutionPolicy Unrestricted`

Steps to Reproduce:

1.Start terminal
2.Profile loads normally
3.Type Get-ChildItem (input buffer lags behind keyboard strokes)
4.Press enter after command line catches up
5.Directory listing contents lags on outputting the content as well

**Comment by DanMacDonald** [comment]
I'm having sluggish input in the integrated terminal on Windows 10 Home edition as well. VSCode 1.31

**Comment by Tyriar** [comment]
Duplicate #10328

**Comment by codec-abc** [comment]
I made some profiling of VSCode. I did the following:

* Wait for a few seconds
* Hold down a key
* Wait for a few seconds

Here are the result in the profiler :

![profiling1](https://cloud.githubusercontent.com/assets/1208646/18643860/30fd1c70-7ea7-11e6-9721-a713ba664106.png)

![profiling2](https://cloud.githubusercontent.com/assets/1208646/18643861/32b40538-7ea7-11e6-9a38-a9af1225b9ef.png)

I don't know if this is useful since we don't have details on the "program" that cause the lag. Is there any way to get more details using the debugger tools ?

**Comment by TwoFistedJustice** [comment]
I've recently begun to experience this as well. Just in the last few days without changing anything.

VSCode becomes unusable after about 15 minutes.

Switching to the Windows 10 built in terminal seems to take care of it.
