### ISSUE TITLE
No longer restore backuped folders and workspaces

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#92467]
Followup for #92318

Due to a bug in 1.32 we haven't been restoring the windows for back-up'ed folders. No one complained until we enabled it again for 1.43 as restoring caused trouble for users that have a large number of back-up'ed folders. We suspect they use the setting `"files.hotExit": "onExitAndWindowClose"`. They are never forced to save their unsaved files and therefore end up with large numbers of back-up'ed folders

Not restoring windows of back-up'ed folders seems to be a practical solution.

The plan:
- no longer automatically restore windows of  back-up'ed folders and workspaces
- empty windows and untitled workspaces should still be restored as there's no way of opening them in any other way.
- improve `Open Recent` to show and maybe sort for entries with unsaved entries

**Comment by bpasero** [comment]
👍 

//cc @Tyriar

**Comment by baslr** [comment]
@aeschli is there a way to open all workspaces with unsaved files?
I dont noticed this change because all my workspaces with unsaved files are open and so they restored. Because restore windows setting is `all`.

**Comment by bpasero** [comment]
@baslr typically you would not notice it if you simply always start VSCode because we do restore all windows based on that setting. However there are ways of opening VSCode where it would NOT restore all windows, specifically when you e.g. right click on a folder in Windows and "Open with VSCode" or when you are on the command line and type "code <folder>". For those cases we think about maybe making it more obvious that a workspace has backups by decorating them in the list of recently opened workspaces.

Not sure if we should also have a command to simply open all workspaces with backups. We may again end up with opening tons of windows at once.

**Comment by bpasero** [comment]
I wonder if we should simply take our dirty-decoration used in other places in the picker:

![image](https://user-images.githubusercontent.com/900690/77341047-6e058480-6d2e-11ea-9333-580aa60b391a.png)

What we miss is a property on the recent workspace if it has backups or not.

**Comment by aeschli** [comment]
@bpasero I pushed the change to no longer restore workspaces and folders: https://github.com/microsoft/vscode/commit/e2a9394a28ccbb3163a091eba9f047466cd5deb4

**Comment by bpasero** [comment]
Current thinking:

![Kapture 2020-03-30 at 10 51 52](https://user-images.githubusercontent.com/900690/77894145-2e322600-7275-11ea-9948-ad98ab780cc1.gif)
