### ISSUE TITLE
Rename "Jump to Cursor" to "Set Next Statement"

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#92585]
The Python team has received feedback in terms of the Jump to Cursor feature as it's not very discoverable and I believe its name is part of the reason why. Changing it to "Set Next Statement" could make it more discoverable for those who are familiar with the feature. See the comments here for example: https://github.com/microsoft/vscode-python/issues/9947.

**Comment by gjsjohnmurray** [comment]
What is the "Jump to Cursor" feature? VSCode debug framework has "Run to Cursor", which is not the same thing as I understand a "Set Next Statement" feature.

**Comment by rcjsuen** [comment]
@gjsjohnmurray I found this in the repository.

https://github.com/microsoft/vscode/blob/418d1974ca0f99529e4f55c8d05f0a202404c980/src/vs/workbench/contrib/debug/browser/debugCommands.ts#L50

From what I understand it's a way to tell the debugger to bypass any intermediate statements and start executing instructions from the selected line.

**Comment by luabud** [comment]
It's exactly what rcjsuen said 😊 

Here's a GIF that shows this in action: https://devblogs.microsoft.com/python/wp-content/uploads/sites/12/2020/02/Feb20-JumpToCursor8.gif

**Comment by gjsjohnmurray** [comment]
@rcjsuen @luabud thanks for the info. I found the relevant release notes at https://code.visualstudio.com/updates/v1_36#_jump-to-cursor

**Comment by isidorn** [comment]
@luabud we decided on `Jump to Cursor` because the name aligned better with the current `Run to Cursor`. We were aware that this feature is called Set Next Statement in Visual Studio, however we just prefered the current name.
Changing the name now might break existing users.
What we could do is register the Set Next Statement command in the command palette that would just do the same thing. So we just duplicate it, not the nicest but people who search for it in the command palette would find it.

I am also open for ideas.
fyi @weinand @connor4312

**Comment by weinand** [comment]
We will not change the name but I like Isidor's suggestion to introduce an alias.

**Comment by isidorn** [comment]
We have added an "alias" for the Jump to Cursor command. The alias is "Set Next Statement'. So now it should be available in the command palette.

@luabud it would be great if you try it with VS Code insiders some time next week and let us know if it works good for you. Thanks

**Comment by luabud** [comment]
That's awesome, thank you so much! 🎉
