### ISSUE TITLE
Provide way to check chrome://gpu

### ISSUE THREAD

**Issue by seawalk24** [microsoft/vscode#92586]
Launching VS Code with --disable-gpu works but adding disable-hardware-acceleration to argv.json has no effect.

- VSCode Version: 1.43.0
- OS Version: MacOS 10.15.3

Does this issue occur when all extensions are disabled?: Yes

**Comment by hangtwenty** [comment]
i've been having the same issue, and vscode has been crashing frequently (which seems to be related)

**Comment by deepak1556** [comment]
@seawalk24 can you please expand on what basis you think the argv.json flag is not working. Thanks!

@hangtwenty the issue you are facing is different, its https://github.com/microsoft/vscode/issues/92420. Please follow that issue for updates.

**Comment by seawalk24** [comment]
@deepak1556 I am running VS Code in a virtual machine that has major graphical issues if I don’t run it with the —disable-gpu option. I’d like to not have to specify the —disable-gpu option every time and instead use disable-hardware-acceleration in argv.json but when I do this the graphical issues are present.

**Comment by deepak1556** [comment]
Sorry for the delay, thanks for adding more context. Can you provide some steps to repro this issue, what vm and OS to use etc

**Comment by cqlmikegross** [comment]
@deepak1556 

The graphical glitching is occurring on MacOS 10.15.5 using Parallels 15. This bug report is not to fix the graphic glitching, as similar glitching occurs for example if you were to open a Finder window with 2 tabs. The purpose of this bug report is to make it so that disable-hardware-acceleration is utilized when specified in argv.json so that it won't be necessary to specify --disable-gpu every time as a command line parameter. I suspect that disable-hardware-acceleration may not be working even outside of a VM.

**Comment by seawalk24** [comment]
@deepak1556 

The graphical glitching is occurring on MacOS 10.15.5 using Parallels 15. The purpose of this bug report is not to fix the graphic glitching because similar glitching occurs elsewhere such as opening a Finder window with 2 tabs. 

The purpose of this bug report is to make it so that disable-hardware-acceleration is utilized when specified in argv.json so that it won't be necessary to specify --disable-gpu every time as a command line parameter. I suspect that disable-hardware-acceleration may not be working even outside of a VM.

**Comment by deepak1556** [comment]
Unable to repro with latest stable.

**Comment by eyalroth** [comment]
I am experiencing this with the latest version of VSCode.

Adding `"disable-hardware-acceleration": true` to the `argv.json` file doesn't seem to work, while running VSCode from the CLI with `--disable-gpu` does.

I believe I am experiencing the same graphical glitches that the OP was experiencing. In any case, I'm trying to disable hardware acceleration in order to workaround these glitches. Like the OP said, I do believe that the glitches are _not_ a problem with VSCode but rather with MacOS.

See this thread for more information of the problem which occurs in other applications as well (perhaps all of them are Chrome-based?): https://forums.macrumors.com/threads/strange-chrome-browser-graphical-glitches.2229803/


VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|11.0.0
vscode-great-icons|emm|2.1.60
prettier-vscode|esb|5.7.2
vscode-docker|ms-|1.7.0
vscode-typescript-tslint-plugin|ms-|1.2.3
wordcount|ms-|0.1.0
vscode-yaml|red|0.12.0
code-spell-checker|str|1.9.4
vscode-todo-highlight|way|1.0.4
local-history|xyz|1.8.1


</details>

**Comment by eyalroth** [comment]
@deepak1556 Could you reopen the issue please?

**Comment by eyalroth** [comment]
@deepak1556 This is still an issue, please reopen.

**Comment by ChadMcCaffery** [comment]
I'm unsure if it's completely relevant to this issue, but I noticed VS Code (or is it Electron?) attempts to use GPU even when `"disable-hardware-acceleration": true` in argv.json:

https://user-images.githubusercontent.com/22089594/143790715-bacf34e3-ce6f-4345-bccb-2532170046dc.mp4

**Comment by seawalk24** [comment]
> I'm unsure if it's completely relevant to this issue, but I noticed VS Code (or is it Electron?) attempts to use GPU even when `"disable-hardware-acceleration": true` in argv.json:
> 
>  vscode-still-using-gpu.mp4

Thank you for sharing the video. What you are describing is exactly what the issue is here. 

CC: @deepak1556

**Comment by deepak1556** [comment]
@ChadMcCaffery the gpu process will be launched even when hardware acceleration is disabled, the name is bit misleading but this process is also responsible for software rasterization. The right way to check if hardware acceleration is used should be via loading `chrome://gpu` in the application. I will make that page available so that the issue can be clarified further.

Side note: @ChadMcCaffery the gpu process failing to launch in your case is a side effect of trying to open the application as an administrator. Due to the nature of sandbox profiles applied to the different processes in the application, you should launch the application as non-elevated to have a stable experience.

**Comment by ChadMcCaffery** [comment]
Thank you for the explanation. I learned something today! 😄
