### ISSUE TITLE
Changing publisher name could break extension dependency chain

### ISSUE THREAD

**Issue by Thaina** [microsoft/vscode#92632]
- VSCode Version: all
- OS Version: all

Steps to Reproduce:

1. Have an extension that was dependency of another extension
2. Install the child extension
3. Changing publisher name of parent extension
4. Open vscode

This is url to the issue : https://github.com/OmniSharp/omnisharp-vscode/issues/3628

Should we have a better way we could handle extension dependency? Any extension that rely on another extension could always broken this way

**Comment by Thaina** [comment]
@aeschli What info I should provide?

**Comment by alexdima** [comment]
AFAICT changing the publisher name is something that can be done in the marketplace, but I don't believe we have any support for that in VS Code.

I think this could be supported if VS Code were to fetch the list of all renames from the marketplace and dynamically rewrite extension dependencies.

In the meantime, since VS Code is built to always update all extensions all the time, the current way is to coordinate with others and release new extensions at the same time for the exceptional case of a publisher rename. Otherwise, this could be staged by shipping without the extension dependency, and checking for both old and new name in code via the `vscode.extensions` API.

FYI @sandy081
