### ISSUE TITLE
Terminal shell path when upgrading from ps7 preview to GA

### ISSUE THREAD

**Issue by guicane** [microsoft/vscode#92642]
Terminal Shell Path crashes after upgrading from PowerShell 7 Preview to GA. Path in settings.json doesn't get changed to reflect the new path.
![image](https://user-images.githubusercontent.com/13142345/76620203-8e5e6380-6524-11ea-9ae6-3ef2ac4d74f1.png)

- VSCode Version: 1.43.0
- OS Version: WindowsNT x64 10.0.18363

Steps to Reproduce:

1. Upgrade from Powershell 7 preview (RC3) to GA
2. Start VSCode and terminal won't load as still looks for the preview path.
![image](https://user-images.githubusercontent.com/13142345/76620231-9ae2bc00-6524-11ea-848b-c53a54cc5186.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by sunliangqin** [comment]
Instead of letting user specify/handcode shell path in setting, can we just detect all installed shells and let user decide which one to use? Windows Terminal allows me to do that and works well during the upgrade from PS6->PS7.

![image](https://user-images.githubusercontent.com/211268/76688040-7bac6300-65e6-11ea-99fd-bdd8c73537de.png)

**Comment by Tyriar** [comment]
You configured the preview explicitly so I don't think we should be touching it anyway.
