### ISSUE TITLE
Ctrl-K is not being passed to internal terminal

### ISSUE THREAD

**Issue by AlexMax** [microsoft/vscode#92656]
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:44:52.965Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.5.8-200.fc31.x86_64

I have tested this with and without extensions.

### Steps to reproduce

1. Open a terminal
2. Type some stuff in, then press Ctrl-A to go to the start of the line.
3. Press Ctrl-K

### Expected

Ctrl-K is passed to the terminal and the line is killed.

### Actual

Ctrl-K is intercepted by Visual Studio Code and waits for another modifier key to be pressed.

### Notes

Ctrl-K is a standard and incredibly common `readline` keybind, and is used by `bash` and `zsh` in a default configuration (or at the very least in a standard configuration).

**Comment by IllusionMH** [comment]
This behavior is controlled by `"terminal.integrated.allowChords"` you can set it to `false`.

An as said in description - chords like <kbd>Ctrl</kbd>+<kbd>K</kbd><kbd>S</kbd> won't work if terminal is in focus.

**Comment by AlexMax** [comment]
Ah, I wondered what the setting was, if there was one.

Honestly I"m not sure that the default behaviour is desirable.  Seems like use of readline keys would be common enough that the editor commandeering one of them is potentially problematic.  I'm not sure what the right play is here - though the fact that there's a setting for it is nice and adequately solves my immediate need.

Thanks for your help. :+1:

**Comment by senhalil** [comment]
I believe the default behaviour changed within these last few days and the previous behaviour was quite acceptable.

Before it was at least possible to repeat the combination to pass it to terminal (i.e., Ctrl+K Ctrl+K to cut the text inside terminal) but now, even though Ctrl+K Ctrl+K is still not defined it doesn't pass it to the terminal.

This makes using git commands inside vscode terminal quite problematic.

![Screenshot from 2020-03-16 11-42-47](https://user-images.githubusercontent.com/20163961/76748808-b1cf1b80-677b-11ea-88ff-817f2d3d5f9b.png)

**Comment by Tyriar** [comment]
Yes this default behavior changed and it also wasn't the easiest decision. The thinking being that those that expect chords to work everywhere I would expect to out weight users of the terminal who use ctrl+k inside the terminal. Defining the defaults within the terminal is tricky as terminal users expect it to act like a full blown terminal application, however it's hosted inside an editor which is also expected to work. That's why the `terminal.integrated.commandsToSkipShell` setting exists but that isn't good enough for chords.

Since I think this is the right way to go for the product as a whole and because this has been the only report of this problem since 1.43 went out I'm going to keep it as is. For anyone else hitting this issue just add this to your settings:

```
"terminal.integrated.allowChords": false
```

Also FYI there is another similar setting coming that is turned off by default (initially?) that will disabled _all_ alt keybindings such that the menu bar mnemonics work. See `terminal.integrated.allowMnemonics` in Insiders.
