### ISSUE TITLE
Add a way to keep the terminal maximized at all times?

### ISSUE THREAD

**Issue by ahmadawais** [microsoft/vscode#92650]
I use the terminal on the right side instead of the bottom. But recently I find myself using iTerm2 again since my brain feels more at home with full-width terminal usage.

Currently, there's no way to set the terminal width to be full at all times. What I mean by that is to be able to set this action `workbench.action.toggleMaximizedPanel` to something like `terminal.integrated.MaximizedPanel` to `true`. 

I tried to configure the keybindings in a way that will open the terminal with max-width but later hide it with the same key — and this causes VSCode to hang.

![](https://on.ahmda.ws/1ba204/c)

```json
{
		"key": "cmd+j",
		"command": "-workbench.action.togglePanel"
	},
	{
		"key": "cmd+j",
		"command": "workbench.action.closePanel",
		"when": "terminalFocus"
	},
	{
		"key": "cmd+j",
		"command": "workbench.action.toggleMaximizedPanel",
		"when": "!terminalFocus"
	},
```

Let me know if it's possible to do or please add this setting so that we can enjoy a full-width terminal experience that is toggle-able.

---

Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.6.0

**Comment by ahmadawais** [comment]
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.6.0

**Comment by Tyriar** [comment]
Hmm, the keybindings work fine on my macbook. Can you follow the instructions for mac crashes here? https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#macos

**Comment by jylin** [comment]
+1 for the feature in the title. It would be great to have any or all of these:

- A user setting to specify that new terminal windows should be maximized by default
- A default hotkey to open the terminal in maximized mode (rather than the small window)
- A new command that opens a full-page terminal in an "editor-like" mode. This could be similar to how the interactive preview for Python works, but instead of a preview, it's an interactive terminal (but instead of being docked at the bottom, it's a file tab).

**Comment by Tyriar** [comment]
The keybindings are meant to work, if the crash still occurs please reopen a new issue with info from following https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
