### ISSUE TITLE
Can't stop close current window action when there is a terminal window still running at version 1.43

### ISSUE THREAD

**Issue by weijuer** [microsoft/vscode#92676]
JUST look here 
step 1.
![image](https://user-images.githubusercontent.com/12313268/76597002-7b568e00-653a-11ea-8b35-c739008707a0.png)

step 2. when you click the close window button, there should be a warning dialog before next close action, but in this version, it close immediately，and then show me the warning dialog flashes.
![image](https://user-images.githubusercontent.com/12313268/76597271-02a40180-653b-11ea-87f9-37758d0cd3d1.png)

step 3.
end

**Comment by gregvanl** [comment]
Hi @weijuer What is the value of terminal.integrated.confirmOnExit? I believe this is false by default.

**Comment by Meyond** [comment]
Can't stop close current window action when there is a terminal window still running at version 1.43

 "terminal.integrated.confirmOnExit": true, 

版本: 1.43.0 (system setup)
提交: 78a4c91400152c0f27ba4d363eb56d2835f9903a
日期: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by Alex-K1m** [comment]
## Steps to reproduce

1. Set `"terminal.integrated.confirmOnExit": true`
2. Open vscode terminal
3. Exit vscode

## Expected behavior

Vscode doesn't close immediatly, instead it shows a popup window asking if you want to kill any active terminal sessions.

## Actual behavior

Vscode closes immediatly, the popup window flashes

![Recorded issue](https://i.imgur.com/HRSdQHl.gif)

## Additional information

* The issue first appeared after 1.43.0 update.
* Vscode is installed on Manjaro KDE through snap.
* The issue also appears on fresh vscode install without any extensions.

## System info

Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:52:11.516Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.19.112-1-MANJARO snap

CPUs  Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 2668)
GPU Status  2d_canvas: unavailable_software
flash_3d: disabled_software
flash_stage3d: disabled_software
flash_stage3d_baseline: disabled_software
gpu_compositing: disabled_software
multiple_raster_threads: enabled_on
oop_rasterization: disabled_off
protected_video_decode: disabled_off
rasterization: disabled_software
skia_renderer: disabled_off_ok
video_decode: disabled_software
viz_display_compositor: enabled_on
viz_hit_test_surface_layer: disabled_off_ok
webgl: unavailable_software
webgl2: unavailable_software
Load (avg)  1, 1, 1
Memory (System) 7.70GB (2.03GB free)
Process Argv  --force-user-env --no-sandbox --unity-launch --no-sandbox
Screen Reader no
VM  0%

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by Alex-K1m** [comment]
I can't reproduce it in 1.44 insiders build :tada:

**Comment by weijuer** [comment]
It is already fixed in 1.44
