### ISSUE TITLE
[themes] File Icon Theme not working

### ISSUE THREAD

**Issue by ajs11174** [microsoft/vscode#92695]
- VSCode Version: 1.44.0-insider
- OS Version: Windows_NT x64 10.0.18362

Description:
My file icons stopped working. It appears that the only two options which are operating correctly are "null" & "vs-seti". The "vs-minimal" and any custom icon extension options fail to populate any icons.

Steps to Reproduce:

1. Change Icon them to anything but vs-seti

Does this issue occur when all extensions are disabled?: Yes

Here is a recording of the icons not showing up:
![2020-03-14_13-06-31](https://user-images.githubusercontent.com/26338484/76686831-d1880780-65f4-11ea-93de-e67d7977563b.gif)

**Comment by aeschli** [comment]
I can't reproduce with Version: 1.44.0-insider 798481c7978af034b054e14ace4e471e7a83f665 2020-03-16T07:12:23.431Z

Can you use the developer tools and inspect the icon's path?

**Comment by ajs11174** [comment]
Here is the html which displays my tsconfig.app.json file in the file expolorer. 
```
<div class="monaco-list-row focused selected" role="treeitem" data-index="11" data-last-element="false" aria-setsize="14" aria-posinset="11" id="list_id_2_11" aria-label="tsconfig.app.json" aria-level="2" draggable="true" style="top: 242px; height: 22px; line-height: 22px;" aria-selected="true">
   <div class="monaco-tl-row">
      <div class="monaco-tl-indent" style="width: 8px;">
         <div class="indent-guide active" style="width: 8px"></div>
      </div>
      <div class="monaco-tl-twistie" style="padding-left: 16px;"></div>
      <div class="monaco-tl-contents">
         <div class="monaco-icon-label file-icon tsconfig.app.json-name-file-icon app.json-ext-file-icon json-ext-file-icon ext-file-icon jsonc-lang-file-icon explorer-item" title="/root/fba/fba-front-end/tsconfig.app.json" style="display: flex;">
            <div class="monaco-icon-label-container"><span class="monaco-icon-name-container"><a class="label-name"><span class="monaco-highlighted-label" title="/root/fba/fba-front-end/tsconfig.app.json"><span>tsconfig.app.json</span></span></a></span><span class="monaco-icon-description-container"></span></div>
         </div>
      </div>
   </div>
</div>
```

Here is the CSS related to the file icon. I can confirm that the file exists locally on my computer. However I'm not sure the content should be empty quotes. This is how it displays for every setting except the default seti logos. 
![image](https://user-images.githubusercontent.com/26338484/76761620-20a17a00-6766-11ea-99d0-9c5fc382a5f6.png)

**Comment by ajs11174** [comment]
I just rolled back to version 1.42 (January) and the icons appear to be working. When I upgrade to 1.43/1.44 the icons don't work. For now my temporary fix is to use the old version. Not sure what the issue is exactly but it appears to break after upgrading from 1.42.

![Code_2020-03-16_20-46-50](https://user-images.githubusercontent.com/26338484/76811692-e0271800-67c8-11ea-8e44-e806feea2c72.png)

**Comment by aeschli** [comment]
@pkief FYI

**Comment by PKief** [comment]
I can't reproduce it either. I tried it with the stable 1.43.0 and also with the 1.44.0-insider b7bfce30be3c30aa2c33fbe94fe82b81d4105668 2020-03-17T07:17:39.113Z and I can see that all icons packs are working fine. The only difference between the seti-icons and other icon packs like Material Icon Theme is that the seti icons are implemented as a [woff font](https://github.com/microsoft/vscode/blob/master/extensions/theme-seti/icons/seti.woff). Then the "content" is not empty:

<img src="https://user-images.githubusercontent.com/12248527/76896659-8ee35b00-6892-11ea-8af1-fd8de31d4704.png" width="200px" alt="CSS content rule for seti icons"/>

The Material Icon Theme and the vs-minimal icons are using SVG files which are not shown in your case. I'm not aware of any changes which affected the icon packs since version 1.42 (which seems to work for you) and versions 1.43 and 1.44 insider.

**Comment by aeschli** [comment]
Maybe the same problem as in https://github.com/microsoft/vscode/issues/92323?

Can you use the network tab on the developer tools and see if the svg icon is correctly loaded?
Check the response header like seen in https://github.com/microsoft/vscode/issues/92323#issuecomment-605063685
