### ISSUE TITLE
VS Code encoding with Myanmar Font

### ISSUE THREAD

**Issue by markkyaw** [microsoft/vscode#92700]
- VSCode Version: 1.43.0
- OS Version: macOS 10.15.3

Steps to Reproduce:

1. Type in any Burmese text
2. When displaying in browser, the text looks jumbled and messed up

Sample code
Note: Due to encoding, when I pasted my code from VS Code to browser, the browser display the text the way it should be (refer to screenshot for reference)

````
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>text1 မြန်မာပြည်</p>
    <p>text2 ျမန္မာျပည္ </p>
</body>
</html>
````
Text 1 will appear similar to text 2 in browser
Text 2 will appear normal (which is text 1)
Text 2 appear that way because the text is copied and pasted from online but encodes properly in browser

Code in vs code:
<img width="599" alt="Screen Shot 2020-03-14 at 2 50 42 PM" src="https://user-images.githubusercontent.com/30735477/76691014-34809b00-6603-11ea-9cb5-42417ace1245.png">

result:
![Screen Shot 2020-03-14 at 2 49 54 PM](https://user-images.githubusercontent.com/30735477/76691004-187cf980-6603-11ea-80c5-503d0bfefdd0.png)

I'm crrently using `UTF-8` encoding

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
@markkyaw Since I do not understand Burmese and I don't understand what you mean when you say that "when I pasted my code from VS Code to browser, the browser display the text the way it should be" I cannot use the sample text you have provided.

So I have used the following wikipedia page: https://my.wikipedia.org/wiki/%E1%80%99%E1%80%BC%E1%80%94%E1%80%BA%E1%80%99%E1%80%AC%E1%80%A1%E1%80%80%E1%80%B9%E1%80%81%E1%80%9B%E1%80%AC

I have selected the first paragraph from there:
```
မြန်မာအက္ခရာ
အ​ညွှန်း​သို့ ခုန်ကူးရန်ရှာဖွေရန် ခုန်ကူးမည်

မြန်မာအက္ခရာဖြစ်ပေါ်လာပုံ
မြန်မာအက္ခရာ သည် ဗြာဟ္မီအုပ်စုတွင် ပါဝင်ပြီး မြန်မာဘာသာ၊ မွန်ဘာသာ၊ ရှမ်းဘာသာ၊ စကောနှင့် ပွဲကရင်ဘာသာများ ရေးသားရာတွင် အသုံးပြုသည်။ မူလပထမ ရှေးမြန်မာအက္ခရာသည် ထောင့်ချွန်းနှင့် လေးထောင့် အက္ခရာတို့သာ ဖြစ်ကြသည်။ သရေခေတ္တရာပြည်နှင့် ရွှေဘိုနယ် ဟန်လင်းကြီးမြို့များ ကောင်းစားစဉ် အခါကာလတို့က ရေးသားသုံးစွဲကြသော အက္ခရာတို့မှာ ထောင့်ချွန်းပုံ အက္ခရာမျိုးများ ဖြစ်ကြ၍ ပုဂံခေတ်မှ အင်းဝခေတ်အထိတွင် ရေးသားကြသော အက္ခရာများမှာမူကား လေးထောင့်ပုံသဏ္ဌာန်များသာ ဖြစ်ကြလေသည်။ ကုန်းဘောင်ခေတ်သို့ ရောက်ရှိမှသာလျှင် အက္ခရာဝိုင်းဝန်းလာလေသည်။ အမရပူရ ပထမမြို့တည်နန်းတည် ဖြစ်တော်မူသော ဘိုးတော်မင်းတရားကြီး (၁၁၄၃-၁၁၈၁)၏ အမိန့်တော်ပြန်တမ်းတွင် "ငါ၏ ပိဋကတ်တော်များကို အက္ခရာစောက်ဖြင့် မသုံးရ။ အက္ခရာဝန်းဖြင့်သာ သုံးရမည်" ဟု ပါရှိသည်မှာ အက္ခရာဝန်းဝိုင်း လာခြင်း၏ ခိုင်မာသော အထောက်အထားပင် ဖြစ်သည်။

မြန်မာအက္ခရာကို ရေးသားရာတွင် ဘယ်မှ ညာသို့ ရေးသားသည်။
```

And have pasted that to a new untitled vs code editor. I have then compared how the rendering looks like and to my untrained eye, it looks correct:
![image](https://user-images.githubusercontent.com/5047891/77961049-8c90f000-72d9-11ea-8d30-4416161ccafd.png)

So I do not understand. What exactly is your problem? What clear steps should be taken to produce a problem?

**Comment by pkyaw** [comment]
Hmm however on my end, things look different.

I've screen captured and have posted here:
https://drive.google.com/file/d/17JxK0iye1x54yioqcOGeum7VwOfJ4NFY/view?usp=sharing

**Comment by alexdima** [comment]
@pkyaw Do you perhaps use some funny clipboard managing software that might try to do something with the clipboard? To eliminate a problem with the copy-paste itself, could you please try the following:
1. Save the following file locally to disk (do not use the clipboard)

[test-page.zip](https://github.com/microsoft/vscode/files/4423756/test-page.zip)

2. Unzip and open the HTML file in VS Code
3. Make a screenshot with the rendering of VS Code, including the encoding (that is shown in the status bar, be sure to open the file with UTF8 encoding).

Here is what I see:
![image](https://user-images.githubusercontent.com/5047891/78301570-931da280-7539-11ea-95cb-158cc815c5bb.png)

**Comment by markkyaw** [comment]
I have alt-c installed but I don't think that'll interfere with the copy and paste since alt-c sends what ihave in my clipboard to my other devices
![Screen Shot 2020-04-02 at 2 31 43 PM](https://user-images.githubusercontent.com/30735477/78301982-d1da3b00-74ee-11ea-9aac-ab30525a4965.png)

**Comment by alexdima** [comment]
I have now also tried on a mac:

![image](https://user-images.githubusercontent.com/5047891/78302636-74201000-753b-11ea-89bb-f9ece642e820.png)

Can you please try to disable all extensions and commenting out all your `settings.json`?

**Comment by markkyaw** [comment]
I have disabled all the extensions and commented out my `settings.json`

![Screen Shot 2020-04-02 at 2 46 12 PM](https://user-images.githubusercontent.com/30735477/78303064-d273d100-74f0-11ea-849a-135e153e4676.png)
![Screen Shot 2020-04-02 at 2 46 48 PM](https://user-images.githubusercontent.com/30735477/78303066-d30c6780-74f0-11ea-84f0-f7fa025a878f.png)

**Comment by alexdima** [comment]
Well, I have to say I don't understand what's wrong, since we have everything the same. I'm on `macOS 10.15.4`, I don't know if that makes a difference... I also don't know if there are some mac user specific settings that might influence things or if perhaps we have different fonts installed on the machine and that might contribute to the problem.

Could you please also try using the settings:
```
"editor.fontLigatures": true,
"editor.fontFamily": "Arial"
```

![image](https://user-images.githubusercontent.com/5047891/78303477-04128980-753d-11ea-81a7-f2363b274715.png)

**Comment by markkyaw** [comment]
Hmm it might be some fonts I've installed before. I'll check through that. Those settings didn't work either. I'll get back to this once I go through fonts I've installed before on my machine to make Burmese font readable (since it wasn't using unicode standard  couple years ago so my machine may be affected by it).
