### ISSUE TITLE
VSC prompting: "Save changes" but there are no any changes in files.

### ISSUE THREAD

**Issue by SzilviaR** [Microsoft/vscode#9279]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 6.1.7601

Steps to Reproduce:

1. Open a file 
2. Close the file
VSC prompting "Save changes". But I have not changed anything...

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by SzilviaR** [comment]
Thanks,it helped.
