### ISSUE TITLE
IntelliSense for React Markdown (*.mdx)

### ISSUE THREAD

**Issue by mlajtos** [microsoft/vscode#92805]
### What is MDX?
[React Markdown](https://mdxjs.com/) is an extension to Markdown which enables you to use:
- import/export statements
- JSX

Its primary use is in writing documentation for design systems, but people are adopting it for various other uses, e.g. writing templates inside [Gatsby](https://www.gatsbyjs.org/).

**Example:**
```mdx
import Highlight from "./Highlight";

# Top-level Heading

This is an *example* of using React component:
<Highlight>MDX</Highlight>

export const answer = 42;
```

### Current tooling
There is [vscode-mdx plugin](https://github.com/silvenon/vscode-mdx/issues/8) that support syntax highlighting and [Prettier](https://prettier.io/) supports formatting. The last missing piece of the puzzle is IntelliSense. There is [vscode-mdx#8](https://github.com/silvenon/vscode-mdx/issues/8) issue covering IntelliSense, but it seems dead without any traction.

### Motivation
Company I work for has large codebase in MDX, and maintaining it without type checking and code completion is a nightmare. It seems I will be spending time at home quarantine, so I'll have a lot of undivided attention to solve this problem.

### Prior experience
In past, I used Monaco on the web – I wrote custom syntax highlighting and worker for displaying warnings/errors. I know about a bit about LSP, but I guess it won't be necessary.

### Goal
**Goal is to have support for IntelliSense in MDX source files: code-completion, type-checking, code navigation, etc.** Is this goal achievable? Where should I start?

### Vague plan
I imagine this problem as hooking up JS/TS machinery to the right spots, but I guess it won't be as easy since nobody has done it yet. Using JS inside <script /> tag is something similar – code-completion is working. However, type-checking does not. Is there any technical limitation for this? Is dissecting HTML plugin a good start?

---

Thank you in advance for any suggestions.

**Comment by mjbvz** [comment]
Some potential starting points for an investigation:

- The html extension's JavaScript support: https://github.com/microsoft/vscode/blob/8f08c2ffa75e9ca53ac8ef67ff023feeb94fe5fc/extensions/html-language-features/server/src/modes/javascriptMode.ts#L1

- How the angular language service implements IntelliSense for angular templates (and for inline strings too I believe)

- How Vetur implements support for Vue templates: https://github.com/vuejs/vetur

In each case, you'll like need to use the [TypeScript language service](https://github.com/Microsoft/TypeScript/wiki/Using-the-Language-Service-API) in your extension. You will likely need to transform the code you feed into the language service so that TypeScript can understand, and then translate the result back so that VS Code displays the information correctly. I don't know a lot of about mdx, but I believe Vetur your best reference here.

Needless to say, you are correct in assuming this is going to be complex (especially if you want intellisense to work across files). Reusing existing services like the TypeScript language service will save you some time, but you will also need to hack these services so that they can deal with mdx in the first place and that's not going to be easy 

Let me know if you have any specific questions about this. Closing this issue for now since we generally try to keep the issue track to only bugs/feature requests
