### ISSUE TITLE
Debt - eliminate deprecated __ language configuration seetings

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#9281]
- Replace the deprecated configuration settings with the `language.configuration.json` file in our extensions.

- Make Pull Requests against the well known extensions that use the deprecated setting: PowerShell, Go, Python

- Document the language.configuration.json file in the extensibility reference.

**Comment by aeschli** [comment]
changes are in #9595

**Comment by aeschli** [comment]
Adoption instructions:
# __characterPairSupport
Instead of
```javascript
__characterPairSupport: {
	autoClosingPairs: [
		{ open: '{', close: '}' },
		{ open: '"', close: '"', notIn: ['string'] },
```
define your auto closing pairs in the language configuration file. The structure is the same:
```json
	"autoClosingPairs": [
		{ "open": "{", "close": "}" },
		{ "open": "\"", "close": "\"", "notIn": ["string"] },
```
# __electricCharacterSupport
Instead of
```javascript
__electricCharacterSupport: {
	docComment: { scope: 'comment.documentation', open: '/**', lineStart: ' * ', close: ' */' }
}
```
add the doc comment start and end symbols to the list of autoClosingPairs.
```json
	"autoClosingPairs": [
		{ "open": "/**", "close": " */", "notIn": ["string"] }
```
Note: if you want '*' in the middle of doc comments, use `onEnterRules` as shown here. https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/typescriptMain.ts#L171
