### ISSUE TITLE
Built-in extension integration tests from a specific build should not run out of sources

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#92843]
Related to https://github.com/microsoft/vscode/issues/92842

I think the git integration tests should run from a separate extension so that the test actually runs on the built in extension and not out of sources. Currently the tests will cause the built in one to be disabled.

**Comment by joaomoreno** [comment]
This is strange. What about [Markdown](https://github.com/microsoft/vscode/blob/a5ab6d665b940d83b7a4b0718b04cc1095e071ba/scripts/test-integration.bat#L52-L52) and [Emmet](https://github.com/microsoft/vscode/blob/a5ab6d665b940d83b7a4b0718b04cc1095e071ba/scripts/test-integration.bat#L55-L55)?

**Comment by bpasero** [comment]
Either:
* tests move into their own tests extension similar to our API tests
* or the git extension literally bundles its tests inside and test run out of there, though would need to be deleted before packaging

I think for normal extensions this is not a problem because they publish their VSIX to the marketplace which excludes tests. This is a problem with our built-in extensions that live inside VSCode. 

Agree that markdown and emmet fall into the same category, but not sure who owns that.

**Comment by joaomoreno** [comment]
Ideally, and I would close this issue in favor of this: we should just start pulling extensions away from the core, since we have a good built-in mechanism.

Since this wasn't an issue for Markdown and Emmet for such a long time... is it really an issue? That is, when do we really run integration tests against a specific build? Usually we run them out of sources or against a build we just built (during our official build).

**Comment by bpasero** [comment]
Yeah it's fine to close this issue, just be aware that your tests test the source variant of the git extension and not the packaged one that we ship.
