### ISSUE TITLE
F1 stopped working in Visual COde

### ISSUE THREAD

**Issue by CloudLassoUK** [Microsoft/vscode#9284]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
@CloudLassoUK like how, like what?

**Comment by CloudLassoUK** [comment]
Sorry.  When I press the F1 key I no longer get the box to type stuff into.  For example, I usually hit F1 and start typing 'change' in order to change the language of the editor.  That box no longer appears when I press F1 and I received an update to day I noticed.

**Comment by bpasero** [comment]
I am very sorry to hear you are having issues with VS Code. I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by CloudLassoUK** [comment]
Hi there -  I'm afraid this may have been a case of user error.  After rebooting my Surface I decided to press the combination CTRL-F1 and that worked.  I will close this comment in shame.  :)
