### ISSUE TITLE
Transfer focus to terminal window

### ISSUE THREAD

**Issue by DerekGogol** [microsoft/vscode#92874]
When the terminal's "Maximize Panel Size" (arrow up) is pressed, the input focus should be transferred to the terminal window. Currently, if the focus is in a tab window, it will be lost and additional click on the maximized terminal window is needed for it to gain input focus.

I use terminal with WSL and Ubuntu.

**Comment by ArturoDent** [comment]
Like https://www.github.com/microsoft/vscode/issues/80897, I agree the expectation when you maximize the terminal is that it gets focus.  Until the issue is resolved as a workaround you could create a macro that (1) maximized the panel and (2) focused the panel to do it in one keystroke (not via the icon though).

Or hit <kbd>Ctrl</kbd>+<kbd>backtick</kbd> if you don't mind two keystrokes.

And upvote https://www.github.com/microsoft/vscode/issues/80897
