### ISSUE TITLE
Hotkey "ctrl+alt+f"  of  "reveal file in explorer" can't open windows explorer, but file-tab right menu can open it.

### ISSUE THREAD

**Issue by gzx-miller** [microsoft/vscode#92893]
Issue Type: <b>Bug</b>

Hotkey "ctrl+alt+f"  of  "reveal file in explorer" can't open windows explorer, but file-tab right menu can open it.

VS Code version: Code 1.43.0 (78a4c91400152c0f27ba4d363eb56d2835f9903a, 2020-03-09T19:47:57.235Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (7.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|11.0.0
auto-close-tag|for|0.5.6
vue|jcb|0.1.5
svg|joc|1.1.5
react-node-desktop-debugger|rea|2.0.0
markdown-all-in-one|yzh|2.7.0
json|Zai|1.0.4

</details>

**Comment by ArturoDent** [comment]
I assume you rebound `Reveal in File Explorer`.  If you did so through the gui (rather than manually) note that it automatically creates this keybinding:

```
{
    "key": "ctrl+alt+f",
    "command": "revealFileInOS",
    "when": "!editorFocus"
 },
```

You may not have expected it to have that `when` clause - which means it will not work if you have an editor focused.  That rebinding works for me everywhere but when an editor is focused - as is the designed behaviour apparently.  

If you want it to work "everywhere", including when an editor is focused (which includes when its tab is focused) just delete the `when` clause.

**Comment by aeschli** [comment]
Thanks @ArturoDent !

@gzx-miller Please speak up if that didn't solve the problem.

**Comment by gzx-miller** [comment]
Very thanks to you. 
It's working!
But in new version, this way need edit "keybindings.json" file directly. 
UI only can edit the "key", can't edit the "when".
