### ISSUE TITLE
Change "expanded" icon in treeview from downwards-looking-arrow to left-top-corner

### ISSUE THREAD

**Issue by schlichtanders** [microsoft/vscode#92913]
Having the tight treeview layout is awesome for saving place. Here a supereasy but powerful change to make the tiny layout even more readable.

Currently the layout uses the downwards-looking-arrow if a section is expanded.
<img width="300" alt="Screenshot 2020-03-18 at 10 41 36" src="https://user-images.githubusercontent.com/4255480/76946931-1c5f9300-6905-11ea-964c-447f215a5fa0.png">

My suggestion with a left-top-corner icon looks like so
<img width="300" alt="Screenshot 2020-03-18 at 10 41 36 - newsuggestion" src="https://user-images.githubusercontent.com/4255480/76947306-b6bfd680-6905-11ea-9c26-81e96cf041e2.png">

At least for me, this so much better readable ;-)

VSCode version: 1.41.1

**Comment by aeschli** [comment]
product icons will be user customizable with https://github.com/microsoft/vscode/issues/92791

**Comment by schlichtanders** [comment]
thanks @aeschli 

nice to have this customaizable, but don't you think that would also be a good default?

One of the big advantages of vscode is that it comes with very good defaults, hence I be glad if we can reopen this ticket.

**Comment by aeschli** [comment]
Assigning to @misolori

**Comment by misolori** [comment]
Thanks for the suggestion. We used to use the angled tree icon:

![image](https://user-images.githubusercontent.com/35271042/76971712-c7168800-68ea-11ea-961a-1996cfb4b91f.png)

But I don't think I've ever seen an example like your screenshot shows. I would say that this still falls under product icon customization (see https://github.com/microsoft/vscode/issues/79130) as it comes down to personal preference since everyone has their own interpretation of what "good" means for icons. Will close this as duplicate.
