### ISSUE TITLE
Problem view icon and hint type

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#9300]
- VSCode Version: 1.3.1
- OS Version: OS X

Steps to Reproduce:

1. Use the spell extension on a doc
2. Configure to provide information items
3. Problem view is missing the icon for information
4. The unknowns are the hint diagnostic type

Status bar:
![image](https://cloud.githubusercontent.com/assets/1051190/16854859/abaec82a-49c7-11e6-8d61-3a21de9701cc.png)

Problems view:
![image](https://cloud.githubusercontent.com/assets/1051190/16854871/b777d14c-49c7-11e6-99e1-d0b08e8576f0.png)

**Comment by sandy081** [comment]
@stevencl Following is the icon currently given for info status

![screen shot 2016-07-15 at 9 57 34 am](https://cloud.githubusercontent.com/assets/10746682/16867525/947aada8-4a72-11e6-9e1c-ebb1849517f2.png)

Let me know if it is good to you, otherwise it would be great if you can provide me other

Thanks

**Comment by sandy081** [comment]
![screen shot 2016-07-15 at 9 59 11 am](https://cloud.githubusercontent.com/assets/10746682/16867563/cc6f1a00-4a72-11e6-9e67-540c46a873a8.png)
