### ISSUE TITLE
Syntax error when use some of ES6 features ... 

### ISSUE THREAD

**Issue by zerubeus** [Microsoft/vscode#9301]
- VSCode Version: 1.3
- OS Version: Windows 10

In the root Dir of my project I'm using the following jsconfig file : 

```
{
    "compilerOptions": {
        "target": "ES6",
        "module": "commonjs",
        "allowSyntheticDefaultImports": true
    },
    "exclude": [
        "dist",
        "node_modules"
    ]
}
```

But VS code still detect syntax errors in my Code ... any solution to fix this ? 

![loool](https://cloud.githubusercontent.com/assets/6376307/16855111/2c89a7de-4a14-11e6-98e3-ef0a72d0b038.JPG)

**Comment by rozzzly** [comment]
Typescript doesn't support object spread (yet), only spreading arrays. Apparently type inference gets pretty complex when you're merging multiple things. You can follow the issue here:
https://github.com/Microsoft/TypeScript/issues/2103

This is by far the feature I await most eagerly, it saddens me that this not getting more attention.

**Comment by dbaeumer** [comment]
See https://code.visualstudio.com/docs/languages/javascript#_disable-syntax-validation-when-using-non-es6-constructs for our recommendation how to work around this until TS/JS from the TS team supports object spread.
