### ISSUE TITLE
Smarter intellisense

### ISSUE THREAD

**Issue by csicky** [microsoft/vscode#93027]
I wish in this case the intellisense would know I work with an array and to show me the method `push`.
The reason why I think it should know is that the `if` is already checking that with `Array.isArray()`. 

![image](https://user-images.githubusercontent.com/3931907/77094332-fde8bd00-6a14-11ea-8c2f-2816e34faf88.png)

**Comment by mjbvz** [comment]
Please share a code example that demonstrates this issue (as text)

**Comment by csicky** [comment]
It's not an issue, it's just a wish.
```
if(Array.isArray(something)){
  something.pu //here the intellisense would recommend the push method because it is sure to be an array
}

**Comment by mjbvz** [comment]
That example works:

![Screen Shot 2020-03-19 at 2 23 57 PM](https://user-images.githubusercontent.com/12821956/77116364-50ae7e80-69ed-11ea-9939-d12d912f5761.png)

Can you share the example where it doesn't. I suspect it's because you have code that's more like:

```ts
const something = window.something.else;
if (Array.isArray(something.else)) {
  something.else
}
```

Which doesn't work because we don't know what type `something` is and `isArray` doesn't correctly narrow the type of dot accessed properties on an unknown type. You can work around this by extracting the value:

```ts
const something = window.something;
const el = something.else
if (Array.isArray(el)) {
  el.pu
}
```

![Screen Shot 2020-03-19 at 2 26 43 PM](https://user-images.githubusercontent.com/12821956/77116638-b3a01580-69ed-11ea-9984-63b42ee9aa37.png)

Or just making sure that `something` has typings using JSDocs

**Comment by csicky** [comment]
I really appreciate that you took the time and explained this. Thank you.
