### ISSUE TITLE
Semantic highlighting notification is not helpful

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#93058]
Every time I open a workspace and open a JS/TS file I get this prompt (that I subsequently have to deal with):

![image](https://user-images.githubusercontent.com/1487073/77126064-15b84500-6a05-11ea-805b-ac2c5ca1bacb.png)

I don't know why I'm being told this (how many people know what semantic highlighting even is?)  but now I have to click on `Learn More` or take an action, even though the message is telling me semantic highlighting is turned on because the theme has it enabled, which I had nothing to do with as a user.  

Even after reading the release notes, I still wonder "why are you telling me this?". It seems like a good thing. And, it is sort of a weird message ... It is like walking into a room and Alexa announcing "The light is on because the light switch is on".

**Comment by chrisdias** [comment]
and since there is a delay when the notification comes up, I get it at seemingly weird times, like after I start a debugging session!

![image](https://user-images.githubusercontent.com/1487073/77126856-c1629480-6a07-11ea-88bb-2259f7010a45.png)

**Comment by gjsjohnmurray** [comment]
I hope the messaging will go at least some way to counteract the number of issues folk have been opening since 1.43 landed, in which they're bamboozled by seeing their colours change a few seconds after opening a JS/TS file.

Maybe make the message read:

**Code colo(u)ring of '{fileName}' may have updated because the theme '{themeName}' has semantic highlighting enabled.**

And perhaps the phrase "semantic highlighting" could hyperlink to the same place as the "Learn More" button goes.

cc @aeschli

**Comment by aeschli** [comment]
I updated the message as @gjsjohnmurray suggested. (also added the link)
Also I made sure the notification only shows if the updated editor is the active editor.

**Comment by chrisdias** [comment]
LGTM
