### ISSUE TITLE
Allow extension developers to register background menu items

### ISSUE THREAD

**Issue by fuweichin** [microsoft/vscode#93078]
The issue:
Moving/renaming files in VSCode is quite common, and in most cases real projects are under source control like Git, but VSCode doesn't do `git mv` when moving/renaming files.

Thus running `git mv` is relatively inconvenient, here is a list of related issues talking about vscode-git integration

https://github.com/Microsoft/vscode/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3Agit+mv+rename+is%3Aclosed

Possible solution:
1. Allow extension developers to register background menu items, which appear on Shift + ContextMenu, in Resource Explorer, just like windows explorer background menu which can be defined in Windows Registry entry
  `HKEY_CLASSES_ROOT\Directory\Background\shell\cmd\command`
2. Then extension developers can register a background context menu "Git > Move", when the menu clicked, Open a FolderBrowserDialog, when a folder selected, check the folder path if ok run `git mv`

**Comment by KristjanTammekivi** [comment]
Most of the discussion on this is in https://github.com/microsoft/vscode/issues/31380 and the main explanation why not have it is because git mv would require staging the file, which would be an unexpected behaviour.

However I would disagree and say that if you have a project on git and you rename/move a file you expect it to be tracked in git as well. Just last week I moved a project from js to typescript and forgot about vscode's behaviour on this. The no-rename only came out as I submitted the PR.

I guess what I'm saying is at least make it a opt-in behaviour.

**Comment by fuweichin** [comment]
Sorry for my misleading issue title, it should be "Allow extension developers to register background menu items", and "adding git-mv context menu in resource explorer" is just a use case for extension developers and potential minority of users.

I do understand in some cases it may cause problems to add `git mv` context  menu, so I'm not asking VSCode to adding a built-in context menu item "Git > Move", also not to recommand extension developers registering a context menu, but to support background menu items for those who want to take risks for convenience, just like an Easter Egg.

**Comment by joaomoreno** [comment]
You can register menu items to both the Explorer context menu as well as SCM.
