### ISSUE TITLE
Previewing files in folder marks them as unsaved

### ISSUE THREAD

**Issue by pukhrajbal** [Microsoft/vscode#9308]
- VSCode Version: 1.3.1
- OS Version: Win 7

Steps to Reproduce:

1. Open a folder
2. Randomly select files to view their contents.
3. Files get marked as unsaved - even though nothing was changed. 

This leaves a trail of all opened files which are marked as unsaved. To close them you have to individually click the "Dont save" button on prompt.

**Comment by weinand** [comment]
@pukhrajbal  this sounds like an issue caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by pukhrajbal** [comment]
@weinand you are right - it was an extension. Found out EditorConfig for VS Code was causing it. https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig
