### ISSUE TITLE
Unwanted generated tsconfig.json file

### ISSUE THREAD

**Issue by jasonfma** [Microsoft/vscode#9324]
- VSCode Version: 1.3.1
- OS Version: macOS (10.11.5)

Steps to Reproduce:

1.  open terminal
2. cd to project dir
3. launch vscode with `code .` command
4. tsconfig.json file is automatically generated

Is there a way to stop this tsconfig file from being generated? My project is actually js and I have a proper jsconfig.json defined but the tsconfig.json is causing a bunch of syntax error highlighting.

**Comment by weinand** [comment]
@jasonfma this sounds like an issue caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: code --disable-extensions and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by jasonfma** [comment]
Yeah you're right. It's the react native extension. Thanks!
