### ISSUE TITLE
Why is there a sync CLI?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93262]
```
--sync <on> <off>                 Turn sync on or off
```

The CLI is already quite cluttered, under what circumstances would someone use this over the UI? Plus this would trigger a quick pick in the UI anyway?

**Comment by sandy081** [comment]
Related request - https://github.com/microsoft/vscode/issues/92516

**Comment by Tyriar** [comment]
@bpasero was just telling me about how we should be keeping CLI options to a bare minimum in https://github.com/microsoft/vscode/issues/93241#issuecomment-602716329, and this seems very niche.

**Comment by bpasero** [comment]
Yes, +1 for not having it. If this is for testing reasons, consider to at least hide it from the help output.

**Comment by sandy081** [comment]
This is not for testing reasons and it is as per user request here - #92516.

Another use case which also makes sense for this is that - if I want to start VS Code by disabling sync because if sync is on there is no way to start VS Code without triggering sync. By the time window comes up and I disable sync VS Code would have already started syncing. It is very similar to `--disable-extensions`.

@Tyriar I closed this in favour of original request and to continue discussion there.

**Comment by bpasero** [comment]
@sandy081 I understand the need but should it move under the troubleshoot section? this seems like a edge case to me.
