### ISSUE TITLE
Add commands to move tabs left and right in group

### ISSUE THREAD

**Issue by vogler** [Microsoft/vscode#9333]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:31:10.994Z)
- OS Version: Darwin x64 15.5.0

I was looking for a command to move an editor within a group, but `workbench.action.moveActiveEditor{Left,Right}` was deprecated (now there are only commands for moving groups).

**Comment by bpasero** [comment]
@vogler there is currently no command to move an editor to the left or right within a group. I assume you mean moving the tab left and right?

**Comment by vogler** [comment]
Yes.

On OS X it'd be nice to have these defaults:
- `shift+cmd+]` for `nextEditor` (OS-wide shortcut for tabs)
- `shift+alt+cmd+]` for `moveEditorRight` (like in iTerm)
- move `(un)fold` to `shift+ctrl+]` (default for Windows/Linux)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/8234 is related though that only talks about extensions API. In theory, once that is there we could assign keys to it.

However, I am having a hard time to justify for this command when tabs are disabled because then it does not make much sense to move the editor within the group unless maybe you look at the "opened editors" view.

**Comment by sandy081** [comment]
This is implemented in #8234
