### ISSUE TITLE
Bot proposal: do not add Feature Request issues automatically to backlog candidates

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93369]
1 minute after I add a feature request label to an issue that has no milestone the bot automatically comes and adds it to the backlog candidates.
This was initialy motivated by making vscode engineers do the least possible amount of work and not to have to explicitly add an issue to the backlog candidates milestone.
However I think this back fired  and we should remove this feature.
I personaly hate it with a passion <3

fyi @jrieken

**Comment by jrieken** [comment]
Yeah - this awkwardly turned out to be stress riser for me - I mean the whole backlog candidate thing stresses me because even for external feature requests I am forced to make a decision when I see it because it might vanish otherwise. Anyways, I have a workaround in place since I want to avoid having this discussion again.

**Comment by JacksonKearl** [comment]
Going to close this out as it hasn't gotten much traction with other team members (I think if I were to make this change, we'd quickly have people asking for it to be the old way...)

**Comment by isidorn** [comment]
That's fair. Thank's for considering this.
