### ISSUE TITLE
URI comparisons and resources.ts

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93368]
This is the continuation of: https://github.com/microsoft/vscode/commit/7d4cd4a30b3b48406f742cead944db6470e11a14#r37940098. 

*Background*: We can classify uris into two categories

1. Those that have posix-paths, like `file:///foo/bar.bazz` or `vscode-remote://bing+bong/boo/far/fazz`, and
2. those with paths without special/known semantics, like `untitled:unitiled-1` or `command:deleteLeft`

Uris of both categories exist in our system, generally uris that represent files are posix style, e.g all file-uris and all [uris from contributed file systems](https://github.com/microsoft/vscode/blob/d778f85cd5f23391cf94fa0965ada594c68e1fc5/src/vs/vscode.d.ts#L6075-L6076). However, uris for virtual documents, command uris, and others don't fall into this category. 

The `URI` class knows a little about this and for instance [enforces](https://github.com/microsoft/vscode/blob/ea2c961eaa738becaacc846ade82f18c96540dc6/src/vs/base/common/uri.ts#L57) that posix style uri paths start with a slash, e.g `URI.parse('file:foo').toString() === 'file:///foo'` whereas that "fixing" doesn't happen for arbitrary schemes (only file, http, https and arguably we should add vscode-remote here)

Now, the following problems exist: 

1. We have the `resources.ts`-utility which offers many convenience functions when working with uris, e.g ways to compare them. **But** these utilities are all written with the assumption that it works on uris with posix-paths, e.g it states that `command:/deleteLeft` equals `command:deleteLeft` (which breaks compatibility with `uri.toString`-usages). To make the confusion perfect it doesn't check, enforce, nor document that it work only works on a subset of uris, e.g. blind adoptions like these https://github.com/microsoft/vscode/commit/dc0ab500359c019bab5fd6bc266a8113bb0bbd53 made a perfect mess
2. We have alternative, also fishy, ways to compare uris of which I know [`ResourceMap<T>`](https://github.com/microsoft/vscode/blob/93cbbc5cae50e9f5f5046343c751b6d010468200/src/vs/base/common/map.ts#L434) and the widespread use of `map.set(uri.toString(), 42)`

I think we need to first decide if

1. the `resources.ts` utility should only work on uris with posix-paths. That means we need at least documentation, better enforcement, and we need to review or revert @mjbvz's "adoption". 
1. alternatively we make the `resources.ts` utility be fit for all uris, esp with respect to uri comparisons. That means we need to know when posix rules apply and when not.

I am strongly suggesting to use variant 2 because anything else will be confusing. 

As a next step we need to use the same URI-equivalence checks, e.g it's bad that the renderer uses a different identity for documents then the extension host. The `ResourcesMap<T>` also uses a different identity than for instance users of `getComparisonKey`. We should align that and ideally have them all root `getComparsionKey` and/or `isEqual`. So, this is what I think needs to be done

* [ ] use `getComparisonKey` in `ResourceMap<T>` @bpasero 
* [ ] use `ResourceMap` whenever storing something by URI 
* [x] use the same logic in `TernarySearchTree@forPaths` which actually is `forUris` @jrieken 
* [ ] define what makes uris equal, e.g. scheme, authority are case insensitive, path is case sensitive or not (depends on the OS, scheme), query is case sensitive, fragment is ignored. Also don't massage paths during compare but during creation of uris. @aeschli

**Comment by bpasero** [comment]
I guess to really see the extend of usage we need to hunt down every single call to `URI.toString()`, possibly even path and `fsPath` to catch cases where `ResourceMap` should be used instead.

Changing to use the `getComparisonKey` seems easy, but we should maybe do this in debt week?

Q: the JSDoc of `getComparisonKey` says: `URI queries are included, fragments are ignored`, but it seems to return a `URI` without `query` (`resource.with({ authority: resource.authority.toLowerCase(), path: path, fragment: null })`)?

**Comment by jrieken** [comment]
Yes - debt week. And careful changes

No - `with` keeps everything as-is when omitted, e.g `URI.parse('http://google.com/?q=foo').with({ path: 'bar', authority: 'bing'}).toString() === 'http://bing/bar?q=foo'`

**Comment by bpasero** [comment]
Oh yeah, got it.

**Comment by jrieken** [comment]
@aeschli and I were wondering why all those comparisons and on-the-fly normalisations are done at all. My assumption has always been that we normalise when "uris enter the system", e.g when you call open editor for `file:///c:/LOWER.txt` and there is already `file:///c:/lower.txt` we return that instead. @bpasero you might know more about this?

**Comment by bpasero** [comment]
@jrieken @aeschli I remember I suggested that as a possible cheap solution in 2017 to https://github.com/microsoft/vscode/issues/12448 by simply letting all my file editor world use case-insensitive comparators and got push back from a couple of people in the team so I reverted this again (see https://github.com/microsoft/vscode/issues/12448#issuecomment-288079711). See also https://github.com/microsoft/vscode/issues/12448#issuecomment-508526893 for a more recent reply I did on that matter.

One of the scenarios that break once we go down this path is:
* you open a file on the "correct" path
* an extension produces markers for the same file but "incorrect" path
* you click on a marker from the problems view
* we show the file as opened on the "correct" path
* the editor does NOT show any markers because they will only appear if the resource matches (assuming that the editor is comparing URIs by strict equalness)

**Comment by jrieken** [comment]
> we show the file as opened on the "correct" path

Is that "make correct" logic re-usable? We could just apply it to markers as well

**Comment by bpasero** [comment]
Well that was basically using `ResourceMap` or similar helpers that will lowercase the key on Windows and macOS. It boils down to using these helpers in all places for comparing URIs I guess. But we will not fix issues such as links or aliases for paths.

**Comment by jrieken** [comment]
Oh, so the "make correct" logic doesn't exist and today two editors would open, right?

**Comment by bpasero** [comment]
@jrieken that's right, and one of the reasons for that is this line:

https://github.com/microsoft/vscode/blob/756849af07555b1e8b76883319414a300a59c4ed/src/vs/workbench/contrib/files/common/editors/fileEditorInput.ts#L310

On top of that, the place where all text file models are stored is using `ResourceMap` ([here](https://github.com/microsoft/vscode/blob/756849af07555b1e8b76883319414a300a59c4ed/src/vs/workbench/services/textfile/common/textFileEditorModelManager.ts#L53)) and would also need to be aware of path casing (as any other place that uses `ResourceMap` probably).

As I said before, any place where we compare URIs (using `toString` or `fsPath`) needs to go through some utility for comparison that would take the case sensitivity into account. Best would be some method in `IFileService` or a service on top that would know exactly what the file system provider supports. Unfortunately in many cases we may not have access to services in some places where we compare today.

**Comment by aeschli** [comment]
> Best would be some method in IFileService or a service on top that would know exactly what the file system provider supports.

I think that's the right direction. `IFileSystemProviders` should offer resource APIs related to comparison and resolving (resolve, join, normalize) resource URIs. The `IFileService` would offer the same APIs and forward to the right `IFileSystemProvider`.
We'll have to migrate resources-API users towards it, which will be a lot of work and cause a lot of ripples, but we should prioritize the places where it matters the most (explorer, models, editors).

**Comment by jrieken** [comment]
>or a service on top that would know exactly what the file system provider supports.

I like that a lot. I would opt for a dedicated service, like the `IUriTruthService` or so. The good news wrt `IFileSystemProvider` is that we spec'd that they must use posix logic and that they already declare if they are case-sensitive or not. So, we can just use the their information but don't need to delegate to them. 

I think an important piece is that such a service is non-destructive. I mean the first occurrence of a path, e.g. `file:///c:/LOWER.txt`, defines it and subsequent case-variants should use the first occurrence. Sample: the editor is already called `LOWER.txt` and therefore the markers panel should also use that name. 

> which will be a lot of work and cause a lot of ripples, but we should prioritize the places where it matters the most (explorer, models, editors).

I am more optimistic and I'd say the opening editors, text models, and markers are 90% here

**Comment by aeschli** [comment]
IMO we should not just tackle the resource equality, but also the operations (join/normalize/..). There we need to know about fs roots, rules for normalizing separators (ok to remove trailing/duplicates, which ones are required), what to do with queries and fragments.
Give that `IFileSystemProvider` can come from remote, always going over the wire to ask a `IFileSystemProvider` to compare/manipulate a URI might not be a good idea. So maybe we need to simplify this and come up with some classes of file systems: case insensitive: yes/now, drive letter/UNC support: yes/no, posix path normalization: yes /no, keep queries, keep fragments...

**Comment by bpasero** [comment]
> I think that's the right direction. IFileSystemProviders should offer resource APIs related to comparison and resolving (resolve, join, normalize) resource URIs. The IFileService would offer the same APIs and forward to the right IFileSystemProvider.

I am not sure that is needed on the level of the provider, I think the provider should declare its behaviour in some format (like we declare the label format) and then some service can take that and work with that information. I think I would prefer a `IURIService` over adding methods to `IFileService` to keep things separate.

> So, we can just use the their information but don't need to delegate to them.

Yes

> I think an important piece is that such a service is non-destructive. I mean the first occurrence of a path, e.g. file:///c:/LOWER.txt, defines it and subsequent case-variants should use the first occurrence. Sample: the editor is already called LOWER.txt and therefore the markers panel should also use that name.

Not sure we can get that to work well across processes. We could end up with different forms in different processes unless we had a central authority for URIs, which of course would mean things have to be async.

> Give that IFileSystemProvider can come from remote, always going over the wire to ask a IFileSystemProvider to compare/manipulate a URI might not be a good idea. So maybe we need to simplify this and come up with some classes of file systems: case insensitive: yes/now, drive letter/UNC support: yes/no, posix path normalization: yes /no, keep queries, keep fragments...

Yes, definitely needs to be sync. Challenge though is that resolving the remote is async and as such you could not properly construct or compare URIs until the remote is resolved. 

Btw we do have a `IPathService` (formerly `IRemotePathService`) that is already there to deal with some aspects of remote file systems and environments. We could probably take some inspiration from that service.

**Comment by jrieken** [comment]
> So maybe we need to simplify this and come up with some classes of file systems: case insensitive: yes/now, drive letter/UNC support: yes/no, posix path normalization: yes /no, keep queries, keep fragments...

Ok, now you are mixing things here. There is query, fragment, and path. When I say posix-path, it means that normalization is always the same, no need to ask a provider because that's part of the spec/API.  Query and fragments are orthogonal parts of uris, there is no normalization for them and we should treat them simple as opaque things and not touch them, e.g ignore them.

**Comment by jrieken** [comment]
@aeschli turns out the different behaviour in uri-equality came in only last year via https://github.com/microsoft/vscode/commit/37efd5cc323418b47133d8b9c229b3bc4140ecb3 - no issue linked, no reasoning why this was done. Given that we want to revisit cell uris (going back to fragments) I am planning make fragment-component part of equality again.

**Comment by aeschli** [comment]
http://www.textuality.com/tag/uri-comp-3.html concludes that because the [URI spec](https://tools.ietf.org/html/rfc2396#section-4.1) defines that fragments are not part of the URI, they should also not be used for comparison. 

My feeling is that fragments should not be part of document URIs, or URIs returned by file system providers. I think we should spec that. Assuming that this never reliably worked (e.g. because of https://github.com/microsoft/vscode/commit/37efd5cc323418b47133d8b9c229b3bc4140ecb3) , I also think that's not a breaking change.

But if you want to make the change, please do so.

**Comment by jrieken** [comment]
> http://www.textuality.com/tag/uri-comp-3.html concludes that because the URI spec defines that fragments are not part of the URI, they should also not be used for comparison.

We (admittedly arbitrary) picked [rfc3986](https://tools.ietf.org/html/rfc3986) which defines  [Syntax-Based Normalization](https://tools.ietf.org/html/rfc3986#section-6.2.2) in the domain of comparing uris and there it says (6.2.3) 

>The fragment component is not subject to any scheme-based normalization; thus, two URIs that   differ only by the suffix "#" are considered different regardless of the scheme.

However, when two uris differ only in their fragments then both are considered to reference the [same document](https://tools.ietf.org/html/rfc3986#section-4.4). 

> When a URI reference refers to a URI that is, aside from its fragment component (if any), identical to the base URI (Section 5.1), that reference is called a "same-document" reference.

A simple sample is are `file:///Users/jrieken/Code/_samples/devfest/94173/a.ts#L3` and 
`file:///Users/jrieken/Code/_samples/devfest/94173/a.ts#L6` which are different but reference the same file. 

What I am trying to save that it isn't that simple as todays [`isEqual`](https://github.com/microsoft/vscode/blob/960205b8a06e3fdc283b9a476952620041cba84a/src/vs/base/common/resources.ts#L70) suggests. Sometimes the fragment matters, sometimes not. We need to find the places in which it matters, like retrieving a file from disk vs knowing what line to reveal.


> My feeling is that fragments should not be part of document URIs, or URIs returned by file system providers. I think we should spec that.

There is two cases

1. _text document content providers_: I am afraid the trains has already left the station (see https://github.com/microsoft/vscode/issues/87332) Also, fragments are our favoured approach for notebook cells in the spirit of ["_The fragment identifier component of a URI allows indirect  identification of a secondary resource by reference to a primary  resource_"](https://tools.ietf.org/html/rfc3986#section-3.5)
1. _file system providers_: File system provider do not return uris, it is always us creating uris from names they return. That puts us into a way better position but fragments still make sense, e.g we also want to support `foo-scheme:///some/file.txt#L80` to reveal line 80 in `file.txt`, but it doesn't mean that we need to pass the fragment to the file system (which would be a behavioural change)

> But if you want to make the change, please do so.

I will, but not to make a decision about honour vs ignore fragment but to get back to a uniform state. Today, users of `isEqual` (211 references) or `getComparisonKey` (11 references) have different behaviour than users of `ResourceMap#set/get` (~2000 references) or users of `toString` and that's what concerns me most

**Comment by bpasero** [comment]
After doing a quick pass over clients of `ITextModelResolverService#createModelReference` I am no longer sure we can actually do this change. The somewhat breaking change is that the URI passed in to create a model may no longer match the URI of the model. While this is probably easy to adopt internally (via `IURIIdentitiyService`), this also has an impact on extensions.

**Impact on VSCode**

Everyone will have to use the `IURIIdentitiyService` for comparing `URIs` which ignores casing on file systems that signal this. I do not think that `URI.toString() === URI.toString()` will be possible with canonical `URIs` going forward because you never know if a `URI` is canonical or not.

A couple of examples:
* `mainThreadDocuments#$tryOpenDocument()` passes in a `URI` but later checks some maps for the model being synced on that `URI`, which may not be the case if a different `URI` was used. This leaks on into extensions (see below)
* we often have code such as `IModelService#getModel()` before calling into the text model resolver to prevent work. This will not work anymore for `URIs` with different casing. Might not be as bad, but worth noting.
* `CustomTextEditorModel` (the one for custom text based editors) keeps a `URI` in its own model and then resolves the text editor model with a potential different URI. This may break assumptions
* similar checks with `URI.toString()` in `[dirtyDiffDecorator`](https://github.com/microsoft/vscode/blob/fb3dc8be662b22054148544a6ccd4e5e2af52531/src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts#L1119)

**Impact on Extensions**
Unfortunately we might break an arbitrary number of extensions with this change, because a text document that was opened with certain `URI`, might no longer have that exact same `URI` associated when it comes back. We do not know how extensions use the document `URI` and if they are ready to deal with case differences.

**PS:** I have not yet checked the impact on editors. Given no-one is directly instantiating `FileEditorInput` but just passing in a `URI` as literal object, I am a little bit more optimistic because typically opening editors does not result in dealing with models.

**Comment by jrieken** [comment]
> The somewhat breaking change is that the URI passed in to create a model may no longer match the URI of the model.

As said before - the chance of this happening is very low because uris for virtual documents are usually not constructed by path math, like join, but they are fed into the system as-is. They truly serve as identifier and I am not afraid a chance there. On the other side, this also means that those places likely don't cause any trouble and we can defer or skip the adoption all together. 

> Unfortunately we might break an arbitrary number of extensions with this change, because a text document that was opened with certain URI

Very much aware of this and I think that's the consequence of fixing this bug. We shouldn't allow extensions to re-introduce this. There are two ways of implementing this (when extensions use a different uri):

1. open the document internally and tell the extension that the document could not be opened (as today)
1. open the document internally and return it and make extension aware of this new behaviour via release notes etc

**Comment by bpasero** [comment]
Just to clarify, code like this today:

```ts
const doc1 = await vscode.workspace.openTextDocument(vscode.Uri.file('/Users/bpasero/Desktop/test-ts/src/extension.ts'));
const doc2 = await vscode.workspace.openTextDocument(vscode.Uri.file('/Users/bpasero/Desktop/test-ts/src/Extension.ts'));
```

Will result in 2 distinct documents being created with different URIs, even though the underlying file is the same. We do not throw in this case. In the future, I think we would return the same document, given we use the canonical form of the URI.

**Comment by jrieken** [comment]
> I do not think throwing an error would be an option to be honest.

That's at least something that extensions must already handle today. But yeah, I think, the better approach is to return the "actual" document despite having a different uri.

**Comment by bpasero** [comment]
Given our code freeze tomorrow, I wonder if we should delay this to debt week just to get most coverage out of it in insiders?

**Comment by jrieken** [comment]
> Given our code freeze tomorrow, I wonder if we should delay this to next debt week just to get most coverage out of it in insiders?

I would make the change now and decide at end of endgame if we ship it or not. Next week is the week where people have critical testing eyes, during debt week there is no insiders build and people are usually busy with their own stuff. 

> One thing that still worries me is that a bad-behaving extension can cause the workbench to use URIs that do not match our truth

Yeah, that can happen. I think it's still better than the current situation. We can also mitigate this by letting the explorer define canonical uris. The "real" fix is obviously a long running retrieval of the actual file name - which I think is quite problematic as well

**Comment by bpasero** [comment]
The editor service change is in https://github.com/microsoft/vscode/pull/98795 but as I said, I would think we need to merge the adoption for text model resolvers as well.

**Comment by bpasero** [comment]
@jrieken please take a look at https://github.com/microsoft/vscode/issues/98861 for testing, I tried to be verbose so that people understand the impact.

**Comment by bpasero** [comment]
Already found a first somewhat regression: renaming a file to same name but different case no longer reflects in the editor:

![recording](https://user-images.githubusercontent.com/900690/83324203-e96e3f80-a263-11ea-99f2-3d2ac9fe2723.gif)

Arguably this is the same issue you will get if an extension introduces a "wrong" case canonical URI and you click on the file in the explorer.

**Comment by jrieken** [comment]
> renaming a file to same name but different case no longer reflects in the editor:

That's a good find. We should maybe not use the canonical uri for display purposes or find a way to re-set a canonical uris, tho that would mean we change the uri of a text model, right?

**Comment by bpasero** [comment]
@jrieken ideally we go with a solution that does not involve touching the model. I actually prefer the way it is now because reusing the same model has a lot of advantages (undo/redo, view state, etc).

I think it would be relatively easy to do this for editors, but we may have many places in our system where we derive a label simply from its `URI` and nothing else. In those cases we have lost the information about the original `URI` potentially.

**Comment by bpasero** [comment]
Listing a few things that I think should happen in June that I noticed while adopting the URI identity. I can open separate issues but we can also leave it here.

### `ITextModelResolverService` using canonical resources
I think we just did not do this yet, but should do it early in June. I had to add some code to the editor service that makes it NOT use canonical URIs in case it gets a request to open a URI for which a model exists:

https://github.com/microsoft/vscode/blob/f4287e67a668402558fd8f7de7dc5662cf919b1e/src/vs/workbench/services/editor/browser/editorService.ts#L946-L952

There is just a lot of paths where a URI might end up to create a model, even beyond the `openTextDocument` API. E.g. if you do "Peek Definition" we open an embedded editor with a URI that I think we get from extensions. If you start to edit that document inside, we would not be able to open it if it is opened with another casing.

### Drop our biased checks or replace with `IURIIdentityService`
I think that our biased checks for `isEqual` and friends are very dangerous because I think the default we assume is not good for remote scenarios. The `vscode-remote` scheme will in 99% of the cases be Linux (e.g. WSL), but we ignore casing for any non-file-scheme. At the very minimum we should add a check for `vscode-remote` and maybe handle that specially. For example, after we resolved the remote agent, we know exactly what target OS we are dealing with and could then do the correct thing.

Nevertheless, adopting `IURIIdentityService` would solve this better.

### `ResourceMap` aware of file system capabilities
I am having at least one case (write queue in file service) where I would benefit from a `ResourceMap` that is aware of a filesystems case sensitivity. It would be great to have a utility that would provide this.

**Comment by jrieken** [comment]
> ITextModelResolverService using canonical resources

Makes sense, but lets do it "careful"

> Drop our biased checks or replace with IURIIdentityService

Yeah, my plan is to drop `exturiBiasedIgnorePathCase` and use `extUri` for the exports, like `isEqual` etc. Once we have adopted canonical uris in enough places we should be safe to make this change

> ResourceMap aware of file system capabilities

Agreed - we should have an overload constructor that allows to pass in a "get-key" function or a comparator (assuming we trust the SkipList)

**Comment by bpasero** [comment]
One thing I should maybe look into is to decouple the `URI` usage in editors for label purpose and add explicit labels that file editors use.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/commit/6a0b3594499122aa48468d9bff94b4229593beb2 adds support for passing in a `URI` as label for file inputs that should be used. This allows to rename files in the explorer and seeing the label get updated even though the underlying resource is still the same.

**Comment by jrieken** [comment]
@bpasero fyi - I have pushed a change that allows to use the `ResourceMap` with a custom toKey-function. The correct one to use can be retrieved from `IUriIdentityService#extUri`.

**Comment by jrieken** [comment]
Done!

The default uri identity utils are now unbiased and compatible with toString-usage. There is still two biased utils which 1 or 2 users only and (hopefully) very clear comments. Last, there is IUriIdentityService for the "truth" and that's adopted in the critical places. Closing

**Comment by sandy081** [comment]
Removed one usage of biased util in `fileUserDataProvider` with `extUri` created using the provider's capabilities.
