### ISSUE TITLE
editor.action.commentLine doesn't comment the uncomment part and uncomment the comment part when the selection content contains both of them

### ISSUE THREAD

**Issue by vincy261** [microsoft/vscode#93374]
- VSCode Version: 1.43
- OS Version: macOS 10.15.3

Steps to Reproduce:

1. use editor.action.commentLine shortcut selecting two lines, one commented and one not

```
1 console.log()
2 // console.log()
```
 in the previous versions of VS Code (don't know which precisely) it was working as a toggle
comment the uncomment part and uncomment the comment part when the selection content contains both of them, now it only comment both adding a plus // to line 2.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
Confirmed for cases where the cursor is on the line without any selection

![Screen Shot 2020-03-25 at 12 21 58 PM](https://user-images.githubusercontent.com/12821956/77576974-47149300-6e93-11ea-9026-644ed1826125.png)


Produces:

```
// console.log()
console.log()
```

**Comment by alexdima** [comment]
@vincy261 

> in the previous versions of VS Code (don't know which precisely) it was working as a toggle
comment the uncomment part and uncomment the comment part when the selection content contains both of them,

That is not correct. It never functioned like that. The toggle line comment always does a first pass, and then decides if it adds comments or removes comments. It will remove comments if all selected lines begin with the comment token.


@mjbvz 

That is as designed and works like that since the beginning. It has been optimized to work well with selecting by clicking on the line numbers (which includes the trailing EOL sequence).
