### ISSUE TITLE
AuthProvider not available when called from a resolver

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#93377]
Background: VS Code Remote Containers support to open a PR into a container. To do so, the extension needs to fetch the PR meta info from Github. 

This is done as part of resolving a remote URL. This is a special state of the extension host where not all contribution points are resolved yet. For this reason an implementor of a contribution needs to do some additional measures to make contribution point work in this state.

Here is the problem. The following code works find when invoked from an extension, e.g., during activation. However, the code fails when invoked from a resolver during a resolve call:
```ts
	let scope = ['repo'];
	let result = await vscode.authentication.getSessions('github', scope);
	if (result.length) {
		return await result[0].getAccessToken();
	}
	let auth = await vscode.authentication.login('github', scope);
	return await auth.getAccessToken();
```

Running the code from the resolver results in a reject with the error 'no GitHub provider' registered. This indicates that the contribution point is not ready yet.

I'm CCing @sandy081 he has addressed this issue before and can provide further guidance.

**Comment by sandy081** [comment]
@RMacfarlane As mentioned resolver is a special case. Resolver gets activated even before other extensions are ready. By ready I mean, core activates resolver even before it reads and registers the contributions of other extensions. So in this case, Account extension's contributions are not yet read and hence @egamma is seeing provider is not registered error.

We had similar issue for custom views. We fixed it in the core by waiting until extensions are ready.

https://github.com/microsoft/vscode/blob/7279524/src/vs/workbench/api/browser/mainThreadTreeViews.ts#L37

This is the pragmatic solution we took at the time instead of having a general solution as resolvers are special. May be you can follow the same approach - `getSessions` call can wait until extensions are ready. I think this a fair assumption in any case.

**Comment by RMacfarlane** [comment]
Authentication providers are registered when they activate and call `vscode.authentication.registerAuthenticationProvider`, they don't contribute anything in the package.json currently. `getSessions` will continue to throw until they are registered, so I think waiting for the `whenInstalledExtensionsRegistered` is not enough if this is only after all extension manifests have been read.

There is a `onDidChangeAuthenticationProviders` event  that can be used for this purpose.

Something like
```ts
 vscode.authentication.onDidChangeProviders(e => {
    if (e.added.indexOf('github') > -1) {
        // get token
    }
}
```

**Comment by egamma** [comment]
@RMacfarlane makes sense I'll wait for the listener, thanks.
