### ISSUE TITLE
Localization smoke test fails

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93462]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=70457&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=05af1eac-c39c-5c75-1e3f-dd115ec8907d&l=98

```
 1) VSCode Smoke Tests (Electron)
       Localization
         starts with 'DE' locale and verifies title and viewlets text is in German:
     Error: Timeout: get text content '.monaco-workbench .part.sidebar > .title > .title-label > h2' after 20 seconds.
      at /Users/runner/runners/2.165.2/work/1/s/test/automation/out/code.js:176:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/runners/2.165.2/work/1/s/test/automation/out/code.js:9:58)

```

Could it be that something changed again with regards to detecting the language? Can we make this more robust?

**Comment by dbaeumer** [comment]
I looked into this and there are a couple of problems:

- this needs to check translations in the render. But we could use some custom commands for it
- it needs to install an extension
- needs to restart VS Code with the installed extension

I checked if I could implement this as an extension test but failed due to point 2 and 3. If someone has an idea please let me know.

**Comment by dbaeumer** [comment]
The path actually still exists:

<img width="784" alt="capture" src="https://user-images.githubusercontent.com/1931590/77623901-3d496900-6f41-11ea-9952-7b268d7d01c6.png">


Looking at the build it also looks like that only the MacOS tests failed and that the localization test is not the only one not being able to find a element. There is also:

```
Error: Active element not found. Current active element is 'HTML > BODY.file-icons-enabled.mac.vs-dark.vscode-theme-defaults-themes-dark_plus-json > DIV.monaco-workbench.mac.chromium > DIV#webview-extensionEditor > WEBVIEW.webview.ready'. Looking for .quick-input-widget .quick-input-box input
    at e.isActiveElement (file:///Users/runner/runners/2.165.2/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1376:211)
    at t.WindowDriverChannel.call (file:///Users/runner/runners/2.165.2/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1380:998)
    at C.onPromise (file:///Users/runner/runners/2.165.2/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:386:102)
    at C.onRawMessage (file:///Users/runner/runners/2.165.2/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:385:737)
    at file:///Users/runner/runners/2.165.2/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:385:256
    at e.fire (file:///Users/runner/runners/2.165.2/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:102:423)
    at EventEmitter.n (file:///Users/runner/runners/2.165.2/work/1/VSCode-darwin/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:99:713)
    at EventEmitter.emit (events.js:203:13)
    at Object.onMessage (electron/js2c/renderer_init.js:3652:16)
```

@bpasero could you please try to reproduce locally on a Mac. I don't have one :-)

**Comment by bpasero** [comment]
@dbaeumer the test seems fine, but it wants "starten" when seems to be "run"

![image](https://user-images.githubusercontent.com/900690/77625794-84852900-6f44-11ea-918c-45c186126e99.png)

**Comment by dbaeumer** [comment]
@bpasero thanks for testing! What is wired then is why the test pass on Windows. Or do we only run the smoke test on MacOS in the build?

I checked todays insider and it is indeed `Run` now. In general having these tests in our daily build is very fragile due to the fact that translations only come once a month. So if @isidorn reorganizes code then the test will be broken because we need a new language pack to adapt to that change. 

I will comment out the debug test for now. Here is what I think we need to do:

- don't run tests with a German local in the build
- use some pseudo translation
- testing of the LPs should happen by the translation team anyways.

**Comment by bpasero** [comment]
@dbaeumer yes the smoke test currently only runs once on macOS. I think that is fine to get some feedback about failing tests.

**Comment by dbaeumer** [comment]
I briefly looked into this and we can't generate a pseudo language pack inside the test since we don't have the necessary information about the built in extensions. So the right approach is to generate a pseudo language pack in the build and may be upload it to the market place or at least be able to install it locally.

**Comment by dbaeumer** [comment]
I fixed the smoke test. Making it more stable didn't make it in April.

**Comment by joaomoreno** [comment]
@dbaeumer Is this still an issue?

**Comment by dbaeumer** [comment]
It is currently not an issue. But the comment here is still valid https://github.com/microsoft/vscode/issues/93462#issuecomment-604333139. I will mark it as debt.

**Comment by chrmarti** [comment]
#Attempt building Linux in https://monacotools.visualstudio.com/Monaco/_build/results?buildId=126062&view=logs&j=1c20ec05-7612-5293-9b87-7ea15c22422f&t=d18f52d5-a1b3-58b4-9e74-367746b19139&s=df1e964f-4580-5d4b-af27-e8818fedb05f shows a similar error:

1) VSCode Smoke Tests (Electron)
       VSCode Smoke Tests (Electron)
         Localization
           starts with 'DE' locale and verifies title and viewlets text is in German:
     Error: Received wrong German localized strings: {"open":"open","close":"close","find":"find"}
      at Context.<anonymous> (out/areas/workbench/localization.test.js:34:27)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by dbaeumer** [comment]
I added more code to understand why this is happening. It is either that the extension didn't install correctly or that the LP is broken. See https://dev.azure.com/monacotools/Monaco/_build/results?buildId=126374&view=logs&j=4d2898ab-dfbe-557e-92e7-aaac158fdd2f&t=41d9f3a8-af10-5350-1c03-229d27a4a1b6

**Comment by isidorn** [comment]
Nothing for endgame, moving out to august

**Comment by dbaeumer** [comment]
This can be closed. We finally track this down. Was a problem with writing the LP cache file when a LP got installed.
