### ISSUE TITLE
can not download any extensions

### ISSUE THREAD

**Issue by izac3d** [microsoft/vscode#93524]
Issue Type: <b>Bug</b>

I read that this problem related to DNS or SSL inspection I dont know but this problem has many months now so please fix it

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by izac3d** [comment]
1.1.1.1 DNS did not work and I cannot open the python page.

Console log: net::ERR_NAME_NOT_RESOLVED
dbaeumer.gallery.vsassets.io/_apis/public/gallery/publisher/dbaeumer/extension/vscode-eslint/2.1.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?redirect=true&install=true:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
dbaeumer.gallery.vsassets.io/_apis/public/gallery/publisher/dbaeumer/extension/vscode-eslint/2.1.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage?install=true:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED

[2020-03-27 18:23:54.532] [sharedprocess] [info] Starting to clean up unused language packs.
[2020-03-27 18:24:53.369] [sharedprocess] [info] Installing extension: dbaeumer.vscode-eslint
[2020-03-27 18:24:53.373] [sharedprocess] [error] Failed to install extension: dbaeumer.vscode-eslint

**Comment by sandy081** [comment]
>  I cannot open the python page.

Seems you have issues with your network. Please check with your administrator.

**Comment by izac3d** [comment]
all other sites open normally !! it is my pc no network admin here !!!

Also this did not fix my main problem.

**Comment by izac3d** [comment]
python page open when I use VPN it is blocking my country IPs it seems
