### ISSUE TITLE
extensions does not download 

### ISSUE THREAD

**Issue by izac3d** [microsoft/vscode#93620]
Issue Type: <b>Bug</b>

I can not install any extensions unless I used a vpn

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
Have you reviewed the information and advice at https://code.visualstudio.com/docs/setup/network ?

**Comment by izac3d** [comment]
yes, prior versions I was able to install extensions. now only through vpn I can install.

**Comment by gjsjohnmurray** [comment]
Any clues in the conversation on #91739 ?

**Comment by izac3d** [comment]
No. admin mode does not solve it.

**Comment by gjsjohnmurray** [comment]
My understanding of https://github.com/microsoft/vscode/issues/91739#issuecomment-595073194 is that running as admin *was* the problem.

But it sounds like you have the problem when running as a non-admin user too, right?

**Comment by izac3d** [comment]
yes I dont run it as admin

**Comment by gjsjohnmurray** [comment]
I am out of ideas.

cc @sandy081

**Comment by mijail73** [comment]
I'm going to reinstall VS to see what happen.

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by izac3d** [comment]
all network requests failed. I changed DNS but problem remain. as I said when I use VPN and change to Europe country for example it work and I can install.

**Comment by sandy081** [comment]
Looks to your network issue. Not sure how I can help here.

**Comment by izac3d** [comment]
@sandy081 you should leave it open it was not solved and someone else may help

**Comment by sandy081** [comment]
But this is a network related issue and I do not think this is the right place about discussing it right?

**Comment by izac3d** [comment]
but I can update all other apps including vsc main update I just dont know why extensions dont install. if someone has a hint about fixing this then no problem to put it here for example like changing DNS.

**Comment by gjsjohnmurray** [comment]
> Have you reviewed the information and advice at https://code.visualstudio.com/docs/setup/network ?

@izac3d did you verify that all of the domains listed in the article I referred you are reachable by you?

**Comment by izac3d** [comment]
checking now. how I check domains begin with * ?

**Comment by izac3d** [comment]
this one is inaccessible vscode.search.windows.net
