### ISSUE TITLE
Opening a new file causes it to be modified and displayed as unsaved

### ISSUE THREAD

**Issue by ibachar** [Microsoft/vscode#9362]
- VSCode Version: 1.3.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open a folder
2. Double click a file to open it in the left panel
3. The file is displayed with a  dot in the tab meaning it is not saved

**Comment by MLefebvreICO** [comment]
I do not have this issue on my end on Window 10 x64.

Are you sure you didn't modified that file in quick view or something like that ?

**Comment by weinand** [comment]
@ibachar This sounds like an issue caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by ibachar** [comment]
Yep, running it with ```--disable-extensions``` solved the issue
