### ISSUE TITLE
Indentation misalignment due to invisible character

### ISSUE THREAD

**Issue by andrecasal** [microsoft/vscode#93689]
- VSCode Version: `Insiders 1.44.0`
- OS Version: `macOS 10.15.3`

Steps to Reproduce:

1. Copy+paste the following to an md file
```
	a
️	b
```
2. Notice a and b are not aligned
3. Go to the end of the second line, press the left arrow key twice and delete one character
4. Notice that you delete a hidden character and that now b is aligned with a.

Does this issue occur when all extensions are disabled?: Yes

This is me deleting the invisible character:
![Mar-29-2020 15-42-02](https://user-images.githubusercontent.com/22457463/77851955-e60ef700-71d3-11ea-9661-e8395b229cb5.gif)

These are the results from https://www.soscisurvey.de/tools/view-chars.php:
<img width="912" alt="characters" src="https://user-images.githubusercontent.com/22457463/77851959-ec9d6e80-71d3-11ea-8bc3-a47dd7a36dba.png">

Notice it says **7 characters, 9 bytes** even though the page only shows 6 characters.

**Comment by alexdima** [comment]
The character is [`'VARIATION SELECTOR-16' (U+FE0F)`](https://www.fileformat.info/info/unicode/char/fe0f/index.htm).

The problem is that the tab rendering code counts this character as a regular character. In other words, it makes no difference between a regular character, like `x` and this character and assumes that the character will be rendered with a typical width. But in this case, the variation selector 16 character is rendered with a width of `0`.

@andrecasal Although this is technically valid Unicode, it does not make sense to have an emoji variation selector except around an emoji. So, given we understand what the problem is, and that this is abnormal (it makes no sense to start a new line with a variation selector), I would choose to not do anything at this time.

**Comment by andrecasal** [comment]
Ok, that makes sense 👍
