### ISSUE TITLE
Unnecessary appearance of 'Code is already running' message

### ISSUE THREAD

**Issue by RajatAgg-21** [microsoft/vscode#93731]
Issue Type: <b>Bug</b>

Many times I am unnecessarily getting the 'Code is already running' message whenever I run the program. Also, it is not capturing any user input in the program.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       M 430  @ 2.27GHz (4 x 2261)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|2.86GB (1.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.9.17
python|ms-|2020.3.69010

</details>

**Comment by Emiel-Bos** [comment]
I have a similar issue where it keeps on stating the following: "Code is already running" unnecessarily. I closed all the terminals and made sure no other screens are opened.

## Context (Environment)
I've been working on the same project for the last few days and can only remember myself encountering this issue since yesterday.  The project uses tkinter and matplotlib so at first I thought the issue was related to those windows not being properly closed. The problem seems to resolve itself by reopening VS code but will reappear sooner or later. It is note worthy that the debugger still works perfectly fine. 
<details>
<summary> Python 3.7.6</summary>
<br> cycler==0.10.0
<br> easygui==0.98.1
<br> genicam==1.0.0
<br> harvesters==1.1.1
<br> kiwisolver==1.1.0
<br> matplotlib==3.2.1
<br> numpy==1.18.2
<br> opencv-python==4.2.0.32
<br> Pillow==7.0.0
<br> pyparsing==2.4.6
<br> python-dateutil==2.8.1
<br> scipy==1.4.1
<br> six==1.14.0
</details>
<details>
<summary>VScode </summary>
<br> Version: 1.43.2 (user setup)
<br> Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
<br> Date: 2020-03-24T07:38:38.248Z
<br> Electron: 7.1.11
<br> Chrome: 78.0.3904.130
<br> Node.js: 12.8.1
<br> V8: 7.8.279.23-electron.0
<br> OS: Windows_NT x64 10.0.18362
</details>
<details>
<summary>Extensions</summary>
<br> batisteo.vscode-django
<br> donjayamanne.python-extension-pack
<br> formulahendry.code-runner
<br> magicstack.MagicPython
<br> ms-python.python
<br> ms-vscode.Theme-PredawnKit
<br> VisualStudioExptTeam.vscodeintellicode
<br> vscode-icons-team.vscode-icons
<br> wholroyd.jinja
</details>

## Possible Implementation
