### ISSUE TITLE
Correct terminal cursor position is lost when chaning window size

### ISSUE THREAD

**Issue by gsscoder** [microsoft/vscode#93744]
If I minimize or maximize (or even resize) **VSCode** window sometime **terminal cursor** compares in _wrong position_.

More easy to see.

![Annotation 2020-03-30 135350](https://user-images.githubusercontent.com/1194228/77909821-4c585000-728e-11ea-8ec9-99a8601c9dd3.png)

Thank you,
Giacomo S. S.

**Comment by Tyriar** [comment]
This issue seems to originate from an upstream component and is not something VSCode can fix by making a change to our code. As such, I will go ahead and close it. Please try to reproduce in [Windows Terminal](https://www.microsoft.com/en-us/p/windows-terminal-preview/9n0dx20hk701) and report to [microsoft/terminal](https://github.com/microsoft/terminal) with repro steps.

Thanks for understanding.

**Comment by gsscoder** [comment]
OK, @TylerLeonhardt. Thank you
