### ISSUE TITLE
js hover highlights class nested properties matching some reserved keywords

### ISSUE THREAD

**Issue by pushkine** [microsoft/vscode#93762]
```javascript
class x {
	foo = {
		bar: [],
		delete: [],
		instanceof: [],
	}
	constructor() {
		this.foo
	}
}
```
![Code_2020-03-30_16-59-00](https://user-images.githubusercontent.com/30108880/77927667-c812c680-72a7-11ea-82a3-99b33addf45c.png)

1.43.2

**Comment by mjbvz** [comment]
@aeschli We currently highlight these code snippets using our normal grammar. This doesn't  work all the time because the snippets are often not valid TypeScript / JavaScript

I wonder we could let extension return semantically highlighted text that we then use to render the snippet. The TypeScript server API already marks up the snippet using `SymbolDisplayPart` which should tell us what is a `keyword` vs `type` and so on

**Comment by aeschli** [comment]
Yes, teh TS server could send the information of what is a keyword, type, property directly in the code block of the hover markdown description. Could be HTML in markdown or we could invent our own codeblock+ to express that. Note, it would not be a color, but the token types/modifiers as used in semantic highlighting.

Alternative is to create a dedicated typescript-hover (TextMate) grammar, where `(property)` is part of the syntax and is used to signal what syntax comes next

**Comment by mjbvz** [comment]
I looked into this but don't think it's worth the engineering work or risk of introducing additional bugs.

I believe TS does send along pseudo-semantic coloring info with the hover response. The best long term fix would be to support that in hovers
