### ISSUE TITLE
Debug "Call Stack" view has extra margin

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93824]
![image](https://user-images.githubusercontent.com/900690/77992604-ae649400-7326-11ea-815e-54aed60fc1bb.png)

See not aligned.

**Comment by ghosej** [comment]
Is this something that the community can work on? If so, I would like to work on this.

**Comment by isidorn** [comment]
@ghosej thanks for offering. We are currently in the endgame week which means we are quickly fixing the last remaining issues before we ship. Due to that I will probably try to fix this bug in the next 8 hours. If you have a solution before than feel free to submit a PR.
Otherwise I recommend looking at issues with a help-wanted tag, or at issues not assigned to March milestone. Thanks

**Comment by isidorn** [comment]
This was broken via https://github.com/microsoft/vscode/pull/92294
On this line https://github.com/microsoft/vscode/blob/b789f6c907387e21b51b519732d5744b6bc8f82d/src/vs/workbench/browser/parts/views/media/paneviewlet.css#L28

@sbatten why do we add maring-left of 7px to all first child of a title? This breaks the call stack view.

**Comment by sbatten** [comment]
V0 of multipanel had no collapse so I think this is just a remnant of that. I am removing.

**Comment by sbatten** [comment]
To Verify:
1. Check that Call Stack view in the Run Viewlet does not have misaligned padding compared to other views.
2. Check other views as well to ensure this fix does not break others.
