### ISSUE TITLE
Update indicator in help menu could be more descriptive

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#93827]
![image](https://user-images.githubusercontent.com/900690/77994970-3ea4d800-732b-11ea-98f3-6cd7d6c4c0f7.png)

Maybe `Update: Download Now`?

**Comment by joaomoreno** [comment]
fyi @sbatten

**Comment by JacksonKearl** [comment]
(Assuming this is Windows because I cant figure out how I even ought to be able to get into this state on mac or linux)

I can't seem to get into this state. Even when I have `"update.mode": "manual"` and `"update.enableWindowsBackgroundUpdates": false`, when I click "check for updates" it instantly converts to the "downloading update"/"restart to update" state. 

Is it a separate bug that `"update.enableWindowsBackgroundUpdates": false` isn't being respected?

**Comment by joaomoreno** [comment]
1. Download the Linux ZIP
2. Extract it and change the `commit` field in `product.json` to `outdated`
3. Launch it and trigger `Check for Updates`
