### ISSUE TITLE
Task Quick Pick 'Go back' has a '...'?

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#93835]
In my opinon the Go back action doesn't prompt for new input, it is only navigational, therefore it should not have a trailing '...'

![image](https://user-images.githubusercontent.com/172399/78001052-731d9180-7335-11ea-8b86-cee194297f2b.png)

Suggest to us a back arrow to indicate the navigation, same as is done in Gitlens

![image](https://user-images.githubusercontent.com/172399/78000934-4bc6c480-7335-11ea-98ae-320a8c96884f.png)

**Comment by bpasero** [comment]
Should this be a button next to the input field? Looks more like a wizard dialog to me then?

**Comment by alexr00** [comment]
I think you're one version behind on insiders, the current version has 
![image](https://user-images.githubusercontent.com/38270282/78031296-a2e38e00-7363-11ea-9de5-5c083d6fe93b.png)

I kept the Go Back as list entry instead of a button because when we discussed it during the UX sync it was brought up that the back arrow in the multi step quick pick is less keyboard friendly to use.

**Comment by misolori** [comment]
> the back arrow in the multi step quick pick is less keyboard friendly to use

I think if we have keyboard issues in the mutli step quick pick then we should fix that instead of duplicating behaviors. This is also what we suggest to extensions to use when needing to go back to the previous step.
