### ISSUE TITLE
Scope `CustomEditorProvider` to document type?

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93868]
re #93767

I am implementing a custom editor with a custom editor and I am not expecting that resolve get a different type as open returns. So, for consideration

```ts

export interface CustomEditorProvider<T extends CustomDocument> {

		openCustomDocument(uri: Uri, token: CancellationToken): Thenable<T>;

		resolveCustomEditor(document: T, webviewPanel: WebviewPanel, token: CancellationToken): Thenable<void>;

		readonly editingDelegate?: CustomEditorEditingDelegate<T>;
	}
```

**Comment by mjbvz** [comment]
Yes I like that overall.

I don't think I can make this change with the current API however since the `EditType` is needed  for types such in `CustomEditorEditingDelegate` and [`CustomDocumentRevert`](https://github.com/microsoft/vscode/blob/a8f383a37cb9e91f695d48cf0222069d263c185a/src/vs/vscode.d.ts#L6986). I don't think there's a way to recover the editType from `CustomDocument<T>`  without getting into conditional types

Implementors should be able to use their own document type though, for example here's what the example binary editor does:

```ts
	async resolveCustomEditor(
		document: PawDrawDocument,
		webviewPanel: vscode.WebviewPanel,
		_token: vscode.CancellationToken
	): Promise<void> {
```

**Comment by jrieken** [comment]
Things might get even more simple when nuking the editing delegate and move everything into `CustomDocument`. I really like @bpasero document implementation here (https://github.com/bpasero/vscode-custom-editor-bom/blob/master/src/extension.ts#L118) and only that made me understand hot exit

**Comment by mjbvz** [comment]
Fixed in current API version
