### ISSUE TITLE
Quick pick actions not verticaly centered properly

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93870]
Refs: https://github.com/microsoft/vscode/issues/93648

Noticable in high contrast theme

![Screenshot 2020-03-31 at 11 35 29](https://user-images.githubusercontent.com/1926584/78011387-ceef1700-7343-11ea-96d1-20338963aec0.png)

**Comment by bpasero** [comment]
@misolori maybe another one for a quick check on the CSS rules for codicons?

**Comment by misolori** [comment]
This was due to a css rule from search:

https://github.com/microsoft/vscode/blob/070e2f88c69fad683f82d2e8eadd7650826c78a0/src/vs/workbench/contrib/search/browser/media/searchview.css#L260-L263

Updated the scope so it only applies to the search viewlet so the quick pick is not affected anymore:

![image](https://user-images.githubusercontent.com/35271042/78050029-9c87ee80-7330-11ea-8143-8b2681f12421.png)
