### ISSUE TITLE
Recently used commands are not getting synced

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#93884]
- Enable sync on two machines
- From first machine try some commands from command pallette
- Go to second machine and open command pallette
🐛 Recent list is not updated.

I checked that state is getting synced but UI is not getting updated.
**Note:** You can repro this opening two windows from same VS Code instance. UI is not getting updated across windows from same instance.

**Comment by bpasero** [comment]
I think this is tolerable. You will get the proper history when you open an instance again.

Since there is no real event when something changes due to syncing, I would have to re-read the entire history every time a storage change happens. But this change is also happening from the same instance when a command is picked. I think that is overkill.

**Comment by sandy081** [comment]
> But this change is also happening from the same instance when a command is picked

@bpasero Are not we supporting at other places like status bar etc? We listen to storage change and update the window state?  I do not have knowledge about command picker history is not this involve just replacing the state whenever there is a change in storage?

Do you mind accepting PRs for this>

**Comment by bpasero** [comment]
@sandy081 I think each location that uses storage can decide to react on the event or not. For commands specifically I chose to not react to the change because you could have one window opened with a TS specific command you always run (so it appears to the top) and another window with a C++ command being the first. It would be frustrating to have the first command always switch across all windows.

Hope that clarifies the intent.

**Comment by sandy081** [comment]
> I think each location that uses storage can decide to react on the event or not.

Completely agree with that.

> For commands specifically I chose to not react to the change because you could have one window opened with a TS specific command you always run (so it appears to the top) and another window with a C++ command being the first. It would be frustrating to have the first command always switch across all windows.

Just trying to understand what and when is the merging strategy when multiple windows have different recent commands history.

**Comment by bpasero** [comment]
Currently history is only updated upon restart, but not within a session. I think we should keep it like that to not damage muscle memory.
