### ISSUE TITLE
Task: Tasks linger on `recently used` section, even after they are deleted

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#93931]
Testing #93746 on Linux

1. Create a new `tasks.json` file
2. Add a task `A`
3. Run it
4. Rename it to task `B`

🐛 Task `A` still appears in the `recently used` task section. It even works! It even appears on reload... and WORKS! 😲

**Comment by joaomoreno** [comment]
I even got it to show up like this, after deleting all tasks.json files I created:

![image](https://user-images.githubusercontent.com/22350/78030342-3916b480-7362-11ea-8270-cf810bcfe436.png)

**Comment by alexr00** [comment]
This was intentional so that the quick pick could be much faster and not actually go and fetch the tasks. However, I can make this better for tasks that were in a tasks.json (it won't help for purely contributed tasks though).

**Comment by JacksonKearl** [comment]
> I can make this better for tasks that were in a tasks.json

Still seeing old names from tasks.json appear - what should I be expecting?

![image](https://user-images.githubusercontent.com/8586769/78376713-8faf0900-7583-11ea-8b8f-09e118a6e920.png)

**Comment by alexr00** [comment]
Since you're changing an `npm` task we'd need to go the the npm extension to determine if there is still a `npm: watch-typecheck` task. In your case you're seeing the expected behavior because the goal here is not to go the the extensions so that we can keep the picker fast.

To verify, try changing the label of a `shell` or `process` task instead. That's where I added some extra checking since those are only user defined.
