### ISSUE TITLE
Cell navigation should always be done in visual not historical order

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#93938]
Refs: #93742

1. Have a notebook file with multiple cells, have an error in each cell. Re-arange the cells such that they are not ordered in the way they got created 
2. Notice how the error jumping is done based on historical creation time (cell 0, before cell 1 before cell 2...). It should be done in a vertical order so it makes sense for the user and is not surprising

![nextError](https://user-images.githubusercontent.com/1926584/78031666-2604e400-7364-11ea-82e5-ac19a1bbe128.gif)

**Comment by jrieken** [comment]
This would require us to rename cells when re-ordering them, e.g close a files and create new once or swap contents...

**Comment by jrieken** [comment]
@rebornix For nicer cell numbers I want to make [_cellhandlePool](https://github.com/microsoft/vscode/blob/449cd6ee93b7216cbad2cccebbce964ad8144d26/src/vs/workbench/contrib/notebook/common/model/notebookTextModel.ts#L21) and instance-field, not a static field. I believe that is OK to do because we only use the cell handle in the context of a notebook, never as "global" identifier but I wanna double check with you before making such a change

**Comment by jrieken** [comment]
We won't fix this for the foreseeable future. What would be required to get this right is some sort of pluggable sort order provider. However, that would need to do a lookup (expensive) when sorting URIs of notebooks because the order isn't obvious anymore
