### ISSUE TITLE
Open recent: open type should show when filtering

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93944]
#93729

Version: 1.44.0-insider (user setup)
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:23:56.446Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

---

When filtering editor groups you see the group number:

![image](https://user-images.githubusercontent.com/2193314/78032433-d994b680-7319-11ea-9324-05fc693a89fd.png)

Same with go to file:

![image](https://user-images.githubusercontent.com/2193314/78032541-047f0a80-731a-11ea-9aea-ad185a6cde73.png)

But not in open recent:

![image](https://user-images.githubusercontent.com/2193314/78032622-29737d80-731a-11ea-8100-de73f30d3947.png)

**Comment by bpasero** [comment]
This may be a bug in quick pick where the separator is filtered out.

**Comment by bpasero** [comment]
Yes, this is really not related to latest changes or quick open (and reproduces in stable): I am using the [`IQuickInputService#pick`](https://github.com/microsoft/vscode/blob/cd0d6485221e0f0e89d04aa760b6110db925575f/src/vs/workbench/browser/actions/windowActions.ts#L127) method and let it deal with filtering. For some reasons, it looks like separators are getting lost in that case. 

@chrmarti not sure you have a duplicate for this one maybe already.

**Comment by chrmarti** [comment]
The items in Open Recent are no longer in groups when they are sorted by score. I'm not sure preserving the groups would make sense because there is no indication that the user would prefer workspaces over files or the other way around.

Preserving the groups with `edt` makes sense because these are different editors.

Preserving the groups with Go To File makes sense because one is much more likely to open a recent file.
