### ISSUE TITLE
Recent workspaces: "hold ctrl+key to open in new window" shows regardless of "window.openFoldersInNewWindow": "on"

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93943]
#93729

Version: 1.44.0-insider (user setup)
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:23:56.446Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

---

I have `"window.openFoldersInNewWindow": "on"` set and recent workspaces shows this:

![image](https://user-images.githubusercontent.com/2193314/78032191-7d319700-7319-11ea-99bd-2e7a9d405168.png)

It would be lovely if the ctrl behavior was inverted here if the setting is `"on"`.

**Comment by bpasero** [comment]
@Tyriar where is this coming from, shouldn't it look like this now:

![image](https://user-images.githubusercontent.com/900690/78043198-5607b380-7373-11ea-97fb-f0a9f84a1fdb.png)

???

**Comment by Tyriar** [comment]
I see it's changed in the code, I reinstalled VS Code. Maybe some folders had permissions issues during an update or something 🤷‍♂

**Comment by Tyriar** [comment]
OH! I have the en-GB language pack installed...

@dbaeumer I would have thought this would invalidate the translation when the string value changes? Should we be changing the nls key if the string changes dramatically like this?

**Comment by dbaeumer** [comment]
No, string values are keyed by the key we provide to the `nls.localize` call. This is how these translation databases work today. One idea we were discussing with them to hash the value and use it as a key but that didn't make them happy since these hash values would show up in all their tools in the user interface and they were concerned this confuses translators. So we left the key.

Bottom line: to be on the save side changing the key will fix this. But it will also be fixed when a new LP ships.

**Comment by Tyriar** [comment]
@dbaeumer does changing the en-US value trigger the string to get re-localized, if not we could be building up a significant amount of strings in other languages that no longer match the English version?

**Comment by bpasero** [comment]
Changed the key.

**Comment by dbaeumer** [comment]
@Tyriar yes, a string change in the nls.localize call will trigger a re-translation in all LP packs.
