### ISSUE TITLE
Show all tasks does nothing when a webview is opened in the background

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93950]
#93641

Version: 1.44.0-insider (user setup)
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:23:56.446Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

---

Works fine when a file is opened, not an extension (webview) though.

![4ca44d10-8157-4db0-8ea9-719c7aa69b57](https://user-images.githubusercontent.com/2193314/78035937-91c45e00-731e-11ea-9345-e6a93900e5b6.gif)

Is this a wider problem with multi-step quick picks?

**Comment by IllusionMH** [comment]
Looks similar to #75209

**Comment by chrmarti** [comment]
This is an interaction between QuickInput and the WebView. When the first picker closes, it passes focus back to the editor which passes it to the webview element. The second picker then opens and takes the focus only to loose it immediately after.

I don't see 'focusin' nor 'focusout' events for the webview element, so that element seems to somehow be special. @mjbvz Do you have an idea of what might be going on here?
