### ISSUE TITLE
applyEdits/undoEdits/revert are messing with my brain

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#93963]
re #93767

This doesn't happen often (ever?) but I had to throw the towel when trying to implement `CustomEditorEditingDelegate` and I had to check the provided sample. Esp. applyEdits/undoEdits/revert are 0% self-explaining and are equipped with little doc. By now, my understanding is that they are just events with payload document, editor and event type (via the method name) and that makes me wonder why the CustomDocument simply cannot emit that as event?

**Comment by mjbvz** [comment]
I know this delegate style is a new pattern in our API so here's some quick background on how we ended up with this design:

* We believe that many custom editors will be readonly.

    Implementers of readonly custom editors should not have to worry about any methods related to editing.

* For writeable custom editors, we want to enforce that extensions implement all methods required for editing

     An extension should not be able to implement a `undo` but not `save` for example.

These points explain why there is a separate `CustomEditorEditingDelegate` in the first place.

Now for the editing methods themselves, we found we could either put these methods on each document or have a single object (the delegate) that handles all of them. These two approaches are very similar, and you can express either one using the other.

I like the delegate based approach because is centralizes all functionality related to editing in a single place. The provider can then delegate the implementation of these operations to its documents if it chooses. The one wart with this approach in my option is the `CustomEditorProvider.editingDelegate` property

---

I feel we could argue this point back and forth (and we already have done so to some degree) so I'm hesitant to change things without a good reason or a consensus.  

On my side, I'll take a look at expanding the api documentation for the current API. Also be sure to check out the [draft extension guide](https://github.com/microsoft/vscode-docs/blob/custom-editors/api/extension-guides/custom-editors.md) I've been working on

/cc @bpasero @kieferrm

**Comment by mjbvz** [comment]
I believe the document baed alternative would look something like this:

```ts
class CustomDocument {
     // Existing custom document class
}

// Editable documents must extend this class 
abstract class EditableCustomDocument extends CustomDocument {
    abstract save(): void;
    abstract saveAs(resource: Uri): void;
    abstract backup(): void;

    makeEdit(edit: EditType): void; // tell VS Code that the document has changed

    readonly onUndo: Event<CustomEditorUndoEvent>;
    readonly onRedo: Event<CustomEditorRedoEvent>;
    readonly onRevert: Event<CustomEditorRevertEvent>;
}


export interface CustomEditorProvider<EditType = unknown> {

    openCustomDocument(uri: Uri, token: CancellationToken): CustomDocument  | EditableCustomDocument;

    ...
}
```

**Comment by jrieken** [comment]
I understand the delegate pattern, my problem is its conflict with `CustomDocument` which is bound to the same `EditType` as the delegate having `appliedEdits` and `savedEdits` which I honestly don't understand. So, my problem here is the overlap and the back and forth of these two players, not the delegate itself but the inconsistency of where to put responsibilities. 

> we want to enforce that extensions implement all methods required for editing

Slight disagree. You obviously need save for edit but hot exit, undo/redo, revert... Sure, it best to have them all but given that we need to protect ourselves from bad implementations we could also handle the absence of optional features.

**Comment by jrieken** [comment]
Apart from the delegate or not delegate discussion, my frustration that led to this issue is that I failed to understand what applyEdits, undoEdits, or revert should do or how I should implement them.

**Comment by jrieken** [comment]
Trying to explain my confusion in more detail (thinking loud)

**1 - applyEdits**

```ts
/**
 * Apply a set of edits.
 *
 * Note that is not invoked when `onDidEdit` is called because `onDidEdit` implies also updating the view to reflect the edit.
 *
 * @param document Document to apply edits to.
 * @param edit Array of edits. Sorted from oldest to most recent.
 *
 * @return Thenable signaling that the change has completed.
 */
applyEdits(document: CustomDocument<EditType>, edits: ReadonlyArray<EditType>): Thenable<void>;
```

- Who calls this? When and why?
- I need translation for "Note that is not invoked when `onDidEdit` is called because `onDidEdit` implies also updating the view to reflect the edit." At least an explainer for when this is *not called* but still confused. But who calls `onDidEdit`, it's an event it fires, right?

**2 - undoEdits**

```ts
/**
 * Undo a set of edits.
 *
 * This is triggered when a user undoes an edit.
 *
 * @param document Document to undo edits from.
 * @param edit Array of edits. Sorted from most recent to oldest.
 *
 * @return Thenable signaling that the change has completed.
 */
undoEdits(document: CustomDocument<EditType>, edits: ReadonlyArray<EditType>): Thenable<void>;
```

- The explains more and I can understand what's going but I don't know how to undo the edits and if this should fire `onDidEdit` event or not
- The doc says "... a user undoes an edit." but the argument is an array of edits
- How does the API ensure that my implementation actually did something?


**3 - revert**

```ts
/**
 * Revert the file to its last saved state.
 *
 * @param document Document to revert.
 * @param edits Added or applied edits.
 *
 * @return Thenable signaling that the change has completed.
 */
revert(document: CustomDocument<EditType>, edits: CustomDocumentRevert<EditType>): Thenable<void>;
```

- Why not `revertEdits`?
- What the relation between `CustomDocumentRevert#appliedEdits` and `CustomDocument#appliedEdits`?
- The doc for `CustomDocumentRevert#undoneEdits` says "List of edits that were undone to get the document back to its on disk state." So, did this already happen? Is the document already reverted?

**Comment by bpasero** [comment]
I think this API is a consequence for not having an explicit `undo` and `redo` method. Back from our very early discussions I think we had 2 camps: this approach, and the other where a custom editor would be in full control of undo, redo, reporting dirty state. 

With exposing edits as first class thing, we make the API considerably more complex to understand but probably help the extension to behave "more" correct when the user triggers undo/redo and to report dirty state properly.

Another downside besides the confusion is that a custom editor cannot report the dirty state itself. E.g. a custom editor that suddenly becomes saved cannot be reported as such from the extension code (as far as I can tell). If e.g. we had a live share like scenario where the host marks a document as saved, not sure how that would travel to the guest.

**Comment by kieferrm** [comment]
https://github.com/microsoft/vscode/issues/93963#issuecomment-607113520 helps to better understand the problem. It seems we can make good progress but directly addressing the questions in the API documentation.  (3)- bullet 3 seems more of a challenge though, but let's see where we get with the updated doc first.

**Comment by mjbvz** [comment]
8a25588 expands the docs on these methods based on the feedback

**Comment by mjbvz** [comment]
Also to some specific points:

- Why not `revertEdits`?

`revert` tells the extension to reload the resource from disk. I've clarified this in the docs. Revert does not always have to involve edits, such as reverting a restored backup. 

- Why are edits arrays if we only ever pass a single edit?

Before we had an explicit `revert`, we would call undo/apply with lists of edits to implement revert. After adding `revert`, I decided to keep using arrays for potential future use. I know we're exploring exposing the edit stack to users for example, and if the user performs an operation such as `undo the last 3 edits` it would be better to call `undoEdits` once with all three edits instead of us calling `undoEdits` 3 times and requiring extensions to debounce things on their side.

- How does the API ensure that my implementation actually did something?

Unfortunately we can't ensure this. We've tried to design the api so that extensions are directed to do the right thing. For example, if you implement an editable custom editor, you have to implement `CustomEditorDelegate.undoEdits`. However we cannot enforce the extensions properly update their webviews when `undoEdits` is called. All we can do is guide extension authors in the right direction with the api design and and documentation

**Comment by mjbvz** [comment]
I discussed this with @kieferrm today. Here are two small proposals for how to change the API:

- Rename `applyEdits` to `redoEdits`
 
    This should make it more clear when this method is called

- Change the `CustomDocumentRevert` type so that it can only have a list of undo edits or a list of redone edits, but not both.

    Right now the type looks like:


    ```ts
	interface CustomDocumentRevert<EditType = unknown> {
		/**
		 * List of edits that were undone to get the document back to its on disk state.
		 */
		readonly undoneEdits: ReadonlyArray<EditType>;

		/**
		 * List of edits that were reapplied to get the document back to its on disk state.
		 */
		readonly appliedEdits: ReadonlyArray<EditType>;
	}
     ```

    However only `undoneEdits` or `appliedEdits` can be set, not both at the same time. The proposal would be change it to something like:

    ```ts
	export enum CustomDocumentRevertType { 
		Undo,
		Redo
	}

	interface CustomDocumentRevert<EditType = unknown> {
		readonly type: CustomDocumentRevertType;

		/**
		 * List of edits that were undone / redone to get the resource to its last saved state
		 */
		readonly edits: ReadonlyArray<EditType>;
	}
    ```

**Comment by jrieken** [comment]
> For example, if you implement an editable custom editor, we force you to implement a CustomEditorDelegate.undoEdits method. 

Reversed that means that someone cannot implement a custom editor in case the underlaying library only supports saving. E.g they would be forced to implement fake-undo doing nothing or not be an editor. For usability,  I think it's better to then say "Editor Foo from extension Bar doesn't support undo/redo"
