### ISSUE TITLE
Extension not synced indicator looks like a button and shows click feedback but does nothing

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#93989]
#93801

Version: 1.44.0-insider (user setup)
Commit: d7d1147d6b764a48b789000c03088ee9afabcd8a
Date: 2020-03-31T08:23:56.446Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

---

It probably shouldn't be right next to a functioning button if it looks like one? Picked below is right click feedback.

![image](https://user-images.githubusercontent.com/2193314/78051750-00131b80-7333-11ea-9ef4-7afb41e85eaf.png)

Alternatively, clicking it could open a quick pick to sync again?

**Comment by roblourens** [comment]
That's a good point about it being right next to the gear button

**Comment by sandy081** [comment]
@Tyriar What do you mean by click feedback? Does the mouse pointer changing it for you?

**Comment by Tyriar** [comment]
@sandy081 left mouse flashes the icon brighter briefly, right mouse makes the icon bright until released (see the white/grey color if different in the screenshot above).

**Comment by sandy081** [comment]
Yeah I observe it but I do not see where this change is coming from. Looks to me very subtle. Mouse gesture does not show pointer on this which is the main feedback. 

> clicking it could open a quick pick to sync again?

Enabling it hides the icon which might not be expected behaviour for the button. I think we shall either make it a toggle button or leave it as it is now. 

I prefer current approach - indicating the state using icon which is not new.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/10746682/78185865-08bb3d00-746c-11ea-9fc7-65d5b3a5d7f8.png">

**Comment by misolori** [comment]
If we're not wanting to make this clickable then we should disable the pointer events on this item and make it strictly an indicator.

If we want this to be clickable, we could surface a confirmation dialog asking the user if they want to sync that extension.

**Comment by sandy081** [comment]
> If we're not wanting to make this clickable then we should disable the pointer events on this item and make it strictly an indicator.

Agreed. 👍

**Comment by sandy081** [comment]
Removed pointer events on disabled icons in extensions view.

**Comment by sandy081** [comment]
This change was reverted as it is causing hovers not to be shown - https://github.com/microsoft/vscode/issues/99105

Not sure how important it is to not to have click feedback instead of having an hover.  Hence keeping this closed as won't fix. If there is another way to fix it please let me know I am open to reopen it.

**Comment by sandy081** [comment]
Fixed by b9833bb962d9831b329323967a7b86a55c7d08fa

Removed the sync ignored icon from the action bar and moved into the the extension header (first row) as detail. In extension editor, made the sync ignored icon a dropdown action to toggle syncing extension.

<img width="839" alt="image" src="https://user-images.githubusercontent.com/10746682/98014575-1b2f9780-1dfc-11eb-8a15-339ba31feaa0.png">
