### ISSUE TITLE
[Feature Request] Wire up new debug console icon to be configurable by extensions

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#94063]
originally opened here https://github.com/PowerShell/vscode-powershell/issues/2593

![image](https://user-images.githubusercontent.com/2644648/78075426-614de580-7359-11ea-933d-0bc11027d698.png)

First time I'm seeing this little terminal icon... it _looks_ like it's just a short cut to the Debug Console... This is not ideal because not every debugger uses the Debug Console some use an integrated terminal. This will be confusing for users.

I don't think there's any sort of configuration for us to say "hey jump to this terminal instead of the Debug Console". But it's brand new so I may be wrong.

Not using the Debug Console is a totally valid thing to do:
![image](https://user-images.githubusercontent.com/2644648/77936197-6b8fb700-7267-11ea-92ef-93e8ccf2a6bb.png)
> from https://microsoft.github.io/debug-adapter-protocol/overview

**Comment by isidorn** [comment]
@TylerLeonhardt this is a valid point. Thus keeping this open as a feature request and we might change this in the future. 
fyi @weinand

**Comment by weinand** [comment]
@TylerLeonhardt @isidorn some clarifications:
- the "terminal icon" in the debug viewlet is nothing new. It was there since the beginning of time (when VS Code did not have an integrated terminal).
- the icon represents the "debug console" and REPL, not a terminal.
- the "debug console" is a mandatory part of the DAP adapter protocol. Output events go there and VS Code's generic REPL implementation uses it.
- the "debug console" is surfaced in VS Code's extension API.
- even when a Debug Adapter does not support to launch the target in the debug console, the REPL and the Output events will always end up there. 

From this it is clear that the debug console and the icon representing it, is part of VS Code's debugger architecture. We are not planning to make this configurable.

But we are open to make it possible for extensions to add additional "icons"...

**Comment by TylerLeonhardt** [comment]
@weinand and @isidorn thanks for the quick reply. 

> the "terminal icon" in the debug viewlet is nothing new. It was there since the beginning of time (when VS Code did not even had an integrated terminal).

I'm aware of the terminal icon. We leverage it in the PowerShell extension in the satus bar:

![image](https://user-images.githubusercontent.com/2644648/78161882-f5bc5480-73fa-11ea-96dd-186a196fb9d5.png)

which, when clicked, allows you to change the version that is used in the PowerShell Integrated Console (a terminal instance that appears in the VS Code Integrated Terminal).

> the icon represents the "debug console" and REPL, not a terminal.

This might be true from the VS Code perspective, but that icon lives as a part of vscode-icons and it seems that extension authors are encouraged to reuse icons where it makes sense and in our case it makes sense to reuse the `console` icon for our needs.

> the "debug console" is a mandatory part of the DAP adapter protocol. 

Just some side feedback, this is not clear on https://microsoft.github.io/debug-adapter-protocol/overview

especially with the screenshot I posted from that link above that says you can launch in an integrated console instead of leveraging the debug console.

#### Anyway... 

This feature request was just one suggestion.

Ideally, VS Code could have an icon that specifically represents the Debug Console a little better (adding a little bug on it or something... but this is probably where we bring @misolori in) rather than using the generic "console" icon especially since there's a debug console and an integrated terminal now.

> But we are open to make it possible for extensions to add additional "icons"...

This is also something that would be ideal to help customers who are confused by the current experience.

**Comment by misolori** [comment]
> Ideally, VS Code could have an icon that specifically represents the Debug Console a little better (adding a little bug on it or something... but this is probably where we bring @misolori in) rather than using the generic "console" icon especially since there's a debug console and an integrated terminal now.

Funny you mention that because we just went through an iteration and did for our the debug console in dynamic views (see https://github.com/microsoft/vscode/issues/92590#issuecomment-603291917) so we added this icon to our icon set:

![image](https://user-images.githubusercontent.com/35271042/78165676-89dcea80-7400-11ea-8c1b-6538e93939a1.png)

So i wonder if it makes sense to update this icon in the debug viewlet as well?

**Comment by TylerLeonhardt** [comment]
@misolori you're awesome!

**Comment by isidorn** [comment]
@misolori yes, as we aleardy discussed it makes sense to update the icon. I will do that right now - since that icon is just better.

**Comment by isidorn** [comment]
Pushed via 56df825f84
