### ISSUE TITLE
Outdent issue with Typescript

### ISSUE THREAD

**Issue by normalser** [Microsoft/vscode#9409]
- VSCode Version: 1.4.0-insider and 1.3.1
- OS Version: OSX

Steps to Reproduce:

1 - Highlight

![image](https://cloud.githubusercontent.com/assets/1723815/16900928/d65d4722-4c01-11e6-97bf-88e73030c606.png)

2 - Outdent with Cmd + [

Result (first issue):

![image](https://cloud.githubusercontent.com/assets/1723815/16900932/ea5d5794-4c01-11e6-913c-0834fb60ac20.png)

3 - Outdent again with Cmd + [

Result (second issue):
![image](https://cloud.githubusercontent.com/assets/1723815/16900936/fb834c4a-4c01-11e6-883d-240859fc6625.png)

Expected behavior:

First outdent:
![image](https://cloud.githubusercontent.com/assets/1723815/16900940/1357a3ac-4c02-11e6-9b39-947596c5ae67.png)

Second outdent:
![image](https://cloud.githubusercontent.com/assets/1723815/16900942/226a08f8-4c02-11e6-9901-4ca94f443515.png)

**Comment by weinand** [comment]
@wallverb I can not reproduce this problem.
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by wallverb** [comment]
@weinand here are the steps to recreate:

1. `mkdir test`
2. `code --disable-extensions test`
3. Create file `test.ts`
4. Paste this into `test.ts`

```
const data = {
  "typeName": "chart",
      "data": {
        "header": "my title"
      }
}



export class Sidebar {
    renderLink() {
        return {
            test: true
        }
    }
}
```

5 - Try to outdent: 

![image](https://cloud.githubusercontent.com/assets/1723815/16901158/d7b45aa0-4c08-11e6-979f-b88103df709d.png)

If works then proceed to step 6

6 - Close VSCode
7 - `code --disable-extensions test`
8 - Try to outdent again

I'm getting the issue from above screenshots

**Comment by weinand** [comment]
@wallverb I can reproduce with your snippet. This problem is independent from TypeScript.

It uses an inconsistent indentation: 6 lines seem to use 4 spaces for one indentation level, 3 lines use 2 spaces. Since you are probably using the default editor setting `"editor.detectIndentation": true`, VS Code determines the tab size to be 4 (you can see this in the editor's status bar at the bottom).

Since the outdent operation has two move the lines to valid tab positions, the result is unexpected but correct.

Your expected behaviour would require a tabSize of 2. To achieve this, you will have to use these settings:

```ts
"editor.tabSize": 2,
"editor.detectIndentation": false
```

**Comment by wallverb** [comment]
Right, I knew it was related to mix of 2 spaces and 4 spaces tabs - but even that assuming that VSCode detected `Spaces: 4` it shouldn't "break" children

In other words: (assuming `Spaces: 4`)

Starting state:
![image](https://cloud.githubusercontent.com/assets/1723815/16901722/6fbf2130-4c19-11e6-96c4-85cf9c0b8829.png)

Current outdent operation results in:

![image](https://cloud.githubusercontent.com/assets/1723815/16901734/b0b2cc3c-4c19-11e6-90f5-711985797c59.png)

(notice how children got unaligned)

Ideal situation would be if VSCode could "fix" the indentation difference and for example create this output:

![image](https://cloud.githubusercontent.com/assets/1723815/16901753/08ecc6aa-4c1a-11e6-8e20-7b34753bd860.png)

(`"data"` was only moved by 2 spaces left to fit into 4 spaces tab and children got "fixed")

or at least just move everything by 2 spaces to the left (so `"data" follows the 4 spaces tab) or (what Atom does) - just move everything 4 spaces to the left - without "breaking children"

**Comment by alexandrudima** [comment]
This issue touches on two topics:

* should outdent "dumbly" remove x spaces from each line -- today it tries to snap code into tab stops.
* should outdent be a no-op if not all lines have leading whitespace.

I think both behaviours have pros and cons. i.e. I have a feeling they should be expressed as settings.

**Comment by lewisl9029** [comment]
IMO dumb indentation should be the default, since that's the default behavior for most editors, and is least likely to break existing formatting. Especially in languages like Clojure where partial indents are very prevalent (see https://github.com/Microsoft/vscode/issues/15598).

That's my 2c, but as long as it's configurable at all as a setting, I can live with it.

**Comment by BillDenton** [comment]
Similar problem in C++ (also C). For example,
![image](https://cloud.githubusercontent.com/assets/17859340/22344051/71a5c08c-e3f2-11e6-9eea-a88c5a6ebdd7.png)
Do outdent:
![image](https://cloud.githubusercontent.com/assets/17859340/22344098/a0acd5be-e3f2-11e6-93ff-0a896f186ecf.png)
Second parameter was aligned, now isn't. A dumb indentation should be default. This would make it work as I expect, i.e. not change the layout. When one of the lines doesn't contain whitespace either stop working or start stripping whitespace (in tab size steps) from the other lines. This is behaviour in SlickEdit, which I find useful occasionally.

**Comment by alexandrudima** [comment]
Setting `"editor.useTabStops": false` gives the desired behaviour. It has been in since quite a while, I forgot to update this issue.
