### ISSUE TITLE
Timeline pin state

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#94092]
Issue Type: <b>Feature Request</b>

Testing https://github.com/microsoft/vscode/issues/93819

Related to https://github.com/microsoft/vscode/issues/94091.

1) Open a timeline from a file in the explorer
2) Hover over the timeline titlebar
-> you see

![image](https://user-images.githubusercontent.com/4674940/78087916-6588fb80-7377-11ea-8af9-73ab163e3ceb.png)

The unpin icon has a couple of issues:
-> The action icon indicates the current state: "I don't follow the active editor" rather than the action it represents.
-> The eye icon to me is not obvious. I have to use it to figure out what it's doing.

I propose we explore using the concept of "pinning" with an appropriate visual presentation.

VS Code version: Code - Insiders 1.44.0-insider (d7d1147d6b764a48b789000c03088ee9afabcd8a, 2020-03-31T08:22:34.682Z)
OS version: Darwin x64 18.7.0
Remote OS version: Linux x64 5.0.0-1022-azure
Remote OS version: Linux x64 5.0.0-1022-azure

**Comment by misolori** [comment]
Funny, I also filed https://github.com/microsoft/vscode/issues/94049 today and agree

**Comment by eamodio** [comment]
I'm a little concerned with using the "pinned" metaphor, as I would expect "pinning" a view, would stop the view from collapsing or something along those lines. I feel like what you are doing is tracking or following -- and we use the follow terminology with the Outline view -- "Follow Cursor"

Visual Studio use the "Track" terminology -- they have a "Track Active Item in Solution Explorer" setting

**Comment by misolori** [comment]
The action `Toggle Active Editor Following` is really oddly phrased, especially since the "follow" concept is really new to the editor. Follow Cursor is different because as you move your cursor the view gets updated. That is not the case in the timeline view because the view doesn't change at all. The action basically means "Stay here and don't move/change", and that resembles the "pinned" metaphor more. I'd almost argue that the "follow" metaphor contradicts the Outline view because it doesn't follow you wherever you go, which is what that actual word means.

I think something like "Pin Active Editor" feels more appropriate.

**Comment by eamodio** [comment]
I'm confused -- this is very similar to the _Follow Cursor_ of the Outline view -- just less granular, instead of following the cursor position exactly it is following the cursor focus. And the view will update automatically as focus changes, just like the Outline does when the cursor and/or focus changes.

**Comment by eamodio** [comment]
If we do decide to switch to a "pin" metaphor we will need a pin/unpin icon -- we currently only have 1

**Comment by misolori** [comment]
We can certainly create a new "pin" and "unpin" icon. I think this comes down whether that's the direction we want to head towards (which I'm personally in favor of doing).
