### ISSUE TITLE
Event when vscode quit.

### ISSUE THREAD

**Issue by azumikav** [Microsoft/vscode#941]
is it there a way to get an event, like onDidCloseTextDocument, when vscode is about to quit?

**Comment by alexandrudima** [comment]
we need to implement calling `deactivate`

**Comment by alexandrudima** [comment]
With 98473e0e88cecd52ba44551d512efe445b6af11e, VSCode's extension host will now call `deactivate()` if extensions export it and call `dispose()` on `ExtensionContext.subscriptions` on shutdown, then will wait 1s before exiting

**Comment by remy-barros** [comment]
And what if we need to do some more complex stuff on deactivation? Something that takes some time like sync files in ftp server? Is there a way to delay vscode closing proccess?

**Comment by alexandrudima** [comment]
@dbaeumer and I did a change where you can return a promise from the `deactivate` function. The VSCode extension host will go down in 10 seconds regardless if your promise completes or not (we must have a time box). If you are doing data critical things in the `deactivate`, I believe the approach is wrong, perhaps you could always save the files to a temporary location and synchronize at better times than on shut-down. Also, the `deactivate` is not the time to veto or prompt for saving, etc. `deactivate` means VS Code is going down or has went down due to a crash. If you want to have some sort of veto API, then please create a new issue asking for it.
