### ISSUE TITLE
Not sure Timeline Open Changes button is needed

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#94107]
- VSCode Version: 1.44 Insiders
- OS Version: Windows

Found while testing #93819

I found the Open Changes button confusing as initially I thought it would do something different than the single click behavior. It also pushes the history date to the left.

![image](https://user-images.githubusercontent.com/12818376/78092089-95d69700-7383-11ea-8826-ba0928438ca9.png)

I think most users will quickly discover that single click or Enter, open the diff view so I don't think we need the extra button.

If we keep the Open Changes button, can it be placed to the left of the history date? That would keep the date from jumping to the left and is more in line with the Source Control view item buttons.

**Comment by eamodio** [comment]
I guess one thing up for discussion is whether or not a click behavior on the item makes sense. With the `git-history` source, it does, because it will open up a diff (similar to existing SCM behavior), but other sources there might not be any valid click behavior -- and since the items will be inter-mixed it might feel like an odd user-experience. So I've been on the fence about disabling the click behavior and instead rely on an action button. /cc @misolori thoughts?

As for moving the commands to the left of the date, I'm definitely not a fan of that because it would cause the location of actions to move around based on the length of the timestamp text.

**Comment by misolori** [comment]
It's really hard to decide when we don't really know what other providers will do. Nearly every list item has a default click action so I would default to that experience. Also, having duplicate actions for the list and an action is odd and not something I've seen done so I'd hide the compare one. 

As for the text moving, in the suggest widget we truncate the text on the right and show the icon on hover:
![image](https://user-images.githubusercontent.com/35271042/78194903-32a43d80-7433-11ea-9497-17bd0bcfe112.png)
