### ISSUE TITLE
Workspace folders from different providers

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#94191]
When I use LSIF together with WSL I always get this message:

![capture](https://user-images.githubusercontent.com/1931590/78168196-cedc3d80-744f-11ea-8226-62620335a4bc.png)

Why do we have this limitation? I don't see this under Windows since there I have a normal file provider.

**Comment by bpasero** [comment]
From https://github.com/microsoft/vscode/commit/175580a76d3df50f85464af6c5bb8e9772ec4d11

**Comment by dbaeumer** [comment]
@isidorn can you explain the underlying reason for this.

**Comment by isidorn** [comment]
@dbaeumer we do not allow workspace folders with different schemas. We always had this limitation - the exact reason I forgot to be honest.
Here are some issues with more details
https://github.com/microsoft/vscode-remote/issues/1608
https://github.com/microsoft/vscode/pull/75273
Also @aeschli might know more since I remember him being the original person that I discussed this with.

**Comment by aeschli** [comment]
@isidorn We want to prevent that local folders are added to remote workspaces. Your check prevents to much.
Can you change the check to
```
if (this.environmentService.configuration.remoteAuthority) {
   foldersToAdd = foldersToAdd.filter(f => f.uri.scheme !== file);
}
```
also remote folders from different remotes should also be disallowed:
```
const remoteAuthority = this.environmentService.configuration.remoteAuthority;
if (remoteAuthority) {
   foldersToAdd = foldersToAdd.filter(f => f.uri.scheme !== Schemas.file && (f.uri.scheme !== Schemas.vscodeRemote || f.uri.authority === remoteAuthority));
}
```

**Comment by isidorn** [comment]
@aeschli thanks for refershing my memory.
Yes, we can loosen the check. Let's do that start of next week.

**Comment by dbaeumer** [comment]
@isidorn & @aeschli Thanks. Will make my LSIF live easier.
