### ISSUE TITLE
VSCode touches file twice when saving file

### ISSUE THREAD

**Issue by ViktorHofer** [Microsoft/vscode#9419]
- VSCode Version: 1.3.1
- OS Version: Windows 7 Enterprise 64-Bit

Steps to Reproduce:

1. NodeJS watcher on file (e.g. watchify with browserify)
2. Update function gets called twice.

When editing the file with notepad, the watcher only fires one update.

Thanks for the great tool!! :+1:

**Comment by ViktorHofer** [comment]
@bpasero @weinand any udpates?

**Comment by weinand** [comment]
@joaomoreno since you are looking into this area: do you have any insights into this issue?

**Comment by joaomoreno** [comment]
Yeah something is definitely off here. Here's a process log of a simple save in Windows:

![image](https://cloud.githubusercontent.com/assets/22350/17175840/09e49626-540a-11e6-8c09-5f0c258eef14.png)

There are a total of 13 `CreateFile` events, when only one is actually a `Write` operation. The second watch fire might be due to the `Generic Read` operation... but I'm just speculating here. All other operations are `Read Attributes`, which seem to relate to `stat` calls.

One interesting optimisation to be done here is to call `fs.open` and use the file descriptors to call operations such as `fs.write`, instead of relying in the higher level functions such as `fs.writeFile`, which create many `CreateFile` lower level operations.

**Comment by ViktorHofer** [comment]
Hey, I just found out that the issue could be related to the way how windows handles read and write implementations and the nodeJS implementation of fs.watch. 

http://stackoverflow.com/questions/12978924/fs-watch-fired-twice-when-i-change-the-watched-file
http://stackoverflow.com/questions/12978924/fs-watch-fired-twice-when-i-change-the-watched-file

**Comment by bpasero** [comment]
I think this is nothing we can prevent because the file gets truncated before the write and then written to. We use fs.writeFile() (same as other editors using node.js) and if this results in too many file events, I suggest to file an issue against node.js.

**Comment by bpasero** [comment]
This is expected as outlined in https://github.com/nodejs/node/issues/6112 and I do not think changing to other fs primitives would change this.

**Comment by jskorepa** [comment]
This could be prevented by creating temporary and then moving it over original (gedit does it this way).
There obviously are cases where this does not work but it would be great if that was a configuration option or if it tried to use renaming approach first and if it fails use current approach.
