### ISSUE TITLE
Placement of "cursor line" incorrect in scrollbar

### ISSUE THREAD

**Issue by mattfan00** [microsoft/vscode#94194]
- VSCode Version: 1.43.2
- OS Version: macOS 10.13.6

Steps to Reproduce:

1. This issue will be focused on the scroll bar and the line that shows where your cursor is in the document. Here is a picture of what I am referencing: 

![image](https://user-images.githubusercontent.com/30060256/78168389-d7b41b80-741d-11ea-95bb-34a7a539991e.png)

I will refer to this white horizontal line in the scroll bar section as the "cursor line"

2. Here is a video of the issue. The problem is that there is a gap in between the cursor line and the bottom of the scroll bar when scrolling down. However, when you scroll upwards, there is no gap.

![ezgif-6-f428f543eb34](https://user-images.githubusercontent.com/30060256/78169483-72f9c080-741f-11ea-8b99-dca90002115e.gif)

Does this issue occur when all extensions are disabled?: Yes

**Comment by smithjosh115** [comment]
I would like to take a look at fixing this

**Comment by alexdima** [comment]
The reason is that there is always one more line when the cursor reaches the bottom of the viewport: this revealing logic is because there is often a horizontal scrollbar that would otherwise always be on top of the last line when editing.

![TO_UPLOAD](https://user-images.githubusercontent.com/5047891/78225276-3cc54b00-74ca-11ea-8377-9038272dd16b.gif)
