### ISSUE TITLE
Unsure what values to use for "fonts" in -product-icon-theme.json

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#94209]
Refs: #93798

What should `style`, `weight`, and `size` be set to? Should they be unset unless they are specifically needed? What would `size` even do? Isn't the size based on the usage? Also, should there be intellisense for `style` and `weight`?

For `src`, what formats do we support? Should there be intellisense for them?

**Comment by sbatten** [comment]
I was verifying an issue around this and spent a long time having `otf` as the format only to realize that we are just putting the format directly into the css so the supported values are listed here: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src meaning that we should put `opentype` instead of `otf`. I think this should be documented and ideally in the hover.

**Comment by aeschli** [comment]
To verify:
- open a product icon theme file, e.g. https://github.com/microsoft/vscode/blob/master/extensions/vscode-colorize-tests/producticons/test-product-icon-theme.json#L20
- you get better hovers, code assist and verification for font id, format, weight and style
