### ISSUE TITLE
Why not using paging by scrolling

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#94258]
Testing #93820

I see paging is implemented using a special action/label `Load More...`. Why did not we consider implementing paging by scrolling just like how extensions viewlet is done?

Is this because of the current paging API design? If so the proposal here - https://github.com/microsoft/vscode/issues/94178 will support paging by scrolling.

**Comment by eamodio** [comment]
It was discussed, but we chose this simpler path to ship and when @isidorn suggested the extension viewlet paging, it seemed to have 2 requirements I couldn't meet -- 1) Only supports list items and we are thinking about possibly allowing tree items and 2) it needs to know the count of all the elements up front.

Although because of a recent major refactor to how the timeline is rendered #2 might not be an issues, but #1 would still be going forward.
