### ISSUE TITLE
[folding] enhancement of display folding regions in c & typescript code

### ISSUE THREAD

**Issue by ret394** [microsoft/vscode#94265]

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by ret394** [comment]
Thank you for being here, and apologies for the delayed response.

why does it need indentation to work?

**Comment by jrieken** [comment]
Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by ret394** [comment]
well, that was brief and I hope the point is clear. spent some time and found this to explain the jargon https://code.visualstudio.com/docs/editor/codebasics#_folding

>Folding regions are by default evaluated based on the indentation of lines.

that is the issue. see for examples https://gist.github.com/ret394/e6be9ed47de8201401605acd842088b3

hope it helps clarify things. take regular breaks .

best of luck!

**Comment by aeschli** [comment]
By default, VSCode has indentation based folding.
Some languages have language aware folding, such as TypeScript, but not C++.

That's why your example works in TypeScript but not in C++.

The request that C++ also adds language aware folding is https://github.com/microsoft/vscode-cpptools/issues/407

Is that what you meant? if not, please add a code sample, not which language mode you are, what you see and what you expect (screenshots help)

**Comment by ret394** [comment]
"language aware folding" does solve the issue for C++. thanks.

Thank you for being here and sharing your knowledge.
thanks. have a nice day. keep up the great work. 👏

[ret394](https://github.com/ret394).
