### ISSUE TITLE
[jade] Jade/Pug #id syntax highlighting

### ISSUE THREAD

**Issue by cg-cnu** [Microsoft/vscode#9436]
- VSCode Version: 1.3.0
- OS Version:  CentOS Linux release 7.1.1503 (Core)

![vscodejadeerror](https://cloud.githubusercontent.com/assets/2767425/16912859/6e80e826-4d04-11e6-98bd-a5c60e1713a0.png)

Jade/pug allows to write **#Id** along with **.class**
As seen in the image, **sizing-addon1** dosen't have any syntax color( expected blue, the same as .class )

**Comment by aeschli** [comment]
Fixed in the January build.
#id is now the same color as the .class.
![image](https://cloud.githubusercontent.com/assets/6461412/22702084/d89cf636-ed5f-11e6-8805-12827d0406a7.png)

Note: .class, #id and data-bind get all the same scope from the [Pug text mate grammar](https://github.com/davidrios/jade-tmbundle). Please file issues there.
