### ISSUE TITLE
JS: incorrect enum hints and member dropdown when `@enum` on a new line

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [microsoft/vscode#94387]
Version: 1.43.2
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Declare a JS object as "enum" in JSDoc comment, one with `@enum` tag on the same line and one with tag on a new line
2. See first enum is recognized correctly while second isn't (screenshots)

Does this issue occur when all extensions are disabled?: Yes

```js
'use strict';

/** Enum OK @enum {Number} */
const ENUM1 =
{
	ONE: 1,
	TWO: 2
}

/**
 * Enum NOT OK
 * @enum {Number}
 */
const ENUM2 =
{
	ONE: 1,
	TWO: 2
}

ENUM1.
ENUM2.
```

![Hint_OK](https://user-images.githubusercontent.com/1469388/78371822-248c2380-75d1-11ea-961a-dc82f2eaa5dc.png)
![Hint_NotOK](https://user-images.githubusercontent.com/1469388/78371818-23f38d00-75d1-11ea-9e25-26d53e3be53e.png)
![Dropdown_OK](https://user-images.githubusercontent.com/1469388/78371815-23f38d00-75d1-11ea-811b-fe92304060dc.png)
![Dropdown_NotOK](https://user-images.githubusercontent.com/1469388/78371813-22c26000-75d1-11ea-9090-1f98312693d3.png)

**Comment by mjbvz** [comment]
This is happening because you have the unclosed `Enum1.` on the line above `Enum2`. This means you are actually triggering suggestions for `Enum1.Enum2`, not on `Enum2` itself.

Once you fix that, both case work fine:

<img width="1360" alt="Screen Shot 2020-07-09 at 11 45 58 AM" src="https://user-images.githubusercontent.com/12821956/87078715-ead34600-c1d9-11ea-8506-d625d3b59c5a.png">
