### ISSUE TITLE
JavaScript: try-catch in self-invoked functions makes the code afterwards unreachable

### ISSUE THREAD

**Issue by IiroUllin** [microsoft/vscode#94426]
- VSCode Version: 1.43.2
- OS Version: Windows 10

Steps to Reproduce:

1. Paste this code into the editor:

let b = ((x) => {
	try {
		return x
	}
	catch (e) {
		return e		//	now this, actually, will never be called
	}
})('c');				//	all this does is assign b = 'c'

d = "everything is marked unreachable from this point on";
console.log('except it definitely is reachable! ...b = '+b);

2...

Does this issue occur when all extensions are disabled?: Yes
![glitch](https://user-images.githubusercontent.com/63135513/78417661-2d88ef00-75e9-11ea-919b-f58b9d108987.png)

**Comment by spahnke** [comment]
I can reproduce with the TypeScript language server at 3.8.2, but not with 3.9-nightly so this is likely fixed in the next version of TypeScript. You can try that out by installing the [TypeScript and JavaScript Nightly extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) which only affects the language server features of the editor.

**Comment by IiroUllin** [comment]
Confirmed: TS 3.9... seems to fix it (after restart). Thanks for this suggestion!
