### ISSUE TITLE
Framerates should not be hardcoded in VS Code

### ISSUE THREAD

**Issue by eligrey** [microsoft/vscode#94427]
- VSCode Version: 1.43.2
- OS Version: Darwin x64 19.4.0
- Device setup: 4K 120hz DisplayPort 1.4 monitor + MacBook Pro 16 running Mac OS Catalina 10.15.4 

VS Code feels like it is locked to 60fps on my 4k 120hz monitor. Dynamic refresh rate support is an important accessibility feature against eye strain for users with high refresh rate monitors.

I noticed that the scrolling framerate is hardcoded here at 16ms per frame (60fps): https://github.com/microsoft/vscode/blob/18b8ef01b85d867d74f7314637c3de89e46227d8/src/vs/base/browser/dom.ts#L354

Many CSS transitions in the editor also seem to be running at 60fps due to a hardcoded configuration somewhere.

Please dynamically adjust to the current monitor's refresh rate instead of using these constant values.

Does this issue occur when all extensions are disabled?: Yes/No

Yes

**Comment by alexdima** [comment]
There are no animations that depend on that constant. That constant is used only in the utility named `addDisposableThrottledListener`. That utility is used when listening for mouse input, like for example clicking on the scrollbar and dragging or when clicking in the editor and dragging to create a selection. This is an optimization to not handle too many incoming mouse events in too short of a time in order to remain responsive in the face of many incoming input event. IMHO this does not influence the quality of operating the editor, but I thank you for your vigilance in tracking this down.
