### ISSUE TITLE
Terminal: moving panel right leaves prompt in weird place

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#94501]
This was running out of sources:

![image](https://user-images.githubusercontent.com/900690/78528661-309a0000-77e0-11ea-9bdf-200c39a8e14d.png)

**Comment by Tyriar** [comment]
I can't repro on macOS with bash or zsh. What state was the terminal in before you moved it?

**Comment by bpasero** [comment]
I am not sure, normal? This is after fresh start running out of `master`

![Kapture 2020-04-06 at 14 16 11](https://user-images.githubusercontent.com/900690/78557511-365c0980-7811-11ea-98b4-ff8b2272d22b.gif)

**Comment by bpasero** [comment]
Hm, cannot reproduce with a fresh user data dir. How can I debug this?

**Comment by Tyriar** [comment]
What I suspect is happening is that zsh is doing this as a reaction to the line size being reduced. This could be confirmed by enabling escape sequence logging https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging, that should log out how zsh reacts after the terminal resize happens.

You could also check what happens when reducing the window width while the panel is on the bottom.

**Comment by bpasero** [comment]
@Tyriar yeah that seems to trigger it as well, just having smaller width for panel:

![image](https://user-images.githubusercontent.com/900690/78564622-00bd1d80-781d-11ea-9165-bffed112f1b5.png)

**Comment by bpasero** [comment]
Output:

```
[Extension Host] debugger inspector at chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5870/901cda19-6248-4d63-a05a-b8cca71fde55
2/Users/bpasero/Development/Microsoft/monaco/node_modules/xterm/lib/xterm.js:1 xterm.js: parsing data 

[0m[27m[24m[J~/Documents/ticino-playground> 
```

**Comment by Tyriar** [comment]
Hmm I guess not then, that does the following:

[0m: clear char styles
[27m: do not invert colors
[24m: do not underline
[J: erase current line and below
Reprint prompt

If you inspect the element does the terminal container fill the view? Does cmd+a select everthing?

**Comment by bpasero** [comment]
`Cmd+A`

![image](https://user-images.githubusercontent.com/900690/78588473-01ff4200-783f-11ea-93c4-25fbfa4bdd1a.png)

Inspect:

![image](https://user-images.githubusercontent.com/900690/78588497-0c214080-783f-11ea-93e6-c537d28a2ea5.png)

![image](https://user-images.githubusercontent.com/900690/78588509-117e8b00-783f-11ea-8541-b1cd817d410d.png)

**Comment by bpasero** [comment]
And I cannot fix it even when resizing:

![Kapture 2020-04-06 at 19 45 22](https://user-images.githubusercontent.com/900690/78588586-307d1d00-783f-11ea-9da8-576e25c87b06.gif)

**Comment by Tyriar** [comment]
😕 

Ok so that tells us that xterm.js isn't resizing correctly. I just tried to repro again with all renderers but couldn't still. Does it change depending on the renderer you're using?

I did just made changes in this area in https://github.com/microsoft/vscode/commit/5b0460a67edb3e326fe5cdbe1307e9e6e2e01928.

Could you try change these lines:

https://github.com/microsoft/vscode/blob/831fe1f617b70d557bc9a28e231999ff29cb058a/src/vs/workbench/contrib/terminal/browser/terminalConfigHelper.ts#L190-L191

To:

```ts
charHeight: xtermCore._charSizeService!.height!,
charWidth: xtermCore._charSizeService!.width!
```

And see if that fixes the problem?

**Comment by bpasero** [comment]
@Tyriar yes, that fixes it. Btw I am running with zoom level 1 always.

**Comment by Tyriar** [comment]
@bpasero thanks, I think that's the piece I was missing 😃 

I can kind of reproduce, it's only down a little bit but that might be because of the font family or monitor size.

**Comment by Tyriar** [comment]
@bpasero hmm, maybe not... Could you debug and take a screenshot of the values of: `xtermCore._charSizeService` and `xtermCore._renderService.dimensions`?

**Comment by bpasero** [comment]
Can you try with `"terminal.integrated.lineHeight": 1.4,`
