### ISSUE TITLE
User Settings: files.encoding not working if opened from contextmenu

### ISSUE THREAD

**Issue by Andyriod** [microsoft/vscode#94519]
- VSCode Version: 1.43.2 (user setup)
- OS Version: Windows 10

Steps to Reproduce:

1. configure language specific option for objectpascal
2. set "files.encoding" : "windows1252"
3. Open .pas-file from the VSCode File-Open Menu - it opens with windows1252 encoding  as expected.
4. Open .pas-file from the File-Explorer ContextMenu - it opens with utf-8 encoding but I set it to open with windows1252!

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
> Open .pas-file from the File-Explorer ContextMenu - it opens with utf-8 encoding WRONG

How exactly?

**Comment by Andyriod** [comment]
@bpasero - please see my edit

**Comment by bpasero** [comment]
> Open .pas-file from the File-Explorer ContextMenu - it opens with utf-8 encoding but I set it to open with windows1252!

I was asking, what context menu?

**Comment by Andyriod** [comment]
I don't understand your question?!? 
Explorer.exe (aka FileExplorer or FileManager), go to any xyz.pas file, right click and than "Open with Code".

**Comment by bpasero** [comment]
Understood. This is likely an issue with timing: when you open the file into a new VSCode instance, at the time the file opens, we are not aware of the object pascal extension because it only loads and activates later. But at that point the file is already opened with the default encoding.

Does it help if you configure `"window.openFilesInNewWindow": "off"` so that the file opens into an existing instance? Does that even work to open into an existing instance?

**Comment by Andyriod** [comment]
This works!
Can I setup an encoding, not for ObjectPascal but for *.pas - files? Than the Extension must not be loaded to aware the right encoding.

**Comment by bpasero** [comment]
@Andyriod yeah we have that as open request in https://github.com/microsoft/vscode/issues/35350 and I suggest we close this one as duplicate, I do not have a better suggestion right now.
