### ISSUE TITLE
Half-width katakana does not work properly.

### ISSUE THREAD

**Issue by ta-ozaki** [microsoft/vscode#94524]
・VSCode Version: 1.43.2 (system setup)
・OS Version: Windows 10

Half-width katakana with semi-voiced dots are treated as one character.

When selecting with 'Shift + Arrow'  key
I want to select one character, but two characters are selected.

example：
selected pattern
OK | a = 1 character selected ... 1 character in 1 bytes
OK | A = 1 character selected ... 1 character in 1 bytes
OK | カ = 1 character selected ... 1 character in 2 bytes
OK | ｶ =  1 character selected ... 1 character in 1 bytes
NG | ｶﾞ = 2 character selected（ｶ + ﾞ） ... 2 character in 2 bytes

I expect 'ｶ'(1Byte) to be selected.
But up to 'ｶﾞ'(2Byte) is selected.
In previous versions, it could be treated as one character.

![image](https://user-images.githubusercontent.com/63237665/78554256-ce73e600-7845-11ea-9d18-f558a938b2e9.png)

**Comment by alexdima** [comment]
@ta-ozaki VS Code implements the Grapheme Cluster Boundary Rules as specified by Unicode at http://www.unicode.org/reports/tr29/#Grapheme_Cluster_Boundary_Rules since a few months.

I have confirmed that this is working correctly by copy pasting `ｶﾞ` in a Chrome input and in TextEdit on macOS and I cannot place the cursor in the middle of the grapheme cluster. So, it appears to me that we are working correctly.

**Comment by ta-ozaki** [comment]
Thank you for your answer.
I understand the indicated behavior.

I often edit fixed-length files.
but, this indicated behavior is inconvenient when selecting rectangles with fixed length data.
How can I be the same behavior as ver1.40.2 in the ver1.43.2?

I checked which version I had used in the past and could be used.
↓
vscode v1.40.2
![image_1_40_2](https://user-images.githubusercontent.com/63237665/78656697-bdd57580-7902-11ea-8c11-ef19773467fe.gif)

vscode v1.43.2
![image_1_43_2](https://user-images.githubusercontent.com/63237665/78656712-c3cb5680-7902-11ea-9576-73ad30f21fad.gif)

**Comment by alexdima** [comment]
@ta-ozaki It looks to me that in this case the `cursorRight` command (arrow right) is not the right primitive to use, since that moves the cursor to one logical position to the right.

The workaround is to use the `cursorColumnSelect*` commands which try (as much as possible) to create a rectangular multi-cursor selection (also available via middle mouse + drag):

```
{ "key": "ctrl+shift+alt+down",   "command": "cursorColumnSelectDown",
                                        "when": "textInputFocus" },
{ "key": "ctrl+shift+alt+left",   "command": "cursorColumnSelectLeft",
                                        "when": "textInputFocus" },
{ "key": "ctrl+shift+alt+pagedown", "command": "cursorColumnSelectPageDown",
                                        "when": "textInputFocus" },
{ "key": "ctrl+shift+alt+pageup", "command": "cursorColumnSelectPageUp",
                                        "when": "textInputFocus" },
{ "key": "ctrl+shift+alt+right",  "command": "cursorColumnSelectRight",
                                        "when": "textInputFocus" },
{ "key": "ctrl+shift+alt+up",     "command": "cursorColumnSelectUp",
                                        "when": "textInputFocus" },
```
