### ISSUE TITLE
Problems view should align counters to the right and have them always visible

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#94530]
This is now more obvious when moving Problems to the sidebar, which I'm really digging (🤘 @sbatten):

![image](https://user-images.githubusercontent.com/22350/78556541-71f5d400-780f-11ea-8bec-ba6c34000e0c.png)

**Comment by sandy081** [comment]
> This is now more obvious when moving Problems to the sidebar, 

Nothing to do with moving to sidebar. This is also same when you move panel to left or right. It shall depend on width.

**Comment by joaomoreno** [comment]
That's what I mean: this issue now becomes more obvious when we move Problems to the sidebar, which typically is more narrow.

**Comment by sandy081** [comment]
Fixed this at base viewpane layer so that other views can adopt it and be consistent. 
`.wide` class is added to `.pane-body` if viewpane is wider that 600 px.

Adopted Problems and Search views accordingly. 
Change in Search view: Wide semantics changed from 1000 to 600 px. 
1000 px is too wide hence went with 600 px after trying out. I am open to change it if someone has better suggestion.

@roblourens FYI
