### ISSUE TITLE
Terminal Panel should memorize the number of opened terminals and current directory for each of them

### ISSUE THREAD

**Issue by GuyoST** [microsoft/vscode#94545]
Issue Type: <b>Feature Request</b>

When we open multiple terminals in the TERMINAL panels, and navigate in different directories using the CD command, when we restart a workspace, this panel should remember how many terminals were opened and their current directories too, and open them again automatically.

VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Tyriar** [comment]
We explored this in the past and it was getting to complicated to solve all use cases in core so currently we defer to extensions to fill this gap, for example https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-terminals

**Comment by ArturoDent** [comment]
I like your request.  Here is only a partial workaround because you have to hardcode the directories and commands that run in them when opened. But if you frequently open a set of terminals and cd to certain directories and/or run the same commands in them see https://stackoverflow.com/questions/60621321/create-multiple-terminals-and-run-commands-in-vscode/60665510#60665510 .
