### ISSUE TITLE
Support F# Syntax Highlighting Inside Markdown Fenced Code Blocks

### ISSUE THREAD

**Issue by dend** [Microsoft/vscode#9457]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:
1. Open a Markdown (`.md`) file.
2. Add a codeblock between triple backtick code block markers, such as:

<img width="175" alt="capture2" src="https://cloud.githubusercontent.com/assets/1389609/16929441/ac24aa90-4cec-11e6-990c-8899d0efb533.PNG">
1. Notice that there is no syntax highlighting for the code block (different color for the block, that is).

This seems like a regression because a couple of version ago this was working.

**NOTE:** Disregard the `fsharp` language identifier. If you remove it, there is still no syntax highlight for the block.

**Comment by mjbvz** [comment]
I think the problem is actually just that we don't highlight F# code. Other languages work fine (omitting a language specifier results in no syntax highlighting, which is expected):

![screen shot 2016-09-27 at 2 39 49 pm](https://cloud.githubusercontent.com/assets/12821956/18892896/56b2c4d2-84c0-11e6-9c32-406dff5180af.png)


We currently have to hard code every language we can highlight inside of markdown fenced code blocks. See this change for example: 5169a9806a6873ec36260663251c984af7bfe0c2

I'm going to change the title of this bug to instead track adding F# to the list of recognized languages.
