### ISSUE TITLE
Incorrect highlighting of JavaScript bracket notations of type Function in object literal.

### ISSUE THREAD

**Issue by Hawmex** [microsoft/vscode#94597]
VSCode version: 1.43.2
OS version: Win 7

VSCode won't highlight bracket notations of type function like normal object properties of type function.

```js
const a = "a";
const b = {
  [a]: () => {}
};
```

**Comment by erickmp07** [comment]
If it's a good first issue, I'd like to try it.

**Comment by mjbvz** [comment]
This is up to each theme:

![Screen Shot 2020-04-07 at 10 45 05 AM](https://user-images.githubusercontent.com/12821956/78702065-dd49af80-78bc-11ea-96fc-29da02e01e5d.png)

VS Code correctly tokenize that code so that themes can choose how to color it. Most leave the brackets the same color as a normal property key
