### ISSUE TITLE
Breakkpoints in debugger not being set correctly when already debugging

### ISSUE THREAD

**Issue by evanoc0** [microsoft/vscode#94618]
- VSCode Version: 1.43.2
- OS Version: MacOS 10.15.4

Steps to Reproduce:

1. Run node debugger on unit tests
2. Debugger stops at a breakpoint at any other position

    The issue is in a file containing:
    ```js
    import CodeBlock from "./CodeBlock";
    import ContentProgressScroll from "./ContentProgressScroll";
    import { singleton as stateManager } from "./StateManager";

    export {
      CodeBlock,
      ContentProgressScroll,
      stateManager
   };
    ```
3. While the debugger is stopped at a breakpoint, trying to add another breakpoint on line 5 `export`, adds it at `1:8` instead and clicking again will add another breakpoint at 1:8.

This _only_ happens while stopped at a breakpoint.

Does this issue occur when all extensions are disabled?: Yes

![Gif](https://user-images.githubusercontent.com/14321104/78690345-37fbff00-78ef-11ea-932c-f708f0782a02.gif)

**Comment by weinand** [comment]
@evanoc0 what you are seeing is the expected behavior.

When the debugger is running, it will verify all breakpoints and adjust (move) them as necessary. So setting a breakpoint on line 5 is not possible because there is no code generated for the "export". The next valid code location to set a breakpoint is on line 8 and the debugger moves the breakpoint to that location.

If the debugger is not running, breakpoints are not verified and consequently they are not moved.
