### ISSUE TITLE
Should provide buttons to select/unselect all changes when preview a workspace edit

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode#94650]
**Use Case**:
When the user renames a Java file from file explorer, the Java extension would watch on `workspace.onDidRenameFiles` event, then calculate and generate a workspace edit to update its class name and references. Since it takes some time to calculate the edit, the user may perceive the file contents to be updated after a while. There is a lag between file rename and file content update. In order to improve the UX, we would show progress notification at the status bar during the calculation, and also want to try the preview API to preview the workspace edit instead of automatically applying the edit.

**Problem**:
Currently `workspace.applyEdit` interface doesn't provide an option to allow the extension to force preview the workspace edit. A workaround is to add `WorkspaceEditEntryMetadata` property to the workspace edit. Since in java language, we don't distinguish which changes need to be confirmed, in order to trigger the preview pane, i just set the needsConfirmation to true for all changes. This will make all changes unchecked in the preview tree, and the users have to check one by one if they want to apply all. This is especially not convenient for large projects, as the possible modifications include many positions.
![image](https://user-images.githubusercontent.com/14052197/78649658-531b3e80-78f0-11ea-9932-8c9eda0c88ed.png)

**Expected**:
At least, provide an easy way to bulk select the changes. Further, it would be nice to expose a client API to force preview a workspace edit and keep all changes checked by default, like what rename did (shift + enter).

**Comment by gjsjohnmurray** [comment]
As a workaround how about setting needs Confirmation on only one of your results?

**Comment by testforstephen** [comment]
that looks weird to leave a random change unchecked.

**Comment by gjsjohnmurray** [comment]
Sure, but as a workaround isn't it better than leaving them all unchecked and requiring the user to do a lot of clicking?

**Comment by jrieken** [comment]
> Since in java language, we don't distinguish which changes need to be confirmed, in order to trigger the preview pane, i just set the needsConfirmation to true for all changes.

If you have confidence in your edits, e.g they have been computed by your "compiler" and not by text-search or similar (weaker) strategies then never set the `needsConfirmation`-flag.

**Comment by testforstephen** [comment]
`needsConfirmation` is just a workaround. The effect i need is to preview all edits and preselect them all, just like what rename (**shift + enter**) did.

I need to clarify that in my user cases, the Java extension generates workspace edit and then manually calls workspace.applyEdit API to preview and apply the edit. If VS Code could add a new parameter like **forcePreview?: boolean** to the current **applyEdit** API (e.g. `workspace.applyEdit(edit: WorkspaceEdit, forcePreview?: boolean)`), and let the extension itself to use this API to control whether to preview all edits forcedly, this will also satisfy my needs!

**Comment by jrieken** [comment]
> I need to clarify that in my user cases, the Java extension generates workspace edit and then manually calls workspace.applyEdit API to preview and apply the edit.

TBH I am very confused. Is this for rename or generic code actions? Note that for generic code action we haven't done anything yet and still wonder how the affordance (similar to Ctrl+Enter with rename) would look like

> If VS Code could add a new parameter like forcePreview?: boolean to the current applyEdit API (e.g. workspace.applyEdit(edit: WorkspaceEdit, forcePreview?: boolean)), and let the extension itself to use this API to control whether to preview all edits forcedly, this will also satisfy my needs!

That's exactly not what we want. For us, showing a preview or not is a user-choice not an extension author choice. That's why for rename we have added `editor.rename.enablePreview`. For rename there is two ways to show a preview

1. *Users* sets `editor.rename.enablePreview: true` because it's their personal preference to see a preview of changes
2. Extension sets the `needsConfirmation` flag on some edits because it did *guess work* to come up with the edits

It seems like you using option 2 to enforce a certain behaviour that you desire. This is bad because it undersells your language service and it doesn't respect user choice. We have no plans to bless such behaviour. If you firmly believe that previewing changes should be the default for java-developers then your extension can ship a language-specific default value for said setting

**Comment by testforstephen** [comment]
> Is this for rename or generic code actions?

No, this is not part of any code actions. 

The scenario we want to try is for some **implicit refactoring from file explorer**. For example, when the user did some file operation through file explorer, such as rename or move, this will cause the file name or package name inconsistent with the class or package declaration in his code. The builder tool will report lots of build errors. And many users complain they need manually update many code.
 
So the Java extension wants to watch on these file events, auto computes a workspace edit and then pop up the preview panel and let the user to determine whether to apply it. 

> For us, showing a preview or not is a user-choice not an extension author choice.

I only partially agree with you on that. If it's an explicit refactor code action, the user would expect there are code changes to happen. Apply it directly would be OK. I definitely agree to give the user to choose whether to preview.

But my case is not an explicit code action. It's just a normal file operation through file explorer, such as rename file name or drag and drop, the user didn't know the extension will update their code. IMO, previewing it makes more sense than quietly apply edit. Also the computation job may take a few seconds to complete. For some big projects, it could be more than 5 seconds. Automatically update the user's code many seconds after the file operation is complete, which is also very unfriendly.

**Comment by jrieken** [comment]
Ok, understood. Thanks for clarifying and 'yes' this outside of what we have thought this feature being used for and I am unsure if it's the right place. TypeScript has a similar challenge and ships a feature which simply asks you what to do when a file has been renamed. This is how it looks:

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/1794099/79960223-72d06c00-8485-11ea-9982-baea675f031c.png">

So, they listen for file rename event (`vscode.workspace.onDidRenameFiles`) and show then shows that prompt which IMO is pretty informative and allows me to make a choice. Once it is actually going (e.g after pressing OK or when having this "always on") you see a progress message that changes are being computed and that's it. I think Java should do something similar. 

Now comes the refactor preview and user choice into play and that's the part where I said that we don't have anything yet. Again, we don't want to enable extensions to force this into your face (instead prompt *before* computing changes) but we want user to be able to express a preference and then play nice with that preference. It will likely be an additional parameter for `applyEdits` - just as you have proposed. However, it won't enable forcing but it should enable extensions to "describe/classify" their code action which we then use to decide if a preview can be shown or not.

**Comment by testforstephen** [comment]
UX discussions are always a tough thing to do. Personally i'm not a fan of dialog notification. Since the API is right there, we thought why not to have a try on the PREVIEW FEATURE. It already looks great now, just a little more improvement would make it more perfect!

**Comment by jrieken** [comment]
> UX discussions are always a tough thing to do. Personally i'm not a fan of dialog notification. 

That proves my point about personal preferences 🤓 Tho, in all fairness: If you don't like dialogs that you would select "never" or "always" in the screenshot above and you would never see it again (this updates a setting)

I also agree that this can be a use-case for the preview feature *but* only for uses that like the preview feature. I can think of the following flow

* users have a setting like `editor.codeaction.enablePreview: true | false`
* Java (or any other extension) calls `appyEdit` with some extra info that classifies the edit as "preview-able code action" (for instance has a label and so)
* VS Code checks the edit info and the user setting to decide if the preview should show or not

Now, users that don't like to see a preview will not observe the Java-rename-smarts because they use `enablePreview: false`. Now,  you can enforce the preview by using the needsConfirmation-trick which doesn't make those users happy and, in return, they might ask us to add something like `enablePreview: 'never'`.

Don't get me wrong. What you are doing is cool but I think the TypeScript-flow works pretty well for this use-case because it informs users right after rename, not after a N seconds compute-pause. Then, after the compute and once we have implemented this, VS Code can show a preview for those users that like previews

**Comment by testforstephen** [comment]
yes, adding a user setting does help for different user preferences. In addition, Java implementation is slightly different from TypeScript, some scenarios (e.g. rename package, move file to another package) are done at `onWillRenameFiles` listener, so displaying a dialog there may not be appropriate.
