### ISSUE TITLE
Problems panels use check new content instead of old

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#9467]
- VSCode Version: 1.3.1
- OS Version: OSX

![image](https://cloud.githubusercontent.com/assets/3254987/16939776/88b3ee02-4d39-11e6-8745-0e47a617f809.png)

When you view the file changes, the problems panel is report errors on the original code instead of the updated code.

**Comment by kieferrm** [comment]
I checked a couple of linters. Errors produced by TSLint don't have the issue. Error produced by jshint do have the issue. 

@sandy081 what is a problem view looking for in the problem markers?

**Comment by sandy081** [comment]
This is because, TSLint is ignoring files which are not real, like in-memory or git schema based whereas other linters or not. In this case left hand side is git-scheme based file.  

Problems view is just a representation and hence it shows all markers generated. We had a pretty good discussion around it in #7773 and decided that extensions should handle these. 
Since these files are temporary or readonly or internal, we are removing markers for such files. Otherwise, its responsibility of extensions to generate or clean up.

Duplicates #7773
