### ISSUE TITLE
launch arbitrary program from launch.json

### ISSUE THREAD

**Issue by xenoterracide** [microsoft/vscode#94698]
Goal: run `npx program` so that we don't have to know the absolute paath inside of `${workspace}/node_modules
problem: there is no way to know where `npx is installed`

solution 1: add some local file (that can be ignored), that allows variables to be set for launch.json, then you could easily set `${usrLocal}/npx`

solution 2: allow executing `env` or `which` or even just searching `$PATH`

solution 3: specifically add an option to node that is autodetected, `${npx} program`

solution 1 is probably the most flexible, and most secure

**Comment by IllusionMH** [comment]
I think it's already possible similar to debugging `npm` scripts. Starting from default config Node.js: Launch via NPM and then using `"runtimeExecutable": "npx"` and `"runtimeArgs": ["program"]`

However it might take a bit extra to pass debug argument to `node` (and requires npx 9.1.0+) See https://github.com/zkat/npx/issues/68

So most likely it should be (unable to test because my npx version doesn't support this flag)

```json
{
    "type": "node",
    "name": "Launch via npx",
    "port": 9449,
    "request": "launch",
    "runtimeArgs": [
        "--node-arg=--inspect-brk=9449",
        "program"
    ],
    "runtimeExecutable": "npx",
    "outputCapture": "std"
}
```

**Comment by xenoterracide** [comment]
I'm not sure if in some cases the --inspect-brk is needed, but that caused it to blow up for me (oh maybe it's because I forgot "port"). this however worked just fine

```
    "runtimeArgs": [
        "mocha"
      ],
      "outputCapture": "std",
      "runtimeExecutable": "npx",
      "args": [
```
thanks. I guess I'll close this, unless it should be in an example doc somewhere, then feel free to reopen.
