### ISSUE TITLE
VSCode updates show "unassigned" when shortcut has been manually unassigned

### ISSUE THREAD

**Issue by macintacos** [microsoft/vscode#94712]
Issue Type: <b>Bug</b>

Just updated to the March release of VSCode and saw this under the Accessibility update:

![image](https://user-images.githubusercontent.com/8128941/78825489-10b83700-79ae-11ea-95aa-89e0c7e4aa85.png)

I heavily modified my keyboard layout, so it's unsurprising that if they're being programmatically accessed they won't show up. Perhaps if it can't find anything, it should default to the actual action ID? Like `workbench.action.name` or something, so that it's easily searchable if I want to go and now add a new shortcut for that action?

VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-08T08:23:56.137Z)
OS version: Darwin x64 19.3.0

**Comment by isidorn** [comment]
This is due to your highly customized keybinding setup.
Though I agree with you that the unassigned is not that useful.

I think we are open to change this, here's a code pointer
https://github.com/microsoft/vscode/blob/379e732c79e6cb0241f95f0e5e45b1dc2255e7ad/src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts#L118
fyi @mattbierner as I see his name over that code

Here's what I see:
![Screenshot 2020-04-09 at 09 58 05](https://user-images.githubusercontent.com/1926584/78871857-a43e4600-7a48-11ea-9a8f-7aeade3348e5.png)

**Comment by gregvanl** [comment]
Actually showing `unassigned` is helpful in keybinding tables to let users know that new commands don't have default keybindings. 
https://code.visualstudio.com/docs/getstarted/keybindings#_default-keyboard-shortcuts
I would prefer to leave the text as `unassigned` (a correct hint in your case) but perhaps we could add a hover to show the command ID.

**Comment by macintacos** [comment]
I’m up for whatever makes this simpler to reason about in the future :)

**Comment by mjbvz** [comment]
Added a hover for the in-product release notes: 

<img width="593" alt="Screen Shot 2020-10-19 at 4 57 39 PM" src="https://user-images.githubusercontent.com/12821956/96524151-5347af80-122c-11eb-9280-dcb90993257d.png">

@gregvanl Can you also make sure that our website shows the correct information? The fix was to add a `title` attribute to the html `<code>` element for keybindings

**Comment by gregvanl** [comment]
For the website, the hover normally show the keybindings for other platforms (for example macOS, Linux) so only showing the commandId when the value is `unassigned`
![image](https://user-images.githubusercontent.com/12818376/96525087-e1249a00-122e-11eb-9407-d70908aefaad.png)

**Comment by alexr00** [comment]
How is this verified? I could repro the original in stable, but I don't know how to get some release notes with a `kb()` in them to show in insiders. The markdown preview doesn't seem to handle `kb()`

**Comment by gregvanl** [comment]
@alexr00 @mjbvz I can take verifying this. I'll temporarily put up a testing section in the 1.51 release notes snapshot on code.visualstudio.com, which I can test on Insiders.
