### ISSUE TITLE
Dashboard stats for extension authors

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#94744]
Refs: #93604

Currently there is nothing built-in to the VS Code marketplace for extension authors to track basic stats (downloads, installs, views, etc). 

It would also be great to see location, OS and other basic information about where extension usage is coming from.

**Comment by prashantvc** [comment]
We have enabled the basic stats report for the extension authors on the VS Marketplace.
You can access it from the extension's `More Actions...` menu

<img width="592" alt="PNG image" src="https://user-images.githubusercontent.com/328076/81797980-17961480-952d-11ea-84d5-772e591566c9.png">

We will evolve the report based on the community feedback. Please give it a try and share your feedback

**Comment by usernamehw** [comment]
I'm genuinely unable to find this. What's the URL address?

**Comment by prashantvc** [comment]
> I'm genuinely unable to find this. What's the URL address?

For anyone who couldn't find it :)
https://marketplace.visualstudio.com/manage

**Comment by usernamehw** [comment]
Sorting in tables feels clunky, it accepts clicks only on column text, but not on the empty space.

**Comment by usernamehw** [comment]
What does this icon mean?

![Screenshot (231)](https://user-images.githubusercontent.com/9638156/81804970-b8cb9d80-9522-11ea-8913-548a0edb50c5.png)

**Comment by usernamehw** [comment]
Are those 2 widgets related? It's just one of the ratings is not reflected in the top one:

![Screenshot (232)](https://user-images.githubusercontent.com/9638156/81805288-40191100-9523-11ea-8dc8-a6cbcaa45ac4.png)

**Comment by dzhavat** [comment]
@usernamehw I think the 4-start is not reflected in the top widget because it's older than 90 days. It says under 5.0 (6) that the number is based on the reviews during the last 90 days.

---

I saw the stats for my extensions and think that it's a huge improvement compared to the non-existing stats before. Definitely something positive and in the right direction. Awesome job.

What I miss in the graph now (or it could be a separate one as well) is a breakdown that shows in which VS Code versions are my extensions running. I think that will be really helpful information.

**Comment by usernamehw** [comment]
Is there a roadmap of the stats that will be available in the future? like:

- [x] ...
- [x] installs
- [ ] downloads
- [ ] VSCode versions
- [ ] OS
- [ ] Locale
- [ ] Active users

I think `downloads` is already implemented internally and available through a badge:

[![](https://vsmarketplacebadge.apphb.com/downloads-short/usernamehw.errorlens.svg)](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens)

So that one should be really easy to do.

**Comment by RandomFractals** [comment]
great start. I think installs and updates/downloads stats display should be split into two lines for the 'Acquisition' Y axes since I find this graph a bit confusing (shows last update stats fro one of my extensions)

![geo-data-viewer-stats-5-15-2020](https://user-images.githubusercontent.com/656833/82054624-d31d8c80-9684-11ea-9762-7ed6f9749f3a.png)

I do like Page Views metric. Helps to see how many devs visited extension page. Something we could not get before from extension web services.

Thank you for adding this simple dash!

**Comment by RandomFractals** [comment]
would it be possible to see total number of installs from Released on date to view the user base growth in addition to the metrics @usernamehw listed? 

Geo/local with a simple map display could be a good way to learn more about our users too.

**Comment by mjcrouch** [comment]
It would definitely be useful to see new installations (i.e. ones that contribute to the 'install count') separately from the rest of the installs

As I mentioned on slack my extension has 2500 unique installs but on one day there were over 7500 installs on the graph. Not sure why so many - I did push an update that day, but only one

**Comment by RandomFractals** [comment]
@mjcrouch that high installs spike you see is because downloads/updates are added to it currently.

I agree seeing uninstalls in that graph would be interesting too.

So, I think the metrics on that graph should be:

- page views
- new installs
- updates
- uninstalls

**Comment by mjcrouch** [comment]
> @mjcrouch that high installs spike you see is because downloads/updates are added to it currently.
> 


Yes, but the specific figure implies that everyone who's ever installed my extension downloaded it three times in one day :D

**Comment by RandomFractals** [comment]
@mjclemente hah! I wonder if updates add extra counts to downloads for every ext. v. or vscode v. update. yeah, very weird.

**Comment by RandomFractals** [comment]
it is interesting to look at the page views and see how they correspond to tweets and other posts for marketing vscode extension. this is a shameless plug, but I thought I'd share it for other devs to use and look at.

Below are my [GeoDataViewer](https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.geo-data-viewer) stats plotted in [DataPreview](https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-data-preview)

![geo-data-viewer-page-views-graph](https://user-images.githubusercontent.com/656833/82107878-840d4100-96f0-11ea-973b-693f727d2fa8.png)

If you look at my tweets promoting that extension and that page views bar chart you should be able to see a close correlation and spikes ...

This based on exported report and plotted with my data preview extension which supports binary xlsx files data display and basic charting.

Feel free to use that tool for plotting your ext. reports.

**Comment by usernamehw** [comment]
Having extension `activation time` would be great also.

**Comment by RandomFractals** [comment]
I had a great chat with @prashantvc about vs marketplace enhancements we'd like to see next.

Topics we covered in our 1 on 1 call:

- Marking extensions as Paid or Free Trial similar to options VS and Azure DevOps ext. developers have. Ideally, I'd like to see an integration on vscode side with payment processors like PayPal and Square and freemium and paid extensions be prominently shown in vscode extensions tab, with Microsoft taking 5-10% cut of those, instead of 30% other app stores charge.

- Hourly extensions stats to view the number of installs & uninstall per hour, in addition to daily currently shown in extension reports
- Date range filter for reports to see installs count and other stats from published extension date and for arbitrary date ranges. Same for the reports to download
- Adding Uninstall counts to extension reports, so we can clearly see extension attrition rate based on Installs & Uninstalls
- Changing Acquisition & Conversion Funnel to use Installs and Uninstalls instead of Page Views and total Installs + Updates
- Breaking Installs & Updates into separate metrics displayed in those reports

**Comment by RandomFractals** [comment]
@prashantvc We also discussed that perhaps it would be more productive for your team to create a separate vs-marketplace documentation github repository for extension authors to log feature requests and for your team to help us understand some of those ext. stats and reports.

I believe it would be an optimal solution for us to provide feedback since the only communication channel we currently have with your team is via email from vs marketplace pages.

**Comment by RandomFractals** [comment]
... until such time, I have one more pressing feature request which I think your team can easily add since you already load our README.md docs in vs marketplace pages:

Frequently, we need to respond to developer reviews and point them to sections of our docs or pending issue on github.

It would be really helpful if on the User Reviews page we could use markdown format, or if you could at least expend links to docs and github issues that we clip there responding to developers feedback.

For example, I often quote my docs and link to github issues. I believe other extension developers do the same. However, without those links converted to proper links, I don't think devs clip and follow them.

https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-data-preview&ssr=false#review-details

Thanks in advance on this & other ext. devs feel free to upvote it! ;)

**Comment by RobFosterNYC** [comment]
> Are those 2 widgets related? It's just one of the ratings is not reflected in the top one:
> 
> ![Screenshot (232)](https://user-images.githubusercontent.com/9638156/81805288-40191100-9523-11ea-8dc8-a6cbcaa45ac4.png)

Yaa.  I believe thats very deceiving. basing review for 90-days, instead of "Over-All"  ..  just saying 🤷‍♂️👀

**Comment by RandomFractals** [comment]
oh, wow! I did not know that even rating is based on their 90 days period. That explains a lot.

**Comment by isidorn** [comment]
There are no plans for any change here on the VS Code side. I see that there are already issues open on the VSMarketplace side. I suggest to continue the discussion there https://github.com/microsoft/vsmarketplace/issues/14 or to open new issues.

Since no changes are planned on the VS Code side I am closing this

**Comment by alefragnani** [comment]
Hi @isidorn ,

I see vsmarketplace repo/team as the right location for install count, downloads and reviews, because those are things related to the _store_ itself. And as noted, they have updated the Marketplace Dashboar with a bit more information. Congrats to that!

But what about other infos requested in the comments above, which seems a bit more _usage_ related, like:

* OS (Windows / MacOS / Linux)
* Flavor (Desktop / Codespaces / GitHub.dev)
* Remote (Docker / SSH / WSL)
* Activation Time
* Locale

Do you think these informations would be available in the marketplace, VS Code, or other team?

Right from the beginning, I would like to know which OS my extension was being used, mostly because I only had Windows available and had no chance to support MacOS/Linux. That's why I opened https://github.com/microsoft/vscode/issues/4801. This week VS code retweet https://twitter.com/prshntvc/status/1430132093758156805?s=20, and it revived my request, with a bit more _scenarios_.

Today, VS Code runs not only different OS but also _flavors_ like Remotes, Codespaces and GitHub.dev, and because extensions can be installed via Settings Sync (not the Extension View), I guess the Marketplace won't know about it.

Thank you

cc @eamodio, @usernamehw

**Comment by isidorn** [comment]
@alefragnani thanks for bringing this up. I believe the whole dashboard experience should be on the marketplace side, and some data should come from VS Code. 
Can you please open an issue https://github.com/microsoft/vsmarketplace and feel free to ping me @isidorn on the issue so we continue the discussion there. I think this makes sense, but depends on the cycles on the Marketplace team side.

I can also open the issue there, just let me know.

**Comment by isidorn** [comment]
@alefragnani thanks for bringing this up. I believe the whole dashboard experience should be on the marketplace side, and some data should come from VS Code. 
Can you please open an issue https://github.com/microsoft/vsmarketplace and feel free to ping me @isidorn on the issue so we continue the discussion there. I think this makes sense, but depends on the cycles on the Marketplace team side.

I can also open the issue there, just let me know.

**Comment by alefragnani** [comment]
Thanks @isidorn! Just moved the comment, as you suggested.

Let me know if you need more details
