### ISSUE TITLE
Provide linting support (eslint?) for deprecated extension APIs

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#94751]
Refs: #93604

It would be great if we provided a lint package that extension authors could use to identify deprecated APIs. Additionally, any other common mistakes, or anti-patterns we've seen used.

/cc @jrieken

**Comment by eamodio** [comment]
FYI @Ikuyadeu has some linting here: https://github.com/devreplay/devreplay/blob/master/src/rules/vscode.ts

**Comment by Ikuyadeu** [comment]
@eamodio Thank you for summarizing!

I want to add the information that I could not tell due to my English.
The lint is available as the [vscode plugin](https://marketplace.visualstudio.com/items?itemName=Ikuyadeu.devreplay)
![devreplay_usage](https://user-images.githubusercontent.com/8369346/78861824-c51a9180-7a70-11ea-805e-62b90eae8483.gif)

Left is deprecated code, right is setting file `./devreplay.json`

Also, implementing vscode-plugin like [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue) is good, but sounds costy.

**Comment by jrieken** [comment]
I love the idea and I am disappointed that TypeScript didn't look at this https://github.com/microsoft/TypeScript/issues/33093. Pretty please, @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
We were looking at this recently and we might have the information on hand to do this at least from things like completion. Whether we could do this for suggestion diagnostics might be another issue.

**Comment by Ikuyadeu** [comment]
In my idea, my extension and linter are MIT, so it can be used in this repository like language syntax files by the following steps.

1. Importing my extension as the basic vscode function
2. Using rule file as the .vscode/rules.json that refer the #88391 knowledge.
3. Putting the rule files on the extension template in Yo.
4. New extension users can get the warning by the rule file.

How do you think?

**Comment by jrieken** [comment]
TS now supports the `@deprecated` and usages of deprecated APIs are flag accordingly. Closing as obsolete
