### ISSUE TITLE
Improve the settings sync flows with authentication

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#94766]
Improve the settings sync flows with authentication

## Sign in flow

Signing in showing too many notifications and not consistent. Sign in from Accounts UI and I see following dialogs 

a. For the first time ever

<img width="622" alt="image" src="https://user-images.githubusercontent.com/10746682/78883896-66e2b400-7a5a-11ea-94eb-ddd40bc304bb.png">

<img width="662" alt="image" src="https://user-images.githubusercontent.com/10746682/78884127-bc1ec580-7a5a-11ea-966a-306608202af1.png">

b. Afterwards

<img width="487" alt="image" src="https://user-images.githubusercontent.com/10746682/78883763-3b5fc980-7a5a-11ea-9eae-de8b6ab2ca8f.png">

<img width="662" alt="image" src="https://user-images.githubusercontent.com/10746682/78884127-bc1ec580-7a5a-11ea-966a-306608202af1.png">

## Sign out flow

Signing out is showing following notification

<img width="489" alt="image" src="https://user-images.githubusercontent.com/10746682/78882615-97295300-7a58-11ea-94ac-327e406f5598.png">

There should be a sign in button instead of Turn on. Because user did not turn off sync here. It shall be same as the action button that is shown in the gear icon

<img width="344" alt="image" src="https://user-images.githubusercontent.com/10746682/78882885-0606ac00-7a59-11ea-87f6-2fc1735a9437.png">

Above notification is also shown even when settings sync is turned off

Also do we need successfully sign out notification here?

## Error flow

Errors while signing in

Following notifications are shown which are not helpful

<img width="499" alt="image" src="https://user-images.githubusercontent.com/10746682/78884626-8c23f200-7a5b-11ea-8ea6-639ecac0391a.png">

## Cross Window Flow

Sign in/Sign out from one window is prompting turn on/turn off sync notification on another window

https://github.com/microsoft/vscode/issues/94176

- Open two windows with sync enabled 
- Sign out from one window and you get a turn off notification in that window 
- But it is not expected to get the same notification in another window
- Now sign in from one window and you get following notification in another window

<img width="480" alt="image" src="https://user-images.githubusercontent.com/10746682/78885085-4156aa00-7a5c-11ea-90e4-ca2838509c33.png">

## Others

- Decouple auth and settings sync - https://github.com/microsoft/vscode/issues/94050

**Comment by sandy081** [comment]
@RMacfarlane I am seeing the following dialog even if sync is turned off

<img width="460" alt="image" src="https://user-images.githubusercontent.com/10746682/79499026-9b420b80-802a-11ea-8810-9e3c2f818098.png">

**Comment by RMacfarlane** [comment]
Ah, yeah, the problem is that I don't have a clear signal of when a token is no longer being used. I track that something has read a token for an account during the current session. Would changing the dialog text to the more accurate text `The account x has been used during this session by:` be better?

**Comment by RMacfarlane** [comment]
The more involved fix would be to return both a value and a dispose method that can be called when using `getAccessToken()`, such that you could call dispose when you no longer care about the access token.

**Comment by sandy081** [comment]
Is it possible to logout only for a given session?

**Comment by RMacfarlane** [comment]
Yeah, that's possible.

However, I'm not sure we want to do that when turning off sync - I don't think I would expect to sign out when turning off sync. Since multiple extensions can read the same session, you potentially stop something else from working by removing that session. I previously made a change to enforce that each session could only be read by one extension, but then undid it because that makes a single sign on impossible. Maybe I could reference count and only really do the logout when nothing depends on the session anymore 🤔

**Comment by sandy081** [comment]
I see. Makes sense. Thanks for explanation/
