### ISSUE TITLE
Winow: Menu Bar Visibility Overwritten by Keybinding

### ISSUE THREAD

**Issue by egarson** [microsoft/vscode#94808]
Issue Type: <b>Bug</b>

GOAL : I want my menubar always hidden unless I press "Alt-F10".

PROBLEM: The value "hidden" set on 'Window: Menu Bar Visibility' reverts to "toggle" after ascribing a keyboard shortcut to 'View: Toggle MenuBar Visibility'

STEPS TO REPRODUCE: 

1. Set 'Window: Menu Bar Visibility' to  "hidden"

2. Set Keyboard Shortcut 'View: Toggle Menu Bar' to "Alt-F10"

3. Be happy (as an 'emacs user') because when Alt is pressed, the menubar no longer appears (nb when Alt is pressed alone, eg as I am thinking about my next test).

4. Press 'Alt-F10' to make the menubar appear and invoke a menu item

5. Be sad, because 'Window: Menu Bar Visibility' reverts to "toggle"

Yes, I tried to set Window: Custom Menu Bar Alt Focus to False; this makes no difference actually.

Many thanks for an amazing environment!

VS Code version: Code - Insiders 1.44.0-insider (ea935488ec0e5415d4205c1f33ba332fd417f85a, 2020-04-07T13:30:47.585Z)
OS version: Linux x64 5.3.0-46-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4271)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.58GB (0.66GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|2.0.5
flutter-snippets|ale|2.0.0
dart-code|Dar|3.9.1
flutter|Dar|3.9.1
vsc-material-theme|Equ|32.5.0
vsc-material-theme-icons|equ|1.1.4
pubspec-assist|jer|0.3.6
vscode-emacs-friendly|lfs|0.9.0
flutter-tree|mar|1.0.0
goto-next-previous-member|mis|0.0.5
awesome-flutter-snippets|Nas|2.0.3
material-icon-theme|PKi|4.0.1

(3 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
@egarson can you explain what you attempted with `Window: Custom Menu Bar Alt Focus`? I see your goal is to have the menubar hidden until you press alt+f10. Based on your steps however, I'd like to ask if your goal is rather to avoid conflicts with alt+ keystrokes.

**Comment by egarson** [comment]
I tried setting `Window: Custom Menu Bar Alt Focus` to both `false` (unchecked) and `true` to no avail. That is to say, it doesn't seem to have an effect on whether or not Alt-F10 reverts the Menu Bar Visibility setting (from 'hidden').
What I think is happening is that invoking `View: Toggle Menu Bar Visibility` from a keyboard shortcut causes the *value* to change, as opposed to making the menubar actually appear or disappear -- or, have I misunderstood the application of `View: Toggle Menu Bar Visibility`?

**Comment by sbatten** [comment]
@egarson your understanding of that command is correct. It's intent is to be a quick way to change the setting which can easily be mistaken for a command that just brings the menu bar into view.

I am now noticing you are on Linux. By default, Linux uses the native title bar experience which is part of electron. Electron only allows us to toggle the menu bar with the alt key which is why the command you are using isn't designed the way you expect.

The setting `Window: Custom Menu Bar Alt Focus` is intended for the Custom menu bar only. To enable this, set `Window: Title Bar Style` to `custom`. This will prevent alt from focusing the menu bar if you are using other emacs keybinds that would conflict. Further, if you want to disable mnemonics (e.g. Alt+F for file menu) you can do so with `Window: Enable Menu Bar Mnemonics`.
