### ISSUE TITLE
Timeline: Show full commits history for a renamed file

### ISSUE THREAD

**Issue by mbelsky** [microsoft/vscode#94803]
Hey,

Thank you for this awesome Timeline feature.

I face that now it doesn't show full commits history for a renamed file. With git I could get it with *--follow* arg like `git log --follow ./PATH/TO/FILE`.

Could something like --follow arg be implemented for vscode too?

**Comment by mbelsky** [comment]
btw I'll be glad to work on this feature if it's possible. Do I correctly understand that it could be fixed in https://github.com/microsoft/vscode/blob/master/extensions/git/src/git.ts#L857 by adding --follow arg? Or this feature requires more complex change?

**Comment by eamodio** [comment]
Unfortunately git `--follow` causes a bunch of other unintended (unwanted) changes to how the history is calculated. It affects how merge commits are shown (they won't be), and even if you try other git incantations to restore the merge commits it also has a series of unwanted changes. Basically I haven't yet figured out any way to get an equivalent history with and without `--follow`. There are also other consequences as well, as determining how to diff with the previous revisions, because of the filename changing.

I've gone through a lot of this pain in the GitLens File History feature, a more powerful version of the Timeline view (though only for Git file history), which provides a toggle for following renames or not. And currently, I'm not convinced it is worth the effort and complexity to bring this over (unless there is overwhelming demand).

In the meantime, you can try the GitLens File History feature. And once the Timeline API is finalized, I will probably bring GitLens' richer features directly into the Timeline view.

**Comment by eamodio** [comment]
[GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) currently provides this feature and as mentioned above it is tricky and has many issues/limitations.

**Comment by hheexx** [comment]
Visual Studio have this by default....

**Comment by Sytten** [comment]
Was there any progress on the timeline API integration of gitlens since then?
It's really annoying to have a dumb timeline when the file itself it properly annotated with gitlens.

**Comment by eamodio** [comment]
GitLens has its own File History view, which is a richer version of the Timeline view. But right now, since the Timeline APIs are still in the proposed state, GitLens can't use them.

**Comment by homezonebenny** [comment]
GitLens can now show "Renamed Files" in the Git History, see:
[https://github.com/gitkraken/vscode-gitlens/issues/2828](https://github.com/gitkraken/vscode-gitlens/issues/2828)

Sadly, VSCode still can't show it in their own History.
Did someone forwarded this to VSCode developer?
