### ISSUE TITLE
docs for DocumentLink lists property that doesn't exist

### ISSUE THREAD

**Issue by noopkat** [microsoft/vscode#94852]
Hi there,

I am trying to use the Document Links Provider feature for a VS Code extension. I'd like to supply a tooltip that briefly describes what the link will be if they follow it (eg. "see [method name] in the API reference online").

Was this an existing property in the past? Is it now deprecated?

- VSCode Version: 1.43.2
- OS Version: macOS Mojave 10.14.6

**Steps to Reproduce:**

1. Visit the following page: https://code.visualstudio.com/api/references/vscode-api#DocumentLink
2. The docs for `new DocumentLink` lists an optional property called `tooltip`
3. Attempt to create an extension that provides Document Links
4. When calling `new DocumentLink` with all three properties, the linter will advise that there is no such third argument `tooltip`.

Here is a screenshot for illustrative purposes:

![Screen Shot of new Document Link method call error](https://user-images.githubusercontent.com/1411284/78954463-25213000-7a91-11ea-9227-e47adc14eba4.png)

**Does this issue occur when all extensions are disabled?:** I cannot test this without having extensions enabled

Thank you!

**Comment by mjbvz** [comment]
Tooltip is a property you can set on `DocumentLink`, not a constructor argument. The docs seem to list the 2 argument constructor properly:

<img width="532" alt="Screen Shot 2020-04-09 at 6 55 54 PM" src="https://user-images.githubusercontent.com/12821956/78955320-c610ea80-7a93-11ea-840e-3284e4b2837e.png">

**Comment by suz-stripe** [comment]
thanks for the fast response. I also at the time tried to access it as a property. When I try to do this, I still get a TypeScript error despite the property [existing in the source code](https://github.com/microsoft/vscode/blob/d4ce7148dd0125d210441762e3501cec351b0e2a/src/vs/workbench/api/common/extHostTypes.ts#L1510). I get `Property 'tooltip' does not exist on type 'DocumentLink'`.

After creating a new DocumentLink, it only allows me to update `target` and `range` properties.

![image](https://user-images.githubusercontent.com/54524269/79005536-eed4c680-7b0b-11ea-84c6-e4560bba7bbc.png)

I understand how TypeScript classes work, or I thought I did until I ran into this, which is why I thought perhaps the documentation was wrong. Apologies if this is not a real issue, but I am really confused at this stage as to how to use the tooltip property.

**Comment by suz-stripe** [comment]
code to reproduce:

```javascript
    const uri = Uri.parse("https://www.typescriptlang.org/");
    const range = new Range(new Position(0,0), new Position(0,10));
    let link = new DocumentLink(range, uri);

    link.tooltip = "see this method in the API Reference"; // typescript error
    link.target = undefined; // no typescript error

```

**Comment by mjbvz** [comment]
You likely have an old version of the VS Code types in your project. Make sure to update them to target a more recent VS Code version

**Comment by suz-stripe** [comment]
@mjbvz thank you so much for your patience. I didn't realise this property was new and sure enough when I updated my types it has shown up. Thank you again 😅
