### ISSUE TITLE
objective-c cannot jump to definition *caused-by-extension ?

### ISSUE THREAD

**Issue by AsteriskZuo** [microsoft/vscode#94867]
Please do not close the problem without resolution.
[https://github.com/microsoft/vscode/issues/94735](94735)

**Comment by RMacfarlane** [comment]
@AsteriskZuo The base install of VSCode does not include support for "Go to definition" for Objective C. We do not support language intelligence for every language out of the box because we want to keep VSCode small, instead, we want users to be able to install extensions to configure VSCode to their needs.

See https://github.com/microsoft/vscode/issues/22452#issuecomment-285908456
