### ISSUE TITLE
Something is clearing Undo buffer. Coder cannot undo as many steps.

### ISSUE THREAD

**Issue by jaygeek** [Microsoft/vscode#9492]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Write code. (Ex: Refactor javascript into a new function)
2. Save often. (some other factor is affecting the undo buffer here, too.)
3. Try to undo your code changes and only a few undo steps are available with Ctrl-Z

**Comment by srjek** [comment]
Also having this issue

VSCode Version: Code 1.3.1 (same git id/timestamp as above)
OS Version: Windows 10 Version 1511 (OS Build 10586.494)

Steps to Reproduce:
1. Open VS Code
2. Type a character somewhere (I'm assuming vs code opened up some project from the last session)
3. Save
4. Switch to another file
5. Switch back to the modified file
6. Attempt to undo

Omitting the save step will allow undo to work as normal

**Comment by kieferrm** [comment]
I can't reproduce neither @srjek nor @jaygeek case on the 1.3.1 stable or the 1.4.0 insider on Windows or MacOS. Pls have a look at #9495 and let us know if that's potentially what you see. Pls reopen if you have some additional details/insights.

**Comment by srjek** [comment]
The description of #9495 doesn't apply as I don't use that setting. That said, I just started up my computer and I'm having trouble reproducing with my own repro steps from last night. If it happens again, I'll try to investigate further and may reopen or comment with whatever I find.

**Comment by srjek** [comment]
Alright, the culprit that messed up the mapResourceToEditor map was git diffs, as they shared the same resource uri as the file they diff, and would occupy the same entry in the map. Closing a git diff would make the editor think any other view of that file was closed.

The issue was fixed by commit [7c415a5](https://github.com/Microsoft/vscode/commit/7c415a5733cc0d95f0706dfa79cb0c741c49f368), which changes mapResourceToEditor to be a refcount instead of a simple is/isn't. The commit is in the insiders build, where I can not repro.

@kieferrm I can't reopen this issue, but is there any point? A workaround is to use the insiders build, it's fixed in what will be 1.4, and from an outsider's perspective the monthly release cycle implies 1.4 will be out soon™.

New repro steps:
1. Open a file
2. Edit
3. Observe that you can undo and redo
4. Without closing the file, open the git diff of the file
5. Close the git diff (should return you to the original file)
6. Observe that you can undo and redo
7. Open some other file
8. Switch back to the original edited file
9. Observe that you can not undo or redo your changes

**Comment by RReverser** [comment]
Periodically having this issue on 1.3.1 too.

**Comment by kieferrm** [comment]
@srjek thanks for the updates! No need to reopen then.

**Comment by bpasero** [comment]
This is https://github.com/Microsoft/vscode/issues/10932
