### ISSUE TITLE
ctrl+A does not respect editorTextFocus condition

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#9493]
- VSCode Version: Stable and Insiders
- OS Version: Win10

Steps to Reproduce:

1. Start a debugging session
2. Highlight some text in the debug console and press ctrl+a
3. All the text in the console and editor is highlighted, including line numbers

**Comment by isidorn** [comment]
ctrl+A is not supported in the console because we use a tree for the debug console, and not an editor - this is a debt item which we have on our radar. Due to this there are other limitations with the console - like the pg up/down not working, no find etc...
I get the same behavior as @roblourens with the exception that line numbers do not get highlighted (tried os x and win10)

However the issue here is that ctrl+A should be ignored because the editor text does not have focus, thus renaming issue and forwarding to @alexandrudima. Simpler repro steps:
* Click on any viewlet
* Press ctrl+A  -> all text in editor gets selected even though `editorTextFocus` condition is not true. I would expect ctrl+A to get ignored

**Comment by alexandrudima** [comment]
I believe this got fixed by the fix for #10222

**Comment by bpasero** [comment]
We now select all in the editor and that is better compared to this issue. Still, we do not support select all in the repl.
