### ISSUE TITLE
VSCode markes newly opened files as modified 

### ISSUE THREAD

**Issue by lorenjerickson** [Microsoft/vscode#9494]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.14372

Steps to Reproduce:

1. Open a folder
2. Open any file in that folder

VSCode marks every file I open as being modified, even though I haven't touched them.  The modified indicator shows up in both the tab label and the open files section of the sidebar.

**Comment by aroemen** [comment]
I am having the same issue on v1.3.1 on Win7. It happens when I just preview the file.

**Comment by mrmlnc** [comment]
Confirm. Windows 10 Pro (build 10586.494)

![2016-07-20_18-52-04](https://cloud.githubusercontent.com/assets/7034281/16993227/1ccce914-4eab-11e6-9995-ebdedba187db.gif)

**Comment by aroemen** [comment]
Hmm, might not be a VSCode issue. When I disable my editorconfig extension, I don't have the problem. They have a closed ticket on their end (https://github.com/editorconfig/editorconfig-vscode/issues/57) and don't seem to be addressing the issue. Files shouldn't be changed until save in my opinion.

**Comment by kieferrm** [comment]
Pls reopen if you see it even when starting with the `--disable-extensions` command line option.

**Comment by 101100** [comment]
According to [this post](https://github.com/editorconfig/editorconfig-vscode/issues/57#issuecomment-230138739) on the editorconfig issue, the problem is that:

> Lastly, I want you to consider the possibility that your issue is actually not with this plugin at all, per se, but with vscode's setEndOfLine method, which not only "sets" your end of line setting, but changes the file in the process! This is the only mechanism that vscode exposes to me, the plugin developer, so who is to blame?

If this is true, than this issue is that VSCode does not provide the API necessary to set the line endings only once the user changes the file.  The plugin developer seems willing to use another API if it would fix this issue (that has caused at least 2 issues to be reported in VSCode and 10 issues to be reported in the editorconfig repo).
