### ISSUE TITLE
Editing history is lost when using onFocusChange

### ISSUE THREAD

**Issue by calebeaires** [Microsoft/vscode#9495]
- VSCode Version: 1.3.1 (1.3.1)
- OS Version: OS X 10.11.5

After last update, when using  ```"files.autoSave": "onFocusChange"``` on user settings and when change editing file by choosing file on left sidebar, history from the previous file history is lost.

Steps to reproduce:

1 - Edit some file, change it many times.
2 - Try CMD + Z -> it works.
3 - Change to another file, by changing clicking on LEFT SIDEBAR Explorer folder files
4 - Back to the previous edited file.
5 - Try using CMD + Z -> does not work. History is lost

ps.: This behavior starts on last update.

**Comment by kieferrm** [comment]
@calebeaires this works for me with with 1.3.1 and the 1.4.0 insider built on MacOS and Windows with and without displaying tabs. I suspect the issue is step 4. Selecting a file in the explorer does not give the editor focus as the file is only in preview mode. You set the focus by either double clicking the file or `Cmd+arrow down` on the file in the explorer or `Cmd+1`. The last command depends on in which group the preview opened. Pls reopen if there is something I overlooked.

**Comment by kieferrm** [comment]
Also see #9492.

**Comment by calebeaires** [comment]
I guess this is not the case. I just wish Visual Code could preserve the history (undo CMD + Z) when I change the file on the window from the Explorer Sidebar.

**Comment by localpcguy** [comment]
There seems to be a few reasons why the history gets lost in VSCode, and this is a big annoyance. I like VSCode, and don't want to go to another editor, but it may force me to. The history shouldn't matter how you open a file, how you get back to that file, or anything. If it's open, and you've made changes, it should have the full history of those changes. I'm trying to track down exactly why I keep losing history states, and having to use git to restore lines I should be able to just use undo to get back. But telling users "you need to double click, or history won't be preserved" is not an acceptable answer.
