### ISSUE TITLE
Bash debugging does not start with version 1.44.0

### ISSUE THREAD

**Issue by manuel-192** [microsoft/vscode#94982]
- VSCode Version: 1.44.0
- OS Version: EndeavourOS (Arch Linux based, rolling, with latest updates installed)

Steps to Reproduce:

1. Update Visual Studio Code to new version 1.44.0 and use the Bash Debug extension (0.3.7) by rogalmic
2. Try to Start Debugging your bash code
3. The terminal output shows error message:
`bash: line 0: cd: too many arguments`
and debugging does not start.

Note: previous Visual Studio Code version 1.43.2 does not have this issue.

Does this issue occur when all extensions are disabled?: Only using the Bash Debug extension.

**Comment by manuel-192** [comment]
The only thing that changed is Visual Studio code. The same extension version of Bash Debug works  as expected with the older (and many other older) versions of Visual Studio Code, but not with 1.44.0.

So I'd like to see more details backing up the claim that the extension is the cause.

**Comment by weinand** [comment]
Yes, may be, but the author of the Bash Debug extension needs to find out what the problem is. We have no know-how with the Bash Debug extension. If the problem is on our side we'll open this issue.

**Comment by manuel-192** [comment]
OK, I already wrote to them as well.
Thanks for answering!

**Comment by manuel-192** [comment]
From the Bash Debug extension creator I got this kind of response: https://github.com/rogalmic/vscode-bash-debug/issues/133.
He thinks this this is a VsCode issue related to semicolon handling. Please look at the thread behind the link.

**Comment by manuel-192** [comment]
The issue is still affecting Visual Studio Code versions 1.44.0 to 1.44.2.
The integrated terminal fails to start bash debugging. The external terminal option allows bash debugging to start.

**Comment by weinand** [comment]
the Bash Debug extension relies on passing a bash script as a program argument via the DAP "runInTerminal" request.

Since the "runInTerminal" API was designed to be shell agnostic, VS Code has to make sure that any possible argument is escaped properly so that it survives being passed through any type of shell. Since this is difficult, there are bugs.

In this case it looks like that the fix #93166 broke Bash Debug.
The fix addressed the issue that ';' in an argument (e.g. `foo;bar`) would result in a truncated argument (`foo`).
Escaping the ';' with a backslash (e.g. `foo\;bar`) works fine as long as the argument is not surrounded by quotes (which happens if the argument contains a space character). So `"foo\;bar"` -> `foo\;bar`.

**Comment by weinand** [comment]
@manuel-192 it would be great if you could verify the fix in the next Insiders (next Monday).

**Comment by manuel-192** [comment]
Sorry about the delay!

With the insider vscode (AUR version 1588139461, updated at 2020-04-24 06:46) it works!
Thanks!

**Comment by weinand** [comment]
@manuel-192 thanks for verifying this.
