### ISSUE TITLE
Microsoft.PowerShell.EditorServices.Host.exe process constantly uses one CPU core

### ISSUE THREAD

**Issue by ykuijs** [Microsoft/vscode#9503]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1. Open VSCode
2. CPU utilization increases with 100/# of cores, which is takes constantly by the process Microsoft.PowerShell.EditorServices.Host.exe

**Comment by kieferrm** [comment]
@ykuijs Do you use the powershell extension? Do you have to open a powershell file to see this behavior?

**Comment by daviwil** [comment]
Please move this issue to the PowerShellEditorServices repo so I can track the problem there.

https://github.com/PowerShell/PowerShellEditorServices/issues

The likelihood is that this is an orphaned process and it's spinning due to an old bug: 

https://github.com/PowerShell/PowerShellEditorServices/issues/31
