### ISSUE TITLE
Unwanted auto-indentation (to the left/decreased indentation) while coding in React and ReactNative

### ISSUE THREAD

**Issue by sourabhbagrecha** [microsoft/vscode#95105]
- VSCode Version: 1.44
- OS Version: 10.0.18362 N/A Build 18362

Steps to Reproduce:

1. Create a JavaScript file(for a ReactNative Component), for eg. ResultsList.js
2. import React
3. Create a functional component
4. Inside the return, statement paste the following:
```
return (
  <Text></Text>
 )
```
5. Now add the following by typing(not pasting) in between the opening and closing <Text> tag:
`{}`
such that it should look like: <Text>{}</Text>
as shown in the gif below:

![Indentation-Final](https://user-images.githubusercontent.com/27056663/79109433-f3acab00-7d95-11ea-9470-2ccf78e0b97e.gif)

6. You will notice that the whole line gets auto indented (decreased indentation, i.e. to the left), which is not expected in this case.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sourabhbagrecha** [comment]
Any updates on this?

**Comment by rebornix** [comment]
The default `autoIndent` setting value is `full`, which will keep the current line's indentation, honor language defined brackets, invoke special onEnterRules defined by languages, and lastly honor indentationRules defined by languages. The catch here is indentations rules are the most powerful one but also problematic sometimes as it's regular expression based rules instead of being real context-aware.

We will explore how we can improve regex based onEnter and indentation rules but for now, please use `"editor.autoIndent": "advanced"`.
