### ISSUE TITLE
Ctrl+Shift+F returns to global replace view instead of global find

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#9513]
- VSCode Version: Code - Insiders 1.4.0-insider (f4780e67933164a2289b86f2c279aaa05fda672f, 2016-07-19T05:07:05.876Z)
- OS Version: Windows_NT ia32 10.0.14390

Steps to Reproduce:
1. Open VS Code
2. Ctrl+Shift+H shows Global Replace (in the Search window)
3. Ctrl+Shift+E shows Explorer
4. Ctrl+Shift+F returns to the Search window (but in Global Replace mode instead of Global Find mode)

Expected:

Ctrl+Shift+F should open Search to Global Find mode. (The only way to use the keyboard to switch away from Global Replace is to do Ctrl+Shift+H (or tab to the Replace field) and then press Escape to hide the Replace box.)

**Comment by sandy081** [comment]
We open Replace on Ctrl + Shift + F only for the first time for the workspace (for discoverability). After that we retain the state of replace. It is shown only if it was opened last time otherwise not. I think this behavior makes sense and is also consistent with Find and Replace. 

I would wait to receive more feedback before changing.

**Comment by dilijev** [comment]
@sandy081 Agree it makes sense given the current UI design in this case, considering Ctrl+Shift+F is one of the hotkeys for the buttons along the side, others being:

* Ctrl+Shift+D [debug]
* Ctrl+Shift+E [explorer]
* Ctrl+Shift+G [Git]

But the similarity of the hotkey between Find and Replace made that behavior confusing.

FWIW many [if not all] other editors will display the appropriate Find vs Replace dialog if the dialog is not visible when the hotkey is pressed again.

**Comment by roblourens** [comment]
This has been annoying me since I saw the other issue and started noticing it. I'd like to make the following change:

- If the search viewlet is not visible, `cmd+shift+f` or clicking the search icon collapses the replace box (if expanded)
- If the search viewlet is visible, `cmd+shift+f` or clicking the search icon has its current behavior.

Reason being that if someone is in the middle of using the viewlet to replace, they might be using `cmd+shift+f` to toggle focus with the editor, for example. But when they are starting a new search, we should hide the replace box.

I'd like to do the same for the editor find widget. Thoughts @sandy081?

**Comment by sandy081** [comment]
@roblourens Sure, we should definitely fix the behaviour if it is annoying. But, May I know the flow of the behaviour you are talking about?

One thingy which I observed is that `cmd+shift+f` is not always toggling between editor and search viewlet. If replace is in focus or one of the results is in focus `cmd+shift+f` focusses Search input box. May be we should always toggle from Search viewlet to editor and back ?

**Comment by roblourens** [comment]
I mentioned toggling just as an example of something that people use `cmd+shift+f` for when the viewlet is already open. I plan to keep the current behavior, whatever it is, when the viewlet is already visible.

**Comment by roblourens** [comment]
Fixed this on the search viewlet but not the editor find widget yet. We can wait to see if this is good.
