### ISSUE TITLE
 Restarting VS Code causes all window icons to flash

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/vscode#95148]
- VSCode Version: 1.45.0-insider (user setup)
  Commit: 44c5185373d5f209cd6c0b5d29a216fb801da34e
  Date: 2020-04-10T18:12:33.780Z
  Electron: 7.2.1
  Chrome: 78.0.3904.130
  Node.js: 12.8.1
  V8: 7.8.279.23-electron.0
- OS Version: Windows_NT x64 10.0.18362

After an Insiders update, I'm greeted by these flashing windows. They're so excited! All of them want me to greet them!

![image](https://user-images.githubusercontent.com/972891/79157864-31a3d200-7d8a-11ea-89d7-7a1a59dc0e54.png)

But ultimately this is exhausting for me (and it's super distracting). I don't want to click on every one of these windows to dismiss the alerts. Is there a way to disable this? I need VS Code to trust that I'm happy to see it, even if I can't dedicate myself to clicking on each of these windows.

**Comment by bpasero** [comment]
VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

Reading this issue, it seems to originate not from VSCode itself but rather one of these upstream components. As such, in order to resolve it, it would need to get fixed in the upstream component. I will go ahead and close this issue and kindly ask to report this issue to the upstream component if possible:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
