### ISSUE TITLE
Breakpoint displacement when source changes while debugging

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#95279]
- VSCode Version: MacOS Mojave 10.14.6
- OS Version: 1.44.1

Steps to Reproduce:

1. Have some source (TS) with indents, if-else, empty lines
2. Start debugging
3. While debugging, change the source before an empty line, adding reference to a new module (in this case `isRemotePath` function) , which will add a new_line in the top of the source file
4. Save the changes
5. Toggle a breakpoint (using mouse click) on the same line you changed
6. The breakpoint icon (red dot) is not added to the correct line (which you updated) but at the empty line right below, and you see the indent lines being displaced as well.

![Kapture_breakpoint_column_issue](https://user-images.githubusercontent.com/3781424/79286660-ab75b180-7e97-11ea-8f5c-1a737f8afc73.gif)

Does this issue occur when all extensions are disabled?: Yes/No

I also noted other _weird behaviours_ with the breakpoint icon on other pieces of source, like adding it in the middle of an identifier instead if its start. 

If I stop the debugging process and rebuild the source, the issue goes away.

Thank you

**Comment by weinand** [comment]
If you change source while a debug session is active, the runtime (e.g. node) does not pickup any changes of already loaded code, so it will continue to execute the old source. If you set breakpoints in the new source, the runtime might veto the location because it verifies the location against the old source. This make breakpoints "jump".

I addition your source is TS which means you need some TS -> JS transpilation running in "watch" mode, so that the JS executed by the runtime is always in sync with the TS source. 

@isidorn please correct me if my assessment is wrong and there is actually an error on our side.

**Comment by isidorn** [comment]
@weinand Your analysis sounds correct. VS Code ui does not change breakpoint location. Thanks

**Comment by alefragnani** [comment]
@weinand the source is from on of my VS Code extensions, and is being debugged running in `watch` mode. 

```
    > Executing task: npm run watch <
    > project-manager@10.11.0 watch /Volumes/xxxx/vscode-project-manager
    > webpack --watch --mode development --info-verbosity verbose

    Compilation  starting…

    webpack is watching the files…
```

The `watch` correctly detects changes, but the debug does not restart automatically (which is the expected behaviour today).

Hope this helps

**Comment by weinand** [comment]
Correct, the debug session doesn't restart automatically. 
Just press the "Restart" button in the debug bar or use the "Reload Window" command.
Both restart the extension host and the debug session.
