### ISSUE TITLE
`editor.wordSeparators` not respected in search input

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#95276]
Issue Type: <b>Bug</b>

Typing "foo:bar" into search and then using `cursorWordStartLeft` and `cursorWordEndRight` does not stop at the semicolon, despite it being in the list of word separators.

This also applies to
* Quick Open
* Find widget
* File names in the Explorer
* Quick filtering in lists
* Problems filter

Though it does work in
* Extensions search
* Integrated Terminal

VS Code version: Code - Insiders 1.45.0-insider (c8826e4ff5246775ebee0fb932402de6af55ddc8, 2020-04-14T05:58:16.222Z)
OS version: Windows_NT x64 10.0.17763

Extensions: none

**Comment by roblourens** [comment]
That's because these are native text inputs so it just uses the native behavior. Extension search is different, it's actually an editor instance. It would be great to replace all text inputs with editors but they are a bit expensive so that's not likely. I'll assign to @rebornix I dunno if there is an issue that would cover this.

**Comment by akbyrd** [comment]
@rebornix Which issue?
