### ISSUE TITLE
vscode.extensions.all misses local extensions

### ISSUE THREAD

**Issue by OmarTawfik** [microsoft/vscode#95272]
- VSCode Version: latest master
- OS Version: MacOS

The API `vscode.extensions.all` returns a list of available extensions. With the new remoting workflow, when connected to the remote host, this API would return different results based on whether the extension is running:
* locally (`extensionKind: ui`) -> returns all extensions (local + remote)
* remotely (`extensionKind: workspace`) -> returns only remote extensions

Steps to Reproduce:

1. Author an extension with the below `main.ts`
2. Run the extension and inspect the output
2. Observe that the list doesn't contain the local extensions

```ts
export async function activate(context: vscode.ExtensionContext): Promise<void> {
  vscode.window.showInformationMessage(vscode.extensions.all.map(e => e.id).join());
}
```

I think this should be fixed by making this API always return **all** extensions (as indicated by its name). Callers then can filter by the `extensionKind` property of the results if needed.

**Comment by alexdima** [comment]
This is intentional. Unfortunately, the API `extensions.all` was finalized and available in VS Code prior to VS Code remote. In the non-remote case, that API allows an extension to look at all other extensions, activate them and access their exported API objects. Many extensions have been written and do this.

But in the remote case, some extensions run on the same extension host process, while some extensions run on a different machine. We had two choices:

1. make `extensions.all` contain extensions from both machines. This would have broken all extensions that used this API and tried to look at some other's extension path, or tried to access the exported APIs from some other extension in the case where the extension was on another machine.

2. make `extensions.all` contain only extensions from the current machine. This is the option we have chosen, such that no breakage occurred and all existing extensions continue to work as expected.

So `extensions.all` now has the meaning: "All extensions that are available on this machine".
