### ISSUE TITLE
Markdown goes wrong when interprets some CJK characters

### ISSUE THREAD

**Issue by LittleYe233** [microsoft/vscode#95284]
I have found that some formats (like bold, italic, deleting line) can't be shown well when these special characters are between certain CJK characters.

I have tested in some situations and the testing results are as below.

| Code | Preview in Code | Result | Notes |
| :-: | :-: | :-: | :-: |
| `~~aaa~~` | ~~aaa~~ | OK | All letters |
| `~~（~~` | ~~（~~ | OK | Chinese bracket |
| `aa~~（~~` | aa~~（~~ | Failed | Chinese bracket and letter |
| `aa~~aa~~` | aa~~aa~~ | OK | Both letters |
| `符号~~aa~~` | 符号~~aa~~ | OK | Chinese characters and letters |
| `符号~~符号~~` | 符号\~\~符号\~\~ | Failed | All Chinese characters. And it can be shown by Github Markdown but failed in VSCode Markdown. |

Other grammers have the similar errors too. Test results about them are omitted.

I use strapdown.js to interpret the markdown codes above and they are shown well. So I think the Markdown interpreter in VSCode may have some bugs.

- VSCode Version: 1.44.0 (user setup)
- OS Version: Windows_NT x64 6.1.7601

Steps to Reproduce:

1. Create a new Markdown file.
2. Write the codes.
3. Click the 'preview' button and check the results.

Does this issue occur when all extensions are disabled?: Yes

**Comment by mjbvz** [comment]
The markdown preview uses markdown-it for rendering and I believe I see the same behavior [in the markdown-it demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%7C%20Code%20%7C%20Preview%20in%20Code%20%7C%20Result%20%7C%20Notes%20%7C%5Cn%7C%20%3A-%3A%20%7C%20%3A-%3A%20%7C%20%3A-%3A%20%7C%20%3A-%3A%20%7C%5Cn%7C%20%60~~aaa~~%60%20%7C%20~~aaa~~%20%7C%20OK%20%7C%20All%20letters%20%7C%5Cn%7C%20%60~~（~~%60%20%7C%20~~（~~%20%7C%20OK%20%7C%20Chinese%20bracket%20%7C%5Cn%7C%20%60aa~~（~~%60%20%7C%20aa~~（~~%20%7C%20Failed%20%7C%20Chinese%20bracket%20and%20letter%20%7C%5Cn%7C%20%60aa~~aa~~%60%20%7C%20aa~~aa~~%20%7C%20OK%20%7C%20Both%20letters%20%7C%5Cn%7C%20%60符号~~aa~~%60%20%7C%20符号~~aa~~%20%7C%20OK%20%7C%20Chinese%20characters%20and%20letters%20%7C%5Cn%7C%20%60符号~~符号~~%60%20%7C%20符号%5C%5C~%5C%5C~符号%5C%5C~%5C%5C~%20%7C%20Failed%20%7C%20All%20Chinese%20characters.%20And%20it%20can%20be%20shown%20by%20Github%20Markdown%20but%20failed%20in%20VSCode%20Markdown.%20%7C%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

Please file this issue upstream [against markdown-it](https://github.com/markdown-it/markdown-it/issues) since we cannot fix this on the VS Code side

**Comment by LittleYe233** [comment]
@mjbvz I found the same issue on 'markdown-it'. Thanks for your answer!
