### ISSUE TITLE
窗口 (Persist window size and location across restarts)

### ISSUE THREAD

**Issue by gentoo96** [Microsoft/vscode#9534]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.希望右键打开的时候 和原来的窗口一样大

**Comment by kieferrm** [comment]
Please provide information in English so that everyone in the community has a chance to understand the issue and any related discussion.

**Comment by rebornix** [comment]
From what he said, the repro steps can be

1. Open VS Code, Maxmize the Window
2. Right click VS Code icon on the task bar
3. Click "New Window" task.

A new window is opened but it's not Full Screen as the existing one. @gentoo96 wishes the sizes of these two windows are the same.

**Comment by gentoo96** [comment]
1.Open VS Code, Resize the window
2.close the window
3.Right to open the file(Right menu)

After closing the window,Open vscode Right menu,
No remember window size and position


[cid:f02491a8-9d0f-4494-b372-b7649f474953]

________________________________
发件人: Kai Maetzel <notifications@github.com>
发送时间: 2016年7月20日 15:07
收件人: Microsoft/vscode
抄送: gentoo96; Author
主题: Re: [Microsoft/vscode] 窗口 (#9534)


Please provide information in English so that everyone in the community has a chance to understand the issue and any related discussion.

―

**Comment by Spown** [comment]
i think its a dup of #422

**Comment by bpasero** [comment]
Yeah, we currently do not persist any window sizes for the Nth+1 window that opens. We only do so if you have Code configured to reopen all folders you had opened (an opt-in setting). But in this case where a new empty window opens, we do not know which size to restore to because we typically associate settings with an opened folder.

**Comment by sprinkle131313** [comment]
@bpasero How about adding a "defaultSize" setting into user settings? For me at least, it would be fine if I could just change the default to be something more in my preference. I prefer to have a horizontally skewed rectangle than a square (which it is closer to). So then when I open a new window that isn't associated with a workspace/folder it will read from the user settings instead. Another setting could also be added "autoResizeDefaultSizeForNewWindows...", so that when a new window is created that isn't associated with a workbench and the size is changed. It will update the defaultSize setting. I'm not sure how practical that last implementation is, ideally you probably don't want to be edting the settings.json file. But just an idea of how it could be implemented. At the very least it would be nice to have a "defaultSize" setting, if nothing more.

**Comment by bpasero** [comment]
Please open a new issue with your desire 👍

**Comment by youurayy** [comment]
Do we need to make a special petition to get this fixed? Atom does this. Every sensible editor does this.

When I open a new window in VS Code on Mac, the new window takes about 1/3 of the screen and I need to manually resize it to make it bigger.

Sensible behavior: The window is opened and positioned with the size and position taken from the last user-sized and user-positioned window.

**Comment by gentoo96** [comment]
thank
