### ISSUE TITLE
Expose utility functions for Uri paths

### ISSUE THREAD

**Issue by iliazeus** [microsoft/vscode#95350]
Seeing as `joinPath` is now [a proposed API](https://github.com/microsoft/vscode/blob/b02307e53deacb2bd84e976449213b7768060367/src/vs/vscode.proposed.d.ts#L1963), it would be nice to also have [`dirname`, `basename` and `extname`](https://github.com/microsoft/vscode/blob/a94e5d915c29906bcf3e375f57420522c29c8e36/src/vs/base/common/resources.ts#L71-L85).

**Comment by ShadowSmog** [comment]
Zhshdjsjdjdjdkdkd

**Comment by dsanders11** [comment]
@jrieken, what work needs to be done to make this happen? It looks like from the link in the original comment that the code more or less already exists, it just needs to be exposed? `dirname` would be particularly useful with `joinPath`, since it lets you do `URI.joinPath(URI.dirname(uri), "foobar.txt")`.

Is it preferred to be a static function like `URI.joinPath`, so, `URI.dirname()`, or as a method on a URI object, like `uri.dirname()`?

**Comment by jrieken** [comment]
Close as out of source, but there is an updated version of the `vscode-uri` module which comes with these utils
