### ISSUE TITLE
Welcome page window remains open after opening a workspace/folder from it

### ISSUE THREAD

**Issue by ronakg** [microsoft/vscode#95363]
## Versions 

```
Version: 1.44.1
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:47:00.296Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

## Steps to Reproduce

Make sure `Workbench: Startup Editor` setting is set to `welcomePageInEmptyWorkbench`.

1. Open VSCode
2. Click a workspace/folder from the `Recent` list.

Expected behavior: The workspace/folder should open in the same window as `Welcome Page`.

Actual behavior: The `Welcome Page` remains open in the background because the workspace/folder opens in a new window.

Does this issue occur when all extensions are disabled?: Yes

**Comment by UndyingSoul** [comment]
## Versions
```Version: 1.44.1 (system setup)
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:48:12.622Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```
## Reproduction Attempt
I was unable to reproduce the issue, it seems everything works as intended. Here are the steps I followed to reproduce your issue.
1. I ensured I was on the latest update (1.44.1)
2. I changed the setting for `Workbench: Startup Editor` to `welcomePageInEmptyWorkbench`
3. I closed and reopened VSCode to get the Welcome Page open.
4. I opened a workspace/folder from the recent pane on the Welcome Page
5. The VSCode window with just the Welcome Page open closed and my workspace opened.

Instead of number 4, I also tried to open via the File>Open Recent context menu and had the same outcome.

**Comment by ronakg** [comment]
This might be specific to MacOS then.

I recorded a video that shows the issue - https://drive.google.com/open?id=13MwYs6VX2FO-Fu1q-bLDMTdKD1Le0vTd

**Comment by ronakg** [comment]
Never mind. This was caused by `Open Folders In New Window` set to `on`.
