### ISSUE TITLE
NPM Audit shows vulnerability in minimist when authoring extension

### ISSUE THREAD

**Issue by GabeDeBacker** [microsoft/vscode#95451]
- VSCode Version:
Version: 1.44.1 (user setup)
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:48:12.622Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

- OS Version:
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Author an extension using VSCode as a dev dependency. Our package.json looks like this
```
    "devDependencies": {
        "@types/glob": "^7.1.1",
        "@types/jquery": "^3.3.35",
        "@types/markdown-it": "^10.0.0",
        "@types/mocha": "^7.0.2",
        "@types/node": "^13.11.1",
        "@types/sarif": "^2.1.2",
        "mocha": "^7.1.1",
        "tslint-microsoft-contrib": "^6.0.0",
        "tslint-no-unused-expression-chai": "^0.1.4",
        "typescript": "^3.8.3",
        "vscode": "^1.1.36",
        "vscode-test": "^1.3.0",
        "tslint": "^6.1.1"
    },
```
These are all the latest packages. When running npm audit:

                       === npm audit security report ===
                                 Manual Review
             Some vulnerabilities require your attention to resolve
          Visit https://go.npm.me/audit-guide for additional guidance
  Low             Prototype Pollution
  Package         minimist
  Patched in      >=0.2.1 <1.0.0 || >=1.2.3
  Dependency of   vscode [dev]
  Path            vscode > mocha > mkdirp > minimist
  More info       https://npmjs.com/advisories/1179
found 1 low severity vulnerability in 453 scanned packages
  1 vulnerability requires manual review. See the full report for details.

Does this issue occur when all extensions are disabled?: Yes

**Comment by GabeDeBacker** [comment]
@Tyriar  - I believe you changed this recently #93662.

**Comment by usernamehw** [comment]
I think it's recommended to use `@types/vscode` instead of `vscode`.

**Comment by Tyriar** [comment]
I improved the situation, moving VS Code's main usage of minimist onto the non-vulnerable version. Assigning @octref who owns vscode-test (though this problem is with the old system?).

@GabeDeBacker FYI the recommendation is to move off of `vscode` and onto `vscode-test` and `@types/vscode`, we ended up splitting out `vscode` into two separate packages for the test runner and types.

**Comment by octref** [comment]
@GabeDeBacker We split `vscode` into `@types/vscode` and `vscode-test` [exactly for this concern]( https://code.visualstudio.com/updates/v1_36#_splitting-vscode-package-into-typesvscode-and-vscodetest) that the large dependency tree might contain a lot of vulnerabilities. Last time it was event-stream, this time miniminst, I'm sure in the future we'll have more. So please do the switch, it shouldn't be hard: https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode

**Comment by gjsjohnmurray** [comment]
I am seeing a warning about minimist, apparently because of my use of webpack

```
                       === npm audit security report ===


                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance


  Low             Prototype Pollution

  Package         minimist

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3

  Dependency of   webpack [dev]

  Path            webpack > watchpack > chokidar > fsevents > node-pre-gyp >
                  mkdirp > minimist

  More info       https://npmjs.com/advisories/1179


  Low             Prototype Pollution

  Package         minimist

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3

  Dependency of   webpack [dev]

  Path            webpack > watchpack > chokidar > fsevents > node-pre-gyp >
                  tar > mkdirp > minimist

  More info       https://npmjs.com/advisories/1179


  Low             Prototype Pollution

  Package         minimist

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3

  Dependency of   webpack [dev]

  Path            webpack > watchpack > chokidar > fsevents > node-pre-gyp >
                  rc > minimist

  More info       https://npmjs.com/advisories/1179

found 3 low severity vulnerabilities in 5503 scanned packages
  3 vulnerabilities require manual review. See the full report for details.
```

**Comment by octref** [comment]
We cannot upgrade `minimist` since it comes in through `mocha@5.2.0`, which no longer receives any updates. Upgrading `mocha` major version is a breaking change.

Verifier: Verify the NPM deprecation package if you still try `npm i vscode`

I added release notes:

In June 2019, we [split the `vscode` module into `@types/vscode` and `vscode-test`](https://code.visualstudio.com/updates/v1_36#_splitting-vscode-package-into-typesvscode-and-vscodetest) in light of the `event-stream` incident. Today, a [security alert for `minimist`](https://snyk.io/blog/prototype-pollution-minimist/) has caused security alerts for extensions that still depend on `vscode`, which depends on `mocha@5.2.0` and therefore `minimist@0.0.8`. Unfortuantely, `mocha@5.2.0` no longer receive updates and upgrading to a new `mocha` version would break existing functionalities.

We published a new version of `vscode` that removes some unnecessary dependencies. We also archived the [repository](https://github.com/microsoft/vscode-extension-vscode) and deprecated the [`vscode` module](https://www.npmjs.com/package/vscode) on NPM. Please [migrate](https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode) to `@types/vscode` and `vscode-test`.

**Comment by gjsjohnmurray** [comment]
@octref should I be concerned about [webpack's use of minimist](https://github.com/microsoft/vscode/issues/95451#issuecomment-615939197)?

**Comment by octref** [comment]
Seems they fixed it: https://github.com/webpack/webpack/issues/10561
