### ISSUE TITLE
Extensions Aren't Downloading

### ISSUE THREAD

**Issue by sharjeelsk** [microsoft/vscode#95503]
Issue Type: <b>Bug</b>

I am trying to download Vs Code Various extensions but its not downloading and error message keeps popping "Failed to install " and download Manually. I tried to change DNS but still it isn't working instead i have to download it manually

VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.8.1
flutter|Dar|3.8.1
vscode-markdownlint|Dav|0.34.0
r|Iku|1.2.6
python|ms-|2020.2.64397
cpptools|ms-|0.27.0-insiders3
material-icon-theme|PKi|3.9.3
java|red|0.55.1
vscodeintellicode|Vis|1.2.5
vscode-java-debug|vsc|0.24.0
vscode-java-dependency|vsc|0.8.0
vscode-java-pack|vsc|0.8.1
vscode-java-test|vsc|0.22.1
vscode-maven|vsc|0.21.0

</details>

**Comment by chrmarti** [comment]
Sounds similar to #95503.

@sandy081 Are we aware of any degradation on extension downloads?

**Comment by sandy081** [comment]
There were many DNS configuration issues on user side.

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by chrmarti** [comment]
@sharjeelsk Also: Are you behind a network proxy?
