### ISSUE TITLE
'Reveal in Side Bar' confused by case-sensitive FileSystemProvider

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#95510]
Issue Type: <b>Bug</b>

1. Clone https://github.com/microsoft/vscode-extension-samples.git
2. Open fsprovider-sample folder
3. Run the 'Launch Extension' configuration
4. When the Extension Development Host window opens, use its Command Palette to run `MemFS: Setup Workspace` followed by `MemFS: Create Files`
5. In Explorer expand xyz folder and its def subfolder.
6. Doubleclick on each of these four files in sequence:
![image](https://user-images.githubusercontent.com/6726799/79552734-53a39a00-8093-11ea-95fa-338abb959aef.png)

7. Working from left to right along the four tabs, use context menu on each in turn to invoke 'Reveal in Side Bar'
![image](https://user-images.githubusercontent.com/6726799/79552873-8c437380-8093-11ea-8a9a-23d6caba5c75.png)

8. :bug: fails to locate `upper.txt` in the tree. The first three work correctly.

VS Code version: Code - Insiders 1.45.0-insider (6e9a34c0de4181a99f11e106733ee3e8c9db79f1, 2020-04-16T05:45:56.832Z)
OS version: Windows_NT x64 10.0.18363

**Comment by gjsjohnmurray** [comment]
I have seen similar problems when my case-sensitive filesystemprovider provides a tree with two sibling folders whose names only differ in their case.

**Comment by isidorn** [comment]
@gjsjohnmurray thanks for filling this.
My guess would be that we have some assumptions about the platform we are on when we search for FileStats.
Looking at the code I see that we take the FileSystemProvide case sensitive capability into account, so not sure what is missing. Code pointer https://github.com/microsoft/vscode/blob/aecef14e24b4c3643bb6025c75819be4a608be1f/src/vs/workbench/contrib/files/common/explorerModel.ts#L378

@gjsjohnmurray would you maybe put a breakpoint there and check what happens when you trigger a reveal.
I can also look into ti next week if you are busy. Thanks!
