### ISSUE TITLE
quickOpenNavigate[Next/Previos]InViewPicker key bindings do not works

### ISSUE THREAD

**Issue by blez** [microsoft/vscode#95512]
- VSCode Version: 1.44.2
- OS Version: Ubuntu 19.10

Steps to Reproduce:

1. When navigate editors through QuickOpen "navigate next" and "navigate previous" work as "navigate next after next" and "navigate previous of previous". So simply said it skip next/previous editor.
Here are keybindings I use
```
    {
        "key": "ctrl+down",
        "command": "workbench.action.quickOpenNavigateNextInViewPicker",
        "when": "inQuickOpen"
    },
    {
        "key": "ctrl+tab",
        "command": "workbench.action.quickOpenNavigateNextInViewPicker",
        "when": "inQuickOpen"
    },
    {
        "key": "ctrl+up",
        "command": "workbench.action.quickOpenNavigatePreviousInViewPicker",
        "when": "inQuickOpen"
    }
````
`ctrl+tab` works ok, but `ctrl+down` and `ctrl+up` don't

Does this issue occur when all extensions are disabled?: Yes

**Comment by bpasero** [comment]
PR: https://github.com/microsoft/vscode/pull/95587

The issue is that we are listening to keys within the quick input control to do certain things but we do not prevent bubbling. This means our keybinding service will also receive these keys and check for actions to perform. In the old quick open widget we always prevented bubbling for that reason.
