### ISSUE TITLE
'${workspaceFolder}' can not be resolved in a multi folder workspace

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#95527]
A fork of https://github.com/microsoft/vscode/issues/94725 for a better fix

@connor4312 what do you think I should do here, don't add `${workspaceFolder}` in a multiroot workspace, or use the first folder, or something else?

**Comment by connor4312** [comment]
I would probably take the workspace folder containing the `program` for launch configs (if any) or the first workspace folder. We do some more advanced stuff in js-debug (e.g. using `lsof` on linux/darwin to resolve the folder for attached processes). We can copypasta some of that into the existing debuggers, or just use that simple logic since js-debug is on track to become default within the next few iterations anyway.

**Comment by roblourens** [comment]
I'll let you do that if you think we should copy the code out, or I could tack on a list of all the workspaceFolders, or whatever works

**Comment by connor4312** [comment]
I think the simple logic is fine :)

**Comment by mbomb007** [comment]
I think that would be fine. Since I realized the ambiguity just now in my own uses, I noticed it is possible to use `${workspaceFolder}/../folder` instead.
