### ISSUE TITLE
TypeScript: Show log command should always be available in command palette

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#95525]
To get more details about an issue I set Typescript logging to verbose. I reprod the issue.

Now I can't find the log file: nothing in the command palette, nothing in the setting description. The setting only mentions the log will be sent to a file.

Also: where is the log file actually? I can't find it.

**Comment by joaomoreno** [comment]
Oh @alexr00 told me there's a command for it... but only if you have a TypeScript file open. 😕  Should we always show this command regardless of the current open editor?

**Comment by IllusionMH** [comment]
Also works in JS files ;)

Would also make sense to do similar to 2 options: Restart TS server and Select TypeScript Version.

**Comment by mjbvz** [comment]
This is intentional. These commands are not intended for regular use so we don't want to clutter up the command palette with them all the time. Logging in particular is almost never useful to end users but we do need to make it relatively easy for them to collect the logs for us

When logging is enabled, we also print the full path to the log file in the `TypeScript` output channel:

![Screen Shot 2020-04-17 at 12 25 54 PM](https://user-images.githubusercontent.com/12821956/79606603-b3577080-80a6-11ea-82ca-a5e2a9ef11b3.png)
