### ISSUE TITLE
Allow tslint's comment style to disable TypeScript validation (visually) for lines/blocks of code

### ISSUE THREAD

**Issue by Jared-Dev** [microsoft/vscode#95538]
I've found at least one feature request (#66017) to disable TS Validation on a file basis, but it would be handy to have the option to disable the visual ques for specific lines or for whole code blocks.

Specifically, I'm working with tests and I'm intentionally leaving out args. For the sake of the file tree/working in the file itself it would be great if I wasn't being screamed at!

Something like...
```
// tsc-disable-next-line
// tsc-disable-line

// ...or

/* tsc-disable:2345 */
// ...validation disabled code 
/* tsc-enable:2345 */
```

Just to make sure it is said, I'm not actually concerned with the watcher *actually* ignoring that code. Just that VSC doesn't make me as the user aware of it.

**Comment by IllusionMH** [comment]
This should be requested in TS repo

Moreover TS already has `// @ts-ignore` and TS 3.9 will bring a bit better alternative [`// @ts-expect-error`](https://devblogs.microsoft.com/typescript/announcing-typescript-3-9-beta/#ts-expect-error-comments).

Ignoring exact codes is not implemented because different version of TS might produce different errors on the same line, but there is already request for that https://github.com/microsoft/TypeScript/issues/19139

**Comment by Jared-Dev** [comment]
Right, I guess that's why I was hoping VSC could have some flags to just ignore the TSC reporting.

I don't want the entire files warnings ignored.

**Comment by IllusionMH** [comment]
Just in case - these two are will ignore error for next line which should be enough for most cases.

In contrast to TSLint/ESLint that has ton of stylistic errors it is strange to hide TS errors for ranges.

**Comment by Jared-Dev** [comment]
For some reason whatever I had read made me think these would disable TSC's validation for the whole file!
