### ISSUE TITLE
Copy image pixels

### ISSUE THREAD

**Issue by Menci** [microsoft/vscode#95636]
VSCode has the ability to open images. Sometimes I want to copy the image pixels to the clipboard and paste it somewhere but I can't do it in VSCode.

This feature is very useful when working on a remote workspace.

**Comment by AdamMomen** [comment]
I really do support now I am trying all possible solution either with importing other libraries or using a hacky solution to get around I really believe this feature worth putting effort on. @Menci

**Comment by iliazeus** [comment]
@mjbvz, AFAIK, VS Code currently only has the API to put _text_ in the clipboard, not image data or other things.

Does that mean the API needs to be extended? Or it's better to just use a third-party library in the `image-preview` extension?

**Comment by Menci** [comment]
I think electron has the API to copy image to the clipboard.

**Comment by mjbvz** [comment]
Can you use a dom api inside the webview itself for this?

**Comment by ctlajoie** [comment]
The vscode API needs to be extended. Extensions are isolated such that you can't access anything "external", such as the DOM. If you could, it would be possible to do this using the the [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard). There is an Image Paste extension that works around this limitation in a very hacky way, and it does not work if you are hosting vscode remotely, such as in [code-server](https://github.com/cdr/code-server).

This seems like a similar request to #77790. Might want to upvote that one too for good measure. We really need this in order to make remote documentation writing possible.

**Comment by mjbvz** [comment]
Yes but webviews can run arbitrary scripts that can access the dom of their content. Here's the script run inside the image preview:

https://github.com/microsoft/vscode/blob/a0328d26aca420f9d0606b825f5a326dc6d0d398/extensions/image-preview/media/main.js#L1

Worth trying to see if it works at least

**Comment by iliazeus** [comment]
So I've tried to take a look at this.

I couldn't make the "`contenteditable` + `document.execCommand('copy')`" approach work, because it's the HTML that gets copied, not the image itself. ([jsfiddle demo](https://jsfiddle.net/ka024htb/54/))

And it looks like we can't use the [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API), because (as far as I undersand) we're not in a secure context.
