### ISSUE TITLE
Icons should have transparency. 

### ISSUE THREAD

**Issue by himanshub16** [Microsoft/vscode#9564]
- VSCode Version: 1.3.1
- OS Version: Debian Stretch

The icon (twisted), should have transparent background in the mid of the twist, which makes it feel like visible through the eye of the logo. Currently, it is white. #

**Comment by boazsegev** [comment]
This is also an issue on macOS...

The twisted application logo has white "eyes" and a very strong white border... and although the white border is a question of taste, the white "eyes" are unexpected and look like a mistake rather an intentional design.

This is especially true considering the "Zoom" effect on the macOS Dock and the fuzzy background in the macOS full screen "Application Launcher".

**Comment by stevencl** [comment]
Thanks for the feedback. We're working on improving the application icon for VS Code. See this blog post for more details: https://blogs.msdn.microsoft.com/visualstudio/2017/03/08/iterations-on-infinity/

**Comment by boazsegev** [comment]
@stevencl ,

Interesting enough, reading through the article you sent mer, I noticed that - on Windows - neither the white border nor the white "eyes" appear on any of the icons.

For example [in the Start menu](https://msdnshared.blob.core.windows.net/media/2017/03/start-menu-490x350.png) the icons are all single color, and also when [used as a folder icon](https://msdnshared.blob.core.windows.net/media/2017/03/vs-for-mac-logo-caption2.png), there's no white border or eyes to be found.

B.

**Comment by bpasero** [comment]
We updated our icon, please see: https://code.visualstudio.com/blogs/2017/10/24/theicon
