### ISSUE TITLE
Not setting focus

### ISSUE THREAD

**Issue by TrueWill** [microsoft/vscode#95650]
On macOS Mojave, set focus to another window. Right-click on a file in the VSCode Explorer and select Rename (similar if add a new file). Start typing. The focus does not change to VSCode.

**Comment by isidorn** [comment]
This is because triggering the context menu does not pass focus to the electron app.
There is already an issue like this so closing as dupliacte. If you want to find it please search our issue repository for context menu focus.
Also it is an underlying electron bug so also check their repository. Thanks
