### ISSUE TITLE
vs code not responding after changing keyboard shortcut

### ISSUE THREAD

**Issue by gilios** [Microsoft/vscode#9566]
- VSCode Version: 1.3.0
- OS Version: win8 64bit

Steps to Reproduce: open vs code, file -> preferences -> keyboard shorcuts
enter:

// Place your key bindings in this file to overwrite the defaults
[
  {
    "key": "ctrl+e",
    "command": ""
  },
  {
    "key": "ctrl+e ctrl+d",
    "command": ["eslint.fixAllProblems", "editor.action.format"]
  }
]

i think the problem is the array commands, after entering this vs code cannot be used any more
need to open the json shortcuts file from %appdata% and edit it manualy

**Comment by kieferrm** [comment]
We fail in https://github.com/Microsoft/vscode/blob/master/src/vs/platform/keybinding/common/keybindingResolver.ts#L52.

There are several things that should happen here:
- fix the exception so that incorrect keybinding.json files don't harm vscode
- ensure keybinding.json files are validated correctly
- ensure intellisense is entering the correct completion

**Comment by alexandrudima** [comment]
Got fixed with a3493c75934a67ddadff71818ab8f7201eeb0fbf

**Comment by steveoh** [comment]
This is still a problem in 1.5.0

**Comment by alexandrudima** [comment]
@steveoh Can you please open a new issue with the precise contents you have in your `keybindings.json`.
