### ISSUE TITLE
CRITICAL: loop forever on the monospaceLineBreaksComputer

### ISSUE THREAD

**Issue by gpetrov** [microsoft/vscode#95686]
- VSCode Version: - Monaco 0.20.0 - March update
- OS Version: Windows and Mac

Causes the editor to go in infinite loop and eventually crash when all system resources are consumed.

It is caused by never ending loop because the variable **prevBreakOffset** somehow gets a value of undefines.

![image](https://user-images.githubusercontent.com/504730/79745704-11838e00-8309-11ea-8172-c72f279c3402.png)

**Comment by gpetrov** [comment]
Further investigation showed that this happens only when the editor was not visible yet. So the sizes can't be calculated.

That might be the reason for slow startup as the code loops till if finally sees the editor active.

Not a very reliable loop, if you ask me, that can loop for ever ... more checks need to be added.

**Comment by alexdima** [comment]
@gpetrov I cannot reproduce, I tried with the following snippet at https://microsoft.github.io/monaco-editor/playground.html:
```js
const domNode = document.createElement('div');
domNode.style.height = '100%';
const editor = monaco.editor.create(domNode, {
	value: "function hello() {\n\talert('Hello world!');\n}",
	language: "javascript",
    wordWrap: "on"
});

document.getElementById('container').appendChild(domNode);
editor.layout();
```

Can you please provide a snippet or a HTML page that reproduces the problem?

**Comment by dmx-patrick** [comment]
We weren't able to reproduce it with the browser version, we are using the ESM version.

I did some debugging on our code and noticed that it kept looping on the while loop at https://github.com/microsoft/vscode/blob/519ceb6283a884a82dcabc536ecb8a9bc125adbc/src/vs/editor/common/viewModel/monospaceLineBreaksComputer.ts#L139. The prevIndex changes from 0 to -1 in the next loop and then back to 0 again, this then goes on forever. The other variables don't change during the looping. There are no undefined variables like in the original screenshot and it is not the prevBreakOffset that is causing the problem.

Here the variables as when it loops, it seems to happen on lines that have tabs in it and that wraps. The looping only happens when the editor was not visible (display: none).
```
lineText = '						<tr dmx-class:table-danger="(alt <= 50)" dmx-class:table-warning="(alt <= 200)" dmx-class:table-primary="(alt <= 400)" dmx-class:table-info="(alt <= 800)" dmx-class:table-success="(alt >= 400)">'
prevIndex = 0 || -1
prevLen = 2
prevBreakingOffset = [161, 200]
prevBreakingOffsetVisibleColumn = [179, 218]
bestDistance = 178
distance = 217
```
Screenshot from scope data:
![image](https://user-images.githubusercontent.com/7900160/79858624-fe87c100-83cf-11ea-9653-9777b5f6e6c0.png)

**Comment by connor4312** [comment]
@alexdima are there verification steps for this?

**Comment by alexdima** [comment]
Unfortunately, this was not reproducible in VS Code. The test covers the case that was occuring.
