### ISSUE TITLE
dropdown.background not applied (debug)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#95704]
I played around with `dropdown.background` to set the background color of the dropdown widget. It works fine in the panel area but e.g. not for the debug dropdown.

That makes me wonder if we possibly have code in debug land that overrides this because the debug view is in the side bar. That is probably not a good idea given you can move views around.

![image](https://user-images.githubusercontent.com/900690/79764128-3c7bdb00-8325-11ea-98a2-f12acfc0663b.png)

**Comment by bpasero** [comment]
Same for remote explorer, so it is maybe more generic:

![image](https://user-images.githubusercontent.com/900690/79765215-9e891000-8326-11ea-8cb1-f9b3752add87.png)

//cc @sandy081 @sbatten

**Comment by isidorn** [comment]
You are correct we use the sidebar_background for the debug [here](https://github.com/microsoft/vscode/blob/95f26d2005ea0633aa48832d11e1f37068c4dcdb/src/vs/workbench/contrib/debug/browser/debugActionViewItems.ts#L53)

I thought the issue is that we also have a green play button which is part of this and we did not want to custmoise it becuase the Green play might not look good on the customised background.

As for the remote explorer I have no clue.

**Comment by bpasero** [comment]
I think the remote one is covered via https://github.com/microsoft/vscode/issues/95705

**Comment by isidorn** [comment]
That one was probably a copy paste mistake from debug land :)

**Comment by sbatten** [comment]
last milestone @misolori  and I saw this differentiation and assumed it was intentional that all sidebar dropdowns do not honor the theme color. this meant that if you drag terminal or output to the sidebar (in their own viewlet), they will also skip using the theme color for dropdown

**Comment by isidorn** [comment]
I am opening this for a PR. 
Code pointer https://github.com/microsoft/vscode/blob/95f26d2005ea0633aa48832d11e1f37068c4dcdb/src/vs/workbench/contrib/debug/browser/debugActionViewItems.ts#L53

The debug select box should listen to style changes and also style the background of the Green Play button.

**Comment by isidorn** [comment]
Adding lable bug so we get this verified.
