### ISSUE TITLE
Temporary color/theme for vscode instance to recognize between different windows

### ISSUE THREAD

**Issue by xfudox** [microsoft/vscode#95748]
Sometimes i need to work with more vscode windows and sometimes those windows are connected trough ssh to staging/poduction servers so it would be very helpful to be able to change single vscode window color to fast recognize which window i'm on without the need to read the title bar.

Actually changing the theme/color applyto every vscode instance and is permanent, i mean the change is persistent if i close vscode and reopen it; it would be nice to have a temporary color change per instance, so i can have multiple vs code windows of different color without affecting the default theme/color.

**Comment by marckassay** [comment]
I completely understand, as I also experienced this need. As an immediate solution, what you can do is set the `workbench.colorTheme` to a different theme for one of those VS Code instances. You can do this in the root project folder by having:
```
// .vscode/settings.json
{
    "workbench.colorTheme": "Posh Azul"
}
```
This example is using a custom theme, which is the same theme as the one I use everyday, but with just some of the UI background properties set to a different color so that I can immediately make a distinction between the two.

The 2 links I referenced to make this custom theme are:

- [create your own color theme for visual studio code](https://livierickson.com/blog/create-your-own-color-theme-for-visual-studio-code/)
- [create a new color theme](https://code.visualstudio.com/api/extension-guides/color-theme#create-a-new-color-theme)

**Comment by marckassay** [comment]
As an alternative to my solution, you can simply set the following into the `setting.json` file:
```
{
  "workbench.colorCustomizations": {
        "activityBar.background": "#ff000030",
        "titleBar.activeBackground": "#ff000030",
        "sideBar.background": "#ff000010",
        "statusBar.background": "#ff000030",
  }
}
```

**Comment by xfudox** [comment]
@marckassay thanks for your response, it indeed is a very simple and quick solution so i'll go with this for now.

**Comment by IllusionMH** [comment]
There is [Peacock](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) extension that allows quickly generate color customization for workspace

**Comment by sbatten** [comment]
As @IllusionMH has mentioned, Peacock is a very popular extension used for automating the solutions also listed above.
