### ISSUE TITLE
Environment Variable Format Change

### ISSUE THREAD

**Issue by SaschaStenger** [microsoft/vscode#95763]
Version: 1.44.2 (user setup)
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T16:36:23.138Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

When using VSCode with python behind a proxy.
Earlier versions of VS Code allowed to set environment variable for certificates by setting
 `"REQUESTS_CA_BUNDLE": "PATH_TO_CERTIFICATE",` in the settings.json

This is no longer setting the variable. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by chrmarti** [comment]
/causedByExtension

`REQUESTS_CA_BUNDLE` appears to be a feature from the Requests Python library. I assume you are using the Python extension and that has stopped working.

This is caused by the Python extension. Please file a new issue for it: https://github.com/microsoft/vscode-python/issues/new/choose
