### ISSUE TITLE
Undo cursor - Cursor history lost after any editing

### ISSUE THREAD

**Issue by chavlji** [microsoft/vscode#95798]
- VSCode Version: 1.45.0-insider
- OS Version: Darwin x64 19.3.0

Steps to Reproduce:

1. Open some file, click on a few different places - try `undo cursor` - works as expected
2. Open some file, click on a few different places, press 'abc' to edit the file - try `undo cursor` - nothing happens. Cursor history is lost! Why?!

History is also lost on character delete, paste,... any kind of editing.

Does this issue occur when all extensions are disabled?: Yes

**Comment by chavlji** [comment]
vscodebot that's not it...

**Comment by alexdima** [comment]
@chavlji The cursor history is cleared when doing edits. This is intentional, because all the positions and selections remembered in the cursor history must be invalidated when doing edits because they might not make sense anymore.

Here is a simple example:
* select on line 10
* select all
* delete

The file is now empty. If we were to attempt to restore the cursor via cursor undo, it will attempt to go to line 10 and that does not exist.

The above is just an example, all kinds of edits can be done which invalidate the remembered cursor positions.

So, conceptionally the cursor undo (also named soft undo in other editors) is just existing between undo stops.
