### ISSUE TITLE
workbench.action.terminal.deleteWordRight not found

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [microsoft/vscode#95802]
Issue Type: <b>Bug</b>

Just run into this problem today after upgrading to the latest insiders version. See the screenshot below. 

![image](https://user-images.githubusercontent.com/1993919/79919538-9c918080-83fc-11ea-871d-b68d466c34c7.png)

VS Code version: Code - Insiders 1.45.0-insider (b83339a3a7bd8e3ec8a8b79deda9c37e0d91f094, 2020-04-21T05:38:43.781Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (1.83GB free)|
|Process Argv|-psn_0_14470604|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.5.1
vscode-database|baj|2.2.0
path-intellisense|chr|1.4.2
bracket-pair-colorizer|Coe|1.0.61
vscode-markdownlint|Dav|0.34.0
gitlens|eam|10.2.1
LogFileHighlighter|emi|2.8.0
shell-format|fox|7.0.1
seito-openfile|Fr4|1.8.5
mdmath|goe|2.4.0
gc-excelviewer|Gra|2.1.34
open-file-from-path|jac|1.3.3
latex-workshop|Jam|8.8.0
vsc-space-block-jumper|jmf|1.2.2
center-editor-window|kai|2.3.0
vscode-docker|ms-|1.1.0
python|ms-|2020.3.71659
sqltools|mtx|0.21.7
highlight-dodgy-characters|nac|1.0.0
neuron-IPE|neu|1.0.4
vscode-ipython|pan|0.5.0
advanced-new-file|pat|1.2.0
vscode-versionlens|pfl|0.25.0
vscode-yaml|red|0.7.2
vscode-dired|rru|0.0.5
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.3.1
vscode-fileutils|sle|3.0.1
emacs-mcx|tut|0.18.0
vscodeintellicode|Vis|1.2.6
vscode-icons|vsc|10.1.1
org-mode|vsc|1.0.0
markdown-all-in-one|yzh|2.8.0

</details>

**Comment by Tyriar** [comment]
This command was removed intentionally as all it did was send something to the terminal which can be done generically with the `sendSequence` command. If you want to run this command now you need to call this command:

```json
{
	"key": "ctrl+delete",
	"command": "workbench.action.terminal.sendSequence",
	"when": "terminalFocus",
	"args": { "text": "\u001bd" }
}
```

This does the same thing as pressing `alt+d` in the terminal.

While the old very specific commands were nice because they were named, they were also a black box and it wasn't clear how it worked. I'm hoping https://github.com/microsoft/vscode/issues/94556 gets fixed and that way you can open the default keybindings file and be able to see exactly how they work:

![image](https://user-images.githubusercontent.com/2193314/80020887-9b109880-848e-11ea-93a2-329defae98d3.png)

**Comment by Tyriar** [comment]
It's possible an extension is calling this command, in which case I'd be interested to hear which one

**Comment by Tyriar** [comment]
Ok I just fixed it, this is what you should see soon which helps users understand what is happening:

![image](https://user-images.githubusercontent.com/2193314/80025518-a3200680-8495-11ea-91b9-eaf58d4d2633.png)

**Comment by amelio-vazquez-reina** [comment]
Thanks @Tyriar 👍 I actually originally tried to use `sendSequence` (see [this Q](https://stackoverflow.com/questions/58476611/forward-backward-words-in-the-vscode-terminal/58477220#58477220) of mine in SO for context), but I couldn't find the control sequence for forward/backward deletion ([see this follow-up question of mine](https://unix.stackexchange.com/questions/554269/xterm-control-sequences-for-backward-forward-word-deletion) in Unix.SE  where I ask for the **XTerm control sequence** for forward/backward deletion, and I am told that none exist (by [Stéphane Chazelas](https://unix.stackexchange.com/users/22565/st%c3%a9phane-chazelas) a well-known top user on the site). Hmm, what am I missing here? e..g how did you know that was the right sequence of characters to send?

**Comment by Tyriar** [comment]
@amelio-vazquez-reina those are based on common keystrokes and aren't guaranteed to work. I see backward-kill-word is mentioned, I think that's one of them. You can see the comments where these keybindings are added for what they are:

https://github.com/microsoft/vscode/blob/78f299ee51a427e53b45f53df4b05dbb67e38e31/src/vs/workbench/contrib/terminal/browser/terminal.contribution.ts#L177-L198

Also the way I typically get these sequences is by enabling [escape sequence logging](https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-escape-sequence-logging) in VS Code which will print out the character codes that get sent to and from the terminal:

![image](https://user-images.githubusercontent.com/2193314/80109358-3f97e680-8532-11ea-94db-5a23e8bc7334.png)

But yeah, all this is best effort and may not actually work. Since the sendSequence command and out keybindings system is so flexible though you can get whatever behavior you're after if your shell lets you do it.
