### ISSUE TITLE
find action: support multiple cursors

### ISSUE THREAD

**Issue by siegebell** [microsoft/vscode#9584]
Feature request: The current behavior of the find action (`ctrl+f` or `f3`) replaces all selections (and cursors) with the next match result. It should instead [optionally?] respect multiple cursors, such that "find next" advances each cursor to the next match from its current position.

(See #9444)

**Comment by tvedtorama** [comment]
This feature would make it possible to move between the documentation comment and function heading while working with multiple cursors.  Or other cases where a some given keywords are present for multiple segments of a file. 

As of now, the navigation with multiple cursors are limited to end of line / next word and the likes.

**Comment by rebornix** [comment]
We closed this issue because we don't plan to address it in the foreseeable future. You can find more detailed information about our decision-making process [here](https://aka.ms/vscode-out-of-scope). If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Thanks for your understanding and happy coding!
