### ISSUE TITLE
Consider to show dynamic launch configs in Welcome view

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#95863]
With the new API #88230 we now have a way to find default debug configurations of a specific debugger. With #95835 they are surfaced in the (not so obvious) "Debug: Select and Start Debugging" command.

We should explore whether it makes sense to automatically show them in the debuggers Welcome view.

/cc @connor4312

**Comment by connor4312** [comment]
👍 that would be great. The dynamic launch configs are designed to edge ever closer to zero-config, so having them in the welcome view makes total sense. This does require activating the extension where the welcome view currently doesn't, but with dynamic configurations we activate them anyway to display the configurations in the select menu.

**Comment by isidorn** [comment]
Agree. We should definetly show them somehow in the welcome to come closer to the zero config. We should at least have an action which would invoke a quick pick with all of them listed (since showing all of them in the welcome view does not scale).
Will ponder more next milestone.

**Comment by isidorn** [comment]
Played around with this and I have a first version:
I have pushed this to Master so you can play around with this and provide feedback.

The best name I could come up with is `Detect then Run and Debug`.
This action currently is always enabled (since at least the js-debug is there).

Feedback very welcome!

Case when current file can not be debugged
![Screenshot 2020-05-12 at 12 58 47](https://user-images.githubusercontent.com/1926584/81676649-7174dc80-9450-11ea-9ea0-083db829b562.png)

Case when current file can be debugged
![Screenshot 2020-05-12 at 13 00 07](https://user-images.githubusercontent.com/1926584/81676696-85204300-9450-11ea-90f2-36b9671500d6.png)

**Comment by weinand** [comment]
@isidorn that's a great start!

some comments:
- since "Detect then Run and Debug" is not a "direct" debug action but more of a "meta" action I suggest not to waste a prominent button for it, but just use a text with an embedded action instead. This gives us more space for explaining what the action does. I would place that text above the "To customize Run and Debug ..." text.
- in addition to the link we could add the first n (e.g. n == 2)  dynamic actions as buttons under  "Run and Debug". If this approach is useful we should consider to add another "presentation" property on the launch config that provides better control over this UI.

**Comment by isidorn** [comment]
@weinand thanks for feedback
1) Makes sense we can also have a Text + link to trigger the actoin. I just prefered this visually since it brings less clutter
2) This is a good idea, however a problem for that is that we would have to activate all the debuggers and make them provide detected configurations as soon as the welcome view is shown. Since this can take a long time this action would come in an an async way, thus resulting in an unstable UI.

**Comment by weinand** [comment]
@isidorn in our [Release Notes](https://code.visualstudio.com/updates/v1_43#_debugger-extension-api) we are suggesting to only contribute for the "current active language".
Since this applies for the dynamic debug configs too, we would only have to activate a single debug extension.

**Comment by isidorn** [comment]
@weinand correct, but even if we just activate a single debug extension it will happen that the configs are comming asyncly and thus the UI would "flash". Thuogh we can try it out.

**Comment by weinand** [comment]
@isidorn yes, let's try it.

Here are some additional ideas about the button you've introduced yesterday:

If we replace the button by "text with a link" we could use a generic wording like this:
"Show automatic debug configurations for <Node.js (preview)>" . The text in angle brackets is the name of the debugger that matches the "current active language".
Pressing some action in the text could open the existing quickpick.

If there is no current active language (and hence no single debugger) the text would just read "Show automatic debug configurations".

An alternative to the quickpick would be to activate the extension and collect the dynamic launch configs for showing them as buttons in the Welcome view. So the flashing would not come as a surprise but would be user initiated. 

If we don't want to use buttons, we could even modify the text: "Show automatic debug configurations for Node.js (preview)" would turn into something like:
"Automatic debug configurations for Node.js (preview): [Run Current File], [Run npm script]"

(The square brackets denote actions links)

**Comment by isidorn** [comment]
I have pushed the change to use the text and not the button.
In order to have a dynamic text we would need a bit more managing of the welcome views (disposing and adding them) which we do not do at the moment. Also we would have to activate and get debuggers based on the active language, something which we also do not do. Something I can look into next week if I find time.

![Screenshot 2020-05-13 at 17 38 52](https://user-images.githubusercontent.com/1926584/81834037-bf690d80-9540-11ea-87ac-8ff5f413b85d.png)

**Comment by weinand** [comment]
@isidorn great!

Since "Show automatic debug configurations" shows configs for **all** debuggers (and is less specific than the "Node.js Debug Terminal" button), I suggest to move it to the bottom and rename it to "Show **all** automatic debug configurations".

---

Since we have the "active language" already for the "where" clause, we could just match that statically with debuggers that contribute the "activate dynamic configs" event for that debug type. So it shouldn't be necessary to activate the extension for this.

**Comment by isidorn** [comment]
@weinand thanks for feedback. As you suggested I moved it to the end and am using "Show all" wording.

Also agree that we can look at the activation mechanism to just get the debuggers and not activate them.

![Screenshot 2020-05-13 at 18 35 36](https://user-images.githubusercontent.com/1926584/81840013-a95f4b00-9548-11ea-8cd7-e3d988f93fe6.png)

**Comment by isidorn** [comment]
I do not plan to push further changes here for May since we code freeze today. Thus moving out of the milestone and we can fine tune this next milestone.

**Comment by isidorn** [comment]
No furhter changes planed here, thus closing
