### ISSUE TITLE
Inconsistent focus feedback on dropdown

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#95870]
Small nit, I often find this feedback to not look so polished:

![image](https://user-images.githubusercontent.com/900690/79981461-02394780-84a5-11ea-88f7-d2564ecbc0db.png)

vs.

![image](https://user-images.githubusercontent.com/900690/79981475-06fdfb80-84a5-11ea-9354-80368a745195.png)

The debug dropdown is probably special, but can we expand the outline around the entire control?

**Comment by isidorn** [comment]
Yeah we could improve this.
We use the outline for focus, the outline has to have the same shape as the html object. Thus it has to be a rectangle of those dimensions.
Using outline offset I could best put it like the attached picture
I think it is better than current state so will push that.

Expanding around the entire control would not be correct since the foucs is first on the dropdown and then on the play aciton. Users should be able to tab into both.

Keeping this open since it is still not perfect, and maybe somebody provides a good pr

![Screenshot 2020-04-22 at 17 38 07](https://user-images.githubusercontent.com/1926584/80002602-248c8e80-84c0-11ea-93cb-b74de3b3c3b2.png)

**Comment by jeanp413** [comment]
Created a PR that polishes the outline

**Comment by isidorn** [comment]
Thanks a lot for the PR, commented on it.

**Comment by bpasero** [comment]
The dropdown is not a strict rectangle with round corners, but I guess we cannot get that outline to have round corners? @misolori ?

**Comment by misolori** [comment]
Correct that we an't do this via outline, we'd have to switch to using borders instead.
