### ISSUE TITLE
Cannot find name 'require' when set to language mode: javascript

### ISSUE THREAD

**Issue by Dygerati** [Microsoft/vscode#9591]
- VSCode Version: 1.3.1
- OS Version: OS X Yosemite

Steps to Reproduce:

1. Create index.es6 file
2. Set language mode to javascript
3. Note linter errors for any require statements, export statements, etc. 

I've also tried setting the "file.associations" property in the JSON settings file, same result. Red underlines under all "exports" and "require" statements.

**Comment by kieferrm** [comment]
@Dygerati pls provide sample workspace/file. Which linter extensions do you have installed? How are they configured? Do you see the same issue when starting vscode with the `--disable-extensions` command line option? Thx!

**Comment by Dygerati** [comment]
The file's really simple; attached:

[example.zip](https://github.com/Microsoft/vscode/files/378767/example.zip)

This is what I'm talking about:

![screen shot 2016-07-22 at 10 21 49 am](https://cloud.githubusercontent.com/assets/444632/17065347/333ded6e-4ff6-11e6-9cc1-eec0d140e0ae.png)

The issue persists with no extensions, and I never really installed anything other than themes so far. The red underlines, even though I've got it set to javascript, are the problem. 

Let me know if you need anything further!

**Comment by kieferrm** [comment]
@Dygerati Thanks! A picture always helps. It looks like you write a nodejs program.  For now, vscode does not know about nodejs out of the box. You have to ***teach*** it.  Since Vscode uses typescript behind the scenes (it's nicely explained in [our doc](https://code.visualstudio.com/docs/languages/javascript)) you do this by adding the appropriate typing files to your project. See the the `TypeScript definition file` section in [our doc](https://code.visualstudio.com/docs/languages/javascript#_intellisense).

**Comment by Dygerati** [comment]
I appreciate the explanation, although I'm a little confused at your statement that VSC doesn't _know_ about node.js, since it *does* seem to know (or at least not complain) as long as the extension is *.js. The issue only makes itself known with a non-standard extension, which I'd hoped could be quickly addressed by simply adding it to the `fileAssociations`.
