### ISSUE TITLE
references-view.next/prev commands don't exist?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95912]
Repro:

1. Run out of sources
2. Open default keybindings json file
3. Search for references-view

![image](https://user-images.githubusercontent.com/2193314/80023113-e6787600-8491-11ea-9063-5a2ffab34611.png)

**Comment by alexdima** [comment]
@jrieken This is happening because the extension `ms-vscode.references-view` does not contribute a command called `references-view.prev`, just a keybinding for it. The command is registered in source code, but never mentioned explicitly in the `package.json` `commands` section:

![image](https://user-images.githubusercontent.com/5047891/80347060-12b63d00-886c-11ea-9d99-d0efed34c6e5.png)

**Comment by jrieken** [comment]
> @jrieken This is happening because the extension ms-vscode.references-view does not contribute a command called references-view.prev, just a keybinding for it.

Which is very much allows and therefore we shouldn't show the squiggle

**Comment by Tyriar** [comment]
> Which is very much allowed and therefore we shouldn't show the squiggle

Why wouldn't we add it to `commands` though? I'm guessing that's why the description is missing for only them.

![image](https://user-images.githubusercontent.com/2193314/80376244-66199280-884e-11ea-801d-da05d377284c.png)

**Comment by alexdima** [comment]
@jrieken of course it is allowed :). 

But we are nice for built-in extensions that contribute keybindings, such that commands can be known statically (without activating all extensions) and such that we can define a schema that knows about those commands.

In other words, the alternative is to remove the enum schema for `command` from `keybindings.json` and leave it as a `string`, which is IMHO not better for our users.

Is there a particular reason why we cannot have this command in the `contributes` / `commands` section? Can we please just add them there?

**Comment by jrieken** [comment]
> Is there a particular reason why we cannot have this command in the contributes / commands section? Can we please just add them there?

Sure, sure - but won't this problem reoccur with every 3rd party extension that is like mine?

**Comment by Tyriar** [comment]
FYI my motivation in this area (https://github.com/microsoft/vscode/issues/94556, https://github.com/microsoft/vscode/issues/95909, https://github.com/microsoft/vscode/issues/94965) is because I plan on directing people to the default keybindings file in the release notes and docs to help them understand how the `workbench.action.terminal.sendSequence` command works. Having warnings all over the file makes it look unpolished.

For third party extension commands this seems like something they should fix as well so the command gets a nice name, so the warning a good thing?

**Comment by alexdima** [comment]
@jrieken Yes, that happens for any extension that contributes a keybinding, but does not contribute the command.

There is a file called `keybindings.json` and it currently has a JSON schema. The JSON schema is computed by looking at contributed commands in `package.json`, which make it to the CommandsRegistry, so that one is asked about commands. 

Do you know of another way to create a JSON schema with all the commands? Otherwise, we would need to activate all of the installed extensions, and wait for them to call `vscode.commands.registerCommand` and only afterwards open `keybindings.json`.

**Comment by jrieken** [comment]
> Do you know of another way to create a JSON schema with all the commands?

You can merge the static list with the information from the `CommandsRegistry` - which also fires `onDidRegisterCommand`-events when commands come and go. 

Anyways, having the schema is great, it helps with suggestions and maybe hover, but IMO the warning squiggle is too aggressive. I am sure there is a way to configure JSON to be less aggressive about this

**Comment by alexdima** [comment]
Yes, that is how it is implemented. [It uses the `CommandsRegistry` to compute the schema](https://github.com/microsoft/vscode/blob/abb4a35cfc26102f93fd00df7b59ce1a19c2017a/src/vs/workbench/services/keybinding/browser/keybindingService.ts#L753), and that is being read on startup and again after the extensions have been scanned.

We could add a listener for `onDidRegisterCommand`, but I don't know how good of an idea that would be since we use dynamic commands for so many things like hovers, code lenses and code actions and that might cause the JSON schema to change all the time.

But even reading the commands again and again still does not help in this specific case. If the extension does not list the command in the `contributes/commands` section and if the extension is not yet activated, the command will not be in the `CommandsRegistry`. So it is still possible to open `keybindings.json` and have missing commands.

So I guess the question here is more if there should be squiggles or not for unknown commands. I don't know if this is something JSON supports. But I tend to think that there should be squiggles, because that can indicate a typo or an uninstalled/disabled extension. Let's call this specific case the "hidden commands" case. For these "hidden commands", how could the user know about their id and add them to `keybindings.json`? Since they don't show up in the keybindings editor, nor in the command palette, the "hidden commands" could appear in user `keybindings.json` only if the user has intimate knowledge about the extension or in default `keybindings.json` only if the keybinding is contributed by the extension itself.

All in all, I think the best course of action right now is to simply add those 2 missing commands to the `package.json`.

**Comment by jrieken** [comment]
> right now is to simply add those 2 missing commands to the package.json.

Yeah, we have all agreed to that and this change will but but that's just bandaid. It will re-occur with all extensions using this pattern. E.g opening the default keybindings on my machines shows more of these warnings for various extensions. 

> So I guess the question here is more if there should be squiggles or not for unknown commands. I don't know if this is something JSON supports.

cc @aeschli who might know that

**Comment by aeschli** [comment]
In the JSON schema, if you want to provide an enum but also allow any other string, do this:
`anyOf: [ { type: 'string': enum: [....] }, { type: 'string' } ]`
