### ISSUE TITLE
Table alignment in Markdown not working

### ISSUE THREAD

**Issue by antfu** [microsoft/vscode#95937]
Version: 1.45.0-insider
Commit: 6e9a34c0de4181a99f11e106733ee3e8c9db79f1
Date: 2020-04-16T05:41:45.257Z
Electron: 7.2.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

----

Steps to Reproduce:

1. Use [setDecorations](https://code.visualstudio.com/api/references/vscode-api#DecorationOptions) API in extension
2. Set hoverMessage as below

```ts
new MarkdownString(`
| A    | B     |
|-----:|-------|
|    a | b     |
| aaaa | bbbbb |
`)
```

![image](https://user-images.githubusercontent.com/11247099/80059196-ecd42400-855d-11ea-911a-7aa483efe801.png)

The `a` in the first row should be aligned to right.

I remember it was working in some old versions last year. But not sure exactly when this broke.

**Comment by octref** [comment]
Simpler repro: hover over this:

```js
/**
 * | A    | B     |
 * |-----:|-------|
 * |    a | b     |
 * | aaaa | bbbbb |
 */
function test() {}
```

**Comment by octref** [comment]
Now it's consistent with GitHub.

| A    | B     |
|-----:|-------|
|    a | b     |
| aaaa | bbbbb |

![image](https://user-images.githubusercontent.com/4033249/80253875-f6798c80-862e-11ea-9017-f25981964243.png)

@mjbvz fyi, the issue is `align` is ignored for `th` and `td. https://github.com/jupyterlab/jupyterlab/issues/3180 and https://github.com/jupyterlab/jupyterlab/issues/1812.

**Comment by antfu** [comment]
Thanks for the quick fix!

**Comment by octref** [comment]
np, btw wenyan is very interesting, I'd be interested in helping with editor support. Let me know if I can help :p
