### ISSUE TITLE
Can't open a folder when extensionHost debugging in web

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#95957]
Happens with both extensionHost and pwa-extensionHost.
Repro steps:
Open a folder with web (I used the pull request extension)
F5
A new tab opens with the extension host
Open a folder in the new tab

Expected: Still extensionHost debugging in the new tab
Actual: It just opens the folder in web VS Code, no extensionHost debugging.

**Comment by isidorn** [comment]
@alexr00 thanks for reporting
@weinand is this a known limitation of web extension host debugging?

**Comment by weinand** [comment]
no, that sounds like a bug

**Comment by bpasero** [comment]
@weinand the issue is that the `payload` from the URL is probably removed when opening the URL for the target folder. However, we do not blindly want to take all of the `payload` over, this needs to be carefully decide case by case. I think we actually have similar code in the Electron side to take properties over:

https://github.com/microsoft/vscode/blob/9450b5e5fb04f2a180cfffc4d27f52f972b1f369/src/vs/platform/windows/electron-main/windowsMainService.ts#L1459-L1464

**Comment by weinand** [comment]
@bpasero where is the corresponding location where we could selectively copy the payload?

**Comment by bpasero** [comment]
@weinand best is here:

https://github.com/microsoft/vscode/blob/ab42ffc44c709aded523b15399a070ae8c724824/src/vs/workbench/services/host/browser/browserHostService.ts#L115

That is the code that gets triggered whenever a window wants to open. We just need to make sure that the payload contains any of the existing payload we want to preserve.

**Comment by weinand** [comment]
@bpasero I've created a [PR](https://github.com/microsoft/vscode/pull/96211) with a fix. It would be great if you could review it.
