### ISSUE TITLE
VS code cant open or install any extentsion 

### ISSUE THREAD

**Issue by ahmedhussein20** [microsoft/vscode#96099]
We have written the needed data into your clipboard because it was too large to 
Issue Type: <b>Performance Issue</b>

VS code cant open or install any extentsion for unknown reason

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz (8 x 2893)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (10.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    96	  6624	code main
    0	    25	  5768	   utility
    0	    69	  6168	   shared-process
    0	    14	  6464	   electron-crash-reporter
    0	   143	  6716	   window (Chap01 - Visual Studio Code)
    0	    11	  2896	     watcherService 
    0	    11	 12136	       console-window-host (Windows internal process)
    0	    54	  9416	     extensionHost
    0	   152	 11800	   gpu-process
    0	    65	 11980	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Chap01 - Visual Studio Code)
|    Folder (Chap01): 1 files
|      File types: py(1)
|      Conf files:;
```

</details>
Extensions: none
send. Please paste.

**Comment by sandy081** [comment]
Do you seen any errors?

Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)
