### ISSUE TITLE
Arguments passed in launch terminal

### ISSUE THREAD

**Issue by andreeis** [microsoft/vscode#96091]
We want to implement in the CMake Tools VSCode extension arguments passing to the launch terminal. We realized that there are numerous situations of quoting and escaping that we would need to handle in order for the arguments to be passed properly in all the available types of terminals.

We were wondering if this is already handled centrally by VSCode, so that all the other extensions wouldn't have to worry all about the same thing. Is there some API we that can act as an intermediary between an array of arguments and any type of terminal supported in VSCode?

Or how do you suggest we best approach this on our side if there is nothing available from your side?

**Comment by Tyriar** [comment]
For `sendText` you can send whatever you want, for args quoting is done for you if you pass in a `string[]`, some cases might not work there which is why we let you use `string` here if you want to pass in a pre-quoted args string:

https://github.com/microsoft/vscode/blob/84ac04e8155d473868f5301eb979ed0dd527e116/src/vs/vscode.d.ts#L8044-L8048

The built-in capability is only provided for args as `string[]`, not for args as `string` or `sendText`.
