### ISSUE TITLE
The year is 2020 - and still their is no "basic solution" for "Launch in browser" 

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [microsoft/vscode#96106]
Why such **basic** feature? (Basic like **bold** text in Word -or- **add slide** on powerpoint) - need to get `350k` views from devs on **stackovefrlow** (And 23 answers + endless comments / ideas / tricks)? 

`350k users` Who were looking for the most basic thing to expect in code editor. 

https://stackoverflow.com/questions/30039512/how-to-view-my-html-code-in-browser-with-visual-studio-code/61419540#61419540

![image](https://user-images.githubusercontent.com/16711871/80266879-f7e69b80-86a6-11ea-93a1-d889b7aaee79.png)

## VS
On the other hand how simple and effective user experience (nodepad++) :

![image](https://user-images.githubusercontent.com/16711871/80266842-c241b280-86a6-11ea-80bc-c1703278579d.png)

**Comment by alefragnani** [comment]
I don’t think you need to wait for that being released _natively_ in VS Code, but instead, try using some of the extensions already available in Marketplace. I suggest you to try [some of these](https://marketplace.visualstudio.com/search?term=Browser&target=VSCode&category=All%20categories&sortBy=Relevance).

Personally, I use [Browser Preview extension](https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview) a lot, because it gives me a browser _inside_ VS Code.

Hope this helps

/extension-candidate

**Comment by Ezra-Siton-UIX** [comment]
I know I don't need to wait.
 
My issue related to the user experience. The idea of plugins is to add `extras`.

One more screenshot examples:
![image](https://user-images.githubusercontent.com/16711871/80310464-92e49000-87e3-11ea-869f-ed3fa7427f2f.png)

**Comment by alefragnani** [comment]
Sure, I’m just saying that, to wait for a tool to have certain feature natively, when it already provides via plugins, may not be necessary. But it depend solely on the team responsible for that tool, and the tool’s objectives. I was just trying to help you, and the VS Code team.

In my daily use, I prefer VS Code being as lightweight as possible, not only on its memory footprint, but also the amount of menus/commands available. I like the idea of choosing/switching the features for each of my development scenarios.

**Comment by Ezra-Siton-UIX** [comment]
Ok. Thanks
