### ISSUE TITLE
(CLI) Foreground recent window on code.exe

### ISSUE THREAD

**Issue by mcandre** [microsoft/vscode#96154]
On macOS, I habitually run `atom .` from the terminal, which either launches a fresh window or reuses an existing window, depending on whether the project is already open. This is a fairly fast workflow when operating across many different projects.

But in Microsoft Windows with Microsoft VSCode, `code .` creates redundant windows. This wastes resources and is annoying to cleanup.

Could VSCode detect on launch whether the specified project paths are already running in existing VSCode windows and foreground them better?

**Comment by alefragnani** [comment]
Hi @mcandre ,

If you want to _reuse_ the last active window, you should use `code . -r` or `code . --reuse-window`, otherwise it will by default, opens in a new window. 

I wouldn't change the default behaviour, so a new setting could be created. Maybe called `window.openCurrentFolderInNewWindow`, which is similar to the already existing `window.openWithoutArgumentsInNewWindow`, which handles running `code` _without arguments_.

Hope this helps

**Comment by sbatten** [comment]
If a directory is already opened in an existing window, that window will be brought to the foreground. This is already the default behavior. Could you clarify you case?

**Comment by alefragnani** [comment]
@sbatten If I understand correctly, @mcandre would like to change how `Code .` (With a dot, which opens the current folder) works today, and make it to _reuse_ the latest active window, by default. 

Today, the default behavior is open in a new window. If you want to reuse, you have to add `-r` parameter in the command line.

**Comment by bpasero** [comment]
> But in Microsoft Windows with Microsoft VSCode, code . creates redundant windows.

Not really, unless the folder is not yet opened. Needs more info about the steps.
