### ISSUE TITLE
Debugging a typescript library - breakpoint won't stop in lib

### ISSUE THREAD

**Issue by gasnier** [microsoft/vscode#96195]
- VSCode Version: 1.44.2 and 1.45.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Get repo https://github.com/gasnier/bug_debug_lib_in_vs_code
2. Steps are defined in the repo README.md

If you put a breakpoint in app/src/main.ts or app/src/appUsingLib.ts AND a breakpoint in lib/src/utilities => the debugger stops and everything works fine

If you put a breakpoint ONLY in lib/src/utilities => the debugger doesn't stop

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by jmaicaaan** [comment]
Same issue here. It doesn't stop when debugging my extension. I thought there's a problem on my extension but it turns out I'm not the one.

**Comment by connor4312** [comment]
Thanks for the issue @gasnier. I can repro this using our older debugger, but this appears fixed in our [new debugger](https://github.com/microsoft/vscode-js-debug#installation) (currently in preview) which takes a more resilient approach to sourcemap/breakpoint handling. I'd recommend trying that out, let me know if that fixes the issue you're running into.

**Comment by jmaicaaan** [comment]
Until the changes not out of preview, we need that extension for the meantime?

**Comment by connor4312** [comment]
Yes. We plan to switch js-debug to be the default debugger on Insiders next week, so if you use Insiders no action will be needed.

**Comment by jmaicaaan** [comment]
Got it, thanks for the quick response!
