### ISSUE TITLE
Remote debug to child process doesn't work as it does on localhost

### ISSUE THREAD

**Issue by Lazarencjusz** [microsoft/vscode#96229]
- VSCode Version: 1.44
- OS Version: Windows 7 / Red Hat 6.7 (Santiago)

Steps to Reproduce:

1. Create NodeJs simple server
2. Use NodeJs `cluster` to create child processes (f.e. 4, no more than CPU cores amount)
3. Run the server in debug mode (on Windows).
4. Create `attach` debug task with `autoAttachChildProcesses` property, provide debug port number
5. Run the Attach debug task to attach debugger to existing process
6. VS Code will attach to it recognizing child processes and breakpoints will work
7. Run NodeJs on other host (Unix type)
8. Try to attach the debugger to it providing host `address` in `.launch` config.
9. Debugger will be attached, but no child processes will be found and breakpoints will not work.

Does this issue occur when all extensions are disabled?: Yes

I am not able to use SSH debug in my organization.
I can assume that it does not work because of host OS, maybe it is possible to implement to VS Code such feature.

Problem description (with screanshots) are here on [Stack Overflow](https://stackoverflow.com/questions/61063936/vs-code-remote-debug-to-nodejs-in-cluster)

**Comment by Lazarencjusz** [comment]
Hi @alexr00, the issue can be related with #75513, but I am not sure because less details in issue description.

**Comment by Lazarencjusz** [comment]
Hi @weinand, are there any plans to handle this issue?

**Comment by weinand** [comment]
We are not planning to address this in the current Node.js debuggers but please try to use our new JavaScript debugger "JS Debug": see https://code.visualstudio.com/updates/v1_45#_new-javascript-debugger.

**Comment by Lazarencjusz** [comment]
Unfortunately, using this extension, I am even not able to attach to remote debugger.
Using options:
`"debug.javascript.automaticallyTunnelRemoteServer": false` `// and true`
 `"debug.javascript.usePreview": true`

**Comment by weinand** [comment]
VS Code's current approach for detecting child processes works by tracking child processes. Since this is only possible locally, you cannot use the "autoAttachChildProcesses" feature when attaching to a remote process. There is just no way to enumerate the **remote** child processes.

There are two options to work around that problem:
- if you know the debug ports of the remote child processes you can attach to them manually (just as you do with the main process).
- when using VS Code's "Remote SSH" extension, the "tracking child processes" will run remotely and will work just fine.

What exactly do you mean by "SSH debug"?

**Comment by Lazarencjusz** [comment]
Thanks for explanation about child processes.

By SSH debug I mean just debugging by "Remote SSH" extension, which, unfortunately, I am not able, for now, to use in my organization.
