### ISSUE TITLE
Allow customizing git status bar action

### ISSUE THREAD

**Issue by FiloSottile** [microsoft/vscode#96306]
The "Synchronize Changes" action performs a git pull and git push. This doesn't work with many workflows (for example with Gerrit, or anything that doesn't use merge commits), and is a pretty dangerous action when one just wants to pull the latest commits.

It would be nice to have a setting to customize the command that funs for the action, so one could for example set it to `git pull --rebase && git push` ot just `git pull --ff-only`.

**Comment by joaomoreno** [comment]
Why not configuring that with git settings instead? https://stackoverflow.com/a/13974638

Also, if you just want to pull, just run `Git: Pull` instead. No need to overload the sync action.

**Comment by FiloSottile** [comment]
I was hoping to customize the behavior of the status bar click. You're right that it might make more sense to simply bind it to a different action, so alternatively this could be a feature request to change the action bound to the status bar indicator.

**Comment by joaomoreno** [comment]
We can have a boolean setting which makes the status bar either show the sync action or a pair of pull/push actions.

**Comment by brunofin** [comment]
Pull and Push are different things and merging both actions into one single button can be dangerous. Imagine you are working `master` branch and you need to pull some changes but have accidentally committed something there on your local repo, your changes will be pushed to origin as well. This could lead to a bad situation at best and a catastrophic at worst.

I vote to split this into 2 buttons one for each action.

Also, I don't think I should need to configure and change git's default behavior just because one application I use has a design flaw. Git is fine. VS Code not so much and could use a little improvement.

**Comment by brunofin** [comment]
well intellij idea does that so I guess 👋
