### ISSUE TITLE
Not seeing setting sync info message everywhere

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96353]
re #96226

* have two computers
* both have settings sync off (at least both show "Turn on Pref Sync")
* on computer A it puts me right into the what-to-sync picker
* on computer B it shows a nice message
* ❓ I am confused. Is that because I am logged in on computer A?

<img width="650" alt="Screenshot 2020-04-28 at 11 17 27" src="https://user-images.githubusercontent.com/1794099/80470178-ecfb6780-8941-11ea-960c-6b5a6423b3ba.png">

**Comment by sandy081** [comment]
This dialog is to inform user that this is a preview feature and is only shown once before user turns on sync successfully on a given VS Code instance. It was shown on machine B you are using this feature there for the very first time and not shown on machine A because you used this feature already before.
