### ISSUE TITLE
Significant startup degradation with extensions disabled

### ISSUE THREAD

**Issue by andymilligan** [microsoft/vscode#96385]
[prof-930b.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/4545568/prof-930b.extHost.cpuprofile.txt)
[prof-930b.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/4545570/prof-930b.main.cpuprofile.txt)
[prof-930b.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/4545572/prof-930b.renderer.cpuprofile.txt)

1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`prof-930b.extHost.cpuprofile.txt`
-`prof-930b.main.cpuprofile.txt`
-`prof-930b.renderer.cpuprofile.txt`

**Comment by jrieken** [comment]
This is due to slow starting of other processes. It takes for instance 10+ seconds to start the extension host, the same is true for the crash reporter. This is usually due to AV software

<img width="907" alt="Screenshot 2020-04-28 at 14 49 43" src="https://user-images.githubusercontent.com/1794099/80489001-8127f780-895f-11ea-9b87-bae8f65b75d6.png">

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Aperf-startup

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/24884
