### ISSUE TITLE
Git: Dirty diff doesn't recognize manual encoding change

### ISSUE THREAD

**Issue by gromzhu** [microsoft/vscode#96380]
- VSCode Version:1.44.0
- OS Version:mac os mojave 10.14

Steps to Reproduce:

1.open a file in git repository ，which have simple chinese and encoding as gb18030
2.reopen it as gb18030
3.git will recognize all simple chinese as changes,because now the file is decoded by gb18030,but the git still decode the file using utf-8.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by joaomoreno** [comment]
Can you show me a screenshot?

**Comment by joaomoreno** [comment]
And can you send me the file which reproduces the issue?

**Comment by gromzhu** [comment]
> Can you show me a screenshot?

![0f48e10df9a6851d2f9434cbf](https://user-images.githubusercontent.com/15223544/80574744-fadde500-8a34-11ea-9290-7e50891e0e74.png)

**Comment by gromzhu** [comment]
> And can you send me the file which reproduces the issue?


[testfile.txt](https://github.com/microsoft/vscode/files/4550501/testfile.txt)

**Comment by joaomoreno** [comment]
I can't figure out how to fix this.

On one hand there's the actual diff computation which seems to use the wrongly detected default encoding. @alexdima how do encodings work in relation to [`editorWorkerService.computeDirtyDiff`](https://github.com/microsoft/vscode/blob/fb4950dc2435233503267b5e9608d460f627617d/src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts#L1100-L1100).

On the other, there's the inline diff editor, which isn't a @bpasero editor, so I can't seem to find any option to set encoding. @bpasero Any ideas there?

Are encodings only a workbench level concept? How do they translate to the editor widget level?

**Comment by alexdima** [comment]
@joaomoreno `computeDirtyDiff` is invoked with two text models. In our codebase, editor text models are instantiated with strings.

Strings are created from bytes. The code that creates the strings from bytes is responsible for interpreting the bytes with a specific character encoding. That code is somewhere in the FS provider, or perhaps in the FS service that sits on top of the FS provider.

In any case, the editor text model can only be constructed with strings, and not with bytes.

**Comment by bpasero** [comment]
I think somewhere you are implementing a file system provider for Git which probably drives this. At that layer you will have to convert using the proper encoding as detected and return that from your FS implementation (as UTF-8). My understanding was that you already to some kind of encoding detection?

As for diff editors: there is currently no way to change the encoding for one side to be different from the other side as far as I remember. At least the one in the status bar will always change it for both.

**Comment by joaomoreno** [comment]
> I think somewhere you are implementing a file system provider for Git which probably drives this. 

@bpasero No, [FS providers work on bytes](https://github.com/microsoft/vscode/blob/669b0daca0fe29ceb3addee5702bb3de3ad11a48/extensions/git/src/fileSystemProvider.ts#L160-L160). The string conversion happens in the workbench.

**Comment by bpasero** [comment]
@joaomoreno sure they work on bytes, I am aware of that, but you could implement your FS provider in a way that it passes the byte stream through a decoder (from `iconv-lite` - they support streams). We are doing the very same thing in our node.js based implementation, but on a slightly higher level (text file service) for layering reasons.

I think what I was suggesting is that you always return UTF-8, independent of what the underlying file has as encoding.

**Comment by joaomoreno** [comment]
@bpasero The user has a file which we fail to automatically detect an encoding. So they go to the status bar and choose a different encoding.

> @joaomoreno sure they work on bytes, I am aware of that, but you could implement your FS provider in a way that it passes the byte stream through a decoder (from iconv-lite - they support streams). We are doing the very same thing in our node.js based implementation, but on a slightly higher level (text file service) for layering reasons.

This makes no sense to me. Why would this be done an the FS Provider layer? The FS Provider should provide bytes as they are and the workbench should interpret them accordingly, especially because the choice of an encoding happens at the workbench level: extensions don't know about what encoding the user has manually chosen for this file.

And generally, why would we pay a performance cost for doing `bytes -> bytes (utf8) -> string` when we can simply do `bytes -> string` at the workbench level, where the encoding is either the manually chosen one, the setting one or the auto detected one?

**Comment by bpasero** [comment]
@joaomoreno it seems to me that we have 2 issues that maybe need different solutions:

**Dirty Diff Decorator**
When I look into the `dirtyDiffDecorator` I believe this one is still using the text model resolver service which dates back to the time where Git was not registering itself as FS provider, but content provider. Now that you changed that, instead what you can do is call `ITextFileService.files.resolve(uri, { encoding })` to get yourself a text file model with the encoding of choice.

However, I think what is still missing here is a way for you to know what encoding the user picked for the editor. Since you only seem to be operating on code editor models in the dirty diff, this information is lost at that point I fear. However, the model of the workbench has a property to get at its encoding: https://github.com/microsoft/vscode/blob/997b4c863a45f171570d5167fee31e74b018ba06/src/vs/workbench/services/textfile/common/textFileEditorModel.ts#L837 

I am understanding too little of the lifecycle of dirty diff to make more suggestions, so that would be something to learn in debt week maybe.

**Diff Editor**
The diff editor will directly be impacted when the user changes the encoding from the status bar. The flow is as follows:
* user changes encoding in opened diff editor
* we apply the encoding to the models in both sides of the diff editor
* this ends up re-reading the file from disk using the specified encoding

I just did a quick test comparing 2 files in `cp1252` encoding with inline diff editor and was able to change the encoding from the statusbar and show it correctly:

![Kapture 2020-04-30 at 14 22 02](https://user-images.githubusercontent.com/900690/80709728-10fbac00-8aee-11ea-8db8-c32cdf5c72b4.gif)

Given that, I wonder if something in the Git FS provider goes wrong during that way, but I do not see why yours would behave any different unless maybe you do some conversion on your layer.

**Comment by joaomoreno** [comment]
> When I look into the `dirtyDiffDecorator` I believe this one is still using the text model resolver service which dates back to the time where Git was not registering itself as FS provider, but content provider. Now that you changed that, instead what you can do is call `ITextFileService.files.resolve(uri, { encoding })` to get yourself a text file model with the encoding of choice (something the text model resolver lacks).

This makes a lot of sense! 👍  I'll investigate.

> **Diff Editor**

Yeah, since in dirty diff I have access to the actual diff editor widget, I should be able to do the same, once I get a hold of the actual encoding.

Let's tackle it together next week 🙏

**Comment by bpasero** [comment]
Well, thing is I would expect everything to work fine for the diff editor at least. I can understand why the dirty decorator fails because that one is not knowing about the encoding, but the other case should work...

**Comment by joaomoreno** [comment]
That diff editor isn't a workbench editor, it's an embedded widget which I control. No one ever sets its encoding.

**Comment by bpasero** [comment]
@joaomoreno ah, sorry man, that was the missing piece. I somehow thought this was the normal compare editor, now I got it 👍

**Comment by joaomoreno** [comment]
@bpasero First attempt: https://github.com/microsoft/vscode/commit/2eb784f0e612c3e248e8a0c1447c303093c90e5b

Despite being [sure](https://github.com/microsoft/vscode/commit/2eb784f0e612c3e248e8a0c1447c303093c90e5b#diff-82247379e64b604beeb505d57ce38a7dR1138) to call `this.textFileService.files.resolve(originalUri, { encoding })` with the proper encoding, this only works for the first time I call that method. The second just seems to use the same encoding that was passed on the first call. Maybe there's some caching there?

I ended up exposing `onDidChangeEncoding` [here](https://github.com/microsoft/vscode/commit/2eb784f0e612c3e248e8a0c1447c303093c90e5b#diff-50b42b89b3f081bf5d0308f2eef07c37R412).

**Comment by bpasero** [comment]
@joaomoreno 

> I had to end up exposing onDidChangeEncoding here, I hope that's OK.

That is not really needed, you can use `this.textFileService.files.onDidChangeEncoding` instead.

> Despite being sure to call this.textFileService.files.resolve(originalUri, { encoding }) with the proper encoding, this only works for the first time I call that method. The second just seems to use the same encoding that was passed on the first call. Maybe there's some caching there?

Yeah that is arguable a flaw with the `resolve` method. If the model exists, `model.setEncoding` can be used, though would need to properly wire up the promises to return a proper async result. The only client of this today is if you change encodings from the status bar, but I think it would be OK to support this directly from the `resolve` method too if the model exists. Would need to do a quick check if anyone is calling this where the result could end up unexpected.

Btw since you now dropped the text model resolver service with refcounts, what is the lifecycle of the changes model that you resolve, I see no dispose?

**Comment by joaomoreno** [comment]
@bpasero Yup 

> Btw since you now dropped the text model resolver service with refcounts, what is the lifecycle of the changes model that you resolve, I see no dispose?

Yup that's a question for you actually: since `resolve` can either create or return an already created model... who is responsible for disposing it? That's the problem the ref counting was solving.

**Comment by bpasero** [comment]
> Seems a bit strange, since I already have a hold of the model, and with that general event I still have to write an ìf` statement to filter our what I don't want. 🤔

Yeah either way, fine with me.

> Yup that's a question for you actually: since resolve can either create or return an already created model... who is responsible for disposing it? That's the problem the ref counting was solving.

Actually I do something similar in `FileEditorInput`, I create a ref later that I then can dispose:

https://github.com/microsoft/vscode/blob/ef0366a74f300b56666066e370d09e15299f6252/src/vs/workbench/contrib/files/common/editors/fileEditorInput.ts#L243-L258

But I am equally fine to add a `encoding` option to the text model ref thingy.
