### ISSUE TITLE
Notebook: executing cells turns editor dirty?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96403]
Refs: #96279

I executed the notebook and wasn't sure why this turns the document dirty? We are surely not writing the results into the file are we?

![Kapture 2020-04-28 at 15 06 21](https://user-images.githubusercontent.com/900690/80490651-f98fb800-8961-11ea-9a25-c8f90617b995.gif)

**Comment by jrieken** [comment]
Yeah, that's something we need to look at. Notebooks can and often do save the output (we have decided against that for issues notebooks) but currently notebook extensions cannot control that, it's the UI that does this (and it shouldn't). For instance, an issues notebook shouldnt become dirty when running but for instance it should become dirty when lock/unlock a cell (since that's saved to disk)

**Comment by bpasero** [comment]
What worries me more is that my input seems to get lost a lot. Is the cell input not saved into the file?

**Comment by jrieken** [comment]
The input should always be saved!

**Comment by jrieken** [comment]
@rebornix Is this still the core or did you move this already to the extension side? My plan is 

* [ ] running doesn't change dirty change (e.g no change event)
* [ ] lock/unlock cell does emit a change event so that the UI can show dirty

**Comment by jrieken** [comment]
I have pushed a change that propagates `NotebookContentProvider#onDidChangeNotebook`, internally that's exposed as `INotebookTextModel#onDidChangeUnknown`. Still work to do, eg. for having undoable change events...

**Comment by jrieken** [comment]
Turns out this was done on purpose via https://github.com/microsoft/vscode/issues/94073, https://github.com/microsoft/vscode/commit/8f82b87b9597488aa18fc254a8b19bb600768a2f. I will go ahead and undo those changes. Extensions that do want to save output should have all the necessary events and API by now (e.g listen to output change, emit dirty/change event)

**Comment by jrieken** [comment]
closed via https://github.com/microsoft/vscode/commit/99fa777e532122214757c7d80862603322e00655
