### ISSUE TITLE
Adopting the new JS Debugger is confusing

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#96410]
Testing #96296

I am aware of `debug.javascript.usePreview`.

But then there are:

- `debug.extensionHost.useV3`
- `debug.node.useV3`
- `debug.chrome.useV3`

And there's also renaming `node` to `pwa-node`.

This is all very confusing, what is the difference between all these 3 different ways of using the new JS debugger?

**Comment by isidorn** [comment]
Yeah we should consolidete these and hopefully get rid of all of them starting in may when JS debugger will be the feault in insdiers.

**Comment by connor4312** [comment]
Yea.

 - The v3 options were added initially as we gradually improved js-debug. For instance js-debug couldn't debug extension hosts until mid-January, and had bad cases with Chrome/Node.
- `usePreview` is the nice new master switch used to flip on js-debug
- `js-debug` used to be called the "pwa debugger", so that's the prefix in the launch configs.

Once js-debug goes stable we will remove those options and drop the `pwa-` prefix. This isn't ideal right now but changing the settings or the prefix would break users.

**Comment by connor4312** [comment]
I'm planning to rework this js-debug readme (and add real documentation!) as part of endgame this week, I clarify at that point and close the issue then.

**Comment by connor4312** [comment]
I've updated and simplified the instructions on the js-debug readme which should hopefully make things simpler in the interim: https://github.com/microsoft/vscode-js-debug/blob/master/README.md
