### ISSUE TITLE
Multiple tabs opened when using "Reopen with..."

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96454]
Testing #96312

- Follow steps in the test issue to set up
- Open .github-issue file
- Reopen with cat scratch editor
- Pin the tab
- Open a different file
- Open the .github-issue file again
- Two tabs are opened and I can't close one of them.

![Apr-28-2020 11-28-18](https://user-images.githubusercontent.com/323878/80514491-3352c580-8946-11ea-86f4-aeecab6cdaea.gif)

**Comment by roblourens** [comment]
I also saw this while using notebooks

**Comment by rebornix** [comment]
Pushed a fix for https://github.com/microsoft/vscode/issues/96455 , which will re-/open the existing editor for the resource instead of creating a new one. For example in your case, when clicking the gihutb-issues file again, the cat editor will be revealed.

I'm wondering what's the right behavior for this as users then can't open the same resource with different editor types in the same group, but it seems Custom Editor has the same behavior.

**Comment by mjbvz** [comment]
I believe this has been fixed now. We had individual fixes on the custom editor and notebook side, which @lramos15 tried to unify

Please let me know if you are still seeing this in any cases
