### ISSUE TITLE
Difficult to pick a break point based on line and column only

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#96473]
Testing https://github.com/microsoft/vscode/issues/96305

For the duration of the profile the user can select some break points. However, it is difficult to make a choice based on the information given:

![image](https://user-images.githubusercontent.com/172399/80524068-52297a00-898f-11ea-875f-8dd454091db1.png)

One idea would be to show the contents of the line, but it would be more natural to do this on a break point directly in the context menu or as a special condition.

![image](https://user-images.githubusercontent.com/172399/80524426-df6cce80-898f-11ea-8484-f6727cafc4fb.png)

**Comment by connor4312** [comment]
I agree, it is kind of awkward. Showing the line contents is a good idea!

I'm not sure about how the experience would be placing it on the breakpoint directly. Would users choose the "stop" breakpoints before starting a profile, or would they enter a "picking mode" while starting a profile?

Something else I considered was hijacking conditional or logpoint breakpoints to let users start or stop profiles through some magic methods. I didn't do that since the discoverability for that functionality is very low, but that could be another way to accomplish this.

**Comment by connor4312** [comment]
Added in the linked commit--keeping the issue open for followup discussion

![](https://memes.peet.io/img/20-04-82f2b43d-5462-4ffe-9d89-46acee973710.png)

**Comment by JacksonKearl** [comment]
A "go to symbol in file"-like experience for this seems fitting. Where moving through the list moves through the editor as well and the quick pick could be filterable by line contents.
![image](https://user-images.githubusercontent.com/8586769/83698264-db972200-a5b5-11ea-809e-66d1838e38d2.png)


![image](https://user-images.githubusercontent.com/8586769/83698048-4f84fa80-a5b5-11ea-9e79-eadfea9ae08b.png)

**Comment by connor4312** [comment]
That's a good idea :)
