### ISSUE TITLE
Random Extension Recommendations

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#96475]
Testing #96233

I get a random assortment of recommended extensions in the recommended view. I have docker installed and a java file opened and no extensions installed. It is always the same workspace.

Sometimes, I get java, debugger for firefox, and elements for edge as recommendations. Other times I get Kubernetes recommended in place of Firefox. And lastly, sometimes I get Cloud Code and Kubernetes only.

**Comment by sandy081** [comment]
This is designed. We have a random algorithm for choosing among 

- exe based recommendations 
  - kubernetes and cloud code because of docker
  - edge because you might have Edge installed
  - Firefox because you might have Firefox installed

- dynamic workspace recommendations
- experimental recommendations
