### ISSUE TITLE
How to implement hot exit on a custom editor?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96484]
Testing #96315

I wanted to implement hot exit, but I am confused about how to restore the backup. VS Code called `backupCustomDocument` and told the extension where to store the backup. How can the extension know where the backup is after a reload? Is it expected to save the location to storage somewhere? It seems like VS Code mainly manages backups so I expected that it would call a method to restore from the backup at location X.

**Comment by mjbvz** [comment]
In [`openCustomDocument`](https://github.com/microsoft/vscode/blob/a00e2c94272213eb50fa80257dda101edcbbde2a/src/vs/vscode.proposed.d.ts#L1365), the context has a `backupId` property. This is only set when we are restoring the editor from a backup (such as on reload). 

However your extension is responsible for restoring itself. Usually this just means reading the editor's initial content from the backup location instead of from the workspace

Try using `backupId` and let me know if you find any bugs or have suggestions on how the documentation could be improved here

**Comment by roblourens** [comment]
I didn't notice that PawDraw uses that, but backupId is not set when I go through a hotExit flow

- Disable autosave
- Make an edit
- Reload the window
- backupId is undefined

Also, why is there an id instead of giving it the path? Are there cases where the backup will be saved in multiple documents and the suggested path will be ignored?

**Comment by mjbvz** [comment]
Yes, the id is entirely up to the extension. I just used the path as the id for convenience. Other extensions may maintain their own mapping between id and their backup resources

**Comment by roblourens** [comment]
Got it, but it does seem to be broken in my testing and hot exit doesn't work in PawDraw

**Comment by mjbvz** [comment]
Pushed fixed to VS Code and to the extension sample. Should be working now but let me know if you still see issues

**Comment by caponetto** [comment]
@mjbvz 
I've tested the latest updates but I'm still seeing some issues.
I'm able to reproduce them on both PawDraw and my custom editor.

Sometimes, when I reopen VSCode having unsaved changes, the editor is not properly loaded. 
Also, it seems that the editor is on an invalid state because I can't close the tab. I can't even close VSCode. I had to kill the process.
![backup-1](https://user-images.githubusercontent.com/638737/80704297-bbf27280-8aba-11ea-83e3-da259883abdf.gif)

I managed to properly reopen the editor once I close VSCode with a text editor on focus.
However, I still can't save or discard the changes.
I can only move forward if I do a new edit.
![backup-2](https://user-images.githubusercontent.com/638737/80704303-bd239f80-8aba-11ea-8acd-88160d1327ca.gif)

Hope this helps.

**Comment by mjbvz** [comment]
@caponetto Thanks for testing! Please try out the next VS Code insiders build with the extension sample from here: https://github.com/microsoft/vscode-extension-samples/tree/master/custom-editor-sample

There were bugs with both VS Code implementation and with the extension sample

**Comment by caponetto** [comment]
Thanks, @mjbvz! These issues I've reported above are gone.
