### ISSUE TITLE
Terminal: Difficult to click on "Relaunch terminal"

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#96497]
testing https://github.com/microsoft/vscode/issues/96300

When hovering over the info icon you get a popup with an action to relaunch the terminal. If you move your mouse towards the link (red arrow) the popup window goes away quickly so you can't click on the action.  you have to move up, then left (green arrow) to actually get to the link. 

![image](https://user-images.githubusercontent.com/1487073/80547997-83458280-896e-11ea-9a19-7d59e84c81dd.png)

**Comment by Tyriar** [comment]
Yeah it's a little tricky for a regular terminal layout, but that's because actions match the editor and are left aligned. I always thought this would look weird but it seems ok:

![image](https://user-images.githubusercontent.com/2193314/80603604-8039a900-89e5-11ea-842e-6e2f925da210.png)

I guess I'll go with that when the popup is squashed against the edge like this.
