### ISSUE TITLE
Authentication from VS Code to ADO pipelines. 

### ISSUE THREAD

**Issue by Raag007** [microsoft/vscode#96520]
I've written a PS script that can download artifacts for a given BuildID but the input parameters for this script is BuildID and ADO PAT. 

Sending PAT every time will become cumbersome and can expose credentials. 

Are there any other options/tools to download build artifacts? 

For reference: https://developercommunity.visualstudio.com/content/problem/1009486/authentication-from-vscode-to-azure-devops-pipelin.html?childToView=1010997#comment-1010997

**Comment by alexr00** [comment]
There might be an extension out there that can do this already. Maybe https://marketplace.visualstudio.com/items?itemName=ms-azure-devops.azure-pipelines ?
And if that extension doesn't have such a feature you could give them a feature request.

Otherwise, no VS Code doesn't have anything built in to do this.

**Comment by Raag007** [comment]
Looks like this extension is for "adds syntax highlighting and autocompletion for Azure Pipelines YAML to VS Code. It also helps you set up continuous build and deployment for Azure WebApps without leaving VS Code" 

Are there any best ways/tools/extensions to download build artifacts from ADO? Thanks!
