### ISSUE TITLE
Tabs: allow to control scrolling direction

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#96544]
This should impact both the scrolling direction ("natural", "reverse") as well as when switching tabs for mouse scroll is enabled.

**Comment by RossBrunton** [comment]
Why should this affect switching tabs via the scroll wheel? It's entirely reasonable for people to want the scroll direction for the tab bar to be different than the vertical scrolling. Why are we requiring that one setting control both?

**Comment by bpasero** [comment]
From https://github.com/microsoft/vscode/issues/96405

**Comment by Chrysaloid** [comment]
Replying to @joaomoreno in #96405 here because that issue is closed.

> Is `reverse` really important to have as a setting?

YES. IT IS!

> And if we reverse it, shouldn't the scrolling be reverse too?

No.

> Those two should be identical right?

No. They absolutely shouldn't. They should be separate settings.

Why your solution to the problem was to throw IMPORTANT PART OF THE FEATURE to the trash?

And how it is even possible for the reverse to work differently than normal? Why didn't you just copy your code for normal and just swap those 2 important values/function calls that tell the VSC to go to the next tab or the previous one? WHY?

PLEASE! FOR THE LOVE OF GOD! Add the `reverse` back! For me reverse is more natural as I am right-handed and my mouse is pointing slightly to the right so scrolling up should  switch to the tab on the right.

Of course, right now, because of many possible users that have changed this setting, you should probably add another boolean setting (probably named `"workbench.editor.scrollToSwitchTabsDirectionNormal"`) that would defaultly be set to `true` so those users won't notice anything.

As for now, for other power users like me who might find this issue before you fix it, here's AHK script that remaps `WheelUp` to `WheelDown` and vice-versa when the mouse is in the tab bar and VSC is the active window.

```ahk
#NoEnv
#SingleInstance Force
CoordMode, Mouse, Relative
SendMode Input
SetTitleMatchMode, 2

#IfWinActive ahk_exe Code.exe
$WheelUp::
MouseGetPos,,yaxis
if (84 <= yaxis and yaxis <= 164) {
   Send, {WheelDown}
} else {
   Send, {WheelUp}
}
Return

$WheelDown::
MouseGetPos,,yaxis
if (84 <= yaxis and yaxis <= 164) {
   Send, {WheelUp}
} else {
   Send, {WheelDown}
}
Return
#IfWinActive

!Insert::ExitApp
```
