### ISSUE TITLE
VSCode should support msys git on windows

### ISSUE THREAD

**Issue by Morilli** [microsoft/vscode#96553]
Note: Probably related to #87102.
I actually haven't noticed for a while, until I realized vscode doesn't work well with msys's git (not the git for windows install). From my little research this appears to be because ``git init`` outputs a different format depending on how git was compiled.

msys git:
``Reinitialized existing Git repository in /g/Dokumente/GitHub/vscode/.git/``

Git for Windows:
``Reinitialized existing Git repository in G:/Dokumente/GitHub/vscode/.git/``

Other features, like merge conflict diffing, seem to work, so I believe this output difference is what makes vscode not working with msys git. Could support for this format be added? I would appreciate being able to work with msys git instead of using the git for windows install.

I found [this statement](https://github.com/microsoft/vscode/issues/87102#issuecomment-575033917), so if this is the final stand, I'd appreciate a reason for why this is the only supported git version.

**Comment by joaomoreno** [comment]
> I found this statement, so if this is the final stand, I'd appreciate a reason for why this is the only supported git version.

There's plenty of reasons why Git for Windows is the only supported version:

- It's the official Git distribution on Windows from git-scm.com
- It's what pretty much every user has installed
- It can be installed side by side to other git versions
- Supporting more versions is dev effort which can be applied to other areas of Code

**Comment by Morilli** [comment]
Thanks for elaborating. I do see your point, although I'd argue the development effort to support it would likely not be great, as in the end it is still a fully functional windows git version.

I just personally don't like to duplicate files or programs, and installing git for windows means installing lots of mingw files too, that are already present on my system if I'm already using a mingw / msys2 setup.

**Comment by eine** [comment]
For completeness, Git for Windows 'Comes with MSYS2 runtime'. Hence, supporting the standard MSYS2 environment does not involve supporting more versions. Just a different location.

Moreover, I find it doubtfult that Git for Windows is 'what pretty much every user has installed'. I see MSYS2 to be much widely used than Git for Windows, precisely because developers prefer the upstream product instead of a limited rebranding. I found several users that changed from Git for Windows to MSYS2 or WSL, but not a single one that did the other way. I'd be glad if such decisions were backend by data. There are ~40 issues about MSYS2 and +500 reactions.
