### ISSUE TITLE
Terminal warning icon

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#96581]
Issue Type: <b>Bug</b>

With the changes we made to feed git credentials to the terminal, I now see in all terminals the info icon.  The visual presentation of the hover as it is right now seems problematic:

![image](https://user-images.githubusercontent.com/4674940/80606497-4074c080-89e9-11ea-9a86-a52ca72e0c89.png)

- font size is too large
- file paths are usually long
- it doesn't scale: The picture above is for three env variables (out of the box). As soon as another extension like python adopts it this number goes up after I opened my first python file.

I think we should show a short information in the hover, with a `Show details` link that opens an editor with the explanation.

VS Code version: Code - Insiders 1.45.0-insider (4bd206856db30c27d38aa0f1fbe74bac6156edc7, 2020-04-29T05:31:36.229Z)
OS version: Darwin x64 18.7.0

**Comment by Tyriar** [comment]
Was going to try a more concise scrollable presentation like this:

```
VSCODE_GIT_IPC_HANDLE=/tmp/vscode-git-ipc-blah...
FOO=${env:FOO}BAR
BAR=FOO${env:BAR}
```

I've also changed it in https://github.com/microsoft/vscode/issues/96574 to not show the info by default, just the warning since git uses the API (ie. every terminal will show it). Will close in favor of https://github.com/microsoft/vscode/issues/96250
