### ISSUE TITLE
Debug viewlet shows misleading information

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#96590]
* debug until here https://github.com/microsoft/vscode-github-issue-notebooks/blob/1cf3f313b515525c3bde62300a28e1b4a224f945/src/notebookProvider.ts#L153
* e.g run a query against an non-existing repo
* :bug: the error object appears as string but is actually an Error

<img width="1079" alt="Screenshot 2020-04-29 at 16 49 31" src="https://user-images.githubusercontent.com/1794099/80610251-69bd3d00-8a39-11ea-9a89-847c8a3caef1.png">

**Comment by connor4312** [comment]
This is actually what the chrome console does as well, however now I've allowed viewing its properties as well, which should make your scenario easier. I didn't want to hide the stack to make it look just like a regular object, since logging and glacing at the stack is a common use case and I did not want to add another click there.

![](https://memes.peet.io/img/20-05-da83e236-690d-4a14-b07f-fd9d91506572.png)
