### ISSUE TITLE
gui: Output | Problems | Debug | Terminal

### ISSUE THREAD

**Issue by gertcuykens** [Microsoft/vscode#9659]
- VSCode Version: 1.3.1
- OSX Version: 10.11.6

Currently there are 5 consoles
![image](https://cloud.githubusercontent.com/assets/863731/17081087/f468ee18-5149-11e6-8b08-2828a0fa8922.png)

Where command pallet gets a special place on top.
![image](https://cloud.githubusercontent.com/assets/863731/17081083/b55269b6-5149-11e6-816b-a8aa836098e6.png)

My personnel opinion it is that it can be organised into tabs. Currently if you want to switch between all 5 you will go insane without using hotkeys and because I have the memory capabilities comparable of a chicken I suggest to group them together in a tab like manner. Take for example edge, firefox, chrome, safari that organize all their consoles into tabs

![image](https://cloud.githubusercontent.com/assets/863731/17081089/1e44e1f6-514a-11e6-9236-e3b53e8d65ec.png)

~~If this get approved consider also to include the command pallet in there so you have a consistent look and feel.~~ Basically the following tabs that looks like this.

Output | Problems | Debug | Terminal ~~| Command Pallet~~ 

I think it will be more intuitive especially for beginners

EDIT: tab notification suggestions
- Output: buffer changed
- Debug: breakpoint hit
- Terminal: command finished / buffer changed
- Problems: new errors

**Comment by leaxoy** [comment]
+1

**Comment by kieferrm** [comment]
For me personally the Command Pallet is a different, but I also think there should be an easier way to switch between the different output consoles. A tabbed UI would also make the consoles better discoverable.

**Comment by rmunn** [comment]
I'm also opposed to merging the Command Palette into other output windows; it should stay where it is, on top. But for the other four, a tab-switching interface would indeed be nice.

**Comment by stevencl** [comment]
We had considered something like this when we started work on the horizontal panel (see #1129).

As well as showing tabs to switch between the panels, we considered ways that we could show panels side by side. It seemed to us at the time that would be a natural expectation of a tabbed UI. But it sounds like from this thread that the request is simply to provide an easier way to switch between panels. Is that the case?

If we were to do this, how likely do you think you would want to view two or more panels side by side?

At the time we decided not to do the tabbed UI because:
1. We were worried about the extra overhead required of managing panels in a tabbed UI and the negative impact this could have on the lightweight, non-IDE feel of VS Code
2. We weren't sure at the time if there were valid scenarios for wanting to view panels side by side.

But like I said, we didn't consider an option where we didn't support viewing panels side by side.

**Comment by gertcuykens** [comment]
Personally side by side (split console) I don't think is useful, just better gui visualisation and one hotkey to toggle between them.

What about introducing 4 extra small icons on the bottom each opening there own console and get highlighted when there representing console is active or start blinking when the content of there console changes, right now you only can open the problem console by clicking on it. (see screenshot)

![image](https://cloud.githubusercontent.com/assets/863731/17158551/57216b62-5397-11e6-831e-def3bcd0b4fa.png)

I think this introduces the most easy and lightweight solution until maybe somebody has a better idea?

**Comment by stevencl** [comment]
We thought about that too when we originally designed the horizontal panel but we want to keep the status bar as a place for ambient information, such as the number of errors and warnings in your project. We don't want it to become a place for commands that simply open panels and other UI as that dilutes the usefulness of the status bar.

**Comment by gertcuykens** [comment]
Technically the new symbols also represent the status of every console like for example the exit status of the terminal last command or the running / pausing state of the debug console or unread output messages.

If we leave the Pallet for what it is, then we are talking about just 3 extra status icons.

**Comment by stevencl** [comment]
@bgashler1 will work on some designs for this. Will discuss the following week.

**Comment by Tyriar** [comment]
Comment so I get participating notifications 😃

**Comment by jrieken** [comment]
I'd like to use this as a chance to draw attention to https://github.com/Microsoft/vscode/issues/1875#issuecomment-175694616. Basically I'd like to see two things

* give the bottom panel full width such that it has real advantage over the editor area
* when the bottom panel shows (and only then **!**) show switcher buttons in the activity bar that allow to toggle between the panes

**Comment by bgashler1** [comment]
**UX Sync Summary, August 3:**
Below is the design we were most interested in pursuing.  It uses a different tab style to avoid users confusing it with editor tabs, which are not interchangeable.  

We need to iterate on two more things: 1) How will we show notifications?  2) What is the maximum bounded width of the local command/inputs on the right for each panel so that it won't obscure the tabs or appear strange (biggest offender "Problems" input box)?

![3](https://cloud.githubusercontent.com/assets/11839736/17377634/64d1e100-596f-11e6-9198-44567fcec885.png)

**Comment by bgashler1** [comment]
Just for the sake of recording history, we also considered the below design, but we decided against it for now because icons could get overloaded.  Also, it's noteworthy that F12 tools moved away from this pattern.
![4](https://cloud.githubusercontent.com/assets/11839736/17378102/8711ab36-5971-11e6-8c05-6e345b1c5fe0.png)

**Comment by gertcuykens** [comment]
1) +1 for Blinking fade in and out effect on the tab name for notifications
2) Rename `debug console` to `debug` the former is too long for a tab name. In case of very small window switch to current design layout without tabs.

**Comment by Tyriar** [comment]
@bgashler1 some questions:

- How much more space does the header take up at 100% zoom level (how much margin is there below the blue line)
- Are the panel labels visible permanently even when the panel is minimized?
- What are these notifications?

**Comment by gertcuykens** [comment]
My list of notification sugestions
- Output: buffer changed
- Debug: breakpoint hit
- Terminal: command finished
- Problems: new errors

**Comment by Tyriar** [comment]
@gertcuykens that would get a little annoying though wouldn't it? It's rare for me to care about other panels other than the active one.

**Comment by gertcuykens** [comment]
Ok, I agree drop the notifications for now we can always at does latter if we find more useful once :)

**Comment by rmunn** [comment]
If notifications are added, I'm STRONGLY :-1: on blinking. But a simple round blue dot, or else a blue badge-with-number-inside (like the "1" visible on the Git icon in the sample UI screenshot) would be fine. That won't be trying to grab my attention away from my code, but I'll know that there's something new available to see in that tab when I get around to it.

If notifications on the output tabs look like the notifications on the Git icon or the Extensions icon, then I'd be :+1: for output notifications. It *would* be useful, I just don't want it blinking, moving, or animating in any way.

**Comment by stevencl** [comment]
The idea is that notifications would be exactly like those on the explorer, git and extensions icon. They would not blink, move or animate :-).

Obviously notifications aren't a must have for this (since we have the panel today without notifications) but we wanted to make sure that any design decision we took now would work well for any future changes such as adding notification badges. In addition, we think this design would work better if we were to add many more panels. We have no idea if we will add more panels, we just wanted to ensure it would work well if we did.

The panel labels would not be permanently visible so when the panel is closed, the labels would not appear anywhere. The labels would only be shown when the panel is shown.

@jrieken - thanks for the reminder about your earlier suggestion about a full width horizontal panel. We can revisit this design too. As I mentioned, when we ran studies on this design previously it wasn't the preferred option. But as you predicted, we now have panels that don't have a strong relationship to the main content in the editor (the integrated terminal for example) which might motivate another look at this design.

**Comment by dragonwolf83** [comment]
Notifications would be very useful on the tabs, more so than on a status bar. One of the things that breaks my flow in Visual Studio IDE is lack of notifications when I have a different tab in focus. I usually resolve it by splitting the tabs so Errors and Output are side-by-side but I hate losing the real estate for it. Notifications would make it easier to remember to switch to the other Panels for useful information.

The notifications listed by gertcuykens would be great

**Comment by SailorMax** [comment]
Can you also think about minimize mode for this panel? When user will see only panel title bar (with new tabs) at bottom of main window? It can be useful when user want to hide it temporary.
You can leave old "v" button for this function or make on double-click on panel title bar.

**Comment by Scoodood** [comment]
Since I am using wide screen monitor so I personally like the OUTPUT panel to be positioned horizontally side-by-side. But I know some of you like the way it is now (veritcally). 

In Sublime Text 3, the tab layout can be repositioned so I use this [plugin](https://github.com/rctay/sublime-text-2-buildview) to render the build output into the tab view, and now I can drag the tab to any position/orientation to suit my need. Please see the sample output here. I believe VScode can accomplish something similar.

![screen shot 2016-10-21 at 2 23 05 pm](https://cloud.githubusercontent.com/assets/15989924/19612220/34ce4fa2-979a-11e6-98cb-dde7082944de.png)
![screen shot 2016-10-21 at 2 23 51 pm](https://cloud.githubusercontent.com/assets/15989924/19612223/3841aa1c-979a-11e6-965d-1fc19705cb32.png)

**Comment by pflannery** [comment]
Is there a reason why we cant just have a CONSOLE panel for both OUTPUT and DEBUG?
It drives me nuts when precompile tasks switch focus to the OUTPUT panel and then I have to manually go back to the DEBUG panel to view the output when debugging.

Like @bgashler1 design, though be nice to replace the all the drop downs with a side explorer list of choices to switch between.

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/22109923/18b9cef2-de5a-11e6-80fa-84c132ab75fe.png)
