### ISSUE TITLE
SCM viewlet gives strange errors when precommit hooks fail

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#96606]
![image](https://user-images.githubusercontent.com/8586769/80618219-e7f8ef80-89f7-11ea-8092-f4c908e1b17b.png)

```
> git commit --quiet --allow-empty-message --file -
Found '/Users/jkearl/Developer/vscode/.nvmrc' with version <10>
Now using node v10.18.1 (npm v6.14.4)

> husky - npm run -s precommit
> husky - node v10.18.1

Reading git index versions...
File not formatted. Run the 'Format Document' command to fix it: src/vs/workbench/contrib/searchEditor/browser/searchEditor.contribution.ts


Hygiene failed with 1 errors. Check 'build/gulpfile.hygiene.js'.

> husky - pre-commit hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run precommit'
> git config --get-all user.name
> git config --get-all user.email
```

**Comment by joaomoreno** [comment]
As you can see, the entire output of git when that fails is:

```
Found '/Users/jkearl/Developer/vscode/.nvmrc' with version <10>
Now using node v10.18.1 (npm v6.14.4)

> husky - npm run -s precommit
> husky - node v10.18.1

Reading git index versions...
File not formatted. Run the 'Format Document' command to fix it: src/vs/workbench/contrib/searchEditor/browser/searchEditor.contribution.ts


Hygiene failed with 1 errors. Check 'build/gulpfile.hygiene.js'.

> husky - pre-commit hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run precommit'
```

It's **very** hard to figure out what exact error message we should show. So we show the first line.

The only thing we can do here is to show something like `Git: Failed to commit`. But we currently print the error because there are some situation in which the first line of the error is actually quite descriptive and the user doesn't have to go into the Git Log.

**Comment by JacksonKearl** [comment]
Oh I see. I’m used to it just saying ‘husky...’, which is more helpful. Something just have changed in my environment to make it now also log about nvm. Including the first line seems reasonable.
