### ISSUE TITLE
Clarify when additional scopes are needed by login

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#96609]
Testing https://github.com/microsoft/vscode/issues/96280

[See full video](https://share.getcloudapp.com/wbu09pXk) for detailed steps. I have signed out of all git accounts locally and also within Insiders w/ only the GH PR extension installed. On my browser I am already signed into GitHub.

1. Clone from https url using explorer and select location
2. Authorize VS Code to access GitHub
3. Open cloned repo on VS Code
4. :bug: Immediately asked to sign in (again) to GitHub

This is confusing because I just authorize VS Code to access GitHub and it's asking me to sign in again. If I click "sign in" I go through the exact same authorization steps and feels extremely repetitive. Even opening the account doprdown in the bottom left shows that I am signed in, so I'm guessing the two items (Git and GitHub PR extension) are not talking to each other.

**Comment by joaomoreno** [comment]
>This is confusing because I just authorize VS Code to access GitHub and it's asking me to sign in again.

Actually you authorized the Git extension to access GitHub.

These are two different features coming from two different extensions:

- Automatic GitHub authentication for Clone, Pull, Push comes from the core Git extension. This is the first auth request.
- Managing issues and PRs comes from the GHPR extension. This is the notification message coming up once you reload.

Your first authentication is for the Git extension. The second one is for GHPR. Having two prompts is security by design.

**Comment by misolori** [comment]
I believe this is related to the login auth provider and the various scopes that are requested by each extension. We run into this issue with the GitHub Issues Notebook after being logged in.

I think one idea was to make the messaging clearer about what scopes are needed/missing so the user understands what is happening. I would guess that when you sign into GitHub, most users assume that you are granting VS Code to have full access to your account, but that's not the case here. So we need to make that clearer.
