### ISSUE TITLE
Multiple designs for the "pill" that is being shown in the input field

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#96608]
I have noticed two different "designs" for the pills that are being shown in input fields.

Settings sync preferences
![image](https://user-images.githubusercontent.com/3372902/80619129-88750100-8a44-11ea-883c-9b0634aedea8.png)

Settings
![image](https://user-images.githubusercontent.com/3372902/80619195-a5113900-8a44-11ea-8d97-f574a25b8853.png)

Version: 1.45.0-insider
Commit: 4bd206856db30c27d38aa0f1fbe74bac6156edc7
Date: 2020-04-29T05:31:36.229Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:
1. Click on "Manage" in the lower left hand corner, and choose "Online Services Settings"
2. Use the palette to open "Preferences Sync: Configure..."

Does this issue occur when all extensions are disabled?: Yes

**Comment by misolori** [comment]
We also have these other ones:

**Keyboard Shortcuts**
![image](https://user-images.githubusercontent.com/35271042/80754873-a4c87a80-8ae4-11ea-9c0b-87d871e6a246.png)

**Debug**
![image](https://user-images.githubusercontent.com/35271042/80754956-d17c9200-8ae4-11ea-84f6-cddc57107c7e.png)


I think they're all modeled after our labels in the sidebar:
![image](https://user-images.githubusercontent.com/35271042/80754902-b6aa1d80-8ae4-11ea-90e1-7e3f27b85748.png)

I agree that we should consolidate all of these so they are consistent.

**Comment by misolori** [comment]
This really comes down to two styles, the "pill" vs the "badge":

![image](https://user-images.githubusercontent.com/35271042/81252251-55011c00-8fda-11ea-936f-2f90de6582cd.png)

We could also explore doing a combo where we say all number counts use the "pill" and all others use the "badge" but I wonder if that would create inconsistencies. Created https://github.com/microsoft/vscode/pull/97104 where we go wit the pill all around since we've been using that style already in the extension viewlet and activity bar.
