### ISSUE TITLE
Preference Sync quick pick description

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#96611]
Re #96226

<img width="602" alt="image" src="https://user-images.githubusercontent.com/876920/80621672-78d1ca00-89fc-11ea-9c8a-142e0166a5b0.png">

IMHO we can use description to show secondary information `Github: rebornix` instead of putting them inside `()`. Also if we use description label, we can align the text with the Account Gear context menu

<img width="210" alt="image" src="https://user-images.githubusercontent.com/876920/80621793-aae32c00-89fc-11ea-8f2e-77cf0e9c9c1a.png">

Right now in the context menu it's `rebornix (GitHub)` while in the quick pick it's `GitHub: rebornix`.

**Comment by sandy081** [comment]
We also have this picker

<img width="642" alt="image" src="https://user-images.githubusercontent.com/10746682/80638604-ff1ff780-8a60-11ea-910b-717cb33d5a7d.png">

And I like the `user (account)` format. I would put `rebornix (Github)` as description in `Preferences Sync` quick pick so that all of them are in sync.

**Comment by sandy081** [comment]
<img width="627" alt="image" src="https://user-images.githubusercontent.com/10746682/80639998-1d86f280-8a63-11ea-84e8-a1aa01c11f3c.png">
