### ISSUE TITLE
Copying a directory with a busted symlink results is partial directory copy

### ISSUE THREAD

**Issue by kingces95** [microsoft/vscode#96648]
- VSCode Version: 
> Version: 1.45.0-insider
Commit: a250df703de955a38aed427a917bce8278ab3331
Date: 2020-04-24T20:46:59.782Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

- OS Version:
![image](https://user-images.githubusercontent.com/4120386/80271377-6867cb00-865b-11ea-8c69-979f015e37a9.png)

Steps to Reproduce:
1. Create `foo/test.js`
2. Create`bar/`
3. Create a symbolic link in `bar` to `foo/test.js` named `test.js`
4. Create `baz/test.js`
5. Move `bar/` into `baz/` to break the symlink `baz/foo/test.js`
6. Copy & Paste `bar/`

Expect a copy of all content of `bar` including `bar/test.js` and the busted symlink. Actually get a new directory `bar copy` but it does not contain a copy of `bar/test.js` so it was only a partial copy.

I'd also expect the symlink to be updated such that if it were valid it would continue to point at the same file location (should that location fall outside of the folder being moved) ala #96303.

![image](https://user-images.githubusercontent.com/4120386/80650920-9ad54780-8a10-11ea-94cb-89feac0a355a.png)

[symlink.zip](https://github.com/microsoft/vscode/files/4554859/symlink.zip)

Does this issue occur when all extensions are disabled? Yes

**Comment by bpasero** [comment]
This has been fixed now via https://github.com/microsoft/vscode/issues/111621

**Comment by isidorn** [comment]
Lovely, let's move to february so we get it verified.
@kingces95 you can also try it out with vscode insiders from Friday to let us if it works fine for you now.

**Comment by roblourens** [comment]
Seems like I still repro the same thing?

![image](https://user-images.githubusercontent.com/323878/109094373-b19b0800-76ce-11eb-8e72-d8f473feffc5.png)

I moved bar into baz, then copied it and pasted it in the root, and it's empty. What's the intent?

**Comment by bpasero** [comment]
I was probably misunderstanding the steps and they are also slightly confusing:

> Expect a copy of all content of bar including bar/test.js and the busted symlink. Actually get a new directory bar copy but it does not contain a copy of bar/test.js so it was only a partial copy.

I think the OP meant to say: "Copy the folder `baz`" because that one contains both the dangling symbolic link and the file `test.js` itself. My fix was to not stumble over a dangling symbolic link when copying. As outlined in https://github.com/microsoft/vscode/issues/111621 which has easier steps to repro. 

I will mark this as a duplicate of https://github.com/microsoft/vscode/issues/111621 to go forward with verification and suggest to verify https://github.com/microsoft/vscode/issues/111621.

Btw we do not automatically "fix" or "rewrite" symbolic links when you move a folder or file. Native OS also does not do so because in the end all are doing a low level `mv` operation that executes fast and does not treat symbolic links any special.

However, I will see if we could copy the symbolic link even if it is dangling. Currently not doing that.
