### ISSUE TITLE
Dragging to activity bar and switching theme causes bad rendering

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#96653]
Version: 1.45.0-insider
Commit: 4bd206856db30c27d38aa0f1fbe74bac6156edc7
Date: 2020-04-29T05:31:36.229Z
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

---

- Nord theme
- Drag something from panel to activity bar
- Switch to file explorer
- Switch to light+ theme

![image](https://user-images.githubusercontent.com/4033249/80658645-88bcce80-8a3b-11ea-9fe8-3c0a0ff9d081.png)

**Comment by sbatten** [comment]
only happening in welcome view of explorer AFAICT

**Comment by isidorn** [comment]
fyi @joaomoreno for welcome views

**Comment by joaomoreno** [comment]
Welcome views do not mess with background.

**Comment by sbatten** [comment]
Turns out this isn't specific to dragging views around. The empty explorer view sets the sidebar background explicitly on drag and drop events here: https://github.com/microsoft/vscode/blob/48248fac233e18ead863c8784a5fee4acfe674d5/src/vs/workbench/contrib/files/browser/views/emptyView.ts#L56-L80

It doesn't validate that the dragged object is relevant either but that isn't the culprit. Nothing is hooked up to remove the explicit theme coloring from this dnd handler. Changing the lines that set the background to `SIDEBAR_BACKGROUND` to just set to empty string fixes the issue, but I am not sure if there is another reason for the explicit set... @isidorn ?

**Comment by isidorn** [comment]
@sbatten thanks for looking into this. I do not remember why we set the background color explicitly.
Feel free to remove it in Insiders to fix this issue and if it casues some breakage we can investigate.

**Comment by isidorn** [comment]
Thanks for fixing this.
Adding to May milestone so we get this verified.

**Comment by Tyriar** [comment]
@sbatten a better fix imo would be to use a class and add/clear it out such that theme colors all live in the theme participant registration.
