### ISSUE TITLE
Open in containing folder should select file/folder

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9671]
- VSCode Version: Code - Insiders 1.4.0-insider (01a3f868552dc8011adf4e79bee8cfb09babfe31, 2016-07-22T05:13:17.693Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04

Steps to Reproduce:

1. Open a folder that contains a folder
2. Say `foo` is the open folder which contains `bar`, right clicking `bar` in the explorer and selecting open containing folder will open `foo` not `bar`.

It does not open the currently opened vscode folder but the parent of the selected folder.

**Comment by kieferrm** [comment]
@Tyriar and I discussed that a bit more. The current behavior is in principle the same on all platforms. The chosen name on Linux is less appealing than on Windows or Mac but since there is no standard explorer or finder it's hard to come up with a different name. 

The real problem on Linux is that the file/folder when being shown within its container folder is not selected as it is on Windows and Mac.

**Comment by bpasero** [comment]
@Tyriar nothing we control, please file against Electron and link to here.

**Comment by Tyriar** [comment]
Found to TODO https://github.com/electron/electron/blob/107d759ea265a6f8733bd7adfd21b2aebbebb6ad/atom/common/platform_util_linux.cc#L59
