### ISSUE TITLE
Don't show "turn sync on" button when sync disabled in CLI

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#96727]
When disabling sync as in https://github.com/microsoft/vscode/issues/95532, the big blue button in the settings editor is still visible, but it doesn't do anything when clicked. It should not appear at all.

**Comment by developerhb** [comment]
Hello @roblourens 
I am new here.

I would like to work on this issue. For that I would like have some more information about this issue. Like, how I can reproduce this issue on my local so that I can understand which code is creating this issue and where & what changes I should do.

**Comment by roblourens** [comment]
Cool! You can read about settings sync here: https://code.visualstudio.com/docs/editor/settings-sync and see some more steps for this issue here: https://github.com/microsoft/vscode/issues/95532

**Comment by developerhb** [comment]
@roblourens I referred the links provided by you. I understand what is `Settings Sync`. 
But the problem is when I build and run the `vscode repo`, I am not able to see the button we are dealing with in this issue. Also, I cannot see the `Turn on Preferences Sync` option in the setting menu.

So, basically I am not able to reproduce this issue on my local.

Also, to have preview of the issue, I downloaded `vscode-insiders`. I started it normally, without enabling or disabling the sync from the CLI. I found, the Big Blue Button with text `Turn on Preferences Sync` does absolutely nothing. But I can turn on sync from settings menu using `Turn on Preferences Sync` option.

Please guide me.

**Comment by roblourens** [comment]
I think this probably isn't a good first issue to work on. You might want to look at issues that are tagged "good first issue"
