### ISSUE TITLE
Better behavior of the View Bar

### ISSUE THREAD

**Issue by jaime-olivares** [Microsoft/vscode#9676]
- VSCode Version: 1.3
- OS Version: any

In the view bar, the icons are ~~not~~ poorly highlighted whenever a view is selected (i.e. Git or Debug). ~~You are assuming that a user may associate the view title with the icon, which is not the case for new users, and even some experienced/distracted.~~ The high-contrast themes show an orange border which is clearly visible, but not other themes.

Besides that, whenever a icon is pressed twice, the view panel disappears. This is related to the first case: if the user is not sure about what view is selected, he/she will end pressing an icon twice and the panel will disappear, while it was expected just to switch views. In this case it would be clearer to have a dedicated collapse/expand button.

**Comment by kieferrm** [comment]
@jaime-olivares This is what I see in version 1.3 (windows, mac, linux): The icons switch from grey to white.  Please reopen if I misread your issue.

![ukg2piazkj](https://cloud.githubusercontent.com/assets/4674940/17118968/11b834fe-5278-11e6-8709-b073ce8bd61a.gif)

**Comment by jaime-olivares** [comment]
Hi, @kieferrm. You are right, the first part of my comment is true, it changes the icon color, although the difference is really not adequate for people with some vision difficulty. I still suggest a more visible highlight.
On the other hand, the second part of my suggest is still totally valid: clicking an icon twice has a non-intuitive effect: close the current view panel. An expand/collapse button is a more standard mechanism. There is a lot of room for that.

**Comment by jaime-olivares** [comment]
@kieferrm, I have modified my initial statement. Please reopen, as I cannot.

**Comment by stevencl** [comment]
Thanks for the feedback @jaime-olivares .

On the issue about closing the current viewlet when clicking the icon twice we don't want to add any visible affordance for this as we are following a design principle of solving for distractions, not discoverability.

If we prioritise discoverability issues over distractions, we would run the risk of ending up with a UI that is overloaded with many visible affordances which serve to help a new user get used to the tool but which then just get in the way of a more experienced user. Since we aim to create a lightweight yet powerful tool, it's really important to us that every pixel we draw on the screen has value for long term usage. So in this case we decided that while the behaviour of toggling the viewlet on and off might be unexpected initially, we believe that this is something that people get used to quickly and thus any visible affordance we add for this would simply become a distraction. 

Your feedback on highlight colours is well taken. We will be spending some time in the near future reviewing the overall look and feel of colours, icons etc throughout and will take this into consideration then.

Given this, I am going to close this issue.
