### ISSUE TITLE
Extension development: postMessage from inside an iframe in a webview crashes the webview

### ISSUE THREAD

**Issue by daniel-vetter** [microsoft/vscode#96844]
Issue Type: <b>Bug</b>

<b>Steps to Reproduce:</b>
1. clone this repository: https://github.com/daniel-vetter/vscode-bug
2. run npm install 
2. open the cloned folder in vscode
3. press ctrl + shift + b to run the typescript build
4. press F5 to start a vscode instance with the test extension running
5. press the "click me" button

<b>Observed behavior:</b>
 - latest vscode (not insider) version:
    - The tab turns grey
    - In the developer tools of the vscode instance (ctrl + shift + i) this message appears: "embedded page crashed"
- insider version:
   - In the webview developer tools this message appears: "Uncaught TypeError: Error processing argument at index 0, conversion failure from undefined"

<b>Expected behavior:</b>
The message should be posted to the iframe host (the html code in the extension.ts) so it can be handled by a "onmessage" event handler.

<b>Versions:</b>
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

Extensions: none

**Comment by M-Widman-Mesh** [comment]
hello @daniel-vetter,

I saw in your iframecontent.html, you are calling 

" <button id="button" onclick="window.top.postMessage('Text Message', '*')">Click me</button>".

I'm using communication in my extension too, however I'm adding an event listener in my html content within my "webview.html", and from my iframecontent.html Im calling window.parent.postMessage instead of window.top.postMessage. I wonder if this would help you out!

so to fix this I would do a couple things.

(1) add an event listener to your extension.ts within your webview.html, to handle your postMessage from your iframe
(2) modify your iframecontent.html to window.parent.postMessage

Let me know if this helps you out! Conceptually I'm using the webview.html as a middle man between my extension and my iframe:) If your thinking about doing bi-directional communication!

**Comment by daniel-vetter** [comment]
Hi @M-Widman-Mesh 

thanks for the advice. window.parent works fine for me. After researching the difference, i think window.parent also makes way more sense in my case. I still think the webview should not crash or give a more descriptive error message if window.top is used.

**Comment by mjbvz** [comment]
Thanks @M-Widman-Mesh

I think their advice is correct. The only way to post a message back to vs code from a webview is [using `vscode.postMessage`](https://code.visualstudio.com/api/extension-guides/webview#passing-messages-from-a-webview-to-an-extension) from the top level webview itself. An iframe inside the webview should post back to the top level webview which can forward the message to VS Code

I'm closing this as won't fix. The crash is certainly not ideal but it also isn't a use case we support
