### ISSUE TITLE
Run build task formats my file

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#96904]
I hit this so many times in https://github.com/joaomoreno/gifcap/, where I have to run the build every time I edit a file.

Set:

- editor.formatOnSave: true
- files.autoSave: afterDelay

Then:

1. Create a workspace with the following two files: https://gist.github.com/joaomoreno/08467605afada8d68f26dc3f8f94da12
2. Open `file.js` and outdent the first line
3. Immediately after, start the build task with <kbd>Ctrl Shift B</kbd>

🐛  The line in `file.js` gets outdented due to auto formatting. I didn't expect auto formatting to run, since I never explicitly saved the file.

**Comment by joaomoreno** [comment]
So fast! 🐇

**Comment by stefanhaller** [comment]
@joaomoreno, I'd like to understand better why you were requesting this change. Can you describe in more detail why it's a problem if files are auto-formatted when running a build task?

In particular, I'm wondering if your problem would also be solved by setting `task.saveBeforeRun` to "never" instead.

The reason I'm asking is that I personally do want files to be formatted when building (and when debugging), and I also think it's the right thing to do, conceptually (see https://github.com/microsoft/vscode/issues/104296). As far as I know, this issue is the only vote against this so far.
