### ISSUE TITLE
WorkspaceEdit without opening the file

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#96920]
Issue Type: <b>Feature Request</b>

When you execute `workspace.applyEdit` it opens modified files in editor (in background). I would like to have an option to avoid that.

**Comment by bpasero** [comment]
@usernamehw that should only happen if the files remain dirty, not if they get saved quickly enough (though we have some delay). Code sample?

**Comment by usernamehw** [comment]
```ts
// filePath is an absolute path to the file outside of the workspace
const uri = vscode.Uri.file(filePath); 
const wEdit = new vscode.WorkspaceEdit();
wEdit.insert(uri, new vscode.Position(0, 0), 'text');
workspace.applyEdit(wEdit);
```
It actually stays dirty if `"files.autoSave": "off"`. Maybe I shouldn't be using workspaceEdit at all and only use node fs.

**Comment by bpasero** [comment]
@usernamehw VSCode opens files that are being changed automatically because a dirty file without associated editor is dangerous, e.g. you can easily loose unsaved data if you are not seeing the file opened somewhere.

However I noticed that we still open files even if `"files.autoSave": "afterDelay"`. I think that is something we can relax because we know for a fact that the file is being saved automatically.

Nevertheless I think what you want is maybe a way to signal to the workspace edit that the edit should be saved right away, would that help? If the save is triggered fast enough (we have a timeout of 50ms before we open the editor) it would not result in this experience.

**Comment by usernamehw** [comment]
> Nevertheless I think what you want is maybe a way to signal to the workspace edit that the edit should be saved right away

Yes. I haven't tried `document.save()` before. Running it after applying edit does not open the file.
