### ISSUE TITLE
More Sorting Options For Key Bindings

### ISSUE THREAD

**Issue by jhomme** [microsoft/vscode#96994]
Sort key bindings by:

* Assigned
* Unassigned
* Active
* context
* Extension
* Core

**Comment by sandy081** [comment]
What do you mean by Active & Context?

**Comment by jhomme** [comment]
Hi,

I am a new user, so I may not know the right terms. I mean when various things are in effect. For instance, some key bindings only work in an editor, some only work in an extension, and so forth.

 

Thanks.

 

Jim

 

==========

Jim Homme

Skype: jim.homme

FreeChess: jhomme

Twitter: jimhomme

Facebook: jimhomme

**Comment by isidorn** [comment]
This feature request makes sense from the accessibility perspective, so our screen reader users can more easily navigate through the keybindings. Thus assigning to Backlog (not sure if we will look into it, but we will keep it open for now).

By default the keybindings are sorted: first the assigned ones alphabatecially and then the unasigned ones. 
It would be hard to show the active ones, since when you are looking at this list you are always in the keybindings view and thus only the keybindings for that view would be active.

The rest I think makes sense. How would this feature work:
User clicks on the first row in the table and the sorting order changes.
We would need to make the first row focusable, so users can also change the sort order via keyboard.

**Comment by RDHaynie** [comment]
I agree with this suggestion.
