### ISSUE TITLE
does vscode have anything to do w/ FilterFindFirst and FilterFindClose

### ISSUE THREAD

**Issue by kirbygit** [microsoft/vscode#97037]
![80170125-16ac3b80-859c-11ea-9b2f-38d74aa503af](https://user-images.githubusercontent.com/20747057/81120383-74684e00-8ee1-11ea-8cae-40630820b84f.png)

Steps to Reproduce:

1. Tried to run a .exe file using Wine
2. I opened the terminal I saw these:
![Screenshot from 2020-05-05 14-58-46](https://user-images.githubusercontent.com/20747057/81120362-6a464f80-8ee1-11ea-80d3-f18cef07c650.png)

**Comment by Tyriar** [comment]
Looks like a Chromium log?

**Comment by kirbygit** [comment]
I have completely removed chromium

**Comment by mahmou7d** [comment]
مرسل من هاتف Samsung Galaxy الذكي.
-------- الرسالة الأصلية --------من: Daniel Imms <notifications@github.com> التاريخ: ٨‏/٥‏/٢٠٢٠  ٤:١٠ م  (GMT+02:00) إلى: microsoft/vscode <vscode@noreply.github.com> نسخة: Subscribed <subscribed@noreply.github.com> الموضوع: Re: [microsoft/vscode] does vscode have anything to do w/
  FilterFindFirst and FilterFindClose (#97037) 
Looks like a Chromium log?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/microsoft/vscode/issues/97037#issuecomment-625806960",
"url": "https://github.com/microsoft/vscode/issues/97037#issuecomment-625806960",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by deepak1556** [comment]
What @Tyriar meant was this comes from the chromium runtime VSCode is written on, removing chromium from the system will not help.

I am not sure what codepath in chromium triggers this but does this impact the behaviour of VSCode in anyway ?

Also curious, why are you using VSCode via wine ?

**Comment by kirbygit** [comment]
@deepak1556 nope I was using an software editor because I can no longer create another virtual machine and thus why I decided to use wine instead and directly run .exe into it. There is no impact at all on VSCode but on the terminal it keeps giving me this messages

**Comment by deepak1556** [comment]
Thanks for the context, the logs mostly indicate calls to stub methods we can ignore it for now. I am closing this issue as no further action can be made on VSCode end.

I haven't used wine in a long time but isn't it possible to share folders, that way you can run VSCode on the linux host and develop for the wine environment ?

**Comment by kirbygit** [comment]
I see what you mean thank you
