### ISSUE TITLE
Folder explorer Fold level control like editor 

### ISSUE THREAD

**Issue by sungle3737** [microsoft/vscode#97117]
![fold example](https://user-images.githubusercontent.com/27716524/81258623-0e123580-9071-11ea-8b49-166a202202a6.gif)

## In Editor - feature exist
I can fold code by `ctrl` + `shift` + `] or [`

and  `shift` + `click`, `alt` + `click`

Especially `shift` + `click` is really great that change all shown fold level like upper gif

## In Folder Explorer - My request
- `alt` + `click` - working but fold everything - not remembering previous state
- `shift` + `click` - doesn't work - like in editor, control of folding level will be great feature

**Comment by joaomoreno** [comment]
From what I can understand, `shift click` in the editor does the following:

- (1) recursively collapses all descendants, if the current node is expanded;
- (2) recursively expands the node and all descendants, if the current node is collapsed, just like `alt click`.

We can't use `shift click` in the tree, since that expands the selection.

But we can have `alt click` do (1) before it actually collapses the node itself. So `alt click` would:

- (1) recursively collapses all descendants, if the current node is expanded and some descendants are expanded (new behavior);
- (1) collapses the node, if the current node is expanded and all descendants are collapsed;
- (2) recursively expands the node and all descendants, if the current node is collapsed.

**Comment by sungle3737** [comment]
In my experiment

## Editor
- `shift + click` - according to my question's gif, `shift + click` unfold tree level one by one, not all descendants
- `alt + click` - Also, alt click remember last folding level, and toggle between (All Folded/Remembered Folding Level)

## Explorer
- `shift + click` (click selected folder) - do nothing 
- `alt + click` - expand recursively all descendants (i think it should remember previous state like in editor)


## Explorer what i suggest
- `shift + click`  (click selected folder) - like editor, unfold tree level one by one, because In my opinion logic could be diverged click same/!same folder.
- `alt + click` - remember folding level!

**Comment by sungle3737** [comment]
alt click was my misconception!
another feature request - `alt + click` - unfold all codes in editor
