### ISSUE TITLE
Timeline: use more horizontal space

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#97127]
Could we perhaps stretch out the content on the rows where no time label is present, and only crop them if the user hovers over? Feels like there's a lot of wasted space here.

Also, what if we could connect the icons?

![image](https://user-images.githubusercontent.com/22350/81272874-61bf5780-904e-11ea-882d-1f6ce608afa3.png)

**Comment by eamodio** [comment]
@joaomoreno I can look into using the horizontal space better -- although I feel like this is a bigger feature, where the tree can tell the node its width when rendering -- because depending on the width a view might want to change the content (especially between the label and the description).

As for connecting the icons, it has been suggested, but not sure its a good idea as the Git entries are only 1 of many types that could be intermixed in the timeline.

**Comment by joaomoreno** [comment]
> @joaomoreno I can look into using the horizontal space better -- although I feel like this is a bigger feature, where the tree can tell the node its width when rendering -- because depending on the width a view might want to change the content (especially between the label and the description).

As the view owner, you know the exact (height, width) layout box so you can propagate the width all the way down to your renderer, right?

**Comment by eamodio** [comment]
@joaomoreno yes and no. The Timeline view is similar to custom views, in that it is populated via a provider model. So we'd need a way to communicate that width to the providers when filling out that data, or the model would need to have some sort of short vs long values that can be chosen based on the width "break point".
