### ISSUE TITLE
  "editor.mouseWheelZoom": true - should be on by default

### ISSUE THREAD

**Issue by DerekSMorin** [microsoft/vscode#97137]
https://stackoverflow.com/questions/30192884/is-it-possible-to-configure-control-scroll-wheel-to-increase-decrease-zoom-in

This has 218 upvotes at stack overflow.

![image](https://user-images.githubusercontent.com/7568856/81282556-5148b600-9029-11ea-8af7-9bc34b9f6271.png)

**Comment by DerekSMorin** [comment]
I'm not sure on the downvote, the original screen cap showed a snarky comment, so that might have been it.  But 218 upvotes on this question, seems to me like false is an odd default.  Ctrl + scrollwheel works in browsers, visual studio, even microsoft teams.  Seems odd to have it off by default.

**Comment by alexdima** [comment]
This request is sensitive and makes sense. But we have a technical problem that forces that has forced us to ship with the setting off by default:

When we initially added this feature, the setting was on by default. But then we received numerous complaints that people were changing the font size of the editor by accident. It turns out that all of those complaints came from folks using a laptop with a trackpad, and perhaps doing some copy-pasting (which involves ctrl/cmd) and touching the trackpad with their hands a bit, inadvertently scrolling.

The technical limitation is that we cannot differentiate `mousewheel` events coming in from the trackpad from events coming in from a physical mouse wheel. So we cannot fix that problem, so we have to leave this setting behind a flag to which people opt in (and most likely they opt in if they use a mouse with a physical wheel)...
