### ISSUE TITLE
Pinned Release Notes tab is blank (looks weird)

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#97218]
Issue Type: <b>Bug</b>

1. Open Release Notes from Help menu
2. Pin it
3. Because Release Notes doesn't show an icon on its normal tab, the pinned one is empty.

VS Code version: Code - Insiders 1.46.0-insider (d487078dc7fc1c276657cadb61b4f63833a8df55, 2020-05-07T16:19:54.327Z)
OS version: Windows_NT x64 10.0.18363

![image](https://user-images.githubusercontent.com/6726799/81379861-c38cc980-9101-11ea-8d9d-5a1364f7e617.png)

Compare its appearance to that of my adjacent pinned tab, which is my settings.json file (very handy to be able to pin it, kudos to @bpasero 🎉 )

**Comment by bpasero** [comment]
This actually looks like a bug to me, because release notes should have the product icon. Looking into devtools I see it being referenced:

![image](https://user-images.githubusercontent.com/900690/81386633-a530c900-9115-11ea-999e-46cebd435744.png)

However, this file does not exist on disk likely because it gets inlined, as you can see in the welcome tab where the icon appears properly:

![image](https://user-images.githubusercontent.com/900690/81386667-b4b01200-9115-11ea-95d0-3cb4c0d4a6f6.png)

Assigning a couple of people to check this.

**Comment by bpasero** [comment]
I should add that I indeed moved this icon to a new place (we had many copies of it). So it could be a regression from that work.

**Comment by bpasero** [comment]
@mjbvz so this is a regression from my push but I think the way the icon is used in here is not ideal because it prevents the image from being inlined:

https://github.com/microsoft/vscode/blob/161d93bb787df7c95f5a24f6ef83e28c93967bfa/src/vs/workbench/contrib/update/browser/releaseNotesEditor.ts#L91

A better solution would be to have it referenced from CSS like we do e.g. in the welcome page:

https://github.com/microsoft/vscode/blob/161d93bb787df7c95f5a24f6ef83e28c93967bfa/src/vs/workbench/contrib/welcome/page/browser/welcomePage.css#L223

However this would require some name to appear as part of the label we could override. I am not sure how to pass a resource name to the webview? Currently it looks like we add a UUID:

![image](https://user-images.githubusercontent.com/900690/81403461-bd174580-9133-11ea-831a-882e387a3edc.png)

Open for ideas. Last resort is to just bring back that icon, but then we have it duplicate as before.

**Comment by misolori** [comment]
This actually has nothing to do with pinned tabs as it appears blank normally:

![image](https://user-images.githubusercontent.com/35271042/81430200-e88a3800-9113-11ea-9ae4-d9f7a0d2117c.png)
