### ISSUE TITLE
Cannot set the value of a watch expression

### ISSUE THREAD

**Issue by wesrupert** [Microsoft/vscode#9722]
- VS Code version: 1.3.1

There is no way for the user to assign a value to an item in the watch window.
### Steps to Reproduce:
1. Hit a breakpoint in a C# project with a local variable `i`
2. Add the watch expression `i`
3. Double click or right click on the value
### Expected Result:
- The user enters the edit **value** box
- In the case of right click, the "Set Value" command **appears** in the context menu
### Actual Result:
- The user enters the edit **expression** box
- In the case of right click, the "Set Value" command **does not appear** in the context menu

In order to make it so that the user does not try to assign values to expressions such as `i + j`, the evaluate response should be able to contain some sort of "isEditable" property.

**Comment by isidorn** [comment]
This conceptually only makes sense if the watch expression added belongs to some container object. Otherwise if you just add a local variable `i` it will be evaluted, and the watch expression does not hold a reference to that object, it is just an evaluation of that object. In order to support this debug protocol would need to be enchanced.

Assigning this to august to start supporting setting primitive variables that belong to some object container.

@weinand can provide more details if needed

**Comment by weinand** [comment]
The debug protocol addition for this feature is https://github.com/Microsoft/vscode-debugadapter-node/issues/85.
We have no plans to implement this in the near future.

**Comment by weinand** [comment]
Closing because no plans to implement this within 12 months.
