### ISSUE TITLE
vim python jupyter notebook

### ISSUE THREAD

**Issue by andyliumathematics** [microsoft/vscode#97253]
Issue Type: <b>Feature Request</b>

I think vscode's supporting jupyter not better than pycharm pro        in jupyter  I cannot use vim  and i want to use it in next release.

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.17134

**Comment by sickerin** [comment]
I'm presuming you're having the same Feature Request / Issue as I am right? I'm not able to use emacs keybindings on Jupyter for vscode. The owner of the emacs repo said that it was because Jupyter uses WebView, and that the plugin needs to . I'm interested in working on this, but I'm not sure whether this is something I need to look at in vscode, vscode-python, or the jupyter project.
https://github.com/tuttieee/vscode-emacs-mcx/issues/145

**Comment by rebornix** [comment]
Currently the Jupyter Notebook support is contributed by the Python extension, which is using a webview under the hood right now. Once we support native notebook in VS Code core (#91987) and the Python extension adopts the API, Vim will just work.

**Comment by andyliumathematics** [comment]
Thank you for writing me back!
vscode-python can open  .ipynb files, but vim on vscode  doesn't work. And then I use .py files and split the code blocks with "# %%", the vim works  and it's splited code blocks like the .ipnb files.
At last I solved the problem by using .py file and use "# %%", but .ipynb file cannot work with vim.


Best wishes for you!
| |
AndyLiu
|
|
andyliumathematics@163.com
|
签名由网易邮箱大师定制
On 6/1/2020 02:39，sickerin<notifications@github.com> wrote：

I'm presuming you're having the same Feature Request / Issue as I am right? I'm not able to use emacs keybindings on Jupyter for vscode. The owner of the emacs repo said that it was because Jupyter uses WebView, and that the plugin needs to . I'm interested in working on this, but I'm not sure whether this is something I need to look at in vscode, vscode-python, or the jupyter project.
tuttieee/vscode-emacs-mcx#145
