### ISSUE TITLE
can't get intellisense from other js file

### ISSUE THREAD

**Issue by JoeWeed** [Microsoft/vscode#9728]
- VSCode Version:1.3.1
- OS Version:macOS 10.11.6

<img width="1117" alt="screen shot 2016-07-26 at 11 44 03" src="https://cloud.githubusercontent.com/assets/10793922/17125472/4bca2568-5326-11e6-965b-ef81f93309af.png">

**Comment by kieferrm** [comment]
@JoeWeed You are running in file scope mode. Pls see [our doc](https://code.visualstudio.com/docs/languages/javascript#_javascript-projects-jsconfigjson).  In order to switch to explicit project mode you need a jsconfig file. Also described in the doc. 

Here is how that works:
![vxg1w0hp6g](https://cloud.githubusercontent.com/assets/4674940/17157084/05f71a98-5342-11e6-86fb-c421103ec07f.gif)
