### ISSUE TITLE
碰到了两个bug

### ISSUE THREAD

**Issue by xinshani** [microsoft/vscode#97334]
Issue Type: <b>Bug</b>

1、cmd+f 打开搜索框，在搜索框中写入搜索内容，在切换tab 工作窗口后，当年的搜索索引不是一个数字，而是一个问号
2、折叠代码后，在选中代码，不会高亮

VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T15:57:33.467Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|8.00GB (0.28GB free)|
|Process Argv|-psn_0_6043075|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.3.11
vscode-eslint|dba|2.1.5
githistory|don|0.6.5
smarty|imp|0.3.0
svelte-vscode|Jam|0.9.3
docthis|joe|0.7.1
git-graph|mhu|1.22.0
formate|Mik|1.1.5
vscode-docker|ms-|1.1.0
vscode-language-pack-zh-hans|MS-|1.45.1
vetur|oct|0.24.0
indent-rainbow|ode|7.4.0
material-icon-theme|PKi|4.1.0
vue-vscode-snippets|sdr|1.9.0
highlight-matching-tag|vin|0.9.9

(1 theme extensions excluded)

</details>

**Comment by wbing520** [comment]
I only duplicated the first issue, So that just translate the first one from Chinese to English as followings:
Issue Type: Bug
1、cmd+f 打开搜索框，在搜索框中写入搜索内容，在切换tab 工作窗口后，当年的搜索索引不是一个数字，而是一个问号

1.  Click cmd + f ---> open search window ---> enter search content --> in the search tab window, it would show #OrderNum of #TotalNum beside the search textbox --->Click "Tab", change to another tab window, beside the search textbox, it would show that ? of #TotalNum, instead of   #OrderNum of #TotalNum as followings. 
![image](https://user-images.githubusercontent.com/1477269/81477514-20fa4680-91e6-11ea-8423-cdb77fa22f9c.png)

Correct one:
![image](https://user-images.githubusercontent.com/1477269/81477544-425b3280-91e6-11ea-8ec0-b393ddc6b965.png)

**Comment by alexdima** [comment]
This is as designed. The `?` is rendered when the selection is not precisely on a find match. When pressing next or prev, the selection is moved to a find match and will read again `1 of 3`, `2 of 3`, etc.

**Comment by alexdima** [comment]
Actually, this might be a regression. Let's track in #97681
