### ISSUE TITLE
Textarea is incorrectly positioned when doing selection + IME

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9736]
- VSCode Version: Code - Insiders 1.3.0-insider (a2b9738a942237b59cb920940b93a0206f1b61d0, 2016-07-01T19:30:41.087Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Turn on the Windows Korean IME
2. Select 2 Korean characters

  ![image](https://cloud.githubusercontent.com/assets/2193314/17129386/a80ac7a6-52c7-11e6-8671-a05d75753499.png)
3. Press 'd' to type 'ㅇ', notice it appears twice, it doesn't override the selection.

  ![image](https://cloud.githubusercontent.com/assets/2193314/17129405/c855d226-52c7-11e6-9772-8e5cef697fd9.png)

**Comment by alexandrudima** [comment]
@Tyriar That is actually the hidden textarea being revealed at the cursor position, not at the cursor selection start. Here I highlight it in your screenshot:

![image](https://cloud.githubusercontent.com/assets/5047891/17933732/7b5d5592-6a15-11e6-9cae-db14b987f091.png)

Once you end the composition (e.g. via a <space>) the textarea disappears.

**Comment by alexandrudima** [comment]
Here are alternative steps that make the problem clear:
* select more than 1 line
* in Japanese, type `sennsei`
* observe how the textarea is painted at the cursor position (when IME started) instead of at the selection start.

![ime-position](https://cloud.githubusercontent.com/assets/5047891/17933847/f01c7bec-6a15-11e6-8073-08df786930d8.gif)
