### ISSUE TITLE
No semantic highlighting in HoverProvider code blocks

### ISSUE THREAD

**Issue by Bynsu** [microsoft/vscode#97409]
- VSCode Version: 1.46.0-insider
- OS Version: Windows 10.0.17763 x64

Steps to Reproduce:

1. Write an extension that uses HoverProvider
2. In provideHover, use MarkdownString.appendCodeblock to append code block in any language with semantic tokens support 
3. When hovering, code block semantic tokens will remain with default colors instead of being highlit appropriately.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
I think this is highly unlikely to ever be done, because semantic highlighting typically requires a project / a lot of metadata. For example, a snippet of C++ cannot just be "semantically colored" without a lot of metadata around it, to get the semantic highlighting correct it is very important to have the entire context of the snippet, etc. The same applies for almost any other language I can think of, like Java, TypeScript, etc.

**Comment by Bynsu** [comment]
@alexdima indeed, when it comes to existing languages, code blocks really need context for semantic highlighting, and tmlanguage highlighting is good enough as it is, but as a custom language extension developer I would really like to have a possibility to colorize my code blocks programmatically, to avoid using tmlanguage highlighting at all. The request is not about implementing a semantic highlighting to exiting languages code snippets, but about adding an optional function to DocumentSemanticTokensProvider that allows extension developer to tokenize the raw text input, so that VSCode could use it for highlighting misc code blocks.
