### ISSUE TITLE
Status bar: Home and end should move focus to start and end of status bar entries

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#97512]
Found by @jvesouza 

F6 to focus status bar
Home and end should move focus to first and last item respectivly

**Comment by jvesouza** [comment]
@isidorn There is a problem when I am editing .java files, probably caused by some extension associated with the java language.
If I press f6 to go to the status bar, press the end key and try to navigate through the items using the left arrow, I get stuck in the twit feedback item.
This only seems to happen if the java extensions are in use.
Please let me know if you need more details.

**Comment by isidorn** [comment]
@jvesouza what jave extension are you using?
Is it enough to have that extension installed and just open a java file? If yes, just let me know the extension and I will try to reproduce. Thanks!

**Comment by jvesouza** [comment]
@isidorn  I believe it is enough to install the extensions vscjava.vscode-java-pack and shengchen.vscode-checkstyle.
After installing these extensions just open a .java file, navigate to the status bar using the f6 key, press the home key and use the left arrow.
It seems to me that the problem is being caused by the extension shengchen.vscode-checkstyle because when I disabled it the problem disappeared.
Thanks.

**Comment by isidorn** [comment]
I tried reproducing and could not.
The issue might be that I do not have java setup on my machine. I would recommend that you file an issue against their extension so they investigate more. And ask if they contribute a status bar item or if they are eating up the keyboard shortcuts.
