### ISSUE TITLE
Investigate deep learning issue classification models

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#97537]
ref #97533 

Look into how much better "deep" models for issue classification would perform. Likely will use models from https://simpletransformers.ai/docs/classification-specifics/

**Comment by hamelsmu** [comment]
How is Issue Classification related to VSCode?  Just curious?

**Comment by julien-c** [comment]
Yeah I won't piggy-back on @JacksonKearl's thread too much but personally, I saw it mentioned in the [release docs for latest vscode](https://code.visualstudio.com/updates/v1_45#_automated-issue-classification) a few days ago:)

**Comment by jlewi** [comment]
@JacksonKearl and @julien-c I'd be curious to learn what ends up working well for you in terms of models.

We have been doing label prediction for [Kubeflow](https://github.com/kubeflow/code-intelligence). I recently switched to a Google AutoML model. So far that seems to have reduced our pass through rate significantly. Its unclear how much of that was actually due to the model itself since I also made some changes to the features (e.g. included the repo).

AutoML is nice for rapid prototyping but since we don't have direct access to the model we can't reuse it for other purposes. For example, I think issue embeddings would be very useful for 1) dedupping issues and 2) clustering to identify common threads.

**Comment by JacksonKearl** [comment]
@hamelsmu yes we are trying to find ways to automatically assign issues to their feature area owners. 

@jlewi 
> I think issue embeddings would be very useful for 1) dedupping issues and 2) clustering to identify common threads.

Yes ideally we'd be able to better identify duplicate issues too, but that's further down the line

**Comment by JacksonKearl** [comment]
Findings:

Using a deep model with the upcoming "minimum accuracy" configuration format (whereby each label has a threshold associated with it, tuned such that the precision per-label is some constant value) results in about 10% higher overall recall and several categories going from 0% recall to non-0, as compared to tested non-deep models.

The overall monthly cost (model storage, VM disks, compute, etc.) is quite reasonable (predicted <<$10/mo on Azure). This is excluding bandwidth, mentioned below.

The GPU-trained models can be run in a CPU-only host (GitHub Actions) with reasonable performance, given the relatively low throughput needed for running against the live issue stream. 


The GPU models are substantially larger than classical ones, which will result in higher bandwidth charges and more load on the Actions. This can be mitigated by running less frequently if needed (current is 30mins, could go to 1-2hr without significant loss in utility).

**Comment by julien-c** [comment]
Really cool! Will you release the model/weights itself?

**Comment by JacksonKearl** [comment]
@julien-c Probably not - it is customer-derived data and may need to be handled sensitively. I've reached out to legal for clarification though.
