### ISSUE TITLE
cant install ms python 

### ISSUE THREAD

**Issue by puneethrj** [microsoft/vscode#97548]
I have tried to install mspython both manually and by using the extension manager in vscode. Both didn't work. And when trying to download the extension, the download never completes and gets stuck at a point. I suspect it some server-side issue. Please look into it

![image](https://user-images.githubusercontent.com/13819936/81609595-ca635700-93f5-11ea-8360-57b2a602785b.png)

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Enable log level to trace
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by puneethrj** [comment]
Seems like this was an issue for 1 day. It started working today and I could also update the extension to the latest version. If I encounter a similar issue again I will make it a point to share the above-mentioned information. 
Thank you
