### ISSUE TITLE
Breakpoints disappear when a file is modified outside current workspace

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#9755]
Testing #9533
- VSCode Version: Latest insiders
- OS Version: OSX

Steps to Reproduce:
1.  Enable a breakpoint on a file and start debug session
2.  Make sure this break point is hit during debugging
3. Modify the file outside - I used a different VS Code (stable) to edit
4. Notice that file gets updates in current workspace - Good

Observed:
- Existing break point disappeared
- Continuing debugging, break point is hit even though it is not appearing

Expected
- Existing break point should be unverified

**Comment by isidorn** [comment]
July to investigate

**Comment by weinand** [comment]
@isidorn I believe this is the problem I showed you yesterday: an unverified breakpoint is not shown if it sits on the "current" (yellow) line.

**Comment by isidorn** [comment]
The issue here can be simplified by the following steps:
* add a brekapoint to a file
* modify that file outside of vscode, notice the breakpoint is no longer shown (you have to add another breakpoint, or go to another file and come back for it to be shown)

The bottomline issue is that the editor deletes decorations when a file is modified on the outside. 

I could fix this by listening on file change events but I would prefer if I check with @alexandrudima once he is back for the underlying problem. Also this is not critical, thus pushing to August.

Git decorations remain preserved becuase the git world always listens on file change events and recomputes those decorations.

**Comment by alexandrudima** [comment]
If the buffer is not dirty, and the file changes outside vscode, then AFAIK we effectively "close and reopen" the file -- all decorations get lost.

**Comment by weinand** [comment]
Closing because we are not planning to implement this within the next 12 months.

**Comment by alexandrudima** [comment]
@weinand I think this might have been implemented as a side effect of #29655

**Comment by isidorn** [comment]
This works fine now. I just chekced in latest insiders.
Thanks for pointing this out @alexandrudima

**Comment by weinand** [comment]
Great, sometimes closing an issue works wonders...
