### ISSUE TITLE
Ability to set context keys per item in the call stack view

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#97633]
For profiling, there may be call stack items in different states. For example, a user might be profiling a webworker, but not their main process, or they might want to profile the two independently. And some targets can't be profiled. Essentially the functionality I'm looking for is "when sessionId in [some list]". We do get [some context information](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/debug/browser/callStackView.ts#L51-L62), but there's "contains" operator or ability to store a regex into a context key at the moment.

Alex D suggested that the best approach for this would be to expose an API in the debug namespace that would let us set context keys per child item. Perhaps something like this:

```ts
enum CallStackItemType {
  Session,
  Thread,
  CallFrame,
}

export function setCallStackContext(itemType: CallStackItemType, itemId: string): void;
```

Thoughts @isidorn ?

**Comment by isidorn** [comment]
@connor4312 having an API like that will probably solve the issue, but let's first look if that is really necessery.
So your Extensoin knows what is the `[some list]`. 
Your extension can also call
* `vscode.commands.executeCommand('setContext', 'Session1_belongs_in_list', true);`
* You can also use the OR to say contribute the command only when one of you context keys is true
* We can also introduce new context on the debug side.

Does a combination of all that maybe give you a solution?

Sorry for being a bit vague since I am not 100% what you are trying to achieve.
Also please note this feature request https://github.com/microsoft/vscode/issues/97544

**Comment by connor4312** [comment]
> Sorry for being a bit vague since I am not 100% what you are trying to achieve

Take the following scenario (tree of sessions):

```
My Cool Server
 |- server.js (profiling)
     |- foo-worker.js (profiling)
     |- bar-worker.js
```

In the inline call stack view, we want to contribute the `Take Performance Profile` command to the bar-worker.js since it's not profiling, but `Stop Performance Profiling` to server.js and foo-worker.js. Today we could do this if we had a _single_ session be setting a context key and then having `"when": "sessionId == jsDebugProfilingSessionId"` or something similar. But the correct way would be a list-like approach. 

> `vscode.commands.executeCommand('setContext', 'Session1_belongs_in_list', true);`

As far as I've know I can't have anything like `"when": "${sessionId}_belongs_in_list"` -- is there another approach you were thinking about?

**Comment by isidorn** [comment]
Thanks for claryfing. My dummy approach is that you set for example 5 context keys for each of the 5 sessions that belongs in the list.
And then you use the `or` between all the contexts you contributed.
Not sure if this other part can be dynamic or you do it staticaly?

**Comment by connor4312** [comment]
Ah, okay. So you're saying to statically have `sessionId == jsDebugProfilingSessionId1 or sessionId == jsDebugProfilingSessionId2 or ...`. That would work, it means we have a max number of sessions, though I don't imagine people will debug more than a couple sessions at once. It'd work for the moment.

**Comment by isidorn** [comment]
Yeah, that was my hacky workaround. Let me know how it goes. Thanks

**Comment by connor4312** [comment]
Thanks! I ran into an issue where it looks like the context keys are not actually set for inline items, e.g. there's no `sessionId`. I tried to get this working by setting context keys for the menu before calling `createAndFillInActionBarActions` in 04b1321c0257f674479900b1d710fde72f87cb9c. This kind of works but causes the Menu to detect changes to its context key items, fire an event, and enter a render loop.  I wasn't sure what the best approach to take was here.

**Comment by isidorn** [comment]
Good catch. So the issue is that we set the context keys only once context menu is triggered. And for inline items there is no such thing as a context menu. I missed this.
What we need is to set context keys on hover. Which I think we do not support anywhere in the workbench.
@connor4312 I checked your commit and you set the context keys when the action bar gets created which is too early. It is immeaditly created, just invisible until we hover over it.

@joaomoreno for SCM view you do not set context keys based on hover correct? Do you think it makes sense to expose a `onDidHover` event on `list` which would fire when an element is being hovered over. If we had that event we could set the context keys based on our hovered element and thus make our inline actions respect the context.

**Comment by joaomoreno** [comment]
> @joaomoreno for SCM view you do not set context keys based on hover correct? Do you think it makes sense to expose a onDidHover event on list which would fire when an element is being hovered over. If we had that event we could set the context keys based on our hovered element and thus make our inline actions respect the context.

Tree/list users own the DOM inside the rows. So it's up to you to implement that if needed.

**Comment by isidorn** [comment]
@joaomoreno yeah I should do it on my elements, thanks. We can do it with a small timeout, and only once hovered element changes. So I think it will not be a performace problem in the end. I can measure.

@connor4312 bottom line, I need to fix that the context key is set per hovered item, not per context menu. I have created this issue to track this https://github.com/microsoft/vscode/issues/98570
I will try to look into it this week.

**Comment by isidorn** [comment]
If we were to add some API to allow extensions to set `contextKeys` on CALL STACK items I think it would make sense to only allow extensions to introduce new `contextKeys` but not to control existing ones.

fyi @weinand

**Comment by connor4312** [comment]
We now have the `in` operator for context keys so can solve this completely without extra work in vscode.
