### ISSUE TITLE
[tab completion] multi cursor behaviour different to emmet

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#9764]
Testing #9698:

- enable tab completion: `"editor.tabCompletion": true`
- create a html snippet
```json
	 "Div": {
		"prefix": "div",
		"body": [
			"<div>",
			"    ${}",
			"</div>"
		],
		"description": "New div"
	}
```
- in a html file have a multiple lines with content 'div'. Set multiple cursors after each div. Press tab.
👉  primary div is expanded
- do the same with multiple lines of span, press tab
👉  tab character is added at each of the cursors

Not sure if the emmet behaviour is intentional.
It would be cool if the expansion happens on every cursor.

**Comment by jrieken** [comment]
I like

**Comment by jrieken** [comment]
@aeschli It seems we only support (and that already today) snippets and multi cursor when [no placeholders](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/common/snippet.ts#L766) are defined. I see how that makes sense, but the 'final selection'-placeholder should always be supported. Still, moving to August since became more work than I though

**Comment by jrieken** [comment]
Reopening as a 'fix' for #11742

**Comment by Gheoan** [comment]
`vscode`'s behavior is still different to `emmet`.

`emmet`:
- in a html file have a multiple lines with content 'div'. Set multiple cursors after each div. Press tab.
=> all divs are expanded

`vscode`:
- `"editor.tabCompletion": false`
- no html snipped with `div` prefix
- in a html file have a multiple lines with content 'div'. Set multiple cursors after each div. Press tab.
=> tab character is added at each of the cursors

**Comment by ramya-rao-a** [comment]
@Gheoan The emmet related behavior is tracked in#9571
