### ISSUE TITLE
"Hot exit" is meaningless to user, and user isn't prompted about it on first use.

### ISSUE THREAD

**Issue by Stokestack** [microsoft/vscode#97642]
- VSCode Version:
1.45.0
- OS Version:
Mac OS 10.15.4
Steps to Reproduce:

1. Have a file open and make some changes.
2. Close VS Code.

Does this issue occur when all extensions are disabled?: Yes/No
Probably.

Why is there no "problem description" or expected/actual behavior section in this bug template? 

Anyway, the problem is the one reported in issue 21228 (closed), but compounded by the use of the meaningless term "Hot exit" in the settings and the failure to prompt the user about it on first use (as a comment in that issue says it's supposed to). I searched the settings for this behavior using various terms and never found it. I found it only because of that bug report.

Read the text for this setting; I can't imagine a more obscure way to express what it does: "Hot Exit: Controls whether unsaved files are remembered between sessions, allowing the save prompt when exiting the editor to be skipped."

Which do you think is more likely: Someone searching for "Prompt to save files on exit" or someone searching for "Remember unsaved files between sessions?"

Please change the setting name and description to something resembling "save files on exit." I have lost work just now because of this behavior, as reported in the other issue. Thanks!

**Comment by Tyriar** [comment]
> Which do you think is more likely: Someone searching for "Prompt to save files on exit" or someone searching for "Remember unsaved files between sessions?"

Luckily the settings search will find both so it doesn't matter which is more likely:

![image](https://user-images.githubusercontent.com/2193314/81811473-86e21900-94d9-11ea-96f8-f3c3023f9588.png)

![image](https://user-images.githubusercontent.com/2193314/81811521-a0836080-94d9-11ea-8859-853b09a47d2a.png)

You can also search the internet and you'll probably hit the feature.

> Please change the setting name and description to something resembling "save files on exit."

We can't change the setting name as too many people rely upon it, and the description seems fine to me? The name hot exit is commonly used in other editors which is why we used it.

The first 4 results on Google for "vscode save files on exit" are directly related to the feature, including the official documentation page that describes the feature. If you don't like hot exit because it doesn't retain the undo stack, you can disable it or wait until https://github.com/microsoft/vscode/issues/15135 is fixed.

**Comment by Stokestack** [comment]
Thanks for the reply. I disagree, however. I've been programming professionally on Windows, Unix, and Mac with various tools and IDEs for 25 years (egads) and I don't recall ever encountering the term "hot exit." Also, when doing a settings search and looking through hits, a reasonable person is going to look at the name of each setting primarily. That's no help here. And then the description is as obtuse as possible. I don't see how people can be "relying on" this description. If we can't even improve a couple lines of descriptive text, this is a dead-end product.

**Comment by Tyriar** [comment]
The feature/name is modeled [after Sublime](https://www.sublimetext.com/blog/articles/sublime-text-2-build-2126) which also enables it by default and doesn't prompt people about the first use.

"save files on exit." isn't any better though, to "save" a file means it will no longer be dirty. That's not what's happening as we're remembering/backing up the file, which is another term where the setting is a number 1 match:

![image](https://user-images.githubusercontent.com/2193314/81879808-99436d80-9540-11ea-9783-800b6846870a.png)

**Comment by Stokestack** [comment]
If it prompts to save the file on exit, and you accede, it is no longer dirty. I don't see what the problem is there.

All the description has to say is, "Prompt to save files on exit, or remember changes between sessions without prompting or saving."
