### ISSUE TITLE
Ctrl+space completions stopped working with the latest Insiders

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#97650]
- VSCode Version: Version: 1.46.0-insider (user setup)
Commit: 288852d8c26d797974bfb8aed06e1bff9b809223
Date: 2020-05-12T05:43:31.363Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Reproed with TypeScript or C++. Doesn't repro with non-Insiders.
2. Use Ctrl+Space after any existing `.' operator. Doesn't repro if you type the '.'.

![image](https://user-images.githubusercontent.com/19859882/81753814-7a25dc80-9469-11ea-9f86-8527b61f5c5b.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by hpsaturn** [comment]
Same situation on Debian GNU-Linux with `PlatformIO` or C++ extensions.

Some times de code navigation and methods autocomplete go to turn off, is weird, works fine in a moment, in the next moment nothing works, all smart features turn off, like it don't understood any code language, I cant determinate the cause.

**Comment by jrieken** [comment]
/needsMoreInfo

Please update this issue after reading https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests. Thanks.

**Comment by sean-mcmanus** [comment]
I don't know what info is missing. Everyone on our team repros the issue.

**Comment by Colengc** [comment]
@jrieken This is an extremely easy to repro, and rather critical issue.  If you are saying that you are unable to repro with the simple steps provided, please let us know.  Otherwise, there would seem to be more than enough information here to notify you of this critical issue.

![image](https://user-images.githubusercontent.com/10354649/81849385-4ef3c980-950b-11ea-8552-380671d345fb.png)

**Comment by bobbrow** [comment]
Alternate steps:
1. Open a new VS Code window
2. Create a new file (Untitled-1 is fine)
3. Set the language to "TypeScript"
4. Type `console.log();`
    1. Note that after typing `.` you get completion suggestions for methods on `console`
5. Move the cursor to the postion right after the `.`
6. Press <kbd>CTL</kbd>+<kbd>Space</kbd>

**EXPECTED**: completion suggestions should appear
![image](https://user-images.githubusercontent.com/12818240/81850429-cd9d3680-950c-11ea-879a-1ac1e57a2f79.png)

**ACTUAL**: no suggestions appear
![image](https://user-images.githubusercontent.com/12818240/81850391-c37b3800-950c-11ea-9bdb-a0ca185c31e8.png)

**Comment by bobbrow** [comment]
Turning on `"typescript.tsserver.trace": "verbose"` and looking at the log shows that the suggestions are being sent, but not displayed for some reason.

**Comment by jrieken** [comment]
> Are you saying you can't repro it? It seems like a widespread issue

I am saying our whole team selfhosts on insiders, didn't report anything, and that gives me some confidence. And I am also saying that this is a badly written bug because the important information is well hidden. See, I look at 100+ bugs every day, if you want a fast fix, write crystal clear, razor-sharp bug.

**Comment by bobbrow** [comment]
Thanks for the fix!

**Comment by jrieken** [comment]
thanks for the good [steps](https://github.com/microsoft/vscode/issues/97650#issuecomment-628168042)
