### ISSUE TITLE
Cannot use message service before workbench is up

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#9769]
while testing https://github.com/Microsoft/vscode/issues/9690:
The 'take feedback survey' does not show up because it is posted too early.
Forcing another notification some time later, brings up both notifications.

**Comment by joaomoreno** [comment]
It all boils down to [this indirection](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/message/browser/messageService.ts#L35) which decouples the message list with the construction of the workbench. The `MessageList` can't know when the workbench is finally ready due to how we set up the whole infrastructure, so it [just drops messages](https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/messagelist/messageList.ts#L167).

Had to push 5418b6c37b7d5daab76c0cdcc9ac2cb435217e8b in order for it to work.

**Comment by bpasero** [comment]
Nice workaround skillz.
