### ISSUE TITLE
VS code freezes when typing and scrolling

### ISSUE THREAD

**Issue by subash7038** [microsoft/vscode#97731]
In the fast few days I am having very poor performance issues .Especialy when scrollling.It almost completely freezes.

**Comment by bemasher** [comment]
I think I may have the same issue. I was able to capture an instance of the lag in the developer tools profiler. After downgrading to 1.44.2, I have not been able to reproduce the issue.

![image](https://user-images.githubusercontent.com/79724/81844633-9cbd0180-950c-11ea-9c5a-4acfcc1b80f5.png)

[Profile-20200513T110910.json.gz](https://github.com/microsoft/vscode/files/4623614/Profile-20200513T110910.json.gz)

**Comment by alexdima** [comment]
I did not recognise the code, but I could see `$onDidChange`, which points to `MainThreadDecorationsShape` -- https://github.com/microsoft/vscode/blob/e1d8f5155c0db5ffdc130c9aa0f14efac02dfdfb/src/vs/workbench/api/common/extHost.protocol.ts#L205

**Comment by schwab** [comment]
Lot's of laggyness on verion 1.45.0. Didn't notice it before so the issue seems new.  Something is definitely blocking the UI thread from drawing in a timely manner.  The issue comes and goes, but it surely destroy's develop flow.  Haven't noticed any unusual cpu usage yet, but this is a 32-core thread-ripper so it takes a lot to have that be a problem.

**Comment by jrieken** [comment]
@schwab, @subash7038 Sorry, I will not be able to help you because you have not provided actionable information. 

@bemasher Thanks for the trace. This is useful. It seems like a massive decoration change happens - that is for the GIT state on the explorer, e.g. "M" for modified, "U" for untracked etc. Is this a very large workspace? Or a state with many, many pending changes or much being ignored?

**Comment by bemasher** [comment]
@jrieken turns out that was the problem, I hadn't been paying attention that a parent directory was a git repository and had added quite a lot of test data (read: a couple hundred individual files). Adding the test data directory to `.gitignore` fixes this.

**Comment by alignsoft** [comment]
Also noticing since the Version: 1.45.1 release everything freezes after saves for half a minute, also on switching back to the app after switching to another app, and occasionally for no discernible reason at all - everything just stops. There was no issue on this project with the previous release. Mac OS X 10.14.6

**Comment by jrieken** [comment]
To verify:

* run `npm i @angular/cli`
* don't ignore node_modules or rename node_modules folder so that you have 5000+ changes
* press refresh in the SCM view
* things should not freeze 🧊

**Comment by MattGrdinic** [comment]
For what it's worth I had a similar experience over the weekend. In my specific case it was when typing. I'd enter up to 4 words before the screen updated. 

Did this over multiple app and system restarts. I uninstalled (On Mac, so drag to trash), downgraded to April, issue was gone. I then updated, issue came back. 

Uninstalled one more time, issue gone, removed extensions (icons and VS Intellicode), updated to newest and now it seems to have resolved itself 

Apologies for not getting a trace, will do so if it comes back!
