### ISSUE TITLE
Add keyboard shortcut to select word

### ISSUE THREAD

**Issue by Janjuks** [Microsoft/vscode#9773]
- VSCode Version: 1.3.1
- OS Version:Win 7 x64

Please, add option to select word where the cursor is. I couldn't find it in the shortcuts list here.
For example, in VS it's `ctrl+w`.

**Comment by wallverb** [comment]
Cmd+D works for me on OSX

**Comment by Janjuks** [comment]
You are right, also works on windows. Thanks!

**Comment by kevinpeno** [comment]
Does not work with multi-column, however.

**Comment by Janjuks** [comment]
If select word doesn't work then why not use cltr+shift+left/right instead of mouse?

**Comment by kevinpeno** [comment]
because not all lines with words I'm selecting are the same size :)

**Comment by PunchyRascal** [comment]
I think that this is actually needed, because what I expect from "select word" shortcut is that it selects the word under caret and when invoked again, puts the cursor back where it was, but with this "workaround" command it starts selecting other occurrences of the word, which is extremely confusing.

**Comment by luizcarlospedrosogomes** [comment]
gostaria de criar palavras de atalho, como no eclipse que tenho o sout ou o psvm
