### ISSUE TITLE
Commit message text box: Suggest file name if just one file has been staged.

### ISSUE THREAD

**Issue by derkallevombau** [microsoft/vscode#97732]
When committing changes to a single file, I always start the message with the name of that file. It would be very convenient to not always have to type in the file name.

**Comment by dustinroepsch** [comment]
I plan on taking a stab at this over the long weekend :)

I assume this should also have an option to be disabled? 

This will be my first contribution so if there is anything you think I should know, advice is appreciated.

**Comment by brennanMKE** [comment]
I am getting automatically subscribed to every new issue for this project. How do I get off of it?

**Comment by mitchell-frost** [comment]
I am willing to work on this and I am new here...any tips to understand the codebase?

**Comment by derkallevombau** [comment]
@dustinroepsch As of now, when you hit Ctrl+Space in the commit message text box, it says 'No suggestions.'. With this feature, it should show an entry with just the name of the staged file, and maybe another entry with the parent folder name before it in case you have multiple files with the same name in your project.

So I don't think we need an option to disable it, at least as long as there are no other kinds of suggestions.

**Comment by dustinroepsch** [comment]
Update:
I setup my dev environment for vscode yesterday and started poking around. This is my first contribution so I mostly spent yesterday reading the code.

I found where the commit message box is created, here:
https://github.com/microsoft/vscode/blob/d2cf860d05066a48e728c1a09709b9e79c6243c2/src/vs/workbench/contrib/scm/browser/repositoryPane.ts#L640

My understanding is that I need to hook up a CompletionItemProvider.
https://github.com/microsoft/vscode/blob/ae4a8e3fbb2f2fec5c98cd92c8de82653c755a0b/src/vs/editor/common/modes.ts#L592

But I want to read a little more so that I understand the structure of the code before I dig in. Any advice is welcome!

That said, I can really only spend ~4-6 hours a weekend on this, so it will be a while before I get it done. 

If anyone feels they can do this faster, feel free! I'm just using this feature request as a hobby on the weekends.

**Comment by plainerman** [comment]
Since there hasn't been an update from @dustinroepsch in the last half a year, I have begun investigating this issue.

I thought that to resolve this issue, the best way might be to register a `CompletitionItemProvider` that not just suggests a single changed file but auto-completes all files that have been modified. 

E.g.
Modified files: server.js, client.js

Now you can type serv, and pressing Ctrl + Space auto-completes to server.js. Analogously for client.js


@joaomoreno, I see you have removed your assignment. Is this issue still something you would like to see implemented? If so, could you point me to a place where this provider should be added or maybe something similar has already been done?

Thank you very much.

**Comment by joaomoreno** [comment]
By now, the git extension exposes API which lets you easily get at the staged files. I'll close this as an extension candidate instead.
