### ISSUE TITLE
Intellisense Not Working on Settings JSON

### ISSUE THREAD

**Issue by prayforwinter** [microsoft/vscode#97756]
- VSCode Version: 1.46.0 insider
- OS Version: Windows 10

Steps to Reproduce:

1. Update to newest Insiders build.
2. Open Settings (JSON)
3. Type in "editor." 
4. Observe _No Suggestions_ box appearing.
5. Next to text, try Control + Spacebar. 
6. Observe _No Suggestions_ box appearing.

Actual: Settings JSON does not prompt user with Intellisense options.

Expected: Settings JSON suggests settings based on words typed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by aeschli** [comment]
@jrieken Debugging this down, it seems the SuggestModel markes all JSON proposals as invalid:

The item is marked invalid because the insert and replace range are not the same. Not clear to me what the intend is.
https://github.com/microsoft/vscode/blob/046e3c7f0ea03489293e29c79093020d19ffce51/src/vs/editor/contrib/suggest/suggest.ts#L97

Change comes from https://github.com/microsoft/vscode/commit/425616820c7a424abf3fbfb1a0e399963d9984d5

**Comment by jrieken** [comment]
Yeah, working on it...

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3Abug+label%3Asuggest
