### ISSUE TITLE
Notebook reacts to selection changes of in peek list

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#97820]
see gif

* open GH notebook with a few cell that reference a variable
* run peek references and select entries
* 👀 notice how notebook cells are being highlighted, like "Milestone Work" get selected 

![May-14-2020 16-34-33](https://user-images.githubusercontent.com/1794099/81947549-facb1100-9600-11ea-9dff-fe89b5fba018.gif)

**Comment by roblourens** [comment]
I can repro in Insiders but not master, I'll check again tomorrow

**Comment by jrieken** [comment]
This happens because of this listener: https://github.com/microsoft/vscode/blob/8e872f41d4ba7807e58938bbf861ca6a22d534aa/src/vs/workbench/contrib/notebook/browser/view/renderers/cellRenderer.ts#L309

Tho, not yet sure why the selection keeps changing... Maybe some inner list event (from the references list) bubbles up to the outer list 🤷

**Comment by roblourens** [comment]
That listener is fine, it's the nested lists

**Comment by roblourens** [comment]
Hey @joaomoreno do you have any thoughts on handling this? We have a list inside another list. The inner list handles the touch event properly. The outer list then handles the event and picks up the wrong index because it finds the data attribute inside the inner list in https://github.com/Microsoft/vscode/blob/master/src/vs/base/browser/ui/list/listView.ts#L865.

We can

- Make sure the event is fired on the outer list with the correct element, by fixing `getItemIndexFromEventTarget` to check whether it's in the right list
- Not fire the event on the outer list at all, when we see that it originates in a different list
- Add some property to the list event that says it originated in a different list so the consumer can decide

In this particular case, I think any of these are fine

**Comment by roblourens** [comment]
Thinking more, I don't think that the event should ever be handled by two lists at all. Meaning we either mark the browserEvent as handled, like with preventDefault/isDefaultPrevented, or we make the list check every event to be sure that it originated in this list.

**Comment by joaomoreno** [comment]
> Thinking more, I don't think that the event should ever be handled by two lists at all. Meaning we either mark the browserEvent as handled, like with preventDefault/isDefaultPrevented

This sounds good to me.

> or we make the list check every event to be sure that it originated in this list.

This also sounds good to me.

**Comment by tanhakabir** [comment]
related when I do peek references, I see markdown cells being selected? 
![image](https://user-images.githubusercontent.com/12758612/135944420-2f0d71ff-77da-43cb-90e0-c0fe83489ca6.png)

Notice I'm looking for under-discussion but "Configure" is being highlighted as one of the references

**Comment by roblourens** [comment]
From #181572 

> @roblourens I'm now seeing very inconsistent behavior in regular trees:
>
> https://github.com/microsoft/vscode/assets/22350/94a73150-fcd7-41a0-92be-fa7851f7165a

Good catch, I didn't notice that

**Comment by joaomoreno** [comment]
Thanks for the quick handling!
