### ISSUE TITLE
Can't paste copied file in File Explorer, using Remote WSL

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#97917]
![recording (6)](https://user-images.githubusercontent.com/22350/82057912-4f839000-96c4-11ea-83a5-a330a1cf0a72.gif)

**Comment by isidorn** [comment]
What a lovely gif, thank you

**Comment by isidorn** [comment]
This works for me just fine in Dev Containers.
@aeschli have you also seen this for WSL?
@joaomoreno can you please put a breakpoint [here](https://github.com/microsoft/vscode/blob/7309285b3c54aa74d8990a7d49a849ba178e2a04/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L493) and check if the fileCopiedContext proeprly gets set to true otherwise it might be that the `clipboardService` is in the wrong.

**Comment by joaomoreno** [comment]
This returns `false` on the first context menu (for copy) as well as on the second context menu (for paste):

![image](https://user-images.githubusercontent.com/22350/82071854-f6712780-96d6-11ea-825c-cd81e08f9e7d.png)

**Comment by letmaik** [comment]
I'm seeing this issue locally as well (not just remote), but in Insiders only. 1.45.1 release is working fine.

**Comment by letmaik** [comment]
> I'm seeing this issue locally as well (not just remote), but in Insiders only. 1.45.1 release is working fine.

This is still broken in Insiders. Works fine in 1.46.1. Could someone look at this? It's a serious regression that's been here for over a month now and makes Insiders for me unusable.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/100797
