### ISSUE TITLE
Dropping a view into an empty panel does not show it

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98016]
Steps to Reproduce:

1. drop a view into an empty panel

=> 🐛 the view does not show directly

![recording](https://user-images.githubusercontent.com/900690/82138409-840c5e80-9820-11ea-8306-69f40619a33b.gif)

**Comment by jeanp413** [comment]
@sbatten after 349b16d, now every time you move a view from the panel to the activity bar and vice versa it gets open automatically, is that the expected behavior in general?.
Personally I liked the previous behavior (from 4210a6a) where the view didn't get open so maybe another way to fix this issue when the panel is empty could be updating this line
https://github.com/microsoft/vscode/blob/fbb367917ce202a89435e2a9ba620d49b25108ac/src/vs/workbench/browser/parts/panel/panelPart.ts#L212
adding some check whether there isn't any visible views
```
const isActive =  ...  || this.compositeBar.getVisibleComposites().length === 0;
```
