### ISSUE TITLE
vim vg0, vg^ and vg$ should include the character at the end of the line in the selection

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#9802]
- VSCode Version: Code - Insiders 1.4.0-insider (fc167f86c1aee27951b7d4b4db51229f62d0a0ad, 2016-07-26T05:12:44.554Z)
- OS Version: Linux x64 4.4.0-28-generic, Ubuntu 16.04

#9699

Not sure if this is an extension, sample extension or API issue?

Steps to Reproduce:

1. Open a file
2. Go to a line with content
3. <kbd>end</kbd>
4. Type `vg0`, notice the character at the end is not included in the selection (unlike when running `vim`)
![image](https://cloud.githubusercontent.com/assets/2193314/17148276/5770a794-531b-11e6-8e57-cdb9c27e9f89.png)

And

5. Go to beginning `0`
6. Type `vg$`, notice that character at the end is not included

And

5. Go to beginning `0`
6. Type `vg_`, notice that non white space character at the end is included, BUT, cursor position is on next character

**Comment by rebornix** [comment]
Same case as #9803. Thanks @Tyriar

**Comment by sandy081** [comment]
This is a different issue than #9803. All selection commands are excluding the last character.

**Comment by sandy081** [comment]
Again these are Vim specific details which has to be implemented by Vim extensions. Because, Vim extension uses Block cursor type for Normal (and Visual mode). Relation between Block type cursor and Line type cursor is that
- To represent current character or column, Line cursor type blinks before it where as block type cursor blinks on top of the character

For eg: `ab|c` <==> block cursor on top of `c`

All movement and selection operations are based on this fact. So, when selecting backwards it is expected to ignore the current character.

One more fact is that in Vim world, there is no special position for end of line, instead last character is represented as end. So when <kbd>end</kbd> or `$` is pressed, Vim moves the cursor to last character. Hence by default `vg0` or `vg^` ignores first character if just calling cursorMove command. So Vim implementation has to handle selecting current character on top of calling this command.

Moving this to Vim sample extension

**Comment by sandy081** [comment]
This issue was moved to Microsoft/vscode-extension-samples#3
