### ISSUE TITLE
support default folding configuration while using LSP 

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#98099]
When LSP is enabled, the folding marker listed in [vscode/extensions/go/language-configuration.json](https://github.com/microsoft/vscode/blob/master/extensions/go/language-configuration.json#L31-L37) seems to be ignored. 
https://github.com/microsoft/vscode-go/issues/3249

Is this intentional?

Is there any way to use this default foldingRange information while using LSP?

The `//#region .... //#endregion` is not part of the language spec so handling this is beyond the language server's responsibility. Either we need to teach vscode to use both information sources, or combine the info from LanguageClient middleware.

**Comment by kieferrm** [comment]
VS Code allows to have multiple folding range providers. So, when the user enables the LS, your extension can add a folding range provider that adds region support.

**Comment by hyangah** [comment]
Thanks @kieferrm 
That's what I originally expected, but we are seeing different behavior. (microsoft/vscode-go#3249) It seems to me that only the result from LS's folding range resultsis reflected  and the default foldingRange information is ignore. Should I reopen this issue?

**Comment by ramya-rao-a** [comment]
@hyangah I believe what @kieferrm is saying is that the language server should update its folding range provider to support region support.

@kieferrm, I believe what @hyangah is asking is whether it is by design that only 1 provider's result is used by VS Code or is it right to expect that VS Code should respect both the default folding provider and the one from language server. This ask would similar to other providers, for example completion. When multiple completion providers are registered for the same language, results from all of them are combined by VS Code.

Personally, I feel that only 1 provider should be respected as otherwise conflict resolution can get tricky

**Comment by stamblerre** [comment]
> @hyangah I believe what @kieferrm is saying is that the language server should update its folding range provider to support region support.

Just to follow up on this - this isn't possible because this syntax is editor, not language, specific. Combining the results from multiple folding range providers would be the only way to get this to work correctly.

**Comment by hyangah** [comment]
@kieferrm @ramya-rao-a 
This is not a language specific but very specific to VS Code. So, I agree that this is not the function of the language server. Either it should be done by the vscode-go extension or the vscode itself. 

My question was whether it's intentional or a bug to disable the existing default vscode's folding provider (that defined and implemented `#region`) when the language server is activated.
