### ISSUE TITLE
In Find menu, move "find in selection" option into search bar with other options that affect search behavior

### ISSUE THREAD

**Issue by rben01** [microsoft/vscode#98275]
- VSCode Version: 1.45.1
- OS Version: Darwin x64 19.5.0 (10.15.5)

Steps to Reproduce:

1. Press ⌘F to open the Find menu

Issue:

There are four options in the Find menu that affect *how* searching is to be done: case (in)sensitivity, whole words, regex, and whether to search only in the selection. The first three of these are handily inside the search window, while the fourth is, unintuitively, on the far right of the Find menu with the buttons for next/previous result and close. It is unintuitive to group a button that affects the search logic with buttons that affect searching more generally instead of with the other three buttons that also affect the search logic.

<img width="425" alt="Screen Shot 2020-05-20 at 5 48 54 PM" src="https://user-images.githubusercontent.com/766670/82501372-28153480-9ac3-11ea-90ee-f36c5ea81159.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by misolori** [comment]
The Find widget is used in multiple places other than the editor (Search, Terminal, and Output). And not every area has the find in selection option for various reasons. So this would cause inconsistencies in the find widget and not be a good experience. Secondly, the find in selection operates is a mode that toggles how search works (wether over the entire document or your selection). So it's not the same as the other search options, which is why it's in a separate section. Thanks for the feedback though, we'll keep this in mind in the future.
