### ISSUE TITLE
Sub menus for Editor Context Menu

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#9827]
Can we have the ability to define sub menus for editor context menus (possibly to the editor/title men too).
For instance when adding menu items for refactoring there could be plenty of refactoring items:
- Extract variable
- Extract method
- Extract constant
- Rename
- Move class
- Change signature... etc

I believe adding all of them to the context menu without adding them as sub menus could result in a cluttered UX.

![sample](http://help.eclipse.org/neon/topic/org.eclipse.cdt.doc.user/images/60/refactorExtractLocalVar.png)

![sample2](https://i-msdn.sec.s-msft.com/dynimg/IC87294.gif)

**Comment by ungod** [comment]
+1

**Comment by TheMegaMatt** [comment]
+1

**Comment by mike-lischke** [comment]
May I asked about the current status of this FR? Given that we have [this patch](https://github.com/Microsoft/vscode/commit/2d052f76a2171bdf40d7cc71ef82494413a5b1b7) since more than a year, I wonder when we can actually use submenus in our extensions?

**Comment by DanTup** [comment]
As well as being able to add items to a sub-menu, we should be able to do this dynamically (eg. with a request to a provider, not just declarative) so that we can disable/hide refactors that are not applicable to the current position/selection.

**Comment by jrieken** [comment]
@DanTup Regarding all those linked issues pointing towards more refactoring, please sync with @mjbvz and me about our new code action types. Idea is that you predefine certain code action types, e.g. this is about extracting and we then populate the light bulb and a (new) refactorings menu for you.  See https://code.visualstudio.com/updates/v1_20#_codeactionprovider-improvements

**Comment by DanTup** [comment]
@jrieken Yeah, I've somewhat changed my mind a little since the last comment. I thought we had a lot of refactors that are available "for the whole file" and would result in lightbulbs no matter where the cursor is; however there actually seem to be very few.

So for now, this isn't a big deal to me - however the idea of adding things like refactors/light bulbs to context menu has come up several times in discussions about visibility. I have noticed that the lightbulb sometimes doesn't seem very noticeable hovering over code (did it used to be in the gutter?).

**Comment by mike-lischke** [comment]
Hmm, is this FR about a different way to add refactoring support or a general FR for submenus? I had the impression, it's the latter. I need a sub menu for various actions my extension can do for a (grammar) file, like showing some graphs, profiling details etc. This is not related to refactoring and hence cannot (and should not) be covered by the light bulb menu.

**Comment by DanTup** [comment]
I think it was a general request for context menus; which I requested can be contributed dynamically (eg. not declarative, so we can handle a request for a context menu and choose what to put in there asynchronously), but possibly I also derailed a little about having lightbulbs shown in there too.

**Comment by jrieken** [comment]
Yeah, this issue is about adding sub-menus but it seems that @DanTup implements various refactoring commands and those we wouldn't like to see as separate commands but to integrate into the platform - it's similar to us not liking separate format or rename commands. However, for code actions (refactorings & quick fixes) it's more fuzzy and that's why we have the new API in place

**Comment by 3dots** [comment]
Hello. Has this FR petered out somewhat? Or does this have a chance of being put in?

I just checked out a highlighting/marker extension, and figured: can't be that hard to make a context sub-menu which lets you toggle a highlight based on a list of colors already used in the file... Turns out it's not that simple after all.

So, what you then have to pipeline all that through the Lightbulb instead?

**Comment by caadam** [comment]
+1 for this request. I'm implementing an extension that has a Visual Studio like treeview and require a context menu that has multiple levels to keep the UI manageable.

**Comment by Yzrsah** [comment]
Hey guys. The reality is that with this great availability of awesome extensions for VSCode, the context menus can become an unusable wreck quickly.

I have to disable useful extensions that I wish I could use because having them breaks the context menus. And with nobody certain of a universal convention to group things consistently, you end up with a bunch of dividers and sections taking up even more space.

I understand the desire to keep the menu as a simple and flat list of commands. But I don't think this will ultimately work out with extensions due to the impossibility to force consistency. The past 3 years show a test case for what people will actually want to do with the extensions.

I added TODO entries for "fork these 20 extensions and alter and fix the menus, fix consistency, remove menu items, then maintain the ongoing forked versions of all of them." But that is something we are just not doing right now because there's been other workload.

At least, extensions with multiple commands can't really break the rules too badly if they just insert a single node at the root. At least you could re-organize the location of that entry. It would be possible to implement a setting which automatically shows commands grouped under submenus by their extension name.

**Comment by phiter** [comment]
updates on this? I wish I could create an extension to create new file from a template like they do in PHPStorm

**Comment by rockxsj** [comment]
+1

**Comment by swjain23** [comment]
Any update on this? We want to group commands to support adding new files from template, like in Visual Studio:

![image](https://user-images.githubusercontent.com/36710109/70651330-76193880-1c05-11ea-9494-f067ce269a43.png)

**Comment by phiter-monetizze** [comment]
Do we have this already? Because I'm seeing this:

![image](https://user-images.githubusercontent.com/56091403/72733278-4c452100-3b76-11ea-9828-024096309f34.png)

V1.41.1

**Comment by gjsjohnmurray** [comment]
AFAIK it's not yet possible for extensions to contribute submenus. See https://github.com/microsoft/vscode/issues/85218#issuecomment-556081709 for my hope that it'll come soon.

**Comment by damgot** [comment]
I'm also interested on it.
I've so many command in my extension's editor context menu... I really need to be able to arrange them in sub-menus

**Comment by viceice** [comment]
We love to see that too. Want to use it in the standalone monaco editor.

**Comment by sentry07** [comment]
Another +1 from me. Grouping editor/context commands into sub menus would be amazing to have.

**Comment by gjsjohnmurray** [comment]
@jrieken until now you have (understandably) resisted requests for extensions to be able to contribute menu items that get computed dynamically (i.e. at the point where the context menu is about to be displayed).

Would you consider permitting this for **sub**menus, when (as many of us hope) it becomes possible for an extension to contribute submenus?

For instance, my extension might add an "Extra Stuff" submenu entry to the editor/context menu in such a way that when the context menu appears it shows `Extra Stuff   >` and invokes an async function in my extension to return the computed contents of my submenu. A cancellation token would allow the menu handler to cancel my compute if the user dismissed the first-level menu before I had supplied the submenu contents. And if the user's interaction with the context menu requests display of the submenu before the async function has completed, maybe show a spinner in place of the `>` on the menu entry.

**Comment by Blaiski** [comment]
Another +1 from me too. It's been four years since this feature has been requested. Is there any hope we might be getting it soon, please? Anyone who can see that it's just impractical to expect extensions to keep adding their menu items all at the top level?  @gjsjohnmurray I also add my voice here. I need to compute and generate my submenus dynamically so I'd expect to be able to do them using async functions just like the case with showQuickPick

Thank you

**Comment by zesluo** [comment]
just wondering, is it available now for adding submenu to context menu?

**Comment by gjsjohnmurray** [comment]
> 
> 
> just wondering, is it available now for adding submenu to context menu? Thanks

Now available in Insiders as a proposed API, slated for finalization in in the next-but-one release.

**Comment by zesluo** [comment]
Thanks for your reply! @gjsjohnmurray , May I know when it will be public?

**Comment by gjsjohnmurray** [comment]
> 
> 
> Thanks for your reply! @gjsjohnmurray , May I know when it will be public?

The related issue (#100172) Is currently showing as on the September 2020 milestone, meaning it's slated to ship in Stable in early October.

**Comment by joaomoreno** [comment]
Closing this, since it's done in `master`.
