### ISSUE TITLE
Web: broken Notebooks smoketests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98364]
```
1) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Notebooks
           inserts/edits code cell:
     Error: Timeout: get element '.quick-input-widget' after 20 seconds.
      at /Users/runner/runners/2.168.2/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/runners/2.168.2/work/1/s/test/automation/out/code.js:9:58)

  2) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Notebooks
           inserts/edits markdown cell:
     Error: Timeout: get element '.quick-input-widget' after 20 seconds.
      at /Users/runner/runners/2.168.2/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/runners/2.168.2/work/1/s/test/automation/out/code.js:9:58)

  3) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Notebooks
           moves focus as it inserts/deletes a cell:
     Error: Timeout: get element '.quick-input-widget' after 20 seconds.
      at /Users/runner/runners/2.168.2/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/runners/2.168.2/work/1/s/test/automation/out/code.js:9:58)

  4) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Notebooks
           moves focus in and out of output:
     Error: Timeout: get element '.quick-input-widget' after 20 seconds.
      at /Users/runner/runners/2.168.2/work/1/s/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/runners/2.168.2/work/1/s/test/automation/out/code.js:9:58)

```

**Comment by rebornix** [comment]
Thanks for the ping. I checked the release history and found that we didn't have a build which passed the web smoke test ever. The error `timeout 'quick-input-widget'` doesn't seem to be notebook logic related, I guess it's due to how the notebook document is being opened (but never finishes successfully).

Tried to debug this issue but didn't get web smoke test running locally, things I tried

* `distro` branch, `yarn gulp vscode-reh-web-darwin`
* switch to `master` branch
* `VSCODE_REMOTE_SERVER_PATH=/Users/penlv/code/vscode-reh-web-darwin VSCODE_DEV=1 yarn smoketest --web`

and then I kept seeing error 

```log
refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https://az416426.vo.msecnd.net 'unsafe-eval' https: 'sha256-UDiEJoRBTqdFzC+PxQOVuk7jNe7IZzGHJIl9OFBHyCE='". Either the 'unsafe-inline' keyword, a hash ('sha256-5PEzOFm7Jc8UuC0tkwsErHIw36A1igTT942G8MD5G+w='), or a nonce ('nonce-...') is required to enable inline execution.

semver-umd.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

Also in the HTML, the `semver-umd` script is referenced as 

```html
<link rel="prefetch" href="./semver-umd.js">
```
which is different from what I saw in https://github.com/microsoft/vscode/blob/master/src/vs/code/browser/workbench/workbench.html#L22

@bpasero do you know how to test this locally without above errors? it is even better if you can share how to troubleshoot the web smoke test.

**Comment by rebornix** [comment]
It seems @roblourens pushed some fixes https://github.com/microsoft/vscode/commit/b877c4d411d0e2e08d6fccb75faf8471838426be

**Comment by bpasero** [comment]
@rebornix I recommend to use the OSS repo and then `yarn gulp mixin-server` because `distro` can always be out of sync and is probably broken right now. I can run the tests (`yarn smoketest --web`) just fine from OSS with that approach and still see failures:

```
  1) VSCode Smoke Tests (Web)
       VSCode Smoke Tests (Web)
         Notebooks
           moves focus in and out of output:
     Error: Timeout: is active element 'webview, .webview' after 20 seconds.
      at /Users/bpasero/Development/Microsoft/monaco/test/automation/out/code.js:181:23
      at Generator.next (<anonymous>)
      at fulfilled (/Users/bpasero/Development/Microsoft/monaco/test/automation/out/code.js:9:58)
```

**Comment by bpasero** [comment]
> I checked the release history and found that we didn't have a build which passed the web smoke test ever.

What?

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=75320&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=1fbbf8a8-a0a4-519f-def5-b5fd8ca21811

**Comment by roblourens** [comment]
I have no clue why it's failing on the very first step which is just running a command in quick access. Disabling it for now.

**Comment by roblourens** [comment]
And I am not reproing the focus error you got, everything passes locally for me.

**Comment by roblourens** [comment]
@bpasero is there any way to write logs during a smoke test that will show up in the CI log?

**Comment by bpasero** [comment]
@roblourens I cannot answer that, but maybe check if there are options you can pass to playwright to see the console:

https://github.com/Microsoft/vscode/blob/876f2e70f9a2e1988887f8ca82294418afac15a2/test/automation/src/playwrightDriver.ts#L143

**Comment by roblourens** [comment]
Currently blocked because `--enable-proposed-api` isn't supported for launching in web. I tried adding it to the list of args for the server, but it doesn't make it to the client. I guess I'm not sure how these args are passed from the server to the client's environment service, can you show me where that happens?

**Comment by bpasero** [comment]
@roblourens yes, but should be easy to add, e.g. we enable all proposed API for integration tests here:

https://github.com/microsoft/vscode/blob/595d2b9b916d063aadfc2c1a8c8f6df5b45572a8/test/integration/browser/src/index.ts#L47

via the `enableProposedApi` payload. Should be possible to do the same here:

https://github.com/microsoft/vscode/blob/595d2b9b916d063aadfc2c1a8c8f6df5b45572a8/test/automation/src/playwrightDriver.ts#L149

**Comment by roblourens** [comment]
That did it, thanks! They are now enabled for web as well
