### ISSUE TITLE
Snippets: drop dependency to IClipboardService#readTextSync

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#98497]
Snippets seems to be the only client of `IClipboardService#readTextSync`. I see no way supporting this method once we move to Electron sandbox. And given this method never worked in web, I think the async `readText` should be adopted for consistency anyways.

**Comment by jrieken** [comment]
Not possible

**Comment by bpasero** [comment]
Then I suggest to remove this feature, we will not be able to support sync access to clipboard in the future.

**Comment by jrieken** [comment]
How does the editor paste? It's not async, right? The challenge is that inserting snippets is sync and therefore I cannot await async clipboard reading, for e.g tab completions. The whole backstory is here: https://github.com/microsoft/vscode/issues/76847

**Comment by bpasero** [comment]
@jrieken the editor has focus on a hidden text area and thus copy/paste work natively. What I am referring to is the use the related sync `IClipboardService` methods. If you can read the clipboard using another trick that does not involve this Electron API, then it is fine as well.

The `clipboard` module is not accessible in sandboxed renderers and as such need a IPC call to the `electron-main` process which makes it async.

**Comment by jrieken** [comment]
This does require changes to all callers of `SnippetController#insert` because they need to (async) resolve the clipboard contents, ideally only when needed, and pass it to the constroller. 

- [ ] src/vs/workbench/contrib/snippets/browser/tabCompletion.ts: _very hard because it happens in the purely sync context_ 
- [x] src/vs/workbench/contrib/snippets/browser/insertSnippet.ts: _used to be the only propper place_
- [x] src/vs/workbench/contrib/preferences/browser/keybindingsEditorContribution.ts: _not needed because snippets are static and don't use the clipboard_
- [x] src/vs/workbench/api/browser/mainThreadEditor.ts: _now checks if snippets need the clipboard and resolves them in place_ 
- [ ] src/vs/editor/contrib/suggest/suggestController.ts: _needs to check every completion for clipboard access and iff so retrieve and pass-on the data_

**Comment by jrieken** [comment]
Closing, this is now as good as it gets... Since reading clipboard is async, two potential problems exist

* (snippet) tab completion is now async. Changes that happen while the clipboard is read cancel tab completion (I guess that's unlikely...)
* for normal completions the clipboard is read during "compute" which means copying something while suggestions show won't be honoured.

**Comment by bpasero** [comment]
Thanks!
