### ISSUE TITLE
brackets inside file paths in the terminal breakes the follow link feature 

### ISSUE THREAD

**Issue by hacknlove** [microsoft/vscode#98498]
Issue Type: <b>Bug</b>

Open the terminal, run whatever command that shows a valid path to an existing file, that has brackets anywhere in the path like /foo/bar/[buz]

Try to follow the link with ctrl+click

The file should be opened, visual code tries to open just until the first bracket /foo/bar/ and it errors Unable to open 'bar': File is a directory.

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.3.0-53-generic

**Comment by Tyriar** [comment]
This sort of thing is difficult to support, we need to have a careful trade off of how many times we hit the disk and how complex the regex that is run on a line each time to cover the majority of cases.

**Comment by benmccann** [comment]
I would expect the regex for matching a path segment not to be overly complicated (something like `[^/\\]+`). And since this runs in the terminal it should run a very limited number of times since you can only display so many file names at once. As a result, I would imagine the performance concerns should be limited and addressable

**Comment by zakkor** [comment]
Any chance we could make the list of characters accepted within a path a configurable option?

This way people who want `][` in their path names can do so (even if that might mean worse performance)
