### ISSUE TITLE
Settings view - add section 'Changed'

### ISSUE THREAD

**Issue by gozzoo** [microsoft/vscode#98515]
The default way to change some setting is with the settings editor. It is very nice, but finding my own changes is a little bit cumbersome. Of course I can always go to json view, but I think it would be very convenient if on the left side, where all groups of settings are listed, below (or above) 'Commonly used' to add 'Changed' section.

**Comment by IllusionMH** [comment]
Just FYI at this moment you can either use: 
"Show modified settings" in three dots menu
![image](https://user-images.githubusercontent.com/1312662/82812460-b90d5680-9e9b-11ea-82f5-c4ec34b97ac6.png)
or `@modified` filter in search bar (type `@` (similar to extensions search) to see possible filters)

**Comment by gozzoo** [comment]
Thanks @IllusionMH, I didn't know that one.

But still, it's a little bit strange that 'Commonly used' is on the left panel, and 'modified settings' is accessable through the `...` menu. Furthermore when selecting both we get some wierd intersection between them that makes no sense.

**Comment by IllusionMH** [comment]
Commonly used - is [predefined list](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/preferences/browser/settingsLayout.ts#L20) of Settings to display that users most likely would want to check/change, and not something personal for each user.

On the other hand - `@modified` is filter of all existing settings settings, and can be applied to list you are looking at.

So when you have Commonly Used or Workbench > Appearance selected in left tree view - you would only see modified settings from that selected category, which makes sense (at leas I can quickly see what 4 settings I changed in Appearance instead of all 97 changed).

So `@modified` might be displayed as checkbox somewhere at the top, but not as category in left side.
