### ISSUE TITLE
Allow customizing hover details for debug sessions

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#98598]
@IllusionMH suggested here https://github.com/microsoft/vscode-js-debug/issues/479#issuecomment-633661692 that session hovers can be customized. Right now it's always simply "Session"

![](https://user-images.githubusercontent.com/1312662/82831638-a279f600-9ec1-11ea-9f13-fd551c75528c.png)

**Comment by isidorn** [comment]
I think this makes session. However what would you have it say?
Just duplicating the name does not make sense.
Maybe "Order Portal Debug Session"?

**Comment by IllusionMH** [comment]
> Just duplicating the name does not make sense.

Duplicating name doesn't looks great for short titles but it can contain Page title (page url) in case of several tabs with same title and will be cropped really fast.
It's impossible to distinguish between cropped `Order Portal (localhost:8080/orde...`  and `Order Portal (localhost:8080/orde...`, but hover will show full title with full URL.

![image](https://user-images.githubusercontent.com/1312662/82936947-00790d00-9f98-11ea-8dc4-e1cec72c4452.png)
Untitled editors don't look bad because of almost similar title, regular files has full path even if user can see file name and parent folder.

Ideally - configurable title as with tree items.
