### ISSUE TITLE
Improve first run experience

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#98614]
This issue to explore how we might improve the (default) first run experience from the file explorer (and other areas). 

### Desktop
Today, when you install VS Code for the first time and open a file you are greeted with a series of views in the explorer:

1. Open Editors
2. Folders
3. Outline
4. Timeline
5. NPM Scripts

![image](https://user-images.githubusercontent.com/35271042/82950090-9477b400-9f59-11ea-9d50-788f19a37b63.png)

## Proposal

We can consolidate some of the features that have overlap in other areas:
1. Hide `Open Editors` in favor of Editor Tabs
2. Folders - Keep Visible
3. Hide `Outline` in favor of Breadcrumbs + `Go To Symbols in Editor`
4. Timeline - Keep Collapsed
5. Hide `NPM Scripts` in favor of adding an action ~in the editor toolbar~ via codelenses in the `package.json` file to surface it

![image](https://user-images.githubusercontent.com/35271042/83075924-809b8300-a029-11ea-933b-7654fc6121c0.png)

## Other Ideas
In addition to this proposal, we also discussed the following options that would require more engineering effort:
- Once we add a secondary sidebar, we could move file specific views onto it (outline, timeline, etc.)
- For Codespaces: hide the remote explorer and surface port forward through the remote picker
- For the GitHub extension: combine the PR and Issues view into the SCM view since they are all `git` related features
- Make the sidebar headers clickable to surface the view options (right-click menu to toggle views)
- Add an action from the `Go To Symbols in Editor` quick pick that toggles the outline view

**Comment by regs01** [comment]
Outline is not a Breadcrumbs alternative. Those are two highly important distinctive features. It's shouldn't be anywhere hidden.

**Comment by isidorn** [comment]
Also assignign to myself since I will have time this and next week to look into this.
To start I suggest that we do the following from your items above: "Make hidden views more discoverable".
That I think is good to have independent of this work and is a good first step so we can hide views more aggressivly by default.
For that I like from the above the following:
* Make the sidebar headers clickable to surface the view options (right-click menu to toggle views). Also use pointer icon for it.

Ideas from @misolori and me which we discussed on Slack:
* Have an additional action in each view container Title area clicking on it would show all views
* Make the View main menu have submenus. So instead of Explorer, it would be a submenu Explorer > Folders, Open Editors, Timeline...

**Comment by misolori** [comment]
Here are two ideas for how to improve the discoverability.

## Global view menu
This would add an ellipsis icon to all global viewlets and surface the view menu. This is the same menu you get when you right-click in the sidebar.

![image](https://user-images.githubusercontent.com/35271042/84207267-c9116280-aa65-11ea-8629-46ab676e9c37.png)

This means that we would need to account for when a viewlet only has a single view and the view actions are collapsed with the title:

![image](https://user-images.githubusercontent.com/35271042/84207409-2ad1cc80-aa66-11ea-97da-57c50416a10b.png)


And when a viewlet already has a context menu:

![image](https://user-images.githubusercontent.com/35271042/84207319-f9f19780-aa65-11ea-8e43-1fd4eb96cc37.png)


## Clickable title
This would make the title on all views clickable and surface the same menu.

![image](https://user-images.githubusercontent.com/35271042/84207273-cd3d8000-aa65-11ea-895b-cf637360987b.png)

**Comment by isidorn** [comment]
@misolori great work, love it. Especialy the first since it makes it very discoverable. The only nit pick, when a viewlet already has a context menu: I would do it
Views > 
Extension actions

So do not put the Extension actions in a submenu. But the Views should still be the first entry.

fyi @sbatten @sandy081 @bpasero even though I think this will be discussed in today's UX call.

**Comment by sandy081** [comment]
I like moving them to `...` action and also liked @isidorn suggestion to only move view actions as sub menu when the viewlet has `...` actions already.

**Comment by misolori** [comment]
So I don't think we're going to find a good icon for "views" since that is a pretty hard concept to show and we already have similar icons that represent view:

<img width="20%" src="https://user-images.githubusercontent.com/35271042/84548078-b8f1c100-acb9-11ea-9076-21776832ba1f.png"> 
<img width="20%" src="https://user-images.githubusercontent.com/35271042/84548104-c5761980-acb9-11ea-8619-4a2dd409a2dc.png">
<img width="20%" src="https://user-images.githubusercontent.com/35271042/84548007-8d6ed680-acb9-11ea-8f57-212728686702.png">


I still think we should stick with using the ellipsis since we also use this for both overflow and showing actions (view context menus and editor ellipsis). Here's how I think we can use the pattern in both:

- Use the same pattern as before, when there is no overflow we show all view options
- When there is overflow, we group view toggles in view menu
- The ellipsis icon would always be visible

![image](https://user-images.githubusercontent.com/35271042/84547894-4da7ef00-acb9-11ea-8667-25607dc31935.png)

**Comment by isidorn** [comment]
@misolori I like this suggestion a lot for the panel.
So let's go with the elipses. I can look into the implementation.

**Comment by isidorn** [comment]
For the first run experience I think a good first steps for this milestone are the following:

- [ ] Show elipses in every view container to make hidden views and the ability to hide views more discoverable
- [x] Have Open Editors collapsed by default
- [ ] Move NPM Scripts into an extension @egamma

We'll see how these changes are accepted by the community and then next milestone we can
- [ ] Show elipses for hidden views also in Panel
- [ ] Think about the Timeline view @eamodio 
- [ ] Think about hiding OUTLINE and OPEN EDITORS only for new users @jrieken and @isidorn We will probably not do this, but we should think about it

**Comment by regs01** [comment]
> Think about hiding OUTLINE only for new users @jrieken and @isidorn We will probably not do this, but we should think about it

Don't think about it. It's unproductive. It's one of most important feature and fundamentally basic feature of IDE.

**Comment by isidorn** [comment]
I have pushed an initial version of the elipses in the title area
Try it out with VS Code insiders from tomorrow and let me know what you think.

![Screenshot 2020-06-22 at 16 33 49](https://user-images.githubusercontent.com/1926584/85299900-2b2a8880-b4a6-11ea-8b1a-0ecac233c76e.png)

**Comment by isidorn** [comment]
So for this milestone we only need to move the npm script to an extension.

**Comment by isidorn** [comment]
I see that we have created an issue for moving the npm scripts view out to an extension.
Since that issue tackles that, and we have done in this issue what we planned for this milestone I am moving this out to July for the other 3 remaining action items from above:

- [ ] Show elipses for hidden views also in Panel
- [ ] Think about the Timeline view 
- [ ] Think about hiding OUTLINE and OPEN EDITORS only for new users. We will probably not do this, but we should think about it

**Comment by isidorn** [comment]
I see we have hidden the npm scripts view by default which is great. 
We will not hide the OUTLINE and OPEN EDITORS views due to their popularity.
I am discusing with Eric if we should hide the Timeline view by default.

As for the panel, we could render `...` in the left most area of the actions and if there is not enough room to render all the panels we would add another section to the `...` effectively merging the panels and views in one context menu. I think this could work nicely, but nothing for July, thus moving out to On-Deck.

**Comment by eamodio** [comment]
@isidorn I made the changes to hide the Timeline view when there are no (excluded) registered providers -- this should help the first-run experience at least when the Timeline view wouldn't be useful.

**Comment by isidorn** [comment]
@eamodio thanks for doing that. I just tried it out and it works nicely.
Since we have done most of the things planned in this item I am closing it and for `...` in the panel I have created this follow up item https://github.com/microsoft/vscode/issues/103813
