### ISSUE TITLE
Sync turns off right after enabling it and a setting forces VS Code to restart

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#98675]
I've enabled sync on a new machine. One of the settings prompted me to restart VS Code (`update.mode`) and I clicked `OK`. When VS Code came back, Sync was turned off.

**Comment by sandy081** [comment]
Following confirmation dialog is shown if you try to reload/restart while settings sync is being turned on. 

<img width="476" alt="image" src="https://user-images.githubusercontent.com/10746682/89475573-b62abe00-d788-11ea-9590-68b38265ec5d.png">

On confirming, settings sync will be cancelled (if not yet turned on) and window is restarted otherwise window restart is cancelled.
