### ISSUE TITLE
Add menu action to delete vscode cache and configuration

### ISSUE THREAD

**Issue by 3ENITblu** [microsoft/vscode#98698]
It would be great to have an option to complete factory reset VScode like Jetbrains IDEs does; sometimes you want to make a clean start and you have to search on google where does the configuration files are, etc....

**Comment by bpasero** [comment]
I suggest to use `--user-data-dir` and or `--portable` options for this. Allowing to delete the VSCode data dir is dangerous as you might have unsaved files in there.

**Comment by kraistt** [comment]
Yes, but having to use a flag from terminal is kinda quirky from a UX perspective; fwiw is not just allowing to hot delete the files. It should be something more safe ofc.

Maybe I explained it wrong since I don't know exactly what files matter for user configuration, maybe an option in the command palette to clean the user data dir? Right now at least to me, it feels weird when I want to clean VSCode (maybe I installed too many extension, maybe I'm paranoid of performance degrading due to a whole lot of extensions manipulation) I end up googling for "clean vscode uninstall" and end up digging posts in stackoverflow, etc, etc...
