### ISSUE TITLE
additional empty line shown at end of file

### ISSUE THREAD

**Issue by christian-rauch** [microsoft/vscode#98749]
- VSCode Version: 1.45.1 (snap package)
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. download [test.txt](https://github.com/microsoft/vscode/files/4697229/test.txt)
2. check line numbers with `wc -l test.txt` -> `5 test.txt`
3. open via `code test.txt` and observe that 6 lines are shown

File in a "normal" text editor:
![test_gedit](https://user-images.githubusercontent.com/8226248/83172503-984d3700-a10f-11ea-9942-44975033861d.png)

File in code:
![test_code](https://user-images.githubusercontent.com/8226248/83172530-a307cc00-a10f-11ea-80fa-5713d6607b3f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by spahnke** [comment]
The file has two newline characters at the end so it makes sense that a 6th line is rendered. You can see those characters by executing the following on the terminal:
```
hexdump test.txt | grep 0a
0000000 6c 69 6e 65 31 0a 6c 69 6e 65 32 0a 6c 69 6e 65
0000010 33 0a 6c 69 6e 65 34 20 2e 2e 2e 20 61 6e 64 20
0000030 6c 6c 20 62 65 20 65 6d 70 74 79 0a 0a
```

Moreover, `wc -l` does not count visual lines, but the number of newline characters, of which there are five. If you run the following you can create a file that has one visual line, but `wc -l` returns 0 because there simply are no newline characters present:
```
echo -n "abc" > abc.txt
```
```
wc -l abc.txt          
       0 abc.txt
```

**Comment by egamma** [comment]
Thanks for the analysis @spahnke.
