### ISSUE TITLE
Links to Regular Expression flavor syntax

### ISSUE THREAD

**Issue by Jared-Dev** [microsoft/vscode#98748]
https://code.visualstudio.com/docs/editor/codebasics#_search-across-files

I don't use regular expressions enough when searching for the info to be kept fresh in my mind and it is consistently a chore to figure out which flavor of regex I should be using. 

Could the docs (and ideally somewhere in the VSC ui) get a link added to the regex syntax that is supported?

**Comment by roblourens** [comment]
I do have this description in the wiki here: https://github.com/microsoft/vscode/wiki/Search-Issues#notes-on-regular-expression-support

I added this recently and haven't wanted to add it to the docs quite yet since I think it's a confusing description. But it should help if you are confused by what is supported.
