### ISSUE TITLE
Provide Intellisense profiling to determine what is causing super slow intellisense

### ISSUE THREAD

**Issue by mohdyusuf** [microsoft/vscode#98754]
First of, I think Intellisense is AMAZING (when it works at full capacity). I have watched to many Vscode intellisense video sessions and it is funny that some folks there were saying the same thing, it is amazing at times, but many times it is just way to slow to response and disrupt the flow more often that it helps.

It is not the fault of developers though, every user has diff unique workspace environment, so, it is hard to tackle every single possibilities.

It would be nice if developers could provide:
1. Intellisense profiling - to allow users to determine what's the actual issue hogging their setup?
    For example, in my environment, there are just a BUNCH of big files (let's not talk about why that is, we wont finish this discussion), after trimming some of those files by files.exclude, it improved the general performance, but Intellisense is still painful, works at times, most times just "Updating Intellisense..." and never really seen to get to a point when things are smooth. Majority of the time, i cant even traverse (CTRL+click - Eclipse keybinding) to static functions local to the same C file. 

2. Intellisense performance analysis tips and tricks. Maybe Intellisense can analyze the workspace and see what is hogging the performance - suggest changes based on best practices. Say, check if cache size is enough, or being on HDD or network storage or something that for sure gonna be slow. I think devs surely know the best operating conditions for this.

**Comment by jrieken** [comment]
There is no simple answer for this because often IntelliSense is computed in a separate process of which we also don't know how to analyse this. Still, you can use logging to see what extension took how long

1. F1 > Log Level > Trace
1. View > Output > Log (extension host)
1. It will print times (quite verbose) of all extension logic 

Alternatively, esp when the IntelliSense computation happens inside the extension host process, you can CPU profile that. 

1. F1 > Show Running Extensions
1. Press the round dot button titles "Start Extension Host Profile"
1. Reproduce slowness
1. Stop profiling, share the profile with out

Then, last but not least, it always best to share a full repro sample that allows us to extension developers to experience slow behaviour.
