### ISSUE TITLE
Move "All Extensions are up to date" popup to toast system

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vscode#98761]
Currently when you check for extension updates, a popup appears if none could be found, when updates are found, it uses the toast notification system to tell them about it.

![image](https://user-images.githubusercontent.com/75278/83195040-e0814f00-a139-11ea-9f02-99ca4e56a1ae.png)

I would suggest moving the "No updates available" popup to the toast system as well, for consistency and also to not steal focus.

**Comment by sandy081** [comment]
> it uses the toast notification system to tell them about it.

Can you please show a screenshot of what you mean by this?

**Comment by Stanzilla** [comment]
Sure, this one 
![image](https://user-images.githubusercontent.com/75278/83533024-577a6700-a4ef-11ea-9f94-d47bb2f73b93.png)

**Comment by isidorn** [comment]
Adding verified since this behaves as the user suggested.
However I think this is not aligned with how the Check for Updates in VS Code behaves. That we use a modal dialog to notify the user there are no updates.
So in this particular case I think a modal dialog is a better approach.
Though will not reopen, just sharing my thoughts.

**Comment by sandy081** [comment]
Yeah this was discussed and went with simple toast as user suggested as the other extensions related notifications are using prompts. 

Again no hard opinions here.
