### ISSUE TITLE
can not insert ' SPACE' key

### ISSUE THREAD

**Issue by LYZ0106** [Microsoft/vscode#9877]
- VSCode Version: Code 1.3.1 (e6b4afa53e9c0f54edef1673de9001e9f0f547ae, 2016-07-12T13:35:06.227Z)
- OS Version: Windows_NT ia32 10.0.10586

Steps to Reproduce:

1.var CommentForm = React.createClass({
  getInitialState: function () {
    return { author: '', text: '' }
  },
  handleAuthorChange: function (e) {
    this.setState({ author: e.target.value })
  },
  handleTextChange: function (e) {
    this.setState({ text: e.target.value })
  },
  handleSubmit: function (e) {
    e.preventDefault();
  var vrauthor = this.state.author.trim();
var     ***************here**********************/*can not insert ' SPACE' key*/**************/*and sometime can't use  'ctrl+Z' */

  },
  render: function () {
    return (
      <form className='commentForm'>
        <input
          type='text'
          placeholder='请输入你的名字'
          value={this.state.author}
          onChange={this.handleAuthorChange}
          />
        <input
          type='text'
          placeholder='评论内容'
          value={this.state.text}
          onChange={this.handleTextChange}
          />
        <input type='submit' value='post' />
      </form>
    )
  }
})
2.

**Comment by kieferrm** [comment]
@LYZ0106 can you pls provide concrete steps to reproduce the problem so that we don't have to guess. 

1. Please provide the concrete source code that shows the problem. In the above what is the file extensions? How is the project set up?
1. Do you have any react related extensions installed? If yes, do you see the same problem when you disable them (launch vscode with the `--disable-extensions` command line argument).
1. Do you have enabled `editor.formatOnType` in your workspace or user settings?

**Comment by kieferrm** [comment]
No additional info. Closing.
