### ISSUE TITLE
live server

### ISSUE THREAD

**Issue by rocks4uankit** [microsoft/vscode#98802]
Issue Type: <b>Bug</b>

when i click on live serve in mac it opens parallel desktop(windows).
error shows in parallel desktop chrome not in mac's chrome.
cant execute my code
this happened after updating vs code

VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:07:18.473Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 2|
|Memory (System)|4.00GB (0.80GB free)|
|Process Argv|-psn_0_307275|
|Screen Reader|no|
|VM|29%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
LiveServer|rit|5.6.1

</details>

**Comment by misolori** [comment]
Please file an issue with the [Live Server](https://github.com/ritwickdey/vscode-live-server/issues) extension. You might have an issue where your default browser on your mac is set to the one that is from Parallels, which is why it's causing Parallels to open.

**Comment by rocks4uankit** [comment]
The issue is not with extension tried other( live server preview) extension still same issue.
before updating vs code i never had issue.
can u suggest some steps to follow to file issue with live server extension but i dont think issue is with them

**Comment by misolori** [comment]
As I said, this is likely an issue with your default browser selection on your Mac. 

This might be harder to decipher since it depends on what file you're trying to preview. But you can try going to an HTML file in Finder and right-click and choose "Get Info". What do you see in the "Open with" section?

![image](https://user-images.githubusercontent.com/35271042/83780977-bef4fb80-a642-11ea-9187-56a852deaeea.png)

If you see a browser from Parallels then you need to change the dropdown to something else and select "Change All". If this is the case then this not a VS Code issue but a OS issue.

**Comment by rocks4uankit** [comment]
went to finder and" get info" 
open with google chrome default app got this

**Comment by rocks4uankit** [comment]
issue solved
went to extension settings
live server >settings: customer browser- null
