### ISSUE TITLE
Dowloading/Installing Extensions takes almost forever

### ISSUE THREAD

**Issue by UltraBlackLinux** [microsoft/vscode#98814]
- VSCode Version: 1.44.2
- OS Version: Manjaro 5.6.12-1

Steps to Reproduce:
I dont quite know, yesterday it worked fine... I also have this error the second time. The last time it was years ago, and I dont know how I fixed it. Extensions can be installed via terminal w/o issues

Does this issue occur when all extensions are disabled?: Yes

**Comment by UltraBlackLinux** [comment]
(so many edits oof)

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by UltraBlackLinux** [comment]
1. I dont use a dns/proxy
2. I think I cant reproduce it atm - its gone again, idk when itll come back
3. Ill follow those instructions when Im facing the error again.

**Comment by sandy081** [comment]
Thanks, please reopen it with required info when you see it again.
