### ISSUE TITLE
Review Preferences Sync UX

### ISSUE THREAD

**Issue by texastoland** [microsoft/vscode#98820]
- https://github.com/microsoft/vscode/issues/93960#issuecomment-626768781: The menu item's label `Preferences Sync is On` looks like a toggle instead of opening a navigator. `Preferences Sync (On)...` seems straightforward. 
- https://github.com/microsoft/vscode/issues/93960#issuecomment-626563549: The menu doesn't access the sidebar which seems like a prominent use case. It's hidden in the command palette instead. None of the entries sound like `Focus on Preferences Sync View`.
- https://github.com/microsoft/vscode/issues/97443#issuecomment-636056967: The cloud icon is subtle enough I couldn't find it. I understand why it's on the folder but kept looking at the file. I expected a context menu on the file itself.
- There's no revert button in the diff view either.
- The cloud icon didn't signify [restoring](https://www.iconfinder.com/icons/1507846/backup_restore_time_icon) to me. I kept trying the refresh button instead. Perhaps the refresh icon could be repurposed and its functionality moved to the top of the sidebar or even the command palette.
- The `Download...` label confused me instead of `Restore` (no `...` because it doesn't open a submenu).

**Comment by sandy081** [comment]
> The menu doesn't access the sidebar which seems like a prominent use case. It's hidden in the command palette instead. None of the entries sound like Focus on Preferences Sync View.

I do not think this is a prominent use case. This is for administering or troubleshooting which is secondary and hence it is made accessible only through Command pallette.

> Cloud icon / Download action / Restore state

I appreciate your feedback about download action that is to restore the state but since it is a brand new thing so I would wait and get more feedback before doing any changes over there

> The menu item's label Preferences Sync is On looks like a toggle instead of opening a navigator. Preferences Sync (On)... seems straightforward.

I do not think this looks like a toggle button as there is no check mark associated to it. It is just an entry as other entries like `Settings` etc., which opens UI or actions related to the feature.

Since there is no action to be taken, I would be closing this. Thanks for the feedback.

**Comment by texastoland** [comment]
It's genuinely hard to use on multiple points. I don't understand how there are no action items. I identified easily implementable improvements. I literally couldn't find your new button after seeing your screenshot. To argue a single point, where else in the entire UI do tree items not respond to context clicks?

**Comment by sandy081** [comment]
Context clicks are less discoverable than primary actions.

**Comment by texastoland** [comment]
But you're postulations are incorrect. I'm the user and couldn't figure out you're implementation. You're correct but they're helpful when you can't figure out a UI. I really want another pair of UX eyes on this.

**Comment by misolori** [comment]
> The menu item's label Preferences Sync is On looks like a toggle instead of opening a navigator. Preferences Sync (On)... seems straightforward.

We modeled this after how browsers use the same terminology. For example, Chrome uses `Sync is on` and it links to their sync management (which is what we're doing here). `Preferences Sync (On)` is also a good alternative.



> The menu doesn't access the sidebar which seems like a prominent use case. It's hidden in the command palette instead. None of the entries sound like Focus on Preferences Sync View.

I do think we should try to bubble this up in the Sync menu. We could have an item at the bottom (maybe it's a new section) that says `Preferences Sync: Advanced`, or something like that, to at least increase discoverability of this and other commands.

 > The cloud icon is subtle enough I couldn't find it. I understand why it's on the folder but kept looking at the file. I expected a context menu on the file itself.

I also agree with this, I would've expected a context menu on the `settings.json` and the parent item as well.

> There's no revert button in the diff view either.

This seems like an oversight, we should add this.

> The cloud icon didn't signify restoring to me. I kept trying the refresh button instead. Perhaps the refresh icon could be repurposed and its functionality moved to the top of the sidebar or even the command palette.

I do think we can find a better icon (possibly the `history` icon), however I don't think having it at the top makes sense as you need to choose what backup you want to restore to. It's much easier to go through the list and choose the one to backup to.

> The Download... label confused me instead of Restore (no ... because it doesn't open a submenu).

+1

cc @Tyriar in case you have any additional thoughts

**Comment by texastoland** [comment]
Sweet! I really appreciate @sandy081's implementation and @misolori's feedback. As someone OCD about their dotfiles I love the functionality of switching between past configurations. I just want it to be obvious to everyone how useful the feature really is.

**Comment by sandy081** [comment]
@texastoland Its good that you asked for third person's perspective.

> We modeled this after how browsers use the same terminology. For example, Chrome uses Sync is on and it links to their sync management (which is what we're doing here). Preferences Sync (On) is also a good alternative.

Preferences Sync (On) might not be symmetric as we do not have Preferences Sync (Off). I would rather go with `Preferences Sync is On` or just `Preferences Sync` and prefer former as it is being used by other browsers too. Other suggestions are welcome.

> I do think we should try to bubble this up in the Sync menu. We could have an item at the bottom (maybe it's a new section) that says Preferences Sync: Advanced, or something like that, to at least increase discoverability of this and other commands.

I see the point of discoverability but it is a trouble shooting feature (which is much advanced) and hence it is added only to command pallette. Let me know if everyone feel that this has to be a primary action, I can add it 👍 

> I also agree with this, I would've expected a context menu on the settings.json and the parent item as well.

I do not understand why we need same action as primary and also as secondary. Do we follow this anywhere else? 

BTW this action was added only to parent because the parent can contain more files for example, different snippets files and in this case adding a download/revert action is specific to that file which has different semantics . It would be same if we add more settings files in future (say platform specific settings). Hence I am reluctant to add an action there.

> There's no revert button in the diff view either.

Agreed that this is good to have - Filed separate request for this https://github.com/microsoft/vscode/issues/99340

> I do think we can find a better icon (possibly the history icon), however I don't think having it at the top makes sense as you need to choose what backup you want to restore to. It's much easier to go through the list and choose the one to backup to.

Not sure history icon is better as it does not mean that it is downloading and replacing. I chose download as it is closer to what we are doing here - downloading the state and replacing. I am open to replace with a better icon.

> The Download... label confused me instead of Restore (no ... because it doesn't open a submenu).

Agreed. Fixed.

Reopening to continue the discussion.

**Comment by misolori** [comment]
> I do not understand why we need same action as primary and also as secondary. Do we follow this anywhere else?

It's common to go to an individual item to perform a single action, just like in SCM. You can make an action on a single one (stage one) or the entire parent (stage all). So I wouldn't say it's the same action since there could be additional files in other views. So you can either restore a single file or the entire folder. That's my expected UX, that may not be what happens in the background. 

> Not sure history icon is better as it does not mean that it is downloading and replacing. I chose download as it is closer to what we are doing here - downloading the state and replacing. I am open to replace with a better icon.

I don't think users think of this as downloading but rather restoring from a backup. That's the terminology used in backups and this is called "Backups". As I said earlier, the user doesn't see this as "downloading" even if that is what is happening in the background.

Btw, in this commit (https://github.com/microsoft/vscode/commit/5b068c1de96ddd0172c6956cb3b0bdce0b2af0c8) you changed the terminology to "Revert", I think you meant "Restore"?

**Comment by misolori** [comment]
Also, why do we show the a line item for the machine that has no actions? This seems like a decoration/label that can be added to the end of the file

![image](https://user-images.githubusercontent.com/35271042/83780602-3ece9600-a642-11ea-80fc-3427926ca83c.png)

**Comment by sandy081** [comment]
> It's common to go to an individual item to perform a single action, just like in SCM. You can make an action on a single one (stage one) or the entire parent (stage all). So I wouldn't say it's the same action since there could be additional files in other views. So you can either restore a single file or the entire folder. That's my expected UX, that may not be what happens in the background.

Convinced - Filed https://github.com/microsoft/vscode/issues/99401

Regarding icon - I agreed that `cloud-download` icon is not the best, but felt better than `history` icon. Would be happy to get a better icon here.

> Btw, in this commit (5b068c1) you changed the terminology to "Revert", I think you meant "Restore"?

Sorry. Changed to `Restore`.

> Also, why do we show the a line item for the machine that has no actions? This seems like a decoration/label that can be added to the end of the file

This is to see from which machine this request is coming from without opening the file.

**Comment by sandy081** [comment]
Closing this as there are issues tracking individual requests.
