### ISSUE TITLE
Extensions doesn't load in vscode when installed from snap on Ubuntu 20.04

### ISSUE THREAD

**Issue by muhammad-ahsan** [microsoft/vscode#98972]
- VSCode Version:
1.45.1
- OS Version:
Ubuntu 20.04

Steps to Reproduce:

1.Install vscode using snap e.g. "sudo snap install --classic code"  
2.Click on the extensions button in left sidebar of IDE
3.Progress bar keeps loading but nothing appears.

Note: When you install using debian package, same version of vscode 1.45.1, everything work smoothly.   

Does this issue occur when all extensions are disabled?: Yes/No

Yes

Note: Installing the same version using .deb works perfectly fine. 
![Screenshot from 2020-06-01 20-17-19](https://user-images.githubusercontent.com/1093769/83440453-45dc8500-a445-11ea-8100-f6c06f9e9f38.png)

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by java4africa** [comment]
I can reproduce this. I have https_proxy and https_proxy env set. (I also tried explicitly setting the proxy in Settings). No user/password auth is set on the proxy.
From the debug Console:
vscodeexperiments.azureedge.net/experiments/vscode-experiments.json:1 Failed to load resource: net::ERR_NO_SUPPORTED_PROXIES

**Comment by chrmarti** [comment]
@java4africa If your proxy values end with a `/`, try to remove that and retry. (This is fixed in Insiders.)

**Comment by java4africa** [comment]
Yes that fixes the issue. Many thanks

**Comment by muhammad-ahsan** [comment]
thank you all.
