### ISSUE TITLE
Problems with the "1" badge on the "Manage" gear icon

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#99020]
VS Code Insiders:

- I was always seeing:
  <img width="129" alt="2020-06-02_09-31-46" src="https://user-images.githubusercontent.com/1898161/83492838-2a5c9300-a4b4-11ea-92f5-0e6eca8811ca.png">
  which made me assume that a VS Code update is available (which wasn't)
- opening the menu showed this:
  <img width="295" alt="2020-06-02_09-31-05" src="https://user-images.githubusercontent.com/1898161/83492952-5aa43180-a4b4-11ea-976c-28d425bbbdae.png">
 IMO the "(1)" at the end of "...Preferences" is hard to identify as the reason for the "1" in the gear icon.
- selecting the item from the menu opened a Quickpick which showed that I'm "signed in as weinand" (and then there were two other entries: one for MS and one for github)
  Since there was no indication for an error, I dismissed the Quickpick but the "1" on the gear icon stayed. Only when I selected the "signed in as weinand" in the Quickpick I could remove the "1" on the gear icon.

There are a few things we should improve:
- a "problem 1" should look different than an "update 1" on the gear icon.
- a space is missing in the "...Preferences(1)" menu action between the "...Preferences" and the "(1)".
- instead of only showing a "(1)" I suggest to show "(1 problem)" to make it stand out.
- in the Quickpick nothing indicated that there is an issue.
- why do I have to run the "signed in as weinand" action to fix the problem? The wording suggested that I'm already signed in. Should it be named "sign in as weinand"?

**Comment by sandy081** [comment]
I see there are two issues you are seeing.

> selecting the item from the menu opened a Quickpick which showed that I'm "signed in as weinand" (and then there were two other entries: one for MS and one for github)
Since there was no indication for an error, I dismissed the Quickpick but the "1" on the gear icon stayed. Only when I selected the "signed in as weinand" in the Quickpick I could remove the "1" on the gear icon.

I am wondering why you are seeing this notification if you are already signed in. Can you please confirm if you were using the selected account for sync before? Ideally it shall show only if the account you are using for sync is not available.

I do not think these are problems, they are notifications for the user to take some action just like update. 

@misolori FYI

**Comment by misolori** [comment]
The `(1)` is the same pattern we use for updates so this is consistent there. It does sound like there are some UX issues with clicking on this when there are errors and the quick pick does not show any indication of an error. We should fix that.

**Comment by weinand** [comment]
The consistency was actually my problem: the "1" badge always made me "Check for Updates...", which resulted in "no updates" because the "1" actually meant something else.
And because the "(1)" in "Sign in to Sync Preferences(1)" does not really stand out in the menu, I was not seeing it.

**Comment by sandy081** [comment]
I think the action `Sign in to Sync Preferences` shall be moved to `Accounts` dropdown because we want all soft sign in actions to be there. Filed a separate issue for this - https://github.com/microsoft/vscode/issues/99227

This leaves following notifications for the user under gear menu
- VS Code Update
- Sync Conflicts

**Comment by misolori** [comment]
I think because we only ever used the `(1)` badge for updates is why it feels inconsistent. Since this is a new pattern where we are adding new items under the gear menu, I think this is something that may take some time to get used to.

We could move the `(1)` to the front of the string so it reads `(1) Sign in to Preferences Sync`. This would also affect the updates item.

**Comment by weinand** [comment]
IMO it would help if we would make the "(1)" more longer and explicit, e.g.
Check for updates **(1 available)**
or
Sign in to Sync Preferences **(1  action)**

**Comment by misolori** [comment]
Haven't seen additional feedback related to this so closing this out
