### ISSUE TITLE
Switching to simple full screen produces a jump

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#99039]
macOS catalina, VS Code insiders

Have 	`"window.nativeFullScreen": false`
Turn on full screen. Notice how the whole top part of window jumps

![recording](https://user-images.githubusercontent.com/1926584/83505993-da3afc00-a4c6-11ea-9669-4647b639fa71.gif)

**Comment by bpasero** [comment]
@isidorn since you are using simple fullscreen for a long time, is this a recent regression?

**Comment by isidorn** [comment]
@bpasero for some strange reason I was not using it for a couple of weeks. Before that I could not reproduce.
I also can not reproduce with VS Code stable.

**Comment by bpasero** [comment]
Ok, maybe @deepak1556 has an idea if an Electron update might have caused this.

**Comment by bpasero** [comment]
@deepak1556 the underlying issue seems to be the same as https://github.com/microsoft/vscode/issues/98844, there is a `display-metrics-changed` event when going fullscreen that triggers some logic here:

https://github.com/microsoft/vscode/blob/595d2b9b916d063aadfc2c1a8c8f6df5b45572a8/src/vs/code/electron-main/window.ts#L434

I think it is time to revisit support for simple fullscreen. You already indicated it will be hard to support this in the future? Should we take it out?

**Comment by isidorn** [comment]
😭

**Comment by bpasero** [comment]
Actually nevermind, found a fix. `display-metrics-changed` carries information why it was triggered and if I know detect `workArea`, I will not do anything as this just means e.g. the dock got hidden, but the bounds are otherwise the same.
