### ISSUE TITLE
GitHub integration breaks private key workflow

### ISSUE THREAD

**Issue by Lewiscowles1986** [microsoft/vscode#99047]
- VSCode Version: 1.45.1
- OS Version: Windows 10 64-bit all updates installed

Steps to Reproduce:

1. Use vs code
2. Download update because it's nagware that wont shut up until you do
3. Attempt to use built-in terminal to perform git actions because the GUI is not fit for more than staging files
4. Be greeted with an interception dialogue that forces me to use my password instead of using my private key

Does this issue occur when all extensions are disabled?: I don't know

I'm furious

* forcing someone to provide a username and password when they've gone to the bother of setting up public/private key-pair which works in git bash and other terminals degrades security, can cause alarm.
* How to opt out
* Can this be opt out by default, with an opt-in plugin for people who cannot work out how to use Git

**Comment by joaomoreno** [comment]
> Download update because it's nagware that wont shut up until you do

You can disable updates with the `update.mode` setting.

> Be greeted with an interception dialogue that forces me to use my password instead of using my private key

You can disable git terminal authentication with the `git.terminalAuthentication` setting.

> forcing someone to provide a username and password when they've gone to the bother of setting up public/private key-pair which works in git bash and other terminals degrades security, can cause alarm.

This is very strange since you seem to be mixing up two things.  VS Code will only intercept HTTPS authentication. If you have SSH setup with private/public key auth it won't mess with that (that's my daily setup actually). So... is it possible that you're seeing this in an HTTPS repo when usually you use SSH repos?

**Comment by Lewiscowles1986** [comment]
@joaomoreno I don't think so, but I'll check my git remotes in-case the interception is due to me cloning poorly

Thanks for the other info, and sorry I was a bit prickly

**Comment by Lewiscowles1986** [comment]
😊 well that is embarrassing. The repo's I was experiencing this with were `https` origin and not `git@github.com:{repo}` origin

`git remote get-url origin` showed me this. I think this can be closed and again. Sorry for pricklyness
