### ISSUE TITLE
Notebook: weird restore from dirty

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#99056]
Steps to Reproduce:

1. create a github issue notebook and leave it dirty
2. reload window
3. create a second github issue notebook and leave it dirty
4. reload window

=> 🐛  3 notebooks open?

![image](https://user-images.githubusercontent.com/900690/83511711-5df8e680-a4cf-11ea-8535-6129ed333a2f.png)

**Comment by rebornix** [comment]
Good catch, another case that the assumptions in `EditorInput` and working copy conflict with new multi editor view types for a single resource. For short, the backupresolver assumes that `WorkingCopy.resource === EditorInput.resource` while in both Notebook and Custom Editor, they are different.

Since it also applies to CustomEditor so cc @mjbvz , here is what happens based on my understanding:

* User click on a file resource, custom/notebook editor tries to open it
  * the resource for the `NotebookEditorInput` or `CustomEditorInput` is `file:///`
  * we will register working copy for the notebook input. However, the working copy resource can't be `file:///` scheme as we allow users to open the same resource in Text Editor, which will also register working copy with `file:///` resource: conflict exception. Instead, we use a different resource for working copy, for example, in Notebook we use `vscode-notebook:///` and in Custom Editor we use `vscode-custom-editor:///`.
  * As we don't know how the notebook document is saved to disk (can be JSON, markdown, etc), so it makes sense to have different working copy for different editor view types.
* When there is a single dirty notebook document, when users reload the window
  * A `NotebookEditorInput` is deserialized
  * It's the active editor, `NotebookEditorInput.resolve()` is invoked. It will load backup data from backup service, remove the backup, make the current editor dirty. Done.
* When there are two dirty notebook documents in the same group, reload the window
  * Two `NotebookEditorInput` are deserialized, say the active one is A, and the inactive one is B
  * A is `resolved()` and loaded from backup
  * `backuprestorer` kicks in, it find an unresolved backup `vscode-notebook:///` resource for B.
  * It then scans all editors to see if there is any editor can handle this backup, the assumption it makes is `isEqual(editor.resource, resource)`
https://github.com/microsoft/vscode/blob/37d90fbfc8a848f96e2985775288252dce2b0d11/src/vs/workbench/contrib/backup/common/backupRestorer.ts#L72-L80
  * however, the resource uri for the document is `file:///` while the backup/workingCopy is `vscode-notebook:///`, they don't match.


The no brainer fix is adding `IEditorInput.canHandleBackup(resource: URI): boolean` but maybe there are much better solutions @bpasero ?

**Comment by rebornix** [comment]
We are not shipping this stable so move it to June.

**Comment by bpasero** [comment]
My understanding is that @mjbvz added code to properly restore backups for custom editors, maybe we can do the same for Notebooks. I suggest you two get together. 

Specifically:

https://github.com/microsoft/vscode/blob/cde20069b3b16256b0fd0def711c35329a84c02d/src/vs/workbench/contrib/backup/common/backupRestorer.ts#L100-L104
