### ISSUE TITLE
Pinned tabs: active border not showing when tabs border enabled

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#99084]
Testing: https://github.com/microsoft/vscode/issues/98019

It would be great to see the active tab border on active pinned tabs.

Since they have none, the tab icon even jumps up and down by one 1px as it is pinned/unpinned:

![recording (9)](https://user-images.githubusercontent.com/22350/83524195-8ab6f900-a4e3-11ea-95e1-b3cc7685ecad.gif)

**Comment by bpasero** [comment]
@joaomoreno not sure how to reproduce, the setting `tab.activeBorder` works for me, but maybe you enabled other settings that make this fail.

**Comment by joaomoreno** [comment]
I was able to repro on a new user data dir and extensions folder:

1. Start Code afresh
2. Install Github Sharp, which has a `tab.activeBorder` color
3. Pin a tab, the color goes away

**Comment by bpasero** [comment]
Only happens when both `tab.activeBorder` and `editorGroupHeader.tabsBorder` are defined. For sticky tabs, `editorGroupHeader.tabsBorder` wins over `tab.activeBorder`.

This is very hard to fix due to the use of `position: sticky` and `z-index` in tabs. There are a couple of rules:
* scrollbar: z-index 3
* sticky tabs: z-index 1 (to be above other tabs)
* bottom border on (all) tabs: z-index 5
* border top/bottom on single tab: z-index 6 to be above the border on tabs

Position sticky seems to have an impact on this and of course z-index also inherit down, so that a lower z-index will not allow a child to have a higher z-index.

The solutions I looked at all brought their own set of issues:
* scrollbar not visible over sticky tabs
* tabs border not visible over active sticky tab
