### ISSUE TITLE
Intellisense UI javascript function signatures gets cut off

### ISSUE THREAD

**Issue by rickmed** [Microsoft/vscode#9909]
- VSCode Version: 1.3.1
- OS Version: win 10 x64

Steps to Reproduce:
1. On a js file:

![image](https://cloud.githubusercontent.com/assets/7104786/17218216/051d07c6-54b5-11e6-9f06-bcf01e8b4c16.png)

The function signature gets cut off. Shouldn't the box size adapt to see all the function signature?

Also, shouldn't the comment above the function definition be added to the intellisense box? Or is it managed with an additional extension?

thanks

**Comment by aeschli** [comment]
To see the full signature and description, press Ctrl+Space a second time.

**Comment by rickmed** [comment]
@aeschli does not work. Also tried with a different keybiding (to test for colliding keybindings). The command does not seem to work.

**Comment by aeschli** [comment]
@rickmed Oh, I see, this only works if there is a doc comment description.
@joaomoreno I think it would be better to also allow the second Ctrl+Space if there is a detail information (like the signature)

**Comment by stevencl** [comment]
If we only showed the signature for the highlighted item in a tooltip, the user wouldn't need to press Ctrl+Space to get more details since we could show the full signature for the highlighted item:

![snip_20160802145546](https://cloud.githubusercontent.com/assets/1704059/17331059/3bb2cd1a-58c1-11e6-8313-04c26bf1cf22.png)

**Comment by joaomoreno** [comment]
Leaving this to each completion item provider to fix.
