### ISSUE TITLE
Remember anchor position across editors

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#99094]
Testing #98087

The cursor anchor position is cancelled very easily. It is gone after switching editors, or when using the anchor with `Select from anchor to cursor`

IMO it would be much more useful if the anchor is kept longer. I don't see any harm to store/restore when switching editors and to  keep it unless a new anchor is set.

**Comment by isidorn** [comment]
@aeschli thanks for feedback, makes perfect sense. Adding label bug so I look into it tomorrow :)

**Comment by isidorn** [comment]
@aeschli I have looked a bit deeper in this and the solution would be to set decorations on the model, not on the editor (how we do it now). Since if we put it on the editor, the editor will get rid of them as soon as a new model is opened.
If we put them on the model then they will get preserved whenever that file is opened in any editor, however for that we would have to keep a record on our side of all the decorations set per uri, so we would know exactly if that file has a decoration set or not.
Will make the code more cumbersome.

So for now will not tackle this, code pointer is somebody is intersted
https://github.com/microsoft/vscode/blob/04c60585ab72bf42943ea0dbe250376057f9a385/src/vs/editor/contrib/anchorSelect/anchorSelect.ts#L23

**Comment by isidorn** [comment]
Did not get more feedback regarding this.
While I think it makes sense, I prefer not to overcomplicate the Controller thus for now closing as will not fix.
