### ISSUE TITLE
Settings sync - Indicate when sync is turned off in the synched machines view

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#99102]
Testing #98962

When sync is turned off on a machine because of an error like (too many requests), the machine is still shown in synced machines view.

**Comment by sandy081** [comment]
Currently when sync is turned off on a machine we are removing the machine. 

Can you please elaborate the use case behind the feature you are suggesting?

**Comment by lszomoru** [comment]
Is that the case also when the sync is turned off due to excessive calls to the service?

**Comment by sandy081** [comment]
I am not clearing the machine when it is turned off due to an error like this, because it is not done by user. But agreed that showing the machine as syncing in the view is not correct in this case.

Updated summary and description accordingly.

**Comment by sandy081** [comment]
Disabling the machine when sync is turned off due to excessive calls is tricky because disabling the machine requires making a request to server which can be failed due to the same error.

Hence in this case I disable the machine eventually meaning, I postpone this after 10 mins hoping that rate limit time is surpassed and requests go through. I do not retry if it fails. This is the best that can be done in this case.

To verify, when sync is turned off due to excessive calls wait for 10 mins or a bit more and make sure machine is disabled. If you turn on sync mean while disabling is not done.

**Comment by lszomoru** [comment]
@sandy081, could we explore a better solution? What is the endpoint that gets called when a machine needs to be disabled? Could we exempt that endpoint from the rate limiting mechanism so that in case sync needs to be turned off, we know that we can actually do that?  

//cc @Tyriar

**Comment by sandy081** [comment]
I am open to it.

@Tyriar Can you please support this on server?

**Comment by Tyriar** [comment]
I feel like the current solution with the delay is good enough, splitting out and rate limiting disable separately (because we still need to rate limit it) seems overkill to me. Rate limiting should essentially never happen if everything is working correctly, so more work in this area just give slightly faster feedback in the synced machines views (which is rarely used) is complicating things  where only a handful of people would ever actually get something out of this.

**Comment by sandy081** [comment]
Actually I do agree with @Tyriar that it is a bit of overkill to support this.

@lszomoru Let me know if it makes sense to you?

**Comment by lszomoru** [comment]
Please correct me if I am wrong but based on my understanding the current implementation only works if the rate limiting is caused by the users's manual actions (ex: invoking the `sync now` command). If the rate limiting is caused by a client side bug, waiting will not help as the client will continuously be throttled due to the bug. I would still like to push for a solution to reliably turn off sync in order to protect the service from an abusive client machine.

**Comment by sandy081** [comment]
Current solution also works for client side throttling.

If client hits rate limit on the client, client disable sync immediately and after 10 mins (which relaxes client side throttling) client also disables the machine on server.

**Comment by sandy081** [comment]
@lszomoru closing this as it seems we do not want to exclude some requests for rate limit
