### ISSUE TITLE
List of targets should be positioned close to targets

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#99124]
Testing #97801

When choosing the Step into targets command it looks like the list of targets is shown on the same line that the user right clicked on. This can end up being a bit confusing especially if the user clicks far away from the line of code that is currently stopped at. For example:

![image](https://user-images.githubusercontent.com/1704059/83540232-edae8d00-a4ef-11ea-9199-70e31efee37e.png)

I think I was expecting a fly out menu rather than a separate list.

**Comment by isidorn** [comment]
Yeah I agree this is a bit strange. The flyout menu would be different but we do a seperate menu due to the implemenation, in more details we fetch the targets in an async way and only want to do it lazily once a user executes the command. If we were to use a submenu we would need to know the targets in advance, thus we would not do it lazily.

So I will not change the menu to menu design.
However for the location, we can change to always show the second menu close to the target. Downside of this is that the first and second menu can be far apart.
Though assigning to May to investigate.

**Comment by sbatten** [comment]
Having the second menu change position would have helped as a first time user to understand what I was doing, but this would be really strange if the targets are scrolled out of view.
