### ISSUE TITLE
Editor selection is not unset while navigating from Problems view

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#99136]
Testing #98821

- Have following issue notebook

```
[{"kind":2,"language":"github-issues","value":"repo:microsoft/vscode assigne:@me label:settings","editable":true},{"kind":2,"language":"github-issues","value":"rep:microsoft/vscode assignee:@me label=1234","editable":true}]
```

- Open the notebook
- Navigate the problems in problems views using arrows
- Selection is not unset when navigating across cells. For eg: See that in the screenshot selection is set in two cells

<img width="786" alt="image" src="https://user-images.githubusercontent.com/10746682/83545566-b1832880-a4ff-11ea-8812-1e98bd9ab021.png">

**Comment by jrieken** [comment]
This is likely an issue with [`selectElement`](https://github.com/microsoft/vscode/blob/d58907bedbe7367cf57d8ab443e1782ca53e9ef7/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L717)

**Comment by rebornix** [comment]
Good catch and yet another case for composite editor. Image you have two editors side by side and each one of them has a problem

![recording (1)](https://user-images.githubusercontent.com/876920/83671206-28b0cf00-a589-11ea-82ee-6ffaa27acefb.gif)

and navigating between the problems will not unset the selection of the previous editor. The problems panel will only set new selection in an editor, thus if you are navigating problems in a single editor, the selection is always updated.

However in our scenario, we have composite editors in one notebook and those composite editors don't share selections. And also since the problems panel doesn't unset selections of previous cells, the selections are left over. The same behavior applies to Find All References, Find & Replace, etc.

**Comment by jrieken** [comment]
I have pushed a change that makes the selection color almost transparent when a cell isn't selected anymore. I think that's better than unsetting the selection of an inactive editor. Let me know what you think.

![Jun-15-2020 16-00-35](https://user-images.githubusercontent.com/1794099/84666474-687c9c80-af21-11ea-9a64-627a8539c976.gif)

**Comment by jrieken** [comment]
⬆️ fyi @misolori

**Comment by misolori** [comment]
I think this is fine for now, once we support cell background colors I'd imagine we'd move towards that to match the selection in the editor.

**Comment by jrieken** [comment]
Thanks. I'll leave it like that then
