### ISSUE TITLE
Renamed file persists after cross-file undo

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#99161]
Testing #98987

Repro:
1. Rename symbol affecting files `a.ts`, `b.ts`, `c.ts`
2. Close all open editors
3. Rename file `a.ts` to `aprime.ts` on disk
4. Undo on file `b.ts` and select undo all 3 file edits
🐛 => I am now left with `a.ts` which is in the initial state and `aprime.ts` that is in the renamed symbol state.

**Comment by alexdima** [comment]
@sbatten I see these steps run into a separate workbench feature where files deleted on disk are still kept open and get a `(deleted)` next to them. AFAICT the cross file undo works OK because the file is still in memory and the undo operation is applied (even if the file is deleted on disk):

![Kapture 2020-06-03 at 9 11 08](https://user-images.githubusercontent.com/5047891/83606687-52162e80-a57a-11ea-9628-0d4613324138.gif)

**Comment by sbatten** [comment]
in my case, I always closed all files after the f2 rename operation

**Comment by alexdima** [comment]
@sbatten I still cannot reproduce with the new steps (closing all files after the f2 rename):

![Kapture 2020-06-03 at 19 09 19](https://user-images.githubusercontent.com/5047891/83666861-dfcf3980-a5cd-11ea-936e-5e7406aa971b.gif)

**Comment by sbatten** [comment]
can no longer repro, sorry
