### ISSUE TITLE
[glob] {**/package.json,**/project.json} matches too much

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#9917]
From #6936

Version 1.4.0-insider, Commit 531a56f772fc33ec88910328b88f4dbd7ae5df43, Date 2016-07-28T16:52:53.252Z
Add this to glob.test.ts:
```typescript  
         p = '{**/package.json,**/project.json}';
         assert(glob.match(p, 'package.json'));
         assert(glob.match(p, '/package.json'));
         assert(!glob.match(p, 'xpackage.json'));
         assert(!glob.match(p, '/xpackage.json'));
```

Fails at the last assert.

**Comment by bpasero** [comment]
I fixed the case you found but this is not the full fix, it would still be possible to construct a case where the same issue happens.

Since this is very related to the glob pattern being not very efficient, I have updated https://github.com/Microsoft/vscode/issues/5438 to include this. The final pattern we come up with that is efficient should also tackle this problem (and I think I tried that initially too).
