### ISSUE TITLE
Explorer: allow to bulk cancel "file already exists" dialog

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99176]
Testing #97714

On firefox, attempting to re-upload a large directory results in a string of "A file or folder already exists do yo uwant to replace it" message with no way to cancel the operation as a whole. Cancel and X both cancel the single replace dialog, I'd expect maybe X to cancel the entire operation, or an "Abort" button.

**Comment by bpasero** [comment]
I guess we currently have no way to cancel the entire operation from the replace dialog. This is probably also true for the native upload.

**Comment by isidorn** [comment]
Yes this is also how native behaves. So we will show a dialog for each conflict. We do not allow to bulk cancel.
Since this can be handled in the Explorer, unassigning from @bpasero and renaming

I am opening this up for PRs.
Code pointer https://github.com/microsoft/vscode/blob/595d2b9b916d063aadfc2c1a8c8f6df5b45572a8/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L707

**Comment by isidorn** [comment]
Actually this issue has more details, closing as duplicate of that one 
https://github.com/microsoft/vscode/issues/99074
