### ISSUE TITLE
Confusing filter on type behavior in SCM when using tree view

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#99182]
Testing #99019

**Repo**
1. In the VS Code repo
1. modify `extensions/markdown-language-features/src/slugify.ts` plus another file in the markdown language features extension
1. Open SCM view and enable filter on type. Make sure you have tree view enabled for scm
1. Type `slug`

**Bug**
Both files are still shown

<img width="903" alt="Screen Shot 2020-06-02 at 1 50 51 PM" src="https://user-images.githubusercontent.com/12821956/83568559-14f96000-a4d8-11ea-8ffe-a0f3152e88e1.png">

If you switch back to the list view, you can see that this happens because the path matches `s` `l` `u` `g`

<img width="881" alt="Screen Shot 2020-06-02 at 1 51 17 PM" src="https://user-images.githubusercontent.com/12821956/83568616-280c3000-a4d8-11ea-958b-c77b157a9fe6.png">

There is no highlight in the tree scm view however which makes this look like a bug

**Comment by lszomoru** [comment]
Thinking about this a little more, it does not make sense to filter based on the path when in `Tree` mode. I have pushed an update so that when in `Tree` mode we only match on the file name since the parent folder(s) of the matches will be displayed automatically. In the case above, when using `Tree` mode, the `markdownExtensions.ts` file will not be matched. In `List` mode we will continue to match both on the file and folder names.

**Comment by lszomoru** [comment]
Verification steps:
1. Open the `vscode` repository
2. Make changes to the following files:
    - `extensions/markdown-language-features/src/slugify.ts`
    - `extensions/markdown-language-features/src/markdownExtensions.ts`
3. Switch to the SCM viewlet
4. Make sure that 'List' mode is enabled
5. Type `slug` and validate that both items contain matches
6. Switch to `Tree` mode
7. Validate that only the `extensions/markdown-language-features/src` folder, and the `slugify.ts` file contain matches
