### ISSUE TITLE
Web: extension host debugging (JS) does not work 

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#99222]
Steps to Reproduce:

1. macOS, Chrome
2. `npm install -g yo`
3. `npm install -g generator-code`
4. `yo code`
5. `end-js` (JS template)
6. `./resources/server/web.sh --folder /Users/bpasero/Desktop/end-js`
7. add breakpoint into the hello world command handler
8. Run
9. trigger "hello world"

=> 🐛 breakpoint not hit

**Comment by weinand** [comment]
This seems to be an issue with `js-debug`.
Turning the new JS debugger off with the setting `"debug.javascript.usePreview": false` makes it work for me.

**Comment by connor4312** [comment]
I think this may be something in core. This is what js-debug does:

 1. Get the launch request, process it like normal.
 2. Fires the custom launchVSCode DAP request. These are the arguments, they're essentially the same as node2, except it passes `--inspect-extensions` instead of `--inspect-brk-extensions` since it does not depend on the entrypoint breakpoint.

```
"{"args":[{"prefix":"--debugId=5907c81b-46dc-4309-a75c-b5568620ab0c"},{"prefix":"--inspect-extensions=38989"},{"prefix":"--extensionDevelopmentPath=","path":"C:\\Users\\Connor\\Documents\\Github\\vscode-js-debug\\demos\\extension"}],"env":{}}"
```

 3. The launch request indicates that it terminated as normal. At this point, VS Code should hand us an "attach" request. However, this does not happen; neither the DebugConfigurationProvider nor the DebugAdapterDescriptorFactory get the launch request. As a result we do not attach.

I will look around today in VS Code to see if I can see anything going obviously wrong, +isidorn

**Comment by connor4312** [comment]
Indeed, I think that is the root cause; changing the argument to inspect-brk makes it work (albeit with an incorrect break at the start). It seems that here, we look at inspect-brk, but not inspect-.

https://github.com/microsoft/vscode/blob/29b5f87288bc093c85f63d8770910fe8c03d1b59/src/vs/workbench/services/environment/browser/environmentService.ts#L268-L271

For some reason I can't debug either js-debug or node2 extension hosts running web locally so I can't validate the fix, I would appreciate it if someone could give the linked PR a shot.

**Comment by bpasero** [comment]
Running out of sources at least I still cannot hit a breakpoint. Is there any setting I need to do?

**Comment by connor4312** [comment]
Can you enable `trace: true` and share the logs here?

**Comment by JacksonKearl** [comment]
Probably doing something wrong here, but I cant seem to get extensions to work on the web. I built from distro and I was able to run the extension, but in the target window the contributed command isn't available.

**Comment by connor4312** [comment]
I was able to test by running this in distro (had to manually apply my changes locally there)

```
.\resources\server\web.bat --insiders
```

(Running that command in oss failed with

```
TypeError: Cannot read property 'alias' of undefined
    at Object.parseArgs (C:\Users\Connor\Documents\Github\vscode\out\vs\platform\environment\node\argv.js:114:19)
```)

Selfhost worked in both places as well -- since this is now in Insiders that should work for you as well

**Comment by weinand** [comment]
Does it help if you run "yarn gulp mixin-server" before starting the webui with the command 6. from above?

**Comment by JacksonKearl** [comment]
worked from oss, thanks @weinand !

**Comment by connor4312** [comment]
Ah, yep, looks like web is in a happier state today. I had `git clean -dfx`'d and re-mixin'd a few times last night with no luck, there must have been some synchronization issue between oss and distro..

**Comment by bpasero** [comment]
While I am getting this to work with a TS extension, it does not work for me with a JS extension. I generated a simple hello world extension with JS and tried to debug.

**Comment by connor4312** [comment]
@bpasero I'm unable to reproduce this with a fresh `yo code` JS sample

![](https://memes.peet.io/img/20-06-502b36b9-0960-4d40-a71b-0abd0d7bff3b.png)

It's possible that you were hitting https://github.com/MicrosoftDocs/vsonline/issues/567. We of course don't need sourcemaps for plain .js files but that _might_ be interfering with some logic. Please enable `trace: true` in your launch config -- that will let me confirm or have enough information to debug either way.

**Comment by bpasero** [comment]
@connor4312 a pre-req for this seems to be that I first had another folder opened and then switched to it. Steps:
* `./resources/server/web.sh --folder /Users/bpasero/Desktop/<some unrelated folder>`
* within web open the folder with the JS extension to debug
* start debugging

=> no breakpoint hit for me

**Comment by connor4312** [comment]
Unfortunately I'm not able to repro with those steps on my machine https://memes.peet.io/img/20-06-c2285ac6-e3a0-4533-8335-37a2422621e0.webm

Can you enable `trace: true` in your launch config and share the logs?

**Comment by bpasero** [comment]
@connor4312 so it seems to be timing related, if I invoke the action early enough the breakpoint is not hit, but if I wait a bit it seems fine.

Logs for an unsuccessful attempt: 

[vscode-debugadapter-7.json.zip](https://github.com/microsoft/vscode/files/4741489/vscode-debugadapter-7.json.zip)

**Comment by connor4312** [comment]
Okay. I also saw that in one run where I invoked it very early and missed a breakpoint. I think the attachment to the extension host is given async, perhaps just in web or maybe web is slightly slower for some reason. From the logs I see that js-debug finished setting up and verified your breakpoints in 2.1 seconds after it got the "attach" request, so it does not seem to be js-debug that is unduly slow, though that may be slightly slower than the previous node debugger.

I think the best solution would be to call [`inspector.waitForDebugger()`](https://nodejs.org/api/inspector.html#inspector_inspector_waitfordebugger) in the extension host so that nothing happens until attachment happens. @weinand thoughts?

**Comment by weinand** [comment]
I can reliably reproduce this problem both with TS and JS extensions by enabling early extension activation with the wildcard activation event ("*").

With this I never hit a breakpoint in the activation method with **js-debug**, but I always hit it with **node-debug2**.

Since this problem only occurs in the Web, I think we can swallow it in this milestone.
But we should address it in June.

(Using "inspector.waitForDebugger()" might be one solution to solve the problem, but I do not want to add this new code today).

**Comment by connor4312** [comment]
I fixed this in the linked commit (see details)

Waiting for the tab's title to change indicating a breakpoint hit is still _very_ slow in web when the tab isn't focused (like a 5-10 second delay) but it works consistently.
