### ISSUE TITLE
system-ui font doesn't differ between Insider and Stable on macOS

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#99235]
Testing #98022

From the double-negated sentence in the test-item's description
> You should not see a difference unless: you are not using a Ubuntu Linux

I conclude that I should see a difference on macOS.

But I do not:

<img width="454" alt="2020-06-03_11-54-27" src="https://user-images.githubusercontent.com/1898161/83623305-7598a380-a591-11ea-8ae8-e7702d8c40eb.png">

(stable left, insiders right).

I do not really understand why I should see a difference if I'm not able to change system fonts on macOS anyway (I tried to do this with TinkerTool but I didn't succeed).

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/83624730-484cf500-a593-11ea-9dee-291b89ef30f2.png)

**Comment by bpasero** [comment]
macOS: no difference is correct.

**Comment by weinand** [comment]
I neither understand the "(!)" nor the highlighted ranges:
- my screenshots do not show editors
-  "you are not using an Ubuntu Linux" includes macOS, right?

**Comment by bpasero** [comment]
`system-ui` is a font that maps to apple-system as far as I know, so the font change should mean no font change on macOS. On Linux `system-ui` will be a font that is picked by the OS and/or user but if you are on Ubuntu that should also mean no difference because we hardcode the Ubuntu font. And on Windows, unless you are using a non-english locale it should also not make any difference.
