### ISSUE TITLE
No `onDidOpenNotebookDocument`-event not called from `modelManager.resolve`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#99240]
For https://github.com/microsoft/vscode/issues/99148 I have pushed https://github.com/microsoft/vscode/commit/1c7510ca13d1440c2e30df7897ebe4383f6a464c to make sure a notebook is (re)opened during resolve of cell content. However, this doesn't fire an `onDidOpenNotebookDocument` event. The following steps

* have a GH issue notebook with 2 cells and a variables that is used in both
* run "Find All References" on the variable, there are result for both cells
* close the notebook editor
* press refresh in the references viewlet
* :bug: there is only results for a single cell

That's because no open event is fired and therefore not the whole notebook is fed into the project system. Instead, an ad-hoc project is created this "new" cell

**Comment by rebornix** [comment]
What I observed from above steps:

* have a GH issue notebook with 2 cells and a variables that is used in both
  * document open event, gh nb set up project
* close the notebook editor
  * document close event, gh nb dispose `projectRegistration`
* press refresh in the references viewlet
  * Reference provider in gh nb is still invoked, which only returns single result

IMHO the events we sent to the ext host is correct in this scenario.

**Comment by jrieken** [comment]
> press refresh in the references viewlet

When you press refresh, the viewlet will re-open the cell-document and will go through [this code](press refresh in the references viewlet) which IMO should reopen the whole notebook.

**Comment by jrieken** [comment]
So, it seems that resolving notebook does trigger the state re-compute and delta logic but for some reason the new (reopened) notebook doesn't make it into the state and therefore not into the delta...

<img width="847" alt="Screenshot 2020-06-04 at 16 05 04" src="https://user-images.githubusercontent.com/1794099/83766933-48292400-a67d-11ea-95d4-8053933b9873.png">

**Comment by rebornix** [comment]
Good point, previously I made the assumption that a document should always be created together with an editor. I pushed a change to allow a document to be created without editors open, but I'm not sure if it's the right thing to do though, as now I don't know when should it be disposed @jrieken ideas? Maybe I should have some kind of ref count.

With the change, the Find All References partially work:

* Close the editor
* Refresh immediately, only see one result
* Refresh again, see two results

This is because on the first refresh, only one `vscode.TextDocument` is created and sent to the ext host, so the `Project` in GH NB can only find one text document associated to the notebook document. Once all text documents are created, Find All References work as expected.

Shouldn't GH NB still work fine if the `vscode.TextDocument` for cells are not created yet?

**Comment by rebornix** [comment]
Moving to June as we are not turning on this feature in Stable yet.

**Comment by jrieken** [comment]
> @jrieken ideas? Maybe I should have some kind of ref count.

Yeah, we ref-count text documents in the workbench and for references that have been acquired by extensions we have special logic to auto-dispose them. The logic is to unref a text document after a few minutes, or when a certain amount of documents are opened, or when those files are moved, deleted etc. 

The workbench concept is the [`TextModelResolverService`](https://github.com/microsoft/vscode/blob/a131d1498af6cea533654a27b86454223ec45f19/src/vs/workbench/api/browser/mainThreadDocuments.ts#L227) and the extension logic is [this](https://github.com/microsoft/vscode/blob/a131d1498af6cea533654a27b86454223ec45f19/src/vs/workbench/api/browser/mainThreadDocuments.ts#L23)

**Comment by jrieken** [comment]
fixed via https://github.com/microsoft/vscode/pull/100266
