### ISSUE TITLE
"editor.tabSize" does not change the default indentation

### ISSUE THREAD

**Issue by IceGiant** [Microsoft/vscode#9926]
- VSCode Version: 1.3.1
- OS Version: Windows 10.0.10586

Steps to Reproduce:

1. Set "editor.tabSize": 2
2. Open a file with two-space width indentation, inserted as spaces
3. Edit any spot in the code, and the indentation gets forced globally to 4 instead of 2 as the tab width

**Comment by alexandrudima** [comment]
@IceGiant Please also see the setting `editor.detectIndentation` which is on by default. The `editor.tabSize` is the fallback value in case detecting indentation is not possible (new file, no indented lines), otherwise the file you open is scanned and an indentation is detected. The detected indentation settings are displayed in the status bar at the bottom, and pressing `Tab` or indenting will respect the indentation displayed in the status bar.

**Comment by IceGiant** [comment]
I missed that an extension was overriding the editor global config when editing .js files and had to be separately configured, so that explains why I was running into that.

**Comment by toddmo** [comment]
You can do ctrl+a then shift+tab a few times in the document to unindent everything. Then close and re-open and do alt+shift+f to get the document on the tab size from the settings.

**Comment by fedry** [comment]
Thanks @toddmo for the solution.
