### ISSUE TITLE
Condition of breakpoint on first line not evaluated

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#9927]
- VSCode Version: Code - Insiders 1.4.0-insider (531a56f772fc33ec88910328b88f4dbd7ae5df43, 2016-07-28T16:55:53.763Z)
- OS Version: Darwin x64 15.5.0

Steps to Reproduce:
1. Place a conditional breakpoint on the first line (entry point), e.g.: console.log('hit')
2. Start debugging
3. Unexpected: Debugger stops without output in the console

This works as expected when the breakpoint is on the second line.

Found verifying #9174.

**Comment by paritosh149** [comment]
Please update on this issue.

**Comment by weinand** [comment]
Analysis:
- "early" breakpoints are a general node problem because they can only be registered if the node runtime is stopped on entry, which means that node needs to be started with "--debug-brk" or "--inspect-brk". This is VS Code standard behaviour.
- if node is started with "--debug-brk" node creates a synthetic breakpoint on line 1. If a conditional breakpoint is placed on line 1 too, only the synthetic breakpoint is hit and any other breakpoints are not considered. That's the reason why the condition is not evaluated and no output shows up in console.
- the program stops in the first line because VS Code assumes that there is a regular breakpoint.

I've fixed this for "legacy":
- the DA evaluates the condition for breakpoints placed on the entry point,
- the result of the evaluation determines whether to break or to continue.

/cc @roblourens
