### ISSUE TITLE
Trusted Domains pops up when trying to file an issue

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#99294]
Testing #97578.

Running on `https://online-ppe.core.vsengsaas.visualstudio.com/environments` (internal only) which run 

Version: 1.46.0-insider
Commit: 595d2b9b916d063aadfc2c1a8c8f6df5b45572a8
Date: 2020-06-03T05:23:16.078Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.13 Safari/537.36 Edg/84.0.522.5

1) Create a new codespace  for `https://github.com/kieferrm/js-debug-sample`. 
2) ** F1 > Help:Report Issue**
-> 

![image](https://user-images.githubusercontent.com/4674940/83658324-ec747300-a576-11ea-90cf-6894bd860b6d.png)

We trust `https://github.com/microsoft/` by default, so `https://github.com/Microsoft/vscode/issues/new` should be trusted but is not. One thing I realize is the difference in casing.

**Comment by JacksonKearl** [comment]
The domains are currently matched case-sensitively because in theory different cased paths could resolve differently.

Looks like in desktop the report issue flow doesn't go through trusted domains so we don't see this there.

Could either make all matching case-insensitive, or special case github paths. Or trust both `Microsoft` and `microsoft`.
