### ISSUE TITLE
"stopAll" ends debugging after the second "attach" config is disconnected

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#99299]
- Start the "VS Code" compound config
- Detach "Attach to Main Process"
- Everything else is still attached
- Detach "Attach to Shared Process"
- All the remaining configs are stopped

Same thing if I do the 2 in the opposite order so I don't think it's anything special about the Shared Process. Is it all supposed to shut down after one attach config is detached, or should it only shut down when a launch config is stopped?

![Jun-03-2020 12-11-36](https://user-images.githubusercontent.com/323878/83667125-8e09bd80-a593-11ea-8108-7f45af3d68c0.gif)

**Comment by connor4312** [comment]
I believe this is because the "main process" you have selected is actually the child session of the main process. Terminating that causes the parent session to exit, but I've set it up so that stopAll only bubbles _explicit_ exits from the user.

For attachment, though, it should be totally safe to forego the parent session. I'll look at getting rid of that.

**Comment by connor4312** [comment]
I've since modified `stopAll` to tell all targets to stop whenever _any_ target, not just a parent, is stopped.
