### ISSUE TITLE
Notebook Editor: scoped context key service

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#99318]
The context key service we used in the notebook editor is not scoped to the DOM node, which might lead to potential context key issues

https://github.com/microsoft/vscode/blob/8fc68f79748e2c29fb64557549f65908bdf004d0/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L105

We should create context key service which scoped to `NotebookEditorWidget` root DOM node.

**Comment by roblourens** [comment]
I'm pretty sure that if you open two notebooks, the second is overwriting the context keys of the first. How this works for code editors - they need to unwrap an `ICodeEditor` here: https://github.com/microsoft/vscode/blob/bed0ab42c3005ed9846a28ffe5d5ae06bd0919f9/src/vs/workbench/browser/parts/editor/titleControl.ts#L233 

@bpasero I'm confused about that code, it looks like I would need to extend it for every editor type in order to get the editor title control to render actions using the editor's contextKeyService?

**Comment by rebornix** [comment]
@roblourens we can use 

```
const activeControl = activeEditorPane.getControl();
if (isCompositeEditor(activeControl) && isCodeEditor(activeControl.activeCodeEditor)) {
	return activeControl.activeCodeEditor;
}
```

**Comment by rebornix** [comment]
maybe we should copy logic from 

https://github.com/microsoft/vscode/blob/4f73c4ad334660157cbaadf0ecd580a2ec1085fc/src/vs/workbench/services/editor/browser/codeEditorService.ts#L26-L40

to 

https://github.com/microsoft/vscode/blob/4f73c4ad334660157cbaadf0ecd580a2ec1085fc/src/vs/editor/browser/editorBrowser.ts#L1035-L1045

@jrieken is it safe to do that?

**Comment by roblourens** [comment]
Well, I don't want the context key service from the code editor inside the notebook editor, I want it from the notebook editor itself.

**Comment by rebornix** [comment]
right, I misread it then I think we can extend 

https://github.com/microsoft/vscode/blob/b987634a8d7656a1fdb99745d913aaa982e6af47/src/vs/editor/common/editorCommon.ts#L548

by adding `invokeWithinContext `

**Comment by bpasero** [comment]
@roblourens I cannot recall, I think Jo wrote that code to ensure the title menu gets the most appropriate context key service before rendering.

**Comment by jrieken** [comment]
> I want it from the notebook editor itself.

Each editor group gets a dedicated context key service - a simple way to enumerate them is to paste this into the console `document.querySelectorAll('[data-keybinding-context]')`. 

I am not quite sure what the actual issue is but I can image that there a problem because context key hierarchies work along the dom structure and given that notebook editors might not always follow that structure, right?

**Comment by roblourens** [comment]
After fixing https://github.com/microsoft/vscode/issues, this is an issue again

- Drag notebook from group A to group B
- Close group A
- Now looking up context keys fails

![image](https://user-images.githubusercontent.com/323878/90177179-07c1e280-dd5f-11ea-8fff-68138ed1dcdc.png)
