### ISSUE TITLE
Notebook cell drag and drop interferes with editor tab drag and drop

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99327]
When dragging a notebook editor tab onto itself for splitting, it now triggers drag hover events in the editor and it it difficult to trigger the editor split event.

**Comment by roblourens** [comment]
Showing the dragover ui for non-cell dragging was fixed, but I still can't trigger the editor split event without going to the tab bar.

**Comment by roblourens** [comment]
This is related to moving the notebook editor out of the main grid view. We add drag listeners to the `.content` element, but they are never triggered when dragging a file/editor into that view because the notebook is covering the whole area. We need a way to add the same listeners to an editor which is outside of the main flow, or have the editor forward those events to the EditorDropTarget in some other way.

**Comment by rebornix** [comment]
As we discussed offline, we can take a look at how Webview Editor does it.
