### ISSUE TITLE
Dropdown from view item menu

### ISSUE THREAD

**Issue by katelynienaber** [microsoft/vscode#99345]
In our extension, we have custom views with various nodes in the tree:
![image](https://user-images.githubusercontent.com/58596139/83736195-91fc1500-a651-11ea-9a8f-3009881bc182.png)

You can see there are 4 commands on the right-hand side of the node. We would like to add a dropdown to hold those items.

I know it's possible to add commands to the context menu, but you have to right-click to see it. We are worried that new users will not be aware they can right-click on nodes for more options. If we could add a dropdown to the toolbar, it would be more obvious that other commands are available.

For example, in the Source Control view, you have an icon with 3 dots, that opens a dropdown:
![image](https://user-images.githubusercontent.com/58596139/83736125-81e43580-a651-11ea-8311-63c4738076af.png)

It would be great if we could either add to a standard dropdown, or use a command like `node.showDropdown` when someone clicks on the 3 dots icon.

**Comment by alexr00** [comment]
Right click to see more actions is a pretty typical thing to do, and I worry that it is busy and duplicating functionality to have drop downs in the tree node inline actions when that is exactly what the right click menu is for. @misolori do you have some thoughts on this?

**Comment by misolori** [comment]
Personally, I'd be in favor of doing this. However, I think we'd need to run this by the team since it does introduce some complexities. Whenever there is a single view in viewlet, we collapse that view title and actions into the header:

![image](https://user-images.githubusercontent.com/35271042/84058058-85d3c880-a96d-11ea-899a-f7bddeb0a239.png)

So introducing a "global" context menu would mean that we would need to account for these additional context menus and have clear indicators for what actions in the menu are global vs the view.

**Comment by 0mkara** [comment]
I have run into a similar requirement where I want the `inline` group of `view/item/context` to have a menu like the `...` icon. :+1: to this feature request.

**Comment by eamodio** [comment]
The `...` menu feels like a good addition here as it will aid in discovery of more actions on items.

**Comment by alexr00** [comment]
This is now possible with [submenus](https://github.com/microsoft/vscode/issues/100172#issuecomment-645203070)
However, there is a bug with using it on inline tree actions: https://github.com/microsoft/vscode/issues/110083
