### ISSUE TITLE
OS X: Focus is not retained if fullscreen, with multiple windows, after cmd+tabbing

### ISSUE THREAD

**Issue by entozoon** [microsoft/vscode#99366]
- VSCode Version: April 2020 (version 1.45)
- OS Version: Catalina MacOS

Steps to Reproduce:

1. Open two windows of VSCode (actual instances, not tabs).
2. Fullscreen the second window (ctrl+cmd+f)
2. cmd+tab to another app and back
You'll see it's focussed on the non-fullscreen original window.

Does this issue occur when all extensions are disabled?: Yes

Quite annoying. Perhaps it's just 'how macs handle fullscreen', and there's nothing to be done but worth reporting as it does strike me as a bug.

**Comment by bpasero** [comment]
VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

Reading this issue, it seems to originate not from VSCode itself but rather one of these upstream components. As such, in order to resolve it, it would need to get fixed in the upstream component. I will go ahead and close this issue and kindly ask to report this issue to the upstream component if possible:
* for UI, OS integration: https://github.com/electron/electron
* for Rendering: https://bugs.chromium.org/p/chromium/issues/list
* for file IO: https://github.com/nodejs/node

Thanks for understanding.
