### ISSUE TITLE
Debugger evaluates `this` wrong after using call on an arrow function

### ISSUE THREAD

**Issue by dj-hedgehog** [Microsoft/vscode#9938]
I know that an Arrow functions `this` can't be set via `call()`. Nevertheless `this` is evaluated wrong in this example:

![test js - desktop 2016-07-29 09-26-23](https://cloud.githubusercontent.com/assets/7140800/17241004/277119a6-556f-11e6-9f8c-b1ead391597c.png)

Note: This could be a Node Debugger issue as well. 

- VSCode Version: 1.3.1
- OS Version: macOS 10.11.6

Steps to Reproduce:

1. Execute the following code in VSCode.

```
function * fn () {
  this.foo = 'bar'
  yield fn2.call(this)
}

var fn2 = () => {
  const ctx = this
  const equal = ctx == this
  debugger;
  return new Promise((resolve, reject) => {
    console.log(this.foo)
  })
}

(function () {
  fn().next()
})()
```

**Comment by weinand** [comment]
@dj-hedgehog node-inspector shows the same behaviour:

![2016-07-29_11-39-38](https://cloud.githubusercontent.com/assets/1898161/17244245/3118b6aa-5581-11e6-86e1-d5e66bcd78e9.png)

Since both VS Code and node-inspector rely on the same v8 debugger protocol, this is a strong indication that the problem is not a VS Code but a node.js issue.
I suggest that you file a bug against node.js.
