### ISSUE TITLE
VSCode logs in file system blowing up to nearly 150GB

### ISSUE THREAD

**Issue by harshavamsi** [microsoft/vscode#99380]
- VSCode Version: 1.45.1
- OS Version: macOS Catalina 10.5.5 with supplemental update for CVE

Okay, for some reason VSCode logs blew up in my system and used up a whopping 147GB in less than 10 seconds. I saw them through the macOS Storage manager. Here's a picture from my phone - 

![IMG_20200604_133751](https://user-images.githubusercontent.com/10369642/83779154-38273980-a6a9-11ea-9972-a27276d6759d.jpg)

I had to delete the whole folder, even now the logs are pretty massive at 28GB.

<img width="586" alt="image" src="https://user-images.githubusercontent.com/10369642/83779301-64db5100-a6a9-11ea-8c55-9cc069283905.png">

I think the issues started occurring after restarting the TypeScript compiler.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by mjbvz** [comment]
Can you share the contents of the `exthost1` directory? Which log files are taking up the most space?

Also, do you have `typescript.tsserver.log` enabled?

**Comment by harshavamsi** [comment]
Unfortunately, I had to delete the contents of the log folder to save some space, but I can confirm that I set `typescript.tsserver.log` to true a few days ago. I guess that's when the issue started occurring. I can set it to true again and try to repro the issue again.

**Comment by mjbvz** [comment]
Yes in general you should don't leave `typescript.tsserver.log `enabled when you are not using it. 

Having said that, it should never generate that volume of data. I have it enabled all  the time and have never run into any issues.

If this happens again, please share the name of the large files, along with some example text content from them so that we can investigate
