### ISSUE TITLE
Opening a context menu in a notebook cell cause a lot of UI churn because of focus change

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#99399]
![focus](https://user-images.githubusercontent.com/641685/83801639-7ad01e00-a677-11ea-9e68-dde7b5ce9953.gif)

You can see the focus outline is lost, chevrons are dimmed, the toolbar loses a button, etc

**Comment by rebornix** [comment]
Another item for polishing the focus tracker in the notebook, if the focus goes into the Context Menu, we can treat it as the focus is still in the notebook list.

**Comment by roblourens** [comment]
@rebornix is there any way to know that a code editor is showing a context menu?

@sbatten were you looking into moving context menus to live in the DOM with the element that they are triggered on, instead of in document.body?

Otherwise I don't know how to tell that focus is in the context menu for this particular cell editor.

**Comment by rebornix** [comment]
> is there any way to know that a code editor is showing a context menu?

no, we are not aware of that, maybe context menu service knows about that.

**Comment by sbatten** [comment]
@roblourens, yes the context view service is capable of doing this today with the massive caveat that it isn't shadow dom'd  so it has css issues. i have a prototype of the shadow dom from last milestone but it isn't complete.
