### ISSUE TITLE
High Contrast theme's yellow breakpoint line color makes text unreadable

### ISSUE THREAD

**Issue by surajs02** [microsoft/vscode#99464]
- VSCode Version: 1.44.0 (user setup)
- OS Version: Windows_NT x64 10.0.18363

When a breakpoint is hit during debugging, the active debug line's yellow background color makes the line's text unreadable (see attached screenshot).

![image](https://user-images.githubusercontent.com/11654341/83899633-affc6f00-a750-11ea-8819-c501a206bbf9.png)

Steps to Reproduce:

1. Enable high contrast mode on Windows 10
1. Ensure VSCode's theme is set to high contrast
1. Set breakpoint and start debugging session
1. Reach breakpoint

Does this issue occur when all extensions are disabled?: Yes

**Comment by isidorn** [comment]
This is fixed in latest. You are using a very old vscode version 1.44
Here's what I see

Please let me know if you can reproduce with latest vscode insiders and I can reopen

![Screenshot 2020-06-08 at 16 07 57](https://user-images.githubusercontent.com/1926584/84039916-3b207380-a9a2-11ea-9ffd-b2390c920322.png)

**Comment by surajs02** [comment]
Thanks for the advice, can confirm text is readable after updating to VSCode 1.45.1

![image](https://user-images.githubusercontent.com/11654341/84075059-64a1c500-a9cb-11ea-9ed8-b96de30e0f0f.png)
