### ISSUE TITLE
VSCode Failed to load resource: net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by michaelNabil316** [microsoft/vscode#99480]
Issue Type: <b>Bug</b>

i just download VSCODE and tried to add extention flutter but it said in log dev tools
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
my internet is work good and my google chrome work normal

![Capture](https://user-images.githubusercontent.com/66490732/83913241-84d54800-a76f-11ea-94d2-ce1cfe696b6c.PNG)

**Comment by michaelNabil316** [comment]
@sandy081 please look to this

**Comment by michaelNabil316** [comment]
@sandy081 look to this please

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by michaelNabil316** [comment]
@sandy081 great man
thanks i changed dns and it work
thanks alot

**Comment by iamabs2001** [comment]
internet connection problem
