### ISSUE TITLE
debugger reads into string's content

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#995]
I've noticed that debugger resolves variables even from strings: 

![](https://dl.dropboxusercontent.com/u/105338698/ShareX/2015-12/2015-12-04_02-52-13.png)

I guess it's not a big deal and maybe can even be useful at some point, but still doesn't seem like an intended behavior...

**Comment by isidorn** [comment]
Yes this is a current limitation because the debug hover does not have language specific knowledge.
This should be fixed in the future as part of a larger debug hover improvement work when the hover should talk to the language service for getting tokens that the user is hovering over.

Closing for now
