### ISSUE TITLE
Can't go back after showing same keybindings

### ISSUE THREAD

**Issue by S-U-M-1** [microsoft/vscode#99530]
At the moment, when I open the keyboard shortcuts, right-click a shortcut and click "Show Same Keybindings", there seems to be no way to go back to the previous view. This forces me to retype (or re-paste) the key search query into the search box. I've tried Backspace, Ctrl+Z, Alt+Left and looking for a back button. I hope I'm not missing some stupid feature.

Steps to reproduce:

1. Open the Keyboard Shortcuts settings page, either via
   - pressing Ctrl+K and then D, or
   - pressing Ctrl+Shift+P and then searching for "Preferences: Open Keyboard Shortcuts".
2. Search for any shortcut (or don't).
3. Right click on any shortcut entry.
4. Click "Show Same Keybindings".
![image](https://user-images.githubusercontent.com/29358863/83951064-f7552f00-a826-11ea-8272-166a0de239bc.png)

5. Observe how the search query changed to the key combination (or single key).
![image](https://user-images.githubusercontent.com/29358863/83951073-0b009580-a827-11ea-9426-ae38af3d99e5.png)

6. Realise that you can't go back to the previous view without entering the search field and re-typing your search query.

Please add a shortcut or button to go back if there isn't one already. Thank you.

**Comment by Cacique99** [comment]
Hello, I would like to take this task if there is no one else is interested, this would be my first contribution. Instead of a button to go back, would you prefer the following type of interaction?

**Step 1:** Click the clear search button that's circled in red
![#99530](https://user-images.githubusercontent.com/37465627/83986854-33ae8b00-a90c-11ea-899b-2a6118690b9d.png)

**Step 2:** Have the element in the list that you last clicked to be shaded like so
![#99530_1](https://user-images.githubusercontent.com/37465627/83987253-9fddbe80-a90d-11ea-8f77-3d73681ba066.png)

**Comment by sandy081** [comment]
Suggestion - Introduce history feature in Keybindings Search Input so that users can go back.

**Comment by S-U-M-1** [comment]
@Cacique99 Thank you for expressing interest. Any feature would be decent, including that, but my preference is that a keyboard shortcut could be possibly used, like the ones I mentioned, as that was my first instinct when trying to go back. I don't usually click the "Clear Search" button anyway (I just Ctrl+A the search field), and I wouldn't want any functionality to be removed/replaced in the course of adding this feature.

**Comment by S-U-M-1** [comment]
@Cacique99 Thank you for expressing interest. I think this feature would be a good addition. If possible, I think it would also be good to have a keyboard shortcut like the ones I mentioned, as that was my first instinct when trying to go back. I don't usually click the "Clear Search" button anyway (I just Ctrl+A the search field).

**Comment by sandy081** [comment]
@Cacique99 I would suggest supporting history in Keybindings Search Input box, just like in Search input box. This suffices the requirement and make it consistent across.

Regarding commands to go back I would keep it on hold and wait for more user feedback.

**Comment by Cacique99** [comment]
Hey @sandy081 sorry to bother you it's that I'm trying to understand the vscode directory layout but I can't seem to find where do I have to make changes in order to have the history feature for the keyboard shortcuts page. Do you know where this file is in the project?

I read the Source Code Organization wiki and somewhat know how everything is supposed to be situated but couldn't figure where should I edit for this specific feature request. Any general tip for better understanding the file structure to contribute in the future would be greatly appreciated.

**Comment by sandy081** [comment]
Here are some references

https://github.com/microsoft/vscode/blob/5eeed7cf46fb0857dde7994d133cae33ad1f34d4/src/vs/workbench/contrib/preferences/browser/keybindingsEditor.ts#L333-L333

Here is the problems view filter code that supports history

https://github.com/microsoft/vscode/blob/d662ba0f31b84ae9356789d8ac8868a8bdf06b9d/src/vs/workbench/contrib/markers/browser/markersViewActions.ts#L321-L321

**Comment by ArturoDent** [comment]
For consistency, just up/down arrows to cycle through Keybindings Search Input.

**Comment by sandy081** [comment]
Verify that
- Keybindings editor search input supports history which can be navigated using up/down arrows.
- History is synchronised across windows and machines
