### ISSUE TITLE
Unify colors of find in file and workspace search results

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#9955]
- VSCode Version: Code - Insiders 1.4.0-insider (4656fe3ff2952e9538d81e7a7571674352e5d62f, 2016-07-29T05:03:52.605Z)
- OS Version: Darwin x64 15.5.0

Find in file (Ctrl+F) and workspace search (Ctrl+Shift+F) results are colored not exactly the same. It might be easier to read the color-coding if it was the same.

Local search:
![localsearch](https://cloud.githubusercontent.com/assets/9205389/17222691/73127592-54ae-11e6-997a-5d221ff45a76.png)

Global search:
![globalsearch](https://cloud.githubusercontent.com/assets/9205389/17222721/9a54f7a6-54ae-11e6-90e4-e58d88a44396.png)

Note the different browns for the results and the different renderings of the current line in the two cases.

(Extracted from #6402.)

**Comment by sandy081** [comment]
This happens when both Search and Find are active on file for the same term. Otherwise they are similar in colors for results. If both are active then each adds same decoration and there are two overlay decoration on the same word which is causing a different color. One soultion for this could be to disallow duplicate decorations but I think this is complex as state is going to be involved. Also it has to be dealt properly when a decoration is removed. 

IMO the current behavior is reasonable. 

![aug-31-2016 17-14-06](https://cloud.githubusercontent.com/assets/10746682/18134354/66d98a26-6f9e-11e6-8935-a78d380dbbbf.gif)


![aug-31-2016 17-14-21](https://cloud.githubusercontent.com/assets/10746682/18134361/6a75be02-6f9e-11e6-9f60-d0bbb1ffefc3.gif)


It leaves to the issue about Search selecting the line of current find result. I will create a separate issue for that and leave this issue only for search and find results color.

**Comment by octref** [comment]
Since this is as-designed, there isn't anything to verify.
I'm adding the `verified` tag and removing `bug`.
@sandy081  Let me know if I'm doing it wrong.

**Comment by Tyriar** [comment]
Related discussion: https://github.com/Microsoft/vscode/issues/11354
