### ISSUE TITLE
Markdown live preview keeps moving editor downwards

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#99574]
Issue Type: <b>Bug</b>

Ran into this issue while editing 1_46 release note

![markdown-preview](https://user-images.githubusercontent.com/876920/83979143-156f6d80-a8c1-11ea-83f5-3cb12212221a.gif)

VS Code version: Code - Insiders 1.46.0-insider (b1ef2bf05f90dd0e6438782411ab84756f97d8f1, 2020-06-05T12:27:56.662Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.15GB free)|
|Process Argv|-psn_0_18395530|
|Screen Reader|no|
|VM|9%|
</details>

**Comment by kenfai** [comment]
I am having a similar issue:

When typing in the editor pane, the preview pane will scroll down by itself as I type. The issue is more severe when there're images on the document.

Disabling the following settings doesn't stop it either.

```json
"markdown.preview.scrollEditorWithPreview": true
"markdown.preview.scrollPreviewWithEditor": true
```

To reproduce, make sure you are editing a long markdown document. A fresh new document will not have the problem as there's nothing below to scroll down to.

Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z (3 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

**Comment by rdhar** [comment]
Related to #89930?
