### ISSUE TITLE
Bug: Emoji modifiers in text treated separately when using backspace

### ISSUE THREAD

**Issue by dmsnell** [microsoft/vscode#99629]
- VSCode Version: All recent versions, maybe all versions, including Monaco outside of VSCode
- OS Version: macOS, Windows, likely Linux and all others

Steps to Reproduce:

1. Enter an Emoji with a modifier, such as a Fitzpatrick skin type modifier: 👶🏾
2. Hit backspace after that character
3. According to the Unicode specification the entire character should be removed.
4. VSCode removes the modifier and leaves the Emoji, producing 👶

The relevant spec, [UTS #51](https://www.unicode.org/reports/tr51/#valid-emoji-tag-sequences), states that:

> A supported emoji modifier sequence should be treated as a single grapheme cluster for editing purposes (cursor moment, deletion, and so on); word break, line break, and so on.

This is probably related to #19390, directly to [a comment about ⚠️](https://github.com/microsoft/vscode/issues/19390#issuecomment-399767433), but separate enough that I suppose it warrants its own issue.

It's worth noting that aspects of this work as expected. The editor won't let you select he modifier - it correctly forces you to select the modifier plus the Emoji it modifies as an atomic whole. As reported in #19390 though it's possible to move the cursor inside the modified grapheme cluster and break it. (While the cursor bug doesn't appear in the Monaco playground the backspace bug does).

Does this issue occur when all extensions are disabled?: Yes

**Comment by alexdima** [comment]
Since about 6 months, we have implemented Unicode's grapheme break rules. So it is not possible to place the cursor inside emojis. A Delete (Fn+Backspace) before the emoji will remove the entire grapheme. But Backspace will only delete one code point at a time. We have made the decision to behave like this due to it being used for input building in various languages. See example in #84897.

See also #69900

There's also an interesting blog post at https://lord.io/blog/2019/text-editing-hates-you-too/

**Comment by dmsnell** [comment]
> We have made the decision to behave like this due to it being used for input building in various languages.

Thanks for explaining @alexdima - I guess that means there's a disagreement with the Unicode spec? Needing to hit backspace seven times to delete a single flag, for example, is something the spec was trying to prevent.

The example in #84897 seems like a different issue, especially since the spec calls out Emoji, Emoji with modifiers, and Emoji Tag Sequences as specific and separate things.

I guess I'm a little confused if you are more or less explaining the context behind why this bug exists or saying that the VSCode team doesn't plan on fixing it or that y'all disagree that it's a bug.

In any case thanks for your help. I know text editing is hard - that's why I've been excited to try out Monaco because it seems like it does a better job than most web-based components.

**Comment by alexdima** [comment]
@dmsnell There's no disagreement with the Unicode spec. In our code, we currently lack the ability to distinguish the emoji flag case from the Thai characters case. Since this use case is important for typing in Thai, we have chosen to allow backspace to remove the last code point from a grapheme, regardless of which grapheme that is. We would need to further refine this and make backspace delete the entire grapheme in case the grapheme is an emoji.

**Comment by alexdima** [comment]
Another use-case is https://github.com/microsoft/vscode/issues/109812 for ✔

**Comment by hediet** [comment]
Interestingly, even browsers show different behaviors when hitting backspace after Emojis with modifiers or combinations of those separated by the Zero Width Joiner (ZWJ).

Firefox 88:
* Address-bar: "✔️" -> ""
* Address-bar: "👨‍👨‍👧‍👧" -> "👨‍👨‍👧" -> "👨‍👨" -> "👨" -> ""
* Input/Text-Areas behave the same

Chrome 90:
* Address-bar: "✔️" -> "✔" -> ""
* Input/Text-Area: "✔️" -> ""
* Address-bar: "👨‍👨‍👧‍👧" -> "👨‍👨‍👧‍" -> "👨‍👨‍👧" -> "👨‍👨‍" -> "👨‍👨" -> "👨‍" -> "👨" -> ""
* Input/Text-Area: "👨‍👨‍👧‍👧" -> ""

Monacos behavior seems to be consistent with Chromes address-bar.
I think Firefox got it right: It always removes the modifier with the modified emoji, but deletes ZWJ-combined emojis step by step.
You can even combine modified Emojis (👨‍👩🏽‍👧‍👦)!
