### ISSUE TITLE
"Toggle Line Comment" doesn't work as expected while multi-line selected

### ISSUE THREAD

**Issue by charleslabachen** [Microsoft/vscode#9964]
- VSCode Version: 1.3.1
- OS Version: Windows 10

Steps to Reproduce:

1. Select the lines with both commented lines and un-commented lines
2. Execute "Toggle Line Comment"

Original Text:
>  // line 1
>  line 2

Current Result:
>  // // line 1
>  // line 2

Expected Result:
>  line 1
>  // line 2

**Comment by alexandrudima** [comment]
This is the designed behaviour. `Ctrl-/` which is Toggle Line Comment will:
1. examine all selected non-whitespace lines
2. if all the non-whitespace selected lines begin with the line comment token, then it will remove this line comment token from the lines (acts as remove line comment).
3. otherwise, it will insert the line comment token to all the lines (acts as add line comment).

Thus it has the name "toggle". It does not do individual line toggle. You can always use multicursor ops to achieve that: `ctrl+alt+down` to the lines or `shift+alt+drag` and then run `ctrl-/`. This will execute this logic for each individual line.
