### ISSUE TITLE
workbench.action.previousSideBarView cannot loop

### ISSUE THREAD

**Issue by k1090** [microsoft/vscode#99663]
- VSCode Version: 1.45.1
- OS Version: macOS 10.15.5

I set keybindings like this.
`  {
    "key": "ctrl+tab",
    "command": "workbench.action.nextSideBarView",
    "when": "sideBarFocus"
  },`
`
  {
    "key": "ctrl+shift+tab",
    "command": "workbench.action.previousSideBarView",
    "when": "sideBarFocus"
  },`

But when I focus the Explorer tab and press "ctrl+shift+tab", It cannot loop.

Does this issue occur when all extensions are disabled?: Yes

**Comment by sandy081** [comment]
It is working for me with above keybindings. Please check if you have other commands bound to the keys?

**Comment by ArturoDent** [comment]
When you say "when I focus the Explorer tab" do mean you are clicking on the Explorer icon in the activityBar?  If so, that is not sufficient to give focus to the sideBar UNLESS that **opens** the sideBar.

If when you press the Explorer icon in the activityBar it opens the sideBar (where all the Exlorer files appear) then focus is in the sideBar and your keybindings will work.

Unfortunately, looking through the `Inspect Context Keys` results, I don't think there is an `activityBarFocus` entry which if it existed would be preferable to your `sideBarFocus`.

Your keybindings work for me as well when the sideBar has focus, but as I said clicking on an icon in the activityBar doesn't necessarily transfer focus to the sideBar unless that action opens the sideBar and doesn't close it.  If the sideBar is closed - by your toggling it closed with the activityBar Explorer icon - then your keybindings willnot work due to the `when` clause.

**Comment by k1090** [comment]
I mean `workbench.action.nextSideBarView` can loop but `workbench.action.previousSideBarView` cannot loop when I open and focus sideBar in my environment.
I disabled my other keybindings but nothing changed.

**Comment by ArturoDent** [comment]
Ahh, now I see what you are saying.  I get weird behaviour if I move the Explorer down one icon - `previousSideBarView` starts just cycling between the side-by-side Explorer and SCM icons and `nextSideBarView` will skip the first (SCM) icon when it loops from the bottom. 

 And if I come to the "Browser Preview" icon it then jumps to the Explorer icon wherever it may be (although maybe that is expected behaviour?).

**Comment by sandy081** [comment]
@k1090 Can you please remove the `when` part and try?

**Comment by sandy081** [comment]
Can you please provide your activity bar configuration so that I can try to mimic?

**Comment by k1090** [comment]
Today I update VScode to 1.46.0, and now it works. Thanks anyway.
