### ISSUE TITLE
Unable to install extensions in this version

### ISSUE THREAD

**Issue by hitansu27** [microsoft/vscode#99668]
I am unable to install extensions from market place, getting below error:

We cannot connect to the Extensions Marketplace at this time, please try again later.

Version : 1.45.1 (user setup)

**Comment by sandy081** [comment]
Please follow these steps

- Help -> Toggle Developer Tools -> Network
- Then check for any network failed requests while browsing and installing the extensions if found all requests fails then its probably a proxy or DNS issue at your end.
- To confirm its a DNS issue check if you can access this page https://ms-python.gallerycdn.vsassets.io/extensions/ms-python/python/2019.8.29288/1565127378610/Microsoft.VisualStudio.Services.Icons.Default, if you cannot please try configuring your DNS like pointing to 1.1.1.1 as suggested here? https://1.1.1.1/dns/. Otherwise please contact your network administrator.
- If it is not a network issue, please share the logs from the following locations
    - Help -> Toggle Developer Tools -> Console
    - View -> Command Pallette... -> Toggle Shared Process -> Console
    - View -> Open View… -> Log (Shared)
    - View -> Open View… -> Log (Window)

**Comment by Daniyal-Javani** [comment]
same problem:
```
error: "Internal Server Error"
message: "sortOrder parameter must be either 'asc' or 'desc'."
path: "/vscode/gallery/extensionquery"
status: 500
timestamp: "2020-06-14T08:59:25.916+0000"
```
