### ISSUE TITLE
Support exception breakpoints per debug session

### ISSUE THREAD

**Issue by dvirtz** [microsoft/vscode#99676]
- VSCode Version: 1.45.1
- OS Version: MacOS Catalina

Steps to Reproduce:

requires C/C++, CMake and python extensions

1. clone https://github.com/dvirtz/vscode-bug
2. open folder in vscode
3. build project
4. put a breakpoint in `hello.py` line 2
5. launch "Python: File" 
6. see exception checkboxes in breakpoints window
4. launch "python + cpp" debug configuration
5. the exception checkboxes disappear

**Comment by isidorn** [comment]
The issue here is that the C++ extension probably does not support exception breakpoints.
And in debug UI we do not have support for exception breakpoints per session.

Thus you could file an issue to C++ to start supporting exception breakpoints if possible, but the issue on vscode remains: to have exception breakpoints per sessino, thus renaming this and leaving open as a feature request.

**Comment by dvirtz** [comment]
If I try to use a C++ debug extension which does support exception breakpoints (like CodeLLDB) then only that extension checkboxes are visible and I still can't modify python's exception breakpoints.

**Comment by isidorn** [comment]
yeah exactly, so the issue is what I mentioned in my previous comment we need to support exception breakpoints per debug session.
