### ISSUE TITLE
Add hover/drag sash color

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#99709]
Here is an example from slack, when you try to grab a resize bar
![sash](https://user-images.githubusercontent.com/641685/84197673-52c62d80-aa70-11ea-8e39-70e146bdd9c7.gif)

**Comment by joaomoreno** [comment]
@lszomoru What do you think?

**Comment by jrieken** [comment]
I really like this ❤️

**Comment by stephengeorgewest** [comment]
I saw this in the release notes and it took a while to figure out how to enable this, since my theme "Dark+ (default dark)" didn't seem to have in enabled. In case someone else lands here 
with the same question, here's what I added to my `C:\Users\...\AppData\Roaming\Code\User\settings.json`:
````  JSON
"workbench.colorCustomizations": {
    "sash.hoverBorder":"#90917452"
}
````
![image](https://user-images.githubusercontent.com/1442484/101939144-d092ff00-3ba1-11eb-9458-4fe809e8bc5f.png)
