### ISSUE TITLE
editor.wordWrapColumn does not work in TOML files

### ISSUE THREAD

**Issue by JKAnderson409** [microsoft/vscode#99776]
- VSCode Version: 1.45.1
- OS Version: MacOS 10.15.5

Steps to Reproduce:

1. Set "editor.wordWrapColumn" for all files or for only TOML files. The setting "editor.wordWrap" must be "bounded" or "wordWrapColumn".
2. Open a TOML file and enter a line of text whose length exceeds the setting

Does this issue occur when all extensions are disabled?: Yes

The issue seems worse on VSCode Insiders. I cannot get the setting to work at all on the Insiders build, it seems to always behave as "bounded" regardless of all relevant settings.

**Comment by alexdima** [comment]
@JKAnderson409 I cannot reproduce what you describe. 

Can you please try the following:
1. disable all extensions
2. comment out all your user settings except the one `"editor.wordWrap": "wordWrapColumn"`.
3. open a new window (without a folder which might have folder settings)
4. try a TOML file in such a new window.

In the past, I have seen issues like this caused by language specific default settings which can be overriden only by doing something like (but we don't ship something like this for TOML):
```
"[toml]": { "editor.wordWrap": "wordWrapColumn" }
```
