### ISSUE TITLE
Editors: override asks for reentrant openEditor calls?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#99771]
Today when you want to override the opening of an editor, you do so by returning an `IEditorPane` as part of the opening of an editor. This is only possible by calling `openEditor` within, making it possible to end up with endless loops unless you break with some condition.

@mjbvz thoughts on why this approach was taken? I guess for historic reasons? Wouldn't a better solution be to simply return the editor input and options that should be used for opening to prevent the re-entrant call?

//cc @jrieken

**Comment by mjbvz** [comment]
Yes I think it is only for historical reasons.

I took a quick look through the code and it does look like the setting editor uses the `IEditorPane`: https://github.com/microsoft/vscode/blob/cadabab73fef89fe0c4bfe23b5a33cd58e39ea9c/src/vs/workbench/services/preferences/browser/preferencesService.ts#L327

Not sure if this could be updated to return an `IEditorInput` instead

/cc @roblourens @rebornix

**Comment by roblourens** [comment]
Probably. @sandy081 ?

**Comment by jrieken** [comment]
There is actually a super weird twist to this because [`onGroupWillOpenEditor`](https://github.com/microsoft/vscode/blob/aa013aa27b176383ecac48423b164238a65f202a/src/vs/workbench/services/editor/browser/editorService.ts#L503) isn't awaited correctly. That means an open-overwrite-handler will be called twice no matter if if the override flag is set or not. This reproduces with the explorer which always calls openEditor twice

* have a simple open-overwrite-handler which does something and set override: false
* select a file on the explorer -> the handler is called twice
* select a file from quick pick -> the handle is correctly called once

**Comment by sandy081** [comment]
> Not sure if this could be updated to return an IEditorInput instead

Yes, If we can get the code editor from it.

**Comment by bpasero** [comment]
I would like to clean this up for June if possible 💪

**Comment by bpasero** [comment]
I have to pull out, didn't get to it in debt week. It is true that for example the settings editor somehow implemented this in a way that it needs the `openEditor` call and cannot just return an editor input, though that could maybe be changed. 

As for @jrieken comment in https://github.com/microsoft/vscode/issues/99771#issuecomment-642520728 I do not understand the issue fully, however found that every click into the explorer results into 2 open editor calls, reported as https://github.com/microsoft/vscode/issues/100175

I opened https://github.com/microsoft/vscode/pull/100173 to clean up the editor override a little bit.

I feel the remaining debt here is that an editor override is forced to set `override: false` as part of the options to ensure that the override-endless-loop is stopped. So still, changing this to return maybe a pair of editor input and options would be best, but this needs adoption in all places.
