### ISSUE TITLE
Notebook: tab order is funky

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#99782]
I like the up / down keyboard navigation over notebook cells, but when you try to use `tab` to navigate the order is very unexpected.

1. Focus a notebook. I am using my-work.github-issues  my work cell
2. Press `tab` -> Focus is on GitHub issues label
3. Press `tab` -> focus seems lost
4. Press `tab` -> focus is on the start of the document, even though I did not traverse until the end of the docuemnt

Ideally tab should go in visual order. If that is not possible `tab` should move focus out of the notebook. Similarly tree tab is not used to move focus so users use up / down, but pressing tab focuses out of the tree and does not lead to unexpected jumping of focus.

**Comment by roblourens** [comment]
Fixed in this change

- Get rid of output focus sink when cell has no output, to avoid a dead spot when tabbing through cell (step 3 in OP)
- Fix the toolbar losing focus shortly after tabbing onto it, by avoid context key churn
- Fix domFocus when focus is in a different element from the one that is selected (depends on an earlier PR in listCommands.ts)

**Comment by isidorn** [comment]
Much better now. Thanks for fixing this.
