### ISSUE TITLE
CMD+D should be smarter

### ISSUE THREAD

**Issue by normalser** [Microsoft/vscode#9978]
- VSCode Version: 1.4.0-insiders
- OS Version: OSX

Steps to Reproduce:
1. Create file with:

```
test
TEST
Test
aTesTer
test-123
test234
test
```
1. Put cursor at position `1:1` and press `CMD+D` 7 times
2. VS Code selects:

![image](https://cloud.githubusercontent.com/assets/1723815/17270639/4d73bcaa-5635-11e6-8a10-4d18431a5aa6.png)

It should only select next matches using case sensitivity and whole words

Here is Atom result for the same:

![image](https://cloud.githubusercontent.com/assets/1723815/17270646/8d4bb508-5635-11e6-869e-65eace900a42.png)

**Comment by spywhere** [comment]
FYI, Sublime Text utilise the settings from Find panel in order to match these words.

**Comment by alexandrudima** [comment]
@wallverb `cmd+d` respects the find widget settings which can be toggled via keyboard (match whole word, case sensitivty)

**Comment by atombender** [comment]
I recommend that VSCode adopt the behaviour that Atom has, and which I believe Sublime also has: If you don't start with a selection, then whole-word matching is implicit.

For example: If I have the cursor at the beginning of the word "foo", then cmd-D will only match whole-word instances of "foo". If I _select_ "foo", then cmd-D will match any substring.

This is extremely convenient as a shorthand.

FWIW, I personally find the feature where cmd-D respects the Find panel's case/whole-word settings to be quite exhausting. The setting I need is usually different every time I need to use cmd-D. I continually have to hit cmd-alt-c, cmd-alt-w in order to toggle these (and I rely on cmd-D a _lot_). My above suggestion will reduce the necessary keypresses to just one key, which would help greatly.

**Comment by ShimShamSam** [comment]
This behavior is the only thing keeping me from switching to VS Code. It's unfortunate when I decide to rename a variable like **i** and it starts selecting random I's in the middle of other words. It ruins the refactor use-case of multiple cursors.

**Comment by atombender** [comment]
Indeed. Replying to myself to make another important point:

> The setting I need is usually different every time I need to use cmd-D.

...and it's exacerbated by the fact that you don't _know_ what the case/word toggles are set to unless you hit cmd-F. Almost every time I use the cmd-D feature, not only are the toggles wrong, but I have to do a cmd-F just to see what the toggles are set to.

**Comment by ShimShamSam** [comment]
The new version (1.9) semi-addresses the problem by making the toggle states visible when using Ctrl+D, but I don't see why these states are shared with the search functionality at this point. Doing this has probably added more complexity when compared to Sublime's behavior as described by @atombender

**Comment by jameslieu** [comment]
Isn't this already addressed?

You'll need to toggle `Match case` and `Match whole words` option:
![image](https://cloud.githubusercontent.com/assets/4426088/24793333/965300f2-1b79-11e7-9965-0f9620c49ac4.png)

Then it'll work as expected:
![image](https://cloud.githubusercontent.com/assets/4426088/24793316/863b19b6-1b79-11e7-8951-1359f6e87b73.png)

I'm pretty sure that sublime also behaves this way

**Comment by atombender** [comment]
@jameslieu: No, Sublime does not work that way. Read [my explanation](https://github.com/Microsoft/vscode/issues/9978#issuecomment-264760988). Sublime always uses whole-word matching unless you explicitly make a selection before hitting cmd-D. It's a superior workflow and reduces the need for a whole-word toggle for cmd-D.

@alexandrudima: Looks to me like this issue is being ignored. Any way we can move it forward?

**Comment by alexandrudima** [comment]
I believe this is resolved with PR #36682 (for #8869) . When starting with a collapsed selection, Command+D will now search with `wholeWords: true and caseSensitive: true`.
