### ISSUE TITLE
Weird timer UI instead of infintie progress bar?

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#99789]
Execute a long running Notebook query
Notice there is a progress UI which shows seconds.

This does not seem to be aligned with other parts of VS Code where we always just show an infite progress bar.
Also I do not see what does this bring to the user, why would the user want to know that his query just ran for 4.7 seconds.
And it feels a bit frantic to me.

![Screenshot 2020-06-10 at 22 08 03](https://user-images.githubusercontent.com/1926584/84313487-e0844480-ab66-11ea-9e3e-f1bd6a9e9c7f.png)

**Comment by misolori** [comment]
Thanks for the feedback! This was actually intentional for a couple of reasons, the primary being that notebook cells often have an execution order and knowing how long a certain cell takes to execute, or how long it took, allows you to either debug or optimize. Since we already show the execution time, we wanted to re-use the same space for also showing in-progress execution. 

This allows you to know how long a cell is currently running, especially when a cell is "stuck", because just showing the progress bar up top doesn't inform you of how long it is taking (we got this feedback from multiple users in our user study). There are existing extensions for notebooks that add this functionality as well.

Additionally, when you have large code chunks where the top of the cell is out of view, you can execute the cell via keyboard shortcuts and never see the indicator since it's out of view. Likewise, if the bottom of the cell is out of view, you can still execute via the action at the top and never see the timer at the bottom. This allows us to cover both of these cases.

I would say that this is notebook specific and doesn't apply to other areas of VS Code, which is ok in my mind because the entire notebook experience is different altogether. Since this is intentional, I'll close this as `as-designed`. Thanks again for the feedback.

**Comment by isidorn** [comment]
Ok, makes sense and thanks for explaining the reasoning. I do not mind having notebook specific UI, I just did not see value here but that is probably becuase I am not a hard core user of notebooks.
