### ISSUE TITLE
Blue border surrounding problems panel does not show on other panels

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#99890]
![blueborderaroundproblemsonly](https://user-images.githubusercontent.com/1704059/84417853-247e5480-ac0e-11ea-88df-14656f010b52.gif)

A blue border is shown around the problems panel when it has focus but is not shown when other panels have focus. This is a bit distracting.

**Comment by misolori** [comment]
@sandy081 @isidorn this does feel weird, the other panels have different focus treatments (output is read only, terminal and debug console has the cursor). I wonder if we should put focus on the panel title?

**Comment by isidorn** [comment]
I agree it does not look consistent with the other panels, however the focus border is consistent with other views that have trees: explorer, search, debug views.
Since with the work @stevencl and @sandy081 are doing it is more easier to move views around I would not introduce any UI rules that are different between panel and sidebar.

What I would change though:
Click on problems title should focus first problem element (or last focused one) not the whole tree. Explorer does the same. Only when the tree is empty you can focus the whole tree and only then the blue border would be there.

**Comment by sandy081** [comment]
Agreed to focus on first entry instead of tree.
