### ISSUE TITLE
Clicking on an account should show a flyout menu rather than quick pick

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#99901]
Clicking on the accounts button shows the list of identities that are signed in. It seems odd to see this listed as commands to begin with but when clicking on any identity in the list, the quick pick shows up with a list of actions that the user can take. Instead of the quick pick, I expected to see a fly out menu with the two commands.
![IdentityShouldShowFlyoutCommandsNotQuickPick](https://user-images.githubusercontent.com/1704059/84420175-91dfb480-ac11-11ea-8c16-1c76f7b7d4d9.gif)

**Comment by misolori** [comment]
@RMacfarlane any thoughts on adding a flyout for the two commands?

**Comment by RMacfarlane** [comment]
That makes sense, I think it would make those actions much more discoverable

**Comment by bpasero** [comment]
@misolori didn't you have designs where clicking on the accounts icon would show a rich overlay (similar to how feedback widget works) with actions?

**Comment by misolori** [comment]
@bpasero yes, that’s on the backlog https://github.com/microsoft/vscode/issues/97168#issuecomment-628794836. I’m not sure when that’s planned to be added but in our current experience we go from command (menu) to command (quick pick). Once we go with the proposed design I don’t think the fly out menu would be necessary since that UI is a different experience.
