### ISSUE TITLE
Double click on debug viewlet sash should take into account the title width

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#99923]
Typically double clicking on a viewlet sash will cause the viewlet to be resized to fit the contents. However the debug viewlet still clips some of its contents when double clicked:
![image](https://user-images.githubusercontent.com/8586769/84450408-e892c180-ac04-11ea-9789-775bcd88d8b3.png)

Notice the `...` is all but missing entirely, and more could probably be shown for the select configuration dropdown.

**Comment by isidorn** [comment]
I acknolwedge this issue. The problem is that this optimal width computation is computed based on the width of the body, not on the width of the header.
So this is a general issue of the views, however since debug can have the widest header it is seen here.

I am open for a PR which fixes this for the debug viewlet.
Code pointer https://github.com/microsoft/vscode/blob/0c9c4dfbbc097cdfc32d166651697e137d5ee5be/src/vs/workbench/contrib/debug/browser/debugViewlet.ts#L37

The PR should simply add the `getOptimalWidth()` method to the `DebugViewPaneContainer` and that method should take into account the width of the toolbar if it is docked.
