### ISSUE TITLE
Do not eslint-disable-next-line eqeqeq

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#99947]
I noticed quite a few of `eslint-disable-next-line eqeqeq` in your code. I feel this bypasses our programming style and I do not understand why we cannot have a consistent code style everywhere.

![image](https://user-images.githubusercontent.com/900690/84477310-b5e1db00-ac8f-11ea-8615-faaf3914fcf6.png)

What is the reasoning?

**Comment by NotWearingPants** [comment]
Specifically comparing with `==` against `null` is useful, since it is comparing to both `null` and `undefined`, which is usually what you want.

Instead of converting `pageSize == null` to `pageSize === null || pageSize === undefined`, use the `"null": "ignore"` option of the eqeqeq rule.

From [eslint eqeqeq docs](https://eslint.org/docs/rules/eqeqeq):
> This rule optionally takes a second argument, which should be an object with the following supported properties:
> - "null": Customize how this rule treats null literals. Possible values:
>   - always (default) - Always use === or !==.
>   - never - Never use === or !== with null.
>   - ignore - Do not apply this rule to null.

**Comment by bpasero** [comment]
Wether this rule makes sense or not is a different question, but our rules are there for a reason so that our code has a consistent look and feel. We should never disable an eslint rule unless we are maybe in the middle of refactoring something or clearly have it identified with a TODO and debt issue.

**Comment by joaomoreno** [comment]
Given that we have strict null checks, having something which can both be `null | undefined` is an issue in itself and should be fixed upstream. There really is no preference between `null` or `undefined`, but you should stick to using only one of them. If you still have a use case for using both, then you very likely will want to distinguish them in a condition, so you should still use `===` for that.

There really is no use case at all for `==` in our codebase.

**Comment by eamodio** [comment]
Strict null checks are great and all, but it won't protect us from inputs we don't control -- just because the return type says `null` or `undefined` doesn't mean an extension won't return  the opposite. And while I've made this argument before -- as @NotWearingPants notes it is rare that you want to distinguish between `null` & `undefined`.

I also don't see why it is preferable to use `foo === null && foo === undefined` when `foo == null` is exactly the same.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/70020 for a related issue that we never settled on why we have both `undefined` and `null` in our system. In the end this is developer preference that we do not enforce and in some cases this leads to `undefined | null` being returned.

I am typically solving this by doing the following:

```ts
const foo = null; // or undefined
if (foo) {
  ...
} else {

}
```

This has the disadvantage of not matching on `0`, but we typically avoid this by e.g. putting enums to start with `1`. 

There is also `isUndefinedOrNull` helper in our `types.ts` lib.

After understanding that we could change the rule to ONLY allow `==` when used with `null` I am less emotional about this. My initial worry was to allow `==` for all checks.

On the other hand, we survived so long without the need, so I am not sure why we need to change it now.

**Comment by roblourens** [comment]
I agree that sticking to one when possible is best, but also that it can be really hard to do in practice. I prefer `isUndefinedOrNull` since it's more explicit. I feel like I do a double-take and have to count the `=` when I see `== null`. But I would be ok with disabling that rule for `== null`, I think it's idiomatic.

**Comment by Tyriar** [comment]
I think we should stick to `===`. By allowing `== null` to not warn it would be easy for one of those to slip in accidentally, defeating the purpose of the rule. Leaving in the comments is a far better option than that imo. Typically when I use `null | undefined` it is either meaningful, in which case `x === null && x === undefined` isn't much of a hassle, or I convert `null` immediately to `undefined` (eg. from browser APIs).

Another reason I don't like `== null` is because what it does is not obvious, I only learned what it did exactly when the same topic came up several months ago.

**Comment by rebornix** [comment]
IMHO `null | undefined` is not rare, we often use it in events (`undefined` for no change, and `null` for clearing the data). I like this clear separation and it forces you to understand what `null` and `undefined` really means in the context, especially when you are modifying components owned by others. When you see `=== null` or `=== undefined`, you know they have special meanings.

Also, `== null` is the same as `== undefined`, one can argue that they prefer `undefined` and then start using `== undefined` in their components. This will be step back of turning on `strictNullChecks`.

**Comment by eamodio** [comment]
I (obviously) prefer the use of `== null` for cases when it doesn't matter, as it is idiomatic, doesn't confuse falsy values,, and is highly optimized in V8 (while the truthy/falsy check causes V8 to do quite a bit more work). I personally would love to see `isUndefinedOrNull` removed, and replaced with `== null` again as its idiomatic and optimized (and not another function call).

We can argue about whether `null | undefined` is rare or not, but I don't see how this changes anything -- if you care about the difference use `===`, and  if you don't use `==`. Also as I mentioned above, I feel like in some places we have become a bit too reliant of TypeScript types, specifically in the extension host -- as we have strong types, but that doesn't mean they will be honored by the extensions calling them, or returning data. So unless there is an explicit need to tell the difference between `null` and `undefined`, I opt for being defensive.

**Comment by rebornix** [comment]
> if you care about the difference use ===, and if you don't use ==

Then we need more efforts when writing code in components which care about the difference between `null` and `undefined`, as eslint no longer warns you that you might use `==` by mistake. So is reviewing PRs. I guess I'll then end up with writing special eslint rules in places where the difference matters.

**Comment by JacksonKearl** [comment]
I personally read `== null` as `isUndefinedOrNull` without pause... regarding performance, in my testing the function gets called around 8k times at startup (!), but even 100M runs of either is only a few hundred ms. That being said, `== null` is indeed a bit faster (~30%).

**Comment by chrmarti** [comment]
`== null` definitely feels like the quirky parts of JavaScript and I don't think it will help with readability. It's also been a while since I encountered a library that doesn't clearly distinguish between `null` and `undefined`, I guess most projects have moved on from using `==`. My vote: 👎

**Comment by alexdima** [comment]
My personal preference is to keep `===`. IMHO the difficulty for me to always need to look twice as careful when reading `== null` vs `=== null` is not worth it. If there is a real speed difference, then we should open an issue against v8.

**Comment by alexr00** [comment]
I also prefer to keep `===` for the same readability reasons as [above](https://github.com/microsoft/vscode/issues/99947#issuecomment-643938930). I have learned that this repository doesn't use `==`, therefore I am never on the lookout for it.

**Comment by dbaeumer** [comment]
Same is true for me. In LSP where I get values from the outside I usually normalize them on entrance if there is no semantic difference.

**Comment by jrieken** [comment]
Also 👍 for `===`.

Still, on a meta-level we should really stick to the (few) guidelines and rules that we have and not unilaterally decide to change/ignore them. Historically, we have only added/changed rules after a team buy-in and I think we should stick to this.

**Comment by bpasero** [comment]
This happened.
